### ISSUE TITLE
GMT 6.0.0.rc1: color filling bugs in wiggle command

### ISSUE THREAD

**Issue by xumi1993** [GenericMappingTools/gmt#1003]
**Description of the problem**

When I'm using `wiggle` command to fill red and blue colors for positive and negative wiggle, respectively. Commands included in `gmt begin` and `gmt end` are shown as follows:

```
 gmt wiggle $trace -Z0.15 -Gblue+n
 gmt wiggle $trace -Z0.15 -Gred+p
```
But the figure was drawn with blue color for positive and red color for negative.
![](https://user-images.githubusercontent.com/7437523/60161448-3498fa80-982a-11e9-8ae1-22ca535162f3.png)

There was no error message raised during the script running.
This function was right for my old script (GMT 5.4.5).

Look forwarding to your reply.
Thanks

**System information**

* Operating system: MacOS 10.14.5
* Version of GMT: 6.0.0.rc1

**Comment by joa-quim** [comment]
Thanks. Should be fixed once #1004 is merged
