### ISSUE TITLE
Old GMT4 vector syntax is not documented

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1011]
Due to users requests, we still allow the old GMT4 syntax for drawing vectors. And this is a good thing because the 4 & 5 vectors are actually different things. But although we support it (and test them in ``oldvec.sh``), we don't document them at all.

**Comment by PaulWessel** [comment]
Not true.  They are fully documented in the GMT4 documentation.  We are not going to document obsolete syntax from GMT4 in a GMT6 manual.  Yes, we will accept the old syntax but we should not be part of perpetuating it.

**Comment by PaulWessel** [comment]
OK, maybe, well.  I hate those dump stiff Cartesian vectors being used as geographic arrows.  Makes GMT look bad I think.  Maybe I will come around if we rebrand those symbols as something else, like retro vector or something...

**Comment by joa-quim** [comment]
Yes, because they offer the possibility of having a fill & outline for the body vector, which the GMT5 vectors do not.
