### ISSUE TITLE
Grid mesh on top for 2D and under for 3D

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1015]
Paul, we discussed this a while ago and ended up forgetting it. The way the grid mesh is set in not consistent. We plot it on top of symbols for ``psxy`` and under them with ``psxyz``. This is well depicted by looking at the ``headercheck.sh`` test (in both psxy & psxyz test directories). The 3D case looks nicer. 

Changing this behavior is a bit of a break, but as is it's not consistent and the time to do it is (still) really now.

**Comment by PaulWessel** [comment]
I agree, they should be beneath the symbols and we will just declare it a bug so not a break but a fix.
