### ISSUE TITLE
Document the runtime dependency on xdg-open under Linux

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1019]
**Both gmt docs and gmt end show rely on it**

Running gmt modern mode on Linux has an unspecified runtime requirement of finding xdg-open to open documentation or plots.  While under Windows and macOS we use other tools that we know are present, the xdg-open is not guaranteed to exist and may need to be installed.  This needs to be documented.

**Comment by PaulWessel** [comment]
One possibility would be to issue a message that if on Linux and xdg-open does not exist, say something like

> You need to run sudo apt-get xdg-utils to install required software.

**Comment by seisman** [comment]
I believe this issue was closed by #1103
