### ISSUE TITLE
How to plot City Boundary.

### ISSUE THREAD

**Issue by thitookyaw** [GenericMappingTools/gmt#1020]
**Description of the desired feature**
I am trying to add city boundary (specifically for Indonesia) in my map. I could not find any resources or tutorials showing how to do it. 

![mapbat](https://user-images.githubusercontent.com/49779158/60314855-1c96b780-999f-11e9-9530-038d9ee3eab0.jpg)

  I know that GMT provides river/marine/national/state boundaries for US. Any idea on how to add additional city boundaries (probably as an input file)? 
  Thank you.
(I am using standalone GMT 5.4.5 on windows and it is working perfectly. My example code and figure are attached)
  Any help will be much appreciated.

**Are you willing to help implement and maintain this feature?** Yes/No
Yes
![mapbat](https://user-images.githubusercontent.com/49779158/60314795-e48f7480-999e-11e9-80ac-99cb3c557513.jpg)

## gmt pscoast -JM6i -R119.417/120.25/-1.0833/0.13 -Ggray -P -B0.2:."":SWNe -Df -Lg120.167/-1+c30N+w10k+l+f -K -E=AS --FORMAT_GEO_MAP=ddd:mmF --MAP_FRAME_TYPE=inside > mapbat.ps

**Comment by PaulWessel** [comment]
GMT does not offer any data to plot what you need.  You may be able to find such resources elsewhere and plot them via psxy in GMT (e.g., shapefiles).  FYI, your **-B** option uses GMT4 syntax (which we still honor), but better to use GMT 5 syntax: **-B**0.2 **-BSWne**

**Comment by seisman** [comment]
FYI, you can get the city boundary data from https://gadm.org/.
