### ISSUE TITLE
Merging 6.0 into master and keeping history informative

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/gmt#1032]
Right now, we are periodically merging 6.0 into the master branch. This creates all of these "Merge branch 6.0" merge commits on master. These commits don't really do much but register the merge and are polluting the history of the master branch (making it even harder for us to keep track of changes and have a meaningful changelog in the future). 

I've been researching how other projects do this and it's common to use `git cherry-pick` instead. This command lets you get one commit from a branch and apply it to another. For example, if commit XXX just landed on 6.0, we can apply it to master by:

```
git checkout master
git cherry-pick XXX
git push origin master
```

This doesn't create the merge commit, only the new commit from 6.0. An even better way would be:

```
git checkout master
# Create a new branch to port the commit
git checkout -b port-XXX
git cherry-pick XXX
git push -u origin port-XXX
# Then open a pull request from port-XXX to master
```

This way, the CI gets run with the new commit to master before anything is merged.

**Comment by seisman** [comment]
We now do the backports automatically. Closing the issue.
