### ISSUE TITLE
test/filter1d/smooth_track.sh needs update

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1053]
test/filter1d/smooth_track.sh gives compatibility warnings:
```
filter1d [COMPATIBILITY]: -Nc|g[<unit>][+a] option is deprecated; use -T[<min>/<max>/]<int>[<unit>][+a|n] instead.
```

**Comment by PaulWessel** [comment]
I think there are a bunch of these.  So in a sense it is a good test that our compatibility is working.  Updating to new syntax leaves no checks on that part.

**Comment by seisman** [comment]
OK. Closed.
