### ISSUE TITLE
IO_COL_SEPARATOR=/ on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1054]
**Description of the problem**

On mac:
```
$ gmt fitcircle @sat_03.txt -L2 -Fm  --IO_COL_SEPARATOR=/     
330.169184777/-18.4206532702
```

On Windows:
```
$ gmt fitcircle @sat_03.txt -L2 -Fm  --IO_COL_SEPARATOR=/
330.169184777C:/Prog-18.4206532702
```

**Comment by PaulWessel** [comment]
That is truly insane.  Need @joa-quim to debug and see what is going on.

**Comment by joa-quim** [comment]
I've shown you that in the Palace. For some reason when running from bash it needs a double ``/``
```
gmt fitcircle @sat_03.txt -L2 -Fm  --IO_COL_SEPARATOR=//
330.169184777/-18.4206532702
```
It works fine with a single ``/`` if run from ``cmd``

This is an example why I have many false failures in tests from Windows.

**Comment by seisman** [comment]
MinGW automatically convert `/` to a Windows path (http://mingw.org/wiki/Posix_path_conversion).

**Comment by seisman** [comment]
BTW, the description of IO_COL_SEPARATOR needs update.

```
IO_COL_SEPARATOR
This setting determines what character will separate ASCII output data columns written by GMT. 
Choose from tab, space, comma, and none [tab].
```

IO_COL_SEPARATOR can be any strings less than 8 characters.

**Comment by PaulWessel** [comment]
So the strange Win case must mean we are not doing a good job of NULL-terminating that string.  Please check where it is assigned and see if it needs some work.  I don't think we meant this to be anything than a single character (despite the 8 size).  Do we really want to document that you can use BREAK as a valid IO_COL_SEPARATOR? If so, why only 8 and not some larger value.

**Comment by seisman** [comment]
> So the strange Win case must mean we are not doing a good job of NULL-terminating that string. 

I think we can do nothing on our side. When IO_COL_SEPARATOR is set to be `/`, MinGW automatically convert `/` to a Windows path like `C:/Programs Files/xxxx`. So what gmt sees is `--IO_COL_SEPARATOR="C:/Programs Files/xxxx"`

In the following function, we truncate it to no more than 7 characters.

https://github.com/GenericMappingTools/gmt/blob/1aebef14a59d6b2f7452ee65eb06824aa117f99f/src/gmt_init.c#L9255-L9266

> I don't think we meant this to be anything than a single character (despite the 8 size). Do we really want to document that you can use BREAK as a valid IO_COL_SEPARATOR? If so, why only 8 and not some larger value.

I agree, a single character is reasonable. Maybe we can check if IO_COL_SEPARATOR is more than one characters. If yes, we may issue a warning or error and explain that MinGW or similar Windows-bash may do the path conversion automatically?

**Comment by PaulWessel** [comment]
Could we perhaps do a WIN32 specific thing of checking if length > 1 and then reset to / with a warning? I.e.,

```
#ifdef WIN32
        else if (strlen (value) > 1) /* Fix MinGW madness of replacing / with a path... */
                strlcpy (GMT->current.setting.io_col_separator, "/", 8U);
#endif 
```

**Comment by seisman** [comment]
what about checking length > 1 and the second character is `:`?

**Comment by PaulWessel** [comment]
Sure, that ought to be fool proof.

**Comment by PaulWessel** [comment]
Will you be implementing this or shall I?
