### ISSUE TITLE
We need rc2 to be released now

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1058]
Dave Sandwell needs to send out his Homework 2 to the GMTSAR students for the UNAVCO workshop just after our GMT workshop.  It tells students how to install the latest GMT 6.  As soon as that email goes out we need to have our stuff together.  I think this means making rc2 tomorrow, or very soon (we can have Dave wait until we are ready but must act very soon).

Since fixing is ongoing, the rc2 is just another snapshot.  However, the only issue I think requires discussion is my WIP PR on trailing text word selection and if that should get into 6.  Please see #1051 at your earliest convenience, @GenericMappingTools/core.

**Comment by joa-quim** [comment]
Sorry, not groking this. Why do we need an RC2 for that? The instruction can be to install the most recent GMT6 available and warn that currently it's RC1, but can well be an RC2 in some near future ... or the final 6.0.0

**Comment by PaulWessel** [comment]
I think the key issue that we may wish to use

> gmt begin
>    stuff
> gmt end show
> 

in the GMT workshop and that will fail if we tell people to install rc1.

**Comment by joa-quim** [comment]
OK, so the question is should it be an RC2 or the 6.0.0?

**Comment by PaulWessel** [comment]
RC2.  We will do 6.0.0 when our paper is published.

**Comment by PaulWessel** [comment]
WIth "gmt end show" and ehnaced -i -o option that can select a single word from trailing text I think we are good to go, unless @seisman wants to try to track down #1070?  Since it takes us a few days to go through the release steps and there is 4th of July on Thursday, we need to start.

**Comment by PaulWessel** [comment]
The building of the tar balls and the macOS bundle can be scripted.  However, we need to run cmake with specific parameters.  Where can we store these? Is it appropriate to add a ConfigReleaseBuild.cmake file to the cmake directory?  How about the script that does all the work, can that go somewhere within the repo?  I don't like the idea of having these loose pieces in my home directory without any backup, and if someone else is going to build these then they will save time.

**Comment by PaulWessel** [comment]
Any thoughts on this, @leouieda and @seisman ?  I just tested my bash script and it build the tar balls and the Bundle.  It just needed the ConfigReleaseBuild.cmake to be placed in cmake.  Unfortunately, I had to hand-edit cmnake/ConfigDefaults.cmake to set GMT_PACKAGE_VERSION_SUFFIX and GMT_PUBLIC_RELEASE TRUE since setting them in ConfigReleaseBuild.cmake did not work.  Perhaps cmake -D<par=setting> ?

**Comment by seisman** [comment]
How do you let cmake use the settings in ConfigReleaseBuild.cmake?

**Comment by PaulWessel** [comment]
See attached script.  Some issues in certain steps:

- [0] It sets the Version variable but we only need that after step3 so perhaps can run the built gmt --version and extract it automatically here.
- [1] Copying in a file from my home dir.  I think it should live in aa guru directory that is not tarred off or it could go in the cmake.
- [10] This will only work for me, obviously.

[ConfigReleaseBuild.cmake.txt](https://github.com/GenericMappingTools/gmt/files/3348198/ConfigReleaseBuild.cmake.txt)

**Comment by seisman** [comment]
Did you forget uploading your bash script?

**Comment by PaulWessel** [comment]
Oops, I uploaded the cmake stub...Here. Driving home, will get back online in ~1 hour.

[build_release.sh.txt](https://github.com/GenericMappingTools/gmt/files/3348210/build_release.sh.txt)

**Comment by seisman** [comment]
What about creating a directory (e.g. `misc`) in the root directory and put these scripts inside.

**Comment by PaulWessel** [comment]
Yes, but perhaps call it admin instead?  And place the script and the Config file and a README?

**Comment by seisman** [comment]
I'm OK with that.

**Comment by PaulWessel** [comment]
And I assume the CMakeLists.txt stuff for tar_release can exclude that directory when it tars off?

**Comment by seisman** [comment]
Of course

**Comment by leouieda** [comment]
Yep, the script is the best option IMO. Calling gmt to get the version is a good idea as well. If it's necessary, the script can build the cmake config file so we don't have to store it (in case it changes all the time). I like the idea of an `admin` or `maintenance` folder with scripts and a README with instructions for this kind of thing.

**Comment by PaulWessel** [comment]
OK we created admin yesterday and populated it.  Still needs refinement.  I am heading in now through traffic - at UH in ~1 hour I hope.

**Comment by seisman** [comment]
Closed. See #1081 for release checklist.
