### ISSUE TITLE
Latest graphicsmagic crashes when running tests

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1059]
Not sure if this is just me but I typically run the 800+ tests before I commit changes that are nontrivial.  I just made some minor changes to subplot and wanted to make sure all was well, but got tons of failures.  The log has stuff like this:

/opt/local/bin/gm compare: abort due to signal 6 (SIGABRT) "Abort"...

Of course, gm was just updated by macports (I run a cron job nightly to get the latest updates):

GraphicsMagick 1.3.32 2019-06-15 Q8 http://www.GraphicsMagick.org/
-rwxr-xr-x  1 root  admin  24824 Jun 29 15:31 /opt/local/bin/gm

Can any of you reproduce this?

**Comment by PaulWessel** [comment]
Rolling back to 1.3.31 restored sanity.  I will try to report a bug. Jeez, everybody are starting to get really sloppy now (netCDF, ghostscript, now graphicsmagick). What is happening?

**Comment by PaulWessel** [comment]
I have reported the problem on the graphicsmagick issue tracker: https://sourceforge.net/p/graphicsmagick/bugs/610/

**Comment by PaulWessel** [comment]
Fixed in gm repo; new version in not too long.  Leaving this open until 1.3.33 is released.

**Comment by seisman** [comment]
gm 1.3.33 was released on July 20, and both macports and homebrew update to 1.3.33. 
We can close this issue if it works for you.

**Comment by PaulWessel** [comment]
The new release 1.3.33 has fixed the problem so we can close this issue.
