### ISSUE TITLE
Modern mode: specify paper size and not cropping the figure

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#106]
In modern mode, figures are by default cropped to the minimum required by the image contents, using `psconvert -A`. 

Sometimes, we may want to plot a figure on A4 paper for printing. In this case, we need to specify paper size and set `psconvert` to not crop the figure.

This is what I try:
```
gmt begin map png
gmt set PS_MEDIA=A4 PS_CONVERT=""
gmt basemap -R0/10/0/10 -JX10c -Bafg 
gmt end
```
![map](https://user-images.githubusercontent.com/3974108/46311003-f0284900-c58e-11e8-816b-d625f58e303c.png)
However, you'll see that the right part of the figure is missing. It seems that the origins for the plot are somehow in the middle of the paper, different from the behavior in classic mode. Is it desired or a bug?

**Comment by PaulWessel** [comment]
Hm, I print PDF figures all the time.  The printer knows its paper size and off it goes.  I can even scale the figure if I want to or let it be exactly as is.  it tends to center the figure on the paper. Anyway, what you got is probably not what we want but I think you are trying to defeat how GMT is doing things.

**Comment by joa-quim** [comment]
I've not tested the modern mode much on Win and suspect there are issues in it. Just to check, do you also get this error?
```
gmt basemap -R0/10/0/10 -JX10c -Bafg --PS_MEDIA=A4 --PS_CONVERT="" --MAP_ORIGIN_X=2i --MAP_ORIGIN_Y=2i map pdf
gmt [ERROR]: Shared GMT module not found: basemap
```

**Comment by seisman** [comment]
@joa-quim I think the correct one-line command should be:
```
gmt basemap -R0/10/0/10 -JX10c -Bafg --PS_MEDIA=A4 --PS_CONVERT="" --MAP_ORIGIN_X=2i --MAP_ORIGIN_Y=2i -pdf map
```
Please note the dash symbol before `pdf`.

**Comment by PaulWessel** [comment]
Note this gives what you want but PS:

`gmt basemap -R0/10/0/10 -JX10c -Bafg --PS_MEDIA=A4 --PS_CONVERT="" --MAP_ORIGIN_X=2i --MAP_ORIGIN_Y=2i -ps map`

**Comment by joa-quim** [comment]
Right. You can see that have not been practicing modernity. But it respects the X,Y origin. I mean, origin is at 2,2 inch

**Comment by seisman** [comment]
Two solutions I just find.
```
gmt begin map ps
gmt basemap -R0/10/0/10 -JX10c -Bafg 
gmt end
gmt psconvert map.ps -P -Tf
```

```
gmt begin map pdf
gmt set PS_MEDIA=A4 PS_CONVERT="" 
gmt basemap -R0/10/0/10 -JX10c -Bafg -X1i -Y1i 
gmt end
```

**Comment by joa-quim** [comment]
Sorry, don't get what is the problem. These both work as intended
```
gmt basemap -R0/10/0/10 -JX10c -Bafg --PS_MEDIA=A4 --PS_CONVERT="" -X1i -Y1i -pdf map

gmt basemap -R0/10/0/10 -JX10c -Bafg --PS_MEDIA=A4 -X1i -Y1i -ps map
```

**Comment by PaulWessel** [comment]
Try MAP_ORIGIN_X|Y instead...

**Comment by seisman** [comment]
MAP_ORIGIN_X and MAP_ORIGIN_Y don't work because they only works for a new plot. For an overlay, the default offset is always zero.

**Comment by leouieda** [comment]
@seisman any update on this issue?

**Comment by seisman** [comment]
Close this issue, since I've found two solutions.
