### ISSUE TITLE
Custom symbol selection of word for label uses wrong count

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1062]
**Description of the problem**

We recently added the capability of selecting a single word from a record's trailing text to be used in a custom symbol via the psxy **-Sl**_size_**+t**_word_ mechanism.  The syntax that I foolishly selected was this: **$t**:_word_, where **$t** represents trailing text and the optional :_word_ selects a single word from **$t**, using the integer _word_ to pick the item.  There are two flaws with this scheme:

1. There should not be any colon needed, as **$t**3 is easy to parse, and that matches the syntax in **-i** and **-o**.
2. The first word should be 0, not 1 (as implemented) and this breaks compatibility with how all other GMT options count – they all start at 0.

The fix is to declare this a bug and use **$t**[_word_], with _word_ starting at 0 for first word.  I believe the only real user of this feature is @KristofKoch and he can handle this correction.  let me know if there are comments, otherwise I will build a PR.

**Comment by KristofKoch** [comment]
@PaulWessel, no problem - I will adjust my scripts accordingly. Thank you for the heads up!

**Comment by PaulWessel** [comment]
Great, we have merged this PR so just replace **$t**:_n_ with **$t**n-1 after you build the latest.
