### ISSUE TITLE
gmt modern mode on Windows does not catch when modules are run without gmt

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1086]
In modern mode (i.e., all commands after gmt begin), we must start each module call with gmt.  One cannot run just basemap, it must be gmt basemap.  if not, we get the message

gmt [ERROR]: GMT modern mode requires all modules to be accessed via gmt

However, under Windows, @joa-quim reports he can type

gmt being
gmtinfo file

and it does not complain.

**Comment by PaulWessel** [comment]
I suspect this is because there is no links but actual executable gmtinfo, gmtmath, etc?

**Comment by seisman** [comment]
There are many 9 KB-size executables in GMT's bin directory. It seems all these executables are compiled from `src/gmtprogram.c` with different names.


![image](https://user-images.githubusercontent.com/3974108/65918751-6a5cfa80-e3a8-11e9-8faa-f2c594ef62e8.png)

**Comment by PaulWessel** [comment]
@joa-quim, I think you explained once that while Windows 10 (7?) support links, some ancient systems do not, hence you build executables.  Should we stop doing that and do links only?

**Comment by joa-quim** [comment]
No, it's a pain. Only administrator accounts can do symbolic links and even those must be activated to do it by default. An installer that would try to do it would fall into those troubles. If it can be done painlessly, I'd be fine with it but suspect not.

**Comment by seisman** [comment]
The macOS bundle doesn't provide these symbolic links. Maybe we should also do the same thing to the Windows installers.

**Comment by PaulWessel** [comment]
Having these only prevents people from using proper gmt module syntax.  I am sure JL is not using GMT from the installer so he can build his links or executables as he pleases, just as I could do when building from source if I wanted to.  But we should not allow new users to gain bad habits no?

**Comment by PaulWessel** [comment]
It also defeats the whole namespace issue of **not** distributing executables called triangle, surface, etc.

**Comment by joa-quim** [comment]
The name space issue is a UNIX issue, not a Windows one.

**Comment by PaulWessel** [comment]
True, but the allowing users to avoid _gmt module_ syntax is a cross-platform concern.  Those in the know can do it but it should not be what we officially allow.

**Comment by seisman** [comment]
I totally agree that we shouldn't provide these symbolic links or executables.

**Comment by joa-quim** [comment]
That would break lots of windows users scripts. And, if we want to say that we are compatible with GMT4 and 5 then full classical names cannot be forbidden. So, in fact, the OSX bundle should come with the links as well.

**Comment by PaulWessel** [comment]
So the problem is we do not have a solution for Windows that involves automatically inserting gmt, such as we have for Unix (gmt_aliases.csh cor csh, gmt_functions.sh for bash, for instance).  Thus, I agree that we would create problems for Windows users living in the past with GMT 4 scripts.  I am thus willing to let the Windows installer have those executables.  The important things is that our scripts and documentation makes no mention of this obsolete usage.  The macOS bundle could technically have links but since it never has had them we are not going to add them.  For the Linux builds via the tarballs we absolutely cannot enable the scripts.  This users can mess with this by themselves if them must (via gmt_links.sh, for instance).  Thus on UNIX, GMT4 scripts without gmt calls are compatible via the scripts gmt5syntax of by first installing the bash functions or csh aliases.

**Comment by joa-quim** [comment]
Yes, GMT4 scripts but the potentially largest number of affected users come from those that still use the standalone names in GMT5 (I know a few). 

However, I had another idea (not in the shower because that's in the morning, but while driving back home). The installer could probably be made to offer the stand-alones as a separate installing option. And we can have a batch script that creates links. It's just that for running that batch the user has to run it from an _elevated cmd_ or right-click it and select _run as administrator_ and obviously only those with admin privileges can execute it.

**Comment by PaulWessel** [comment]
That sounds promising.  Regardless of outcome, we should change the default behavior of cmake to not build those links.  As long as we distribute them in the Windows installer (either as we do now or via some optional install or a script that creates them), the default building should not do so. I.e., 

`set (GMT_INSTALL_MODULE_LINKS FALSE)
`

should be the default setting.

**Comment by PaulWessel** [comment]
Meanwhile, I will change the default from TRUE to FALSE for GMT_INSTALL_MODULE_LINKS. That means @joa-quim will need to add 

`set (GMT_INSTALL_MODULE_LINKS TRUE)
`

to his current setup.

**Comment by PaulWessel** [comment]
> The name space issue is a UNIX issue, not a Windows one.

Wait a minute.  Can you really open a command window and type "triangulate" and it will distinguish between the GMT triangulate and some other program called triangulate that you have also installed?  How does that work?  I understand the two triangulate.exe are in separate directories under C:\programs, but Windows is not a mind reader, no?

**Comment by joa-quim** [comment]
Because you would not store them in the same directory (contrary to unix habits) the files would not clash, but the one used would be the one that is higher in the path hierarchy.
In the 20 years of Win usage we never heard of a complain about name clashing of a GMT module with someone else program.

**Comment by joa-quim** [comment]
I think this one is old enough to be let go.
