### ISSUE TITLE
Scheduled builds don't work on Azure Pipelines 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1088]
Azure Pipelines no longer supports setting scheduled builds in the Web UI. Instead, we have to define scheduled builds in the YAML file.

I edited the YAML file in #1034, following the Azure Pipeline documentations. However, I don't see any scheduled builds since that PR was merged. I don't see any problem with #1034.

@leouieda Any idea what happened?

**Comment by leouieda** [comment]
I don't see anything obviously wrong. Investigating now

**Comment by leouieda** [comment]
I have no idea why this kind of stuff doesn't work. The code in #1034 doesn't seem to have any problems. It's just that the scheduled build never got picked up by Azure. It might be something on their side.

**Comment by seisman** [comment]
It seems something wrong with Azure. See https://developercommunity.visualstudio.com/content/problem/613157/new-cron-schedule-not-working.html

**Comment by seisman** [comment]
Scheduled builds work now.
