### ISSUE TITLE
psmeca -G transparency

### ISSUE THREAD

**Issue by sabertwirl** [GenericMappingTools/gmt#1091]
I hope I haven't disregarded something here. I want to plot only nodal lines of e.g. 5 moment tensors and no fill for quadrants, but for example ```-Gred@100``` hides previous moment tensors' nodal lines.

```
(
echo 41.0  21.0  10  0.246353  -0.008177  -0.238176  0.218433  -0.328568  -1.057033  0  41.0  21.0
echo 41.0  21.0  10  0.007605  0.063209  -0.070814  0.281461  -0.400748  -1.043118  0  41.0  21.0
echo 41.0  21.0  10  0.152530  -0.007075  -0.145455  0.199577  -0.273671  -1.001348  0  41.0  21.0
echo 41.0  21.0  10  0.285217  0.003404  -0.288621  0.239516  -0.282131  -1.073507  0  41.0  21.0
echo 41.0  21.0  10  0.148979  -0.004716  -0.144264  0.247282  -0.352058  -0.973016  0  41.0  21.0
) | psmeca -R39/45/20/35 -JX30/30 -Sm0.3 -V -Gred@100 -L0.05p,black -M > 02.ps
```
The output:

![02](https://user-images.githubusercontent.com/52400174/60564011-f3fe1d00-9d12-11e9-8a4d-dd8a38d66608.png)

There is only one mechanism, not 5. ```-t``` helps here. For example ```-t50```:

The output:

![03](https://user-images.githubusercontent.com/52400174/60564699-84d5f800-9d15-11e9-936a-fd6245c30618.png)

But now the nodal lines have different transparencies.

* Operating system: Windows 10
* Version of GMT: 6.0.0rc1

**Comment by seisman** [comment]
Please try if `-Gred@100 -Ewhite@100` works for you.

**Comment by sabertwirl** [comment]
Excellent! Thank you so much.

**Comment by seisman** [comment]
I think it makes sense to specify "no-fill" for extensive and compressional quadrants of beach balls. I just reopened this issue and will see if it's technically possible.

**Comment by seisman** [comment]
@sabertwirl Just realize that you can use `-G- -E-` instead. 

`-G-` and `-E-` means no fill for extensive and compressional quadrants, respectively.
