### ISSUE TITLE
Run-time dependency for macOS installer package

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1099]
**Description of the problem**

Mac users who just install the GMT bundle will get everything needed to run the basic GMT tools (executable, all required shared libraries like netcdf, GDAL, etc).  However, GMT also expects several executables to be available in the PATH for things to work at run-time:

- ghostscript (gs): psconvert issues system calls to gs to convert PostScript to other formats.
- gdal_translate: psconvert calls gdal_translate to make Geotiffs.
- ogr2ogr: GMT calls ogr2ogr to convert ESRI shape files to GMT/OGR format.

While the GDAL library is present in the bundle, the run-time executables gdal_translate and ogr2ogr are not.  Likewise, while macOS supplies Preview to view files, including PostScript, there is no gs executable installed (need to verify this).  Our discussions with Artifex about suppling a gs executable in our installers have met with resistance.  So, we could presumably add the two GDAL executables to the bundle (@seisman, is there a CMake setting for adding extra executables to the bundle?) but we still need a solution for installing gs.  It seems perhaps the easiest way is to use homebrew (e.g., http://macappstore.org/ghostscript/).  One possibility would then be this:

If macOS and running the bundle gmt executable and there is no gs, set up a system call to launch and install gs via brew.

**Comment by seisman** [comment]
@joa-quim added the file [add_exes_cpack.txt](https://github.com/GenericMappingTools/gmt/blob/master/cmake/dist/add_exes_cpack.txt) to install gdal and proj executables into the Windows installer. I don't know how and why it works, but we possibly can do that on macOS.

**Comment by PaulWessel** [comment]
Of course, I left out two others:

- gm: Used by movie to create animated GIFs.
- ffmpeg: Used by movie to make MP4 movies.

Where is add_exes_cpack.txt used, @joa-quim, and does cpack track down the shared libraries used by those executables or must we add those libraries explicitly (there is a very long list for ffmpeg and a few for gm, as well as the others above).

**Comment by PaulWessel** [comment]
Finally, it looks like add_exes_cpack.txt does not include the gm and ffmpeg stuff, only goal executables.

**Comment by joa-quim** [comment]
Right, we need better documentation for this

I use that file by setting this in my ``ConfigUser.cmake``
```
		# .../cmake/dist/CMakeList.txt Import a list of files to add to the installer
		set (EXTRA_INCLUDE_EXES "../../cmake/dist/add_exes_cpack.txt")
```
AFAIK, cpack doesn't follow dependencies for those so we need to have a complete list of them. Given the number of dependencies, I don't think we should bother adding ``gm`` to that list. What we should do is to replace animated gifs with APNG (animated PNGs). ffmpeg can do that (though there are questions about it on SO, so maybe not so straightforward, but we have to try).

But there is more. Soon you'll have to start using GDAL3+PROJ6. For that combo (but probably for current GDAL version) a full self-contained package need also the data files. I think my solution works only for GDAL3 because it uses a function added in that version. If you look at ``share/CMakeList.txt`` at line 58, you'll see
```
if (GDAL_DATA_PATH)
	install (DIRECTORY ${GDAL_DATA_PATH}/
		DESTINATION ${GMT_DATADIR}/GDAL_DATA
		COMPONENT GDALDATA)
endif ()
if (PROJ_DATA_PATH)
	install (DIRECTORY ${PROJ_DATA_PATH}/
		DESTINATION ${GMT_DATADIR}/GDAL_DATA
		COMPONENT GDALDATA)
endif ()
```

So in my ``ConfigUser.cmake`` I have
```
	# ------- The GDAL_DATA and PROJ_LIB files location -----------------------------------------
	set (GDAL_DATA_PATH C:/programs/compa_libs/gdal_GIT/compileds/VC14_64/data)
	set (PROJ_DATA_PATH C:/programs/compa_libs/proj5_GIT/compileds/VC14_64/share/proj)
``
This part is documented in ``ConfigUserTemplate.cmake`` but this is not good enough (too buried).

**Comment by PaulWessel** [comment]
Somehow,  cpack determines all the shared libraries needed by gmt though and adds them automatically, e.g., libcurl, etc.  So it must examine the executables and follow that list.  I would have thought it would do the same for any executable added to the pack.

**Comment by joa-quim** [comment]
Yes, but here we are telling it to just copy a a bunch of files (it doesn't know they are executables). But maybe there is a cleverer way of doing this.

**Comment by PaulWessel** [comment]
Is there something similar for shared libs? I know you place your DLLs with the exes but for other OS we want to place the shard libs in the lib folder.  I could get the list of libs via tool -L on macOS.  When I google EXTRA_INCLUDE_EXES I get no hits but our own...

**Comment by joa-quim** [comment]
See ``cmake\dist\CMakeLists.txt`` line 164

```
# If defined, import a list of files to add to the installer
if(EXTRA_INCLUDE_EXES)
	include (${EXTRA_INCLUDE_EXES})
endif()
```
Just define another tag/file for libs

**Comment by PaulWessel** [comment]
From https://www.ghostscript.com/license.html it seems tricky/illegal for us to include gs in the GMT bundle.  Might it be possible to simply make a gs bundle for us to offer to, say, workshop participants to install on short notice?  Since all Linux users can just do a "sudo apt-get install gs" or similar, and Windows users installs from an installer, it is the macOS users without fink, macports, homebrew that are the odd group.

**Comment by joa-quim** [comment]
At least this bit of the license (contrary to most of the rest) is crystal clear.
``If you are redistributing our software in binary form, you must make the source code available. AGPL also requires this.``
So, based on this we can make a Git repo with ghostscrip source code and add binaries to it for Win and Mac. Than we could refer GMT users to those binaries, or even offer to automatically download them if they are not found in users system.

**Comment by joa-quim** [comment]
At least this bit of the license (contrary to most of the rest) is crystal clear.
``If you are redistributing our software in binary form, you must make the source code available. AGPL also requires this.``
So, based on this we can make a Git repo with ghostscrip source code and add binaries to it for Win and Mac. Than we could refer GMT users to those binaries, or even offer to automatically download them if they are not found in users system.

**Comment by PaulWessel** [comment]
I am less convinced than you about the reading their license.  What do the rest of you at @GenericMappingTools/core think?

**Comment by leouieda** [comment]
We wouldn't include gs in our GMT bundle but make a gs bundle of our own so it seems to be in compliance. I would ask them about this to be on the safe side.

**Comment by PaulWessel** [comment]
We need some action on this pretty soon.  To be fully self-contained the macOS GMT installer should have

gs (used by psconvert)
ffmpeg (used by movie)
gm (used by movie)
GDAL executables (we use gdal_translate and ogr2ogr; used by psconvert, gmt i/o)

Looks like we cannot distribute gs.  How about the rest? At the very least we need to have simple instructions for people just using the bundle.

**Comment by seisman** [comment]
For macOS users, it's very convenient to install these dependencies via brew, fink or macports. Do we really need to take on the burden to include them in the bundle?

**Comment by PaulWessel** [comment]
Maybe we need at least a clear Bundle.README or something that explains what they need to do to have all the run-time prerequisites installed.  I.e., given them a list of three commands, one per distro, on what to do.  I am not sure everybody who installs from the bundle is running a Linux distro.

**Comment by seisman** [comment]
I think we can include these instructions in INSTALL.md.

**Comment by seisman** [comment]
Do we want to close this issue?

**Comment by PaulWessel** [comment]
Yes, I think we mention it now so OK.
