### ISSUE TITLE
Animation tests fail on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1105]
**Description of the problem**

All animation tests fail on our Windows CI. 

The error output of anim01 is:
```
150/839 Test #150: anim01/anim_01.sh .......................***Failed   12.96 sec
Set GMT_SESSION_NAME = 7666
gmtconvert [ERROR]: Error for input file: No such file (sin_curve.txt)
gmtconvert [ERROR]: Error for input file: No such file (sin_point.txt)
psconvert [ERROR]: Syntax error option -Mb: Cannot read file ..movie_background.ps
end [ERROR]: Failed to call psconvert
end [ERROR]: process_figures returned error 71
mv: cannot stat 'anim_01.ps': No such file or directory
ERROR: gmtest:145
memtrack errors: 0
exit status: 1
```
Obviously, the main script can't find the files generated by the preflight script.

The actual content of the preflight script is:
```
#!/usr/bin/env bash
# Preflight script
export GMT_SESSION_NAME=$$
source movie_init.sh
gmt math -T0/360/20 T SIND = sin_point.txt
gmt math -T0/360/2 T SIND = sin_curve.txt
gmt begin
#       Set fixed background output ps name
        gmt figure movie_background ps
        gmt set PS_MEDIA 4ix2i
        gmt set DIR_DATA C:\Users\seisman\Desktop\anim01:C:\Users\seisman\Desktop\anim01\anim_01
        gmt basemap -R0/360/-1.2/1.6 -JX3.5i/1.65i -X0.35i -Y0.25i      -BWSne+glightgreen -Bxa90g90f30+u'\232' -Bya0.5f0.1g1 --FONT_ANNOT_PRIMARY=9p
gmt end
```

I believe we are having trouble with parsing DIR_DATA 
```
gmt set DIR_DATA C:\Users\seisman\Desktop\anim01:C:\Users\seisman\Desktop\anim01\anim_01
```

**Comment by joa-quim** [comment]
When I debugged this I found that it couldn't run bash scripts. It has to be called/fed by batch files.

**Comment by PaulWessel** [comment]
Is this being called from a bash client on Windows? Since the script is called *.sh it will select mode = 0 based on the file extension and call bash via a system call:
*sc_call[3] = {"bash ", "csh ", "start /B"}
So why would not that work? Maybe a system call to bash does not work as we expect?

**Comment by joa-quim** [comment]
Don't remember exactly why trying to run a bash (it did picked it) didn't work but it wasn't obvious either (seen from a debug session).

**Comment by seisman** [comment]
I ran the script in Git Bash (I believe it's also MinGW bash). The hidden scripts `movie_init.sh` and `movie_preflight.sh` are also executed by bash. 

The problem is, we change DIR_DATA in `movie_preflight.sh`, but on Windows, the paths in DIR_DATA are not correctly parsed.
```
gmt set DIR_DATA C:\Users\seisman\Desktop\anim01:C:\Users\seisman\Desktop\anim01\anim_01
```

**Comment by PaulWessel** [comment]
So the path separator is selected as : since it is bash scripts but the paths are Windows paths with colons.  This is screwed up.  I guess we are back to the mingw path messing-up.  Damn if we do and damn if we don't?   From inside movie.c we think this is Unix because of the bash scripts, but perhaps we need to do some ifdef WIN32 and check if there are paths like X:\ and if so switch to ; as path separator?

**Comment by PaulWessel** [comment]
Can this now be closed?
