### ISSUE TITLE
issue with test/exmod/ex18.sh

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1109]
**Description of the problem**

Although the test passes, running the script gives an error:

```
$ sh ex18.sh
grdmath [ERROR]: Grid must be geographic; see CDIST for Cartesian data.
```

The annotations in the original PS file are also wrong:
![image](https://user-images.githubusercontent.com/3974108/60741748-a4993600-9f38-11e9-8694-5f65eb4c2389.png)

**Comment by PaulWessel** [comment]
You can add **-fg** to that grdmath statement to be safe.  The orig PS looks fine to me - no squares.

**Comment by seisman** [comment]
Do you see any "degree" symbols? I expect to see figures like:
![image](https://user-images.githubusercontent.com/3974108/60743833-386f0000-9f41-11e9-98ee-194eadc07150.png)

**Comment by joa-quim** [comment]
And I don't see neither squares nor degree symbols in the orig PS

**Comment by PaulWessel** [comment]
Yes, the PS has those for me.  Both gs and Preview shows them.  Looking at the PS I see

> 471 -167 M PSL_font_encode 0 get 0 eq {Standard+_Encoding /Helvetica /Helvetica PSL_reencode PSL_font_encode 0 1 put} if
> 200 F0
> (î148è) tc Z
> 471 4725 M (î148è) bc Z

So I am guessing you dong have the right charset selected somehow? That is usually the case when weird symbols show up.

**Comment by PaulWessel** [comment]
BTW, I see exactly the same PS in ex17 - is that not viewing for you also (and probably all geo maps?)

**Comment by seisman** [comment]
@PaulWessel I'm talking about the modern mode example 18 in test/exmod/ex18.sh, not the classic one in `doc/example/ex18`.

**Comment by seisman** [comment]
This is the screenshot of modern ex18.ps on my computer.
![image](https://user-images.githubusercontent.com/3974108/60744961-42473200-9f46-11e9-935c-6c86e60c0327.png).

The upper panel is wrong and the lower panel is correct.

**Comment by seisman** [comment]
Here is a minimal script to reproduce the issue:
```
gmt begin map
gmt subplot begin 2x1 -A+JTL+o0.2i -Fs6i/3.5i -M0.2i/0.35i -R0/10/0/10 -JM5.5i -Baf -BWSne
gmt basemap -c
gmt basemap -c
gmt subplot end
gmt end
```
However, the figure looks good if `-A` options is removed.

The generated figure is:
![image](https://user-images.githubusercontent.com/3974108/60745393-01e8b380-9f48-11e9-91bb-23dcca0d9803.png)

**Comment by PaulWessel** [comment]
I figured it out.  It was the definition of the _PSL_completion_ macro that is created before the plot is made but not called until after the plot is made.  However, defining the macro tells GMT that a font has been encoded, so it does not do so the next time that font is needed (plotting labels).  But plotting labels is actually the first time it is needed since teh completion is called later.  Reseting the encoded[font] to false fixes the problem.  I will push a PR soon.
