### ISSUE TITLE
Let *contour accept different pens for different contours

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1112]
**Description of the desired feature**

This request is tied to the #322 PR. Implementation of that feature would be very much simplified if grdcontour had a way to accept a list of contours with specific pens.  As it is, it would be much more involved to do so.  Right now, there are four ways to specify contours:

1. A fixed contour interval
2. A comma-separated list of contours
3. A file with contor levels in col 1 and **C**|**A** in col 2 [and optional angle in col 3]
4. A CPT file

The closest thing to what is needed is way 3 if we added an optional col 4 with pens.  This would just be an enhancement to grdcontour and pscontour and would let grd2kml prepare the required input file by simply adding the two missing columns with a **C** in col2 and the unused 0 in col 3.

Any other ideas on how to handle this? It seems like a useful addition to the contour tools and has the side-effect of making implementation of #322 simpler.

**Comment by PaulWessel** [comment]
I will answer this myself: I think this is the best solution since it does not add any new option and it is optional within an existing option.  This is intended for master and not for 6.0.0 release.

**Comment by seisman** [comment]
Closed by #1115.
