### ISSUE TITLE
Add OS-specific GMT_KNOWN_FAILURE flag

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1121]
Some tests are known to pass on one OS but fail on others. It would be good if we can add a OS-specific flag, like:

```
# GMT_KNOWN_FAILURE_ON_WINDOWS
```

**Comment by PaulWessel** [comment]
I think this is a topic for discussion at summit.

**Comment by PaulWessel** [comment]
We should probably start by making a list of the failures on different OS and remind us why they are there and why they differ.  After 6 release.
