### ISSUE TITLE
add SHA256 algorithm for file checksum information

### ISSUE THREAD

**Issue by holishing** [GenericMappingTools/gmt#1123]
Most of release information in official sites and github release pages still uses md5 algorithm for checksums of released files, but maybe there are more reliable algorithms like SHA256, SHA2 ...etc.
I just wondering if it is possible to provide sha256 version checksum in recently release (`5.4.5`) and pre-release (`6.0.0rc2`) information?  Thanks!

**Comment by seisman** [comment]
We just released 6.0.0rc4 and added sha256sum information in the release page. Closed.
