### ISSUE TITLE
PS_PAGE_ORIENTATION=landscape not working for PS format in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1141]
**Full script that generated the error**

```
gmt begin map ps
gmt set PS_MEDIA a4 PS_PAGE_ORIENTATION landscape
gmt basemap -R0/20/0/17 -Jx1c -Baf
gmt end
```

The generated PS file is in portrait mode.

**Comment by PaulWessel** [comment]
The reason is we decided not to listen:

```
case GMTCASE_PS_PAGE_ORIENTATION:
	if (GMT->current.setting.run_mode == GMT_CLASSIC) {	/* Ignore under modern mode */
		if (!strcmp (lower_value, "landscape"))
			GMT->current.setting.ps_orientation = PSL_LANDSCAPE;
		else if (!strcmp (lower_value, "portrait"))
			GMT->current.setting.ps_orientation = PSL_PORTRAIT;
		else
			error = true;
	}
	break;
```

I guess perhaps if people want to make PostScript only and they want to control layout like that, we can decide to revert the above or tell them to use classic mode.  Since we are not resurrecting **-P** for modern mode (Portrait is default) I guess we should allow PS_PAGE_ORIENTATION?

**Comment by PaulWessel** [comment]
Thoughts on this @seisman, @leouieda and @joa-quim ? I guess as long as we are still allowing people to make PostScript plots (the only output format with a specificed page size that is not cropped later), it seems reasonable to allow control of the orientation of that paper.  Agreed?

**Comment by seisman** [comment]
I agree.

**Comment by joa-quim** [comment]
Yes, me too.

**Comment by PaulWessel** [comment]
You guys - PostScript lovers...
OK, I will look into it.

**Comment by leouieda** [comment]
Yep, as long as postscript is an option this makes sense
