### ISSUE TITLE
External calls should not trigger online help for "begin" and others

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1145]
This example shows the point. It's expected to start a modern mode and not to print the online help
```
julia> gmt("begin")
gmt begin [core] 6.0.0_5034cf7_2019.07.10 [64-bit] [MP] - Initiate a new GMT modern mode session

usage: gmt begin [<prefix>] [<format(s)>] [-V[<level>]] [--PAR=<value>]
...
```

**Comment by PaulWessel** [comment]
Not happening on command line.

**Comment by joa-quim** [comment]
That's exactly the point. It shouldn't happen from "external command line" too. I workaround it by stating
``gmt("end -V")`` but would be better not having to use tricks.

**Comment by PaulWessel** [comment]
From looking at begin.c, it will only issue that message if you call it with an argument and that argument is either -? or -+ or -.  I.e., it says

```
if (options) {
	if (options->option == GMT_OPT_USAGE) bailout (usage (API, GMT_USAGE));		/* Return the usage message */
	if (options->option == GMT_OPT_SYNOPSIS) bailout (usage (API, GMT_SYNOPSIS));	/* Return the synopsis */
}
```

The other path to usage is

`if (mode == GMT_MODULE_PURPOSE) return (usage (API, GMT_MODULE_PURPOSE));	/* Return the purpose of program */
`

Hard to see how any of that is happening.  Are you able to step into the calls?

**Comment by joa-quim** [comment]
Shit. It's my doing. When no options I add a ``-?``

https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L195

**Comment by PaulWessel** [comment]
I accept your apology.
