### ISSUE TITLE
Let pstext work without input data.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1155]
This works (writes the word MAP at the middle of figure)
```
echo 0 0 | pstext -R0/40/20/60 -JM12 -Bafg -F+f30+cMC+tMAP -P > lixo.ps
```
but this hangs, waiting to be fed
```
pstext -R0/40/20/60 -JM12 -Bafg -F+f30+cMC+tMAP -P > lixo.ps
```

**Comment by PaulWessel** [comment]
Might be possible if we

1. Detect this situation from **-F** in GMT_Encode_Options and turn off input setup;
2. Detect this situation from **-F** after parse and set no_data = true;
3. Use no_data to avoid reading a record
4. At end of loop, use no_data to exit read loop

**Comment by PaulWessel** [comment]
Instead of 3,4 above, might be simpler with a separate branch:

```
if (no_data) {
    plot label
    Return (GMT_NOERROR);
}
```

**Comment by joa-quim** [comment]
Yep, something like that.
