### ISSUE TITLE
Should there be a rc3 before next week?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1156]
With some of the improvements since rc2 (Window issues fixed, mostly, ffmpeg added), etc., is there a need for rc3 in a hurry?  So for, respondents to the survey are Windows and Mac, with a few Linux.

**Comment by joa-quim** [comment]
Given that the fixes were mostly Win only we could make a ``Win.rc3.win64``.

**Comment by PaulWessel** [comment]
Apart from the various Windows-only path issues, there seems to be these:

- subplot crash #1093
- pslegend paragraph text bug #1097
- pswiggle **-G** old-style failed #1106
- label bug in subplot #1110
- gmt math stack bug #1128
- PS_ORIENTATION effect #1149
- pstext SEGV in **-F+t**_string_ if it had color codes #1161

The pstext issue allows us to avoid echo in setting static labels.  Not sure, may be worth an rc3?

**Comment by PaulWessel** [comment]
Given workshop looming, and the above fixes, should we do rc2 or not? @seisman, @joa-quim, @leouieda ?

**Comment by joa-quim** [comment]
I've said _yes_ already

**Comment by PaulWessel** [comment]
Yes, you did, but limited your answer to Win only. I think the other fixes are beyond Win and hence we need a full rc3.

**Comment by seisman** [comment]
I agree with a full rc3.

**Comment by PaulWessel** [comment]
Adding the gmt docs issue #1171 to the list.

**Comment by leouieda** [comment]
Agreed as well. Should we tell participants to update their install? If so, we'd need instructions.

**Comment by PaulWessel** [comment]
Yes, we should, once the installers are ready.  Probably by tomorrow at the latest.  I just finished building tar balls and mac bundle.
