### ISSUE TITLE
Replace lots of echo "something" | gmt pstext with -F+c+j

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1160]
**Description of the desired feature**

We have close to 300 scripts where we do something like this: 

`example_03.sh: echo "Coherency@+2@+" | gmt pstext -R -J -F+cTR+f18p,Helvetica-Bold -Dj0.1i ...
`

Following #1165, we should replace those with calls like

`gmt pstext -R -J -F+cTR+f18p,Helvetica-Bold+t"Coherency@+2@+" -Dj0.1i ...
`

**Comment by seisman** [comment]
Is it necessary to do the replacements in the test scripts? I think I can write a simple script to do it automatically.

**Comment by PaulWessel** [comment]
Probably not necessary, but would simplify the scripts and avoid setting up
lots of pipes (slightly more involved than a single processor).

Note that not all of the examples are like that.  Many echo in a lon lat
string and that needs to stand.  Some use quotes for the string and others
do not, so your script would need to think about those cases.  E.g., how do
you tell

echo 3 4 string | gmt text

from

echo three four string | gmt text

**Comment by seisman** [comment]
Just check if there is a `-F+c` in `gmt text`.

**Comment by PaulWessel** [comment]
I need more coffee...
Yes, that should be safe.

**Comment by seisman** [comment]
Closed by #1173
