### ISSUE TITLE
pstext bug with -F+t

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1162]
**Description of the problem**

Command:
```
gmt pstext -R0/40/20/60 -JM12 -Bafg -F+f30+cMC+t"-SV0.2i+e -W2p+c -Ct.cpt" -P > lixo.ps
```

Output: the text "-SV0.2i+e -W2p+c -Ct.cpt" isn't plotted.

**Comment by joa-quim** [comment]
It's apparently trying to parse the static text. I get
```
gmt pstext -R0/40/20/60 -JM12 -Bafg -F+f30+cMC+t"-SV0.2i+e -W2p+c -Ct.cpt" -P > lixo.ps
pstext [ERROR]: Error -F: Unrecognized modifier +e
```

**Comment by PaulWessel** [comment]
Since there are no quotes when parsing, all I can suggest is that we state that if +t has a string with other plus arguments then it must be the last item in -F so that we can ignore those other plus modifiers.

**Comment by joa-quim** [comment]
It seems good enough but could it be made to work with single quotes? Double quotes are eaten by the shell but single quotes perhaps not.
```
gmt pstext -R0/40/20/60 -JM12 -Bafg -F+f30+cMC+t'-SV0.2i+e -W2p+c -Ct.cpt' -P > lixo.ps
```
