### ISSUE TITLE
Annotated lines ignore the bezier setting

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1165]
Not sure it's a bug but I was expecting it to curve.
Another surprising behavior is that if the text line is too long (just increase font size bellow to 30) then nothing is printed.

```
echo 0 | gawk '{printf("0 2\n 3.5 1\n 7 3\n 10 2\n")}' | psxy -Sqn1:+f18+l"I have only 4 vertices and should be curved"+v -R-1/11/-1/4 -JX14 -Baf -BWSen -W1,gray+s -P > lixo.ps
```
![lixo](https://user-images.githubusercontent.com/537321/61176374-9e016300-a5b7-11e9-9656-a6d43a6b34a8.png)

**Comment by PaulWessel** [comment]
Not a bug _per se_ but a feature: For quoted lines we are writing out the coordinates, text, etc. to the postscript file and it simply plots that.  For regular lines with Bezier we compute all those help points needed to define the bezier and write that out, and call a different PostScript operator to draw the line.  To do what you expected would mean to resample the line first using a bezier spline (or some spline) before writing out.

**Comment by joa-quim** [comment]
I imagined something along those lines. But the second issue is more of a bug. If line is too long, only the excess should be trimmed not all line. It's again some PS decision?

**Comment by PaulWessel** [comment]
Yes, this is all in PS and now possible to get an error message.  Best we can do is to warn in the docs that if the text length exceeds the line length then no text will appear.  I guess that could go under the **+l** documentation?

**Comment by joa-quim** [comment]
OK, closing this.
