### ISSUE TITLE
Release GMT 6.0.0rc3

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1176]
**Version**:  6.0.0rc3

**Before release**:

- [x] run `src/gmt_make_*.sh` to update some .c and .h files
- [x] check if all tests pass on macOS, Linux and Windows
- [x] update changelog
- [x] update INSTALL.md
- [x] build documentations and fix warnings if any
- [x] check/set values in `cmake/ConfigDefault.cmake`
    - [x] `GMT_VERSION_YEAR` is current year
    - [x] `GMT_PACKAGE_VERSION_*` is correctly set
    - [x] `GMT_LIB_SOVERSION` is correctly set
    - [x] set `GMT_PUBLIC_RELEASE` to `TRUE`
- [x] freeze codes and commit all changes to GitHub

**Release**:

- [x] create source tarballs (tar.gz and tar.xz) (@PaulWessel)
- [x] create macOS bundle (@PaulWessel)
- [x] create Windows installers (win32 and win64) (@joa-quim)
- [x] make a tag and push it to github
    ```
    git tag 6.0.0rc3
    git push --tags
    ```
- [x] go to [GitHub Release](https://github.com/GenericMappingTools/gmt/releases) and make a release. Remember to attach the source tarballs, macOS bundle and Windows installers.
- [x] upload source tarballs, macOS bundle, Windows installers to the GMT FTP (@PaulWessel)
- [x] update README and VERSION files on the GMT FTP
- [x] make announcements

**After release**:

- [x] update `GMT_PACKAGE_VERSION_*` in `cmake/ConfigDefault.cmake`
- [x] comment the `set (GMT_PUBLIC_RELEASE TRUE)` line
- [x] commit changes to GitHub

**3rd-party update**

- [ ] update [conda-forge feedstock](https://github.com/conda-forge/gmt-feedstock) (@leouieda, @seisman)
- [x] update [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmt.rb) (@claudiodsf, @seisman)
- [ ] update [fink package](https://github.com/fink/fink-distributions/blob/master/10.9-libcxx/stable/main/finkinfo/sci/) (@remkos)
- [ ] update [macports ports](https://github.com/macports/macports-ports/tree/master/science)

---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by PaulWessel** [comment]
Hi @seisman, perhaps force the tests to be run so we can check the boxes?  Passes locally on macOS.

**Comment by seisman** [comment]
The tests are running now.

**Comment by PaulWessel** [comment]
Assuming tests pass, I have made tar balls and bundle and placed  in ftp://ftp.soest.hawaii.edu/pwessel/release/gmt6.0.0rc3*:

MD5 (gmt-6.0.0rc3-darwin-x86_64.dmg) = b6ba49aedd4da4e393d05c06c71b2d05
MD5 (gmt-6.0.0rc3-src.tar.gz) = a653ec859fc6d66a0b29a98b32e50059
MD5 (gmt-6.0.0rc3-src.tar.xz) = 9933ef64a3631bc8645fce5ded50d2c3

@joa-quim, please make Win installers.

**Comment by joa-quim** [comment]
I'm afraid we need a new rc
```
..\src\docs.c(74): error C2143: syntax error: missing ';' before 'string'
```

Just submitted a PR fix

**Comment by seisman** [comment]
No need for a new rc. We haven't make any tags to the source codes.

**Comment by PaulWessel** [comment]
Yes, I will just rerun the tar building after that PR is committed.

**Comment by PaulWessel** [comment]
OK, here are the new tarballs and bundle placed in ftp://ftp.soest.hawaii.edu/pwessel/release/gmt6.0.0rc3*:



> MD5 (gmt-6.0.0rc3-darwin-x86_64.dmg) = 1f67be251512c4ea789a678dcc748758
> MD5 (gmt-6.0.0rc3-src.tar.gz) = 1663bcd2423e881f795ec6816ada29c4
> MD5 (gmt-6.0.0rc3-src.tar.xz) = bb4e75dad861f3c053220b76b3ef54f6
>

**Comment by joa-quim** [comment]
OK, went way, fixed the error in my src and built the installers. 
On the Box now.

https://www.dropbox.com/s/xfcgwqrvxu37ip6/gmt-6.0.0rc3-win64.exe?dl=1
https://www.dropbox.com/s/q4r3ywpogtobyzr/gmt-6.0.0rc3-win32.exe?dl=1

**Comment by seisman** [comment]
Tests pass in CI builds.

**Comment by PaulWessel** [comment]
I tested the bundle and it works fine.

**Comment by PaulWessel** [comment]
I tested the Windows installers and all worked.  @leouieda, could you do the Conda package for rc2? Once that is done then we can update the UNAVCO instructions, remove rc2 from the FTP, and email the participants.

**Comment by PaulWessel** [comment]
Hi @seisman, can you do the GitHub release step please?

**Comment by seisman** [comment]
OK. Now working on that. I also can help with the conda package if @leouieda is not available.

**Comment by seisman** [comment]
Done with the GitHub release. 

PR to update the conda package https://github.com/conda-forge/gmt-feedstock/pull/74.

@claudiodsf Please help update the homebrew PR.

**Comment by claudiodsf** [comment]
Homebrew PR updated! :+1:

**Comment by PaulWessel** [comment]
Maybe @seisman and @leouieda can collaborate on getting the conda package updated so we can email the participants to update to rc3?

**Comment by leouieda** [comment]
Working on it. But GDAL is giving us problems again.
