### ISSUE TITLE
Some guys should be allowed to not set -R if first in a modern script

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1181]
```
gmt begin
     gmt coast -EIT -M

pscoast [ERROR]: Syntax error: Must specify -R option
```

So far the workaround is to set a _e.g._ bogus **-Rg** option. Otherwise, we can move that line to before the ``gmt begin`` but then it will have to be ``gmt pscoat ...``, which probably is even more confusing

**Comment by PaulWessel** [comment]
I will look, but probably should stay away from this for the short course since we cannot fix it in time.

**Comment by joa-quim** [comment]
Nope, we have to live with it openly for the moment. I found it when inventing my challenge fig. The “Italian Seismologist”
