### ISSUE TITLE
subplot end should update current projection and region to fit all panels

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1190]
**Description of the problem**

When a subplot is completed and **gmt subplot end** is called, we would like the graphics state to equal that of a single plot covering all subplot panels.  If that were so, then it would be simple to place a common color bar on one of the sides of the composite plot, just like it is for a single plot.  As it is, we go through unnecessary gymnastics like this:

`gmt colorbar -Bxa -By+lm -Dx0/1c+jBC+w12c+h -Xw/2 -Yh
`

Ideally, this would be something like this instead:

`gmt colorbar -Bxa -By+lm -DJBC
`

What is needed is for subplot end to set a fake linear projection and region that encompasses the entire subplot collection, place that in the internal history, and let _gmt_plotend_ write this out as the "current" projection parameters.  This is a bit similar to what **gmt inset end** does to restore the prior projection and region and some ideas can be borrowed from that module.

**Comment by seisman** [comment]
@PaulWessel Is this feature implemented?

**Comment by PaulWessel** [comment]
Yes, today via #1339, so closing this one.
