### ISSUE TITLE
Degree symbol too small

### ISSUE THREAD

**Issue by matt-crs** [GenericMappingTools/gmt#1193]
**Description of the desired feature**
I am trying to figure out how to increase the degree symbol for annotating map boundaries.

I cannot find info to do it in any gmt version besides gmt3.
**GMT3 info**:
>        DEGREE_FORMAT
>               Output format to be used when annotating map boundaries. Choose between 12 formats:
>                       0 Longitudes go from 0 to 360, latitudes from -90 to 90 [Default].
>                       1 Longitudes go from -180 to 180, latitudes from -90 to 90.
>                      2 Longitudes are unsigned 0 to 180, latitudes unsigned 0 to 90.
>                      3 Same as 2, but with letters W, E, S, or N appended as appropriate.
>                      4 Same as 0, with decimal degrees instead of degrees, minutes, and seconds.
>                      5 Same as 1, with decimal degrees instead of degrees, minutes, and seconds.
>                      6 Same as 4, but with letters W, E, S, or N appended as appropriate.
>                      7 Same as 5, but with letters W, E, S, or N appended as appropriate.
>                      8 Same as 0, with degrees and decimal minutes instead of degrees,  minutes, and seconds.
>                      9  Same as 1, with degrees and decimal minutes instead of degrees, minutes, and seconds.
>                      10 Same as 2, with degrees and decimal minutes instead of degrees, minutes, and seconds.
>                      11 Same as 3, with degrees and decimal minutes instead of degrees, minutes, and seconds.
>              Add 100 to these values to use  the  large  degree  symbol  character  (octal  217) [Default is the small degree symbol (octal 312)].

If I was using GMT3 I guess the solution would be any of those 11 options plus 100 to the option values (101,102,...,110,111).

**However, I am using gmt4.**
With GMT4 specifying details to do with PLOT_DEGREE_FORMAT don't appear to have this flexibility to increase degree symbol. But, I may be wrong. If you know how to increase the degree symbol of map boundary annotations please let me know.

Thanks,
Matt

**Comment by PaulWessel** [comment]
From the docs:

> MAP_DEGREE_SYMBOL
> Determines what symbol is used to plot the degree symbol on geographic map annotations. Choose between ring, degree, colon, or none [ring].

It says the ring is default but degree is the larger one.  FYI, both GMT3 and 4 are obsoleted and are not seeing any further updates.  GMT 6 will be released later this summer.

**Comment by PaulWessel** [comment]
I hope you figure it out.  I will close this issue tomorrow - let me know if there are still problems.

**Comment by matt-crs** [comment]
Thanks Paul! 
Oops, I forgot to confirm that it worked (it did!). 
Also, that was my first github post didn't know they had to be closed once solved. 
FYI this information helped 3 other people in my office too.

**Comment by PaulWessel** [comment]
Great, and no worries.
