### ISSUE TITLE
shake map

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#120]
What would be the interest of having a new module(s) to compute [shake maps](https://earthquake.usgs.gov/earthquakes/eventpage/us1000h3p4/map) like those displayed by USGS?
I have it done (ported from my old MEX for GMT4) and makes it a breeze to compute the Vs30 grids as compared to the cumbersome [(original) way](https://github.com/cbworden/earthquake-global_vs30).

The point is that I'm not a seismologist and if people start to ask questions the burden of it would probably had to go to @seisman

**Comment by PaulWessel** [comment]
Right, we do want a seismologist's perspective on this.  And @seisman is our man!  What say you?

**Comment by seisman** [comment]
@joa-quim @PaulWessel I don't got what you're going to do. Can you explain more details?

**Comment by PaulWessel** [comment]
@joa-quim , links please.

**Comment by joa-quim** [comment]
Well, I gave links (two). More, [USGS shake maps](https://earthquake.usgs.gov/data/shakemap/)
I have two modules that:

Compute the [Vs30 ](https://github.com/cbworden/earthquake-global_vs30)(Vs velocities on the upper 30 meters) just from topography 
```
vs30 palu_bat.grd -C1 -Glix_vs.grd
```
use that Vs30 grid and compute the shake map ([intensity](https://github.com/cbworden/earthquake-global_vs30)) of the recent Indonesia earthquake.
```
shake lix_vs.grd -Glixo.grd -Lline.dat -Ci -V -M7.5
```

**Comment by PaulWessel** [comment]
Yes you did give links, sorry.

**Comment by joa-quim** [comment]
I'm afraid this is falling on the oblivion category. @seisman, do you have a opinion on this?

**Comment by seisman** [comment]
Sorry for the late reply. I just came back from a field trip.

I know little about Vs30 and shakemap. The idea of shakemap is interesting. However, USGS has provided a Python module and CLI (https://github.com/usgs/shakemap) to generate near-real-time shakemap. Do we really need to rewrite it with GMT?

**Comment by seisman** [comment]
@joa-quim Feel free to add it into GMT. I'll try my best to answer related questions.

**Comment by PaulWessel** [comment]
As we try to finish up GMT 6 for release, adding modules makes this more complicated, no.  We have to draw the line soon.

**Comment by joa-quim** [comment]
I don't mind to leave this to a 6.1 but by now I would like to have a copy in other place than my local repo only.

**Comment by PaulWessel** [comment]
@leouieda and I discussed this and you could simply create a branch specifically for working on the shakemap but not merge it to master until after 6 is released.

**Comment by joa-quim** [comment]
That's the solution I thought too. I only have to learn how to keep my local branch in sync with master, so that I can build a dll updated with all to use from Mirone.

**Comment by leouieda** [comment]
@joa-quim you can `git merge master` from your branch any time you want to sync.

**Comment by joa-quim** [comment]
Opened issue on USGS interest at vs30 grids generation
https://github.com/usgs/earthquake-global_vs30/issues/45
