### ISSUE TITLE
Improve meca syntax

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1207]
**Description of the problem**

Some of the seis options are very old-style, e.g. the **-S** option in meca has several optional items (font size, offset) given via slash-separated items, and there is a **+u** to change the justification of the text but only above and below is available.  Instead, we should introduce backwards-compatible optional modifiers **+f**_font_, **+o**_offset_ and **+j**_justification_ as is done elsewhere in GMT.

**Comment by seisman** [comment]
Also, -S option should be a required option.

**Comment by seisman** [comment]
There is also an incompatibility about the required columns for input data. For example, -Sa needs 10 columns. 
```
lon lat depth strike dip rake newX newY event_tile
```

In GMT4, the last three columns are optional. Since GMT5, only the last column is optional.

**Comment by seisman** [comment]
-S option was improved in #1298 and 1304, and now it's a required option.

For the incompatibility of required input columns, it seems difficult to have a flexible number of columns with current GMT I/O mechanism. 

Closed it as won't be fixed.
