### ISSUE TITLE
New failing tests on Linux, possibly caused by grdimage openmp 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1233]
**Description of the problem**

We have 4 more failing tests on Linux (6.0 branch). You can view the latest [build log](https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=1697) and download the [build directory tarball](https://dev.azure.com/GenericMappingTools/11594061-301d-45f0-bffe-9e94e7973e8a/_apis/build/builds/1697/artifacts?artifactName=BuildDirectory&api-version=5.2-preview.5&%24format=zip). They may be caused by the openmp grdimage.

One failing PS is attached here [pacific_map_1.ps.zip](https://github.com/GenericMappingTools/gmt/files/3433785/pacific_map_1.ps.zip).

We have openmp enabled on Linux CI, but disabled on macOS CI, so not sure if the tests also fail on macOS.

**Comment by PaulWessel** [comment]
I will diagnose this problem today.  Hopefully just an issue in grdimage and not the speedup from OpenMP in gmt_map.c

**Comment by seisman** [comment]
Fixed by #1239 and #1240.
