### ISSUE TITLE
question on annotation in JE projection

### ISSUE THREAD

**Issue by zhituma** [GenericMappingTools/gmt#1237]
Hi I am trying to add annotation -Ba in JE projection but the annotations are not showing up. I understand that it's hard to write annotation in this projection since the outermost circle essentially covers half of the Earth. But is there a way to at least label the longitude and latitude for the region I chose?  Thanks. 

My code is simply:
gmt psbasemap -Rg -JE-100/40/180/5i -P -Ba30f10g30 -X2 -Y2 -V > test2.ps

**Comment by PaulWessel** [comment]
Unfortunately, not currently possible. I suggest you open a Feature Request issue for this so we can have a look at solutions.
