### ISSUE TITLE
Misses to detect time column in modern mode from externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1246]
In Julia this works fine
```
gmtset(FORMAT_DATE_IN="dd-o-yy", FORMAT_DATE_MAP=:o, FONT_ANNOT_PRIMARY="+10p", FORMAT_TIME_PRIMARY_MAP=:abbreviated, PS_CHAR_ENCODING="ISOLatin1+")
R = "1999-08-11T00:00:00/2007-12-31T00:00:00/0/300"
basemap(region=R, frame=(axes=:WSen, title="RedHat"), figsize=(22,15))
plot!("@RHAT_price.csv", f=:T, lw=:thin, lc=:red)
```
But on modern mode it crashes because the *data* field is never assigned.
```
gmtbegin()
gmtset(FORMAT_DATE_IN="dd-o-yy", FORMAT_DATE_MAP=:o, FONT_ANNOT_PRIMARY="+10p", FORMAT_TIME_PRIMARY_MAP=:abbreviated, PS_CHAR_ENCODING="ISOLatin1+")

R = "1999-08-11T00:00:00/2007-12-31T00:00:00/0/300"
basemap(region=R, frame=(axes=:WSen, title="RedHat"), figsize=(22,15))
plot!("@RHAT_price.csv", f=:T, lw=:thin, lc=:red)
gmtend()
```

**Comment by joa-quim** [comment]
The real issue in this case turns out to be that there is a hidden call to ``gmtread`` and that's it who causes the trouble because it reads all as text. That is, in modern mode this apparently does not care of the ``gmtset`` above returns no numeric values. Only text.
```
D = gmt("read -Td @RHAT_price.csv")
```

**Comment by PaulWessel** [comment]
No, it is the failure to add **-fi**0T so the time column can be adequately processed - otherwise it is just text, as you say.

**Comment by joa-quim** [comment]
Yes, the problem is that.

And BTW, ``solar`` also has problems in modern. Like ``makecpt -H`` yesterday, it also plots to stdout and no assigning to variable takes place

```
julia> gmtbegin()

julia> t = solar(sun=(date="2016-02-09T16:00:00",), formated=true, Vd=1)
        pssolar  -C -I+d2016-02-09T16:00:00
-179.064877883  -22.9753108089  182.20446533    -67.0066970773  0.250084287778  0.755110835093  0.502597561435  727.238228134  -67.0042486535  -3.74048846694

julia> t

julia> typeof(t)
Nothing
```

**Comment by PaulWessel** [comment]
Works in Matlab:

a = gmt ('pssolar', '-C -I+d2016-02-09T16:00:00')        

a = 

  struct with fields:

       data: [1x10 double] ...

Both command line and mex gives

-56.4476786349	-14.7067083083	252.518382605	32.316162216	0.257475289379	0.762259829316	0.509867559347	726.889737509	32.3415988931	-14.2092854602

**Comment by joa-quim** [comment]
And are you running modern mode here? How? It shouldn't allow the use of the ``pssolar`` name.
It works for me though if I set a ``gmt begin`` first from shell. And accepts the ``pssolar`` but on Windows that it's possible, not on unix.

**Comment by PaulWessel** [comment]
Sorry, that was classic.  Modern works not so good:

>> gmt ('begin', 'stuff') 
>> a = gmt ('solar', '-C -I+d2016-02-09T16:00:00')       
Matlab [ERROR]: Shared GMT module not found: solar 

=

**Comment by PaulWessel** [comment]
but using pssolar works in modern mode.

**Comment by joa-quim** [comment]
But it should not be possible to use ``pssolar`` in modern, right? So who knows what it's doing.

**Comment by PaulWessel** [comment]
Classic names are allowed in modern mode but will give a compatibility warning.  The only thing that is required in modern mode is to start with gmt.

**Comment by PaulWessel** [comment]
The keys for pssolar are

`">X},>DI,>DM@ID),MD)"
`

which for modern mode is the stuff after the @ sign, or

`"ID),MD)"
`

meaning it requires **-I** or **-M** to enable output.  So as long as **-I** or **-M** are used there will be output, no?

**Comment by joa-quim** [comment]
Thtat's the problem. When I call GMT_encode_options from Julia it doesn't return ``n_items = 1`` and there is no output assigned. Just printed to screen.

**Comment by PaulWessel** [comment]
So something must be done differently on your end since the mex correctly determines there needs to be one output (since left hand sign has an output) and it works.

**Comment by joa-quim** [comment]
Well mex works on first time ... but after displays the same issue

```
>> gmt('begin','stuff')

>> a = gmt ('pssolar', '-C -I+d2016-02-09T16:00:00')

a = 

  struct with fields:

       data: [-56.448 -14.707 252.52 32.316 0.25748 0.76226 0.50987 726.89 32.342 -14.209]
       text: []
     header: []
    comment: []
      proj4: []
        wkt: []

>> a = gmt ('pssolar', '-C -I+d2016-02-09T16:00:00')
One or more output arguments not assigned during call to "gmtmex".

Error in gmt (line 33)
		[varargout{1:nargout}] = gmtmex (cmd, varargin{:});
 

```

**Comment by PaulWessel** [comment]
OK, To be continued....

**Comment by joa-quim** [comment]
Not working the example but no longer crashes. Closing till it/if resurfaces
