### ISSUE TITLE
Unfortunate trailing + in -J option

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1248]
Per the **-J** documentation,

> Append **h**, **+**, or **-** to the given width if you instead want to set map height, the maximum dimension, or the minimum dimension, respectively [Default is **w** for width].

There are a few problems with this:

1. We now extensively use +_modifier_ to modify the behavior of option settings.  This particular case is in fact a similar thing: we are modifying behavior, but there is no modifier, just a trailing + sign.  Once we introduce the long-option syntax then the auto-parsing I have written will be tripped up because the modifier is in fact missing.
2. There is no parsing for a trailing **w**.
3. This ought to be fixed before 6.0.0 is released, and we are using this syntax in one of our examples in the G-cubed paper.

Apart from dealing with backwards compatibility, my proposal would be to use the modifier **+d** for dimension:

**+d**h for map height
**+d**w for map width [default]
**+d**u for the upper (maximum) dimension
**+d**L for the lower (minimum) dimension

Any better ideas, or any problems you foresee with this scheme?

**Comment by PaulWessel** [comment]
Any thoughts on this, @seisman, @leouieda, @joa-quim ?

**Comment by joa-quim** [comment]
Discuss it over dinner?

**Comment by PaulWessel** [comment]
Good idea, dinner is required anyway.

**Comment by PaulWessel** [comment]
Fixed in #1250
