### ISSUE TITLE
Numbering order in subplot row, col differs from rest of GMT

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1253]
**Description of the problem**

In most place, GMT expects you go give a column number that starts at 0.  However, we are not following this scheme in subplot.  There, the _row,col_ setting (or the common GMT option **-c**_row,col_) starts at 1.  This may match what other softwares do (e.g., MATLAB subplot) but it is not how GMT works elsewhere.  Thus, we should decide on this pronto if we are to correct it before the 6.0.0 release.

**Comment by PaulWessel** [comment]
Following discussion by the whole GMT team, we will implement a zero-based row,col scheme prior to 6.0.0 release.

**Comment by seisman** [comment]
Implemented in #1315.
