### ISSUE TITLE
grdfilter [ERROR]

### ISSUE THREAD

**Issue by annisa3** [GenericMappingTools/gmt#1258]
I found bellow issue everytime i run preproc_tops_batch.csh script from GMTSAR software 

grdfilter [ERROR]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdfilter [ERROR]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtlib_read_grd_info): Use grdedit -A on your grid file to make region and increments compatible [dem.grd]

How to solve this problem? I've tried using `grdedit dem.grd -A` command but it wouldn't change a thing.

I'm using GMT Version 6.0.0_r20495 in Ubuntu 19.04 OS

**Comment by seisman** [comment]
@annisa3 We have released GMT 6.0.0rc3 recently, which includes more improvements and bug-fixes. You may try to build 6.0.0rc3 following the [building instructions](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md) and see if it works for you.

**Comment by annisa3** [comment]
> @annisa3 We have released GMT 6.0.0rc3 recently, which includes more improvements and bug-fixes. You may try to build 6.0.0rc3 following the [building instructions](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md) and see if it works for you.

I've installed it but still got the same issue

**Comment by seisman** [comment]
@annisa3 Can you run `gmt grdinfo dem.grd` and post the output?

**Comment by annisa3** [comment]
> @annisa3 Can you run `gmt grdinfo dem.grd` and post the output?

grdinfo [ERROR]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdinfo [ERROR]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdinfo (gmtlib_read_grd_info): Use grdedit -A on your grid file to make region and increments compatible [dem.grd]
dem.grd: Title: Produced by grdmath
dem.grd: Command: grdmath dem_ortho.grd egm96.grd ADD = dem.grd
dem.grd: Remark: 
dem.grd: Gridline node registration used [Geographic grid]
dem.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
dem.grd: x_min: 108.841286 x_max: 111.499117 x_inc: 0.000277783340301 (1 sec) name: longitude n_columns: 9569
dem.grd: y_min: -8.46521 y_max: -6.40618 y_inc: 0.000277759341697 (1 sec) name: latitude n_rows: 7414
dem.grd: z_min: -23.8958644867 z_max: 3442.58862305 name: z
dem.grd: scale_factor: 1 add_offset: 0
dem.grd: format: netCDF-4 chunk_size: 130,131 shuffle: on deflation_level: 3

**Comment by PaulWessel** [comment]
Was the dem.grd the file produced by interacting with the gmtsar data website?  I know it is too big to post here but maybe you can place it somewhere on an ftp for us to get to?

**Comment by annisa3** [comment]
> Was the dem.grd the file produced by interacting with the gmtsar data website? I know it is too big to post here but maybe you can place it somewhere on an ftp for us to get to?

Yes, I downloaded it from http://topex.ucsd.edu/gmtsar/demgen/. I put it in my gdrive, here is the link https://drive.google.com/file/d/12GTVP1vMAj4PNRoAjZ8esoKXrYx4XF4f/view?usp=sharing

**Comment by justrayyan** [comment]
What is the solution for this problem?
I have similar error.
I used GMT 6.0.0 in ubuntu 18.04

**Comment by PaulWessel** [comment]
I dont know.  These grid have very odd regions that do not seem to be clean multiples of 1 arc second.  Howev are they created?  For instance, west =  108.841286 = 108:50:28.6296 and east =  111.499117 = 111:29:56.8212.  So not even an increment of 1 arc second.  The problem lies in the source.
