### ISSUE TITLE
-JZ in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1265]
Following script should plot a point on a 3D map, but it actually not.
```
gmt begin map3D png
gmt coast -R70/135/15/55/0/5 -JM15c -JZ5c -Glightgray -Slightblue1 -p200/40 -Baf -Bz
echo 120 30 3 | gmt plot3d -Sc0.5c -Gred -p -V
gmt end show
```

Running this script gives a warning message:
```
psxyz [WARNING]: -R with six parameters but no -Jz|Z given - ignore zmin/zmax
psxyz [WARNING]: Central meridian not given, default to 102.5
```

I have to add `-JZ` to the `plot3d` command to make it work.

**Comment by PaulWessel** [comment]
In modern modem, perhaps we should do this:

If **-p** is given and **-R** has 6 items and **-JZ** is missing, fish the latest from gmt.history and add to the options automatically.

Can you see any downsides to this?  I would implement this in gmt_module_init before we do GMT_Parse and parse **-J**.

**Comment by PaulWessel** [comment]
Looking at this now.  One issue is that unlike the horizontal projection **-J** history, the vertical stores **JZ** and **Jz** as separate entries. Thus, we cannot really know if we are to fish **-Jz** or **-JZ** from the history.  I think the only solution to this would be to maintain a **Z** history item, just like the **J** history item, and it would in this case either say **Zx** or **ZX** as the most recent vertical projection.  We can then pick that letter and look for the actual **-Jz** or **-JZ** in the history.   The **-p** is required to tell us we are doing 3D.  Yet, one can use **-p** without **-Jz|Z** so we must also consult the **-R** to ensure zmin/zmax was given before we add a **-Jz|Z** to the history.

Does this seem like a robust plan?

**Comment by seisman** [comment]
The script below doesn't work as expected.
```
gmt begin map3D png
gmt set MAP_FRAME_TYPE plain
gmt coast -R70/135/15/55/0/5 -JM15c -JZ-5c -Glightgray -Slightblue1 -p200/40/0 -Baf -Bz
echo 120 30 0 | gmt plot3d -Sc0.5c -Gred -p
gmt end show
```
I still have to add **-JZ** manually to the plot3d command.
