### ISSUE TITLE
gmt logo -DJBL+w2c doesn't works

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1273]
**Full script that generated the error**

```
gmt begin logo
gmt basemap -JX10c/10c -R0/10/0/10 -Baf
for i in TL TC TR ML MC MR BL BC BR; do
    gmt logo -DJ$i+w2c
done
gmt end show
```

**Full error message**

```
gmtlogo [ERROR]: Internal Error = GMT_MAP_NO_REGION
gmtlogo [ERROR]: Internal Error = i
gmtlogo (gmtlogo.c:372(GMT_gmtlogo)): No map region selected
```

Output:
![image](https://user-images.githubusercontent.com/3974108/62329180-fcf52200-b469-11e9-8eb0-076f90bc5d6c.png)

**Comment by seisman** [comment]
A related issue:
```
gmt logo -Rg -JH20c -DjTR -pdf logo
gmtlogo [ERROR]: Internal Error = GMT_MAP_NO_REGION
gmtlogo [ERROR]: Internal Error = i
gmtlogo (GMT_gmtlogo): No map region selected
psconvert [ERROR]: Unable to decode BoundingBox file /Users/seisman/.gmt/sessions/gmt6.22093/psconvert_40421c.bb (maybe no non-white features were plotted?)
```

**Comment by PaulWessel** [comment]
This may go away depending on how we fix #2451.

**Comment by seisman** [comment]
I still have the bug after #2451.

**Comment by PaulWessel** [comment]
Yep, debugging as we speak (type).

**Comment by PaulWessel** [comment]
Well, no logo width given via **+w.**  Perhaps we should have a default but I don't think it says there is one.

**Comment by seisman** [comment]
We have a default. `gmt logo -pdf map` works.

**Comment by PaulWessel** [comment]
We have this:
-Dx0/0+w2i
so I guess I can add a test if width == 0 set to 2 inches.

**Comment by seisman** [comment]
Closed again by #2456.

**Comment by seisman** [comment]
Reopen the issue again. The command below gives nothing. It should generate a 5cm wide GMT logo. At least it should complain that *refpoint* isn't given.
```
gmt logo -D+w5c -PNG map
```

**Comment by PaulWessel** [comment]
OK, will fix.  There should be a default of x0/0 when no reference is given.
