### ISSUE TITLE
A few compiler warnings to get rid of

### ISSUE THREAD

**Issue by remkos** [GenericMappingTools/gmt#128]
<pre>
gmt/trunk/src/gmt_init.c: In function 'gmt_auto_offsets_for_colorbar':
gmt/trunk/src/gmt_init.c:15170:8: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
  fgets (file, PATH_MAX, fp); fclose (fp); /* Recycle file to hold the -B arguments */
        ^
</pre>
<pre>
In file included from /usr/include/string.h:640:0,
                 from gmt/trunk/src/gmt_dev.h:108,
                 from gmt/trunk/src/movie.c:35:
In function 'strncat',
    inlined from 'GMT_movie' at gmt/trunk/src/movie.c:1375:12:
/usr/include/x86_64-linux-gnu/bits/string3.h:150:3: warning: call to __builtin___strncat_chk might overflow destination buffer [enabled by default]
   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
   ^
</pre>
<pre>
gmt/trunk/src/psconvert.c: In function 'pipe_HR_BB':
gmt/trunk/src/psconvert.c:1034:9: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
   write (H->fd[1], PS->data, PS->n_bytes);
         ^
gmt/trunk/src/psconvert.c: In function 'pipe_ghost':
gmt/trunk/src/psconvert.c:1227:10: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
    write (H->fd[1], PS->data, PS->n_bytes);
          ^
</pre>

**Comment by remkos** [comment]
Addressed by pull request #129

**Comment by PaulWessel** [comment]
Closing this issue since addressed by PR.
