### ISSUE TITLE
-X|-Y not allowed in subplot mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1282]
Script to reproduce the issue:
```
gmt begin map pdf
gmt subplot begin 1x2 -Fs5c/5c
    gmt subplot set 1,1
    gmt basemap -R0/10/0/10 -Baf 
    gmt subplot set 1,2
    gmt basemap -R0/10/0/10 -Baf -X1c
gmt subplot end
gmt end show
```

**Comment by PaulWessel** [comment]
I think you must use **-Cw**1c for that type of thing - we do not allow **-X -Y** in subplot panels.

**Comment by seisman** [comment]
It should be documented that -X -Y are not allowed in subplot mode, or give better error messages.

**Comment by seisman** [comment]
Close it or keep it open as a feature request?

**Comment by PaulWessel** [comment]
Keep it open until we can add some checks.  My first attempt did not work so need more time.

**Comment by joa-quim** [comment]
Close it or keep it open as a feature request?

**Comment by PaulWessel** [comment]
I am guessing this is extremely low on my to-do list now so unless someone wants to dig into the C on this I think the best we can do is add some warnings/errors which might not be that hard to figure out.
