### ISSUE TITLE
grdimage [WARNING]

### ISSUE THREAD

**Issue by annisa3** [GenericMappingTools/gmt#1289]
I run intf_tops.csh script to process Sentinel 1 time series and I got grdimage [WARNING] like  the following script:

clean up topo/ folder

 
DEM2TOPOPHASE.CSH - START
USER SHOULD PROVIDE DEM FILE
 range decimation is:  2
grdimage [WARNING]: Basic z(x,y) with optional illumination and no colormasking.
DEM2TOPOPHASE.CSH - END
NO TOPOPHASE SHIFT 

START FORM A STACK OF INTERFEROGRAMS

I attached the batch_tops.config file that I use to run this script here
[batch_tops.zip](https://github.com/GenericMappingTools/gmt/files/3462013/batch_tops.zip)

Is there anything wrong with the batch_tops.config or anything?

**Comment by PaulWessel** [comment]
Thanks, that statement should not be a warning but is just for information.  I have submitted a PR to change this (#1290).

**Comment by PaulWessel** [comment]
PR has been merged so I am closing this issue.
