### ISSUE TITLE
Let hidden CPT follow a hierarchy

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1294]
**Description of the desired feature**

GMT modern mode supports hidden, current CPTs.  Because we may have any number of figures in a modern mode session, and any figure may have subplots with many panels, and figures or panels may have insets, we need to separate CPTs created for different purposes.  We distinguish between five CPTs: session CPT, figure CPT, subplot CPT, panel CPT, and inset CPT.

The session CPT [Level 0]  is a CPT created by _makecpt_, _grd2cpt_, or indirectly by _grdimage_ at the top level (0) in a session (i.e., not after a figure call).  This CPT is available to all modules needing a CPT, but can be overridden by any of the others.  It is called gmt.cpt.

The figure CPT [Level 1] is similar to the session CPT but it is created after a _gmt figure_ call has happened.  The scope of a figure CPT is limited to that figure.  If you switch to a new figure then that CPT is no longer accessible (but the session CPT is - if it exists).  These files are called gmt.#.cpt, where we insert the figure number.

The subplot CPT [Level 2] can be created immediately after _gmt subplot begin_ has been issued.  If so then that CPT can be accessed from all modules regardless of which panel they are plotting into.  The subplot CPT is deleted once _gmt subplot end_ is called.  This file is called gmt.#.subplot.cpt.

The panel CPT [Level 3] is created inside a subplot panel (i.e., after positioning to plotting to a particular panel via _gmt subplot set_ or **-c**), will only be available to that panel.  All panel CPTs and the subplot CPT are deleted once _gmt subplot end_ is called. Panel CPTs are called gmt.#.panel.#.cpt, with the second number referring to the panel ID.

The inset CPT [Level X] is a CPT created between _gmt inset begin_ and _gmt inset end_, and its scope is limited to that inset.  Once the inset ends the inset CPT is removed.  It is marked as level X since it may be an inset of a figure (perhaps the session figure) or a subplot panel.  This file is called gmt.inset.cpt since only one can exist at any given time,

Which hidden CPT is accessed by a module when a CPT is implied (e.g., _grdimage_ without **-C** or _plot_ **-C**)?  We work up the hierarchy given the above.   If a gmt module called from a level _L_ above, we first look for a current CPT at that level.  If none, then we look for one at level _L-1_, _L-2_, etc until we run out of levels.  If no CPT is found this way then we either create one (e.,g., _grdimage_ will make one from default CPT and grid range) or we have a user error.

This implementation will not allow for subplots within subplots.  It is possible we will extend this mechanism later to allow such nesting.

It is the intent to implement this plan before GMT 6.0.0 is released.  I ask @GenericMappingTools/core to comment on the plan.

**Comment by seisman** [comment]
It sounds reasonable to me. We definitely need to document it in the cookbook.

**Comment by seisman** [comment]
Close this issue?

**Comment by PaulWessel** [comment]
Yes.
