### ISSUE TITLE
Modern mode scripts susceptible to getting wrong PPID

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1299]
**Description of the problem**

Because UNIX shells are not uniformly implemented and do odd stuff (#1297) it would be nice to have a foolproof way to avoid the troubles that can happen if the shell invokes a sub-shell without the user needing to add

`export GMT_SESSION_NAME=$$
`

to the start of their scripts (this is foolproof).  A very simple fix that takes care of most situations is simply to insert

`export GMT_SESSION_NAME=$$
`

into your .bashrc script and then each terminal window you launch will have its unique variable.  However, if you use a single window to run two or more gmt modern mode scripts in the background at the same time, e.g.,

```
long_job_1.sh &
long_job_2.sh &
```

then both scripts will have the same $GMT_SESSION_NAME and chaos ensues.  If this is how you operate then placing the GMT_SESSION_NAME assignment into your scripts is the best solution.

Since a child process cannot affect the environment of the parent (unlike in real life!) I don't think there is a clever way to do something via .bashrc, and don't get me started on csh or tcsh which some users use.

**Comment by PaulWessel** [comment]
Should we distribute gmt script templates that set up an empty gmt modern mode session? E.g., the bash version might be

```
#/usr/bin/env bash
# GMT standard bash template
# Date:
# Purpose:
export GMT_SESSION_NAME=$$    # Set a unique session name
gmt begin
    <modern session commands here>
gmt end show
```

We could even have `gmt --new-script` write this to stdout in the same shell format the users is using.

**Comment by joa-quim** [comment]
Like this idea.

**Comment by PaulWessel** [comment]
Since we document this in begin and also added the --new-script option I think there is nothing more we need to do? Can we close this?

**Comment by seisman** [comment]
Agreed.
