### ISSUE TITLE
How to create a vertical scale at the right side of grdimage/psbasemap using psscale?

### ISSUE THREAD

**Issue by abhi99328** [GenericMappingTools/gmt#1310]
I am willing to make a colored contour plot along with a vertical scale (which defines the value of the colors) at the right side of the plot. But unable to do it. Another issue is the psbasemap and grdimage are making two boxes at the top and bottom, not at the same position.

**The command I used given below:**
system("psbasemap -JX8/8 -R40/60/1.60/1.90 -X8 -Y2 -Ba5f1:\"H (km)\":/a0.1f0.02:k:WSne -K");
     system("grdimage -JX3i/3i $Reg -Ba5f1:\"H (km)\":/a0.1f0.02:k:WSne $tgrd -C$cpt -P -K -O -Y4i");
     system("psscale -Dx3i+jLM/2i+w7.5c/1.25c+e -O -C$cpt $tgrd -I -Bx5+lBATHYMETRY -By+lm");

**The error showing is:**
psscale: Syntax error -D option: scale length must be nonzero
psscale: Syntax error -D option: scale width must be positive
psscale: Syntax error: No input files are allowed

[plot.pdf](https://github.com/GenericMappingTools/gmt/files/3470473/plot.pdf)

**Comment by PaulWessel** [comment]
Looks like you are mixing GMT 4 and 5 from looking at the difference in your **-B** syntax and the **-D** option in psscale (which is why it complains about your syntax). Also, you are passing a grid to psscale but that module does not accept any input files (which is what the message says).  It would help us to help you if you would note what GMT version you are using.  I am also not sure why you switch projection dimensions between plotting the baseman and the image since I cannot tell what $Reg stands for.

**Comment by abhi99328** [comment]
I am using GMT 5.3.1 version. The grid was a mistake. I removed it now. I didn't get you what switching projection you talking are about? Is it "-X8 -Y2" in basemap? I am using it because the two boxes are partially overlapping each other without that. To separate the boxes totally I have to use it. Can you suggest anything to superimpose the boxes on each other fully? How can I create a scale at the right of the figure?

**Now I am using**
system("psbasemap -JX8/8 -R40/60/1.60/1.90 -X8 -Y2 -Ba5f1:\"H (km)\":/a0.1f0.02:k:WSne -K");
system("grdimage -JX3i/3i -R40/60/1.60/1.90 -Ba5f1:\"H (km)\":/a0.1f0.02:k:WSne $tgrd -C$cpt -P -K -O -Y4i");
system("psscale --Dx3i+jLM/2i+w7.5c/1.25c+e -O -C$cpt -I -Bx5+lBATHYMETRY -By+lm");

**The output is same as the previous attached file.**

**The current error showing is**
psscale: Syntax error -D option: scale length must be nonzero
psscale: Syntax error -D option: scale width must be positive

**It is not making any sacle.**

**Comment by PaulWessel** [comment]
I don't have any old GMT version like 5.3.1 so cannot be sure, but I think back then the -D in psscale looked like this: -D<xpos/ypos/length/width>[h].
Sorry, I thought you were trying to coregister the baseman and grid but I see you are doing something else.

**Comment by abhi99328** [comment]
I have tried this -D<xpos/ypos/length/width>[h] but it isn't making any differences.

**Comment by PaulWessel** [comment]
That is hard to believe, could you show the exact command you used for this case?

**Comment by abhi99328** [comment]
**used command**
system("psscale -Dx5c/5c+w3i/1.25i -O -C$cpt -I -Bx5+lBATHYMETRY -By+lm -V");

**Error showing**
psscale: Processing input CPT
psscale: Error: CPT api_colors2cpt_3870.cpt has no z-slices!
[Session psscale (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session psscale (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session psscale (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)

Can you please write the exact command which I need to use? Because I am not getting it.

**Comment by PaulWessel** [comment]
I would like to but I do not know how your $cpt file as created.  How did you create it?  It seems to be empty judging from the messages.  I suggest you model your script after one of the many similar type scripts in our gallery or tutorial - they are both online at www.generic-mapping-tools.org.

**Comment by abhi99328** [comment]
I only found 3 examples in the psscale documentation which was not helpful much. Can you give me the specific link where I can find those scripts? If you don't mind asking what would you do if you have to make an colored contour plot along with a vertical scale at the right of the plot?

In anticipation of your response.

**Comment by PaulWessel** [comment]
Have a look at the gallery and model your script after something that has what you need.  There may not be exactly what you want in one plot but there are color contour maps and color tables placed not the side in many of them: https://docs.generic-mapping-tools.org/latest/Gallery.html#the-50-examples.

**Comment by seisman** [comment]
No feedback. Closed.
