### ISSUE TITLE
Remove SVN completely

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#132]
Following files still contain SVN or svn, which should be removed completely. The file list is updated on Jan 29, 2019.

- [ ] cmake/dist/CMakeLists.txt
- [ ] cmake/dist/Info.plist.in
- [ ] cmake/modules/ConfigCMake.cmake
- [ ] doc/examples/gmtest.in
- [ ] doc/rst/conf.py.in
- [ ] doc/scripts/gmtest.in
- [ ] share/VERSION.in
- [ ] src/config.h.in
- [ ] src/gmt-config.in
- [ ] src/gmt.c
- [ ] src/gmt_init.c
- [ ] src/gmt_version.h.in
- [ ] test/gmtest.in

**Comment by PaulWessel** [comment]
We will try to fix the remaining ones during the Faro workshop.
