### ISSUE TITLE
Incorrect position on page for subplot leads to cropping

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1320]
**Description of the problem**

Some subplots appear cropped at the bottom.  This example illustrates the problem.  It appears in the PostScript so not a ghostscript problem this time:

```
gmt begin map ps
gmt subplot begin 4x2 -Fs4c/4c -A
for i in $(seq 1 8); do
    gmt basemap -R0/10/0/10 -Baf -c
done
gmt subplot end
gmt end
```

**Comment by PaulWessel** [comment]
I noticed that the debug option to see what the spacing etc are (-F+d) is broken (looks like a inch to cm problem) so this may be related to the lack of proper offset.  Will need to dig in.

**Comment by PaulWessel** [comment]
All is well when **-S** is used to set things up.  Things seems to break when no **-S** is used.  Need to determine what the equivalent **-S**.  Also, cannot fully account for sizing when **-B** is given later since dimensions are already calculated.

**Comment by PaulWessel** [comment]
Hi @seisman, I think this is a hard one to solve.  It may be better to issue a warning to users who bypass the -S options and set various -B settings as they wish.  The math on offsets are all based on -S settings and all our examples uses -S.  This setup seems a bit fragile.  I will try to document this in gurudocs for now so we understand what is going on.

**Comment by seisman** [comment]
@PaulWessel It seems this issue is fixed by some unknown commits. Please check it again.

**Comment by PaulWessel** [comment]
Yes, there was one commit straight to 6.0 where I goofed yesterday.  Must be that.  I was working on that yesterday and the problem had to do with incorrect sums of tick lengths and margiins etc adding up to the figure dimensions, which is then used to move the origin.  Works fine now.
