### ISSUE TITLE
SBAS problem

### ISSUE THREAD

**Issue by annisa3** [GenericMappingTools/gmt#1321]
I got some problem when I run SBAS in GMTSAR. Here is a command I use `sbas intf.tab scene.tab 33 16 24452 16212 -wavelength 0.0554658 -rms -dem` and the result I got is

compute RMS misfit
compute DEM error

setting smoothing to   0.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  37.000 degree 
setting range to 866000.000 m 
memory allocation! phi

**Comment by seisman** [comment]
This is the repository of GMT, not GMTSAR. Please post GMTSAR related questions to [their forum](http://gmt.soest.hawaii.edu/projects/gmt5sar/boards/6) or [GitHub Issue](https://github.com/gmtsar/gmtsar/).
