### ISSUE TITLE
The meaning of margin option -M in subplot begin

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1327]
**Description of the problem**

I think my intention with the **-M**_margin_ option was to specify the extra spacing _between_ subplots in the whole sets of subplots.  I.e., this is interior margins.  The outside frames of the subplot should not change.  However, the docs says

> **-M**_margins_
> This is margin space that is added around each subplot beyond the automatic space allocated for tick marks, annotations, and labels. The margins can be a single value, a pair of values separated by slashes (for setting separate horizontal and vertical margins), or the full set of four margins (for setting separate left, right, bottom, and top margins) [0.5c].

This description implies margins are added around each subplot on _all_ sides, not just between subplots.  I think this is wrong.  It should say

> **-M**_margins_
> This is margin space that is added between neighboring subplot in addition to the automatic space allocated for tick marks, annotations, and labels. The margins can be a single value, a pair of values separated by slashes (for setting separate horizontal and vertical margins), or the full set of four margins (for setting separate left, right, bottom, and top margins) [0.5c].

Note that the default of 0.5c means that between subplots there will be a 1 cm extra separation.

**Comment by seisman** [comment]
Agreed. I believe the extra exterior margins (if there are any) are automatically cropped by psconvert.

**Comment by joa-quim** [comment]
Yes, but this is a good example of when *subplot* should be replaced by *panel*.

**Comment by PaulWessel** [comment]
I think subplot and panel means the same thing.  The figure is a collection of many subplots, i.e., panels.
