### ISSUE TITLE
Clarifying the language used for subplots

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1338]
**Description of the problem**

Our documentation is a bit loose with regards to subplots.  My understanding is this:

1. A subplot is, as the name implies, a component of a larger figure.
2. In this context, a subplot and panel means the same thing
3. The collection of all the subplots should be refered to as a figure, not a "subplot".

If @GenericMappingTools/core agree on this then I can improve the subplot documentation by only using two terms: _figure_ to mean the collection of all those subplots, and _subplot_ to refer to one of those components.

**Comment by joa-quim** [comment]
Yes, agree.

**Comment by seisman** [comment]
OK to me.
