### ISSUE TITLE
Consistent module name format in usage

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1357]
Classic-name usage:

```
$ gmt pscoast -                                                                                                                 
pscoast [core] 6.0.0_010caf5_2019.08.09 [64-bit] - Plot continents, countries, shorelines, rivers, and borders on maps

usage: pscoast -J<args> [-A<min_area>[/<min_level>/<max_level>][+a[g|i][s|S]][+r|l][+p<percent>]] [-B<args>]
```

Modern-name usage:
```
$ gmt coast -                                                                                                                   
gmt coast [core] 6.0.0_010caf5_2019.08.09 [64-bit] - Plot continents, countries, shorelines, rivers, and borders on maps

usage: gmt coast -J<args> [-A<min_area>[/<min_level>/<max_level>][+a[g|i][s|S]][+r|l][+p<percent>]] [-B<args>]
```

The modern-name usage has an extra prefix "gmt" before module name. Why don't the classic-name usage have the same "gmt" prefix?

**Comment by seisman** [comment]
After #1358, the usage message is:

```
gmt coast [core] 6.0.0_44efb6e_2019.08.10 [64-bit] - Plot continents, countries, shorelines, rivers, and borders on maps

usage: coast -J<args> [-A<min_area>[/<min_level>/<max_level>][+a[g|i][s|S]][+r|l][+p<percent>]] [-B<args>]
```

We still miss a prefix "gmt" before the module name, i.e. `usage: coast` -> `usage: gmt coast`

**Comment by PaulWessel** [comment]
May have to go through all modules and replace "usage: %s" with "usage: gmt %s".

**Comment by seisman** [comment]
We had the "gmt" prefix for modern usages before #1358 was merged.

I think we can fix it by setting `mode_name = full_name` in function `gmt_show_name_and_purpose`.

**Comment by PaulWessel** [comment]
Sorry, yes you are right.  Please return full_name; I am going out for dinner.

**Comment by PaulWessel** [comment]
We should do the same for the classic modules in RST.  No reason why it should say "psbasemap" and not "get psbasemap" in GMT 6 classic mode.
