### ISSUE TITLE
Is there any relationship between the spacing of pssac and psxy?

### ISSUE THREAD

**Issue by abhi99328** [GenericMappingTools/gmt#1360]
I want make two different figures. One figure of receiver functions (RF) using pssac and another figure of its corresponding BAZ and DELTA using psxy. For that I have to plot the corresponding baz and delta of each RF at equal spacing as in the pssac plot.

I am attaching a file how I want to make that plot.
![IMG-20190718-WA0006](https://user-images.githubusercontent.com/53807516/62820971-1db82880-bb8a-11e9-8642-2382af2ffb1f.jpg)

**Comment by seisman** [comment]
@abhi99328 Sorry, I don't follow what you want to do. What are the X axis and Y axis of the two panels? What is DELTA?

**Comment by abhi99328** [comment]
In the left panel X-axis is time and the individual receiver functions (RF) are plotted along the Y-axis with a spacing of 0.05i.
In the right panel the lower X-axis is DELTA (epicentral distance) and the upper X-axis is BAZ. The values of these two parameters are stored in the receiver function (RF) name. This is the corresponding DELTA and BAZ plot of the individual RFs plotted in the left panel.

**To make the left panel I am using the following script**
psbasemap -JX3i/6.85i -R-5/25/-0.4/0.5 -Ba5f5weSn -P -K> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2018.224.14.58.076.015.eqr -O -K -Gn+gblue -Gp+gblack -Y-6.9>> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2017.121.14.21.086.018.eqr -O -K -Gn+gblue -Gp+gblack -Y0.05i>> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2017.121.14.18.086.018.eqr -O -K -Gn+gblue -Gp+gblack -Y0.05i>> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2017.148.07.37.082.032.eqr -O -K -Gn+gblue -Gp+gblack -Y0.05i>> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2017.144.16.36.080.035.eqr -O -K -Gn+gblue -Gp+gblack -Y0.05i>> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2017.088.04.09.062.038.eqr -O -K -Gn+gblue -Gp+gblack -Y0.05i>> plot_BAZ_BANS.ps
pssac -R -J -C -M1.5 BANS.2017.128.15.47.075.039.eqr -O -K -Gn+gblue -Gp+gblack -Y0.05i>> plot_BAZ_BANS.ps


**BANS.2018.224.14.58.076.015.eqr** In this eqr filename, 076 is DELTA and 015 is BAZ.

I am attaching my RF plot but I am not able to make the DELTA and BAZ plot. Because I am not getting how to convert the pssac spacing (0.05i) into psxy plot. And one more the thing, in a single plot can I use two different parameters for the lower and upper X-axis or do I need to make two different plots first and then overlap it with another?

[plot_BAZ_BANS.pdf](https://github.com/GenericMappingTools/gmt/files/3491235/plot_BAZ_BANS.pdf)

In anticipation of your response.

**Comment by seisman** [comment]
For the left panel, you can use following command to plot all waveforms in a single pssac command.

```
gmt pssac *.eqr -R -J -C -M1.5 -En -O -K -Gn+gblue -Gp+gblack >> plot_BAZ_BANS.ps
```

`-En` means you're plotting a trace-number profile, in which the Y axis is the trace number (staring from 0). The order of the traces is determined by the bash wildcard expansion, the same as `ls *.eqr`.

Then, in the right panel, you can loop over all your *.eqr file. For each file, the Y value is the trace number.

**Comment by abhi99328** [comment]
I was trying to plot .eqr files according to your pssac command but it's showing some errors and the plot wasn't made.
**USED COMMAND**
pssac *.eqr -JX3i/4.2i -R-5/35/0/72 -C -M1.5 -En -O -K -Gn+gblue -Gp+gblack -V >> plot.ps

I DON'T KNOW HOW TO FIX THE ZMIN/ZMAX RANGE? FOR TOTAL NUMBER OF 73 FILES I GAVE THE RANGE OF 0/72.

**The given error**
_pssac: Plotting SAC file 71: CHAM.2018.308.07.55.046.109.eqr_
pssac: => CHAM.2018.308.07.55.046.109.eqr: reference time is 0
pssac: => CHAM.2018.308.07.55.046.109.eqr: depmax=0.323016 depmin=-0.232287 depmen=0.00528215
pssac: => CHAM.2018.308.07.55.046.109.eqr: yscale of trace: 18.231
pssac: => CHAM.2018.308.07.55.046.109.eqr: location of trace: (-5, 71)
pssac: => CHAM.2018.308.07.55.046.109.eqr: Painting traces: zero=71 t0=-5 t1=34.95
pssac: => CHAM.2018.308.07.55.046.109.eqr: Painting traces: zero=71 t0=-5 t1=34.95
_pssac: Plotting SAC file 72: CHAM.2018.313.01.49.063.339.eqr_
pssac: => CHAM.2018.313.01.49.063.339.eqr: reference time is 0
pssac: => CHAM.2018.313.01.49.063.339.eqr: depmax=0.562183 depmin=-0.45348 depmen=0.0116525
pssac: => CHAM.2018.313.01.49.063.339.eqr: yscale of trace: 9.96761
pssac: => CHAM.2018.313.01.49.063.339.eqr: location of trace: (-5, 72)
pssac: => CHAM.2018.313.01.49.063.339.eqr: Painting traces: zero=72 t0=-5 t1=34.95
pssac: => CHAM.2018.313.01.49.063.339.eqr: Painting traces: zero=72 t0=-5 t1=34.95

**I want plot .eqr files as a function of BAZ. Lowest BAZ at the bottom and the highest BAZ at the top. Can I do that with your command? Because currently it is making a mixed type of arrangement**

**Comment by seisman** [comment]
> pssac: Plotting SAC file 71: CHAM.2018.308.07.55.046.109.eqr
pssac: => CHAM.2018.308.07.55.046.109.eqr: reference time is 0
pssac: => CHAM.2018.308.07.55.046.109.eqr: depmax=0.323016 depmin=-0.232287 depmen=0.00528215
pssac: => CHAM.2018.308.07.55.046.109.eqr: yscale of trace: 18.231
pssac: => CHAM.2018.308.07.55.046.109.eqr: location of trace: (-5, 71)
pssac: => CHAM.2018.308.07.55.046.109.eqr: Painting traces: zero=71 t0=-5 t1=34.95
pssac: => CHAM.2018.308.07.55.046.109.eqr: Painting traces: zero=71 t0=-5 t1=34.95
pssac: Plotting SAC file 72: CHAM.2018.313.01.49.063.339.eqr
pssac: => CHAM.2018.313.01.49.063.339.eqr: reference time is 0
pssac: => CHAM.2018.313.01.49.063.339.eqr: depmax=0.562183 depmin=-0.45348 depmen=0.0116525
pssac: => CHAM.2018.313.01.49.063.339.eqr: yscale of trace: 9.96761
pssac: => CHAM.2018.313.01.49.063.339.eqr: location of trace: (-5, 72)
pssac: => CHAM.2018.313.01.49.063.339.eqr: Painting traces: zero=72 t0=-5 t1=34.95
pssac: => CHAM.2018.313.01.49.063.339.eqr: Painting traces: zero=72 t0=-5 t1=34.95

These are verbose messages, not errors.

> I want plot .eqr files as a function of BAZ. Lowest BAZ at the bottom and the highest BAZ at the top.

Use `-Eb` instead.

**Comment by abhi99328** [comment]
But using -En it wasn't making any figure so I put the -V.

**Comment by abhi99328** [comment]
The -En is working now after putting the -Bx switch.
**The used command**
`gmt pssac *.eqr -R-5/25/-5/32 -JX3i/2.1i -Bx5+l'Time(s)' -En -BWSen -M1.5c -Y2 -Gn+gblue -Gp+gblack -P -V >> plot_new.ps `

It is plotting the .eqr files but not in ascending order. There is a problem using -Eb. It plots all the .eqr file in a particular BAZ bin. But I want to plot individual .eqr files from lowest to highest according to their BAZ. I am attaching a file for your consideration.
![1-s2 0-S0031920116300292-gr4](https://user-images.githubusercontent.com/53807516/62995664-2a38cb80-be7f-11e9-9c2f-2c3194b0be7d.jpg)

**Comment by seisman** [comment]
I think you can save the baz value to a SAC header variable, e.g. user3, and use `-Eu3`, which means the Y value of any file is determined by the SAC header variable user3.

**Comment by seisman** [comment]
No feedback. Closed.
