### ISSUE TITLE
Some thoughts before GMT 6 release

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1362]
**Description of the desired features**

GMT5 was released in October 2013, so GMT 6 will come out about 6 years later.  Here are some ideas, some new, some we have discussed, to decide on before we release.

- Should we make some (subtle) modifications to the colors used by the logo module? That way the 6 logo will look somewhat distinct from previous releases.  We have tended to change the logo for major updates.
- We discussed getting a DOI for the 6.0.0 release and have gmt --show-doi or --show-citation display this information. @leouieda said we could reserve the DOI now and apply it when we release.  How will this work and when do we do it?
- Should there be a --show-commands to list the modern mode commands begin, end, etc?
- Should there be a --show-dataserver to display the currently selected GMT data server?
- Should we have undocumented --show-version and --show-help so that there is a --show-* for all the choices?

**Comment by joa-quim** [comment]
Almost no opinion on this, but leaning to a no at all but second. On the other hand I wouldn't mind having a logo with slight darker green and red. 

The *--show-dataserver*, however, made me think in the aliases.  **GMT_DATA_URL** is something no one will remember, meaning that a visit to the ``gmt.conf`` man page is mandatory but a ``gmt set dataserver=XXX`` would much easier to remember. Ofc not for 6.0

**Comment by PaulWessel** [comment]
I think GMT_DATA_SERVER is a better word that GMT_DATA_URL.  We could add that as an alias to GMT_DATA_URL and only document GMT_DATA_SERVER (i.e., backwards compatibility).

**Comment by PaulWessel** [comment]
in the same vein, GMT_DATA_URL_LIMIT is a bad name I think, should have been GMT_DATA_SIZE_LIMIT or GMT_DATA_SERVER_SIZE_LIMIT (pretty long).

**Comment by seisman** [comment]
> * Should we make some (subtle) modifications to the colors used by the logo module? That way the 6 logo will look somewhat distinct from previous releases.  We have tended to change the logo for major updates.

I agree.

> * We discussed getting a DOI for the 6.0.0 release and have gmt --show-doi or --show-citation display this information. 

Do you mean `gmt --show-doi` displayes the DOI of specific version, and `gmt --show-citation` displays .the G-cube paper? 

> @leouieda said we could reserve the DOI now and apply it when we release.  How will this work and when do we do it?

Yes, we can do reserve a DOI at any time. This is what [zenodo FAQ](http://help.zenodo.org/) says:

> **Can I know the DOI of my record before publishing, so that I can include it in the paper or dataset?**
> Yes you can! On the upload page under Basic Information and Digital Object Identifier click the Reserve DOI button. The text field above will display the DOI that your record will have once it is published. This will not register the DOI yet, nor will it publish your record (so you can still update the files). This DOI can be safely used in the record's own content as well as any other separate datasets or papers you might be planning to publish.

> * Should there be a --show-commands to list the modern mode commands begin, end, etc?

Do users care about (or need to know) the difference between "gmt commands" and "gmt modules"?

> * Should there be a --show-dataserver to display the currently selected GMT data server?

Agree.

> * Should we have undocumented --show-version and --show-help so that there is a --show-* for all the choices?

I think `--version` and `--help` are standard options for most CLI softwares. Why do we need `--show-version` and `--show-help`?

**Comment by PaulWessel** [comment]
How about this compared to https://www.generic-mapping-tools.org:
![logo](https://user-images.githubusercontent.com/26473567/62920893-c0b3a280-bd42-11e9-9495-9559a558c8c2.png)

**Comment by leouieda** [comment]
I like the old color better. This is too dark.

> I think --version and --help are standard options for most CLI softwares. Why do we need --show-version and --show-help?

I agree. These are go to commands in most CLI

**Comment by PaulWessel** [comment]
Throwing another one at you:
![logo](https://user-images.githubusercontent.com/26473567/62959950-55df8700-bd95-11e9-955c-5bae9bce63a2.png)
#define c_land		"sandybrown"
#define c_gmt_fill	"darkseagreen"
#define c_water		"lightsteelblue"

**Comment by joa-quim** [comment]
I like greens. The previous (red) was too dark I agree. 

Sent from my iDedo

No dia 13/08/2019, às 17:41, Paul Wessel <notifications@github.com> escreveu:

**Comment by PaulWessel** [comment]
Feel free to play with those three defines in gmtlogo.c and submit candidates.

**Comment by joa-quim** [comment]
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/63050259-942e9080-bed2-11e9-869f-a0e524e7fa79.png)

From a Cork tree
#define c_land		"seagreen"
#define c_gmt_fill	"175/98/70"

**Comment by joa-quim** [comment]
Or, with the Cork  bark as a pattern
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/63064384-b89d6380-bef8-11e9-9445-1c05ccb67aa1.png)
![sobreiro](https://user-images.githubusercontent.com/537321/63064389-bdfaae00-bef8-11e9-95b7-e5dbcb64e9f8.jpg)

**Comment by PaulWessel** [comment]
LOL.  Not sure about texture fill for the logo though.

**Comment by PaulWessel** [comment]
Status update on this issue:

1. We added --show-dataserver and --new-script to gmt.c
2. There were no takers to add --show-version as --version and --help are standard
3. We still need to reserve a DOI.  This is for what, exactly? The source code tarball for 6.0.0?
4. We are not converging on new colors for the logo as no obvious excitement was detected for my last posted candidate (I think @joa-quim bark is too complicated for the logo).

I could add the two --show-doi and --show-citations and have them print two constants.  From other constants these should probably be added to cmake/ConfigDefault.cmake? Should I go ahead with this and then we can change those constants when known once paper is finalized?

**Comment by seisman** [comment]
Yes, I think it's fine to add them now, and the constants should be put in cmake/ConfigDefault.cmake.

**Comment by joa-quim** [comment]
I actually like my bark version but don't know how to add the pattern to the code, and we don't want it to depend on an external file.
But I also proposed a version with just the bark's color.

**Comment by PaulWessel** [comment]
Seems like only me and you voting on this, @joa-quim so the process lacks buy-in.  The default action is to do nothing of course.

**Comment by leouieda** [comment]
Sorry all, I actually prefer the old colors. I don't see much point in
changing the colors for the sake of making a change.

To be honest, I'm not a huge fan of the logo from a design perspective (it
doesn't work in small sizes, dark backgrounds, etc). But I appreciate it as
a coder geek.

>

**Comment by PaulWessel** [comment]
Ah, from the young and the drunk we learn the truth.  If there is no great excitement of chaining the color on the logo then we should not.  I move we stick with the current logo until the bus cometh.

**Comment by PaulWessel** [comment]
Closing this issue.
