### ISSUE TITLE
psbasemap unwanted rotation using UTM projection

### ISSUE THREAD

**Issue by zuliani71** [GenericMappingTools/gmt#1369]
**Description of the problem**
The  -Ju33/1:2000 in psbasemap rotates the frame of 90° the same psbasemap command but with a differern projection such -Jm1:2000 keeps the frame in the right orientation.

**Full script that generated the error**

```
psbasemap -R13.252/13.254/45.962/45.963 -Ju33/1:2000 -Bxa2sf1sg2s -Bya2sf1sg2s -V >> ./out.ps
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: macOS Mojave 10.14.5
* Version of GMT: 5.4.5

**Comment by PaulWessel** [comment]
I am unable to reproduce that.  There is nothing in the code that would add a 90 degree rotation.  Perhaps it is your postscript viewer?

**Comment by zuliani71** [comment]
Hello, below my code:
psbasemap -R13.252/13.254/45.962/45.963 -Jm1:2000 -Bxa2sf1sg2s -Bya2sf1sg2s -V > ./out.ps
psbasemap -R13.252/13.254/45.962/45.963 -Ju33/1:2000 -Bxa2sf1sg2s -Bya2sf1sg2s -V > ./out.ps

The 1st command works, the 2nd produce a rotated frame. I've tried with both macos preview and gv. They give me the same results.

**Comment by PaulWessel** [comment]
Well, that is because there is no -O and -K involved in any of the commands.  The first one needs -K, the second comand needs -O (and you probably want to offset the plots with -X and/or -Y).  See any of the examples in the gallery.

**Comment by zuliani71** [comment]
No, there is a misunderstanding: I've tried them separately. The following commands may be can clarify (pay attention to the output file):
psbasemap -R13.252/13.254/45.962/45.963 -Jm1:2000 -Bxa2sf1sg2s -Bya2sf1sg2s -V > ./out1.ps
psbasemap -R13.252/13.254/45.962/45.963 -Ju33/1:2000 -Bxa2sf1sg2s -Bya2sf1sg2s -V > ./out2.ps

out1.ps is orientend as I expect but out2.ps is 90° rotated

**Comment by PaulWessel** [comment]
Sorry, I somehow saw a >> in there...

Nevertheless, both of the commands gives land-scape oriented plots that come up that way in ghostview.  Looking inside the postscript files they both have the standard 90 degree rotation command to switch to landscape orientation.  What is telling you that one is rotated differently (i.e., what tool are you using to view the PostScript)?  You could zip the two PS files and attach them here.

**Comment by zuliani71** [comment]
Here attached the zip file with both outputs.
[out.zip](https://github.com/GenericMappingTools/gmt/files/3494426/out.zip)

**Comment by zuliani71** [comment]
The tools I use to view the ps are:
- "preview" for macos
- gv or ghostview

**Comment by PaulWessel** [comment]
Thanks, gv works find with your files.  Preview rotates the one you mentioned.  This is therefore a problem with preview (there is no rotated by 90 degree extra commands in the postscript).  It probably makes that decision based on some rules Apple added. Not much we can do.

**Comment by PaulWessel** [comment]
Probably safer to use gmt psconvert to convert the PS to PDF etc.

**Comment by zuliani71** [comment]
Ok, thanks for the support, probably you find out the real reason caused by some extra rule form Apple infact the gv version I'm using is one that runs on my mac.
