### ISSUE TITLE
an extra line in the national boundaries

### ISSUE THREAD

**Issue by bridgeW** [GenericMappingTools/gmt#1388]
**Description of the problem**

an extra line plotted in the solar results. There was a grey line tangential to the west edge of the Eger VI projection map  when I used the SOLAR module to plot the day-night terminator.

**Full script that generated the error**

```
export GMT_SESSION_NAME=$$
#!/usr/bin/env bash
gmt begin solar pdf
DATEstr=2019-04-24T12:15:30

gmt coast -Rd -JKs100/10i -Dl -A5000 -W0.5p -N1/0.5p,gray -S175/210/255 -Bafg --MAP_FRAME_TYPE=plain
gmt solar -Td+d${DATEstr} -Gnavy@95
gmt solar -Tc+d${DATEstr} -Gnavy@85
gmt solar -Tn+d${DATEstr} -Gnavy@80
gmt solar -Ta+d${DATEstr} -Gnavy@80

gmt solar -I+d${DATEstr} -C | gmt plot -Sc0.5c -Gyellow -t40
echo 90 28 | gmt plot -SE-10c -Wred

gmt end
```

**Full error message**

No error message comes out.

**System information**

* Operating system: MacOS 10.14.4
* Version of GMT: v6.0.0rc3

**Comment by seisman** [comment]
A minimum script to reproduce the bug:
```
gmt begin solar pdf
gmt coast -Rd -JKs100/10i -Dl -A5000 -W0.5p -N1/0.5p,gray -S175/210/255 -Bafg
gmt end show
```
It looks like a bug of GSHHG data or **coast**.

**Comment by PaulWessel** [comment]
It comes from the political boundaries (-N1) and affects all resolutions.  Will try to dig in later today or during workation.

**Comment by joa-quim** [comment]
Is the ``export GMT_SESSION_NAME=$$`` line now mandatory? Without it I get

```
C:\v>C:\programs\WinGit\bin\bash.exe t.sh
gmt.exe [ERROR]: Shared GMT module not found: coast

ERROR: No module named coast was found.  This could mean one of four cases:
  1. There actually is no such module; please check your spelling.
  2. You used a modern mode module name while running in GMT classic mode.
  3. Module exists in the GMT supplemental library, but the library could not be found.
  4. Module exists in a GMT custom library, but the library could not be found.
Shared libraries must be in standard system paths or set via environmental parameter %%PATH%%.

gmt.exe [ERROR]: Not available in classic mode
```

**Comment by PaulWessel** [comment]
No, it is not mandatory.  Runs fine for me.  Try with -Vd to see what is happening.

**Comment by joa-quim** [comment]
Runs fine if I make it a batch, but otherwise in bash

```
gmt.exe [DEBUG]: Exit:  gmtinit_get_history
gmt.exe [DEBUG]: GMT_Create_Session initialized GMT structure
gmt.exe [DEBUG]: Shared Library # 0 (core). Path = gmt_w64.dll
gmt.exe [DEBUG]: Loading core GMT shared library: gmt_w64.dll
gmt.exe [DEBUG]: Loading GMT plugins from: C:/progs_cygw/GMTdev/gmt5/compileds/gmt6/VC14_64/bin/gmt_plugins
gmt.exe [DEBUG]: Shared Library # 1 (supplements). Path = C:/progs_cygw/GMTdev/gmt5/compileds/gmt6/VC14_64/bin/gmt_plugins/supplements_w64.dll
gmt.exe [DEBUG]: Shared Library # 2 (mbgmt). Path = C:/progs_cygw/GMTdev/gmt5/compileds/gmt6/VC14_64/bin/gmt_plugins/mbgmt_w64.dll
gmt.exe [ERROR]: Shared GMT module not found: coast

ERROR: No module named coast was found.  This could mean one of four cases:
```

**Comment by PaulWessel** [comment]
Runs fine for me in git bash but I did not type bash.exe, just typed t.sh.  This is with rc3.

**Comment by joa-quim** [comment]
Right, confirm that too. I type ``bash t.sh`` when running from the WinGit cmd window that knows about WinGit bash.exe. Can't do the same in a regular cmd window because then it's thw WSL bash.exe that pops up and it complains that it doesn't know who is ``gmt`` (would need to say ``gmt.exe``).

**Comment by PaulWessel** [comment]
An update on this: It comes from bin number 171 (low resolution).  Minimal plot of just the national boundaries for that bin shows the stray line:

```
gmt begin solar pdf
    gmt coast -Rd -JKs100/10i -Dl -N1/0.5p,gray -Bafg10 -+171
gmt end show
```

So something goes wrong when the end of the line touches the periodic boundary on the right.
