### ISSUE TITLE
Use country code instead of coordinate pairs

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#139]
What about adding a switch that enables e.g. ``psxy`` or ``psxtext`` to be able to translate country codes (DCW) to centroid coordinates?

Assume we have a textfile that we want to plot with ``pstext``. In the case for Georgia we would put
```
GE Georgia
```

which would be translated to
```
43.5479837681   42.1557072697 Georgia
```
(coordinates obtained with ``$ pscoast -EGE -M | gmt spatial -Q``)

I do see issues in this; e.g. I had to pick Georgia to get a single polygon from DCW - and a single centroid. Alot of countries have > 1 country polygon.

**Comment by leouieda** [comment]
@abanbj as you pointed out, this might put country labels outside of countries for some configurations. Could you not do this with awk and `pscoast -EGE -M | gmt spatial -Q` as you pointed out?

**Comment by abanbj** [comment]
Absolutely, I agree. Closing the issue.
