### ISSUE TITLE
Optional fade in/out in movies

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1391]
**Description of the desired feature**

It would be convenient to add fade in and/or out option to movie.  It would add a short sequences of frames that would enclose the main movie part.  It may also be helpful to have a simple way to add in a title slide with basic items like movie title, movie authors, citation, etc and for how many frames it should be visible.  While these things can be added later by tools like iMovie and MovieMaker, that adds an extra layer of complexity.

**Comment by seisman** [comment]
Sounds a good idea.
