### ISSUE TITLE
The -M option in subplot has no logical default value

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1401]
**Description of the problem**

When subplot begin is called one can add _extra_ space between neighboring frames via the **-M** option.  However, I assigned it a default value of 0.5 cm and one must use **-M** to change that and even **-M**0 to not add extra space.  Since suitable spacing depends entirely on the size of the overall figure as well as the subplots themselves, it seems the default of 0.5c is arbitrary.  The only default that would make sense to me is zero, as in inset.  What do @GenericMappingTools/core think?

**Comment by seisman** [comment]
What about 5% or 10% of the subplot dimension?

**Comment by PaulWessel** [comment]
Possible.  Not sure if this is a relative measure (your suggestion) or if an absolute offset (e.g., such as 0.5c) is better.  Seems somewhat dependent on font size used for annotations.  Play with the subplot script you used to demonstrate -C issue and let -M take on different values.
There is also a factor-of-two problem: Since the margin only applies to the spaces between subplots the 0.5c becomes a 1cm gap between subplots.  This may not be obvious to users.  I think it makes more sense then to say the gap is 1 cm.  So I suggest we describe -M in terms of extra spacing between neighboring subplots and internally divide by two.

**Comment by seisman** [comment]
> So I suggest we describe -M in terms of extra spacing between neighboring subplots and internally divide by two.

I agree.

Default margin of 0 doesn't make sense to me. Attached below is a figure with 
```
subplot begin 3x3 -Fs5c/5c -BWSen -M0
```

![image](https://user-images.githubusercontent.com/3974108/63216152-4480dc80-c0ff-11e9-8eb6-c9a689f7d1b9.png)

**Comment by PaulWessel** [comment]
Yes, if parallel annotations (+p in -S I think) is not used then it is difficult for us to estimate the width of those horizontal annotations (your "10").  Try -M6p and see if that is OK (eventually 12p or PRIMARY_ANNOT_FONTSIZE) once the factor of two is dealt with,

**Comment by PaulWessel** [comment]
I think using the annotation font size is a pretty good default selection.  Like your % suggestion it will scale with something that can change (annotation font) and give a reasonable value.  I can imagine a wide subplot where % would not be a great default.  
As for the factor of two there is this complication: We allow user to set separate margins on all four sides, hence the total spacing between any two tiles can vary and we cannot combine up the total and then assign that to "west" or "east".  So looks like we must retain the "half-margin" practice as the most flexible.  This means I will use half the font size as the default margin.

**Comment by joa-quim** [comment]
Yes, I think that annot font size is the right measure but don’t we need also to take into account the separation between annotations and axes?

Sent from my iDedo

No dia 18/08/2019, às 04:53, Paul Wessel <notifications@github.com> escreveu:

**Comment by PaulWessel** [comment]
The subplot modules tries to accommodate all of that: offsets, ticks, annotations.  The -M adds extra space to separate the tiles.

**Comment by PaulWessel** [comment]
To be clear, the distance from the right frame of one subplot to the left from of the next subplot includes both ticks, annotations, and even labels, all depending on what is present.  Because we cannot do this exactly in C, I added -M margin to add more control.

**Comment by seisman** [comment]
I agree with the annotation font size as the default margin.

**Comment by PaulWessel** [comment]
So maybe the way to explain this is that the default gives one font size spacing between interior tiles but you can change that and even have asymmetrical spacing with west having different space that east.  In all case, the observed space is a sum of west+east or south+north spacings, which normally sum to one font size. So, if you are to specify different margins then you are specifying half-spaces specific to one side.
