### ISSUE TITLE
Let subplot draw lines between the tiles

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1403]
**Description of the desired feature**

The subplot module should have a **-W**_pen_ option that will draw lines centered between all neighboring tiles.  This is particularly useful with the subplot does not use **-B** to draw annotations.

**Comment by PaulWessel** [comment]
For padding, this is a way it can be done now, which seems pretty clean to me:

```
#!/usr/bin/env bash
gmt begin tictactoe png
    gmt set FONT_ANNOT_PRIMARY 12p
    gmt subplot begin 3x3 -Fs5c+p1p+w1p -M0 -Blrbt -C0.25c
        gmt coast -Rg -JG30/30/?  -Gred -Bg -c0,0
        gmt coast -Rg -JG120/30/? -Gred -Bg -c1,1
        gmt coast -Rg -JG210/30/? -Gred -Bg -c2,2
    gmt subplot end
gmt end show
```
![tictactoe](https://user-images.githubusercontent.com/26473567/63229491-6ed4a780-c19c-11e9-8064-0a744c849d87.png)

**Comment by seisman** [comment]
It doesn't work well if you give **-M1c**

![tictactoe](https://user-images.githubusercontent.com/3974108/63230725-bed45e00-c1de-11e9-8fcb-3c7a3d3803bc.png)

**Comment by PaulWessel** [comment]
Yes, which is why you would not use -M here but use -C.  This is a bit work in progress I think.  There is the -F+c that may need to be included in this discussion as well.  I think for now we leave it and gain some more experience.

**Comment by seisman** [comment]
OK.

**Comment by joa-quim** [comment]
The -F is fine to draw lines for ALL subplots, but if we want to draw only around filled canvas or paint them with different bg colors then we will need to have the +p, +g, etc available as an option in gmt subplot set as well. 

(Waiting for plain to Cambodia)

Sent from my iDedo

No dia 19/08/2019, às 04:50, Dongdong Tian <notifications@github.com> escreveu:

**Comment by PaulWessel** [comment]
Feature request for 6.1.  Closing this now,
