### ISSUE TITLE
Gallery in the documentation mixes classic and modern

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1412]
**Description of the problem**

The 50 GMT examples in the gallery shows classic mode while the 8 animation examples are modern.  Since we have separate documentation and tutorials for classic and modern we should probably  have separate classic and modern mode galleries, where the classic simply won't have any animations.  We can probably finish the remaining non-modern examples before the release.  Thoughts?

**Comment by seisman** [comment]
> we have separate documentation and tutorials for classic and modern 

I remember we decided to remove classic tutorial and cookbook from the repository and let classic-mode users to read the 5.4 documentations. I think we can do the same thing to the gallery.

**Comment by PaulWessel** [comment]
OK, then we need to convert examples 37, 38, 40, 45 to modern mode (test/exmod).  I think I saved those because there is more work then many of the others or they are inherently very classic.  Feel free to have a look.  Going out for a few hours - cannot avoid the beach the entire workation.

**Comment by seisman** [comment]
I've finished ex40 and ex45, but not sure what's the best way to convert ex37 and ex38.

**Comment by seisman** [comment]
Are we going to replace the classic examples with the modern ones now? The only issue is the Windows batch scripts, which are still in classic mode.

**Comment by PaulWessel** [comment]
They have not changed since 5.4 I think so anyone foolish enough to want to write BAT files can go there.

**Comment by PaulWessel** [comment]
So yes, I think we should show modern mode scripts.
