### ISSUE TITLE
Add grdcontour option for grd2kml

### ISSUE THREAD

**Issue by btozer** [GenericMappingTools/gmt#142]
**Description of the desired feature**

Add an option (e.g. -W) for overlaying contours in grd2kml using either:

1. a constant sample spacing and pen attributes (e.g. spacing=500 pen=1p,black)

gmt grd2kml input.grd -I+a340 -Ctable.cpt -W500+w1p,black -Nkml_output

or 

2. an input text file that contains the contour levels and corresponding pen attributes

gmt grd2kml input.grd -I+a340 -Ctable.cpt -Wcontours.txt -Nkml_output

contours.txt =
-4000 1p,grey
-3000 1p,grey
-2000 3p,black
-1000 1p,grey

"Under the hood" - Call grdcontour after grdimage and before psconvert

**Are you willing to help implement and maintain this feature?** Yes/No

4464c7b

**Comment by leouieda** [comment]
Relaying @PaulWessel's message:

> Hi @btozer, could you turn this into a branch and I will accept it and work on this soon. In my ignorance of git I dont know how to take this commit and make a branch.

**Comment by leouieda** [comment]
@btozer if you open a pull request from your `grd2kml_add_grdcontour` branch, we can get this started.

@PaulWessel once Brook opens the PR, we can comment and suggest changes or make changes directly to his branch. If you do make changes, please leave a comment on the PR before pushing them so Brook knows to `git pull` before making any new commits.

**Comment by btozer** [comment]
Ok, Just created a pull request: #322

**Comment by PaulWessel** [comment]
I think this should be closed - I added a contouring option a long time ago (**-W**).

**Comment by seisman** [comment]
Closed by #1117.
