### ISSUE TITLE
A issue when converting ex37 to modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1426]
Just tried to convert ex37 to modern mode. 

Below is part of the script:
```
gmt begin ex37 png

G=@grav.V18.par.surf.1km.sq
T=@mb.par.surf.1km.sq
gmt set FONT_TITLE 14p GMT_FFT kiss

gmt makecpt -Crainbow -T-5000/-3000 -H > z.cpt
gmt makecpt -Crainbow -T-50/25 -H > g.cpt
gmt grdinfo $T.nc -Ib > bbox
scl=1.4e-5
sclkm=1.4e-2
gmt grdimage $T.nc -I+a0+nt1 -Jx${scl}i -Cz.cpt -X1.474i -Y1i
gmt basemap -R-84/75/-78/81 -Jx${sclkm}i -Ba -BWSne+t"Multibeam bathymetry" 
gmt grdimage $G.nc -I+a0+nt1 -Jx${scl}i -Cg.cpt -X3.25i -V
gmt basemap -R-84/75/-78/81 -Jx${sclkm}i -Ba -BWSne+t"Satellite gravity"
gmt end show
```

The generated figure doesn't show the right panel correctly, because in modern mode, GMT automatically adds **-R-84/75/-78/81** to the second grdimage command.

![image](https://user-images.githubusercontent.com/3974108/63405460-e4b35b80-c3b4-11e9-9ceb-baa102df5cf7.png)

**Comment by PaulWessel** [comment]
Maybe have to add -R$G.nc to override the previous -R?

**Comment by seisman** [comment]
Adding -R$G.nc works.
