### ISSUE TITLE
Wrong -J history in subplot mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1427]
```
gmt begin map png
  gmt subplot begin 2x2 -Fs5c/5c
    gmt basemap -R0/160/0/1 -JX10c/7c -Baf
    echo 100 0.5 | gmt plot -Sc0.2c -Gred  -Baf
  gmt subplot end
gmt end show
```

The **plot** command should also have **-R0/160/0/1 -JX10c/7c**.

![image](https://user-images.githubusercontent.com/3974108/63438724-cec88980-c3fa-11e9-8825-e90e17d1aea1.png)

**Comment by PaulWessel** [comment]
So it picks up -R correctly and linear projection but then does something odd with the dimensions (making it square, not fitting the given space even.

**Comment by PaulWessel** [comment]
Wait a minute.  It is a subplot.  Did we not decide that for Cartesian plots you will either use -JX and it gets autoscaled or you use -Jx if you need to preserve a fixed scale?  So the second plot autoscales to fit the 5x5 cm subplot while the first one overrides it completely.  Do we really want that?

**Comment by seisman** [comment]
Same problem for geographic plots.
```
gmt begin map png
  gmt subplot begin 2x2 -Fs5c/5c
    gmt basemap -R0/360/-90/90 -JH10c -Baf
    echo 100 0 | gmt plot -Sc0.2c -Gred  -Baf
  gmt subplot end
gmt end show
```
![image](https://user-images.githubusercontent.com/3974108/63465691-c8083980-c42f-11e9-802f-0ff0cee47b4d.png)

**Comment by PaulWessel** [comment]
So isn't the answer that -J options given inside a subplot needs ? and not a fixed dimension?  We want this stuff to be easy, so having users overriding sizes should not be allowed.

**Comment by seisman** [comment]
I think we decided to allow options like -JH10c in subplot. See https://github.com/GenericMappingTools/gmt/issues/1344 for discussion.

**Comment by PaulWessel** [comment]
Seems like we decided to apply autoscaling?  Maybe we did not implement error checking when someone gives dimensions like you did.  I think it is very tricky to allow a user to specify an actual dimension in this controlled setting where we do all this stuff under the hood.  In hindsight, I think we should only allow these scenarios:

1. User can specify ? to indicate the map width or scale (e.g., -JP?/30) and we auto-compute the missing parameter and replace the ? value.
2. If no ? is used then we append /1 by assuming a width or scale is missing.  The / is only required ion there is a previous value (e.g., -JM takes no slash).
3. Use of -JX will fill the canvas. use -F and/or -C if you have specific needs
4. Use of -Jx will scale equally up to maximum fit in width or height.

**Comment by seisman** [comment]
_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/gmt/pull/1354#issuecomment-520073232_

> Basically, Cartesian projections will fill the subplot dimensions, so you use -Fs to set the subplot sizes and then Cartesian plots should auto-scale there if you dont give -J.  If you do give a -J then you are overriding that and your plot may no longer be centered in the subplot; see -C for fudging that.

I thought it meant **-JX10c/7c** in subplot is allowed. 

In this first script, **-JX10c/7c** is saved to gmt.history after the basemap command is executed. It looks "straightforward" (not sure if it's difficult technically) to get -J history and pass it to the plot command.

The reason I want such a feature is that, it's common to have a irregular subplot layout like this one:

![image](https://user-images.githubusercontent.com/3974108/63470049-9dbb7980-c439-11e9-9c30-471961d43e93.png)
Currently, nesting subplot isn't implemented, so there is no easy way to have a subplot layout like this one.

Of course, I can use **gmt subplot set 0 -Ce-5c** to have more space to the east side in the first subplot, but it's more intuitive to specify a figure size with **-JX10c/7c**.

**Comment by PaulWessel** [comment]
I agree that the layout you show is pretty common.  We currently allow different sizes but we have the same number of subplots per row.  I wonder if specifying 0% fraction for the second (missing) subplot might work?

**Comment by seisman** [comment]
> I wonder if specifying 0% fraction for the second (missing) subplot might work?

I believe it doesn't work. The subplot width settings are applied to all rows, which means the subplot layout must be regular.

**Comment by PaulWessel** [comment]
Since are are not going to implement nesting for 6.0, so need an interim decision about this.  I am off for a few hours now but will think about that and see if your suggestion can work.

**Comment by joa-quim** [comment]
In terms of syntax we could generalize mxn to c1,c2,c3 which would mean ”plot 3 rows in which first row has c1 columns, second c2 columns, ...”
Then, 2x2 and 2,2 would be equivalent. 

Sent from my iDedo

No dia 22/08/2019, às 05:07, Paul Wessel <notifications@github.com> escreveu:

**Comment by seisman** [comment]
Subplot also doesn't support logarithmic and power projections, e.g. `-JX?l`.

**Comment by PaulWessel** [comment]
I will look at log scaling to see what happens. BTW, please look at example 14 in the gallery for a way to manually do something similar to what you suggest.

**Comment by seisman** [comment]
Just checked ex14. It works by plotting the "irregular" panel outside of the **subplot mode**. But what if I want to tag the subplots? For the top 4 panels, I can use **subplot set -Axx**, but for the bottom panel, I may have to use `gmt text` to manually add the tag.

**Comment by PaulWessel** [comment]
Still not had time to learn why your fixed size -J fails...

**Comment by PaulWessel** [comment]
After resetting the subplot history, your script

```
gmt begin map png
  gmt basemap -R0/100/0/100 -JX10c/5c -Baf
  gmt subplot begin 1x2 -Fs5c/5c -Yh+2c -M0.5c -BWSen -A -R0/5/0/5
    gmt basemap -c
    gmt basemap -c
  gmt subplot end
gmt end show
```

now gives correct **-R**:

![map](https://user-images.githubusercontent.com/26473567/66944618-3eb55380-efe9-11e9-8da5-c910d4148f4b.png)

**Comment by seisman** [comment]
My first script still doesn't work:
```
gmt begin map png
  gmt subplot begin 2x2 -Fs5c/5c
    gmt basemap -R0/160/0/1 -JX10c/7c -Baf
    echo 100 0.5 | gmt plot -Sc0.2c -Gred  -Baf
  gmt subplot end
gmt end show
```

**Comment by PaulWessel** [comment]
I think this is getting back to the need for nested subplots.  We should leave that for 6.1 since it requires a redesign.  I made certain assumptions implementing the current scheme and adding special tests to deal with exceptions is not good style and likely to introduce problems.  Nesting is much cleaner.

**Comment by seisman** [comment]
OK, closing. Feature request for subplot nesting is in #1280.
