### ISSUE TITLE
Bug in Azimuthal Equidistant projection (-JE) 

### ISSUE THREAD

**Issue by longgangfan** [GenericMappingTools/gmt#144]
**Description of the problem**
When  I run the code below:
(1)`pscoast -JE-120/30/4.5i -Rg -Glightgray -B30/30 -Dc -A10000 -Wthinnest -P >test.ps`
![test](https://user-images.githubusercontent.com/11954551/47424333-05714b80-d7ba-11e8-8464-18adf9c15400.jpg)
It seems all right, but if I change the Longitude and latitude of the projection center or use "-S", it will output a image with some area overlapped like below.
(2)`pscoast -JE120/30/4.5i -Rg -Glightgray -B30/30 -Dc -A10000 -Wthinnest -P >test.ps`
![test](https://user-images.githubusercontent.com/11954551/47424607-9a744480-d7ba-11e8-97d5-f38ea3721a3a.jpg)
(3)`pscoast -JE-120/30/4.5i -Rg -Glightgray -Slightblue -B30/30 -Dc -A10000 -Wthinnest -P >test.ps`
![test](https://user-images.githubusercontent.com/11954551/47424860-3f8f1d00-d7bb-11e8-8f99-5d0590465bd8.jpg)

I test this bug on macos 10.14 (homebrew version gmt 5.4.4) and ubuntu 16.04 (github master branch), it can be reproduced on both of them.
If I set the horizon to 179.9999, the output seems to be right.
(4)`pscoast -JE-120/30/179.9999/4.5i -Rg -Glightgray -Slightblue -B30/30 -Dc -A10000 -Wthinnest -P >test.ps`
![test](https://user-images.githubusercontent.com/11954551/47425398-ca244c00-d7bc-11e8-89c0-7977a512977d.jpg)

**System information**

* Operating system: ubuntu 16.04/macos mojave
* Version of GMT: 6.0.0_93597c0/5.4.4

**Comment by joa-quim** [comment]
This is a duplication of the SVN https://gmt.soest.hawaii.edu/issues/872 issue.

**Comment by longgangfan** [comment]
> This is a duplication of the SVN https://gmt.soest.hawaii.edu/issues/872 issue.

Sorry for my duplication.

**Comment by joa-quim** [comment]
It's OK. We have to port the remaining bugs in the Track system to here anyway, so we may well start with this one.

**Comment by PaulWessel** [comment]
Thanks for this post.  It is a tricky nut to crack when some land hits the antipole (which is the perimeter).  I will check out your trick with the almost 180 horizon if I can detect when to set it that way.

**Comment by longgangfan** [comment]
The almost 180 horizon is not always working well, It depends on the longitude and latitude of the projection center.

**Comment by remkos** [comment]
Fixed by commit 86a2263
