### ISSUE TITLE
Create a gitter chatroom

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#145]
Before we find a better replacement of the forum, maybe we should create a gitter chatroom where people can ask questions. 

IMHO, github issue should be used to track issues only, not for asking questions.

**Comment by PaulWessel** [comment]
I agree we don't want folks to use issues for basic questions.  @leouieda has some thoughts about this as well.

**Comment by joa-quim** [comment]
Changed our minds about this. Closing
