### ISSUE TITLE
Should we have a RC4 release now prior to official 6.0.0 release

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1459]
It has been a while since RC3.  RC4 might be good since we had several issues in RC3, especially on the Windows side with malfunctioning ffmpeg.  I will be giving some short GMT workshops here in my department (some of the very basics from our UNAVCO workshop) and there is big interest. Would be a good opportunity to check that we are OK before we release.  Not sure if @joa-quim is anywhere near his laptop though.  Thoughts?

**Comment by joa-quim** [comment]
Hi, still in Thai but starting the way back. Today to Bangkok and tomorrow to Lisbon. Maybe I can do some work on Saturday but not sure. Better aim it to Sunday.

**Comment by PaulWessel** [comment]
Great, that works well.  There are steps before we get to building installers anyway.

**Comment by seisman** [comment]
Continue in #1471. Closed.
