### ISSUE TITLE
Proper use of the bbox device in psconvert

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1466]
The **bbox** device is described in the gs documentation, and there are a few points that we have not fully grasped, I think:

> By default, white objects don't contribute to the bounding box because many files fill the whole page with white before drawing other objects. This can be changed by:
> 
> << /WhiteIsOpaque true >> setpagedevice
> 
> Note that this device, like other devices, has a resolution and a (maximum) page size. As for other devices, the product (resolution x page size) is limited to approximately 500K pixels. By default, the resolution is 4000 DPI and the maximum page size is approximately 125", or approximately 9000 default (1/72") user coordinate units. If you need to measure larger pages than this, you must reset both the resolution and the page size in pixels, e.g.,
> 
> gs -dNOPAUSE -dBATCH -sDEVICE=bbox -r100 -g500000x500000

The first point is why #1462 became an issue: Only white was plotted and by default that does not count.  I reported this as a potential bug or feature and learned from the gs developers that one should read the manual. It would seem reasonable that if users select transparent PNG then we should add the /WhiteisOpaque true setting?

The second point addresses the page size.  The default is about 3x3 meters while we are assuming we can plot up to 11.55x11.55 meters.  This is untested territory of course and I am sure the HighResBoundingBox may depend on that resolution setting (4000 by default).  If we wanted to match that size I think we might need -r1098 -g500000x500000 but not sure that might work.  It is clear it is highly unusual that anyone would make a plot that is several meters but wall-maps can get that large.  We probably should test this at some point.  A related point here is that our PostScript coordinates are written as integers using 1200 units per inch.  So this is not that far from the 1098 needed to reach the 11.55 meter page if 500000 pixels is a hard limit.  Perhaps if we used -r1200 and -g500000x500000 we are OK since this is a 10.58x10.58 meter plot?  Finally, text outlines are not in 1/1200 inches so their coordinates will not be quantized like that, only lines etc.

Some possible actions to take:

1. If PNG is selected, insert the WhiteisOpaque true setting when calling the bbox device.
2. Consider lowering the resolution for boundinbox to handle a larger page size by passing -r1200 -g500000x500000.

Thoughts out there, @GenericMappingTools/core?

**Comment by PaulWessel** [comment]
It seems unfortunate to use -r1200 to ensure we can handle 11x11 meter plots while 99.99999% of plots would safely fit inside the 3x3 meter box that -r4000 can handle.  Maybe we can peak and look at GMTBoundingBox for this and realize the plot is > 3 meter and then we switch to -r1200, other wise keep -r4000.  That seem possible, no?

**Comment by PaulWessel** [comment]
Another option: We could call gs_BB with -r1000 which can handle max paper size, and if the resulting bounding box is < 3 meters then we can rerun the gs_BB call with -r4000.  The downside is two gs calls which may take extra time on very large PS files.  The trouble with GMTBoundingBox is that there may be lots of them so getting the first may simply tell us a small plot and there may be 100 of them filling in a 10 meter canvas.  So far, the double gs call is the only foolproof solution I have. Can @seisman or @joa-quim think of other schemes?

**Comment by joa-quim** [comment]
Why do we have many ``GMTBoundingBox``? That is used to create the GeoPDF and so far Kristof never reported any issue due to multiple GMTBBs.

**Comment by PaulWessel** [comment]
Well, the first GMT call writes a GMTBoundingBox but subsequent overlays (**-O**) do not.  So how do we know this is not a giant poster with lots of plots on it? The GMTBoundingBox only reports the extent of the first plot, not the entirety of the final illustration.

**Comment by joa-quim** [comment]
Yes, but occurrences of ``GMTBoundingBox`` there is only one.
But I think I have the solution. Do it the other way around. Run with ``-r4000`` (like we do) and if paper > 3 m rerun with ``-r1000``. Since this will be so rare in practice we are not adding any extra timing.

**Comment by PaulWessel** [comment]
I agree this is a good solution, but we cannot check if paper > 3m since it cannot return that - at best it will return the max it candors at that resolution, which is probably 500000/4000 = 125 inches.  I think on the safe size if we detect a bounding box that exceeds 2 meters in any dimension then it is OK to rerun with -r1000.

**Comment by PaulWessel** [comment]
I think we need more testing if we implement something like this and I dont want to do this days before 6.0.0.  I think we can live with a 3x3 meter limit until 6.0.1 or so since this can be labeled a bug.

**Comment by remkos** [comment]
Agreed not to mess with the bounding box part at this point, as it is difficult to assess all the side effects.

Regarding `/WhiteIsOpaque true`, would it not be possible to always add it? I.e. in the standard GMT header. I do not think it can harm, would it? Also, in issue #1462 it was a PDF being created, not a PNG. So this issue is generic when creating the BoundingBox. However, despite the discussion on resolution that follows in the quote in the original post, the `/WhiteIsOpaque` issue appears to be separate from the BoundingBox issue. That's why I suggest to incorporate at least that into 6.0.0.

**Comment by remkos** [comment]
I just did some test, and it works with the `/WhiteIsOpaque` in place.
For certain plots, that I later want to use on a dark background, I have white borders and annotations. To avoid cutting them off in the trimmed and transparent PNG, I have used grey95 instead as colour.

Now I tried if with white, and indeed some of the annotation got trimmed off. But with the line
<pre>
<< /WhiteIsOpaque true >> setpagedevice
</pre>added to the header, the trimming is correct.

So I suggest adding it to the GMT header. Possibly within a `PSLevel gt 1 { } if` as the other `setpagedevice` command.

**Comment by remkos** [comment]
Issue can be closed with commits f85c80a and 2cf022b

**Comment by seisman** [comment]
Do we really want to close this? The `-r1000` and `-r4000` issue seems unsolved.

**Comment by PaulWessel** [comment]
We should make a new issue on just that.  I'll do that after breakfast.
