### ISSUE TITLE
Transparent PNG images don't display well in Chrome

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1467]
The images in the documentations are in transparent PNG format, generated by `gmt psconvert -TG`.

The images looks good in web pages, but not readable if opened directly in Chrome.

This is what I see when I open this image https://docs.generic-mapping-tools.org/dev/_images/ex02.png in Chrome. The black texts are invisible, due to the dark background of Chrome.

![image](https://user-images.githubusercontent.com/3974108/63959923-521d5700-ca5b-11e9-9f39-d10382808ddd.png)

Maybe we can use `gmt psconvert -Tg` so that the images always have a white background.

**Comment by PaulWessel** [comment]
Yes, I think that is what we imagined, and because the browser fills in white for us we did not really notice. I agree -Tg should be used - these are all plots designed for paper.
