### ISSUE TITLE
Release GMT 6.0.0rc4

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1471]
**Version**:  6.0.0rc4

**Before release**:

- [x] run `src/gmt_make_*.sh` to update some .c and .h files
- [x] check if all tests pass on macOS, Linux and Windows
- [x] update changelog
- [x] update INSTALL.md
- [x] build documentations and fix warnings if any
- [x] check/set values in `cmake/ConfigDefault.cmake`
    - [x] `GMT_VERSION_YEAR` is current year
    - [x] `GMT_PACKAGE_VERSION_*` is correctly set
    - [x] `GMT_LIB_SOVERSION` is correctly set
    - [x] set `GMT_PUBLIC_RELEASE` to `TRUE`
- [x] freeze codes and commit all changes to GitHub

**Release**:

- [x] create source tarballs (tar.gz and tar.xz) (@PaulWessel)
- [x] create macOS bundle (@PaulWessel)
- [x] create Windows installers (win32 and win64) (@joa-quim)
- [x] make a tag and push it to github
    ```
    git tag x.x.x
    git push --tags
    ```
- [x] go to [GitHub Release](https://github.com/GenericMappingTools/gmt/releases) and make a release. Remember to attach the source tarballs, macOS bundle and Windows installers.
- [x] upload source tarballs, macOS bundle, Windows installers to the GMT FTP (@PaulWessel)
- [x] update README and VERSION files on the GMT FTP (@PaulWessel)
- [x] make announcements
- [x] update links on the main site (News, Download & Documentation)

**After release**:

- [x] create branch 6.x for bug-fixes if this is a minor release (i.e. create branch 6.1 after 6.1.0 is released)
- [x] update `GMT_PACKAGE_VERSION_*` in `cmake/ConfigDefault.cmake`
- [x] comment the `set (GMT_PUBLIC_RELEASE TRUE)` line
- [x] commit changes to GitHub

**3rd-party update**

- [x] update [conda-forge feedstock](https://github.com/conda-forge/gmt-feedstock) (@leouieda, @seisman)
- [x] update [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmt.rb) (@claudiodsf, @seisman)
- [ ] update [fink package](https://github.com/fink/fink-distributions/blob/master/10.9-libcxx/stable/main/finkinfo/sci/) (@remkos)
- [x] update [macports ports](https://github.com/macports/macports-ports/tree/master/science)

---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by PaulWessel** [comment]
Was told by Wiley they are working on the galleys.  We better do rc4 as training before the real release.  I will start on the top.
Given my libcurl problem at UH, could you guys check that tests pass and check that box pelase? I will be busy until the early afternoon with other things.

**Comment by PaulWessel** [comment]
Hi @seisman, are you able to verify that tests pass and check taht box above? Also, we still dont have a changelog I think so I guess we can check that as well.  I can run tests tonight at home and then I can build the tarballs and macOS bundle as well, and give links to those for @joa-quim  to build win installers.

**Comment by seisman** [comment]
The tests are still running, see https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=2381&view=results. It may take one more hour for the Windows tests.

**Comment by seisman** [comment]
@PaulWessel There are two new failing tests on Windows, ex29 and ex39.

**Comment by seisman** [comment]
Please check the attached two zip files.
[ex29.zip](https://github.com/GenericMappingTools/gmt/files/3576954/ex29.zip) 
[ex39.zip](https://github.com/GenericMappingTools/gmt/files/3576955/ex39.zip)

**Comment by PaulWessel** [comment]
Looks OK to me. It is just switching from rainbow to turbo CPT so the images are almost entirely different, no?  Do you see anything else? I would just update the orig PS.

**Comment by seisman** [comment]
But why these two tests pass on macOS and Linux?

**Comment by PaulWessel** [comment]
Well, they both fail for me under macOS.  Perhaps the PS were not merged?

**Comment by seisman** [comment]
Running the scripts directly shows that the generated PS is different from the orig PS. Don't know why ctests didn't detect those for me.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/blob/1e4c65a071b27de5f5f7b54baf2df2bf8f665985/doc/examples/gmtest.in#L169-L173

In the gmtest script of examples, it creates symbolic links for *.bat, *.sh and *.ps. Why does the *.ps symbolic links needed?

**Comment by seisman** [comment]
I believe the *.ps symbolic links are not needed at all. I've opened the PR #1513 to address the issue. After applying PR #1513, tests ex29 and ex39 fail for me.

**Comment by PaulWessel** [comment]
This is cryptic code from Florian.  It sets up links to files in the original ex?? directory so that the script will run in the temporary build directory (some of them access local files and they would not be found).  I am pretty sure I replaced the BLOBIGNORE since it nevern worked for me on macOS and we could not figure out why.  But I agree in principle that the gm commands specifies the path to the original PS so why...

**Comment by PaulWessel** [comment]
At home I got on error in proj4.sh - presumably because macports installed goal 3.0.1 and there may be some subtle differences.  How are things on your end?

**Comment by seisman** [comment]
I have one failing test on my local mac. GMT_App_P_2.sh fails because it can't find gmt_shell_functions.sh in its local directory.

The scheduled builds reports 0 failing tests on macOS, 1 failing test (`mapproject/proj4.sh`) on Linux. The Windows tests are still running, but should be good after update the orig PS of ex29 and ex39.

**Comment by PaulWessel** [comment]
Should the line

. gmt_shell_functions.sh

instead use the source directory path? E.g.

. ${GMT_SOURCE_DIR}/gmt_shell_functions.sh

**Comment by seisman** [comment]
Yes, it should be. The test failed suddenly because I removed GMT's bin from PATH, so `. gmt_shell_functions.sh` can't find gmt_shell_functions.sh.

**Comment by seisman** [comment]
There are 11 failing and 3 timeout tests on Windows. Look good to me.

**Comment by PaulWessel** [comment]
OK, all committed so checking the box.

**Comment by seisman** [comment]
The DOI of the G3 paper is out: 10.1029/2019GC008515, although it's not activated yet. I think we can update the citation information before 6.0.0rc4 is out.

**Comment by PaulWessel** [comment]
Should we enter that now before I build the tarballs or wait for 6.0.0?

**Comment by seisman** [comment]
OK, we can wait for the 6.0.0 release.

**Comment by PaulWessel** [comment]
Tarballs and macOS bundle built:

> MD5 (gmt-6.0.0rc4-darwin-x86_64.dmg) = 752ae6d72f1d87ec8f5c98a3f00a6a9e
> MD5 (gmt-6.0.0rc4-src.tar.gz) = bdb585c07e88c81f9da205b4f9f83102
> MD5 (gmt-6.0.0rc4-src.tar.xz) = 517040d28c12d844e672cda5e7f97cce

In ftp://ftp.soest.hawaii.edu/pub/pwessel/release

**Comment by seisman** [comment]
ftp://ftp.soest.hawaii.edu/pub/pwessel/release should be ftp://ftp.soest.hawaii.edu/pwessel/release

**Comment by joa-quim** [comment]
Win installers

https://www.dropbox.com/s/qfbebkhhfq0hyo5/gmt-6.0.0rc4-win64.exe?dl=1

https://www.dropbox.com/s/8l95av3cggcnsvr/gmt-6.0.0rc4-win32.exe?dl=1

**Comment by seisman** [comment]
@joa-quim 
![image](https://user-images.githubusercontent.com/3974108/64350989-92cf2000-cfc7-11e9-96f0-63d3698df9e6.png)

**Comment by joa-quim** [comment]
Damn it, forgot to change to Release build. Restarting

**Comment by joa-quim** [comment]
OK, please try again. The links are the same but the files should have been updated.

**Comment by seisman** [comment]
@joa-quim The win32 installer works, but the win64 one still has the same problem. Can you verify that you updated the win64 installer, and also provide the md5sum value.

**Comment by joa-quim** [comment]
80ee26db5471723ea3c8a7ada5044261  .\gmt-6.0.0rc4-win32.exe
b8fcf84bbf2d5e2be0e4ff598a834b9e  .\gmt-6.0.0rc4-win64.exe

**Comment by joa-quim** [comment]
Don't get how this is happening but you are right, the one at the Dropbox is a debug build.
... rebuilding

**Comment by joa-quim** [comment]
and again

https://www.dropbox.com/s/rsrzml8rap5r7mh/gmt-6.0.0rc4-win64.exe?dl=1
e98e2f90a3d619f8bec758957e01235a  gmt-6.0.0rc4-win64.exe

**Comment by seisman** [comment]
The win64 installer works now, but the GDAL may not work well.

![image](https://user-images.githubusercontent.com/3974108/64375390-d6d81a00-cff3-11e9-87ee-8c1868e1b0d0.png)

**Comment by joa-quim** [comment]
It's getting more mysterious.

**Comment by joa-quim** [comment]
The problem is that grdinfo does not call the proj4 function that I patched, but gdal_translate does. And with all of that happening in C++ my capacity to patch is quickly draining up.

**Comment by seisman** [comment]
This is what I get on macOS. The output grid information is almost the same, except the error messages on Windows, and the `+proj=utm +zone=10 +datum=NAD27 +units=m +no_defs` on macOS.
```
$ gmt grdinfo m30dem.tif
m30dem.tif: Title: Grid imported via GDAL
m30dem.tif: Command:
m30dem.tif: Remark:
m30dem.tif: Gridline node registration used [Cartesian grid]
m30dem.tif: Grid file format: gd = Import/export through GDAL
m30dem.tif: x_min: 532950.13 x_max: 577290.13 x_inc: 30 name:  n_columns: 1479
m30dem.tif: y_min: 4149809.82 y_max: 4205669.82 y_inc: 30 name:  n_rows: 1863
m30dem.tif: z_min: -32768 z_max: 785 name: z
m30dem.tif: scale_factor: 1 add_offset: 0
+proj=utm +zone=10 +datum=NAD27 +units=m +no_defs
```

**Comment by PaulWessel** [comment]
And this is gdal 3.0.1 (June 28, 2019)?

**Comment by seisman** [comment]
I'm using gdal 2.4.2.

**Comment by seisman** [comment]
grdimage can plot the tif file correctly and it also reports errors.

**Comment by PaulWessel** [comment]
@joa-quim, what is your GDAL version? Might it help to install an older one (assuming you are doing GDAL 3)?  We aren't using curring edge GDAL anyway, no?

**Comment by joa-quim** [comment]
I am using GDAL master (I always do). But the issue,  I think, is related to the fact that on Win I'm trying to have GDAL+proj bundle

**Comment by joa-quim** [comment]
OK, here is what I think I learned so far.
- In gmt_init I set an option to to tell gdal to also search for its needs files (PLUS those of proj4) in share/GDAL_DATA. This used to work fine (see bellow).
- but gdal_translate (and others) know nothing about this alternative location and proj has a fall back mechanism to search ``proj.db`` under (proj's) bin/../share/proj. This seems to have been made for the case where proj is build locally. It was this mechanism that I patched to also look for ``prod.db`` in the GMT share dir. But because I intended to submit a PR to proj, I moved the proj's parameter files in GMT from share/GDAL_DATA to share/proj. But this means that gdal functions called from GMT (the grdinfo example) will no longer be able to find ``proj.db`` because it now lives in share/proj and not share/GDAL_DATA

The obvious solution is to put back everything  in share/GDAL_DATA but then I have no courage to ask proj4 people to accept my patch.

What do you think? Shell I make just now to solve this dead end and move on with rc4?

**Comment by PaulWessel** [comment]
Because this is the Win installer only I think any solution you can think up that works for users is fine.  It does seem like you will eventually need to work with the proj folks to solve this in a reasonable manner.

**Comment by joa-quim** [comment]
For now it's Windows only but I think you'll face the same issue if you want to make fully self contained GMT+GDAL+PROJ4.
Be cause I'm tiered of this, I'll put back everything in GDAL_DATA.

**Comment by joa-quim** [comment]
Found a much obvious (not for a while) solution. I can tell GMT to to tell GDAL to look into TWO directories. So we can keep ``share/GDAL_DATA`` and ``share/proj``.

@seisman please try this while I rebuild the 32 bits
https://www.dropbox.com/s/rsrzml8rap5r7mh/gmt-6.0.0rc4-win64.exe?dl=0

feac4ebf65b98a48d69d59b93ff85831  gmt-6.0.0rc4-win64.exe

**Comment by seisman** [comment]
The 64-bit installer works.

**Comment by joa-quim** [comment]
Fine(ally). And the 32-bits

https://www.dropbox.com/s/vgf68rl45k2008r/gmt-6.0.0rc4-win32.exe?dl=0
b00d75fe393abc5222e450b58b8fface  gmt-6.0.0rc4-win32.exe

**Comment by seisman** [comment]
I compiled the source package, and tested the macOS bundle and Windows installers. They all work well. For #1522, I think we can merge it into 6.0, then @PaulWessel can rebuild the tarballs and bundle. No need to rebuild the Windows installers for @joa-quim.

**Comment by PaulWessel** [comment]
Revsied tarballs and macOS bundle built after merging #1522:

> MD5 (gmt-6.0.0rc4-darwin-x86_64.dmg) = 563e93978731d888dbf6ef044839c27e
> MD5 (gmt-6.0.0rc4-src.tar.gz) = 4f0885ac9bcd13b2790ec354d7e73d35
> MD5 (gmt-6.0.0rc4-src.tar.xz) = a2d25de23c27c28c572705b3e4b21948

In ftp://ftp.soest.hawaii.edu/pwessel/release

**Comment by seisman** [comment]
Tested again and all are good.

**Comment by seisman** [comment]
@PaulWessel I'll do the tag and release tasks if you think it's OK.

**Comment by PaulWessel** [comment]
Yes, please I think we are good to go.

**Comment by seisman** [comment]
Done in https://github.com/GenericMappingTools/gmt/releases/tag/6.0.0rc4. Unlike previous releases, I uploaded a gmt-6.0.0rc4-checksums.txt which lists the sha256sums of the 5 packages. 

The reasons are:
1. md5sum is known to be insecure. sha256 is more secure.
2. sha256sum is needed by other package managers, e.g. homebrew, macports, and conda

Let me know if you prefer md5sum instead.

**Comment by PaulWessel** [comment]
No, I have no opinion on this.  On macOS we can use shasum -a 256.  We should then modify admin/build-release.sh to use shasum instead.

**Comment by PaulWessel** [comment]
I think I have done all the steps I can.  The rest of the shopping list has to do with packaging, so @seisman and @leouieda may wish to do this now before we do it all again with 6.0.0.

**Comment by seisman** [comment]
The [conda-forge build](https://github.com/conda-forge/gmt-feedstock/pull/79) is ready, after applying the patches in #1527 and #1528. It's waiting for approval.

I also tested the homebrew recipe for 6.0.0rc4 locally, and it works fine.

**Comment by seisman** [comment]
I've submitted a new port [gmt6](https://github.com/macports/macports-ports/pull/5225) for macports, and is waiting for feedbacks and approval.

@remkos Maybe we can have a gmt6 fink package?

**Comment by seisman** [comment]
The conda-forge package is ready.

**Comment by claudiodsf** [comment]
Hi, not sure why the homebrew formula checkbox is checked.

Anyway, I'll probably skip making a formula for rc4, since the homebrew maintainer prefers to wait on final release.

See this comment: https://github.com/Homebrew/homebrew-core/pull/41119#issuecomment-513593029

**Comment by claudiodsf** [comment]
On a second thought, I can still push a formula to my homebrew fork 😉 

So, if you're interested in testing rc4 installation via homebrew, you can do:

```
brew install https://raw.githubusercontent.com/claudiodsf/homebrew-core/GMT6.0.0/Formula/gmt.rb
```

**Comment by seisman** [comment]
@claudiodsf I tested homebrew with rc4 locally, and it worked well for me. So I checked the checkbox.
