### ISSUE TITLE
Pack graphicsmagick in the Windows installers?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1472]
GMT needs the **gm** command provided by graphicsmagick to make movies in GIF format. Is it feasible to also pack **gm** in the Windows installers?

**Comment by PaulWessel** [comment]
Yes, if we want the Windows installer to have everything it needs gs, gdal_translate, ogr2ogr, ffmpeg, gm.

**Comment by joa-quim** [comment]
Doesn't seem practicable. GraphicksMagic has some 130 dll and is still build with VS 6.0 (15 years?) compiler.

**Comment by PaulWessel** [comment]
So perhaps not possible.  Do we close this issue and just spell out run-time requirements for WIndows in addition to what the installer adds somewhere?

**Comment by joa-quim** [comment]
Yes, close this.
