### ISSUE TITLE
Error message "Cannot find proj.db" on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1475]
The issue was originally reported by @zhaozhiyuan1989.

**Description of the problem**

Use the gdal_translate shipped with the GMT installer, to convert a tif grid to netCDF format. The gdal_translate command generates the netCDF file successfully, but is also reports some errors. Please see the attached screenshot below.

![image](https://user-images.githubusercontent.com/3974108/64065569-14e0d280-cbdd-11e9-9cde-6b68851473d4.png)

**System information**

* Operating system: Windows
* GMT version (`gmt --version`): 6.0.0rc3

![image](https://user-images.githubusercontent.com/3974108/64065553-f24eb980-cbdc-11e9-9714-f416a107184b.png)

**Comment by joa-quim** [comment]
Hmm, cannot reproduce this. Works fine for me
```
C:\v>where gdal_translate
C:\programs\gmt6\bin\gdal_translate.exe

C:\v>gdal_translate -of GMT lixo.tiff lixo.nc
Input file size is 512, 512
```
Is the ``proj.db`` really not present in ``share/GDAL_DATA``?

And, BTW, you probably do not want to do ``-of GMT`` that's the old, old (GMT3) GMT netCDF format.

**Comment by seisman** [comment]
Yes, the `proj.db` is in `share/GDAL_DATA`.

Do you set the environmental variable `PROJ_LIB` manually? How does gdal or proj know to find the proj.db file in GMT's share/GDAL_DATA?

**Comment by joa-quim** [comment]
All is done automatically. See ``gmt_init.c`` line 15083.
So do you have a ``PROJ_LIB`` set and pointing to an older proj4 install?

**Comment by seisman** [comment]
> So do you have a `PROJ_LIB` set and pointing to an older proj4 install?

No, I didn't set `PROJ_LIB`.

**Comment by joa-quim** [comment]
OK, I'm being dumb. This is a pure GDAL call so it must know where ``proj.db`` is located. From within GMT the code that I pointed takes care of that, but ``gdal_translate`` knows nothing about it. So ``PROJ_LIB`` must be set manually. However, I still didn't figure out how in my machines it does manage to find the ``proj.db`` that I have in proj4 build dir. And that even without a ``PROJ_LIB`` being set.

**Comment by joa-quim** [comment]
@seisman Can you try to make a copy of ``share/GDAL_DATA`` and rename it to ``share/proj`` to see if that's a magic name?

**Comment by seisman** [comment]
> @seisman Can you try to make a copy of `share/GDAL_DATA` and rename it to `share/proj` to see if that's a magic name?

No, it doesn't work.

**Comment by joa-quim** [comment]
Yep, just found it too. And also found why it works for me. The bloody thing things it's a Mac and saves the original address of the ``proj.db`` file inside the dll. See image of a bin dump. That's how it finds the file, but that's very stupid because only works at the building machine.


![Annotation 2019-09-02 192655](https://user-images.githubusercontent.com/537321/64130053-c0de1580-cdb7-11e9-9660-5969ed1f66c2.png)

**Comment by seisman** [comment]
Can the installer set PROJ_LIB to GMT's share/GDAL_DATA during installation?

**Comment by joa-quim** [comment]
Even if yes (which I assume it's possible) it would not be a good solution because potentially break a previous ``PROJ_LIB`` setting.

**Comment by joa-quim** [comment]
I think I managed to solve this but it involved patching proj4 (that now has moved to the dark side (C++)). Testing will have to wait until RC4 installer.

**Comment by seisman** [comment]
I may give it a try if you can build a installer before rc4.

**Comment by joa-quim** [comment]
Ok, you can try [this one](https://www.dropbox.com/s/0lpk3xs3ttt3ael/gmt-6.0.0_2019.09.03-win64.exe?dl=0). It has also ghostscript. I tried to add a new entry on the installer to make it optional by replicating the same logic of ``GDALDATA`` in ``cmake\dist\CMakeList.txt`` but don't understand why it doesn't show up. This point is very important if we want to put it in the official installer. One of the Artifex conditions is 
``The end user has the ability to opt out of installing the AGPL version of our products during the install process.``

**Comment by seisman** [comment]
@joa-quim I got this error:
![image](https://user-images.githubusercontent.com/3974108/64177856-54522d80-ce2e-11e9-9cf6-3f8394907880.png)

**Comment by joa-quim** [comment]
Shit. That's a cpack job to put in installer. I also had troubles with lapack and did not include it. This is all in the new laptop. Please approve #1487 so that can try in the old machine.

**Comment by joa-quim** [comment]
Please try again with [this](https://www.dropbox.com/s/aq11nyseay11h6i/gmt-6.0.0_f26fdfe_2019.09.03-win64.exe?dl=0). You can also test if the ghost works or not (ofc it will)

**Comment by seisman** [comment]
Surprised to see that gmt, gdal_translate and also ghostscript (tested by generating a PDF image) all work as expected.

**Comment by seisman** [comment]
Maybe this issue can be closed? @joa-quim

**Comment by joa-quim** [comment]
Yes. It may come back because my proj4 patch only makes it find ``proj.db`` and not the rest of the files in the PROJ_LIB dir. But we'll see when/if that comes out.
