### ISSUE TITLE
Can not install the softwere

### ISSUE THREAD

**Issue by Sonny-19** [GenericMappingTools/gmt#1482]
Hi there. 
I was trying to install the software, but the file ask for a username and password. I have already opened an account but the software is not taking the username and password. Probably this issue is written in the github wiki page. Can you please solve the issue?
My user name : Sonny-19
Email: fatimatuj.sonny@gmail.com
Full name:  Fatimatuj Zohara Sonny

**Comment by joa-quim** [comment]
Sonny, our installers do not ask user/password. What _software_ are you referring to? And what operating system?

**Comment by Sonny-19** [comment]
I have downloaded gmt-6.0.0rc3-win64.exe file. as this one is newest version.

**Comment by joa-quim** [comment]
Hm, I think it's Windows that is asking for the username and passw. It might mean that you are trying to install in a computer where you have no permissions to do it and Win is asking for an administrator login.
If that's the case, it's not on purpose on our side but it's strange that this issue has never been brought to out attention before.

**Comment by seisman** [comment]
@Sonny-19 It would be better if you can provide a screenshot when the installer asks for your username and password.

**Comment by Sonny-19** [comment]
yes the problem was in my work computer. it has restriction on installing any software. I finally managed to install it in my laptop. thanks everybody to help me. and sorry to bother you.
