### ISSUE TITLE
Possibly issues in our use of libcurl?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1491]
**Description of the problem**

Some of the remote data access and inquiries fail if one is located inside the U of Hawaii firewall.  It works for users on the outside (which is the vast majority of users).

**Full script that generated the error**

```
pwessel@macnut:~/GMTdev/gmt-dev/dbuild-> rm -f ~/.gmt/cache/ship_15.txt
pwessel@macnut:~/GMTdev/gmt-dev/dbuild-> gmt info @ship_15.txt
gmtinfo [ERROR]: Unable to down file http://oceania.generic-mapping-tools.org/gmt_md5_server.txt
gmtinfo [ERROR]: Libcurl Error: Failure when receiving data from the peer
gmtinfo [ERROR]: Failed to get remote file http://oceania.generic-mapping-tools.org/gmt_md5_server.txt
gmtinfo [ERROR]: Libcurl Error: Failure when receiving data from the peer
gmtinfo [ERROR]: File ship_15.txt not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
```

Looking in gmt_remote.c I see we use curl_easy_setopt to pass settings to curl before the access is attempted.  For instance, we use curl_easy_setopt (Curl, CURLOPT_FOLLOWLOCATION, 1L) to make sure curl will follow redirects.  However, there are places, such as in the function skip_large_files where we do not set that parameter.  I wonder if such inconsistencies are partly to blame.  Should we not always allow for redirects?

**Comment by seisman** [comment]
Do the curl CLIs work for you?
```
curl http://oceania.generic-mapping-tools.org/gmt_md5_server.txt
curl -L http://oceania.generic-mapping-tools.org/gmt_md5_server.txt
```

**Comment by PaulWessel** [comment]
No, everybody at UH gets curl: (56) Recv failure: Connection reset by peer

The SOEST IT staff verified that it works fine from the outside.  Since it fails both inside the SOEST network (i.e., for me) as well as outside SOEST but inside UH they believe it may be related to the UH firewall and not the SOEST firewall.  I have a request with UH IT staff about this so we will see.

**Comment by PaulWessel** [comment]
I think we should call curl_easy_setopt (Curl, CURLOPT_FOLLOWLOCATION, 1L) when trying to determine the remote file size.  It cannot find the file if we are not allowing redirection, no?

**Comment by seisman** [comment]
I don't see any harm in allowing redirection, so yes from me.

**Comment by PaulWessel** [comment]
Should we be using https: for the data servers?

**Comment by seisman** [comment]
I think we can have both http and https, and use https as the default.

**Comment by seisman** [comment]
Close this issue?

**Comment by PaulWessel** [comment]
Yes, if it still works fine for you and now me then we are good.
