### ISSUE TITLE
gmt end show in movie's main script

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1498]
For movie module, main script ending with `gmt end show` causes some troubles, as GMT may try to open lots of files or open some deleted files. Is it possible to check if there is a **show**?
If yes, we may change it to `gmt end`.

**Comment by PaulWessel** [comment]
That is a good idea, I will add that check.  show postdates movie.c...

**Comment by PaulWessel** [comment]
See latest PR in #1497.

**Comment by seisman** [comment]
Closed by #1497.

**Comment by seisman** [comment]
After #1621, it seems we can always add "export GMT_END_SHOW=off" to movie's scripts and no longer need to check "gmt end show".

**Comment by PaulWessel** [comment]
True, but already implemented and saves you from adding that export statement to all movie scripts.  I think this is a good feature to have in movie.c.

**Comment by seisman** [comment]
OK.
