### ISSUE TITLE
movie should use \r\n as the newline character for generated batch script

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1499]
@liuzhumei found another weird issue with the movie module. She ran the example in the movie manpage using CMD.

This is a screenshot of the generated movie_frame.bat script. It looks correct:

![image](https://user-images.githubusercontent.com/3974108/64225033-b438ea80-cea7-11e9-89f5-da5ed83b2814.png)

But the gmt movie command gives weird errors:

![image](https://user-images.githubusercontent.com/3974108/64225155-31645f80-cea8-11e9-88a4-b53365ff2715.png)

It turns out the batch script generated by **movie** sometimes uses LF as the newline character:
![image](https://user-images.githubusercontent.com/3974108/64225142-26113400-cea8-11e9-8dce-bb6b01784dc5.png)

I suspect the weird errors are caused by the misuse of LF and CRLF.

**Comment by PaulWessel** [comment]
Did you not say that all the movie examples run in the CI under Windows? I take it that was git bash (so more UNIX like and LF is OK) and not batch then? If I google I find this: https://softwareengineering.stackexchange.com/questions/29075/difference-between-n-and-r-n which says \n actually writes CRLF under Windows, but that is not what happens above.  I though compilers took care of this for us so that we dont have to actually set a cariable to LF or CRLF depending on OS...

**Comment by seisman** [comment]
We only run the **bash scripts** in our Windows CI using git-bash, and they all run fine. For batch scripts, there are no tests at all. Not sure what happens here. @liuzhumei is using the latest Windows installer provided by @joa-quim in #1475.

**Comment by seisman** [comment]
The last figure shows mixed LF and CRLF. The figure may be a little misleading, as @liuzhumei may have modified a few lines for debugging.

**Comment by PaulWessel** [comment]
I suspect this: I read in a line including line feed.  Normally in GMT we then strip off the CRLF with gmt_chop, and then fprintf with "%s\n".  I suspect this behaves differently than just printing "%s" when there is a \n in the string.  That \n won't be expanded to \r\n but the explicit \n in the FORMAT statement might.  Could we think of a short 3line C program to test this idea before I add all those gmt_chop calls to movie?  I gotta drive home so cannot do it right away.  We may want to get the original input script that  @liuzhumei used as input to check.

**Comment by seisman** [comment]
Please see the attached zip file provided by @liuzhumei 

[testMovie.zip](https://github.com/GenericMappingTools/gmt/files/3572879/testMovie.zip)

**Comment by PaulWessel** [comment]
Maybe tomorrow you can compile and run this file (dump.c) under Windows:

```
#include <stdio.h>
int main () {
	char line[250] = {""};
	while (fgets (line, 250, stdin))
		printf ("%s", line);
}
```

and and run this command on Windows with her globe.bat file:

dump < globe.bat > new.bat

and then on Linux run od -c new.bat to see if it is still CRLF or just LF.

**Comment by PaulWessel** [comment]
@joa-quim, maybe you know the answer to this: Do I need to strip off those CRLF and then use printf ("%s\n", line) to get those CRLF in the output?

**Comment by joa-quim** [comment]
I wouldn't think we do.
Anyway your dump shows that globe.bat and new.bat are exactly equal. That is CRLF maintains.
And for me the movie worked, although it printed this at the end
```
...
        1 file(s) moved.
        1 file(s) moved.
Invalid switch - "movie_init.bat".
Invalid switch - "movie_frame.bat".
movie [ERROR]: Running cleanup script movie_cleanup.bat returned error 1 - exiting.
```

**Comment by joa-quim** [comment]
The problem with ``movie_cleanup.bat`` is that it does
```
del globe/movie_init.bat
```
but in this case it has to use a backslash
```
del globe\movie_init.bat
```
Never fully understood when backslashes are mandatory.

**Comment by joa-quim** [comment]
Instead of creating a ``movie_cleanup`` script shouldn't ``movie`` take care of doing the cleanup itself?

**Comment by seisman** [comment]
I tried it in my Windows 10, and the movie works and I have the same issue with @joa-quim.
```
...
        1 file(s) moved.
        1 file(s) moved.
Invalid switch - "movie_init.bat".
Invalid switch - "movie_frame.bat".
movie [ERROR]: Running cleanup script movie_cleanup.bat returned error 1 - exiting.
```

It seems we can't reproduce the bug reported by @liuzhumei.

**Comment by joa-quim** [comment]
Can Windows handle this?
![Capture](https://user-images.githubusercontent.com/537321/64242059-c85b0700-cefc-11e9-91a1-a8f796f3f35c.JPG)

**Comment by PaulWessel** [comment]
I can understand that when we write commands for DOS we must use the backslash in directory names.  The rest (CF, CRLF etc) seems very odd and apparently not reproducible.

**Comment by joa-quim** [comment]
We have been here before (slash vs backslash) and ended up always using slashes because it eased to solve a problem we had at the time. We can use slashes to build paths and can cd to it but running some dos commands (del in present case) need to have a backslash. I'll make a PR that solves current issue.

**Comment by PaulWessel** [comment]
Programmatically in C we can use slashes (internal paths passed to fopen, etc), but we cannot write out slashed paths and expect them to work in DOS.  We CAN do it when setting GMT_DATA_DIR since those are read back in and used programmatically,.

**Comment by joa-quim** [comment]
Some dos commands work with both
```
C:\v>cd build14/src

C:\v\build14\src>
C:\v\build14\src>cdv

C:\v>cd build14\src

C:\v\build14\src>
```

**Comment by PaulWessel** [comment]
I am glad they decided that inconsistency is the way to go.

**Comment by PaulWessel** [comment]
Can this be closed now?

**Comment by seisman** [comment]
I think it's OK to be closed, as we cannot reproduce the issue.

**Comment by liuzhumei** [comment]
Thanks to @seisman 's reminder, the Chinese characters in the `GMT_DATADIR` path caused the failure of the `movie` execution. Change Chinese path to English, `moive` module can be executed normally.
