### ISSUE TITLE
gmt clear only in modern mode?

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#1501]
Isn't ``gmt clear history`` and ``gmt clear conf`` supposed to work in *old* mode anymore?

```
$ gmt clear conf
clear [ERROR]: Target "defaults" is only valid in a modern mode session
$ gmt clear history
clear [ERROR]: Unrecognized target history - skipped
clear [ERROR]: No clear target given
```

**Comment by PaulWessel** [comment]
clear is used to delete _hidden_ files in the hidden session directory.  if you want to delete gmt.conf beneath your feat you an do rm -f gmt.conf, etc.

**Comment by PaulWessel** [comment]
This is what happens when you go on these lengthy vacations.

**Comment by abanbj** [comment]
I see. I've been using it for *visible* files (e.g. gmt.conf in local dir) for a long time. Oh well.

**Comment by abanbj** [comment]
You're totally right, Paul. I apologize my absence, ignorance and insolence.

**Comment by PaulWessel** [comment]
Oops, I actually thought this was @joa-quim and hence the harsh treatment!  You are right it used to work as you describe but until 6.0.0 is released it is all beta.  We decided we don't need a command to delete a file in the current directory.

**Comment by abanbj** [comment]
All good!
