### ISSUE TITLE
segfault in new surface -M option

### ISSUE THREAD

**Issue by HamishB** [GenericMappingTools/gmt#1511]
Hi, passing this along from one of our users. I thought he had installed it in MS Window 7 but the backtrace shows /usr/local so I'm not sure, maybe it's Ubuntu 16.04.
```
I try to run this gmt surface command using GMT version 6.0.0_r20495

"gmt surface $file-median1 -G$output -I$spacing -R$region -T0.4 -M20c -V"

the surface command runs without problems when the -M option is not
used. As soon as I try to use -M this error message appears:

ERROR: Caught signal number 11 (Segmentation fault) at
/usr/local/lib/libgmt.so.6(GMT_surface+0xa7a)[0x7f1b6d13588a]
[0x7f1b4cfb9000]
Stack backtrace:
/usr/local/lib/libgmt.so.6(sig_handler+0x2b1)[0x7f1b6cef69b1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f1b6ccb4390]
/usr/local/lib/libgmt.so.6(GMT_surface+0xa7a)[0x7f1b6d13588a]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0xc0)[0x7f1b6cf0c730]
gmt(main+0x60d)[0x4012cd]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f1b6c8f9830]
gmt(_start+0x29)[0x401759]
```

**Comment by PaulWessel** [comment]
I canot reproduce that with some other data examples.  If you can, please post the input file and the actual command (i.e., spell out the -R -I etc arguments) and we can try with that case.  surface basically calls grdmask when -M is given, so try to see if

`gmt grdmask $file-median1 -I$spacing -R$region -S20c -NNaN/1/1 -Gmask.grd
`

runs without crashing.

**Comment by PaulWessel** [comment]
Closing this for lack of feedback and reproducibility.  Please reopen if you wish to add more feedback.
