### ISSUE TITLE
Nicer plots in earlier versions?

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#1520]
I'm scratching my head trying to figure this out. The two attached plots are made up of exactly the same data (except for the circles) and same script. *old_and_sweet.png* was made on 26.09.2017 and *new_and_messy.png* today (05.09.2019). 

The former has a better look in my opinion, with crisp and sharp lines. The latter looks more messy, and the lines appears more smeared out (aliasing?). So I was wondering, has the drawing routine changed since 2017? What could be the cause of this?

PS! I know this is not a bug, but thought this was the best place to post it.

![old_and_sweet](https://user-images.githubusercontent.com/29237824/64362625-21b35b00-d00f-11e9-9fe7-0d025c2a99ca.png)
![new_and_messy](https://user-images.githubusercontent.com/29237824/64362624-21b35b00-d00f-11e9-8ae4-8558cbdf009d.png)

**Comment by PaulWessel** [comment]
You are probably seeing evolutions in ghostscript.  There are no fundamental changes to how we draw PostScript over the years.  Are you able to compare the two PostScript files? That would be the real comparison.  You could then convert to PNG and see if the latest gs gives a different picture.  It is also possible that gs does something different when there are color (your circles) versus when there is only 1-bit black white.

**Comment by abanbj** [comment]
Unfortunately, I only have the PNG from 2017, so cannot compare the PostScript files. Maybe I could reinstall an old version of gs and check. Also, I've made this figure (messy version) with circles and color, so I dont think tahts the problem. Thanks for good ideas and comment, Paul.

**Comment by PaulWessel** [comment]
gs 9.28 rc2 is being tested.  We found several bugs in 9.27 as well as 9.28rc1 so gs is a moving target.  We have never had as many issues with them as the last few years...
PS. Nice GMT figures!

**Comment by abanbj** [comment]
Thanks! You can create lots of nice stuff when you have the perfect tool.

OK, so I did a test on Windows. Downloaded latest gs (9.27), installed, ran my script. Looks **good** (like the 2017-version). Checked which version of gs that I use in Ubuntu , which was 9.26. This is the version that gives the messy one. Uninstalled 9.27 and installed 9.26 on Windows. Still, looks good. Why!? Is Windows vs. Linux the issue here? This is strange.

**Comment by joa-quim** [comment]
This looks like a resolution type thing. It's as if the poor one was rasterized a much lower resolution.

**Comment by abanbj** [comment]
I agree joaquim. Could ``psconvert`` be the culprit?

**Comment by joa-quim** [comment]
psconvert _just_ calls ghostscript to do the conversion. You can check that it's doing the same thing on Win vs Linux by making it print the gs command (option -S, I think).

**Comment by PaulWessel** [comment]
Maybe they patched 9.26 on windows, just like they patched 9.27 on macports but not fink (yet).  Who knows.  But not a psconvert problem.

**Comment by abanbj** [comment]
Okay, progression. I ran the script on Windows and Ubuntu with an added ``-S..`` to ``psconvert`` to see what's going on. This is the gs command on Windows:

```
gswin64c.exe
-q 
-dNOPAUSE 
-dBATCH 
-dPDFSETTINGS=/prepress 
-dDownsampleColorImages=false 
-dDownsampleGrayImages=false 
-dDownsampleMonoImages=false 
-dUseFlateCompression=true 
-dEmbedAllFonts=true 
-dSubsetFonts=true 
-dMonoImageFilter=/FlateEncode 
-dAutoFilterGrayImages=false 
-dGrayImageFilter=/FlateEncode 
-dAutoFilterColorImages=false 
-dColorImageFilter=/FlateEncode 
-dSCANCONVERTERTYPE=2 
-dMaxBitmap=2147483647 
-dUseFastColor=true 
-sDEVICE=pngalpha  
-g710x915 
-r300 
-sOutputFile="test.png" 
-f"./psconvert_10544d.eps"
```

And this is the gs command on Ubuntu

```
gs 
-q 
-dNOPAUSE 
-dBATCH 
-dNOSAFER 
-dSCANCONVERTERTYPE=2 
-dMaxBitmap=2147483647 
-dUseFastColor=true 
-dGraphicsAlphaBits=2 
-dTextAlphaBits=4 
-sDEVICE=pngalpha  
-g709x915 
-r300 
-sOutputFile='test.png' 
'./psconvert_879d.eps'
```

I then copied the Windows gs command and ran that on Ubuntu. And what do you know. Crisp and clear figure. Why does psconvert (or gs?) issue different commands depending on if you're on Windows or Linux?

**Comment by PaulWessel** [comment]
It doesn't.  What gmt version is this? If it is what ubuntu ships then it is ancient.  Did you build it yourself from source?

**Comment by PaulWessel** [comment]
Meaning: The same GMT version of psconvert runs exactly the same gs command. But an older psconvert will run whatever we decided to do in the past.

**Comment by abanbj** [comment]
I just built a GMT version from sometime in September 2017 and ran the script. Here the issued gs command from psconvert is

```
psconvert [L-1]: gs 
-q 
-dSAFER 
-dNOPAUSE 
-dBATCH 
-dPDFSETTINGS=/prepress 
-dDownsampleColorImages=false 
-dDownsampleGrayImages=false 
-dDownsampleMonoImages=false 
-dUseFlateCompression=true 
-dEmbedAllFonts=true 
-dSubsetFonts=true 
-dMonoImageFilter=/FlateEncode 
-dAutoFilterGrayImages=false 
-dGrayImageFilter=/FlateEncode 
-dAutoFilterColorImages=false 
-dColorImageFilter=/FlateEncode 
-dSCANCONVERTERTYPE=2 
-dMaxBitmap=2147483647 
-dUseFastColor=true 
-sDEVICE=pngalpha  
-g710x915 
-r300 
-sOutputFile='test.png' 
-f'./psconvert_4751d.eps'
```
```

**Comment by abanbj** [comment]
Ah, of course. Sorry. My Ubuntu GMT is super fresh, built from source. Windows version: 5.4.5.

**Comment by PaulWessel** [comment]
Hm, so perhaps one or both of 

-dGraphicsAlphaBits=2 
-dTextAlphaBits=4 

are causing problems?  You like the result better when those are not used, right?  Try leaving these out, or just one of them, etc. to see if that is the culprit.

**Comment by abanbj** [comment]
So the ``gs`` command that ``psconvert`` is running has been changed (at least since 5.4.5 and 6.0.0 in September 2017), right? Why?

**Comment by abanbj** [comment]
Removing ``-dGraphicsAlphaBits=2`` did the trick.

**Comment by PaulWessel** [comment]
We were told by ghostcript developers that many of our settings that pertained to PDF have no effect on PNG, etc.  Also, we did some experiments with the AlphaBits as well that showed these settings where the best.  You can control then with -Q.  Please post your PS so we can give it a test.

**Comment by abanbj** [comment]
Three runs

```
$ gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -sDEVICE=pngalpha -g1400x1400 -r300 -dTextAlphaBits=4 -sOutputFile='only_text_alphabits.png' 'alphabits_test.ps'

$ gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -sDEVICE=pngalpha -g1400x1400 -r300 -dGraphicsAlphaBits=2  -sOutputFile='only_graphics_alphabits.png' 'alphabits_test.ps'

$ gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -sDEVICE=pngalpha -g1400x1400 -r300 -sOutputFile='no_alphabits.png' 'alphabits_test.ps'
```
Including ``TextAlphaBits`` doesnt seem to matter. Removing ``GraphicsAlphaBits`` creates the crisp plot that I was looking for.

[alphabits_test.zip](https://github.com/GenericMappingTools/gmt/files/3581089/alphabits_test.zip)

**Comment by PaulWessel** [comment]
Note you are trading stair-stepping curves (crisp) versus sub-pixeling with gray (blurry) to make the line look straight and not broken (crips).  I think different users may differ as to what they prefer, hence we made the -Q option.  Of course, unless you are forced to make a raster you should avoid that altogether and stick with PDF.  I did a big review of all this and I thought I posted it in the old wiki under devel but now I cannot find it - annoying.

**Comment by abanbj** [comment]
Never thought about the -Q option. Thank you so much for your help, Paul. I'll close this one.
