### ISSUE TITLE
What should gmt --show-doi return?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1525]
We have added gmt --show-doi and anticipate it will return the DOI of the most relevant/recent release source tarball, right?  Do we expect it to be just

xx.yyyy/asdfasdfasdf

or do we expect it to be a real link like

http://dx.doi.org/xx.yyyy/asdfasdfasdf

I assume gmt --show-citation will output the full reference to the G-cubed paper, including its (separate) DOI.

Slightly related, do we want

gmt docs reference (or similar)

to actually open the published open access PDF for the user?  of should this feature be done via gmt --show-reference (doing a call to gmt docs)?

**Comment by seisman** [comment]
> We have added gmt --show-doi and anticipate it will return the DOI of the most relevant/recent release source tarball, right? 

Yes.

> Do we expect it to be just xx.yyyy/asdfasdfasdf or do we expect it to be a real link like
> http://dx.doi.org/xx.yyyy/asdfasdfasdf

I prefer a real link so that I can open it with a single-click.

> I assume gmt --show-citation will output the full reference to the G-cubed paper, including its (separate) DOI.

Yes, and the AGU style also uses http://dx.doi.org/xx.yyyy/asdfasdfasdf instead of doi: xx.yyyy/asdfasdfasdf


> Slightly related, do we want
> 
> gmt docs reference (or similar)
> 
> to actually open the published open access PDF for the user? of should this feature be done via gmt --show-reference (doing a call to gmt docs)?

`gmt --show-citation` already outputs the URL of the paper, do we really need another one to just open the website.

**Comment by PaulWessel** [comment]
OK, good feedback, we will do the DOI as a link and not do any reference pop-ups.
