### ISSUE TITLE
grdraster problem in 5.4.4, where is grdraster in GMT 6?

### ISSUE THREAD

**Issue by dwcaress** [GenericMappingTools/gmt#153]
The MB-System program mbgrid has a longstanding capability to underlay a bathymetry or topography grid with  a global  or  regional topography model extracted using grdraster. With GMT 5.4.4 this capability is broken.

The problem is that grdraster is requiring the -Iincrement option when it used to use the increment defined in the source global model by default. For instance, the command

   % grdraster 28 -R-13.775815/-13.702018/53.549101/53.588000 -Gtmpgrdraster11839.grd

just yields the error message:

    grdraster: No increment given and no -I in effect.  Cannot initialize new grid

I tried to see if this is still an issue in the current code. However, when I cloned gmt-master, I no longer find grdraster defined anywhere in the codebase. Am I missing something, or is grdraster disappearing?

I'm working on MacOs 10.13.06.

**Comment by joa-quim** [comment]
Dave,
From memory (mine) and references in the Changes file, the grdraster functionality has been integrated in core but I've not been able to find more info about it.

**Comment by seisman** [comment]
It seems grdraster is deleted in commit https://github.com/GenericMappingTools/gmt/commit/199e1606af0327969ec9acdf89a974fa1d9d191e.

**Comment by PaulWessel** [comment]
We decided that grdraster could be removed as nobody has non-grids they want to use with that program anymore (we used to have these in the late 1980s and early 1990s.  It is easier now for users to just say 

 gmt grdcut @earth_relief_30s -R-13.775815/-13.702018/53.549101/53.588000 -Gtmpgrdraster11839.grd

to get (for instance) a chunk of the 30 arc sec SRTM+.  If the user does not have it then it gets downloaded to their GMT data cache automatically.  What is your grid # 28 Dave?

**Comment by PaulWessel** [comment]
I am talking GMT 6.  grdraster is still in GMT 5.4.x. I dont remember making any changes to require -I.

**Comment by PaulWessel** [comment]
Dave, could you share your grdraster.info file and I can have a look as to why 5.4.4 is not getting your -I.

**Comment by PaulWessel** [comment]
Fixed in PR #155.  Dave, let me know if your background grid is something you maintain or if it is one of the standard global grids.  If the latter then the remote grid option in grdcut should be better for you.

**Comment by PaulWessel** [comment]
Closing this issue due to lack of follow-up.
