### ISSUE TITLE
Visualize PS files on Windows

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1532]
We will have an issue here because Artifex drop _gsview_. While for the time being it's still possible to google up some alternative location of it, that's not a liable solution. And furthermore we now ship gswin64c.exe but no PS previewer. So, if _regular_ new user wants to visualize a PS file, either directly, or via ``gmt end show`` he/she will come to us saying it's not working.

We can (I think) host a copy of the gsview6 (I prefer gsview5 but it doesn't work on my new laptop), but that's messy because without an officially installed gs the viewer won't work because it also finds the gs.dll via registry and not via system path.

What we can do to help minimizing the hassle of this not pretty situation is to provide a way to show up a PS figure. Note that it can be done by typing ``gswin64c file.ps`` but who will remember that? A possibility that I thought is to use ``psconvert`` to this purpose. Letters are now almost all taken, but we can add a ``psconvert file.ps -N`` to just display the PS file. And talking about this, it would be nice if ``psconvert`` could show up the result of the conversion like ``gmt end show`` does. The idea is that we should be able to combine these two functionalities in the same option.

**Comment by PaulWessel** [comment]
Hm, several issues here.  One seems to be that Windows is not a very friendly place for PostScript.  That is a long-held MicroSoft position of course.  That GhostScript is dropping their gsview adds too that.  If making PostScript files is imperative to people they should do it via the Ubuntu for Windows 10 option or similar.
That being said, we could probably manage to make gmt end show to check if it is Windows and the file is PS to call gswin64c file.ps if that actually opens up the PS file.  Is that what you are saying it does?

**Comment by joa-quim** [comment]
I don't see what MS has to do with it. On Linux there a gv that was made by someone, not Linus. And WSL does not have graphic display so would not be an alternative. And WSL is Windows Pro edition only. Not Home edition. The ``gmt end show`` is a possibility but we are not dropping GMT classic mode so the solution must work there as well.

You can try on OSX ``gs file.ps``. It should open the ps file.

**Comment by PaulWessel** [comment]
I believe you can install gs and gv under Ubuntu and with an X11 server for windows you can do gv plot.ps.
Yes, gs file.ps works for OSX but it expects more commands (we get a GS prompt).  We need to find an option or scheme that ends that and puts the plot in the background so it does not lock up the terminal.
Still think using PS under Windows is an uphill battle - MS does not provide any mechanism to view PostScript because they hate Adobe.

**Comment by PaulWessel** [comment]
I do believe there is value in opening PS files directly if the user wants PS.  Under Linux and macOS, if gv is installed, I have made changes so that we open with gv file.ps & instead.  If the file is PostScript then I check if gv is installed and if true then change the viewer from the default (open or dxg-open) to gv (and append " &").  I do not use gs for this though, and I guess for you we would need to use gsview64c directly instead lf the default "cmd /c start"?
Question for @seisman: Under Linux, does dxg-open normally open PS files via gv anyway? I.e., i this just a solution for macOS to avoid Preview converting to PDF first?

**Comment by joa-quim** [comment]
> I believe you can install gs and gv under Ubuntu and with an X11 server for windows you can do gv plot.ps.

That not used to be possible. Maybe with next generation WSL expected soon but clearly not a solution for masses.

But are right about landing on a GS prompt. Not good enough solution either.

**Comment by PaulWessel** [comment]
There are also lots of cygwin users and they all install a X11 server for Windows and run gv - I had several of those folks in my class over the years.
See if there is any way to avoid the GS prompt via some option.

**Comment by joa-quim** [comment]
``cmd /c start gswin64c lixo.ps`` almost does it. It does not land on the GS prompt, thus releasing the cmd shell but still open a second command cmd with the GS prompt.

**Comment by seisman** [comment]
> Question for @seisman: Under Linux, does dxg-open normally open PS files via gv anyway? I.e., i this just a solution for macOS to avoid Preview converting to PDF first?

Under Linux, xdg-open calls evince, the default PS viewer, to open PS files. The [evince documentation](https://wiki.gnome.org/Apps/Evince/SupportedDocumentFormats) says it uses [libspectre](https://www.freedesktop.org/wiki/Software/libspectre/) as its PS backend.

**Comment by PaulWessel** [comment]
Thanks, I will make this an #ifdef Apple only then

**Comment by joa-quim** [comment]
Can't find a way to avoid having a window with the GS prompt, which when killed kills the display PS window.

**Comment by PaulWessel** [comment]
So what would you like: Leave as is or use cmd /c start gswin64c file.ps?

**Comment by joa-quim** [comment]
I think ``cmd /c start gswin64c file.ps`` is preferable. But ``gswin64c `` is for 64 bits only. Don't know how to reliably detect if 32 bits, so let's live it like this.

**Comment by PaulWessel** [comment]
But if gswin64c is not in the PATH, then this command may fail as well.  Is that acceptable?

**Comment by joa-quim** [comment]
gswin64c is in the path because we ship it in the 64 bits installer.

**Comment by PaulWessel** [comment]
OK, will implement a branch and then you can test it.

**Comment by joa-quim** [comment]
Yes, but tomorrow

**Comment by PaulWessel** [comment]
OK
