### ISSUE TITLE
Windows installer doesn's create a desktop icon

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1534]
The Windows installers give a checkbox to allow "Create a desktop icon". But even if it's checked, the installers don't create a desktop icon. For first-time users, I believe it helps to have a desktop icon, which opens a CMD, just like what we do with the macOS bundle.

**Comment by joa-quim** [comment]
Well, IMO it's a nearly useless thing. Since GMT adds to the path any cmd window is as good as the one opened by that icon. And it's just another icon cluttering the desktop.

**Comment by seisman** [comment]
I agree it's almost useless and may not be created by default. But it may help first-time users understand that GMT is a command-line only software, otherwise they may not know they have to type a "gmt" in a CMD.

**Comment by joa-quim** [comment]
If they haven't read a single line of the documentation, maybe. But I don't think we should aim that low level of computer knowledge.

**Comment by seisman** [comment]
OK, then at least we should remove that checkbox, as it never works.

**Comment by joa-quim** [comment]
Right.

**Comment by seisman** [comment]
Closed by #1536
