### ISSUE TITLE
Shut up a system call that returns a stderr message

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1537]
We use commands such as

fp = popen ("gs --version");

to determine if gs is installed and perhaps check what version it has later on.  However, if gs (or any other program we look for in the path) is not there then we get an ugly
-bash: gv: command not found
message to stdout.  I can fix that for *nix by using

fp = popen ("gs --version 2> /dev/null ");

What works on Windows> is it > NUL ?

@joa-quim please let me know, you can try this and change to > NUL.

#include <stdio.h>

int main () {
	FILE *fp = popen ("asdfs --version 2> /dev/null", "r");
	if (fp) fclose (fp);
}

**Comment by joa-quim** [comment]
It runs silently. But why would we need this on Windows? There is no ``gs`` on Win and in psconvert we use the ``ghostbuster`` function to detect ghostscript.

**Comment by PaulWessel** [comment]
No need.  I have done #ifdef __APPLE__ on it now.  But the point is still valid for ffmpeg, gm, etc.  These are in your PATH and not fished from registry, no?  So I will use > NUL for those.

**Comment by joa-quim** [comment]
Only the Ghost is hunted in registry.
