### ISSUE TITLE
Remove age.3.30.nc from gmt_md5_server.txt

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1546]
`age.3.30.nc` doesn't exist in the GMT data server and isn't used anywhere. Please remove its md5sum information from the `gmt_md5_server.txt` file.

**Comment by PaulWessel** [comment]
There is no age.3.30.nc, do you mean age.3.10.nc ( in md5 list)

**Comment by seisman** [comment]
There is a `age.3.30.nc` at line 54 of http://www.soest.hawaii.edu/gmt/data/gmt_md5_server.txt.

**Comment by PaulWessel** [comment]
Ay, the one in svn is out of date.  OK, I removed the line on the server and changed the file count (rec 1) to 167.

**Comment by PaulWessel** [comment]
Maintenance and upkeep of cache is not a resolved issue and has bus factor of 1.

**Comment by seisman** [comment]
I think we can even remove some earth relief files from the data server. For example, `AFR.nc`

```
 $ gmt grdinfo @AFR.nc
/Users/seisman/.gmt/cache/AFR.nc: Title: Produced by grdcut
/Users/seisman/.gmt/cache/AFR.nc: Command: grdcut etopo2m.nc -R0/10/0/10 -GAFR.nc
/Users/seisman/.gmt/cache/AFR.nc: Remark:
/Users/seisman/.gmt/cache/AFR.nc: Pixel node registration used [Geographic grid]
/Users/seisman/.gmt/cache/AFR.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
/Users/seisman/.gmt/cache/AFR.nc: x_min: 0 x_max: 10 x_inc: 0.0333333333333 (2 min) name: longitude n_columns: 300
/Users/seisman/.gmt/cache/AFR.nc: y_min: 3.46944695195e-18 y_max: 10 y_inc: 0.0333333333333 (2 min) name: latitude n_rows: 300
/Users/seisman/.gmt/cache/AFR.nc: z_min: -5023 z_max: 3614 name: z
/Users/seisman/.gmt/cache/AFR.nc: scale_factor: 1 add_offset: 0
/Users/seisman/.gmt/cache/AFR.nc: format: netCDF-4 chunk_size: 150,150 shuffle: on deflation_level: 3
```

This file is a subset of the earth_relief_02m.grd, and is only used by our test scripts (not in any examples). I think it's safe to remove these files from the remote data server, and generate these files in the test scripts.

**Comment by PaulWessel** [comment]
Yes maybe, but that is just one file.  The other grids are not cuts from etopo.

**Comment by seisman** [comment]
Yes, only a few files. Closed.
