### ISSUE TITLE
Flags in x2sys_list -F can no longer be in arbitrary order.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1575]
Probably a consequence of, in a mixed numeric text file, having to write all the numerics first but now flags in option **-F** of ``x2sys_list`` can no longer be in arbitrary order. This old code of mine now breaks in Mirone because it's expecting the name in first column but it's now put in 4th although **-Fnxyc** was used.

```
# Tag: MGD77+ best_cm4
# Command: x2sys_list C:\a1\mgd77\COEs_17_linear.dat -TMGD77+ -Fnxyc -Cbest_cm4 -S00bigset -Qe -R-16.0333/-7.3000/33.2333/42.9000
#
# lon	lat	best_cm4_x	track
-11.1711797059	36.7291785784	57.3634097407	01010031
-9.64781085531	36.2601970421	17.6599921479	01030122
...
```

**Comment by PaulWessel** [comment]
THe usage says:

	-F Specify any combination of acdhiINtTvwxyzn in the order of desired output:
	   Exception: n, if chosen, will always be placed at the end of the output record.

I will improve the rst docs on this.

**Comment by PaulWessel** [comment]
Sorry, no need, already there:

The output order
    of the columns follows the order they were given in *flags* with the
    exception that **n**, if chosen, will always be placed after all
    numeric columns (it becomes part of the trailing text).

**Comment by joa-quim** [comment]
... and I had consulted the the docs this time, except not to the end.
Closing this.
