### ISSUE TITLE
Cleanup changelog

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1580]
**Description of the desired feature**

The changelog (https://docs.generic-mapping-tools.org/latest/changes.html) is outdated. I think we can remove it and start a new changelog after 6.0.0.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
Any thoughts on the changelog?

**Comment by PaulWessel** [comment]
I will see what I can do.

**Comment by PaulWessel** [comment]
Can you remind me how to run git log and get the entry sentence for all commits since 5.4.x?

**Comment by seisman** [comment]
`git log 5.4.5..6.0` to get all the commits since 5.4.5.

**Comment by PaulWessel** [comment]
I know I ran this a few days ago on my laptop and it works.  But now here at home, on 6.0, I get

```
pwessel@MacBeth:~/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev-> git log 5.4.5..6.0
fatal: ambiguous argument '5.4.5..6.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```

**Comment by seisman** [comment]
Try `git log 5.4.5..6.0 --` or `git log 5.4.5..6.0 -- .`?

**Comment by PaulWessel** [comment]
Neither, both gives fatal: bad revision '5.4.5..6.0'
Oh, duh, there is no 5.4.5, only 5.4.4...

**Comment by seisman** [comment]
Maybe you need to run `git pull` to fetch all tags to your local repository.
