### ISSUE TITLE
Use begin and end in the tutorial

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1583]
In the tutorial, we should always use 
```
gmt begin map
gmt ...
gmt end show
```

instead of the one-liner commands.

**Comment by PaulWessel** [comment]
I agree that it is just plain confusing to switch between one-lines and the regular modern mode syntax.  One you know your way around GMT you can cheat and use those one-liners for simple stuff.

The other problem with the tutorial (I just got a new graduate student and he is learning GMT by working through the tutorial) is that we are mixing some classic mode calls, e.g., how to make a CPT, such as

`gmt makecpt -Crainbow -T1000/5000/500 -Z > topo.cpt
`

but then we may have a modern mode script with

`gmt grdimage @tut_relief.nc -JM6i -B -Ctopo.cpt
`

and my student simply pasted the makecpt command into the gmt begin/end script but of course in modern mode you need -H for this, or even better, you just do

```
gmt makecpt -Crainbow -T1000/5000/500 -Z
gmt grdimage @tut_relief.nc -JM6i -B
```

So separating them out can also be confusing.

**Comment by PaulWessel** [comment]
I will work on this now.

**Comment by seisman** [comment]
Closed by #1586

**Comment by PaulWessel** [comment]
What about man pages? We have lots of one-liners in the man pages and those examples are not particularly helpful for new users trying to build a modern mode script by hunting for examples.  Copying

`gmt colorbar -Ct.cpt -Dx8c/1c+w12c/0.5c+jTC+h -Bxaf+l"topography" -By+lkm -pdf map
`

into a gmt begin myplot pdf modern mode script is disastrous.  I know we wanted 1-liners because they are short, but are we setting people up for trouble?

**Comment by seisman** [comment]
Yes, as the one-liner syntax is introduced in an appendix of the long cookbook, most users may never realize the existence of the one-liner syntax.

**Comment by PaulWessel** [comment]
There are also lots of man pages examples that has one-liners that cannot work by themselves, e.g., clip sets a clip path but we have no example on the man page that users can copy and paste to see the effect.  There must be lots of those cases across most man pages.

**Comment by joa-quim** [comment]
When one liners are clearly incorrect (clip, makecpt, etc), ofc I agree that they should be replaced by a
```
gmt begin
   makecpt ...
   ...
gmt end
```
But I don't think we should remove all one-liners from man pages. Man pages are not for beginners only and I don't think we should hide one-lines so much as making them disappear. What we can do is, every time a one-liner is used in a man page, wrap it's introdution with something like *as a one-liner* and link the sentence to the now appendix xxx

**Comment by PaulWessel** [comment]
That is a good suggestion.  If we were to hide things completely then might as well remove the feature.  I will do a few examples and then we can see.  The goal is that users can copy paste any code group and it will work, not just present theoretical examples of a gmt command that could be used in a larger context.  Newbies will copy/paste those too and get frustrated.

**Comment by PaulWessel** [comment]
What do @seisman and @joa-quim think of letting one-liner mode have built in "show" as well?  if it is for the convenience of simplifying typing and showing a quick plot, why not also open it up.  A small price to pay for the ultimate simplicity, no?

**Comment by PaulWessel** [comment]
Along the same lines, should our plot modern examples in the docs end with gmt docs show?  I think they should since they are there for users to copy/paste.

**Comment by seisman** [comment]
Yes, I agree with both.

**Comment by PaulWessel** [comment]
Will start with the auto-show part.

**Comment by PaulWessel** [comment]
All modern mode examples in the docs already uses "gmt end show".  The one-liner update brings parity to all plotting examples.

**Comment by PaulWessel** [comment]
Hi @seisman, how to I reference the cookbook/one-liner.rst via a ref: call from the module documentations?

**Comment by seisman** [comment]
You can use 

```
:doc:`/cookbook/one-liner`
```

**Comment by PaulWessel** [comment]
Thanks, going for a walk but back later.

**Comment by PaulWessel** [comment]
Because we were lazy and use the one-liner in some of our tests, postscript plots are popping up in gv when I run the tests.  I think we agree that the benefit of having auto-show is worth this inconvenience. Possible ways to prevent one-liners to call end with show:

1. Have those test scripts set export **GMT_SHOW_OFF** and have the online code check if that is set or not and take action accordingly.
2. Add a global debug option not documented to the users (e.g., -/) to turn off show.
3. Add a trailing - to the one-liner options, e.g., -pdf- to indicate no show.

I think any of these are not likely to accidentally be used by users.  Thoughts?

**Comment by seisman** [comment]
I like **GMT_SHOW_OFF** (maybe **GMT_FIGSHOW_OFF** is better?), because it looks more flexible. I think we can export **GMT_SHOW_OFF** in the **gmtest** scripts, so that we don't need to change the test scripts directly.

I also hope **GMT_SHOW_OFF** can work for both one-liners and modern "gmt end show", as it makes the development of the [sphinx_gmt](https://github.com/GenericMappingTools/sphinx_gmt) much easier. The idea of the sphinx_gmt extension is to execute any GMT scripts and automatically insert the generated images into the rST-generated HTMT/PDF document. Currently, sphinx_gmt has to check if the script contains "gmt end show". If yes, then change the code "gmt end show" to "gmt end" to disable the auto-show for modern-mode examples. Although currently sphinx_gmt isn't used by the GMT official documentation, it's extensively used by the [GMT Chinese documentation](https://docs.gmt-china.org/latest/). I believe we will apply sphinx_gmt to the official documentation in the near feature.

**Comment by joa-quim** [comment]
I normally resist to add more parameters to gmt.conf but this time we seem to have a strong reason. So, I agree with **GMT_SHOW_OFF** too.

**Comment by seisman** [comment]
I think @PaulWessel is proposing a environmental variable, not a gmt parameter. Anymore, both work in a similar way.

**Comment by PaulWessel** [comment]
Yes, not proposing a GMT parameter.  So OK with checking that environmental parameter then?

**Comment by PaulWessel** [comment]
BTW: this was surely the easiest fix - just add a setting to gmtest.in instead of adding option to each single one-liner script.

**Comment by joa-quim** [comment]
It will be the first time we use environment variables to condition behavior (well, except GMT_SHAREDIR)

**Comment by PaulWessel** [comment]
There are others, such as GMT_SESSION_NAME, etc.

**Comment by PaulWessel** [comment]
FYI, the parameter and its value was called GMT_END_SHOW=off.

**Comment by PaulWessel** [comment]
Can we close this now?
