### ISSUE TITLE
pscoast ignores -R?

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#159]
```
$ pscoast -M -W -R-25/34/57/81 | gmtinfo -I1
-R-30/40/50/84
```
``pscoast`` does not seem to respect the given ``-R``. Should not the reported ``-R`` from ``gmtinfo`` be exactly the same as was input to pscoast?

6.0.0_8c30e1e

**Comment by PaulWessel** [comment]
Ideally, yes.  However, we are writing out the line segments which are binned in certain intervals. In your case that binning is 2x2 degrees hence the output data reflect that.  Trimming those lines before write out adds more complexity. I will see how easy it might be.

**Comment by abanbj** [comment]
I see. Maybe it's not worth the while. I was posting this because I thought it may be a bug. Obviously it's not.

**Comment by joa-quim** [comment]
Note that you can achieve the wished result by piping through ``gmtselect -R``

**Comment by abanbj** [comment]
Looking good!
