### ISSUE TITLE
mapproject -A for Cartesian data is backwards

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1591]
**Description of the problem**

Per mapproject man page, **-Af**_lon/lat_ shall return the (forward) azimuth to each data point from the fixed point, while **-Ab**_lon/lat_ shall return the back-azimuth from each data point to the fixed point.  This works for geographic data:

`echo 0 0 | gmt mapproject -Af1/1 -o2 -fg
`

gives 225.004363545 which seems fine (azimuth of line from (1,1) to (0,0) on a sphere, while for Cartesian data (no **-fg**):

`echo 0 0 | gmt mapproject -Af1/1 -o2
`

returns 45 which is the azimuth of line from (0,0) to (1,1) in the plane.  The results flip if **-Ab** is used.  The problem is thus in the Cartesian azimuth function.  This is likely to affect some tests so I wanted someone like @seisman or @joa-quim to verify that this is in fact the incorrect result.  I will work up a fix in the mean time.

**Comment by seisman** [comment]
Yes, looks incorrect to me.

**Comment by joa-quim** [comment]
I get a NaN

```
C:\v>echo 0 0 | gmt mapproject -Af1/1 -o2
45

C:\v>echo 0 0 | gmt mapproject -Abf1/1 -o2
NaN
```

**Comment by seisman** [comment]
@joa-quim Maybe you can check if #1592 fixes your NaN issue.

**Comment by joa-quim** [comment]
Nope. Still get the NaN. Will try to debug it later.

**Comment by joa-quim** [comment]
Ghrrr, sorry dumb user; bad syntax. It works

```
echo 0 0 | gmt mapproject -Ab1/1
0       0       225
```
but it's to right for geogs
```
echo 0 0 | gmt mapproject -Ab1/1 -fg
0       0       44.9956364553

echo 0 0 | gmt mapproject -Af1/1 -fg
0       0       225.004363545
```

**Comment by PaulWessel** [comment]
Are you saying you are getting

> echo 0 0 | gmt mapproject -Ab1/1
> 45
> 

_after_ applying #1592?  I get

> echo 0 0 | gmt mapproject -Ab1/1
> 225
>

**Comment by joa-quim** [comment]
After #1592 This is correct
```
echo 0 0 | gmt mapproject -Ab1/1
0       0       225
```

But this is wrong
```
C:\v>echo 0 0 | gmt mapproject -Ab1/1 -fg
0       0       44.9956364553
```

**Comment by PaulWessel** [comment]
I get ~45 for both.  -Ab computes azimuth _from_ data point  (0,0) _to_ fixed point (1,1).  That is clearly 45.  It is truly interesting if your Cartesian calculation still gives 225 after #1592.

**Comment by joa-quim** [comment]
Hmm, this is getting a little confusing. This is what I get. For me Cartesian is right, geog is wrong (flipped). Azim from 0 to 1 is ~45 not ~225
```
C:\v>echo 0 0 | gmt mapproject -Af1/1
0       0       45

C:\v>echo 0 0 | gmt mapproject -Ab1/1
0       0       225

C:\v>echo 0 0 | gmt mapproject -Af1/1 -fg
0       0       225.004363545

C:\v>echo 0 0 | gmt mapproject -Ab1/1 -fg
0       0       44.9956364553
```

**Comment by PaulWessel** [comment]
Agree, and I run your geographic commands and get the same because there were no code changes here recently.
However, #1592 fixed the error in the Cartesian case and now I get almost the same result for Cartesian as geographic data.  Are you really sure you have updated and built the very latest GMT 6.0 branch?  I very much doubt your atan2 has a bug.

**Comment by joa-quim** [comment]
I keep forgetting to do ``ninja install``. But now they are all wrong. Or isn't it the idea that we want the azimuths from 0 to 1 (-Af) and from 1 to 0 (-Ab)?

```
C:\v>echo 0 0 | gmt mapproject -Af1/1
0       0       225

C:\v>echo 0 0 | gmt mapproject -Ab1/1
0       0       45

C:\v>echo 0 0 | gmt mapproject -Af1/1 -fg
0       0       225.004363545

C:\v>echo 0 0 | gmt mapproject -Ab1/1 -fg
0       0       44.9956364553

C:\v>gmt --version
6.0.0_d4ee600_2019.09.20
```

**Comment by PaulWessel** [comment]
The results are now correct as described in the mapproject man page.  If you want to switch that description and change all the calculations then we are causing more trouble than it is worth I think.

**Comment by joa-quim** [comment]
No, I don't want to do that. The way it is, is the correct one. It's just that ``one liners`` give us (me) the false impression that the input point is the reference but it can't be because we can have many input points.

But don't get me wrong, ``one liners`` are coolest examples we can have.

**Comment by PaulWessel** [comment]
OK, reached agreement, time to close this one.
