### ISSUE TITLE
greenspline/gspline_3 fails after #1592 was merged

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1596]
gm diff image:
![gspline_3](https://user-images.githubusercontent.com/3974108/65332633-0f97f780-db8d-11e9-9d18-5533ece9f77b.png)

**Comment by PaulWessel** [comment]
Yes, but if you look at the PDF there is hardly any difference.  I am not sure why fixing an issue in azimuths should affect this example which does not use azimuths at all (no slope constraints).  I will see if get_dircosine is somehow called by mistake (?) in greenspline.

**Comment by seisman** [comment]
Original panel b:

![image](https://user-images.githubusercontent.com/3974108/65347061-2437b800-dbac-11e9-9638-66f2b6cf80a9.png)

New panel b:
![image](https://user-images.githubusercontent.com/3974108/65347095-36b1f180-dbac-11e9-87fc-ce1bcc204d78.png)

The grayscale in the red box is different apparently.

**Comment by PaulWessel** [comment]
Hm, so the shading which is grdgradient which does call azimuths.  Will look.

**Comment by PaulWessel** [comment]
OK, so spline3 tests calls greenspline **-Q**135 to compute the slope in the 135 direction, so it _does_ call gmt_az_backaz.  Since that function had a bug for Cartesian calculations (which this is), I think we need to update the PS with the new (and correct plot), no?

**Comment by PaulWessel** [comment]
Also ex39.sh fails because it uses grd2cpt -E which had a bug just fixed in #1595 so it needs to be updated too.

**Comment by seisman** [comment]
Yes, go ahead please.

**Comment by PaulWessel** [comment]
Closed as fixed by #1598.
