### ISSUE TITLE
Azimuths and vectors disagree?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1599]
Below is the output from the failing new test mapproject/azimuth.sh.  It shows oblique gridlines around a rotation pole (red), hence motion of the plate is along the oblique parallels.  Using mapproject -A to compute the azimuth from the red point to the green point (i.e., the azimuth of the red great circle at the green point) we get 323.7, and adding 90 I get the azimuth of motion at the green point to be 53.7.  These values are matched by online azimuth calculators.  Measuring the angles between these vectors and the black N-S line yields exactly the same azimuths.  Yet, my vectors are not parallel to the oblique gridlines.  Shouldn't they be?

![azimuth](https://user-images.githubusercontent.com/26473567/65350157-c6da4180-db80-11e9-9e1b-70794d270fd1.png)

**Comment by PaulWessel** [comment]
Anything obvious I am missing, @seisman?

**Comment by seisman** [comment]
I think the figure is correct. The vectors are not parallel to the oblique gridlines, because on a sphere
```
azimuth (A->B) != back-azimuth (B->A) + 180
```

If you change `-Af` to `-Ab` in your mapproject command, you'll get the figure below:
![image](https://user-images.githubusercontent.com/3974108/65356147-b72f1d00-dbc1-11e9-9753-dc805a391b10.png)

**Comment by PaulWessel** [comment]
Brilliant, I knew it would take a seismologist who deals with these back-azimuths to set me straight.  So confusion on my part. I will fix the script.  Closing this issue.

**Comment by seisman** [comment]
Closed by #1602.
