### ISSUE TITLE
Add a new section "Quicklinks" in the documentation landing page

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1609]
I propose to add a new section "Quick links" in the documentation landing page, as there are many useful tables or figures, which are hidden in the lengthy cookbook, e.g.:

1. common options
2. projection specifications
3. gmt.conf
4. gmtcolors
5. 35 postscript fonts
6. builtin CPTs
7. octal codes of characters

**Comment by seisman** [comment]
We already have common options, projection specifications and gmt.conf in the "Reference documentation" section. I think it make more sense to move them to the "Quick links" section.

**Comment by PaulWessel** [comment]
I agree these are/should be high-traffic areas in the docs. Let's see what @joa-quim thinks before implementing.

**Comment by joa-quim** [comment]
I agree too and even extend it also list the pen syntax and grid formats (3D nc details)
