### ISSUE TITLE
Region not correct when contouring grid as one-liner

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1616]
In trying to update some documentation examples, found that this command gives no contour map:

`gmt grdcontour @AK_gulf_grav.nc -JM16c -C50,150 -A100,+f10p -B -pdf alaska_grav2
`

With **-Vl** we get these hints:

> grdcontour [WARNING]: Central meridian not given, default to 3
> grdcontour [WARNING]: Your grid y's or latitudes appear to be outside the map region and will be skipped.
> grdcontour [WARNING]: No data within specified region

**Comment by PaulWessel** [comment]
Adding **-R**@AK_gulf_grav.nc works but of course that should not be necessary.

**Comment by PaulWessel** [comment]
The problem was/is that there was a gmt.history file with some random -R setting in the current directory. Somehow that file was ingested before modern mode was turned on and it corrupted the case.

**Comment by seisman** [comment]
Closed by #1617.
