### ISSUE TITLE
Use SHA instead of MD5 for remote file hashes?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1622]
From the md5 man page:

> MD5's designer Ron Rivest has stated "md5 and sha1 are both clearly broken (in terms of collision-resistance)".  So MD5 should be avoided when creating new protocols, or implementing protocols withbetter options.  SHA256 and SHA512 are better options as they have been more resilient to attacks (as of 2009).

I don't think there are much security issues with our data files, but let me know if you think we should move to SHA (256?) now before the release.

**Comment by PaulWessel** [comment]
Also SRTM15 v2.0 just released so we should update that one.

**Comment by PaulWessel** [comment]
Also note that srtm15 v2 is pixel registration only while the rest of our earth* are gridline registration.

**Comment by joa-quim** [comment]
I would prefer sticking to MD5 (don't even know the Win command to do SHAs)

**Comment by PaulWessel** [comment]
We should discuss the plans for the data server.  For instance, do we derive the lower resolution grids from the latest 15 arc second grid that has lots of new original data not available when the other grids (e.g., ETOPO1m) was made?  I think we want to provide the best data, not historical records.  If anyone needs ETOPO1m for some comparison work they can get it from NEIC.  So, this means we will extend my global spherical filtering scheme (which I used to create everything coarser than 2m) to start at 15s instead, then build 30s, 1m, etc etc.
Grid registration is an issue.  I selected gridline registration since that is used by most grids as well as complementary grids like the crustal age grid from EarthByte, and having mixed registrations hurt.  So I think for now I would generate gridline registrated products from the pixel-registered 15s since I am down filtering anyway.  FYI, resampling a pixel grid to a gridline grid at the same resolution results in irretrievable loss of the Nyquiest frequency and attenuation to other frequencies as well, hence should not be done...

**Comment by PaulWessel** [comment]
Users dont need to run SHA or MD5, we do here.  You just compare your local table with the latest server table to detect differences - you dont compute anything.

**Comment by joa-quim** [comment]
They do if they want to compare the signature of a download file (e.g. installers) with our computed one.

**Comment by PaulWessel** [comment]
Sure, and our installers are SHA256.  Anyone who cares deeply enough to check this will know how to compute those hashes.

For our data services running under the hood though, it is just adding more peace of mind knowing that we dont use an abandoned system (md5) and at at least are using a 256-bit key.

**Comment by PaulWessel** [comment]
If @leouieda is around, please read above about updating grids.  Some of this may impinge on plans in the NASA proposal, but should be done.  I think the docs, scripts, etc for maintaining the oceania cache and data needs to be ported to our GitHub collection (it is svn now), since the large files themselves are not in the repo anyway.

**Comment by seisman** [comment]
I prefer sha256, but note that sha256 is ~50% slower than md5. 
```
$ time openssl dgst -md5 earth_relief_30s.grd
MD5(earth_relief_30s.grd)= 342a533584d2473282e36080054a36b1
openssl dgst -md5 earth_relief_30s.grd  1.20s user 0.31s system 97% cpu 1.552 total

$ time openssl dgst -sha256 earth_relief_30s.grd
SHA256(earth_relief_30s.grd)= 7fd3afaa245207e77e1b413ac829c1519cc738fac30767d2d7b09a00a9563d56
openssl dgst -sha256 earth_relief_30s.grd  1.82s user 0.21s system 99% cpu 2.048 total
```
@PaulWessel How often does GMT calculate the checksum of an earth relief file? Every time or everyday?

**Comment by PaulWessel** [comment]
Yes, it is slower, but we are the only ones who do it (once per file) and store the results.  gmt does not compute SHA or MD5 codes during the remote interaction.  So would we not want to use the better hash since the cost is just one time?

**Comment by PaulWessel** [comment]
Does it concern anyone that if we switched to SHA and changed the filename to gmt_hash_server.txt that rc4 and earlier would  not be able to find gmt_md5_server.txt anymore?  The only "MD5"-specific thing in our code is that file name.  It is simply fixed via a symbolic link to gmt_hash_server.txt that can eventually be removed once 6.0 is established, and then if we change our hash method the filename does not have to change anymore.

**Comment by seisman** [comment]
Looks OK to me.

**Comment by PaulWessel** [comment]
Cleaning up the cache server: Found meca.dat which was used in San Diego course.  Perhaps you can actually use that @meca.dat to add simple example in coupe and/or meca?  May I rename it to meca.txt to match other names (txt for text files)?

**Comment by seisman** [comment]
You can delete it from the cache server. I may use simpler data for meca and coupe in the feature.

**Comment by PaulWessel** [comment]
OK, gone.

**Comment by PaulWessel** [comment]
Never.  Well, once on our end.  gmt does not calculate checksums.  It stores them on the server, users download that list from the server, and once a day (if GMT is run) it will refresh the list.  When entries in the list differ from the local copy we must re-download the file since it has changed.

**Comment by PaulWessel** [comment]
SHA256 implemented on oceania.
