### ISSUE TITLE
Add GSHHG description to the "Datasets" section

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1623]
There is a chapter [The GMT High-Resolution Coastline Data](https://docs.generic-mapping-tools.org/latest/cookbook/coastline.html) in the cookbook. I think we can move it to the "Datasets" section.

![image](https://user-images.githubusercontent.com/3974108/65396515-edf96480-dd74-11e9-9d00-31b37551df55.png)

**Comment by PaulWessel** [comment]
I agree, makes sense.
