### ISSUE TITLE
Xcode and macOS issues

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1629]
I am a bit concerned that Apple has released Xcode 11 which seems to expect macOS 10.15 which will be released in October.  My home machine cannot compile GMT since my current OS 10.14.6 (current release) is "too old"...
Hopefully my office machines are not affected yet.  I am reinstalling Xcode 10.3 now to see if I can roll things back.
History tells us it is problematic to release GMT at the same time or just before a macOS update since Apple has a tendency of making unannounced changes to Frameworks or libraries and possibly break something for us.  I suspect Wiley till tells within days that the paper has been fully finished and placed online so not sure what to do.  More tomorrow.

**Comment by seisman** [comment]
If you still can't have a working Xcode on you home machine, maybe you can install the macOS 10.15 public beta release (https://beta.apple.com/sp/betaprogram/), and try if 10.15 breaks anything.

**Comment by PaulWessel** [comment]
I decided to get Xcode 10.3 and do xcode-select etc and got that to work.

**Comment by PaulWessel** [comment]
Closing this issue

**Comment by seisman** [comment]
FYI, macOS 10.15 was release on Oct. 7, 2019.

**Comment by PaulWessel** [comment]
Yes, and I was going to dive in but we should do some research.  A few things i noted:

1. https://www.macobserver.com/tips/quick-tip/macos-catalina-terminal-bash/
2. https://www.macobserver.com/analysis/macos-catalina-deprecates-unix-scripting-languages/
3. There is no Catalina installer for macports. For Fink http://www.finkproject.org you can install but /roo is now locked down by Apple
4. https://medium.com/@hammen/significant-changes-in-macos-10-15-catalina-of-interest-to-mac-admins-fbc3865c055e
5. https://www.macobserver.com/tips/quick-tip/reference-all-about-macos-catalina-system-files/

It would seem wise to wait for other to go first and get macports, brew, working.  But someone user will quickly get Catalina and try to build, etc.  At least our bundle should be built via Mojave until further notice.

**Comment by PaulWessel** [comment]
Xcode 11.1 restores sanity on Mojave. Looks like 11.0 had issues...

**Comment by PaulWessel** [comment]
From fink pages: Xcode11 is known to currently break building the gccX and several other important packages. If possible (especially 10.14 users), hold off on upgrading to Xcode11 unless you need something specific from it. If you do upgrade to Xcode11, make sure that the Command Line Tools are also upgraded to version 11 for your macOS release.
