### ISSUE TITLE
Three failing tests

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1644]
```
1/3 Test #238: filter1d/mfilter.sh ..............***Failed    0.22 sec
filter1d [ERROR]: Error for input file: No such file (weekly_in_situ_co2_mlo.csv)
gmt [ERROR]: Error parsing filter1d options
ERROR: gmtest:58
memtrack errors: 0
exit status: 1

2/3 Test #395: grdimage/url_map.sh ..............***Failed    0.24 sec
grdimage [ERROR]: Error for input file: No such file (untooned_jessicarabbit.jpg)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
ERROR: gmtest:58
memtrack errors: 0
exit status: 1

3/3 Test #830: x2sys/x2sys_06.sh ................***Failed    0.25 sec
x2sys_cross [ERROR]: x2sys_read_file : Cannot find track c2308.txt
(null): Error from fclose [@c2308]
ERROR: gmtest:58
memtrack errors: 0
exit status: 1

```

**Comment by PaulWessel** [comment]
Yep, working on it.

**Comment by PaulWessel** [comment]
Hm, I had not committed a change to deal with this.  Testing my branch works in getting the file, but now filter1d complains about no data columns.  Looking at the file it has lots of header records that I dont think we can recognize:
"-------------------------------------------------------------------------------------------"
" Atmospheric CO2 concentrations (ppm) derived from in situ air measurements                "
" at Mauna Loa, Observatory, Hawaii: Latitude 19.5°N Longitude 155.6°W Elevation 3397m      "
...

I don't know if they changed their format recently?  GMT expects headers to start with #.

**Comment by seisman** [comment]
I can't get the files with the latest 6.0 branch. Checkout the codes before commit https://github.com/GenericMappingTools/gmt/commit/8cf32eeeaa4175f69834b67231b8427bebab54f5, then I can get the files.

**Comment by PaulWessel** [comment]
Now, oddly, in my cache I got that file this morning, and it has these headers:
#-------------------------------------------------------------------------------------------#
# Atmospheric CO2 concentrations (ppm) derived from in situ air measurements                #
# at Mauna Loa, Observatory, Hawaii: Latitude 19.5<C2><B0>N Longitude 155.6<C2><B0>W Elevation 3397m      #
#                                                                                           #
# Source: R. F. Keeling, S. J. Walker, S. C. Piper and A. F. Bollenbacher                   #

so it works again.  How does this happen? Deleting it and running again gives the quotes!

**Comment by joa-quim** [comment]
Just downloaded with the browser and it has

```
"-------------------------------------------------------------------------------------------"
" Atmospheric CO2 concentrations (ppm) derived from in situ air measurements                "
" at Mauna Loa, Observatory, Hawaii: Latitude 19.5Â°N Longitude 155.6Â°W Elevation 3397m      "
"    
```

**Comment by PaulWessel** [comment]
They must have changed the file format.

**Comment by PaulWessel** [comment]
Added -fT to ensure proper parsing of first record.  Tests are working.

**Comment by seisman** [comment]
I think x2sys/x2sys_06.sh is still failing.

**Comment by PaulWessel** [comment]
Passes for me but anim_08.sh and urlquakes.sh fail.  I think the NEIC data changed - what do you see?

**Comment by seisman** [comment]
Error message for `x2sys/x2sys_06.sh`:
```
Test project /Users/seisman/Gits/gmt/gmt/build/debug
    Start 830: x2sys/x2sys_06.sh
1/1 Test #830: x2sys/x2sys_06.sh ................***Failed    0.13 sec
x2sys_cross [ERROR]: x2sys_read_file : Cannot find track c2308.txt
(null): Error from fclose [@c2308]
ERROR: gmtest:54
memtrack errors: 0
exit status: 1
```
anim_08.sh and urlquakes.sh pass for me.

**Comment by PaulWessel** [comment]
Weird.  I am on 6.0 branch and just rebuilt.  I have c2308.txt in the .gmt/cache because it is on oceania.  I dont understand why it cannot find c2308.txt. Does it exist in your cache?

**Comment by seisman** [comment]
Yes, I have it in my cache. I removed the cached `c2308.txt` and run it again, now it works.

**Comment by seisman** [comment]
But now I don't have c2308.txt in my cache directory after running the script.

**Comment by PaulWessel** [comment]
I think I set it up to only write it to the curent directory and not
cache...

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa


On September 27, 2019 at 10:51:39 AM, Dongdong Tian (
notifications@github.com) wrote:

But now I don't have c2308.txt in my cache directory after running the
script.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/GenericMappingTools/gmt/issues/1644?email_source=notifications&email_token=AGJ7IXZOOCEWJKODFAXVCM3QLZW5XA5CNFSM4I2PHJQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72B6VY#issuecomment-536092503>,
or mute the thread

**Comment by seisman** [comment]
x2sys_06.sh passes if I don't have c2308.txt in my cache. But it fails if I have c2308.txt in my cache.

**Comment by seisman** [comment]
This also explain why the CI tests fail, as in the CI we download all cached files before running the tests.

**Comment by PaulWessel** [comment]
Thanks, I should be able to debug that case then.
