### ISSUE TITLE
No documentation of remote files and URLs

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1647]
The Appendix "GMT File Formats" in the cookbook does not mention remote files or general URL files at all.  Seems like we need to document what happens when @file is given (cache file), what happens if a full URL is given, and what happens if that URL is a query.

I could not find that description - let me know if @seisman or @joa-quim knows where it may be - otherwise I will write some for that Appendix.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/blob/6.0/doc/rst/source/cookbook/features.rst#urls-and-remote-files

**Comment by PaulWessel** [comment]
Ah, forgot the cookbook is now a directory so my naive grep remote *.rst in top dir failed...

**Comment by seisman** [comment]
Try [ack](https://beyondgrep.com/), better than grep.
