### ISSUE TITLE
subplot annotations truncated to length 16

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/gmt#1653]
**Description of the problem**

Setting a fixed label using the `-A` setting for subplot doesn't work if the text is greater than 16 characters in length.

**Full script that generated the error**

```bash
gmt begin truncatedannotation png
    gmt subplot begin 2x1 -Fs11c/3c -A
        gmt subplot set 0,0 -A"a) 456789abcdefghijklmnop"
        gmt basemap -R0/20/0/10 -JX11c/3c -BWSen
        gmt subplot set 1,0 -A"b) 456789abcdefghijklmnop"
        gmt basemap -R0/20/0/10 -JX11c/3c -BWSen
    gmt subplot end
gmt end show
```

**Actual outcome**

![truncatedannotation](https://user-images.githubusercontent.com/23487320/65652426-da484980-e065-11e9-8eb5-e0c61bd6e297.png)

**Expected outcome**

The subplot annotation should show "a) 456789abcdefghijklmnop"

This is somewhat related to #940 which was fixed in #943 by increasing the `Baxes` length in [gmt_types.h](https://github.com/GenericMappingTools/gmt/blob/7b910486f44754c6f3f963265fe53bb578309fe7/src/gmt_types.h#L153) from `GMT_LEN8` to `GMT_LEN128`. I'm guessing that changing the line below will help (happy to submit a PR too):

https://github.com/GenericMappingTools/gmt/blob/7b910486f44754c6f3f963265fe53bb578309fe7/src/gmt_types.h#L150

**System information**

* Operating system: Linux
* GMT version (`gmt --version`): 6.0.0rc4

**Comment by PaulWessel** [comment]
Thanks for posting - fixed in PR #1654.
