### ISSUE TITLE
Merge supplemental modules list into core modules list

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1662]
Currently, we have two lists for core modules and supplemental modules, separately. I think most users don't care and don't know "velo" comes comes from core or seis, and they may feel frustrated if they can't find velo in the GMT core modules list. I think we can merge these two into a "GMT modules" list, just like what `gmt --help` and `gmt --show-modules` do.

**Comment by PaulWessel** [comment]
Sorry, where are the two lists?

**Comment by seisman** [comment]
https://docs.generic-mapping-tools.org/latest/modules.html and https://docs.generic-mapping-tools.org/latest/supplements.html.

**Comment by PaulWessel** [comment]
Not sure on this.  The --help and --show-modules still maintain separation though. But I can agree with only having one "GMT Modules" entry in that index and that the page we land on starts like the current core modules (I like the 6 columns of dense core module listing).  Maybe we should have a similar dense listing of all supplemental modules (regardless of which supplement) as another dense 6 column listing with a header "Supplemental Modules" and add "Core Modules" ahead of the first listing? Then place the supplemental page at the end.  I think there is value in having all the mgd77 and x2sys modules together and not split mgd77track into the core "plotting" modules as the sense of grouping is lost.

**Comment by seisman** [comment]
yes, sounds better.
