### ISSUE TITLE
RST files not included in the document

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1668]
After #1665 and  #1666, there are still a few RST files which are not included in the documentation.

- gmt.rst
- gmt5syntax.rst
- gmt_shell_functions.sh.rst
- gmtswitch.rst (could be included into https://docs.generic-mapping-tools.org/latest/switching.html）
- isogmt.rst
- matlab_wrapper.rst (should be removed, but left by purpose, see #870).
- supplements/img/img2google.rst (it's a bash script, not a real GMT module)

Any ideas how and where to include these RST files.

**Comment by seisman** [comment]
Maybe we can add a "Programs & Scripts" section before the "Core Modules" section in the [module list page](https://docs.generic-mapping-tools.org/latest/modules.html).

**Comment by PaulWessel** [comment]
Aren't they all scripts only? Seems to prominent to be on top. Maybe at end?

**Comment by seisman** [comment]
`gmt` is the only program, and others are scripts. It's OK to put the scripts at the end, but what about `gmt`?

**Comment by PaulWessel** [comment]
Right.  Well, gmt is essential so should be at the very top in a sense.  It drives all the other modules.  I know JL does not use it but we should insist (we do in all examples) and it should be first.

**Comment by PaulWessel** [comment]
Maybe say

GMT Modules

This is a list of all GMT core and supplemental modules and their uses, as well as some utility scripts.  All modules are requested via a call to the gmt program

<gmt man page link>
