### ISSUE TITLE
Add GMT mirror list to the main site

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1675]
1. Add the GMT mirrors to the [download page](https://www.generic-mapping-tools.org/download/) so that users know the existence of these mirrors
2. Remove [MIRROR.md](https://github.com/GenericMappingTools/gmt/blob/master/MIRRORS.md) from the gmt repository.

**Comment by PaulWessel** [comment]
Hm, yes.  I tried all mirrors and all but Japan seems OK.  The S Africa ends in gmt/ while the others dont have that trailing slash - probably typo?
No mirror in Europe is pretty crazy - maybe lean on Joaquim and Leo now?

**Comment by seisman** [comment]
The Japan and Brazil mirrors don't work for me.

**Comment by PaulWessel** [comment]
Maybe @leouieda could check with Eder and status of their mirror?  I will ask my Japanese colleague.

**Comment by PaulWessel** [comment]
Seems we should have instructions on our website for potential GMT distribution and data server mirrors.  There should one mirror script for an ftp server (to serve the GMT installers) [could just server the latest [< 1 Gb] or the entire history of releases [15 Gb], and one mirror script for a data server[50+ Gb].

**Comment by seisman** [comment]
I've opened [another issue](https://github.com/GenericMappingTools/website/issues/21) in the "website" repository. Closing.
