### ISSUE TITLE
Shrinking vector heads need to go with shrinking vector stem

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#168]
In GMT 4 the vector was a single polygon so when we shrunk it down (via +n) then everything shrunk automatically.  In GMT 5 the head is a separate polygon and the stem is a line.  Now, +n shrinks the head but we forgot to shrink the pen width of the stem.  Probably something that @PaulWessel should fix...

**Comment by PaulWessel** [comment]
No, that is all wrong.  Stem shrinks just fine.  I just got confused by the original poster's report.  Closing this one.

**Comment by PlanetGus** [comment]
Sorry about that.

**Comment by PlanetGus** [comment]
My bad :)
