### ISSUE TITLE
Failing examples in man pages

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1689]
The documentation for each module is still full of "examples" of GMT syntax that cannot be cut-and-pasted because they access nonexistent files, or they are just snipped of a larger context (for some plot examples) that would not produce a viewable plot.  For example, the gmtconvert man page has many examples, such as

`gmt convert test.b -bi4f > test.dat
`

but of course nobody has that test.b file (it does not exist here either).  It is probably to much to correct all the examples in all the man pages, but maybe we could try to have at least the first example in each module be a working command?  Some already do, like block*.

**Comment by PaulWessel** [comment]
Maybe we should do this: Replace all the occurrences of

```
Examples
--------
```

lines in all the man pages with

> Examples
> --------
> 
> Note: Below are some examples of valid syntax for this module.  The examples that use remote files (file names starting with @) can be cut and pasted into your terminal for testing.  Other commands requiring input files are just dummy examples of the types of uses that are common but cannot be run verbatim as written.
> 

Can this replacement be done cleverly with a script, @seisman, maybe by using a *.rst_ include file for the new header plus text?

**Comment by seisman** [comment]
Yes, doable with a simple script. I'll do it later.

**Comment by PaulWessel** [comment]
Note that at least one file had Example instead of Examples, in case your script looked for Examples when inserting that extra line.  This was grdfilter I think which I changed to Examples.

**Comment by PaulWessel** [comment]
I think we did this, no? Close this issue?

**Comment by seisman** [comment]
There are still many modules which don't have at least one working example. But it's fine to close this issue. We're always working on improving the examples anyway.
