### ISSUE TITLE
Bands (+b) are broken and no 'image' module

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1702]
This
```
gmt image @needle.jpg=gd+b2,1,0 -Dx0/0+w7c -P -Y15c -K > lixo.ps
```
and this
```
gmt image @needle.jpg=gd+b0,1,2 -Dx0/0+w7c -P -Y15c -K > lixo.ps
```
produce the same output (**+b** seems to be ignored). 

and ``gmt image`` not found
```
gmt image @needle.jpg=gd+b2,1,0 -Dx0/0+w7c -P -Y15c -K > lixo.ps
gmt [ERROR]: Shared GMT module not found: image
```
Trying to see what's going on with -b but will have to leave in a while.

**Comment by PaulWessel** [comment]
But otherwise you are right:

```
gmt image @needle.jpg=gd+b2,1,0 -Dx0/0+w7c -pdf one
gmt image @needle.jpg=gd+b0,1,2 -Dx0/0+w7c -pdf two
```

produces the same plot.

**Comment by PaulWessel** [comment]
That must be in the GDAL read part, no?

**Comment by joa-quim** [comment]
No, it's psimage L445

**Comment by PaulWessel** [comment]
You are right.  So need to add a c[0] = '=' just before L471 I think?

**Comment by joa-quim** [comment]
Not enough. Need to follow track but have only ~20 min before going to airport pick up Alexandra

```
ERROR 5: C:/Users/joaqu/.gmt/cache/needle.jpg: GDALDataset::GetRasterBand(0) - Illegal band #

ERROR 10: Pointer 'hBand' is NULL in 'GDALGetRasterDataType'.

ERROR 10: Pointer 'hBand' is NULL in 'GDALRasterIO'.

psimage [ERROR]: GDALRasterIO failed to open band 2 [err = 3]
```

**Comment by joa-quim** [comment]
> There is no image command in classic mode.

This is too confusing. Classic mode should accept the modern mode names as well.

**Comment by PaulWessel** [comment]
Classic mode has no idea there are modern mode names and neither do classic mode users.  Mixing that up is what would be truly confusin.

**Comment by joa-quim** [comment]
There will be not clear cut division between classic and modern mode users. Classic will be modern too (the inverse will be much more rare) and that's where the forbidding rules will produce confusion.

**Comment by PaulWessel** [comment]
So on further review ... we accept pscoast and psbasemap etc in modern mode so not sure why image is not accepted...

**Comment by PaulWessel** [comment]
Sorry, got turned around.  It is one thing to allow module links so that GMT4 scripts will run, but quite another thing to add new features to classic mode.  There is no backwards compatibility to address there.

**Comment by joa-quim** [comment]
It's not about compatibility but about surprises, distractions, forgetting call as you want. I just did it so others will fall in there as well.

**Comment by PaulWessel** [comment]
And we learn from such failures.
