### ISSUE TITLE
Mixed tabs and spaces in example scripts

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1714]
Some examples use tabs for indentation (e.g. https://docs.generic-mapping-tools.org/latest/gallery/ex05.html) while others use spaces (e.g. https://docs.generic-mapping-tools.org/latest/gallery/ex01.html). We should have a consistent indention style.

**Comment by PaulWessel** [comment]
Not sure if we can control how wide a tab is on the web page? If not, I think two space indent looks tighter.
