### ISSUE TITLE
pi gets crazzy

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#172]
psbasemap -JX12c/8c -Bpa1pi2 -Ba -BWS -R0/14/-1/1 -P > lixo.ps
![lixo](https://user-images.githubusercontent.com/537321/48224853-0fd33e00-e393-11e8-9412-16468b306321.png)

**Comment by PaulWessel** [comment]
It is a feature: We only do fractional pi up to <= 2 pi.  From the comments:
		/* We only allow n pi, 1.5pi, and fractions 3/4, 2/3, 1/2, 1/3, and 1/4. */

The idea was to keep it simple, but if you want 5pi, 16 pi/3, 17 pi/3, 6pi, etc then we need to recode that section.

**Comment by joa-quim** [comment]
It was the first time I used it and even then it was on Julia test. Now I see (better) that the man says ``for an optional integer n and optional m fractions 2, 3, or 4.`` but very easy to not see it. Not sure what it should do. Possibly a warning and only print (n)pi's after 2pi
