### ISSUE TITLE
Drop UNIX man pages?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1728]
The UNIX man pages seem useless for most users, as now they can access the HTML version local/remote documentation via `gmt docs`. The UNIX man page format is also limited to plain text, preventing us from adding non-text elements (e.g. figures) to the manual.

Do you think we should drop the UNIX man pages?

**Comment by PaulWessel** [comment]
I think we will have too.  Right now, events and psevents are probably the only "man ages" with illustrations, but the idea is to add more.  So I vote yes on dropping 1990s man pages.

**Comment by seisman** [comment]
@joa-quim Are you OK with dropping the man pages? If yes, I'll do it  tonight.

**Comment by joa-quim** [comment]
I have no opinion on this. In principle yes, but no idea if people still use them.

**Comment by PaulWessel** [comment]
There is no requirement that a package in a distro must have man pages.  Having them is a legacy from the 1980s.  Once we add more figures then using gmt docs module will be a much better way to get information about a module.  There is still gmt module -? for a description.  What does @leouieda think about this?

**Comment by leouieda** [comment]
Personally, I don't use man pages and we have limited time to maintain things. So dropping makes sense.

**Comment by sebastic** [comment]
Not happy with this for the Debian package, as all packages should have manpages per [Debian Policy 12.1](https://www.debian.org/doc/debian-policy/ch-docs.html#manual-pages).

Please consider reverting this change or generating the manpages via `gmt docs`.

**Comment by PaulWessel** [comment]
We can have that discussion.  One reason we decided to drop man pages is that while man pages are pretty straightforward and useful for tools like awk and grep, they are strongly limiting for documentation for modules makes graphical products.  We want to add actual command examples with actual plot output and nroff is not capable of that (?).  So now we would have to maintain a limited/crippled version of man pages plus the html docs derived from rst.  We do for certain not want to maintain two sets of rst files.  I don't know what sphinx/nroff does when there are images in the rst and if the resulting nroff files will look strange as sections of code is missing.  Graphics or not, navigating GMT documentation with crosslinks etc is vastly simpler via a browser than via the man command.

It is also a problem for us and Debian users of GMT that the distro tends to lag 1-2 years behind the current version and many users simply need to build from source anyway.  Of course, we understand that Debian is not going to change policies we think are wrongheaded.

Anyway, I would like to hear opinions from @GenericMappingTools/core.

**Comment by seisman** [comment]
Since GMT5, the only command/executable GMT provides is `gmt`. Other "commands" (e.g. `coast`, `basemap`) are modules of the core `gmt` command. 

I think we can provide **one single manpage** for the `gmt` command. It's not much burden for us, and also makes Debian happy.

**Comment by PaulWessel** [comment]
Yes, sounds like a nice compromise.

**Comment by joa-quim** [comment]
I was thinking about something of that kind, but I'm not sure this is enough to please the Debian Policy. What would contain that single ``gmt.man``? They say _Each program, utility, and function should have an associated manual page ..._ Just the module's synopsis would (minimally) fit that but would require separate rst.

**Comment by PaulWessel** [comment]
Well, we are working on a compromise here.  Providing 1990s man pages for graphical tools is the wrong decision, so the best that can be done in this context is to provide a man page for gmt which can have some new text on how to get detailed module information.

**Comment by sebastic** [comment]
> Since GMT5, the only command/executable GMT provides is `gmt`.

There are a few more:

 * `/usr/bin/gmt`
 * `/usr/bin/gmt_shell_functions.sh`
 * `/usr/bin/gmtswitch`
 * `/usr/bin/isogmt`
 * `/usr/bin/gmt-config`

**Comment by sebastic** [comment]
> It is also a problem for us and Debian users of GMT that the distro tends to lag 1-2 years behind the current version and many users simply need to build from source anyway. Of course, we understand that Debian is not going to change policies we think are wrongheaded.

During the stretch lifetime gmt was actively backported, so it had the latest gmt after a week or so.

If you want GMT users to build from source any way, we can remove the package from Debian to encourage them to stop using the package. Do you want me to remove it? You don't have to worry about this issue or any future ones once it's gone.

**Comment by PaulWessel** [comment]
OK, sorry, you have been very helpful with patches etc. so I should not be upset with you.  My apologies.

**Comment by seisman** [comment]
We have added manpages of the five commands back in #1901, #1904, #1905. Closing.

**Comment by sebastic** [comment]
Excellent, thanks!
