### ISSUE TITLE
Add final GMT 4.5.18 tar ball to download page

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1730]
It seems only reasonable that we add gmt-4.5.18-src.tar.bz2 to the GitHub download page.  As the old wiki will go and probably the old gmt4 page as well, that is a good final resting place for it.  It could say

> GMT 4.5.18 (final)

The file is at ftp://ftp.soest.hawaii.edu/gmt/gmt-4.5.18-src.tar.bz2.

**Comment by seisman** [comment]
We may also need to provide links to the Windows and macOS installers.

**Comment by PaulWessel** [comment]
Hm, yes, maybe the list should be a three column table with source, Windows macOS?

**Comment by seisman** [comment]
What about creating a [wiki page](https://github.com/GenericMappingTools/gmt/wiki) on GitHub, and list the links of tarballs and installers for 4.5.18? 

Then the download page could say

**GMT 4.5.18 (final) (link to the wiki page)**

**Comment by PaulWessel** [comment]
I think that would be fine too.

**Comment by seisman** [comment]
The wiki page link for 4.5.18 is available from https://github.com/GenericMappingTools/gmt/wiki/GMT-4.5.18

**Comment by seisman** [comment]
For the gmt4 [documentation](http://gmt.soest.hawaii.edu/gmt4/gmt/html/gmt_services.html) or even [the whole site](http://gmt.soest.hawaii.edu/gmt4/), I think we can push it to the gh-pages branch, and host it at https://docs.generic-mapping-tools.org/4/

**Comment by seisman** [comment]
@PaulWessel Could you create a tarball of the whole gmt4 site (http://gmt.soest.hawaii.edu/gmt4/) and share it with me?

**Comment by PaulWessel** [comment]
See if you can get it as per email - hitting the road now so cannot check until back home.

**Comment by seisman** [comment]
Done.

Here are the links for all the versions we are hosting.

- GMT4: https://docs.generic-mapping-tools.org/4
- GMT5: https://docs.generic-mapping-tools.org/5.4
- GMT6 6.0 branch: https://docs.generic-mapping-tools.org/6.0 and https://docs.generic-mapping-tools.org/latest
- GMT6 master branch: https://docs.generic-mapping-tools.org/dev

**Comment by doctortuba** [comment]
Link on 4.5.18 wiki page is still pointing to ftp site at soest.hawaii.edu which is gone. Would it be possible to host the 4.5.18 tar ball here on GitHub?

**Comment by PaulWessel** [comment]
Hm, the files are there but I see Safari returns a message with "FTP URLs are disabled". I added the GSHHG links here for convenience but same issue. Some configuration, @seisman ?

**Comment by seisman** [comment]
I think it's because Safari and other web browsers have dropped FTP support. So there is nothing we can do on the FTP server side.

**Comment by PaulWessel** [comment]
OK, http[s] then?

**Comment by seisman** [comment]
Yes, http[s] is always the better option.

**Comment by PaulWessel** [comment]
So maybe add this to the https://www.generic-mapping-tools.org/download/ page under "Legacy GMT 4 version" ?

**Comment by Esteban82** [comment]
What about in Zenodo?

**Comment by PaulWessel** [comment]
Hm, I guess that is an option too. Comments from others on this?

**Comment by joa-quim** [comment]
Github is clearly preferable.

**Comment by doctortuba** [comment]
Thanks guys, good to know the file is there. I would like it to be as similar as possible to the other resources, i.e. https from github.
