### ISSUE TITLE
Separate chapter for common options in the coobook

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1738]
The chapter [General Features](https://docs.generic-mapping-tools.org/latest/cookbook/features.html) is too long. I think we can separate the section [Standardized command line options](https://docs.generic-mapping-tools.org/latest/cookbook/features.html#standardized-command-line-options) out of the chapter "General Features".

**Comment by PaulWessel** [comment]
I agree.  The general feature section has really important stuff for new users such as specifics on pens, fills, cpts and more.
