### ISSUE TITLE
Remove some duplicates from the cookbook

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1741]
Just some random thoughts in my head:

1.  Remove the section [Acknowledgements](https://docs.generic-mapping-tools.org/latest/cookbook/acknowledgments.html): most of the content are already in the main site [about page](https://www.generic-mapping-tools.org/about/#support) and the [AUTHORS.md](https://github.com/GenericMappingTools/gmt/blob/master/AUTHORS.md). It's also a little odd to have acknowledgements in a cookbook.
2. Remove the section [Reminder](https://docs.generic-mapping-tools.org/latest/cookbook/citation.html): duplicate of [the main site citation page](https://www.generic-mapping-tools.org/cite/), except the last two paragraphs
3. The section [Copyright and Caveat Emptor](https://docs.generic-mapping-tools.org/latest/cookbook/copyright.html) is very similar to the [LICENSE.txt](https://github.com/GenericMappingTools/gmt/blob/master/LICENSE.TXT) in the gmt repository and we already have a link to the LICENSE.txt at the bottom of the sidebar. IMO we can combine these two files into one LICENSE.txt and links to the LICENSE.txt whenever it's needed.
4. The [compatibility page](https://docs.generic-mapping-tools.org/latest/compatibility.html) is outdated and confusing, as we claim GMT6 is fully compatible with GMT4 and GMT5. IMO we can totally remove it, but the table of old and new GMT defaults names are still useful, which can be moved to a section of the [gmt.conf man page](https://docs.generic-mapping-tools.org/latest/gmt.conf.html).

Any thoughts?

**Comment by PaulWessel** [comment]
Agree on 1 and 2 - they can be removed.  Yes, agree we can combine and eliminate that section. 4 is probably incomplete anyway and since we do want compatibility we don't need to list these.  Maybe just delete all that, keep the table, and rename to Deprecated GMT Defaults Names?
