### ISSUE TITLE
gmtinfo -r option

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1753]
I find that `gmtinfo` supports `-r` option. Is it right? Do netCDF tables care about registration?

**Comment by PaulWessel** [comment]
No, this has to do with getting useful -R region information depending on how a data x,y,z table may be used in gridding.  I have to look more carefully to see exactly how we did this, but it has nothing to do with netcdf tables.

**Comment by seisman** [comment]
OK. Invalid issue. Closed.
