### ISSUE TITLE
Hemispherical dome

### ISSUE THREAD

**Issue by Yacob72** [GenericMappingTools/gmt#1770]
**Can one plot hemispherical dome using
![dome](https://user-images.githubusercontent.com/56369378/66521772-24acda00-eaec-11e9-8b3a-b808f793d93c.gif)
 GMT like the plot attached?**

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by seisman** [comment]
I don't think GMT can do it.

**Comment by joa-quim** [comment]
Closing on the *age* criteria.
