### ISSUE TITLE
test/modern/insetlegend.sh fails

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1786]
gm diff image:
![image](https://user-images.githubusercontent.com/3974108/66678017-ee30a580-ec38-11e9-9531-82fac4a66b23.png)

**Comment by PaulWessel** [comment]
Yes, and for me also waypoints.sh fails.  But I ran all these fine before - I don't see any changes to pslegend since then?

**Comment by seisman** [comment]
waypoints.sh works for me. The insetlegend.sh failure may be related to https://github.com/GenericMappingTools/gmt/pull/1784?

**Comment by PaulWessel** [comment]
Will see; yes might and the new might be the correct one.
