### ISSUE TITLE
Exactly determine legend width

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1790]
**Description of the desired feature**

Currently, the width of a legend must be specified, while the legend height is computed automatically. This leads to tedious trial and error to get an acceptable width. I propose to do the exact calculation in _PostScript_.

**Are you willing to help implement and maintain this feature?** Yes

As we scan the legend _specfile_ we can call _PSL_deftextdim_ on all labels and update the widest string dimension. This PS variable can then be used to draw the correct legend box directly in _PostScript_.

**Comment by PaulWessel** [comment]
Auto-width cannot be used if paragraph text is set, and at least initially I will only allow **N** = 1.

**Comment by PaulWessel** [comment]
I am close to wrapping this up.  It is working for those cases where only legend codes **A, C, D, G, H**, and **S** are used (i.e., no multi-column legends). This is all done in _PostScript_ by measuring text lengths and doing some math there.  I will have to rewrite all of pslegend to make it work for the general case, so that is in the future, but the bulk of legends are quick, 1-column ones and they can now be typeset perfectly regardless of fonts or text content, especially those set via **-l**.

This brings up one remaining technical issue.  See attached sketch of how our formatting works:

![IMG_0803](https://user-images.githubusercontent.com/26473567/66707169-21764180-ecd8-11e9-901d-9d0034d30fa8.jpg)

The distance from the clearance to the center of the symbol (_dx1_ = 1s) is an argument to the legend **S** code but if given "-" we set it to the symbol size.  Same with distance from clearance to start of symbol label (_dx2_ = 2s); if not specified it defaults to 2 x symbol size.  However, with exact text computations the symbol label will end exactly at the far right clearance line.  Thus, visually it seems there is more clearance on the left side than on the right side.  One solution is to change the default for _dx1_ to be 0.5 x symbol size and let _dx2_ = 1.5 x symbol size. Symbol size here means the max size in the legend.

Below are examples of this with the 1x, 2x version (first) and the 0.5x, 1.5x version next:
![2x](https://user-images.githubusercontent.com/26473567/66707263-6f3f7980-ecd9-11e9-848b-214ef049c24c.png)
![1 5x](https://user-images.githubusercontent.com/26473567/66707266-71a1d380-ecd9-11e9-939e-235a25b09dac.png)

The largest symbol is the line, hence it seems perfect in this case.  My vote is for the 0.5, 1.5 scheme. Thoughts @seisman and @joa-quim ?

Finally, the hardwired settings for **-l**: white filled legend box, black pen outline at 1p, and 0.2 cm offset from justification point. Do we leave things that way or do we introduce two new GMT defaults:

- PS_LEGEND = +o2c
- PS_PANEL = +gwhite+p1p

so that users can override them?  Surely those settings are not ideal for all tasks?

**Comment by seisman** [comment]
I like the 0.5, 1.5 scheme, too. 

As for the two new GMT defaults, I don't think they're necessary. If users are not satisfied with the default legend box, they still can call `gmt legend` to get a better legend, right?

**Comment by PaulWessel** [comment]
Yes

**Comment by joa-quim** [comment]
I'm hesitant about the two new GMT defaults. The **-l** is much simpler than the ``legend`` module. It would be annoying having to resort to ``legend`` if one would want to change the background or the clearance when making a poster. I'm normally very reluctant in adding more defaults, but maybe these are for a very good cause.

**Comment by PaulWessel** [comment]
I think we will wait to see the reception and use.  We can always add them later if there is huge demand, versus removing things not used. FYI, you can use the -l with explicit call to legend and you can use -Tfile to save the spec file and make manual improvements if you want, so I think we have everything covered for now.  So the last thing I added was the+l[<code>/]<label> which mimics the L code.  With that I think we are good to go.  Once the server is up later today I will run tests etc.  But I think the 0.5, 1.5 scale works for the auto-spacing and the -F +i +s now also works with PostScript text width stuff if called from legend.

**Comment by joa-quim** [comment]
Not directly related but it would be nice to have an easy way to combine symbols and lines like in this plot
![01841970df81ac53fb1d71ef12b06a557b9200f1](https://user-images.githubusercontent.com/537321/66722832-1e7b6e00-ee0a-11e9-9ff3-31f66952c543.png)

**Comment by PaulWessel** [comment]
Partly a problem that plot has yet to be rewritten to ingest the datafile, then have ability to plot both lines and points.  I think we can do the legend by adding a **+g**_gap_ with the **-l** when you plot the second part (say the symbols) which will move the current point back up by gap and thus plot on top of the previous (line) symbol.  While it normally takes units (e.g., 0.45c, 0.2i) I want to add the unit "l" for linespacing.  So **+g**-1l would wind back exactly one line, which is what we want.

**Comment by PaulWessel** [comment]
Turns out we already added that a while back:

`  height += (txt_a[strlen(txt_a)-1] == 'l') ? atoi (txt_a) * one_line_spacing : gmt_M_to_inch (GMT, txt_a);
`

so **l** is already a valid unit.  We should try to see if this works for such combined symbols.

**Comment by PaulWessel** [comment]
So adding **+g**-1l should work for such things.

**Comment by joa-quim** [comment]
Almost, but too much jumping
```
gmt begin two png
  gmt subplot begin 2x1 -Fs7i/3i
    gmt plot -R0/7/3/7 -B @Table_5_11.txt -Sc0.15i -Glightgreen -Wfaint -lApples+hLEGEND+f16p+d -c0
    gmt plot @Table_5_11.txt -W1.5p,gray -l"My Lines"
    gmt plot @Table_5_11.txt -St0.15i -Gorange -lOranges+g-1l 
    gmt plot -R0/7/3/7 -B @Table_5_11.txt -Sc0.15i -Glightgreen -Wfaint -lApples+hLEGEND+f16p+d+x2.0 -c1
    gmt plot @Table_5_11.txt -W1.5p,gray -l"My Lines"
    gmt plot @Table_5_11.txt -St0.15i -Gred -lRed
  gmt subplot end
gmt end show
```
![two](https://user-images.githubusercontent.com/537321/66723860-483a9200-ee16-11e9-8827-157310caeff5.png)

**Comment by PaulWessel** [comment]
Because parse -l did not know about the l unit... will fix.

**Comment by PaulWessel** [comment]
OK, after fixing that and running

```
gmt begin two png
    gmt plot -R0/7/3/7 -B Table_5_11.txt -Sc0.15i -Glightgreen -Wfaint -l"My Trend"+hLEGEND+f16p+d
    gmt plot Table_5_11.txt -W1.5p,gray -l+g-1l+s0.25i
    gmt plot Table_5_11.txt -St0.15i -Gorange -l+g-1l 
gmt end show
```

I get perfection:

![two](https://user-images.githubusercontent.com/26473567/66724020-4ba12f80-edbc-11e9-9380-21d81718a574.png)

When plot can do more than one thing (e.g., both line and symbol) then the corresponding **-l** will do the **+g** automatically.

**Comment by joa-quim** [comment]
🥇
