### ISSUE TITLE
Memory files are not downloadable

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#1793]
Today I had this warning (an a looooong delay in the image display)
```
julia> imshow(img, colorbar=true)
grdimage [ERROR]: Unable to download file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
grdimage [ERROR]: Libcurl Error: Couldn't resolve host name
grdimage [ERROR]: Failed to get remote file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
psscale [ERROR]: Unable to download file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
psscale [ERROR]: Libcurl Error: Couldn't resolve host name
psscale [ERROR]: Failed to get remote file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
```

It turns out that it happens because in-memory file names start with ``@`` and that it apparently triggers the call to ``gmt_download_file_if_not_found()``.
![Capture1](https://user-images.githubusercontent.com/537321/66703465-d6295680-ed0a-11e9-8369-e6252e959285.PNG)

The cure is probably to add a test on the ``input`` var in ``gmt_api`` L7119 that the call is executed only when it doesn't start with ``@GMTAPI@``

**Comment by seisman** [comment]
I can't open this file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt via browsers. Possibly something wrong with the gmt server?

**Comment by joa-quim** [comment]
Maybe, but that's a totally separate issue. The point here is that it should not had tried to download anything in first place.

**Comment by PaulWessel** [comment]
Power out in POST building due to AC repair so possibly server was down.  We do not try to download @GMTAPI files.

**Comment by joa-quim** [comment]
The messages from the julia console says that it . was trying to download ``gmt_hash_server.txt``. Why?

**Comment by PaulWessel** [comment]
GMT will **always** try to do that, at most once a day.  That is how we know files have changed on the server.  That is how the remote file stuff works.

**Comment by PaulWessel** [comment]
Still down.

> pwessel@macnut:~-> ping gmtserver.soest.hawaii.edu
> PING gmtserver.soest.hawaii.edu (128.171.156.218): 56 data bytes
> Request timeout for icmp_seq 0
> Request timeout for icmp_seq 1
>

**Comment by joa-quim** [comment]
So, from this experience if the server is down and user is connected then ALL gmt commands will take a long time to run (until it gives up trying to download that file).

Correction, "when run from Julia (and bet the other externals)". See (In third run I switched to Airplane mode).
(have to make the dinner-break)

```
julia> tic();imshow(rand(128,128));toc()
grdimage [ERROR]: Unable to download file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
grdimage [ERROR]: Libcurl Error: Couldn't connect to server
grdimage [ERROR]: Failed to get remote file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
elapsed time: 21.687673201 seconds
21.687673201

julia> tic();imshow(rand(128,128));toc()
grdimage [ERROR]: Unable to download file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
grdimage [ERROR]: Libcurl Error: Couldn't connect to server
grdimage [ERROR]: Failed to get remote file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
elapsed time: 21.7012088 seconds
21.7012088

julia> tic();imshow(rand(128,128));toc()
grdimage [ERROR]: Unable to download file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
grdimage [ERROR]: Libcurl Error: Couldn't resolve host name
grdimage [ERROR]: Failed to get remote file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
elapsed time: 0.2554539 seconds
0.2554539
```

**Comment by PaulWessel** [comment]
So we could time that command and if it takes > 10 seconds we can want that server is possibly down and they can set GMT_DATA_SERVER_LIMIT=0 for a while.  In fairness, the server is not down that often (this is a major AC repair that affects all the labs as well so only done because it had to be done).  Having 99.99999% uptime would be expensive for an open source data repo.

**Comment by PaulWessel** [comment]
Or better, if > 10 seconds we mark the file as updated and do try for another 24 hours.

**Comment by joa-quim** [comment]
Yes, better. And you can test right now. PR's are failing tests because of this issue.
