### ISSUE TITLE
Does GMT depends on lapack and blas?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1799]
The [building instruction](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md#build-and-runtime-dependencies) mentions that lapack and blas are optional for more capabilities. I tried to search "lapack" and "blas" in the source codes, but found nothing related. Does GMT really depends on these two libraries?

**Comment by joa-quim** [comment]
Yes, it does. Some inversion functions use lapack it it finds it. However, lapack it's a quite heavy dependency (>40 Mb for a full build on Win) for the limited usage we have for it. And on Windows I'm not even able to build GMT with VS2019 and my mingw lapack built lib.

**Comment by PaulWessel** [comment]
FYI, GMT has two Ax=b solvers: gmt_gaussjordan and gmt_svdcmp (which does a SVD then gmt_solve_svd solves for x).  We also have gmt_matrix_matrix_mult.  Some of these call Lapack/Accellerate functions: dgemm_, dsyev.  I believe for now these are only used by greenspliine and potential's gpsgridder.

**Comment by PaulWessel** [comment]
It is an optional prerequisite if you want to use those tools effectively.

**Comment by seisman** [comment]
What about blas? I can find many `HAVE_LAPACK` macros in the source codes, but almost can't find `HAVE_BLAS`? Is blas a GMT dependency?

**Comment by PaulWessel** [comment]
Dont quite remember because on macOS none of that matters (we have accelerate), but I think for Linux and maybe Win, Lapack depends on BLAS.  Not sure what happens if we remove that dependency - I am pretty sure I did test some of these things on Linux, but cannot recall.
