### ISSUE TITLE
RPM repository for Fedora/CentOS/RHEL

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1800]
As we all know, many Linux distros provide GMT binary packages which can be easily installed via package managers `apt-get` or `yum`. However, they are usually way behind packaging a recent version. In order to use the latest GMT releases, linux users usually have to build GMT source codes. Non-experienced users may spend a lot of time to build GMT, and may be unwilling to update/rebuild it when new versions are available.

The [Fedora copr system](https://copr.fedorainfracloud.org/) provides an easy way to setup a personal repository for Fedora/RHEL/CentOS. I've created a [personal RPM repository (seisman/gmt)](https://copr.fedorainfracloud.org/coprs/seisman/gmt/), and the only things I need to provide are the specfiles, which are available from https://github.com/seisman/gmt-rpm. I think this repository can greatly improve the installation experience for Fedora/CentOS/RHEL users.

For Fedora users, they can run following commands to install the latest GMT release (currenly it's 6.0.0rc4):

	# enable the RPM repository
	dnf copr enable seisman/gmt

	# Install the latest GMT provided by the RPM repository
	dnf install gmt

	# Update to the latest GMT
	dnf update gmt

For RHEL/CentOS users, it's slightly different but also very easy.

	# install epel-release and the copr plugin for yum
	yum install epel-release yum-plugin-copr

	# enable the RPM repository
	yum copr enable seisman/gmt

	# Install and update GMT
	yum install gmt
	yum update gmt

Currenly, the `seisman/gmt` repository provides following three packages:

- `gmt`: 6.0.0rc4
- `dcw-gmt`: 1.1.4
- `gshhg-gmt`: 2.3.7

while Fedora and EPEL prefer to split each into multiple packages:

- `GMT`, `GMT-common`, `GMT-devel`, `GMT-doc`: 5.4.5
- `dcw-gmt`: 1.1.1
- `gshhg-gmt-nc4`, `gshhg-gmt-nc4-full`, `gshhg-gmt-nc4-high`: 2.3.3

Since both Fedora and the seisman/gmt repository provide `dcw-gmt`, the newer one from
seisman/gmt has higher priority. But for GMT and GSHHG, the package names
are different. 

Questions:

1. What do you think about the RPM repository? 
2. Can it be the "official" GMT repository for Fedora/RHEL/CentOS and be written into the install instructions?
3. After enabling the seisman/gmt repository, there will be two GMT packages, `gmt` from seisman/gmt and `GMT` from Fedora, which may cause some confusion. I can also follow the Fedora conventions and split it into several smaller packages. Any suggestions?

**Comment by PaulWessel** [comment]
I think splitting gmt into several smaller package is dumb; it made sense in the early 2000s.  Just more work to make and install.  I like the idea of the rpm repo tough since the official ones are so far behind. Might it be possible to do something similar for ubuntu?  Finally, if we were to do this it would be better, if possible, to have an account called genericmappingtools or similar instead of your personal account, and even add your gmt-rpm stuff under the GenericMappingTools family?

**Comment by joa-quim** [comment]
> Might it be possible to do something similar for ubuntu?

PPA's?
https://askubuntu.com/questions/4983/what-are-ppas-and-how-do-i-use-them/4990#4990

**Comment by PaulWessel** [comment]
I worry about 9 year old posts on the internet.  We need something newer to follow.

**Comment by seisman** [comment]
> Might it be possible to do something similar for ubuntu? 

Yes, PPA is the solution for Ubuntu/Debian, although I don't know how PPA works.

> if we were to do this it would be better, if possible, to have an account called genericmappingtools or similar instead of your personal account

Yes, I agree. A repository named `genericmappingtools/gmt` looks more trustworthy. The problem is, as far as I can see, the copr system doesn't support organization accounts. Someone (you or me) have to register a "genericmappingtools" account and configure the `genericmappingtools/gmt` repository (it's easy), then I and other maintainers can request admin permissions to the repository.

> and even add your gmt-rpm stuff under the GenericMappingTools family?

Yes, I'll move gmt-rpm to the GenericMappingTools family after some testing.

BTW, `gmt` from `seisman/gmt` conflicts with `GMT` from Fedora/EPEL. If someone already has `gmt` installed, then installing `GMT` will give following errors and stop the installation, so it won't mess up their operation system.
```
$ yum install GMT
Loaded plugins: copr, fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.trouble-free.net
 * epel: epel.mirror.constant.com
 * extras: mirror.trouble-free.net
 * updates: mirror.fileplanet.com
Resolving Dependencies
--> Running transaction check
---> Package GMT.x86_64 0:5.4.4-3.el7 will be installed
--> Processing Dependency: GMT-common = 5.4.4-3.el7 for package: GMT-5.4.4-3.el7.x86_64
--> Processing Dependency: gshhg-gmt-nc4 for package: GMT-5.4.4-3.el7.x86_64
--> Running transaction check
---> Package GMT-common.noarch 0:5.4.4-3.el7 will be installed
---> Package gshhg-gmt-nc4.noarch 0:2.3.3-1.el7 will be installed
--> Processing Conflict: gmt-6.0.0rc4-1.el7.x86_64 conflicts GMT
--> Processing Conflict: gmt-6.0.0rc4-1.el7.x86_64 conflicts GMT-common
--> Processing Conflict: gshhg-gmt-2.3.7-1.el7.noarch conflicts gshhg-gmt-nc4
--> Finished Dependency Resolution
Error: gshhg-gmt conflicts with gshhg-gmt-nc4-2.3.3-1.el7.noarch
Error: gmt conflicts with GMT-common-5.4.4-3.el7.noarch
Error: gmt conflicts with GMT-5.4.4-3.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by PaulWessel** [comment]
OK, since you already have the knowledge, perhaps you can make that genericmappingtools account?
Presumably we can add instructions to our page describing the RPMs and PPAs that users may need to uninstall any older packages provided by their bistro.

**Comment by seisman** [comment]
I've moved my gmt-rpm repo to https://github.com/GenericMappingTools/gmt-rpm and created a [genericmappingtools account](https://copr.fedorainfracloud.org/coprs/genericmappingtools) in the copr system.

Closing this issue. More discussion in the https://github.com/GenericMappingTools/gmt-rpm repository.
