### ISSUE TITLE
Two failing tests

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1802]
```
1/3 Test #198: ex46/ex46.sh .....................***Failed    1.42 sec
Set GMT_SESSION_NAME = 92159
psxy [ERROR]: Could not find either custom symbol or EPS macro @sunglasses
psxy [ERROR]: Could not find custom symbol @sunglasses
ERROR: gmtest:57
memtrack errors: 0
exit status: 1
ERROR: ex46.sh:14
memtrack errors: 0
exit status: 1

2/3 Test #387: grdimage/readwrite_withgdal.sh ...***Failed    2.92 sec
/usr/bin/gm compare: image difference exceeds limit (0.0284896 > 0.003).
grdimage/readwrite_withgdal.ps: RMS Error = 0.0285 [FAIL]
memtrack errors: 0
exit status: 1
```

**Comment by PaulWessel** [comment]
Can confirm the failure for ex46.  Will try to have a look. @joa-quim, might the failure in readwrite_withgdal.sh be related to recent gdal image work you did? The PDF looks good but there are certainly some changes - please review and update PS if you think the new results are correct.

**Comment by joa-quim** [comment]
Yes, I said at the time that the original ps must be updated because now bands are written in reverse order (the test changed).
