### ISSUE TITLE
makecpt -E still fails from external interfaces

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#181]
```
julia> makecpt(rand(10,1), E="", C=:rainbow, Vd=1)
        makecpt  -Crainbow -E
makecpt [ERROR]: Syntax error -E option: Cannot decode value
```
The problem is that the ``#define THIS_MODULE_KEYS	">C},ED(,SD(,TD("`` so the input file lands on the **-E** option  and then the test
```
				Ctrl->E.active = true;
				if (opt->arg[0] && sscanf (opt->arg, "%d", &Ctrl->E.levels) != 1) {
					GMT_Report (GMT->parent, GMT_MSG_NORMAL, "Syntax error -E option: Cannot decode value\n");
					n_errors++;
				}
```
triggers the error (``opt->arg`` holds the filename pointer). However, the (simple) solution is not to change the ``MODULE_KEYS`` and replace for example ``ED(`` by ``>D(`` because then it hangs, apparently waiting for the input file to come in.

**Comment by PaulWessel** [comment]
Simplest fix is to (under the hood) replace -E with -E0 and -S with (new) -Sr and then it works.  Will test.
