### ISSUE TITLE
Increase curl timeout?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1810]
The Linux CI builds sometimes fail due to curl timeout, with error messages:
```
$ gmt grdimage @earth_relief_60m -JH10c -Baf -pdf map
Time spent = 5 seconds
gmt [ERROR]: Unable to download file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
gmt [ERROR]: Libcurl Error: Timeout was reached
gmt [ERROR]: GMT data server may be down - delay checking hash file for 24 hours
gmt [ERROR]: You can turn remote file download off by setting GMT_DATA_SERVER_LIMIT = 0.
gmt [ERROR]: Failed to get remote file https://oceania.generic-mapping-tools.org/gmt_hash_server.txt
gmt [ERROR]: Unable to obtain remote file @earth_relief_60m
grdimage [ERROR]: Error for input file: No such file (@earth_relief_60m.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
##[error]Bash exited with code '71'.
```

It's a little bit annoying. Maybe increase the curl timeout to 10 s?

**Comment by PaulWessel** [comment]
Perhaps my 5 second limit is a bit too tight then?  BTW I just removed that fprintf line about time spent from 6.  Since this will only happen once, perhaps make it 10 seconds?

**Comment by joa-quim** [comment]
I find it strange that 5 sec are not enough to dwl ``gmt_hash_server.txt``. But what we shouldn't have is a test that depends on a downloaded file.

**Comment by seisman** [comment]
I added the test `gmt grdimage @earth_relief_60m -JH10c -Baf -pdf map` because we once broke the remote file mechanism.

**Comment by PaulWessel** [comment]
I agre 5 seconds seems plenty but in real life we dont want network slowness to prevent a gmt command from working.  Since now, this test (if failing) is punted 24 hours down the road it seems OK to me to make it 10 seconds.  It will only happen once.

**Comment by seisman** [comment]
If you check the latest build log (https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=3261&view=results), you'll find that both the macOS and Windows builds pass, but the Linux build has the curl timeout. Is it possible a curl bug on Linux?

**Comment by joa-quim** [comment]
That's what make me suspect on the linux failure.

**Comment by PaulWessel** [comment]
Will have to run tests locally on Linux.  Maybe I can find time later today, or maybe you can?  I suspect slow CI, not libcurl bug.

**Comment by seisman** [comment]
It should be the slow CI. 

In this build (https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=3258&view=results), one of the Linux build passes, while the other one fails.

**Comment by PaulWessel** [comment]
Please change GMT_HASH_TIME_OUT in gmt_remote.c to 10L and see what happens.
