### ISSUE TITLE
Let movie make temporary files in a temp directory

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1812]
**Description of the desired feature**

Currently, movie **-N**_name_ does two things:

1. Sets the final name of the movie product (name.mp4 or name.gif)
2. Creates a subdir called name where all intermediate frame scripts and PNGs are placed

Having one option set two different settings is not always ideal.  For instance, automatic backup systems like TimeMachine or DropBox will start to sync those thousands of temporary files, causing various bottlenecks.  We need a way to separate the two settings and should introduce this now before 6.0 release.

A complication is that we also have **-W**_workdir_ which is a place where movie should look for data files.  This is marginally useful as is since one can always add to **DATA_DIR** any such directories, and GMT already has several directories it looks in anyway. Finally, movie already looks in the parent directory (where movie was started from), so having yet another option to specify a data directory seems unnecessary.

I propose we repurpose **-W** to set an actual work directory [default is current directory] where the _name_ sudirectory is created.  There is no backwards compatibility issues here since movie has not previously been part of a GMT distribution.

**Comment by PaulWessel** [comment]
Hi @seisman and @joa-quim, my student and I need to do something about this now - let me know if you have any concerns.

**Comment by joa-quim** [comment]
No concern

**Comment by seisman** [comment]
I'm OK with it.

**Comment by seisman** [comment]
Closed by #1815.
