### ISSUE TITLE
All animations fail on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1820]
And also ex22.sh

**Comment by PaulWessel** [comment]
Cannot tell why.  The log has lots of gmtserver failures but I dont see any details as to why it fails.  Are you able to run one locally under Windows and get some clues?  I will review the code changes in movie but since it works on macOS and Linux there must be something that is not quite the same for Windows.

**Comment by PaulWessel** [comment]
@joa-quim, can you test an animation and let me know if there is anything?

**Comment by seisman** [comment]
Just ran the anim02.sh, it doesn't report any error, but it also don't generate the PS file.

Below is part of the verbose messages.
```
movie [DEBUG]: Found file main.sh
movie [DEBUG]: Found file main.sh
movie [DEBUG]: Found file main.sh
movie [INFORMATION]: Paper dimensions: Width = 3.5i Height = 4.167i
movie [INFORMATION]: Pixel dimensions: 252 x 301
movie [DEBUG]: Look for file angles.txt in C:/Users/seisman/.gmt
movie [DEBUG]: Look for file angles.txt in C:/Users/seisman/.gmt/cache
movie [DEBUG]: Look for file angles.txt in C:/Users/seisman/.gmt/server
movie [DEBUG]: Look for file angles.txt in C:/Users/seisman/.gmt/server/srtm1
movie [DEBUG]: Look for file angles.txt in C:/Users/seisman/.gmt/server/srtm3
movie [INFORMATION]: Create parameter initiation script movie_init.sh
movie [INFORMATION]: Create preflight script movie_preflight.sh and execute it
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Object ID 0 : Registered Data Table File angles.txt as an Input resource with geometry Non-Geographical [n_objects = 1]
movie [DEBUG]: api_begin_io: Input resource access is now enabled [container]
movie [DEBUG]: api_import_dataset: Passed ID = 0 and mode = 0
movie [INFORMATION]: Reading Data Table from File angles.txt
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Found file angles.txt
movie [DEBUG]: Source col types: (Number,Number)
movie [DEBUG]: ASCII source scanned: Numerical columns: 2, Trailing text: N, Record type: Numerical only
movie [DEBUG]: GMT memory: Initialize 2 temporary column double arrays, each of length : 0
movie [DEBUG]: GMT_End_IO: Input resource access is now disabled
movie [INFORMATION]: Number of animation frames: 37
movie [INFORMATION]: Create individual parameter include files per frame for 37 frames
movie [INFORMATION]: Create master frame script movie_master.sh
movie [INFORMATION]: Single master plot (frame 0) built: anim_02.ps
movie [DEBUG]: Delete movie_master.sh
movie [DEBUG]: gmtapi_garbage_collection: Destroying object: C=0 A=1 ID=0 W=Input F=Data Table M=File S=Used P=2e9e4a8f3a0 N=angles.txt
movie (gmt_free_table): tried to free unallocated memory
movie [DEBUG]: GMTAPI_Garbage_Collection freed 1 memory objects
movie [DEBUG]: gmtapi_unregister_io: Unregistering object no 0 [n_objects = 0]
movie [DEBUG]: GMT memory: Free 2 temporary column arrays, each of length : 2097152
gmt.exe [DEBUG]: Entering GMT_Destroy_Session
```

**Comment by PaulWessel** [comment]
Please run movie with -Qs, then cd into the directory with the scripts and run one of the scripts, e.g.,

stuff_frame.sh 20

20 is just a particular frame, depending on # of frames you may use 020.

**Comment by joa-quim** [comment]
I'll try to look into this in an hour but I'm f with WSL. Now Windows/System32/bash.exe manages to get in front of everything and I can't run the tests. Even if I move it out of the may ctest complains that it doesn't find it. HTF does it knows that it even existed?

**Comment by seisman** [comment]
Found a small bug. The movie_frame.sh shows:
```
export GMT_SESSION_NAME=$$
GMT_END_SHOW=off
```
It should be:
```
export GMT_SESSION_NAME=$$
export GMT_END_SHOW=off
```

**Comment by PaulWessel** [comment]
I see it, fixing now - just running local tests first.

**Comment by joa-quim** [comment]
Run ``anim_02.sh`` and it worked fine. But also got this error message

```
bash anim_02.sh
gmt [ERROR]: Failed to remove C:/Users/joaqu/.gmt/server/gmt_hash_server.txt.new! [remove error: No such file or directory]
```

**Comment by PaulWessel** [comment]
OK, will need to improve that to check if the file exists first.

**Comment by seisman** [comment]
Still doesn't work. No errors but also no PS generated.

**Comment by PaulWessel** [comment]
Is the test running the bash version in WIndows bash for git on CI? So I should be able to reproduce this manually running bash for git on my Win10 Dell?

**Comment by seisman** [comment]
Yes, we use bash for git on CI.

**Comment by PaulWessel** [comment]
Hm, but I cannot build for Windows.  Anyway you can run a small example movie like the first example on the movie man page but add -Qs and examine or tar up the content of that directory?

**Comment by seisman** [comment]
Please see the attached. [globe.zip](https://github.com/GenericMappingTools/gmt/files/3737059/globe.zip)

**Comment by joa-quim** [comment]
It works for me, but runs only in a single core. Even if I add a **-x** to the movie command.

**Comment by seisman** [comment]
Running one frame gives me following error:
![image](https://user-images.githubusercontent.com/3974108/67030962-8e297b80-f0de-11e9-811f-88153f9fd9e3.png)

The movie_frame.sh can't source `movie_init.sh`, but it's definitely in the current directory.

Then I change the movie_frame.sh to:
```
source ./movie_init.sh
source ./movie_params_$1.sh
```
it works.

**Comment by seisman** [comment]
**Update:** `bash movie_frame.sh 000` works but `sh movie_frame.sh 000` fails.

**Comment by seisman** [comment]
Sorry if my comments above confuse you.

The example in the gmt movie man page works, but the anim01 doesn't work. Please see the attached tarball for anim01. [anim_01.zip](https://github.com/GenericMappingTools/gmt/files/3740651/anim_01.zip)

The bug is caused by the last few lines of the movie_master.sh script:
```
# Move master file up to top directory and cd up one level
mv -f anim_01.ps C:\gmt\doc\examples\anim01
cd ..
```
I think we need to change the path separator `/`.

**Comment by PaulWessel** [comment]
So getcw returns a path with backslash but then the shell cannot process them... Brilliant.

Of course, we have had this before and hence the gmt_replace_backslash_in_path function.  I will apply that to the workdir path as well.

**Comment by joa-quim** [comment]
Are you guys getting multi-processor runs when running the movie examples?
It certainly does not work on Windows when running bash scripts, but I think we tested and it worked when running batch files (there, we use ``cmd /B``)

**Comment by PaulWessel** [comment]
If bash script is passed, on windows, we set GMT_SESSION_NAME=$$ so that part should work in bash.  Once we make rc5 I should be able to install on my Dell and try in git bash.  Should be multi-core runs if gmt --show-cores returns > 1 no ?

**Comment by seisman** [comment]
The bash animations now pass on Windows CI.

**Comment by PaulWessel** [comment]
I will drink to that, except I will be teaching first...
Can you confirm that many cores are being used - i.e., @joa-quim's point?

**Comment by seisman** [comment]
Multi-core works on macOS, but not sure if it works on Windows, as my Windows is in a single-core virtual machine.

**Comment by PaulWessel** [comment]
OK, I can test on my Dell with rc4 for that question I think

**Comment by PaulWessel** [comment]
While slow, my Dell reports 7 available core (we subtract one for the movie process itself) and I can see it starts 7 jobs at the same time, then sits there for a while, then start 7 more.  So I think all is working well - closing this issue?

**Comment by joa-quim** [comment]
The problem is that the loop
```
		while (n_frames_not_started && n_cores_unused) {	/* Launch new jobs if possible */
			sprintf (cmd, "%s %s %*.*d &", sc_call[Ctrl->In.mode], main_file, precision, precision, frame);

			GMT_Report (API, GMT_MSG_DEBUG, "Launch script for frame %*.*d\n", precision, precision, frame);
			if ((error = system (cmd))) {
				GMT_Report (API, GMT_MSG_NORMAL, "Running script %s returned error %d - aborting.\n", cmd, error);
				Return (GMT_RUNTIME_ERROR);
			}
			status[frame].started = true;	/* We have now launched this frame job */
			frame++;			/* Advance to next frame for next launch */
			i_frame++;			/* Advance to next frame for next launch */
			n_frames_not_started--;		/* One less frame remaining */
			n_cores_unused--;		/* This core is now busy */
		}
```
is run sequentially. Only when the ``if ((error = system (cmd))) `` call finishes is a new one started. I can confirm with Task Manger that only ~1 core is being used.

**Comment by PaulWessel** [comment]
Hm, if we are talking bash then that & puts it in the background.  It is not sitting there to complete the job since it is launching 7 such system calls and then waits for completion.  I am running bit bash in Win 10.  Are you talking Windows batch now?

**Comment by PaulWessel** [comment]
BTW, I agree that the & etc is probably not what to do for batch files under Windows.

**Comment by joa-quim** [comment]
No, I'm talking ``anim_02.sh``. With -Vd I can perfectly see that the lines ``Launch script for frame XX`` take about 1-2 sec to print and the ones ``Frame 00 of 37 completed`` to ``Frame 10 of 37 completed`` are printed instantaneously. That is it waits till the 11 jobs are run, ONE by ONE, and then prints de info for the 11 all at once.

I'm running Git bash. 

```
movie [INFORMATION]: Build frames using 11 cores
movie [INFORMATION]: Execute movie frame scripts in parallel
movie [DEBUG]: Launch script for frame 00
movie [DEBUG]: Launch script for frame 01
movie [DEBUG]: Launch script for frame 02
movie [DEBUG]: Launch script for frame 03
movie [DEBUG]: Launch script for frame 04
movie [DEBUG]: Launch script for frame 05
movie [DEBUG]: Launch script for frame 06
movie [DEBUG]: Launch script for frame 07
movie [DEBUG]: Launch script for frame 08
movie [DEBUG]: Launch script for frame 09
movie [DEBUG]: Launch script for frame 10
movie [INFORMATION]: Frame 00 of 37 completed [  2.7 %]
movie [INFORMATION]: Frame 01 of 37 completed [  5.4 %]
movie [INFORMATION]: Frame 02 of 37 completed [  8.1 %]
movie [INFORMATION]: Frame 03 of 37 completed [ 10.8 %]
movie [INFORMATION]: Frame 04 of 37 completed [ 13.5 %]
movie [INFORMATION]: Frame 05 of 37 completed [ 16.2 %]
movie [INFORMATION]: Frame 06 of 37 completed [ 18.9 %]
movie [INFORMATION]: Frame 07 of 37 completed [ 21.6 %]
movie [INFORMATION]: Frame 08 of 37 completed [ 24.3 %]
movie [INFORMATION]: Frame 09 of 37 completed [ 27.0 %]
movie [INFORMATION]: Frame 10 of 37 completed [ 29.7 %]
```

**Comment by PaulWessel** [comment]
So is this a flaw in git bash that it is not really interacting with system calls that can run in the background then?  Since it is bash we are doing the right calls, but if system waits for a return because there cannot be background jobs...  Sounds like Windows (batch) can handle backgrounds jobs but not git bash?

**Comment by joa-quim** [comment]
Possibly.

**Comment by PaulWessel** [comment]
BTW, I do not have gm on Windows and it printed an error message but it was not caught properly by the gmt_check_executable function so it kept running, producing the PNG then finally complied again of no gm.

**Comment by PaulWessel** [comment]
Since you can build GMT on win and run in git bash, could you try to figure out why gmt_check_execytabke fails to detect that gm is not found? It prints 'gm' is not recognized as an internal or external command, etc.

**Comment by PaulWessel** [comment]
I am able to place a script in the background on the git bash command and it launches the process (it prints another PID), so it clearly can.  However, when we call system ("bash job &") in movie running in git bash, what "system" is being executed is unclear to me.

**Comment by PaulWessel** [comment]
Googleing for what system does on Window machine seems to agree that it will call cmd.exe which apparently can run bash (and the command string we generate on windows for bash starts with bash).  However, the trailing "&" may not be interpreted the way we expect.  It may be seen by cmd.exe and ignored - which makes sense since we see the jobs running one at the time.

What to do? We use start /B for pure batch which is passed to cmd.exe as well, presumably.  Should we try to make a command string for bash (#fdef WIN) that writes

start /B bash movie_frame.sh 020

instead of

bash movie_frame.sh 020 &

What do you guys thinK?  Could any of you try this?  It would mean replacing line 1656 with
```

#ifdef WIN32
  sprintf (cmd, "start /B %s %*.*d", main_file, precision, precision, frame);
#else 
  sprintf (cmd, "%s %s %*.*d &", sc_call[Ctrl->In.mode], main_file, precision, precision, frame);
#endif

```

**Comment by joa-quim** [comment]
About the ``gm`` issue. If I move ``gm.exe`` out of the way, then it correctly fails

```
movie [ERROR]: GraphicsMagick is not installed or not in your executable path - cannot build animated GIF.
```

**Comment by PaulWessel** [comment]
Hm, not for me (rc4).

**Comment by joa-quim** [comment]
Back to the parallel. I suspected something of that nature. And indeed we can make it work but need to make ``cmd`` call ``bash``. After all, ``bash`` is nothing more then another Win prog (except the fck WSL bash.exe that behaves mysteriously).

With this, it uses all cores

```
#ifdef WIN32
			if (Ctrl->In.mode < 2)		/* A bash or sh run from Windows. Need to call via "start" to get parallel */
				sprintf (cmd, "start /B %s %s %*.*d", sc_call[Ctrl->In.mode], main_file, precision, precision, frame);
			else						/* Runing batch, so no need for the above trick */
				sprintf (cmd, "%s %s %*.*d &", sc_call[Ctrl->In.mode], main_file, precision, precision, frame);
#else 
			sprintf (cmd, "%s %s %*.*d &", sc_call[Ctrl->In.mode], main_file, precision, precision, frame);
#endif
```

**Comment by PaulWessel** [comment]
Well I am smarter than your average bear, no?
Can you commit this - I am teaching lab soon.

**Comment by seisman** [comment]
I believe the issue has been fixed. Closing.
