### ISSUE TITLE
Using auto legend with OGR/GMT format polygon file

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#1826]
I was testing the new auto legend functionality and became confused when trying to plot an OGR/GMT format polygon file (i.e. with ``# @VGMT1.0 @GPOLYGON`` in the header). This entry was not added to the legend. When I removed the header, it showed up. 

Maybe specify in the docs that auto legend only works when dealing with lines/points (if that is the case)? Or trick GMT by malforming the OGR/GMT file header.

**Comment by abanbj** [comment]
Wouldnt this functionality also be nice for e.g. ``grdcontour``?

```
gmt grdcontour [..] -l"Contour interval 500 m."
```

**Comment by PaulWessel** [comment]
I wonder for polygons, perhaps we place a square symbol with the same color/outline as the polygon and using the size modifier for the size?  That seems like a reasonable resolution, no? Agree, @seisman and @joa-quim?

**Comment by joa-quim** [comment]
I think we should REALLY decree a code freeze. To release 6.0.0 next Friday and with a RC5 in between, there is no time for more features now.  And, BTW, we should aim to release the the RC5 during the week-end.

**Comment by PaulWessel** [comment]
OK, I am fine with that.  I will turn my PR into a WIP for master.

**Comment by abanbj** [comment]
But the polygons in a dataset may be very very diffent. What then?

**Comment by abanbj** [comment]
Totally agree. Just trying to trick you into making brilliant ideas.

**Comment by PaulWessel** [comment]
I can imagine labels coming from aspatial values in a shape file but we want to think about this some more before rushing out a solution.

**Comment by abanbj** [comment]
Yes, totally with you.
