### ISSUE TITLE
Are contours oriented consistently?

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#1828]
Are contours line strings oriented consistently? Directly from the man page of ``gdal_contour`` (https://gdal.org/programs/gdal_contour.html);

```
The contour line-strings are oriented consistently and the high side will be on the right, i.e. a line string goes clockwise around a top
```

It would be nice if this could be added to the ``grdcontour`` man page.

**Comment by PaulWessel** [comment]
I think we place contours so they are readable from below, so the base angle is in the -90/+90 range.  Is that what you mean?

**Comment by abanbj** [comment]
Does that mean that all contours are either clockwise or counter clockwise?

**Comment by abanbj** [comment]
(Sorry to answer you with another question)

**Comment by abanbj** [comment]
I'm asking you because of this: https://landscapearchaeology.org/2018/tanaka-contour-lines/

(The 'Contour' section)

**Comment by abanbj** [comment]
I'm asking because of this (https://landscapearchaeology.org/2018/tanaka-contour-lines/) from the **Contours** section.

```
Contour shading requires consistent contour direction, that is, they should all be either clockwise or counter-clockwise, but not both. (There is one exception, the bottom level contours should be in an opposite direction, but that’s a detail.)
```

**Comment by PaulWessel** [comment]
Contours are only oriented when written to files via **-D** when **-F** is used.

**Comment by abanbj** [comment]
Any reason why ``-F`` should not be dropped and not do it like ``gdal``?
