### ISSUE TITLE
pslegend crashes after about 200 lines of inputfile

### ISSUE THREAD

**Issue by MatzIT** [GenericMappingTools/gmt#1847]
When invoking pslegend with an inputfile of roughly more than 200 lines, pslegend crashes with a segmentation fault, that is triggered by pstext.
The pslegend created PostScript is completed, but pstext fails early.

pslegend version: 6.1.0_7ead9ce_2019.10.07
pstext version: 6.1.0_7ead9ce_2019.10.07

The call that fails: pslegend /tmp/airportlist-00 -Dx0/0/2.0c/14.8063c/BL/0.25c/4.83c -F+gwhite+p1p,18/71/123 -C1.5p/2p -K -O

The inputfile is attached (with .txt ending to allow the upload of the file)

[airportlist-00.txt](https://github.com/GenericMappingTools/gmt/files/3747203/airportlist-00.txt)

The relevant part of the output that shows the invocation of pslegend.
% PostScript produced by:
%@GMT: gmt pslegend /tmp/airportlist-00 -Dx0/0/2.0c/14.8063c/BL/0.25c/4.83c -F+gwhite+p1p,18/71/123 -C1.5p/2p -K -O
%@PROJ: xy 0.00000000 0.78740157 0.00000000 5.82925197 0.000 0.787 0.000 5.829 +xy

The relevant stdout output of the pstext part:
% PostScript produced by:
%@GMT: gmt pstext -R0/0.787402/0/5.82925 -Jx1i -O -K -N -F+f+j @GMTAPI@-000001 --GMT_HISTORY=false
%@PROJ: xy 0.00000000 0.78740200 0.00000000 5.82925000 0.000 0.787 0.000 5.829 +xy
%%BeginObject PSL_Layer_2
0 setlinecap
0 setlinejoin
3.32551 setmiterlimit
ERROR: Caught signal number 11 (Segmentation fault) at
/lib/x86_64-linux-gnu/libc.so.6(+0xb6ba0)[0x7fcb2f22eba0]
[0x0]
Stack backtrace:
/opt/gmt/lib/libgmt.so.6(sig_handler+0x2b1)[0x7fcb2f7c1151]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fcb2f57b890]
/lib/x86_64-linux-gnu/libc.so.6(+0xb6ba0)[0x7fcb2f22eba0]
/opt/gmt/lib/libgmt.so.6(api_get_record_dataset+0xe1)[0x7fcb2f7ccef1]
/opt/gmt/lib/libgmt.so.6(GMT_Get_Record+0x70)[0x7fcb2f7cee70]
/opt/gmt/lib/libgmt.so.6(GMT_pstext+0x1add)[0x7fcb2fa6d1cd]
/opt/gmt/lib/libgmt.so.6(GMT_Call_Module+0x185)[0x7fcb2f7d8df5]
/opt/gmt/lib/libgmt.so.6(GMT_pslegend+0x313f)[0x7fcb2fa873df]
/opt/gmt/lib/libgmt.so.6(GMT_Call_Module+0x185)[0x7fcb2f7d8df5]
gmt(main+0x96a)[0x5643d3f9787a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fcb2f199b97]
gmt(_start+0x2a)[0x5643d3f97c1a]

OS: Ubuntu 18.04 Server
GMT: 6.1.0_7ead9ce_2019.10.07

**Comment by PaulWessel** [comment]
Can confirm the crash - now looking to see why.

**Comment by PaulWessel** [comment]
Closed as fixed
