### ISSUE TITLE
gmt which -Gl should report full path

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1867]
Running `gmt which -Gl @earth_relief_30m` returns:
```
$ gmt which -Gl @earth_relief_30m
earth_relief_30m.grd
```
But the `gmtwhich` manpage says `Find full path to specified files`.

**Comment by PaulWessel** [comment]
Hm, not sure if that is a bug or a feature.  Do we really want to report the full path to a local file? I assume in your case that file exists in the local dir, yes?

**Comment by seisman** [comment]
Yes, seems useless to report the full path here. We probably need to update the description of the manpage, since gmtwhich doesn't always report full path.

**Comment by PaulWessel** [comment]
I agree.  I can do this in a few hours or you can do it now if you want.
