### ISSUE TITLE
-B primary/secondary mix

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#187]
We have [this example](https://gmt.soest.hawaii.edu/doc/latest/GMT_Docs.html#general-features) in the CookBook for custom axes where the the figure is made up of two psbasemap calls. But it should be possible to do the same in a single call, namely:
```
psbasemap -R416/542/0/6.2831852 -JX-8/4 -Bsxcxannots.txt -Bpycyannots.txt -Bpxa25f5g25+u" Ma"
-BWS+glightblue  --MAP_ANNOT_OFFSET_SECONDARY=10p --MAP_GRID_PEN_SECONDARY=2p -P > liox.ps
```
Note that the ``-Bpx`` and ``-Bsx`` ar well separated but the result is

![gmtjl_tmp](https://user-images.githubusercontent.com/537321/48913808-6ea7b580-ee71-11e8-9955-83114396023e.png)

**Comment by PaulWessel** [comment]
Nice weekend to work on this but of course it is tax man visit to day so that makes less time available.  Will see.

**Comment by remkos** [comment]
No regarded relevant any more.
