### ISSUE TITLE
grdcontour/varpens.sh fails on master branch

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1873]
grdcontour/varpens.sh fails on master branch but passes on 6.0 branch.

gm diff file:

![image](https://user-images.githubusercontent.com/3974108/67292113-91db4a80-f4b0-11e9-8003-51db8c9bbdb7.png)

**Comment by PaulWessel** [comment]
Has to be grid differences no? This is not caused by a bug in plotting but either the PS orig is somehow wrong or the plot uses the wrong grid?

**Comment by seisman** [comment]
Looks like grid differences, but don't know why the test passed before and suddenly fail yesterday.

**Comment by seisman** [comment]
Actually it failed after we updated the grids. We forgot to update the original PS because the test was added to master branch only.

**Comment by PaulWessel** [comment]
Makes sense.  I have not built and run tests on master for some weeks..
