### ISSUE TITLE
grdtrack -E makes separate segments when a single line is requested

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1880]
The **-E** option can take a series of comma separated lines, with each line defined by a start and end point.  However, when making a multi-point line we do not want these parts to be separate segments but instead part of the same segment.  Specifically, the cumulative distance along the line should continue and not be reset at any bend. For example, if we give **-E**A/B,B/C,C/D for defining a line that goes from point A through B via C to D, then it is one line, while -EA/B,C/D is two lines.

This can either be considered a bug or a feature:

- BUG: We fix the problem so we get a single line when segments share a common endpoint.
- FEATURE: We add a modifier **+c** for "make lines cumulative if sharing endpoints".

I think "feature" is more flexible since then we can get either behavior, so that would be my vote.  If so, then that goes into 6.1.  if you think it is a bug then we should fix it before 6.0.

Thoughts?

**Comment by seisman** [comment]
Never used **-E** before, but I think sometimes users may want separate segments even when segments share a common endpoint. Vote for **+c**.

**Comment by PaulWessel** [comment]
Exactly.  OK, I think there can be no harm adding **+c** and clearly benefits.

**Comment by PaulWessel** [comment]
Implemented in #1885.
