### ISSUE TITLE
Avoid text overlap

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#1881]
I'm plotting points with ``psxy``. Then I plot a label with ``pstext``, using ``pstext [..] -D0.2c+v`` to offset the label. Problem is, the labels **very** often overlap. Would it be possible to expand the ``-D``-switch with an optional e.g. ``+a`` that would automatically place text/labels to avoid overlap? The ``-D`` could then, rather than explicitly define a (offset) point to put the text (given by ``-D``), define a radii where GMT *may* put it - as long as it doesnt overlap other text.

**Comment by joa-quim** [comment]
Let me close this. Something a want too for long time but needs an algorithm that knows how to do it.

**Comment by anbj** [comment]
Love your spring cleaning @joa-quim.

**Comment by joa-quim** [comment]
??

**Comment by anbj** [comment]
It's nice that you're closing stale issues, etc.
