### ISSUE TITLE
GMT built from source is hard to uninstall(?)

### ISSUE THREAD

**Issue by liamtoney** [GenericMappingTools/gmt#1886]
**Description of the problem**

A few weeks ago I built & installed 6.0.0rc2 from source for development purposes. Now I want to uninstall it in favor of a conda install. I want to avoid deleting executables/libraries by hand, as [this old Issue](http://gmt.soest.hawaii.edu/issues/291) alludes to. I found [this wiki entry](http://gmt.soest.hawaii.edu/projects/gmt/wiki/CMake) detailing the switch to CMake that suggests running
```
$ xargs rm < install_manifest.txt
```
to  remove all the files. But I can't locate a `install_manifest.txt` file so it's unclear how to proceed. I'd appreciate some guidance on this — or please show me the docs I missed, if that's the case! Thanks.

**System information**

* Operating system: macOS Catalina 10.15
* GMT version: 6.0.0rc2

**Other information**

* Output of `$ which gmt`: `/usr/local/bin/gmt`
* Source code origin: [gmt-6.0.0rc2-src.tar.gz](https://github.com/GenericMappingTools/gmt/releases/tag/6.0.0rc2)

**Comment by seisman** [comment]
@liamtoney There is a shell script `gmt_uninstall.sh` in GMT's share/tools directory. It should be able to delete all GMT files.

**Comment by liamtoney** [comment]
Thank you, @seisman.
