### ISSUE TITLE
filter1d

### ISSUE THREAD

**Issue by YaoYu9404** [GenericMappingTools/gmt#1887]
**When using filter1d to filter along track data (three columns: lon; lat; slope), I use -T5k to set the increment to be 5 km. GMT showed an error: filter1d [ERROR]: Syntax error: Distance units must be one of d|m|s|e|f|k|M|n|u. I also tried -T2.7m or add more +e, +a. It still returned the same error.**

** 

gmt filter1d altikaa0.txt -Fg50 -S0.3 -Q0.5 -T2.7m+e -jf -gy15d > altikaa0.5km.txt
[altikaa0.txt](https://github.com/GenericMappingTools/gmt/files/3769325/altikaa0.txt)
  **

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):
GMT - The Generic Mapping Tools, Version 6.0.0rc3 [64-bit] [4 cores]

**Comment by joa-quim** [comment]
Aside from the ``Distance units must be one of ...`` issue that I'm not sure of, you can't use *filter1d* with you data file. For *filter1d* you need one column with a monotonically increasing variable, and you have none. See ``mapproject -G`` on how to compute distance along track that would be that needed variable.

**Comment by PaulWessel** [comment]
No, the general usage is correct.  -T with a spatial dimension will compute distances from the lon,lat columns, append a new distance column, and use that as the "time" variable.  it is a relatively new feature (last few years).  I will have a look at this before 6.0 release.  Thanks for posting it.

**Comment by YaoYu9404** [comment]
Thanks Paul! Hope we can use this new feature soon!

**Comment by PaulWessel** [comment]
Closing this issue s fixed in #1903.
