### ISSUE TITLE
Color for arc symbol from data file

### ISSUE THREAD

**Issue by frspin** [GenericMappingTools/gmt#191]
**Setting color in data file for arc symbol**

I am unable to set color for draw arc using data file

In my data file I have

x, y, num_color, radius, alfa_star, alfa_end

with num_color a number in a range for a cpt file

This is simple misc1.txt data file 

15 15 2 2.0 45. 135.

And this is fari.cpt file

0 white  1 white
1 red    2 red
2 green  3 green
3 yellow 4 yellow
4 white  9999 white 
B black
F red
N white

Using
gmt plot misc1.txt -R0/100/-50/100 -JX6i -Sm10c  -Cfari.cpt -B20  -pdf map

I get correct arc (angle, radius) but only black color for arc

Is this a bug or I am wrong?

**System information**
GMT beta from GitHub

* Operating system: Linux Ubuntu 18.04

Regards

Franco Spinelli

**Comment by PaulWessel** [comment]
It works if you at -W+cl, otherwise the CPT is by default used for a fill (which does not apply for arc which is a line).  See the documentation of -C and -W for plot.

**Comment by frspin** [comment]
Il 26/11/18 21:59, Paul Wessel ha scritto:
> It works if you at -W+cl, otherwise the CPT is by default used for a
> fill (which does not apply for arc which is a line). See the
> documentation of -C and -W for plot.

My apologize.
I have read -W documentation but don't understood +cl option

Now I will use this for a marine light sector draw until I am able to
write a custom symbol with parametric data drawing arc and radius on
both end.

Many thanks

Franco Spinelli

**Comment by joa-quim** [comment]
Hi, I would like to recall that the issues is not the right place to ask questions. We still have a forum for that.

**Comment by frspin** [comment]
Il 27/11/18 00:41, Joaquim ha scritto:
> Hi, I would like to recall that the issues is not the right place to ask
> questions. We still have a forum for that.
> 

But, in forum interface, I am unable to find how to register for posting
a question. Tried with Firefox and with Chrome.

Where can I register to forum?

Regards

Franco Spinelli

**Comment by joa-quim** [comment]
Ah, sorry. I thought that problem with forum was solved. But when I try to register I get to a page that shows me this. Don't you see that?
![capture](https://user-images.githubusercontent.com/537321/49094097-54991900-f25d-11e8-835d-b6e5b33c6bb1.JPG)

**Comment by frspin** [comment]
Il 27/11/18 16:59, Joaquim ha scritto:
> Ah, sorry. I thought that problem with forum was solved. But when I try
> to register I get to a page that shows me this. Don't you see that?
> capture
> <https://user-images.githubusercontent.com/537321/49094097-54991900-f25d-11e8-835d-b6e5b33c6bb1.JPG>
> 
> —

Where you get the link to this page?
I go to to GMT home page, -> Forum and I get forum page without any link
for subscribe. login or post a new message.

What I am missing?

Regards

Franco Spinelli

**Comment by joa-quim** [comment]
At top right we have a Si gn in/ Register

![capture](https://user-images.githubusercontent.com/537321/49098667-5962ca80-f267-11e8-84a5-454c3bae07fd.JPG)

**Comment by frspin** [comment]
Il 27/11/18 18:11, Joaquim ha scritto:
> At top right we have a Si gn in/ Register

Now I have found it.
But re"CAPTCHA V1 IS SHUTDOWN"  message don't give any text for type in.
And without text there is no registration

Regards

Franco Spinelli

**Comment by frspin** [comment]
Il 27/11/18 18:25, Joaquim ha scritto:
> Ah, yes. It seems that it must be replaced by CAPTCHA V2

So, until this replacement, no forum registration.

Regards

Franco Spinelli

**Comment by PaulWessel** [comment]
Unfortunately, we are unable to fix the captcha stuff.  I have manually added new users to the forum but we need to replace that with another mechanism, soon.

**Comment by frspin** [comment]
Il 27/11/18 19:48, Paul Wessel ha scritto:
> Unfortunately, we are unable to fix the captcha stuff. I have manually
> added new users to the forum but we need to replace that with another
> mechanism, soon.

I am slowly teaching GMT for paper nautical maps from OSM data and I
have sometime some questions.

If you want I can send you a private mail request for manual adding
myself as a new user or I can wait some time for forum registration
correction.

Regards

Franco Spinelli

**Comment by PaulWessel** [comment]
Sure, just email me your preferred email and account name and I will set things up and tell you what the password is (so you can change it)

**Comment by PaulWessel** [comment]
No, there are plugins that needs updating but the virtual machine is too old to handle newer things and it is a mess... Leo and I tried for a while but ran into version troubles due to the old OS and libraries.  Remember, Florian installed the old gmtserver as a virtual machine on the new server.  While the new server runs CentOS7, the virtual server (which is where the wiki etc live) is CentOS5 with old libraries and toolsets.

**Comment by joa-quim** [comment]
Shit, that's too bad. We don't really have an alternative for the forum and asking questions in issues is quite bad too.

**Comment by frspin** [comment]
Il 27/11/18 20:16, Paul Wessel ha scritto:
> Sure, just email me your preferred email and account name and I will set
> things up and tell you what the password is (so you can change it)

Please create an account for me on GMT forum as:

Usename : frspin
Email : frspin@gmail.com

Regards

Franco Spinelli
