### ISSUE TITLE
OpenMP on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1912]
I enabled OpenMP support in the Windows CI in #1895. It works but there is a related compilation warning.
```
LINK : warning LNK4044: unrecognized option '/openmp'; ignored
```

**Comment by PaulWessel** [comment]
Looks like a compiler switch ends up being passed to the linker, which of course does not understand it?

**Comment by amtrident** [comment]
I got "**warning LNK4044: unrecognized option '/openmp'; ignored**" while compilation, when I used following two flags.
QMAKE_CXXFLAGS += -openmp
QMAKE_LFLAGS +=  -openmp



I **commented**  **QMAKE_LFLAGS += -openmp** , no more LNK4044 warning. 

MSVC's linker does not need or accept QMAKE_LFLAGS , it works in case of gcc.

https://stackoverflow.com/questions/25358741/linker-ignores-openmp-in-qtcreator-on-windows

**Comment by joa-quim** [comment]
Can you tell us more on what you are trying to achieve? Preferably in a new issue or discussion in the forum.
