### ISSUE TITLE
Building under brew lists fftw as dependency

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1920]
Under macOS we select Accelerate framework so fftw is never needed.

**Comment by seisman** [comment]
Do you mean that even if fftw is installed, GMT still uses Accelerate framework? I thought users can select the fft algorithm by setting GMT_FFT.

**Comment by PaulWessel** [comment]
I am not sure when we build the GMT bundle that FFTW is included.  I agree once should be able to switch via GMT_FFT but it has been a while since I did that.  You can certainly do that in brew or macports or Linux and just install fffw separately.

**Comment by seisman** [comment]
I believe fftw is optional on all platforms, since gmt supports kiss and brenner fft as fallbacks. If fftw is installed and correctly linked, users have more fft algorithms to choose.

**Comment by PaulWessel** [comment]
I need to install and add fftw shared lib to the Bundle. Sorry, do we need fftw-3-single (macports) then?

**Comment by seisman** [comment]
For macports, `fftw-3-single` is not enough, because it doesn't provide the fftw3.h. We still need `fftw-3`.

**Comment by PaulWessel** [comment]
In terms of manually adding the shared libs to the bundle, here is what is in lib:

ls *fftw*.dylib
libfftw3.3.dylib		libfftw3_threads.dylib		libfftw3f_threads.3.dylib
libfftw3.dylib			libfftw3f.3.dylib		libfftw3f_threads.dylib
libfftw3_threads.3.dylib	libfftw3f.dylib

libfftw3f_threads requires libfftw3f.dylib.dylib and we are just using the "f" float version, right, so perhaps just list libfftw3f_threads.dylib in that script?

**Comment by PaulWessel** [comment]
Per GhostScript AGPL: If you are redistributing our software in binary form, you must make the source code available. AGPL also requires this.

Do we therefore add the ghostscript-9.50.tar.bz2 [38Mb] to a new /Extra directory?

**Comment by joa-quim** [comment]
That is crazy. *Making available* does not have to mean *in the same file*. It can be a in separate file that would sit next to the bundle.

**Comment by PaulWessel** [comment]
It is also available from their download site.  Silly for us to copy their tarball regardless of where we place it (bundle, online link, link to their link, etc).

**Comment by claudiodsf** [comment]
I can confirm that the homebrew formula builds correctly without `fftw` installed.
Should I remove the dependency, then?

**Comment by seisman** [comment]
I think no. fftw is optional, but we should still keep it so that users can choose to use the fftw algorithm if they want.

**Comment by claudiodsf** [comment]
Not sure if runtime dependencies should be listed as required in a homebrew formula.

We should probably add a caveat to the formula, something like:
```
GMT uses  the Accelerate framework for fast Fourier transform.
I you prefer to use FFTW, `brew install fftw` and set the
environment variable `GMT_FFT` to `fftw`.
```

What do you think?

**Comment by seisman** [comment]
> Anyway, how many people will likely use this? What is the advantage of using FFTW over Accelerate on macOS?

I know little about FFTW and macOS Accelerate. @PaulWessel should be able to answer this question.
 
> Should we rather add `fftw` as optional dependency? (i.e., people will need to build the package explicitly with `fftw` as a dependency, while the bottle will come without `fftw` support).

Personally, I would like to have all features enabled by default. I don't see any benefits to have a bottle without fftw support.

Actually I have a question about homebrew runtime dependencies. Currently, we still have to run:
```
brew install gmt
brew install ghostscript graphicsmagick ffmpeg
```
Is it possible to add ghostscript, graphicsmagick, ffmpeg as runtime dependencies, so they can be  automatically installed when running `brew install gmt`? I checked the homebrew documentation once, and can't find any instructions about runtime dependencies.

**Comment by claudiodsf** [comment]
We already got a comment by one of Homebrew maintainers on not adding `ffmpeg` and `graphicsmagic` as dependencies: https://github.com/Homebrew/homebrew-core/pull/41119#issuecomment-503515397

I think that we should better add a caveat for that.

**Comment by seisman** [comment]
Agree, a caveat is necessary.

**Comment by PaulWessel** [comment]
All I know is that FFTW has some clever planning of how to do things fast and remembers this decisions via a hidden file, so the next FFT can take advantage of what was learned.  It also handles non-radix two cases - the Accelerate framework is only used for radix-2 cases.

**Comment by joa-quim** [comment]
FFTW makes justice to its name. It's the fastest FT in the West and East. Not even MKL beats it.

**Comment by seisman** [comment]
From what I saw in https://github.com/GenericMappingTools/gmt/pull/1924, FFTW is the default algorithm on all platforms if fftw is enabled and correctly linked.

**Comment by seisman** [comment]
@claudiodsf We're working on the 6.0.0 release. The temporary links of the 6.0.0 tarballs are available in #1925. It would be good if you can try if the manpage works for you (#1928) and also try the tarball with homebrew. But please note that the links are temporary.

**Comment by claudiodsf** [comment]
Is the `movie` command the only one needing `ffmpeg` and `graphicsmagick`?
If so, I can be more specific in the caveat.

**Comment by seisman** [comment]
> Is the `movie` command the only one needing `ffmpeg` and `graphicsmagick`?
> If so, I can be more specific in the caveat.

Yes.

**Comment by seisman** [comment]
Good.

**Comment by claudiodsf** [comment]
> From what I saw in #1924, FFTW is the default algorithm on all platforms if fftw is enabled and correctly linked.

If this can be confirmed, we can close this issue.

**Comment by seisman** [comment]
@PaulWessel Need your confirmation.

**Comment by PaulWessel** [comment]
Here is what happen if **GMT_FFT** is set to _auto_ (which is the default):

```
	/* Here we want automatic selection from available candidates */
	if (GMT->session.fft2d[k_fft_accelerate] && radix2 (n_columns) && radix2 (n_rows))
		return k_fft_accelerate; /* Use if Radix-2 under OS/X */
	if (GMT->session.fft2d[k_fft_fftw])
		return k_fft_fftw;
	return k_fft_kiss; /* Default/fallback general-purpose FFT */
```

So except for the special case of radix-2 dimensions under macOS, which results in a call to Accelerate, all other cases on macOS and for every case on all other OS, we will select FFTW if it is available.  The fallback is KISS which we distribute with GMT.

**Comment by seisman** [comment]
Then I believe we can close this issue, right?

**Comment by PaulWessel** [comment]
Yes, so confirmation given and closing the issue now.
