### ISSUE TITLE
potential/flexure_e.sh failed on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1921]
gm diff image for Linux:
![image](https://user-images.githubusercontent.com/3974108/67648379-e3019900-f90b-11e9-9278-d690b5e29e43.png)

gm diff image for Windows:
![image](https://user-images.githubusercontent.com/3974108/67648386-ec8b0100-f90b-11e9-8508-f7dd5cd5a0c6.png)

**Comment by PaulWessel** [comment]
Isn't this just reflecting that the macOS-produced grid used Accelerate while Windows and Linux probably used FFTW?  We have some tests in grdfft that passes --GMT_FFT=brenner because we comparing the results  E.g., power2D.sh.

**Comment by seisman** [comment]
Sound reasonable. So accelerate is the "auto" fft algorithm on macOS?

**Comment by PaulWessel** [comment]
Actually, selection if auto is dealt with in fft_1d_selection and fft_2d_selection.  Loks like if dimensions are radix 2 on Mac we do accelerate else we try fftw (if available, else default to KISS.

**Comment by seisman** [comment]
The test used to pass on Linux but failed recently. I think it failed because I accidently disabled fftw on Linux in #1892 (it was then reverted in #1923). Let's see the build results tonight.

For this test, should we force it to use the same algorithm to make it pass?

**Comment by PaulWessel** [comment]
Not sure, if it passes then it is OK I think.

**Comment by seisman** [comment]
Now it pass on Linux. But why it fails on Windows. I think both Windows and Linux use FFTW, right?

**Comment by PaulWessel** [comment]
Still failing after the recent _fftw_plan_ default change?

**Comment by seisman** [comment]
Yes, the test still fails on Windows. It also fails on macOS, if GMT is linked with the fftw library provided by vcpkg. 

Both homebrew and vcpkg provide fftw version 3.3.8, but the configurations used in building possibly are different.

**Comment by seisman** [comment]
The test passes after setting GMT_FFT to KISS.
