### ISSUE TITLE
Remove links to old-style commands in GMT6.0.0 Homebrew formula? 

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/gmt#1948]
Currently the Homebrew formula still builds the links to the old-style commands:

`-DGMT_INSTALL_MODULE_LINKS:BOOL=TRUE`

Should we stop this with 6.0.0 release? This would be more consistent with the man pages shipped by default (see #1927).

**Comment by seisman** [comment]
Totally agree.

**Comment by claudiodsf** [comment]
Ok, so I'll set `-DGMT_INSTALL_MODULE_LINKS:BOOL=FALSE` for the GMT6 homebrew formula.
I'll keep it `TRUE` for GMT5, though.
