### ISSUE TITLE
Add mention to 'gmt docs' in 'gmt' manpage 

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/gmt#1949]
Manpages in GMT6 are reduced to the bare minimum, in order to promote the use of `gmt docs`.
(see https://github.com/GenericMappingTools/gmt/issues/1927#issuecomment-547510797). 

It would be nice, then, to have a reference to `gmt docs` in the `gmt` man page.

**Comment by PaulWessel** [comment]
We have decided to do this for 6.0.1 which I imagine wont take too long...
