### ISSUE TITLE
The GMT logo should change on certain days

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1958]
**Description of the desired feature**

Around key dates such as Halloween, Christmas week, etc, the colors of the GMT logo as written by gmtlogo should take on more festive combinations, such as the Halloween colors below:

![logo](https://user-images.githubusercontent.com/26473567/68061092-47737e00-fca7-11e9-8245-8a98ca10c385.png)

**Comment by seisman** [comment]
I like it. It also has lower impact on users than the idea of "April Fools" random figures.

**Comment by PaulWessel** [comment]
I will put this on the back-burner.  Would need a few more actual color examples associated with holidays.  Christmas is easy (red/green) but we need to do more.  Chinese new years colors, @seisman? Brazilian green/yellow during world cups, @leouieda? Portuguese wine colors (think @joa-quim had wine and cork earlier)? Norwegian [lutefisk](https://en.wikipedia.org/wiki/Lutefisk) colors around my birthday? All for one week centered on the holiday/event? Maybe need a **-C** option for classic to ensure reproducible standard logo at any time?  Add "nth anniversary" around each Oct 21. Etc., etc.

**Comment by joa-quim** [comment]
I can open a couple of bottles and take pictures, but I failed to understand where would these new logos show up. After all, the logo is not something we generate often.

**Comment by PaulWessel** [comment]
I think the main use may be to update the logo on the website during those times.

**Comment by PaulWessel** [comment]
Hi @leouieda, could we somehow add building the GMT logo used for the website to the CI so that it gets updated every night? Then, if I add the date-dependent coloring we would have a website that occasionally would throw in different GMT logo colors.

**Comment by leouieda** [comment]
@PaulWessel I like this! Yes, we could have the logo be built as part of the docs and use the image from docs.generic-mapping-tools.org on the main website.

**Comment by seisman** [comment]
We decided not to implement the feature (see a draft implementation in #1986). Closing the feature request.
