### ISSUE TITLE
'gmt docs' always uses online pages for Homebrew-installed GMT

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/gmt#1960]
The [homebrew GMT formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmt.rb) installs html doc pages in `/usr/local/Cellar/gmt/6.0.0/share/doc/gmt/html`.

However, those pages are not seen by `gmt docs`, which always uses online pages.

I don't know wether this is a bug in the formula (a missing CMake argument?) or in `gmt docs`.

**Comment by seisman** [comment]
AFAIK, `gmt docs coast` tries to open a local HTML file from `${GMT_SHAREDIR}/doc/html/coast.html`.

For homebrew, `${GMT_SHAREDIR}` is `/usr/local/Cellar/gmt/6.0.0/share/gmt`.
However, the real documentation path is `/usr/local/Cellar/gmt/6.0.0/share/doc/gmt/html/coast.html`.

**Comment by PaulWessel** [comment]
docs.c looks here:

`snprintf (URL, PATH_MAX, "file:///%s/doc/html/%s", API->GMT->session.SHAREDIR, module);
`

so we assume the GMT_SHAREDIR dir points to the directory with all the share sub-dirs, including doc.

**Comment by seisman** [comment]
The homebrew recipe specifies the docs location by add the option `-DGMT_DOCDIR=#{share}/doc/gmt`. Since we allow users or package maintainers to put the docs at any place, maybe it's better to check GMT_DOCDIR/html/coast.html before checking GMT_SHAREDIR/doc/html/coast.html

**Comment by PaulWessel** [comment]
Probably.  Right now, GMT_DOC_DIR is defined in gmt_config.h but not used anywhere.

**Comment by seisman** [comment]
Fixed by #1964, but waiting for the homebrew recipe update.

**Comment by claudiodsf** [comment]
New formula PR submitted to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/46231.
Waiting for merging of that PR before closing this issue.

**Comment by seisman** [comment]
The PR was merged. Closing.
