### ISSUE TITLE
basemap reports weird errors if single quotes used 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1969]
**On Windows**, the command below reports weird errors:

Commands:
```
gmt begin GlobalMap png
gmt basemap -R10/70/-4/8/-10/10 -JX8c/5c -JZ5c -Bxa10+lX -Bya4+lY -Bzaf+lDepth -BSEwnZ+b+t'3D plot' -p130/30
gmt end
```

The error message:
![image](https://user-images.githubusercontent.com/3974108/68080153-7c78f100-fdcb-11e9-9f74-b861fb3b9801.png)

Changing `+t'3D plot'` to `+t"3D plot"` works as expected, and the commands work on macOS.

**Comment by PaulWessel** [comment]
So the single quotes don't really work and gmt is seeing

`-BSEwnZ+b+t3D plot
`

and completes about being given an input file called plot.  The -< option is a valid option to specify an input file on the command line (used by the API usually).  You can actually say

gmt plot -<myfile.txt

instead of

gmt plot my file.txt
May have to quote this as < has meaning...

**Comment by seisman** [comment]
FYI, both single and double quotes work well on git-bash on Windows, but only double quote works in batch. Maybe single quotes have special meanings for batch.

**Comment by PaulWessel** [comment]
Good question for @joa-quim.

**Comment by joa-quim** [comment]
I think the issue is that single quotes have (or other) meaning on bash. Using awk on batch is a pain because single quotes must be replaced by double quotes and double quotes must be escaped. A damn pain.

**Comment by PaulWessel** [comment]
That is not one of our test scripts though, no? I think we use double quotes for text since single quotes can't expand variables, etc.

**Comment by seisman** [comment]
Related stackoverflow question: https://stackoverflow.com/questions/24173825/

I think it's not a GMT bug. Batch users should know they can't use single quotes to enclose a string.

Closing.
