### ISSUE TITLE
Test bot for GMT releases

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1971]
I'm experimenting a test bot for GMT installers in my repository https://github.com/seisman/gmt-release-testbot.

For each GMT release, @PaulWessel and @joa-quim create macOS bundle and Windows installers, then we need to install and test these installers on our own machines to confirm they're not broken. It usually takes some time and we still have the risk publishing broken installers, as we don't have an isolated environment for testing.

The idea of the test bot is to take advantage of the CI service. After we create the installers, we can trigger the testbot to download the installers, install and then run any necessary commands in many different platforms. 

Currently the installers are tested on macOS 10.10-10.14, and Windows. The [latest tests](https://travis-ci.org/seisman/gmt-release-testbot) show that, the macOS bundle works for 10.12-10.14, but breaks on 10.10 and 10.11. The Windows installers (win32 and win64) probably don't have a working ffmpeg included.

I'm glad to transfer it to the genericmappingtools family if you think it's useful.

**Comment by PaulWessel** [comment]
That sounds really good, @seisman.  I fully believe that our goal must be to have the building and testing of the installers happen on the CI somehow so it is decoupled from whatever libraries we have.  We have seen how it can cause trouble with @joa-quim, but macOS is not that far behind.  After installing the bundle my other builds act up because of mixing of shared libraries somehow and only way to truly reset was to remove the bundle installation, etc.  So ideal to have a clean environment for these builds.

**Comment by PaulWessel** [comment]
Following up on your results, should we add somewhere that our macOS installer requires macOS 10.12 or later? Also, what does it mean that the 2 win installers probably don't have a working ffmpeg?  I.e., if you run the simple globe.bat example on the movie man page, does that fail?  if so, do we need to update the installers pronto?

**Comment by seisman** [comment]
Below are the command currently tested.
```bash

#!/usr/bin/bash

set -x

# check GMT version
gmt --version

# check GMT defaults
gmt defaults -Vd

# check GMT classic mode, GSHHG and DCW
gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -P -Vd > test.ps

# check GMT modern mode, GSHHG and DCW
gmt begin && gmt coast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -Vd && gmt end

# check remote file, one-liner
gmt grdimage @earth_relief_60m -JH10c -Baf -pdf map

# check remote file and PROJ settings
gmt grdinfo @BlueMarble_60m.tiff

# check local documentation
gmt docs -Q coast

# check movie in MP4 and GIF format
cat > globe.sh << EOF
gmt begin
   gmt coast -Rg -JG\${MOVIE_FRAME}/20/\${MOVIE_WIDTH} -Gmaroon -Sturquoise -Bg -X0 -Y0
gmt end
EOF
gmt movie globe.sh -Nglobe -T12 -Fmp4 -C6ix6ix100 -Lf -Vd
gmt movie globe.sh -Nglobe -T12 -Agif -C6ix6ix100 -Lf -Vd
```

For macOS 10.10 and 10.11, most commands pass, but the commands using remote files fail:
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/GMT-6.0.0.app/Contents/Resources/bin/../lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```
It seems something wrong with the packed curl library, and we can't solve it. I think we can add a note in the INSTALL.md.

As for the Windows installers, the testbot checks globe.sh. It complains 
```
movie [DEBUG]: Found file globe.sh
movie [DEBUG]: Found file globe.sh
movie [DEBUG]: Found file globe.sh
movie [DEBUG]: gmt_check_executable: Pass to popen: [ffmpeg -version 2> NUL]
movie [DEBUG]: ffmpeg -version 2> NUL failed
movie [ERROR]: ffmpeg is not installed - cannot build MP4 or WEbM movies.
```

**Comment by PaulWessel** [comment]
As for the lazy symbol binding: I think this is not too crazy: We have a recent libcurl and an older OS system library.  I think it is OK that people who for whatever mental reason don't want to upgrade will simply have to build from source.  Let's place the warning somewhere on the download pages that the installer requires 10.12 or later.

@joa-quim, can we install a tool in the CI that does the dependency tracking in Windows for ffmpeg so we can see what is missing?

**Comment by seisman** [comment]
I tested the Windows installer locally. The ffmpeg works. Possibly something wrong with my testbot.

**Comment by seisman** [comment]
The Windows installer should set PATH and maybe other environmental variables. I don't know why in the Travis CI the PATH is not set, and I have to manually set it manually. Probably I missed some other environmental variables?

**Comment by PaulWessel** [comment]
Right, yes that is possible.

**Comment by joa-quim** [comment]
The other env variable is ``GMT6_SHAREDIR`` that points to gmt *share*

Regarding a dependency tracker. The only one I know, and fails time to time, is CPACK itself. 
I have a tool to track dependencies but it's manual and would not detect the ffmpeg need. I say ``need`` because it's not exactly a dependency.

**Comment by seisman** [comment]
I've transfer the testbot to GenericMappingTools (https://github.com/GenericMappingTools/gmt-release-testbot). Closing.
