### ISSUE TITLE
Modules that should take -l for auto-legend building

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1973]
**Description of the desired feature**

Looking at all the modules that produce plots, I think this is the list that may need **-l**:

- contour: Need to resolve how/if to deal with annotated vs regular contours.
- grdcontour: ditto
- grdvector: Place a scaled vector in legend.  Alternatively, or possible in addition, to how wiggle plots a scale bar?
- plot/plot3d: Need to allow **-l** for polygon, plotting a filled/outlined rectangle.
- velo: maybe arrow with error ellipse? Or like grdvector add option to plot a scale
- meca: Could plot using the mega custom symbol in plot.

For contours the proposed option was **-l**[_annotlabel_]/[_contourlabel_] in order to allow one or both lines.
I have excluded modules like coast and wiggle since not likely to need legends (?).

**Comment by seisman** [comment]
@PaulWessel No need to have "6.1" in the title. You can add this issue to the "6.1.0" milestone.

**Comment by PaulWessel** [comment]
Slowly learning GitHub...

**Comment by meghanrjones** [comment]
xref https://github.com/GenericMappingTools/gmt/issues/442#issuecomment-1032907528, which requests auto-legend support for custom symbols in plot.
