### ISSUE TITLE
Typos in earth_relief_xxy names causes wasted download of nonexistent files

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#1978]
**Description of the problem**

If a user requests an earth_relief_xxy file that does not exist, such as might happen if a typographical error is introduced (e.g., earth_relief_1m instead of earth_relief_01m) then we should immediately recognize that and give an error, rather than sending off libcurl on a fool's errand to the remote server only to return empty-handed and full of error messages.  Since we know which files are allowed, we should check that first on the client side.

**Comment by seisman** [comment]
Closed by #1979.
