### ISSUE TITLE
Incorrect file name in modern mode when prefix contains dots

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#200]
**Description of the problem**

In modern mode, if there are dots in the filename, the string after the last dot is regarded as filename suffix and is omitted in the output. This cause troubles if users needs dots in filenames. 

Maybe gmt can check if the *suffix* is a legal figure format, e.g. pdf, PDF, jpg, ...

**Full script that generated the error**

```
gmt begin stations.loc pdf
gmt basemap -JX10c -R0/10/0/10 -Baf
gmt end
```
- Expected filename: stations.loc.pdf
- Actual filename: stations.pdf

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_2a0f78d

**Comment by PaulWessel** [comment]
We probably have some very clever algorithm that finds the first period in the file name...
Will fix when I have some time.  Thanks.
