### ISSUE TITLE
GMT colors list

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2000]
We have a long list of GMT colors in the [gmtcolors](https://docs.generic-mapping-tools.org/latest/gmtcolors.html) manpage. To me, the list is almost useless, as I can't guess what the color looks like from the color names.

We also have RGB charts (in both PDF and PNG), which I think is much more useful. But they're hidden in the `share/doc/pdf` directory.

Here are some my suggestions:

1. Include the PNG version RGB charts in the gmtcolors manpage, and add links to the PDF versions (someone may want to have a printed copy)
2. Remove the list or make it shorter by having two or three colors in each row
3. Allow `gmt docs colors` to open the manpage.

**Comment by PaulWessel** [comment]
Those are all good suggestions, @seisman.

**Comment by seisman** [comment]
I'll work on points 1 and 2. @PaulWessel Can you help with point 3?

**Comment by PaulWessel** [comment]
Yes, I can help with that.

**Comment by seisman** [comment]
Most are done in #2002. More work are needed to add links to the PDF version RGB charts.

**Comment by seisman** [comment]
Fixed in #2002 AND #2011.
