### ISSUE TITLE
UTF8 chars in -B string, crash

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#201]
This shows the problem
```
pscoast  -Rg -JA300/30/14c -Bg -B+t"ai¯ai" -Dcrude -Gnavy -P > lixo.ps
```
It crashes on the ``gmt_parse.c`` at line 97
```
if (isdigit (in[k])) n_digits++;
```
But it's not impossible that this is VS pickyness thing with debug builds, as I've seen cases in the past where ``isdigit`` crashed with invalid chars but gcc/clang happily digested it.

**Comment by PaulWessel** [comment]
No crash in OSX with debug build.

**Comment by joa-quim** [comment]
Doesn't crash anymore
