### ISSUE TITLE
Missing documentation for some share/tools scripts

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2014]
Maybe I just cannot find it but we should document what at least some of the scripts in share/tools do.  In the chapter on [switching](https://docs.generic-mapping-tools.org/6.0/switching.html) between GMT versions there is some discussion of how to run old scripts but there is nothing about gmt_aliases.csh, gmt_links.sh, or gmt_functions.sh, for instance.

**Comment by seisman** [comment]
I can confirm that we don't have such documentations.

**Comment by PaulWessel** [comment]
OK, I can hack up a single rst for this that covers a GMT 4 to 6 transition or something.  It is a separate issue from switching between versions.

**Comment by PaulWessel** [comment]
Implemented via the new migration.rst documentation.
