### ISSUE TITLE
List DCW data in the GMT datasets

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2015]
The [Datasets page](https://docs.generic-mapping-tools.org/latest/datasets.html) describe GSHHG and global earth relief data. The DCW data should also be listed there.

We need to add a section about DCW:

- Explain what's DCW
- The syntax to specify a continent, a country or a state.
- Where can the DCW data be used (e.g. `gmt coast -E`, **-R** option)
- A few examples

**Comment by PaulWessel** [comment]
Implemented, closing this issue.
