### ISSUE TITLE
filter1d/mfilter.sh fails due to the missing remote file

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2017]
The test script uses the data http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/weekly/weekly_in_situ_co2_mlo.csv.

It seems something wrong with their server. The URL was redirected to (note the missing slash after `edu`)

https://scrippsco2.ucsd.eduassets/data/atmospheric/stations/in_situ_co2/weekly/weekly_in_situ_co2_mlo.csv

and of course the file is not there.

There is nothing we can do here. Just open a new issue to remind us the failure. Maybe we should change to another data file for testing purpose?

**Comment by PaulWessel** [comment]
I send them a note - hopefully they can fix it quickly.

**Comment by seisman** [comment]
The test is still failing. Maybe they changed the data file format. Now the file starts with 
```
% Weekly average baseline air CO2 data
% From archive dated 05-Sep-2016 09:05:56
%
1958-03-29, 316.19
1958-04-05, 317.31
1958-04-12, 317.69
1958-04-19, 317.58
1958-04-26, 316.48
1958-05-03, 316.95
1958-05-17, 317.56
1958-05-24, 317.99
1958-07-05, 315.85
1958-07-12, 315.85
1958-07-19, 315.46
```

**Comment by PaulWessel** [comment]
It is always a day of joy when formats change to something that violates the ISO standard.  Now we can add back in awk, etc.  I will waste my time asking them to consider a standard format but since they did not respond to my first email there is probably not much hope they will bother.

**Comment by PaulWessel** [comment]
So GMT actually handles the yyyy-mm-dd string with the missing **T**, and we can use --IO_HEADER_MARKER=% to overcome those comments.  So perhaps this can work well with just that change.

**Comment by PaulWessel** [comment]
I am implementing this now.

**Comment by seisman** [comment]
Fixed by #2128.

**Comment by seisman** [comment]
mfilter.sh is failing again, because they changed the data format.

**Comment by PaulWessel** [comment]
Hm, looks like they are back to what it was before they started messing around.
