### ISSUE TITLE
gmt earthtide -S does not use now time

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#203]
According to the man page (http://gmt.soest.hawaii.edu/doc/latest/supplements/potential/earthtide.html) ``gmt earthtide -S`` should use *now* time. I'm getting

``
1970-01-01T00:00:00     -38.4486951628  -22.4007363626  147414091986    -58.2684135883  -14.1173275505  381803346.516
``

It appears to be using ``1970-01-01T00:00:00``.

using **6.0.0_1ded948**

**Comment by joa-quim** [comment]
Yes, some issue here. But if you plot the sun/moon position you'll see that it's correct. It's the time info that is wrong.

**Comment by PaulWessel** [comment]
Fixed in #211
