### ISSUE TITLE
Can't open the forum via Google Chrome

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2033]
I can't open the forum via Google Chrome, but can open it via Safari. The Chrome console reports several errors:

![image](https://user-images.githubusercontent.com/3974108/68635488-b5e5e680-04c6-11ea-93d8-e83b8659dab5.png)

Not sure if it's something wrong with my browser (Chrome Version 78.0.3904.97).

**Comment by seisman** [comment]
After clearing the cache, I got this warning:
![image](https://user-images.githubusercontent.com/3974108/68635709-65bb5400-04c7-11ea-8797-74588d393756.png)

**Comment by PaulWessel** [comment]
I am getting that warning as well for both safari and chrome, but once ignoring it the site works form chrome for me.  I will ask our IT who set up discourse what to do.

**Comment by seisman** [comment]
It seems the https certification expired yesterday.

![image](https://user-images.githubusercontent.com/3974108/68635795-a3b87800-04c7-11ea-8124-6ca681fdc556.png)

**Comment by PaulWessel** [comment]
Yep, I've sent my question to them,

**Comment by seisman** [comment]
Fixed.

**Comment by joa-quim** [comment]
Funny, it has always worked for me (but Firefox is a superior browser)
