### ISSUE TITLE
-Jepsg:xxx swaps lon/lat

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2036]
This is something that was broken in proj6 but there is some var/function to restore the the previous behavior. Oddly I must have implemented it for ``+proj=...`` strings but not for ``EPSG`` and can't find it right now.

This is correct
```
echo 674730 6580270 | mapproject -J+proj=utm+zone=33 -I
18.0709919933   59.3249929836
```
but not this
```
echo 674730 6580270 | mapproject -Jepsg:3006 -I
62.9706616532   4.07859679075
```
and woks again if we swap input
```
echo 6580270 674730 | mapproject -Jepsg:3006 -I
18.0709919933   59.3249929847
```

**Comment by seisman** [comment]
This is what I got using GMT 6.0.1_946425f_2019.11.12 (macOS):

```
echo 674730 6580270 | gmt mapproject -J+proj=utm+zone=33 -I           
18.0709919933	59.3249929847

echo 674730 6580270 | gmt mapproject -Jepsg:3006 -I
18.0709919933	59.3249929839

echo 6580270 674730 | gmt mapproject -Jepsg:3006 -I
62.9706616532	4.07859679061
```

**Comment by joa-quim** [comment]
That's because I forgot again and committed to master. But just back-ported to 6.0 so it should work now.

**Comment by joa-quim** [comment]
Wait, what you showed is the correct result.

**Comment by seisman** [comment]
Yes, I got correct results without your patch.

**Comment by joa-quim** [comment]
And aren't you using a GDAL < 3? Because my patch is only for GDAL3+PROJ6

**Comment by seisman** [comment]
No, I have GDAL 2.4.2 + PROJ 6.2.0, provided by homebrew.

**Comment by joa-quim** [comment]
Yes, but that combination uses (not 100% but 99% sure) a proj macro to set backward compat, which is gone in GDAL3.

**Comment by joa-quim** [comment]
Shit, it's still screwing
```
$ echo 500000  4427757.218 | gmt mapproject -J"epsg:32629 +to epsg:4326"
39.9999999933   -9

$ echo 500000  4427757.218 | gmt mapproject -J"+proj=utm +zone=29 +to +proj=longlat"
-9      39.9999999933

$ echo 500000  4427757.218 | gmt mapproject -J"epsg:32629 +to +proj=longlat"
-9      39.9999999933
```

**Comment by joa-quim** [comment]
With #2058 I finally get

```
$ echo 500000  4427757.218 | gmt mapproject -J"epsg:32629 +to epsg:4326"
-9      39.9999999933
```

**Comment by joa-quim** [comment]
Close again
