### ISSUE TITLE
grdconvert fails conversion to ESRI

### ISSUE THREAD

**Issue by martaneres** [GenericMappingTools/gmt#204]
I start to convert ESRI grids to gmt, and do some operations with them. Then I want to save the results back in ESRI. However, when using grdconvert it gives the following:

grdconvert depth_reflector.grd -Gdepth_reflector.asc=ef
grdconvert (api_export_grid): Only square pixels are allowed in ESRI grids [depth_reflector.asc=ef]
Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)

It seems to be saying that the grid is not squared, however xinc=yinc, at least as long as grdinfo is able to say.

I am sending the script, the input grids and two error prints.

Thanks for your concern

Marta

**System information**

* Operating system: Windows 10
* Version of GMT: 5

**Comment by PaulWessel** [comment]
Running your commands first, the command

`gmt grdconvert depth_reflector.grd -Gdepth_reflector.asc=ef
`

worked fine for me.  What does gmt grdinfo depth_reflector.grd say?

**Comment by martaneres** [comment]
I attach a screen shot of the whole script run.
in the last command, grdinfo gives xinc=yinc

thanks for your support

**Comment by joa-quim** [comment]
Please show us the output of
```
grdinfo --FORMAT_FLOAT_OUT=%.15 depth_reflector.grd
grdinfo --FORMAT_FLOAT_OUT=%.15 reflector.grd 
```
No screenshots please. Just the plain text

**Comment by joa-quim** [comment]
Sorry, I chop off one character in the printing format. It's
```
grdinfo --FORMAT_FLOAT_OUT=%.15g depth_reflector.grd
```

**Comment by joa-quim** [comment]
Please, the two of them.

**Comment by joa-quim** [comment]
It would also worth the trying of doing this operation via GDAL (using the =gd: .... mechanism, see the docs). Maybe that alternative code is less strict when comparing the x_inc/y_inc

**Comment by PaulWessel** [comment]
Also, what GMT version? 5 is not informative enough.  What does gmt --version say?

**Comment by joa-quim** [comment]
Hmm, the input files are gone!!!

**Comment by martaneres** [comment]
I had 5.4.3. I updated for 5.4.4, and it worked!
Thanks

**Comment by PaulWessel** [comment]
Closing this issue.
