### ISSUE TITLE
psvelo has ugly way to set fontsize

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2045]
The syntax of **-S** in psvelo is somethings this: **-Se**_velscale_/_confidence_/_fontsize_, where the _fontsize_ is given in the old style.  However, elsewhere in the old meca supplement (now split into seis and geodesy) we have replaced this with the more modern **+f**_font_ setting.  I propose we make that the default way of setting the font (and size) but obviously allow for the old syntax to be parsed.  There are two flavors of **-S** that take that optional font specification.

**Comment by seisman** [comment]
Closed by #2049.
