### ISSUE TITLE
gs is a run-time dependency, no?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2055]
The BUILDING.md file lists ghostscript among the build dependencies but we only use it via a system call to gs I think?  Should it be listed instead with the ffmpegs, etc?  I think GMT will build fine without gs but you cannot use psconvert.

**Comment by seisman** [comment]
Yes, we probably can list build and run-time dependencies separately.

**Comment by PaulWessel** [comment]
I want to hear form @joa-quim tomorrow but I think even on Windows he opens a popen process to write/read via pipes instead of the system call.  I could not get that to work on macOS.

**Comment by joa-quim** [comment]
GS cannot be listed as a building dependency. For one side it is not and for other it's (A)GPL licensed product.
On Windows it can be accessed via popen like Paul says, but even that I have to check because I suspect latest changes on GS may have broken it. Anyway, it's a build dependency.

**Comment by seisman** [comment]
Closed by #2060.
