### ISSUE TITLE
Add install instruction for ArchLinux?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2056]
I'm not an ArchLinux user and also don't know how AUR (ArchLinux User Repository) works.

There are two gmt packages on AUR:

- https://aur.archlinux.org/packages/gmt/
- https://aur.archlinux.org/packages/gmt6

Both are well-maintained and provide the latest 6.0.0 release. I think we can add it to INSTALL.md.

I know the second package is maintained by @holishing, but it seems the first package is more popular (have more votes).

**Comment by holishing** [comment]
I will suggest normal ArchLinux user to use former package ( https://aur.archlinux.org/packages/gmt/ ) to do `makepkg -sc`, although there's some little problem let this package may manually install optional package(`ghostscript`, `python-sphinx`) to let the AUR be built successfully.

After I confirm related information, I'll add a new PR for improve document for this.

**Comment by seisman** [comment]
@holishing Great! Thanks for your help.

I have some comments for the [PKGBUILD script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gmt) of https://aur.archlinux.org/packages/gmt. Could you help improve it? 

> pkgdesc="Generic Mapping Tools: Collection of tools for manipulating geographic and Cartesian data sets, and generating EPS maps."

Change to "Generic Mapping Tools: Tools for manipulating and plotting geographic and Cartesian data"

> url="http://gmt.soest.hawaii.edu/"

Change to "https://www.generic-mapping-tools.org/"
