### ISSUE TITLE
To implement violin plot with GMT

### ISSUE THREAD

**Issue by chiyu-chiu** [GenericMappingTools/gmt#2068]
Hello, Sir,

The violin plot is the combination of box plot and kernel density plot. (https://en.wikipedia.org/wiki/Violin_plot). I could create box plot with the command "psxy -E[X|Y]", but I couldn't find the way to make kernel density plot. Would you provide some advice? Thanks for your help.

    Best Regards,
    Chi-Yu

**Comment by joa-quim** [comment]
Implemented in GMT.jl

https://www.generic-mapping-tools.org/GMTjl_doc/examples/plotting_functions/05_1_stats/#example_14299581446007642096
