### ISSUE TITLE
Different behavior of grdmask form externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2072]
I cannot reproduce this on command line, but notice how from Julia **-S** has to be set when number of points is greater then 2 and they do not define a closed polygon.

```
julia> G2 = grdmask(rand(3,2)*5, R="0/5/0/5", I=1, Vd=1);
        grdmask  -R0/5/0/5 -I1
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon
grdmask [ERROR]: given non-closed polygon

julia> G2 = grdmask(rand(3,2)*5, R="0/5/0/5", I=1, S=0, Vd=1);
        grdmask  -R0/5/0/5 -I1 -S0

julia> G2 = grdmask(rand(2,2)*5, R="0/5/0/5", I=1, Vd=1);
        grdmask  -R0/5/0/5 -I1
```

**Comment by PaulWessel** [comment]
Without **-S** we assume you are giving a closed polygon to determine in and out, while with **-S** we consider each input point a center of a circle and all nodes within radius are considered in.  So when you set **-S** you are switching between two entirely different algorithms.  The rand call is unlikely to yield a meaningful polygon.

**Comment by joa-quim** [comment]
Yes, but notice how it prints the ``-I1 -N10/NaN/NaN -Glixo.grd`` only when n > 2 and on command line it never prints it. Not even with -V

```
echo 3 3 | gmt grdmask -R0/6/0/6 -I1 -N10/NaN/NaN -Glixo.grd -V
```

**Comment by PaulWessel** [comment]
Who is doing the printing of "grdmask  -R0/5/0/5 -I1"?  Not GMT.  if the question is what happens when n <= 2 then yes, that seems to be a black hole and we should print an error.  Is that what you mean?

**Comment by joa-quim** [comment]
The ``grdmask -R0/5/0/5 -I1`` is printed by julia in response to the ``Vd=2`` option. It's a debug message.

What I mean is that there are two issues here.
1. The case ``<= 2`` is treated differently
2. On command line the ``grdmask [ERROR]: given non-closed polygon`` message is never printed.

**Comment by PaulWessel** [comment]
The case <= 2 needs an error message - I will work on that.
The other case of missing message must be a Julia implementation thing: grdmask.c does this:

```
gmode = (Ctrl->S.active) ? GMT_IS_POINT : GMT_IS_POLY;
if (GMT_Init_IO (API, GMT_IS_DATASET, gmode, GMT_IN, GMT_ADD_DEFAULT, 0, options) != GMT_NOERROR)	/* Registers default input sources, unless already set */
		error = API->error;
```

So when GMT_Read_Data reads the file it automatically closes any open polygon because it knows you are giving it polygons.  I don't know exactly how things roll in your Julia wrapper but I assume that flag is never passed and it returns an open polygon and then later gmt_inonout complains about an open polygon.

**Comment by joa-quim** [comment]
It's possible. For table data I read it before hand to be able to compute automatic -R, etc and than pass the data struct to the module.

**Comment by PaulWessel** [comment]
If you use GMT_Read_Data to read it beforehand then you will need to pass the geometry flag if not -S I think.
