### ISSUE TITLE
Long options names

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2079]
A [user in the forum](https://forum.generic-mapping-tools.org/t/standardized-human-readable-gmt-parameters-for-pygmt-matlab-julia-pyshtools-etc/77) recently brought up a bit of this issue. We also have a very small collection of these in the *longoptions* branch but the full number of the to-be-baptized options is huge. Since I already did it for the Julia wrapper, I'm posting the here for discussion/approval.  The list is probably not complete because my recollection method from the .jl files not completely systematic. One thing that for sure is not complete is the list of aliases names, but most of it is (for main options) here.

Though the list is quite long, it's only the beginning. If we remember that most options have several (to many) sub-options (flags) and that all should get a keyword name we can have an idea of the full extend of this baptizing job. I've done it for many in the Julia wrapper but I'm keeping it to a later iteration.

And now, the list. Please check the boxes for the *pacific* names and bring the others to discussion.

### Common options
- [ ] -B   frame | axis | axes | xaxis,yaxis,zaxis
- [ ] -C   color | cmap
- [ ] -J   proj | projection
- [ ] -Jz  zscale | zsize
- [ ] -P   portrait
- [ ] -R   region | limits
- [ ] -U   stamp | time_stamp
- [ ] -V   verbose
- [ ] -X   xoff | x_off | x_offset
- [ ] -Y   yoff | y_off | y_offset
- [ ] -a   aspatial
- [ ] -b   binary
- [ ] -bi  binary_in
- [ ] -bo  binary_out
- [ ] -c   panel
- [ ] -d   nodata
- [ ] -di  nodata_in
- [ ] -do  nodata_out
- [ ] -e   pattern
- [ ] -f   colinfo
- [ ] -g   gaps
- [ ] -h   header
- [ ] -i   incol
- [ ] -j   spheric_dist | spherical_dist
- [ ] -l   legend
- [ ] -n   interp | interpol
- [ ] -o   outcol
- [ ] -p   view | perspective
- [ ] -r   reg | registration
- [ ] -s   skip_NaN
- [ ] -t   alpha | transparency
- [ ] -x   cores | n_threads
- [ ] -:   yx

### basemap
- [ ] -A   polygon
- [ ] -F   box
- [ ] -L   map_scale
- [ ] -Td  rose
- [ ] -Tm  compass        

### blockmean 
- [ ] -E   extended
- [ ] -S   npts | number_of_points
- [ ] -A   fields
- [ ] -C   center
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -W   weights

### blockmedian 
- [ ] -E   extended
- [ ] -Q   quick
- [ ] -T   quantile
- [ ] -A   fields
- [ ] -C   center
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -W   weights

### blockmode 
- [ ] -E   extended
- [ ] -D   histogram_binning
- [ ] -Q   quick
- [ ] -A   fields
- [ ] -C   center
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -W   weights

### clip 
- [ ] -A   straight_lines
- [ ] -C   end_clip_path
- [ ] -N   invert
- [ ] -T   clip_limits

### coast 
- [ ] -A   area
- [ ] -C   river_fill
- [ ] -D   res | resolution
- [ ] -E   DCW
- [ ] -F   box
- [ ] -G   land
- [ ] -I   rivers
- [ ] -L   map_scale
- [ ] -M   dump
- [ ] -N   borders
- [ ] -S   water | ocean
- [ ] -Td  rose
- [ ] -Tm  compass
- [ ] -W   shore

### colorbar 
- [ ] -G   truncate        
- [ ] -I   shade           
- [ ] -M   monochrome      
- [ ] -N   dpi             
- [ ] -Q   log             
- [ ] -S   nolines         
- [ ] -W   zscale          
- [ ] -Z   zfile           

### contour 
- [ ] -A   annot
- [ ] -C   cont | contours | levels
- [ ] -D   dump
- [ ] -E   index
- [ ] -G   labels
- [ ] -I   fill | colorize
- [ ] -L   mesh
- [ ] -N   no_clip
- [ ] -Q   cut
- [ ] -S   skip
- [ ] -T   ticks
- [ ] -W   pen

### fitcircle 
- [ ] -L   norm
- [ ] -F   coord
- [ ] -S   small_circle

### gmt2kml 
- [ ] -A   altitude_mode  
- [ ] -D   descript       
- [ ] -E   extrude        
- [ ] -F   feature_type   
- [ ] -I   icon           
- [ ] -K   not_finished   
- [ ] -L   extended_data  
- [ ] -N   feature_name   
- [ ] -O   overlay        
- [ ] -Qa   wiggles       
- [ ] -Qs   wiggle_scale  
- [ ] -S   scale          
- [ ] -T   title          
- [ ] -Z   attrib         

### gmtconnect 
- [ ] -C   closed
- [ ] -D   dump
- [ ] -L   linkfile
- [ ] -Q   list_file
- [ ] -T   tolerance

### grdcontour 
- [ ] -A   annot
- [ ] -C   cont | contours | levels
- [ ] -D   dump
- [ ] -F   force
- [ ] -G   labels
- [ ] -L   range
- [ ] -N   fill
- [ ] -Q   cut
- [ ] -S   smooth
- [ ] -T   ticks
- [ ] -W   pen
- [ ] -Z   scale

### gmtconvert 
- [ ] -A   h_cat             
- [ ] -C   n_records         
- [ ] -D   dump              
- [ ] -E   first_last        
- [ ] -F   conn_method       
- [ ] -I   invert            
- [ ] -L   list_only         
- [ ] -N   sort              
- [ ] -Q   select_num        
- [ ] -S   select_hdr        
- [ ] -T   suppress          
- [ ] -W   word2num          
- [ ] -Z   range             

### gmtinfo 
- [ ] -A   ranges
- [ ] -C   per_column
- [ ] -D   center
- [ ] -E   get_record
- [ ] -F   counts
- [ ] -L   common_limits
- [ ] -S   for_error_bars

### gmtregress 
- [ ] -A   all_slopes
- [ ] -C   confidence_level
- [ ] -E   regression_type
- [ ] -N   norm
- [ ] -F   column_combination
- [ ] -S   restrict
- [ ] -T   equi_space
- [ ] -W   weighted

### gmtselect 
- [ ] -A   area
- [ ] -D   res
- [ ] -E   boundary
- [ ] -F   polygon
- [ ] -G   gridmask
- [ ] -I   reverse
- [ ] -N   mask
- [ ] -Z   in_range

### gmtsimplify 
- [ ] -T   tol tolerance

### gmtspatial 
- [ ] -A   nn
- [ ] -C   clip
- [ ] -D   duplicates
- [ ] -E   handedness
- [ ] -F   force_polygons
- [ ] -I   intersections
- [ ] -N   in_polyg
- [ ] -Q   area
- [ ] -S   polyg_process
- [ ] -T   truncate

### gmtvector 
- [ ] -A   single_vec
- [ ] -C   cartesian
- [ ] -E   geod2geoc
- [ ] -N   normalize
- [ ] -S   secondary_vec
- [ ] -T   transform

### gmtwhich
- [ ] -A   with_permissions
- [ ] -C   confirm
- [ ] -D   report_dir
- [ ] -G   download

### grd2cpt 
- [ ] -A   alpha
- [ ] -D   bg background
- [ ] -E   nlevels
- [ ] -G   truncate
- [ ] -F   force_rgb
- [ ] -I   inverse
- [ ] -L   limit
- [ ] -M   overrule_bg
- [ ] -N   no_bg nobg
- [ ] -Q   log
- [ ] -S   steps
- [ ] -T   symetric
- [ ] -W   no_interp
- [ ] -Z   continuous

### grd2kml 
- [ ] -E   url
- [ ] -F   filter
- [ ] -H   sub_pixel
- [ ] -L   tile_size
- [ ] -N   prefix
- [ ] -Q   nan_t
- [ ] -T   title

### grd2xyz 
- [ ] -C   row_col
- [ ] -W   weight
- [ ] -Z   flags

### grdblend 
- [ ] -C   clobber
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -N   nodata
- [ ] -Q   headless
- [ ] -W   no_blend
- [ ] -Z   scale

### grdclip 
- [ ] -G   outgrid
- [ ] -S   high above
- [ ] -S   low below
- [ ] -S   between
- [ ] -S   old

### grdcontour 
- [ ] -D   dump
- [ ] -F   force
- [ ] -L   range
- [ ] -N   fill | colorize
- [ ] -Q   cut
- [ ] -S   smooth

### grdcut 
- [ ] -G   outgrid       
- [ ] -N   extend        
- [ ] -S   circ_subregion
- [ ] -Z   z_subregion   

### grdedit 
- [ ] -A   adjust
- [ ] -C   clear_history
- [ ] -D   header
- [ ] -E   flip
- [ ] -G   outgrid
- [ ] -N   replace
- [ ] -S   wrap
- [ ] -T   toggle

### grdfft 
- [ ] -A   azim          
- [ ] -C   upward        
- [ ] -D   dfdz          
- [ ] -E   radial_power  
- [ ] -F   filter        
- [ ] -G   outgrid       
- [ ] -I   integrate     
- [ ] -N   inquire       
- [ ] -S   scale

### grdfill 
- [ ] -A   algo
- [ ] -G   outgrid
- [ ] -L   list
- [ ] -N   nodata

### grdfilter 
- [ ] -D   distflag | distance
- [ ] -F   filter
- [ ] -G   outgrid
- [ ] -N   nans
- [ ] -T   toggle

### grdgradient 
- [ ] -A   azim
- [ ] -D   find_dir
- [ ] -G   outgrid
- [ ] -S   slopegrid

### grdhisteq 
- [ ] -C   n_cells
- [ ] -D   dump
- [ ] -G   outgrid
- [ ] -N   gaussian
- [ ] -Q   quadratic

### grdimage 
- [ ] -A   img_out image_out
- [ ] -D   img_in image_in
- [ ] -E   dpi
- [ ] -G   bit_color
- [ ] -M   monochrome
- [ ] -N   noclip
- [ ] -Q   nan_t

### grdinfo 
- [ ] -C   numeric
- [ ] -D   tiles

### grdlandmask 
- [ ] -A   area
- [ ] -D   res
- [ ] -E   bordervalues
- [ ] -I   inc
- [ ] -G   outgrid
- [ ] -N   mask_geog

### grdmask 
- [ ] -A   steps | straight_lines
- [ ] -I   inc
- [ ] -G   outgrid
- [ ] -N   out_edge_in
- [ ] -S   search_radius

### grdpaste 
- [ ] -G   outgrid

### grdproject 
- [ ] -C   center
- [ ] -D   inc
- [ ] -E   dpi
- [ ] -F   one2one
- [ ] -G   outgrid
- [ ] -I   inverse
- [ ] -M   projected_unit

### grdsample 
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -T   toggle

### grdtrack 
- [ ] -A   interp_path
- [ ] -C   equidistant
- [ ] -D   dfile
- [ ] -E   by_coord
- [ ] -N   no_skip
- [ ] -S   stack
- [ ] -T   radius
- [ ] -Z   z_only

### grdtrend 
- [ ] -D   diff
- [ ] -T   trend

### grdvector 
- [ ] -A   polar
- [ ] -I   inc
- [ ] -N   noclip
- [ ] -S   vec_scale
- [ ] -T   sign_scale
- [ ] -Z   azimuth

### grdview 
- [ ] -C   color | cmap
- [ ] -G   drapefile
- [ ] -I   shade | intensity | intensfileintens
- [ ] -N   plane
- [ ] -Q   surftype | surf_type
- [ ] -S   smooth
- [ ] -T   no_interp
- [ ] -W   pens

### grdvolume 
- [ ] -C   cont
- [ ] -L   base_level
- [ ] -S   unit

### greenspline 
- [ ] -A   gradient
- [ ] -C   approx
- [ ] -D   mode
- [ ] -E   misfit
- [ ] -G   grid
- [ ] -I   inc
- [ ] -L   leave_trend
- [ ] -N   nodes
- [ ] -Q   dir_derivative
- [ ] -S   splines
- [ ] -T   mask
- [ ] -W   uncertainties

### histogram 
- [ ] -A   horizontal
- [ ] -D   annot
- [ ] -F   center
- [ ] -Q   cumulative
- [ ] -S   stairs

### image 
- [ ] -D   ref_point
- [ ] -G   bit_color
- [ ] -I   invert_1bit
- [ ] -M   monochrome

### inset 
- [ ] -D   inset | inset_box
- [ ] -F   box
- [ ] -N   no_clip
- [ ] -M   margins

### kml2gmt 
- [ ] -F   select
- [ ] -Z   altitudes
- [ ] -E   extended

### legend 
- [ ] -C   clearance
- [ ] -D   refpoint | pos | position
- [ ] -F   box

### makecpt 
- [ ] -A   alpha | transparency
- [ ] -D   bg | background
- [ ] -E   data_levels
- [ ] -F   force_rgb
- [ ] -G   truncate
- [ ] -H   getcpt
- [ ] -I   inverse | reverse
- [ ] -M   overrule_bg
- [ ] -N   no_bg | nobg
- [ ] -Q   log
- [ ] -S   auto
- [ ] -T   range
- [ ] -W   wrap | categorical
- [ ] -Z   continuous

### mapproject 
- [ ] -A   azim               
- [ ] -C   center             
- [ ] -D   override_units     
- [ ] -E   geod2ecef          
- [ ] -F   one2one            
- [ ] -G   track_distances    
- [ ] -I   inverse            
- [ ] -L   dist2line          
- [ ] -N   geod2aux           
- [ ] -Q   list               
- [ ] -S   supress            
- [ ] -T   change_datum       
- [ ] -W   map_size           
- [ ] -Z   travel_times       

### mask 
- [ ] -C   end_clip_path
- [ ] -D   dump
- [ ] -F   oriented_polygons
- [ ] -L   node_grid
- [ ] -N   invert
- [ ] -Q   cut_number
- [ ] -S   search_radius
- [ ] -T   tiles

### nearneighbor 
- [ ] -E   empty
- [ ] -G   outgrid
- [ ] -N   ids
- [ ] -S   search_radius
- [ ] -Z   weights

### plot 
- [ ] -A   steps | straight_lines
- [ ] -C   color | cmap
- [ ] -D   shift | offset
- [ ] -E   error | error_bars
- [ ] -G   fill | markerfacecolor | MarkerFaceColor | mc
- [ ] -F   conn | connection
- [ ] -I   intens
- [ ] -L   close
- [ ] -N   no_clip | noclip
- [ ] -S   symbol | marker | Marker | shape
- [ ] -W   pen

### project 
- [ ] -A   azim
- [ ] -C   origin
- [ ] -E   end_pt
- [ ] -F   out_flags
- [ ] -G   step
- [ ] -L   length_control
- [ ] -N   flat_earth
- [ ] -Q   km
- [ ] -S   sort
- [ ] -T   pole
- [ ] -W   width_control

### psconvert 
- [ ] -D   out_dir
- [ ] -E   dpi
- [ ] -F   out_name
- [ ] -G   ghost_path
- [ ] -I   icc_gray
- [ ] -L   list_file
- [ ] -Q   anti_aliasing
- [ ] -S   gs_command
- [ ] -Z   del_input_ps

### rose 
- [ ] -A   sector
- [ ] -D   shift
- [ ] -F   no_scale
- [ ] -L   labels

### sample1d 
- [ ] -A   resamp
- [ ] -F   interp_type
- [ ] -N   time_col
- [ ] -T   equi_space

### solar 
- [ ] -C   formated
- [ ] -M   dump
- [ ] -N   invert

### spectrum1d 
- [ ] -C   response_fun
- [ ] -D   sample_dist
- [ ] -L   leave_trend
- [ ] -N   time_col
- [ ] -S   size

### sphdistance 
- [ ] -C   save_mem
- [ ] -E   what_quantity
- [ ] -G   grid
- [ ] -L   dist_unit

### sphinterpolate 
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -Q   tension
- [ ] -T   nodetable
- [ ] -Z   scale

### sphtriangulate 
- [ ] -A   area
- [ ] -C   save_mem
- [ ] -D   skip
- [ ] -L   unit
- [ ] -N   nodes
- [ ] -Q   voronoi

### splitxyz 
- [ ] -A   azim_tol
- [ ] -C   course_change
- [ ] -D   min_dist
- [ ] -F   filter
- [ ] -Q   xyzdh
- [ ] -S   dh

### subplot 
- [ ] -A   autolabel | fixedlabel
- [ ] -C   clearance
- [ ] -M   margins
- [ ] -F   dims | dimensions | size | sizes
- [ ] -S   SC | SR | row_axes | col_axes
- [ ] -T   title

### surface 
- [ ] -A   aspect_ratio
- [ ] -C   convergence
- [ ] -G   grid
- [ ] -I   inc
- [ ] -Ll  lower
- [ ] -Lu  upper
- [ ] -N   max_iter
- [ ] -Q   suggest
- [ ] -S   search_radius
- [ ] -T   tension
- [ ] -Z   over_relaxation

### ternary 
- [ ] -D   shift | offset
- [ ] -L   labels
- [ ] -M   no_plot
- [ ] -N   no_clip

### text 
- [ ] -A   azimuths
- [ ] -C   clearance
- [ ] -D   offset
- [ ] -F   attrib
- [ ] -G   fill
- [ ] -L   list
- [ ] -M   paragraph
- [ ] -N   no_clip | noclip
- [ ] -Q   change_case
- [ ] -T   text_box
- [ ] -W   pen
- [ ] -Z   threeD

### trend1d 
- [ ] -C   condition_number
- [ ] -I   confidence_level
- [ ] -F   output
- [ ] -N   n_model
- [ ] -W   weights

### trend2d 
- [ ] -C   condition_number
- [ ] -I   confidence_level
- [ ] -F   output
- [ ] -N   n_model
- [ ] -W   weights

### triangulate 
- [ ] -C   slope_grid
- [ ] -D   derivatives
- [ ] -E   empty
- [ ] -G   grid
- [ ] -M   network
- [ ] -N   ids
- [ ] -Q   voronoi
- [ ] -S   triangles
- [ ] -T   edges
- [ ] -Z   xyz

### wiggle 
- [ ] -A   azimuth
- [ ] -C   center
- [ ] -I   fixed_azim

### xyz2grd 
- [ ] -A   multiple_nodes
- [ ] -D   header
- [ ] -G   outgrid
- [ ] -I   inc
- [ ] -S   swap
- [ ] -Z   flags

**Comment by PaulWessel** [comment]
I wonder if this is a good topic to get started on during AGU.  Since we are all there it should be possible to make progress.  Until AGU things will be very hectic.

**Comment by joa-quim** [comment]
Yes, but better if we already had the list reduced to the more questionable namings.
Not sure on how to proceed here. Maybe start moving the agreed modules into an rst file for future reference.

**Comment by PaulWessel** [comment]
Also unclear what you mean by _pacific_ names.

**Comment by joa-quim** [comment]
*pacific* = *no discussion*. For example **-g** => *gaps*

**Comment by PaulWessel** [comment]
So therefore _atlantic_ = discussion.  Got it.
I wonder if another document is better for this, such as a list of proposed words (Like yours) plus room for comments.  Maybe even a google docs to let us hash out the arguments.  For instance, for **-B**, there is axis and axes.  In Matlab those are very different thing (axis is more like **-R**).  So I don't know what it means to check that box.

**Comment by joa-quim** [comment]
> So therefore atlantic = discussion

I though in giving exactly this example too.

My idea was that we maybe could use my list to select the Atlantic cases and then discuss them. Not easy, it's a long list.
**-B** continues to be a tough case. I actually am only using *frame* and *xaxis*, *yaxis* where later are used for setting parameters on individual axis separately.

**Comment by joa-quim** [comment]
Do you know why the *Pacific Ocean* is got that name?

**Comment by PaulWessel** [comment]
I think because it was peaceful when Magellan first encountered it.

**Comment by joa-quim** [comment]
Right

Sent from my iDedo

**Comment by joa-quim** [comment]
Outdated too.
