### ISSUE TITLE
One liner plot and output name

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#2082]
If you include the file extension while doing a one liner plot, you get an error that the file does not exist. ``xdg-open`` tries to find ``map.pdf.pdf``, but GMT removed the extra extension producing  ``map.pdf``.

```
$ pscoast -RNO -Gblack -Swhite -pdf map.pdf
xdg-open: file 'map.pdf.pdf' does not exist
docs [ERROR]: Opening local file map.pdf.pdf via xdg-open failed with error 512
docs: No such file or directory
end [ERROR]: Failed to call docs
end [ERROR]: process_figures returned error 78
coast [ERROR]: Unable to call module end for a one-liner plot.
```

Of course, this is more of a user error as you should not include the file extension in the file name.

**Comment by seisman** [comment]
`gmt basemap -JX10c -Baf -R0/10/0/10 -pdf map.abcpng` gives me `map.ab.pdf`.
