### ISSUE TITLE
Modern mode is fooled by PS_MEDIA setting

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2099]
A modern mode plot should not listen to **PS_MEDIA** settings unless we are making a PostScript plot.  This example demonstrates the problem:

```
gmt begin map
  gmt set PS_MEDIA letter
  gmt coast -JU20/9i -BWSen -B2mf1mg2m -R-64.34/-64.19/44.43/44.56 -Df -Gtan -Wthinnest
gmt end show
```

If we comment/remove the gmt set command it works correctly.

**Comment by seisman** [comment]
Closed by #2100.
