### ISSUE TITLE
Scripts for GMT4-compatibility don't work

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2104]
We provide several scripts to allow users to call modules like "grdimage" without the "gmt" prefix.
- gmt_aliases.csh
- gmt_functions.sh
- gmt_links.sh

These scripts don't work because `gmt --show-modules` now returns modern mode module names. Thus, these scripts provide "basemap" instead of "psbasemap".

**Comment by PaulWessel** [comment]
Might we need a gmt --show-classic-modules option to solve this problem?

**Comment by seisman** [comment]
I think so.

**Comment by seisman** [comment]
Closed by #2137.
