### ISSUE TITLE
Enhancement of Blockmedian -Q

### ISSUE THREAD

**Issue by hanoia** [GenericMappingTools/gmt#2111]
Make it possible to get true positions reported for all values when -Q is used, even for cells with even number of values.

**First:** It would be great to get a option to force “blockmedian -Q” _(or blockmedian -Q -T0.5)_  to select the smaller or larger of the two values if there is a tie (even number of samples)? That would give a small shallow or deep bias to a bathymetric dataset, but still only select from true measured points in their true positions. 
**Second:** One could also add a random selection whether the low or high value should be selected to keep the output to provide the sought z value to be a measured value in true position. As the number of cells and number of datapoints normally is high the distribution of cells containing odd or even number of datapoints could be random enough to just have a toggle switch assigning the first occurance of a tie to the low value, second tie to the high and so on.
**Comment:** Even if only one of the two suggestions above is included in future releases it would solve the main issue assertaining only true values and positions as output from blockmedan -Q.

I can see that for the switch " -E r | s [ - ] there is a possibility to select if the record number should origin from the low or high value, given it is a tie.

**Are you willing to help implement and maintain this feature?** No (dont have enough knowledge of C programming)

**Comment by joa-quim** [comment]
I'm afraid this will happen only if an interested person steps on with an implementation.
