### ISSUE TITLE
mapproject, grdtrack bug

### ISSUE THREAD

**Issue by sistephenson** [GenericMappingTools/gmt#2112]
I have an issue with mapproject and grdtrack in gmt6.0.0.  NB. this issue may also apply to some other functions but so far I have only encountered it with these two.

It seems that output data columns, instead of being appended to the end of the data file as in previous versions, are being inserted into the data table before the first field containing text strings.  I am not 100% certain this is always the pattern but it seems so.  In the following examples I have highlighted the output value from grdtrack in **bold**.

I have an input file of the format (x, y, text string):
47 -17 Hello

and I want to extract values from a grid using the following snippet of code...
`cat input.dat | gmt grdtrack -Ggrdfile.grd

e.g. with gmt5 grdtrack gives...
47 -17 Hello **0.24706250016**

But with gmt6 grdtrack the same code gives...
47 -17 **0.24706250016** Hello

Note that the last two columns are flipped.  If text strings or numeric fields follow the first text field, then the output from grdtrack is always inserted before the first text field.  e.g...

`echo 47 -17 Hello 10 27 | gmt grdtrack -G$infile`

yields...
47 -17 **0.247062500161** Hello 10 27

while...
`echo 47 -17 10 27 Hello | gmt grdtrack -G$infile`

yields...
47 -17 10 27 **0.247062500161** Hello

So the output seems to appear in any arbitrary column, but always immediately before the first text string.  grdtrack works absolutely as expected if input data tables only contain numerical values.

e.g.
`echo 47 -17 10 27 | gmt grdtrack -G$infile`

yields...
47 -17 10 27 **0.247062500161**

with the new value always appended to the end of the table as the final field.

I don't know if I am misunderstanding a new feature in GMT 6 or whether this is a bug!

Many thanks.

**Comment by PaulWessel** [comment]
Please see https://docs.generic-mapping-tools.org/6.0/cookbook/options.html#input-columns-selection-the-i-option.

This aspect (random text placement) is one thing we had to break compatibility with going forwards.  GMT 6 has a much stronger handling of text as part of records, one can even address individual words in the trialing text via **-it**.  But all text is trailing, that is, following any and all numerical columns, and numerical columns added as part of a module operation will be added at the end of the numerical section, before any trailing text.  Hence this is not a bug but a deliberate decision that had to be made to address a host of other issues, especially in passing GMT data to/from external environments such as MATLAB, Python, and Julia.

**Comment by sistephenson** [comment]
Hi Paul,

Many thanks for clarifying.  I hadn't seen this new part of the cookbook and that makes sense.

Thanks

Simon

**Comment by sistephenson** [comment]
Hi Paul,

Many thanks for clarifying.  I hadn't seen this new part of the cookbook and that makes sense.

Thanks

Simon
