### ISSUE TITLE
Missing gmt.conf in GMT Modules list

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2118]
Like it says. Front page doesn't list gmt.conf but it can be accessed via the gmtdefaults man

**Comment by PaulWessel** [comment]
Well, so is colors, but neither is a module.

**Comment by joa-quim** [comment]
Right, it's not a module, but what if we need to consult it?

**Comment by PaulWessel** [comment]
Sorry, I don't understand the question now.  You can consult it with

gmt docs defaults
gmt docs gmt.conf

**Comment by joa-quim** [comment]
The point is that I don't understand why we are hiding it (we have had it for decades next to the other man pages). Yes, we can consult it with gmt docs but for that we need to know that page exists. An occasional user will most likely not.

**Comment by seisman** [comment]
It's in the quick links.
![image](https://user-images.githubusercontent.com/3974108/69392324-a7a48100-0ca3-11ea-814a-5e9ab10c655a.png)

**Comment by joa-quim** [comment]
And it's called ``GMT Defaults`` and we also have a module called gmtdefaults so when I see the first I think on the second. Good that it is on the quick links but it should also be next to other man pages, even though it's not a module. Again, that's what with did since last century.

**Comment by seisman** [comment]
"GMT Defaults" looks a bad name. What about `GMT Default Settings (gmt.conf)`?

**Comment by PaulWessel** [comment]
I like the word "settings" but GMT Default Settings (gmt.conf) is pretty long, no?

**Comment by seisman** [comment]
Not that long.
![image](https://user-images.githubusercontent.com/3974108/69396248-a5e0ba80-0caf-11ea-80f4-254fe1980427.png)

**Comment by PaulWessel** [comment]
OK, then fine with me.

**Comment by seisman** [comment]
I don't like the idea to have "gmt.conf" or "gmtcolors" in the module list, even though they have been there for a long time.

**Comment by PaulWessel** [comment]
I agree, they are not modules.

**Comment by joa-quim** [comment]
Do you guys think a user cares if ``gmt.conf`` is a module or not when he/she searches the 
https://docs.generic-mapping-tools.org/latest/modules.html
page, that gathers all the man pages, and does not find it? Heck, I was that user yesterday.

And BTW none of these ([utility scripts](https://docs.generic-mapping-tools.org/latest/modules.html#utility-scripts)) are modules but they live in the same page.

**Comment by PaulWessel** [comment]
If you start at the top then it lists a few quick links first, so one of the first things you see is the defaults link.  If you go to modules to look for non-modules then I think you are doing it wrong.
Yes, the utilities are not modules either and if that bothers you I don't mind seeing those as a separate entry under Resources.  But that is not an argument for letting a configuration table appear under modules.

**Comment by seisman** [comment]
@joa-quim Are you OK closing this issue?

**Comment by joa-quim** [comment]
With closing yes, what not ok is with the result.
