### ISSUE TITLE
Cached remote files are never updated

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2129]
When we access the remote files distributed via the GMT servers have checks on sha256 and dates, so if we update these files on the server then the users will notice within 24 hours or so.

We also allow remote files in two other formats:

- Plain URL reference [e.g., _site_/file.txt]
- URL Query [e.g., _site_?minmagnitude=5]

The query result is used locally and is always rerun each time, but the plain URL file is placed in the GMT cache file and is then found when read a 2nd time.  This means the user will have to remember to delete it if it may change with time.  However, even if we did not place it in cache and just in the current directory, as long as that file is there and the user rerun the command in that directory, the user will get the local file.

There is no perfect solution here, but I think leaving it in the local directory makes more sense than adding it to a hidden .gmt directory that the user may not think about.

**Comment by seisman** [comment]
I agree.
