### ISSUE TITLE
gmt simplify - avoid loss of aspatial data

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#213]
Using ``gmt simplify`` may lead to aspatial data loss. In my case below the ELEV (contour level) attribute is lost.

Extract contours from a dataset. See the aspatial data present in this data.
```
$ gdal_contour -i 1000 -a ELEV earth_relief15m_cut.grd contours.gmt -f GMT

# @VGMT1.0 @GLINESTRING
# @R-9.125/33.625/57.875/80.875                                           
# @NID|ELEV
# @Tinteger|double
# FEATURE_DATA
>
# @D0|-4000.000
-2.51908396946565 80.875 -4000
-2.51908396946565 80.75 -4000
-2.5 80.7411504424779 -4000
-2.25 80.6331325301205 -4000
-2.0 80.5235294117647 -4000
-1.87459283387622 80.75 -4000
-1.87459283387622 80.875 -4000
>
# @D1|-1000.000
14.8101851851852 80.875 -1000
14.8101851851852 80.75 -1000
15.0 80.7099609375 -1000
15.25 80.6861036639857 -1000
15.5 80.6823694029851 -1000
15.75 80.6968716289105 -1000
16.0 80.7331824062096 -1000
16.0714285714286 80.75 -1000
16.0714285714286 80.875 -1000
```

Then simplifying with ``gmt simplify``, the aspatial data is lost.
```
$ gmt simplify -T1k cont.gmt
>
-2.51908396947  80.875  -4000
-2.51908396947  80.75   -4000
-2      80.5235294118   -4000
-1.87459283388  80.875  -4000
>
14.8101851852   80.875  -1000
14.8101851852   80.75   -1000
15      80.7099609375   -1000
15.25   80.686103664    -1000
15.5    80.682369403    -1000
15.75   80.6968716289   -1000
16.0714285714   80.75   -1000
16.0714285714   80.875  -1000
```

In my opinion, this greatly reduces the usefulness of the tool.

**Comment by PaulWessel** [comment]
Agreed, we need to fix this.  Currently at AGU and no time for coding.

**Comment by abanbj** [comment]
Some more about this.

- Why does not GMT write the OGR/GMT header after processing with ``gmt simplify``?
- What about adding an option to ``gmt simplify`` to specify min/max length to process? Like ``gmt spatial -Q][+cmin[/max]`` option.

**Comment by PaulWessel** [comment]
Lets keep this one alive.

**Comment by abanbj** [comment]
Lets keep this one alive?

**Comment by joa-quim** [comment]
This is becoming boring. How do we change the label properties so that the bot does not try to close it.

**Comment by PaulWessel** [comment]
Could we just have it label the issue STALE but not close it after 7 days?

**Comment by anbj** [comment]
Too old. Lack of interest. Closing. Will turn up again if it needs to.
