### ISSUE TITLE
Update gmtdefaults usage 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2143]
The usage and manapge says the **-D** is optional, but `gmt defaults` alone only print its usage. So **-D** is required. Right?

I'd like to fix it after you confirm that it's a bug.

**Comment by PaulWessel** [comment]
More than one thing here.  I think the **-Du**|**s** derives from the olden days when we wrote inches or cm as length units for things like **MAP_ORIGIN_X**, but now we always write points.  E.g.,

```
gmt defaults -Du > u
gmt defaults -Ds > s
diff u s

```
returns nothing.  So what is the point of **-D** at all?  Maybe better to remove it (but accept it as backwards compatibility) and not have any options at all.

**Comment by seisman** [comment]
This is what I get:
```
diff u s
121c121
< PROJ_LENGTH_UNIT               = inch
---
> PROJ_LENGTH_UNIT               = cm
127c127
< PS_CHAR_ENCODING               = Standard+
---
> PS_CHAR_ENCODING               = ISOLatin1+
135c135
< PS_MEDIA                       = letter
---
> PS_MEDIA                       = a4
150c150
< TIME_WEEK_START                = Sunday
---
> TIME_WEEK_START                = Monday
```

**Comment by PaulWessel** [comment]
I think that was the intention but clearly it depends on gmt.conf setting somewhere.  If you have a gmt.conf set to US then they are identical.  So a bug I would say.

**Comment by PaulWessel** [comment]
If there is a gmt.conf that has all those 4 settings already, then regardless what they are the gmt defaults **-D** will read those and write out the same thing, hence my diff gave nothing.  If the gmt.conf misses one or more of those, then the output will be different but only for that one.  So not sure what is a good solution here, other that to say **-D** is required.  I think the real fix would be to either ignore the gmt.conf (but that is processed during session creation) or re-initialized to either US or SI depending on -D and then print that out.
