### ISSUE TITLE
gmt logo -U

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2162]
```
gmt logo -Dx0/0+w2i -U -png logo
```

![image](https://user-images.githubusercontent.com/3974108/69667940-ef892680-105c-11ea-8b38-fd559057ddea.png)

**Comment by PaulWessel** [comment]
So all the GMT_Call_Module calls add the time stamp.  I will have to debug to see why because we reset U.active to FALSE in gmt_init_module somewhere.
