### ISSUE TITLE
gmtinfo -Is oddity

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#2165]
I'm attaching a file (tws.txt) consisting of 5664 records. When issuing this command:

> gmtinfo tws.txt

the response is:

tws.txt: N = 5664	<0/5657>	<0.0914101/17.674>

just as expected.

But, when using -Is1 (upper case "eye"), the response is far off the mark:

> gmtinfo tws.txt -Is1
-R-51/5708/-6/25

What was expected was: -R-1/5658/0/18

Is there something amiss?
[tws.txt](https://github.com/GenericMappingTools/gmt/files/3894101/tws.txt)

**System information**

* Operating system: Mac OS 10.13.6
* GMT version (`gmt --version`): 6.1.0_2413ce5_2019.11.26

**Comment by PaulWessel** [comment]
Why do you say "Far off the mark"? It returns a region that has a nx by ny that will work fast in surface.  The -Is1 gives you 5760 by 32 it seems.

**Comment by PaulWessel** [comment]
Specifically, 5760 has factors 2^7, 3^2, and 5, hence lots of intermediate stages for surface to work on.

**Comment by macpurity** [comment]
I see. You presumed that I was feeding this to surface, but it's just an xy-file (no z-values). My intention was to ask gmtinfo for suggested -R parameters to make a simple xy-plot, with a slight extension to the bounds of the plot. By giving -Is[dx], with dx=1, I was expecting gmtinfo to return -R-1/5658/0/18, rounding to the next (outside) value. Am I misusing this command?

**Comment by macpurity** [comment]
No oddity (except for user misuse!). The command without "s" is:

gmtinfo tws.txt -I1

yielding: -R0/5657/0/18, which is close enough. I'd still like x-values to go from -1 to 5658, in order to avoid data being plotted directly on the axes, but I can live with this.

Please close this issue.

**Comment by seisman** [comment]
I find a few issues/questions when trying the gmtinfo module:

1. Zero is always multiples of any _dx_. Like in this case, you can never get a string like `-R-2/5668/0/18` by giving **-I2**

2. Confusing error message:
```
$ gmt info tws.txt -I
gmtinfo [ERROR]: Syntax error: -Ip requires -C
$ gmt info tws.txt -Ip 
gmtinfo [ERROR]: Syntax error: -Ip requires -C
$ gmt info tws.txt -Is  
gmtinfo [ERROR]: Syntax error: -Ip requires -C
$ gmt info tws.txt -Ip1 
gmtinfo [ERROR]: Syntax error: -Ip requires -C
```

3. **-Ib** doesn't support dx/dy
```
$ gmt info tws.txt -Ib2
0	0.09141009
5657	0.09141009
5657	17.67401976
0	17.67401976
0	0.09141009
```

**Comment by joa-quim** [comment]
I recently had a similar issue in Julia. My solution was to add +/- 0.05% of the column's data range. Like this we never have points plotted on the axes.

**Comment by PaulWessel** [comment]
Perhaps gmtinfo can take a few tricks from ****-R**_ISO_**+r**|**R**?  As you know, **+r** extends the domain outward to the nearest multiple, while **+R** extends the domain outward by adding the amount.  This is different from the exact multiple of dx which, as you point out, means point at 0 will always plot on the axis.  I think we could add **+r**|**R** to the **-I** option, no?

**Comment by seisman** [comment]
Just found some other issues:

```
$ gmt info tws.txt -Ip -C
-179.96	180	0.09141009	17.67401976
```
The first two columns don't make any sense.

**-I** with non-positive increment:
```
$ gmt info tws.txt -I0
gmtinfo [ERROR]: Syntax error -I option: Must specify positive increment(s)
gmtinfo [ERROR]: Syntax error -I option: Must specify positive increment(s)
$ gmt info tws.txt -I-5
-R0/5657/0.09141009/17.67401976
```

**Comment by macpurity** [comment]
Paul, that could be a welcome feature, to add +r|R to the -I option.

I guess, for quite some time, I was thinking that -Is option would do exactly that, but clearly, I was not fully appreciating that it is really meant for feeding data into surface. [You mean I have to read the fine print in the man page?!]

**Comment by PaulWessel** [comment]
Try -I+e|r|R<incs> in master.
