### ISSUE TITLE
No struct GRD_HEADER in GMT-V5.x?

### ISSUE THREAD

**Issue by Liu-Richard** [GenericMappingTools/gmt#2184]
**System information**:
server: aarch64-arm-linux
OS:centOS7.6
gcc:4.8.5
shakemap:v3.5 
gmt:5.4.5

**Description of the problem**

when I built shakemap(v3.5), compiling error as flows:
can not find struct GRD_HEADER
**Full script that generated the error**:
**Full error message**:
[root@ shakemap-3.5]# make all
.....
make[2]: Entering directory `/home/gmt/shakemap-3.5/src/contour'
/usr/bin/cc -O -I . -I /usr/local/gmt/include/gmt -I /usr/local/netcdf/include -c contour.c
contour.c: In function ‘main’:
contour.c:237:21: error: storage size of ‘gh’ isn’t known
   struct GRD_HEADER gh;
                     ^
contour.c:260:19: warning: incompatible implicit declaration of built-in function ‘strlen’ [enabled by default]
         } else if(strlen(optarg) == 0 || (contourfile = strdup(optarg)) == 0) {
                   ^
contour.c:260:57: warning: incompatible implicit declaration of built-in function ‘strdup’ [enabled by default]
         } else if(strlen(optarg) == 0 || (contourfile = strdup(optarg)) == 0) {
                                                         ^
contour.c:426:57: error: ‘FALSE’ undeclared (first use in this function)
   if( GMT_read_grd(grdfile, &gh, grid, 0, 0, 0, 0, pad, FALSE) ) {
                                                         ^
contour.c:426:57: note: each undeclared identifier is reported only once for each function it appears in
contour.c: In function ‘get_new_cpoint’:
contour.c:928:5: warning: incompatible implicit declaration of built-in function ‘memset’ [enabled by default]
     memset(buf, 0, NGRAB * sizeof(CPoint));
     ^
contour.c: In function ‘dup_cpoint’:
contour.c:938:3: warning: incompatible implicit declaration of built-in function ‘memcpy’ [enabled by default]
   memcpy(np, p, sizeof(CPoint));
   ^
make[2]: *** [contour.o] Error 1
make[2]: Leaving directory `/home/gmt/shakemap-3.5/src/contour'
make[1]: *** [contour] Error 2
make[1]: Leaving directory `/home/gmt/shakemap-3.5/src'
make: *** [all] Error 2

I found the struct GRD_HEADER is in gmt_grd.h, but only gmt version 4.x has struct GRD_HEADER , gmt -5.4.5 does not has struct GRD_HEADER.

any idea to solve this issue? use gmt-v4.x or modify gmt-5.x ?
thanks

**Comment by PaulWessel** [comment]
See gmt.h and gmt_resources.h for what is exported.  In GMT 5 and 6 we have

`struct GMT_GRID_HEADER;`

That will get you past that compilation hurdle, but probably you will eventually want to use the GMT API functions rfor eading grids etc, e.g.,

`G = GMT_Read_Data (API, GMT_IS_GRID, GMT_IS_FILE, GMT_IS_SURFACE, GMT_CONTAINER_AND_DATA, wesn, Ctrl->F.file, NULL));`

**Comment by joa-quim** [comment]
@Liu-Richard, The GMT6 has a branch called ``shakemap`` with two modules ``vs30`` and ``shake``. It would be very nice if you could build and test it. They don't have man pages yes but the online help should be enough to start. I'm printing it below.

```
$ vs30
gmt vs30 [meca] 6.1.0_6dc011b_2019.11.29 [64-bit] [MP] - Compute VS30

usage: gmt gmt vs30 <grid> -G<outgrid> [-C<val>|fname[+g]] [-W<water_vel>] [-R<west>/<east>/<south>/<north>[/<zmin>/<zmax>][+r]] [-V[<level>]]
        <grid> The input grid name of the topography.
        -G File name for output grid with the Vs30 velocities.
        -C Argument can be one of three:
           - A value between 0 and 1, where 0 means a stable Craton and 0 an Active region.
           - The name of a multi-segment file with the 'cratons' polygons. In this case the
             polygons will be feed to grdmask to compute a cratons/active tectonic mask.
           - The name of a grid with the cratons/active tectonic regions.

        OPTIONS:
        -W water_vel sets the Vs30 value used in areas designated as water in the
           landmask [default=600]
```

```
$ shake
gmt shake [meca] 6.1.0_6dc011b_2019.11.29 [64-bit] [MP] - Compute Peak Ground Acceleration/Velocity and Intensity.

usage: gmt gmt shake <grid> -G<outgrid> -L<fault.xy> -M<mag> [-F<mecatype>] [-R<west>/<east>/<south>/<north>[/<zmin>/<zmax>][+r]] [-V[<level>]]
        <grid> The grid with the Vs30 velocities.
        -G Specify file name for output grid file(s).
           If more than one component is set via -C then <outgrid> must contain %s to format component code.
        -L <fault.xy> name of a file with the coordinates of the fault trace.
        -M <mag> Select magnitude.

        OPTIONS:
        -C List of comma-separated components to be written as grids (requires -G). Choose from
           a, v, i. [Default is i(ntensity)].
        -F Select focal mechanism type (e.g. -F1 or -F2 ...).
           1 unknown [Default].
           2 strike-slip.
           3 normal.
           4 thrust.
```

**Comment by Liu-Richard** [comment]
thanks but I still want to use gmt-5.4.5 and shakemap-3.5, but how do i find the map relation between gmt-4.x and gmt-5.4.x,
eg: in gmt-4.5  has function "GMT_read_grd" .but gmt-5.4.5 doesn't has.

so how do i modify the call function in shakemap-3.5,thanks

**Comment by joa-quim** [comment]
GMT4 & GMT5 are very different beasts. GMT5 is a library, you must use it's API to do the file reading. There is no simple one-to-one replacement.

**Comment by PaulWessel** [comment]
I suggest you look at a simple gmt module that reads and writes grid files to see what modifications you need to do.  I think grdsample.c is pretty simple. It first reads the grid header, then uses that to create an output grid, then read in the input grid, do its thing, and then write the output grid.  We can help you as you have questions on this.  Being stuck doing GMT 4 now that GMT 6 is released is not a good plan in my opinion.

**Comment by seisman** [comment]
Closing the issue. If you still have questions, please post on the [forum](https://forum.generic-mapping-tools.org/).
