### ISSUE TITLE
The plot man page has strange formatting for -L and example

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2189]
Looks like some old HTML code example for **-L** survived by is badly formatted and looks out of place. A few parameters are also not italicized in the text.

**Comment by PaulWessel** [comment]
Hi @joa-quim is this something we should remove or move down to examples, etc?

**Comment by joa-quim** [comment]
It's more like the old functionality should be restored.

**Comment by PaulWessel** [comment]
OK, but can it?

**Comment by joa-quim** [comment]
It was a pure RST before so I'm assuming it can.
