### ISSUE TITLE
GMT_Encode_Options and modern mode troubles

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2196]
The GMT mex was built and tested for classic mode.  Experiments by @joa-quim via Julia with modern mode has shown a few issues, which are also shared in GMT mex.  Here I list gmt mex commands:

1. `gmt ('begin') `does initiate a modern mode session, and API->GMT.current.settings.run_mode is set to **GMT_MODERN**. However, when the next module is called, here `gmt('plot', xy)` (xy is a MATLAB matrix),  and the persistent MATLAB API pointer is recycled, the _run_mode_ is back to **GMT_CLASSIC**.  So we don't know we are being called in modern mode; not sure where it gets reset yet.
2. The various checks in _GMT_Encode_Options_ are using classic module names, but we are running **plot**.  I have fixed this to always obtain the classic names, so that problem is solved.
3. Next is the issue of **KEYS**.  I notice many of the _PostScript_ modules have **KEYS** in the format _classic@modern_, and if modern mode we get the _modern_ keys after the @ character, else we get the _classic_ part.  This failed because the run_mode parameter was not set yet.  I can probably set that one one way or the other to extract the correct keys.  A simple ways is to compare if given and classic module name differs, but that will fail if someone uses the name psxy in modern mode (a bad idea anyway, but seems fragile).
4. Yet, many _PostScript_ producing modules do **not** have _classic@modern_ strings and I don't understand why. Some, like pscoast, can do many things and those cases are explicitly handled by tests in GMT_Encode_Options. But, for instance, psxy/plot is only a _PostScript_ producer so why does it not have the modern keys that specifically exclude the _PostScript_ key? As it is, _GMT_Encode_Options_ determines it needs an output filename and we end up with the command `gmt plot -<? ->?`, where the input ? will be linked to data from MATLAB but the output will go crazy since we don't write _PostScript_ to stdout in modern mode.  Again, if we know it is modern mode then all the PostScript keys should just be skipped.

I will try to determine we are modern mode and see if adding modern keys to psxy takes us a step further.

**Comment by PaulWessel** [comment]
I think I got these things solved. Determining modern mode is about calling `gmt_manage_workflow (API, GMT_USE_WORKFLOW, NULL)` which sets the run_mode for us.  Once that is set then the _PostScript_ **KEYS** are automatically skipped.  That is why there is no _classic@modern_ keys for many _PostScript_ producers: they have the same keys except for the _PostScript_ output.  Then, the key problem was the need to read the memory data twice: First to detect the region, then as input to plot.  The first read sets the resource to **GMT_IS_USED** and then we cannot read again.  Because of where the call to gmtinfo happens I had to finesse a temporary setting so that we automatically set the resource to **GMT_IS_UNUSED** after reading.  And finally, in gmtmex.c we needed to allow for a check for the module end which was added after GMTMEX was published.

**Comment by PaulWessel** [comment]
This mex script now works for me:

```
xy = [0.0 0; 1 1; 2 3];   
gmt ('begin', 'lixo ps')  
gmt ('plot', xy)          
gmt ('end', 'show')   
```

Need help to get the _apiencodefix_ commit turned into a pull request...

**Comment by PaulWessel** [comment]
Remind me to do a similar fix for memory **grids**.

**Comment by joa-quim** [comment]
It now works in julia too. Leave it as is. It's already committed and works. Otherwise I suspect that the commit would have to be reverted and create a PR with the same content.
What do you mean by ``memory grids``? When first module is ingests a grid and use it to set the script's -R?

**Comment by PaulWessel** [comment]
Yes, I asked @dondong to help turn it into a PR so I can add the solution for grids as well.
