### ISSUE TITLE
The results of the psxy plot are not precise

### ISSUE THREAD

**Issue by Halauwet** [GenericMappingTools/gmt#2197]
**psxy plot give unprecise results (maybe decimal rounding)**

My psxy plot have no error, but give plotted data like a grid point, even though the input data is more than 4 decimal precision. Anyone can help?

**Full script that generated the error**

```
#
set ps=animasi.ps
set data=data.txt

gawk -F" " "{print $6,$7,$8,$9,$10}" %data% | project -C128.38/-3.53 -A180 -Fxyzpqrs -Q > proyeksi.dat
psbasemap -JX8/3.5 -R-40/40/-50/0 -Bxa20+l"Distance (km)" -Bya20f20+l"Depth (km)" -BWSne+t"Cross Section" --MAP_ANNOT_MIN_SPACING=0.1p --FONT_ANNOT_PRIMARY=8 --FONT_LABEL=9 --FONT_TITLE=10 -K > %ps%
gawk -F" " "{print $7,$3*(-1.0)}" proyeksi.dat | psxy -R -J -Sc0.08 -Gred -W0.2 -O -K >> %ps%

```

**gmtset format that is used**
FORMAT_GEO_OUT=D
FORMAT_GEO_MAP=ddd:mm:ss
FORMAT_FLOAT_OUT=%.12g
FORMAT_FLOAT_MAP=%.12g

**System information**

* Operating system: Windows 10 64-bit
* GMT version (`gmt --version`): 5.4.5
* Ghostscript: 9.50

[data.txt](https://github.com/GenericMappingTools/gmt/files/3911756/data.txt)
![output](https://user-images.githubusercontent.com/45411706/69968274-a4837d80-154c-11ea-85f8-254c8ab155c3.jpg)

**Comment by joa-quim** [comment]
> Anyone can help?

Please, we have a [forum ](https://forum.generic-mapping-tools.org/) that is the right place to ask help.

**Comment by joa-quim** [comment]
And if you look at your Y coordinates, you'll see that they are all integers 

```
gawk -F" " "{print $6,$7,$8,$9,$10}" data.txt | project -C128.38/-3.53 -A180 -Fxyzpqrs -Q | gmt gmtinfo -i6,2
<Standard Input>: N = 865       <-136.541713179/35.5296734225>  <1/79>
```

**Comment by Halauwet** [comment]
> > Anyone can help?
> 
> Please, we have a [forum ](https://forum.generic-mapping-tools.org/) that is the right place to ask help.

I'm sorry @ joa-quim, I already tried to create an account at http://gmt.soest.hawaii.edu/account/register before to ask, but there is a captcha problem so I can ask there. Thank you for providing this [forum](https://forum.generic-mapping-tools.org/) link , I will my question there.

**Comment by Halauwet** [comment]
> And if you look at your Y coordinates, you'll see that they are all integers
> 
> ```
> gawk -F" " "{print $6,$7,$8,$9,$10}" data.txt | project -C128.38/-3.53 -A180 -Fxyzpqrs -Q | gmt gmtinfo -i6,2
> <Standard Input>: N = 865       <-136.541713179/35.5296734225>  <1/79>
> ```

Yes, the maximum and minimum values happen to an integer, but other values are float.

**Comment by joa-quim** [comment]
Right, but your z column has only 1 decimal place, not 4.

**Comment by Halauwet** [comment]
> Right, but your z column has only 1 decimal place, not 4.

I mean the input with more than 4 decimal is the x column. It has 9-10 decimal, but the plot show vertical line trend with straight space between the lines.
