### ISSUE TITLE
plot3d bugs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2209]
Tried plot3d and found some possible bugs.

1. This is an example shown in the plot3d manpage. Copy and run the command should report an error "t.cpt not found", but it doesn't.

```
echo 175 30 0 | gmt plot3d -R150/200/20/50 -JM15c -Sc0.5c -Z65 -Ct.cpt -pdf map
```

2. Without **-G** or **-W** options, **plot** module plots symbols with the default pen. But for **plot3d** module, I have to give **-G** or **-W**. The command below gives nothing unless **-G** or **-W** is given.
```
echo 175 30 0 | gmt plot3d -R150/200/20/50 -JM15c -Sc0.5c -pdf map
```

3. The command below plots a distorted circle in a 3D perspective view. Sometimes users may want undistorted circles. Is it possible to achieve that? 
```
echo 175 30 0 | gmt plot3d -R150/200/20/50/0/10 -JM15c -JZ8c -Sc0.5c -Gred -BWSenZ -Baf -p145/30 -png map
```

![image](https://user-images.githubusercontent.com/3974108/70089330-deed2900-15e5-11ea-8a76-09fc1fc3e72d.png)

**Comment by PaulWessel** [comment]
Quick responses to 1-3 above:

1. That needs to be fixed.
2. Agree it should be the same for plot and plot3d on -G -W behavior
3. Not possible since we are setting up a projection 3x3 matrix in PostScript.  So we are still plotting regular circles but they will appear as you see, as does all text, lines, whatever.  So if a user wants undistorted circles they need to use less capable software!

**Comment by joa-quim** [comment]
The real limitation of 3 is that we can't plot spheres.

**Comment by seisman** [comment]
https://rosettacode.org/wiki/Draw_a_sphere#PostScript

It looks like a real sphere.

![image](https://user-images.githubusercontent.com/3974108/70103628-a3fcec80-1609-11ea-87f8-47ddcd73538a.png)

**Comment by PaulWessel** [comment]
That is nice. But I would like a general ellipsoid with arbitrary orientation.  Yet, sphere is nice too, and probably can be colorized.  We could offer a wireframe version of an ellipsoid though, but not with the projection system we have right now.

**Comment by seisman** [comment]
Close this issue?

**Comment by PaulWessel** [comment]
Yes, the 3-D stuff is a bit premature and not easily implemented given how plot3d works.
