### ISSUE TITLE
Debug message for one-liners still show mixed modern and classic names

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2210]
To reproduce the issue, run
```
gmt basemap -Rg -JH10c -Baf -pdf map -Vd
```

**Comment by joa-quim** [comment]
Not so important, isn't it? Debugging is coder, not a using thing.

**Comment by seisman** [comment]
Yes, not a big issue, but should be fixed.

**Comment by PaulWessel** [comment]
I noticed the other day when tracking @joa-quim's virtual file region issue but forgot.  I will take a look in the debugger one of these days, so leave this issue open.

**Comment by joa-quim** [comment]
Agree that a fix is nice, but it takes time from more important things.
