### ISSUE TITLE
Add share/tools script to download all cache and server data

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2218]
**Description of the desired feature**

As you head to the airport or a ship, you may want to make sure you have all your GMT remote data in your cache.  It would be nice to have a script in the share/tools folder that could do that.  I think we may have something like that buried in the CI, @seisman?

**Comment by seisman** [comment]
Yes, it's here.
https://github.com/GenericMappingTools/gmt/blob/eebf17676d1c3da29f9b207947a95f54abaafbd7/ci/azure-pipelines-linux.yml#L87-L89

**Comment by seisman** [comment]
I'll work on the script if you haven't started.

**Comment by PaulWessel** [comment]
Sorry,, almost ready to commit - thought I'd run it first!

**Comment by seisman** [comment]
OK.
