### ISSUE TITLE
coast -C documentation has link to color docs but -G and -S do not

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/gmt#2225]
**Description of the problem**

This is the example task for the AGU2019 GMT Workshop.

**Full script that generated the error**

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by PaulWessel** [comment]
fixed.
