### ISSUE TITLE
The "Grid file format specifications" misses example on how to write with GDAL 

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2237]
We have an [example ](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#grid-file-format-specifications) on how to read but not on how to write grids via GDAL. However, we do have them [here](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#writing-grids-and-images)

**Comment by jratike80** [comment]
Practical example could be about how to create a lossless, deflate compressed, and tiled GeoTIFF, perhaps optimized to yield better compression if output raster is of floating point type. 

`-Goutput.tif=gd:GTiff+cTILED=YES+cCOMPRESS=DEFLATE+cPREDICTOR=3`

Probably there is also room for a small note: "See available options for each output format from the GDAL driver documentation, for example https://gdal.org/drivers/raster/gtiff.html".

**Comment by joa-quim** [comment]
PR #2414 sumitted.

**Comment by joa-quim** [comment]
and merged.
