### ISSUE TITLE
Links to get GSHHG and DCW in BUILDING.md can be confusing

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2240]
Instead of going to the latest versions they go to the general web page that lists multiple download options, including (forGSHHG) the shapefiles, which is not what we want for the GMT installation.  Better to add links to the actual files to download.

**Comment by seisman** [comment]
We can add links to latest GSHHG and DCW tarballs, but we may forget to update the links when new versions of data are released.

**Comment by abanbj** [comment]
And what about linking to e.g. `gshhg.tar.gz` and `dcw.tar.gz` and creating symlinks on the hosting system instead of hardlinking to specific versions.

**Comment by PaulWessel** [comment]
@seisman, I guess we should consider this at the same time as the other issue I just pinged you.  What do you think is a good solution here? Since we dont offer a gmt.tar.gz symlink I dont think we should do it with the other files either no?. SO perhaps close this issue?

**Comment by seisman** [comment]
We have two repositories https://github.com/GenericMappingTools/gmt-dcw and https://github.com/GenericMappingTools/gmt-gshhg. I think we can create a release, attach the GSHHG and DCW tarballs, and update the README files.

**Comment by seisman** [comment]
For the links on the website, we can also link to the github releases, just like what we do with the GMT 6.0.0 and 5.4.5 links.
