### ISSUE TITLE
Avoid near-duplication in -J explanation

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2267]
The **-J** option explanation has pairs of near-identical syntax cases, where we show one with lower-case code (and _scale_) and one with upper-case code (and _width_).  E.g., for Mercator we list

**-Jm**[_lon0/[lat0_/]]_scale_ or **-JM**[_lon0/[lat0_/]]_width_ (Mercator [**C**])

Given that we start **-J** by explaining the purpose of the lower and upper letter codes and that they mean we give map scale or map width, might we not be able to use the single statement

**-Jm**|**M**[_lon0/[lat0_/]]_scale_|_width_

to avoid the repetition that gets seriously long for some of the azimuthal projections?  Would you prefer

**-Jm**|**M**[_lon0/[lat0_/]]_scaleorwidth_

instead? I bring this up since I just fixed a copy/paste error for **-JO** due to this duplication.

**Comment by PaulWessel** [comment]
Anyone has feelings about this?  Is the **x**|**X** and _scale_|_width_ too confusing despite explaining why there are upper and lower cases?  What say you @leouieda, @seisman and @joa-quim?

**Comment by seisman** [comment]
I prefer **-Jm**|**M**[*lon0*/[*lat0*/]]*scaleorwidth*.

**Comment by PaulWessel** [comment]
Full speed ahead!  OK, what say you @joa-quim? I know you like short things in general.

**Comment by joa-quim** [comment]
*scaleorwidth* no. It's incomprehensible to anyone who doesn't already knows how it works.
-Jm|M[lon0/[lat0/]]scale|width should be OK but I fear that it will still confuse first readers.

**Comment by PaulWessel** [comment]
If we have a clear statement on top that says (we do already I think, but even clearer) that

1. Projections can be specified using a map _scale_ or a map _dimension_ (height or width)
2. A lower-case projection code means we must supply a _scale_.
3. An upper-case projection code means we must supply a _dimension_.

If life is confusing after that then I think we just tell Lester to read it again.

**Comment by joa-quim** [comment]
That is useful but still *scaleorwidth* is just too confusing, three words in one. When one wants to consult the man of a particular projection it's not reasonable to expect that the user reads the entire man page.

**Comment by PaulWessel** [comment]
Is this a language issue? To me, _scale-or-width_ or _scaleorwidth_ says to me that I need to provide either scale or width.  When do I provide one or the other? That was given above.  Might we have a link that says (why?)... and user can click and be explained why and how?
Since our target users are scientists (no?) they should be literate and know the difference between a map scale and a map dimension, I think?

**Comment by joa-quim** [comment]
Since I already know how it works I confess incapable of judging that. Just have the feeling that it will be confuse to many new users.

**Comment by seisman** [comment]
New users who don't read the manpage carefully even don't know the difference between lower-case and upper-case.

**Comment by PaulWessel** [comment]
So there is always a trade-off here.  It is not 100% on us to write extensive documentation with lots of repetitions everywhere to overcome the inability of users to bother to read the documentation.  I think our first goal is to have accurate documentation where every aspect of GMT modules and options are correctly presented.  We constantly work on that.  The next is to make it easier for users to find what they need.  That is also ongoing with rearrangement of docs, more graphics examples, more examples in general, etc.  So we can take no action of this issue above and let the near-identical text be there as is.

**Comment by joa-quim** [comment]
Don't want to be a censor here but since we don't say **-J***morM* at least we should say *scale|width*

**Comment by PaulWessel** [comment]
We should use the vertical bar which means "or".

**Comment by meghanrjones** [comment]
I will implement the agreed upon format (i.e., **-Jm**|**M**[_lon0/[lat0_/]]_scale_|_width_)
