### ISSUE TITLE
PATH Too Long Error

### ISSUE THREAD

**Issue by cemarshall** [GenericMappingTools/gmt#227]
While installing gmt-5.4.4-win64.exe, I am getting the error message in the middle of the install of the following:

Warning! PATH too long installer unable to modify PATH!

It doesn't happen with every install, but I am trying to find out what PATH is being added to manually do it myself if needed.

Windows 10 x64
GMT 5.4.4 x64

**Comment by joa-quim** [comment]
Unfortunately this is an annoying cmake issue that I don't know if we can do anything bout it, except, like you said, setting the path manually. Which PATH to use is up to you. Either ``user`` or ``system`` will do.

**Comment by seisman** [comment]
As far as I know, some users encounter the same issue and don't know what to do. If we cannot fix this issue, at least we can change the warning message so that users know they can modify the PATH manually to make GMT working.

**Comment by PaulWessel** [comment]
Maybe an old complaint: https://cmake.org/Bug/view.php?id=11931
https://cmake.org/pipermail/cmake/2011-March/043494.html

with no clear solution.

**Comment by joa-quim** [comment]
Yes, I remember to have searched a bit for this but never found one solution.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/blob/d39dcbc35fd739820a8248cad3cb89711b205965/cmake/modules/NSIS.template.in#L223-L227

Does these lines control the warning message?

**Comment by joa-quim** [comment]
Great. It was Florian who took care of the config scripts and, given the web complains, I always assumed that it all happened inside NSYS. So, yes, we should provide a better warning message.

**Comment by joa-quim** [comment]
So far we have done what is at our reach (change the error message to warn users that they must add to path manually) so, closing this issue.
