### ISSUE TITLE
Download links for GSHHG and DCW: ftp -> https

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#2275]
The download links on https://www.generic-mapping-tools.org/download/ are `ftp`. On the old website, I think(?) they were http(s) (http://gmt.soest.hawaii.edu/projects/gmt/wiki/Download). Any change that you would change the links on the new page to http?

* `ftp` is frequently being blocked
* Chrome and Firefox aim to remove `ftp` support (if not done so already)

**Comment by PaulWessel** [comment]
Yes, they could for instance go to http://www.soest.hawaii.edu/gmt/pub/gmt/dcw-gmt-1.1.4.tar.gz instead.

**Comment by PaulWessel** [comment]
Hi @seisman, is this a benign change - i.e., listing the http link instead (or in addition)?

**Comment by seisman** [comment]
How are the FTP file and the HTTP file related? Are they the same file but served with different protocols?

**Comment by PaulWessel** [comment]
Yes, the same file with different protocols.
