### ISSUE TITLE
Eventually remove -: in favor of -i

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2276]
When we go to long-name options the --read-columns will be the way to do -:, but -: will remain as backwards compatibility but no longer documented.

**Comment by seisman** [comment]
I'm not sure if I explained myself clearly during the GMT meeting. 

If I have a table with 4 columns, i.e. *Y, X, Z1, Z2*, I can use `-:` to swap the first two columns, but with `-i`, I have to use `-i1,0,2-3`. 

The -i  option is even more complicated if the input data contains some texts. Below is an example:
```
gmt begin map
gmt text -R0/360/-90/0 -JX10c/10c -Baf -: << EOF
-45 120 ABC DEF
EOF
gmt end show
```

**Comment by PaulWessel** [comment]
Good point, but your example works fine for me, plotting the text centered on lon=120 and lat=-45. What do you see?

**Comment by seisman** [comment]
The example works because I use `-:`, and I have no idea how `-i` can work in the similar way.

**Comment by PaulWessel** [comment]
I see, good point.  The -i option in pstext is a different implementation that the one used for data columns so I will have to think about how that might work in another way.

**Comment by PaulWessel** [comment]
Given #2286 I can imagine we can replace **-**:i with a shorthands **-i**: and **--read-columns**=_latlon_ that stand for **-i**1,0,2:,t and **-**:o can become **-o**: and **--write-columns**=_latlon_ that stand for **-o**1,0,2:,t.  Or something similar.  We could just internally call the parse_colon function to accomplish this.  Or, we could avoid the colon-syntax entirely by having **-if** and **-of** for flip lon/lat.

**Comment by remkos** [comment]
Note that the flipping of the columns is not only for latlon but also yx. This means that
`--read-columns=yx` and `--write-columns=yx` should also be supported.

I would not like to introduce yet a third way `f` by supporting `-if` and `-of`. I think in that case it would just be `-iyx` and `-oyx`.

**Alternatively**, a way to be consistent would be:
* `--read-columns=flip` or `-if`
* `--write-columns=flip` or `-of`

**Comment by PaulWessel** [comment]
I agree _flip_ is better than having two sets of _latlon_ or _yx_ argumenst.
