### ISSUE TITLE
-JM standard parallel ignored

### ISSUE THREAD

**Issue by viktor76525** [GenericMappingTools/gmt#2287]
Setting projected area using Mercator
-Jm[lon0/[lat0/]]scale or -JM[lon0/[lat0/]]width (Mercator [C])
`psbasemap -JM173/-42/7i -R-200/200/-200/200+uk -Ba1 > test.ps && psconvert -A test.ps`
![test](https://user-images.githubusercontent.com/7464462/70872651-92a2df80-200e-11ea-932c-936677c3f1b2.jpg)

In the attached output the centre is at 0 latitude, I was expecting it to be at lat0 (-42).

**System information**
* Operating system: Linux 64 bit
* GMT version (`gmt --version`): 6.1.0_e60fa2f_2019.12.14

**Comment by joa-quim** [comment]
I see your point but notice that *lat0* is the latitude where the scale in preserved, not the mid-height of the map.

**Comment by PaulWessel** [comment]
Seems like this should be possible though. Maybe when -R is given in local coordinates relative to origin we should make that correction.
