### ISSUE TITLE
Ability to limit input rows and even row time-range

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2288]
**Description of the desired feature**

While _events_ can handle the appearance and disappearance of symbols in animations, I need to implement a solution for animated _lines_.  For instance, one may wish to draw lines that appear and disappear, and even display only a part of the line segment in each frame. Like other events, such temporal tracks have time in the 3rd column (e.g., ship tracks, satellite tracks).   At time _t_ in a frame, maybe just the line segment from its beginning to _t_ should be visible, while other cases may wish to just highlight the last 6 hours (or 200 km), as time moves forward.  Since _t_ may fall between data points, we will need to interpolate the exact locations.  Now, _sample1d_ **-T** can do that, but it is overkill since we actually do not want to resample the whole segment. We just add a new start and stop point with original data records in-between as needed.  The ability to only select a _section_ of a track, being based on row numbers or row _time_, can be useful across many modules, such as _filter1d_, _gmt2kml_, _gmtconnect_, _gmtmath_, _gmtselect_, _gmtspatial_, _mapproject_, _plot_, _plot3d_, _sample1d_, _wiggle_, and _mgd77list_ to name a few.  Thus, I propose this ability should be encoded as a new common option:

**-q**[_first_][/_last_][**+c**_col_] or **--read-rows**=[_first_][/_last_][**+column**=_col_]

This option would complement the _column_ selectors **-i** and **-o** (long-forms **--read-columns** and -**-write-columns**) as it selects the range of input _rows_ instead [Default is all].  If not specified, _first_ = 0 and _last_ = the last record.  If **+c** is used then we interpret _first_ and _last_ to be monotonically increasing coordinates in column _col_ (i.e., a time series) and we instead ensure that the first input record (if required) is interpolated between the nearest two records so that the coordinate equals _first_; the same will be done for _last_.  All original records with coordinates _first_ < _coord_ < _last_ are read as they are. 

I note that _gmtconvert_ has some of this capability implemented as **-Z**[_first_][/_last_] where we only operate on row numbers and not row time. Of course, from MATLAB, Julia and Python you have subscripting available to select part of a matrix via both rows and columns, but you dont have the interpolating selection via **+c**.

Possible additional modifiers: We may wish to reset the current record count per segment (**+s**) or per file (**+f**) [per dataset], for instance to only use the first 10 row per segment, per file, or per the entire data set.  For **+c** there is no need since time is the same for all.

Finally, for symmetry I can imagine some of you may want **--write-rows** as well.  I think that is reasonable too.  There are no more lower-case letters to use, unless you do **-qi** and **-qo**, but we could simply just have the long-form as that is what UNIX tools (like grep) seem to do when they run out of single letters.

Comments are appreciated from the entire @GenericMappingTools/core.

**Comment by PaulWessel** [comment]
Given the small Xmas window when I can get some coding in, it would be good to get your first impressions on the plan above, @GenericMappingTools/core, so that I could get started.

**Comment by seisman** [comment]
Let's first see if my understanding is correct.

So if I have a table below, 
```
1 1 2019-01-01T00:00:00
2 2 2019-01-01T00:01:00
3 3 2019-01-01T00:02:00
4 4 2019-01-01T00:03:00
5 5 2019-01-01T00:04:00
```

`gmt plot -Sc0.2c -q0/2` plots the first three points (records 0-2) as circles and `gmt plot -q0/2` plots a line connecting the first three points.

If **+c** is appended, e.g. `gmt plot -Sc0.2c -q2019-01-01T00:01:30/2019-01-01T00:03:30+c2`, only two points at (3,3) and (4,4) are plotted.

**Comment by PaulWessel** [comment]
Yes, your **-q**0/2 interpretation is correct.  This is how gmt select **-Z**0/2 would work as well.

Your **+c** interpretation is not correct since we will interpolate at 1:30 as well as at 4.30, and what gmt plot will see is actually these 5 records (here I assumed linear but that is under the control of **GMT_INTERPOLANT**).  Remember, using **+c** implies we are looking at a multi-column time series with time in column _col_:

```
2.5 2.5 2019-01-01T00:01:30
3 3 2019-01-01T00:02:00
4 4 2019-01-01T00:03:00
4.5 4.5 2019-01-01T00:04:30
```

So we would call _gmt_intpol_ twice times _n_columns_ - 1, each time with 2-6 nearest rows (depending on interplant selected).  The "middle section" far form the ends is untouched.

**Comment by seisman** [comment]
**+c** for interpolation makes sense for "continuous" line segments, but not for "discrete" symbols. I expect `gmt plot -Sc0.2c -q2019-01-01T00:01:30/2019-01-01T00:03:30+c2` to plot only the two circles in the time window, not the two "interpolated" circles.

**Comment by PaulWessel** [comment]
That is a valid point, so perhaps **+d** for discrete, i.e., just your two records.

**Comment by seisman** [comment]
Then the **-q** looks good to me. As for output, I think it's better to have **-qi** and **-qo**, instead of having mixed single-letter option and long options (e.g. **-q --write-columns=**)

**Comment by PaulWessel** [comment]
Perhaps

**-q**[**i**|**o**][**+c**|**d**_col_]
**--read_rows**[**+continuous**|**discrete**=_col_] and **--write_rows**[**+continuous**|**discrete**=_col_]

but if no **i** or **o** we default to **i** (since this will be by far the most common case I think?).

**Comment by seisman** [comment]
Wait, the proposed **-q** option sounds very similar to the **gmtselect -Z** option, although **gmtselect -Z** only works for selection of z-value. Can we just add an **-Q** option to **gmtselect**, so we can do the same thing with `gmt select input.dat -Q2019-01-01T00:01:30/2019-01-01T00:03:30+c2 | gmt plot -Sc0.2c`?

**Comment by PaulWessel** [comment]
That is not a very flexible solution from within events.c.  It is like saying **-i** should only be an option for gmt select and then we have to pipe the output into plot to get the right columns.
Yes, the proposed **-q** is identical to gmtselect **-Z** and we would remove **-Z** from the documentation and make that backwards compatible for that module.  However, most/all modules that read tables would gain **-q**.

**Comment by joa-quim** [comment]
I am confused. Why would ``-q2019-01-01T00:01:30/2019-01-01T00:03:30+c2`` select
```
2.5 2.5 2019-01-01T00:01:30
3 3 2019-01-01T00:02:00
4 4 2019-01-01T00:03:00
4.5 4.5 2019-01-01T00:04:30
```
I guess ``2019-01-01T00:04:30`` is a mistake and should be ``2019-01-01T00:03:30`` but the ``04:30`` is mentioned twice, so not so sure. But this is hardly described as an interpolation since only the two end records are subject to interpolation. And it can only be a linear interp since otherwise it would be required that ALL columns are equi-spaced. Where would one need this other then ``events``?

Also the *discrete vs continuous* naming doesn't seem correct to me. What was called *discrete* is actually a record selector for it picks all records ``>= first && <= last``. This seems a useful thing but let's don't baptize it any further.

**Comment by PaulWessel** [comment]
Sorry, yes of course it should be 3:30 not 4:30. Depending on GMT_INTERPOLANT it may involve up to 6 records (3 on each side for cubic splines if there are 3 available).
Not sure I understand your comment about equispaced etc.  If file is a time series and it has many columns they are all f(t). Equidistant has nothing to do with it, we interpolate where it is needed.
And it is not really events who needs it but plot, otherwise I would need to introduce lots of temporary files or awkward piping in system calls where the PPID will change, etc.

**Comment by PaulWessel** [comment]
There are clearly two separate effects here.  The one that I think is super easy to implement is **-q**[**i**|**o**][_first_][/_last_] which would simply skip any record not in the desired record number range.  It is very similar to what we do when we encounter a header record and we just keep reading until we get to a data record.  Here we would keep reading until we are in the valid range.  Perhaps I should implement that first for testing.
Once that is working we can consider adding the **+c**_col_ modifier for time-series range selection.  I think @seisman's point of not always interpolating is valid, and @joa-quim does not like the word discrete here.  However, we need two different modifiers for this.  Either there are two flavors that both set _col_, or there is another modifier **+i** that turns on interpolation.  Perhaps that is more appropriate?  I like that better than two ways to specify a column.  So complete syntax would be

**-q**[**i**|**o**][_first_][/_last_][**+c**_col_][**+i**]
**--read-rows**=[_first_][/_last_][**+column**=_col_][**+interpolate**]
**--write-rows**=[_first_][/_last_][**+column**=_col_][**+interpolate**]

**Comment by PaulWessel** [comment]
Hm, I am looking at the corresponding options **-i** and **-o** and they use this syntax to indicate which _columns_ to select:

> Give individual columns (or column ranges in the format start[:inc]:stop, where inc defaults to 1 if not specified) separated by commas...

Perhaps we should stick to that format and for specifying which _rows_ to use, e.g.,

-qi5:15,45:

to only read records 5-15 and 45 until the end of the table?  This format is much more flexible than the limiting _first_/_last_ proposed above.

**Comment by PaulWessel** [comment]
And my final post on this before Christmas takes over: Perhaps I am pushing the interpolation scheme too far by making it a common option. I think the **-q** based on record numbers are super useful in lots of modules, but the ability to interpolate the exact endings was clearly driven by my need to plot lines for that particular interval in an animation scheme.  So I suggest the following compromise proposal:

1. Implement **-q**[**i**|**o**]_rows_ as discussed above, with _rows_ a comma-separated list of desired rows, including row ranges - i.e, the familiar syntax that is used in **-i** and **-o**.
2. Implement a line-truncating/interpolating option in modules that plot lines.  This would seem to be limited to plot, plot3d, and wiggle.  These could get a new **-M**_start_/_end_**+c**_col_ option that handles this particular truncation.

The benefit of this proposal is that the **-q** common option becomes very simple and fast to both implement and execute as we already have almost similar situations related to skipping header records on input and skipping nan-records on output.  It also limits the potentially more challenging implementation (of **-M**) to those few modules that may need it (infrequently) and avoid being buried deep in the core input functions and possibly slow that part down.

If @GenericMappingTools/core  agree with this then I will make a branch to implement **-q** during the Christmas break.

**Comment by joa-quim** [comment]
Not that I disagree but would prefer **-q[i|o][first][/last][+ccol][+i]**
For one thing, it would be only one more option instead of two. Right, in many cases the **[+i]** would not make sense, but the fact that the **[+ccol]** alone would allow selecting ``>= first &&<= last`` is a powerful feature that is not allowed in ``-q, -M`` proposal.

**Comment by PaulWessel** [comment]
I don't think we should have a common option that has modifiers that are not available in some modules, such as **+i**, unless we have already broke that rule before (?).  However, I agree that the coordinate selection limit _could_ remain with **-q**.  The implementation of that selection will be a separate code section since it requires us to first parse the record _before_ deciding if it should be used [unlike record number which is known just by counting].

This retains the specialized interpolation scheme as a separate option in the modules that need it, and it could simply be **-M** in concert with **-q**.  The fall-back is if we have already broken the rule above then we might as well add the **+i** to only those few modules where it makes sense.

**Comment by PaulWessel** [comment]
Also to consider: As implemented in #2341, _rows_ is either individual rows, ranges of rows (first:last) or even strides (first:inc:last), and any number of ranges can be comma-separated (e.g, -qi1:10,40-99), and you can even use a single negative range (e.g., -qi~100-200) to select all but some particular rows).  For time coordinates on the command line we expect ISO 8601 so then first and last must be yyyy-mm-ddThh:mm:ss.xxxx format.  Given that format, this dictates the use of first/last for time-limits (since hyphen and colons are part of the data), so that breaks the general **-q** (and _-i_, **-o**) syntax for ranges.

**Comment by joa-quim** [comment]
I don't remember any instance where we have a global option where some of its flags (sub-options) are not apply-able to some modules.

**Comment by PaulWessel** [comment]
So probably best not to introduce such a thing so that leaves **+i** off the **-**q option.  As I said, I think it is very rare that a user will want to do that interpolation and they could always do something similar via sample1d.  Better to focus on the row or time limits and save any interpolation to the few modules have may actually need it.
