### ISSUE TITLE
Themes for default settings

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2290]
**Description of the desired feature**

We discussed this in the past but took no actions.  I think lumping a group of GMT defaults together and give them a name (a theme) can be helpful to users.  For instance, the current defaults would be called "classic" while we could add a set of new ones with other names.  For instance, our map frame defaults is due for an upgrade, such as adding "auto" to the MAP_FRAME_WIDTH settings so that it scales with the map size (when users plot a 5x5 cn figure for Nature it looks bad for GMT that the frame is still 5p regardless of the small map.  Other things may be to have a them for inside ticks and annotations, maybe change up some annotation fonts, and maybe have a theme suitable for white on black for presentations.

Implementation would simply be via a new parameter called **GMT_THEME** and when that setting is given via gmt set we (a) reset to system defaults and (b) apply the collection of settings grouped under that theme.

It is unfortunate that we did not create the "modern" theme but I still think we should and make it default in modern mode.

**Comment by seisman** [comment]
Good idea. GMT should provide some built-in themes and also allow users define their own themes.

**Comment by PaulWessel** [comment]
Realizing that a _movie_ theme would be good since some defaults are not very good for movies.  For instance, see #3341, and I find the defaults for **-X -Y** usually need to be overridden and **COLOR_HSV_MIN_V** I usually need to set to 0.  So these themes would be good:

1. _classic_: What we default to now, basically.
2. _modern_: Revamp some settings as discussed above
3. _movie_: Pick suitable defaults for a (relatively) low-resolution raster (most of our defaults work well for PS and PDF).
4. _darkmode_: Why not: white (or bright) text colors and lines, dark/black paper, etc.

Since a theme is basically a list of gmt.conf settings it should be easy to implement.  We provide a few themes and users can add their own in ~/.gmt.  I will work on this as I think introducing the modern theme is overdue.

**Comment by meghanrjones** [comment]
Implemented by #3344
