### ISSUE TITLE
Leftover transition from subversion to git related to CPT files

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2309]
The reading of CPT has a check on some of the comments and one is

`			if (strstr (line, "$Id:")) master = true;
`

After moving to git we no longer has $Id: markers in the master CPTs.  I will need to examine how this bool value is used and find another way to set it.

**Comment by PaulWessel** [comment]
The use of the bool master is this:
`/* Skip first 2 lines of GMT master CPTs */
`
Thus, no bug was introduced by removing the $Id: string but now the first two lines are included in the CPT header strings.  This seems inconsistent anyway since there are sometimes more than 2 leading records.  I think we might as well remove the whole test and let all master CPT comments be stored in the header strings.

**Comment by seisman** [comment]
Removing the if statement looks good to me. Anyway, all lines starts with "#" are ignored with only a few exceptions (e.g. COLOR_MODEL, CYCLIC).
