### ISSUE TITLE
update igrf13 coefficients

### ISSUE THREAD

**Issue by MarceloBanik** [GenericMappingTools/gmt#2326]
**Description of the desired feature**
Please, consider update igrf13 coefficients as published in 
https://www.ngdc.noaa.gov/IAGA/vmod/coeffs/igrf13coeffs.txt

I just tried it, and appears that it didn't break any mgd77 test (see attached zip file).
Beside updating 2015, 2020 and sv coefficients, I changed a little the spacing of older models.
I hope it could help.

**Are you willing to help implement and maintain this feature?** Yes/No
yes

[mgd77.zip](https://github.com/GenericMappingTools/gmt/files/3992645/mgd77.zip)

**Comment by joa-quim** [comment]
Marcelo, can you please make a PR with this?

**Comment by MarceloBanik** [comment]
Joaquim,

Could you check if I did it properly?

Marcelo

**Comment by joa-quim** [comment]
Marcelo, perfect. Thanks, you saved me of relearning what has to be done (so far) every 5 years and the annoyance of having to count how many new coefficients are added.
Merged in master.
