### ISSUE TITLE
Rethinking default verbosity and the hierarchical order of verbosities

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2346]
**Description of the desired feature**

Here are the various verbosity levels offered by GMT:
```
-V Change the verbosity level (currently v).
   Choose among 6 levels; each level adds more messages:
     q - Quiet, not even fatal error messages.
     n - Normal verbosity: only error messages.
     c - Also produce compatibility warnings [Default when no -V is used].
     v - Verbose progress messages [Default when -V is used].
     l - Long verbose progress messages.
     d - Debugging messages.
```
Currently, it says default verbosity level is **-Vc** which only prints error messages and compatibility warnings.  I think most users find it a bit odd that if their selection of options produces a case _we_ deem worthy of a warning message (e.g., we must do great circle interpolation despite users wanting ellipsoidal) they do not actually see that message unless they specify **-V**.  Thus, the warning _we think_ they should see is not visible unless they anticipate the problem in the first place.  I think this needs to change.  The current decision derives from a past situation when we had a mix of warnings and informational messages at the same level.  Now, users can set their own verbosity default level via gmt set **GMT_VERBOSE**, but out of the gate that is set to compat.  Finally, the description of **-Vv** is wrong since it does not report progress messages, only warnings.  As you know, all messages a prepended with the scary upper case words ERROR, WARNING, INFORMATION, COMPAT, and DEBUG and we do not want to say `WARNING: Reading file test.txt`, for instance.  Harmless but informative messages need to be under **-Vl**.  The users must _choose_ to get that extra information.

Since we correctly parse any deprecated option syntax it is also annoying to people that we constantly badger them with these "get with the program" messages.  I think users should be able to select such badgering if they are motivated to change their scripts, but not if they don't want to.

**Proposal:**

My proposal has two parts:

1. Slightly adjust the order of the verbosity (and use some new mnemonic letters, yet keep the old letters for backwards compatibility).
2. Let the default verbosity level be **-Vw** (error messages _and_ warnings).

We would then have this situation:
```
-V Change the verbosity level (currently w).
   Choose among 6 levels; each level adds more messages:
     q - Quiet, not even fatal error messages.
     e - Error messages only.  (note: We will also accept -Vn)
     w - Warning and Error messages [Default] (note: we also accept -Vv).
     i - Informational messages (note: Also accept -Vl).
     c - Compatibility warnings are added.
     d - Debugging messages [meant for developers only].
```
The biggest changes here are

1. Change the default verbosity to include warnings.
2. Relegate the compatibility warnings to the level just before debugging.
3. Refresh the verbosity codes to be mnemonic.

I hope the entire @GenericMappingTools/core can comment on this proposal.  If accepted it will be implemented in master.

**Comment by PaulWessel** [comment]
Time for @GenericMappingTools/core to chime in or I will take matters into my own BDFL hands.

**Comment by joa-quim** [comment]
Right, but we also have the forgotten **-Vt** that only prints timings at certain potentially long time runs chunks. Since it's a not known option the simplest would be to integrate it in **-Vw**, or otherwise keep it and inset between **-Ve** and **-Vw**

**Comment by PaulWessel** [comment]
My first thought on **-Vt** is that it provides more information, and certainly is not a warning.  So therefore it belongs between w and i.

**Comment by joa-quim** [comment]
Well, where it belongs is a implementation detail. The other thing is what it will do. By putting it between *w* and *i*, will it also print warnings?

**Comment by PaulWessel** [comment]
I think so; each level builds on the previous one.

**Comment by joa-quim** [comment]
That's why I thought in having it before *w* so it would be timings only, but after is almost the same.

**Comment by PaulWessel** [comment]
And if you are not triggering any warnings it would be exactly the same.

**Comment by PaulWessel** [comment]
Any comments on this, @seisman and @remkos?

**Comment by remkos** [comment]
I like your proposal above. It makes total sense. In my mind -Ve also covered warnings, but it might be good to have that separated. And indeed, it is also time to put -Vc after -Vl (now -Vi).

I have no preference regarding the -Vt discussion, but in my mind this sounds to me like either a warning (i.e. be part of -Vw) or a higher level of verbosity, i.e. be part of -Vi). No need for a special level.

**Comment by seisman** [comment]
I'm a little confused. What will I see if I don't use the **-V** option, both errors and warnings?

**Comment by PaulWessel** [comment]
Correct. For instance, **surface** may report

WARNING: Your grid dimensions are mutually prime.  Convergence is very unlikely.

It is not a fatal error but I think we want to tell users that using **-R**0/127/0/113 **-I**1 is not a good selection.  Right now they won't know and wonder why the result is so bad. One should not have to add **-V** to find out if what you did is problematic.

**Comment by seisman** [comment]
I agree that we should report errors and warnings without the **-V** option, but I believe users expect to see more information when they add the **-V** option. But in your new proposal, **-V** or **-Vw** doesn't give more information.

**Comment by PaulWessel** [comment]
You are right.  Perhaps -V needs to mean -Vi then.

**Comment by seisman** [comment]
Yes, that makes more sense to me.

We also need to change some warnings to informational messages. Like the warning below:
```
gmt basemap -R0/30/-20/20 -JM10c -Baf -pdf map -V
basemap [WARNING]: Central meridian not given, default to 15
```

**Comment by PaulWessel** [comment]
Yes, we need to review what is labeled as VERBOSE vs LONG_VERBOSE.

**Comment by PaulWessel** [comment]
I will make a branch addressing the new scheme.

**Comment by PaulWessel** [comment]
I ran all 900 tests with GMT_VERBOSE = information.  I got 1131 unique WARNING messages and 34999 unique INFORMATION messages.  A very brief scan suggest that many WARNING messages might be better as INFORMATION and many INFORMATION messages should be pushed to DEBUG.  I post the listings here so you can see.   I am afraid we will need to do this manually...

[information.txt](https://github.com/GenericMappingTools/gmt/files/4136815/information.txt)
[warning.txt](https://github.com/GenericMappingTools/gmt/files/4136816/warning.txt)

**Comment by PaulWessel** [comment]
After fixing many scripts with deprecated syntax and resetting the verbosity level of many messages to match reality (too many were set to warning but really were information or even debug), we have some remaining warnings to investigate when running all tests:

1. `-JX8c/8 not a valid number and may not be decoded properly`.  This is coming from psbasemap/test-JXd.sh when that item is fed as 3rd column textstring.  Not yet able to reproduce in a simple case.  Presumably the GMT i/o is trying to convert to z.
2. `2i/0.2i/0.075 not a valid number and may not be decoded properly`.  Coming from pslegend/lines.sh parsing of symbol size of obsolete vector parameters.
3. `Changing paper size to US Letter, but we cannot know if this is adequate for your plot; use PS_MEDIA`.  Several tests and examples create a landscape plot (e.g., GMT_-B_slanted.sh), and we get these messages when we have to guess.  It means PS_MEDIA was not set first which I thought we do in the tests.
4. `TIME_UNIT is invalid.  Default assumed. Choose one only from y o d h m s`. In a few places, and reproducible via `gmt math -T2011-02-01T/2011-02-28T/1 --TIME_UNIT=d TROW 200 ADD = /tmp/shit`.  Clearly the unit is valid...
5. `Figure # 1 was registered but no matching PostScript-|+ file found - skipping`.  Several of the anim*.sh scripts report this, like anim03.sh.
6. `Module was expected to change clip level by 0, but clip level changed by 1`.  gmtlogo/logos.sh gives lots of those.
7. `Representation of font type not recognized. Using default`.  Example 31 with Cyrillic complains.
8. `Your data array row 0 contains NaNs - no resampling taken place! `Coming from apivec.sh test.

The other warnings seems like OK warnings to issue, such as

```
Fill/clip continent option (-G) may not work for this projection.
3 unusable points were supplied; these will be ignored.
Data constraint 53 is identical to 48 and will be skipped.
Near- or actual antipodal points encountered. Precision may be reduced slightly.
```
etc.

**Comment by joa-quim** [comment]
I have also these from my Julia tests. Some are not prefixed and plot lots of lines

```
gmtsimplify [WARNING]: gmtsimplify only implemented using Flat-Earth calculations.

Window 0 from 0 to 256
X var: 0  X pow: 0  ratio: -nan(ind)  Y var: 0  Y pow: 1  ratio: 0
Window 1 from 128 to 384

upward continuation...
inverse FFT...
cross-spectrum...
grdfilter [WARNING]: Your output grid spacing is such that filter-weights must
grdfilter [WARNING]: be recomputed for every output node, so expect this run to be slow. Calculations
grdfilter [WARNING]: can be speeded up significantly if output grid spacing is chosen to be a multiple
grdfilter [WARNING]: of the input grid spacing.  If the odd output grid is necessary, consider using
grdfilter [WARNING]: a 'fast' grid for filtering and then resample onto your desired grid with grdsample.
        grdmask  -R0/100/0/100 -I2 -N100/0/0
Coefficient fit to Mean: 25

grdgradient [WARNING]: 37 (of 37) inconsistent grid values at West and East boundaries for repeated nodes.
PSL: Warning: no deflate compression done.
grdimage [WARNING]: The image memory layout (TRPa) is of a wrong type. It should be BRPa.
PSL: Warning: no deflate compression done.
mapproject [WARNING]: No UTM zone given; zone 60T selected


psbasemap [ERROR]: 1 external clip operations were not terminated!
psrose [WARNING]: 12c/8 not a valid number and may not be decoded properly.
PSL: Warning: no deflate compression done.

basemap [WARNING]: Must specify a paper size when requesting a PostScript file
basemap [WARNING]: Changing paper size to A4, but we cannot know if this is adequate for your plot.
surface [WARNING]: Your upper value is < than max data value.
```

**Comment by PaulWessel** [comment]
Thanks.  I am fixing those non-prefix messages in #2606.  The PSL messages have been dealt with already so you need update.  let me know if your Julia tests reports other things that is either questionable (a bug?) or is more of an informational message.  For instance, the grdfilter warnings above is not "warning" taht something might be wrong or approximate, it is about speed.  Is that INFORMATION?

**Comment by joa-quim** [comment]
Ok, rebuilt and re-rerun. Still getting this that looks like an INFO
```
grdgradient [WARNING]: 37 (of 37) inconsistent grid values at West and East boundaries for repeated nodes.
```
And yes, I think the grdfilter warning should be an INFO.

Note that many of many Julia tests are meant to test if the right GMT syntax is generated but the code is not actually run (but many others are).

**Comment by PaulWessel** [comment]
The inconsistent grid values messages and grdfilter information are now INFORMATION.

**Comment by seisman** [comment]
Closing this?

**Comment by PaulWessel** [comment]
Yes.
