### ISSUE TITLE
psimage using 1-bit images does not use -G with +b and +f

### ISSUE THREAD

**Issue by pagecp** [GenericMappingTools/gmt#2381]
I am using psimage since a long time with GMT to put Sun Raster images on a larger image. Latest version I used was 5.1.2.

The .ras format I was using with GMT 5.1.2 is not supported by GDAL, in 6.0.0 so I converted the images to .bmp (1-bit as reported by ImageMagick) and I also tried .tif with the same results:
- The -Gcolor+f is not used
- Same for -G+b to get transparent background: it does not do anything
- Using -Gwhite+t does make the background pixels (white) transparent, but I cannot color the foreground pixels as I need.

psimage bruine_forte.tif -G+b -G255/51/2+f -Dx39p/438p+r72
and
psimage bruine_forte.bmp -G+b -G255/51/2+f -Dx39p/438p+r72

do not work as intended.

If I run identify on the new bruine_forte.tif image and the original bruine_forte.ras image:

Image: bruine_forte.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 18x18+0+0
  Units: PixelsPerInch
  Type: Bilevel
  Base type: Bilevel
  Endianess: LSB
  Colorspace: Gray
  Depth: 1-bit
  Channel depth:
    gray: 1-bit
  Channel statistics:
    Pixels: 324
    Gray:
      min: 0 (0)
      max: 1 (1)
      mean: 0.700617 (0.700617)
      standard deviation: 0.457988 (0.457988)
      kurtosis: -1.23248
      skewness: -0.876082
      entropy: 0.880535
  Colors: 2
  Histogram:
        97: (  0,  0,  0) #000000 gray(0)
       227: (255,255,255) #FFFFFF gray(255)
  Rendering intent: Undefined
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 18x18+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: None
  Orientation: TopLeft
  Properties:
    date:create: 2020-01-02T15:25:17+00:00
    date:modify: 2020-01-02T15:25:17+00:00
    signature: 9ae0d931e26aafaa0501df98a44809f66dc5bc6c4197021c2e44bd24acbdde01
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: min-is-black
    tiff:rows-per-strip: 18
  Artifacts:
    filename: bruine_forte.tif
    verbose: true
  Tainted: False
  Filesize: 312B
  Number pixels: 324
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

Image: bruine_forte.ras
  Format: SUN (SUN Rasterfile)
  Class: PseudoClass
  Geometry: 18x18+0+0
  Units: Undefined
  Type: Bilevel
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 1-bit
  Channel depth:
    gray: 1-bit
  Channel statistics:
    Pixels: 324
    Gray:
      min: 0 (0)
      max: 1 (1)
      mean: 0.700617 (0.700617)
      standard deviation: 0.457988 (0.457988)
      kurtosis: -1.23248
      skewness: -0.876082
      entropy: 0.880535
  Colors: 2
  Histogram:
        97: (  0,  0,  0) #000000 gray(0)
       227: (255,255,255) #FFFFFF gray(255)
  Colormap entries: 2
  Colormap:
         0: (  0,  0,  0) #000000 gray(0)
         1: (255,255,255) #FFFFFF gray(255)
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 18x18+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Undefined
  Orientation: Undefined
  Properties:
    date:create: 2019-11-19T13:27:33+00:00
    date:modify: 2006-04-23T20:19:12+00:00
    signature: 9ae0d931e26aafaa0501df98a44809f66dc5bc6c4197021c2e44bd24acbdde01
  Artifacts:
    filename: bruine_forte.ras
    verbose: true
  Tainted: False
  Filesize: 104B
  Number pixels: 324
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

**Actual outcome**

The foreground pixels are in black and the background in white.

**Expected outcome**

The foreground pixels in color 255/51/2 and the background pixels transparent.

**System information**

* Operating system: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-70-generic x86_64)
* GMT version (`gmt --version`): 6.0.0

**Comment by joa-quim** [comment]
Fixes were done after 6.0. See #2186 #2188 and example
https://github.com/GenericMappingTools/gmt/blob/master/test/psimage/bitimage.ps

**Comment by pagecp** [comment]
Thanks! Then to which version should I update my 6.0.0 stable release code?

**Comment by joa-quim** [comment]
There will be a 6.1.0 within a month or so. Meanwhile, the only option is to build from source (master).

**Comment by pagecp** [comment]
The master is in good shape to be used? If so I will pull it and update my copy.

**Comment by joa-quim** [comment]
Yes, as far as we know, master is in good shape.

**Comment by pagecp** [comment]
ok Thanks! I will try it.

**Comment by pagecp** [comment]
I tested with the latest master branch, and it works but I had to reverse the options and use +t ...
It works with the following:

psimage bruine_forte.tif -Gblack+t -G255/51/2+b -Dx39p/438p+r72

but not with

psimage bruine_forte.tif -G+b -G255/51/2+f -Dx39p/438p+r72

as it should be.... Am I missing something?

**Comment by PaulWessel** [comment]
Could you please share your tif so we can debug the issue?

**Comment by pagecp** [comment]
Yes of course!

I made it available temporarily here: http://meteocentre.com/bruine_forte.tif

**Comment by PaulWessel** [comment]
Looks like the example we have that @joa-quim referred to only tests one case of transparency and that case works but the other cases don't.  Going to bed but know where to work on this, tomorrow.

**Comment by PaulWessel** [comment]
Thanks, I have fixed the problems via #2396.  Note that your 

`psimage bruine_forte.tif -Gblack+t -G255/51/2+b -Dx39p/438p+r72`

will now be ignored since there is no **+t** modifier for 1-bit image.  Also know that we have to assume that the first color in the image's colormap is the background and the second is the foreground.  It may be reversed in your tiff since I think you want red cloud/rain on transparent background?

**Comment by pagecp** [comment]
Thanks! I can confirm that it now works as expected.
For the colormap, it is not possible to also assume for 1-bit B&W images that the background is white?

**Comment by PaulWessel** [comment]
Will have a look to see what is the norm or definition, if any.

**Comment by PaulWessel** [comment]
Hi @joa-quim, perhaps we should heed this point? I think the vader1.png I made happen to have a scary Lord Vader photo where the background is black and the foreground is white, but perhaps that is the exception?  I think bit-images like these may come with different two-color colormaps so not sure what we should do other than assume color 0 is background and color 1 is foreground?

**Comment by joa-quim** [comment]
BW images have only 0&1. What is fore or background is a user case specific, no? If ``-Gcolor+b`` is not the *wantedground* the solution is to use ``-Gcolor+f``. We could have a **-D...+s** to do this, but it looks a overcomplication and makes the docs more cryptic.

**Comment by pagecp** [comment]
I have always thought that for BW images 0 is the background because the pixel is off. The shape being defined with a value of 1 with pixel on. But maybe I am wrong...

**Comment by joa-quim** [comment]
But that doesn't contradict what Paul said. 0 is first *color* in color map and is taken as the background color. 
From ``gdalinfo bruine_forte.tif``
```
Band 1 Block=18x18 Type=Byte, ColorInterp=Palette
  Image Structure Metadata:
    NBITS=1
  Color Table (RGB with 2 entries)
    0: 0,0,0,255
    1: 255,255,255,255
```

For me BW images work as masks. 0 is false and 1 is true. No back or fore grounds.

**Comment by pagecp** [comment]
With the original .ras images I used with GMT 5.x, I always had the same behavior when using them with the background being transparent, using:
psimage images.ras -Gb- -Gfcolor

With GMT6 after converting them to .tif 1-bit B&W (because .ras was no longer working) I had to reverse foreground and background:
psimage images.ras -G+f -Gcolor+b 


For reference:

Image: bruine_forte.ras
  Format: SUN (SUN Rasterfile)
  Class: PseudoClass
  Geometry: 18x18+0+0
  Units: Undefined
  Type: Bilevel
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 1-bit
  Channel depth:
    gray: 1-bit
  Channel statistics:
    Pixels: 324
    Gray:
      min: 0 (0)
      max: 1 (1)
      mean: 0.700617 (0.700617)
      standard deviation: 0.457988 (0.457988)
      kurtosis: -1.23248
      skewness: -0.876082
      entropy: 0.880535
  Colors: 2
  Histogram:
        97: (  0,  0,  0) #000000 gray(0)
       227: (255,255,255) #FFFFFF gray(255)
  Colormap entries: 2
  Colormap:
         0: (  0,  0,  0) #000000 gray(0)
         1: (255,255,255) #FFFFFF gray(255)
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 18x18+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Undefined
  Orientation: Undefined
  Properties:
    date:create: 2019-11-19T13:27:28+00:00
    date:modify: 2006-06-19T19:40:43+00:00
    signature: 9ae0d931e26aafaa0501df98a44809f66dc5bc6c4197021c2e44bd24acbdde01
  Artifacts:
    filename: bruine_forte.ras
    verbose: true
  Tainted: False
  Filesize: 104B
  Number pixels: 324
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org


Image: bruine_forte.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 18x18+0+0
  Units: PixelsPerInch
  Type: Bilevel
  Base type: Bilevel
  Endianess: LSB
  Colorspace: Gray
  Depth: 1-bit
  Channel depth:
    gray: 1-bit
  Channel statistics:
    Pixels: 324
    Gray:
      min: 0 (0)
      max: 1 (1)
      mean: 0.700617 (0.700617)
      standard deviation: 0.457988 (0.457988)
      kurtosis: -1.23248
      skewness: -0.876082
      entropy: 0.880535
  Colors: 2
  Histogram:
        97: (  0,  0,  0) #000000 gray(0)
       227: (255,255,255) #FFFFFF gray(255)
  Rendering intent: Undefined
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 18x18+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: None
  Orientation: TopLeft
  Properties:
    date:create: 2020-01-02T21:44:50+00:00
    date:modify: 2020-01-02T21:44:50+00:00
    signature: 9ae0d931e26aafaa0501df98a44809f66dc5bc6c4197021c2e44bd24acbdde01
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: min-is-black
    tiff:rows-per-strip: 18
  Artifacts:
    filename: bruine_forte.tif
    verbose: true
  Tainted: False
  Filesize: 312B
  Number pixels: 324
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

**Comment by PaulWessel** [comment]
It is true that our 1-bit images treatment after abandoning the Sun rasters is very new, and Joaquim implemented the passing of a 2-color colormap back for these 8-bit images (GDAL reads 1-bit images but returns 8-bit images as the smallest one, so we had to make some decisions).
We could decide to inspect the color map and if we find the two colors black and white we could decide that the black is background and the white is foreground, but there is no guarantee that it reflects what the user or image meant.

**Comment by pagecp** [comment]
Yes, I understand that with the change from 1-bit images to minimum 8-bit images it is different and decisions for defaults must be taken... 

On a side note the psimage documentation for GMT 6 mistaken me:
===
This must be an Encapsulated PostScript (EPS) file or a raster image. An EPS file must contain an appropriate BoundingBox. A raster file can have a depth of 1, 8, 24, or 32 bits and is read via GDAL. Note: If GDAL was not configured during GMT installation then only EPS files are supported.
===
I struggled because I thought that SUN Raster was still supported because it was a raster and it was 1-bit. I thought I had misconfigured GDAL at compilation time, first.

**Comment by PaulWessel** [comment]
Hi @joa-quim, I think it is no contradiction with what you said about true/fase in that true is "set" and that is what the foreground is.  So given that @pagecp has a ras and tif with exactly the same content, it is odd that we would switch things around on him.  Perhaps detecting which color is "not set" i.e., 0/0/0 is how to decide what the background is.  If the colors are _not_ black and white or white and black we resort to current scheme of first color is background.

**Comment by joa-quim** [comment]
I'm getting confused and have the impression that we are all saying the same thing. BW images come from GDAL with always
```
  Color Table (RGB with 2 entries)
    0: 0,0,0,255
    1: 255,255,255,255
```
So first color is 0 and that is what use as background. Isn't it what @pagecp wants?
If it happens that some gif or png 1-bit image has a true color map and GDAL gives that (not tested as we never had such case) than ... we would do the same thing first is bg and second fg.

Aside from these dounts, I agree that GMT6 should do what GMT5 used to do with same image but as Sun raster.

**Comment by joa-quim** [comment]
> I struggled because I thought that SUN Raster was still supported because it was a raster and it was 1-bit.

Don't remember. Did we drop the Sun raster format?

**Comment by pagecp** [comment]
GDAL does not seem to support it, gdal-info do no work on it.

**Comment by joa-quim** [comment]
Yes, *mine* GDAL doesn't list it either but we still have ``gmt_ras_read_grd()`` and alike functions. What happened when you tried to read a Sun raster image?

**Comment by PaulWessel** [comment]
Yes, we dropped it since it is a historical document with little/no support.

**Comment by PaulWessel** [comment]
You can still read Sun rasters as a data grid, but that is different from painting in image.

**Comment by pagecp** [comment]
@joa-quim I had the error saying it is an unsupported format. I think it is the error thrown back by GDAL.
