### ISSUE TITLE
pslegend uses inches when it should be using default units (cm)

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#239]
```
julia> plot(rand(10), marker=:square, markeredgecolor=:white, size=0.4, markerfacecolor="red", show=1, leg=true, fmt=:png)
leg = ["S 0.375c s0.4 0.75c red 0.5p,white 0.89c y1"]
```
In the above the ``leg = ["S 0.375c s0.4 0.75c red 0.5p,white 0.89c y1"]`` is the argument sent to ``pslegend`` and if the symbol size has no units pslegend uses it in inches and the result is wrong.

![lixo](https://user-images.githubusercontent.com/537321/50461082-9360e280-0973-11e9-99b7-5bc253305502.png)

**Comment by PaulWessel** [comment]
More Julia parser error I suppose.  Per legend man page, input for S is

`S [dx1 symbol size fill pen [ dx2 text ]]
`

so the space between symbol and its size is important.  In your case, things get messed and 0.75c is seen as symbol size, not 0.4.

**Comment by PaulWessel** [comment]
I think your Julia parser needs a debug mode so that you can see what it is passing into the GMT core; otherwise I waste time tracking down non-bugs.

**Comment by joa-quim** [comment]
It has that debug mode. When I add Vd=1 it prints the generated command. However, for  auto generated legends I need to manually make it print it. Which I did and saw the command was good. It may had happened that the copy paste has eaten the space (happened before). 

Sent from my iDedo

No dia 28/12/2018, às 22:10, Paul Wessel <notifications@github.com> escreveu:

**Comment by joa-quim** [comment]
I’m not at the computer. When I get back I’ll post more cases showing that without s0.4c it prints in inches. 

Sent from my iDedo

No dia 28/12/2018, às 22:10, Paul Wessel <notifications@github.com> escreveu:

**Comment by PaulWessel** [comment]
Fine, but now that you're 0.75c (dx2?) is in the wrong order as well.  The S line has max 8 entries (including the S) but yours seems to have 9.  Cannot have both 0.4 and 0.75c at the same time.

**Comment by joa-quim** [comment]
You may see in the second line of first post that the number of terms, including the S, is 8

Sent from my iDedo

No dia 28/12/2018, às 23:02, Paul Wessel <notifications@github.com> escreveu:

**Comment by PaulWessel** [comment]
OK, sorry, so

`S 0.375c s0.4 0.75c red 0.5p,white 0.89c y1
`

has indeed 8 entries but the order should be

`S [dx1 symbol size fill pen [ dx2 text ]]`

So in your case, symbol is s, **0.4 is discarded,** 0.75c is size, etc.

**Comment by joa-quim** [comment]
OK, that 0.75c is there from the lines case but for other symbols the ``symbol`` element seems to ingest also its size (which helps me with these commands construction). See

```
julia> plot(rand(10), marker=:square, markeredgecolor=:white, size="0.4i", markerfacecolor="red", show=1, leg=true, fmt=:png)
leg = ["S 0.375c s0.4i 0.75c red 0.5p,white 0.89c y1"]

julia> plot(rand(10), marker=:square, markeredgecolor=:white, size="0.4c", markerfacecolor="red", show=1, leg=true, fmt=:png)
leg = ["S 0.375c s0.4c 0.75c red 0.5p,white 0.89c y1"]
```
So, if we specify the units the 0.4<unit> is not discarded.

![lixo_in](https://user-images.githubusercontent.com/537321/50532290-69442780-0b0f-11e9-8417-ae4f1aa1402f.png)
![lixo_cm](https://user-images.githubusercontent.com/537321/50532291-69dcbe00-0b0f-11e9-9947-623aaadd13a6.png)

**Comment by joa-quim** [comment]
Actually it's much more handy that size can be concated with the symbol. Otherwise I'll have to break up the symbol<size> token that we provide in the command line.

**Comment by PaulWessel** [comment]
I understand, but pslegend reads separate words for symbol and size, and if I have to parse both for symbol size and/or unit it is getting unwieldy, no?  The effect you are seeing is definitely a bug in letting user mistakes being parsed.

**Comment by PaulWessel** [comment]
Closing this issue now.
