### ISSUE TITLE
-S under Azimuthal Equidistant projection

### ISSUE THREAD

**Issue by yangleir** [GenericMappingTools/gmt#2409]
When add `-Scolor` for pscoast under the Azimuthal Equidistant projection, the map shows a bug that some land is filled with the color set by -S.
If we add a optionally horizon parameter like  `-JE180/50/170/4.5i`, the map is changed to normal. But if the horizon is set to 180 (default), the map is broken again. So I guess it is the default horizon affected the -S.
The value of the longitude in `-JE` also related to the bug. If it was set to a 10 like `-JE10/50/170/4.5i` (with -S), the map shows bug, too. So it is a bit confused.

**Description of the problem**

**Full script that generated the error**

```
gmt pscoast -Rg -JE180/50/4.5i -Bg -Dc -A1000 -Glightgreen -Sgray > GMT_az_equidistant.ps
gmt pscoast -Rg -JE180/50/170/4.5i -Bg -Dc -A1000 -Glightgreen -Sgray > GMT_az_equidistant.ps
```

**Actual outcome**

![GMT_az_equidistant](https://user-images.githubusercontent.com/9152905/71777395-4bd75280-2fda-11ea-9922-f2503b94d0e4.png)

**System information**

* Operating system:MINGW64_NT-10.0-17763
* GMT version (`gmt --version`):6.0.0

**Comment by PaulWessel** [comment]
Hi @yangleir, I have addressed this particular problem and it has been merged into the repo.  Thank you for your report.

**Comment by yangleir** [comment]
Hi @PaulWessel ,Thanks l so much. You and your team always fix bugs so fast.
