### ISSUE TITLE
Add new map projetion

### ISSUE THREAD

**Issue by yangleir** [GenericMappingTools/gmt#2418]
**Description of proposed changes**
An interesting Chinese scientist  invented a interesting map projection named vertical map projection which give us a new view of the world. See his [sites](http://www.hxgmap.com/),but in Chinese. 

For vertical projection the earth surface is slit on the E-W direction and projected to flat surface. Here is figure to show the different between traditional map projection and the vertical one.
![切](https://user-images.githubusercontent.com/9152905/71878805-89b5b180-3167-11ea-908a-54d95a315d70.jpg)

In addition to the fun perspective, the vertical map could be used in polar science because its deformation at polar area is small. It can put the arctic and antarctic into one map with small deformation over polar area. So I think this map projection is both interesting and useful for science. 

The GMT could map such kind of vertical map using the `-JT` projection. But the maps are actually different, since the mathematics  behind the maps is different.

I hope The GMT could add the map projection. 

Here is the media report and the map.
![sjb20170218](https://user-images.githubusercontent.com/9152905/71878147-eca64900-3165-11ea-9cef-425e3b0ce43d.jpg)
![1106south](https://user-images.githubusercontent.com/9152905/71878367-6f2f0880-3166-11ea-87db-bc5e87dc282b.jpg)

**Comment by joa-quim** [comment]
@yangleir The best way to have that projection in GMT if you lobby it into PROJ4. All projections supported by PROJ4 are accessible in GMT (though for many of them we still have no mechanism to plot the a frame)

**Comment by PaulWessel** [comment]
I am closing this issue since we have no plans of adding new projections to GMT - in fact our long-term plan is to migrate exclusively to using PROJ.
