### ISSUE TITLE
pscoast  -W failed to export different level data

### ISSUE THREAD

**Issue by yangleir** [GenericMappingTools/gmt#2433]
**Description of the problem**
Using pscoast -M and seting one of the -I,-W,-N or -E,  the GMT could dumps data.
-W shows a bug that the dumped data are always including all levels no matter the level changed.

**Full script that generated the error**

```
#!/bin/bash
ps=example_large.ps
R=-R60/140/20/70
gmt psbasemap $R -JM4.5i -K -Bag > $ps
gmt pscoast $R  -M -W2  -Df > data.txt
gmt psxy $R -J data.txt -W0.4p,green -O >> $ps
```
* Operating system: window 10
* GMT version (`gmt --version`):6.0.0

**Comment by PaulWessel** [comment]
More of a feature than a bug.  We cannot tell your -W2 from the pen 2.  However, implementing a fix so you can use -W2/_pen_ so the parsing can work.

**Comment by PaulWessel** [comment]
Implemented.
