### ISSUE TITLE
Add progress bar option to movies

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2439]
**Description of the desired feature**

While **movie** offers automatic labeling of frame number, elapsed time, or real time via the **-L** option, it is often of interest to add a progress bar that indicates how far into the animation we have reached. Having given this some thought, here are some proposed progress bars (showing a snapshot at frame 185 of 555, or a progress of 33%):

![progressbar](https://user-images.githubusercontent.com/26473567/72216636-d0890b80-34c7-11ea-9031-24f02fdc2c03.png)

The illustration shows three circular and three linear progress indicators.  I imagine a currently available option like **-E** or **-K** in **movie** could follow a syntax like this:

**-E**[_just_][**+w**_width_][**+p**_pen1_[/_pen2_]][**+g**_fill1_[,_fill2_]][**+**_offset_][**+a**[**e**|**f**|**p**|**c**_col_]][**+s**_kind_]

where most of these modifiers are familiar from the placement of other types of embellishments (e.g., _just_ for positioning, _width_ for bar/circle width, _offset_ to move away from the anchor point). There may be 1-2 pens and 1-2 fills to specify (the progress bars typically have two colors, either via lines or via fills), and **+a** controls if there is any annotation and if so if we should display **e**lapsed time, **f**rame counter, **p**ercentage, or the time from **c**olumn _col_ (this is similar to codes in **-L**). Finally, **+s** selects which progress indicator from this list (a-f).  There should be reasonable defaults for most settings and even just **-E** should plot a reasonable progress bar [we need to pick a default bar - maybe a)?].

Since all such indicators consist of a constant part (e.g., the background line, the filled circle) and a changing part (the inner line, the wedge or partial arc, the percentage text) I can implement it efficiently.  As for labels via **-L** the **-E** option would be repeatable.

Let me know if @GenericMappingTools/core or anyone else have any comments or suggestions.

**Comment by seisman** [comment]
It's really cool! 

For the two pens and fills, better to use the same separator, i.e.  [**+p**_pen1_[/_pen2_]][**+g**_fill1_[/_fill2_]].

**Comment by PaulWessel** [comment]
problem is things like the colors 233/14/15 and 13/155/200, it would look odd I think with **+g**233/14/15/3/155/200, no?  Alternative is a second **+g**-like option, say **+G**.  Same for second pen **+P.**

**Comment by seisman** [comment]
You're right. **+P** and **+G** seem OK to me.

**Comment by PaulWessel** [comment]
Yes, better to stick with individual options than inventing a unique multi-pen or fill setting.  So the updated syntax would be

**-E**[_just_][**+w**_width_][**+p**_pen1_][**+P**_pen2_][**+g**_fill1_][**+G**_fill2_][**+o**_offset_][**+a**[**e**|**f**|**p**|**c**_col_]][**+s**_kind_]
