### ISSUE TITLE
gs 950 should always use -dNOSAFER?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2460]
A Chinese user tried to let his GMT support Chinese text. He failed with gs9.50, but succeeded with gs 9.26.

Below is the error message he got with gs950. I think he didn't use the gs9.50 shipped with GMT installers, because that gs doesn't ship configuration files for CJK fonts:

![image](https://user-images.githubusercontent.com/3974108/72578954-a491cf80-38a5-11ea-921b-aa078318a57d.png)

The first message says gs can't find the Chinese font, and the second says "permission denied". I guess the problem is the gs command which uses the `-dSAFER` option. With this option, gs probably can't read the file system (i.e. the font, or font configuration file). What's the reason for "-dSAFER" here? Should gs always use `-dNOSAFER`, at least for gs950?

**Comment by PaulWessel** [comment]
I suppose so.  We left the **-d**SAFER in the boundingbox calculation but we have **-d**NOSAFER everywhere else.  So no big leap to either remove the -dSAFER from boundingbox or use **-d**NOSAFER instead.  Perhaps he could give that a try and report back?

**Comment by seisman** [comment]
Using `gs -dNOSAFER` gives no error, but the generated "bb" file is empty. Is it normal?

BTW, if a script starts with `gmt begin map pdf A,C-dNOSAFER`, it can generate the PDF file with Chinese characters correctly.

**Comment by PaulWessel** [comment]
So if we replace -DNOSAFER with -dSAFER  in the gs_BB string in psconvert then you would not have to do A,C-dNOSAFER, right? I think we should do that.  The safe stuff is the gs people worrying about rouge PS code that access file systems etc.  I dont think we have any issues with that.

**Comment by seisman** [comment]
Yes, I think so.

**Comment by PaulWessel** [comment]
OK, feel free to make the edit.

**Comment by seisman** [comment]
Fixed in #2464. @joa-quim Could you please build a 64-bit Windows installer for the latest master branch, so that we can do a real test before 6.1.0 is released.

**Comment by joa-quim** [comment]
@seisman made [one ](https://www.dropbox.com/s/v604u8xjac9e7ma/gmt-6.1.0_a405b19_2020.01.21-win64.exe?dl=1) today

**Comment by seisman** [comment]
@joa-quim Thanks. It's confirmed that the issue has been fixed!

BTW, your installer may miss a dll file, VCRUNTIME140_1.dll.
