### ISSUE TITLE
Four failing tests on macOS CI

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2466]
The macOS CI reports four failing tests recently, although they all work well for me locally. The four tests are:

```
	253 - geodesy/case_largeR_noW.sh (Failed)
	254 - geodesy/case_largeR_withW.sh (Failed)
	255 - geodesy/case_smallR_noW.sh (Failed)
	256 - geodesy/case_smallR_withW.sh (Failed)
```

However, the CI doesn't give any useful information for debugging.

**Comment by PaulWessel** [comment]
Hm, wonder about Ax= b and eigenvalues and lapack issues?
