### ISSUE TITLE
Remove all trailing whitespaces?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2470]
There are many trailing whitespaces in the codes. Some editors automatically remove the trailing whitespaces while others may not. Sometimes it's frustrating to realize that a small change results in a large diff file, which also makes the review difficult.

I think we can have a simple script to remove all these trailing whitespaces.

**Comment by PaulWessel** [comment]
Yes, I have noticed that.  Cut and paste and incomplete edits result in these I think.  We also have the issue of indentation.  I think @leouieda mentioned something about having such a check as part of the commit process?

**Comment by seisman** [comment]
https://pre-commit.com/ This tool seems useful.

**Comment by remkos** [comment]
Thanks for removing all the trailing whitespace. Indeed the editor that I usually use (SublimeText) by default removes the trailing spaces, so I have stumbled upon this more often.

Now that that is done, and we seem to agree to try to keep them out, I think we can close this issue.

**Comment by leouieda** [comment]
As @seisman said, we could make more use of precommit to have certain things be run automatically when committing (locally). Having CI push changes to PRs is a bit more complicated since it can mess up the history if the person is unaware. We we could (should?) run a basic linter in a dedicated CI job (so it finishes fast). What do you all use for C?

**Comment by PaulWessel** [comment]
I am embarrassed to say I have not use a linter since SunOS days.  The compiler -Wall helps a lot though.

**Comment by PaulWessel** [comment]
Just installed cppcheck and there is useful information at [this site](https://invisible-island.net/personal/lint-tools.html).

**Comment by joa-quim** [comment]
Maybe we have more important things to care about?
