### ISSUE TITLE
Review of gallery examples points out weaknesses

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2471]
In going through the gallery examples I noticed a few recurring issues that we should address.  Many of these reflect the old age of the scripts (first conceived in GMT 3) and others reflect the US-centric use of units.  This is separate from the fact we need a different type of gallery to show how things are done.  Anyway, here they are:

1. The majority of geographic maps are using **--FORMAT_GEO_MAP**=dddF to get the W|E|S|N suffix emplaced.  I wish that was the default, but see below for another solution.
2. Most scripts use inches for plot dimensions (e.g., map widths and so on).  We should redo those in SI units; the PS plots will change since we should stick to integer cm where possible.
3. Most script uses fractional inches to indicate small offsets or clearances related to text or nudging of color bars and other embellishments (e.g., **+o**0.1i/0.1i).  Given we specify fonts in points I think it makes more sense to use points in such adjustments (e.g, **+o**8p).  Also, there is no need to repeat an identical y-offset.
4. Less sure about this, but symbol sizes are also candidates for specifying in points, no?

The convoluted **--FORMAT_GEO_MAP**=dddF is annoying to me.  Not only is it tedious to add; I usually have to look up the exact name of it and sometimes the syntax.  There are two solutions that does not break backwards compatibility.

1. Implement GMT _themes_, where we say gmt set GMT_THEME=_classic_|_modern_|_darkmode_|_whatever_ and we spiff up the to-be-designed modern theme so we don't have to add all those **--PAR**=_value_ statements. 
2. Add a new modifier to **-B** that will turn that feature on, e.g., **+f** for "formatted annotations".

The theme implementation should be simple - it is basically collecting a bunch of GMT settings and placing them in a file in share somewhere, called modern.conf and then add the GMT_THEME parameters which will expect a theme prefix and then open and process those settings.  I think we all all of that already in place (parsing gmt.conf files) and just need the themes and the new keyword.  Of course, that implementation does not rule out the usefulness of the **+f** proposal.

Comments from @GenericMappingTools/core appreciated!

**Comment by seisman** [comment]
> 1. The majority of geographic maps are using **--FORMAT_GEO_MAP**=dddF to get the W|E|S|N suffix emplaced.  I wish that was the default, but see below for another solution.

I don't think **--FORMAT_GEO_MAP**=dddF is a good default, especially for small regions. For example, `gmt basemap -R0/1/0/1 -Baf -JM10c --FORMAT_GEO_MAP=dddF -pdf map`. Even for large regions, using negative values for south and west hemisphere is commonly accepted.

> 2. Most scripts use inches for plot dimensions (e.g., map widths and so on).  We should redo those in SI units; the PS plots will change since we should stick to integer cm where possible.

I agree.

> 3. Most script uses fractional inches to indicate small offsets or clearances related to text or nudging of color bars and other embellishments (e.g., **+o**0.1i/0.1i).  Given we specify fonts in points I think it makes more sense to use points in such adjustments (e.g, **+o**8p).  Also, there is no need to repeat an identical y-offset.

I agree.

> 4. Less sure about this, but symbol sizes are also candidates for specifying in points, no?

Usually I find cm is more intuitive to me, because I never remember how large is a 20p symbol. It's a little different for text strings, because most users are used to specify font size in points when they use MS Word or other softwares.
 
> The convoluted **--FORMAT_GEO_MAP**=dddF is annoying to me. Not only is it tedious to add; I usually have to look up the exact name of it and sometimes the syntax. There are two solutions that does not break backwards compatibility.

See my first comment.

**Comment by PaulWessel** [comment]
I did not really mean dddF but the "F" part.  Your small map area should be 0 30' N  etc.

**Comment by joa-quim** [comment]
Agree with all 1 to 4. Symbol size in integers is preferable to decimals of some unit.
Did not quite get the **+f** proposal. It would be a way to select THEMES?

**Comment by PaulWessel** [comment]
No, the **+f** was suggested to be another modifier to **-B** and it would simply add the W|E|S|N to the annotations, similar to how **+p** and **+u** add prefix and units for Cartesian axes, respectively.  Theme changes would require gmt set.

**Comment by PaulWessel** [comment]
All but 1-2 gallery scripts are now in SI.  Will get the last ones soon enough.

I will review how the **FORMAT_GEO_MAP**=dddF stuff works.  This is way too complicated for something so basic.  I will see if a modifier **+f** to **-B** is the way to go, and perhaps otherwise we can achieve the change via a GMT modern _theme_.

**Comment by PaulWessel** [comment]
Closing this as addressed.
