### ISSUE TITLE
Dose pshistogram  -W control the pen thickness or the data bin width?

### ISSUE THREAD

**Issue by yangleir** [GenericMappingTools/gmt#2490]
Seems the -W in pshistogram  controls the data bin width as the test script wrote. But in the document it still say  `-Wpen`. So is it wrong ?  Or -W control both?

Besides, -T in pshistogram  also controls the bin width as document writes.  But when use -T and -W at the same time, it says:
```
yangleir@DESKTOP-FVRFATD MINGW64 ~/Documents/GMT/gmt-master/test/pshistogram
$ ./distributions.sh
pshistogram [COMPATIBILITY]: The -T<col> option is deprecated; use -i<col> instead.

```
Maybe this is related the COMPATIBILITY between different versions?

**Full script that generated the error**
This is modified from test dir `GMT/gmt-master/test/pshistogram`.
```
gmt pshistogram -Baf -BWSne+glightblue @v3206_06.txt -R-6000/0/0/1300 -JX3i/2.0i -Gorange -L1p -Z0 -W200 -P -K -N0+p1p,red -N1+p1p,green -N2+p1p,blue -Y0.75i  > test.ps
```

```
gmt pshistogram -Baf -BWSne+glightblue @v3206_06.txt -R-6000/0/0/1300 -JX3i/2.0i -Gorange -L1p -Z0 -T200 -W1 -P -K -N0+p1p,red -N1+p1p,green -N2+p1p,blue -Y0.75i  > test.ps
```

* Operating system: MINGW64
* GMT version (`gmt --version`): GMT6.0.0

**Comment by PaulWessel** [comment]
It is true -W used to set the bin width and -T the column to read back in the GMT4 days.  In the new syntax the we use -T for output intervals (and optional range) throughout GMT, -i to select any particular columns(s), and -W sets the pen; yet this is all backwards compatible with old scripts.

**Comment by seisman** [comment]
I think we should update most of the test scripts to the new syntax, while keeping one or two for checking backwards-compatibility.

**Comment by yangleir** [comment]
The ex06 script still uses the -W to set the bin width. See https://docs.generic-mapping-tools.org/6.0/gallery/ex06.html#example-06 

If I change the script based the new mode. It dose not work good.
```
#!/usr/bin/env bash
#		GMT EXAMPLE 06
#
# Purpose:	Make standard and polar histograms
# GMT modules:	histogram, rose
#
gmt begin ex06
	gmt subplot begin 2x1 -A+JTL+o0.3i -Fs6i/3.5i -M0.4i -X1.25i
		gmt histogram -Bx+l"Topography (m)" -By+l"Frequency"+u" %" -BWSne+t"Histograms"+glightblue @v3206_06.txt \
			-R-6000/0/0/30 -Gorange -L1p -Z1 -T250 -W1p -c0
		gmt rose @fractures_06.txt -: -A10r -S -Gorange -R0/1/0/360 -Bx0.2g0.2 -By30g30 -B+glightblue -W1p -c1
	gmt subplot end
gmt end show
```


```
yangleir@DESKTOP-FVRFATD MINGW64 /c/programs/gmt6/share/doc/examples/ex06
$ ./ex06.sh
histogram [ERROR]: Unrecognized option -T
histogram [ERROR]: Syntax error -T: Increment is zero
```

**Comment by PaulWessel** [comment]
Did you change both options, i.e., you have **-W**1p **-Z -T**250.  That runs fine for me.

**Comment by yangleir** [comment]
Yes, I need to delete the -L1p. After that it works.

**Comment by PaulWessel** [comment]
Thanks, we have updated the repo.
