### ISSUE TITLE
CPT work broke externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2495]
Now both Julia and Matlab crash with this simple command
```
gmt('makecpt -T30.969/31.031 -Clightblue')
```
First look shows that happens in ``gmt_stretch_cpt()`` because ``P.data`` is NULL

**Comment by joa-quim** [comment]
Actually the problem is not in the *externals*. This now returns nothing
```
makecpt -T10/20 -Cred
```
while before used to return
```
10	red	20	red
B	black
F	white
N	127.5
```

**Comment by joa-quim** [comment]
Shit happens in ``gmtlib_make_continuous_colorlist()`` when it does 
```
P->n_colors--;	/* One less slice */
```
The issue is that when there is only one color ``P->n_colors`` becomes zero and later when duplicating the palette, in ``makecpt``
```
if (!Ctrl->T.interpolate) {	/* Just copy what was in the CPT but stretch to given range min/max */
		if ((Pout = GMT_Duplicate_Data (API, GMT_IS_PALETTE, GMT_DUPLICATE_ALLOC, Pin)) == NULL) return (API->error);
```
since there are no colors there is no memory allocated to ``P->data``.

adding
```
if (P->n_colors == 0) P->n_colors = 1;		/* Happens when there was only one color to start with */
```
at the end of ``gmtlib_make_continuous_colorlist()`` solves the issue, but not sure if this is the best solution.

**Comment by PaulWessel** [comment]
OK, will look.

**Comment by PaulWessel** [comment]
The solution will be to not call _gmtlib_make_continuous_colorlist_ when _n_colors_ == 1 since that is a special case of only one color and hence that single slice must remain discrete.  PR coming soon.
