### ISSUE TITLE
Outdated description of common options in the cookbook

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2512]
The description of -X, -Y, -e, -f in the cookbook are outdated and need to be updated.

**Comment by PaulWessel** [comment]
I am fixing -X -Y -e but what is it about -f you you want changed?

**Comment by seisman** [comment]
The -f option in the cookbook says the column range is given like 3-6, but the explain_-f_full says 3:6.

**Comment by PaulWessel** [comment]
Thanks, missed that.  Fixing in the PR before merging.  We now use the colon syntax throughout our documentation (but can also parse hyphen ranges).  Pretty sure we have lots of hyphen syntax in tests and examples so I will look for that next.
