### ISSUE TITLE
Separate chapter for CPTs in the cookbook

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2513]
As said before, the "General Features" chapter in the cookbook is too long to read. Splitting the CPT part to a separate chapter may make it easier to read.

**Comment by PaulWessel** [comment]
It may, but it would be a bit odd to separate out one feature from all the others.  Yes, it is long, but still much shorter than "Plot Embellishments" further down the Chapter.  I would think a more drastic reorganization is needed to make the cookbook more accessible, not just carving out a CPT chapter.

**Comment by seisman** [comment]
Yes, agreed. Closing.
