### ISSUE TITLE
Use list-table directive for the list of common options

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2576]
[std_opts.rst](https://github.com/GenericMappingTools/gmt/blob/master/doc/rst/source/std_opts.rst) uses a grid table to list all common options. The table is difficult to maintain, since grid-table is strict and all the grids ("|", "+", ...) must be well aligned. 

Sphinx has another directive "list-table" (an example shown below). list-table gives the same output as grid-table, but much easier to maintain.

```
.. list-table::
   :widths: 50 50
   :header-rows: 1

   * - STANDARDIZED COMMAND LINE OPTIONS
     -
   * - **-B**\ *information*
     - Specify map frame and axes parameters :ref:`(...) <-B_full>`
   * - **-J**\ *parameters*
     - Select map projection :ref:`(...) <-J_full>`
   * - **-p**\ [**x**\|\ **y**\|\ **z**]\ *azim*\ [/*elev*\ [/*zlevel*]][**+w**\ *lon0/lat0*\ [/*z0*]][**+v**\ *x0/y0*]
     - Control 3-D perspective view :ref:`(...) <perspective_full>`
```

**Comment by PaulWessel** [comment]
Yes, that does look like it would be easier to maintain and not deal with those gridlines.
