### ISSUE TITLE
GMT6 Tutorial page has no Table of contents

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2578]
Contrary to the GMT5 version that displays a TOC on the left side, the GMT6 version does not, which makes it quite hard to navigate the Tutorial.

**Comment by joa-quim** [comment]
Thanks. But it's still not enough. Yes we can now see the TOC (the four main points) but everytime we click on one topic the TOC disappears again.

**Comment by seisman** [comment]
It's probably because not all HTML files are rebuilt. You can try to delete all HTML files and rebuild it again.

**Comment by joa-quim** [comment]
Yes, you right. Rebuilding all HTMLs makes it behave well.
