### ISSUE TITLE
Rewrite gmt.conf.rst with Sphinx's glossary directive

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2586]
gmt.conf.rst contains all GMT parameters. Now it looks like:
```
.. _COLOR_BACKGROUND:

**COLOR_BACKGROUND**
    Color used for the background of images (i.e., when z < lowest color
    table entry) [black].

.. _COLOR_FOREGROUND:

**COLOR_FOREGROUND**
    Color used for the foreground of images (i.e., when z > highest
    color table entry) [white].
```
For each parameter, we have to specify a label (e.g. `.. _COLOR_BACKGROUND:`) so that we can reference the parameters in other files. The reference syntax is lengthy, e.g.
```
:ref:`COLOR_BACKGROUND <COLOR_BACKGROUND>`
```

Sphinx provides a directive "glossary". With the glossary directive, the gmt.conf.rst can be rewritten as:
```
.. glossary::

    **COLOR_BACKGROUND**
        Color used for the background of images (i.e., when z < lowest color
        table entry) [black].

    **COLOR_FOREGROUND**
        Color used for the foreground of images (i.e., when z > highest
        color table entry) [white].
```
Then we can reference the parameters with a shorter and more intuitive syntax
```
:term:`COLOR_BACKGROUND`
```

**Comment by PaulWessel** [comment]
Nice, seems like a useful simplification for the referencing.
