### ISSUE TITLE
Simplify the CMake configuration file

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2587]
**Description of the desired feature**

Right now the cmake/ConfigUserTemplate.cmake has 311 lines. The vast majority of these are not to be changed by the user.   It is easy to get lost in this large file.  Also, once you have made your copy to ConfigUser.cmake and we change the template, most users will not remember to update their config file.  Might it be better to use CMake's [include statement](https://cmake.org/cmake/help/latest/command/include.html) and instead isolate the few parameters that users may change into a ConfigGMTTemplate.cmake file that users can copy to ConfigGMT.cmake which is then included by our ConfigUser.cmake (renamed from ConfigUserTemplate.cmake)?  Maybe we could use CMake to tell [check if a file exists](https://cmake.org/cmake/help/v3.5/command/if.html) and then include the users GMT configuration file from their home directory instead of creating things in cmake?

**Comment by seisman** [comment]
What about splitting the parameters into two files: ConfigUserTemplate.cmake and ConfigUserAdvancedTemplate.cmake? 

Following parameters can be put in the ConfigUserTemplate.cmake file:

- CMAKE_INSTALL_PREFIX
- GMT_INSTALL_MODULE_LINKS
- GSHHG_ROOT
- COPY_GSHHG
- DCW_ROOT
- COPY_DCW

**Comment by PaulWessel** [comment]
Yes, that is a good idea.  There are several more advanced parameters that could go there that is separate from the scripting part of the file.  I just think it is easier to digest a parameter file(s) instead of having the assignments embedded in a CMake script.

**Comment by PaulWessel** [comment]
Not sure if the COPY_GSHHG and COPY_DCW are necessary at that level.  One users have downloaded these they should not need to duplicate them - that is for our bundle, etc?
