### ISSUE TITLE
Tutorial GMT environment figure needs an update

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2612]
The GMT environment figure (1) in the tutorial shows GMT producing PostScript output.  This is no longer correct in modern mode.

**Comment by PaulWessel** [comment]
Hi @remkos, I realized this figure is something you created with xfig.  I have trouble with xfig and Catalina + never used xfig.  Could I ask you to edit that xfig file and change the PostScript Plot File to something generic like Graphics Plot File since it may no longer be PostScript.  Then reproduce the PDF and PNG files? Thanks!

**Comment by seisman** [comment]
I can help by editing the PDF file with Adobe Illustrator.

**Comment by seisman** [comment]
ping @PaulWessel

**Comment by PaulWessel** [comment]
Sure, OK. Remko has not responded so I guess we can abandon the .fig file.
