### ISSUE TITLE
Broken externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2634]
```
>> gmt('grdimage JX12c/0 -Baf -BWSen -R1/128/1/128 -C', rand(128,128), C)
Error using gmtmex
gmtmex_palette_init: Expected a CPT structure for input
```
Debugging from Julia (where same happens ofc) shows the problem is that order of arguments is now reversed.  That is ``gmtmex_palette_init()`` is receiving the ``rand(128,128)`` instead of ``C``

**Comment by PaulWessel** [comment]
Hm, the required args are dealt with before the optional args.  So grid should be taken first for the default input.  I looked at this in trying to figure out the issue with the matrix/dataset recently, but I dont think I made any changes in GMT_Encode_Options where the order of things happen?

**Comment by joa-quim** [comment]
Understand nothing. Now in Julia this does nothing
```
C = makecpt(T="-6/8/1")
```
but it's part of a test and there apparently it works.

Also the Ml example, even if we swap the order of rand(), C we still get the same error.

**Comment by joa-quim** [comment]
Can't reproduce the Matlab case now, so closing this
