### ISSUE TITLE
plot warning: Can't use +f for Cartesian basemaps 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2659]
```
echo 5 5 | gmt plot -R0/10/0/10 -JX10c/10cd -Bxaf -Byaf+f -BWSen -Sc0.2c -pdf map
plot [WARNING]: Option -B: Cannot use +f for Cartesian basemaps - modifier ignored
```
It shouldn't complain about **+f** modifier, since I use **10cd** for Y axis.

**Comment by PaulWessel** [comment]
Hm, need to see if I can split the formatting across two axis (right now **+f** affects both axes even if there are separate **-Bx -By**).
