### ISSUE TITLE
mapproject seems inconsistent with default distance type

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2676]
**Incremental or Accumulated Distances**

Given [this forum message](https://forum.generic-mapping-tools.org/t/mapproject-g-parsing-doesnt-match-documentation/231/2) I am reviewing mapproject and its usage messages and documentation.  The crux of this issue is when mapproject **-G** defaults to issuing cumulative distances (summing along a track, for instance) and when it defaults to incremental distances (between two points only).  The current intention is this (per man page):

1. If **-G** is given with a point, i.e., **-G**_lon_/_lat_[_modifiers_], then we by default compute _incremental_ distances, i.e., each input point is used to compute its distance from _lon_/_lat_ and we report that result per point.  The default of incremental distances makes most sense here since summing these distances is not the most likely need of the user.  However, adding **+a** will switch to cumulative distances.
2. If **-G** has no fixed point, i.e., **-G**[_modifers_] then we default to _cumulative_ distances, so we are in "track" mode and sum distances along the track.  Since there is no fixed point, adding the distances makes most sense and hence that is the default.  You can request increments instead by adding **+i**.

Gray areas:

1. There is **-G+v**, which means that the fixed _lon_/_lat_ point is instead given in columns 3&4, and in effect those values are passed to **-G** on a per-record basis.  Because we now have a _fixed_ point (even though it changes per record) we then default to incremental distances.  You can add **+a** to switch to cumulative distances.  If you do, we do not check if the data in fact constitute a _track_: I.e., we do not check if the last record's col3&4 coordinates match the next record's col1&2 coordinates. If they don't, then we have a gap of some sort and it does not make much sense integrating up these distances.
2. There seems to be variability in how the **+i** and **+a** modifiers work.  In some cases they just reinforce the default: If cumulative is the default and you add **+a** then nothing new happens.  I think that is the expected behavior.  However, if accumulated distances is the default and **+i** is added then it seems we toggle to outputting incremental distances, not adding an extra column so that both accumulated and incremental distances are written.

Proposal: I suggest we want to ensure these principles:

1. If **+i** _or_ **+a** is given and it is the opposite of the default, then we switch and only output that type of distance.
2. If both **+i** _and_ **+a** are given then we output both distances.
3. If **-G+v+a** is given and there are gaps in the track then we should issue a WARNING.

Do you agree with this, @joa-quim and @seisman?

**Comment by seisman** [comment]
I never used mapproject, but what you proposed sounds good to me.

**Comment by joa-quim** [comment]
I agree with both 1-3. Just wonder if it worth slowing down the code checking for gaps in 3.

And, one day we must consider moving out these operations out of *mapproject*. It now does a lot more of *mapprojecting* things.

**Comment by PaulWessel** [comment]
Well, gmtspatial does lots of spatial stuff and it is over-booked as well.  We could consider making a new tool and let mapproejct call it for those options so we are backwards compatible.  Maybe gmttrack.
Meanwhile I will wrap this up as discussed above.
