### ISSUE TITLE
Move the "Installing dependencies" section of BUILDING.md to github wiki?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2687]
The "Installing dependencies" section of BUILDING.md is too long and is also a little off-topic (not directly related to GMT). Maybe it's better to put it in the GitHub wiki and add a link in BUILDING.md

**Comment by holishing** [comment]
I agree, another reason is that dependencies even other information related to building and packaging varies with time, it's more convenient to update those detailed information in github wiki.

**Comment by seisman** [comment]
Ping @joa-quim @PaulWessel

**Comment by PaulWessel** [comment]
Yep, I am onboard with that plan.
