### ISSUE TITLE
EXTRA_MODULES and EXTRA_INCLUDE_GMTSUPPL are not documented in ConfigUserAdvanced.cmake

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2690]
These two cmake variables are used in src/CMakeLists.txt, but not listed in ConfigUserAdvanced.cmake.

**Comment by PaulWessel** [comment]
EXTRA_MODULES is for developers to add new modules for testing without adding them to the main list of core modules.
EXTRA_INCLUDE_GMTSUPPL is for developers to test out new supplements without adding them to the main list.

**Comment by seisman** [comment]
Add them to ConfigUserAdvanced.cmake?

**Comment by seisman** [comment]
It’s better to rename EXTRA_INCLUDE_GMTSUPPL to EXTRA_MODULE_SUPPL to have consistent names?

**Comment by PaulWessel** [comment]
Yes to both.

**Comment by joa-quim** [comment]
EXTRA_MODULES actually doesn’t work. Tried it yesterday. The problem Is that one needs to set the core c code as well  

Sent from my iDedo

**Comment by PaulWessel** [comment]
I think works on macOS/Linux only without running gmt_make_module_src.sh.

Speaking of which, ideally cmake should figure out that if any of the core module files are younger than gmt_core_module.[ch] then it should run `gmt_make_module_src.sh core`, and likewise if any supplemental modules change it should run `gmt_make_module_src.sh supplements`.  Or if not actually running them, warn us.  The problem is that those KEYS change very infrequently, but when they do we need to remember to run those commands.

**Comment by joa-quim** [comment]
It works in the sense that it builds but when try ``gmt newmodule`` the *newmodule* is not known.

Everytime I change a KEY, I update the ``gmt_core_module.c`` It was long ago but the batch script always gave me troubles on Win.

**Comment by seisman** [comment]
> Speaking of which, ideally cmake should figure out that if any of the core module files are younger than gmt_core_module.[ch] then it should run `gmt_make_module_src.sh core`, and likewise if any supplemental modules change it should run `gmt_make_module_src.sh supplements`. Or if not actually running them, warn us. The problem is that those KEYS change very infrequently, but when they do we need to remember to run those commands.

I think we can do it in CI. For each CI job, we can run these scripts 
```
gmt_make_PSL_strings.sh     gmt_make_module_src.sh
gmt_make_enum_dicts.sh      gmt_make_pattern_include.sh
```
If any files are changed, then the CI job fails, so that we know we need to manually run these scripts.

**Comment by PaulWessel** [comment]
How does the CI job fail if `gmt_make_module_src.sh core` creates a modified gmt_core_module.c file? The changes to the KEYS only affect external API use.

**Comment by seisman** [comment]
I mean adding a new CI job. If gmt_core_module.c is modified, then the CI job reports an error to warn us.

**Comment by PaulWessel** [comment]
OK, I see.  It create the latest .ch files and diffs with what is in the repo and if different then we are told to run it and commit.

**Comment by seisman** [comment]
Yes, exactly.
