### ISSUE TITLE
Use earth_relief_10m instead of etopo10m_48.nc

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2709]
Some scripts use a remote cache data `@etopo10m_48.nc`. The data can be replaced by `@earth_relief_10m`.

**Comment by PaulWessel** [comment]
Agreed.

**Comment by seisman** [comment]
Most are addressed in #2711, except two scripts:

- test/potential/grdokb_grav.sh
- test/potential/fc_okb.sh

Changing `etopo10m_48.nc` to `earth_relief_10m` results in large difference between old and new PS files.

**Comment by PaulWessel** [comment]
Hi @joa-quim, perhaps you can check that out since those are your tests.  Perhaps the old topo is a chunk of the old ETOPO2 and earth_relief_02 is quite different, being a down filtered version of SRTM15.  I suspect the plots are very different but that they are correct?

**Comment by seisman** [comment]
Closed as #2711 was merged.
