### ISSUE TITLE
gmt_check_filearg() mistakes directory for file

### ISSUE THREAD

**Issue by dwcaress** [GenericMappingTools/gmt#2713]
I had an odd problem this morning with an MB-System generated plot script running 6.0.0 in classic mode. In the process of generated a slope-shaded map of bathymetry in a very typical grid file named ZTopo.grd, calls to grdgradient are made with azimuths of -A0 and -A90. The call with -A0 was failing as follows:

  gmt grdgradient ZTopo.grd -A0 -GZTopo.grd.drvy -fg

  ERROR 4: `0' not recognized as a supported file format.
  grdgradient (api_import_grid): Not a supported grid format [0]
  [Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
  [Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)

The problem turned out to be that there is a directory named '0' in the survey directory  that was created by the sonar datalogger, and the function gmt_check_filearg() was deciding that this directory is a readable file, which means that the -A0 argument was interpreted as setting a grid file to be read with variable azimuths rather than setting a fixed azimuth of 0 degrees. Later on the call to import data from this file failed. This is not really a bug, but it would be an improvement if you protected against this particular problem by augmenting gmt_check_filearg() to not treat readable directories as readable files. 

It looks to me as though this change would require using stat() rather than access() in the function gmt_file_is_readable() at line 3968 in gmt_io.c

The offending datalogger is a Windows application from Norbit, a Norwegian sonar company. 

**System information**
* Operating system: MacOs
* GMT version (`gmt --version`): 6.0.0

**Comment by PaulWessel** [comment]
That is a good one.  Yes, unintended consequences and not checking what is given.  Will take care of this shortly.
