### ISSUE TITLE
Backup download site for coastlines

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#2717]
I'm getting a 404 for ``https://mirrors.ustc.edu.cn/gmt/gshhg-gmt-2.3.7.tar.gz`` that is our backup download site but that I also use for Julia.
We have a ``gmt-gshhg`` GMT repo. Shouldn't we host the coastline files there?

**Comment by seisman** [comment]
The USTC server was down recently and the recovery is highly delayed by the coronavirus.

As for gmt-gshhg, I agree we can make releases there.

**Comment by joa-quim** [comment]
> highly delayed by the coronavirus

That has crossed my mind. Thanks

**Comment by PaulWessel** [comment]
Yikes, I hope your family in China are unaffected, @seisman.

**Comment by seisman** [comment]
They're all good. Thanks.

**Comment by seisman** [comment]
@PaulWessel Any thoughts about making GSHHG and DCW releases in the repositories?

**Comment by PaulWessel** [comment]
That seems very reasonable.  Keeps things together.

**Comment by seisman** [comment]
We now host the GSHHG and DCW on their own repositories:
- https://github.com/GenericMappingTools/gmt-dcw/releases/download/1.1.4/dcw-gmt-1.1.4.tar.gz
- https://github.com/GenericMappingTools/gmt-gshhg/releases/download/2.3.7/gshhg-gmt-2.3.7.tar.gz
