### ISSUE TITLE
Test nearneighbor/nat_nn.sh fails

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2721]
```
nearneighbor [ERROR]: gdal_grid: failure
nearneighbor [ERROR]: GDAL nearest neighbor returned error -1
ERROR: gmtest:54
memtrack errors: 0
exit status: 1
```

**Comment by joa-quim** [comment]
What GDAL do we have in CI? We need at least 2.1. It works fine here, though the test fails due to tinny differences between the GMT and GDAL solution.

**Comment by seisman** [comment]
It fails on all platforms:

Linux, gdal 2.2.3:
```
/usr/bin/gm compare: image difference exceeds limit (0.0211854 > 0.003).
nearneighbor/nat_nn.ps: RMS Error = 0.0212 [FAIL]
memtrack errors: 0
exit status: 1
```

macOS, gdal 2.4.4:
```
nearneighbor [ERROR]: gdal_grid: failure
nearneighbor [ERROR]: GDAL nearest neighbor returned error -1
ERROR: gmtest:54
memtrack errors: 0
exit status: 1
```

Windows, gdal 2.4.1:
```

C:\Program Files\GraphicsMagick-1.3.32-Q8\gm.exe compare: image difference exceeds limit (0.0211854 > 0.003).
nearneighbor/nat_nn.ps: RMS Error = 0.0212 [FAIL]
memtrack errors: 0
exit status: 1
```

**Comment by joa-quim** [comment]
They don't fail for the same reason. Linux and Win fail due to a different PS 
(same for me here
 image difference exceeds limit (0.0211854 > 0.005).
)
Mac fail because of a GDAL error. That is worst.

**Comment by PaulWessel** [comment]
runs fine on macos locally.

**Comment by joa-quim** [comment]
Anyway. We need an updated version of the orig PS

**Comment by PaulWessel** [comment]
we just got one via #2720.

**Comment by joa-quim** [comment]
@seisman The ``bUsageError`` initialization in #2775 may be important to this issue.

**Comment by seisman** [comment]
@joa-quim Yes, it fixes the failing tests.

**Comment by joa-quim** [comment]
Good but shit. That means the CI GMT builds were initializing that variable to **1**.  Not that I was counting on a particular initialization value (that would be very dumb), but was counting that GDAL set it to either 1 or 0. Which it doesn't. Only sets to 1 in case of error, otherwise just leave alone the value sent in. Not good.
