### ISSUE TITLE
Move advanced building and packaging instructions to other places

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2729]
Some sections in the BUILDING.md file are for advanced users and maintainers only. Most users never build documentation, run tests or make packages.

I think we can move the "Packaging GMT" section to GitHub wiki and the following sections to MAINTENANCE.md.

- Building documentation
- Running tests
- Creating source packages
- Packaging

**Comment by PaulWessel** [comment]
That is a good idea.  Packaging is for 0.001% of GMT users and building docs and running tests surely must be just developer types.
