### ISSUE TITLE
subplot crashes when the total number of panels is too large

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2730]
```
gmt begin map
gmt subplot begin 30x20 -Fs2c/2c
[1]    93421 abort      gmt subplot begin 30x20 -Fs2c/2c
```

**Comment by PaulWessel** [comment]
We are overflowing a short text string:

<img width="1285" alt="bug" src="https://user-images.githubusercontent.com/26473567/74458594-08b89c80-4e2e-11ea-82a6-0c1900576b1b.png">

I will be on the road most of today so cannot fix this now.  Solution is to keep count of how long the report string is and use strncat instead.  Feel free to work on this.
