### ISSUE TITLE
mapproject squeaks to stderr

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#2731]
Deliberate? 

```
$ pscoast -ENO -M | mapproject -Jm0/1:100 -R4/32/57/72 -C > /dev/null
4/32/57/72 -> 445277.963173/3562223.70538/7724253.02813/11712494.4545 [cm]
```

**Comment by PaulWessel** [comment]
Not really.  We recently overhauled how the default verbosity in GMT works and we still need to reassign different verbosity levels to some messages.  This one should be INFORMATIONAL so only visible with -V [which is -Vi].  Will fix.

**Comment by PaulWessel** [comment]
Note to self: Need to convert several GMT_Message calls to a single string and report via GMT_Report at the INFORMATION level of verbosity.
