### ISSUE TITLE
Use SI defaults for all examples

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2752]
Recently, @PaulWessel updated all examples to SI units (cm or point instead of inch). However, the original PS files are still generated using US defaults, and in the gmtest script, we have 
```
gmt set -Du FORMAT_TIME_STAMP "Version 6" GMT_GRAPHICS_FORMAT ps
```

We should regenerate all PS files using SI defaults, and change `gmt set -Du` to `gmt set -Ds`.

**Comment by PaulWessel** [comment]
The -Du also set page size to US Letter so there may be some examples or tests that will have plots that exceed the skinny A4 format...

**Comment by seisman** [comment]
`-Du` also set `PS_CHAR_ENCODING`, which determines how to explain octal codes. For example, users who run ex45 will get a different plot, because octal code `\264` is different for SI and US defaults.

**Comment by seisman** [comment]
BTW, we don't need to update the tests now. Users only care about the examples.

**Comment by PaulWessel** [comment]
OK, I can set it to -Ds, rerun all tests, and update any example PS files.  Is this what you want me to do?

**Comment by seisman** [comment]
Yes, but only for the example PS files.
