### ISSUE TITLE
Specifying 2-D input grids to grdinterpolate

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2783]
**Description of the desired feature**

The grdinterpolate module has not yet been released but will be soon (in 6.1.0).  Thus, this is a good time to discuss some aspects of it before we release it, as changing things later is more of a hassle.

grdinterpolate can sample a 3-D data cube along the 2-D plane normal to the time axis (or depth; will just call it time in this post).  The 3-D cube can be specified in two ways:

1. A 3-D netcdf file [Times are obtained from the data cube metadata]
2. A list of 2-D grids [Times are obtained from **-Zi**, either equidistant setup of a list]

While this may be fine if you have a manageable number of grids and they are simply spaced (e.g., imagine `gmt grdinterpolate temperature_*.grd -Zi0/1000/100`) for feeding in 11 grids at different depths 0, 100, 200, etc., it may be messier if you have grids at different times.  For that we added the option **-Zi**_times_, so you could do `gmt grdinterpolate INSAR*.grd -Zidates.txt`.

I can imagine that it may also be convenient to have a single list file that contains the times _and_ the file names per record:

```
2012-12-12T04:33 firstfile.grd
2012-12-16T14:03 nextfile.grd
...
```

and then pass that file to grdinterpolate somehow.  This also has the benefit of ordering the files properly and in only one place (versus making sure your input file order and level list match).  If you chose poor filenames then ls *.grd may not yield the desired order.

Given different users may have different needs., perhaps we should add a third way to enter the data:

3. A list file with times and corresponding file names given via a new option **-L**_listfile_.

Let me know what you think, hopefully David and Eric can comment on what is useful for them.

**Comment by dsandwell** [comment]
Our files are not always equally spaced in time so the -Zidates.txt would be good.  The file names we use will always be listed in the proper order because the time is YYYYDDD where DDD  is the day of the year.  We could easily have YYYY.YYYYYY where the values behinf the decimal point are fractions of a year.

**Comment by PaulWessel** [comment]
OK, since your needs are covered by the current scheme, we can always reconsider a **-L** option later if the need arises from some other quarter.
