### ISSUE TITLE
triangulate output depending or order of input data

### ISSUE THREAD

**Issue by simolon** [GenericMappingTools/gmt#279]
**Description of the problem**

It seems that the output of triangulate depends in some cases on the order of the data in the input table.

```
gmt triangulate -
cat  xxx.txt | gmt triangulate -R362000/382000/399500/419500 -I250 -Gunsrt.grd
gmt grd2xyz unsrt.grd > unsrt.xyz
sort xxx.txt | gmt triangulate -R362000/382000/399500/419500 -I250 -Gsrted.grd
gmt grd2xyz srted.grd > srted.xyz
diff -q srted.xyz unsrt.xyz 
```
**Full error message**
```
triangulate(core) 5.3.1 (r17229) [64-bit] - Optimal (Delaunay) triangulation and gridding of Cartesian table data
[...]
Files srted.xyz and unsrt.xyz differ
```

**System information**

* Operating system:
Debian GNU/Linux 9 (stretch)
* Version of GMT:
 5.3.1 (r17229) [64-bit]

![unsrt](https://user-images.githubusercontent.com/46345943/50636633-b92b5000-0f4e-11e9-9f71-26be1ab27e2f.png)
![srted](https://user-images.githubusercontent.com/46345943/50636634-b92b5000-0f4e-11e9-8810-a51d601dd037.png)

[xxx.txt](https://github.com/GenericMappingTools/gmt/files/2723622/xxx.txt)

**Comment by joa-quim** [comment]
It's not a known issue to us and I doubt that we will try to investigate/fix it. There are many more important things to do in GMT than to worry because Debian decided to build against Watson instead of Shewchuk. Sorry.

**Comment by simolon** [comment]
Thank you for your direct answer. I know from own experience that adding
new features and maintaining a reliable codebase can not always go hand in
hand and the developers always have to prioritise.

I hope that someone might eventually find and commit a fix for this bug now
that it is documented.

May I suggest, as a very, very quick fix, to add a small warning when this
algorithm is used, and point out that it is (now) known to be buggy?

Such a warning might have saved us quite a few manhours in find this weak
spot in our workflow. :-)

**Comment by PaulWessel** [comment]
I will try to look into this over the weekend but my plate is very full these days so no promises.

**Comment by PaulWessel** [comment]
Closing this since the warning is now merged into master.

**Comment by simolon** [comment]
Hi Paul and Joaquim,

sorry to post into this closed thread, but I just figured out what the real problem seems to be. We missed to spot that there were duplicate lines in some of our input files. This seems to be the culprit, having identical x/y pairs in the input data. The sorting in some cases fixed it, but in some other cases caused the error to manifest while the unsorted ones worked. 

So the warning when unsorted is in fact unnecessary, and rather should be an error when duplicate x/y pairs are found.

Sorry for your troubles... and thanks for your great work.
