### ISSUE TITLE
Plotting Earth cross-sections without going crazy

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2791]
Seems to me GMT is not doing a great job here - but maybe I am not used to making these types of plots.  Seismologists like @seisman may have more experience with this.  To plot just the mantle and exclude the core, I know Earth radius is ~6370 km and core is at a depth of ~ 2890 km.  OK, so I want a windshield-wiper plot where the (not plotted) center of the Earth is at the projection center and the two arcs should be at r = 6370 (surface) and r = 6370-2890 = 3480 (core-mantle boundary).  So looks like this works: `gmt basemap -R0/180/3480/6370 -B -JP15c+z -png map` :

![map](https://user-images.githubusercontent.com/26473567/75101756-d4f41a00-5585-11ea-852e-93742a4c7be5.png)

**Problem 1:** Why do I have to do that math manually?  I want to use 0 and 2890 as my depths (z-value).

Lets say this is a slice along equator, so those degrees are degree longitude.  Then, the plot is OK if looked at from the N pole (since longitudes increase counterclockwise).  However, if I want to look at this from the S pole, then I need to do more work, and after some trial/error I select `gmt basemap -R0/180/3480/6370 -B -JPa15c/90+z -png map`:

![map](https://user-images.githubusercontent.com/26473567/75101794-8004d380-5586-11ea-9d27-2449312652ca.png)

**Problem 2:** This might be hard to find out for laypeople.  OK, that is fine I guess, perhaps fixable in the documentation.

Now I want to display seismic velocities in this crossection.  I take the S362ANI_kmps.nc and extract data from 25 to 2890 in steps of 5:

gmt grdinterpolate S362ANI_kmps.nc -E0/0/180/0+i1d -T30/2890/5 -Gslice.nc -Ap

That grid now has x from 0/180 and y from 25 to 2890.  How to plot as above?  Trying `gmt grdimage slice.nc -B -JP15c+z -png map` brings no joy:

![map](https://user-images.githubusercontent.com/26473567/75101895-0968d580-5588-11ea-99d2-0935a25fb189.png)

since there is no info on radius range or depth range, and the depth of 25 (start of grid) results in a tiny cavity at the center with ugly annotations.  OK, maybe need to use the **-R**0/180/3480/6370 from before? No, that gives 

> grdimage [WARNING]: Your grid y's or latitudes appear to be outside the map region and will be skipped.

which of course is true.  Hacking away I do

```
gmt grd2xyz slice.nc | awk '{print $1, 6370-$2, $3}' | gmt xyz2grd -R0/180/3480/6345 -I1/5 -Gt.nc
gmt grdimage t.nc -B -R0/180/3480/6370 -JP15c+z -png map
```

(t.nc _y_-range is 3480 to 6345) to get

![map](https://user-images.githubusercontent.com/26473567/75102032-c1967e00-5588-11ea-9b3b-fefef37dd8ab.png)

**Problem 3:** The y-coordinates in an Earth crossection grid needs to be radial distances.  Not nice, and we have no simple method to switch that around.

Summary: Seems like a few things are missing to make this much simpler:

Specifying the radius of the sphere. We have to convert from depth positive down to radius and the max radius is needed. GMT knows about that value per PROJ_ELLIPSOID (in meters), so we should not have to specify it.  But we may need to tell GMT to do the flip since we cannot tell if 2000/3000 is depth or radial range.  Having that info will allow us to flip the grid from depth to radius.
Seems like the +z modifier to **-JP** could perhaps take that max radius and if given then we should automatically flip things.  E.g., `gmt grdimage slice.nc -B -JP15c+z6370 -png map` should

1. Take the depth range from the grid (25 to 2890) and convert to radial extent.
2. Flip the grids y-coordinates internally via _r = 6370 - z_.

Other planetary bodies have different radii. As a shorthand we could use **+zr** to pick the radius from the selected GMT ellipsoid but then we need a way pick meters vs km.  Perhaps this is obvious from the grid range or given **-R** so we can tell without needing any extra modifiers. One concern is **-JP** also has a **+r** modifier so **+zr** may be subject to confusion.  Perhaps **+z**[**f**[_radius_]] to maintain backwards compatibility: **+z** works as now (as above), **+zf** would **flip** using the current ellipsoid radius, and **+zf**_radius_ would use the given _radius_. Finally, when flip is activated we expect **-R** to be in depth, not radial distances.

**Comment by joa-quim** [comment]
I wonder if it wouldn't be better to introduce another projection, **-JPp** (*p*lanet) and move the new features to it. Would make both **-JP** and **-JPp** simpler to use/explain.

**Comment by PaulWessel** [comment]
Hm, that is true.  So **-JPp**_width[_/_radius_] or **-Jpp**_scale_[/_radius_].  If no _radius_ given then we use the one for the current ellipsoid and figure out (via **-R** or grid) if we should use m or km?  Only thing this is useful for non-planets too, just when it makes sense to measure distance from the surface inward.   We have **-JPa** already to say _theta_ is azimuths.  As you see above, we may need that ability as well, so now we would need to turn a into a modifier for -JPp?  Getting messy, so perhaps my initial proposal is better?

**Comment by joa-quim** [comment]
I was trying to avoid that *flip* option. I think it's a bit confusing to understand when not in a planetary context. And here, the flipping would be the default (and thus needing a modifier to revert it).
We could make [a] a modifier too in **-JP**.
Don't know, but still seem that isolating the radial planetary on its own makes things simpler.

**Comment by PaulWessel** [comment]
I understand. We want something that uses depth positive down versus radius positive out for a polar cylindrical projection.  I think that may be useful even if not dealing with planets.  The **a** in **-Jpa** is ancient and not how we should do things (we should use modifiers).  In fact, we should replace the a with **+a** (backwards compatible; I must have missed this one earlier in my reformation).  That sort of eliminates the need for a new projection but might make it clearer to document.  Sorry, have to run now, more later, but

**-JP**_width_[**+a**][**+o**_origin_][**+r**|**z**[_radius_]]

addresses all those needs I think, using modern modifier syntax.

**Comment by PaulWessel** [comment]
Specifically, for my case above (N pole view) I would need `-JP15c+zr `only and the y-coordinates in the grids are too small to be meters, so GMT supplies 6371 as the missing radius.  Seems OK and not too complicated to me as long as our -JP documentation is improved.  Does @seisman think two separate but almost similar projections are better than upgrading **-JP** to use modifiers only and no funny **a** or **p** etc. needed.

PS. I just edited my previous comment since in order to be backwards compatible we need to distinguish plain **+z** (current syntax) from the radius-to-depth flipping that **+z**_radius_|**r** would imply.

**Comment by seisman** [comment]
I prefer the new **-JP** syntax with modifiers, but I'm a little confused with the difference of **+r** and **+z**.

Why does the command below give R from 0 to 50?
```
gmt basemap -R0/180/20/70 -B -JP15c+z -png map
```
![image](https://user-images.githubusercontent.com/3974108/75124816-9d699880-567f-11ea-85a6-a54e609ee139.png)

And this command plots R from 20 to 70.
```
gmt basemap -R0/180/20/70 -B -JP15c+r -png map
```
![image](https://user-images.githubusercontent.com/3974108/75124846-c722bf80-567f-11ea-9fb3-373588b8dc37.png)

**Comment by PaulWessel** [comment]
Because r = 0 is always at the center, so you get a donut half starting at r = 20 to r = 70.  The +r has to do with angular measurements.

**Comment by seisman** [comment]
What about my first example? Why r is annotated from 0 to 50, not 20 to 70?

**Comment by PaulWessel** [comment]
Not sure, will have to look at the **+r** stuff and rediscover what it was about.

**Comment by PaulWessel** [comment]
Looking at this some more in order to implement the new feature.  Testing the existing scheme I ran `gmt basemap -R0/180/3480/6371 -JP6i+z -Baf -png map` and got this plot:

![map](https://user-images.githubusercontent.com/26473567/75199831-3a701400-5708-11ea-8dd9-2ed588548465.png)

Without **+z** we would have radial _r_ annotations starting around 3480 on the inner circle ending at 6371 on the outer circle.  The **+z** computes _z = north - r_ and annotates _z_ at the _r_ locations.  So it is hardwired to use whatever _north_ value you give in **-R** to do this conversion.  We want the new extension **+zr**|_radius_ to do two things:

1. Use _radius_ instead of _north_ in the equation (if given **r**, look up _radius_ from current ellipsoid)
2. Expect data _y_-coordinates to be _z_-values, not _r_-values.

I think this makes **+z** a poor choice for the new modifier since it really changes what is done and specifically it reverses what **-R** must be.  So I think we should leave **+z** alone for backwards compatibility and instead use a new modifier for the new feature.  As before, I think **+f**[_radius_] is a good choice, standing for flip and optionally accept a fixed radius (otherwise, use the current ellipsoid). However, I can also be convinced to use **+d** (for down), **+i** (for inward), and possibly even **+p** (for planet).

Let me know what @joa-quim and @seisman think about this so we can move on this.

**Comment by PaulWessel** [comment]
Playing with this in branch new-polar-projection.  The 'flip' is very similar to the **+r** but instead of 90-_y_ it is _r-y_.  So I added a variable for _r_ that is 90 if **+r** or _radius_ if **+f**.  If no radius given I pick the current ellipsoidal radius and scale to km if the **-R** is off by a factor of ~1000.  Initial results of running `gmt grdimage slice.nc  -JP6i+f -Bafg -png map` is shown below.  Apart from needing to set the annotation justifications backwardly I think we are close.  It picked up the z-range from the grid, the correct _radius_, and plotted things in the right spots.

![map](https://user-images.githubusercontent.com/26473567/75292366-18d66180-57c8-11ea-968a-b2c827dd79f5.png)

**Comment by PaulWessel** [comment]
To reproduce the above plot, get the data from [here](http://ds.iris.edu/spudservice/data/17996723) then run

`gmt grdinterpolate S362ANI_kmps.nc?vs -E0/0/180/0+i0.25d+g+p -T25/2890/5 -Gslice.nc`

and plot with

`gmt grdimage slice.nc  -JP6i+f -Bafg -png map  --PROJ_ELLIPSOID=sphere`

**Comment by seisman** [comment]
I haven't checked your branch, but note that the -JP syntax was modernized in PR #2620 and #2799, which were merged after the 6.0.0 release. That means we don't need to deal with **+r** **+z** backward compatibility.

**Comment by PaulWessel** [comment]
Yes, the +r and +z was there already.  It is the a -> +a that is new, plus whatever +f we decide on.

**Comment by seisman** [comment]
Your proposal sounds good to me, except that
> If no radius given I pick the current ellipsoidal radius and scale to km if the -R is off by a factor of ~1000.

It assumes that users are plotting crosssections of a planet. It doesn't make sense and sounds nonintuitive to me. **+f** without a _radius_ should flip the radius only.

----

After reading all the discussions above, here I summarize the rules in my mind, which are simpler and more intuitive (at least to me).

1. r=0 is always at the center if no modifiers are appended
2. The **-R** option should always match the range of input data, no matter how the y-coordinates are annotated (either *r_value* or *z_value*)
3. **+f** means *flipping* the radius direction only, thus the r=_north_ is at the center
4. **+f***radius* *flipping* the radius direction and also set the center to r=*radius*.
5. **+z** change the annotations to *north-r*

A few shorthands:

1. **+fr** is equivalent to **+f90**, and also changes _r_ to _elevations_ (i.e. limits _r_ to 0-90, and adds degree symbols to all _r_ annotations). The old **+r** modifier is no longer needed.
2. **+fp** is equivalent to **+f6371**, while 6371 is given by **PROJ_ELLIPSOID**.

---

The script and figure below show how -JP would work following the rules above.
The plots are generated using the old -JP syntax, but the titles show the new -JP syntax. For panels d, f, h, there are two different ways to plot the same figure, depending on the range of the input data.

Scripts:
```
gmt begin polar png
gmt set FONT_TITLE 12p,9

gmt subplot begin 4x4 -Fs10c/10c -A+o-0.5c/-0.5c
gmt basemap -JP? -R0/120/0/60 -Baf -B+t'-JP10c -R0/120/0/60' -c
gmt basemap -JP? -R0/120/30/80 -Baf -B+t'-JP10c -R0/120/30/80' -c
gmt basemap -JP? -R0/120/0/2891 -Baf -B+t'-JP10c -R0/120/0/2891' -c
gmt basemap -JP? -R0/120/3480/6371 -Baf -B+t'-JP10c -R0/120/3480/6371 OR -JP10c+fp+z -R0/120/0/2891' -c

gmt basemap -JP?+z -R0/120/0/60 -Baf -B+t'-JP10c+f -R0/120/0/60' -c
gmt basemap -JP?+z -R0/120/30/80 -Baf -B+t'-JP10c+f80 -R0/120/0/50 OR -JP10c+z -R0/120/30/80' -c
gmt basemap -JP?+z -R0/120/0/2891 -Baf -B+t'-JP10c+f -R0/120/0/2891' -c
gmt basemap -JP?+z -R0/120/3480/6371 -Baf -B+t'-JP10c+fp -R0/120/0/2891 OR -JP10c+z -R0/120/3480/6371' -c

gmt basemap -JP?+r -R0/120/0/60 -Baf -B+t'-JP10c+fr -R0/120/0/60' -c
gmt basemap -JP?+r -R0/120/30/80 -Baf -B+t'-JP10c+fr -R0/120/30/80' -c

gmt subplot end
gmt end show
```

Output:
![image](https://user-images.githubusercontent.com/3974108/75317655-891bcc00-5836-11ea-917e-1a7666a7b568.png)

**Comment by seisman** [comment]
As mentioned above, GMT 6.0.0 is using the old `-JPa<width>/<origin>[r|z]` syntax. So we can choose any characters for the modifiers.

**Comment by PaulWessel** [comment]
Yes, and I have been thinking of being more direct: For elevations, why not **+e** instead of **+r**? And for flipping, why not **+d** for depth instead of **+f**?

**Comment by seisman** [comment]
> And for flipping, why not **+d** for depth instead of **+f**?

**+d** makes sense for planet cross-sections only, while **+f** (flipping) or **+r** (for reverse, not for elevation) is more universal.

> For elevations, why not **+e** instead of **+r**? 

I agree **e** is easier to remember than **r**. As mentioned above, *elevation* is a special case of flipping (limits to 0-90, and annotate with degree symbols), it may be better to use **+fe** (or **+re**).

**Comment by PaulWessel** [comment]
While we are discussing polar, lets consider what is needed to do polar histograms like [this](https://landscapearchaeology.org/2018/polar-diagram/).  Seems to be a radial offset so actual _radius_ = _r * scale + roffset,_ with _roffset_ default being zero. Maybe the word offset, which we are considering as **+o** in angular space, is not so good?.  It is more of a _rotation_ than an _offset_.  So maybe **+r**_rotation_ and **+o**_offset_ could control the angular and radial "offsets", respectively?  With this new syntax we could also decide to make the rotation always CCW instead of depending on **+a**, and maybe under the hood ensure that the plots for **+a** and no **+a** has the same positioning on the page for the same angular offset, and that the only real differences is the positive direction of the angular direction?

**Comment by PaulWessel** [comment]
Strawman proposal for the new syntax:

**-JP**_width_[**+a**][**+f**[**e**|**p**|_radius_]][**+o**_offset_][**+r**_rotation_][**+z**]

1. **+a** switches from CCW angles to CW azimuths. Placement of plot should not change.
2. **+f** flips radial direction. Append **e** for elevations (enforces _y_-range to 0-90 and adds degree symbol), **p** for planetary radius (determined from current ellipsoid in m or km as needed), or a specific radius.
3. **+o** adds a radial offset [0]
4. **+r** adds an angular rotation [0]
5. **+z** annotates _n - r_ instead or _r_

**Comment by seisman** [comment]
The new syntax looks great to me.

**Comment by PaulWessel** [comment]
OK, so I will start with that and a test script that exercises these using the new syntax, and work on getting it all to work.  This will all go into the new-polar-projection branch.

**Comment by joa-quim** [comment]
A somewhat related issue that we already discussed and visible in the histogram page is the ability to annotate along the radial direction. We cannot currently do that for 360 plots.

**Comment by PaulWessel** [comment]
Question regarding **+o** for radial offset (e.g., that histogram above).  Is the offset in the _users_ radial units or is it in _plot_ units? E.g., do we use **+o**2c to get a 4cm radial hole, or do we use **+o**30 and what that is depends on the scale and range.
Seems to me it must be plot units, otherwise we cannot easily control this offset, especially if plotting many such plots on the same page.  If so, then a plot set with -JP12c+o2c will be 12 cm in width (diameter if 360 range) with a 2c radius hole, while -Jp1c+o2c will be 2*(north-south)*1cm in width and a 2c radius hole.

Agreed?

**Comment by seisman** [comment]
I agree. Offset in users radius units can be achieved by -R option like -R0/360/30/100.

**Comment by PaulWessel** [comment]
Small complication: Our projection machinery first projects input (x,y) to unscaled (x', y') and then we do 

```
x = (x - GMT->current.proj.origin[GMT_X]) * GMT->current.proj.i_scale[GMT_X];
y = (y - GMT->current.proj.origin[GMT_Y]) * GMT->current.proj.i_scale[GMT_Y];
```

which is where scaling to plot units comes in.  For us to add a 2c shift to the projected radial value and then break that into x,y components I may have to convert the rad_offset from cm back to the equivalent user r-values so that I can apply the shift in gmt_polar where we have r,theta.  I think it is simply

`rad_offset_user = rad_offset_plot / GMT->current.proj.i_scale[GMT_X];` and then I can use the equation

```
x = (r + rad_offset_user) cos(angle)
y = (r + rad_offset_user) sin(angle)
```

in gmt_polar and gmt_ipolar.  Currently that equation does not have rad_offset_user [0].

**Comment by PaulWessel** [comment]
OK, I think I have completed the implementation of the _mapping_ system for the revised polar projection.  There is still some work to be done on _annotation justification_ stuff, so ignore those bugs for now.  Below is 12 plots (new test subplot/polarcases.sh) which explore those new modifiers.  All the ones with **+f** has radius inwards. Only **+fe** adds degrees.  The **+fp** picks up the planetary radius. Just **+z** simply annotates _z = n - r_ and cannot be used with **+f**.  The plot labeled default in row 2 col 3 uses angles CCW, so angle = 0 is the horizontal (positive x-direction), while if I add **+a** then the azimuth of 90 points straight up (positive y-direction). Before you would have to rotate it to get a sensible layout.  Rotations now behave in the same way in that either (direction-rotation) is due east or (azimuth-rotation) is due north.  The newest feature is the radial offset **+o**.  The last row shows a default plot and then two cases of radial offset.  You can see the radial values are 0-1 in all cases but the last two have taken out a hole first.  Apart from the label justifications, let me know if you agree with what you see.

![polarcases](https://user-images.githubusercontent.com/26473567/75390260-0de50500-588c-11ea-91eb-11dc9630f2f6.png)

**Comment by PaulWessel** [comment]
As for annotation justifications, I have work to do with **+f** (except **+fe**), **+a**, and **+o**.  I will write a new justification setup function for the polar projection instead of sharing with geographic polar projections.  I need @joa-quim and @seisman to vet this plot first, though.

**Comment by seisman** [comment]
Is the panel **7** correct? **+a** means north is 0°, right?

**Comment by PaulWessel** [comment]
**+a** means azimuth of 90 is due north.

**Comment by PaulWessel** [comment]
Sorry, you are right.  We direction = 0 to be x-direction and azimuth = 0 to be north. My bad.  Fixing now.

**Comment by PaulWessel** [comment]
Updated plot.  Yes, the +a was actually correct, and the rotations will be in different directions to ensure that the given rotation angle aligns with the x-directon or y-direction (**+a**).

![polarcases](https://user-images.githubusercontent.com/26473567/75395998-92895080-5897-11ea-9b87-6de6ad871309.png)

**Comment by joa-quim** [comment]
Just in case you haven't noticed it, last panel has a strange labeling issue. The 90º label is overlapping the tick mark.

**Comment by PaulWessel** [comment]
Yep, saw that one too.

**Comment by seisman** [comment]
The command below should report an error, as **+fa** is invalid.
```
gmt basemap -Baf -R0/120/0/60 -JP15c+fa -pdf map
```

**Comment by seisman** [comment]
Here is a use case that the current **-JP** cannot do.

The data range is **-R0/120/0/2891**, but I want to annotate y-coordinate as *radius* like the figure below.
![image](https://user-images.githubusercontent.com/3974108/75399621-b9ad4580-58ca-11ea-87d7-edb74a0e1e93.png)

**Comment by PaulWessel** [comment]
Might this be a case where +z could be a toggle? Of a separate modifier.  So your -R and data would be 0/2891 and you want to use +fp, but flip from annotating z to r.

**Comment by seisman** [comment]
Another option is to allow **+z**[**p**|*radius*], and annotate as *radius* - *r* instead of *north* - *r*.

**Comment by PaulWessel** [comment]
> The command below should report an error, as **+fa** is invalid.
> 
> ```
> gmt basemap -Baf -R0/120/0/60 -JP15c+fa -pdf map
> ```

Not more careful with the parsing.
