### ISSUE TITLE
Fix Proj.4 to PROJ

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2809]
The GMT documentation mention Proj.4 in many places. The [wikipedia page](https://en.wikipedia.org/wiki/PROJ) says:

> With the release of version 5.0 in February 2018, the software was renamed to PROJ, removing 
> version four (".4") from the name. With the acquisition of the proj.org domain name in June 2019, 
> the project was also renamed as PROJ.

We should fix Proj.4 and its variants (e.g. PROJ4, PROJ.4) to PROJ.

**Comment by PaulWessel** [comment]
Any issues with this, @joa-quim ?

**Comment by joa-quim** [comment]
As long as we restrict the changes to the RST files I'm not totally against. I never liked that decision. For instances, all postgis functions and man keep referring to proj4, as well as the [EPSG database](https://spatialreference.org/) but it was taken.

**Comment by seisman** [comment]
Yes, only for the documentations.
