### ISSUE TITLE
Dash vs underscore for URLs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2810]
See https://stackoverflow.com/questions/119312/urls-dash-vs-underscore. Google recommends using dashes in URLs. We should follow the convention and change links like "custom_symbols.html" to "custom-symbols.html".

**Comment by PaulWessel** [comment]
I have no strong feelings about this, but note we have generic-mapping-tools as our top URL so makes sense to use dashes below as well.

**Comment by joa-quim** [comment]
> "custom_symbols.html" to "custom-symbols.html".

Why changing? To please a Google recommendation?
Sorry, but I think we have other more important things where to focus our attention.

**Comment by seisman** [comment]
Just make it consistent throughout the whole documentation. Anyway, it should take only minutes to do the changes.

**Comment by PaulWessel** [comment]
Just do it, not many pages anyway.
