### ISSUE TITLE
Option -c is not recognized in one-liner commands

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2812]
Example command:
```
$ gmt basemap -Baf -R0/120/0/60 -JP15c -c -png map
basemap [ERROR]: Option -c is not a recognized common option
```

**-c** doesn't make sense in one-liner commands. The command should either ignore **-c** silently, or report that **-c** is not allowed in one-liners. I prefer the latter.

**Comment by PaulWessel** [comment]
Fixed, but in new-polar-projection...

**Comment by seisman** [comment]
Confirmed. Closing.
