### ISSUE TITLE
'_tcslen' undefined in Windows build

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2814]
The Windows CI reports an warning:
```
..\src\gmt_support.c(14907): warning C4013: '_tcslen' undefined; assuming extern returning int
```
probably because we forgot to include the header file `tchar.h` somewhere.

**Comment by seisman** [comment]
Ping @joa-quim

**Comment by seisman** [comment]
I'm not sure where to put the `#include <tchar.h>` for Windows.

**Comment by PaulWessel** [comment]
Why not just add a
```
#ifdef WIN32
#include <tchar.h>
#endif
```
right at the top of that function?

**Comment by joa-quim** [comment]
I that error was really true  we would get a linking error due to a missing symbol. I think this is simply an harmless warning.

**Comment by seisman** [comment]
It seems `_tcslen` is a macro.
> The headers for the Microsoft C run-time libraries define a similar set of macros. For example, _tcslen resolves to strlen if _UNICODE is undefined; otherwise it resolves to wcslen, which is the wide-character version of strlen.

See https://docs.microsoft.com/en-us/windows/win32/learnwin32/working-with-strings.
