### ISSUE TITLE
Improve the documentation of GMT map projections

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2815]
GMT map projections are documented in three separate places.

1. The [table of all map projections](https://docs.generic-mapping-tools.org/latest/proj_codes.html) provides a quick view of all GMT map projections. It's pretty useful if users want to use a specific projection but don't remember the projection code. 
2. The [-J description in the gmt manpage]( https://docs.generic-mapping-tools.org/latest/gmt.html#the-common-gmt-options) shows map projection parameters and also explains their meanings.
3. The ["Map Projections" chapter in the cookbook](https://docs.generic-mapping-tools.org/latest/cookbook/map_projections.html): This chapter provides more details of map projections, and also provides maps showing what the projections look like. However, this chapter doesn't show the full syntax of map projections. For example, the **-Jb** section says 
``` 
To define the projection in GMT you need to provide the following information:
- Longitude and latitude of the projection center.
- Two standard parallels.
- Map scale in inch/degree or 1:xxxxx notation (-Jb), or map width (-JB).
```
but it's not clear which parameters are optional.

Usually, I have to look through all the maps in the cookbook, find the one I need, remember its projection code, and then go the gmt manpage or the quick-view table to check which parameters are required.

Here are suggestions to improve the documentation:

1. Decide the style to describe projection syntax (see #2267)
2. In "Map Projection" chapter of the cookbook, add the map projection syntax at the beginning ot each section. The structure of each section thus look like:
    ```
    Albers conic equal-area projection (-Jb -JB)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    The full syntax of the map projection is:

    -Jblon0/lat0/lat1/lat2/scale or -JBlon0/lat0/lat1/lat2/width
    
    - lon0 is ...
    - lat0 is ...

    More details about the projection.
    The projection is developed by xxx, and mostly used for large regions. 
   
    Here is an example.
    
   Example command.

   Example figure. 
    ```
3. The **-J description in the gmt manpage** may be shortened by only including the quick-view table.

**Comment by meghanrjones** [comment]
In preparation for consolidating the source ReST files for the manpage and cookbook common options, I would like to create a PR with the proposed changes, with the exception of adding the table [to cookbook section 4.2](https://docs.generic-mapping-tools.org/dev/cookbook/options.html#coordinate-transformations-and-map-projections-the-j-option) rather than in the **-J** description in the gmt manpage and linking from the table to the appropriate sections of chapters 5 and 6 rather than the sections of the gmt manpage. Is that OK with you, @seisman?

**Comment by seisman** [comment]
Sounds good to me.
