### ISSUE TITLE
Literally include one-liner scripts in the cookbook

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2824]
**Description of the desired feature**

In the [Map Projections](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html) chapter of the cookbook, some maps are generated by one-liner scripts in the `doc/scripts` directory. These one-liner scripts use `-ps` to generate PS files for testing purposes. However, we want to show `-pdf` in our cookbook, thus we can't literally include them in the cookbook.

Since all scripts are converted to txt files by script2verbatim, I think we can update script2verbatim.c to allow it to replace `-ps` with `-pdf` during the conversion.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Yes, that should be pretty simple to do.
