### ISSUE TITLE
Annotate longitudes or radial values for closed maps

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2844]
**Description of the desired feature**

There are two situations where GMT will not annotate an axis:

1. Polar projections where the longitude range or angular range is 360.  Consider `gmt basemap -JP6i -R0/360/0/10 -Bafg -png map1` shown below:

![map1](https://user-images.githubusercontent.com/26473567/75826579-e12d6380-5d4b-11ea-9b42-5d544a2af48e.png)

There are no annotation for the radial extent, so there is no way of knowing what the boundaries are on radius.  Cheating doing `gmt basemap -JP6i -R0/359.999/0/10 -Bafg -BWeSN -png map2` I can get this:

![map2](https://user-images.githubusercontent.com/26473567/75827214-3c138a80-5d4d-11ea-9bf7-62e2b54d40ac.png)

which draws the W axis and not the E, and nobody can tell we did not do 360 degrees.  Yet, the maximum radius prints on top of the boundary. However, this trick works poorly for geographic polar maps such as `gmt basemap -JA0/90/6i -R0/359.999/60/90 -Bafg -BWeSN -png map3` due to the fancy frame type chosen by default:

![map3](https://user-images.githubusercontent.com/26473567/75826799-687ad700-5d4c-11ea-8ca4-16fee9c266bc.png)

2. Global geographic maps that cover all latitudes.  Consider `gmt basemap -Rd -JH0/6i -Bafg -png map4`:

![map4](https://user-images.githubusercontent.com/26473567/75826893-96f8b200-5d4c-11ea-9217-8a41b96c2f1b.png)

Unlike the polar plot above, we at least know that longitudes cover a 360 range, but we cannot tell what the central longitude is here.  Awkward workarounds would include attempts like

```
gmt begin map5 png
	gmt basemap -Rd -JH0/6i -Bafg30
	gmt math -T-150/150/30 -N3/0 -C2 T = | gmt text -F+f10p -Gwhite
gmt end show
```
yielding

![map5](https://user-images.githubusercontent.com/26473567/75827119-08386500-5d4d-11ea-8396-a303c8c31591.png)

This is clearly not a user-friendly solution, and more elbow-grease is needed to add degree symbols.  We need to allow these two types of annotations.

**My proposal is as follows:**

Add a new modifier **+e**[_arg_] to **-B** that, for the above cases only, adds annotations as indicated above.  For polar projection the arg is the angle of the radius [0] while for global projections it can be the latitude along which to place longitude annotations [0].

**Comment by joa-quim** [comment]
Didn't get the polar case. We want annotations to go from ``> r_min`` to ``< r_max``

**Comment by PaulWessel** [comment]
Yes, we want >= r_min to < r_max but which radius you annotate (i.e., angle) can be selected via the _arg_.

**Comment by joa-quim** [comment]
Ah, I see.

**Comment by PaulWessel** [comment]
Any preference for **+e** for "extra annotations" or **+i** for "internal annotations", or do any of you think we should give separate modifiers for the meriodinal vs parallel annotations?  E.g., **+m**lon to draw those radial or latitude annotations along _lon_ (e.g., along a meridian), and **+p**_lat_ for annotations of longitude (or angle) along a parallel (or radius) _lat_?

**Comment by joa-quim** [comment]
**+m** and **+p** seem more comprehensible.

**Comment by PaulWessel** [comment]
Being plotted inside the map frame, should we offer support of plotting white or colored boxes behind these annotations (i.e., like in `text -Gwhite`)?  If you are plotting a colormap then annotating on top in black may be hard or impossible to see, and if you are drawing gridlines they will go right through these annotations.

**Comment by seisman** [comment]
> Being plotted inside the map frame, should we offer support of plotting white or colored boxes behind these annotations (i.e., like in `text -Gwhite`)? If you are plotting a colormap then annotating on top in black may be hard or impossible to see, and if you are drawing gridlines they will go right through these annotations.

I can see it's useful, but the **-B** option is already too long and complicated now.

**Comment by PaulWessel** [comment]
I will leave clipping or painting off for now.  These are very specialized cases anyway.

**Comment by PaulWessel** [comment]
Second pass through, I think we should **not** use **+p** for parallel since **+p** is used by the **-B** axes modifiers for annotation prefix.  Given this will be an infrequently used option, perhaps we should simply have one as initially suggested.  I think **+i**[_val_] for internal annotation is as good as any, no?

**Comment by seisman** [comment]
Looks OK to me. It also saves one modifier.

**Comment by joa-quim** [comment]
But the **+i** alone cannot do what **+p** & **+m** were meant to do. no?
And, at this point of multi-multi options, we should not worry anymore if a character is mnemonic. No one remembers options+flags anymore. Specially in **-B**

**Comment by PaulWessel** [comment]
Yes, **+i** can do that because it is an either/or case: Either you have an azimuthal map and you want to annotate latitudes/radius along a meridian, **or** you have a global map and you want to annotate longitudes along a parallel.

**Comment by PaulWessel** [comment]
Unless you want to actually do both...  The issue above was not so much about mnemonic than avoiding two +p.  We could do +x and +y instead, for instance, if you think we should retain the possibility of two internal annotions.

**Comment by joa-quim** [comment]
No, I think one internal annotation is enough (we didn't have any during 30 years)

**Comment by PaulWessel** [comment]
Implemented.
