### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GenericMappingTools/gmt#287]
I would like to point out that identifiers like “[`_COMMON_MATH_H`](https://github.com/GenericMappingTools/gmt/blob/3344c5786a94e0edb1902e3c44f6f29967a038a0/src/common_math.h#L31 "Update candidate")” and “[`_GMT_H`](https://github.com/GenericMappingTools/gmt/blob/650e821a9b238ed19bf245b262822c9c68053905/src/gmt.h#L34 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by PaulWessel** [comment]
We do strive to follow the C standard.  What is the issues and what do you propose?

**Comment by joa-quim** [comment]
I think the issue is the leading underscore. Those identifiers should be renamed to ``COMMON_MATH_H`` and ``GMT_H``

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by PaulWessel** [comment]
Well, we would like to avoid that.  Do you have an example where we fall into that trap?

**Comment by elfring** [comment]
Would you like to change any more source code places besides the mentioned affected include guards?

**Comment by PaulWessel** [comment]
You are being too indirect about all of this.  If you have specific recommendations or a commit you wish for us to consider then please do, but your comments (and I may of course be wrong) is starting to sound like a build up to a sales pitch.

**Comment by seisman** [comment]
@PaulWessel He looks like a bot. He has opened so many similar issues in other projects and his comments are almost the same for all the issues.

**Comment by PaulWessel** [comment]
Right, I was telling @joa-quim the same thing!

**Comment by elfring** [comment]
Do you find [recommendations from secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/SEI+CERT+C+Coding+Standard "SEI CERT C Coding Standard") harder to apply than expected?

**Comment by PaulWessel** [comment]
Thanks for playing @elfring, life goes on.

**Comment by joa-quim** [comment]
But we can still address its first point about the leading underscores.

**Comment by PaulWessel** [comment]
Yes I agree, after we slant our way back to master.
