### ISSUE TITLE
Support asymmetrical grid ticks as in navigational charts

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2875]
**Description of the desired feature**

Currently GMT plots symmetric crosses.  For navigational charts it is customary to for meridians to have asymmetrical ticks that point away from Greenwich and for parallels to have have ticks pointing away from Equator.  That way, users know from tick orientation what hemisphere they are in.  See Discourse forum [discussion](https://forum.generic-mapping-tools.org/t/asymmetric-grid-tick-marks/291) for context.

I suggest this can be implemented by letting **MAP_GRID_CROSS_SIZE_PRIMARY**|**SECONDARY** accept a _negative_ size.  Then, we implement the above, else for positive sizes we do symmetric crosses.  For zero we instead do gridlines.

**Comment by KristofKoch** [comment]
Wow, that was quick. I'll give it a try when I solved my problem with [installing GMT from source on MacOS](https://forum.generic-mapping-tools.org/t/install-gmt-from-source-on-macos-cmakelists-txt/292).

**Comment by KristofKoch** [comment]
Already mentioned in #2877 but to keep things in order:

0°/180° longitude and 0° latitude remain symmetrical with all ticks extending on both sides of the grid line. See below example taken from ONC M-2:

![onc_m-2](https://user-images.githubusercontent.com/45796239/76698702-c396bd00-66ae-11ea-8958-7a6f01f9be70.jpg)

**Comment by seisman** [comment]
Closed by #2877.
