### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [GenericMappingTools/gmt#288]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [get_data](https://github.com/GenericMappingTools/gmt/blob/3344c5786a94e0edb1902e3c44f6f29967a038a0/src/gmt_ogrread.c#L128)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [parse](https://github.com/GenericMappingTools/gmt/blob/3344c5786a94e0edb1902e3c44f6f29967a038a0/src/gmtread.c#L101)

**Comment by PaulWessel** [comment]
For the malloc in get_data; yes that could return NULL if too large and not enough member.  For the strdups we decided it is not worth it to convolute the code checking for NULL here since we use this to just duplicate a tiny handful of byes.  Extremely unlikely that these calls will return NULL.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by PaulWessel** [comment]
I agree that should be the goal of course.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by joa-quim** [comment]
We do use [coverity ](https://scan.coverity.com/projects/gmt) analysis

**Comment by elfring** [comment]
Does [this tool](https://scan.coverity.com/projects/gmt "Source code analysis by Coverity") point also the mentioned update candidates out since an analysis was performed for your software on 2018-07-02?

**Comment by PaulWessel** [comment]
I think @joa-quim needs to replace those sloppy malloc calls with proper gmt_M_memory calls in gmt_ogrread.c.
