### ISSUE TITLE
Let tests detect failure of ghostscript conversion

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2897]
**Description of the desired feature**

We have suffered through a long series of ghostscript updates and bugs the last couple of years.  Apparently, the **ghostscript** team does not have a good system of testing that their changes are not breaking things that work.  Recently, they released version 9.51 and at first go it seems fine, but then we learned that the transparency feature is broken.  Our tests do not actually look for that (it compares an original and a newly created PostScript plot via conversion to PNG and pixel-wise comparison, but that conversion does not honor transparency anyway).

Since we know when **ghostscript** gets updated, there is no reason to include this type of check in our standard tests. However, it would help prevent the release of a broken **ghostscript**.  Perhaps a simple script in admin we can run as needed that will create two identical plots except one has transparency, then convert those to PNG with psconvert and then use gmt compare?

**Comment by seisman** [comment]
It sounds a good idea to me.

**Comment by seisman** [comment]
Closed by #2905.
