### ISSUE TITLE
Check status of ghostscript before releasing 6.1.0

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2903]
Once again a **ghostscript** release (9.51) comes with bugs affecting GMT, in this case a loss of transparency.  The problem has already been [reported](https://bugs.ghostscript.com/show_bug.cgi?id=702219) and hopefully distributions will get a patch or there will be a 9.52 soon.  Whatever the situation is, when GMT 6.1.0 is released we may need to warn against 9.51 or add a warning in **psconvert** when users request transparency.

A secondary issue in 9.51 was the unannounced breaking of backwards compatibility by now requiring the option [-dALLOWPSTRANAPARENCY](https://www.ghostscript.com/doc/9.51/Use.htm) to activate the PDF transparency machinery.  GMT enabled this in #2902 but due to the above bug it has no effect yet.

**Comment by joa-quim** [comment]
I can see transparency directly on the PS files when using the, now abandoned by Artifex, gsview6.0.

**Comment by PaulWessel** [comment]
(.52 has been released but apparently not addressing the bug in transparency reported above.

**Comment by PaulWessel** [comment]
Update: Per Chris Liddel, next gs 9.53 is slated for September.  They do one very 6 months apparently.  So 9.50 for a while for us.

**Comment by remkos** [comment]
Have you tried the solution that is posted on the ghostscript website, i.e. using -dALLOWPSTRANSPARENCY ?
See: https://www.ghostscript.com/doc/9.52/News.htm (Section 1.1.)
And: https://www.ghostscript.com/doc/9.52/Use.htm#ALLOWPSTRANSPARENCY

Although, reading https://www.ghostscript.com/doc/9.52/Language.htm#Transparency, I'm not so certain this will do it.

**Comment by PaulWessel** [comment]
Thanks @remkos for checking.  We will probably need to look at the transparency setup more carefully going forward, but plate is full right now....

**Comment by seisman** [comment]
FYI, ghostscript 9.53 is released.

**Comment by seisman** [comment]
One of the biggest changes is that the ghostscript version is 9.53.0, not 9.53. It may break some codes.

**Comment by PaulWessel** [comment]
I think we only check gs --version output in psconvert where we take the string returned and do this:

`		int n = sscanf (cmd, "%d.%d", &gsVersion.major, &gsVersion.minor);`

If the string "9.53.0" is given I think (because of %d) that we still will return 53 and the ".0" is not used.  We should add a &gsVersion.patch entry going forward and if we get 3 or 2 it does not matter.  I guess once we install 9.53.0 we will know if this causes any problems.

**Comment by joa-quim** [comment]
Windows installer is already using pre-9.53.0, which because it was built from master claims to be 9.54.0

**Comment by seisman** [comment]
I installed gs 9.53.0 on macOS via homebrew. It works perfectly for me, although it gives me annoying warnings for transparent figures:
```
   **** WARNING: .setopacityalpha is deprecated (as of 9.53.0) and will be removed in a future release
   **** See .setfillconstantalpha/.setalphaisshape for the improved solution
```

In the Windows CI, we install Ghostscript from [Chocolatey](https://chocolatey.org/packages/Ghostscript). It used to work fine, but after updating to gs 9.53.0, GMT can't find gs anymore:
```
psconvert [ERROR]: Cannot execute Ghostscript (gswin64c).
end [ERROR]: Failed to call psconvert
end [ERROR]: gmtinit_process_figures returned error 78
```

**Comment by PaulWessel** [comment]
I guess we will have to implement the new scheme under a version if-test...

**Comment by seisman** [comment]
I suspect that the new gs 9.53.0 installer doesn't modify the Windows registry or use a different name, thus GMT fails to find it.

**Comment by joa-quim** [comment]
Yes, we have this
>	if (psconvert_ghostbuster(GMT->parent, C) != GMT_NOERROR)  /* Try first to find the gspath from registry */
		C->G.file = strdup ("gswin64c");     /* Fall back to this default and expect a miracle */

But no miracle expected anymore on 64 bits systems because we now ship a ``gswin64c`` in the installer.
If Artifex changed the registry key they would break all softs that depend on ghostcript.

**Comment by seisman** [comment]
> But no miracle expected anymore on 64 bits systems because we now ship a `gswin64c` in the installer.

It doesn't help solve the problem in the Window CI.

For Chinese users who want to typeset Chinese characters in GMT, the gswin64c shipped in the installer doesn't work due to the lack of some CJK configurations files, so they still have to install the official ghostscript.

> If Artifex changed the registry key they would break all softs that depend on ghostcript.

I asked @sqdeng to try ghostscript 9.53.0 and report some details. When he installed GMT 6, he didn't choose the builtin ghostscript component, and he installed ghostscript 9.26, which works fine. 

He then uninstalled gs 9.26, and installed gs 9.53.0. Here are the error messages:
```
end [DEBUG]: gmtlib_get_graphics_item: Fig: 0 Subplot: 2 Panel: () Inset: 0
end [DEBUG]: psconvert: 'C:/Users/sqdeng/.gmt/sessions/gmt_session.11968/gmt_0.ps-' -Tg -Fmag_hist -A
end [DEBUG]: GMT now running in modern mode [Session ID = 11968]
end [DEBUG]: Revised options: 'C:/Users/sqdeng/.gmt/sessions/gmt_session.11968/gmt_0.ps-' -Tg -Fmag_hist -A
end (gmtlib_free_tmp_arrays): tried to free unallocated memory
psconvert [DEBUG]: Ghostscript not found in registry. Fallback to PATH.
psconvert [DEBUG]: gmt_check_executable: Pass to popen: [gswin64c --version 2> NUL]
psconvert [DEBUG]: gswin64c --version 2> NUL failed
psconvert [ERROR]: Cannot execute Ghostscript (gswin64c).
psconvert (gmtlib_free_tmp_arrays): tried to free unallocated memory
end [ERROR]: Failed to call psconvert
end [ERROR]: gmtinit_process_figures returned error 78
```
Obviously, GMT can't find the newly installed gs 9.53.0 in the registry.

This is the screenshot of the Windows registry for gs 9.53.0:
![image](https://user-images.githubusercontent.com/3974108/93161421-856f6a00-f6e0-11ea-92b9-2cdb2aa08ebc.png)

This is the screenshot of Windows registry for gs 9.26 (he renamed the old gs 9.26 registry to "**aaaaa**"):
![image](https://user-images.githubusercontent.com/3974108/93161435-8c967800-f6e0-11ea-90b0-625053cb4b62.png)

Does anything seem weird to you?

**Comment by joa-quim** [comment]
That's not what I have. It misses the GS_DLL key that stores the dll location.

![image](https://user-images.githubusercontent.com/537321/93227597-7209e080-f76c-11ea-8438-165f54782ffd.png)

**Comment by seisman** [comment]
FYI, ghostscript just released a patch version 9.53.1 yesterday. Will try and report later.

**Comment by seisman** [comment]
I just installed ghostscript 9.53.1 in a Windows 10 Virtual Machine environment. Here is the registry for gs:

![image](https://user-images.githubusercontent.com/3974108/93291633-9a67fe00-f7b1-11ea-80fc-04475e019da8.png)

It looks normal to me, but GMT (again, I don't choose the build-in gs when installing GMT) still can't find it in the registry.

![image](https://user-images.githubusercontent.com/3974108/93291689-c4212500-f7b1-11ea-8cf6-303012f0c7f1.png)

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/blob/d3d64d0027263892efd88e9b23c4d40e167a2a98/src/psconvert.c#L2767-L2768

I can't say that I fully understand the codes, but it seems the codes assume the ghostscript version is a "float"-like value, e.g., 9.53, but ghostscript now uses 9.53.1. It may explain why GMT can't find the registry.

**Comment by joa-quim** [comment]
Yes, they f it up when they changed the format of that registry key. Please try #4223 
But note that for the Chinese users they will need to remove the ``gswin64c.exe`` (and dll) that we ship because it will be picked first even checking the registry. This is not ideal. The best is that we provide also the missing files.

**Comment by seisman** [comment]
It seems we can close the issue as gs 9.53.3 was released a few months ago and works well with GMT.
