### ISSUE TITLE
The +m|M modifiers to greenspline -C

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2909]
**Description of the desired feature**

There are now two modules that would like to write a 3-D netCDF data cube: **greenspline** and **grdinterpolate**.  Here, **greenspline** can do 3-D Cartesian interpolation via Green's functions but is limited to dumping the result as a stack of 2-D grids - which is what **grdinterpolate** currently must do as well. @joa-quim writes 3-D netCDF cubes in a separate program (tsunami simulation) and I can use that as a template.  Here is my plan of attack, plus some questions:

Currently, the two modules have their own loop over the layers and writing 2-D grids.  I want to replace this with a single call to _gmt_write_nc_cube_ (an existing but unused function to be worked on further) which can either write the same stack as individual grids (current status) or as a single cube.  This capability will simplify the code in the modules in that I can do this in two stages: Simplify the modules to use _gmt_write_nc_cube_ to write the stack, and later improve _gmt_write_nc_cube_ to actually write a cube.  Passing a filename with a C-format stub for the level leads to the stack, else a cube.

Looking at **greenspline** I rediscovered some undocumented features that we use to examine the effect of _eigenvalues_.  The full but undocumented syntax is **-C**[**n**]_val_[**+f**_file_][**+m**|**M**].  The undocumented part is [**+m**|**M**].  The **-C** option docs says this:

```
-C Solve by SVD and eliminate eigenvalues whose ratio to largest eigenvalue is less than <val> [0].
     Optionally append +f<filename> to save the eigenvalues to this file.
     A negative cutoff will stop execution after saving the eigenvalues.
     Use -Cn to select only the largest <val> eigenvalues [all].
     [Default uses Gauss-Jordan elimination to solve the linear system]
```

The undocumented modifiers are only meant for 2-D gridding and will loop over all eigenvalues and write a grid for either the contribution for that eigenvalue only (**+m**) or for the cumulative result up to and including the contribution from that eigenvalue (**+M**).  One can then make a movie and examine  the contributions that way.  I also point out that our animation 05 is making a movie like that but it is _not_ using this modifier and thus calling **greenspline** lots of time in the main loop.  It would be much faster to call **greenspline** _once_ with **+M** and then animate the stack of grids.  Anyway, this brings me to my proposals/questions:

1. We should document these modifiers as they are generally useful for anyone trying to determine the effect of their choices on eigenvalues, or anyone studying orthogonal components.
2. The resulting stack of grids should also be written as a single 3-D data cube. I think it is way better to write a single cube than hundreds of grids cluttering the directory, so this should not be a user choice.  GMT has had the ability to read individual layers for a decade or more.

Thoughts, @joa-quim and @seisman?

**Comment by PaulWessel** [comment]
Here is a related but secondary and slightly futuristic issue (to be tackled after funding appears): External tools that wish to do 3-D gridding and resampling like this (this is GMT/MATLAB syntax) cannot do so:

```
cube = gmt ('greenspline', -R0/10/0/10/0/10 -I0.1 -D5', xyzw_data);
new_cube = gmt ('grdinterpolate', '-T0/10/0.1', cube);
```

The reason is we have no representation of a 3-D grid in GMT. Might this be a possible solution:

- _GMT_Create_Data_: if GMT_IS_GRID, examine dim[GMT_Z] for layers or range, inc for z-range and increments, but only if GMT_IS_CUBE is added to the input mode. If allocating data we allocate n grid layers.
- Add new hidden grid header parameters _n_layers_ to store the number of layers and double *_layer_ for the layer value, and a _type_ parameter for what type that dimension is (float, time).
- Introduce new macros _gmt_M_ijkp_ and _gmt_M_ijkp0_ that take the 3rd index of _k_ for layer.  With these, modules needing to access points in a cube can find the index.  The current _GMT_M_ijp_ etc. macros are basically versions of these called with _k_ = 0.
- _GMT_Read_Data_: If input grid is 3-D netCDF and no layer is selected, read in the entire cube into the grid structure and set the above-mentioned parameters.
- _GMT_Write_Data_: If output grid is 3-D and _filename_ does not contain %, write the cube, else write the individual layer grids.

This ability would simplify those modules dealing with cubes and could enable new modules or features that would be easier to do with a single 3-D grid than a stack of 2-D grids.

**Comment by PaulWessel** [comment]
FYI, the two modules now must read the 3-D cube into an array of 2-D grids.  This was the only way to make things work, but if _GMT_Read_Grid_ was aware of 3-D and could return what I describe above then I could in a module loop over the layers set `this_layer_z = &Grid->data[gmt_M_ijk0(0,0,k)];` and work on that 2-D array.

**Comment by PaulWessel** [comment]
Update: The 3-D grid read/write is now addressed separately in #2912, so please just focus on the first part of this feature request.

**Comment by PaulWessel** [comment]
I will implement the first task listed above:

1. We should document these modifiers (**+m** and **+M**) in greenspline as they are generally useful for anyone trying to determine the effect of their choices on eigenvalues, or anyone studying orthogonal components.

Any objections to this gentle step,  @joa-quim and @seisman ?

**Comment by seisman** [comment]
Good to me.

**Comment by joa-quim** [comment]
I guess yes.
