### ISSUE TITLE
Convert PostScript directly to PNG, JPEG et al.

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2911]
I guess we may need to research the PDF 1.4 specifications.  They are using odd things like .pushpdf14devicefilter and .setopacityalpha, etc.  We would need to study [their docs](https://www.ghostscript.com/doc/current/Language.htm#Additional_operators) and replace the PostScript commands our _PSL_settransparency_ and _PSL_settransparencymode_ functions produce.  If this allows transparent PNG directly from PS then we should do this instead of wasting CPU on making an intermediary PDF file.

_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/gmt/pull/2902#issuecomment-599159040_

**Comment by seisman** [comment]
We actually do deal a bit with this.  Our definition of PSL_trans is

```
/PSL_transp {						% Set transparency
  /.setopacityalpha where {pop .setblendmode .setopacityalpha}{		% Using ghostscript
  /pdfmark where {pop [ /BM exch /CA exch dup /ca exch /SetTransparency pdfmark}	% Or Adobe
  {pop pop} ifelse} ifelse				% Or skip if neither are supported
```
}!

So depending on what tools is processing our PS (Adobe Distiller or ghostscript) we try to issue the right transparency lingo.  But we are not adding some of those things mentioned above.

Originally posted by @PaulWessel in #2902

**Comment by PaulWessel** [comment]
I have experimented by examining the intermediate commands used to build the PDF before converting to PNG and I cannot get our intermediate EPS file to convert directly to PNG **and** show transparency.  I think the transparency machinery **only** works to make PDF (which is what it says) and we must go via PDF to get transparent PNGs.  I think we can close this issue, no @seisman?
