### ISSUE TITLE
EXTRA_MODULES_SUPPL doesn't work as documented

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2917]
The `cmake/ConfigUserAdvanced.cmake` file documents that the variable contains a list of C codes.

https://github.com/GenericMappingTools/gmt/blob/758119cee25740c7f2cdc43437b7b9c7c697e189/cmake/ConfigUserAdvancedTemplate.cmake#L202-L203

But, in the `src/CMakeLists.txt`, the variable is used in the other way. The `include` directive in CMake expects to load and run a CMake script rather than a C code.

https://github.com/GenericMappingTools/gmt/blob/758119cee25740c7f2cdc43437b7b9c7c697e189/src/CMakeLists.txt#L489-L495

We have another three cmake variables:
- **EXTRA_MODULES**: list of C codes to be included into GMT's core modules. Works as documented.
- **EXTRA_BUILD_DIRS**: list of directories with a CMakeLists.txt file, just like seis. The codes in the directories will be added as GMT's supplemental modules.
- **EXTRA_INCLUDE_NEWSUPPL**: the variable is not documented.

**Comment by PaulWessel** [comment]
We should revise these things.  For most new modules we usually do a branch anyway until it is ready to merge, so EXTRA_MODULES is not that useful.  What I think would be useful is this:

**EXTRA_BUILD_DIRS**: directories with CMakeLists.txt like other supplements but these should build a separate project.so file, one per subdirectory.  This would simplify how other developers can leverage GMT to build new supplements without having to manage their own build system.

Only our supplements should end up in supplements.so; the rest should be individual shared libraries.

**Comment by seisman** [comment]
@joa-quim, I think some of the variables are used in your mbsystem plugin, right?

**Comment by joa-quim** [comment]
The ones I need for MB are: ``EXTRA_MODULES_SUPPL`` and ``EXTRA_INCLUDE_NEWSUPPL``

**Comment by PaulWessel** [comment]
So in your case, do the MB modules end up in supplements.so then?  I think they should go in mbsystem.so (or dll) like on the Unix side (the MB install script builds these).

**Comment by joa-quim** [comment]
No, they end up in ``mbgmt_w64.dll``

**Comment by PaulWessel** [comment]
Great, so do you place the mb dir inside gmt/src or do you link, or what? This is the capability I would like for other dirs.

**Comment by joa-quim** [comment]
I put it (the installer does that) in ``bin/gmt_plugins``
My setting is something like this
```
	set (EXTRA_MODULES_SUPPL "mb/suppl_add_mb.txt")	# This include(s) will add new modules to the official GMT supplements
	set (EXTRA_INCLUDE_NEWSUPPL "mb/plug_mb.txt")	# This include will create new pluggins
```
where all the particular configs are done in the included files. For reference I'm including them here. Probably they have lots of non-needed stuff but since it works I don't want to care much about it.

[suppl_add_mb.txt](https://github.com/GenericMappingTools/gmt/files/4335561/suppl_add_mb.txt)
[plug_mb.txt](https://github.com/GenericMappingTools/gmt/files/4335562/plug_mb.txt)

**Comment by seisman** [comment]
It seems most of the MB settings are exactly the same as those for supplements. In the ideal case, developers, who want to develop a new plugin and want to access some interval functions, can simply create a directory under `src`, have some C codes and a CMakeLists.txt file. 

The CMakeLists.txt file should contain some variables to describe the plugin, and the GMT's src/CMakeLists.txt should do all the dirty work for them.

**Comment by PaulWessel** [comment]
Yes, that would make thinks much simpler.  The only think that would help would be a staging dir that is not in GitHub, so that if I add a subdirectory there it won't want to add it.  Instead of adding the dir to src, might src/staging be possible to do (with staging in .gitignore).  Probably simpler to add a symbolic link there to the actual source directory elsewhere.

**Comment by seisman** [comment]
What about splitting the library supplements.so into several smaller plugins, e.g. meca.so, gshhg.so?

**Comment by PaulWessel** [comment]
That may make the Cmake setup easier? I.e., each subdirectory ends up producing a directory.so file.  We could then probably update gmt_api to look for the "standard" set of shared libs before the custom ones.

**Comment by joa-quim** [comment]
I don't like that idea. Libraries are for storing many functions not just a couple. Why multiplying the number of shared libs for nothing?

**Comment by seisman** [comment]
Third-party plugins like MB are very similar to GMT's built-in plugins, except that GMT's built-in plugins are built into supplements.so while third-party plugins are built into their own libraries, e.g. mb.so.

If we want to make the development of third-party plugins easier, we need some cmake codes to process third-party plugins. I can imagine that the cmake codes for third-party plugins are almost the same as the codes for GMT's supplements.so, but we have to copy most cmake codes and make some tiny changes.

If we split the supplements.so into several smaller libraries, built-in and third-party plugins have no difference, and no more cmake codes are needed for third-party plugins.

**Comment by joa-quim** [comment]
> If we split the supplements.so into several smaller libraries, built-in and third-party plugins have no difference, and no more cmake codes are needed for third-party plugins.

How so? The MB plugin depends on several other libs so it always need it's own cmake codes.

**Comment by PaulWessel** [comment]
I agree we cannot make the assumption that all supplements only depends on GMT and its dependencies.  Must be possible to add in extra libs.

**Comment by seisman** [comment]
Each plugin has its own CMakeLists.txt. Developers can put more cmake codes there. It's also possible to allow include a file like suppl_add_mb.txt, which could have any customized cmake codes (e.g. linking extra dependency libraries). 

For developers, they don't need to care about gmtlib, pslib et al.

**Comment by PaulWessel** [comment]
Banged my left pinky hard yesterday so mostly typing one-handed today. Sigh..

**Comment by seisman** [comment]
There were four settings related to new supplements, EXTRA_MODULES, EXTRA_BUILD_DIRS, EXTRA_INCLUDE_NEWSUPPL, and EXTRA_MODULES_SUPPL.

After #3125, we only keep **EXTRA_BUILD_DIRS** and remove all the other three settings. Now it's much easier for other developers to add their own supplements. I think it's OK to close the issue. 

Before that, do you think **EXTRA_BUILD_DIRS** is a good name? What about renaming it to "SUPPL_EXTRA_DIRS" or other better names?

**Comment by PaulWessel** [comment]
yes, the "BUILD" is confusing to me, I am thinking separate "build/" subdirectories? Confusing. These are actually source directories, so SUPPL_EXTRA_SRC_DIRS or just SUPPL_EXTRA_DIRS would be better.
