### ISSUE TITLE
GMT_DATA_SERVER_LIMIT=0 doesn't work?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2954]
The documentation says remote file download can be turned off by setting GMT_DATA_SERVER_LIMIT to 0. I want to see what will happen if remote file download is turned off.

Here are the commands I use:
```
# remove the cached file
rm ~/.gmt/cache/ridge_07.txt

# turn off remote file download
gmt set GMT_DATA_SERVER_LIMIT 0

# see what will happen if I want to use a remote file that doesn't exist locally
gmt which -Gc @ridge_07.txt
```

This is my output:
```
/Users/seisman/.gmt/cache/ridge_07.txt
```

I expect to see a warning like "remote file cann't be downloaded because ..." or similar.

**Comment by seisman** [comment]
It turns out that `gmt set GMT_DATA_SERVER_LIMIT 0` gives me a gmt.conf file with 
```
GMT_DATA_SERVER_LIMIT          = unlimited
```

**Comment by PaulWessel** [comment]
The check on that limit being zero should happen right after we determine it is a remote file.  We don't need to determine the remote file size to compare to zero!  Will fix.
