### ISSUE TITLE
Requesting Bezier spline in psxy is defeated by default line resampling

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2957]
For background, see [this case](https://forum.generic-mapping-tools.org/t/s-for-spline-doesnt-work/310/2).

The problem is _not_ that the **+s** spline modifier for the pen setting is not allowed for geographic projections.  The problem is that for sparse geographic coordinates (like that of the user) we first interpolate along great circles.  Hence, by the time the Bezier function is called we already have finely resampled the curve and the spline cannot do anything different than follow the points.  This can be defeated by using **-A** of course.

There are two solutions:

1. Recognize that **+s** means the user wants a Bezier spline fit through the original data points and automatically turn on **-A** under the hood.
2. Add documentation to **psxy** to raise awareness of this issue so that users can choose to use **-A** or not or **+s** or not.

For backwards compatibility reasons as well as for flexibility I think we opt for better documentation.  OK with @joa-quim, @seisman and @KristofKoch?

**Comment by joa-quim** [comment]
Normally I would go for **1.** but given the past, I'm fine with **2.**

**Comment by KristofKoch** [comment]
I agree with @joa-quim: 1 would be elegant but happy with 2.

**Comment by KristofKoch** [comment]
Maybe add a note that `+v`/`+vb`/`+ve` doesn't work with `+s` as well. I'm just getting straight lines. Or, if I may dream, make `+v` work with `+s`? ;)

**Comment by seisman** [comment]
Should we declare it a bug and go for the 1st solution?

**Comment by PaulWessel** [comment]
I vote for the bug and solution number one too, had a change of heart.

**Comment by KristofKoch** [comment]
9c198ca works for me as expected. `+s` now behaves like `+s -A` in my testing. Thank you @PaulWessel! 

Understood the problems with `+v` as well. Might become a problem for a future feature request of mine.
