### ISSUE TITLE
Paths such as /tmp/gmt.gridlines are not suitable for multiuser systems

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#2989]
After commit e89bfdd4e45 I got a following problem
psbasemap [ERROR]: Unable to save current gridline information to /tmp/gridlines !
and no gridlines on the map.
The study showed that this file is not writable because it was created by another user. Obviously, in such cases on multi-user systems, the file name must be user-specific.

**Comment by PaulWessel** [comment]
Yep, I got lazy implementing a feature that required this knowledge.  Thanks for catching this - will fix.

**Comment by PaulWessel** [comment]
See if PR #2990 works for you, please.

**Comment by uleysky** [comment]
It works now. Session name is the parent pid, so there should be no conflict between parallel running scripts.
But I do not understand. I see in strace log
[pid 1041812] openat(AT_FDCWD, "/tmp/1041649-gmt.gridlines", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
[pid 1041812] fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid 1041812] write(3, "1\t1\n", 4)     = 4
[pid 1041812] close(3)                  = 0
[pid 1041812] access("/tmp/1041649-gmt.gridlines", F_OK) = 0
[pid 1041812] unlink("/tmp/1041649-gmt.gridlines") = 0
and many unsuccessful acess calls.
So, a file is created, written, deleted, and never read. What is the meaning of what is happening?

**Comment by PaulWessel** [comment]
It is something needed under the hood in case the user wants to add gridline ticks on the gridlines in a subsequent call.  We then need to know what those gridlines spacings were.  We may change how this is done over time but for now this should solve your immediate problem.

**Comment by uleysky** [comment]
Maybe make the place of such files user-defined? For example, by default they are written to a temporary directory, but you can change it with gmt set to the current directory or even set your own.

**Comment by PaulWessel** [comment]
There is always the GMT_USER_DIR.  I am looking at options. Placing in gmt.history which is written anyway is a leading candidate.
