### ISSUE TITLE
grdmath can't copy grid anymore

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#2992]
After commit f37ae5f208, the following code does not work

grdmath <grid1> = <grid2>

and gives an error

grdmath [ERROR]: Expression must contain at least one grid file or -R, -I

This is just copying and it can be done in another way, but in scripts where a command line for the grdmath is generated, the workability of such a construction is very useful.

**Comment by PaulWessel** [comment]
I don't understand.  Giving an error is the correct decision here since there are no arguments present to determine the grid.  if it did not before then that is a but, no?

Finally, when I run

```
gmt grdmath =
echo $?
0
```
it works fine (no errors).  Giving = as only argument to a module simply exits with a zero status if the module exists, else nonzero; see gmt docs:

`if <module-options> is '=' we call exit (0) if module exist and non-zero otherwise.`

**Comment by PaulWessel** [comment]
Let me know if my example works for you.  `grdmath =` should work the same way even though not using the gmt program directly is discouraged.

**Comment by uleysky** [comment]
No, not empty grdmath call. It was a formatting error, I did not check, sorry. Must be grdmath \<grid1\> = \<grid2\>. Here is full example:

echo "0 0 0                                                                                                                                                                                                                                  
0 1 0                                                                                                                                                                                                                                        
1 0 0                                                                                                                                                                                                                                        
1 0 0" | gmt xyz2grd -Gtest.grd -I1/1 -R0/1/0/1                                                                                                                                                                                              
gmt grdmath test.grd = test1.grd

**Comment by PaulWessel** [comment]
OK, will check.  Fixing your CPT issue at the moment.

**Comment by PaulWessel** [comment]
Can confirm the bug.  Will fix after my next zoom meeting today.
