### ISSUE TITLE
plot -Sf not following -W+s

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#2993]
**Description of the problem**

When using `-Sf` together with `-W+s` the symbols aren't placed along the bezier spline. Maybe related to #1165? I have the feeling that this is somewhat related to bezier splines being a pure PostScript thing. 

![map](https://user-images.githubusercontent.com/45796239/77941862-19788100-72bb-11ea-96b5-e8706b240712.jpg)

**Full script that generated the error**

```
cat > path.txt << END
 1.3 -1.5
 0.2  0.4
-0.8  0.1
-1.8  1.2
END

gmt begin map
	gmt basemap -R-2/2/-2/2 -JM6i -Bafg1
  gmt plot path.txt -W2p,red+s -Sf30p/10p+f
  gmt plot path.txt -Skcrosshair/0.5c -Wthinnest,black
gmt end show
```

**System information**

* Operating system: macOS
* GMT version : a6f3e31

**Comment by PaulWessel** [comment]
Yes, cannot be done.  PR coming to fix docs and prevent this combination.
