### ISSUE TITLE
Differences in plot and plot3d w.r.t. resampling lines

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2997]
**Description of the problem**

Both **plot** and **plot3d** can plot lines on maps.  Without a perspective angle and vertical relief, the two can make identical plots of lines.  However, **plot** has a default resampling of geographic data along great circles as its default mode (this can be deactivated or modulated via **-A**), while **plot3d** was no such default nor option.  For instance, this script plots the same data, but give very different default results (bold line):

```
cat << EOF > path.txt
30	30	0
90	50	0
120	20	0
EOF
gmt begin two png
  gmt subplot begin 2x1 -Fs12c -Baf -R20/130/0/60 -JM12c -A
    gmt subplot set 0 -A"plot"
    gmt plot -W1p path.txt
    gmt plot path.txt -A -W0.25p
    gmt plot path.txt -Sc0.2c -Gred
  
  gmt subplot set 1 -A"plot3d"
    gmt plot3d -W1p path.txt
    gmt plot3d path.txt -W0.25p
    gmt plot3d path.txt -Sc0.2c -Gred
  gmt subplot end
gmt end show
```

![two](https://user-images.githubusercontent.com/26473567/77969772-3cd50900-7286-11ea-9507-d94282866d0f.png)

**Recommended action**: Add the same **-A** option used in **plot** to **plot3**.

Alternatives, such as let **plot** have the same default as **plot3** (no resampling), but let both have **-A** for resampling, would break 20+ years of backwards compatibility.

Comments welcome.

**Comment by seisman** [comment]
Since **plot3d** is less commonly used, adding **-A** option to **plot3d** makes more sense to me.
