### ISSUE TITLE
Removing part of a frame in azimuthal

### ISSUE THREAD

**Issue by gouldin** [GenericMappingTools/gmt#3011]
**Description of the problem**
Revised version.  I actually tried

-JE0/90/16c -R-90/90/-89/90 -Bg0/g90 > map.ps

Once again, I got a complete frame, semi-circle at the south pole, line through -90/90 long.
I want to remove the -90/90 line.  How do I do this ?  

**Full script that generated the error**

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by joa-quim** [comment]
Please, don't open consecutive issues. Use the [Forum ](https://forum.generic-mapping-tools.org)to ask questions.
