### ISSUE TITLE
gmt psconvert produces an incorrect PDF file 

### ISSUE THREAD

**Issue by EduardoZorita** [GenericMappingTools/gmt#3012]
I am using GMT 6.0
I have produced a postscript file showing a global map of surface temperatures from gridded data using:

 gmt  grdcontour  -A-  -N -K  -P -Cmybar.cpt  further_options  > output.ps
gmt pscoast  -O -K    -P  further_options >> output.ps

The resulting postscript file output.ps  is correct (here shown as jpg)
![output](https://user-images.githubusercontent.com/63028211/78202519-deca4080-7494-11ea-922f-2c61cbc85389.jpg)
, but the transformed pdf file output.pdf
gmt psconvert -Tf output.ps

shows  a superposed rectangular grid of very fine while lines.

I have tried other conversion software with the same result .
[output.pdf](https://github.com/GenericMappingTools/gmt/files/4418445/output.pdf)

The offending option seems to be gmt grdcontour -N . When leaving this option out, the problem does not show up.

**Comment by PaulWessel** [comment]
You are seeing the effect of antialiasing.  Adjust the antialiasing setting of your PDF viewer and it will go away.

**Comment by PaulWessel** [comment]
Hi @EduardoZorita, did my response make sense and were you able to see the difference? BTW, I printed your PDF and it looks fine.  Closing this issue - please reopen if more feedback.
