### ISSUE TITLE
Let GMT play nicer with MATLAB data files

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3016]
**Description of the desired feature**

By default, GMT tables use the hashtag in the first position to indicate a data header or comment, e.g.,

`# This is a comment or header`

However, via **IO_HEADER_MARKER** any other single character can be used for input and/or output.

MATLAB uses % to indicate comments. While GMT can read such file by supplying `--IO_HEADER_MARKER=%`, MATLAB has no provision for accepting our # marker without some programming.

It would simplify life for users who (1) need to go between MATLAB and GMT and (2) that are not using the GMT/MEX tool if GMT could simply accept records starting with % as another comment or header without having to use `--IO_HEADER_MARKER=%` for **reading**.  For **writing** one needs to select this marker.  Internally, GMT maintains separate variables for the input and output markers.  My proposal for making this more flexible is to let the input marker variable be a **string** so that more than one marker would be recognized as flagging a header.  Thus, if the GMT defaults were like this:

`IO_HEADER_MARKER               = #%,#`

then GMT would seamlessly read MATLAB tables without any special arguments.  If there are other major softwares with another flag for header then that could be added too [I just don't know].

**Comment by PaulWessel** [comment]
Do you see any negative effects of allowing this flexibility? Note, this is separate from multiple segment headers where Matlab uses NaNs to break up lines.  So it should only affect file headers.

**Comment by joa-quim** [comment]
Reading ascii files already slow, also because every line is checked to be a comment line. I'm afraid that checking for strings instead of a single char slows it even more, and that for a very marginal use case.

**Comment by PaulWessel** [comment]
So I made a test: I created a 10 million record three-column ASCII data table (343 Mb) and ran **gmt info** on it 5 times using the current single char check: Each record has its first character compared to the single marker character `(line[0] == marker[GMT_IN])`.  I then made some quick changes to the read function so that instead it used `strchr (list_of_markers, line[0])` to detect header records that started either with "#" or "%".  Recompiled and ran that 5 times too, timing it.  The two data sets of elapsed times are identical at the 99.84% level of confidence, using MATLAB's two-sample t-test.

It is indisputable that GMT ASCII i/o is on the slow side - and hopefully this can be addressed during the refactor.  But with no detectable change for an enhancement that addresses an actual issue, I think this is a reasonable feature to consider, no?

**Comment by joa-quim** [comment]
Ok, than. But out of curiosity, how fast would it be if no testing for headers at all?

**Comment by PaulWessel** [comment]
Same, makes no difference.  The time is spent converting ascii to binary, plus lots of other things that should be profiled.

**Comment by joa-quim** [comment]
Strange. The *if* branch, probably more then the comparison itself, should have some weight in times.
Does the example file has headers?

**Comment by PaulWessel** [comment]
No, it is comparing random digits to '#' (or now '#' or '%').

**Comment by PaulWessel** [comment]
Every record is potentially a commented on or a header, so there is 10 miliion checks.  When I commented that out as you asked, no discernible difference.

**Comment by PaulWessel** [comment]
Realizing that some non-GMT ascii tables (e.g., CSV) have quoted text as header. So things like

```
"Data from NOAA"
1,1
2,2
```

and I have also seen

```
; strange semicolon header
12, 10
13, 14
```

So this makes me wonder if we should do this instead:

1. For ASCII input, flag header/comment records if they start with any of the characters `#!@$%;"'` and do away with IO_HEADER_MARKER as a user-setting for input.
2. Let IO_HEADER_MARKER only control the single output character `[#]`.

Much more user friendly.

**Comment by PaulWessel** [comment]
Does @seisman have any skin in the game on this discussion?

**Comment by joa-quim** [comment]
Given that none of these chars can be used as segment separators, perhaps remove the ``@$`` so that they are available for that case.

**Comment by PaulWessel** [comment]
OK, I agree that those are odd to begin with.  I am also having second thoughts about removing the IO_HEADER_MARKER setting for input since it is of course possible that someone has a crazy file with = as the marker and now we have lost that ability.  So I think keep the variables, but tolerate `#!%;"'`as header markers.  I have added the check to make sure segments are not selecting the same char - we never had that test before either.
