### ISSUE TITLE
Question about external and static functions

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3029]
In our effort to reduce the amount of symbols that are exported in the library, we have focused on making functions static.  This works well.  However, I am not sure I understand how this case might be affected.  In gmt_custum_io.c we have lots of these assignments:

`GMT->session.readinfo[id]   = &gmt_srf_read_grd_info;`

Somewhere deep in the bellly of GMT, a grid read function will call `GMT->session.readinfo[id]` with the value of ID that points to _gmt_srf_read_grd_info_.  Clearly, GMT and its pointers are exported.  My question is: If we made _gmt_srf_read_grd_info_ a static function (it is only used explicitly inside gmt_custom_io.c) will the pointer to that function still work?  I guess we can test but from experience things sort of work on macOS and it is Windows what is hard-core.  Note there is no **EXTERN_MSC** for these functions so I assume that means they are not really exported in Windows.

@joa-quim , might you do an experiment and make that function static, recompile, and try to grdinfo a surf grid.  Or, pick any of the other functions for whatever grid you have handy.  Let me know if things work.  if so, I suggest all those function go static.

**Comment by joa-quim** [comment]
Tested with *gmt_srf_read_grd_info* and grdinfo still worked. The big difference from Win and unix is, from what I remember, that on Win only the explicitly exported (EXTERN_MSC ) are exported whilst on unix everything is exported unless declared as static. If there were cross boundary (different dlls) cases, things might be different.

**Comment by PaulWessel** [comment]
Yes, that is what I know too.  So as long as we have one gmt.dll, at least those pointers seem good to go static.  We have many cases like that and I was not sure how to handle them.  No rush, though.

**Comment by joa-quim** [comment]
Which makes me think this is another reason for not breaking the supplements dll in pieces.
