### ISSUE TITLE
Rename static functions in gmt_map.c to start with gmtmap_

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3048]
**Description of the desired feature**

Per our [coding convention](CODE_CONVENTIONS.md), we want all static functions (i.e., only used inside a single source file) to start with the file name (minus any underscores in the file name).  So static functions in gmt_map.c should be named gmtmap_*.  Attached is the output log from the source convention scanner that pertains to gmt_map.c.  If you wish to take this task on, please assign this issue to yourself first so that only one person works on this.  Feel free to ask me for any help.  If you have some skills with bulk replace in an editor or via scripting then that is the fastest way.  Just make sure you build GMT successfully after your change and ideally run all the tests before you submit a pull request.

[gmtmap.txt](https://github.com/GenericMappingTools/gmt/files/4458376/gmtmap.txt)

**Comment by seisman** [comment]
I'll work on this one. Before I start to work on it, I need to confirm the renaming rules below:

- Convert all functions starting with "map_" to "gmtmap_", e.g. map_lon_to_corner -> gmtmap_lon_to_corner
- Convert all functions starting with "gmt_" to "gmtmap_", e.g. gmt_cartesian_dist_periodic -> gmtmap_cartesian_dist_periodic
- Add "gmtmap_" to all other functions

Is it correct?

**Comment by PaulWessel** [comment]
Thanks. Yes, correct.  In the end, all static functions should be called gmtmap_*.
