### ISSUE TITLE
Possibly renaming of some gmt library source files

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3080]
**Description of the desired feature**

This is about convenience and not a material change to behavior.  Here are a few things I would like feedback on:

1. It is convenient that all the files used to build the GMT API and library are called `gmt_*.[ch]`. Oh, but they are not.  We have some exceptions, such as 9 `common_*.[ch]` files, all written by Florian.  Might it not be simpler if they also got called `gmt_*`?  I am aware of other files with other names, but they are not ours (e.g., triangle.c, kiss_fft.c).
2. Because GDAL is (still) an optional prerequisite for GMT, we have lots of `#ifdef HAVE_GDAL` statements in the code.  I wonder (and @joa-quim may know best) if all the library access to GDAL should be consolidated into two `gmt_gdal.[ch]` files?  I count 7 files, including those called **ogr** (which is still calling GDAL).
3. If item 2 gets voted down, my backup request would be to at least rename gmt_gdal_librarified.c to something shorter.

My preference would be number 2 though.  Comments?

**Comment by joa-quim** [comment]
I have nothing against joining all GDAL code in a single source file but after merging #2973

**Comment by PaulWessel** [comment]
Ok, that merge has happened.  Would be gets if you did the joining so I don't mess things up for you.

**Comment by joa-quim** [comment]
Thins are messed for me right now because I can't build the MB suppl and can't find a cure

**Comment by PaulWessel** [comment]
OK, no worries.  I am shitting with grdvector and grd2kml this weekend.  Happy fucking Easter.

**Comment by joa-quim** [comment]
It can only have been #2929 Ghrrr

**Comment by joa-quim** [comment]
> Would be gets if you did the joining so I don't mess things up for you.

What do you want me to do with this?

**Comment by PaulWessel** [comment]
Basically, it would be to take the contents of the 7 gdal/ogr library files and put them all in gmt_gdal.c (and gmt_gdal.h I think).  Then make adjustments in src/CMakeLists.txt and make sure compiles.

**Comment by joa-quim** [comment]
MB shit id getting deeper and deeper. And I'm using the an old version that used to work.

**Comment by joa-quim** [comment]
Very irritating night ... and will continue

**Comment by PaulWessel** [comment]
Have you escaped from MB hell to consider a common gmt_gdal.[ch] model and consolidating those codes, @joa-quim ?

**Comment by joa-quim** [comment]
Started joining those files but hesitating. It will make navigation in their functions more complicated. As is *_read* deals with the reading part, *_write* with the writing and *_librarified* with accessing gdal modules as library functions.

**Comment by PaulWessel** [comment]
OK, I guess this also came about by trying to keep the names a bit shorted since the new dictum for naming of static functions makes things very long (and I know your monitor width is apparently finite).  Maybe gmt_gdal_librarified could just become gmt_gdal.?

**Comment by joa-quim** [comment]
*gmt_gdal* is too generic. *gmt_gdalprogs*?

**Comment by PaulWessel** [comment]
Sure, or gmt_gdalcall.

**Comment by seisman** [comment]
Close the issue?

**Comment by PaulWessel** [comment]
Yes, done.
