### ISSUE TITLE
Add testing of mbsystem to pre-release checklist

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3087]
**Description of the desired feature**

Since it has happened before, we should make sure a GMT release is not causing any trouble for the current MB-system release.  While we do not need to run something like this in the CI (or could we just when we are about to release only?), we need to have a short script that

1. Downloads the current mbsystem
2. Configures to use our GMT release candidate
3. Make sure it compiles fine
4. Set GMT_CUSTOM_LIBS to point to the mbsystem.so plugin
5. Test that gmt mbcontour = returns a 0 status (meaning we found the plugin)

Thoughts?

**Comment by seisman** [comment]
It would be better that MB-system can have a nightly CI job running with the latest GMT master branch. Then we can ping the developers and wait for their feedback before we make a new release.

**Comment by joa-quim** [comment]
Yes. My MB build is broken again. Now it complains
```
C:\progs_cygw\GMTdev\gmt5\master\src\gmt_dev.h(90): fatal error C1083: Cannot open include file: 'gmt_config.h': No such file or directory
```
Don't understand it.

**Comment by PaulWessel** [comment]
That file is certainly there. Looks like mb depends on proj4 and I have proj 5 and 6...

**Comment by joa-quim** [comment]
proj4, 5 & 6 should all do for MB. I advised Dave to do as I did and rely on GDAL only to interface with proj but he hesitated.

**Comment by PaulWessel** [comment]
Get this:

```
Check for Proj.4 library libproj
PROJ library location specified: /opt/local/lib/proj49/lib - check if libproj is there...
checking for pj_init_plus in -lproj... no
configure: error: Did not find libproj according to --with-proj-lib - check the installation!
```

**Comment by PaulWessel** [comment]
Take that back.  Just have to tell him everything:

```
    --with-proj-lib=/opt/local/lib/proj6/lib \
    --with-proj-include=/opt/local/lib/proj6/include \

```

**Comment by PaulWessel** [comment]
Got one issue:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src/mbio -I../../src/mbio -I../../src/mbaux -I/Users/pwessel/GMTdev/gmt-dev/dbuild/gmt6/include/gmt -I/opt/local/include -I/opt/local/include -g -I/opt/X11/include -MT mbswath.lo -MD -MP -MF .deps/mbswath.Tpo -c mbswath.c  -fno-common -DPIC -o .libs/mbswath.o
mbswath.c:454:52: error: too few arguments to function call, expected 5, have 4
                        if (gmt_check_filearg(GMT, '<', opt->arg, GMT_IN)) {
                            ~~~~~~~~~~~~~~~~~                           ^
/Users/pwessel/GMTdev/gmt-dev/dbuild/gmt6/include/gmt/gmt_prototypes.h:77:1: note: 'gmt_check_filearg' declared here
EXTERN_MSC bool gmt_check_filearg (struct GMT_CTRL *GMT, char option, char *file, unsigned int direction, unsigned int family);

```

So _gmt_check_filearg_ has changed in GMT at some point.  @seisman, what is the magic to find out when that happened?  I am sure it is me though.

**Comment by seisman** [comment]
1. The function `gmt_check_filearg` is defined at line 16244 in `gmt_init.c`.
2. Run `git blame -- gmt_init.c`, then go to line 16244, you'll see
```
ae6774152bb (Paul Wessel        2016-02-27 01:29:55 +0000 16244) bool gmt_check_filearg (struct GMT_CTRL *GMT, char option, char *file, unsigned int direction, unsigned int family) {
01e442d6524 (Paul Wessel        2016-02-17 03:44:45 +0000 16245)        /* Return true if a file arg was given and, if direction is GMT_IN, check that the file
a7e327116f8 (Paul Wessel        2014-10-30 21:55:09 +0000 16246)         * exists and is readable. Otherwise we return false. */
682ed025ee8 (Paul Wessel        2017-04-26 08:25:08 +0000 16247)        unsigned int pos = 0, kind = 0;
682ed025ee8 (Paul Wessel        2017-04-26 08:25:08 +0000 16248)        bool not_url = false;
d90ddd6213a (Paul Wessel        2013-10-30 16:46:27 +0000 16249)        char message[GMT_LEN16] = {""};
```
The first column gives you the commit hash of the last change for each line. So the latest change for this function is in ae6774152bb.

**Comment by PaulWessel** [comment]
6.0.0 already has the 5-arg version. 5.4.5 as well.  OK, problem is here:

```
#if GMT_MINOR_VERSION == 1 && GMT_RELEASE_VERSION < 2
			if (gmt_check_filearg(GMT, '<', opt->arg, GMT_IN)) {
#else
			if (gmt_check_filearg(GMT, '<', opt->arg, GMT_IN, GMT_IS_DATASET)) {
#endif
```

No check for MAJOR version so this fails for 0 0...  Will make work and suggest fixes via github.

**Comment by PaulWessel** [comment]
Thanks @seisman. I've forked their repo but now I fail with
`mbsvpselect.cc:193:10: fatal error: 'geodesic.h' file not found`
Did not get that with 5.7.5 tarball.  Not clear where they specify their prereqs. @joa-quim, thoughts on this include file?

**Comment by joa-quim** [comment]
I have that file under src/utilities but I have not rebuild MB in some time. They changed so many things that I'm sure the Windows build is broken again and patience starts to lack for this cat-&-mouse game.

**Comment by PaulWessel** [comment]
Their [list of required software](https://www.mbari.org/products/research-software/mb-system/how-to-download-and-install-mb-system/#toggle-id-4) does not mention proj, only GDAL, and their [README.md](https://github.com/dwcaress/MB-System/blob/master/README.md) does not even list GDAL?  How to know?

**Comment by joa-quim** [comment]
``mbsvpselect.cc``  Shit, they are putting C++ in the mix?

**Comment by PaulWessel** [comment]
Do you know what package geodesic.h comes from?

**Comment by seisman** [comment]
PROJ has the include file. See https://github.com/OSGeo/PROJ/blob/master/src/geodesic.h

**Comment by joa-quim** [comment]
Have convince myself to blow up some more nights and have a look. They used to require proj but not GDAL.

**Comment by PaulWessel** [comment]
/opt/local/lib/proj6/include

has what I need and I configure with

```
    --with-proj-lib=/opt/local/lib/proj6/lib \
    --with-proj-include=/opt/local/lib/proj6/include \
```

so something is screwed in their setup.

**Comment by joa-quim** [comment]
I don't think I will ever update MB again. Tons of files has become C++. No patience for C++ shits.

**Comment by PaulWessel** [comment]
Got the 5.7.5 tarball which works up to the point of not checking for major GMT version and thus fails.  Their master now has 100 C++ files vs 2 in the tarball.  Their build process is probably not very robust yet.  I opened an [issue](https://github.com/dwcaress/MB-System/issues/1055) to try to help.

**Comment by joa-quim** [comment]
More shit. My MB build of ``mbgmt_w32.dll`` is indeed broken. The dll is not being generated. It seems have been broken about a month ago (date of my last successful build). No errors but no file either.

**Comment by seisman** [comment]
Anything we can do here?
