### ISSUE TITLE
-Z in segment headers does not fill polygons

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3101]
Adapting the ``variable_z.sh`` test to put the info in the segment headers does not fill the polygons
```
cat << EOF > pol.txt
> -Z1
0 0
0 1
1 1
1 0.3
0 0
> -Z4
1 1
1 2
2 2
2 1
1 1
EOF

makecpt -Chot -T0/5 > t.cpt
gmt psxy -R-2/5/-1/3 -Jx2c pol.txt -B0 -Ct.cpt -W1p -P -K > lixo.ps
```

![lixo](https://user-images.githubusercontent.com/537321/79255177-c3d8d280-7e7d-11ea-8e38-741a2089f773.png)

**Comment by PaulWessel** [comment]
Pretty sure you need to use the +c modifier options in -W for that, no?

**Comment by joa-quim** [comment]
But we don't need to do that when using the -Z<file> option, and the **-Z** man says

*Instead of specifying a symbol or polygon fill and outline color via -G and -W, give both a value via -Z and a color lookup table via -C. Alternatively, give the name of a file with one z-value (read from the last column) for each polygon in the input data. To just set the fill or outline, append +f or +l, respectively [both].*

**Comment by PaulWessel** [comment]
Hm, yes does say that.

**Comment by PaulWessel** [comment]
The code says you need -L in this case since there is nothing on the _command line_ that says polygon.  We do parse the header and fill_active is set to true and active_fill is set to the right color.  But then this happens:

```
if (change & 2 && !Ctrl->L.polygon) {
	polygon = false;
	PSL_setcolor (PSL, current_fill.rgb, PSL_IS_STROKE);
}

```

That has been there forever.  We could comment that out and see if bad things happen.

**Comment by PaulWessel** [comment]
Uncomment leads to several failed tests that expects it to set the pen color unless -L is used.  So I think you just need to use -L.  I can update the docs to make this clear.

**Comment by joa-quim** [comment]
But even with **-L** it still doesn't fill the polygons.

**Comment by PaulWessel** [comment]
Was for no. You updated?

**Comment by PaulWessel** [comment]
Was for me.

**Comment by joa-quim** [comment]
I did, but I added the **-L** to the header and that doesn't work. Adding it to the command line, does.

**Comment by PaulWessel** [comment]
OK, yes it has to be command line since we have already decided on the reading by the time a segment header is parsed.

**Comment by joa-quim** [comment]
Right. And I re-encountered this. Do you remember? It only happens with the fill, not when no **-L**

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/79284707-58115c80-7eb3-11ea-88e0-a4b9310934d5.png)

**Comment by PaulWessel** [comment]
Remember that, but we showed it was a bad data point, right?

**Comment by joa-quim** [comment]
Yes it was. But why does it go to (0,0) (paper?) when filling and not line only?

**Comment by PaulWessel** [comment]
Can't recall why.  Perhaps it is a NaN, NaN point so for lines it means pen up but for polygons there is no pen up in the middle?

**Comment by joa-quim** [comment]
Seems likely. I don't see a problem in data, but it's a bit strange with an island at zone where the excursion starts.

![image](https://user-images.githubusercontent.com/537321/79286694-4b900280-7eb9-11ea-8094-54576825fa74.png)

![image](https://user-images.githubusercontent.com/537321/79286726-6498b380-7eb9-11ea-91ac-61dcf99e6c05.png)

**Comment by joa-quim** [comment]
Yes. I can reproduce it with
```
> -Z1
0 0
0 1
1 1
1 0.3
0 0
> -Z4
1 1
1 2
2 2
2 1
1 1
> -Z4
NaN NaN
1.2 1.2
1.2 1.8
1.8 1.8
1.8 1.2
1.2 1.2
makecpt -Chot -T0/5 > t.cpt
gmt psxy -R-2/5/-1/3 -Jx2c pol.txt -B0 -Ct.cpt -W1p -L -P > lixo.ps
```
