### ISSUE TITLE
change the way grd2xyz writes out the x,y values?

### ISSUE THREAD

**Issue by jocabo** [GenericMappingTools/gmt#3108]
If you have a netCDF grid that has irregularly spaced data, when using grd2xyz it writes out the x,y locations at locations corresponding to the average spacing, not the actual x or y locations specified in the x or y array in the netCDF file.

It would be nice if grd2xyz read the actual values from those arrays and wrote them to the xyz file, then the data could be regridded to a uniform lattice for proper plotting in GMT.

not sure if i explained it properly, but i think Paul and Joaquim know what I am talking about!

Thanks!

**Comment by joa-quim** [comment]
Can we have also a link to one of those files?

**Comment by jocabo** [comment]
Here is a sample file:
https://www.dropbox.com/s/uzg83vh1ho9qjat/NPac_Tohokuh.nc?dl=0
6.2 mb

**Comment by PaulWessel** [comment]
Sorry for the delay, but trying the dropbox link brought only sorrow - probably gone?

**Comment by seisman** [comment]
I can access the dropbox link. Reattached here [NPac_Tohokuh.nc.zip](https://github.com/GenericMappingTools/gmt/files/4566842/NPac_Tohokuh.nc.zip)

**Comment by jocabo** [comment]
Links still active for me.  Did you get it from Dongdong?  I tried his link and it worked as well.  Thanks for looking in to this.

**Comment by PaulWessel** [comment]
Thanks, I got it via @seisman.

**Comment by PaulWessel** [comment]
Hi @jacobo, please try grd2xyz -D in #3216.

**Comment by PaulWessel** [comment]
We removed -D and made this the default action.

**Comment by jocabo** [comment]
Hey guys,  Thanks for this, keen to give it a go. Assuming I need to download and re-install? But i looked at the windows installer and i think it is still V6 from a few months back Do i just wait for the 6.1 to be released? if so, that 's fine... I run GMT on windows through cygwin.

**Comment by joa-quim** [comment]
Yes, so far we have released installers only for the official releases. I use to have _dev_ versions at my site but it's not updated either.
