### ISSUE TITLE
non-perpendicular axes

### ISSUE THREAD

**Issue by hdkarimi** [GenericMappingTools/gmt#3117]
Hi everybody,

I want to something similar to below figure, BUT I don't know how shift x-axis to y=0
and how to tilt y-axis to specific angle using GMT.

![Constellation_updated-022019](https://user-images.githubusercontent.com/45714416/79485718-f247e080-802a-11ea-83dc-b90576eae828.jpg)

**Comment by joa-quim** [comment]
Please, use the Forum to ask questions.

**Comment by hdkarimi** [comment]
Due to DNS error I can not access forum.

**Comment by PaulWessel** [comment]
Perhaps a problem on your end? I reach it just fine from home: https://forum.generic-mapping-tools.org
