### ISSUE TITLE
GSHHG version 2.2.0 or newer is needed to use coastlines with GMT

### ISSUE THREAD

**Issue by Niemand112233** [GenericMappingTools/gmt#3122]
Hi,
I built GMT from source after your guide and when I try to run this: gmt coast -R-90/-70/0/20 -JM6i -B -Gchocolate
I get this error:

coast [WARNING]: GSHHG version 2.2.0 or newer is needed to use coastlines with GMT.
        Get and install GSHHG from ftp://ftp.soest.hawaii.edu/gshhg/.
coast [ERROR]: Could not find file [GSHHG intermediate resolution shorelines]
coast [ERROR]: No GSHHG databases available - must abort

What do I have to do? 
I downloaded the gshhg from your ftp server. And now what?
cheers

**Comment by KristofKoch** [comment]
Have you specified the path to GSHHG in `ConfigUser.cmake` before building GMT?

```
[…]

# 3a. Set full path to the GSHHG Shoreline Database directory [auto]:
set (GSHHG_ROOT "/path/to/your/folder/gshhg-gmt-2.3.7")
# 3b. Copy GSHHG files to ${GMT_DATADIR}/coast [TRUE]?:
#set (COPY_GSHHG FALSE)

[…]
```

**Comment by seisman** [comment]
@Niemand112233 Please use the [GMT forum](https://forum.generic-mapping-tools.org/) to ask questions.
