### ISSUE TITLE
A logical system to assigning color to pens and fills for plot features

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3131]
See #3124 for background.  In plot and plot3d, the options **-W** and **-Z** have a similar way of indicating if the color obtained via a CPT and a _z_-value should set the fill color, the pen color, or both [**-W** gets the *z* from a segment header (for lines) or column 3 (for points), while **-Z** gets the *z* value as a constant or from an auxiliary file].  However, **-W** uses a modifier **+c** which can take the arguments **f** (for fill) and/or **l** (for line), while the new **-Z** option uses modifiers **+f** and **+l** for the same thing.  We have several issues here that I think we need to correct before 6.1 release:

1. Since the **-Z** syntax is new since 6 we should correct it and use the same modifier **+c** with the optional **l** and/or **f** values.
2. Everywhere else in GMT we use the letters **g** for fill and **p** for pen, but here we use **l** for pen.  We should change this to **p** for both options but allow for the backwards compatibility of **l** for **-W**.
3. The default for **-W**..**+c** is to use to color for both fill and outline.  This seems like the most unlikely combination: It is much more likely that the user wants to use the color for the fill. Moreover, it is problematic that **-W** is used to set a _fill_ to begin with, given it has always been associated with a _pen_.  We have **-G** for setting fills, but it currently has no **+f** modifier to update the fill via the _z_ value.
4. The default of **-Z** is also to use the color for both fill and outline.  Again, this seems an unlikely choice.  Furthermore, because it defaults to setting the pen color as well, users are confused when they add **-W**1p,red only to find out that the red is replaced by the looked-up color!

**What is OK:**

These two mechanisms for changing fill and pen via segment headers are working well and will stay as is:

**Fill**: A constant fill for symbols or polygons is set via **-G**_fill_.  This is updated if we find a new **-G**_fill_ option in a segment header that is then parsed accordingly.  A **-G-** turns off fill until another **-G** option specifies fill again.

**Pen**: A constant pen width, color, and style for symbol outlines, lines, or polygons are set via **-W**_pen_. This is updated if we find a new **-W**_pen_ setting in a segment header that is then parsed accordingly.  A **-W-** turns off outlines (but not drawing of a line) until another **-W** option specifies a pen again.

**Summary:**

I think we need to declare a mix of bug fixing and change some recent decisions (**-Z**) to get a more logical system (in addition to two established option mechanisms listed above). For the remaining cases we **must** supply a _cpt_ via **-C** and **get** a *z* value somehow; the new color is then obtained via cpt(z) lookup.  A new *z* value can be obtained in any of four ways:

1. For symbols it is obtained via the 3rd column.
2. It can be given via  a segment header **-Z**_value_ .
3. It may be hard-wired via the **-Z**_value_ command line option.
4. Variable values may be obtained via the **-Z**_file_ command line option.

Thus, whether **-Z** is given or not is not important, what is important is that when **-C** is given a *z* value _must_ be obtained via one of these means.  With that, we are ready for the proposal:

**Proposal:**

1. To let the *z* value change the **fill**, specify **-G+z** (no args).
2. To let the *z* value change the **pen**, specify **-W**_pen_**+z** (Leave off **+z** if you want to draw the line with another, fixed pen color, and don't give **-W** at all if no outline is desired).
3. Eliminate the **-W** **+c** (backwards compatible) and **-Z**  **+l +f** stuff (entirely).

Need comments and feedback from @joa-quim and @seisman on this.

**Comment by joa-quim** [comment]
I like it that by rule 1. even if a multi-segment header has a **-Z***val* we can choose not to apply it but we should extend it to be automatically set when **-Z** is used in command line. As I understand the proposal, one would have to state **-Z -G+z** to have filled polygons by value and cpt.

Otherwise, this is a much more clear way of painting and outlining.
