### ISSUE TITLE
histogram: Error in drawing the equivalent normal distribution for horizontal histograms

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3141]
Example data: [eq.txt](https://github.com/GenericMappingTools/gmt/files/4508375/eq.txt)

Vertical histogram:
```
gmt histogram eq.txt -W1p -Gred -T5 -Baf -i2 -N -png histV
```
![hist](https://user-images.githubusercontent.com/3974108/79838565-361b4c80-8381-11ea-8818-1f79bac9600b.png)

Horizontal histogram:

```
gmt histogram eq.txt -W1p -Gred -T5 -Baf -i2 -N -A -png histH
```

![hist](https://user-images.githubusercontent.com/3974108/79838629-4df2d080-8381-11ea-9d29-d4483e0ec73a.png)

The normal distribution curve doesn't look correct for horizontal histograms.

**Comment by PaulWessel** [comment]
Probably first time someone has tried...
