### ISSUE TITLE
gmt_proj_setup() doesn't return error when it errors

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3157]
For example this case
```
 grdproject lixo.grd  -Glixo2.grd -Jm1:1 -C -F -R-12/90/0/90
grdproject [ERROR]: Option -R:  Cannot include south/north poles with Mercator projection!
```
still returns ``return (GMT_NOERROR);`` even if due to the above error many function pointers were not set. Then, in ``grdproject``
```
if (gmt_M_err_pass (GMT, gmt_proj_setup (GMT, GMT->common.R.wesn), ""))
```
skips the return and it later crashes when null function pointers are accessed.

**Comment by PaulWessel** [comment]
Clearly some old code handling here:

```
if (GMT->common.R.wesn[YLO] <= -90.0 || GMT->common.R.wesn[YHI] >= 90.0) {
	GMT_Report (GMT->parent, GMT_MSG_ERROR, "Option -R:  Cannot include south/north poles with Mercator projection!\n");
	GMT_exit (GMT, GMT_PROJECTION_ERROR); return false;
}
```

Remember the GMT_exit shit and Matlab etc.?  And yes it does not pass errors up the chain.

**Comment by PaulWessel** [comment]
This was actually addressed recently, so closing this issue.
