### ISSUE TITLE
Renaming sub-structures

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3198]
We have in many of our *mains* structures with sub-structres using naming conventions like this
```
struct GRDCLIP_CTRL {
	struct In {
		bool active;
		char *file;
	} In;
	struct G {	/* -G<output_grdfile> */
		bool active;
		char *file;
	} G;
	struct S {	/* -Sa<high/above>, -Sb<low/below>, -Si<low/high/between>, -Sr<old>/<new> */
		bool active; 
		...
	} S;
};
```
But Visual Studio debugger really doesn't like that and when debugging the contents of *opt->G* shows up whatever content a previous *struct G* from another module in the library may have. Apparently this naming is an undefined behavior in C.

The good practice is to give those sub-structs unique names, like
```
struct GRDCLIP_CTRL {
	struct GRDCLIP_In {
		bool active;
		char *file;
	} In;
	struct GRDCLIP_G {	/* -G<output_grdfile> */
		bool active;
		char *file;
	} G;
	struct GRDCLIP_S {	/* -Sa<high/above>, -Sb<low/below>, -Si<low/high/between>, -Sr<old>/<new> */
		bool active; 
		...
	} S;
};
```
This has been done in several modules but we need to apply it to all.

**Comment by PaulWessel** [comment]
So I can imagine a shell script that loops over each module file, makes an upper case name (e.g. GRDCLIP) from the module name (grdclip.c), and then builds a sed script with things like this:

```
s/struct A/struct GRDCLIP_A/g
s/struct B/struct GRDCLIP_B/g
...
```

etc. for all letters, plus "In".

Don't have to know which letters are used - just make one for all.  There may be a few cases where we have used something other than [A-Z] though - maybe add a way to discover that?  Does this sound like the way, @seisman ?

**Comment by seisman** [comment]
`s/struct A/struct GRDCLIP_A/g` is not safe. It also matches `struct AXIS`. 
`s/struct A {/struct GRDCLIP_A {/g` looks better.

**Comment by seisman** [comment]
Try this one instead. There is no need to loop over all single letters.
```
sed -E -i "" 's/struct ([A-Za-z]*) {/struct GRIDCLIP_\1 {/g' grdclip.c
```

**Comment by seisman** [comment]
There are still a few files left, block_subs.h, and 
```
$ grep 'struct [A-Za-z0-9]* {' **/*.c                                                                                          130 ↵
gmt2kml.c:	struct R2 {	/* -R */
gmt_remote.c:struct FtpFile {	/* Needed for argument to libcurl */
greenspline.c:	struct R3 {	/* -Rxmin/xmax[/ymin/ymax[/zmin/zmaz]] | -Ggridfile */
pscontour.c:struct PSCONTOUR {
psconvert.c:	struct popen2 {
seis/pscoupe.c:	struct A2 {	/* -Fa[size[/Psymbol[Tsymbol]]] */
seis/pscoupe.c:	struct E2 {	/* -Fe<fill> */
seis/pscoupe.c: 	struct G2 {	/* -Fg<fill> */
seis/pscoupe.c: 	struct P2 {	/* -Fp[<pen>] */
seis/pscoupe.c:	struct R2 {	/* -Fr[<fill>] */
seis/pscoupe.c: 	struct T2 {	/* -Ft[<pen>] */
seis/psmeca.c:	struct A2 {	/* -Fa[size[/Psymbol[Tsymbol]]] */
seis/psmeca.c:	struct E2 {	/* -Fe<fill> */
seis/psmeca.c:	struct G2 {	/* -Fg<fill> */
seis/psmeca.c:	struct P2 {	/* -Fp[<pen>] */
seis/psmeca.c:	struct R2 {	/* -Fr[<fill>] */
seis/psmeca.c:	struct T2 {	/* -Ft[<pen>] */
seis/psmeca.c:	struct O2 {	/* -Fo */
seis/psmeca.c:	struct Z2 {	/* -Fz[<pen>] */
seis/pspolar.c:	struct H2 {	/* -Qh for Hypo71 */
seis/pspolar.c:	struct S2 {	/* -Qs<half-size>[+v<size>[+<specs>] */
spotter/grdspotter.c:	struct S2 {	/* -S2 */
triangle.c:struct otri {
triangle.c:struct osub {
triangle.c:struct badsubseg {
triangle.c:struct badtriang {
triangle.c:struct flipstacker {
triangle.c:struct event {
triangle.c:struct splaynode {
triangle.c:struct memorypool {
triangle.c:struct mesh {
triangle.c:struct behavior {
```

**Comment by PaulWessel** [comment]
OK, after dinner.  We wont touch triangle.c as not ours.

**Comment by seisman** [comment]
Done in #3202, except `block_subs.h`. Should we update this file?

**Comment by PaulWessel** [comment]
Hm, that is too painful to contemplate. Looking it it, I am not sure we gain much saving with that file versus near-duplicate it for each of the three modules.  it is probably quite unreadable as it is.

**Comment by seisman** [comment]
@PaulWessel Perhaps we should document the substructure naming rules in CODE_CONVECTION.md.

**Comment by PaulWessel** [comment]
Yep too a stab at that in #3204.

**Comment by PaulWessel** [comment]
Perhaps this can be closed now @seisman ?
