### ISSUE TITLE
Exporting symbols in shared libs

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3199]
Windows and Unix behave differently in what goes exported into shared libs. While Unix exports everything by default, Windows only exports the symbols explicitly marked to be exported. Because exporting everything makes the shared libs larger and is prone to name clashing we use the ``GMT_LOCAL`` qualifier to many functions that are meant to be local to the source file (for example the *usage* function in all modules). We also use a lot of ``EXTERN_MSC`` when exporting functions from one source code to be used in another. But there are still lots of functions that are not qualified at all and as such they are not accessible by external codes on Windows.

Now, being accessible from external would provide not only a potential larger usage ground but specially would allow writing unit tests in Julia.  But we still do not want to export everything on regular builds. An option is to create EXPORT qualifiers that would just do nothing on default builds but allow an export value with a building option. As an example
``EXPORT_GMTLIB gmtlib_xxx``
would export all *gmtlib_xxx* functions when a, say, -DEXPORT_GMTLIB=YES" cmake build options is used. And a similar one for ``EXPORT_GMT gmt_xxx``. Also the ``GMT_LOCAL`` could be conditionally turned into an export directive. If seen useful we can even create an ``EXPORT_ALL`` for the remaining functions. This one would set ``EXPORT_GMTLIB`` and ``EXPORT_GMT`` to YES. This way we can have different levels of functions exports, depending if only for testing or for real third party use.

**Comment by PaulWessel** [comment]
I think we start with changing these four text bits across all modules:

```
GMT_LOCAL void *New_Ctrl (struct GMT_CTRL *GMT)
GMT_LOCAL void Free_Ctrl (struct GMT_CTRL *GMT
GMT_LOCAL int usage (struct GMTAPI_CTRL *API
GMT_LOCAL int parse (struct GMT_CTRL *GMT
```

to

```
static void *New_Ctrl (struct GMT_CTRL *GMT)
static void Free_Ctrl (struct GMT_CTRL *GMT
static int usage (struct GMTAPI_CTRL *API
static int parse (struct GMT_CTRL *GMT
```

since these should never be exported.  Seems like a harmles sed-script, @seisman ?

**Comment by seisman** [comment]
Looks good.
