### ISSUE TITLE
GMT5 xyz2grd creates netcdf-3 file, can't be read by other GMT modules

### ISSUE THREAD

**Issue by prokman135** [GenericMappingTools/gmt#3205]
Hello,

I apologize for first posting this at Unidata/Netcdf-c first, but this GMT site is probably more appropriate.  There is a related posting already at Netcdf-c:

https://github.com/Unidata/netcdf-c/issues/1689

I am running the latest version of GMT5, GMT 5.4.5 on a Mac OS 10.15.4 (Catalina), installed via macports, and with netcdf 4.7.4

When I try to run this simple script:
echo "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16" | gmt xyz2grd -Gzrun.grd -I3/3 -R-3/6/-3/6
it apparently creates a netCDF-3 file, which cannot be read by other gmt modules such as grdinfo:

grdinfo (api_import_grid): NetCDF: Attempting netcdf-4 operation on netcdf-3 file [zrun.grd]

If I use the option --IO_NC4_CHUNK_SIZE=2,2 for xyz2grd, then xyz2grd will create a netcdf-4 file that can then be read by grdinfo

Is there a better solution, without having to use a very small chunk size?  Is there a version of grdinfo that can read netCDF-3 files?

Thanks,
Mark

**Comment by PaulWessel** [comment]
Netcdf, after decades, introduce the above as an error - it used to be skipped.  We have a workaround in GMT 6.1 master.  Or, you can build GMT5 with the previous netcdf release.

**Comment by prokman135** [comment]
Thanks for the response.
Can GMT5 be built using netcdf-3 via Macports?  There doesn't seem to be a variant that allows that.  Otherwise I'm not sure how to build GMT5 with a previous netcdf release

**Comment by PaulWessel** [comment]
I'm building GMT 6 master on macports.  You can always [downgrade](https://trac.macports.org/wiki/howto/InstallingOlderPort) your netcdf to the version before the current release.  Or you can install GMT 6 from github and not worry about it.

**Comment by prokman135** [comment]
Hi Paul, Thank you for your advice
Using Macports, I uninstalled GMT5, activated an earlier version of netcdf (4.7.4 to 4.7.3), and then installed GMT5 and now everything works as before. Let's hope this gets fixed soon!
Mark
