### ISSUE TITLE
Allow GMT_OPENMP to enable OpenMP support for backward compatibility

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3221]
For a long time, users can enable OpenMP support by setting either **GMT_OPENMP** or **GMT_ENABLE_OPENMP** to TRUE, although only **GMT_ENABLE_OPENMP** is officially documented.

I just realized that package maintainers for Fedora/CentOS and macports use **GMT_OPENMP**, probably due to some historic reasons. 

In PR #2884, we eliminated the unused and undocumented variable **GMT_OPENMP**. Thus, now the only way to enable OpenMP is setting **GMT_ENABLE_OPENMP** to TRUE. This is backward incompatible and breaks many maintainers' building script.

I think we should add **GMT_OPENMP** back and report a warning if this variable is set.

**Comment by PaulWessel** [comment]
Yes, that is a good idea.  Perhaps if we warn it will become deprecated in the future they will stop using it and we can remove it.
