### ISSUE TITLE
psxy: incorrect great circle arc for near antipodal points

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#324]
**Full script that generated the error**

Following codes plot great circle arc of near antipodal points using two different ways:
1. generate great circle path using `project`, then plot it
2. plot the line segment between the two points directly, and let `psxy` calculate the great circle path and plot it.

Theoretically, these two ways should plot the same arc.

```
x0=29.83
y0=-40
x1=209.83
y1=40.75

gmt project -C$x0/$y0 -E$x1/$y1 -G10 -Q > great_circle_points.xyp
gmt begin map png
gmt plot great_circle_points.xyp -JM15c -R0/360/-80/80 -Baf -W3p,red
gmt plot -W1p,blue << EOF
$x0 $y0
$x1 $y1
EOF
gmt end
```
![image](https://user-images.githubusercontent.com/3974108/51361857-56ce6580-1a9f-11e9-82e3-e5b3f7f9c9e0.png)

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_8608e5e

**Comment by PaulWessel** [comment]
Looks like project is correct and psxy fails.  They are using separate methods to do this which likely is the cause of the trouble.  Will debug and see why it derails.
