### ISSUE TITLE
Transparent movies?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3243]
**Description of the desired feature**

The **movie** module works by converting _PostScript_ plots to fixed-size png images and then these are converted to a movie (MP4 or GIF).  It was assumed that each frame replaces the previous frame in a movie and hence these are **opaque** pngs (format png).  Thus, a dumb movie that plots a point along a sine:

```
gmt begin
	y=\`gmt math -Q \${MOVIE_FRAME} SIND =\`
	echo \${MOVIE_FRAME} \$y | gmt plot -R0/360/-1.2/1.6 -JX3.5i/1.65i -Sc0.1i -Gred -BWSne -Bxa90g90f30+u@. -Bya0.5f0.1g1  -X0.35i -Y0.25i  --FONT_ANNOT_PRIMARY=9p
gmt end
```

and run it this way:

`gmt movie main.sh -C4ix2ix125 -T360 -Ntransp -D24 -A+l -Zs`

results in the GIF animation below:

![opaque](https://user-images.githubusercontent.com/26473567/80930864-ef026380-8d51-11ea-80be-8f535c9604fc.gif)

Now, if we had an option to select **transparent** png images (format PNG; here I just changed the code) then the same movie looks like this:

![transp](https://user-images.githubusercontent.com/26473567/80930899-3688ef80-8d52-11ea-9374-c81b7ecd1ff9.gif)

Here, the movie is the accumulated concatenation of all the transparent images up to a given frame.  This brings up a few questions:

1. It seems this effect can be useful for some movies so I would argue we need to control if gmt makes png or PNG.  Depending on where it is displayed (powerpoint, web), the movie itself may be transparent (depending on what is plotted [have not checked this yet]).
2. You can tell that the basemap frame has been stacked many times. It is curious to me that it does not start out like the top then get fatter, but perhaps if we played it at a very low frame rate we would see that the 2nd frame is fatter than the first.  Anyway, this begs the question if when transparent PNG is requested that perhaps any backgrounds layer (which might produce the basemap) shall only be included for frame 0 since otherwise we are just stacking them.
3. There may be other subtleties that will appear with more testing, but that is it for now.

Thoughts, @joa-quim and @seisman?

**Comment by seisman** [comment]
Looks an interesting feature.

> Anyway, this begs the question if when transparent PNG is requested that perhaps any backgrounds layer (which might produce the basemap) shall only be included for frame 0 since otherwise we are just stacking them.

What can we do with the foreground layer?

**Comment by PaulWessel** [comment]
Ah, foreground layer.  Not sure.  It would definitively overlay everything, but that is how it has been anyway.  Unlike the background layer, it cannot be plotted once since things should not go on top of it.  So it would be plotted as normal.

**Comment by PaulWessel** [comment]
I am also not sure if I understand PDF transparency.  I implemented the movie fade in/out from/to black a while ago and it works fine.  Basically, after all PS is plotted I have psconvert add this:

```
0.2 /Normal PSL_transp 
clippath 0 0 0 F 
```

Here, transparency is 0.2.  So I am plotting a black but transparent rectangle over everything .  Hm, so I thought why not make the fade color a choice.  Fade from white should work too, and the same way. With no transparency we should reach a white page that is slowly getting transparent.  But no, doing

```
0.2 /Normal PSL_transp 
clippath 1 1 1 F 
```

gives me exactly the same result.  Surely that cannot be right? What am I missing?

**Comment by PaulWessel** [comment]
So found I have a bug related to fading, which is why the above is screwed: I am missing a C after the rgb values...

**Comment by PaulWessel** [comment]
AN update on transparent movies: The above are animated GIFs which display the desired effect.  However, at the present time, alpha channel (transparency) in video codecs is mostly experimental. H.265 (HECV) has support for transparency but FFmpeg would not allow me to use transparency PNG.  VP9 (WebM) claims support, and maybe it worked, but not the the same way (not stacking like for GIF but individual transparent frames).  Good for experimentation.
