### ISSUE TITLE
Move some animations to HD movies

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3245]
Look at the animations in the [GMT Gallery](https://docs.generic-mapping-tools.org/latest/gallery.html). You'll see that some animations play very fast (e.g. anim04, anim07, anim08). It's because we have very limited resources on CI and have to reduce the number of frames when building these animations.

The animations can be more attractive if we can increase the number of frames. What we can do:

- modify the scripts and increase the number of frames
- make the HD movies and upload to YouTube
- move animXX to movieXX

**Comment by PaulWessel** [comment]
The main driver of the tiny animation with a small frame number and thumbnails that skips to every 10th frame, etc, was (initially, pre-CI) the long time it took to render larger movies, and then post-CI it was the fact that the CI would time-out.  The end result is animations that are now awe-inspiring so why should anyone spend time to learn this when it looks shitty?  Also, the git thumbnails for the movies are mostly distracting anyway.

If we spruce up the scripts to HD and make more frames then there really is no need to separate anim from movie; it is an artificial divide.  Currently, make check runs these tests with no argument passed to the script and then we simply make just a master frame in PS.  That way we know if an animation fails.  This would not translate well to the new movie01.sh which would take many minutes to build a global intensity file  from @earth_relief_30m (not to mention downloading that file if you don't have it).  So if we are to have CPU/space intensive movies then perhaps they need to be excluded from manual check test altogether.  We may want to make a target

`make -jx movie_test`

which would only build the master frames and thus at least test the scripts, and then we can run do_movies.sh to build the whole thing.

**Comment by seisman** [comment]
For anim08, we already have a wonderful video on YouTube (https://www.youtube.com/watch?v=H0RyjHRhJ3g). It's much better than the one in the GMT documentation.

What we could do:

- [ ] Modify the anim08.sh to generate the YouTube video
- [ ] Remove the PS file, i.e. not testing anim08. We already have a similar test in test/psevents.
- [ ] Update the cmake script and documentation.

**Comment by PaulWessel** [comment]
Working on anim07 right now and it will be another multi-hour job.  So 7 is before 8.  How should we do this?  I guess I will update 8 as well to do what was done for AGU and then change your cutoff to 6 for now.

**Comment by seisman** [comment]
You need to modify the script, make the animation and upload it to YouTube. Then I can help with the documentation and cmake script.

**Comment by PaulWessel** [comment]
Deal!  Working on these now - but takes hours to render and I may need to do it more than once.  I am also going to explore newer codecs. Apparently h265 won't take over for h264 since it has 3 patents to deal with.  The AV1 (supported by Google, Apple, the big guys) has none.  Called VS10 it will likely get good adoption and is supported in browsers (but not Safari and iOS yet).  Should make file sizes much smaller.  Should work in YouTube (Google) etc.  I will at least test this.

**Comment by seisman** [comment]
Are we going to migrate the remaining animations (anim01-05) to YouTube? Building the documentation takes only 1 minute, but running the animations takes more than 5 minutes. Sometimes, the animations even hang up and time out.

**Comment by PaulWessel** [comment]
Yes, perhaps that is the better solution. having these low-res tiny examples is not a good plug for making movies.  So I agree not worth having these run in the CI (other than to make the master frame).  I will have a look, but presumably I would fix these up to be larger, more frames, and overall slicker.

**Comment by meghanrjones** [comment]
All the animations are now hosted on YouTube, so I am closing this issue.
