### ISSUE TITLE
Separate pages for examples and animations

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3246]
Now we have 50 examples, 8 animations, and 1 HD animation. They are all listed in the [Gallery page](https://docs.generic-mapping-tools.org/latest/gallery.html) and the animations are listed at the bottom.

As we expect to add more examples and movies in the future, I think it's better to separate them into two pages, gallery.html and animations.html. It also makes GMT's movie-making feature more visible to users.

**Comment by PaulWessel** [comment]
Agree.
