### ISSUE TITLE
Test genper/snyder_map.sh fails on Linux

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3255]
```
1/1 Test #252: genper/snyder_map.sh .............***Failed    1.14 sec
/usr/bin/gm compare: image difference exceeds limit (0.00638103 > 0.0055).
genper/snyder_map.ps: RMS Error = 0.0064 [FAIL]
memtrack errors: 0
exit status: 1
```

CI Generated PS:
[snyder_map.ps.zip](https://github.com/GenericMappingTools/gmt/files/4583215/snyder_map.ps.zip)

GM diff image:

![snyder_map](https://user-images.githubusercontent.com/3974108/81107935-ee9ad180-8ee5-11ea-9c24-15e970578fbd.png)

**Comment by PaulWessel** [comment]
All of them failed earlier after I upgraded postscriptlight to use more decimals in angles.  But I dont remember updating this one specifically, so perhaps it slipped through.  The PNG has the same feel as all the others I fixed.  I don't see anything wrong?

**Comment by seisman** [comment]
The RMS error is 0.0035 on macOS and 0.0064 on Linux, and GRAPHICSMAGICK_RMS is set to 0.0055. Perhaps updating the PS can fix it. I'll make a PR for it.
