### ISSUE TITLE
Input with leading strings

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3261]
It seems GMT cannot deal with input with leading strings. Please try following commands:
```
echo ABC 2 4 | gmt select -it
echo ABC 2 4 | gmt select -it1,t2
```

**Comment by PaulWessel** [comment]
No need to try, it is verboten.  The GMT input model is clear: All numerical columns followed by optional trailing text.  The -i operates with that in mind.

**Comment by seisman** [comment]
> The GMT input model is clear: All numerical columns followed by optional trailing text.

I'm OK with that, but GMT should raise a warning or an error for that. Currently, the second command gives a segment fault.

**Comment by PaulWessel** [comment]
OK, will have a look.Bug me if nothing happens by week's end...
