### ISSUE TITLE
line color in custom symbol

### ISSUE THREAD

**Issue by gouldin** [GenericMappingTools/gmt#327]
**Description of the problem**
I try 0  0 M -W1p+cl255/140/0 
        0 1 D
in a custom symbol file.  (that's "ell", not "eye" after c, But "eye" fails as well).
I get the broad stroke, but no color.

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Version of GMT:

**Comment by PaulWessel** [comment]
I think it the macro symbol language there is no modifier **+cl**.  The **-W** only sets the outline pen and the separate **-G** sets any optional fill.  Does not **-W**1p,255/140/0 work as you need it to?

**Comment by gouldin** [comment]
Many thanks.  -W1p,255/140/0 is perfect.

**Comment by PaulWessel** [comment]
Closing this issue.
