### ISSUE TITLE
Maybe not warn about things we cannot do anything about?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3273]
**Description of the desired feature**

When we write a grid and the range of z-values is quite large, we may sometimes get this:

`grdcut [WARNING]: The z-range, [-1.03878e+08,1.61299e+07], might exceed the significand's precision of 24 bits; round-off errors may occur.`

For instance I can easily create that message:

```
gmt grdmath -R0/2/0/2 -I1 X 16777216 MUL = t.nc
grdmath [WARNING]: The z-range, [0,3.35544e+07], might exceed the significand's precision of 24 bits; round-off errors may occur.
```

because any z value larger than the integer 16777216 (2^24) cannot be represented exactly in a float.

There is usually nothing we can do about this, since we are writing floats, and it is usually understood that you cannot represent every number in a computer.  We are not writing double grids.  Should this remain a **WARNING** or should we relegated it to **INFORMATION**?  I favor the latter.

**Comment by joa-quim** [comment]
I think we should simply remove this warning/info. As you say, there is nothing that can be done and it's a very cryptic message to the vast majority of people who don't know that the base of a float is 24 bits or how floint point representation works.
