### ISSUE TITLE
Better warnings for faulty gs

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3282]
**Description of the desired feature**

While the developers know that gs 9.51 and 9.52 have a broken transparency system, the users don't know that.  So we get issues posted here or on the forum that sometimes we quickly can dismiss and other times it may take lots of debug to realize the problem is related to a bad gs.

Suggestion: Maybe have a list of known bad gs version in a file, and when **psconvert** checks what gs version it has, we can compare and at least warn about problematic versions.  It could be a file like this

```
struct GS_VERSIONS {
#include "gmt_bad_gs.h"
0, 0};

```
and then a call to a small function to check if ours is one of the bad, then warning.

OK, or any better ideas, @joa-quim and @seisman? We spent hours trying to figure out why a movie did not have transparency until we learned the other user had 9.52...

**Comment by seisman** [comment]
But it will definitely annoy users if they don't use any transparency in their figures.

**Comment by PaulWessel** [comment]
We could only issue the message if they are doing transparency.  We know since we scan the PS to find out.

**Comment by seisman** [comment]
> We could only issue the message if they are doing transparency. We know since we scan the PS to find out.

Good to know that. Then I agree we should warn them.

**Comment by PaulWessel** [comment]
Are you able to build and test gs from source (e.g., to see if their bug has been fixed in the repo)?

**Comment by seisman** [comment]
Just build their master branch. The transparency bug in 9.51 and 9.52 is fixed. Now I can see transparency in PDF, JPG and PNG.

However, I get the following warnings for transparent plots:
```
   **** WARNING: .setopcaityalpha is deprecated (as of 9.53) and will be removed in a future release
   **** See .setfillconstantalpha/.setalphaisshape for the improved solution
```

**Comment by PaulWessel** [comment]
This is a threat for us, so we need to figure out how to rewrite the PSL_transp PostScript function that is defined in the PSL_strings.h include file.  I have yet to find any documentation on .setfillconstantalpha and how to use it.  Just replacing .setopacityalpha with . setfillconstantalpha did not seem to wark (no errors, but no transparency).  We will need to research this more to better document how we do this, possibly asking the gs people for advice.

**Comment by seisman** [comment]
> Just replacing .setopacityalpha with . setfillconstantalpha did not seem to wark (no errors, but no transparency).

It works for me with gs 9.53 (built from their master a few days ago). It doesn't work for you possibly because you're still using 9.50?

**Comment by PaulWessel** [comment]
Yes.  So we cannot drop it in yet, but also cannot wait until they drop support.  I guess we need a way to issue the right code based on gs version.  Have to think about how that should be done, maybe with a bit-flag passed into PSL_plotinit.

**Comment by seisman** [comment]
I just opened another issue #4453 to discuss the compatibility of setopacityalpha and setfillconstantalpha. This issue can be closed.
