### ISSUE TITLE
Simpler image blending

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3286]
**Description of the desired feature**

I want to blend two images so that the output pixel `p = p1*a + p2 (1-a)`, where p1 and p2 are pixels from the two images, and a is a weight (alpha) from 0-1.  For instance, given a night/day shade as a, I want this output:

![new](https://user-images.githubusercontent.com/26473567/81383906-9235de80-90ac-11ea-8640-589c605c25ca.jpg)

which I can then wrap on a sphere.  However, to do this I had to do it the hard way: extract separate r,g,b channels for both grid, do the grdmath, then combine the channels.  I got close with 

`gm convert  p1.tif p2.tif alpha.png p.png`

but it only worked if alpha.png was either 0 or 255 (i.e., two separate values only).  Do I really have to write imgblend.c as a new GMT module, or let grdmath understand r,g,b layers?  Surely this should be a one-line gm or gdal command...

**Comment by joa-quim** [comment]
Don't think GDAL can do it out of the box. ``gdalbuildvrt`` says
>If there is some amount of spatial overlapping between files, the order of files appearing in the list of source matter: files that are listed at the end are the ones from which the content will be fetched. Note that nodata will be taken into account to potentially fetch data from less prioritary datasets, but currently, alpha channel is not taken into account to do alpha compositing (so a source with alpha=0 appearing on top of another source will override is content). This might be changed in later versions.

and we don't want to include ``gm`` as another dependency.

**Comment by PaulWessel** [comment]
With GMT_Read|Write_Data for GMT_IMAGE this would be a very simple module.  But it moves GMT into "image processing", hence my hesitation.  I don't know where something like

`file1.png file2.png -Afile3.png -Gblend.png`

could go otherwise.  I don't think I can do this in grdmath on images, and starting a supplement with one module seems lame.

**Comment by joa-quim** [comment]
You don't need to call it *image processing*. Just say it blends 2 grids using a mask and just let it work for images too (using int arithmetics?)

**Comment by PaulWessel** [comment]
`gmt grdmix grdorimg1 [grdorimg2] -Agrdorimg3|constant -Goutgrdorimg`

If one input item then must be image.  We use the values in -A (grid, image, or constant) to add an alpha channel.
If two input items they can be grids or images.  We then use the values in -A (grid, image, constant) to blend between teh two inputs, writing out a third.
Other useful things we may want to do in this context?

**Comment by joa-quim** [comment]
Don't worry, we'll think on  ton of options to add later. For example Can the two grids/images have different resolution , and cover different regions although with some overlap?

**Comment by PaulWessel** [comment]
gmt grdimage grid -Ccpt -Aimage.jpg

creates an image directly from the grid.  However, it requires a dummy -J.  We should bypass that somehow.

I was thinking perhaps grdmix could also have options to read CPTs and turn the grid into an image first.  As an example,

gmt grdmix dem.grd oceanfaa.grd -Cdem.cpt -Dfaa.cpt -Alandseamask.grd -Gmap.tif

with output being a geotiff

**Comment by joa-quim** [comment]
See. And now you also want to burn the coastlines.

**Comment by PaulWessel** [comment]
Hm, probably not.

**Comment by joa-quim** [comment]
Maybe not you, but users will.

**Comment by PaulWessel** [comment]
Closed as implemented via grdmix.c
