### ISSUE TITLE
gmtinfo -C -: gives wrong result from externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3289]
Without -C it behaves well

```
julia> gmtinfo("", [1 10;2 20])
 "<matrix memory>: N = 2\t<1/2>\t<10/20>"


julia> gmtinfo("-:", [1 10;2 20])
 "<matrix memory>: N = 2\t<10/20>\t<1/2>"
```
but with it, no

```
julia> gmtinfo("-C", [1 10;2 20])
 1.0  2.0  10.0  20.0


julia> gmtinfo("-C -:", [1 10;2 20])
 20.0  10.0  1.0  2.0                           # Should be 10.0 20.0 1.0 2.0
```

**Comment by joa-quim** [comment]
And there is more
```
julia> D = gmtread("svp.dat");

julia> gmtinfo("-: -C", D)
 12000.0  0.0  1501.4  1669.0


julia> gmtinfo("svp.dat -: -C")
 1669.0  1501.4  0.0  12000.0


julia> gmtinfo("-: -C", D[1].data)
 1669.0  1501.4  0.0  12000.0
```
So reading from file or passing the Mx2 matrix gives correct values but passing the Dataset swaps also 1/2 columns info

(Confirmed with Matlab)

[svp.zip](https://github.com/GenericMappingTools/gmt/files/4602370/svp.zip)

**Comment by joa-quim** [comment]
OK, the problem is that for the externals the ``-:`` is still active at time of writing so it swaps first ans second element. To make it work correctly on has to use ``-:i``
```
julia> gmtinfo("-C -:i", [1 10;2 20])
1×4 Array{Float64,2}:
 10.0  20.0  1.0  2.0
```

Tricky because the need of ``-:i`` is not obvious and we cannot reset the column order before the report because it would affect the reading of other eventual segments. Also, oddly ``-i1,0`` is ignored
```
julia> gmtinfo("-C -i1,0", [1 10;2 20])
1×4 Array{Float64,2}:
 1.0  2.0  10.0  20.0
```
This looks a bug.

**Comment by PaulWessel** [comment]
I should be able to get -: to work, but I am pretty sure we agreed not to use -i for externals since they can do their own thing.

**Comment by joa-quim** [comment]
That i remember right now, I use -i to duplicate columns in some ``plot`` trickery to add automatic color columns and things like that. So, yes -i is useful in externals too

**Comment by PaulWessel** [comment]
Focusing on -: for the moment, with test data t.txt

```
1  10
2  20
```

If there is no **-C** then we form a text record.

```
gmt info t.txt
t.txt: N = 2	<1/2>	<10/20>
gmt info t.txt -:
t.txt: N = 2	<10/20>	<1/2>
```

but if we use **-C** then we build 4 columns:

```
gmt info t.txt -C
1	2	10	20
gmt info t.txt -: -C
20	10	1	2
```

This odd result is because we first flip input, so we would get 10 20 1 2, but on output (-: does both) it flips the 10 and 20.  I think that is something we can agree is a bug, since the first two columns is no longer x and y, but xmin xmax, and now xmax is given as xmin.  So in gmtinfo, if **-C** and **-:** is used it should quietly set **-:i** instead

10	20	1	2

**Comment by PaulWessel** [comment]
Separately, about -: in general.  I have a branch where I fixed this for when we read from externals into dataset, and when we write from dataset to external dataset,matrix,vectors.  Still testing and want to merge the one you just approved first.

**Comment by meghanrjones** [comment]
Closed by https://github.com/GenericMappingTools/gmt/pull/3605. @joa-quim, please re-open if this is still a problem for GMT.jl.
