### ISSUE TITLE
Release tarballs do not bundle anymore compiled docs and manpages

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/gmt#329]
Up to GMT version 5.4.4, release tarballs contained the `doc_release` and `man_release` directory with compiled html and pdf documentation and manpages.

Starting from version 5.4.5, these two directories are missing.

Is this intended? Should users now build the manpages and the doc by themselves?

**Comment by PaulWessel** [comment]
I think that was a mistake - we were editing the release CMakeLists.txt file to deal with git rather than subversion and now use git archive to build the tarball.  However, there are steps to build the release directories and the dependency on that target got broken.  A workaround is to use the 5.4.4 docs since I think there are minor to none differences with 5.4.5.   We will look into the issue and try to fix it.

**Comment by claudiodsf** [comment]
Hi, just saw that you merged #347 to the master branch, which should solve the problem.

Are you planning to back port this to 5.4.x and make a 5.4.6 release including this fix (or, re-release 5.4.5)?

This will give back GMT manpages to homebrew users on macOS and, most likely, to users on other platforms.

Thanks!

**Comment by opoplawski** [comment]
This would be appreciated for Fedora as the docs fail to build on EL7 due to an old version of sphinx.

**Comment by seisman** [comment]
Are we going to release a GMT 5.4.6 before or after 6.0.0b? If not, we can close the issue.

**Comment by PaulWessel** [comment]
I think we should.  Since GMT 6 cannot really be called a stable version we should update 5.4 for a while.

**Comment by joa-quim** [comment]
I don't see the point of keep releasing 5.4.XX versions that have received only a very reduced number of bug fixes. It's a lot of work for very little.

**Comment by claudiodsf** [comment]
Either case, it would be nice to give back manpages to macOS Homebrew users as soon as possible!

**Comment by seisman** [comment]
Closed by #1022. Next GMT5 release (i.e. 5.4.6) will have documentations included.
