### ISSUE TITLE
Contact Fedora maintainers to upgrade GSHHG and DCW data

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3308]
Currently, Fedora 31, 32, and Rawhide (unstable) are providing GMT 6.0.0. However, their DCW and GSHHG are too old. The latest version is DCW 1.1.4 and GSHHG 2.3.7, but they are providing DCW 1.1.1 and GSHHG 2.3.3.

It would be better if we can contact any of the package maintainer to upgrade these two data.

**Comment by PaulWessel** [comment]
That is amazingly old...

**Comment by seisman** [comment]
@opoplawski It seems you're the one maintaining the GMT, dcw-gmt, and gshhg-gmt packages for Fedora. The dcw-gmt and gshhg-gmt data provided by Fedora were released in 2014. Could you please upgrade the data to the latest version? 

The new data are available from 
- dcw-gmt: https://github.com/GenericMappingTools/dcw-gmt/releases/tag/1.1.4
- gshhg-gmt: https://github.com/GenericMappingTools/gshhg-gmt/releases/tag/2.3.7

**Comment by opoplawski** [comment]
Thanks for the updated locations.  I've added release monitoring as well so I'll get notified for new releases in the future.

Updates:
https://bodhi.fedoraproject.org/updates/?packages=dcw-gmt
https://bodhi.fedoraproject.org/updates/?packages=gshhg-gmt-nc4

**Comment by PaulWessel** [comment]
Great, maybe close this one, @seisman ?
