### ISSUE TITLE
We still have exit's in gmt_prototypes.h

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3315]
These guys kill everything. Must replace with ``GMT_exit``
```
/* This macro is called via each modules Return macro so API and options are set */
#define gmt_M_free_options(mode) {if (GMT_Destroy_Options (API, &options) != GMT_OK) exit (GMT_MEMORY_ERROR);}
```

**Comment by PaulWessel** [comment]
Yes, seems awfully harsh to exit.  Does this every happen? I think I put exit there because surely this cannot happen in real life?

**Comment by PaulWessel** [comment]
Also, why the hell is that defined in gmt_prototypes.h and not in gmt_macros.h?

**Comment by joa-quim** [comment]
AFAWK, it never happened but if it does it will be impossible to debug (debuggers don't go into macros).

**Comment by PaulWessel** [comment]
OK, will lower the threat level to orange and meekly do a return...  Also move the macro to its siblings.
