### ISSUE TITLE
Night/Day mask grid from solar?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3316]
**Description of the desired feature**

To do interesting plots involving shading due to the Sun, we have solar that can compute a terminus line as well as Sun position.  However, to make a grid with 0 for dark, 1 for light, and some finite interval of transition, I have to do this in ex52:

 ```
 # Get the location of the Sun at noon on Jun 22, 2000, Hawaii Standard Time
  slon=$(gmt solar -C -o0 -I+d2000-06-22T24:00+z-10)
  slat=$(gmt solar -C -o1 -I+d2000-06-22T24:00+z-10)
  
  # Make a global 6m grid with a smooth transition across day/night boundary.
  # We take advantage of the ATAN function to relatively quickly ramp from 0 to 1
  gmt grdmath -Rd -I0.1 -r --PROJ_ELLIPSOID=sphere $slon $slat SDIST KM2DEG 90 SUB NEG 2 DIV ATAN DUP UPPER DIV 1 ADD 2 DIV = w.grd
```

This is not user friendly.  I have some suggestions:

1. Let grdmath get new operator called SOLAR, SUNLIGHT, DAY, whatever, which takes slon slat width and creates the day grid  (width above is 2 degrees).
2. Make a new module grdsolar for this purpose
3. Let solar have new options (-R -I -r + a grid out) and implement it there.

I do think option 1 is the very simplest.  I would just call solar via GMT_Call_Module and the rest  is inside grdmath.

**Comment by seisman** [comment]
I personally prefer option 2, because grdmath has a complicated syntax (the Reverse Polish Notation) and already has too many operators.

**Comment by PaulWessel** [comment]
OK, I know @joa-quim will agree so we are 2 against 1.  I will make grdsolar.

**Comment by PaulWessel** [comment]
Still thinking about this.  Let me push back a bit.  I know **grdmath** has many operators (223) and RPN is hard.  But adding a full module to do this one thing that only a few people will care about is not necessarily a great solution either.  I suspect the people who can handle setting these things up can figure out how to run 

`grdmath -Rd -I0.1 -r $slon $slat 2 SOLAR = blend.grd`

Making it 224 instead of 223 operators makes no difference to anyone.  Also adding a full module (even with one purpose) still takes a bit of work.  Who is doing that work and how quickly? I can add **SUNLIGHT** in a few hours...

**Comment by seisman** [comment]
I'm OK with the grdmath operator if it's much easier for you.

The command below should work better.
```
grdmath -Rd -I0.1 -r $(gmt solar -C -I+d2000-06-22T24:00+z-10) 2 SOLAR = blend.grd
```

**Comment by PaulWessel** [comment]
With **DAYNIGHT** implemented I am closing this issue.  Up to @joa-quim if he wishes to expand the solar module.
