### ISSUE TITLE
Generate module_core_purpose.rst_ and module_supplements_purpose.rst_ automatically

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3327]
These two files list the purpose of all modules and are used in the documentation.

- doc/rst/source/module_core_purpose.rst_
- doc/rst/source/supplements/module_supplements_purpose.rst_

They were automatically generated by the "gmt_make_module_src.sh" script but the script was removed in #3133. It means we have to manually update these two files and we can get inconsistent module purposes if we make small changes to existing modules.

These two files should be generated automatically to avoid any potential inconsistence.

**Comment by PaulWessel** [comment]
Yes I agree.  I learned this the hard way having to add manual entries for grdmix and batch. Since the order does not matter this may not be as hard to do I think, just grepping for #define THIS_MODULE_PURPOSE and write that rst line.

**Comment by seisman** [comment]
OK. I assign the simple job to myself.
