### ISSUE TITLE
gmt4.5.18 call in matlab

### ISSUE THREAD

**Issue by suiuy** [GenericMappingTools/gmt#336]
*i have installed matlab2016b and GMT4.5.18,i  called psxy in bash,and listed a lot of information.so i think it was installed right.and i add path to matlab.but i don't know how to call GMT in matlab.is there any way to test it.maybe i havn't set link to matlab right.i would appreciate it  if who talks to me.
* Operating system:ubuntu16.04 amd64
* Version of GMT:GMT4.5.18

**Comment by joa-quim** [comment]
Ops, failed to see that you are on Ubuntu. So just forget my last sentence about "no need to set anything". That's for the Windows lucky fellows.

**Comment by PaulWessel** [comment]
Please see http://gmt.soest.hawaii.edu/projects/gmt-matlab-octave-api/wiki and if you take this on let us know how it goes,

**Comment by joa-quim** [comment]
Closing due to lack of feedback.
