### ISSUE TITLE
Auto-legend has some shortcomings

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3362]
**Description of the desired feature**

Currently, the **-l** option for automatic legends has this syntax:

**-l**[_label_][**+d**pen][**+f**_font_][**+g**_gap_][**+h**_header_][**+j**_just_][**+l**[_code_/]_txt_][**+n**_cols_][**+s**_size_][**+v**[_pen_]][**+w**_width_][**+x**_scale_]

For reference, here is the command string we are building to pass to legend during the **gmt end** section:

`-Dj%s+w%gi+o0.2c -F+p1p+gwhite -S%g`

As you can see, the hard-wired parts that remain are the **offset** from the origin, the **fill** color, and the outline **pen**. I have several issues with my initial implementation:

1. We have been very consistent throughout various options that modifier **+g** be used to set a fill (**+g**_fill_).  Yet here I unfortunately invented a gap modifier because **G** is the macro code used by legend.
2. We are also very consistent using **+p**_pen_ to set a pen.  Here, we are setting pen secondarily as the primary modifiers turn on lines.  
3. We also use **+o**_offset_ in numerous places, including in **legend's** **-D** option, but here we have a fixed non-scalable value.

The lack of a fill and and a pen means users cannot easily control the auto-legend's appearance since it is fixed to be white with a black pen.  This may be fine for many users, but I have already run into a case where very light pens don't show very well on the white and it is complicated to move to an explicit call of **legend** to change that.  I think setting the fill will be a much more needed modifier than changing the gap which is usually done for a more complicated and manual layout. A fixed offset also means it won't scale well for different figure sizes.  Finally, I like the consistency of modifiers **+g**,  **+p** and **+o** throughout GMT.

Proposal: Since none of this is yet released, I suggest we do the following:

1. Let **+p**_pen_ set the outline pen used for the frame around the legend [1p]
2. Let **+g**_fill_ set the fill of the frame around the legend [white], and let **+a**_gap_ replace **+g**_gap_ as a much less frequently used modifier.
3. Add **+o**_offset_ to adjust the anchor point away from the reference point.

Would any of you have any problems with these changes, @joa-quim and @seisman ?

**Comment by seisman** [comment]
Implemented in PR #3364. Closing.
