### ISSUE TITLE
Let -o also scale/offset  columns

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3363]
On input we can use **-i** to scale/offset some of the columns, but we don't have the same facility for output (**-o** doesn't offer it). The use case is for example from externals that read some table format or even ``grd2xyz`` if we wanted for example to scale the z column by some value, -1 for example.

**Comment by PaulWessel** [comment]
I think it should not be a bit deal to implement that.  Yet, I vaguely remember there was a reason though.  I will have to look.  It seems pretty clean on output (if o.active, pick the column in the order you wanted, then output.  Should be easy to insert a scaleofffsetlog thing there.
