### ISSUE TITLE
Subplot issues when plotting decorated line

### ISSUE THREAD

**Issue by AlainPlattner** [GenericMappingTools/gmt#3365]
**Description of the problem**

When plotting a decorated line within a 2x2 subplot in a panel in the rightmost column, all subsequent plot commands (including legend) are plotted outside of the panel. This does not happen when plotting a regular line.

**Full script that generated the error**

The following code uses decorated lines and produces wrong results
```
gmt begin map pdf
gmt subplot begin 2x2 -Fs5c/5c
    gmt subplot set 0,0
    gmt basemap -R0/10/0/10 -Baf  
    gmt subplot set 1,1
    gmt basemap -R0/10/0/10 -Baf
    gmt plot -Wblack -S~d1c:+st0.2c+pthick,blue<<EOF
3,3
9,1
EOF
    gmt plot -Wgreen -S~d1c:+si0.2c+pthick,red<<EOF
2,8
6,2
EOF
    gmt legend -F -DjTR<<EOF
S 0.1c c 0.1c blue blue 0.3c bla
EOF
gmt subplot end
gmt end show
```

The following code uses a regular lines and produces a correct result

```
gmt begin map pdf
gmt subplot begin 2x2 -Fs5c/5c
    gmt subplot set 0,0
    gmt basemap -R0/10/0/10 -Baf  
    gmt subplot set 1,1
    gmt basemap -R0/10/0/10 -Baf
    gmt plot -Wblack <<EOF
3,3
9,1
EOF
    gmt plot -Wgreen <<EOF
2,8
6,2
EOF
    gmt legend -F -DjTR<<EOF
S 0.1c c 0.1c blue blue 0.3c bla
EOF
gmt subplot end
gmt end show
```

**Full error message**

No error messages

**Actual outcome**

This is the resulting pdf when using decorated lines (first code)

[mapBad.pdf](https://github.com/GenericMappingTools/gmt/files/4659733/mapBad.pdf)

**Expected outcome**

This is the resulting pdf when using regular lines (second code)

[mapGood.pdf](https://github.com/GenericMappingTools/gmt/files/4659735/mapGood.pdf)

**System information**

* Operating system: Ubuntu 20.04
* GMT version (`gmt --version`): 6.0.0

**Comment by PaulWessel** [comment]
Thanks for pointing this out.  I have fixed it in master and the PR has been merged.

**Comment by AlainPlattner** [comment]
Wow, that was fast! Incredible! Thanks!
