### ISSUE TITLE
Remove gratuitous use of "Unix"

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3369]
**Description of the desired feature**

While GMT is usually used in Unix command line environment, this is clearly no longer the only choice.  Thus I think we should remove the work Unix when not specifically talking about issues related to that OS.  A grep revealed these lines I would target for edits:

`./gmt.rst:GMT is a collection of public-domain Unix tools that allows you to`
Either remove "Unix" or exchange with "command-line"
`./explain_-U_full.rst_:    Draw the GMT Unix System time stamp on the plot.`
Remove "Unix"
`./cookbook/options.rst:The **-U** option draws the GMT UNIX System time stamp on the plot.`
Remove "Unix"
`./cookbook/introduction.rst:GMT software is written as a set of UNIX tools [3]_ and is`
Either remove "Unix" or exchange with "command-line"
./cookbook/introduction.rst:on-line documentation under the UNIX **man** utility or as web
This need some rewriting to push gmt docs.

**Comment by KristofKoch** [comment]
I'd volunteer to change those if you want.

**Comment by PaulWessel** [comment]
Sure, thanks!
