### ISSUE TITLE
Coverity scan link is redirected to a unrelated website

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#337]
**Description of the problem**

Click the link https://scan.coverity.com/projects/gmt, then the website is redirected to https://community.synopsys.com/s/.

**Comment by joa-quim** [comment]
Ho @seisman. Apparently a temporary hiccup only (for users). See Synopsis notice [here ](https://community.synopsys.com/s/article/Coverity-Scan-Update)
