### ISSUE TITLE
Problem with 3D view in modern mode (grdview and coast)

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#3378]
Some days ago I published [this question](https://forum.generic-mapping-tools.org/t/problem-with-3d-view-in-modern-mode-grdview-and-coast/479) in the forum. I have been try to solve but without any luck. I think that the problem with -p (used to plot the sea in a 3D view) is a bug. I try with different zlevel but the sea was plotted always at the bottom of the z-axis.
Should I copy all the info of the forum here again? Or is it not necessary?

* Operating system: Win 10
* GMT version: 6.0.0

**Comment by PaulWessel** [comment]
Sorry, been swamped with other things but we will try to fix this before 6.1 is released.
