### ISSUE TITLE
Script changing the user dir

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3379]
I noticed that two scripts do this:

```
# Must temporarily change GMT_USERDIR to the gallery documentation dir
export GMT_USERDIR=`gmt --show-sharedir`/../doc/rst/source/users-contrib-symbols/geology

```

What happens next is that we check to see if any of the hash and index tables should be updated and lo and behold there are none in the new directory, which by the way we should not write to.  However, we don't know that, the user has changed the userdir to something in the git area.

Per the code, we only look in share and user:

	if (!gmt_getsharepath (GMT, "custom", &name[*pos], ".def", path, R_OK) && !gmtlib_getuserpath (GMT, &file[*pos], path)) {	/* No *.def file found */

Trying

`export GMT_SHAREDIR=`gmt --show-sharedir`/../doc/rst/source/users-contrib-symbols/geology`

does not work either, probably because of the getsharepath looking in a subdir "custom".

**Comment by PaulWessel** [comment]
With **GMT_USERDIR** being the site where remote files are cached, it does not make much sense to temporarily change **GMT_USERDIR** to another place in order to access these files to run the test.  We end up with background maintenance hash tables being written into a server directory in the git repo.  The problem is not so much this one-time script but the fact that lots of tests run in parallel and those will pick up the change adn start writing remote files and hash tables to that place...

One solution is to copy the symbols to the current directory and delete afterwards, since custom symbols will be looked for first in the current directory. 

Another solutions would be to temporarily set **GMT_SHAREDIR** instead and also look in that directory in addition to the subdirs that are specific to each thing.  E.g., "custom" for these symbols.  Currently, I cannot set **GMT_SHAREDIR** because the symbols are not in a "custom"-named directory.  So it would mean when calling 

`gmt_getsharepath (GMT, "custom", &name[*pos], ".def", path, R_OK)`

we would look both in sharedir/custom and sharedir itself.  If "" or NULL is passed as subdir we only look in sharedir.

What do you think, @seisman ? Meanwhile I may go with Plan A above to avoid more files being written...

**Comment by PaulWessel** [comment]
Actually, I think my proposed change to getsharepath makes most sense.  the sharepath is a read-only directory so temporarily changing it to serve a specific need is fine, unlike userdir which is a read and write area.

**Comment by PaulWessel** [comment]
While this is a good change, it wont necessarily fix the test suite because it seems that other scripts running in parallel picks up on the change, so if GMT_SHAREDIR is set to another dir we probably will get errors of not finding GMT master cpt tables...
I think the only failsafe method for these tests is to not change those parameters but copy the files temporarily in the local directory that the test uses per test.

**Comment by seisman** [comment]
> With **GMT_USERDIR** being the site where remote files are cached, it does not make much sense to temporarily change **GMT_USERDIR** to another place in order to access these files to run the test.

Yes, I agree. I don't think users have the need to temporarily change GMT_SHAREDIR and GMT_USERDIR. 

For the two tests, copying these files seems to be the easiest way.

**Comment by PaulWessel** [comment]
Implemented and merged.
