### ISSUE TITLE
Doc about "psxy -Sv"

### ISSUE THREAD

**Issue by haibo-wang-seis** [GenericMappingTools/gmt#3406]
The doc about "psxy -Sv" says,
"-Sv
vector. **Direction** (in degrees counter-clockwise from horizontal) and **length** must be found in columns 3 and 4, and **size**, if not specified on the command-line, should be present in column 5. The size is the length of the vector head. "

So, if I do not specified the size on the command-line, I should give a table in this manner "x y direction length size".

After some tests, I find, if the size is not specified on the command-line, the table should be "x y size direction length" not "x y direction length size" .

e.g.,
```
gmt psxy -R0/50/-50/50 -JX6i -Sv0.2c+bc+ea -Gyellow -P -W0.5p -Baf -K << EOF > map.ps
10 10 45 2i
30 10 0 1.5i
EOF
gmt psxy -R0/50/-50/50 -JX6i -Sv+bc+ea -Gyellow -P -W0.5p -Baf -O << EOF >> map.ps
10 0 0.2c 45   2i
30 0 0.2c 0    1.5i
EOF
```

* Operating system: macOS Mojave
* GMT version (`gmt --version`): 6.0.0 (classic model)

**Comment by seisman** [comment]
Ping @PaulWessel to check whether it's a bug or a documentation error.

**Comment by PaulWessel** [comment]
Sorry, yes the poster is correct. The start of the -S explanation says as much, but then -Sv says it wrong.  I will fix now.
