### ISSUE TITLE
Color the corners of fancy borders not just plain white

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#3409]
**Description of the desired feature**

Currently the corners of `fancy` and `fancy+` borders are simply white regardless of the color of the adjacent border. See the images in the upper row:

![corners](https://user-images.githubusercontent.com/45796239/82306273-1f3b3a80-99bf-11ea-9ff9-b0d74ff5e14c.jpg)

I would prefer the behavior in the lower row with the adjacent border color filling the corner up to its bisectrix. In my eyes this makes for a more eye-pleasing corner.

This issue is made from my post in issue #3344. I feel it should be separated form the discussion over there.

**Comment by KristofKoch** [comment]
As my feature request hasn't seen any activity in a year – is it worth keeping it around or should I let it silently die?

**Comment by PaulWessel** [comment]
Keep it there.  I did look briefly when first posted but it was not an easy thing to add so it did not get a high mental priority...
