### ISSUE TITLE
Simpler options to get or remove remote data and cache files

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3412]
**Description of the desired feature**

We currently have a shell script in share/tools (_gmt_getremote.sh_) that can be used to download all the cache and/or data files.  However, this is not cross-platform and hence not an ideal solution. We are also planning to expand the remote file service to serve data from other planets than earth.  This combination leads to this proposal:

1. Let the rarely used **gmtget** module gain a new option **-D** for download.  It would take various directives: **all** for all cache and all data, **cache** for just cache, **data** for just data, and _planet_ for just data for that planet.
2. Let **gmt clear** _data_ take the optional directive _planet_.  This restricts the deleting to just data for that planet.

The alternative to (1) above might be gmtwhich, but given the names of the modules I think this is a good new task for gmtget.

Thoughts, @seisman and @joa-quim ?

**Comment by joa-quim** [comment]
You mean in 1. **gmtget** right? Yest it's a good name for such purpose.

**Comment by PaulWessel** [comment]
Yes I mean lets add this feature to the existing (and very rarely used) module **gmtget**.  I think gmtset is used quite a bit, but gmtget is its unknown cousin.

**Comment by seisman** [comment]
OK with the decision, but we need to update the gmtget module purpose accordingly.

**Comment by PaulWessel** [comment]
Yes.  However, I won't start this work until the remote tile/etc stuff is working.

**Comment by seisman** [comment]
Implemented in #3370. Closed.
