### ISSUE TITLE
Wrong tag date in gmt binary

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3419]
Build it today with the ``new-remote-files`` branch and
```
$ gmt --version
6.1.0_bea4b7d_2020.05.22
```

**Comment by seisman** [comment]
You're building the commit https://github.com/GenericMappingTools/gmt/commit/bea4b7d 12 days ago. Perhaps you didn't update your local branch correctly?

**Comment by joa-quim** [comment]
That's what happen when you make me do things early in the morning. I did change the branch but forgot to do a ``git pull``. That's why I had so many test failures.
Running them again.
