### ISSUE TITLE
accessing /vsicurl/http  files no longer works

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3425]
```
 grdinfo /vsicurl/http://larryfire.files.wordpress.com/2009/07/untooned_jessicarabbit.jpg
grdinfo [ERROR]: File /vsicurl/http://larryfire.files.wordpress.com/2009/07/untooned_jessicarabbit.jpg was not found
grdinfo [ERROR]: Cannot find file /vsicurl/http://larryfire.files.wordpress.com/2009/07/untooned_jessicarabbit.jpg
grdinfo [ERROR]: Must specify one or more input files
```
 but gdalinfo works

```
 gdalinfo /vsicurl/http://larryfire.files.wordpress.com/2009/07/untooned_jessicarabbit.jpg
Driver: JPEG/JPEG JFIF
Files: /vsicurl/http://larryfire.files.wordpress.com/2009/07/untooned_jessicarabbit.jpg
Size is 1097, 1024
Metadata:
  EXIF_ColorSpace=65535
  EXIF_DateTime=2008:04:19 11:26:14
...
```

**Comment by PaulWessel** [comment]
I see we have checks for /vsi*/ but clearly something is broken.  Will deal with this after our TGIF seminar.

**Comment by joa-quim** [comment]
``gmt_M_file_is_url`` does not check for them

**Comment by PaulWessel** [comment]
Yep, so never makes it into the grd read machinery where these are handled.

**Comment by joa-quim** [comment]
But even before that, ``gmt_set_remote_and_local_filenames()`` jumps out because

```
	if (file[0] == '/' || file[1] == ':')
#else
	if (file[0] == '/')
#endif
	{
		clean_file = gmt_get_filename (API, file, "honsuU");	/* Strip off any file modifier or netCDF directives */
		if (access (clean_file, F_OK)) {
			GMT_Report (API, GMT_MSG_ERROR, "File %s was not found\n", file);
			gmt_M_str_free (clean_file);
			return GMT_FILE_NOT_FOUND;
		}
```

**Comment by PaulWessel** [comment]
I am on it.

**Comment by joa-quim** [comment]
and even if I make it jump that test it will later try to download the file with curls. It should not do this but pass the hand to gdal instead. Seems the tiling work stripped the gdal machinery to do remote accesses.

**Comment by PaulWessel** [comment]
Got it to work.  Running tests first , the PR.

**Comment by PaulWessel** [comment]
By virtue of getting into readgrid it will also address #3424.

**Comment by PaulWessel** [comment]
I may want to change the name of gmtlib_check_url_name since its name does not describe well what it does.

Maybe gmtlib_check_if_url_is_vsi  ?

**Comment by joa-quim** [comment]
It's not only *vsi*, this started when I tried to read a WCS file
```
gdalinfo WCS:https://elevation.nationalmap.gov:443/arcgis/services/3DEPElevation/ImageServer/WCSServer?version=2.0.1&coverage=DEP3Elevation
```
and we have also the WMS (Web Map Server) files. I don't know how to use them but we will want to do that in future. So please redefine the macro as

```
#define gmt_M_file_is_url(file) (file != NULL && (!strncmp (file, "http:", 5U) || !strncmp (file, "https:", 6U) || !strncmp (file, "ftp:", 4U) || !strncmp(file, "/vsi", 4U) || !strncmp(file, "WCS:", 4U) || !strncmp(file, "WMS:", 4U)))
```

**Comment by PaulWessel** [comment]
I can, but you are mixing the macro with your function.  This is the function you wrote:

```
bool gmtlib_check_url_name (char *fname) {
	/* File names starting as below should not be tested for existence or reading permissions as they
	   are either meant to be accessed on the fly (http & ftp) or they are compressed. So, if any of
	   the conditions holds true, returns true. All cases are read via GDAL support or other. */
	if (gmt_M_file_is_url (fname) ||
	    !strncmp(fname,"/vsizip/", 8)  ||
	    !strncmp(fname,"/vsigzip/",9)  ||
	    !strncmp(fname,"/vsicurl/",9)  ||
	    !strncmp(fname,"/vsimem/", 8)  ||
	    !strncmp(fname,"/vsitar/", 8)) {
#ifdef WIN32
		/* On Windows libcurl does not care about the cerificates file (see https://github.com/curl/curl/issues/1538)
		   and would fail, so no choice but prevent certificates verification.
		   However, a CURL_CA_BUNDLE=/path/to/curl-ca-bundle.crt will overcome this and will consult the crt file. */
		if (!getenv ("GDAL_HTTP_UNSAFESSL") && !getenv("CURL_CA_BUNDLE"))
			putenv ("GDAL_HTTP_UNSAFESSL=YES");
#endif
		return true;
	}
	else
		return false;
}
```

Since it can check for all the /vsi flavors it is safer than my strcmp just on /vsi i think.  OK, so not vsi specific but certainly gdal read specific, no? Maybe

gmtlib_check_if_url_for_gdal ?

**Comment by joa-quim** [comment]
and in gmtlib_check_url_name (or whatever name) make it

```
	if (gmt_M_file_is_url (fname) ||
	    !strncmp(fname,"WCS:", 4)  ||
	     !strncmp(fname,"WMS:", 4)  ||
	    !strncmp(fname,"/vsi",4) )
        {
```
because there are more *vsi* types.

**Comment by joa-quim** [comment]
ok, some cross postings.

**Comment by PaulWessel** [comment]
So I need to remove the _GMT_M_file_is_url_ call in your function because I need to ability to separate these special addresses that need to to go GDAL from regular URLS (that need to go to libcurl).  So I will break that up and rename the function accordingly.

**Comment by joa-quim** [comment]
Yes, though ideally all url used by grdinfo, except, those pointing to netcdf files, should be done via gdal because it doesn't download the file first.
The shit with the nc files is that the remote access does not work and distinguishing them by extension does not work either.
