### ISSUE TITLE
CentOS install

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3433]
Got fresh install of CentOS 8. Trying our install prerequisite page:

sudo yum install cmake libcurl-devel netcdf-devel

Fails with nothing provides libsz.so needed by netcdf-devel-...
Suggests adding --skip-broken or --nobest, etc.  Not ideal I think?

**Comment by seisman** [comment]
I think it's a bug of the EPEL netcdf-devel package. 

The netcdf-devel package requires libsz.so (see https://centos.pkgs.org/8/epel-x86_64/netcdf-devel-4.7.0-2.el8.x86_64.rpm.html for a list of netcdf-devel's requirements). However, the package [libaec](https://centos.pkgs.org/8/centos-powertools-x86_64/libaec-1.0.2-3.el8.x86_64.rpm.html) which provides libsz.so is in another repository called **CentOS PowerTools**. This repository is not enabled by default. 

Perhaps you can try if enabling PowerTools following this (https://serverfault.com/questions/997896/how-to-enable-powertools-repository-in-centos-8) works for you.

**Comment by PaulWessel** [comment]
Interesting that basic installs are so cumbersome. Following the powertools link worked.  Got to the very end but

`sudo yum install python-sphinx
`

says unable to find a match.

**Comment by seisman** [comment]
There is no `python-sphinx` on CentOS 8, only `python3-sphinx`.

CentOS 6 and 7 have both.

**Comment by PaulWessel** [comment]
OK, shall I try the python3 one then?

**Comment by seisman** [comment]
Yes.

**Comment by PaulWessel** [comment]
Thanks, install works.  Up to you if you want to update the wiki.

**Comment by seisman** [comment]
The wiki is updated.

**Comment by PaulWessel** [comment]
Thanks
