### ISSUE TITLE
-B0 should default to --MAP_FRAME_TYPE=plain

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3439]
Certainly not what is expected
```
gmt psbasemap -JB-96/22/29.5/45.5/6i -R-130/-64/22/52 -B0 -png map
```
![map](https://user-images.githubusercontent.com/537321/83986308-3cb35280-a934-11ea-806e-c3051648be79.png)

**Comment by PaulWessel** [comment]
Yes, that looks lame. Will need to catch that.
