### ISSUE TITLE
A bit more granularity in gmt get

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3443]
**Description of the desired feature**

As more Earth datasets are added, not all may be of interest to all users.  Yet, if you run

gmt get -Ddata=earth -I01m

you are getting DEMs, masks, and day/night images, and soon geopotentials.  It may be helpful to add a further sub-selection.  Perhaps

`gmt get -Ddata=planet+set=list -Iinc`

E.g.,

gmt get -Ddata=earth+set=relief,mask -I01m

**Comment by seisman** [comment]
Yes, but the proposed syntax `gmt get -Ddata=earth+set=relief,mask -I01m` is different from other GMT syntax, which mixes single-character (**-D**) and long-format (**+set**) options/modifiers.

**Comment by seisman** [comment]
What about the syntax like below:
```
gmt get  -Dcache -Ddata=earth_relief -Ddata=earth_mask  -I01m
```

**Comment by PaulWessel** [comment]
Hm, I'd like to avoid repeated uses of an option - we rarely do in GMT.

Maybe

gmt get -Ddata=planet|list -Iinc

gmt get -Ddata=earth_relief,earth_mask -I01m

**Comment by seisman** [comment]
I like this one:
```
gmt get -Ddata=earth_relief,earth_mask -I01m
```
