### ISSUE TITLE
MB-System build fails due to missing GMT header file gmt_remote.h

### ISSUE THREAD

**Issue by dwcaress** [GenericMappingTools/gmt#3449]
I'm following up on a bug report to me - a user is trying to build a new MB-System pre-release distribution with GMT downloaded from your master branch (which is to say, bleeding edge stacked on bleeding edge...). 

I've verified this using the state of the GMT master branch a bit earlier this afternoon. The downloaded current GMT was build and installed without issue. The MB build fails fails with the error message:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src/mbio -I../../src/mbio -I../../src/mbtrn/r7kr -I../../src/mbtrn/utils -I../../src/mbtrn/mframe/src -I/usr/local/include/gmt -I/usr/local/Cellar/gdal/2.4.4_4/include -I/usr/local/Cellar/netcdf/4.7.4/include -g -I/opt/X11/include -MT mb_readwritegrd.lo -MD -MP -MF .deps/mb_readwritegrd.Tpo -c mb_readwritegrd.c  -fno-common -DPIC -o .libs/mb_readwritegrd.o
In file included from mb_readwritegrd.c:29:
/usr/local/include/gmt/gmt_dev.h:164:10: fatal error: 'gmt_remote.h' file not found
#include "gmt_remote.h"          /* GMT type declarations */

It appears that the new header file gmt_remote.h is referenced in gmt_dev.h but is not actually installed with the other GMT header files in /usr/local/include/gmt/

I'm working on a Mac, with most GMT prerequisites installed with Homebrew.

**Comment by PaulWessel** [comment]
Yep sorry, recent development and with gmt_remote.h now addressed in gmt_dev.h we needed to add it to the CMakeLists.txt for distribution.  Done in #3450 once the PR is accepted and merged.

**Comment by PaulWessel** [comment]
Problem addressed, just pull a fresh master.

**Comment by dwcaress** [comment]
Thanks Paul.

> On Jun 8, 2020, at 6:08 PM, Paul Wessel <notifications@github.com> wrote:
> 
> 
> Problem addressed, just pull a fresh master.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775
