### ISSUE TITLE
histogram: -G doesn't work for stairs-step diagram (-S)

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3451]
```
gmt histogram  @v3206_06.txt -F -T250 -W0.25p -S -Glightblue -B -png plot
```
Output:

![image](https://user-images.githubusercontent.com/3974108/84099618-05967d00-a9d8-11ea-8316-10bd93c805a8.png)

**Comment by PaulWessel** [comment]
Never implemented I think, and I actually needed this a few days ago...  Will look.
