### ISSUE TITLE
Silent install hangs with PATH error on Win64

### ISSUE THREAD

**Issue by toxicbubble** [GenericMappingTools/gmt#3457]
When running the installer for gmt-6.0.0-win64.exe on a Windows 10 1909 PC, no previous versions of GMT installed at all, this error pops up:

![image](https://user-images.githubusercontent.com/13129267/84225433-350dcc80-ab33-11ea-9e80-ab0882c06536.png)

**Warning! Failed to add GMT to PATH. Please add the GMT bin path to PATH manually.**

I've seen it suggested on a Chinese forum that it may be because the existing PATH environment is too long. I'm not sure the root cause, easy enough to edit PATH myself, and dismissing the error does continue and complete the install. 

However, the issue occurs when running "gmt-6.0.0-win64.exe /S" (the nullsoft /S silent installer switch), the interactive GUI error is still displayed, and the install will hang until it's dismissed. The error still displays even if I've already added the GMT installdir\bin to PATH before starting the install. This makes automated\silent install impossible. 

Ideally, whatever's causing the issue editing PATH in the first place could be fixed. Alternately, the error prompt should respect the /S switch and not display in silent\unattended install mode.

**Comment by joa-quim** [comment]
This should be solved, I think.
