### ISSUE TITLE
Error during first-time installation

### ISSUE THREAD

**Issue by marrett** [GenericMappingTools/gmt#3478]
**I am a first-time user trying to install GMT for the first time, and I have used Terminal only a handful of times since OSX came out.  I followed [instructions](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md) and used Homebrew as indicated.  Outcomes appeared normal until I entered "brew install gmt", which led to what I assume was an aborted installation:
![Screen Shot 2020-06-15 at 7 50 06 AM](https://user-images.githubusercontent.com/15524368/84677952-a8755c80-aeec-11ea-82aa-cebcd5625e2e.png)

**in Terminal:
RexMadison-Lending-Library-03:~ randallmarrett$ brew install gmt
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.2.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/1b/1bbea4983a4c883c8eb8b7e19df9fab52f0575be8a34b629fc7df79895f48937?__gda__=exp=
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/isl-0.22.1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/29/29213891860c971e084d1e2a3d1ad00c92371140dea599aae2894e26ec0d6874?__gda__=exp=
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.0.2.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/cf/cfce7ab866e98360c9364cd924da620ae7936d3a224d686aacc209c2107d19aa?__gda__=exp=
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.1.0.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/gcc-9.3.0_1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/de/de8319322428721741a0dc41dfdf2eece80e0215a7a4a861e0e206a9bfbca583?__gda__=exp=
#########################################################                 79.6%
curl: (18) transfer closed with 18046872 bytes remaining to read
Error: Failed to download resource "gcc"
Download failed: https://homebrew.bintray.com/bottles/gcc-9.3.0_1.mojave.bottle.tar.gz
**

**System information**

* Operating system:  macOS Mojave version 10.14
* GMT version (`gmt --version`):  gmt-6.0.0-darwin-x86_64.dmg

**Comment by seisman** [comment]
Your brew failed to download the gcc package, most likely due to temporary bad internet connections. Try to run the `brew install gmt` command again.

**Comment by seisman** [comment]
BTW, please post general questions on the [GMT Community Forum](https://forum.generic-mapping-tools.org/) instead.

**Comment by joa-quim** [comment]
And please use the forum to ask this kind of questions. This is no GMT bug.
