### ISSUE TITLE
Images and GMT

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3481]
As the failures in #3479 and another reported side-effect in **grd2kml** shows, the image handling in GMT is not well documented or consistent.  My understanding is that it has to do with the two different ways that GMT handles images with transparency, which needs to be flexible because PostScript, externals, and GMT itself have different expectations:

1. Transparency may be given as a 2nd (for grayscale) or 4th (for color) band in the image data (I->data array)
2. To add transparency to an image (either when creating one from scratch) or adding it to an existing image, we use a separate alpha array in the image (I->alpha).
3. At other times we will want to create that 4th image layer instead and place transparency there.

The solution to this will be to pass suitable modes when creating the image.  I suggest we add a new flag **GMT_IMAGE_ALPHA_LAYER**. When _GMT_Create_Data_ is given **GMT_IS_IMAGE**|**GMT_IMAGE_ALPHA_LAYER** then  if transparency is specified (2 or 4 layers are requested), then we allocate an image array for 2 or 4 bands.  Otherwise, we allocate 1 or 3 layers **and** the separate alpha array.

This would let us either create images with space for transparency directly in the image or images with separate alpha array that is then merged by GDAL when writing a file.  This way, the existing default remains to use the alpha array. At the same time, we fix a bug that also allocated 4 bands **and** the alpha array.

Did I miss a case here, @joa-quim? I think **GMT_IMAGE_ALPHA_LAYER** may be passed in GMT_Read_Data as well for images so that the returned image has the expected information.

**Comment by joa-quim** [comment]
There is yet another way to set transparency in gdalwrite but it doesn't involve any array. See references for ``GDALSetRasterNoDataValue`` (an index for a cpt entry). I make use of it from Julia but don't remember if from anywhere else.

**Comment by PaulWessel** [comment]
So I will go forth and implement the above in the branch I am working on.
