### ISSUE TITLE
gmtsimplify outputs plot related info

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#3484]
Just used `gmtsimplify`. I'm on the `gmt-themes`-branch. I was surprised when I got this:

```
gmtsimplify [NOTICE]: Computed primary annotation font size: 6.66667 p  Dimension scaling: 0.666667
```

Is and should not be *bug* report, but why the h*ll not. Better safe, than sorry.

**Comment by PaulWessel** [comment]
the NOTICY is just there while testing this branch.  It becomes DEBUG (-Vd) once we merge.

**Comment by anbj** [comment]
Alright, good to know. Closing.
