### ISSUE TITLE
movie is broken on Windows

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3500]
It's broken because this code fall into the error branch
```
if (sscanf (movie_item_arg[k][T], "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[GMT_X], &clearance[GMT_Y], PP, FF, font, label) != 9) {
				GMT_Report (GMT->parent, GMT_MSG_ERROR, "Unable to parse MOVIE_LABEL_ARG %s for 9 required items\n", movie_item_arg[k][T]);
				return NULL;	/* Should never happen */
			}
```
Now debugging it is very hard, so made a little program that replicates that parsing and ... surprises

Compile and run this program. You will see that it prints ``Read 0``. However, swapping the commented ``if`` lines will print ``Read 9``, which is the expected.

Now, I get that exact same behavior whether I compile it with VS or Cygwin's gcc. So how the hell the movie works for you???????????? 

```
#include <stdio.h>

int main() {

	char buf[] = "L 0.0555556 5.94444 0.00555556 0 9 0.0416667 0.0416667 - - - - 20p,Helvetica,black 001";
	char FF[64] = {""}, PP[64] = {""}, font[64] = {""}, label[64] = {""};
	int justify, k;
	double clearance[2] = {0.0, 0.0};
	double plot_x, plot_y;

	if (k = (sscanf(buf, "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[0], &clearance[1], PP, FF, font, label)) != 99);
	//if ((k = sscanf(buf, "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[0], &clearance[1], PP, FF, font, label)) != 99);
		fprintf(stderr, "Read %d\t%f\t%f\n", k, plot_x, plot_y);

	return 0;
}
```

**Comment by PaulWessel** [comment]
After fixing a few errors in your code, it runs and gives 9 for both lines.  The two sscanf lines looks identical to me - what am I missing?

**Comment by PaulWessel** [comment]
BTW, this is with either Apple clang or GNU gcc9.  I am staring and staring and cannot see anything syntactically wrong with that sscanf statement.  So the question why is Windows expecting that is different?

**Comment by PaulWessel** [comment]
You can try replacing \n with \0 at the end of that line and see - may give warning.

**Comment by PaulWessel** [comment]
On Windows, that raw record read in may end in \r\n perhaps? So then the \n will not work.  Maybe try to use gmt_chop on the input record first, and then use \0 (or I think \n then is OK) to see how that goes.

**Comment by joa-quim** [comment]
My program compiles in gcc with no warnings
![image](https://user-images.githubusercontent.com/537321/85172290-a56dc980-b268-11ea-8caf-77d8b278b12e.png)

![image](https://user-images.githubusercontent.com/537321/85172380-d817c200-b268-11ea-980e-9bc11e621f51.png)

The differences between the two versions is the position of the parenthesis ``(``
```
(k = (sscanf(buf,
```
vs
```
if ((k = sscanf(buf,
```
I don't f understand why, but the fact is.

**Comment by joa-quim** [comment]
Same in WSL gcc
![image](https://user-images.githubusercontent.com/537321/85172849-d1d61580-b269-11ea-8bcc-755c391f79bd.png)

**Comment by PaulWessel** [comment]
I know, the wrong placement of parenthesis and the extra semi-colon at the end of the if. Sorry, are you saying that the different assignments to k give different answers?  There is only one way to do this:  (k = sscanf (...)).  Did you tru the \r\n stuff and \0 suggestions?  That is the only thing I can think of would trip you up.  the rest is basic C sscanf syntax.

**Comment by PaulWessel** [comment]
Furthermore, it seems to ahve read both plot_x and plot_y so that is at least two conversions, so k = 1 is cleary not correct.

**Comment by joa-quim** [comment]
Sorry, what ``\r\n``? I'm reading from the static ``buf[]`` variable. No new lines in it and this is not a *Windows* thing. I get exactly the same in WSL (and Cygwin).

I'm printing the ``plot_x, plot_y`` to show that it reads well but returns a wrong number of read values and that's what triggers the error.

To me both forms of the ``k`` assignment seem correct, but compilers think differently.
The ``;`` at end is because I was playing with the ``if`` and no ``if`` form and left it behind.

**Comment by PaulWessel** [comment]
OK, never mind the \r\n for your label.c program of course - I was talking about the actual i/o.

I also don't quite understand what you are trying to say: Are you saying that

1. My sscanf syntax is wrong? If so, what is it?
2. The Windows sscanf is broken?
3. Other system's sscanf are broken?

Does @seisman see any bugs here?

**Comment by PaulWessel** [comment]
sscanf shall return the number of items it assigned, so k = 1 is worrisome given the plot_y assignment.

**Comment by PaulWessel** [comment]
OK, sorry:

	if (k = (sscanf(buf, "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[0], &clearance[1], PP, FF, font, label)) != 99);

will return 1 because you are assigning the result of comparing what sscanf returns to ~= 99.  And yes, sscanf doees not return 99 so the comparison is true, hence 1.

Which is why we use if ((k = sscanf (...)) != 99)

**Comment by joa-quim** [comment]
I'm only saying that:
- what seems to be the correct syntax is returning a wrong value.
- the other syntax, that also seems correct to me, is returning the right answer.
- I have no idea why.

**Comment by joa-quim** [comment]
At a point I thought on that too. Used the !99 to force printf (lazy). But make the it
```
if (k = (sscanf(buf, "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[0], &clearance[1], PP, FF, font, label)) != 9) {}
```
Now it prints
```
C:\v>label
Read 0  0.055556        5.944440
```

**Comment by PaulWessel** [comment]
So that means it read 9, and since 9 != 9 is false you get 0.

**Comment by joa-quim** [comment]
Yes, I deleted the post when I realized that.

**Comment by PaulWessel** [comment]
Having zoom now so offline for 30 minutes.

**Comment by joa-quim** [comment]
I may be dinning then.
But, in my toy program
```
	if ((k = (sscanf(buf, "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[0], &clearance[1], PP, FF, font, label))) != 9)
		fprintf(stderr, "Read1 %d\t%f\t%f\n", k, plot_x, plot_y);

	fprintf(stderr, "Read2 %d\t%f\t%f\n", k, plot_x, plot_y);
```
correctly prints
> Read2 9 0.055556        5.944440

So WTF is the difference for the ``gmt_plot`` case that when I change it to
```
if ((kk = (sscanf (movie_item_arg[k][T], "%*c %lg %lg %*s %*s %d %lg %lg %s %*s %s %*s %s %[^\n]", &plot_x, &plot_y, &justify, &clearance[GMT_X], &clearance[GMT_Y], PP, FF, font, label))) != 9) {
	GMT_Report (GMT->parent, GMT_MSG_ERROR, "Unable to parse MOVIE_LABEL_ARG %s for 9 required items\n\tJust read %d\n", movie_item_arg[k][T], kk);
```
prints
```
coast [ERROR]: Unable to parse MOVIE_LABEL_ARG "L 0.0555556 5.94444 0.0416667 0 9 0.0416667 0.0416667 - - - - 20p,Helvetica,black 014" for 9 required items
        Just read 0
```

Can't be a ``\n`` because the string is printed and no line change occurs. And besides that string comes from
```
gmt_chop (record);
...
movie_item_arg[k][n_movie_items[k]++] = strdup (record);
```

**Comment by joa-quim** [comment]
Found one bug. ``movie_item_arg[2][GMT_LEN32];`` (which is clearly too short, again *nix compilers don't care) but later
```
movie_item_arg[k][n_movie_items[k]++] = strdup (record);
```
where records is ``record[GMT_LEN256] = {""};``
However, fixing it it's still not the cure.

**Comment by PaulWessel** [comment]
movie_item_arg is an array of points (up to 32 for labels and progress indicators) not the length of the string.  so strdup () returns the pointer to whatever allocated string is returned and that pointer is stored in the array.  So it is not too short unless we have more than 32 labels on one frame.

**Comment by PaulWessel** [comment]
See #3501 as possibly a fix.

**Comment by joa-quim** [comment]
No, not yet.
```
coast [ERROR]: Unable to parse MOVIE_LABEL_ARG "L 0.0555556 5.94444 0.0555556 0 9 0.0416667 0.0416667 - - - - 20p,Helvetica,black 019" for 9 required items [only made 0 or 9 conversions]
```
but if I replace  ``movie_item_arg[k][T]`` by ``"L 0.0555556 5.94444 0.0555556 0 9 0.0416667 0.0416667 - - - - 20p,Helvetica,black 019"``
then that lines works and the same type of error occurs further down.
```
coast [ERROR]: Unable to parse MOVIE_PROG_INDICATOR_ARG "a 5.94444 5.94444 0.0638889 0.3 11 0.0416667 0.0416667 - - lightred lightgreen 14p,Helvetica,black " for 14 required items [only made 1 of 13-14 conversions]
```
We are clearly in presence of a memory corruption.

**Comment by PaulWessel** [comment]
I think we should just accept the no-enviroment branc (#3499 ) because I am now distrustful of the passing of all those strings in and out of the environment.  This bypasses that entirely so then we can see if perhaps this problem simply goes away.  The branch passes find for me.  It even did not give the usual gdal_nn crash...

**Comment by joa-quim** [comment]
OK, commit it and work from it in case of need.

**Comment by PaulWessel** [comment]
OK, I have merged #3499 into master and also into the #3501 branch.  Please update that one and try again,

**Comment by joa-quim** [comment]
And that was it, I'm getting a nice spinning globe. Uff

**Comment by joa-quim** [comment]
Even from Julia
```
julia> movie("main_sc.jl", pre="pre_sc.jl", C="7.2ix4.8ix100", N=:anim04, T="flight_path.txt", L="f+o0.1i", F=:mp4, A="+l+s10", Vd=1)
        movie main_script.bat -C7.2ix4.8ix100 -Nanim04 -Tflight_path.txt -A+l+s10 -Fmp4 -Lf+o0.1i -Sbpre_script.bat
movie [NOTICE]: Running: gm convert -delay 4 -loop 0 +dither anim04/anim04_*[0].png anim04.gif
movie [NOTICE]: Running: ffmpeg -loglevel warning -f image2 -framerate 24 -y -i "anim04/anim04_%02d.png" -vcodec libx264  -pix_fmt yuv420p anim04.mp4
```

**Comment by PaulWessel** [comment]
We may be getting older, but still learning.  When will it stop...

**Comment by joa-quim** [comment]
I'm proud of my Julia version (I mean that of the movie). It's a piece of imagination ... but with fragilities.

**Comment by joa-quim** [comment]
> When will it stop...
With luck we won't notice.
