### ISSUE TITLE
Wrong master CPT for shading?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3511]
I'm using the latest master branch `6.1.0_885f4fa_2020.06.20` and running the following two commands:
```
gmt grdimage @earth_relief_01m -RMG+r2 -V -png noshading
gmt grdimage @earth_relief_01m -RMG+r2 -V -I+d -png shading
```
The verbose message tells me that the first one uses the *geo* cpt, and the second one uses turbo. It's not correct, but why no tests fail? Something wrong with my laptop because I have multiple GMT versions installed?

Here are my results. Please check if you have the same issue.

**noshading.png:**
![image](https://user-images.githubusercontent.com/3974108/85214911-93ab2580-b33f-11ea-9c53-3b2c0564bf02.png)

shading.png:

![image](https://user-images.githubusercontent.com/3974108/85214913-986fd980-b33f-11ea-82dd-46de52c05792.png)

**Comment by PaulWessel** [comment]
Will check once done with another branch check.

**Comment by PaulWessel** [comment]
I get the same as you.  Will check.

**Comment by PaulWessel** [comment]
I know this has to do with a failed check for earth_relief_ since the 01m is tiled and hence grdblend returns something named differently...

**Comment by PaulWessel** [comment]
We need a more general solution.  The old scheme worked when we had single large remote grids called earth_relief.  Now we have many different remote grids and not all are topographic relief.  I can imagine that some other remote grids may want their own default CPT tables, e.g., gravity, ages, etc.  I think the best way for this is to include the master cpt (or -) in the gmt_data_server.txt table.  Then I can fish the master CPT from the information array.

**Comment by seisman** [comment]
It sounds a good solution.

**Comment by PaulWessel** [comment]
Sigh, do you remember the URL we used for the test server? I had to remove the forward since our IT people were testing something else.  I think we just did http://gmtserver.soest.hawaii.edu/test/server/... ?

**Comment by seisman** [comment]
Do you mean this URL http://test.generic-mapping-tools.org?

**Comment by PaulWessel** [comment]
Yes.  Hm, I will set up the forward since I cannot get plain curl to work:

curl -k -O http://gmtserver.soest.hawaii.edu/test/gmt_data_server.txt
curl -k -O http://gmtserver.soest.hawaii.edu/gmt/test/gmt_data_server.txt

I guess it cannot work without that forward.

**Comment by PaulWessel** [comment]
Darn it, cannot recall the exact details.  I set this up - I guess it will work or not:

![Untitled](https://user-images.githubusercontent.com/26473567/85216234-bcbabe80-b31d-11ea-8e4a-cfac32fcfe15.png)

Not sure if the /gmt/ is needed for the gmtserver forward.

**Comment by seisman** [comment]
Perhaps you can try http://www.soest.hawaii.edu/gmt/test

**Comment by seisman** [comment]
Fixed in #3513.

**Comment by PaulWessel** [comment]
Must be update Monday.  So apparently GDAL 3.1.0 was attempted installed overnight.  Failed.  Running the update manually (this is macports) ended with the usual

```
Error: Failed to build gdal: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
pwessel@macnut:~-> e /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/main.log
```

The log is not very useful and ends with

```
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/work/gdal-3.1.0/gdal/frmts/pcraster'
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/work/gdal-3.1.0/gdal/frmts/jpeg'
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/work/gdal-3.1.0/gdal/frmts'
:info:build make: *** [frmts-target] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/work/gdal-3.1.0/gdal'
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/work/gdal-3.1.0/gdal" && /usr/bin/make -j24 -w 
:info:build Exit code: 2
:error:build Failed to build gdal: command execution failed
:debug:build Error code: CHILDSTATUS 95033 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec build"
:debug:build     (procedure "portbuild::build_main" line 8)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_gdal/gdal/main.log for details.
```

Any suggestions how to deal with this, again.  Rebuilding GMt then yields this:

```
pwessel@macnut:~-> gmt grdinfo t.nc -Vd
dyld: Library not loaded: /opt/local/lib/libqhull.7.dylib
  Referenced from: /opt/local/lib/libgdal.27.dylib
  Reason: image not found
Abort trap: 6
```

So I cannot check if the server works.

**Comment by PaulWessel** [comment]
Well I am not alone.  The idea that they only test the basic build (without the variants) does not pass my sanity test.  I need the openjpeg stuff and they do not include it in their base...
https://trac.macports.org/ticket/60625

**Comment by seisman** [comment]
Just ran all the tests. Only `ex34/ex34.sh` and `grdimage/grdimage_img_tif.sh` fail.

**Comment by PaulWessel** [comment]
Moving back to 3.0.4 for now.

**Comment by PaulWessel** [comment]
But that does not work either, same libqhull error.  Do I have to do the same for qhull?

**Comment by PaulWessel** [comment]
Yes, that worked.  What a stupid system...

**Comment by PaulWessel** [comment]
I wonder if ex34 orig now has turbo like the autointense test had.  I seem to have updated it not too long ago, will check.

**Comment by PaulWessel** [comment]
ex34 says
`grdimage [INFORMATION]: Auto-stretching CPT file geo to fit data range -4920 to 3994`
but our example has

`	gmt makecpt -Cglobe -T-5000/5000`

Will debug.
