### ISSUE TITLE
More automatic session cleanings?

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3517]
I just fell into this from Julia
```
if (!access (file, F_OK))	{	/* Subplot information file already exists, two begin subplot commands? */
	GMT_Report (API, GMT_MSG_ERROR, "Subplot information file already exists: %s\n", file);
	GMT_Report (API, GMT_MSG_ERROR, "Please run 'gmt clear sessions' (or equivalent if from Julia, Matlab, Python, etc...) to solve this issue.\n");
	Return (GMT_RUNTIME_ERROR);
}
```
but instead of suggesting the use of an ``equivalent 'gmt clear sessions'``, shouldn't just GMT do it?

**Comment by PaulWessel** [comment]
Hm, not there.  Session is already created and if you call clear sessions you delete your own session.  Perhaps more sensible to just overwrite the subplot file.  I guess this file is there because a previous subplot figure failed or never completed?

**Comment by joa-quim** [comment]
>  I guess this file is there because a previous subplot figure failed or never completed?

Yes, that was the case (and still is while I don't figure out what's failing from my julia script)

**Comment by joa-quim** [comment]
Ping this, It's very annoying and Julia users will not know what is ``"Please run 'gmt clear sessions' (or equivalent if from Julia, Matlab, Python, etc...) to solve this issue``

Yes, it happens when a previous subplot had an error.

**Comment by PaulWessel** [comment]
I guess we cannot do too much damage at this point to delete that file with a WARNING.  There should be some message since the user fucked up.  As explained, we cannot clean the session easily from that point.  OK?

**Comment by joa-quim** [comment]
Yes, but why a WARNING? Whatever cause the breaking of the previous subplot already issued warnings/errors.
