### ISSUE TITLE
Be able to ignore any existing gmt.conf files in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3525]
Currently gmt begin always checks for a gmt.conf in the search path (home, .gmt,cwd).  That makes it possible that a modern mode script will give different results depending on the presence of such files.  I think having a way for a clean start would be good.  Options:

1. Accept a gmt begin option to not look for outside gmt.conf files, e.g., **-C** for clean.
2. Let the syntax be gmt begin [**clean**] [_prefix_] [_format(s)_] [_psconvertoptions_] [-V[<level>]]
3. Have another begin-like module called begin-clean that does the same.
4. Do a better documentation to let people know that` gmt clear settings` as first command will do this.
5. Same, for `gmt set -Du|s`.
6. ???

_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/gmt/pull/3524#issuecomment-647905090_

Options 1, 4, and 5 look good to me.

_Originally posted by @seisman in https://github.com/GenericMappingTools/gmt/pull/3524#issuecomment-647912428_

Not a super high priority for me, but what does @joa-quim think?

_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/gmt/pull/3524#issuecomment-647926950_

**Comment by PaulWessel** [comment]
Just comment on my own list:

1. This is simple and just adds a single option to the currently single option **-V**.
2. This rules out using clean as a session (or file) name.
3. This seems a bit silly to me but would work.
4. Do people still read in 2020?
5. Ditto.
6. Not sure if there are other ways.

Given that it seems option 1 is the best candidate.  Just need to parse the **-C** and pass a bool argument into the _gmt_manage_workflow_ function that deals with the essence of the problem.

**Comment by joa-quim** [comment]
I was about to mention also your new 4. Option 1. is the simpler.

**Comment by PaulWessel** [comment]
OK, one last decision: Modern on-liners calls begin implicitly. I guess backwards compatibility means no **-C** to be used there?

**Comment by joa-quim** [comment]
Yes, but you mean no **-C** by default but it can be used if wants, or not? (not that important anyway)

**Comment by PaulWessel** [comment]
Default is no -C.  There is no place for a user to insert -C inside the GMT bowels.

**Comment by PaulWessel** [comment]
Implemented so closing this.  But here is an observation: was running all tests to see which one fails after my hierarchical stuff so I can adjust those scripts.  But from testing the begin -C option I had left a simple gmt.conf file in my home directory, and promptly several more failures. So that is annoying.  The gmt tests should not grab a gmt.conf from my home dir.

**Comment by seisman** [comment]
> The gmt tests should not grab a gmt.conf from my home dir.

Why does it happen? The test script always set the GMT system defaults before running the test.

https://github.com/GenericMappingTools/gmt/blob/e3c40a48564eb7170940a8c0242ff877eb929889/test/gmtest.in#L241

**Comment by PaulWessel** [comment]
yes, but gmtset first calls GMT_Create_Session which initializes the defaults to whatever is found in the conf search path, then does the -Du.  You would think that would overwrite everything but maybe not.  I should do some more testing on this first.  I have already wiped what failed but only remember GMT_movie_progress.sh and PS_layers.sh, which are both movie calls. You could try to create a gmt.conf in your home dir and run tests, say set FONT_ANNOT_PRIMARY=Times-Roman and see how it goes.

**Comment by seisman** [comment]
Can't reproduce what you said using the following quick testing:
```
$ cd ~/
$ gmt set MAP_FRAME_TYPE plain
$ cat gmt.conf
#
# GMT 6.1.0 Defaults file
#
# MAP Parameters
#
MAP_FRAME_TYPE                 = plain

$ cd ~/Desktop/workspace/
$ gmt set -Du
$ cat gmt.conf
#
# GMT 6.1.0 Defaults file
#
# Projection Parameters
#
PROJ_LENGTH_UNIT               = inch
#
# PostScript Parameters
#
PS_CHAR_ENCODING               = Standard+
PS_MEDIA                       = letter
#
# Calendar/Time Parameters
#
TIME_WEEK_START                = Sunday
```

**Comment by PaulWessel** [comment]
OK, that is good.  I will see if I can force it later.
