### ISSUE TITLE
plot -Sf+p in segment headers

### ISSUE THREAD

**Issue by tomeracles** [GenericMappingTools/gmt#3531]
When using gmt plot -Sf with multiple segments, segment headers with +p set appear to affect the -W settings of the following segment in the file.

**Full script that generated the error**

Data:
[CYPRUS_TRENCH.txt](https://github.com/GenericMappingTools/gmt/files/4826021/CYPRUS_TRENCH.txt)

```
gmt plot CYPRUS_TRENCH.txt -JM10c -Bwesn -R25/40/30/40 -Sf -Gblack -Wthinnest -pdf test
```

The key is that the four segments in the data file have the following headers:

```
> -Sf4c/12p+s+l+o1.4c+p1p 
...
> -Sf1.0c/0.2c+r+t+o0.5c 
...
> -Sf2c/12p+s+r+o0.4c
...
> -Sf1.0c/0.2c+l+t+o0.5c
...
```

I set +p1p in the first segment to make the sense-of-slip arrows 1p thickness. This worked, but appears to have the knock-on effect of setting the pen thickness of the second segment to 1p, rather than 'thinnest' as set by -W. But then for the third segment onwards, the correct thickness (thinnest) is used. What's going on here? (And should I just put my strike-slip and reverse faults in different data files?)

**Actual outcome**

<img width="439" alt="image" src="https://user-images.githubusercontent.com/49723355/85577232-f860cb80-b630-11ea-9e84-f1d90057cb04.png">

(The segments go from east to west)

* Operating system: macOS Mojave 10.14.1 
* GMT version (`gmt --version`): 6.0.0

**Comment by PaulWessel** [comment]
Looks like a bug to me. **+p** should only affect symbol (triangle) outline.  Work-arounds for now might be to not use **+p** (don't really need to draw a black outline on a black symbol), or put in different files. I will have a look after the obligatory zoom meetings...
