### ISSUE TITLE
For ffmpeg Pixel width and Height must be divisible by 2. 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#3540]
I make a movie and I adjust the width and height of the canvas to adjust the size of the figure (19.202 c x 12.264 c). I use this values (plus -Y and -X in the mainscript). GMT make all the figures without anyproblem but then ffmpeg couldn't create a mp4 because the Pixel width and heigth were odd (1921 x 1263). So I have to modify the size (19.22cx12.635c) to get even pixels and get the movie. 

I think that maybe a warning could be add, or to set movie to add another pixel if needed. 

This issue maybe could be merge with #3357.

**Full script that generated the error**
```
Fail:
gmt movie "TdF_Bouguer_Upward_MainScript.bat" -N"Upward8" -T"temp_col0.txt" -C19.202cx12.624cx100 -Fmp4 -D12 -V3

Worked:
gmt movie "TdF_Bouguer_Upward_MainScript.bat" -N"Upward8" -T"temp_col0.txt" -C19.22cx12.635cx100 -Fmp4 -D12 -V3

```
**Full error message**

![Capture_error2](https://user-images.githubusercontent.com/17908951/85766443-6cf94000-b6ed-11ea-9a2b-bfe07140b90b.PNG)
![Capture_error](https://user-images.githubusercontent.com/17908951/85766450-6f5b9a00-b6ed-11ea-9d52-e155a010bc8e.PNG)

* Operating system: Win 10
* GMT version: 6.0.0

**Comment by PaulWessel** [comment]
Hm, did you not get this message? We have a check for it:

```
if (p_width % 2)	/* Don't like odd pixel widths */
	GMT_Report (API, GMT_MSG_ERROR, "Your frame width is an odd number of pixels (%u). This may not work with FFmpeg...\n", p_width);
```

**Comment by Esteban82** [comment]
I checked it. It doesn't appeared if I ask also for a GIF (-Agif)

`gmt movie "TdF_Bouguer_Upward_MainScript.bat" -N"Upward2" -T"temp_col0.txt" -C19.202cx12.635cx100 -Fmp4 -D12 -V3`

![Capture_error3](https://user-images.githubusercontent.com/17908951/85779674-3aa20f80-b6fa-11ea-8192-57b638598dee.PNG)

`gmt movie "TdF_Bouguer_Upward_MainScript.bat" -N"Upward2" -T"temp_col0.txt" -C19.202cx12.635cx100 -Fmp4 -D12 -V3 -Agif`

![Capture_error4](https://user-images.githubusercontent.com/17908951/85779629-2e1db700-b6fa-11ea-99e0-41598a2cdb58.PNG)
