### ISSUE TITLE
Unable to set line colors via -Z and -C

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3541]
I want to plot some lines, with the line colors determined by a value and a CPT file. After reading the **plot** documentation, I think I can get my plot using the codes below:
```
gmt begin map png
gmt makecpt -Crainbow -T0/100/10 -I
gmt basemap -R0/10/0/8 -JX10c/8c -Baf -BWSrt
gmt plot -W2p -C -Z10 << EOF
2 2
5 5
EOF
gmt colorbar
gmt end show
```
This is the output. Obviously, it doesn't work as I expect
![image](https://user-images.githubusercontent.com/3974108/85798138-f3704a80-b70a-11ea-94c4-b974146f81c4.png)

However, the following slightly different script works (moving **-Z** from command line to table header):
```
gmt begin map png
gmt makecpt -Crainbow -T0/100 -I
gmt basemap -R0/10/0/8 -JX6c/3c -Baf -BWSrt
gmt plot -W2p -C << EOF
> -Z10
2 2
5 5
EOF
gmt colorbar -Baf
gmt end show
```
Output:
![image](https://user-images.githubusercontent.com/3974108/85798261-2a466080-b70b-11ea-96d0-e77026225621.png)

Looks like a bug, right?

**Comment by PaulWessel** [comment]
The first case works if you use -W2+z.  Perhaps the docs are not clear.

**Comment by seisman** [comment]
You're right. I probably was reading the 6.0 documentation. The dev documentation looks good.

**Comment by PaulWessel** [comment]
OK, so zap thie #3543 PR?
