### ISSUE TITLE
a module of 'citation' is needed

### ISSUE THREAD

**Issue by wangliang1989** [GenericMappingTools/gmt#3561]
````bash
$ gmt citation
# gmt show the information for citing information of gmt
$ gmt citation surface
# gmt show the information for citing information of the module of surface
````

**Are you willing to help implement and maintain this feature?** 
Yes

**Comment by PaulWessel** [comment]
Thanks for the suggestion, but we do not need a separate program for that.  Have you tried

```
gmt --show-citation
Wessel, P., Luis, J. F., Uieda, L., Scharroo, R., Wobbe, F., Smith, W. H. F., & Tian, D. (2019). The Generic Mapping Tools version 6. Geochemistry, Geophysics, Geosystems, 20, 5556–5564. https://doi.org/10.1029/2019GC008515

gmt --show-doi     
https://doi.org/10.5281/zenodo.3407866
```

There are lots of individual reference for some modules, and these are listed in the documents, e.g.,

`gmt docs surface
`

and scroll to the end.

**Comment by wangliang1989** [comment]
I didn't know that

**Comment by wangliang1989** [comment]
Maybe, exporting a file of BibTeX will be more convenient

**Comment by PaulWessel** [comment]
We could post a bibtex EndNote file with GMT references on our website, but this is not a good use of a module.  So I am sorry, but we are not expanding gmt to write such reference materials.  I will look into adding a bibtext/EndNote file to the documentation somewhere, though.

**Comment by wangliang1989** [comment]
This is also good

**Comment by seisman** [comment]
FYI, we already have a bibtex in https://github.com/GenericMappingTools/gmt/blob/master/CITATION.md

**Comment by seisman** [comment]
Both Google Scholar and [the G3 site](https://agupubs.onlinelibrary.wiley.com/action/showCitFormats?doi=10.1029%2F2019GC008515) provide citations in many formats. To me, there is no need for us to do more work.

**Comment by PaulWessel** [comment]
I agree, we are closing this issue.
