### ISSUE TITLE
GMT_AUTO_DOWNLOAD may not work as expected.

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3608]
**Description of the problem**

Please check if you can reproduce the issue by following the steps:

1. Turn off your internet connection
2. Run `gmt set GMT_AUTO_DOWNLOAD off -Vd`. Since the internet connection is off, the debug messages say `Libcurl Error: Couldn't resolve host name`
3. Run `gmt defaults -Vd`. The command still tries to download the gmt_data_server.txt file and reports the the same error `Libcurl Error: Couldn't resolve host name`

**Comment by PaulWessel** [comment]
Hi @seisman, is this issue still relevant after merging #3616 ?

**Comment by seisman** [comment]
Yes, the issue is still here. To reproduce the issue, run:

```
gmt set GMT_AUTO_DOWNLOAD off
gmt grdimage @earth_relief_06m -pdf map -Vd
```
