### ISSUE TITLE
Add a daily CI job to check if all the GMT mirrors are running 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3635]
**Description of the desired feature**

Currently, we have one official data server: https://oceania.generic-mapping-tools.org/, and shortly will have a mirror in Europe. 

We should add a daily CI job to check if all the GMT mirrors are running correctly. To do that, we just need to run:
```
gmt set GMT_DATA_SERVER url-of-the-mirror
gmt grdimage @earth_relief_01d
```
then check if gmt_data_server.txt, gmt_hash_server.txt and earth relief data is in the ~/.gmt directory.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Yes, useful to know.  If we were very clever, we could use it to add a green or red circle next to each entry in the table of available mirrors that I was planning to add to the docs.  Or more likely make a figure.

**Comment by seisman** [comment]
Closing as it's implemented using the https://shields.io/ service.
