### ISSUE TITLE
Scientific color map (cpt) files are incorrect

### ISSUE THREAD

**Issue by MarkWieczorek** [GenericMappingTools/gmt#3640]
The scientific color maps that are provided as cpt files with gmt do not represent the original color maps created by Fabio Crameri. This is easily verified by looking at the colorbars in the [gmt documentation](https://docs.generic-mapping-tools.org/latest/cookbook/cpts.html) and on his [web site](http://www.fabiocrameri.ch/colourmaps.php).

As an example, here are the relevant color bars for ‘Vik’

from gmt:
<img width="411" alt="Screen Shot 2020-07-09 at 23 29 43" src="https://user-images.githubusercontent.com/8697285/87219711-f3548980-c35d-11ea-911b-543609accf53.png">

And from Fabio Crameri's web site
<img width="889" alt="Screen Shot 2020-07-09 at 23 29 34" src="https://user-images.githubusercontent.com/8697285/87219714-f5b6e380-c35d-11ea-95a9-ebc33c11a55f.png">

I have verified that this issue is not simply something simple like a conversion from RGB to CYM

**Comment by PaulWessel** [comment]
What happened is that Fabio has updated his colormaps and we have not thought of a mechanism for us to learn this, hence we are a few versions behind.  I am working on a PR now that will bring us up to the latest 6.0.4 released in June.  However, what you see above is actual changes in the RGB values in vik.cpt due to his revisions. Maybe @seisman can think of a way for us to learn that his site has been updated and alert us (e.g, a CI job running once a week or moth?)

**Comment by seisman** [comment]
> Maybe @seisman can think of a way for us to learn that his site has been updated and alert us (e.g, a CI job running once a week or moth?)

It's doable. Please leave this issue open even after you fix it, so that I won't forget it.

**Comment by PaulWessel** [comment]
OK, I've emailed Fabio to see if he as some sort of notifications (email list) or if there is a particular ascii or html file we could curl and grep on in a CI.

**Comment by MarkWieczorek** [comment]
It appears that Fabio's colormaps have **not** been updated in GMT 6.1.1 (macOS, installed via brew). My maps are still being plotted with the old washed out colors as in the original post.

**Comment by PaulWessel** [comment]
Yes, unfortunately it looks like those were not merged back to the 6.1 branch.  They were fixed in master only.  We wrote scripts to automate lots of these steps so that we will be notified when Fabio changes anything, but we forgot to merge those changes back to 6.1.  Sorry.

**Comment by seisman** [comment]
Yes, PR #3649 did many things, so we decided not to backport that PR into 6.1 branch. 

@MarkWieczorek A workaround for you is to download the CPT files in the master branch (https://github.com/GenericMappingTools/gmt/tree/master/share/cpt) and override the CPT files from GMT 6.1.1.

**Comment by joa-quim** [comment]
Well, they were not GMT bugs.

**Comment by MarkWieczorek** [comment]
> Yes, PR #3649 did many things, so we decided not to backport that PR into 6.1 branch.
> 
> @MarkWieczorek A workaround for you is to download the CPT files in the master branch (https://github.com/GenericMappingTools/gmt/tree/master/share/cpt) and override the CPT files from GMT 6.1.1.

No problem. I can wait until 6.2.0 comes out. The only reason I caught this is that I have a notebook that compares projections using pygmt and Cartopy.
