### ISSUE TITLE
error on pscontour

### ISSUE THREAD

**Issue by geophysics91** [GenericMappingTools/gmt#3641]
**Description of the problem**
Dear experts, i want to plot a pscontour in psxy file using the code below but there is some bugs. I am using ubuntu 20.04.

**Full script that generated the error**
data and script is pasted here          https://i.fluffy.cc/QRGsMKS434rNCdszq6Jqw6F4RSjmzCLS.html
```
#!/bin/sh

gmt makecpt -Cpolar -T-0.5/0.5/0.5 > con.cpt

cat dat | gmt pscontour -JX10/7 -R30/45/2.0/4.0 -Ccon.cpt -W1p -A- -O -P -K > g.ps
```

```
# PASTE ERROR MESSAGE HERE
```
pscontour [ERROR]: WARNING: Bug Report Advice for Watson ACORD External Code:
pscontour [ERROR]: The Watson algorithm can fail if there are duplicate (x,y) records.
pscontour [ERROR]: We found 67732 duplicate records in your data set.
pscontour [ERROR]: Please remove duplicates and redo your analysis if the results are corrupted.
ERROR: Caught signal number 11 (Segmentation fault) at
/lib/x86_64-linux-gnu/libgmt.so.6(gmt_delaunay+0x535)[0x7f2037bbd3f5]
[0x7f202e017ff8]
Stack backtrace:
/lib/x86_64-linux-gnu/libgmt.so.6(sig_handler+0x2bb)[0x7f2037b089fb]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f2037933210]
/lib/x86_64-linux-gnu/libgmt.so.6(gmt_delaunay+0x535)[0x7f2037bbd3f5]
/lib/x86_64-linux-gnu/libgmt.so.6(GMT_pscontour+0x72a)[0x7f2037d8aeca]
/lib/x86_64-linux-gnu/libgmt.so.6(GMT_Call_Module+0x31d)[0x7f2037b21bfd]
gmt(main+0x250)[0x564e07203590]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f20379140b3]
gmt(_start+0x2e)[0x564e0720434e]

**Actual outcome**

it should produce a psxy file

**Expected outcome**

it should produce a psxy file

**System information**

* Operating system: ubuntu 20.04
* GMT version (`gmt --version`): Version 6.0.0 [64-bit] [4 cores]

**Comment by joa-quim** [comment]
There is no GMT bug in here, please use the forum to post this type of questions.
As the code warns, or better get a GMT that uses the other triangulation algorithm (the Shewchuk's algorithm).

```
pscontour [ERROR]: The Watson algorithm can fail if there are duplicate (x,y) records.
pscontour [ERROR]: We found 67732 duplicate records in your data set.
pscontour [ERROR]: Please remove duplicates and redo your analysis if the results are corrupted.
```

**Comment by geophysics91** [comment]
is it a ubuntu problem??? can anybody suggest some solutions for this problem.

**Comment by joa-quim** [comment]
I feel sympathetic with you and I always hatted that we offer this option but the problem is the GPL license. The Shewchuk algorithm does not comply with the GPL so some package managers decide to build GMT with Watson algorithm, which is very limited. What to do? Sorry but the options I see are:
1. Build GMT yourself?
2. Change your Linux distro?
3. Use Windows?

**Comment by joa-quim** [comment]
And given that you'll have to wait some(?) years until GMT6.1 is available in Ubuntu option 1. is really the optimal solution.
