### ISSUE TITLE
Always write OGR/GMT header in files

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#366]
Is there a reason why many (all?) gmt tools producing spatial output does not pr. default output the OGR/GMT header (*and* aspatial data)? E.g. ``grdcontour``, ``gmtconnect``, ``gmtspatial``, ``block[mean,median,mode]`` etc.

In my opinion this would be a good idea. This makes workflows involving ``ogr2ogr`` ~flawless and consistent. 

As a user of QGIS, it also appears that it now requires the OGR/GMT to be present (at least ``# @VGMT1.0``) or else if will fail to recognize the file.

Very related to issue #213.

**Comment by PaulWessel** [comment]
Fully agree, there are technical reasons why it is not that way; we do want to try to reach that goal.

**Comment by abanbj** [comment]
Great!

**Comment by anbj** [comment]
Just adding the header:

```
# @VGMT1.0 @GLINESTRING
```

makes it readable by `ogr2ogr`. Great benefit!

**Comment by anbj** [comment]
Too old. Lack of interest. Closing. Will turn up again if it needs to.
