### ISSUE TITLE
Unavailave GMT Forum registration

### ISSUE THREAD

**Issue by Olivine-Ryo** [GenericMappingTools/gmt#368]
I'm afraid it is the problem of not GMT itself but the website, as I don't know how to cotanct them.
In the GMT Forum registration site, the reCAPTCHA provided by google has been abolished so nobody can register the forum.
https://gmt.soest.hawaii.edu/account/register

**Comment by leouieda** [comment]
Hi @Olivine-Ryo we've added a notice to the website warning about this issue. If you need to ask a question, I can create an account for you. Please tell me:

1. Desired user name
2. Email
3. Full name

**Comment by seisman** [comment]
> There will be a new mailing list soon.

@PaulWessel Are you going to setup an old-fashioned mailing list or a modern forum?

**Comment by PaulWessel** [comment]
We discussed this issue in Faro.  We wanted to avoid people posting general GMT questions (how to do this, does anyone have data for that, etc.) as issues on GitHub since it will fill up quickly.  The forum on the old wiki was good in that way but we are trying to get off that server.   There seems to be no similar capability on git.  If you have suggestions for a modern forum let us know.

**Comment by KristofKoch** [comment]
> The forum on the old wiki was good in that way but we are trying to get off that server.

@PaulWessel If the problem is just getting the forum off that SOEST server I might be able to arrange some server space for you/GMT. Maybe even free of charge but I'll have to ask some people in case there is interest from your side. No promise.

**Comment by joa-quim** [comment]
When we reach 15 contributors (currently 11) we could apply to a free [Discourse ](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/) hosting.

**Comment by seisman** [comment]
Discourse is a nice solution for a forum.

> When we reach 15 contributors (currently 11) we could apply to a free [Discourse ](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/) hosting.

@joa-quim The biggest limitation of the free discourse hosting service is that the domain name must be something like `gmt.discourse.group`.

**Comment by KristofKoch** [comment]
> Discourse is a nice solution for a forum.

@seisman Are you familiar with self-hosting Discourse?

**Comment by seisman** [comment]
@KristofKoch I've never tried it. But it should be easy, since they [use docker](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md).

**Comment by leouieda** [comment]
We're trying to avoid self hosting solutions to minimize the amount of maintenance required and decentralize our process. This is why we moved to GitHub and are closing down the current forum (hosted at SOEST)

**Comment by KristofKoch** [comment]
@leouieda understandable

**Comment by seisman** [comment]
@leouieda Can we really avoid a server? At least we need an FTP server.

**Comment by PaulWessel** [comment]
I think we can assume that a SOEST server will be available for the foreseeable future (10 years) but we may end up with another solution after I retire, of course.

**Comment by leouieda** [comment]
The problem is finding someone who can commit to maintaining this for the next 10 years (updating the OS, security fixes, etc). It's no use to us if someone sets it up right now and steps away from the project after a year. Unless we have a critical mass that knows the system and can assume maintenance.

**Comment by PaulWessel** [comment]
If I understand things correctly, once we purchase genericmappingtools.org then we can set up the email forum and ftp at SOEST, and should we need to move it to UNAVCO or similar then this can be done without any impact/change to the users.  Sounds to me this is the best move for us now.

**Comment by joa-quim** [comment]
While that is true, if we had applied the same logic before we never would have had the Redmine site running.

 

If we could have a Discourse forum (Dongdong mentioned a Docker install), it would be far better than a mailing list. And, I assume, it should also be `moveable` though I have no idea on the issues of doing that.

**Comment by PaulWessel** [comment]
Hm? REdmine was running at SOEST since 2012? and the logic was the same - that it would be find for 10+ years.  Still true I think even after I retire - I will be Prof. Emeritus there and will through my growing weight around for years.

**Comment by joa-quim** [comment]
I'm not referring to the mailing list solution but rather to the give up going beyond that (a Discourse forum is my favorite goal)

**Comment by KristofKoch** [comment]
While this decision is not my business I'd like to share my thoughts from a user perspective: 

I really appreciate the lean approach of the current (Redmine) forum and ticketing system. No avatar/social-media/likes/groups/interaction/feature bloat. Just a simple forum which is surprisingly fast even with a bad internet connection (it even works properly on a mobile device out of Iran - maybe not your everyday use case though). 

Discourse, while a neat solution, seems a bit overkill to me. I'd appreciate it in a more streamlined way. But this is my totally subjective opinion.

**Comment by leouieda** [comment]
Moving this discussion to #505.
