### ISSUE TITLE
Using command project -N (Cartesian) with text and coordinates outside geographic range

### ISSUE THREAD

**Issue by MarceloBanik** [GenericMappingTools/gmt#3695]
**Description of the problem**

using gmt4.5.18:
```
$ echo "1141.4213562373095 1000.0 text" | project -C1000/1000 -A45 -N
```
I get:
```
1141.42135624   1000    text    100     100     1070.71067812   929.289321881
```
it is what I expected.
Using gmt6.2.0:
```
echo "1141.4213562373095 1000.0 text" | gmt project -C1000/1000 -A45 -N
```
I get:
```
project [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN
project [WARNING]: Column selected for latitude-formatting has values that exceed +/- 90; set to NaN
61.4213562373   NaN     100     100     -9.28932188135  NaN     text
```
The p,q values are as expected, but x,y,r,s appears to be treated like geographic coordinates, what I suppose is a bug when using a Cartesian [-N option] projection.
I noted that the text position changed, but it I suppose is just the new way in gmt.
I checked that gmt 6.1.0 and 6.0.0 behaves like 6.2.0 and gmt 5.4.5 like 4.5.18.

**System information**

* Operating system: linux Ubuntu 18.04.4
* GMT version (`gmt --version`): 6.2.0_88a75a8_2020.07.19

**Comment by PaulWessel** [comment]
Thanks for this.  It is being fixed in #3743.  Also yes, locations of numerical and text columns are standardized in GMT 6, with all text kept as trailing text.
