### ISSUE TITLE
movie requires that the path has no spaces in it

### ISSUE THREAD

**Issue by earjcr1** [GenericMappingTools/gmt#3698]
e.g. if I have animations/ in my Google Drive and run the command, 

(base) see2-236:animation chris$ gmt movie earth.sh -C360p -T91 -Nearth -M55,pdf -Fnone
gmtset [ERROR]: Unrecognized keyword Drive/animation,/Users/chris/Google.
gmtset [ERROR]:  1 GMT Defaults conversion errors from command options
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory

**Comment by seisman** [comment]
FYI, I just transferred the issue to the gmt repository.

**Comment by PaulWessel** [comment]
@earjcr1 for now please do this task not in your Google Docs folder.  The movie scripting in the background does not like those spaces. so we need to add a fix.

**Comment by earjcr1** [comment]
No problem! Thanks everyone!
________________________________
