### ISSUE TITLE
Be consistent as to what is a required table argument

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3729]
**Description of the desired feature**

Lots of modules take input from a list of tables or _stdin_.  In app cases, the input is required and without files or piping the module sits there.  So clearly, the input is required.  However, we are inconsistent in explaining this.  For instance, [**sphinterpolate**](https://docs.generic-mapping-tools.org/dev/sphinterpolate.html) lists the input table under **Optional Arguments**.  In contrast, [**grdmask**](https://docs.generic-mapping-tools.org/dev/grdmask.html) lists the input table under **Required Arguments**.  Clearly in all these cases the input is **required**, whether it comes from stdin or one or more files.

Proposal: Go through all the table-reading module documentation and

1. Ensure the input is listed under Required Arguments
2. Standardize on the input being referred to as *table* and not other names

**Comment by wangliang1989** [comment]
Input tables in all modules should be under Required Arguments?
Build a new branch based master to fix it?

**Comment by PaulWessel** [comment]
yes, it should be based on master. Thanks for being willing to help.  In case there are things I meant to say that I forgot, it is probably best to start with just doing one supplement, say spotter, and make a pull request.  That way, it is not too much work and if we need to request changes then it is not too much to do.  Once all is good, then do each supplement that, then the core.

**Comment by seisman** [comment]
Should we also change `[<table>]` to `<table>` in the module usage?

**Comment by PaulWessel** [comment]
Hm, I think no. The file name is optional (you can redirect or type on keyboard) but the input is required

**Comment by seisman** [comment]
Closed by #4317.
