### ISSUE TITLE
File lock on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3765]
A new failure on Windows:
```
 9/11 Test #815: psxy/urlquakes.sh ................***Failed    4.14 sec
Set GMT_SESSION_NAME = 40326
psxy [ERROR]: Failed to create lock file C:\Users\VSSADM~1\AppData\Local\Temp/query.csv?starttime=2016-01-01%2000:00:00&endtime=2016-02-01%2000:00:00&minmagnitude=4.5&orderby=magnitude.download
psxy [ERROR]: Unable to obtain remote file https://earthquake.usgs.gov/fdsnws/event/1/query.csv?starttime=2016-01-01%2000:00:00&endtime=2016-02-01%2000:00:00&minmagnitude=4.5&orderby=magnitude
ERROR: gmtest:58
memtrack errors: 0
exit status: 1
```

**Comment by PaulWessel** [comment]
Fair enough.  I need to disable locking on URLs queries.

**Comment by seisman** [comment]
Closed by #3768.

**Comment by seisman** [comment]
Re-open the issue because I still see the same error in yesterday nightly CI job.

**Comment by joa-quim** [comment]
Still fails for me
```
psxy [ERROR]: Failed to create lock file C:\TMP/query.csv?starttime=2016-01-01%2000:00:00&endtime=2016-02-01%2000:00:00&minmagnitude=4.5&orderby=magnitude.download
```

**Comment by PaulWessel** [comment]
Could you find out why my check for the url query fails?  Perhaps that macro has a problem.

**Comment by joa-quim** [comment]
The problem is not the macro. The error message is not coming from ``gmtremote_get_url()`` but from ``gmt_download_file()``

**Comment by joa-quim** [comment]
Maybe the problem is this. Windows doesn't accept ``?`` in file names.

![image](https://user-images.githubusercontent.com/537321/88988606-3d7fb980-d2d1-11ea-9ade-19a2f8824dbd.png)

**Comment by PaulWessel** [comment]
That is fine, it is allowed in the URL and I (think) I am checking the URL string for the question mark.  THe idea is that if the URL makes the gmt_M_is_query return true then we dont try to make that lock file, but it is not triggering the test.

**Comment by joa-quim** [comment]
You are trying to create a file that has question marks in its name

```
	Lfile = gmtremote_lockfile (API, (char *)name);
	if ((fp = fopen (Lfile, "w")) == NULL) {
		GMT_Report (API, GMT_MSG_ERROR, "Failed to create lock file %s\n", Lfile);
		return 1;
	}
```
and that is not allowed.

**Comment by PaulWessel** [comment]
Well, I am trying **not** to create that file when it is an URL query:

```
	bool query = gmt_M_file_is_query (url);
	if (!query) {	/* Only make a filename if not a query */
		Lfile = gmtremote_lockfile (API, file);
		if ((fp = fopen (Lfile, "w")) == NULL) {
			GMT_Report (API, GMT_MSG_ERROR, "Failed to create lock file %s\n", Lfile);
			return 1;
		}
		gmtlib_file_lock (GMT, fileno(fp));	/* Attempt exclusive lock */
	}
```

So clearly query is false for this case and I dont know why.

**Comment by joa-quim** [comment]
No, query is true. I told you the error message is not coming from that function but from ``gmt_download_file()`` where it tries to create a file with a question mark.

**Comment by PaulWessel** [comment]
Shits, I must have forgotten to duplicate the test there... OK will fix now.  Jeez.

**Comment by joa-quim** [comment]
OK, it works now.

**Comment by PaulWessel** [comment]
If I don't get it right on the _n_'th try, I usually get it right on the _m_'th try (_m > n_, sometimes _m >> n_).
