### ISSUE TITLE
Move non-official GMT install instructions to wiki

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3779]
**Description of the problem**

The GMT install instructions for Linux is complicated, because for some distros there are both official and "non-official" ways to install GMT. Here, "official" way means installing GMT from the Linux official repository via `apt-get` or `yum`. "Non-official" way means installing GMT from third-party repository (for example, the GMT "official" RPM repository for CentOS and Fedora). The official way usually provide old GMT versions, while "non-official" way always provides latest GMT version. I think we should document both ways well.

In the INSTALL.md file, we can

1. only document the official ways to install GMT
2. alert users that following these instructions, you may get old GMT versions (for example, it's still GMT 6.0.0 on Fedora 32)
3. ask users to follow the "non-official" instructions in the wiki to install the latest GMT versions.

**Comment by seisman** [comment]
@PaulWessel any thoughts?

**Comment by PaulWessel** [comment]
I think your proposal is clear and helpful.  If done right it will educate the more casual Linux users to better understand why the their official distro does not provide the version they expected.
