### ISSUE TITLE
Transparency does not work

### ISSUE THREAD

**Issue by gfz-chw** [GenericMappingTools/gmt#380]
Dear GMT-team,

Previously working GMT-scripts do not compile transparent features anymore. It is likely that this issue is related to my operating system and software distribution but I cannot find help anywhere else.

I had been working with GMT 5.4 printing transparent surfaces which would perfectly show after conversion from ps to pdf. For a while now this procedure does not work anymore. Surfaces intended to be transparent are shown opaque (sudden change during long term usage of Ubuntu 16.04). 

The below example bash-script is executed on a new Ubuntu 18.04 distribution with a simple GMT-installation as recommended in your documentation. The issue prevails!

That missing transparency is not a failure of GMT is evident from the fact that the desired effect is correctly achieved when converting the ps-file at www.ps2pdf.com . However, the detour over this webpage is not very handy.

What must be changed in the disposition of Ubuntu/ghostscript etc. to make this work again?

Best, Christoph

###############
#! /bin/bash

gmt pscoast -R26.3/30.5/39.8/41.4 -JM16 -Dh -Bpya1 -Bpxa1 -BWesN -N1/red -Ggray -I4/blue -K > outfile.ps
echo "27 40.5" | gmt psxy -R -J -Sa4c -Wthin -Ggreen -t50 -O >> outfile.ps

ps2pdf outfile.ps

exit 
###############
 
* Operating system: Ubuntu 18.04
* Version of GMT: 5.4.3
* ps2pdf from texlive-extra-utils

**Comment by gfz-chw** [comment]
Hi,

thank you for your prompt answer. I interpreted it as an encouragement to install a newer version of gmt from source. I followed the corresponding instructions and now use gmt 6.0.0 .

However, I am afraid the issue prevails.

**Comment by gfz-chw** [comment]
I accept your fatherhood. That works for me as well. Thanks a lot.

**Comment by PaulWessel** [comment]
Very good.
