### ISSUE TITLE
Using default IO_COL_SEPARATOR in output. Example with gmtconvert.

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#3806]
The default ``IO_COL_SEPARATOR`` is tab, but it's giving me somewhat unexpected results. E.g.

```
$ echo 35.2121213 76.43243423 | gmt convert -fg --FORMAT_GEO_OUT=D
35.2121213      76.43243423
$ echo 35.2121213 76.43243423 | gmt convert -fg --FORMAT_GEO_OUT=ddd:mm.xxxxx
35:12.72728     76:25.94605
$ echo 35.2121213 76.43243423 | gmt convert -fg --FORMAT_GEO_OUT=ddd:mm:ss.xxxxx
35:12:43.63668  76:25:56.76323
```
First of all, the space between the two output numbers vary in all cases. And if you print four instead of five number of digits after decimal point in the last example above you get a different spacing. I would expect a tab to be a tab.

```
$ echo 35.2121213 76.43243423 | gmt convert -fg --FORMAT_GEO_OUT=ddd:mm:ss.xxxx
35:12:43.6367   76:25:56.7632
```

Seems like github strips away tab(ish) characters, so you might have to run this in terminal.

Furthermore, I consider that tabs must be destroyed (and replaced by space as default).

**Comment by PaulWessel** [comment]
If I pipe the output from all your commands via od -c I only see one tab character in all the cases.  Which is what we are printing anyway.  Any space you "see" is determined by terminals, editors, etc.

**Comment by anbj** [comment]
Yes, I see the same. That's strange. Why would ``\t`` not be printed the same way everywhere. I'm using WSL 2 with Ubuntu 20.04 in this case.

**Comment by PaulWessel** [comment]
TAB is configurable in various apps.  My editor can have it set to any number of spaces.  Not sure waht terminals do, but this is not a GMT issue.  We always write just one tab.  If you need formatted output you will need to look at spaces.

**Comment by anbj** [comment]
Thanks Paul. There's something to learn everyday.

I cant understand why TAB is printed differently in the different commands. It's all run in the same terminal.
