### ISSUE TITLE
grdview without -C crashes

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3820]
For example in ex04 if we remove the -C it crashes because the *P pointer is accessed without first checking it's not null.
The man for -C says
```
The name of the CPT. Must be present if you want (1) mesh plot with contours (-Qm), or (2) shaded/colored perspective image (-Qs or -Qi). For -Qs: 
```
but looking at the -Q options it seems that more (-Qc for instance) sub-options require **-C**. In fact it looks that they all need it, but that can't be true if only **-Qm** is required.

In summary, I'm lost on when we absolutely need **-C** and must error if not present.

**Comment by PaulWessel** [comment]
Certainly **-Qs**[**m**] requires a cpt since it is filling in the surface.  I think only -**Qm**[**x**|**y**] can work without a cpt. In modern mode I think we would like **-C** to be optional entirely  since I do not think **-C** by itself selects anything special (other than giving a cpt).  If **-Q** implies a cpt and no **-C** is given it should use the default CPT, no, like **grdimage**?
In contrast, **-C** in **plot** _is_ required because it also says we must expect a 3rd data column.  I think in **grdview -C** does not imply anything like that.  So should we declare a bug and implement the above?

**Comment by joa-quim** [comment]
Yes, **-C** alone in modern should use default CPT. But **-Qs** doesn't require **-C** if *r,g,b* grids we provided.

**Comment by PaulWessel** [comment]
OK, adding to list of shits to do.

**Comment by joa-quim** [comment]
Separate but related, I found this as a consequence of another issue in ``makecpt``
```
julia> gmtbegin()
julia> C = makecpt(cmap=(255,100), range=(-10,10,10), no_bg=true)
julia> @show(C)
C = nothing
julia> gmtend()
```
That is, without **-H** ``makecpt`` doesn't return the CPT in modern mode.

**Comment by PaulWessel** [comment]
How should we "fix" that? Same with grd2cpt.  I think when makecpt/grd2cpt are called by externals they may not always want to return an item, so this depends on the lhs.  If no lhs then nothing should be returned in modern mode, but if lhs is 1 then if modern we could add -H ?

**Comment by joa-quim** [comment]
Yes, consulting the lhs is the solution but can that be solved from the C side only? The shit in Julia is that I only know the nlhs at the end of running the module.

**Comment by seisman** [comment]
Perhaps you can use `makecpt(H="newcpt.cpt")` to save the CPT to a file, and use `makecpt(H=true)` to return the CPT?

**Comment by PaulWessel** [comment]
Yes, that is true, I do not know that in GMT_Encode_Options.  But you know if you are doing modern or not.  Do you have a keyword for the case of just setting a default CPT versus returning one?

**Comment by joa-quim** [comment]
I think I got a solution.
```
	if ((val = find_in_dict(d, [:cptname :cmapname])[1]) !== nothing)
		if (IamModern[1])  cmd *= " -H"  end
		cmd *=  " > " * string(val)
	elseif (IamModern[1])  cmd *= " -H"
	end
	cmd = "makecpt " * cmd
	global current_cpt = gmt(cmd, arg1)
```
This means I can write to file in either classic or modern (I already could) and that in modern -H is always set. And since I always keep a copy of the current CPT (remember, Julia classic is almost modern mode), I don't need to always assign the output of ``makecpt`` to a variable.
