### ISSUE TITLE
Remove warning

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3830]
```
        coast  -R-6/20/35/52 -JM11 -X5 -Glightgray -EFR,IT+gP8+r300 -Da
coast [WARNING]: Option -E: Ambiguous modifier +r<val>; could be dpi of the pattern or (a deprecated) region increment - choosing dpi.
coast [WARNING]: If you meant the region modifier then place it before the +g pattern specification.
```
```+gP8+r300``` is valid 6.0 syntax and it's annoying (and scary to some) to have this warning messages.

**Comment by PaulWessel** [comment]
Yep, I think I added that when to my horror I discovered that +r could be used in two different way.  Maybe change to a DEBUG message requiring -Vd?  I agree there is nothing wrong here.
