### ISSUE TITLE
Rename and improve the build-gmt-master.sh script

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3837]
**Description of the desired feature**

Currently, we provide the [ci/build-gmt-master.sh](https://github.com/GenericMappingTools/gmt/blob/master/ci/build-gmt-master.sh) script for building GMT master branch. It's not used by GMT, but mostly useful for external projects. AFAIK, the script is already used in https://github.com/GenericMappingTools/pygmt and https://github.com/GenericMappingTools/custom-supplements. 

The biggest limitation of the script is that it can only build GMT master branch. It's really easy to make it support building a specific branch (master, 6.1 or any others), a specific release (6.1.0 or 6.0.0) or even a specific commit (the full commit hash is needed). 

I think we can:

1. Allow the script to build any branch, release or commit. It still builds the master branch by default
2. Rename the script to `ci/build-gmt.sh`

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Yes, seems like a useful enhancement.
