### ISSUE TITLE
One more PyGMT crash with grid shading

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3843]
The script reads the remote file `@tut_relief.nc` in to xarray and pass it to grdimage. It crashes with `shading=True`, but works without shading.
```python
import pygmt
import xarray as xr

pygmt.show_versions()

fig = pygmt.Figure()
fname = pygmt.which("@tut_relief.nc", download='a')
dem = xr.open_dataarray(fname)

fig.grdimage(dem, frame='af', projection='M6i', cmap='geo', shading=True, V='d')

fig.savefig("shading.png")
```

Here is the screenshot showing where it crashes:

It crashes at line 627 in grdgradient.c:
![image](https://user-images.githubusercontent.com/3974108/89369618-a9d13300-d6ac-11ea-849b-2017733adffa.png)

![image](https://user-images.githubusercontent.com/3974108/89369682-d8e7a480-d6ac-11ea-8a66-3b366467d6fa.png)

Related variables:

![image](https://user-images.githubusercontent.com/3974108/89369647-bd7c9980-d6ac-11ea-9db8-144b64d5367d.png)

![image](https://user-images.githubusercontent.com/3974108/89369665-ca998880-d6ac-11ea-98ff-9ba55c55dbe3.png)

**Comment by PaulWessel** [comment]
Do you know if the variable new_grid is true?

**Comment by seisman** [comment]
Yes, it's `true`.
