### ISSUE TITLE
WTF - *gmt* may mean *git mergetool* in ubuntu

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3845]
See https://github.com/GenericMappingTools/GMT.jl/issues/413

**Comment by seisman** [comment]
I believe it's an alias defined by the "git" plugin of [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git).

**Comment by PaulWessel** [comment]
I posted a request on their github site.  It is a namespace clash and I think we have precedence. Perhaps Ubuntu has rules for this; we could ping Sebastian.

**Comment by seisman** [comment]
We already opened an issue in the oh-my-zsh repository (https://github.com/ohmyzsh/ohmyzsh/issues/9154), but got no response. Besides that, there is nothing we can do. Closing the issue.
