### ISSUE TITLE
Different CPTs used with Earth Mask

### ISSUE THREAD

**Issue by wangliang1989** [GenericMappingTools/gmt#3846]
gmt version: 6.2.0_2e81cc5_2020.07.04

gmt grdimage @earth_mask_20m -png a
![image](https://user-images.githubusercontent.com/12059719/89448607-7664d600-d78a-11ea-830a-c408aa12b0f5.png)

gmt grdimage @earth_mask_01d -png b
![image](https://user-images.githubusercontent.com/12059719/89448585-6fd65e80-d78a-11ea-839a-a3806cb618a0.png)

I think their default CPTs should be the same

**Comment by PaulWessel** [comment]
There actually is no default CPT assigned to the masks since they are, well, masks and not data.  The difference arise in the mask having up to 5 levels but at the 1x1d resolution the highest level is not reached, so colors are scaled differently.

**Comment by wangliang1989** [comment]
OK
I can understand "The difference arise in the mask having up to 5 levels but at the 1x1d resolution the highest level is not reached, so colors are scaled differently."
I cannot understand "masks are not data", 0-5 are still data.

**Comment by PaulWessel** [comment]
Yes values 0-5 are numbers and hence data, but the intent with the mask is to use in mathematical operations with other grids to mask data over land or ocean, etc.  If you just want to plot those 5 values then you might as well do it exactly with coast.

**Comment by seisman** [comment]
I believe we won't assign default CPT to the this dataset. Closing.
