### ISSUE TITLE
Weird strips in shaded earth_day and earth_night image

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3847]
**Description of the problem**

Running the example 52 in the GMT gallery, but using a slight different projection.

Here is the image I'm getting:

![image](https://user-images.githubusercontent.com/3974108/89455152-d8442200-d72f-11ea-9773-93994ebc8800.png)

If you zoom in, it seems there are a lot of near-vertical strips (or bright pixels) in the night region:

![image](https://user-images.githubusercontent.com/3974108/89455254-00cc1c00-d730-11ea-866d-3e5114b76268.png)

**Comment by PaulWessel** [comment]
Is this with

`  gmt grdimage view.tif -JQ80W/18c -Bafg
`

or similar?  I get similar results.  Looking at the intermediate files it does not seem like a problem: We have mostly east to west illumination so it will highlight gradients in the E-W direction and completely ignore N-S gradients.  Then we are looking ag a crude grid so the pixel size starts to dominate.  So even if the topography varies with latitude, those changes do not give rise to any intensity variations.  The view.tif looks the same so it is not our projection of it.

**Comment by seisman** [comment]
I just use `gmt grdimage view.tif`, so I'm not sure about the exact projection parameters.

**Comment by PaulWessel** [comment]
OK, that would be -JQ probably centered.  So I dont see a bug here, just the pixel crudeness and preferential e-w shading.

**Comment by seisman** [comment]
OK. Closed as an invalid bug report.
