### ISSUE TITLE
gmt_chop_ext and gmt_get_ext fail when a directory of the path to the file contains a '.'

### ISSUE THREAD

**Issue by sarzeaud** [GenericMappingTools/gmt#3854]
**Description of the problem**

gmt_chop_ext and gmt_get_ext fail when a directory of the path to the file contains a '.'
For example, the path /home/sarzeaud/test/GMT5.4/myfile will be transformed to /home/sarzeaud/test/GMT5 which is not what one would expect (the path should not be modified here). This problem exists in all versions of GMT since at least GMT4.

**Full script that generated the error**

A simple test can be made converting a ps file with ps2raster (GMT5) or convert (GMT6).

mkdir /tmp/GMT5.4.0
ps2raster afile.ps -Tg -F/tmp/GMT5.4.0/afile

will generate the file /tmp/GMT5.4.png instead of /tmp/GMT5.4.0/afile.png

**Suggested correction**

Test if a file separator character appears after the last point of the path.
GMT4 (in gmt_support.c)
`	for (i = n - 1; i > 0; i--) {`
`		if (string[i] == '.') { 	/* Beginning of file extension */`
`			pos_ext = i;`
`			break;`
`		}`
`                else if (string[i] == '/')  // need to be adjusted for Windows`
`                        break;`
`	}`

GMT5 and GMT6 (in gmt_common_string.c)
`        if ((p = strrchr(string, '.')) && (p > strrchr(string, '/'))) {  // not 100% sure of this solution, not tested`
`		*p = '\0';`
`		return (p + 1);`
`	}`

**System information**

* Operating system: Linux Debian 8 and 9
* GMT version (`gmt --version`): 4.5.9, but the error still exists in all later versions

**Comment by PaulWessel** [comment]
I just tried this:

1. Make a plot: pscoast -R0/30/0/30 -JM6i -P -Baf -Gred > t.ps
2. Make a directory with periods in the name: mkdir /tmp/1.2.3
3. Do the conversion: gmt psconvert t.ps -Tg -F/tmp/1.2.3/t
4. Check result: ls /tmp/1.2.3
t.png

So it looks OK here - I cannot reproduce your issue with GMT 6.0, 6.1, or master.  Are you sure this fails for you with 6.1?  if it did in older versions then looks like it was fixed.

**Comment by seisman** [comment]
I believe we fixed the issue in https://github.com/GenericMappingTools/gmt/pull/202, https://github.com/GenericMappingTools/gmt/pull/2083.

**Comment by sarzeaud** [comment]
My mistake, it has been fixed in GMT6 a way I did not think about. It still exists in GMT5, doesn't it?

**Comment by seisman** [comment]
GMT 5 is no longer maintained.

**Comment by sarzeaud** [comment]
OK, I did not know, thanks.
