### ISSUE TITLE
splitxyz should accept to be also splitxy

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3857]
See https://forum.generic-mapping-tools.org/t/splitxyz-not-working-as-expected/745/3
That is when no **z** column add a 0 under the hood.

**Comment by PaulWessel** [comment]
Looking at the code there are lots of mentions of no_z_column so this should already by supported.  Will have a look to see why.  We check the input file and if it only has 2 then we set no_z_column, etc.

**Comment by PaulWessel** [comment]
Even our code says
	<table> is one or more data files (in ASCII, binary, netCDF) with 2, 3 or 5 columns.
