### ISSUE TITLE
rotsmoother is confused

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#386]
It says that data should be ``lon lat time angle`` but it's actually expecting ``lon lat angle time``. However, the output is indeed ``lon lat time angle``, but data is not equidistant in time.

Example data with ``lon lat angle time``
```
138.07  62.83   -6.190  27.47
138.24  62.26   -7.274  33.25
139.75  56.84   -8.268  39.13
140.06  60.18   -9.306  43.14
```

```
rotsmoother polos.dat -T27/43/3 -N -Vl
rotsmoother [INFORMATION]: Processing input table data
rotsmoother [INFORMATION]: Reading Data Table from file polos.dat
rotsmoother [INFORMATION]: Range of input ages   = 27.47/43.14
rotsmoother [INFORMATION]: Range of input angles = -9.306/-6.19
rotsmoother [INFORMATION]: Writing Data Table to Standard Output stream
rotsmoother [INFORMATION]: Found 1 rots for the time interval 27 <= t < 30
rotsmoother [INFORMATION]: Mean opening angle  -6.1900 vs median opening angle  -6.1900
138.07  62.83   27.47   -6.19
rotsmoother [INFORMATION]: Found 1 rots for the time interval 30 <= t < 33
rotsmoother [INFORMATION]: Mean opening angle  -7.2740 vs median opening angle  -7.2740
138.24  62.26   33.25   -7.274
rotsmoother [INFORMATION]: Found 1 rots for the time interval 33 <= t < 36
rotsmoother [INFORMATION]: Mean opening angle  -7.2740 vs median opening angle  -7.2740
138.24  62.26   33.25   -7.274
rotsmoother [INFORMATION]: Found 1 rots for the time interval 36 <= t < 39
rotsmoother [INFORMATION]: Mean opening angle  -8.2680 vs median opening angle  -8.2680
139.75  56.84   39.13   -8.268
rotsmoother [INFORMATION]: Found 1 rots for the time interval 39 <= t < 43
rotsmoother [INFORMATION]: Mean opening angle  -8.2680 vs median opening angle  -8.2680
139.75  56.84   39.13   -8.268
```

**Comment by PaulWessel** [comment]
rotsmoother is not interpolating to equidistant times but performing quaternion averaging of all rotations found within each interval.  It is "smoothing" but not interpolating.
If input and output formats are different then that might be a problem - will have a look.

**Comment by joa-quim** [comment]
I kinda of thought it did both (smooth and interp) but no big deal, I can interpolate them if I need.

I would prefer lon, lat, angle, time (first the 3 pole parameters and then time) though the stage poles already use time first  ``#longitude	latitude	tstart	tend	angle``, so don't know.

Another issue that I just found is that if input file is multisegment then nothing is output.

**Comment by joa-quim** [comment]
Too old to know if relevant. Reopen if this reappears.
