### ISSUE TITLE
Unexpected shift before and after mapproject

### ISSUE THREAD

**Issue by billyauhk** [GenericMappingTools/gmt#3867]
**Unexpected shift before and after mapproject**

I am trying to overlay some graphics onto a LCC-based map, which may extend beyond the mapped region. Therefore, I experimented to have my lat-lon data to pass through ```mapproject``` and drawn them directly using a Cartesian coordinate overlaying on the map, without using the normal ```plot``` so that it would not be clipped away.

However the two always fail to align properly and thus I reduced the problem into the minimum script below which shows a offset between the two. I have no simple explanation of the shift and think it should be a bug, or at least something that was not properly documented so that I cannot easily compute that shift and compensate it on my own.

**Full script that generated the error**
```
#!/bin/bash

# Minimum test case

projection1="-R111/117/20/24 -Jl114/22/20.58333333333333333334/23.41666666666666666666/1:1000000"
projection2="-R-50/50/-40/40 -Jx1c"

gmt begin

# Without pass through mapproject: red "x"
gmt basemap ${projection1} -B1g1 -U "Test Projection Overlay" -Xc -Yc
(for lon in `seq 111 0.5 117`;do for lat in `seq 20 0.5 24`;do echo "$lon $lat";done;done) | gmt plot ${projection1} -Sx0.25c -Wred -Xc -Yc
echo "114 22" | gmt plot ${projection1} -Sc0.5c -Wred -Xc -Yc

# Passing through mapproject: green "+", red rectangle bounding box and black tight mapped area
gmt psbasemap -A ${projection1} | gmt mapproject ${projection} -C | gmt plot ${projection2} -L -Wred -Xc -Yc
(
lat=20;for lon in `seq 111 0.01 117`;do echo "$lon $lat";done;
lon=117;for lat in `seq 20 0.01 24`;do echo "$lon $lat";done;
lat=24;for lon in `seq 117 -0.01 111`;do echo "$lon $lat";done;
lon=111;for lat in `seq 24 -0.01 20`;do echo "$lon $lat";done
) | gmt mapproject ${projection1} -C | gmt plot ${projection2} -L -Wblack -Xc -Yc
(for lon in `seq 111 0.5 117`;do for lat in `seq 20 0.5 24`;do echo "$lon $lat";done;done) | gmt mapproject ${projection1} -C | gmt plot ${projection2} -S+0.25c -Wgreen -Xc -Yc
echo "0 0" | gmt plot ${projection2} -Sc0.5c -Wgreen -Xc -Yc

gmt end
```

**Full error message**

(No error message during run)

**Actual outcome**

An unexpected vertical shift between the two sets of markers.

**Expected outcome**

Red "x" comes from the LCC projection should coincide with the green "+" which drawn via Cartesian coordinate, since the points are projected via an appropriate mapproject command (with "-C" options) and all plotting commands are set to "-Xc -Yc".

**System information**

* Operating system: Ubuntu 16.04 (Linux  4.4.0-181-generic #211-Ubuntu SMP Fri May 29 07:10:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
* GMT version (`gmt --version`): 6.1.0_dcaa16f_2020.04.29

**Comment by seisman** [comment]
>  have my lat-lon data to pass through mapproject and drawn them directly using a Cartesian coordinate overlaying on the map, without using the normal plot so that it would not be clipped away.

Not sure if I understand it correctly, but if you use **plot -N**, then points outside your map region won't be clipped.

**Comment by PaulWessel** [comment]
Not sure what **-Xc -Yc** is used for in modern mode.  Also, how did you arrive at the Cartesian region and projection to overlay on the Lambert conic? They do not seem to give the same dimensions to me:

```
gmt mapproject -Dc -R111/117/20/24 -Jl114/22/20.58333333333333333334/23.41666666666666666666/1:1000000 -W
62.8030925668	44.5872043786
gmt mapproject -Dc -R-50/50/-40/40 -Jx1c -W
100	80
```

Normally, one would use the same scale for the Cartesian and geoprojection and work it that way, e.g., GMT example 28.

**Comment by billyauhk** [comment]
Seems I found my solution, but first responding to the comments given above:

@seisman Thanks for the note but sorry it does not fit in my use case. I want some better control on map labelling and want to have my map labels managed on a Cartesian coordinate before "sticking" them onto the final map.

@PaulWessel Things should be okay if one (map) projects all points outside the GMT pipeline (via ```mapproject``` or even calling ```proj``` directly) and draw all data on a simple x-y plane, treating GMT as a simple x-y plotter. Therefore I did not set the region of the projection2 (Cartesian) to be a tight bound, as anything larger than the region I needed to plot will work. Conceptually it is like having a separately-made map on transparency and then I overlay that onto a paper map -- the only hurdle is how to align them properly. My fault was thinking that what I got from ```mapproject -C``` will work out of the box if the ```plot``` common is given ```-Xc -Yc``` to shift it to the "same" place (as my "paper" is also centered via ```-Xc -Yc```).
Sorry for mixing up traditional and modern mode which may made the situation less understandable.

**Solution**

I finally figured out that I mis-interpreted the "-C" option in {{{mapproject}}} will have the output with the bounding rectangle being centered -- it is not. This causes a very small offset (a few mm, large enough to be detectable) as the (0,0) in the {{{mapproject}}}ed coordinate is not the centroid of the bounding rectangle (an offset which depend on the chosen projection and region). The offset have to be computed and taken care of. I have fixed my script as below (luckily my shift is purely vertical due to my choice of projection1):

**Amended Script**
```
#!/bin/bash

# Minimum test case

projection1="-R111/117/20/24 -Jl114/22/20.58333333333333333334/23.41666666666666666666/1:1000000"
projection2="-R-50/50/-40/40 -Jx1c"

gmt begin

# Without pass through mapproject: red "x"
(for lon in `seq 111 0.5 117`;do for lat in `seq 20 0.5 24`;do echo "$lon $lat";done;done) | gmt plot ${projection1} -Sx0.25c -Wred -Xc -Yc
gmt basemap ${projection1} -B1g1 -Xc -Yc -U"Test Projection Overlay"

gmt basemap -A ${projection1} | gmt mapproject ${projection1} -C > rectangle.txt
# The bounding rectangle is not centered at (0,0). The offset have to be manually computed and compensated.
voffset=`gmtinfo rectangle.txt | grep "<" | cut -d ">" -f 2 | sed -E -e"s/^[ \t]+</scale=10;(/g" -e"s/\//+/g" -e"s/$/)\/2/g" | bc`
echo $voffset

# Passing through mapproject: green "+", red rectangle bounding box and black tight mapped area
gmt basemap -A ${projection1} | gmt mapproject ${projection1} -C | gmt plot ${projection2} -L -Wred -Xc -Yc-${voffset}c
(
lat=20;for lon in `seq 111 0.01 117`;do echo "$lon $lat";done;
lon=117;for lat in `seq 20 0.01 24`;do echo "$lon $lat";done;
lat=24;for lon in `seq 117 -0.01 111`;do echo "$lon $lat";done;
lon=111;for lat in `seq 24 -0.01 20`;do echo "$lon $lat";done
) | gmt mapproject ${projection1} -C | gmt plot ${projection2} -L -Wblack -Xc -Yc-${voffset}c
(for lon in `seq 111 0.5 117`;do for lat in `seq 20 0.5 24`;do echo "$lon $lat";done;done) | gmt mapproject ${projection1} -C | gmt plot ${projection2} -S+0.25c -Wgreen -Xc -Yc-${voffset}c
echo "0 0" | gmt plot ${projection2} -Sc0.5c -Wgreen -Xc -Yc-${voffset}c

gmt end
rm rectangle.txt
```

As now everything fits together, I would consider the issue solved (as I corrected my bad understanding on the documentation -- may be a note could be given there so that others will not fall into this again). Sorry for submitting an issue only to be solved within a few hours -- although I did stuck for a day or two before trying to minimize the script for submission.
