### ISSUE TITLE
-JP description in the cookbook is outdated

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3869]
**Description of the problem**

The [-JP description in the cookbook](https://docs.generic-mapping-tools.org/dev/cookbook/coordinate-transformations.html#linear-projection-with-polar-coordinates-jp-jp) still uses the old syntax, and is inconsistent with the new syntax 
```
-Jpscale[+a][+f[e|p|radius]][+roffset][+torigin][+z[p|radius]]]
```

**Comment by PaulWessel** [comment]
Are you fixing this or shall I?

**Comment by seisman** [comment]
Please fix it.
