### ISSUE TITLE
pspolar bubble scaling

### ISSUE THREAD

**Issue by 79seismo** [GenericMappingTools/gmt#387]
Hello,
We know that psmeca beach ball size is scaled to a magnitude 5, whereas pspolar bubble is not. If one is using psmeca before using pspolar in a script, then one has to scale the bubble of the pspolar manually. e.g.

example shell code
mag=2.5
ball_size='4i'
polar_ballsize=`echo "scale=3; ${ball_size::${#ball_size}-1}*$mag/5" | bc`

Can't you use the same function for scaling in psmeca and pspolar? This sounds like a reasonble modification to pspolar function.

**Comment by PaulWessel** [comment]
Just a comment: the meca code was written by a French group and donated to us a decade ago.  While we have tried to update it to work as expected it is not a well documented code nor are most of us seismologists.  Your request seems reasonable to me but we would need other seismologist to comment on this issue and how to avoid creating a backwards incompatibility.

**Comment by seisman** [comment]
In psmeca, the beachball size is determined by `-S<format><scale>` and `-M`.
- If `-M` is not used, the beachball size = $mag/5*<scale>
- If `-M` is used, the beachball size is `<scale>`

For pspolar, the beachball size is determined by `-M<size>`. We can add a modifier (e.g. `+m<mag>`) to `-M`:
- `-M5i` means the beachball size is 5 inch
- `-M5i+m8` means that the beachball size of M5 earthquake is 5 inch, and the magnitude of current beachball is M8. So we know the beachball size is 8/5 * 5inch = 8inch.

**Comment by 79seismo** [comment]
Thanks @seisman, this helps. The information about the +m flag is not included in the manual.

**Comment by seisman** [comment]
@79seismo There is no `+m` for current pspolar. I just proposed to add the `+m` modifier to implement this feature and also keep backwards compatibility.

**Comment by seisman** [comment]
@PaulWessel What do you think about the `+m` modifier I proposed? I can help implement it if you think it's worthy.

**Comment by PaulWessel** [comment]
I think it is a reasonable idea.  You are the seismologist here so if you think it is useful then feel free to implement it.
