### ISSUE TITLE
Inconsistent rendering of hyphens/minus

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#388]
```
echo 5 2 -A -B -C -123 | gmt text -Jx1c -R0/10/0/3 -Baf -B+t'-A -B -C -123' -png hyphens
```

![image](https://user-images.githubusercontent.com/3974108/52096546-40db9d00-2595-11e9-9380-6cb79d1cedb4.png)

The hyphen in `-A` is different from others.

**System information**

* Operating system: macOS
* Version of GMT: gmt latest

**Comment by PaulWessel** [comment]
Hi @seisman, see if you agree that we can close this one.
