### ISSUE TITLE
-U+c prints the classic module name in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3901]
**Description of the problem**

```
gmt basemap -R0/10/0/5 -JX10c/3c -Bx1 -By1 -U+c -png GMT_-U
```

![image](https://user-images.githubusercontent.com/3974108/89743372-bd93e500-da70-11ea-8a5e-c2844d026e40.png)

It shows psbasemap, instead of basemap.

Just a tiny issue. Feel free to close it if you think it's not worth the time.

**Comment by PaulWessel** [comment]
In my experience, no issue is too tiny to be fixed.  Will fix this.
