### ISSUE TITLE
Improve the parsing of MAP_LOGO_POS

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3904]
**Description of the desired feature**

Give *justification* only doesn't work
```
$ gmt set MAP_LOGO_POS=TL
gmtset [ERROR]: MAP_LOGO_POS given illegal value (TL)!
gmtset [ERROR]:  1 GMT Defaults conversion errors from command options
```

**Are you willing to help implement and maintain this feature?** YES, it looks a simple fix.

**Comment by seisman** [comment]
@PaulWessel Thoughts on this small improvement?

**Comment by PaulWessel** [comment]
You mean the concept? So TL is relative to the default POS?

**Comment by seisman** [comment]
No, I mean adding the feature to specify the _justification_ code only.
```
gmt set MAP_LOGO_POS=TL/72p/72p     # works
gmt set MAP_LOGO_POS=72p/72p           # works
gmt set MAP_LOGO_POS=TL                    # fails
```

**Comment by PaulWessel** [comment]
Sure, and I guess the POS defaults to 0/0 in that case?

**Comment by seisman** [comment]
Tried the following command:
```
gmt begin map png
gmt basemap -R0/10/0/5 -Jx1c -Baf -U"Default"
gmt basemap -R0/10/0/5 -Jx1c -Baf -U"TL" --MAP_LOGO_POS=TL
gmt end show
```
Using `0/0` as the default position is a bad choice. The logo is plotted at the current plot origin.

![image](https://user-images.githubusercontent.com/3974108/95657593-47007b80-0ae3-11eb-8a9f-3b7ca617a234.png)

Using the default value `-54p/-54p` seems more reasonable, i.e., setting MAP_LOGO_POS to `TL` only overrides the justification code, but the xpos/ypos.

![image](https://user-images.githubusercontent.com/3974108/95657697-d574fd00-0ae3-11eb-8e45-d2af2f9835d7.png)
