### ISSUE TITLE
gmt select always needs at least one argument

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3907]
The command below prints the module usage:
```
echo 5 5 TEXT | gmt select
```
but adding `-Ve` (or any other options) works:
```
echo 5 5 TEXT | gmt select -Ve                      
5	5	TEXT
```

**Comment by PaulWessel** [comment]
Usually, gmt select is given a directory on how to select, i.e., one of -C, -F, -G, -L, -R, -S, -Z.  If nothing is given the perhaps that should be an error instead of giving usage?

**Comment by seisman** [comment]
Sometimes I find it useful to run `gmt select` without any other options to remove the comments in the file or convert GMT/OGR format to a plaintext format (removing the ORG specific comments). It's also common to use options like **-i**, **-o**, **-h**, **-q** to process the data.

BTW, `gmt select input.dat` without any options also works. The only one that doesn't work is `echo 5 5 TEXT | gmt select`.

**Comment by PaulWessel** [comment]
Wouldn't gmt convert be the more logical module for this purpose?

**Comment by seisman** [comment]
Aha, didn't realize that "convert" is the better choice.

**Comment by PaulWessel** [comment]
Maybe just close this one?
