### ISSUE TITLE
Ellipses and circles wrong in gmt 5.4.3

### ISSUE THREAD

**Issue by gempa-dirk** [GenericMappingTools/gmt#3908]
**Description of the problem**

Circles and ellipses are not correctly plotted in Mercator projection. Circles always appear as circles no matter the latitude. Circles must be stretched, ellipse must be distorted.

**Full script that generated the error**

Ellipse:

```
echo 10 -83 45 3 1 | gmt psxy  -R0/20/-84/-82 -JM15 -Se -Gred -Bafg > map.ps
```

Circle:

echo 10 -83 45 3 3 | gmt psxy  -R0/20/-84/-82 -JM15 -Se -Gred -Bafg > map.ps

**Full error message**

The circle remains to be a circle in the plot and has not projection-related distortions.

**Actual outcome**

Circles appear as circles and the shape of ellipses does not change with latitudes

**Expected outcome**

circles and ellipses are stretched at high and low latitudes

**System information**

* Operating system: Ubuntu 18.04
* GMT version (`gmt --version`): 5.4.3

**Comment by PaulWessel** [comment]
The -Se option is for Cartesian ellipses.  See -SE for ellipses that follow geographical projections.

**Comment by gempa-dirk** [comment]
Fine. Seems to work correctly.
