### ISSUE TITLE
Breaking changes of CPTs?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3914]
Running `gmt makecpt -Cpolar`.

GMT 6.0.0 and 6.1.0 give:
```
-1	blue	0	white
0	white	1	red
B	black
F	white
N	127.5
```
but master gives:
```
gmt makecpt -Cpolar
-1	blue	0	white	L
0	white	1	red	B
B	black
F	white
N	127.5
```

It doesn't affect most use cases, but breaks the dcw-gmt plotting script (https://github.com/GenericMappingTools/dcw-gmt/blob/master/dcw-figure.sh).

**Comment by seisman** [comment]
Ping @PaulWessel to check if it's a feature or a new bug.

**Comment by PaulWessel** [comment]
Will check all these later after family zooms...

**Comment by PaulWessel** [comment]
Closing this as not affecting GMT.
