### ISSUE TITLE
Trouble with some shells like csh

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3916]
It seems that some shells like tcsh and csh will attempt to replace our inset/subset unknown projection width (e.g. **-JM?**) with a filename via UNIX wildcard expansion, as in this [failure](https://forum.generic-mapping-tools.org/t/error-when-make-the-map-insets/757/4) . However, unlike bash, zsh, if there is no match then csh will foolishly remove the question mark and GMT fails (as if all text on a commandline is a filename).  Users can be told to turn off globbing or escape the question mark with a backslash, but neither are great options.

Looking at my code in _gmt_init_module_, it should be possible to simply leave off the unknown width without the ? place holder.  This is because we have these situations only:

1. Geographic projection.  They all end with the scale or width so we know where to append the actual width
2. Cartesian -JXwidth or -JXwidth/height.  We know if a slash that the height is right after the slash and the width is right after the X.
3. Polar cylindrical.  The scale or width is the first item after -Jp|P, so if that letter is a modifier or NULL then we know where to put it

If we can get away with no specification, then ? can remain a backwards compatible way to do this (and it works fine for sensible shells), but we could move on and simply update the docs accordingly once we find this works.

**Comment by seisman** [comment]
> However, unlike bash, zsh, if there is no match then csh will foolishly remove the question mark and GMT fails

It's even worse. It fails not because the question mark is removed. When there is no match, the whole command fails without running the gmt command.

**Comment by seisman** [comment]
> 1. Geographic projection.  They all end with the scale or width so we know where to append the actual width

Is it always true? Some projections (for example, -JS) say:

> Scale as 1:xxxxx (true scale at pole), slat/1:xxxxx (true scale at standard parallel slat), or radius/latitude where radius is distance on map in plot-units from projection center to a particular oblique latitude (-Js), or simply map width (-JS).

So command like below is allowed:
```
gmt coast -R-30/30/60/72 -Js0/90/12c/60 -B10g -Dl -A250 -Groyalblue -Sseashell -pdf GMT_stereographic_polar
```

**Comment by PaulWessel** [comment]
Right, so that would be -Js0/90//60 and pretty easy to detect.  I think we we can pull it off, simply leaving the scale/width completely off, wherever it is, would be simpler for the users than any special character.
