### ISSUE TITLE
Allow gmt coast -M to dump a ASCII file

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#392]
CODE:
```
gmt coast -RIS -Dh -W -M
```

**Full error message**

```
gmt [ERROR]: Shared GMT module not found: coast
```

**Comment by seisman** [comment]
What about `gmt coast -E+l` to list country codes? It's a useful one-line command in modern mode.

**Comment by PaulWessel** [comment]
Yes, those things are similar to patent -L etc.
