### ISSUE TITLE
FORMAT_GEO_OUT with D and F/G does not work

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#3921]
When using ``FORMAT_GEO_OUT = D``, ``+D`` and ``D`` the ``F`` (_Encode sign using WESN suffix_) and ``G`` options does not work (https://docs.generic-mapping-tools.org/latest/gmt.conf.html#term-FORMAT_GEO_OUT).

E.g.

```
$ echo 14.545454 71.343333334334 | gmt convert -fg --FORMAT_GEO_OUT=DF
14.545454	71.3433333343
$ echo 14.545454 71.343333334334 | gmt convert -fg --FORMAT_GEO_OUT=DG
14.545454	71.3433333343
```

**Comment by PaulWessel** [comment]
FYI, these options work

```
gmt convert -fg t.txt  --FORMAT_GEO_OUT=ddd.xxxxxF
gmt convert -fg t.txt  --FORMAT_GEO_OUT=ddd:mm.xx.sssF
```

Even G works but I think we should plug that whole since it creates extra columns on output which makes no sense.

I am not sure if -DF and DG were meant to work for this given the specifics you can do with ddd...

**Comment by anbj** [comment]
Yes,  this works. Thanks for the tip. Shall I close?

**Comment by PaulWessel** [comment]
OK, we will close this,
