### ISSUE TITLE
Rename splitxyz to gmtsplit

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3928]
The **splitxyz** name is an odd duck and goes way back.  However, "xyz" is not really true anymore since we accept xy as well and more columns.  I suggest we do the same we did to other oddly named modules, such as **grdreformat** being changed to **grdconvert**, by allowing the old name as well but rename the official name to **gmtsplit**.

[Moved form old GMT wiki issue from 2012]

**Comment by PaulWessel** [comment]
Anyone for or against this proposal, or just have no opinion, @joa-quim and @seisman?

**Comment by seisman** [comment]
OK to me, as long as it's backward compatible.
