### ISSUE TITLE
Inconsistent behaviors of -q options

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3948]
Example data:
```
>
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
>
5  5  5
6  6  6
7  7  7
8  8  8
9  9  9
```

row number doesn't start from 0?
```
$ gmt convert input.dat -q0
gmtconvert [WARNING]: No data records provided
```

Same output for `-q0:5` and `-q1:5`:
```
gmt convert input.dat -q0:5
0	0	0
1	1	1
2	2	2
3	3	3
4	4	4
$ gmt convert input.dat -q1:5
0	0	0
1	1	1
2	2	2
3	3	3
4	4	4
```

Counter by segment:
```
$ gmt convert input.dat -q1:3
0	0	0
1	1	1
2	2	2

$ gmt convert input.dat -q1:3+s
>
1	1	1
2	2	2
3	3	3
>
6	6	6
7	7	7
8	8	8
```

**Comment by PaulWessel** [comment]
Yep, a problem here. Per documentation there are two principles:

- Only count data records, meaning segment headers are not counted and row numbers should not be increased.  In your case, the record counter is increased despite reading a segment header.
- First record is row = 0.  That is standard GMT so we want to honor that.

Will have a look.
