### ISSUE TITLE
Improve the gmtest script

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3949]
GMT's more than 900 test scripts are stored in three separated directories, `test`, `doc/examples`, and `doc/scripts`. Each  directory has its own gmtest script, and the three gmtest scripts are almost the same, except some difference on full path to test scripts. It seems possible to have only one gmtest script in the test directory and still be able to run the tests in other  directories. Thus, we don't have to maintain gmtest scripts at three separated places.

**Comment by PaulWessel** [comment]
yes, good ideal.  Those script are neither short nor clear, so having just one with a few more comments is probably a good plan.
