### ISSUE TITLE
pssolar - add moonrise, moonset and moons position

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#396]
Because lets be fair. Add to ``pssolar`` or make a ``psmoon``?

**Comment by KristofKoch** [comment]
A bit more work involved on your side but that data is available via an API for example from the U.S. Naval Observatory: https://aa.usno.navy.mil/data/docs/api.php

**Comment by abanbj** [comment]
Thanks for the tip @KristofKoch!
