### ISSUE TITLE
Warnings "Your primary y annotation interval exceeds the secondary interval"

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3963]
Running the -B examples in the cookbook. 
```
gmt begin GMT_-B_time1
	gmt set FORMAT_DATE_MAP=-o FONT_ANNOT_PRIMARY +9p
	gmt basemap -R2000-4-1T/2000-5-25T/0/1 -JX12c/0.5c -Bpa7Rf1d -Bsa1O -BS
gmt end show
```

The example above gives some warnings:
```
basemap [WARNING]: Your primary y annotation interval exceeds the secondary interval.
basemap [WARNING]: GMT expects it to be the other way around (primary annotations are closest to axis, secondary are further away)
basemap [WARNING]: Consider correcting your command - proceeding with your selections
```
The warnings doesn't make sense to me:

- There are no **Y** annotations
- Even for **X** annotations, the primary annotation interval (7 days) is still smaller than the secondary interval (1 month)

**Comment by seisman** [comment]
`-Bpa7Rf1d -Bsa1O` only makes sense to datetime axis. We should change it to `-Bpxa7Rf1d -Bsxa1O`.

**Comment by PaulWessel** [comment]
Yes, that was the first thing I tried and the messages stopped.  I will fix it.
