### ISSUE TITLE
anim07 needs updates

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3970]
Currently anim07 uses the following command:
```
gmt grdimage @earth_age_02m.grd+s0.01 -Is.nc -C@crustal_age.cpt -JG\${MOVIE_COL0}/15/10.8c -X0 -Y0
```

Issues:

1. should be `@earth_age_02m` without the `.grd` suffix
2. Is the `+s0.01` necessary? 
3. The CPT also needs update

One more related issue:
```
$ gmt grdinfo @earth_age_02m.grd+s0.01

grdblend [ERROR]: Unable to open file /var/folders/mz/d3wtwjtx4fg8qlds5lgt1c240000gn/T/=tiled_4_GX.JnvkhD+s0.01 for Input
: Title:
: Command:
: Remark:
: Gridline node registration used [Cartesian grid]
: Unrecognized grid file format! Probably not a GMT grid
: x_min: 0 x_max: 0 x_inc: 0 name: x n_columns: 0
: y_min: 0 y_max: 0 y_inc: 0 name: y n_rows: 0
: z_min: NaN z_max: NaN name: z
: scale_factor: 1 add_offset: 0
```

**Comment by PaulWessel** [comment]
The script predates the releast of the earth_age files, so the 0.01 was needed but not now I think.  There is now a default CPT for ages so probably should use that.  I will play with this - takes ours to run the final movie.

**Comment by PaulWessel** [comment]
Another problem is that each time @earth_*_02m is referenced we end up with a big grdblend job, for each frame.  The immediate solution is to use the pre script to run grdcut and get two global grids, then use those.  The longer term solution is that once all tiles are obtained we create teh global single grid and remove (?) the tile grid.

**Comment by PaulWessel** [comment]
Looks like movie and batch are the strongest arguments for why we should only tile a global grid once locally.

**Comment by PaulWessel** [comment]
A 2m grid makes this a very slow job.  We get a 1080 pixel picture of a hemisphere, which is 180 degrees.  So 1080 / 180 suggests about a 10m grid on average.  Because of projection that is not true everywhere, but wonder if doing this with the 06m grid will look just as good.  I will test that since 6m is the last single size grid.

**Comment by PaulWessel** [comment]
Adding a plug for #3973 here.

**Comment by seisman** [comment]
Closing the issue. 

The issue for `gmt grdinfo @earth_age_02m.grd+s0.01` is off-topic. I just opened a new issue (https://github.com/GenericMappingTools/gmt/issues/3980) for it.
