### ISSUE TITLE
Make writing animation scripts simpler

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3976]
**Description of the desired feature**

The least intuitive part of writing the scripts for **movie** is the use of the built-in variables (e.g., **MOVIE_COL3**).  The actual syntax varies with the scripting language and if one is using the UNIX [here-document](https://en.wikipedia.org/wiki/Here_document) method to create the main and pre scripts inside a single movie script it requires us to _escape_ the dollar signs to preserve the full variable name (e.g., \\$MOVIE_COL3).  It is pretty easy even for experienced scripters to forget the backslash and then the script is no longer working.

A solution would be to simply use the variable names as is, e.g. MOVIE_COL3, and have movie on the fly replace that with ${MOVIE_COL3} or %MOVIE_COL3% depending on the script language.  This simplifies most uses of these variables.  It does not prevent anyone from using the special characters but it makes them optional.  Since there is only a small, finite set of parameters it should be easy to do.

**Comment by PaulWessel** [comment]
Can you see any downsides to this, @joa-quim or @seisman? So things like **$MOVIE_FRAME**, **%MOVIE_FRAME%,** **${MOVIE_FRAME}** will be left as is but **MOVIE_FRAME** (without those things around it) will be expanded using the syntax of the chosen shell.  Any special situation in batch or UNIX shell that could cause trouble?  `let n=MOVIE_FRAME+10` works the same with or without $ so should not matter if this becomes` let n=${MOVIE_FRAME}+10`. Maybe there could be non-unique things like `echo "MOVIE_FRAME is a variable" `and `echo "$MOVIE_FRAME is a variable"` where the first just wants to print that text while the second wants the variable substitution.  I guess if found inside quotes we leave as is?

**Comment by seisman** [comment]
To me, the easiest way is to write the main, include, pre and "gmt movie" scripts in separated files. 

You solution may not work for the include script (the **-I** option), right?

Take the anim09 for example, 

Using here document, the projection is written with too many backslashes:
```
-JG\${MOVIE_COL0}/\${MOVIE_COL1}/\${ALTITUDE}/\${MOVIE_COL2}/\${TILT}/\${MOVIE_COL3}/\${WIDTH}/\${HEIGHT}/\${MOVIE_WIDTH}
```

With your solution, it can be rewritten as
```
-JGMOVIE_COL0/MOVIE_COL1/\${ALTITUDE}/MOVIE_COL2/\${TILT}/MOVIE_COL3/\${WIDTH}/\${HEIGHT}/MOVIE_WIDTH
```
It looks more confusing to me.

**Comment by PaulWessel** [comment]
Yes, that is true, but not sure if that is representative of most movie script.  I don't know.  But as long as we accept both ways I don't see a problem.  We cannot guess that WIDTH should be $WIDTH but we would know that MOVIE_COL2 should have a special sign.  Remember, I am trying to lowering the bar so you don't need to know too much about programming scripts to do this.  I am guessing a rookie trying to write a movie script might find reading about MOVIE_COL2 and using MOVIE_COL2 as is would be less confusing than reading about "now, for bash, you need ${} but for DOS you need %...%, etc).  That was the ugliness I am trying to hide from new users.  Gurus knows what to do.

**Comment by PaulWessel** [comment]
Agreeing that this is not a uniformly good suggestion, so closing.
