### ISSUE TITLE
A couple of halph bugs in plot3d

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3983]
1- The fill should extend to the vertical walls
2- The *x,y* gridlines as well
3- The cube should be open (new option to not show the facing two faces)
4- Z annot labels should be horizontal by default (probably only in a new theme to not break compat)

```
gmt basemap -JX12c/0 -Bafg -Bzag -BWSenZ+b+ggray -p210/30 -JZ10 -R-2/2/-1/3/0/4 -png map
```

![map](https://user-images.githubusercontent.com/537321/90344564-be012280-e012-11ea-9fb9-74c00c97161b.png)

**Comment by PaulWessel** [comment]
> 1- The fill should extend to the vertical walls

Always, or as options
> 2- The _x,y_ gridlines as well

That should be doable
> 3- The cube should be open (new option to not show the facing two faces)

I think the **+b** modifier could do more here. It is the box modier and could take args to allow some of the changes you want.
> 4- Z annot labels should be horizontal by default (probably only in a new theme to not break compat)

Yes I agree but perhaps by modifier?
> 
> ```
> gmt basemap -JX12c/0 -Bafg -Bzag -BWSenZ+b+ggray -p210/30 -JZ10 -R-2/2/-1/3/0/4 -png map
> ```
> 
> ![map](https://user-images.githubusercontent.com/537321/90344564-be012280-e012-11ea-9fb9-74c00c97161b.png)

**Comment by Esteban82** [comment]
I think it is related with3). In [3D view of Parana Basin](https://forum.generic-mapping-tools.org/t/3d-view-of-parana-basin/519) I used the plot3d twice. I add +b the first time I used it (to plot the grayscale surface). So, then I used it again (with the color one) and this surface overlap the outlne of the cube in the front of the figure (near the river mouth).

**Comment by joa-quim** [comment]
>    1- The fill should extend to the vertical walls
> Always, or as options

I think always. That's what Matlab does. If user wants only the base he can do it with two calls.

- 3 Thinking better, the cube should be always open. Why would one want to draw 3 lines ON TOP of the image?

**Comment by PaulWessel** [comment]
I started last night to add new frame options +x[fill], +y[fill] so they are optional, can take same fill as the ground, or be separate.  But struggling with a few issues so on hold during my meetings...

**Comment by PaulWessel** [comment]
Branch wall-paint will let you run

`gmt basemap -JX12c/0 -Bafg -Bzag -BWSenZ+b+ggray -p200/35 -JZ8 -R-2/2/-1/3/0/4 -png map
`

but for reasons I dont yet understand, the gridlines are plotted behind the painted walls even though the code writes them second...

**Comment by seisman** [comment]
Close the issue?

**Comment by PaulWessel** [comment]
Yes, all done and for the better.
