### ISSUE TITLE
Nicer clipping of lines/polygons at map region boundaries

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#402]
(Issue is based on this forum thread: http://gmt.soest.hawaii.edu/boards/1/topics/8037)

**Description of the problem**

When a line or polygon intersects the map region boundary its clipping point is exactly at the boundary. While logically correct, it is not visually pleasing for _line pen width_ > _map boundary pen width_ : 

![image](https://user-images.githubusercontent.com/45796239/52325656-1e5ae100-29e6-11e9-913d-e44b83971fd6.png)
The issues are the "bleeding" over the map region boundary and the "missing" wedge inside the plot. Basically the current implementation is only correct for zero _line pen width_ or for an intersect angle between the line and the boundary of exactly 90°. 

The desired result is more like this mockup:

![image](https://user-images.githubusercontent.com/45796239/52325882-fd46c000-29e6-11e9-8edf-7ccbd08d91ed.png)
**Possible solution**

The solution @PaulWessel suggested in the forum thread:
> Whenever a line intersects the map boundary and we clip the line to the starting point, we must instead extend the start of the line geometrically backwards/outwards so its end point is 0.5 pen thickness from the boundary. […] GMT will set up a clip path so that we will achieve the desired result.

![ugly_explain-o-graph](https://user-images.githubusercontent.com/45796239/52326020-84943380-29e7-11e9-8823-44fb2d1d531c.png)

This is basically a visualization of Pauls idea.

**Script that generated the error**

This is the simple script that generates the _red line example_ above. 

```
#!/bin/bash

FILE=test_bleeding_pen.ps

gmt psxy \
    -R7.5/49.5/9.5/50.5r \
    -JL8.5/50/49.75/50.25/15c \
    -Bwesn \
    -W35p,red \
    > $FILE << END
 7.6 49.4
10   49.9
END
```

**System information**

* Operating system: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0 x86_64)
* Version of GMT: 6.0.0_f5755c1 [64-bit] [MP] [4 cores]

**Comment by PaulWessel** [comment]
I think I have a general solution to this issue:  When we prepare lines for plotting then we clip them at the map boundary if they go outside.  This results in lines whose first point has a pen flag = PSL_MOVE (i.e., move pen to this point), followed by 1 or more points with PSL_DRAW (keep pen down) until we reach the last point.  If instead we added a new bit flag PSL_CLIP to the array of pen flags for such points, then the flags for a line segment that was clipped at the map boundary in both ends would be PSL_MOVE|PSL_CLIP, PSL_DRAW, PSL_DRAW, ..., PSL_CLIP.  Now, gmt_plot_line can use those bit flags to determine if an end point needs to first have an extension outward of length given bybasic trig involving the pen thickness.  I think this should be relative straight forward. 

1. Replace tests like "if (pen == PSL_MOVE) ..." with "if (pen & PSL_MOVE) ..." and make sure nothing breaks.
2. Experiment with adding the PSL_CLIP bits to the clipped coordinates and make sure nothing breaks.
3. Implement the line extension and test it.

This should ensure I dont add any bugs in the process.

**Comment by PaulWessel** [comment]
When running with branch shown in #426, @KristofKoch's example above with two additional lines gives the illustration shown here.
[t.pdf](https://github.com/GenericMappingTools/gmt/files/2863583/t.pdf)

**Comment by KristofKoch** [comment]
I'm closing this issue as it is solved for the majority of cases and the discussion has shifted to #426
