### ISSUE TITLE
Errors in Argentina provinces (N2) in the GSHHG.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4032]
I compare the limits of the argentine provinces from national oficial site (dashed black lines) with the GSHHG (pscoast -N2, red lines).  As you can see in the figure, there are some errors. How can I help to fix these errors? Could I provide the data in a particular format? The data should be as polygon or lines? Also, then I will check the DCW data.

![EJ1 5_Argentina_Ver_Limites](https://user-images.githubusercontent.com/17908951/90970828-efc92c00-e4df-11ea-8968-f98ce0bd218b.png)

**Comment by seisman** [comment]
Closing the issue as it was already reported in the gshhg repository.
