### ISSUE TITLE
"gmt defaults" download all GSHHG data when they're not installed locally

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4039]
After #3644 and #3645 is merged, running `gmt defaults` downloads all GSHHG files (all resolutions) when the data are not installed locally.

I believe this is not what we want, right?

BTW, it just download GSHHG, not DCW data.

**Comment by PaulWessel** [comment]
Hm, cannot reproduce.  I renamed the gshhg directory, deleted stuff in .gmt and ran gmt defaults.  Nothing got downloaded.

**Comment by PaulWessel** [comment]
Sorry, can reproduce.  GMT looked in many places...
