### ISSUE TITLE
grdview/cuerpo.sh fails on master 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4043]
| Old  | New  |
|---|---|
| ![image](https://user-images.githubusercontent.com/3974108/91088177-8fd99f00-e61f-11ea-91d7-133851260540.png) | ![image](https://user-images.githubusercontent.com/3974108/91088203-98ca7080-e61f-11ea-8f0d-472ce23aee00.png) |

**Comment by PaulWessel** [comment]
So I am trying to fix that and thought I had the solution.  However, the strangest thing:  The PostScript plot looks good, and computing a PNG from it looks good, but if I do a PDF the fat checkerboard basemap has the wrong perspective.
Here is the PNG and attached is the PDF.
![cuerpo](https://user-images.githubusercontent.com/26473567/91117044-6de51a00-e629-11ea-9294-cf0ff6c0d728.png)

[cuerpo.pdf](https://github.com/GenericMappingTools/gmt/files/5121108/cuerpo.pdf)

What I am seeing is this:
![Untitled](https://user-images.githubusercontent.com/26473567/91117181-b4d30f80-e629-11ea-96c2-66020968c657.png)

**Comment by PaulWessel** [comment]
Update: Looks fine in Adobe Acrobat.  Preview bug?  gs cuerpo.pdf looks fine too.  I will reboot since this triggers some bad memory.

**Comment by PaulWessel** [comment]
I get the same on my laptop with files produced Aug 21.  However, "open cuerpo.ps" works fine.  Can you duplicate this, @seisman ?  gs 9.50 still.

**Comment by PaulWessel** [comment]
**Works:**

`gmt basemap -R-70:10:17.05/-70:10:0.10/-42:40:31.10/-42:40:19.95 -JM-70:10:13.525/-42:40:25.525/3.5i -Ba10sf10s -BWESN  -p315/30/550 -ps map1`

**Fails:**

`gmt basemap -R-70:10:17.05/-70:10:0.10/-42:40:31.10/-42:40:19.95 -JM-70:10:13.525/-42:40:25.525/3.5i -Ba10sf10s -BWESN -p315/30/550 -pdf map2`

**Comment by seisman** [comment]
Yes, I can reproduce what you have.

**Comment by seisman** [comment]
It looks a Preview bug to me. Is there anything GMT can do?

**Comment by PaulWessel** [comment]
Not sure if we can.  I think we simply did not notice this since it passes the tests since the PNG is OK.  It is just PDF in Preview, the PDF looks fine in other viewers.  I can try to slap some gsave/grestore around the 3-D map to see if that can trick it.
