### ISSUE TITLE
Better DIR_DCW and DIR_GSHHG if data aren't pre-installed

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4053]
**Description of the problem**

If DCW and GSHHG are not pre-installed when building GMT, DIR_DCW and DIR_GSHHG have invalid values.
```
#
# DIR Parameters
#
DIR_CACHE                      = /Users/seisman/.gmt/cache
DIR_DATA                       = /Users/seisman/.gmt/data
DIR_DCW                        = DCW_PATH-NOTFOUND
DIR_GSHHG                      = GSHHG_PATH-NOTFOUND
```

These invalid values don't break GMT, but perhaps in this case, we should set them to `~/.gmt/geography/gshhg` and `~/.gmt/geography/dcw`?

**Comment by PaulWessel** [comment]
Yes, can do that.  I guess just search for NOTFOUND in the path and do the replace?  This is just in the place where I turned off the download part in gmt_init.c

**Comment by PaulWessel** [comment]
in gmt_init when we initialze GMT we have this:

```
	if (GMT->session.DCWDIR)
		gmt_M_str_free (GMT->session.DCWDIR);
	GMT->session.DCWDIR = strdup (DCW_INSTALL_PATH);
	/* DIR_GSHHG */
	if (GMT->session.GSHHGDIR)
		gmt_M_str_free (GMT->session.GSHHGDIR);
	GMT->session.GSHHGDIR = strdup (GSHHG_INSTALL_PATH);
```

It is those INSTALL_PATHS that have the NOTFOUND strings in them.  I can detect that and then need to use the USERDIR settings to form those paths.

**Comment by seisman** [comment]
It should work, but I'm not sure if it's a good idea to check the "NOTFOUND" string, which is cmake specific.

**Comment by PaulWessel** [comment]
Isn't the point to detect when the user has not configured GSHHG and DCW during the build/install and hence those settings ad NOTFOUND?  What else should I check for?

**Comment by seisman** [comment]
Yes, you're right. I think I misunderstood how it works.

**Comment by PaulWessel** [comment]
Please test to see if the PR gives the expected paths for you.
