### ISSUE TITLE
Improve the documentation of the image/psimage module

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4066]
**Description of the problem**

The image module documentation says:

> image: Plot raster or EPS images
>
> This must be an Encapsulated PostScript (EPS) file or a raster image. An EPS file must contain an appropriate BoundingBox. A raster file can have a depth of 1, 8, 24, or 32 bits and is read via GDAL. Note: If GDAL was not configured during GMT installation then only EPS files are supported.

It's not true. With GDAL enabled (although it's optional), it can plot PDF images and maybe other formats. We need to improve the documentation to clarify this point.

One more thing, when I run something like `gmt image XXXX.pdf -Dx0/0+w7c -pdf plot`. I thought the PDF image will be plotted as an vector image, but actually it's plotted as a raster image. It's limited by how GDAL works?

**Comment by joa-quim** [comment]
Very likely. The PDF driver in GDAL is an hard beast.

**Comment by PaulWessel** [comment]
May be better off converting that PDF to EPS then.
