### ISSUE TITLE
gmtspatial dosen't work for self intersections

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#407]
This works fine with   ``x2sys_cross`` 
```
x2sys_cross -TLINE l9-25.txt -Qi > cros_9-25.dat
```
but doesn't with gmtspatial
```
gmtspatial l9-25.txt -Ii > cros_9-25.dat
```

[l9-25.txt](https://github.com/GenericMappingTools/gmt/files/2843038/l9-25.txt)

**Comment by PaulWessel** [comment]
Could you please also post LINE.def?

**Comment by joa-quim** [comment]
line.def
```
#
# Define file for X2SYS processing of ASCII lon,lat,z files
#
# This file applies to plain 3-column ASCII files.
#
#---------------------------------------------------------------------
#ASCII		# The input file is ASCII
#GEO		# Data are geographic 
#---------------------------------------------------------------------
#name	intype	NaN-proxy?	NaN-proxy	scale	offset	oformat
lon	a	N		0		1	0	%10.5f
lat	a	N		0		1	0	%9.5f
sst	a	N		0		1	0	%7.2f
```

**Comment by PaulWessel** [comment]
Sorry, there must be an x2sys_init call somewhere so need that to replicate exactly what you did.

**Comment by joa-quim** [comment]
```
x2sys_init LINE -Dline -Etxt -G -F
```
But the point is not on x2sys that works, but about gmtspatial that doesn't.

**Comment by PaulWessel** [comment]
Looks like there are > 2000 km jumps in your file and no segment headers indicating different lines?  I suspect this is the cause of the problem (x2sys_cross may see that as a gap but gmtspatial does not know this). So my verdict is user error unless you can convince me otherwise.

**Comment by joa-quim** [comment]
Yes, 2000 km jumps there are. BG, I suspect the NASA guys are screwing in the coordinates . Consider our satellite image example in the GMTMEX paper. The files have independent arrays for lon, lat and sst. The acquisition is by scanlines so the coordinates should not intercept. But they damn do, and a lot. Just open the attached kml and zoom on the left side. Labels are the line numbers and they are NOT in order (they are at the swath center). This means there must be crazy line crossings. So I decided to see what are the COEs but to be minimize the amount of torture in the procedure I consider only a few firs scan lines, let them all be in the same file and ask for internal COEs. x2sys_sys seem to work but also does not detect the 2000 km jumps (I see no gap option in cross). gmtselect just gives what you see.

[MironeTec.kml.zip](https://github.com/GenericMappingTools/gmt/files/2846410/MironeTec.kml.zip)

**Comment by joa-quim** [comment]
With #411 and looking only at the first 100 rows of the 2030 from L2 file, we can see lots of non-zero COEs, so ...
![coe](https://user-images.githubusercontent.com/537321/52505596-ecaf6900-2be3-11e9-976e-cbda9db4efc0.png)

**Comment by PaulWessel** [comment]
x2sys_cross via x2sys_init has default gaps of infinity, so should not ignore any gaps unless something else is happening on your settings.

**Comment by joa-quim** [comment]
Ah, I did not use -Wd<gap> in x2sys_init
