### ISSUE TITLE
Wrong side of Y annotations in a 3D view 

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4077]
In the example 
https://forum.generic-mapping-tools.org/t/surface-plot-of-ackley-function/601
the Y annotations are now invisible.

Same as
```
gmt basemap -JX12c/0 -Baf -Bza -BWSenZ -p135/30 -JZ10 -R-5/5/-5/5/0/10 -png map
```
![map](https://user-images.githubusercontent.com/537321/91495166-0db4d900-e8b2-11ea-8013-c08a7004dc83.png)

**Comment by PaulWessel** [comment]
Wrong side? You have selected WS as the annotated sides and that is what you got, no?

**Comment by joa-quim** [comment]
Yes, shit, one more of my defaults in Julia that is backfiring. I didn't even see the WS
