### ISSUE TITLE
Arrow heads with double color

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4082]
This is a minimalist of my "Snake Skier" example in Julia. The arrows now double-colored

```
julia> lines([0.0 0; 5 5], pen=(lw=7,lc=:sienna, arrow=(len=2.2,shape=:arrow, fill=:darkgreen)), Vd=1, show=1, fmt=:png)
        psxy  -JX12c/8c -Baf -BWSen -R-0.2/5.2/-0.2/5.2 -W7,sienna+v2.2+gdarkgreen+h1 -P -K > C:\TMP\GMTjl_tmp.ps
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/91505632-f1239b80-e8c7-11ea-8f85-651758253c34.png)

**Comment by PaulWessel** [comment]
I cannot tell if you are posting a bug or showing off a feature?  You selected dark green to fill the vector heads and a fat sienna pen to draw lines.  Looks good?

**Comment by joa-quim** [comment]
This is how it used to plot

![image](https://user-images.githubusercontent.com/537321/91506465-0ac5e280-e8ca-11ea-9b6b-8dc73638da82.png)

**Comment by PaulWessel** [comment]
Seems a few different regresses on pens today.  I think inheriting the line pen as arrow outline should only happen if fill is not set.

**Comment by PaulWessel** [comment]
Actually, this is the documentation:

+p[pen] sets the vector pen attributes. If no pen is appended then the head outline is not drawn. [Default pen is half the width of stem pen, and head outline is drawn]. Above, we used +p2p,orange. The vector stem attributes are controlled by -W.

The default is to draw with half pen width.  Use +p with no args to turn off outline.  We may have had a bug in this stuff.

**Comment by joa-quim** [comment]
I think I liked the bugged behavior better. **+p**_pen_ could be used to set a different outline than the fill color if wished. Otherwise just paint the whole header with the fill color. Simpler.

**Comment by PaulWessel** [comment]
I wish we wrote down the reasons for changes, but I am pretty sure this revision had to happen in order to handle things consistently.

**Comment by PaulWessel** [comment]
Would someone as smart as @seisman know a way to see how this command's output might have changed over the last versions:

`echo 0 0 2 0 | gmt plot -R-1/3/-1/1 -Jx2i -B -W7p,sienna -Sv48p+s+b+e+gdarkgreen -png map`

Currently gives this which is compatible with the docs, but I am open to determine if we haev broken something backwards here:

![map](https://user-images.githubusercontent.com/26473567/91609679-8e57f180-e913-11ea-907b-dd9992a2aabc.png)

**Comment by seisman** [comment]
I don't understand it. GMT 6.0.0 gives the same results. What do you want me do?

**Comment by PaulWessel** [comment]
Hm, from @joa-quim Julia-plot I assumed perhaps GMT had made some changes but I think his example post-dates 6.0.0 so we need him to explain why it changed for him if GMT has not changed in that time.

**Comment by seisman** [comment]
Issue https://github.com/GenericMappingTools/gmt/issues/404 and PR https://github.com/GenericMappingTools/gmt/pull/415 may be related, but that's before the 6.0.0 release.

**Comment by PaulWessel** [comment]
The Julia wrapper started before 6.0.0 so I suspect it is out of sync with >= 6.0.0 on this issue.  He will surface eventually - Friday is usually trip to Lisbon.  But I think the evidence points toward GMT being consistent at least since those older fixes (thanks for digging those up).

**Comment by joa-quim** [comment]
Not Lisbon but still summer dinners. 

The Snake fig was done for last AGU after 6.0

Sent from my iDedo

**Comment by joa-quim** [comment]
I rebuild a version of 26 November and some shit errored when used the Julia call. But the pure GMT call already showed this behavior. Maybe I used a fig version created in 2018.

**Comment by seisman** [comment]
It sounds we can close the issue.
