### ISSUE TITLE
Incorrect translation of "february" in gmt_it.locale

### ISSUE THREAD

**Issue by crish4cks** [GenericMappingTools/gmt#413]
Hi,
I've noticed a possible wrong translation of "february" in gmt_it.locale.
Here below I've attached a simple patch.

Thank you in advance for your time.

Best regards,
Cristiano Urban.

[gmt_it.locale.patch.tar.gz](https://github.com/GenericMappingTools/gmt/files/2847714/gmt_it.locale.patch.tar.gz)

**Comment by joa-quim** [comment]
Thanks. Applied directly in master.
