### ISSUE TITLE
Ex08 failure

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4133]
The diff image

![ex08](https://user-images.githubusercontent.com/537321/91776697-ce55f780-ebe5-11ea-8daa-358cd0c2ffbe.png)

**Comment by PaulWessel** [comment]
I think all those pass on the CI for Windows, @seisman ?.  The data file and the script changed recently, make sure your cached files are fully updated.

**Comment by seisman** [comment]
Yes, it passes in ci.

**Comment by joa-quim** [comment]
We must replace this with synthetic data. Can't be changing data/PS every month.

**Comment by PaulWessel** [comment]
I agree we could do that.  But we will still have lots of other examples using the same dataset (5m).  Has not changed since refresh in June?

**Comment by joa-quim** [comment]
I got failures for GMT_tut_11.sh, GMT_tut_18.sh and grdcontour/contours.sh. All seem to be related to data change. We must stabilize this. And BTW GMT_tut_11 & contours seem to be testing exactly the same thing.

**Comment by PaulWessel** [comment]
Tut 11 is just a rough contour map over Bermuda. contours.sh tests orientation of contours via -F option as well as some coloring by distance.

**Comment by joa-quim** [comment]
So we could drop Tut 11 from the test set.

**Comment by PaulWessel** [comment]
So that would be the only tutorial script we don't have in the test but that we still have to make a plot for to use in the docs?  That does not make much sense to me.

**Comment by joa-quim** [comment]
The tests are for testing, right? Build figs for docs is another thing. The test suit is very big and takes long time, with tests taking 1, 2 and even 3 minutes to run. I run them rarely mainly because it.

**Comment by PaulWessel** [comment]
I know, we will need to work on this.  It should mostly be done in the CI, and probably at some point we will need to split tests into subsets and run those on separate days of the week or month.

**Comment by seisman** [comment]
The CI runs the full tests nightly. It takes ~20 min on macOS, ~30 min on Linux and ~90 min on Windows.

**Comment by seisman** [comment]
BTW, it seems straightforward to split all tests into three groups (tests, examples and scripts in the docs). I may find some time working on it later.

**Comment by seisman** [comment]
I think we can close the issue, as ex08 passes.
