### ISSUE TITLE
Clarify -Js aspects.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4139]
The cookbok says 
> A map scale factor of 0.9996 will be applied by default (although you may change this with PROJ_SCALE_FACTOR). However, the setting is ignored when a standard parallel has been specified since the scale is then implicitly given.

but the [docs ](https://docs.generic-mapping-tools.org/6.0/gmt.html#j-full) do not mention the scale factor.
> -Jslon0/lat0[/horizon]/scale or -JSlon0/lat0[/horizon]/width (General Stereographic [C]).
    lon0/lat0 specifies the projection center. horizon specifies the max distance from projection center (in degrees, < 180, default 90). Give scale as 1:xxxx (true at pole) or lat0/1:xxxx (true at standard parallel lat)

The problem is that if there is a scale factor then it means that the latitude of true scale is not 90º, right? And what is that *ts* value? For Example this [wiki ](https://en.wikipedia.org/wiki/Universal_polar_stereographic_coordinate_system) says UPS has a scale factor of 0.994 and that it corresponds to a *ts=81.11451786859362545*, so a 0.996 must also correspond to a certain *ts != 90*.

This needs to be taken into account when establishing the **-Js** <=> proj4 strings.

**Comment by PaulWessel** [comment]
Yes, this could be improved.  THe 0.996 etc was done back in the early 1990s and I did not really know much.  I am sure there must be something in Snyder for converting scale factor to latitude for given projection.
