### ISSUE TITLE
CMake Error Library found but netCDF-4/HDF5 format unsupported

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/gmt#414]
**Description of the problem**

Hi there,

I'm trying to compile/install GMT from github on my university workstation running Ubuntu following the instructions at http://gmt.soest.hawaii.edu/projects/gmt/wiki/BuildingGMT and also looking at [build-gmt.sh](https://github.com/GenericMappingTools/gmt/blob/master/ci/build-gmt.sh), but I'm having trouble with the script not finding netCDF-4/HDF5 format support. This is even though I've installed `libnetcdf-dev` (along with the other required dependencies).

The weird thing is that the compile works fine on my laptop (running Debian Testing) and on a docker image I've built (using Ubuntu Bionic). I'd like to know how I can debug this situation better as it might be due to libraries from different PATHs getting mixed in, so feel free to ask for more information.

**Full script that generated the error**

```
git clone --depth=1 https://github.com/GenericMappingTools/gmt.git
cd gmt
mkdir build
cd build
cmake -G Ninja ..
```

**Full error message**

```
CMake Deprecation Warning at CMakeLists.txt:61 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Unable to determine svn version number for non-public release - ignoring.
-- Found UnixCommands: /bin/bash  
-- Searching dependent libraries. This may take a few minutes...
-- Looking for nc_def_var_deflate
-- Looking for nc_def_var_deflate - not found
CMake Error at cmake/modules/FindNETCDF.cmake:131 (message):
  Library found but netCDF-4/HDF5 format unsupported.  Do not configure
  netCDF-4 with --disable-netcdf-4.
Call Stack (most recent call first):
  src/CMakeLists.txt:45 (find_package)


CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NETCDF (missing: HAVE_NETCDF4)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNETCDF.cmake:136 (find_package_handle_standard_args)
  src/CMakeLists.txt:45 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/.../gmt/build/CMakeFiles/CMakeOutput.log".
See also "/home/.../gmt/build/CMakeFiles/CMakeError.log".
```

**Output of `nc-config --all`**

```
This netCDF 4.6.0 has been built with the following features: 

  --cc        -> /usr/bin/cc
  --cflags    -> -I/usr/include -I/usr/include/hdf5/serial
  --libs      -> -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5_hl -lhdf5 -lpthread -lsz -lz -ldl -lm -lcurl

  --has-c++   -> no
  --cxx       -> 

  --has-c++4  -> no
  --cxx4      -> 

  --has-fortran-> no
  --has-dap   -> yes
  --has-dap2  -> yes
  --has-dap4  -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-logging-> no
  --has-pnetcdf-> no
  --has-szlib -> no
  --has-cdf5 -> no
  --has-parallel-> no

  --prefix    -> /usr
  --includedir-> /usr/include
  --libdir    -> /usr/lib/x86_64-linux-gnu
  --version   -> netCDF 4.6.0
```

**System information**

* Operating system: Ubuntu Bionic
* Version of GMT: GMT from Github master branch commit 2f1f82999ff9ee9b892c83c22324d2ea7a12c76e

**Comment by PaulWessel** [comment]
The line

> Looking for nc_def_var_deflate - not found


is troubling.  Can you verify that that function in fact is in the export table of the .so file, e.g., does

nm -gU /path/to/libnetcdf.so | grep nc_def_var_deflate

show it?

**Comment by weiji14** [comment]
This is the result:

```
$ nm -gu /usr/lib/x86_64-linux-gnu/libnetcdf.so | grep nc_def_var_deflate
nm: /usr/lib/x86_64-linux-gnu/libnetcdf.so: no symbols
```

**Comment by PaulWessel** [comment]
Maybe need to run some other command on Ubuntu.  Google how to list contents of a shared object file.  Or do it on the *.a file if it exists.  Do it without the piping to grep to make sure stuff is being listed.

**Comment by weiji14** [comment]
```
$ nm -D /usr/lib/x86_64-linux-gnu/libnetcdf.so.13 | grep nc_def_var_deflate
0000000000022170 T nc_def_var_deflate
```

**Comment by PaulWessel** [comment]
Good, so the check if failing for some other reason.  Looking at the FindNETCDF.cmake file it has

`	check_symbol_exists (nc_def_var_deflate netcdf.h HAVE_NETCDF4)
`

so it checks that the nc_def_var_deflate function prototype is listed in your netcdf.h file. Perhaps you have more than one such include file and it gets the wrong one?  It does not check the library file (I was wrong), only the include file.

**Comment by weiji14** [comment]
Mm, I can see one at `/usr/include/netcdf.h`. Will see if I can find another one somewhere else, there's a lot of pre-installed libraries on this university computer :sweat_smile:

**Comment by PaulWessel** [comment]
grep nc_def_var_deflate /path/to/netcdf.h
and if nothing is returned then it won't work.

**Comment by weiji14** [comment]
So the one at `/usr/include` works:

```
$ grep nc_def_var_deflate /usr/include/netcdf.h
 * property can be set with the function nc_def_var_deflate(). */
nc_def_var_deflate(int ncid, int varid, int shuffle, int deflate,
```

I've also found some `netcdf.h` files in my ~/miniconda3 directory:

```
$ find -name 'netcdf.h'
./pkgs/libnetcdf-4.6.1-h628ed10_200/include/netcdf.h
./envs/gmt-python/include/netcdf.h
```

which is a hangover from my old [gmt conda](https://anaconda.org/conda-forge/gmt) installation from developing gmt-python (now [PyGMT](https://github.com/GenericMappingTools/pygmt)). I don't think it should matter but I'll remove that conda environment anyway and see if the compile works.

**Comment by weiji14** [comment]
Nope, cleaning up the conda `netcdf.h` files didn't work, still getting the original error message. I've had a look in the `CMakeError.log` and this is what it shows:

```
Determining if the nc_def_var_deflate exist failed with the following output:
Change Dir: /home/.../gmt/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_00e25"
ninja: error: '/usr/local/lib/x86_64-linux-gnu/libhdf5_hl.so', needed by 'cmTC_00e25', missing and no known rule to make it

File /home/.../gmt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <netcdf.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef nc_def_var_deflate
  return ((int*)(&nc_def_var_deflate))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

**Comment by PaulWessel** [comment]
Thanks, so you dont have hdf5 installed it seems?

**Comment by weiji14** [comment]
It *was* installed, but the build script was looking inside `/usr/local/lib/` before `/usr/lib`, and the former folder had those broken libhdf5*.so symlinks. Removing the broken symlinks lets the script look inside `/usr/lib` and the compilation now works!

Closing this as it's basically resolved. Thanks @PaulWessel.

**Comment by jpesicek** [comment]
Had a similar issue that this helped resolve on osx, thanks
