### ISSUE TITLE
Auto legends for histograms 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4143]
**Description of the desired feature**

Auto-legend (**-l**) would be very useful when plotting multiple histograms in one plot. For example (example figure from https://www.r-graph-gallery.com/2-two-histograms-with-melt-colors.html):

![image](https://user-images.githubusercontent.com/3974108/91892250-4cef7b00-ec60-11ea-8f64-68bb1788f3f7.png)

**Comment by PaulWessel** [comment]
May not be too hard.  I suppose we must pick a sensible square symbol size. The width of the bar? Always, even if very thick?

**Comment by joa-quim** [comment]
No, squares like Dongdong's example.

**Comment by PaulWessel** [comment]
You read my message to fast.  it says square symbol size.

**Comment by joa-quim** [comment]
Oops, yes. It was the *Always, even if very thick?* that overlapped the square. What you mean *same as with of the bar*? That can be 1 cm or more.

**Comment by PaulWessel** [comment]
I am thinking that we should have a default max size in mind given plot size, and if the bar is wider than that then we go with the default, else we use the bar width as square dimension.  The user also has the option of overriding all that via +s.  Looks like a few % of map width might be a reasonable default size?

**Comment by PaulWessel** [comment]
OK, fontsize is a good measuring rod.  Rectangles: A bit awkward to specify via +s I think, but I like your legend.  We could default to a rectangle with those proportions given the default height (is that ~ 3:2 ratio) but if user interferes we set a squre?

**Comment by seisman** [comment]
Perhaps you misunderstood what I expect. Here is what I expect:

- Left: default behavior, squares with width and height determined by font size
- Middle: squares for a larger font size
- Right: using **+s** to increase the width only. **+s1.5** means width=1.5*height=1.5*fontsize

![image](https://user-images.githubusercontent.com/3974108/92172261-a1822a00-ee09-11ea-9380-78ce1aa42b95.png)

**Comment by PaulWessel** [comment]
yes, I misunderstood.  This is a good plan to me.  Ok with @joa-quim ?

**Comment by joa-quim** [comment]
House is under inner paintings. Chaos all around. I’m fine with everything 

Sent from my iDedo
