### ISSUE TITLE
Default value for grdcontour -Gd and similar for quoted and decorated lines

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4167]
**Description of the desired feature**

It says

	    `   d<dist>[c|i|p] or D<dist>[d|m|s|e|f|k|M|n|u]  [Default is d10.16c].`

This of course is the original 4 inches implemented during the Clinton Administration.  Shall we

- Switch to points as we do many places? 288p to retain backwards compatibility
- Or, do we switch this to 10 cm instead and slightly bacakwards incompatible?

What you thinkg, @joa-quim and @seisman ?

**Comment by joa-quim** [comment]
Sorry, don't understand the question.

But now that you made me reread this. Let's just drop **D** from docs. Why would I use *meters*, or even worst **US survey foot**, to set the distance between annotations?

**Comment by PaulWessel** [comment]
I think you misunderstand the reason those units are there.  There are two schemes:

- Measure distance between annotation on your map
- Measure distances between annotation on the real Earth

It is perfectly OK for me to want an annotation every 100 km on my map.  After all, they may just be a few cm apart.

**Comment by seisman** [comment]
The [documentation](https://docs.generic-mapping-tools.org/dev/grdcontour.html#g) says:

![image](https://user-images.githubusercontent.com/3974108/92296650-e343cb00-ef04-11ea-8d08-6058e88abc6e.png)

**Comment by PaulWessel** [comment]
OK, so the code does not do that.  It says

	`gap = 4.0 * GMT->session.u2u[GMT_INCH][GMT->current.setting.proj_length_unit];`

So I should make it

```
gap = (GMT->current.setting.proj_length_unit == GMT_CM) ? 10.0 / 2.54 : 4.0;
gap *= GMT->session.u2u[GMT_INCH][GMT->current.setting.proj_length_unit];
```

This will give 10c, 4i, or 288p.
