### ISSUE TITLE
pstext/boxtext.sh fails

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4175]
This is the image generated by the Linux CI job. It seems something wrong with this command:
```
gmt psxy -R -J -O -K -Sri -Gred << EOF >> $ps
3   2   6   4
EOF
```

![image](https://user-images.githubusercontent.com/3974108/92311434-f302f400-ef84-11ea-8bc5-250ce3638daa.png)

**Comment by seisman** [comment]
Here are the PS files generated by:

- the Linux CI. [boxtext.ps.zip](https://github.com/GenericMappingTools/gmt/files/5178504/boxtext.ps.zip)
- macOS [boxtext.ps.zip](https://github.com/GenericMappingTools/gmt/files/5178505/boxtext.ps.zip)

The PS diff is tiny:
```diff
1247c1247
< 4800 7200 3600 2400 Sr
---
> 0 0 3600 2400 Sr
```

**Comment by seisman** [comment]
`psxy/gallo/gallo.sh` sometimes also fails. The PS diff is:
```diff
1251,1255c1251,1255
< 2202 1890 3465 5354 Sr
< 2753 2362 1575 2362 Sr
< 1398 1200 5512 1575 Sr
< 4195 3600 4724 8661 Sr
< 2797 2400 787 10236 Sr
---
> 0 0 3465 5354 Sr
> 0 0 1575 2362 Sr
> 0 0 5512 1575 Sr
> 0 0 4724 8661 Sr
> 0 0 787 10236 Sr
```

**Comment by seisman** [comment]
`GMT_RGBchart.sh` also sometimes fails on macOS.

**Comment by PaulWessel** [comment]
OK, Sr is the rectangle macro and I made changes to -Sr in psxy.c so probably my fault.  Will look.
