### ISSUE TITLE
psscale example from man page produces zero output

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4182]
This example (adated) from the ``colorbar`` man page produces zero output
```
gmt psscale -Dx6.5i+jLM/2i+w7.5c/1.25c+e -Cgeo -I -Bx5+lBATHYMETRY -By+lm
```

**Comment by PaulWessel** [comment]
Yes, that should give an error since only x-coordinate provided.  Need to check where that return code ends up.

**Comment by joa-quim** [comment]
Hmm, I assumed he would make *y = x*

**Comment by PaulWessel** [comment]
No.  That make sense when specifying things like a 2-D size (one value means square) but not for coordinates.  It would set a really bad precedent: Lets have 30 mean (30,30) - some place in Africa...
