### ISSUE TITLE
Fails to compile GMT using very old GCC compilers

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4186]
A user who uses a very old GCC (v4.4.7) reports an error when compiling GMT 6.1.1:
![image](https://user-images.githubusercontent.com/3974108/92551118-39797c80-f22b-11ea-9199-180e478c00a1.png)

The error is:
![image](https://user-images.githubusercontent.com/3974108/92551083-223a8f00-f22b-11ea-8d1c-18afcf39773f.png)

Not sure if we should fix it or not.

**Comment by seisman** [comment]
BTW, CentOS 6 is still providing 4.4.7.

**Comment by PaulWessel** [comment]
Maybe slap

```
#ifndef HAVE_GLIB_GTHREAD
#endif 
```

around it?

**Comment by PaulWessel** [comment]
I guess do you know if the user has glib installed? Because either GMT_declare_gmutex is define as nothing or it is static GMutex mutex.  I am guessing from the message that it has an old glib that is not compatible?

**Comment by seisman** [comment]
GMT uses function [`g_thread_new`](https://developer.gnome.org/glib/stable/glib-Threads.html#g-thread-new) in `grdfilter.c`, which was added since GLIB 2.32. However, CentOS 6 is providing [GLIB 2.28](https://centos.pkgs.org/6/centos-x86_64/glib2-2.28.8-10.el6.i686.rpm.html). I believe it's related to this issue.

What we can do:

1. Document that GMT needs GLIB>=2.32
2. In cmake, check glib>=2.32?

**Comment by PaulWessel** [comment]
Either or both are fine with me.  I have no patience for people running very old versions of things.
