### ISSUE TITLE
Rotation of annotations

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4191]
Script:
```
gmt begin map png
gmt subplot begin 2x2 -Fs10c/10c -M1c/2c
gmt basemap -R0/10/0/10 -JX? -Bxaf+u" Ma"+a0   -BWSEN+t"+a0"   -Byaf -c
gmt basemap -R0/10/0/10 -JX? -Bxaf+u" Ma"+a1   -BWSEN+t"+a1"   -Byaf -c
gmt basemap -R0/10/0/10 -JX? -Bxaf+u" Ma"+a30  -BWSEN+t"+a30"  -Byaf -c
gmt basemap -R0/10/0/10 -JX? -Bxaf+u" Ma"+a-30 -BWSEN+t"+a-30" -Byaf -c
gmt subplot end
gmt end show
```

Output:

![image](https://user-images.githubusercontent.com/3974108/92657897-9759a300-f2c3-11ea-989e-a56e42d43d61.png)

It seems the default anchor for X annotations is **MC** (or **TC**, **BC**), but when **+a** is given, the anchor changes , depending on the sign of the given angle and the side of the annotations. Is it designed like this? I actually prefer to always have X annotations centering on the corresponding x values.

**Comment by PaulWessel** [comment]
It was designed that way with intent.  If we used TC then there would be this extra large gap between the tick and the text beneath it.  I think we decided this looked better.

**Comment by seisman** [comment]
OK. Close as it's invalid.
