### ISSUE TITLE
Make +cslat in basemap +L optional.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4227]
In order to draw a simple map scale (basemap +L), I think it would be good to make optional to define the latitude where the scale is calculated (slat; as in done for the longitude). The default could be the central parallel of the map. 

**Are you willing to help implement and maintain this feature?** 
I would like to help but I am not sure if I could.

**Comment by PaulWessel** [comment]
Easy to implement for rectangular wesn maps, but oblique pose a challenge. maybe for those choose projection center longitude as default?

**Comment by joa-quim** [comment]
I think the reasonable thing is to computed scale at the lat at which it is plotted.

**Comment by PaulWessel** [comment]
Hm, yes that sees like a better default.  Also easier to do. But is it not true that we like to place these scales in the corner of plots but rarely want the scale applied to that location?

**Comment by joa-quim** [comment]
Well, then supply the lat at which it should be calculated. But plotting at one position and calculating at another, the scale will be *wrong*, though the difference should normally not be noticeable.

**Comment by PaulWessel** [comment]
Yes, I do think it is better to default **+c** to the scale location than make the default the middle of the map.  But perhaps we can be more clever:

1. No **+c**: Default to location of scale
2. **+c** no args: Default to center of map
3. _+_c_lat_: Use given latitude for scale
4. **+c**_lon/lat_: Use given lon/lat for scale.

I should add I am not sure if we do 1 or 2 right now.  We obviously do 3 and 4.  Would this work for you, @Esteban82 ?

**Comment by Esteban82** [comment]
I have seen that most of my students don't modify +cslat and often used a latitude very different from the ones of the maps. So, yes, any option would be fine.

**Comment by PaulWessel** [comment]
Hi @Esteban82, this improvement has now been merged into master.  Please give it a spin and let us know if anything odd happens.
