### ISSUE TITLE
Wrong column numbering in "meca" documentation

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/gmt#4232]
In `meca` documentation, the text `Using 0,0 in columns 8 and 9 will plot the beach ball at the longitude, latitude given in columns 1 and 2.` is repeated for each `-S` option.

Now, the columns with longitude, latitude at which to place beachball are not always 8 and 9: it depends on the option used.

**Comment by seisman** [comment]
I believe that's a copy-and-paste error. Do you mind opening a pull request.

**Comment by claudiodsf** [comment]
Will do that later today or tomorrow 😉

**Comment by claudiodsf** [comment]
Yes, it's a regression introduced here: https://github.com/GenericMappingTools/gmt/commit/0fa52fb72a57be3ff729d66cfb9539423bb08a56

**Comment by seisman** [comment]
@claudiodsf Please let me know if you're still willing to work on the fix.
