### ISSUE TITLE
sphinterpolate extremely slow

### ISSUE THREAD

**Issue by nickywright** [GenericMappingTools/gmt#4252]
**Description of the problem**

I'm trying to using sphinterpolate to create a global grid. Previously I've used a GMT-dev version (6.0.0_b03d6d7_2019.03.06) and I've recently been testing it using the GMT 6.0.0 release.

My issue is that GMT 6.0.0 is extremely slow compared to the GMT-dev version. e.g. for  `gmt sphinterpolate  tmp-0.xyz -Rd -I0.1d -Q0 -Gout.nc` :

```
bash-3.2$ gmt6 --version
6.0.0_b03d6d7_2019.03.06
bash-3.2$ time ./gmt6_spherinterpolate.sh
real	34m15.143s
user	34m12.420s
sys	0m3.368s
```

```
bash-3.2$ gmt --version
6.0.0
bash-3.2$ time ./gmt_spherinterpolate.sh
real	301m35.718s
user	301m1.579s
sys	0m31.541s
```

Here `tmp.xyz` is 88 Mb file with 2410711 rows, so I'm not surprised that it takes a little while (though I wasn't expecting 5 hours - the first couple times I ran it, I actually thought it'd had gotten stuck after a couple hours!). 
This machine (Mac Pro) doesn't have GMT 6.1, but I also tried the same file using GMT 6.1.1 on my MacBook Pro, and it took about 8 hours.

I've also tested it with a downsampled ETOPO, just to see if I also get a difference between the GMT versions (which I do): 

```
bash-3.2$ gmt grdsample -Rd -I0.5d /Volumes/nmw2/Data/ETOPO1_Bed_g_gmt4.grd -Getopo.nc
bash-3.2$ gmt grd2xyz etopo.nc > etopo.xyz

bash-3.2$ gmt6 --version
6.0.0_b03d6d7_2019.03.06
bash-3.2$ time gmt sphinterpolate -Rd -I0.5d etopo.xyz -Gtest.nc
real	0m56.933s
user	0m57.210s
sys	0m0.391s

bash-3.2$ gmt --version
6.0.0
bash-3.2$ time gmt sphinterpolate -Rd -I0.5d etopo.xyz -Gtest.nc
real	5m19.079s
user	5m18.720s
sys	0m0.267s
```

Is this increased processing time expected? If so, all good, but I was not expecting such a huge difference here. Or am I missing something or is it a fluke that the gmt-dev version here is so much quicker?

In case it helps: the tmp-0.xyz and etopo.xyz file in the test above can be downloaded from here: https://www.dropbox.com/sh/nnnq423n1tdk0kg/AAD0glIRRCQiCiQtVDApdhXea?dl=0

**System information**

* Operating system: macOS Sierra 10.12.6 (16G2136)
* GMT version: 6.0.0_b03d6d7_2019.03.06 [64-bit] [24 cores] and 6.0.0 [64-bit] [24 cores]

**Comment by PaulWessel** [comment]
Thanks Nicky, looking at this on the weekend

**Comment by PaulWessel** [comment]
The excessive slowing is due to our nazi-style check for duplicate points.  The STRIPACK function library we use cannot deal with duplicates so these must be stripped off.  But, that is probably not an issue for many people so we should not apply this strict check by default.  I am working on adding/resurrect a **-D** option across the sph*c modules where one will opt-in to have that slow check - otherwise it is up to you to ensure you have unique locations (e.g., via blockmean or similar).

**Comment by joa-quim** [comment]
But something else must be going on. The ``etopo.xyz`` has no repeated points but it stil says
```
...
sphinterpolate [WARNING]: Data constraint 260279 is identical to 258481 and will be skipped
sphinterpolate [WARNING]: Data constraint 260280 is identical to 258481 and will be skipped
sphinterpolate [WARNING]: Skipped 1799 data constraints as duplicates
```

**Comment by PaulWessel** [comment]
Have not looked that that example.  Are these points on the pole so all the same 3-D vector?

**Comment by joa-quim** [comment]
The ``.xyz`` is a grid with 721 columns so two poles makes 1442 < 1799

**Comment by PaulWessel** [comment]
OK, I can run in debugger with -D and see why it stops there.

**Comment by PaulWessel** [comment]
Add in the repeated W = E for all lats and you get to 1799. (-180 == +180)

**Comment by PaulWessel** [comment]
Fixed in master.  Nicky, best to update and build from master and then this job will take < 30 minutes.  Closing this issue.

**Comment by nickywright** [comment]
Wow that was super quick! Sorry I didn't see any of these emails with the weekend. I just tried it and it's back to around 30 mins - thank you!

**Comment by PaulWessel** [comment]
Thanks for pointing this out - we rarely use **sphinterpolate** so never noticed and our tests are all baby data sets.
