### ISSUE TITLE
Further concerns with sphinterpolate

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4254]
See #4252 and #4253 for context.  The issue relates to what the STRIPACK library does with duplicates.  From the docs, it will return an error code if it finds duplicates, and GMT will use that to print an error and abort.  However, it seems presence of duplicates are not (ever?) detected.  In the etopo case in #4252, for instance, there are 1799 duplicates due to repeated N and S pole values for 720 different longitudes as well as repeated values at -180 and +180 longitude.  If we just run sphinterpolate -Q0 with that data, you get this map:

![bad](https://user-images.githubusercontent.com/26473567/94323180-8732fc00-ff30-11ea-98d7-1501d625d040.png)

However, if you carefully exclude the duplicates via -D (and pay the price in extreme slowness), then you get this map:

![good](https://user-images.githubusercontent.com/26473567/94323191-8f8b3700-ff30-11ea-9f85-203a10d84310.png)

Perhaps a less intrusive, default duplication check would be to warn if multiple points are found along a pole, and if the data has both -180 and +180 longitude values (or 0 and 360)?

**Comment by PaulWessel** [comment]
I will see if it is primarily the E-W or pole points that causes this damage.

**Comment by PaulWessel** [comment]
Eiminating duplicates along poles (just keeping one value at each pole), leads to an exit:

`sphinterpolate [ERROR]: Failure in INTRC0: I = 159, J = 391, IER = -3`

putting them back and eliminate E-W duplicates runs but gives something (different but bad) like the top plot.

**Comment by joa-quim** [comment]
Checking the 4 sides of a -Rd|g seems reasonable.

**Comment by PaulWessel** [comment]
Testing that now.  Problem is your data maybe -180/+180 but you may use -Rg, so how do I know without drilling in to the data?  For -Rd with this data it worked great:

gmt sphinterpolate -Rd -I0.5d etopo.xyz -Gtest3.nc -V -Q0
```
sphinterpolate [INFORMATION]: Reading Data Table from file etopo.xyz
sphinterpolate [WARNING]: Skipped 720 North pole duplicates
sphinterpolate [WARNING]: Skipped 720 South pole duplicates
sphinterpolate [WARNING]: Skipped 359 East longitude duplicates
sphinterpolate [INFORMATION]: No duplicate check performed [-D was not activated]
```
 
Right now I check against east (here 180) but -Rg sets east to 360 so no matches.  There may be data that go 0-360 where we wish to skip 360 instead.

**Comment by PaulWessel** [comment]
I see no way of knowing which longitude to skip without reading the data.  I can determine if longitudes -180, 0 180 360 are found and if 0+360 then that is bad or -180 + 180 is bad, but that is after the fact.

**Comment by PaulWessel** [comment]
The simplest is to explain that -R sets east, and data points with lon = east are skipped.

**Comment by PaulWessel** [comment]
Other posibilities are:

1. No -D: Just eliminates duplicate polar points
2. -D<long> : Also eliminates points with that longitude
3. -D: Full duplication check (slow)
