### ISSUE TITLE
Bar plot enhancements

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4264]
- Let the bars have a top text. Similar to what one gets in ``pshistogram`` when plotting the bar counting
- Expand **-D** to also accept an offset in data units.

**-D** behavior, however, is now not very consistent with pshistogram's new **-E** option, where **-E+o10** means an offset of 10 data units, whilst **-D10/0** means an offset of 10 plotting units.

**Comment by PaulWessel** [comment]
But -D and -E are very different things though. The -D was added to allow us to shift everything away.  It is like a -X -Y followed by another -X -Y in the opposite direction.  -E is there to allow multibar histograms and not some arbitrary change, and it only affects the axis with the bars.
Why not plot your bars with pshistogram?

**Comment by joa-quim** [comment]
Well, yes, one can use histogram but it requires some bin arithmetic and we can no longer put error bars.
See this Julia script. It achieves the result by shifting xx left and right, but not obvious to do this in shell.
And strange that the brown bares are still partially on top of the frame.
```
men_means, men_std = (20, 35, 30, 35, 27), (2, 3, 4, 1, 2);
women_means, women_std = (25, 32, 34, 20, 25), (3, 5, 2, 3, 3);
x = collect(1:length(men_means));
width = 0.35;

bar(x.-width/2, collect(men_means), width=width, color=:lightblue,
    limits=(0.5,5.5,0,40), axis=:none, error_bars=(y=men_std,))
bar!(x.+width/2, collect(women_means), width=width, color=:brown,
    xaxis=(custom=(pos=1:5, label=[:G1 :G2 :G3 :G4 :G5]),), yaxis=(annot=5,label=:Scores),
    axis=(title="Scores by group and gender", axes=:WSrt), error_bars=(y=women_std,), savefig="genders.png")
```

![genders](https://user-images.githubusercontent.com/537321/94473863-b06bba80-01c4-11eb-8294-425cc6351980.png)

**Comment by PaulWessel** [comment]
You also want to duplicate the label machinery from hist to plot too though.  That is -D[+b][+f<font>][+o<off>][+r] in histogram.  I am not sure how to accommodate that in plot.

**Comment by joa-quim** [comment]
OK, if that's a lot of work there are more important things to do.

**Comment by PaulWessel** [comment]
May be close this one, @joa-quim ?

**Comment by joa-quim** [comment]
Closing till better times.
