### ISSUE TITLE
Apparently GMT does not build with Ububtu Focal

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4268]
See this failed [Travis run](https://travis-ci.com/github/GenericMappingTools/GMT.jl/jobs/392311018) that has lots of scary warnings.

Tied to reproduce it in WSL2 (where I have ``Focal``) but now it decided that 
```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.
```
beautiful

**Comment by seisman** [comment]
>   The C compiler
> 
>     "/usr/bin/cc"
> 
>   is not able to compile a simple test program.

Ubuntu Focal should work. I think something wrong with your C compiler.

**Comment by joa-quim** [comment]
I know that and I don't know how to fix the compiler, but the main point is the Travis build that stalls when compiling GMT. And that happens when I use Ubuntu Focal.

**Comment by seisman** [comment]
Perhaps try `make` instead of `make -j`. I know sometimes `make -j` causes problems/crashes on some Ubuntu versions.

**Comment by joa-quim** [comment]
OK, I had a gcc with 57 kb. So you learn that ``sudo apt install gcc`` installs 57 ks of thing and insists reporting that gcc9 is installed. Much googling after I was able to find that ``libc`` and cousins had to be installed  manually too.

After all that I was able to compile GMT with no problems. Yes, there is an horror of hyper verbose warnings but it dis build fine in ``Focal``
