### ISSUE TITLE
Histograms and -C CPT use

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4292]
**Description of the desired feature**

**histogram** **-C** says this:

**-C**_cpt_
Give a CPT. The mid x-value for each bar is used to look-up the bar color. If modern mode and no argument is given then we select the current CPT.

However, **rose -C** says this:

**-C**_cpt_
Give a CPT. The r-value for each sector is used to look-up the sector color. Cannot be used with a rose diagram. If modern mode and no argument is given then we select the current CPT.

So one uses the bin's x-value while the other uses the y-value.  While for **rose** I think it makes no sense to ever apply the cpt via the angle value, for **histogram** there are such reasons.  For instance, test/pshistogram/flip.ps uses a CPT to color the bins according to x, which represents elevation.  In conjugation with a map of elevations, it makes sense to use the same CPT scheme in the histogram.  However, one might alternatively want to use the CPT on the bin's y-value (like **rose**), say to flag bins below or above some threshold, but we do not have that ability.

Proposal:

1. Declare a bug and let **histogram -C** apply to the bin's y-value by default, like in **rose**.
2. Add modifier **+b** to **-C** when we want the CPT to apply to the bin's x-value instead.

Comments, @joa-quim and @seisman ?

**Comment by PaulWessel** [comment]
Pinging @joa-quim and @seisman for input.  I still like my proposal since it adds more capability.  It does break compatibility but I am happy to declare that as a bug.

**Comment by joa-quim** [comment]
Since painting bins in histograms does not seem an important feature (honestly I find it useless) I believe not many people has ever used it, so change the default won't probably be noticed by anyone.
Good to go.

**Comment by PaulWessel** [comment]
I agree with this and personally have no immediate needs.  But I do want to fix the lack of consistency between polar and Cartesian histograms.  In fact, I am not sure if the painting of them due to x-coordinate (my +b suggestion) has any practical use.  I can certainly understand coloring by z-value, but x-value?  So perhaps just call a bug and switch from x to z and that is it (for now at least).
