### ISSUE TITLE
psxyz -L eats the entire polygon (if not painted)

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4295]
```
julia> Ds = mat2ds([1 1 -1; -1 1 -1; -1 -1 -1])

# Works
julia> plot(Ds, R="-1.1/1.1/-1.1/1.1", show=1, fmt=:png, close=true, Vd=1)
        psxy  -R-1.1/1.1/-1.1/1.1 -JX12c/8c -Baf -BWSen -L -P -K > C:\TMP\GMTjl_tmp.ps

# No triangle at all
julia> plot3(Ds, R="-1.1/1.1/-1.1/1.1/-1/1", show=1, fmt=:png, close=true, Vd=1)
        psxyz  -R-1.1/1.1/-1.1/1.1/-1/1 -JX12c/8c -Baf -Bza -JZ6c -L -p200/30 -P -K > C:\TMP\GMTjl_tmp.ps

# Works if painted but does not plot the outline
julia> plot3(Ds, R="-1.1/1.1/-1.1/1.1/-1/1", show=1, fmt=:png, close="+p1", fill=:green, Vd=1)
        psxyz  -R-1.1/1.1/-1.1/1.1/-1/1 -JX12c/8c -Baf -Bza -JZ6c -Ggreen -L -p200/30 -P -K > C:\TMP\GMTjl_tmp.ps
```

**Comment by PaulWessel** [comment]
OK, so for case 2, there is no pen specified.  However, we agreed long time ago that if polygon and no color and no pen then we set the default pen.  Will look at that issue.
For case 3 I see no problem: You are asking for a filled polygon and you get it.  We are not going to randomly add outlines to polygons without -W (except for case 2 where no fill was given either).

**Comment by joa-quim** [comment]
Case two was when I was reading the  ``psxy`` man. It should have been **-W**, but like I showed you in the *3D triangles* mail, **-W** doesn't work either.

**Comment by PaulWessel** [comment]
Can you find any problem with my PR #4306?

**Comment by joa-quim** [comment]
Yes, I can. You didn't try my example in the 3D triangles mail.

```
using GMT
D = gmtread("lixo.dat");
 C = makecpt(T=(0,12,1));
plot3(D, show=1, fmt=:png, Z=collect(1:12), fill="+z", cmap=C, aspect3=1, W=(1,:black), Vd=1)
        psxyz  -JX12c/0 -Baf -Bza -JZ12c -R-1.1/1.1/-1.1/1.1/-1/1 -C -Z -G+z -p200/30 -W1,black -P -K > C:\TMP\GMTjl_tmp.ps
```

No edges

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/95667915-6c819980-0b64-11eb-982c-87dd9a7f2ee3.png)
[lixo.dat.zip](https://github.com/GenericMappingTools/gmt/files/5360440/lixo.dat.zip)

**Comment by PaulWessel** [comment]
Cannot recreate your -Z since dont know what collect does.  I need to get that file so I can run command line.

**Comment by joa-quim** [comment]
Sorry, ``collect`` is a Julia thing to get the vector that ``1:12`` does not generate (``1:12`` is just an exotic type ``UnitRange{Int64}`` that does not actually hold the 12 numbers).  Basically, ``collect(1:12)``  gives (same as Matlab [1:12])
```
julia> collect(1:12)
12-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
```

**Comment by PaulWessel** [comment]
OK, looks like I can confirm the missing outlines.  Will check.

**Comment by PaulWessel** [comment]
Good news: The pen outline is drawn.  Bad news: The pen color matches the triangle fill color.  I need to read the docs now to see what is expected.

**Comment by PaulWessel** [comment]
This can be closed, no?
