### ISSUE TITLE
grdcontour annotations are not aligned well in ex23

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4301]
For example, the "8000 km" annotation in the figure:
![image](https://user-images.githubusercontent.com/3974108/95512309-a5641780-0986-11eb-8bb4-4bd164fe6521.png)

**Comment by PaulWessel** [comment]
Angles are derivatives so probably need more decimals in the coordinates. Will look when back home.

**Comment by seisman** [comment]
Reopen the issue because we have the same issue in `doc/scripts/GMT_App_O_9.ps`:
![image](https://user-images.githubusercontent.com/3974108/95797685-1cb6e580-0cbe-11eb-8bdd-65b5223468ac.png)

**Comment by PaulWessel** [comment]
They did change of course, but here the contours are much more wiggly than the great circles in ex 23. Yes, the hour word is wiggly because of that, but I don't see anything wrong in your picture.

**Comment by seisman** [comment]
I see. Closing again.
