### ISSUE TITLE
GhostScript bug on rendering fat lines?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#431]
I had a look at Case 2 in @KristofKoch's examples for testing #426.  The problem is not related to my efforts there since this also shows in master.  If you run these lines:

```
cat > gc.d << END
-85.5 85
-4.5  85
END
gmt psxy -R-85/82/-5/87+r -JM-45/84.5/15c -W35p gc.d -P > bug.ps

```

then run

gmt psconvert -Tg -P -A bug.ps

you get
![bug](https://user-images.githubusercontent.com/26473567/52882223-13513080-310b-11e9-922f-8f0b38e68a80.png)

There are several problems with this line:

1. Its thickness varies greatly (compare center to either side)
2. The line endings are crazy
3. The line itself has cuts and notches and is not very smooth (if you zoom in).

For normal line thickness you probably would not notice this.I suspect this must be another ghostscript bug.  However, I note that Adobe Distiller gives the same result.  Any other possible solution?

**Comment by PaulWessel** [comment]
I should say I tried gs 9.25 and 9.26 and no difference.  FYI, the two lines input file gets resampled along a great circle with lots of intermediate points.  I looked at the coordinates of that line once in PostScript and I don't see anything wrong.  The x-coordinates are monotonically increasing from left to right and y goes up then down.  We cannot be the first group to plot a curved fat line so there must be something odd with this example.

**Comment by PaulWessel** [comment]
To make it clear what I mean by notches and cuts, I attached a zoomed-in section in PNG:
![bug](https://user-images.githubusercontent.com/26473567/52889288-5d461080-3123-11e9-8802-b36a8ec7daf5.png)

**Comment by joa-quim** [comment]
Zooming as much as I can in Illustrator shows that the 'skeleton' line in the ps file has its jumps (roundings for sure) and that its likely the reason for the cuts. But it doesn't explain ofc the double line nature.

![jig](https://user-images.githubusercontent.com/537321/52889939-32d37200-317a-11e9-848b-b027e4dcb377.jpg)

**Comment by PaulWessel** [comment]
We know there is rounding since we are using a 1200 dpi quantification, so steps of 1/1200 inch is expected, but those notches are worse.

**Comment by joa-quim** [comment]
But they seem clearly related to the line quantization.
![jig2](https://user-images.githubusercontent.com/537321/52892622-0c1e3700-318c-11e9-9b70-c499193662df.JPG)

**Comment by PaulWessel** [comment]
When I made a test setting the dpi to 7200 it got worse.  So there is something odd here.

**Comment by PaulWessel** [comment]
What say you, @remkos?

**Comment by KristofKoch** [comment]
Maybe it is a lead that in the example without `lat0` the line end is behaving nonstandard and the line is jagged as well. Not as funny as extreme as in this case but also noticeable.

**Comment by uleysky** [comment]
The default line draw algorithm in PostScript is fast, but sometimes leads to ugly lines, especially if line segment is lesser then line width. The easiest way to fix this problem is to use more advanced algorithms for drawing the join of segments and line endings. The GMT already can do this by simply adding --PS_LINE_CAP=round --PS_LINE_JOIN=round to the psxy command line.

**Comment by PaulWessel** [comment]
Thanks @uleysky, I should have thought of that.  Trying your suggestion, the ugly example 2.1 of @KristofKoch above no longer shows the problem.  This may lead to discussions on what GMT join and end default settings should be or we add a warning about the problem of fat lines somewhere.  Below is the updated plot:
 
![bug](https://user-images.githubusercontent.com/26473567/53839842-a0ceb600-3f3c-11e9-8c9c-c2414165a71f.png)
