### ISSUE TITLE
Let GMT have ability to write a 3-D netCDF grid

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4314]
**Description of the desired feature**

We have two modules (**greenspline**, **grdinterpolate**) that need the ability to write out a 3-D grid.  Currently, they are only able to write a stack of 2-D grids but this is not a good longterm solution.  I intend to implement the 3-D grid writing by leveraging code that @joa-quim has written for some non-GMT programs of his:

https://github.com/joa-quim/NSWING/blob/master/nswing.c#L3050
 
and
 
https://github.com/joa-quim/NSWING/blob/master/nswing.c#L3294

This request is mostly to serve as placeholder for this links since my ability to loose emails in the early onslaught of emails is pretty good...

GMT mostly reads 2-D grids and can read a 2-D slice from higher dimension netCDF grids.  Thus, there is no immediate need for a function to _read_ in a 3-D grid per se, but this could change in the future.  Writing the 3-D grid is a _much_ higher priority and should be implemented before 6.2.0 is released later this year.

**Comment by seisman** [comment]
Related discussions at https://github.com/GenericMappingTools/gmt/issues/2912.

**Comment by PaulWessel** [comment]
Closed as implemented by #4581.
