### ISSUE TITLE
mapproject -G with -R -J is not doing the right thing

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4319]
If one wants to compute distance along a segment after projecting to plot coordinates you would run something like

`mapproject -R-3/3/-1/1 -JX6i/2i line.txt -G+uC > pts.txt`

where **+uC** means "use Cartesian projected coordinates". However, the code fails to do this as it is using the original input coordinates in the calculation, not the projected ones.  Hence the distances are not correct.  Furthermore, it is undefined (in the documentation) what the output _x,y_ values should be.  If **-G** is _not_ used then we get the projected _x,y_ coordinates, but with **-G** we get the input coordinates (plus the wrong distance).

I think it makes most sense to output projected coordinates when **-R -J** is used.  Many uses of mapproject involves geographic distances and no **-R -J** is given and we get _lon, lat_ back plus distance in chosen units (km, meter).  For projected coordinates it really should consistently output projected _x,y_.

In addition we must fix the wrong calculation of distances.

Finally, seems like **+uC** is superfluous when **-R -J** is used, unless we are to allow things like

`mapproject -R-3/3/-1/1 -JM16c line.txt -G+uk > pts.txt`

which would compute distances in km based on the input _lon,lat_ but report projected _x,y,dist_.  So perhaps that is a reasonable interpretation of things and consistent with my point above.  It is also unclear to me if we always get inches out of this or if it depends on **PROJ_LENGTH_UNIT** or if we could instead use **+uc**|**i**|**p** instead of **+uC** like we do in other modules.

So this looks a bit messy to me (mix of bugs and unclear documentation), please give me some guidance on this, @joa-quim and @seisman.  This affects some details on how I will address #4312.

**Comment by PaulWessel** [comment]
I should add that at least the azimuth **-A** option, if also given **-R -J**, should compute the Cartesian angles after projecting the coordinates, but like **-G** it only operates on input coordinates.

**Comment by joa-quim** [comment]
Ok, but just don't get where you want any advise. If the output should be computed on projected coordinates, it seems logic to get projected *x,y* as well.

**Comment by PaulWessel** [comment]
Yes, wasn't very clear.  But we agree projected x,y should be issued when -R -J is given, and the rest I think is bug fixing.  Thanks.
