### ISSUE TITLE
Show background, foreground and NaN colors of the built-in CPTs

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4322]
**Description of the desired feature**

In https://docs.generic-mapping-tools.org/latest/cookbook/cpts.html, we have three figures showing GMT's built-in CPTs. However, it's unclear what the background, foreground, and NaN colors are. We should add these colors when plotting the colorbars.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
I suppose it is OK to add the **+e+n** to these and make more space between columns.  If you wish to do this then that is fine.  I expect a lot of gray NaN boxes.  If that is the case, then perhaps better to write that in a caption.

**Comment by joa-quim** [comment]
Can we leave them as they are (and were for ~20 years)? More lots of repeated boxes will look bad.

**Comment by PaulWessel** [comment]
I think extending with +w is probably OK since many have their own fore and back, but surely most will have default gray as NaN so no box needed.

**Comment by seisman** [comment]
Looks good, right?

![image](https://user-images.githubusercontent.com/3974108/95810178-63b4d300-0cde-11eb-91e2-438163a05050.png)

![image](https://user-images.githubusercontent.com/3974108/95810187-68798700-0cde-11eb-8ec5-5a9cba0509f3.png)

![image](https://user-images.githubusercontent.com/3974108/95810196-6c0d0e00-0cde-11eb-9d7b-5d379057c2ee.png)

**Comment by PaulWessel** [comment]
Yep, looks very nice, @seisman .

**Comment by DD-ZHAO** [comment]
> I think extending with **+e** is probably OK since many have their own fore and back, but surely most will have default gray as NaN so no box needed.

@PaulWessel Hello,thank you for your suggestion, and how can I customise the colour of the extend arrows?

**Comment by PaulWessel** [comment]
Back and foreground colors are attributes of your CPT so it will use those.  If there are no such entries (B and F) GMT will use the COLOR_BACKGROUND and COLOR_FOREGROUND default settings which you can change as you see fit.

**Comment by DD-ZHAO** [comment]
> Back and foreground colors are attributes of your CPT so it will use those. If there are no such entries (B and F) GMT will use the COLOR_BACKGROUND and COLOR_FOREGROUND default settings which you can change as you see fit.

OK, I solved my problem, and thank you very much for your reply!
