### ISSUE TITLE
Issue with grdfft

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4340]
I run the last example of grdfft from the [docs ](https://docs.generic-mapping-tools.org/latest/grdfft.html) in order to get the real and imaginary components. Is it a bug or the example is deprecated? I only want to get the real and imaginary components without any operation.

```
gmt grdmath -R0/256/0/256 -I1 -r 0 1 NRAND = GRD.nc
gmt grdfft GRD.nc -N+w+z -V
```

**Full error message**
Must specify at least one operation
Option -G: Must specify output grid file

* Operating system: Win 64 
* GMT version: (`gmt 6.1.1`)

**Comment by PaulWessel** [comment]
I think the exampled is bugged.  grdfft currently needs an operation to do.  This works

gmt grdfft GRD.nc -N+w+z -V -E > /dev/null

We could consider adding a null operator, but the above is close.  I will update the docs.

**Comment by PaulWessel** [comment]
OK, master updated.

**Comment by Esteban82** [comment]
And this for windows: 
gmt grdfft GRD.nc -N+w+z -V -E > null
