### ISSUE TITLE
grdimage. Weird warning message

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4341]
When I run the commands below I get the message:

_grdimage (WARNING): Modifier +E detected but not a valid modifier! - ignored_

```
	SET	CUT="FFT+E+n.nc"
	gmt grdmath -R0/256/0/256 -I1 -r 0 1 NRAND = %CUT%
	gmt grdimage -R -JX8c %CUT% >> out.ps
```

grdimage try to interpret the the "+E+n" from the name of the file. If I remove it from the name, the warning message do not appear. Is it a normal behaviour that the module try to interpret the name of the file? Should I be carefull with the names that I choose?

Terminal screen capture with debug information: 
![grdimage_+E+n](https://user-images.githubusercontent.com/17908951/96327689-2ddf5980-1012-11eb-9b31-67123b167933.png)

* Operating system: Win64
* GMT version: `gmt 6.1.1`

**Comment by PaulWessel** [comment]
This is a good point.  GMT do have certain modifiers used in grid file names (+n+s+o comes to mind, as do +u), but the parsing is not robust enough.  So we probably should warn about using what looks like modifiers in actual file names.

**Comment by PaulWessel** [comment]
We possibly do not want that message to be a WARNING as well.

**Comment by PaulWessel** [comment]
Also, the parser should be improved to not worry about "modifiers" until after the file extension.  E.g.

FFT+E+n.nc should give no messages as no modifiers are found after ".nc", while
FFT+E.nc+n should only find one modifier (+n) since appended to the file.

I will make an issue out of this.

**Comment by PaulWessel** [comment]
Should be fixed, let me know if you catch other cases.

**Comment by Esteban82** [comment]
I got the same warning message with: 

`	gmt grdimage -R -J -O -K $DEM -Crainbow >> $OUT -Itemp_EJ7.6_Mapa_DEM+Grav_AireLibre_shadow.nc`

Warning message: 
`grdimage [WARNING]: Modifier +G detected but not a valid modifier! - ignored`

**Comment by joa-quim** [comment]
If we can't use divisions in filenames why should we be allowed to use additions? 😄

**Comment by PaulWessel** [comment]
Multiplications are also not allowed.  On macs, colons (:) are not allowed.
