### ISSUE TITLE
Dark mode for the web pages

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4353]
Just an idea. Add a dark mode for forum and the website. I know that there are extensions in the browsers but usually they are not very good.

**Comment by seisman** [comment]
Possible for discourse. See some related posts:

1. https://meta.discourse.org/t/allow-users-to-select-dark-light-theme/60857/22
2. https://meta.discourse.org/t/dark-mode-automatic-theme-switcher/112071/3
3. https://meta.discourse.org/t/dracula-a-dark-theme-for-discourse/146350

More difficult for the website.

**Comment by seisman** [comment]
I have enabled dark mode in the forum, following this official post (https://meta.discourse.org/t/automatic-dark-mode-color-scheme-switching/161593). It automatically switches color schemes when the user’s device is in dark mode. Users can disable it in their "Preferences > Interface" settings.

**Light mode:**
![image](https://user-images.githubusercontent.com/3974108/100545933-81a5ab00-322c-11eb-8c1d-c211d2aaa32b.png)

**Dark mode:**

![image](https://user-images.githubusercontent.com/3974108/100545946-91bd8a80-322c-11eb-9b86-534d1ae1b9d1.png)

**Comment by seisman** [comment]
I'm closing the issue, as the dark mode for the forum has been implemented.

I don't think any of us will work on the dark mode for the main site.
