### ISSUE TITLE
GMT adds a .cpt file extension to color palette table files

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#4361]
## General
Say I create a file ``colors`` that contains my CPT table. Doing a ``grdimage -Ccolors [..]`` then causes an error since gmt adds a ``.cpt`` extension to the filename; this file does does not exist. 

```
$ gmt grdimage @earth_relief_05m -Ccolors -JM15c -RNO > /dev/null
grdimage [ERROR]: File /usr/local/share/colors.cpt was not found
grdimage [ERROR]: Cannot find file /usr/local/share/colors.cpt
grdimage [ERROR]: File /usr/local/share/colors.cpt not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grdimage [ERROR]: Failed to read CPT colors.
```
A file is defined by it's content, not it's name. So why the need to impose a file extension?

## Problems when using process substitution
This also causes problems when one want to use process substition. Process substitution allows one to treat the output of a command as file.

Here are some links about process substitution:

- https://tldp.org/LDP/abs/html/process-sub.html 
- https://en.wikipedia.org/wiki/Process_substitution)
- https://medium.com/factualopinions/process-substitution-in-bash-739096a2f66d
- https://www.jumpingbean.co.za/blogs/mark/linux-process-substitution

Wikipedia about process substitution:

The main advantages of process substitution over its alternatives are:

- Simplicity: The commands can be given in-line; there is no need to save temporary files or create named pipes first.
- Performance: Reading directly from another process is often faster than having to write a temporary file to disk, then read it back in. This also saves disk space.
- Parallelism: The substituted process can be running concurrently with the command reading its output or writing its input, taking advantage of multiprocessing to reduce the total time for the computation.

### Example
```
$ echo <(gmt makecpt -Cjet -T-1000/0/100)
/dev/fd/63

$ cat <(gmt makecpt -Cjet -T-1000/0/100)
-1000	0/0/178.2	-900	0/0/178.2	L	
-900	0/25.5/255	-800	0/25.5/255	L	
-800	0/127.5/255	-700	0/127.5/255	L	
-700	0/229.5/255	-600	0/229.5/255	L	
-600	76.5/255/178.5	-500	76.5/255/178.5	L	
-500	178.5/255/76.5	-400	178.5/255/76.5	L	
-400	255/229.5/0	-300	255/229.5/0	L	
-300	255/127.5/0	-200	255/127.5/0	L	
-200	255/25.5/0	-100	255/25.5/0	L	
-100	178.2/0/0	0	178.2/0/0	B	
B	black
F	white
N	127.5
```
So if I want to create a CPT on the fly and use it, I should be able to do this:

```
$ gmt grdimage @earth_relief_05m -C<(gmt makecpt -Cjet -T-1000/0/100) -JM15c -RNO > /dev/null
grdimage [ERROR]: File /dev/fd/63.cpt was not found
grdimage [ERROR]: Cannot find file /dev/fd/63.cpt
grdimage [ERROR]: File /dev/fd/63.cpt not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grdimage [ERROR]: Failed to read CPT /dev/fd/63.
```
But, since GMT adds ``.cpt`` to the filename, the file that was generated, ``/dev/fd/63`` becomes ``/dev/fd/63.cpt`` in GMTs eyes. This file does not exist, resulting in an error.

It would be nice if it was possible to use process substitution in GMT scripts. This is a very useful feature.

This may apply to other operations in GMT as well(?); ref. the section in general about letting file names define files instead of it's content. I'm open for discussion!

**Comment by joa-quim** [comment]
> A file is defined by it's content, not it's name. So why the need to impose a file extension?

This is not an universal truth. For example ``grdimage file.xyz ...`` will trigger a GDAL driver that will interpret that ``.xyz`` extension as meaning a grid in *x,y,z* triplets and will do an equiavalent of ``xyz2grd`` under the hood.

Generally, guessing file formats from their contents imply using what is known as *magic numbers*, a short series of unique bytes at the beginning of file. However, this is for binary files, not ascii. But since this would be a new feature in GMT, maybe it could always print a first unique ``# I-am-a-CPT`` that would work as a magic number.

**Comment by PaulWessel** [comment]
Nevertheless, I am working on a branch to eliminate the requirement of having to use ".cpt".  So, once done the .cpt will move from being required to recommended (especially in presence of modifier-like substrings, just like for grid names.

**Comment by anbj** [comment]
@joa-quim : absolutely, thanks for the input.

@PaulWessel : great!

**Comment by anbj** [comment]
I'll test as soon as I have the chance. Probably monday.

**Comment by anbj** [comment]
Tested and works. Excellent work, Paul!
