### ISSUE TITLE
Plotting axes labels but not the axes

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4372]
Title says what I was trying to get, but instead I found that classic and modern do different things but none of the wished
```
echo 0 1 | gmt plot -JX12c/8c -B0 -Bx+lBlaBla -R-0.1/0.1/-0.04/1.04 -Sb0.8u+b0 -G0/115/190 -png map
```
![map](https://user-images.githubusercontent.com/537321/97094503-1543f480-164d-11eb-897a-7ce9923c78f2.png)

In *classical* no label and no axes at all, only the blue rectangle (not attached)

```
echo 0 1 | gmt psxy -JX12c/8c -Bx+lBlaBla -R-0.1/0.1/-0.04/1.04 -Sb0.8u+b0 -G0/115/190 -P > lixo.ps
```

Background: I was trying to prove my point on https://forum.generic-mapping-tools.org/t/how-to-plot-bar-charts-on-world-map/959

**Comment by PaulWessel** [comment]
Axis labeling is part of the axis function, so I suspect if not selected then it skips it entirely and no label.  Will have to see if we can proceed to the end of it without plotting things in order to plot the label (note we are building up a PostScript variable with the require offset normally).

**Comment by PaulWessel** [comment]
So Cartesian axis label happens at end of gmt_xy_axis which is not called if axis not selected.  So we would need to extract that part into a function that could be called independently if axis is not called for drawing.  And we would need to determine that if axis is not selected but a label is set then do that.

**Comment by PaulWessel** [comment]
Unless we decouple axis labels then you cannot get what you want.  I am not sure this is a reasonable request (a map frame without the frame but just the label but no annotations).  I understand you were just trying to take advantage of **-B** instead of placing text.  For what it's worth both classic and modern give the same result (Frame and label) as long as you do not imply auto-annotation:

```
echo 0 1 | gmt psxy -JX12c/8c -Bx0+lBlaBla -R-0.1/0.1/-0.04/1.04 -Sb0.8u+b0 -G0/115/190 -P > lixo.ps 
echo 0 1 | gmt plot -JX12c/8c -Bx0+lBlaBla -R-0.1/0.1/-0.04/1.04 -Sb0.8u+b0 -G0/115/190 -png lixo
```

Shall we just close this one?

**Comment by joa-quim** [comment]
[See](https://forum.generic-mapping-tools.org/t/how-to-plot-bar-charts-on-world-map/959/8). That was the first reason for no wanting the axes. I ticked it by plotting with a line width of 0, which still plots a line, and white, but we can still see it if zooming enough. Perhaps the best would be to just use full transparency.

I think this could be a useful thing in plain GMT as well but feel free to close.

**Comment by joa-quim** [comment]
OK, I can do it now fully invisible by playing with transparency in Julia.
