### ISSUE TITLE
Improve the documentation of makecpt -C & -D

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4381]
makecpt documentation: https://docs.generic-mapping-tools.org/dev/makecpt.html

> -C[cpt|master[+h[hinge]][+izinc][+u|Uunit] |color1,color2[,color3,…]]

The meaning of **+i***zinc* is unclear.

> -D[i|o]

What **-Do** does is not explained.

**Comment by PaulWessel** [comment]
OK, should not be any izinc except in grdimage,view,vector I think.  Will check -Do presumably refers to using the output CPT end colors.  I will update.
