### ISSUE TITLE
grdconvert output not working with windows file paths

### ISSUE THREAD

**Issue by RichardScottOZ** [GenericMappingTools/gmt#4384]
**Description of the problem**

Running grd convert with files in a current working directory works - referencing other paths does not, although the latter works fine with some other gmt programs.

```
 D:\Exploracorn\Brazil\PendockProjectData\surface>gmt grdconvert D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif -G'D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317test.nc -Vi
grdconvert [INFORMATION]: File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Translating file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif (format gd = Import/export through GDAL) to file 'D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317test.nc (format nf = GMT netCDF format (32-bit float), CF-1.7)
grdconvert [INFORMATION]: File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
```

The above fails

This works

D:\Exploracorn\Brazil\PendockProjectData\surface>gmt grdconvert GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif -GGMTBrazilCarajas_1019_1_CTB_01_CUT2317test.nc

```
debug for the first version
D:\Exploracorn\Brazil\PendockProjectData\surface>gmt grdconvert D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif -G'D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317test.nc -Vd
gmt [DEBUG]: Obtained the ppid from parent: 27628
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = C:/Users/rscott/AppData/Local/Continuum/anaconda3/envs/pygmt/Library/share/gmt
gmt [DEBUG]: GMT->session.HOMEDIR = C:/Users/rscott
gmt [DEBUG]: GMT->session.USERDIR = C:/Users/rscott/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = C:/Users/rscott/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR C:/Users/rscott/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir C:/Users/rscott/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir C:/Users/rscott/AppData/Local/Continuum/anaconda3/envs/pygmt/Library/share/gmt/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR C:/Users/rscott/AppData/Local/Continuum/anaconda3/envs/pygmt/Library/share/gmt
gmt [DEBUG]: GMT: 6. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_reload_settings
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Look for file C:/Users/rscott/gmt.conf
gmt [DEBUG]: Look for file C:/Users/rscott/.gmt/gmt.conf
gmt [DEBUG]: Look for file C:/Users/rscott/.gmt/server/gmt.conf
gmt [DEBUG]: Look for file C:/Users/rscott/.gmt/cache/gmt.conf
gmt [DEBUG]: Could not find file gmt.conf
gmt [DEBUG]: Exit:  gmt_reload_settings
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 12 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Loading core GMT shared library: gmt.dll
gmt [DEBUG]: Shared Library # 0 (core). Path = gmt.dll
gmt [DEBUG]: Loading GMT plugins from: C:/Users/rscott/AppData/Local/Continuum/anaconda3/envs/pygmt/Library/bin/gmt_plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = C:/Users/rscott/AppData/Local/Continuum/anaconda3/envs/pygmt/Library/bin/gmt_plugins/supplements.dll
gmt [DEBUG]: Revised options: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif -G'D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317test.nc -Vd
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Given full path to file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Replace file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif with D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.hdr Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.hdr
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [INFORMATION]: File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Translating file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif (format gd = Import/export through GDAL) to file 'D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317test.nc (format nf = GMT netCDF format (32-bit float), CF-1.7)
grdconvert [DEBUG]: Local file C:/Users/rscott/.gmt/server/gmt_data_server.txt found
grdconvert [DEBUG]: File C:/Users/rscott/.gmt/server/gmt_data_server.txt less than 24 hours old, refresh is premature.
grdconvert [DEBUG]: Load contents from C:/Users/rscott/.gmt/server/gmt_data_server.txt
grdconvert [DEBUG]: Local file C:/Users/rscott/.gmt/server/gmt_hash_server.txt found
grdconvert [DEBUG]: File C:/Users/rscott/.gmt/server/gmt_hash_server.txt less than 24 hours old, refresh is premature.
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Given full path to file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Given full path to file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Object ID 0 : Registered Grid File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif as an Input resource with geometry Surface [n_objects = 1]
grdconvert [DEBUG]: gmtapi_begin_io: Input resource access is now enabled [container]
grdconvert [DEBUG]: gmtapi_import_grid: Passed ID = 0 and mode = 1
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [DEBUG]: gmt_get_filename: In: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.hdr Out: D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.hdr
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [INFORMATION]: File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [DEBUG]: Found readable file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
```

**Actual outcome**
No output

**Expected outcome**
netcdf grid file

**System information**
Windows 10
* Operating system:
* GMT version (`gmt --version`):
6.1.1

**Comment by joa-quim** [comment]
> ``-G'D:\...``

is not a valid Windows path. ``-G"D:\...`` is (if I'm not wrong)

**Comment by RichardScottOZ** [comment]
Yes, tried that already earlier, fails the same way:

 D:\Exploracorn\Brazil\PendockProjectData\surface>gmt grdconvert "D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif" -G"D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote.nc" -Vi
grdconvert [INFORMATION]: File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Translating file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif (format gd = Import/export through GDAL) to file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote.nc (format nf = GMT netCDF format (32-bit float), CF-1.7)
grdconvert [INFORMATION]: File D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff

**Comment by RichardScottOZ** [comment]
However, have discovered this works :-

 D:\Exploracorn\Brazil\PendockProjectData\surface>gmt grdconvert GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif -G"D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote.nc" -Vi
grdconvert [INFORMATION]: File GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Translating file GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif (format gd = Import/export through GDAL) to file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote.nc (format nf = GMT netCDF format (32-bit float), CF-1.7)
grdconvert [INFORMATION]: File GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Cartesian input grid
grdconvert [INFORMATION]: Cartesian input grid
grdconvert [INFORMATION]: Reading grid from file GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [INFORMATION]: Read band(s): 1
grdconvert [INFORMATION]: Cartesian input grid
grdconvert [INFORMATION]: Set boundary condition for all edges: natural
grdconvert [INFORMATION]: Set boundary condition for left   edge: natural
grdconvert [INFORMATION]: Set boundary condition for right  edge: natural
grdconvert [INFORMATION]: Set boundary condition for bottom edge: natural
grdconvert [INFORMATION]: Set boundary condition for top    edge: natural
grdconvert [INFORMATION]: Writing grid to file D:\Exploracorn\Brazil\PendockProjectData\surface\GMTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote.nc
grdconvert [INFORMATION]: Proj4 string to be converted to WKT:
        +proj=lcc +lat_0=6 +lon_0=-66 +lat_1=9 +lat_2=3 +x_0=1000000 +y_0=1000000 +ellps=intl +units=m +no_defs
grdconvert [INFORMATION]: WKT converted from proj4 string:
PROJCS["unknown",
    GEOGCS["unknown",
        DATUM["Unknown based on International 1909 (Hayford) ellipsoid",
            SPHEROID["International 1909 (Hayford)",6378388,297]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["latitude_of_origin",6],
    PARAMETER["central_meridian",-66],
    PARAMETER["standard_parallel_1",9],
    PARAMETER["standard_parallel_2",3],
    PARAMETER["false_easting",1000000],
    PARAMETER["false_northing",1000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH]]

**Comment by RichardScottOZ** [comment]
so problem in the input reading part by the looks

**Comment by RichardScottOZ** [comment]
however, this works :-

 D:\Exploracorn\Brazil\PendockProjectData\surface>gmt grdconvert D:/Exploracorn/Brazil/PendockProjectData/surface/GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif -GD:/Exploracorn/Brazil/PendockProjectData/surface\/MTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote2.nc -Vi
grdconvert [INFORMATION]: File D:/Exploracorn/Brazil/PendockProjectData/surface/GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Translating file D:/Exploracorn/Brazil/PendockProjectData/surface/GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif (format gd = Import/export through GDAL) to file D:/Exploracorn/Brazil/PendockProjectData/surface\/MTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote2.nc (format nf = GMT netCDF format (32-bit float), CF-1.7)
grdconvert [INFORMATION]: File D:/Exploracorn/Brazil/PendockProjectData/surface/GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif reads with GDAL driver GTiff
grdconvert [INFORMATION]: Cartesian input grid
grdconvert [INFORMATION]: Cartesian input grid
grdconvert [INFORMATION]: Reading grid from file D:/Exploracorn/Brazil/PendockProjectData/surface/GMTBrazilCarajas_1019_1_CTB_01_CUT2317.tif
grdconvert [INFORMATION]: Read band(s): 1
grdconvert [INFORMATION]: Cartesian input grid
grdconvert [INFORMATION]: Set boundary condition for all edges: natural
grdconvert [INFORMATION]: Set boundary condition for left   edge: natural
grdconvert [INFORMATION]: Set boundary condition for right  edge: natural
grdconvert [INFORMATION]: Set boundary condition for bottom edge: natural
grdconvert [INFORMATION]: Set boundary condition for top    edge: natural
grdconvert [INFORMATION]: Writing grid to file D:/Exploracorn/Brazil/PendockProjectData/surface\/MTBrazilCarajas_1019_1_CTB_01_CUT2317testdoublequote2.nc
grdconvert [INFORMATION]: Proj4 string to be converted to WKT:
        +proj=lcc +lat_0=6 +lon_0=-66 +lat_1=9 +lat_2=3 +x_0=1000000 +y_0=1000000 +ellps=intl +units=m +no_defs
grdconvert [INFORMATION]: WKT converted from proj4 string:
PROJCS["unknown",
    GEOGCS["unknown",
        DATUM["Unknown based on International 1909 (Hayford) ellipsoid",
            SPHEROID["International 1909 (Hayford)",6378388,297]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["latitude_of_origin",6],
    PARAMETER["central_meridian",-66],
    PARAMETER["standard_parallel_1",9],
    PARAMETER["standard_parallel_2",3],
    PARAMETER["false_easting",1000000],
    PARAMETER["false_northing",1000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH]]

**Comment by joa-quim** [comment]
It works fine for me (no need for quotes when names have no blanks)

```
grdconvert C:\SIG_AnaliseDadosSatelite\SIG_ADS\DadosEx2\LC82040332015145LGN00\LC82040332015145LGN00_B1.TIF -GC:\SIG_AnaliseDadosSatelite\SIG_ADS\DadosEx2\LC82040332015145LGN00\lixo.grd
```

**Comment by RichardScottOZ** [comment]
ok, possibly some annoying Windows10 update bug or other esoterica - as working fine on some other commands yesterday at least  .. Thanks!

**Comment by seisman** [comment]
Closing the issue.
