### ISSUE TITLE
Annotations for categorical CPT

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4388]
`makecpt -F+c` can produce a categorical CPT, but when plotting the colorbar, the annotations look weird. See the example below. Why the annotations are "0-1", "1-2", and "2-3". Should they be "0", "1", and "2", no?

```
gmt begin map png
gmt basemap -R0/10/0/10 -JX4c -Baf -BWSen
gmt makecpt -Ccubhelix -T0/3/1 -F+c
gmt colorbar
gmt end show
```

![image](https://user-images.githubusercontent.com/3974108/97264104-aa382080-17fa-11eb-90e1-5627d408f397.png)

**Comment by PaulWessel** [comment]
Hm, see colorbar -Li.  Seems to be doing that.

**Comment by seisman** [comment]
`colorbar -Li` doesn't change anything.

**Comment by seisman** [comment]
BTW, the categorical CPT looks correct:
```
gmt makecpt -Ccubhelix -T0/3/1 -F+c
0	24/45.5/72.5	L
1	159.5/121/72.5	L
2	194/215.5/242	B
B	black
F	white
N	red
```

**Comment by PaulWessel** [comment]
When **colorbar** plots a categorical CPT and no **-B** is given then it will center the annotations on each unique color and it will use as label whatever is given in the CPT (after the ; label marker per record) or, if no such labels, create one from the boundaries, i.e., 0-1, 1-2, 2-3 in your case.  If I manually fix your cpt to look like this:

0	24/45.5/72.5	L	;0
1	159.5/121/72.5	L	;1
2	194/215.5/242	B	;2

then I get what you would prefer.  Given this behavior is very long-lived and often reasonable, we could consider other schemes to simplify setting these labels.  Here are some thoughts/suggestions for makecpt:

Let **-F+c**[_label_] take an optional modifier argument to **+c** that will do the following, depending on _label_:

1. If _label_ is an integer, say 0, then we auto-add labels 0, 1, 2, ...
2. If _label_ is a letter (say g or G), we auto-add labels g, h, i or G, H, I
3. If any of the above is followed by a _hyphen_, then we instead set labels as 0-1, 1-2, G-H, g-dh, etc.
4. If _label_ contains a _comma_ then we will use the comma-separated items as verbatim labels, until we run out, e.g.,

```
gmt makecpt -Ccubhelix -T0/3/1 -F+c Clouds,Trees,Water
0	24/45.5/72.5	L	;Clouds
1	159.5/121/72.5	L	;Trees
2	194/215.5/242	B	;Water
```

![m](https://user-images.githubusercontent.com/26473567/97367457-3a9f5100-184d-11eb-9153-9a9aa1daa444.png)

I think this is a splendid proposal no?

**Comment by PaulWessel** [comment]
I think this possibility is a good improvement.  Let me know if you agree, @joa-quim and @seisman.

**Comment by joa-quim** [comment]
Agree. Nice adding
This is something we won't get easier on Julia and cousins.
