### ISSUE TITLE
Simplify access to constant result from grdmath operations

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4389]
**Description of the desired feature**

See the [forum](https://forum.generic-mapping-tools.org/t/getting-numerical-values-from-grdmath-to-use-in-pstext/981) post for background.

Many **grdmath** operators (e.g., **MEAN**, **STDEV**, **LMS**) computes a single statistic from the grid, then populates the top stack grid with that constant so it can be used in further calculations.  However, at times the end game is simply to obtain that constant, and in those cases receiving it in the form of a _n x m_ grid is not convenient, necessitating further scripting via **grd2xyz** or similar.  Here are various possibilities:

1. Let **grdmath** write a single number on output if the last stack is a constant.  _Pro_: Great if that is what you want.  _Con_: Workflows expecting a grid, as well as external calls, would be confused, and maybe I want that constant grid.  So clearly an option would be needed.
2. Same, but add option **-T** that means "Write a one-item table if last stack is a constant".  _Pro_: Now it is predictable, but not really since still depends on operators used. _Con_: Still a problem for externals.
3. Continue to write grids, but let an optional **-T**_file_ write any final constant to the secondary output file.  _Pro_: Does not break external use since **THIS_MODULE_KEYS** still has **=G}** as primary output and only grid is expected to be returned, but now a secondary output table may be written.  _Con_: Still writes the final grid even if the user does not want it.

I think suggestion 3 is the only one we can implement that would not break anything since it would just add a secondary **TD)** item for an optional one-row-one-column table to be written.  We _could_ consider letting the command-line interface not write that final grid but always do so for externals.  However, this means some specific KEYS handling when API->external is false which I think sets up a bad precedent.  So I think the clean option 3 is the way to make this simpler for many users. Do you external folks agree, @joa-quim and @seisman ?

**Comment by joa-quim** [comment]
I think is this should be left alone as is and not complicate further. ``grdinfo`` already reports several cheap statistics. And in Julia one would just do
```
G = GMT.peaks();
using Statistics

std(G)
1.8652234f0

mean(G)
0.37613478f0
```

**Comment by PaulWessel** [comment]
Well, none of that is helping a command line user.  I do not think we have decided to abandon the CLI.

**Comment by PaulWessel** [comment]
I am confused. Are you arguing that we should not add **-T**_file_ since you do not need it and those who do should instead change their workflows and move to Python or Julia, even though such an option would help them now at no detriment to Julia. Matlab and python users?

**Comment by Esteban82** [comment]
> `grdinfo` is CLI. And yes, maybe some day not too far pure CLI will start to phase out.

If you allow me to ask a question off topic. 

I am currently working with pure CLI and sometimes I feel that it should change my workflow. So, what do you suggest me to use? Which programming language? Python/Julia? Which software? VSC? Jupyter notebook? I know that it depends on what I want to do but any idea would be appreciated.

**Comment by joa-quim** [comment]
Well, but my totally unbiased opinion ( 😇 ) is ofc, Julia

Why? Julia has a very nice syntax (IMO, way nicer than Python). Julia is a very efficient language. Either in terms of velocity (where it blows competition) but mainly in terms of  productivity. 
Surely this is a matter of debate and many others would have different opinions, but see. I alone was able to learn the language and to came up with the GMT Julia wrapper, which is way more advanced than ... *competition*

**VSC** is probably the only unanimous point
**Jupyter notebook** Yes, it's nice specially for documenting, but Julia has an evolutionary step over it, _Pluto_
, an interactive notebook, see this https://youtu.be/DGojI9xcCfg and the all series of this [MIT course](https://computationalthinking.mit.edu/Fall20/)

My honest recommendation is, if you don't have a Python background (and even if you do) and to use GMT, definitively go for **Julia + GMT.jl**. I even think we should recommend that to all new GMT users.

**Comment by Esteban82** [comment]
Many thanks @joa-quim.

**Comment by PaulWessel** [comment]
I've decided against adding a new option.
