### ISSUE TITLE
Trouble when DCW polygon splits at periodic boundary

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#439]
I try pscoast -JQ105/0/23.2c -Rg -Bg15/g90 -D1 -N1 -Sblue -E=NA+p ?out.ps
All works fine. I get the map after converting to pdf.
Then I append -K, and write
pscoast -R -J -EUS+gyellow -O >>out.ps
and gmt hangs. Maybe there is something peculiar with the 105 longitude.

**Comment by PaulWessel** [comment]
So this problem is not so clear-cut but gives some useful insight into an area of postscriptlight that needs improvement.  It turns out pscoast is _not_ hanging but just taking a very long time (many minutes).  The result is shown here.  The technical problem is this: Unlike the GSHHG data in pscoast (which have been chopped into small pieces that are reassembled to make a quick-fill puzzle, the DCW polygons are painted as they are.  For the US this involves a polygon of > 700,000 coordinates.  After projecting and converting to PostScript units we send it through psl_shorten_path which removes intermediate points along straight line segments.  It is this function that is the bottle neck as it does not scale well for large number of points.  There are two solutions:

1. Replace this algorithm with something faster (even if less perfect).
2. Package the DCW polygons like we do the GSHHG data and apply the same pscoast on-the-fly machinery for painting.

The solutions are not mutually exclusive, of course.
![t](https://user-images.githubusercontent.com/26473567/53518526-5dc09e80-3a75-11e9-95c5-dc76b93439f3.png)

**Comment by PaulWessel** [comment]
I disabled what psl_shorten_path does and let the PostScript interpreter deal with the larger files involved.  My preliminary conclusions:

1. No "bottleneck" when running the GMT commands
2. Maybe 50% larger PostScript files
3. Conversion to PDF or similar not noticeable slower

I will try to quantify this better.  The motivation for psl_shorten_path stems from the early days where we were fixated on producing as small PostScript output as possible.  This is arguably less important today but bottlenecking is clearly a problem, always.

**Comment by joa-quim** [comment]
What I don't get is why the psl_shorten_path is so much slower for certain lon_0 (more IF branches visited?). But if cannot make way faster then probably the best not use it. 

It would it would be good to also have a low res DCW.

**Comment by PaulWessel** [comment]
That has to do with splitting across the periodic boundary (see yellow above) and extra wrk involved in cropping.

**Comment by joa-quim** [comment]
So then we can suspend ``psl_shorten_path`` on global -R only, no?

**Comment by PaulWessel** [comment]
Let me finish my data analysis on the impact first before we do specifics.

**Comment by PaulWessel** [comment]
So based on the 236 plots that "failed" the tests (because lines are rendered differently), then median size increase was 50%.  But some are much larger and some are smaller.  An easy fix would be to skip the shortening if the number of points are very large (50000+ maybe, needs calibration).  It is harder to set this depending on -R since this is very deep in postscriptlight.

**Comment by joa-quim** [comment]
Yep, that's a too large increase to use always. ``OLD_shorten_path`` looks faster. Why was is dropped?

**Comment by PaulWessel** [comment]
To fix a bug I think where the old method failed.  Hopefully I can resurrect why.

**Comment by PaulWessel** [comment]
I need to restart this issue.  I think there is no real problem if a PostScript file grows 5x bigger if it is overall a small file.  The problem is only series for larger polygons.  I can add a switch so that it goes to the smart algorithm if n < M and use the dummer algorithm for larger files.  I can try M = 50000 and see what that does to file size, etc.
