### ISSUE TITLE
psxyz does not documment the -Sb...+Z|z option

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4391]
That happens because both ``psxyz`` and ``psxy`` both use the ``explain_symbols.rst_`` file that does not mention it.

Also, the -Sb...+Z|z option that was introduced mainly to simplify ex10 is very handy and would be a nice to have in ``psxy``. As is one have to do a **lot** of gymnastic to produce a figure like this in plain shell GMT

```
julia> bar([0. 1 2 3; 1 2 3 4], stack=1, show=1,  fmt=:png, fill=["red" "green" "blue"])
```

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/97494135-d15b3300-195d-11eb-81eb-ea563b9d3209.png)

**Comment by PaulWessel** [comment]
I agree we should port this to psxy as well - should not be too hard, and then update the docs.

**Comment by PaulWessel** [comment]
Wait a minute - this is fully documented [here](https://docs.generic-mapping-tools.org/dev/plot3d.html#id10), no @joa-quim?

**Comment by joa-quim** [comment]
Ups, yes. I just looked at **-Sb**

**Comment by PaulWessel** [comment]
I've started to work on extending this to the flat 3-D bars in **psxyz** as well as the 2-D bars in **psxy**.  Just need to rediscover how I made it work....
