### ISSUE TITLE
Building on FreeBSD fails - gmt_common_sighandler.c

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#4396]
Originally posted in forum; https://forum.generic-mapping-tools.org/t/building-gmt-on-freebsd-12-1-release/967.

System:
```
$ uname -a
FreeBSD  12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64
```
During ``cmake --build .``:
```
[... everything OK up until this point ...]
Scanning dependencies of target gmt
[100%] Building C object src/CMakeFiles/gmt.dir/gmt.c.o
[100%] Linking C executable gmt
ld: error: libgmt.so.6.2.0: undefined reference to backtrace
ld: error: libgmt.so.6.2.0: undefined reference to backtrace_symbols_fd
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/anbj/gmt/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/anbj/gmt/build
*** Error code 1

Stop.
make: stopped in /usr/home/anbj/gmt/build
```

Adding ``add_definitions(-DNO_SIGHANDLER)`` to *cmake/ConfigUser.cmake* makes it build successfully.

The error is likely caused by https://github.com/GenericMappingTools/gmt/blob/master/src/gmt_common_sighandler.c; the **#ifdefs** not being correct for FreeBSD.

**Comment by seisman** [comment]
These two functions are defined here:
https://github.com/GenericMappingTools/gmt/blob/1c0595bd99312aa9c041fff492407045d11507ae/src/gmt_common_sighandler.c#L40-L53

Perhaps in FreeBSD, the header file `execinfo.h` is found, but there are no definitions for these two functions?

Could you please if `execinfo.h` is found when running `cmake ..` (without adding `add_definitions(-DNO_SIGHANDLER)` to cmake/ConfigUser.cmake? On macOS, I see these outputs:
```
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for signal.h
-- Looking for signal.h - found
```

If `execinfo.h` is found, you can try run `locate execinfo.h` to get the full directory to the file, and then check if these two functions are defined in that file.

**Comment by anbj** [comment]
@seisman ``cmake`` **does** find *execinfo.h* and both functions, *backtrace* and *backtrace_symbols_df* are present in the file.

**Comment by seisman** [comment]
Here are the manpages of backtrace on Linux and FreeBSD:

- GNU Linux: https://man7.org/linux/man-pages/man3/backtrace.3.html
- FreeBSD: https://www.freebsd.org/cgi/man.cgi?query=backtrace&sektion=3&manpath=FreeBSD+11-current

The backtrack functions are included in the `glibc` library for GNU Linux, but for FreeBSD, it's in a separate library:
```
LIBRARY
     Backtrace Access Library (libexecinfo, -lexecinfo)

Because these	functions use elf(3) this is a separate	library	in-
	  stead	of being part of libc/libutil so that no library dependencies
	  are introduced.
```

It seems on FreeBSD, GMT should link to the `libexecinfo` library if found.

**Comment by PaulWessel** [comment]
From googling, looks like the cmake variable **CMAKE_SYSTEM_NAME** will be FreeBSD under FreeBSD, so maybe we need to add something like this around line 300 in src/CMakeLists.txt?

```
if (${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
	find_library (EXECINFO_LIBRARY NAMES execinfo)
	list (APPEND GMT_OPTIONAL_LIBRARIES ${EXECINFO_LIBRARY})
endif (${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
```

**Comment by seisman** [comment]
I think yes. Please open a PR to make it easier for @anbj to try.
