### ISSUE TITLE
Improve output of absolute time coordinates

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4408]
**Description of the desired feature**

While GMT writes proper ASCII output absolute time coordinates in ISO format, there are some **awkward limitations**.  The output format is controlled by **FORMAT_DATE_OUT** and **FORMAT_CLOCK_OUT**. The problem occurs when the time increments are very small.  The default **FORMAT_CLOCK_OUT** is _hh:mm:ss_ so if the time coordinates have a higher precision than 1 second then those decimals are lost unless the user is aware of this problem and adds **--FORMAT_CLOCK_OUT**=_hh:mm:ss.xxxxx_, where _xxxxx_ may be the required number of decimals to do the data justice.  This is not a good system as it requires us to constantly add **--FORMAT_CLOCK_OUT** to commands to make sure we do not loose precision in ASCII output. Most users will not have the wherewithal to know this and get frustrated when their output is ruined.

**Solutions:**

1. If any of the output columns contain absolute time, we could scan that column to find the widest sub-second remainder and automatically set a _hh:mm:ss.xxxxx_ that can handle the maximum precision needed.
2. We could do this only when GMT creates an array to make sure the array can be printed with adequate precision.

(1) means we must scan all the rows and determine `sub = S->data[tcol][row] - floor (S->data[tcol][row])` and keep track of the **widest nonzero** _sub_.  Say we have three records with UNIX times 1601514000.5, 1601514010.75, 1601514020.00.  These are ~10 seconds apart but to preserve precision we clearly need to use _ss.xx_.    We would find _sub_ = 0.5 and 0.75 and learn we need 2 decimals. (2) means we only do this for a fixed increment _inc_ and we then apply the same scheme to _inc_ to learn how many decimals.  E.g., if we set up an equidistant time _inc_ of 2 msec then we should find 3 decimals, _ss.xxx_.

In reality, we will find **wide** sub values like 0.3333333333 (a third of a sec), 0.041666666666 (1/24 second in **movie**), etc. that has _no_ finite number of xxxxx.  However, writing these data out with _hh:mm:ss_ is surely _not_ a good solution since we would completely wipe the data precision and distort the coordinates.  A better solution is to write these repeating decimals out with _enough_ precision so that the difference between the actual _sub_ in memory (say _D_ = 0.0416666666666) and what can be read from a _ss.xxxxx_ formatted file (i.e., _T_ = 0.41667) is such that |_D-T_|/_D_ < _error_.  If we set this truncation error to a known documented value, say, 10^-4 then we can determine the precision needed.  In my case that is 5 (_error_ = 0.8e-5).

I want to make a pitch for solution (1) since I do not think GMT should garble user data.  While this pre-processing will add some calculations before writing output, note that

- It _only_ applies when writing **ASCII output** of data with absolute time columns
- It is _not_ an i/o-step but a simple calculation, which tends to be pretty fast
- If you have millions of large ASCII records then your time is mostly spent doing the formatting anyway

I am curious what @joa-quim and @seisman think about this problem and these solutions.  I have already coded up the algorithm and it works well but I will optimize it further.  I could make a branch and we can do some timings to see if that is even an issue.

**Comment by joa-quim** [comment]
I can't say I fully understood the options (specially 2)) but what ever they are, can't it only be applied to the, lets say first 20 records, to decide the number of decimals?

**Comment by PaulWessel** [comment]
That is a great idea, @joa-quim - I will do that.
