### ISSUE TITLE
Choropleth maps

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#441]
We have no current way to do [them ](https://en.wikipedia.org/wiki/Choropleth_map)easily. Actually the machinery already exists and is provided by the **-Z** option in multi-segment headers but we have no way of setting it other than manually, which is impractical for cases like painting countries by some criteria.

A possibility could be if the **+g**_fill_ modifier could accept a file holding ID and values and than use those IDs to do a pattern matching like gmtconvert can do to assign the **-Z** _value_. But even this will require some new syntax to assign IDs to multi-segment headers.

Not obvious, but choropleths is  something that GMT should be able to do. Better ideas are welcome.

**Comment by PaulWessel** [comment]
I started looking at this some months ago.  The idea was to automatically call on a CPT (categorical) and auto-supply -Z values monotonically (0.1,2...) following the segment numbers in the input.  So if input has 59 segments we get 59 unique colors and paint 59 different polygons.  This should not be rocket science to implement.

**Comment by KristofKoch** [comment]
May I request some kind of built in normalization? Sure, I could compute the size of the polygon/country and do the math myself. But I imagine this is a rather often used technique so it might be useful for quite a few users. Your thoughts?

**Comment by joa-quim** [comment]
A categorical cpt solution, besides putting the burden on the user to create it correctly,  would be hard to use with the DCW polygons. What's the numbering there? That's why I thought in the ID segment. 

There are also many GeoJSON files with counties and departments polygons that have a name (ID?). We can't currently read them but GDAL can so _gmt_ogrread_ will be able to do it for us.

**Comment by PaulWessel** [comment]
@KristofKoch: gmt spatial can compute area of polygons (and length of lines) and write that to segment headers, but I dont think it will write that in a useful format for psxy.  For instance, if gmtspatial would write "> -Z<somearea>" then users could use a CPT file tuned to area to make maps with color tied to polygon area.
@joa-quim: Sounds like we are saying the same things with segment ID as lookup value.  The categorical CPT is one of the options in makecpt so users would not make one themselves (but they could if they want to).

**Comment by joa-quim** [comment]
I gave this some work (quite a bit actually) but from Julia. I can now do this
```
# Load packages needed to download data and put into a DataFrame 
using CSV, DataFrames, HTTP

paises = CSV.File(HTTP.get("https://raw.githubusercontent.com/tillnagel/unfolding/master/data/data/countries-population-density.csv").body, delim=';') |> DataFrame;

# Extract the Europe countries from the DCW
eu = coast(DCW="=EU+z", dump=true);

# Generate two vector with country codes (2 chars codes) and the population density for European countries
codes, vals = GMT.mk_codes_values(paises[!, 2], paises[!, 3], region="eu");

# Create a Categorical CPT that allows plotting the choropleth (this was the most hard work)).
# Note that I needed to limit the CPT range to leave out incredibly high density *states* like Monaco 
# otherwise all others would get the same color.
C = cpt4dcw(codes, vals, range=[10, 500, 10]);

# Show result
plot(eu, C=C, G="+z", J=:guess, R="-76/36/26/84", title="Population density", colorbar=true, fmt=:png, show=true)
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/108138637-4d68ba80-70b6-11eb-8387-f2dbeedc5411.png)

**The problem**

Making the categorical CPT was the real head ache. The problem is that to paint the country polygons one need one entry in the CPT for each country and when we do ``makecpt(-T<contry-codes-list>)** one get a CPT whose C.range goes from 1 to number-of-countries, but that's not what we want if plotting that CPT with ``colorbar`` is wished (and if we don't then no one knows what the colors mean.

Another problem with current GMT is that  we cannot paint the DCW countries with a CPT. Hence we are forced to write those polygons down into disk, unless we use externals and hold those polygons in memory like shown above in Julia.

And not all is solved. The high density countries had to be left out (Macau has a density of > 6000 /sqr km) to not *steal* the colors to all others.
