### ISSUE TITLE
GMT_Encode_Options: Unable to allocate GMT_RESOURCE array

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4411]
I started receiving errors like this that actually are non-fatal errors
```
julia> gmtset(MAP_GRID_CROSS_SIZE_PRIMARY=0, FONT_ANNOT_PRIMARY=10, PS_CHAR_ENCODING="Standard+")
GMT [ERROR]: GMT_Encode_Options: Unable to allocate GMT_RESOURCE array
Error returned from GMT API: GMT_MEMORY_ERROR (25)
```
It turns out that they are caused by the fact that ``gmtset``, ``gmtbegin`` (others?) have no *keys*, so ``gmt_api#L11580``
```
key = gmtapi_process_keys (API, keys, type, *head, n_per_family, &n_keys);	/* This is the array of keys for this module, e.g., "<D{,GG},..." */
```
*returns* ``n_keys = 0`` and later (``gmt_api#L11606``)
```
	n_alloc = n_keys;	/* Initial number of allocations */
	if ((info = gmt_M_memory (API->GMT, NULL, n_alloc, struct GMT_RESOURCE)) == NULL) {
		GMT_Report (API, GMT_MSG_ERROR, "GMT_Encode_Options: Unable to allocate GMT_RESOURCE array\n");
		return_null (NULL, GMT_MEMORY_ERROR);
	}
issue that error innocuous but annoying message.

What have changed to cause this?

```

**Comment by PaulWessel** [comment]
Hm, I think I recently changed that due to some compiler warnings.  Probably should check that n_alloc > 0 in that test,  Do you want to try this:

```
	if (n_alloc && (info = gmt_M_memory (API->GMT, NULL, n_alloc, struct GMT_RESOURCE)) == NULL) {
		GMT_Report (API, GMT_MSG_ERROR, "GMT_Encode_Options: Unable to allocate GMT_RESOURCE array\n");
		return_null (NULL, GMT_MEMORY_ERROR);
	}

```

**Comment by joa-quim** [comment]
Then I get an ``Unable to reallocate`` further down (didn't trace it where).
But when there are no KEYs, shouldn't it return right at (would need to test if ``keys == ""``)
```
if ((keys = gmtapi_retrieve_module_keys (V_API, module)) == NULL) {
...
```

```
julia> gmtset(MAP_GRID_CROSS_SIZE_PRIMARY=0, FONT_ANNOT_PRIMARY=10, PS_CHAR_ENCODING="Standard+")
GMT [ERROR]: GMT_Encode_Options: Unable to reallocate GMT_RESOURCE array
```

**Comment by joa-quim** [comment]
OK, applying the same medicine at line 11737 make the warnings go away. Still, it has been doing a lot for nothing. Some parts of it are needed?

**Comment by PaulWessel** [comment]
It may have been coded up assuming there would always be KEYS. But checking is the right approach.

**Comment by joa-quim** [comment]
Don't get it. What test? The ones before calling ``gmt_M_memory()``?
But when no KEYs, isn't that function, called *GMT_Encode_Options*, sneaking more that it should?

And, have you voted already?

**Comment by PaulWessel** [comment]
Voted weeks ago.  Yes, I think if this line:

`	key = gmtapi_process_keys (API, keys, type, *head, n_per_family, &n_keys);	/* This is the array of keys for this module, e.g., "<D{,GG},..." */`


returns NULL, n_keys = 0 etc then it is probably game over for this function.  Just set *n = 0 and return NULL I think.  Feel free to try that.  I am f*ng with your peaks shit.

**Comment by joa-quim** [comment]
OK, seem to work well and no visible side effects.

I thought you had cleaned the peaks shit with that commit to master.

**Comment by PaulWessel** [comment]
No commit to master I hope.  My fix worked well for peaks but open can of worms elsewhere...

**Comment by joa-quim** [comment]
> No commit to master I hope

I think I saw it going to master. No PR
