### ISSUE TITLE
Issue with the default turbo CPT

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4414]
I'm reading [Crameri et al.,'s paper about color maps](https://www.nature.com/articles/s41467-020-19160-7). It says:

> Perceptual uniformity and intuitive colour order are both needed to prevent bias percolating into colour maps. This is also the case for so-called ‘improved’ rainbow-like maps such as Google’s Turbo. Although Turbo appears to meet perceptual order, the perceptual uniformity requirement of a science-ready colour map is not met due to its non-uniform lightness spectra.

**Comment by weiji14** [comment]
Crossref previous discussion on switch from rainbow to turbo at #1488. Also see PR at #1504.

**Comment by joa-quim** [comment]
What is the issue with turbo?

**Comment by PaulWessel** [comment]
It has a non-uniform lightness spectra and thus not perfect...

**Comment by joa-quim** [comment]
not perfect, right. But shade illuminated or not?

**Comment by PaulWessel** [comment]
Yes, I do not think the article talks about illumination and how that affects things, but presumably the argument will be that adding/subtracting shade should be done from a neutral unbiased color...

**Comment by joa-quim** [comment]
> neutral unbiased color.

You mean palettes with only a few colors, most of them ugly.

**Comment by PaulWessel** [comment]
If you read the article you will see they talk about applying a CPT to a know things (e.g., topography) versus new data you know nothing about.  The latter case certainly can bias you, but for bathymetry I may want to highlight, say, the mid-ocean ridges and use a CPT that will bias that part.  There is room for both as long as one knows what one is doing [note: most do not].

**Comment by joa-quim** [comment]
I didn't read that paper but have read quite a few on the subject. They basically say one must ditch any form of *jet* and should even be shammed of using it to use only uniformly perceptive CPTs. I disagree on that mainly because the illumination, which is crucial in our maps, is always (maybe not always but I've not seen it discussed) ignored.

But people are free and we already have lots perceptual continuous CPTs in GMT. And we can have more, ofc.

**Comment by PaulWessel** [comment]
Matplotlib added turbo after some discussion: https://github.com/matplotlib/matplotlib/issues/15091

**Comment by seisman** [comment]
Just a quick thought about the [GMT's built-in CPTs](https://docs.generic-mapping-tools.org/dev/cookbook/cpts.html).

We include the 28 CPTs (and maybe more in #4403) from "scientific color maps", but I feel that we don't give enough credits to SCM. We could add a note that, those CPTs are from SCM, and users who use those CPTs are encouraged to cite "Crameri, F., (2018). Scientific colour-maps. Zenodo. http://doi.org/10.5281/zenodo.1243862". We may even add acknowledgments in our README file.

**Comment by PaulWessel** [comment]
Yes, I had the same thought this morning.  We should definitively add the reference and maybe a paragraph about this issue, at the same time we update with the categoricals.  I guess we need to update the check for new SCM while at it.

**Comment by seisman** [comment]
BTW, in the page (http://www.fabiocrameri.ch/colourmaps.php), 

![image](https://user-images.githubusercontent.com/3974108/98484970-22cab400-21e1-11eb-9eb2-cf44c7857043.png)

The GMT link is still using the old soest site.  It would be good if you can contact Fabio to update to the new GMT site.

**Comment by PaulWessel** [comment]
OK, I sent the email

**Comment by PaulWessel** [comment]
I am looking at the zenodo page and not sure what we grab to determine if there is a new version.  But this seems promising:

```
curl -ks https://zenodo.org/record/4153113/export/hx#.X6hq_i9h0Wo | grep 'version      = {'
  version      = {6.0.4},
```

since 4153113 is the main record and I am asking for the bibtex reference.  We can get 6.0.4 out of that and compare to current.

I notice that the URL we have in the admin script is http://doi.org/10.5281/zenodo.1243862 and it I use that I get the same page as above.\ but my curl does not work.  So not sure what is the _permanent_ URL to use.

**Comment by seisman** [comment]
> I am looking at the zenodo page and not sure what we grab to determine if there is a new version. But this seems promising:
> 
> ```
> curl -ks https://zenodo.org/record/4153113/export/hx#.X6hq_i9h0Wo | grep 'version      = {'
>   version      = {6.0.4},
> ```
> 
> since 4153113 is the main record and I am asking for the bibtex reference. We can get 6.0.4 out of that and compare to current.
> 
> I notice that the URL we have in the admin script is http://doi.org/10.5281/zenodo.1243862 and it I use that I get the same page as above.\ but my curl does not work. So not sure what is the _permanent_ URL to use.

We already have a workflow checking the SCM version by parsing this page (http://www.fabiocrameri.ch/colourmaps.php). It works well.

**Comment by PaulWessel** [comment]
OK, spry, I guess it is just adding the categorical files then.

**Comment by PaulWessel** [comment]
We will have to run this manually once since version has not changed.  Will look after the family zoom is over...

**Comment by joa-quim** [comment]
Another interesting reading for categorical CPTs

https://blog.datawrapper.de/beautifulcolors/

**Comment by seisman** [comment]
I believe we're not going to change the GMT default CPT. We can close this issue after addressing this comment:

> I feel that we don't give enough credits to SCM. We could add a note that, those CPTs are from SCM, and users who use those CPTs are encouraged to cite "Crameri, F., (2018). Scientific colour-maps. Zenodo. http://doi.org/10.5281/zenodo.1243862". We may even add acknowledgments in our README file.
