### ISSUE TITLE
pscoast -RSA plots Saudi Arabia instead of South America

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4419]
gmt coast -RSA -JX12cd/0 -Baf -BWSen -Ggray -png map
![map](https://user-images.githubusercontent.com/537321/98054365-a62b8480-1e32-11eb-9458-dd64583a2f5f.png)

**Comment by PaulWessel** [comment]
As expected. **SA** as is the code for Saudi Arabia.  For continents, use **=**_continent-code_, i.e., **=SA**.

**Comment by joa-quim** [comment]
Ó right
