### ISSUE TITLE
Decide on what -B switch takes precedence for setting frame sides

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4421]
**Description of the desired feature**

The example on the [forum](https://forum.generic-mapping-tools.org/t/sloppy-frame-when-using-bxafg/1010) also points out another issue: The user only specified **-Bxafg** but the frame selections (implicitly set by **-BWESN**) involves all 4 frames even though **-By** was not set explicitly.  The effect here is that while delta_latititude is zero so no annotation or frame is drawn, the "frame is active" is still true due to the implicit **-BWESN** and you can see the frame extensions sticking out from the S and N curved borders.

I propose that if only **-Bx** or only **-By** is specified then the user does not want the other frames and we need to basically implement under the hood the equivalent of **-BSN** or **-BWE**, respectively.

Agree with this, @joa-quim and @seisman?

**Comment by seisman** [comment]
It doesn't sound intuitive to me. Why should **axes settings** (**-Bx** or **-By**) affect **frame settings** (**-BWSEN**)?

**Comment by seisman** [comment]
```
gmt begin map
gmt basemap -R0/10/0/10 -JX10c -Bxafg
gmt basemap -R0/10/0/10 -JM10c -Bxafg -X12c
gmt basemap -R0/10/0/10 -JM10c -Bafg -X12c
gmt end show
```
![image](https://user-images.githubusercontent.com/3974108/98289469-3de5bb80-1f76-11eb-80f9-f3a94523e3a2.png)

It seems there are more issues with the middle panel.

**Comment by PaulWessel** [comment]
Hm, yes - did not have that yesterday... Clearly the fancy frame outlines should still be plotted - minus their extenders.

**Comment by PaulWessel** [comment]
The curved ones are drawn and here we see the original issue:

`gmt basemap -R0/10/0/10 -JA5/90/10c -Bxafg -png map`

And time for another unrelated zoom meeting....

**Comment by joa-quim** [comment]
It makes sense to me that if you only say **-Bx** than the default of plotting also **y** frame is drop.

**Comment by PaulWessel** [comment]
Yes I agree.  This works as I intended:

`gmt basemap -R0/10/0/10 -JM10c -Bafg -BSN -png map`

![map](https://user-images.githubusercontent.com/26473567/98297533-a1f98700-1f58-11eb-80e8-caa906924038.png)

but @seisman's example fails because he is setting both -BWESN (implicitly as the default) but gives no y increments.  So we cannot have this limbo and it seems if you give no axis information then we cannot have that axis at the same time be "active"/

**Comment by PaulWessel** [comment]
Working on this and fixing a bug in the process.  I am trying to only update frame status if frame status has not been set by the user.  However, we have a few examples where I get failures:

1. admittance.sh: Here we intentionally plot x and y axes separate in two modules in order to set color.  This works; the failure is just due to the unspecified axis being drawn twice (so this is a good failure).
2. arrowline.sh: Here we are plotting with -Bx0 -Byg0.1 expecting to get a square frame ("-B0") plus y-gridlines.  Oddly, the south axis is missing but north is drawn, so possibly another bug.
3. poleline.sh: This is a geographic map with an oblique region (+r) stating -Bya1f1g1 only.  But curved gridlines fross the north axis and it is drawn while south is missing.  Similar to the previous in that regard.

Will look at these.
