### ISSUE TITLE
Consolidate GMT_AUTO_DOWNLOAD and GMT_DATA_UPDATE_INTERVAL

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4429]
**Description of the problem**

We have some inconsistencies in these parameters with room for improvements:

1. All the GMT defaults pertaining to the handing of the remove data on the selected data server start with **GMT_DATA_** except **GMT_AUTO_DOWNLOAD**.
2. There is implied redundancy between **GMT_AUTO_DOWNLOAD** and **GMT_DATA_UPDATE_INTERVAL** in that the latter could be set to 0 to indicate _never_.
3. Having fewer defaults settings is generally better - there are already a long list.

Proposal:

1. Honor **GMT_AUTO_DOWNLOAD** for backwards compatibility but otherwise retire the setting.
2. Let **GMT_DATA_UPDATE_INTERVAL** accept 0 or off as arguments that turns off auto-download.

Comments, @GenericMappingTools/core ?

**Comment by seisman** [comment]
I agree.
