### ISSUE TITLE
Shorter entry for GMT_DATA_SERVER selection

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4462]
**Description of the desired feature**

Since all the data mirrors are http://_name_.generic-mapping-tools.org, I think we might as well also accept just _name_ as the entry and if so build the URL ourselves.  That means

gmt set **GMT_DATA_SERVER** noaa

will basically set http://noaa.generic-mapping-tools.org.  of course, if name starts with http then we use it as given.

**Comment by PaulWessel** [comment]
Any concerns about this one, @joa-quim or @seisman ?  I know oceania lists https but http works are resolves to https anyway,

**Comment by joa-quim** [comment]
No, well on the contrary.

**Comment by seisman** [comment]
Sounds good to me.
