### ISSUE TITLE
Failed to create bundles

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4481]
The latest macOS CI fails when creating the macOS bundle.
```
+ cpack -G Bundle
CPack: Create package using Bundle
CPack: Install projects
CPack: - Install project: GMT []
CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/BundleUtilities.cmake:988 (message):
  error: fixup_bundle: not a valid bundle
Call Stack (most recent call first):
  /Users/runner/work/1/s/build/cmake/dist/cmake_install.cmake:70 (fixup_bundle)
  /Users/runner/work/1/s/build/cmake_install.cmake:46 (include)

CPack Error: Error when generating package: GMT
```

Possibly caused by #4461.  

@PaulWessel Could you try if you can build the bundle locally?

**Comment by PaulWessel** [comment]
Yes, and I get the same error. I think cmake also got an update so we need to sort out if #4461 or that.

**Comment by seisman** [comment]
The CI is using cmake 3.18.4. Perhaps you can revert #4461 and see if you can build the bundle.

**Comment by PaulWessel** [comment]
Might you be able to send me a git command that accomplishes the revert?  Then I will build and try.

**Comment by seisman** [comment]
```
# check out master branch
git checkout master
# create a new temporary branch
git checkout -b revert-4461

# revert the change in PR #4461
git revert 38af7209314461c0a6b19371eb2f75efce8ca042
```

**Comment by PaulWessel** [comment]
Thanks, building now.

**Comment by PaulWessel** [comment]
I mean, I am in the process - not taht the bundle is building yet.

**Comment by PaulWessel** [comment]
OK, bundle builds fine after the revert.

**Comment by seisman** [comment]
I believe we have to revert #4461 before we have a solution for the failure.

**Comment by PaulWessel** [comment]
Yes I agree.  And I am not sure what his original issue was.  Once can install the bundle in any directory (I just placed it in ~/pwessel/tmpdir) and ran it from there.  I think the whole point is to have a bundle be relocatable.

**Comment by seisman** [comment]
> And I am not sure what his original issue was.

In the old CMake scripts, `GMT_BINDIR` must be a relative path, e.g., `bin`, then we prepend the `CMAKE_INSTALL_PREFIX` to build the full path, e.g., `/usr/local/bin`. If `GMT_BINDIR` is an absolute path, e.g., `/another/absolute/path/bin`, then our CMake scripts will fail.

**Comment by rtburns-jpl** [comment]
Happy to look into this - how can I reproduce this error locally?

**Comment by PaulWessel** [comment]
Hi @rtburns-jpl, we simply ran the full build then cd into the build dir and try `cpack -G Bundle`.  This failed after the patch and we need it to work, obviously.

**Comment by rtburns-jpl** [comment]
Does removing these extraneous backslashes fix the issue? (I'm able to proceed past the initial error, but I think I am missing some prereqs such as hdf4 so it fails later on)

```diff
diff --git a/cmake/dist/CMakeLists.txt b/cmake/dist/CMakeLists.txt
index 1503a12cc..a078d2327 100644
--- a/cmake/dist/CMakeLists.txt
+++ b/cmake/dist/CMakeLists.txt
@@ -140,7 +140,7 @@ if (WIN32 AND NOT CYGWIN)
        install (CODE "
        if (CMAKE_INSTALL_PREFIX MATCHES \"_CPack_Packages\")
                include (BundleUtilities)
-               fixup_bundle(\"\${GMT_BINDIR_FULL}/gmt${CMAKE_EXECUTABLE_SUFFIX}\" \"\" \"\")
+               fixup_bundle(\"${GMT_BINDIR_FULL}/gmt${CMAKE_EXECUTABLE_SUFFIX}\" \"\" \"\")
        endif ()
        " COMPONENT Runtime)
 endif(WIN32 AND NOT CYGWIN)
@@ -195,7 +195,7 @@ if (APPLE)
                endfunction(gp_item_default_embedded_path_override)
 
                include (BundleUtilities)
-               fixup_bundle(\"\${GMT_BINDIR_FULL}/gmt${CMAKE_EXECUTABLE_SUFFIX}\" \"\${GMT_LIBDIR_FULL}/gmt${CMAKE_EXECUTABLE_SUFFIX}/plugins/${GMT_SUPPL_LIB_NAME}.so\" \"\")
+               fixup_bundle(\"${GMT_BINDIR_FULL}/gmt${CMAKE_EXECUTABLE_SUFFIX}\" \"${GMT_LIBDIR_FULL}/gmt${CMAKE_EXECUTABLE_SUFFIX}/plugins/${GMT_SUPPL_LIB_NAME}.so\" \"\")
        endif ()
        " COMPONENT Runtime)
 endif (APPLE)
```

(I think this won't work if the tooling needs to use a fake INSTALL_PREFIX during the Bundle build step. I haven't used bundle utilities extensively so I'm not sure if that will be an issue.)

**Comment by joa-quim** [comment]
Close this?
