### ISSUE TITLE
Strange failure in painting polygons with -Z and projecting

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4482]
```
makecpt -T100/500/100 > lixo1.cpt
```
This works
```
gmt plot -R-9.75/-6/36.9/42.2 -JX12c -Baf -BWSen -Clixo1.cpt -Zlix_vals1.dat -G+z -L -W0.5 lix_pol.dat -png lixo_lin
```

![lixo_lin](https://user-images.githubusercontent.com/537321/99985635-1b410880-2da6-11eb-9dbf-9aaba172eea0.png)

Now, if we project it screws
```
gmt plot -R-9.75/-6/36.9/42.2 -JM12c -Baf -BWSen -Clixo1.cpt -Zlix_vals1.dat -G+z -L -W0.5 lix_pol.dat -png lixo_merc
```
![lixo_merc](https://user-images.githubusercontent.com/537321/99985613-1419fa80-2da6-11eb-9706-cdeee913d173.png)

If, however we use the ``lix_vals.dat`` file that go from 1 to 4 instead of 100 to 400 and adapt the CPT accordingly, then both the linear and the projected maps are fine.

[data.zip](https://github.com/GenericMappingTools/gmt/files/5584226/data.zip)

**Comment by PaulWessel** [comment]
That is a great example.  I am actually curious what bug I will find when I debug!

**Comment by joa-quim** [comment]
And you’ll be even more curious to know that the bug kicks for zvals >180. 
The beast may think it’s a geog feature.  

Sent from my iDedo

**Comment by PaulWessel** [comment]
Thanks for the tip.  Will be PR fixed once the tests completes.  Easy.
