### ISSUE TITLE
grdimage can't read selected bands from GeoTIFF

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4493]
See [forum post](https://forum.generic-mapping-tools.org/t/how-to-plot-satellite-optical-image-of-geotif-format-and-show-the-true-color/225/13) for reference.

Debugging shows that gdalread is called 4 times, three of them in the *info* mode. The second time it carries the bands info but that is lost in subsequent calls and when it finally reads the data, the entire bands set is read. This happens because ``grdimage`` has this block that consumes and looses the bands request
```
	if (!Ctrl->D.active && ftype == GMT_IS_GRID) {	/* See if input could be an image of a kind that could also be a grid and we don't yet know what it is.  Pass GMT_GRID_IS_IMAGE mode */
		if ((I = GMT_Read_Data (API, GMT_IS_IMAGE, GMT_IS_FILE, GMT_IS_SURFACE, GMT_CONTAINER_ONLY | GMT_GRID_IS_IMAGE, NULL, Ctrl->In.file, NULL)) != NULL) {
			gmtlib_read_grd_info (GMT, Ctrl->In.file, I->header);	/* Re-read header as grid to ensure orig_datatype is set */
```

**Comment by joa-quim** [comment]
Does it really need to repeat header reading?
```
gmtlib_read_grd_info (GMT, Ctrl->In.file, I->header);	/* Re-read header as grid to ensure orig_datatype is set */
```
``orig_datatype`` should be right on first read.

**Comment by PaulWessel** [comment]
Perhaps not. Maybe you just need to change individual items (such as datatype) but how do you know without reading the header (again)?
