### ISSUE TITLE
White lines and white MAP_FRAME_PEN don't go along.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4497]
```
printf "0.0 0\n1.1 1" | gmt plot -JX12c/8c -Baf -BWSen+tBLA -R-0.04/1.12/-0.04/1.04  --MAP_FRAME_PEN=thicker,white --PS_PAGE_COLOR=gray -W1,white -png lixo
```

![lixo](https://user-images.githubusercontent.com/537321/100492771-71f06e80-3127-11eb-8038-14c7f85934c3.png)

**Comment by PaulWessel** [comment]
Probably a case for **GMT_THEME**=_inverse_.
Yet, that W axis should be white like the test.

**Comment by PaulWessel** [comment]
Interestingly, the basemap command work:

`gmt basemap -JX12c/8c -Baf -BWSen+tBLA -R-0.04/1.12/-0.04/1.04  --MAP_FRAME_PEN=thicker,white --PS_PAGE_COLOR=gray -png lixo`

So somewere we must be reverting to black before stroking.  Will look.

**Comment by joa-quim** [comment]
> Probably a case for GMT_THEME=inverse.

That's were it started (*dark* actually).

And if I take the ``darkmode.conf`` make it a ``gmt.conf`` and  run
```
printf "0.0 0\n1.1 1" | gmt plot -JX12c/8c -Baf -BWSen+tBLA -R-0.04/1.12/-0.04/1.04 --PS_PAGE_COLOR=gray -png lixo
```
then it cashes.

**Comment by joa-quim** [comment]
The crash occurs in ``gmtremote_data_load()``. It should not have to visit that function when plotting a local file.

```
printf "0.0 0\n1.1 1" | gmt plot -JX12c/8c -Baf -BWSen+tBLA -R-0.04/1.12/-0.04/1.04 --PS_PAGE_COLOR=gray -png lixo
```

**Comment by PaulWessel** [comment]
Working to fix the initial problem and have done so and find my fixes reveals 4 new failures that are actually corrections.  One is mgd77/cm4.sh which I think you wrote.  In it, you plot 3 axes WSn and then you plot the E axis with a separate setting: --MAP_DEFAULT_PEN=+1p,red.  Per the documentation, the leading + means

`Prepend + to overrule the color of the parameters MAP_GRID_PEN_PRIMARY, MAP_GRID_PEN_SECONDARY, MAP_FRAME_PEN, MAP_TICK_PEN_PRIMARY, and MAP_TICK_PEN_SECONDARY by the color of MAP_DEFAULT_PEN`

This means MAP_FRAME_PEN shall be red as well and the axis read.  This is not in the orig, but my revision now paints it red.  I am just checking that this is what you wanted when you wrote that script, if so then I can update the PostScript toghether with 3 others.

**Comment by PaulWessel** [comment]
Also, I may replace many of the extra AWK calls with GMT internal stuff (e.g, FORMAT_FLOAT_OUT=%.2lf instead of running awk to do taht.

**Comment by joa-quim** [comment]
Still on my my example, we get a warning
```
Your gmt.conf file (gmt.conf) may not be GMT 6 compatible
```
because the line 
```
else if (strlen (line) < 7 || (ver = strtol (&line[6], NULL, 10)) < 5 )
```
is triggered by this line in the ``darkmode.conf``
```
# Defaults file for darkmode theme
```

But above all, I'm finding that these problems are causes because ``gmt_begin()`` always calls ``gmtlib_refresh_server()`` that calls ``gmtremote_data_load()``. 

These is too intrusive and prone to give troubles. I don't think ``gmtlib_refresh_server()`` should be called by every GMT command. Loading a ``@file`` is a minor GMT feature and we should not condition all GMT commands to the risky shits that may happen with web access.

**Comment by PaulWessel** [comment]
Honestly, I thought this was fixed a while ago.  I will see if I can reproduce.  There is no reason to refresh the server until a remote file is referenced.

But I need to finish the first color issue first.  OK with your East axes being red then?

**Comment by joa-quim** [comment]
The East is red to show that it's the axis for the red line in plot. What is it that you want to change (though it's just a test)?

> there is no reason to refresh the server until a remote file is referenced.

Yes but the point is that the check for a refreshing server should only be done when a remote file is referenced, not by all commands, as it happens now with that call being in ``gmt_begin()``

**Comment by PaulWessel** [comment]
> The East is red to show that it's the axis for the red line in plot. What is it that you want to change (though it's just a test)?

I want to fix the bug that draws the line black despite the script requesting red.  It now draws red so I assume that is what you wanted.

**Comment by joa-quim** [comment]
Yes, it's a kind of poor plotyy

**Comment by PaulWessel** [comment]
> Still on my my example, we get a warning
> 
> ```
> Your gmt.conf file (gmt.conf) may not be GMT 6 compatible
> ```

Well, it is not a stand-along gmt.conf file.  We could rename these themes to have another extension if that is confusing.  They are not meant to be used as such, but via --GMT_THEME=darkmode or gmt set GMT_THEME darkmode.

**Comment by joa-quim** [comment]
OK, the issue  is fixed by #4498 but I still get
```
Your gmt.conf file (gmt.conf) may not be GMT 6 compatible
Your gmt.conf file (gmt.conf) may not be GMT 6 compatible
```
when using ``darkmode.conf`` as a local ``gmt.conf``

**Comment by joa-quim** [comment]
>  They are not meant to be used as such, 

Why? It has valid set of settings.

**Comment by PaulWessel** [comment]
But no headers etc as gmt.conf files do. Surely, you do not plan to do

`cp gmt-dev/share/theme/darkmode.conf ~/gmt.conf
`

to use the themes, with all the OS-specifics as well?

**Comment by PaulWessel** [comment]
FYI, the headers and version stuff in gmt.conf is generated by GMT code while the themes files are static text.

**Comment by joa-quim** [comment]
> Surely, you do not plan to do ... ``cp ...``

Just did that to check if the failures were the same as in my ``theme()`` function in Julia.

**Comment by PaulWessel** [comment]
I understand since the themes branch is not finalize yet.  But faking headers in _darkmode.conf_ means more things to edit when we change version numbers.  I rather not go there.
