### ISSUE TITLE
Rename README.Cmake

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#45]
Currently, there are two README files in the repo: README.md and README.Cmake. GitHub display the content of README.Cmake at the homepage of the repo. However, README.Cmake is too technical, and README.md is more useful for potential new users. 

IMHO we should rename README.Cmake to make GitHub display README.md instead.

**Comment by leouieda** [comment]
Hi @seisman, yeah I noticed that. I thought it would be good to morph the README.cmake into a CONTRIBUTING.md. We would need to add some things about the Github process and code quality, which we can copy from the GMT/Python CONTRIBUTING.md.

**Comment by remkos** [comment]
Best approach would be to merge README.CMake into README.md. There is already some overlap between the two.

**Comment by joa-quim** [comment]
I think we can this one now
