### ISSUE TITLE
Use of gdal drivers outputs .xml file (PAMDataset)

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#451]
More of a question than a bug (sorry).

Doing a ``grdcut @earth_relief_15m -RIS -Gtest.tif=gd:GTIFF`` creates the anticipated ``.tif`` file. In addition, a ``test.tif.aux.xml`` is also created. This file is rather empty:

```
<PAMDataset>
  <PAMRasterBand band="1">
    <NoDataValue le_hex_equiv="000000000000F87F">nan</NoDataValue>
  </PAMRasterBand>
</PAMDataset>
```

Same thing with ``grdcut @earth_relief_15m -RIS -Gtest.nc=gd:GMT``, but now the ``.xml`` contains more information:
```
<PAMDataset>
  <SRS>GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]</SRS>
  <PAMRasterBand band="1">
    <NoDataValue le_hex_equiv="000000000000F87F">nan</NoDataValue>
    <Metadata>
      <MDI key="STATISTICS_MAXIMUM">1606</MDI>
      <MDI key="STATISTICS_MEAN">134.09206349206</MDI>
      <MDI key="STATISTICS_MINIMUM">-1563</MDI>
      <MDI key="STATISTICS_STDDEV">486.8305866477</MDI>
    </Metadata>
  </PAMRasterBand>
</PAMDataset>
```

Doing a ``grdcut @earth_relief_15m -RIS -Gtest_netcdf.nc=gd:netcdf`` creates no ``.xml`` file.

Is the output of this ``.xml`` a deliberate action by ``gmt`` or is it made by ``gdal``?

**Comment by joa-quim** [comment]
That's a GDAL thing. It has an option (something like a``no PAM``) to prevent the .xml file creation but I have not present the details.

**Comment by abanbj** [comment]
Got it. Thanks joaquim.

As an additional info; if you specify more gdal options, the .xml is not created. E.g.:

```
grdcut @earth_relief_15m -RIS -Gtest.tif=gd/1/0/-9999:GTIFF
```

**Comment by abanbj** [comment]
Closing.
