### ISSUE TITLE
Update Scientific Colour Maps (F. Crameri)

### ISSUE THREAD

**Issue by GD-A** [GenericMappingTools/gmt#4513]
Version 6 has been released in January 2020. (http://www.fabiocrameri.ch/colourmaps.php)

[also, when using the polar-type palette (Vik for example), this new version goes from 0 to 1 (instead of -1 to 1), which differs from the version currently used by GMT

(in gmt current)
> gmt makecpt -Cvik -G-1/0 -T0/100 -I > cold_only.cpt
> gmt makecpt -Cvik -G0/1 -T0/100 > hot_only.cpt

(with files from v6)
> gmt makecpt -Cvik -G0/0.5 -T0/100 -I > cold_only.cpt
> gmt makecpt -Cvik -G0.5/1 -T0/100 > hot_only.cpt

**Comment by PaulWessel** [comment]
We just updated all of this 1-2 weeks ago.  When you say current, do you mean 6.1.1? We have updated master since then.

**Comment by GD-A** [comment]
I'm indeed under 6.1.1

**Comment by PaulWessel** [comment]
OK, then I think we can close this issue since already done (there wont be a 6.1.2 release)
