### ISSUE TITLE
#4499 is bothering externals with false error message

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4528]
The #4499 introduced this line in ``gmt_api.c#L8926``
```
first = gmt_download_file_if_not_found (API->GMT, input, 0);	/* Deal with downloadable CPTs */
```

but that now makes that any call that uses a CPT or even a color complains like.

```
julia> makecpt(range="-1/1/0.1");
makecpt [ERROR]: Cannot find file turbo
```

 Didn't try but I'm sure that the ``gmtmex`` is suffering from the same.

**Comment by joa-quim** [comment]
Actually the same happens in command line
```
makecpt -T-1/1/0.1
makecpt [ERROR]: Cannot find file turbo
-1      55.375/37.125/104.63    -0.9    55.375/37.125/104.63    L
...
```

**Comment by PaulWessel** [comment]
@seisman reported this a few days ago.  I will get to it when I get to it.  Lots of new issues during a week of lots of Chair work.

**Comment by PaulWessel** [comment]
Repeat of #4512 - so closing this one.
