### ISSUE TITLE
Inconsistent error/warning in surface

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#454]
When surface **-Q** or **-Vl** are used we get a message like this:

> surface [ERROR]: Grid domain: W: -179.5 E: 179.5 S: -89.5 N: 89.5 n_columns: 359 n_rows: 179 [gridline registration]

The problem is the word ERROR.  It is not an error, it is information so it should say

> surface [INFORMATION]: Grid domain: W: -179.5 E: 179.5 S: -89.5 N: 89.5 n_columns: 359 n_rows: 179 [gridline registration]

I can make this happen if **-Vl** is set, but if just **-Q** is set and the verbosity level is none, that line will not print at all.  My suggestion is that if **-Q** is set I temporarily lift verbosity to GMT_MSG_LONG_VERBOSE (**-Vl**) so that the messages are formatted correctly, then reset to its prior value.  Seems reasonable?

**Comment by leouieda** [comment]
Woudln't it be confusing to have an "information" message when the user requests no verbosity?

**Comment by PaulWessel** [comment]
Not really.  The **-Q** is sort of like a verbosity option as you are just asking for information but not actually do the gridding:

> 	-Q Query for grid sizes that might run faster than your selected -R -I.


So it would be odd to receive no output, and odd to be told it is an ERROR.  You expect INFORMATION in this case but may not think to add **-Vl** in addition to **-Q**; having to add both would be silly, no?

**Comment by leouieda** [comment]
>  having to add both would be silly, no?

Yep, completely agree. But then the information being printed is the actual output of the module, right? It's not really information related to the processing (which is that `surface [INFORMATION]` would imply). To me, the fact that we would need to forcibly overwrite our own logging mechanics to make this happen is evidence that this output should be handled the same way the output of `grdinfo` for example. Since that output is something that the user will want to parse possibly input into another module call.

**Comment by PaulWessel** [comment]
Okey, can agree with that.  So **-Q** changes the output type of the module from GRID to DATASET, where the output is generally text records (this has implications for the THIS_MODULE_KEYS and external interfaces).  We may wish to reformat this output to be more easily parsable.  Then **-Q** would output such records, while **-Vl** will instead print said INFORMATION texts.  Is this what you mean?

**Comment by leouieda** [comment]
That seems to be the more reasonable format but we have to weight how bad it would be to break compatibility like this. I can image people (GMTSAR?) parsing the output of -Q in a script and now ending up with broken code. One person's bug is another person's feature.

> So **-Q** changes the output type of the module from GRID to DATASET, where the output is generally text records

Seems reasonable. What is the current output of surface with -Q? Is it an empty GRID?

> We may wish to reformat this output to be more easily parsable.

From the description of -Q, it would be reasonable to expect that one could:

```
gmt surface `gmt surface -R... -I... -Q` -Gout.grd -VI ...
```

Right?

**Comment by PaulWessel** [comment]
No, -Q produces just verbose text on stdout for now.  As an example, see this command and its output; it is basically the prime number case of the original post re surface on the old wiki:

```
gmt surface -R-179.5/179.5/-89.5/89.5 -I1  -Q -Gout
surface [ERROR]: Grid domain: W: -179.5 E: 179.5 S: -89.5 N: 89.5 n_columns: 359 n_rows: 179 [gridline registration]
surface [ERROR]: Hint: Choosing -R-179.5/180.5/-89.5/90.5 [n_columns = 360, n_rows = 180] might cut run time by a factor of 131.07784
surface [ERROR]: Hint: Choosing -R-179.5/180.5/-95.5/96.5 [n_columns = 360, n_rows = 192] might cut run time by a factor of 123.71138
surface [ERROR]: Hint: Choosing -R-179.5/180.5/-99.5/100.5 [n_columns = 360, n_rows = 200] might cut run time by a factor of 118.28795
surface [ERROR]: Hint: Choosing -R-191.5/192.5/-95.5/96.5 [n_columns = 384, n_rows = 192] might cut run time by a factor of 117.30276
surface [ERROR]: Hint: Choosing -R-191.5/192.5/-89.5/90.5 [n_columns = 384, n_rows = 180] might cut run time by a factor of 114.70614
surface [ERROR]: Hint: Choosing -R-199.5/200.5/-89.5/90.5 [n_columns = 400, n_rows = 180] might cut run time by a factor of 111.93449
surface [ERROR]: Hint: Choosing -R-179.5/180.5/-107.5/108.5 [n_columns = 360, n_rows = 216] might cut run time by a factor of 110.78153
surface [ERROR]: Hint: Choosing -R-215.5/216.5/-89.5/90.5 [n_columns = 432, n_rows = 180] might cut run time by a factor of 109.1695
surface [ERROR]: Hint: Choosing -R-199.5/200.5/-95.5/96.5 [n_columns = 400, n_rows = 192] might cut run time by a factor of 109.07659
surface [ERROR]: Hint: Choosing -R-199.5/200.5/-99.5/100.5 [n_columns = 400, n_rows = 200] might cut run time by a factor of 106.4346
surface [ERROR]: Hint: After completion you can recover the desired region via gmt grdcut
```

So it does not give you one solution, but lists a range of options and estimated savings (these are very approximate).

**Comment by abanbj** [comment]
What about adding an option that chooses the first(/best/optimal?) suggestion by ``surface -Q [..]``? E.g. a ``-Qauto`` (``-Qa``) which in practice would run this command (in Pauls case above):

```
#    User input
$ gmt surface -R-179.5/179.5/-89.5/89.5 -I1  -Qa -Gout

#    This is the command 'behind the scenes' that is executed
#    surface chooses a good -R based on the first Hint 
$ gmt surface -R-179.5/180.5/-89.5/90.5 -I1  -Gout
```

**Comment by joa-quim** [comment]
I'm fine with just replacing ERROR by INFORMATION. But once we are at it there is probably more to **-Q**. For example the last line  (``surface [ERROR]: Cannot suggest any n_columns,n_rows better than your current -R -I settings.``) would preferably also say INFORMATION.
```
C:\v>surface  -Rd -Q -I1
surface [ERROR]: You are attempting to grid a global geographic data set, but surface cannot handle poles.
surface [ERROR]: It will do its best but it remains a Cartesian calculation which affects nodes near the poles.
surface [ERROR]: Because the grid is flaggged as geographic, the (repeated) pole values will be averaged upon writing to file.
surface [ERROR]: This may introduce a jump at either pole which will distort the grid near the poles.
surface [ERROR]: Consider spherical gridding instead with greenspline or sphinterpolate.
surface [ERROR]: Grid domain: W: -180 E: 180 S: -90 N: 90 n_columns: 360 n_rows: 180 [gridline registration]
surface [ERROR]: Cannot suggest any n_columns,n_rows better than your current -R -I settings.
```
On the forum topic 8097, Paul you told Axexander that
  > To try to help, surface extends the grid but in this case that results in > 90 degree latitude and hence the scary

We discussed this several times but I was not aware that it was implemented. In that case those scary messages (scary because very few users understands them) should simply not be printed anymore. With this, the usefulness of **-Q** is highly reduced. 

  > surface [ERROR]: Hint: Choosing -R-179.5/180.5/-89.5/90.5 [n_columns = 360, n_rows = 180] might cut run time by a factor of 131.07784

**Comment by leouieda** [comment]
> No, -Q produces just verbose text on stdout for now .

Right, so then I agree with @joa-quim that it's best to just replace ERROR with INFORMATION
