### ISSUE TITLE
Issue warning if negative contour interval is given and suggestion to improve grdcontour 

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#456]
1. Issue a warning/error if the user specifies a negative contour *interval*. It has happened to me that I forgot to add the ``+`` to draw a single negative contour. E.g.

```
$ gmt grdimage @earth_relief_15m -RNO,IS -JS0/90/20c -K > temp.ps
$ gmt grdcontour @earth_relief_60m -R -J -C-500 -O >> temp.ps
```
This will give a  plot with no contours. 

2. If you want to draw a very limited amount of contours (e.g. one or two) contours, having to make a contour level file is cumbersome. What about having the ability to specify "several single" contours? E.g. if I want to draw the -2000, -1000 and -500 contour, I could specify ``-C+-2000,-1000,-500``.

**Comment by PaulWessel** [comment]
Listing comma-separated contours is a nice idea - please suggest it as a feature issue.  Meanwhile, the way to do it is this:

> 	-C Contours to be drawn can be specified in one of three ways:
> 	     1. Fixed contour interval, or a single contour if prepended with a + sign.
> 	     2. File with contour levels in col 1 and C(ont) or A(nnot) in col 2
> 	        [and optionally an individual annotation angle in col 3].
> 	     3. Name of a CPT.
>

**Comment by abanbj** [comment]
Super. Feature request for comma-separated contours (2) created; #461. #460 closes (1).
