### ISSUE TITLE
Failure to compile GMT on Apple Silicon

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4567]
**Description of the problem**

I am testing our build process on a Mac mini with an M1 chip (ARM architecture).  I am doing this without GDAL for now since at least for MacPorts the geos library fails to build (and libpvx does not support arm64 so **ffmpeg** cannot be installed - these have tickets and will be fixed soon I hope).

I anticipated this compilation Eror:

```
../src/gmt_common_sighandler.c:178:14: error: no member named '__eip' in 'struct __darwin_arm_thread_state64'
        array [0] = UC_IP (uc); /* caller's address */
                    ^~~~~~~~~~
../src/gmt_common_sighandler.c:62:56: note: expanded from macro 'UC_IP'
#   define UC_IP(uc) ((void *) (uc)->uc_mcontext->__ss.__eip)
                               ~~~~~~~~~~~~~~~~~~~~~~~ ^
```

Basically, I need to the `__arm64__` equivalent of

`#   define UC_IP(uc) ((void *) (uc)->uc_mcontext->__ss.__rip)`

for the M1 chip.  Could anyone with knowledge point me to a solution?

**Comment by seisman** [comment]
Maybe try something like:
```
uc_mcontext->__ss.__pc
```

https://www.programmersought.com/article/1124476622/
https://opensource.apple.com/source/cctools/cctools-877.8/include/mach/arm/_structs.h.auto.html

**Comment by PaulWessel** [comment]
The GDAL and ffmpeg issues remain, but not a GMT problem.
