### ISSUE TITLE
-By +angle

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#4575]
Sorry for the failed pull request. I'm not very familiar with Github yet... At any rate :

>For the y- and z-axes, arbitrary angles are not allowed but +an and +ap specify annotations normal [Default] and parallel to the axis.

## Somehow related to this :
I have a plot with Y calendar axis going down (January at the top, December at the bottom). I wanted to add a secondary Y-axis with the "year", but it takes to much space horizontally and the `-Bys+ap` gives the "year" written from bottom to top (opposite direction / you tilt your head to the left to read it).
With an arbitrary angle, one could easily do `-Bys+a270` to have it correctly written... 

Is it possible to add the feature ?
Thanks

**Comment by delaviel-anger** [comment]
up :)
I understand it's not a priority, but will it be considered?

**Comment by gd-a** [comment]
I like to update this one from time to time (:
