### ISSUE TITLE
Add description of lrbt to MAP_FRAME_AXES gmt.conf documentation

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4579]
Unless something changes, it seems that the MAP_FRAME_AXES default for modern theme will be WrStZ. Currently, the option to draw an axis without annotation and ticks is detailed in [-B documentation](https://docs.generic-mapping-tools.org/latest/gmt.html#b-full) but not in [gmt.conf documentation](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#map-parameters). I think it would be good to add this sentence to MAP_FRAME_AXES in the gmt.conf documentation:

"To just draw an axis without annotation and ticks you can use the l(eft), r(ight), b(ottom), t(opt) and (for 3-D) u(p) codes."

I can submit a PR with this tiny change if others agree that it would be useful.

**Comment by PaulWessel** [comment]
Yes, please do, it was just forgotten
