### ISSUE TITLE
Possible gmtdefaults documentation error

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4585]
The documentation for [gmtdefaults](https://docs.generic-mapping-tools.org/dev/gmtdefaults.html) says:
> (2) in classic mode you may use any text editor to edit the file gmt.conf in your home, ~/.gmt or current directory (if you do not have this file, run gmtset -D to get one with the system default settings)

I think "gmtset -D" should be "gmtdefaults -D > gmt.conf". ```gmtset -D``` outputs a blank gmt.conf file, whereas ```gmtdefaults -D``` writes the system default settings to stdout, which is the stated behavior. If my interpretation is correct, I can submit a PR with the change.

**Comment by PaulWessel** [comment]
Yes, sounds right - please fix.

**Comment by meghanrjones** [comment]
Thanks, will do. I am also going to change the language about the settings' permanence to account for differences in classic versus modern mode. Please correct the PR if my interpretation of the way sessions work in modern mode is wrong.
