### ISSUE TITLE
something werid when using xy2sys module

### ISSUE THREAD

**Issue by isLiYang** [GenericMappingTools/gmt#4601]
while using x2sys module to find crossovers between Jason-2 altimetry tracks data, the result is not what I expected.

1. With all the data in a jason cycle, cannot find all the intersections, plz see global.tif.
2. with sample points in the southern Hemisphere , intersections in  southern Hemisphere could be found well. plz see south.tif

my GMT version :6.1.1.
my operation system: Windows 10.

Result Map:
![expected_map](https://user-images.githubusercontent.com/69391863/103093218-a37c2d00-4634-11eb-923f-00774acd5284.jpg)
![global](https://user-images.githubusercontent.com/69391863/103093224-a545f080-4634-11eb-94fa-1ce801797631.jpg)
![north](https://user-images.githubusercontent.com/69391863/103093232-aaa33b00-4634-11eb-9626-5adb9ea042f1.jpg)

Origin Data:(It has to be noted that Origin data  eliminated NaN values. )

[Origin_south.txt](https://github.com/GenericMappingTools/gmt/files/5739822/Origin_south.txt)
[Origin_global.txt](https://github.com/GenericMappingTools/gmt/files/5739824/Origin_global.txt)

Batch Scripts:
set X2SYS_HOME=E:\x2sys_test\
gmt x2sys_init HY2A -Edat -Dnew.fmt -V -Gg -Wd100 -F
gmt x2sys_cross out.dat -THY2A -Ia -V -Rg -Z >out1.dat

new.fmt is defined as follows:
# Format define file for HY-2A project
#---------------------------------------------------------------------
# ASCII
# SKIP 0
# GEO
#---------------------------------------------------------------------
#name	intype	NaN-proxy?	NaN-proxy	scale	offset	oformat
lon 		a 		N 			0 		1 			0 		-
lat 		a 		N 			0 		1 			0 		-
ssh 		a 		N 			0 		1 			0 		-

**Comment by isLiYang** [comment]
[new.fmt.txt](https://github.com/GenericMappingTools/gmt/files/5739863/new.fmt.txt)
This is new.fmt

**Comment by PaulWessel** [comment]
The x2sys algorithm probably cannot do a full globe.  It should not have anything to do with latitude though, but longitude.  Can you try to set things up with -R-180/0/-90/90 as one run and -R09/180/-90/90 for another and see if combined the catch all the crossings?

**Comment by isLiYang** [comment]
> The x2sys algorithm probably cannot do a full globe. It should not have anything to do with latitude though, but longitude. Can you try to set things up with -R-180/0/-90/90 as one run and -R09/180/-90/90 for another and see if combined the catch all the crossings?

Thank you for your reply and you work on open source xy2sys module, I will try your suggestion, the issue will be closed in time.
