### ISSUE TITLE
Potential memory corruption in the gmtinit_init_fonts function

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#4605]
This bug is difficult to reproduce, but it is clearly visible in the code. If the length of the font name in the file PSL_custom_fonts is 31 characters, then sometimes when copying a string, it will not end with a null byte. The problem is on this line:
`strncpy (GMT->session.font[i].name, fullname, GMT_LEN32-1);`
Line 6342 in the src/gmt_init.c
If the string is 31 bytes long, it is copied without the terminating null byte. Similar line (3271) in the src/postscriptlight.c:
`strncpy (PSL->internal.font[i].name, fullname, PSL_NAME_LEN-1);`

For the font DejaVuSerifCondensed-BoldItalic I sometimes get lines in the ps file like
> /F69 {/DejaVuSerifCondensed-BoldItalic-ffffff.? Y}!

But not always.

It should also be noted that the maximum length of 31 characters for a font name is not sufficient. This is a GMT limit, not a PostScript. For example, in the Noto font family, many fonts have significantly longer names (e.g., NotoSerif-ExtraCondensedExtraBoldItalic). I suggest increasing the maximum font name length to 63 bytes.

**Comment by PaulWessel** [comment]
Thanks, we will increase that.

**Comment by uleysky** [comment]
Thanks, works fine
`echo "NotoSerifDisplay-CondensedExtraLightItalic 0.700 0" >PSL_custom_fonts.txt

echo "0.5 0.5 NotoSerifDisplay-CondensedExtraLightItalic" | gmt pstext -JX10c -R0/1/0/1 -F+jCM+a45+f18p,NotoSerifDisplay-CondensedExtraLightItalic -Bswne -P >test.ps
`
![test](https://user-images.githubusercontent.com/5275343/103145101-4a211480-4780-11eb-9a8f-0139096562a0.png)
