### ISSUE TITLE
psxy -Sq ignores font outline specification

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#4607]
Test code:
`
echo "0 0
1 1" | gmt psxy -JX10c -R0/1/0/1 -Sqn1:+lTest+f25p,Times-Bold,green=~1p,red -P -K >test.ps

echo "0.4 0.6 Test" | gmt pstext -JX10c -R0/1/0/1 -F+a45+jCM+f25p,Times-Bold,green=~1p,red -P -O >>test.ps
`
Result: font outline ignored by psxy
![test](https://user-images.githubusercontent.com/5275343/103117638-06160d00-46b7-11eb-8287-c9e947ddffc6.png)

**Comment by PaulWessel** [comment]
Not working in 6.0.0 and that is the oldest version I have installed.  Do you know if this actually was working in a previous version?

**Comment by seisman** [comment]
GMT 5.4.5:

![image](https://user-images.githubusercontent.com/3974108/103161940-74da8f80-47b7-11eb-8f79-7b0031629387.png)

**Comment by PaulWessel** [comment]
So green instead of red, but no outline.  I think having outline fonts in **-Sq** was never implemented since that typesetting is all done in PostScript via our _PSL_straight_path_labels_ function.

**Comment by PaulWessel** [comment]
Might you be able to post the PS file resulting in 5.4.5 from

`printf "0 0\n1 1\n" |  gmt psxy -JX10c -R0/1/0/1 -Sqn1:+lTest+f25p,Times-Bold,green=~1p,red -P -B0 > t.ps`

**Comment by seisman** [comment]
From 5.4.5: [t.ps.zip](https://github.com/GenericMappingTools/gmt/files/5744023/t.ps.zip)

**Comment by PaulWessel** [comment]
Experimenting a bit.  The PS function that places the label (_PSL_ST_place_label_)  sets the location, makes a small move (_G_), and then calls show:

`psl_label dup sd neg 0 exch G show	% Place the text, adjust vertically for any depth below baseline`

However, with outline and fill font going on our font specification is a mix of both:

`(\{0 1 0 C\} FS 17 W 1 0 0 C \[\] 0 B 700 F5)`

_show_ is not going to do anything here except fill the font like normal. If I comment out the line above and instead try

`psl_label dup sd neg 0 exch G false charpath V S U fs N	% Place the text, adjust vertically for any depth below baseline`

then I get this:

![Untitled](https://user-images.githubusercontent.com/26473567/103162888-9f6a1f80-479a-11eb-837f-ac3109353ce4.jpg)

So if we can set yet another bit flag when such a font spec is selected then I could perhaps edit PSL_straight_path_labels to end up calling either _PSL_ST_place_label_ and (a new) _PSL_ST_place_label_outline_ instead and we might have a winner.  This is just hard work during the Xmas break though. Note: Pretty sure that here we end up drawing the outline first, then fill with green, so the outline ends up being just teh outwards 0.5p of the fill outline.

**Comment by PaulWessel** [comment]
OK, using ~1p draws pen first while 1p will draw pen last.  Bit-flags for these two cases need to be different as the latter will need this instead:

` psl_label dup sd neg 0 exch G false charpath V fs U S N % Place the text, adjust vertically for any depth below baseline`

since now we want to fill first then stroke second.  It is starting to make sense (again).

**Comment by PaulWessel** [comment]
Comments in gmt_plot.c:

```
/* Note for PSL_strings.h: The function PSL_ST_prepare_text will examine the font string above and if it
 * contains the substring "FS" then we set PSL_fmode to 2, else it is 1.  Then, PSL_ST_place_label will
 * consult PSL_fmode and call show or false charpath fs S accordingly. */
```

I see nothing of the sort in the PostScript functions, so perhaps this note was for future fixing (which I sort of rediscovered today).

**Comment by uleysky** [comment]
This bug has already been opened on the old site http://gmt.soest.hawaii.edu/issues/1226 and fixed 50%.
