### ISSUE TITLE
Custom symbols machinery fails with spaces at beginning of empty lines

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#4638]
**Description of the problem**

When writing custom symbols it helps readability of the code a lot that one can insert spaces in front of commands:

```
-0.075  0            M -W0.3p
 0.075  0            D
 0      0      0.05  c -W0.3p -Gwhite
```
This works really great. But it breaks when you have spaces at the beginning of lines that are otherwise empty lines.

I made a test script that covers the possibilities of
* no spaces at beginning of lines
* a space in front of a command
* a space in front of a comment
* a space in an empty line

As the differences are a bit difficult to discern here on GitHub so I highlighted them in the following screenshot:

<img width="581" alt="spaces_annot" src="https://user-images.githubusercontent.com/45796239/104088465-7a2fe380-5267-11eb-94ba-ccefb9585e98.png">

Additionally, the error message is not very helpful in this particular case.

**Full script that generated the error**

```
#!/usr/bin/env bash

cat > location.txt << EOF
0.5 0.5
EOF

cat > no-space.def << EOF
# some boring comment

0 0 1 x -W2p,black
EOF

cat > command-space.def << EOF
# some boring comment

 0 0 1 x -W2p,black
EOF

cat > comment-space.def << EOF
 # some boring comment

0 0 1 x -W2p,black
EOF

cat > empty-line-space.def << EOF
# some boring comment
 
0 0 1 x -W2p,black
EOF

echo -e "\n### no space (works) ###" 
gmt plot -R0/1/0/1 -JX10c -B location.txt -Skno-space/1c -pdf no-space

echo -e "\n### command space (works) ###" 
gmt plot -R0/1/0/1 -JX10c -B location.txt -Skcommand-space/1c -pdf command-space

echo -e "\n### comment space (works) ###" 
gmt plot -R0/1/0/1 -JX10c -B location.txt -Skcomment-space/1c -pdf comment-space

echo -e "\n### empty line space (fails) ###" 
gmt plot -R0/1/0/1 -JX10c -B location.txt -Skempty-line-space/1c -pdf empty-line-space
```

**Full error message**

```
### no space (works) ###

### command space (works) ###

### comment space (works) ###

### empty line space (fails) ###
plot [ERROR]: Failed to parse symbol commands in file empty-line-space.def
plot [ERROR]: Offending line:
plot [ERROR]: Option -S: Parsing failure
```

**Actual outcome**

`plot` gets thrown off by an empty line with a space in the symbol definition file.

**Expected outcome**

`plot` simply ignores the empty line with space and carries on.

**System information**

* Operating system: macOS 10.15.7
* GMT version (`gmt --version`): 6.2.0_0bddcbf_2021.01.08

**Comment by KristofKoch** [comment]
Found another case that doesn't work:

If you have two lines with comments and the second comment has a space in front of the `#`, it fails as well.

```
cat > 2comment-space.def << EOF

# some boring comment
 # second line comment

0 0 1 x -W2p,black
EOF
```

This is independent of the first comment.

**Comment by PaulWessel** [comment]
In GMT, comment lines must start with a hashtag in the very first position.  This is imposed throughout, for data files, CPTs, def files.  I do not think we wish to relax that - it is a syntax we have defined over decades.
As for blank lines with a few stray lines: These we can fix - we do this elsewhere.

**Comment by KristofKoch** [comment]
Hi @PaulWessel, "hashtag must be in first position" is fine with me. I was just surprised that the `comment-space.def` example worked where the line starts with a space followed by the hashtag. 

I'd appreciate if you could take care of the empty lines with stray spaces – they are hard to pin down when the error message only says `plot [ERROR]: Offending line:` without anything else.

Thank you for looking into this!
