### ISSUE TITLE
GEOS_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by gsakkis** [GenericMappingTools/gmt#4641]
Building against a custom GEOS location on linux fails to find the library dir (although it finds the include dir). The error is in [this line](https://github.com/GenericMappingTools/gmt/blob/master/cmake/modules/FindGEOS.cmake#L148); the following change fixes it:
```diff
-          FIND_LIBRARY(GEOS_LIBRARY NAMES ${GEOS_LIB_NAME} PATHS ${GEOS_LIB_DIRECTORIES}/lib)
+          FIND_LIBRARY(GEOS_LIBRARY NAMES ${GEOS_LIB_NAME} PATHS ${GEOS_LINK_DIRECTORIES})
```

**Comment by seisman** [comment]
Could you please submit a pull request?
