### ISSUE TITLE
Coordinated response to GDAL's driver pruning request

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4645]
**Description of the desired feature**

Per emails from Kurt and Evan, GDAL are looking to prune their 200+ driver support.  GMT/OGR was mentioned as a candidate, as was the (old?) GMT/netcdf grid driver.  We should work on the response to their requests.  I think we will ask to keep the GMT/OGR until we have implemented this capability directly via OGR.  As for the old 2-D GMT/netcdf grid I think that is the old driver for 1-d GMT grids, @joa-quim ?

**Comment by joa-quim** [comment]
Yes, I saw that thread. Originally it did not mention any of the GMT related drivers. I even intended to add that the *GMT* driver could be removed. Yes, that driver id for the old 1-d grids, which I think we can still read. It's important that those grids can still be read (not long ago they were still distributed by the Multi Resolution ... forgot the rest) but it should be hour responsibility to read them.

Regarding the GMT/OGR, sure we need it. It's jus saying that it's being used internally by GMT.

I can report this in the GDAL thread.

**Comment by anbj** [comment]
> I think we will ask to keep the GMT/OGR until we have implemented this capability directly via OGR

GMT/OGR vs. 'directly via OGR'

Could you please explain what this means, Paul?

**Comment by PaulWessel** [comment]
It means have GMT read shapefiles directly via the GDAL library and not via a system call to ogr2ogr which makes an ASCII GMT/OGR temporary which we then read in.

**Comment by joa-quim** [comment]
Replied

http://osgeo-org.1560.x6.nabble.com/template/NamlServlet.jtp?macro=print_post&node=5454536

**Comment by PaulWessel** [comment]
Perfect, thanks.
