### ISSUE TITLE
Fix COLOR_NAN default setting

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4649]
**Description of the desired feature**

The default value for **COLOR_NAN** is set this way:

```
/* COLOR_NAN */
error += gmt_getrgb (GMT, "127.5", GMT->current.setting.color_patch[GMT_NAN]);
```

which clearly was meant to be half-way between 0 an 255.  However, having a floating-point NaN gray value is a bit silly since any image is likely to be created using integers and then suggestions like the one advanced in #4648 cannot easily work by default (since no pixel will have r = g = b = 127.5) and one must be using **--COLOR_NAN**=128.

Proposal: I suggest we set the default gray NaN value to 128.

**Comment by PaulWessel** [comment]
Any concerns with this, @joa-quim ?

**Comment by joa-quim** [comment]
No, but there are other ways of setting a transparent color via GDAL that I must dig out from the code. But busy figuring more shits with sending images and the pad.

**Comment by PaulWessel** [comment]
The 128 COLOR_NAN was updated via #4654. And with -Q[color] we do not need to address the proposal in #4648.

**Comment by PaulWessel** [comment]
THe 128 **COLOR_NAN** was updated via #4654. And with **-Q**[_color_] implemented this issue is resolved.
