### ISSUE TITLE
gravfft requires -D (density contrast) to go from Faa to Geoid, which is nonsense

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4655]
gravfft faa.grd -Fg -fg -E1 -N+l -Gfaa2geoid_gravfft.grd -Vl
gravfft [ERROR]: Must set density contrast

**Comment by PaulWessel** [comment]
You should strongly complain to the developer.

**Comment by joa-quim** [comment]
I'm just echoing users complains. Maybe the developer is listening.

**Comment by joa-quim** [comment]
Ghrrrrr, dumb of me. Ofc *Must set density contrast*. ``gravfft`` computes the effect of bat/topo grid. It is not to be used to convert FAA into Geoid (like in ``grdfft``)
