### ISSUE TITLE
grdimage lost ability to deal with indexed images from externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4657]
That happened in the ``grdimage`` rewrite where, from memory (mine), indexed images are previously expanded to RGB after reading. But now from externals (where the Image object lands), grdimage now does this and doesn't look anymore to the colormap contents. I used to be able to set transparency via colormap but that is lost too.

```
gray_only = (I->header->n_bands == 1);	/* Got a grayscale image */
```

**Comment by PaulWessel** [comment]
Can you present an example as I probably will have to debug that case.  So n_bands == 1 for indexed images and we need to consult the other header info on this.

**Comment by joa-quim** [comment]
```
# Works fine
imshow("trees.tif", fmt=:png, axes=:none)

# Gray only
It = gmtread("trees.tif");
imshow(It, fmt=:png, axes=:none)
```

But there is also the issue of the transparency. I forgot where I dealt with it in GMT. The code is probably still there but unused now.

[trees.tif.zip](https://github.com/GenericMappingTools/gmt/files/5822621/trees.tif.zip)

**Comment by PaulWessel** [comment]
Feel fee to look via _gmtapi_import_image_.  I have several Chair-related zooms today so won't have time to start on this.
