### ISSUE TITLE
Suppress Visual Studio deprecation warnings C4996 for postscriptlight.c

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#467]
**Description of the problem**

Appveyor builds reports lots of deprecation warnings C4996 when compiling postscriptlight.c (see https://ci.appveyor.com/project/seisman/gmt/builds/22794046/job/xn2yg3tvswt38d4c?fullLog=true for detailed build logs). We probably need add a `#pragma warning( disable : 4996 )` directive to suppress the Visual Studio warnings.

**Comment by joa-quim** [comment]
No need, you can just add ``/D_CRT_SECURE_NO_DEPRECATE``  to the cmake build command.

**Comment by seisman** [comment]
@joa-quim I added `/D_CRT_SECURE_NO_DEPRECATE` to `CMAKE_C_FLAGS` and the builds reported some weird errors about `common_runpath.c`.
See https://ci.appveyor.com/project/seisman/gmt/builds/22806354/job/2636jgcax2gg4ky3 for detailed logs.

**Comment by joa-quim** [comment]
@seisman I think I saw one of your commits adding Ninja. Please use it because the vcproj is unbearable verbose and it's a pain to figure out which was the first command that errored.

I have this in my ``ConfigUser.cmake`` and (ofc) builds do fine. Try adding the same.
```
	set (CMAKE_C_FLAGS "/D_CRT_SECURE_NO_WARNINGS /D_CRT_SECURE_NO_DEPRECATE ${CMAKE_C_FLAGS}")
	set (CMAKE_C_FLAGS "/D_CRT_NONSTDC_NO_DEPRECATE /D_SCL_SECURE_NO_DEPRECATE ${CMAKE_C_FLAGS}")

```
