### ISSUE TITLE
[NOTICE] warnings

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4670]
We should not be printing these warnings. Right **-Vq** shuts it up but that's too drastic. I would rather not see it at all. It brings nothing new.
```
julia> I = gmtread("https://www.gstatic.com/webp/gallery/4.sm.webp");
gmtread [NOTICE]:   -> Download URL file: https://www.gstatic.com/webp/gallery/4.sm.webp
```

**Comment by PaulWessel** [comment]
I think the initial idea here was limited to our server grids to to

1. Acknowledge the author(s) of the data set
2. Acknowledge the host of the data

It was not meant to do this for every possible file given via an URL.  For instance, the first time you access a particular earth_relief file you get

```
grdinfo [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdinfo [NOTICE]: Earth Relief at 10x10 arc minutes from Gaussian Cartesian filtering (18 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].
grdinfo [NOTICE]:   -> Download grid file [3.0M]: earth_relief_10m_p.grd
```

but no message after initial download.  Perhaps the solution here is to only do this for the served data?
