### ISSUE TITLE
Events -Mi. Clarify the meaning of color intensity.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4675]
I've been reading the documentation of [events](https://docs.generic-mapping-tools.org/dev/events.html) and the [animation 8](https://docs.generic-mapping-tools.org/dev/animations/anim08.html). There are some phrases about "whiten/darken the symbol" which are related to -Mi. 
However It is not clear to me how the color is changed. I am thinking that the HSV color system is used but not sure how. Are the parameters (for example in Mi1+c-0.6) indicating a shifting in the Saturation? Or in the Value? What are the min/max values that could be used? Is there any differences for the Duration of the Event (-Mi) and its coda (+c)? 

Thanks in advance.

**Comment by meghanrjones** [comment]
Take a look at [this section](https://docs.generic-mapping-tools.org/dev/events.html#the-three-time-functions). If it makes sense after reading that section, I think the solution is to link to there from the **-M** option in the ```event``` docs. If not, maybe some revisions are needed.

**Comment by PaulWessel** [comment]
The intensities given via **-Mi** are the same values that can be passed to **psscale -I**, **psxy -I** and of course **grdimage -I**.  They are expected to go from -1 to +1 and gets saturated if beyond that.  In all cases, any color we wish to shade is converted to h,s,v and then we keep the hue constant while changing the saturation and value, according to this schematic:

![Illlumination](https://user-images.githubusercontent.com/26473567/105243148-bb9b7b00-5b12-11eb-8215-b23966cfd8e5.png)

Here you can also see the two settings **COLOR_HSV_MAX_S** and **COLOR_HSV_MIN_V** which by default is not zero.

I will have to return to the code after lots of meetings coming up, I'm afraid.  This plot is one of many we need to add to the documentation on how shading works...

**Comment by Esteban82** [comment]
Thanks to both. Yes, that graph is very clear. So the parameter is the movement along the path. 

I have a new doubt based on the graph The change of the color in the coda, is made from the original one or from the new color after it first modification?

**Comment by PaulWessel** [comment]
For **-Mi**, the coda sets a fixed intensity that is applied to the original color of the symbol.  I have make a PR (#4685) that updtes the documentation.
