### ISSUE TITLE
The TYME_SYSTEM is not working

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4679]
Grepping the source tree shows no sign of ``RD0001`` or any other of the short-cuts.

```
julia> histogram(Dates.value.(eqs[!, 1]) ./ 1000, bin=86400*365, par=(TIME_SYSTEM=:RD0001,), f=:T, Vd=1,show=1)
        pshistogram  -JX12c/12c -Baf -BWSen -fT --TIME_SYSTEM=RD0001 -G150 -T31536000 -P -K > C:\TMP\GMTjl_tmp.ps
pshistogram [ERROR]: TIME_SYSTEM given illegal value (RD0001)!
pshistogram [ERROR]: Option -- parsing failure. Correct syntax:
        --<PARAMETER>=<value>.
           See gmt.conf for list of parameters.
pshistogram [ERROR]: Offending option --TIME_SYSTEM=RD0001
```

**Comment by PaulWessel** [comment]
I think line 11112 in gmt_init.c should use _lower_value_ instead of _value_ since all the checks in _gmt_init_time_system_structure_ are lower case. Not sure when/how that changed but the comparisons are agains dr001, rata, unix, etc.  Give it a try.

**Comment by joa-quim** [comment]
Works but found another bug. This works ``--TIME_SYSTEM=dr0001`` but notice that it's **dr** not **rd** like is said in gmt.conf and I think is right. Presumably it means RataDia 0001, which I found is the origin of Julia's DateTime system. The fix should retain the two so that I don't have to do a *case GMTver this else that*

**Comment by PaulWessel** [comment]
OK, so you want me to (1) fix the lower case, and (2) leave in a backwards compatible for both rd and dr, and (3) fix the docs so it says rd in the docs, yes?

**Comment by joa-quim** [comment]
I already did (1) & (2) (PR coming) but (3) is not needed. The docs already say RD.
