### ISSUE TITLE
Unable to install custom fonts

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#469]
I tried to install a few custom fonts but was stopped quite early in the process. According to the documentation [17.1. Using non-default fonts with GMT](http://www.generic-mapping-tools.org/gmt/latest/GMT_Docs.html#using-non-default-fonts-with-gmt) I should follow the instructions in the `PSL_custom_fonts.txt` under the `share/postscriptlight` directory. This folder doesn't exist on my system, neither does the text file. 

How do I install custom fonts in GMT 6?

**System information**

* Operating system: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0 x86_64)
* Version of GMT: 6.0.0_8eebf23

**Comment by seisman** [comment]
@KristofKoch The whole `share/postscriptlight` directory was removed in GMT6 and the documentation was not updated.

Before updating the documentation, you can refer to the PSL_custom_fonts.txt in 5.4 branch (https://github.com/GenericMappingTools/gmt/blob/5.4/share/postscriptlight/PSL_custom_fonts.txt)

**Comment by KristofKoch** [comment]
@seisman I installed the font on my system and it does show up with `fc-list | grep "Futura"`. So I understand it is properly installed on the system. Then I went ahead and created the `share/postscriptlight` directory as well as the `PSL_custom_fonts.txt`file and added the Postscript Name of the fonts I want to use:

```
Futura-Bold			0.700		0
Futura-Medium                   0.700		0
```

However it seems not to work. `pstext -L` doesn't list the Futura fonts. Where do I make a mistake?

**Comment by seisman** [comment]
I followed your steps and it works. Not sure why it's not working for you.

GMT first tries to search for `PSL_custom_fonts.txt` in your currently directory. If not found, then search in `~/.gmt`, then in `GMTHOME/share/postscriptlight/`. Is there a `PSL_custom_fonts.txt` in your current directory or `~/.gmt`?

Can you run `gmt pstext -L -Vd` to print the detailed debug information?

**Comment by KristofKoch** [comment]
The error was located between keyboard and chair. I created the folder in `/usr/share/` instead of `/usr/local/share/`.

**Before moving the file into the proper directory:**
```
kristof@h2813222:/opt/gmt-dev/test_fonts$ pstext -L -Vd
pstext [DEBUG]: Obtained the ppid from parent: 1303
pstext [DEBUG]: Enter: gmtinit_new_GMT_ctrl
pstext [DEBUG]: GMT->session.SHAREDIR = /usr/local/share
pstext [DEBUG]: GMT->session.HOMEDIR = /home/kristof
pstext [DEBUG]: GMT->session.USERDIR = /home/kristof/.gmt [created]
pstext [DEBUG]: GMT->session.CACHEDIR = /home/kristof/.gmt/cache [created]
pstext [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
pstext [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
pstext [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /home/kristof/.gmt
pstext [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /home/kristof/.gmt/postscriptlight
pstext [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/share/postscriptlight
pstext [DEBUG]: GMT: 5. gmt_getsharepath failed
pstext [DEBUG]: Map distance calculation will be Cartesian
pstext [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
[… snip …]
	 37	GothicBBB-Medium-EUC-H
	 38	GothicBBB-Medium-EUC-V
pstext [DEBUG]: Entering GMT_Destroy_Session
kristof@h2813222:/opt/gmt-dev/test_fonts$
```

Those two lines made it clear to me …
```
pstext [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/share/postscriptlight
pstext [DEBUG]: GMT: 5. gmt_getsharepath failed
```


**After moving the file into the proper directory**
```
kristof@h2813222:/opt/gmt-dev/test_fonts$ pstext -L -Vd
pstext [DEBUG]: Obtained the ppid from parent: 1303
pstext [DEBUG]: Enter: gmtinit_new_GMT_ctrl
pstext [DEBUG]: GMT->session.SHAREDIR = /usr/local/share
pstext [DEBUG]: GMT->session.HOMEDIR = /home/kristof
pstext [DEBUG]: GMT->session.USERDIR = /home/kristof/.gmt [created]
pstext [DEBUG]: GMT->session.CACHEDIR = /home/kristof/.gmt/cache [created]
pstext [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
pstext [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
pstext [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /home/kristof/.gmt
pstext [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /home/kristof/.gmt/postscriptlight
pstext [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/share/postscriptlight
pstext [DEBUG]: Map distance calculation will be Cartesian
[… snip …]
	 38	GothicBBB-Medium-EUC-V
	 39	Futura-Bold
	 40	Futura-Medium
pstext [DEBUG]: Entering GMT_Destroy_Session
kristof@h2813222:/opt/gmt-dev/test_fonts$
```

Now it works properly. Thank you for looking into this and nudging me in the right direction, @seisman !
