### ISSUE TITLE
Improve the behavior of inset if -D is not given

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4713]
**Description of the problem**

The inset documentation says that **-D** options is required, but it doesn't report any errors if **-D** is not given. It simply ignores the inset map.

**Full script that generated the error**

```
gmt begin inset pdf
  gmt basemap -R0/40/20/60 -JM6.5i -Bafg -B+glightgreen
  gmt inset begin # -DjTR+w2.5i+o0.2i
    gmt basemap -Rg -JA20/20/2i -Bafg
  gmt inset end
gmt end show
```

**Actual outcome**

When **-D** is not given, the inset map is not plotted.

**Expected outcome**

It should either gives an error, or **-D** should have a default value, similar to `logo`, `image` etc.

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): `6.2.0_2ea7528_2021.01.14`

**Comment by PaulWessel** [comment]
I think it is not really possible to have a default value for inset, so the best solution is to give an error.  I will look at that.
