### ISSUE TITLE
Let psevents have access to textbox color, outline, and shade

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4728]
**Description of the desired feature**

Since **psevents** calls **pstext** to place labels, it need to have an option to control the aspets of a textbox: clearance, boxshape, boxpen, boxfill, and drop-down shaded background.  A suitable option is one of -H, -I, or -Z.

**Comment by joa-quim** [comment]
Probably a lot more of work but if all symbols and polygons were given that extra shade property we could do funny things simulating volumes.

**Comment by PaulWessel** [comment]
Not sure if the same kind of 2-d shifted shade would work that way, but you can do that now by plotting twice: first the shade color and -Ddx/dy, then the regular symbol color.  See what it looks like.

**Comment by joa-quim** [comment]
Yes, had thought on it too but it would need computing a good *dx/dy*, whilst if we could give it in plot units the result would the same yes.

**Comment by joa-quim** [comment]
Well, **-D** is not clear on the *dx/dy* units.

**Comment by PaulWessel** [comment]
Those are in c|i|p.

**Comment by PaulWessel** [comment]
I will fix.

**Comment by joa-quim** [comment]
OK, so **-D** will do.
