### ISSUE TITLE
Bug with -Yc and -Xc in Movie and -Sb

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4733]
I made an animation with background script. I use -**Yc1.92** and -**Xc** for the offset but the plot is not correctly generated as you can see in the main frame. With -Y/Xa or numbers it worked correctly.

![EJ24 2_Anim_Mapa_Anim_ARG_Sismicidad_Vulcanismo_v9](https://user-images.githubusercontent.com/17908951/106411129-2dcd6300-6423-11eb-883e-c778cd3d94e1.png)

I share the shell file as txt:
[EJ24.2_Mapa_Anim_ARG_Sismicidad_Vulcanismo.txt](https://github.com/GenericMappingTools/gmt/files/5901701/EJ24.2_Mapa_Anim_ARG_Sismicidad_Vulcanismo.txt)

**System information**

* Operating system: Ubuntu 20.04
* GMT version (`gmt --version`): 6.2.0_b7eaa8f_2021.01.29

**Comment by PaulWessel** [comment]
I have verified this problem.  I have to dig through comments to see if a) This can be fixed or b) the -Xc -Yc cannot be used in movie.

**Comment by Esteban82** [comment]
I found that if the width ot canvas it is the same of the map, then -Xc works fine. But, in other cases like mine where I add a frame to the map and a legend outside the map, then it doesn't work.
