### ISSUE TITLE
Behavior of PS_MEDIA setting in classic and modern mode

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4734]
This issue follows up on comments by @meghanrjones in #3344. In **classic** mode, **PS_MEDIA** is _always_ used to set the paper size of the PostScript plot as the only supported graphics format.  The default paper size is either A4 or US letter, but this is typically changed via **PS_MEDIA** for larger maps or specialized plots.  This behavior is correct and has not nor will not change going forward.

However, for **modern** mode all the PostScript plotting is removed from the users direct control in several ways.  For instance, the default graphics format is PDF, but users can specify a range of raster formats, EPS and PS.  Apart from the pure PS choice, all other formats imply a limitless canvas (actually, limited to 11 x 11 meters), and then we crop the canvas do what was actually used.  In this context, **PS_MEDIA** should have **no** purpose.  A complication arises should a user request several graphics formats with one being PS, such as in

```
gmt begin map ps,png
   gmt coast -Rg -JH180/15c -Gpink -B
gmt end show
```

Here there is a mix of plots that must be cropped (png) and one that has a specified paper size (whatever **PS_MEDIA** says).  Since in reality we always make a PostScript file first, what should be behavior be in this case?  Right now, both the PNG and PS plot actually have the size of the default paper size for PostScript [A4].  I think the correct behavior should be:

1. Always plot using the infinite canvas
2. For ps (PostScript output), crop this boundingbox to what **PS_MEDIA** says
3. For other formats, crop to fit (as per **PS_CONVERT** settings)

However, I am not sure what a user imagine they want by asking for a PS. Say they ask for EPS instead. Well, setting eps,png yields a correctly cropped EPS file but still a page-sized PNG!  I doubt that is what is expected, but who knows what goes on in the minds of users.

Seems to me we should enforce the rule above, making all PDF, EPS, and rasters cropped to the plot size, while PS output is cropped to the page size.  Any guru who for whatever reason wants a PNG with exact page size can make the PS then run **psconvert** as needed.  I cannot really see the need for this in modern mode.

Comments, @GenericMappingTools/core ?

**Comment by meghanrjones** [comment]
> 1. Always plot using the infinite canvas
> 2. For ps (PostScript output), crop this boundingbox to what **PS_MEDIA** says
> 3. For other formats, crop to fit (as per **PS_CONVERT** settings)

Yes, I agree that this would be a good solution.

**Comment by seisman** [comment]
Totally agree. 

Just want to make sure that, the following script produces both PNG and PS in A4-size, right?
```
gmt begin map ps,png
   gmt set PS_MEDIA A4
   gmt coast -Rg -JH180/15c -Gpink -B
gmt end show
```

**Comment by PaulWessel** [comment]
Hm, that seems counter to what I just proposed, @seisman?

**Comment by joa-quim** [comment]
I don't even understand what is the interest of supporting both PS and others in a single command.

**Comment by PaulWessel** [comment]
I don't either, but again reading the users minds is hard. The PS_MEDIA should only set the size of the **PS** Media, not the PNG media.

**Comment by seisman** [comment]
Re-read your post again. Are you proposing that the following script still produces a cropped png file, although users explicitly set PS_MEDIA to A4?
```
gmt begin map png
   gmt set PS_MEDIA A4
   gmt coast -Rg -JH180/15c -Gpink -B
gmt end show
```

**Comment by PaulWessel** [comment]
Yes, I was, but I can actually imagine a case, other than movie making, where a user needs to make 18 PNG figures that are somewhat different but for webpage or similar layout they prefer each PNG to have the same dimension.  I assume that is what you might be thinking of?  That would mean that a PS_MEDIA set via gmt set after start of the session changes the behavior from auto to fixed.  So in that scenario, we have the issue with users pre-existing gmt.conf file which may have a PS_MEDIA 20cx20c and then do we ignore that or not?

**Comment by seisman** [comment]
I think we had some similar discussions before (e.g., #2100, #2120).

> Yes, I was, but I can actually imagine a case, other than movie making, where a user needs to make 18 PNG figures that are somewhat different but for webpage or similar layout they prefer each PNG to have the same dimension. I assume that is what you might be thinking of?

Yes. 

> That would mean that a PS_MEDIA set via gmt set after start of the session changes the behavior from auto to fixed. So in that scenario, we have the issue with users pre-existing gmt.conf file which may have a PS_MEDIA 20cx20c and then do we ignore that or not?

We already have **gmt begin -C** to ignore it.

**Comment by PaulWessel** [comment]
We will need a mechanism to detect this.  Since **PS_MEDIA** default is a4 already setting PS_MEDIA to a4 does not change the setting but now we want it to be honored, so to speak.  Complications:

I do not think we can assume that some gmt.conf in the current directory which happens to have **PS_MEDIA** letter or a4 is actually an attempt of the user to enforce a fixed size PNG plot.  While the gmt.conf will be included in the session (unless begin -C is used) I think **PS_MEDIA** cannot interpreted that way.  It should take an active gmt set PS_MEDIA a4 to change that.
Perhaps a better solution is for the user to change **PS_CONVERT**? The default is "A" which means crop to size. I think this is a better solution (also avoids the misnomer of PS_* being applied to rasters).  The only issue is how to pass a blank string (i.e., no A) via **gmt begin** _name_ _psconvertopts_.  Trying `gmt begin map png ""` did not work, so we probably need a dummy psconvert option we can give that means "enforce media setting".  Perhaps **-N** for "eNforce paper size"?

**Comment by seisman** [comment]
> We will need a mechanism to detect this. Since **PS_MEDIA** default is a4 already setting PS_MEDIA to a4 does not change the setting but now we want it to be honored, so to speak. Complications:

Hm, is it already implemented in GMT?
```
gmt begin map png
   gmt coast -Rg -JH180/15c -Gpink -B
gmt end show
```
The above script produces a cropped PNG.

```
gmt begin map png
   gmt set PS_MEDIA A4
   gmt coast -Rg -JH180/15c -Gpink -B
gmt end show
```
This script produces a A4 PNG.

**Comment by PaulWessel** [comment]
No, since this gives a A4 figure:

```
gmt set PS_MEDIA A4
gmt begin map png
   gmt coast -Rg -JH180/15c -Gpink -B
gmt end show
```

since the gmt.conf created before the session has the default set.

**Comment by PaulWessel** [comment]
Per psconvert man page, -A+n should do what is desired but not working if I give A+n as psconvertoption.  Will debug.

**Comment by PaulWessel** [comment]
I am working on this.  Not trivial, so will take a bit longer. We have the 5 inch padding forth 11x11m canvas that interferes a bit so far, but working on that.

**Comment by seisman** [comment]
> No, since this gives a A4 figure:
> 
> ```
> gmt set PS_MEDIA A4
> gmt begin map png
>    gmt coast -Rg -JH180/15c -Gpink -B
> gmt end show
> ```
> 
> since the gmt.conf created before the session has the default set.

Hmmm, this is actually what I expect. I feel that what you propose may be more user friendly (users won't get uncropped images due to old gmt.conf) but is not intuitive (users will be surprised to see that "setting PS_MEDIA explicitly doesn't work").

**Comment by seisman** [comment]
From users' point of view, I feel that the following rules are simple and intuitive (thus easier to remember and understand):

1. In modern mode, all images are cropped by default
2. Setting PS_MEDIA to a specific paper size can fix the final paper size (i.e., uncropped)
3. GMT always follow the configurations in the "gmt.conf" file unless `gmt begin -C` is used

Exceptions to the above rules:

1. PS image is uncropped and has a default paper size to A4.

**Comment by PaulWessel** [comment]
we are going to get so many emails about why their PNG plot has so much whitespace around it - only to eventually learn they had some old gmt.conf laying around from a classic gmt command and once they deleted it everything worked again.  I think it is better to insist that we always crop, regardless of begin -C or now, UNLESS the user actively turns off cropping.  Since we have A+n already for that purpose, why not use that in those rare cases when media cropping is desired - this is the solution I am working on.

**Comment by seisman** [comment]
OK, fair enough.
