### ISSUE TITLE
Include from src directory during build incorrectly assumes the src directory is next to build

### ISSUE THREAD

**Issue by remkos** [GenericMappingTools/gmt#4740]
**Description of the problem**

build/doc/rst/source/devdocs/long_options.rst includes this line
```
.. literalinclude:: ../../../../../src/gmt_common_longoptions.h
```
This assumes that the src directory is next to build, but that is a wrong assumption.
In my case, I have ~/gmt/master/src but ~/gmt6/build.
Since I can put the build directory anywhere, and many build systems do, this literalinclude simply does not work.

One way to circumvent is to copy gmt_common_longoptions.h into the build/src directory and then use
```
.. literalinclude:: ../../../src/gmt_common_longoptions.h
```

Same for src/blockmean.c which is included in long_options.rst as well.

**Full script that generated the error**

```
make -j8 all docs_man docs_html install
```

**Full error message**

```
[100%] Building manpages...
~/gmt6/build/doc/rst/source/devdocs/long_options.rst:109: WARNING: Include file '~/gmt6/src/gmt_common_longoptions.h' not found or reading it failed
~/gmt6/build/doc/rst/source/devdocs/long_options.rst:124: WARNING: Include file '~/gmt6/src/blockmean.c' not found or reading it failed
```

**System information**

* Operating system: Mac OS 11.1
* GMT version (`gmt --version`): 6.2.0_b7eaa8f_2021.01.29

**Comment by joa-quim** [comment]
I had seen those warnings too and wondered wtf is ``blockmean.c`` doing here? The file has > 600 lines, are we including it in the docs?

**Comment by seisman** [comment]
> The file has > 600 lines, are we including it in the docs?

@PaulWessel included a few lines of the C source codes into the documentation to show how long-option works (see https://docs.generic-mapping-tools.org/dev/devdocs/long_options.html).

**Comment by PaulWessel** [comment]
No 600 lines are include, just a handful:

```
.. literalinclude:: ../../../../../src/blockmean.c
    :language: C
    :lines: 44-52

```

yes, we do want to do this.  @seisman may perhaps know how to do this in CMake?

**Comment by remkos** [comment]
Superfast! 👍
