### ISSUE TITLE
Bug in Animation 9? Plot text with Events

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4742]
When I run the animation 09 I get an error related to the following command.

`gmt events -Rg MOR_names.txt -L100 -Et+r6+f6 -T\${MOVIE_FRAME} -F+f12p,Helvetica-Bold,yellow`

`events [ERROR]: Must specify either -A or -S.`

**Comment by PaulWessel** [comment]
Ah yes.  So the ability to handle lines and polygons was added (-A) and now this attempt to just plot labels fails.  I can fix this since -Et is the only one given (not -Es).

**Comment by Esteban82** [comment]
Ok, thanks @PaulWessel. BTW I just want to plot text in an animation (the name of a volcano when it erupts). I hope this would worked.
