### ISSUE TITLE
Bug in -SE- without border?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4750]
I want to plot the symbol -SE- without border but I can't. I think it is bug. I make a frame with the following commands 
```
	gmt events q.txt -Scp -Cq.cpt --TIME_UNIT=o -T\${MOVIE_COL0} -Es+r2+d6 -Ms3+c0.5 -Mi1+c0.5 -Mt+c0
	gmt events q.txt -SE- -Cq.cpt --TIME_UNIT=o -T\${MOVIE_COL0} -Es+r2+d6 -Ms3+c0.5 -Mi1+c0.5 -Mt+c0
```
I get this figure. The greater circles without border are done with -Scp. The smaller one with -SE-

![EJ24 2_Anim_Mapa_ARG_Sismicidad_Vulcanismo_prueba3](https://user-images.githubusercontent.com/17908951/106967914-acc5e280-6726-11eb-88a1-e78d86a15772.png)

**Comment by PaulWessel** [comment]
OK, will check.

**Comment by PaulWessel** [comment]
I can confirm the bug.
