### ISSUE TITLE
Have EPS custom symbols in decorated lines

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#4755]
**Description of the desired feature**

I'm a heavy user of `-S~:+i+sk` (Thank you again, @PaulWessel!) with custom symbols written [the GMT way](https://docs.generic-mapping-tools.org/latest/cookbook/custom-symbols.html#macro-commands). I just learnt that one awesome feature of `plot -Sk` doesn't work: I can't use an EPS custom symbol with `-S~`:

`plot [ERROR]: Cannot use EPS custom symbol in the decorated line specification: circle_star`

When my symbols get a bit complicated (more curved lines than I'm willing to calculate the parameters for, parts of an ellipsoid or similar), and no logic is required in the symbol, I like to take the lazy route via an EPS custom symbol. 

Therefore I'd greatly appreciate if you could kindly make EPS custom symbols usable in decorated lines. 

_Some code to play with:_

```
cat > path1.txt << END
-1.5 -1
 0    1
 1.5  1.2
END

gmt begin eps_symbol_line
  gmt basemap -R-2/2/-2/2 -JM6i -Bafg1
  gmt plot path1.txt -W4p,black,8_4
  gmt plot path1.txt -S~n1:+i+skcircle_star/2c
gmt end show
```

[Download circle_star.eps.zip](https://github.com/GenericMappingTools/gmt/files/5935747/circle_star.eps.zip) (~1 KB, just a quick'n'dirty example for an EPS symbol)

**Comment by PaulWessel** [comment]
You know my weakness well, @KristofKoch...
I have a plan to make the EPS symbol just another item that a custom symbol can place, e.g.,

_x y size name_ **i**   # Place an EPS file

This is needed so that the decorated symbol machinery can rotate the EPS plot as it does with the other symbols.

**Comment by KristofKoch** [comment]
I support your plan @PaulWessel – and that rotate functionality will be greatly appreciated outside `-S~` as well … would some air displacement in a certain glass help?

**Comment by KristofKoch** [comment]
… I assume you are aware of this but just a quick heads up: `i` is already [used for the inverted triangle](https://docs.generic-mapping-tools.org/dev/cookbook/custom-symbols.html) so are `e` and `s`. If you want to stick to lower case `p` would be available.

**Comment by PaulWessel** [comment]
Yes, moving along with I for insert PS but this can still change of course, including 'p'.

**Comment by KristofKoch** [comment]
Hi @PaulWessel, I'd like to point out that with the font currently used here and in the docs the letters uppercase I (`I`) and lowercase l (`l`) look almost identical and might be a source for user-error.

**Comment by PaulWessel** [comment]
Yes, I suppose p is better.

**Comment by PaulWessel** [comment]
Well, p stands for point and is one of the allowed common symbols.  I  think capital P works.
