### ISSUE TITLE
Standardize on a maximum usage message width

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4762]
**Description of the desired feature**

When you type gmt module you get the usage message.  These vary in character length and some are really long, probably wrapping around on most people's laptop and making it harder to read.  A quick script made this histogram of these lengths:

![hist](https://user-images.githubusercontent.com/26473567/107159755-2c75cc00-6936-11eb-9a65-abed254cc231.png)

I think we should

1. Decide on a maximum width for these (100 characters, 120?)
2. Go through all usage messages and do the manual wrapping
3. This is a chore than almost anyone can help with so we can ask for volunteers.

**Comment by KristofKoch** [comment]
Default terminal size is 80 x 24 characters. Why not stick to this size? Yes, more work (lots of red east of 80 …). But I'd volunteer. Where the 80 x 24 comes from? This size is seemingly dating back to IBM punched cards. 

Another note about ideal line length and characters per line:

> Generally for printed text it is widely accepted that line length fall between 45–75 characters per line (cpl), though the ideal is 66 cpl (including letters and spaces).

_Bringhurst, R. (1992). Horizontal Motion. The Elements of Typographic Style, pp 25-36. Point Roberts, WA: Hartley & Marks._

**Comment by PaulWessel** [comment]
Those are good points, @KristofKoch.  My vote should count very little on this since I have a 42 inch 4K TV as may monitor and my terminals are not 80x24!

**Comment by joa-quim** [comment]
110-120 chars. Remember that the listings do not start at 0 but at several <tabs> long. For example the longest line in the image is at position 105 and that on a Windows terminal with "thick" chars.

I never agreed with those very short widths defended with arguments on human perception, comfort of reading etc. This not about relaxed reading a novel but about (repeatedly) reading a couple of lines in order to understand a certain point. And now all command windows can be enlarged to not produce an excessive line wrapping.

![image](https://user-images.githubusercontent.com/537321/107162567-14d12e80-699c-11eb-9743-eab430b91371.png)

**Comment by KristofKoch** [comment]
That's a really nice setup! When I put two terminals adjacent to each other I can go 92 characters wide on each.  I don't have a 42" monitor though … Maybe that 80 count isn't so bad after all? 

If you accept me for doing this job I'd appreciate some guidance on where to find the messages, @PaulWessel.

**Comment by KristofKoch** [comment]
For those working in a single window 100-120 might be a good choice, I like to work with several windows simultaneously and prefer therefore my smaller very personal <92 char width limit.

Would it hurt you to have an 80 char line length @joa-quim? Would impede readability/information ingestion?

**Comment by seisman** [comment]
Some options are pretty long, for example, **gmt coast -L**:
```
gmt coast -                                                                                                                                                                                        63 ↵
gmt coast [core] 6.2.0_36c8106_2021.02.05 [64-bit] - Plot continents, countries, shorelines, rivers, and borders

usage: gmt coast -J<args> [-A<min_area>[/<min_level>/<max_level>][+a[g|i][s|S]][+r|l][+p<percent>]] [-B<args>]
	[-R<west>/<east>/<south>/<north>[/<zmin>/<zmax>][+r]] [-C<fill>[+l|r]]
	[-D<resolution>][+f] [-E<code1,code2,...>[+l|L][+g<fill>][+p<pen>][+z]] [-G[<fill>]]
	[-F[+c<clearance(s)>][+g<fill>][+i[[<gap>/]<pen>]][+p[<pen>]][+r[<radius>]][+s[<dx>/<dy>/][<fill>]]]
	[-I<feature>[/<pen>]]
	[-L[g|j|J|n|x]<refpoint>+w<length>[e|f|M|n|k|u][+a<align>][+c[[<slon>/]<slat>]][+f][+j<justify>][+l[<label>]][+o<dx>[/<dy>]][+u]]
	[-M] [-N<feature>[/<pen>]] [-Q] [-S[<fill>]]
	[-Td[g|j|J|n|x]<refpoint>+w<width>[+f[<level>]][+j<justify>][+l<w,e,s,n>][+o<dx>[/<dy>]]]
	[-Tm[g|j|J|n|x]<refpoint>+w<width>[+d[<dec>[/<dlabel>]]][+i<pen>][+j<justify>][+l<w,e,s,n>][+p<pen>][+t<ints>][+o<dx>[/<dy>]]]
	[-U[<label>][+c][+j<just>][+o<dx>/<dy>]] [-V[<level>]] [-W[<feature>/][<pen>]]
	[-X[a|c|f|r]<xshift>] [-Y[a|c|f|r]<yshift>] [-bo[<ncol>][t][w][+l|b]] [-c[<row>,<col>|<index>]] [-do<nodata>]
	[-p[x|y|z]<azim>[/<elev>[/<zlevel>]][+w<lon0>/<lat0>[/<z0>][+v<x0>/<y0>]] [-t<transp>[/<transp2>[+f|s]] [-:[i|o]] [--PAR=<value>]
```

**Comment by joa-quim** [comment]
On a laptop I have normally about 20 windows open ... just not all at same time 😄 
Honestly, I think 80 chars is too short. Remember that with the tabs we are talking on  some 65-70 chars.
A side effect of making lines short is that it makes the message longer and then we must scroll more more.

The synopsis messages are somewhat different. They are really concentrated info and would gain with shorter lines. But it's a very difficult task. Many of those options are macronized (made with macros) and we don't exactly know their length. There are others that are very long by themselves and cannot  e broken. But yes, synopsis is where line length reduction is more needed.

**Comment by PaulWessel** [comment]
For the synopsis we could determine the longest individual option (e.g., -L in coast, -D in others) plus the tabs.  We clearly cannot go shorter than that.  Because we want the synopsis to be alphabetical within requires and optional settings, there will be liens that will have to be oddly short so that a very long option can be by itself on the next line.

**Comment by PaulWessel** [comment]
Thanks @joa-quim that just came in after I hit submit.  So I think that sets the length at least for coast.  Not sure if we must keep the same length (130) everywhere because of this case though.

**Comment by PaulWessel** [comment]
The -Tm can be shorted a small bit by using a shorter word for refpoint, remove the d in dlabel, and ???

**Comment by joa-quim** [comment]
Yep, *refpoint* may become *refpt* and then
```
	[-L[g|j|J|n|x]<refpt>+w<length>[e|f|M|n|k|u][+a<align>][+c[[<slon>/]<slat>]][+f][+j<justify>][+l[<label>]][+o<dx>[/<dy>]][+u]]
```
will become ... 130 chars (with 4-chars tabs)

**Comment by KristofKoch** [comment]
What about using 

⏎ U+23CE RETURN SYMBOL

to indicate a line break and allow for shorter lines?

**Comment by KristofKoch** [comment]
@joa-quim's example in 80 chars wide:

````
    [-L[g|j|J|n|x]<refpt>+w<length>[e|f|M|n|k|u][+a<align>] ⏎
        [+c[[<slon>/]<slat>]][+f][+j<justify>][+l[<label>]][+o<dx>[/<dy>]][+u]]
````

**Comment by PaulWessel** [comment]
That is not bad-looking but how do you print that character to a dumb ascii terminal?

**Comment by KristofKoch** [comment]
Ok, caveat: Terminal needs to be UTF-8 enabled for it to work.  You can write it directly or via the equivalent hex code.

```
$ echo -e "⏎"
⏎
$ echo -e "⏎" | hexdump -C
00000000  e2 8f 8e 0a                                       |....|
00000004
$ echo -e "\xe2\x8f\x8e"
⏎
$
```

The hex-code version is the most reliable across different shells. So I read. Can't speak for non-*nix shells.

**Comment by PaulWessel** [comment]
I tried this, as probably what we do in GMT:

```
#include <stdio.h>
#define GMT_LF "\xe2\x8f\x8e\n"
int main () {

	fprintf (stderr, "\tTrying to break the line with fancy return%s\tand continuing on\n", GMT_LF);
}
```

It worked fine macOS terminal but not in an X11 xterm (not that I care, but).  See what happens in basic Linux and Window terminals.  Just call the above lf.c, `cc lf.c -o lf` and run lf.

**Comment by joa-quim** [comment]
```
C:\v>lf
        Trying to break the line with fancy returnΓÅÄ
        and continuing on
```
This from the Windows Terminal that supports unicode.

**Comment by PaulWessel** [comment]
OK, so just as sad as X11 xterm then.
Change that GMT_LF into the unicode code and see how that goes.

**Comment by joa-quim** [comment]
Note I couldn't make ``echo -e "\xe2\x8f\x8e"`` work in WSL neither. It only worked in git bash. We better forget this

**Comment by KristofKoch** [comment]
Ok, too bad. That idea was supposed to make things easier …

**Comment by joa-quim** [comment]
But even without the symbol I think with the indentation it should pretty obvious that's a continuation line.

**Comment by KristofKoch** [comment]
So max width 80 chars and multi line options get an additional indentation?

**Comment by PaulWessel** [comment]
I wonder if there is a way to programmatically determine if the terminal is lame or UTF-8 enabled.  if so then we could set GMT_LF accordinly (with or without fancy symbol).

**Comment by PaulWessel** [comment]
I guess no go.  WHile git bash can do utf-8 you have to configure, so we would get lots of complaints from people with unconfigured terminals... https://stackoverflow.com/questions/10651975/unicode-utf-8-with-git-bash

**Comment by seisman** [comment]
Manpages of `gawk` and others also have very long lines, even longer than GMT.

**Comment by PaulWessel** [comment]
This will be a good chunk of work.  All the common options is simply editing gmt_init for the explain_options section.  Some common but no GMT_common options like -D, -F for refpoints and panels are also in gmt_init.c. Then there is the 150 modules with their own options to look at.  I do not see a simple way to programmatically do this... or do I?  Maybe, if instead of using GMT_Message we used another that did the line-wrapping for us given a setting.  We would still have to edit things like

```
GMT_Message (API, GMT_TIME_NONE, "\t-T Toggle header from grid-line to pixel-registered grid or vice versa.\n");
GMT_Message (API, GMT_TIME_NONE, "\t   This shrinks -R by 0.5*{dx,dy} going from pixel to grid-line registration\n");
GMT_Message (API, GMT_TIME_NONE, "\t   and expands  -R by 0.5*{dx,dy} going from grid-line to pixel registration.\n");
GMT_Message (API, GMT_TIME_NONE, "\t   No grid values will be changed (a non-destructive change to the grid).\n");

```
to

`GMT_Wrap (API, GMT_TIME_NONE, "\t-T Toggle header from grid-line to pixel-registered grid or vice versa. This shrinks -R by 0.5*{dx,dy} going from pixel to grid-line registration and expands  -R by 0.5*{dx,dy} going from grid-line to pixel registration. No grid values will be changed (a non-destructive change to the grid).\n");`

and let GMT_Wrap do what it can to make this even and pretty given a max length.  It would know about tab indentation.
