### ISSUE TITLE
Coding styles and code formatting

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#477]
With more people contributing to the GMT codes, it's necessary to define coding styles for the GMT projects to helps maintain consistent coding styles for multiple contributors across various editors and IDEs.

For example, I prefer spaces for indentation while GMT uses tabs. So I need to convert spaces to tabs before committing my codes to keep the consistence. Sometimes, I forgot to do the conversion before committing my codes, making GMT codes mixing tabs and spaces (sorry for that).

We may use some tools (e.g. `clang-format`) to define our coding styles and automatically format the GMT codes.

**Comment by leouieda** [comment]
I usually like the auto-formatting route because it takes the burden off of our shoulders. It really sucks when you commit a file only to realize that your editor auto-converted all the tabs to spaces and your diff is the whole file.

**Comment by PaulWessel** [comment]
I prefer tabs to indicate indent.  The editor can be set to translate that into any number of spaces.  You cannot go the other way (have the editor know that your # of spaces is a tab for indent).  I think we are consistently using tabs across GMT and I fix stuff when I notice spaces.

**Comment by PaulWessel** [comment]
A related issue is the length of a line. Apparently, some people (I am looking at you, @joa-quim) have monitors that are less than 40 inches and thus will break a tiny 200-character line into two lines, sometimes with the backslash.  Why am I buying 40" SamSung 4K TVs as monitors if people are cramping my style and forcing 80-character punchcard widths on me?

**Comment by seisman** [comment]
I agree that it's unnecessary to force the line length to <=80 characters for GMT. 

Clang-format won't break the input long lines if the option `ColumnLimit` is 0.

See https://clang.llvm.org/docs/ClangFormatStyleOptions.html for all clang-format's options.

**Comment by joa-quim** [comment]
@seisman don't believe in all you read here. No one is defending a 80 chars limit, not even 92 (which probably covers all that other code standards defend). But there should be a limit well behind 200 chars. Specially if they are used to write code with
```
for() ...; for() ...; if () ...
```
instructions in a single line.
I think something between 120 and 130 is ok. Unfortunately we still have many lines longer than this. (the fig trims at 200 but there several that go beyond 300).

![histo_LL](https://user-images.githubusercontent.com/537321/54879695-e0017000-4e33-11e9-91c6-a167ffb31603.png)

**Comment by joa-quim** [comment]
Actually our code lines are way longer because the script that counted their lengths counted tabs as one char only.

**Comment by PaulWessel** [comment]
Love it!  Could we get a plot via git blame that shows who is responsible for those long lines, say over 120? Also a nice spike at 80 characters. Are you counting the PS files also?

**Comment by PaulWessel** [comment]
A tab is a single character (ASCII code 9).

**Comment by joa-quim** [comment]
Don’t know how to do that. The spike at 80 is surprising indeed. 
Counted only the *.c files. 

Sent from my iDedo

No dia 24/03/2019, às 19:28, Paul Wessel <notifications@github.com> escreveu:

**Comment by joa-quim** [comment]
Don't understand why this didn't show up. I saw it in Lisbon. Updated version with tabs counted as 4 spaces.

![histo_LL](https://user-images.githubusercontent.com/537321/54885130-ea8e2a80-4e70-11e9-8a6e-5e74bf617aad.png)
