### ISSUE TITLE
BATCH (path to gmt.conf and outputs)

### ISSUE THREAD

**Issue by delaviel-anger** [GenericMappingTools/gmt#4779]
> 6.2beta on macOS Big Sur

I'm currently trying to implement a script with [`gmt batch`](https://forum.generic-mapping-tools.org/t/question-using-gmt-batch/1320/11).

Among all the mistake I can make, I noticed that `gmt.conf` was not accessed
1. working dir with script
   2. subfolder batch (with `batch_*` + sub-subfolder per plot)
      3. sub-subfolder with plots

When created from `-Ivariable.sh` or `-Sbpre.sh` gmt.conf is located in (2) and not accessible by (3) where the plot is done.

```
gmt get TIME_EPOCH
1970-01-01
[...]
cp ../gmt.conf ./
gmt get TIME_EPOCH
1980-01-01
```

**Comment by PaulWessel** [comment]
The contents of those scripts are not _scanned_ to see what is going on, so **batch** does not know that you created a gmt.conf in the top directory.  While data files created there become available to the job scripts via the **DIR_DATA** variable, there is no mechanism to read gmt.conf files from other places than ~, ~/.gmt, and current directory.  I think the solution is to determine if a gmt.conf file exists in the top directory, and if it does then, as you show, we can insert a `cp ../gmt.conf . `command into the job script.  This probably applies to **movie** as well.

**Comment by meghanrjones** [comment]
Another solution rather than tracking directories and copying gmt.conf files would be to use the *pending* themes implementation and add an examples to the relevant docs for how to control settings for batch processing and movies.

**Comment by PaulWessel** [comment]
I think perhaps both can be needed.  IT should be allowed for a user to have a preferred gmt.conf, or have the preflight script assemble one, and that it should be used by the batch or movie scripts.  To do so requires that file to be placed in the subdirectory used by each parallel job I think.

**Comment by delaviel-anger** [comment]
@PaulWessel : another problem I found [see forum](https://forum.generic-mapping-tools.org/t/question-using-gmt-batch/1320/15?u=planetgus)

**Comment by PaulWessel** [comment]
BTW, I see no problem with pre.sh creating a CPT with makecpt -H > name.cpt and then the jobs using -Cname.cpt in commands.  Works fine for me.  You cannot use ../name.cpt though, just name.cpt.

**Comment by delaviel-anger** [comment]
What do you mean ?

my CPT is created in `pre.sh` then called with `-C'../colr.cpt'` in `main.sh`.

If I write '-Ccolr.cpt' is doesn't work

**Comment by PaulWessel** [comment]
That works for me.  Try this example.  It is modified from the example on the batch man page to add making plots in main that use the CPT created in pre.s

```
cat << EOF > pre.sh
gmt begin
    gmt math -o0 -T50/200/50 T = widths.txt
    gmt grdcut -R-10/20/-10/20 @earth_relief_02m -Gdata.grd
    gmt makecpt -Cpolar -T-1000/1000 -H > junk.cpt
gmt end
EOF
cat << EOF > main.sh
gmt begin \${BATCH_NAME} pdf
    gmt grdfilter data.grd -Fg\${BATCH_COL0}+h -G\${BATCH_NAME}.grd -D2
    gmt grdimage \${BATCH_NAME}.grd -B -B+t"Width \${BATCH_COL0}" -Cjunk.cpt
gmt end show
EOF
cat << EOF > post.sh
gmt begin \${BATCH_PREFIX} pdf
    gmt grdmath \${BATCH_PREFIX}_*.grd -S STD = \${BATCH_PREFIX}_std.grd
    gmt grdimage \${BATCH_PREFIX}_std.grd -B -B+t"STD of Gaussians residuals" -Chot
    gmt coast -Wthin,white
gmt end show
EOF
gmt batch main.sh -Sbpre.sh -Sfpost.sh -Twidths.txt -Nfilter -V -Z
```

**Comment by delaviel-anger** [comment]
Hum .. both work actually

**Comment by delaviel-anger** [comment]
Another "subtlety" I guess : 

I just used 
```
gmt batch main_alone.sh -Sbpre_alone.sh -Sfpost_alone.sh -Nalone -Wplots/batch -Ttimes_absolute.txt -Iinclude_alone.sh -Z
```
where all *sh files are actual files (not created through EOF). The -Z option delete them as one would expect (so better be careful with this flag). 
However, the subfolder created with -N*prefix* or -W*path* isn't.

**Comment by PaulWessel** [comment]
Closing this as fixed by PR.
