### ISSUE TITLE
Bug in grdinfo -RCountryCode -I -D for southern hemisphere countries

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4789]
I run this code to get the region of Ecuador by sub-region of 4x4

`gmt grdinfo -REC+r1 -D0 -I4`
 
and I get this answer:
```
-R267/271/-5/**359**
-R271/275/-5/**359**
-R275/279/-5/**359**
-R279/283/-5/**359**
-R267/271/-1/3
-R271/275/-1/3
-R275/279/-1/3
-R279/283/-1/3

```
As you can see, for the northern border has no sense when is a negative value (360 is added but it is a latitude). The same happened with all other southern countries that I try.

gmt Version 6.2.0_217ff38-dirty_2021.02.10

**Comment by joa-quim** [comment]
Hmm, works well here in Win and WSL
```
gmt grdinfo -REC -D0 -I4
-R267.989227/271.989227/-4.998823/359.001177
-R271.989227/275.989227/-4.998823/359.001177
-R275.989227/279.989227/-4.998823/359.001177
-R279.989227/283.989227/-4.998823/359.001177
-R267.989227/271.989227/-0.998823/3.001177
-R271.989227/275.989227/-0.998823/3.001177
-R275.989227/279.989227/-0.998823/3.001177
-R279.989227/283.989227/-0.998823/3.001177
```

**Comment by joa-quim** [comment]
Sorry, you're right. Only payed attention to the **

**Comment by PaulWessel** [comment]
Funny one.  If @joa-quim cannot figure it out then I can later today - meetings coming up...
