### ISSUE TITLE
Oblique Mercator -JOa doesn't work north of 83N

### ISSUE THREAD

**Issue by rhagen77** [GenericMappingTools/gmt#4798]
**Description of the problem**
Oblique Mercator -JOa works correctly at 83N, but not at 84N

**Full script that generated the error**
This command works at 83N:
gmt basemap -R-200/200/-200/200+uk -JOa8/83/46/4i -B2g2 -T8/83/3c -png test83N
But it doesn't work at 84N
gmt basemap -R-200/200/-200/200+uk -JOa8/84/46/4i -B2g2 -T8/84/3c -png test84N

**Actual outcome**
![test83N](https://user-images.githubusercontent.com/78966154/107776980-420d3c00-6d10-11eb-8458-6ab981a8d6e4.png)

![test84N](https://user-images.githubusercontent.com/78966154/107777035-50f3ee80-6d10-11eb-9977-f76738acb2e5.png)

* Operating system: MacOS 10.14.6
* GMT version (`gmt --version`): 6.1.1

**Comment by PaulWessel** [comment]
I am reminded of what John Mutter at Lamont told us students back in the day: "Never work at latitudes that exceed your IQ".  I have thus stayed south of 60N - I think you are taking chances here, @rhagen77.

**Comment by rhagen77** [comment]
I better go back to working in the tropics then.
