### ISSUE TITLE
gmtlib_free_cpt_ptr() may crash from externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4799]
When it calls ``gmtsupport_free_range()`` the line
```
gmt_M_str_free (S->label);
```
crash if ``S->label`` points into a memory hold by an external. Curiously, there is no equivalent free for ``S->key`` so Categorical CPTs can be set from externals as long as they don't set the "label" too.

**Comment by PaulWessel** [comment]
Could you put this in context.  You are creating a CPT in Julia and passing it via -C or similar?  Who owns the GMT_PALLETE structure?

**Comment by joa-quim** [comment]
Yes, from Julia but see ``gmtmex_palette_init()``. We are are not setting the *key* and *label* there. If we were, we would have a Matlab owned memory string and the crash would occur when GMT tried to free that memory.
In Matlab, since we are dealing with C only we could do some strdup and pass a GMT owned memory but from Julia I don't see how to do the same trick, so memory passed in is owned by Julia.

**Comment by PaulWessel** [comment]
If you are creating the CPT via GMT_Create_Data in Julia then it should have a flag that we can use to not free stuff in GMT.  That is how we dont free other things passed in like matrices and tables.  Help me understand.  You use GMT_Create_Data then do a virtualfile open on it and pass that string via -C?

**Comment by joa-quim** [comment]
Let me commit (and wait for tests to run) what I have to show how it works.

**Comment by joa-quim** [comment]
OK, see function https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L1049
Read it as a mix of C and Matlab. At line https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L1101
I create a ``GMT_LUT`` structure in Julia and pass it as a pointer to the ``P``, struct created and owned by GMT.
The issue is that I must fill the *key* and *label* fields of this structure and what I have is only Julia owned strings (that are converted to pointers) and passed to GMT.

Shit this is getting complicated. I do have access to P.data (the line that read ``glut = unsafe_load(Pb.data, j)``) but GMT could not have allocate the memory to hold the *key* and *label* so I cannot fill that memory but have instead to pass in a fully filled ``GMT_LUT`` struct ... and that's when  shit happens upon memory freeing.

**Comment by PaulWessel** [comment]
Seems like the underlying problem is for externals to set the key and label strings in a palette.  Perhaps we need to add a new API to allow that to happen so that GMT can properly own things.  At the most abstract, maybe allow

`int GMT_Put_Strings (void *V_API, unsigned int family, void *object, char **array);
`

to accept family as **GMT_IS_PALETTE** and use (new) bitflags **GMT_IS_KEY** or **GMT_IS_LABEL** to tell what the array should be used for.  This would mean you pass an array of character strings, one for each LUT entry, so that GMT_Put_Strings can duplicate these strings.

If you need to do this one by one then we could make something like 

```
GMT_Put_Key (API, P, index, string)
GMT_Put_Label (API, P, index, string)
```

but I would prefer the first solution.

**Comment by joa-quim** [comment]
First option seems cleaner (though I have the impression it will give me more work figuring out how to use it from Julia) but how would we use it? Like this?

```
GMT_Put_Strings (GMT->parent, GMT_IS_PALETTE | GMT_IS_KEY, P, keys);
GMT_Put_Strings (GMT->parent, GMT_IS_PALETTE | GMT_IS_LABEL, P, labels);
```

**Comment by PaulWessel** [comment]
Yes, exactly.  And I would loop over the color LUTs and for each check if array[index] == NULL else strdup.

**Comment by joa-quim** [comment]
OK then.

**Comment by PaulWessel** [comment]
Have a look at the new PR and I think you should be able to do 

```
GMT_Put_Strings (GMT->parent, GMT_IS_PALETTE | GMT_IS_PALETTE_KEY, P, keys);
GMT_Put_Strings (GMT->parent, GMT_IS_PALETTE | GMT_IS_PALETTE_LABEL, P, labels);
```

and no freeing will take place unless you also pass **GMT_IS_DUPLICATE** (then GMT makes its copies so it is allowed to free).

**Comment by joa-quim** [comment]
Ok, I'll start looking into this but you say in that PR that
>Note: GMT_Get_Strings does not yet accept GMT_IS_PALETTE since ...

**Comment by PaulWessel** [comment]
Do you need it though? I only did GMT_Put_Strings.

**Comment by PaulWessel** [comment]
_GMT_Get_Strings_ would only be useful if you need to get the key or label items back into an array in Julia for some reason, and I guess we would then allocate that array and the strings just with malloc and not GMT_memory and GMT would forget about it.  But I assume you actually though my comment was about _GMT_Put_Strings_?

**Comment by joa-quim** [comment]
Yes, sorry I was thinking in ``GMT_Put_Strings``. 
I must now find again how to send in **chars and deal with all those Julia types to C pointers conversion. Not fun.

**Comment by joa-quim** [comment]
Ok, I have it working now, so good to go. But this all started when I found that it was freeing the *label* array, but it does not free the *key* array, so it must be leaking.

**Comment by PaulWessel** [comment]
Are you sure? I updated the _gmtsupport_free_range_  function to free both:

```
GMT_LOCAL void gmtsupport_free_range  (struct GMT_CTRL *GMT, struct GMT_PALETTE_HIDDEN *H, struct GMT_LUT *S) {
	if (H->alloc_mode_text[GMT_CPT_INDEX_LBL]) gmt_M_str_free (S->label);
	if (H->alloc_mode_text[GMT_CPT_INDEX_KEY]) gmt_M_str_free (S->key);
	gmt_M_free (GMT, S->fill);
}
```

**Comment by joa-quim** [comment]
Ah, sorry. Had missed that.

**Comment by PaulWessel** [comment]
Closing now that #4801 has been merged.
