### ISSUE TITLE
Custom grid lines may be drawn outside the figure

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#480]
This code
```
echo "-0.1 g
0.5 g
1.1 g
1.2 g
" >ints

gmt psbasemap -R0/1/0/1 -JX10c -Bxcints -Bycints -Bswne -P >gtest.eps
```
generates this picture
![gtest](https://user-images.githubusercontent.com/5275343/53851281-fcb34080-4009-11e9-8991-9a790806edae.png)

You can see grid lines outside of frame.

**Comment by PaulWessel** [comment]
Thanks @uleysky, yes we have no defense against this.  Will have a look.
