### ISSUE TITLE
Update formatting for input values to gmt.conf parameters in documentation

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4820]
**Description of the problem**

In most of the [gmt.conf documentation](https://docs.generic-mapping-tools.org/dev/gmt.conf.html), the allowed (non-numeric) values for each parameter are **bolded**. There are some parameters that do not follow this convention. For example, in [GMT_EXTRAPOLATE_VAL](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-GMT_EXTRAPOLATE_VAL), 

> Choose among ‘NaN’, ‘extrap’ or ‘extrapval,val’ (without quotes)

 should be 

> choose among **NaN**, **extrap**, and **extrap**,*val*.

and in [GMT_INTERPOLATE](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-GMT_INTERPOLANT), 

> Determines if linear (linear), Akima’s spline (akima), natural cubic spline (cubic) or no interpolation (none) should be used for 1-D interpolations in various programs [akima].

should be

> Determines if linear (**linear**), Akima’s spline (**akima**), natural cubic spline (**cubic**) or no interpolation (**none**) should be used for 1-D interpolations in various programs [**akima**].

**Comment by meghanrjones** [comment]
This would be a really good first issue if anyone's interested in reviewing the [gmt.conf documentation](https://docs.generic-mapping-tools.org/dev/gmt.conf.html) (just comment here that you'd like to work on it). The needed resources are in the [restructuredText Cheatsheet](https://docs.generic-mapping-tools.org/dev/rst-cheatsheet.html) and the [contributing guide](https://github.com/GenericMappingTools/gmt/blob/master/CONTRIBUTING.md) (and questions are welcome).

**Comment by gd-a** [comment]
started
