### ISSUE TITLE
Recent changes (maybe #4813) break some tests on Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#4821]
Recent changes (maybe #4813) break some tests on Windows:
```
The following tests FAILED:
	124 - doc/scripts/GMT_movie_progress.sh (Failed)
	234 - doc/examples/anim01/anim01.sh (Failed)
	235 - doc/examples/anim02/anim02.sh (Failed)
	236 - doc/examples/anim03/anim03.sh (Failed)
	237 - doc/examples/anim04/anim04.sh (Failed)
	238 - doc/examples/anim05/anim05.sh (Failed)
	485 - test/grdmath/daynight.sh (Failed)
	575 - test/movie/PS_layers.sh (Failed)
	576 - test/movie/movie_indicator_de.sh (Failed)
	577 - test/movie/movie_indicator_f_hor.sh (Failed)
	578 - test/movie/movie_indicator_f_ver.sh (Failed)
Errors while running CTest
	618 - test/psbasemap/JOb_pole.sh (Failed)
```

The error messages are:
```
 1/19 Test  #124: doc/scripts/GMT_movie_progress.sh .....***Failed   13.60 sec
Set GMT_SESSION_NAME = 48886
cp: cannot stat 'D:agmtgmtbuilddocscriptsGMT_movie_progressgmt.conf': No such file or directory
ERROR: D:/a/gmt/gmt/build/test/gmtest:210
memtrack errors: 0
exit status: 1
```

**Comment by PaulWessel** [comment]
Hopeing someone can run these manually on a local Windows system and see what is happening.

**Comment by Squadzone** [comment]
@PaulWessel 

can you take a look this
https://github.com/Squadzone/gmt/commit/e58ecd6fbc03801e93d196d1cafc098ec3f95dcc

**Comment by joa-quim** [comment]
We are aware of that. When time allows.  

Sent from my iDedo

**Comment by PaulWessel** [comment]
@joa-quim, what should I do with this one? The ifdef applies to the Win executables and I guess the issue is that these can be run from cmd or git bash and there should be a different behavior?

**Comment by joa-quim** [comment]
I may have a clue. The error message says **cp:** ``cannot stat`` but on **cmd** it's **copy**, not **cp**. But because the script is run from bash, the **cp** command exists but does not recognize the backslash as a file separator.

**Comment by PaulWessel** [comment]
Right. here is what I think is happening: A user is using the GMT Windows executables.  These have various #ifdef WIN32 branches that compiles in certain behavior.  Some of these related to path separators.  However, these binaries may be used in either git bash or cmd.  When used in git bash we should presumably issue bash system commands and not match commands, whereas if run in cmd batch it is the opposite.  Note, this is pretty much just limited to movie and batch where there are scripts written and system calls issued.
FOr batch and movie, the key thing is the input scripts.  If they are bash scripts then everything movie/batch do should be done assuming system will execute a bash script properly.  If input is a batch file then we write batch files and run things that way.
So the solution is to decide on any path formats based on the current script language mode and NOT place those under any if-defs.

**Comment by joa-quim** [comment]
Yes, I agree that's how it looks it should work.

**Comment by PaulWessel** [comment]
Thanks.  I am fixing those runtime decisions.  The only remaining ifdef I have now is this block which I thought I'd show you:

```
#ifdef WIN32
	if (Ctrl->In.mode < GMT_DOS_MODE)		/* A bash or csh run from Windows. Need to call via "start" to get parallel */
		sprintf (cmd, "start /B %s %s %*.*d", sc_call[Ctrl->In.mode], script_file, precision, precision, frame);
	else						/* Running batch, so no need for the above trick */
		sprintf (cmd, "%s %s %*.*d &", sc_call[Ctrl->In.mode], script_file, precision, precision, frame);
#else		/* Regular Linux/macOS shell behavior */
	sprintf (cmd, "%s %s %*.*d &", sc_call[Ctrl->In.mode], script_file, precision, precision, frame);
#endif
```

So this says that if you use the windows movie binary to run bash or csh scripts, we need to launch those scripts like this via system:

`start /B bash movie_master.sh 001`

to get them run in the background.  I guess this is still correct? While if you are using DOS batch files it becomes

`start /B movie_master.bat 001 &`

Does the & make sense here in a DOS call?  I guess it must since I know you at least tried to globe.bat example successfully.

**Comment by joa-quim** [comment]
Kindof forgot all about it but I'm not sure ``&`` works on batch. I see that we have several of this in movie.c
```
if (Ctrl->In.mode == GMT_DOS_MODE)	/* Needs to be "cmd /C" and not "start /B" to let it have time to finish */
```

**Comment by PaulWessel** [comment]
I will make a WIP branch of what I have now.  I will need your help to at least build on Win and run the globe bash and batch version on Windows with those binaries.  If we can get past that step then we can ask @Squadzone to test further, perhaps.

**Comment by PaulWessel** [comment]
Hopefully fixed by #4871

**Comment by PaulWessel** [comment]
Hopefully @seisman can update this issue if there are still lingering issues.

**Comment by seisman** [comment]
Have to wait for the CI reports.

**Comment by seisman** [comment]
Confirm that it was fixed.
