### ISSUE TITLE
Update format for default values in gmt.conf documentation

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4822]
**Description of the problem**

In the [gmt.conf documentation](https://docs.generic-mapping-tools.org/dev/gmt.conf.html), the default values are given in brackets [ ]. For most parameters, the brackets contain the default value (e.g., [pdf]) rather than stating "[default]" and there is no text preceding the default value (e.g., [pdf] rather than [default is pdf]). There are a few inconsistencies in the application of this convention. Here are a few examples:

[COLOR_MODEL](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-COLOR_MODEL) - add "[**none**]" to the end
[COLOR_SET](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-COLOR_SET) - change "[default, which is #0072BD,#D95319,#EDB120,#7E2F8E,#77AC30,#4DBEEE,#A2142F]" to "[#0072BD,#D95319,#EDB120,#7E2F8E,#77AC30,#4DBEEE,#A2142F]"
[GMT_EXTRAPLATE_VAL](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-GMT_EXTRAPOLATE_VAL) - change "[Default]" to "[**NaN**]"

**Comment by gd-a** [comment]
started

**Comment by gd-a** [comment]
Ok, I've "commit" changes to a certain point ... where it is and how do I push it to "pull request" ?

**Comment by meghanrjones** [comment]
Here's some instructions for the pull request workflow: https://www.asmeurer.com/git-workflow/.
