### ISSUE TITLE
Save/Show table data of a histogram with modern mode

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4830]
See #4829 for backgroud. 

Basically, how could I do the following with Modern Mode?

`gmt pshistogram @v3206_06.txt -T250 -Io > data.txt `

**Comment by joa-quim** [comment]
Honestly we should save Paul's time not getting him busy with things like this.

**Comment by Esteban82** [comment]
I agree. I am confort with the classic mode.

**Comment by joa-quim** [comment]
Besides, there are other cases
```
pscoast -M
psmask -D
...
```

**Comment by joa-quim** [comment]
So can we close it?

**Comment by Esteban82** [comment]
Ok. I will close it.
