### ISSUE TITLE
Political boundaries Japan/Korea

### ISSUE THREAD

**Issue by alextmartin** [GenericMappingTools/gmt#4835]
The dcw marks Ulleung Island off Korea's east coast in Japan's borders. The island is close to the Liancourt rocks, which is disputed territory, and Korea includes those rocks under the administration of the island, but Ulleung Island itself is not disputed.

* Windows
* gmt -- 6.1

**Comment by joa-quim** [comment]
Honestly, we (well, me but likely the other developers) don't know what you are talking about. We don't interfere with countries disputes (there are several). So maybe we should close this issue that clearly is not a GMT bug.

**Comment by alextmartin** [comment]
Sorry I was not very clear in the post. My point was that it is _not_ disputed, but may have an incorrect boundary because of the other nearby dispute. I recognize it is not a bug per se, but it is a problem for  those who work on Korean maps.

**Comment by joa-quim** [comment]
OK, but the point is we adopted a dataset that already came that way, so either someone will submit a pull request with a fix or it likely risks to stay as it is. Note that there is not even a map for us to see what is wrong.

**Comment by alextmartin** [comment]
![ulleung](https://user-images.githubusercontent.com/79380730/108643514-c02fb800-745f-11eb-8fa9-0d9d79cb8175.png)

I apologize for this report as it seems like this is not the forum for dealing with these issues. Under bugs on the coast module page it says to notify you of political boundaries that are out of date.

**Comment by alextmartin** [comment]
![image](https://user-images.githubusercontent.com/79380730/108644001-e3f3fd80-7461-11eb-901b-99bc6c97ab17.png)

I apologize since it seems this is not the forum to resolve this type of issue. Under bugs on the Coast Module page it asked that you be notified of incorrect political boundaries.
