### ISSUE TITLE
mfilter.sh test fails

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4839]
**Description of the problem**

test/filter1d/mfilter.sh currently fails. This is because it downloads this data file:
https://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/weekly/weekly_in_situ_co2_mlo.csv
which is updated monthly with new data.

Options for fixing the test:
1. Cache the data file so that the data do not change
2. Use **-q** to set the number of rows to read in
3. Update the postscript file

**System information**

* Operating system: macOS Big Sur
* GMT version (`gmt --version`): 6.2.0_1d2d6c8_2021.02.21

**Comment by PaulWessel** [comment]
It may be updated monthly but we are only plotting through 2018.  Are they changing the older values?

**Comment by meghanrjones** [comment]
Is the test failing for you? It is possible that it's something local for me, although I did search for stray gmt.conf files and the like.

**Comment by PaulWessel** [comment]
It fails. In the past they have done fun things like change the format or file name...

**Comment by meghanrjones** [comment]
OK, it also fails on older commits, so it is almost certainly due to a change in the file rather than anything internal to GMT. Is the purpose of using the USCD file to test the remote download mechanism in addition to filter1d?

**Comment by PaulWessel** [comment]
Yes, and to avoid adding too many files to the repo.

**Comment by PaulWessel** [comment]
Looks like they adjusted the data a tiny bit so I think I just update the PS.

**Comment by seisman** [comment]
I think the issue has been fixed. Closing.
