### ISSUE TITLE
Bug in Movie with master frame and ${MOVIE_NAME}

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4842]
I make a movie with the following commands which selects data based on a sub-region and extracts and plots the info from each one. 

```
cat << EOF > main.sh
gmt begin

#	Seleccionar Datos
	gmt select "Az_Pendientes.txt" \${MOVIE_TEXT} -o2,3 -fg > "temp_rumbo" -bi4f -bof
	gmt rose "temp_rumbo" -bi2f -D -T -I > q.txt
	gmt info \${MOVIE_NAME}/q.txt -C -I1 -o0 > N
	gmt text N -R1/10/1/10 -JX10 -F+cTL -Ya0.375c
	
gmt end
EOF

gmt movie main.sh -Sbpre.sh -C11.8cx11.8cx60 -TSR.txt -N$title -H2 -Fmp4 -D12 -M0,png -Z -Vi
```
It works fine for all the frames except for the mater one where I get this error: 

`gmtinfo [ERROR]: Cannot find file Lineamientos_Movie_Subregiones_bug_00/q.txt`

I think that the problem is that the folder and the file are created after the master frame. 

* GMT version): Version 6.2.0_e752793-dirty_2021.02.22

**Comment by PaulWessel** [comment]
I think you should just access q.txt with no directory prefix. The user “does not know” where these are run other than in the current directory so using that directory should fail

**Comment by Esteban82** [comment]
It worked. There is no bug. Sorry.
