### ISSUE TITLE
Update web font

### ISSUE THREAD

**Issue by liamtoney** [GenericMappingTools/gmt#4848]
**Description of the desired feature**

The PyGMT website has a new font which is designed to maximize the difference between lowercase L and uppercase I, etc. Example here: https://www.pygmt.org/dev/api/generated/pygmt.Figure.grdimage.html#pygmt.Figure.grdimage

PR for PyGMT here: https://github.com/GenericMappingTools/pygmt/pull/938

It seems like GMT's site could benefit from the same update. Maybe also would be nice for a coherent "design language" for what it's worth.

Pinging @meghanrjones who was involved in the PyGMT font convo.

**Are you willing to help implement and maintain this feature?**

No

**Comment by meghanrjones** [comment]
We used the Vercel app to preview the changes for PyGMT. Does anyone know if continuous documentation would similarly work for GMT? I can adjust the css settings for a different font, but it will not be convenient for everyone to build locally to evaluate the changes.

**Comment by seisman** [comment]
> Does anyone know if continuous documentation would similarly work for GMT?

Vercel should work for GMT, but I guess it's more complicated because we need to download and build the GMT codes first. I could give it a try or you want to try it?

**Comment by meghanrjones** [comment]
> > Does anyone know if continuous documentation would similarly work for GMT?
> 
> Vercel should work for GMT, but I guess it's more complicated because we need to download and build the GMT codes first. I could give it a try or you want to try it?

I have never used Vercel before, so it would likely go better for you to try if you do not mind.

**Comment by seisman** [comment]
> I have never used Vercel before, so it would likely go better for you to try if you do not mind.

OK.

**Comment by weiji14** [comment]
Looking back, it probably wasn't a good idea to use GMT as the team name on Vercel (i.e. https://vercel.com/gmt) for PyGMT :sweat_smile:. The current (old) free plan we're on has a limit of 3 owners (me, @seisman and @leouieda). I can probably kick Leo out and add you in @meghanrjones so you can actively work on things behind the scenes. Or we can upgrade and pay $20/month per team member according to https://vercel.com/pricing :slightly_smiling_face:

**Comment by seisman** [comment]
> it probably wasn't a good idea to use GMT as the team name on Vercel (i.e. [vercel.com/gmt](https://vercel.com/gmt)) for PyGMT

Can we change the team name to "GenericMappingTools"?

**Comment by weiji14** [comment]
> > it probably wasn't a good idea to use GMT as the team name on Vercel (i.e. [vercel.com/gmt](https://vercel.com/gmt)) for PyGMT
> 
> Can we change the team name to "GenericMappingTools"?

You mean without spaces? Sure. But for the **Team URL**, I would recommend keeping it as GMT, so that the vercel URL will be shorter. For those without any idea what we're talking about, this is a screenshot from the Vercel settings page:

![image](https://user-images.githubusercontent.com/23487320/109490499-2f0ab200-7aed-11eb-9612-9e2111515fa9.png)

**Comment by meghanrjones** [comment]
@PaulWessel, do you think it's worth inquiring about the open source pricing for Vercel?

**Comment by PaulWessel** [comment]
> @PaulWessel, do you think it's worth inquiring about the open source pricing for Vercel?

Sure, that cannot hurt.  At $20/mo we would be at $240/year which is still something the budget could absorb though.

**Comment by meghanrjones** [comment]
> > @PaulWessel, do you think it's worth inquiring about the open source pricing for Vercel?
> 
> Sure, that cannot hurt. At $20/mo we would be at $240/year which is still something the budget could absorb though.

OK, I will reach out to Vercel. I think a discount will be necessary - my interpretation of the standard pricing is $20/mo/team member which could get exorbitant quickly.

**Comment by PaulWessel** [comment]
Right, forgot the math on the times number of team members.  That would get uglier.

**Comment by meghanrjones** [comment]
> @meghanrjones Although we're using Vercel in [pygmt](https://github.com/GenericMappingTools/pygmt) and [website](https://github.com/GenericMappingTools/pygmt), and it works well in these two repositories, I still don't like it. The main reasons are:
> 
>     1. As you can see in the pygmt repository, we need to add two files `package.json` and `vercel.json` to the repository.
> 
>     2. For GMT, we need to write instructions in the `pacakge.json` file to build GMT and the documentation. It's not easy to do, because the `package.json` file is in JSON format (developer unfriendly)
> 
>     3. I tried to switch the vercal-action in PR [GenericMappingTools/pygmt#964](https://github.com/GenericMappingTools/pygmt/pull/964), so that we can build the documentation in the CI and then deploy to vercel. However, it doesn't work for PRs from forks, so making it useless to an open-source project.

OK, I do not know of a better solution than Vercel. So, it seems like the best path forward is to keep Vercel for now but to not upgrade the account in hopes that a better option is developed in the future.

**Comment by weiji14** [comment]
> > @meghanrjones Although we're using Vercel in [pygmt](https://github.com/GenericMappingTools/pygmt) and [website](https://github.com/GenericMappingTools/pygmt), and it works well in these two repositories, I still don't like it. The main reasons are:
> > ```
> > 1. As you can see in the pygmt repository, we need to add two files `package.json` and `vercel.json` to the repository.
> > 
> > 2. For GMT, we need to write instructions in the `pacakge.json` file to build GMT and the documentation. It's not easy to do, because the `package.json` file is in JSON format (developer unfriendly)
> > 
> > 3. I tried to switch the vercal-action in PR [GenericMappingTools/pygmt#964](https://github.com/GenericMappingTools/pygmt/pull/964), so that we can build the documentation in the CI and then deploy to vercel. However, it doesn't work for PRs from forks, so making it useless to an open-source project.
> > ```
> 
> OK, I do not know of a better solution than Vercel. So, it seems like the best path forward is to keep Vercel for now but to not upgrade the account in hopes that a better option is developed in the future.

[Netlify](https://www.netlify.com/) is probably the closest competitor to Vercel. Another one is readthedocs, they have a documentation previewer for each Pull Request (see https://docs.readthedocs.io/en/stable/pull-requests.html) ([xarray](https://github.com/pydata/xarray/) uses it). Either way there will be time spent on development to use any of these platforms.
