### ISSUE TITLE
EPS cropping is incorrect

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#485]
**Description of the problem**

Code to reproduce the bug:
```
gmt begin map eps
gmt basemap -R0/10/0/10 -JX10c/10c -Baf
gmt end
```
The output EPS file isn't cropped correctly. The left and bottom sides are right, while the right and top side are wrong.

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_b03d6d7_2019.03.06
* gs version: 9.26

**Comment by PaulWessel** [comment]
I don't see that.  The bounding box I get is 
%%BoundingBox: 0 0 329 321
and in ghostview it looks fine:
![screen shot 2019-03-06 at 9 00 27 am](https://user-images.githubusercontent.com/26473567/53906237-7dfcda00-3fee-11e9-90cb-6f84c371f14a.png)
Opening in Preview or gs do not seem to honor the BoundingBox though.

**Comment by seisman** [comment]
The BoundingBox and HiResBoundingBox of my EPS file seem correct.
```
%%BoundingBox: 0 0 329 321
%%HiResBoundingBox: 0 0 328.4280 320.9580
```
This is what I see when I open the EPS file with mac previewer.
![image](https://user-images.githubusercontent.com/3974108/53907558-71db4180-401b-11e9-8239-006a2d8fff62.png)

**Comment by joa-quim** [comment]
Just convert it to PDF and you'll see that it's correctly cropped. Problem is in the Mac previewer.

**Comment by seisman** [comment]
Got it.
