### ISSUE TITLE
psxy -SE bug when using linear projection

### ISSUE THREAD

**Issue by tmgreenfield1101** [GenericMappingTools/gmt#4877]
I have been having some issues with using the -SE option with psxy and linear projections. I've specifically been having issues with ellipses, but I think the problem can be best described with this example:

echo "0 0 0.1" | gmt psxy -JX10c/10c -R-0.1/0.1/-1/1 -SE- -Gred -Wthinner,black -Bxa0.05 -Bya0.5 -BSWne > tmp.ps
gmt psconvert -Tf -Z -P -A tmp.ps

This should plot a circle with a diameter of 0.1 units. As you can see from the attached plot, this command isn't working how I would expect. It seems the x and y direction are flipped (i.e. in this case the shape should be rotated by 90 deg).

[tmp.pdf](https://github.com/GenericMappingTools/gmt/files/6062185/tmp.pdf)

**System information**

* Operating system: ubuntu
* GMT version (`gmt --version`): 6.1.1

**Comment by meghanrjones** [comment]
@tmgreenfield1101, you can follow the [building from source](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md) instructions if you want to try out the solution implemented in PR #4886.
