### ISSUE TITLE
Add CI information to MAINTENANCE.md

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4900]
**Description of the desired feature**

We should add information about continuous integration and continuous documentation to [MAINTENANCE.md](https://github.com/GenericMappingTools/gmt/blob/master/MAINTENANCE.md). This could be similar to PyGMT's [maintenance section](https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md#continuous-integration). 

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
@meghanrjones Are you working on it? I can add the information as I wrote the most (if not all) workflows in this repository. It's also good if you want to take the opportunity to get familiar with how the CI in GMT works.

**Comment by meghanrjones** [comment]
> @meghanrjones Are you working on it? I can add the information as I wrote the most (if not all) workflows in this repository. It's also good if you want to take the opportunity to get familiar with how the CI in GMT works.

I have not started anything. But I could give it a go to, which might be a good check on whether I understand the workflows properly. #4950's description will be helpful.

**Comment by seisman** [comment]
OK. I'm glad to offer any help.
