### ISSUE TITLE
GMT_Create_Data(API, GMT_IS_GRID, ...) created from externals always transposes input

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4906]
When I create a grid in Julia with a padded scanline array, set the alloc mode as external and the "API_GRID_LAYOUT" to "TR", GMT should simply swallow it without touching, but it doesn't. Regardless if I set

GMT_Set_Default(API, "API_GRID_LAYOUT", "TR");
or
GMT_Set_Default(API, "API_GRID_LAYOUT", "TR");
or nothing

the input array is always transposed.
Tried to find where that happens but got lost in the IO

Hard to provide an working case other then a Julia example.

**Comment by PaulWessel** [comment]
Please post a simply Julia case since we have [a plan](https://docs.generic-mapping-tools.org/dev/debug.html#debug-gmt-jl-in-xcode-on-macos).

**Comment by joa-quim** [comment]
Found the shit. This is a not so simple case. I'm fetching the **padded** data in Julia directly from a GDAL dataset and since both GMT & GDAL are C it's stupid to make copies + transpositions when going through Julia but I had a bug in computing the _incs_ that took the pad into account and hence ``GMT_Create_Data`` got a wrong number of rows/cols.

This is solved now but I still have a problem  with array UD flipping. Seems (I'm never able to remember this) that GMT & GDAL uses one bottom-up and the other top-down arrays. Shit.

**Comment by joa-quim** [comment]
Ok, I'm back in troubles and this time it's not an issue with bad coordinates/increments.
A MWE
```
z = zeros(Float32, 6, 7);
z[3,3:5] = 1:3;
z[4,3:5] = 4:6;

G = GMT.GMTgrid("","",0,[1.,3,1,2,1,6], [1.,1],0,NaN,"","","",[1.0,2,3],[1.,2],deepcopy(z),"","","","TRB",2);

G
6×7 GMT.GMTgrid{Float32, 2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  2.0  3.0  0.0  0.0
 0.0  0.0  4.0  5.0  6.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

imshow(G, show=false)      # Calls grdimage

G
6×7 GMT.GMTgrid{Float32, 2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
```

That is, after that call the array is all zeros. And that despite the array had been declared as ``GMT_ALLOC_EXTERNALLY`` in https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L819

Also, using ``GMT_Set_Default(API, "API_GRID_LAYOUT", "TR");`` or ``TC`` or nothing makes no difference.

GMT.jl#master is needed to reproduce this

**Comment by PaulWessel** [comment]
OK, and imshow calls grdimage with what args?  Just passing the grid and get default color image, right (no shading, etc)?

**Comment by joa-quim** [comment]
```
julia> imshow(G, show=false, Vd=2)
"grdimage  -R1/3/1/2 -JX14c/0 -Baf -BWSen -n+a -C -P -K > C:\\TMP\\GMTjl_tmp.ps"
```

**Comment by PaulWessel** [comment]
and the grid is passed via a virtual file name as a GMT grid?

**Comment by joa-quim** [comment]
Paul, it's like the MEX. See the link I sent. First create a GMT_Create_Data() with ``mode = GMT_CONTAINER_ONLY`` and next a add data via pointer.

**Comment by joa-quim** [comment]
See what is getting me crazy. This is a slightly larger example (that works well) where I create a GDAL ``dataset``, fill it with julia data, next get that same data from the  the ``dataset``, fill a GMTgrid with it 
```
julia> G = gd2gmt(dataset)        
245×185 GMT.GMTgrid{Float32, 2}:  
 0.0  0.0  0.0         0.0        
 0.0  0.0  0.0         0.0        
 0.0  0.0  0.0212253   0.0224272  
 0.0  0.0  0.0229302   0.0242287  
```
Launch the debugger and see the data correctly in place (in gdrimage)
![image](https://user-images.githubusercontent.com/537321/110168276-d9851c80-7dee-11eb-91c1-9245c87b79b3.png)

But with my tinny example the 42 elements of ``API->object[1]->G->data`` are all zero.

**Comment by PaulWessel** [comment]
Let me wrap up some dept stuff/email and then I will go through the Julia install etc and see if I can get to the debugging.

**Comment by joa-quim** [comment]
Before loosing time with debugging just try first my Julia commands. Even in ``GMT_Call_Module()`` when module == ``grdimage`` the ``data`` array is already zeroed.

**Comment by joa-quim** [comment]
Still can't make any sense out of this. To avoid dimensions problems I made a square grid, but it still screws and I keep wondering. Why is input changed
```
julia> nx = 3; ny = 3; rang = [1, nx, 1, ny, 0.0,1]; x = collect(1.0:nx); y = collect(1.0:ny); inc = [1.0, 1]; zz = rand(Float32,ny,nx); z = zeros(Float32, ny+4, nx+4); z[3:end-2, 3:end-2] = zz; G1 = GMT.GMTgrid("","",0,rang, inc,0,NaN,"","","",x,y,deepcopy(z),"","","","TRB",2)
7×7 GMT.GMTgrid{Float32, 2}:
 0.0  0.0  0.0       0.0       0.0       0.0  0.0
 0.0  0.0  0.0       0.0       0.0       0.0  0.0
 0.0  0.0  0.790661  0.450669  0.18067   0.0  0.0
 0.0  0.0  0.479507  0.365586  0.403586  0.0  0.0
 0.0  0.0  0.502914  0.51916   0.167791  0.0  0.0
 0.0  0.0  0.0       0.0       0.0       0.0  0.0
 0.0  0.0  0.0       0.0       0.0       0.0  0.0

julia> imshow(G1, show=false)

julia> G1
7×7 GMT.GMTgrid{Float32, 2}:
  0.0       0.0       1.70903    0.352794  -0.503165    0.0         0.0
  0.0       1.44181   1.10182    0.465758  -0.042245   -0.312244    0.0
  2.03128   1.13065   0.790661   0.450669   0.18067    -0.0893283  -1.12603
 -1.06137   0.258865  0.479507   0.365586   0.403586    0.900295    3.4705
  0.674819  0.486669  0.502914   0.51916    0.167791   -0.183577   -1.38302
  0.0       0.510076  0.526322   1.04035   -0.0680033  -0.419372    0.0
  0.0       0.0       0.0519496  3.18391   -1.06078     0.0         0.0
```

**Comment by joa-quim** [comment]
Hmm, finally something makes a little sense. What is being changed are the values in the padding zone. With _flints_ we can see better that original values are not changed. But this raises another question, why are boundary conditions being applied in linear plots?

```
julia> nx = 3; ny = 3; rang = [1, nx, 1, ny, 0.0,1]; x = collect(1.0:nx); y = collect(1.0:ny); inc = [1.0, 1]; zz = rand(1:nx,ny,nx); z = zeros(Float32, ny+4, nx+4); z[3:end-2, 3:end-2] = zz; G1 = GMT.GMTgrid("","",0,rang, inc,0,NaN,"","","",x,y,deepcopy(z),"","","","TRB",2)
7×7 GMT.GMTgrid{Float32, 2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  3.0  2.0  2.0  0.0  0.0
 0.0  0.0  1.0  3.0  1.0  0.0  0.0
 0.0  0.0  3.0  1.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

julia> imshow(G1, show=false, Vd=1)
        grdimage  -R1/3/1/3 -JX14c/0 -Baf -BWSen -n+a -C -P -K > C:\TMP\GMTjl_tmp.ps

julia> G1
7×7 GMT.GMTgrid{Float32, 2}:
   0.0   0.0  11.0  -10.0   7.0   0.0    0.0
   0.0   6.0   5.0    0.0   3.0   3.0    0.0
  12.0   4.0   3.0    2.0   2.0   2.0    7.0
 -30.0  -5.0   1.0    3.0   1.0  -4.0  -24.0
  15.0   5.0   3.0    1.0   3.0   5.0   14.0
   0.0   7.0   5.0   -5.0   5.0   7.0    0.0
   0.0   0.0  15.0  -31.0  15.0   0.0    0.0
```

**Comment by PaulWessel** [comment]
Got julia updated and master.  But the https://docs.generic-mapping-tools.org/dev/debug.html#debug-gmt-jl-in-xcode-on-macos instructions leaves out how to load GMT.jl I think.  Should be using GMT I think. Doing that it loads and compiles. Set the stop point and run.  It gets to my stop point inside GMT_Call_Module but then the debugger progress wheel is spinning and no more action...  I probably have to build with a prior Xcode version, which is painful.

As for why the BCs: Two concernsL (1) no, I cannot think of a reason why this is done since is a linear projection and nothing needs to be resampled.  I thought we checked for that anyway. and (2) if the grid is readonly but has no pad then I know we allocate a new grid with pad to do the resampling.  in your case, it has a pad already, so is not caught by that test.  I guess it should get caught as a read-only here regardless.

**Comment by PaulWessel** [comment]
in grdimage we have

	`need_to_project = (gmt_M_is_nonlinear_graticule (GMT) || Ctrl->E.dpi > 0);`

and if true then we call _gmt_grd_project_ etc.  But in your case **-JQ** is used which is linear, and you are not passing **-E,** so how do you end up in that part of the code?

**Comment by joa-quim** [comment]
The instructions look right, except that when you already have GMT.jl installed you only need to do ``] up`` to update it.
The never-ending-spin, however, reminds me something.

**Comment by joa-quim** [comment]
Put a breakpoint in that line and ``need_to_project`` came out *false*

**Comment by PaulWessel** [comment]
OK, so where do you see a BC is being applied then?

**Comment by joa-quim** [comment]
If I remembered the function name I could put a bp there and see from where it came.

**Comment by joa-quim** [comment]
``GMT_Read_Data`` calls ``gmtapi_pass_object`` that calls ``gmt_grd_BC_set`` that does it.

**Comment by PaulWessel** [comment]
Can you just step through grdimage and see what it does in your case? That is what I do.

**Comment by PaulWessel** [comment]
Just saw your post after I hit return - I was going to say that it probably happens during read.  So at that point we cannot know if linear or not.  But we can know it is read-only so not apply the BC.  Can you see what you need to do in that function, i.e., get the hidden struct pointer and check the alloc_mode?

**Comment by PaulWessel** [comment]
I am looking at gmtapi_pass_object and perhaps this is the solution:

FOr each case (GRID, IMAGE, DATASET) I think we nee to get the container hidden pointer, i.e.
struct GMT_GRID_HIDDEN *GH = gmt_get_G_hidden (G), and if GH->alloc_mode == GMT_ALLOC_EXTERNALLY then do not call the BC stuff etc.

Or perhaps it is better if I do this?

**Comment by joa-quim** [comment]
But that would mean the BCs would never be applied to externally allocated memory. The changed values are in the padding zone and supposedly only applied if that padding is filled with zeros (or at least it should test that), which should do no harm. I got into this while trying to understand my down to the metal was screwing. Images still are, shitty column-major/row-major and what are the dimensions of the passed arrays is a nightmare.

**Comment by PaulWessel** [comment]
For grids (and images) there are a few concerns;

1. The user may give a read-only grid and request a sub-region.  Since we cannot change the grid we make changes to the padding settings in the header.  So the pad may be larger since the actual desired grid is a small part of what was given.  That way we do not reallocate anything.
2. IN preparing the user grid for what comes later we apply the BC which only changes the pad.  Does it bother you that the pad changes? I suppose we might be able to find a way to reset it to zeros in the end.  We are certainly not checking if the pad has zeros or not as that is irrelevant.

So I guess, what is the problem with GMT making changes to pad values as long as it is not allocating or freeing user memory?

**Comment by joa-quim** [comment]
But that what I said "...which should do no harm" unless an array was sent with true data in the padded zone. Then it should no change those values. Hence the idea of testing if the pad is zeroed (not even need to test them all).

**Comment by PaulWessel** [comment]
Well, the only way to test if the pad is zero is to check all.  But again, why on Earth would you care about the pad? It is a scratch area, not useful for data, and thus it makes no sense why we inside GMT have to worry about zeros or not in that pad.  If it is so precious, why not just make a copy before sending it to GMT then? Users should not even need to know about the pad.

**Comment by joa-quim** [comment]
Because for the same reason GMT fills the padding zone with real data when doing a grdcut, externals for the exact same reason can send also real data in the padding zone that should not be changed. And sure, this is not a users thing.

**Comment by PaulWessel** [comment]
OK, but then we need to set some flag then.  The GMT header keeps track if your pad is data or created by BCs.  Perhaps if you could set that flag then GMT will treat it as data BC and not overwrite them.  Isn't that a better solution?  May just take a bit-flag that must be passed when creating or filling the matrix.

**Comment by joa-quim** [comment]
What flag is it? I may be able to set it afterwards without needing to add nothing new.

**Comment by PaulWessel** [comment]
Well, no flag for you yet I think.  I am looking at gmt_grd_BC_set where we have this:

```
	for (i = n_skip = 0; i < 4; i++) {
		if (HH->BC[i] == GMT_BC_IS_DATA) {set[i] = false; n_skip++;}	/* No need to set since there is data in the pad area */
	}
```

So if we could get you to set the BC array to **GMT_BC_IS_DATA** then it will skip the BC-setting step.
Tell me how you actually attach your matrix to the GMT grid so I can see what is the best way to do this.

**Comment by joa-quim** [comment]
Maybe if I rename this to ``.m`` I'll make you finally look at it
https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L819
but I'm not unwrapping the ``hidden`` in
```
mutable struct GMT_GRID
	header::Ptr{GMT_GRID_HEADER}
	data::Ptr{Cfloat}
	x::Ptr{Cdouble}
	y::Ptr{Cdouble}
	hidden::Ptr{Cvoid}
end
```
so I can't change the ``BC[i]`` for the moment. But leave this. I'll find a way if I ever will really need this (or resume this discussion). The usefulness of it relies in me being able to go fish directly in GDAL from Julia, which I am but just a little and it's consuming too much time.

**Comment by joa-quim** [comment]
Funny, now all of the sudden this started to work (even revert color channels). Just have to figure why it's escaping my filter to know that in this case no default axes should be printed.

```
ds = readraster("map.png");                     # Tell GDAL to read the image
I = gd2gmt(ds, bands=[3,2,1], pad=0);    # Gert the image from the GDAL pointer and construct am GMTimage obj
imshow(I, fmt=:png)                                 # Pass the column-major array declared as external. No copies nor transpositions
```

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/110193302-20910300-7e2b-11eb-8398-93eb45527dd0.png)
