### ISSUE TITLE
basemap -L+llabel requires fancy scale

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4911]
**Description of the problem**

The documentation does not specify that a fancy map scale is required for **+l**, but the scale label does not show up without **+f**.

**Full script that generated the error**

```
gmt basemap -JM6i -Baf -R-5/5/-5/5 -Ln0.5/0.5+w100k+l"Distance at equator" -png test
```

**Full error message**

**Actual outcome**

There's no label for the map scale.

**Expected outcome**

A label for the map scale, similar to the output from this but with a plain scale:

```
gmt basemap -JM6i -Baf -R-5/5/-5/5 -Ln0.5/0.5+w100k+l"Distance at equator"+f -png test
```

**System information**

* Operating system: MacOS BigSur
* GMT version (`gmt --version`): 6.2.0 - 2021.03.04

**Comment by meghanrjones** [comment]
I think this is a code bug, but I can specify that **+f** is required for **+l** in #4878 if it is instead a documentation issue.

**Comment by PaulWessel** [comment]
It is actually by design.  The optional panel frame (-F) for the simple label does not take into account any label other that the numbers, so it is a feature.  I suggest you just add that +f is required for a label to be placed.

**Comment by meghanrjones** [comment]
Thanks for the clarification - I will add that to the docs.
