### ISSUE TITLE
Several oddities with pscoupe

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#4941]
Now that I have spent some time in the _seis_ supplement to do animations, there are several aspects of **coupe** that I find odd or wrong:

1. The **-A** option has a **+f** modifier to "get the frame from the cross-section parameters".  What this cryptic phrase means is to get the 2-D Cartesian **-R** domain implied via **-A**.  For instance, with **-Ab**128/11/120/250/90/400/0/100+f that implies **-R**0/250/0/100 but for other variants of **-A** it is not that simple.  What **+f** does is to update the internal **-R** setting and use these new parameters in setting up the plot, i.e., it _overrides_ any given **-R**.  However, if **-R** is not given in the first place then we get an error since **-R** is a required option.  Also, **+f** is usually used for fonts, and that is even true elsewhere in the _seis_ supplement, so it is a bad modifier choice (it derives from the old syntax which as a trailing **f**).  Finally, the syntax of **-A** is abhorrent and for some reason avoided getting a haircut via new modifiers during the GMT 5/6 revisions.
2. The **coupe** man page is silent on the most common use of **coupe** (vertical crossection) and should inform that you must use a negative y-scale to get depth down.
3. When animating via **events** I found that for plotting beachballs with polarity dots using **-Z**"-Sc3c -Fa0.1i/cc" the polarity dots selected via **-Fa** have fixed size.  So when the beachball gets autoscaled by **events**, the polarity dots stay at 0.1i.  I think it only makes sense to have the whole symbol scale.  This is a bit complicated since **coupe** basically plots two symbols, and the size I read from the input file (computed by events) is for the main **-S** symbol and cannot be used for **-T**.  I think the same is true in **meca**.
4. The documentation for **-A** needs to start with an upper case sentence.

Here are proposed changes I am thinking we should do:

1. In a backward compatible way, redesign the **-A** option to be
 **-Aa**_lon1/lat1/lon2/lat2_**+d**_dip_**+w**_width_**+z**_min_/_max_[**+r**] and **-Ab**_lon1/lat1_**+s**_strike_/_length_**+d**_dip_**+w**_width_**+z**_min_/_max_[**+r**] (and similar for **-Ac** and **-Ad**).  We could have sensible defaults for dip [90], etc.
2. Improve the man page on the need for vertical negative scaling for depth down and fix formatting
3. Find a way to let **-R** be an optional switch if the **+r** modifier is given in **-A** (one simple way is to just add -R0/1/0/1 when **+r** is given and **-R** is missing before we hit GMT_Parse_Common).  Or better: If **-R** is not given then **-A** sets **-R**, no **+r** should be needed.
4. Change **event** -> **meca**/**coupe** scale information so that we still pass on an actual fixed size in **-S** and **-F**, but then these numbers are modulated by the scale (not size) found in the new column.  This will require a hidden mechanism for these modules to know they are being called by **events** (which I think I can do).

Finally, along (4), it is a bit jarring to see symbols change size in the animation, yet pen thicknesses stay the same.  So for smaller scalings the pen is too thick at times.  I think the solution suggested for (4) should extend to **plot** and **plot3d** as well so when called from **events** with a variable scale column the scale applies to the _entire_ symbol, including pen widths.

Comments needed, especially from coupe users (@seisman ?).

**Comment by PaulWessel** [comment]
Pinging @seisman to see if there are objections to this.  I will do this with full backwards compatibility.

**Comment by seisman** [comment]
> 1. **-Aa**_lon1/lat1/lon2/lat2_**+d**_dip_**+w**_width_**+z**_min_/_max_[**+r**] and **-Ab**_lon1/lat1_**+s**_strike_/_length_**+d**_dip_**+w**_width_**+z**_min_/_max_[**+r**] (and similar for **-Ac** and **-Ad**).  We could have sensible defaults for dip [90], etc.

The new syntax is better than the old one, but I feel it can be further improved. Usually, modifiers are optional, but in the new syntax for **-Ab**, **+s** is necessary, unless we can give some reasonable defaults, which I think we can't. 

The following syntax makes more sense to me:

- **-Aa**_lon1/lat1/lon2/lat2_[**+d**_dip_**][+w**_width_][**+z**_min_/_max_][**+r**]
- **-Ab**_lon1/lat1/strike/length_[**+d**_dip_][**+w**_width_][**+z**_min_/_max_][**+r**]

_lon1/lat1/lon2/lat2_ or _lon1/lat1/strike/length_ are two different ways to define the start and end points of a cross-section, so they are always required. Other modifiers are optional,

- **+d**_dip_: dip=90 is a reasonable default value
- **+w**_width_: *width* is the width of the cross-section on each side of a vertical plane or above and under an oblique plane. I think a reasonable value is *infinity*, so that all beachballs are projected and plotted.
- **+z**_min_/_max_: the *depth* range of beachballs that are plotted. A reasonable defaults are -infinity to +inifity, i.e., all earthquakes are plotted.

**Comment by seisman** [comment]
> 1. However, if **-R** is not given in the first place then we get an error since **-R** is a required option.

I don't fully understand this. Do you mean `gmt coupe -A...+f` without -R gives an error?

**Comment by PaulWessel** [comment]
yes, pretty sure I tried that.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/2020-unavco-course/blob/master/seismology/beachball-cross-section.sh

This example uses `-A...+f` without `-R`, but it works. I'm a little confused about what you mean.

**Comment by PaulWessel** [comment]
Hm, strange.  That does work.  OK, I guess I was piping data into coupe, something like this:

```
echo "112 32 25  30  90   0  4  Strike-slip" | gmt coupe -Sa1c -Aa111/33/119/33/90/500/0/50+f -Q -JX15c/-8c -Bxaf+l"Distance (km)" -Byaf+l"Depth (km)" -BWSen -pdf t
coupe [ERROR]: Could not parse an into Geographical, Cartesian, or Temporal coordinates!
coupe [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
coupe [ERROR]: Offending option -Rnan/nan/nan/nan
```

but I see this might be a more general problem:

```
echo 0 0 | gmt plot -Sc0.2c -Gred -B -pdf t
plot [ERROR]: Could not parse an into Geographical, Cartesian, or Temporal coordinates!
plot [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
plot [ERROR]: Offending option -Rnan/nan/nan/nan

```

OK, so point 1 may need to be modified.  As for your suggestions for -A, they are good, but if infinity is a default then we cannot do an auto -R, no? Since depth is the y-range.

**Comment by seisman** [comment]
> but if infinity is a default then we cannot do an auto -R, no? Since depth is the y-range.

https://github.com/GenericMappingTools/gmt/blob/f1c04a99e1086ba8e0c868d08d6e4485d101b929/src/seis/pscoupe.c#L925-L929

Can we determine the Y range from the projected data? For a vertical cross-section, a reasonable Y range is the minimum and maximum depth from the input data. For non-vertical cross-section, it's more complicated, but maybe still possible?

**Comment by PaulWessel** [comment]
Yes, possibly.  I can start a branch on pcoupe.c to start addressing the changes.  Then we can see how it goes with the -R.

**Comment by PaulWessel** [comment]
The usage and man page talk about -Aa|b|c|d with the last two like a and b but for Cartesian coordinates, but the code does not check for that, only a vs b, and the proj_type variable that holds those codes are only compared against a and b.  is this just ancient code no longer usable for anyone?  Should I check with Kurt Feigl if we should remove it completely?

**Comment by PaulWessel** [comment]
I assume length and depths are always in km.  Docs dont say.

**Comment by seisman** [comment]
> I assume length and depths are always in km. Docs dont say.

I think yes.
