### ISSUE TITLE
gmt_conf symbol diapeared from shared lib?

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#4953]
Julia tests are failing because
```
ERROR: LoadError: LoadError: could not load symbol "gmt_conf":
/home/runner/gmt-install-dir/lib/libgmt.so: undefined symbol: gmt_conf
Stacktrace:
```
It  looks that the ``gmt_conf`` symbol is gone from the shared lib.

**Comment by PaulWessel** [comment]
Seems like this issue came up some weeks ago and possibly was fixed in master, only to be overwritten by a marge from gmt-themes?  You probably want gmt_conf_SI.

**Comment by PaulWessel** [comment]
I suppose we can add

```
void gmt_conf (struct GMT_CTRL *GMT) {
    gmt_conf_SI(GMT);
}
```

so you can continue to use it.

**Comment by joa-quim** [comment]
Will not really help since I now have no access to either ``gmtinit_conf_classic()`` or ``gmtinit_conf_modern()`` because they became ``GMT_LOCAL``.

**Comment by PaulWessel** [comment]
We need a better system that you picking and choosing functions to use, no records kept, and then these things happens.  We want to minimize the exported symbols in general, but not prevent you from doing stuff, but clearly so far all these things are ad hoc after a problem like this.  I think you may want to add a comment at all the functions you expect to remain as is for external use since there is no way I am going to simply remember that you using something low-level.

**Comment by PaulWessel** [comment]
So from the above you are saying you need to call gmt_conf, gmt_conf_classic and gmt_conf_modern?

**Comment by joa-quim** [comment]
I don't remember exactly what I needed, also because it was an half-finished work. I want to be able to set a mechanism  that allows easy setting of a theme just with a ``kwarg`` and that theme to be valid just one call for example. And all of that without writing conf files. I guess that at the point I left it I waned to be able to call the *reset_defaults* but it now is dependent of if one is in modern or classic and remember that I have no access to the contents of ``*GMT``.

```
void gmt_conf_SI (struct GMT_CTRL *GMT) {
	if (GMT->current.setting.run_mode == GMT_MODERN)
		gmtinit_conf_modern (GMT);
	else
		gmtinit_conf_classic (GMT);
```

**Comment by PaulWessel** [comment]
If you need deep access to GMT low-level functions then perhaps the solution is for you to have a gmt_julia.c|h files that goes with the julia installation and handles things there.  It is not a good situation to have the external depend on low-level GMT functions that are both undocumented and unstable, made more complicated that the C developers (minus you) do not know anything about this need and it is not documented anywhere.  Give some thought to how this could work better.

**Comment by joa-quim** [comment]
What do you have in mind with ``have a gmt_julia.c|h files that goes with the julia installation``?
GMT.jl does not distribute any *.c files.
Adding Julia specific comments on *.c files next to lower level used functions seems the best option. But, from what I remember, they are nearly none (but != 0) on that situation.

**Comment by PaulWessel** [comment]
Not sure what I have in mind but as you know, MB-system also calls some low-level stuff and we have been burned a few times when we change them.  Perhaps what we need (in GMT core) is another file called gmt_external.c|h where all of this stuff is listed and documented.  It would be for thinks that the external cannot do via the API but needs to do, and we basically decide to have a back-door for these actions and collect them in this specific file.  It would be a lot easier to have juts a dozen or so functions in that one file than spread across all of gmt_*.c.  Just to be clear, the gmt_externals.? file would be with GMT and part of libgmt.

**Comment by joa-quim** [comment]
We have talked about this several times in the past. The issue is that we need at least another layer of stable/documented functions other then the *very generic* API functions. For example one issue mentioning that is #3385

**Comment by PaulWessel** [comment]
I understand, and we do have these.  But clearly our system is not working given issues like #3385 and prior MB-system screw-ups.

**Comment by joa-quim** [comment]
Well, Dave is not reading this (at least not now) but most of MB-screws were due to use of lower level functions (*readsomething*) for which API functions were also provided.

**Comment by joa-quim** [comment]
I think I invented an workaround for this too.
