### ISSUE TITLE
gmt docs coast -B cannot open the documentation

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#496]
**Description of the problem**

```
$ gmt docs coast -B 
docs [ERROR]: Found no history for option -B
```

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_5c276b2_2019.03.09

**Comment by PaulWessel** [comment]
Basically, all the common options (-B, -R, -J, ...) will give the same error if not found in gmt.history.  We will need to intercept this parsing...

**Comment by joa-quim** [comment]
Hmm, -R & -J work for me. Only -B fails

**Comment by PaulWessel** [comment]
Did you remove all your gmt.history files? -R fails for me after doing that.

**Comment by joa-quim** [comment]
Yes, you're right. But curiously it always works if called from Julia.
