### ISSUE TITLE
coast command fails with bash on windows

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#4984]
**Description of the problem**

*Originally posted in https://github.com/GenericMappingTools/gmt/pull/4983#issuecomment-801467593 by @seisman*

**Full script that generated the error**

```
gmt begin
gmt coast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -Vd
gmt end
```

**Full error message**

```
Error:  [ERROR]: Shared GMT module not found: coast

ERROR: No module named coast was found.  This could mean one of four cases:
  1. There actually is no such module; please check your spelling.
  2. You used a modern mode module name while running in GMT classic mode.
  3. Module exists in the GMT supplemental library, but the library could not be found.
  4. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
Shared libraries must be in standard system paths or set via environmental parameter %%PATH%%.

gmt.exe [DEBUG]: Entering GMT_Destroy_Session
gmt.exe [DEBUG]: Failed to release lock (Error <158>: The segment is already unlocked.
)
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by Esteban82** [comment]
I cannot reproduce the error. 


GMT version: Win 6.1.1 (64-bit) on Win7.

I think that I have had a similar error sometimes (that a module was not found) but then I run again the script and it works. It was like there was something that do not allow to recognized the GMT modern mode (maybe I am wrong).

![coast](https://user-images.githubusercontent.com/17908951/111560040-71302680-8770-11eb-8e81-a63d7ad175aa.png)

**Comment by Esteban82** [comment]
And also works on Win 10 (same GMT version).
