### ISSUE TITLE
plot -Sb (shift band)

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#5022]
Hi,

When creating a bar plot using `plot -Sb`, the x-axis is centred on the value
```
plot -Sb3u
x = 0
bar : [-1.5 : 1.5]
```

Would it be possible to add a "phase" option similar to the one in -Bafg<+phase> so we could do
```
plot -Sb3u+1.5
x = 0
bar : [0 : 3]
```

Thanks.

**Comment by PaulWessel** [comment]
You can probably do this via -i0+o1.5,1 (add 1.5 to all x-values) or shift your symbols via -D.

**Comment by gd-a** [comment]
Hum, will try.
-D option didn't work because the "unit" option is not there

**Comment by gd-a** [comment]
+o works perfectly well. This is actually the feature.
Thanks !
