### ISSUE TITLE
Borken link to GMT.jl

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5029]
This link https://www.generic-mapping-tools.org/GMT.jl/ is now broken.

But that's strange because for example this one works
https://www.generic-mapping-tools.org/GMT.jl/dev/gallery/scripts_agu/bars_3D/

**Comment by seisman** [comment]
> This link [generic-mapping-tools.org/GMT.jl](https://www.generic-mapping-tools.org/GMT.jl/) is now broken.

I think it's because you don't provide an `index.html` file in your gh-pages branch.

**Comment by joa-quim** [comment]
But this one works
https://github.com/GenericMappingTools/GMT.jl
and the one above is the one we have in https://www.generic-mapping-tools.org/projects/ for the documentation.

![image](https://user-images.githubusercontent.com/537321/112675103-a3234600-8e5e-11eb-8573-da3451457afc.png)

probably the simplest is just to fix the link but I think it was working before.

**Comment by seisman** [comment]
https://www.generic-mapping-tools.org/GMT.jl/dev/ works because there is an `index.html` file in the dev directory.

The simplest fix is adding an `index.html` file in the [gh-pages](https://github.com/GenericMappingTools/GMT.jl/tree/gh-pages) branch, which redirects https://www.generic-mapping-tools.org/GMT.jl/ to https://www.generic-mapping-tools.org/GMT.jl/dev/.

The `index.html` file only contains one line:
```
<meta http-equiv="Refresh" content="0;url=dev/"/>
```

**Comment by joa-quim** [comment]
Hmm, did that, but still no works. I had sometime ago a very strange episode where something nuked my ``latest`` directory and now I only have a ``dev``.
When a ``index.html`` does not exist one should get ``you don't have permission to sneak year`` instead of a 404, no?

**Comment by seisman** [comment]
I think it works. Now https://www.generic-mapping-tools.org/GMT.jl/ is redirected to https://www.generic-mapping-tools.org/GMT.jl/dev/ for me.

**Comment by joa-quim** [comment]
Yes? How strange. It doesn't for me at home and not even if I try from a remote login into a university computer.

**Comment by seisman** [comment]
Maybe because your browser cache?

**Comment by joa-quim** [comment]
It was to test that that I tried via the University's computer

**Comment by joa-quim** [comment]
Can it be that country-wide cashes exist? Had to update Windows, which implies reboots and took the opportunity to run some cleaning apps ... and now it works!
