### ISSUE TITLE
wiggle bug: +n & +p of the +G option cannot work at the same time

### ISSUE THREAD

**Issue by core-man** [GenericMappingTools/gmt#5035]
**Description of the problem**

It seems that **+p** and **+n** cannot work at the same time **-G***fill*[**+n**][**+p**]. However, see the documentation of [+G](https://docs.generic-mapping-tools.org/latest/wiggle.html#g) option:

> Set fill shade, color or pattern for positive and/or negative wiggles [Default is no fill]. Optionally, append +p to fill positive areas (this is the default behavior). Append +n to fill negative areas. Append +n+p to fill both positive and negative areas with the same fill.

---

I use [an example](https://docs.generic-mapping-tools.org/latest/wiggle.html#examples) in GMT wiggle documentation to test it.

**no -G:**
```
gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -W0.5p -pdf map-noG
```

**Output:**
<img src="https://user-images.githubusercontent.com/50591376/112815666-1de49f00-90b3-11eb-8302-44b2197c0550.png" width=300 />

**-G:**
```
gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -Gred -W0.5p -pdf map-G
```

**-G+p:**
```
gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -Gred+p -W0.5p -pdf map-p
```

**-G+p+n:**
```
gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -Gred+p+n -W0.5p -pdf map-p-n
```

**-G+n+p:**
```
gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -Gred+n+p -W0.5p -pdf map-n-p
```

**Output of the above four cases are the same:**
<img src="https://user-images.githubusercontent.com/50591376/112815815-48365c80-90b3-11eb-9df1-1a4cec636612.png" width=300 />

**-G+n:**
```
gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -Gred+n -W0.5p -pdf map-n
```

**Output:**
<img src="https://user-images.githubusercontent.com/50591376/112815858-571d0f00-90b3-11eb-9e4a-15e1600bd2bc.png" width=300 />

**System information**

* Operating system: CentOS 7.5
* GMT version (`gmt --version`): 6.1.1

**Comment by PaulWessel** [comment]
I think this is a case of incomplete documentation.  If you want separate colors then you need to give **-G** twice: Once with +n and once with +p:

`gmt math -T-8/6/0.01 -N3/0 -C2 T 3 DIV 2 POW NEG EXP T PI 2 MUL MUL COS MUL 50 MUL = | gmt wiggle -R-10/10/-1/1 -JX15c -BWSne -Bxa2f1 -Bya0.5 -Z10c -DjRM+w100+lnT -T0.5p -Gred+n -Gblue+p -W0.5p -png map-n-p`

![map-n-p](https://user-images.githubusercontent.com/26473567/113040888-08b05480-9135-11eb-95ab-738699f8b014.png)

I will improve the documentation so it is clear.

**Comment by PaulWessel** [comment]
Actually, the -Gred+n+p should paint both and it does not.  So I will look at that as well.

**Comment by seisman** [comment]
Just want to mention that: The [sac](https://docs.generic-mapping-tools.org/dev/supplements/seis/sac.html#g) module has similar feature, but it looks more powerful than the one in the wiggle module.
