### ISSUE TITLE
grid processing fails: axis is not geographic

### ISSUE THREAD

**Issue by viktor76525** [GenericMappingTools/gmt#5037]
GMT not accepting geolgraphic units in `-I`.
Works in 6.1.1, master as of 30th march <now> doesn't work.
Actually I started with `gmt surface` which has the same problem, this example is for `gmt blockmean`.
[sample.zip](https://github.com/GenericMappingTools/gmt/files/6225503/sample.zip)

**Full script that generated the error**

Note that sample.zip includes history which may need changing between 6.1.1 and 6.2.0 in the header.
(-R is -R171.02263762683282/178.44992526831228/-42.576706555680545/-39.359384439577184)
xyz.bin is a lon, lat, value binary file.
```
gmt blockmean xyz.bin -bi3f -I0.16k/0.16k -R -fg > xyz_620.txt
```

**Full error message**

```
blockmean [WARNING]: Unit k is ignored as the x-axis is not geographic
blockmean [WARNING]: Unit k is ignored as the y-axis is not geographic
```

**Actual outcome**

Seems to have taken -I0.16k as -I0.16 degrees, block size is large, output file is ~7KB.
**Expected outcome**
Take it as k for kilometers. Like in 6.1.1, block size is small, output file is ~9MB.

**System information**

* Operating system: Linux 5.4.97-gentoo
* GMT version (`gmt --version`): 6.2.0_76e4118_2021.03.29
```
gmt blockmean xyz.bin -bi3f -I0.16k/0.16k -R -fg > xyz_620.txt
```

**Full error message**

```
blockmean [WARNING]: Unit k is ignored as the x-axis is not geographic
blockmean [WARNING]: Unit k is ignored as the y-axis is not geographic
```

**Actual outcome**

Seems to have taken -I0.16k as -I0.16 degrees, block size is large, output file is ~7KB.
**Expected outcome**
Take it as k for kilometers. Like in 6.1.1, block size is small, output file is ~9MB.

**System information**

* Operating system: Linux 5.4.97-gentoo
* GMT version (`gmt --version`): 6.2.0_76e4118_2021.03.29
```
gmt blockmean xyz.bin -bi3f -I0.16k/0.16k -R -fg > xyz_620.txt
```

**Full error message**

```
blockmean [WARNING]: Unit k is ignored as the x-axis is not geographic
blockmean [WARNING]: Unit k is ignored as the y-axis is not geographic
```

**Actual outcome**

Seems to have taken -I0.16k as -I0.16 degrees, block size is large, output file is ~7KB.
**Expected outcome**
Take it as k for kilometers. Like in 6.1.1, block size is small, output file is ~9MB.

**System information**

* Operating system: Linux 5.4.97-gentoo
* GMT version (`gmt --version`): 6.2.0_76e4118_2021.03.29

**Comment by PaulWessel** [comment]
Thanks for the issue posting - it duplicates one we received from the [forum](https://forum.generic-mapping-tools.org/t/creating-a-zero-level-grid/1516/3) a bit earlier today, and the issue was hopefully fixed by #5036.  The warnings go away using your command with some -R values and fake data.
Let us know if otherwise - in the meantime I am closing this issue.
