### ISSUE TITLE
Documentation search not working in dev branch

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#5039]
Not sure if correct place for this but when using the search box in the documentation I get no results when searching in "dev" branch.

"latest" works:
https://docs.generic-mapping-tools.org/latest/search.html?q=plot&check_keywords=yes&area=default#

"dev" doesn't work:
https://docs.generic-mapping-tools.org/dev/search.html?q=plot&check_keywords=yes&area=default#

**Comment by meghanrjones** [comment]
The source distribution for the sphinx_rtd_theme includes many more files than are included in https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/themes/rtd. It seems to me that I can just update the files that are already included in the GMT repository and were changed between v0.5.0 and v0.5.1 (https://github.com/readthedocs/sphinx_rtd_theme/compare/0.5.0...0.5.1). @seisman, does this solution seem good to you based on your experience with updating sphinx_rtd_theme in https://github.com/GenericMappingTools/gmt/pull/3797?

**Comment by seisman** [comment]
> The source distribution for the sphinx_rtd_theme includes many more files than are included in https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/themes/rtd. It seems to me that I can just update the files that are already included in the GMT repository and were changed between v0.5.0 and v0.5.1 ([readthedocs/sphinx_rtd_theme@0.5.0...0.5.1](https://github.com/readthedocs/sphinx_rtd_theme/compare/0.5.0...0.5.1)). @seisman, does this solution seem good to you based on your experience with updating sphinx_rtd_theme in #3797?

Yes to me

**Comment by KristofKoch** [comment]
Time to re-open this one …

Problem is the same as two years ago:

When using the search box in the documentation I get no results when searching in "dev" branch.

"latest" works:
https://docs.generic-mapping-tools.org/latest/search.html?q=plot&check_keywords=yes&area=default#

"dev" doesn't work:
https://docs.generic-mapping-tools.org/dev/search.html?q=plot&check_keywords=yes&area=default#

**Comment by seisman** [comment]
Related to https://github.com/readthedocs/sphinx_rtd_theme/issues/1451.
