### ISSUE TITLE
Options for GMT forum/mailing list

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/gmt#505]
As discussed in #368, we still don't have a replacement for the GMT forum at http://gmt.soest.hawaii.edu. This is the last bit of infrastructure that hasn't been migrated. The options pointed out in that discussion were:

* [Discourse](https://www.discourse.org/). A forum software designed by one of the creators of StackOverflow. :heavy_plus_sign: Can serve as forum but also allows emails :heavy_minus_sign: We'd have to self host of pay them to host it.
* [Google Groups](https://groups.google.com/). Kind of forum but mostly a mailing list. :heavy_plus_sign: Easy to setup and free :heavy_minus_sign: Owned by Google so could disappear at any time and requires Google account.
* Self hosted mailing list. Fairly easy to setup but would still rely on SOEST infrastructure.

We have to pick something and go with it. Ideally, what we choose should have a few features:

* Allow posting by email.
* High bus factor (more than 1 person who knows how to setup and keep alive).
* Ability to search old posts.

Please feel free to contribute other key features.

cc @GenericMappingTools/core

**Comment by leouieda** [comment]
Some challenges for hosting discourse: we need to host a mail server as well so that discourse can send out emails. It doesn't have to be self hosted, could also be a cloud. But still another cost.

**Comment by abanbj** [comment]
So github has no kind of forum service? They should just clone the 'Issues' tab and rename it 'Forum' and we  would have a decent place to discuss!

**Comment by leouieda** [comment]
@abanbj I agree but currently that's not an option :( There is also no way to filter out issues from questions in a way that separates the notifications.

**Comment by seisman** [comment]
For the github solution, what about creating a separated repo (e.g. https://github.com/GenericMappingTools/forum)?

**Comment by leouieda** [comment]
That's a good solution! It would be very difficult to migrate in the future. We're looking into hosting a Discourse at SOEST under forum.generic-mapping-tools.org. We could easily migrate this to another hosting service in the future without the users being impacted.

**Comment by PaulWessel** [comment]
Just FYI, we have secured permission by the University of Hawaii to host *.generic-mapping-tools.org on the hawaii.edu domain so we will be working on this the next weeks.

**Comment by coynedog** [comment]
Have you checked out groups.io? I use it as a forum/maillist for another community and it seems to work well.

**Comment by leouieda** [comment]
@coynedog I've seen it and it seems good. We ended up going with Discourse because it's a more sustainable alternative and not likely to go away any time soon.

**Comment by relphj** [comment]
And registering for the current Forum doesn't work because Google changed their recaptcha API.

**Comment by PaulWessel** [comment]
Yep, we are about to release the Discourse forum any day now.  Stay tuned.

**Comment by seisman** [comment]
The new GMT community forum is available from https://forum.generic-mapping-tools.org. Closed.
