### ISSUE TITLE
pswiggle: drawing tracks without connecting

### ISSUE THREAD

**Issue by 79seismo** [GenericMappingTools/gmt#506]
Is there an option in pswiggle to draw tracks without connecting adjacent tracks? (i.e. an offset in the 2nd column in the input file marks an individual track)? I remember this feature was there in earlier versions of GMT? Thanks!

**Comment by PaulWessel** [comment]
Gap detection is a general GMT feature handled by GMT common option **-g**; see https://www.generic-mapping-tools.org/gmt/latest/gmt.html#g-full.

**Comment by 79seismo** [comment]
Thanks Paul!
