### ISSUE TITLE
grdimage -Em using Cartesian Map Angle iso. Geographic Azimuth

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#5082]
**Description of the problem**

When calculating illumination with `grdimage` I noted that `-Em` uses _positive counter-clockwise from horizontal_ as reference system while `-Es` uses _positive clockwise from vertical_ as reference.

**Full script that generated the error**

```
#!/usr/bin/env bash

gmt grdmath -R-20/20/-20/20 -I0.1 X Y HYPOT DUP 2 MUL PI MUL 8 DIV COS EXCH NEG 10 DIV EXP MUL = sombrero.nc

gmt grdgradient sombrero.nc -Em0/45 -Glight_Em_0_45.grd
gmt grdgradient sombrero.nc -Es0/45 -Glight_Es_0_45.grd

gmt grdimage -JX15c sombrero.nc -Ilight_Em_0_45.grd -AEm_0_45.png
gmt grdimage -JX15c sombrero.nc -Ilight_Es_0_45.grd -AEs_0_45.png


gmt grdgradient sombrero.nc -Em90/45 -Glight_Em_90_45.grd
gmt grdgradient sombrero.nc -Es90/45 -Glight_Es_90_45.grd

gmt grdimage -JX15c sombrero.nc -Ilight_Em_90_45.grd -AEm_90_45.png
gmt grdimage -JX15c sombrero.nc -Ilight_Es_90_45.grd -AEs_90_45.png
```

**Actual outcome**

**Light Source 0/45**

`-Es0/45` correct, light source 12 o'clock
![Es_0_45](https://user-images.githubusercontent.com/45796239/113453914-4e0ba500-9407-11eb-97e7-d4bd0eafd1e0.png)

`-Em0/45` wrong, light source 3 o'clock
![Em_0_45](https://user-images.githubusercontent.com/45796239/113453913-4d730e80-9407-11eb-8cbb-b37548b7767a.png)

**Light Source 90/45**

`-Es90/45` right, light source 3 o'clock
![Es_90_45](https://user-images.githubusercontent.com/45796239/113453910-4c41e180-9407-11eb-99e2-dfffe0f03a39.png)

`-Em90/45` wrong, light source 12 o'clock
![Em_90_45](https://user-images.githubusercontent.com/45796239/113453917-4ea43b80-9407-11eb-90ea-8714db9ebf99.png)

**Expected outcome**

I expected `-Em` behaving the same way `-Es` does – _positive clockwise from vertical_

**System information**

* GMT version (`gmt --version`): 6.2.0_c8b9282_2021.03.27

**Comment by PaulWessel** [comment]
Hi @joa-quim, I think you implemented these.  Could you please check and if a bug enforce the same behavior as the rest of the options?

**Comment by PaulWessel** [comment]
@KristofKoch, once #5087 is merged, please give it a test to make sure.

**Comment by KristofKoch** [comment]
Tested 2c09657 and works fine for me.
