### ISSUE TITLE
Broken formatting with docutils 0.17 #1176 

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5097]
**Description of the problem**

Same issue as https://github.com/GenericMappingTools/pygmt/issues/1176, but more extensively affects the GMT documentation front page, in that the quicklinks section and toctree are both now formatted poorly:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/14077947/113591381-d190e600-9601-11eb-8ea5-d04e0bc1b260.png">

<img width="298" alt="image" src="https://user-images.githubusercontent.com/14077947/113591418-dce41180-9601-11eb-97db-6c6cc0d45eef.png">

**Comment by meghanrjones** [comment]
@seisman, do you know if there will be a new dropdown option for 6.2rc1 in the docs when the tag is made on GitHub? If so, I think we should pin docutils<0.17 soon rather than waiting for an upstream bug fix.

**Comment by seisman** [comment]
The dropdown option is manually added here https://github.com/GenericMappingTools/gmt/blob/888b1feb4c36becb5593d0091824916b59234b3c/doc/rst/_static/version_switch.js#L12, so it depends on if we want to have a 6.2rc1 dropdown or not.
