### ISSUE TITLE
gmt set MAP_TITLE_OFFSET with no units, screws

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#511]
None of these uses the unit and all but ``MAP_TITLE_OFFSET`` are correctly set to points.

``gmt set MAP_TITLE_OFFSET 7 FONT_TITLE 24 FONT_ANNOT_PRIMARY 9``

```
#
# GMT 6.0.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 9p,Helvetica,black
FONT_LABEL                     = 14p,Helvetica,black
FONT_TITLE                     = 24p,Helvetica,black
#
# MAP Parameters
#
MAP_TITLE_OFFSET               = 77
```

**Comment by PaulWessel** [comment]
Weird, if 7 is seen as inches then why does it not write 7*72 = 504? What does 77 mean?

**Comment by joa-quim** [comment]
And it's even more strange. I found this when porting the ``rose_mag1.sh`` test to Julia. And what I see in the ps file is that the ``7`` is interpreted as ``7 cm``, which I find normal (another units confusion) but that 77 is weird (77 is ASCII ``M``, so not even that).

**Comment by PaulWessel** [comment]
Well, 7 should certainly be interpreted as 7 cm unless PROJ_LENGTH_UNIT is inch and then it is 7 inches.  I suspect the problem has to do with the appending of the unit on the output and the array length that holds those values might be exceeded and you get another char like '7'.  Will check.

**Comment by PaulWessel** [comment]
Hm. a MAP_LABEL_OFFSET of 3 gives 33....

**Comment by PaulWessel** [comment]
It clearly is picking the last character as the 'unit' and not realizing none where given.

**Comment by joa-quim** [comment]
No, all the others are interpreted as points which is very convenient because I can be lazy an type

``
par=(FONT_ANNOT_PRIMARY=9, FONT_LABEL=14, FONT_TITLE=24, MAP_TITLE_OFFSET=7, MAP_VECTOR_SHAPE=0.5)
``
instead of

```
par=(FONT_ANNOT_PRIMARY="9p", FONT_LABEL="14p", FONT_TITLE="24p", MAP_TITLE_OFFSET="7p", MAP_VECTOR_SHAPE=0.5")
``

**Comment by joa-quim** [comment]
> Hm. a MAP_LABEL_OFFSET of 3 gives 33....

Had noticed that too

**Comment by PaulWessel** [comment]
Well, I just did this which demonstrates a problem:

> rm -f gmt.conf
> gmt set MAP_TITLE_OFFSET 7 MAP_LABEL_OFFSET 3                
> cat gmt.conf
> #
> # GMT 6.0.0 Defaults file
> #
> # MAP Parameters
> #
> MAP_LABEL_OFFSET               = 33
> MAP_TITLE_OFFSET               = 77
>

**Comment by joa-quim** [comment]
So, it's in the ``MAP_`` group (the ``FONT_`` works fine)

**Comment by PaulWessel** [comment]
Fonts are expected to be given in points, distances are expected to have units or default to cm (or inch).

**Comment by PaulWessel** [comment]
Fixing the problem, running tests then will add PR.
