### ISSUE TITLE
grdimage: Use of grid names with space and -I+d

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5119]
See example below.
The initial call to ``grdimage`` works fine due to the file name being contained within ``'`` or ``"``. The subsequent call to ``grdgradient`` apparently does not do this, and the file is not found. 

```
gmt grdcut -RNO @earth_relief_10m -G"stupid file name.nc"
gmt grdimage 'stupid file name.nc'
gmt grdimage 'stupid file name.nc' -pdf f -I+d
grdgradient [ERROR]: Cannot find file stupid
```

**Comment by PaulWessel** [comment]
Thanks @anbj, I am sure there are many places like that in GMT, still.  I also think (at least I do) it is poor use of developer time to implement lots of checks just because some people  find file names with spaces appealing.  We will see what we can do.

**Comment by anbj** [comment]
Totally agree; I just want to make you aware of it. I often come across such not-really-a-bug-but-stupid-use-cases. Would you prefer to have them posted in the GMT-forum? Or some other place? Or not bother with them at all?

**Comment by PaulWessel** [comment]
No, this is the perfect place for them.  I am just being grumpy this morning, and that is after coffee.

**Comment by anbj** [comment]
You have my fullest sympathy. Go get a bucket of the black stuff.

Good; I'll keep posting when I come across stuff like this.

Thanks Paul.

**Comment by anbj** [comment]
..... Ai, _after coffee_ ?... Oh my.
