### ISSUE TITLE
Failed to specify the suffix for latitudes (i.e. N/S) in the polar coordinate system (-Jp, -JP)

### ISSUE THREAD

**Issue by zhong-yy** [GenericMappingTools/gmt#5120]
**Description of the problem**
I wanted to plot data that are given in polar coordinates (latitude, radius), so I chose the linear projection `-JP`. But I encountered the following problems:
1. The angle was treated as longitude by default rather than latitude, so the suffix was W or E. 
2. The options **+l**_label_ and  **+u**_unit_ didn't work under the projection with polar coordinates `-JP`.

**Full script that generated the error**

Here is a minimum working example:
```
gmt begin Jp jpg E300
    gmt set FORMAT_GEO_MAP ddd:mm:ssF
    gmt basemap -JP5c+z+t0 -R-30/30/4371/6371 -Bxa15f+u" N" -Bya+l"Depth (km)" -BWNse
gmt end show
```
I have tried `-JP3c+z+t0+a`, but it didn't work.

**Actual outcome**
![Jp](https://user-images.githubusercontent.com/38816011/114184241-2f615d00-9977-11eb-93a1-79e03572fb95.jpg)

**Expected outcome**

I want to change W (E) to S (N), like this:
![image12](https://user-images.githubusercontent.com/38816011/114188285-91bc5c80-997b-11eb-9e18-19eca21084ae.png)

**System information**

* Operating system: Ubuntu20.04
* GMT version (`gmt --version`): 6.1.1

**Comment by PaulWessel** [comment]
Thanks for the post.  I guess GMT cannot know what the angular measures are, so it will need to be told.  It looks like it assumes these are always longitudes.  I think we need to contemplate a situation where we can communicate to **-JP** the following

1. The angles are longitude: Formatting will be as for longitude.
2. The angles are latitude: Formatting will be as for latitude.
3. The angles are just angles: Formatting will be for angles with degree symbol only.

I am guessing we need to add a new modifier to **-JP|p**, e.g. **+k**_kind_, where kind may be _x_ (longitude) or _y_ (latitude).  The default would just be degrees.

Alternatively, we use **-f**0x and **-f**0y instead to indicate the same information.

Other thoughts on this, @joa-quim, @meghanrjones and @seisman ?

**Comment by meghanrjones** [comment]
> Thanks for the post. I guess GMT cannot know what the angular measures are, so it will need to be told. It looks like it assumes these are always longitudes. I think we need to contemplate a situation where we can communicate to **-JP** the following
> 
>     1. The angles are longitude: Formatting will be as for longitude.
> 
>     2. The angles are latitude: Formatting will be as for latitude.
> 
>     3. The angles are just angles: Formatting will be for angles with degree symbol only.
> 
> 
> I am guessing we need to add a new modifier to **-JP|p**, e.g. **+k**_kind_, where kind may be _x_ (longitude) or _y_ (latitude). The default would just be degrees.
> 
> Alternatively, we use **-f**0x and **-f**0y instead to indicate the same information.
> 
> Other thoughts on this, @joa-quim, @meghanrjones and @seisman ?

This solution seems good to me.

**Comment by seisman** [comment]
> I am guessing we need to add a new modifier to **-JP|p**, e.g. **+k**_kind_, where kind may be _x_ (longitude) or _y_ (latitude). The default would just be degrees.

This makes more sense to me.

**Comment by zhong-yy** [comment]
> Thanks for the post. I guess GMT cannot know what the angular measures are, so it will need to be told. It looks like it assumes these are always longitudes. I think we need to contemplate a situation where we can communicate to **-JP** the following
> 
>     1. The angles are longitude: Formatting will be as for longitude.
> 
>     2. The angles are latitude: Formatting will be as for latitude.
> 
>     3. The angles are just angles: Formatting will be for angles with degree symbol only.
> 
> 
> I am guessing we need to add a new modifier to **-JP|p**, e.g. **+k**_kind_, where kind may be _x_ (longitude) or _y_ (latitude). The default would just be degrees.
> 
> Alternatively, we use **-f**0x and **-f**0y instead to indicate the same information.
> 
> Other thoughts on this, @joa-quim, @meghanrjones and @seisman ?

Thank you for your quick reply.  I'm looking forward to the new modifier. By the way, do you know how to enable the axis label for `JP`? In this example, I used `-Bya+l"Depth (km)"` and but "Depth (km)" didn't show.

**Comment by PaulWessel** [comment]
No such option at the moment. I am having a look.
