### ISSUE TITLE
Auto-legend in subplots doesn't work well in subplot mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5127]
**Full script that generated the error**

```
gmt begin map png
	gmt subplot begin 1x2 -Fs8c/8c -A
		gmt plot -Baf -W1p,blue -c0 -l"Line1" <<- EOF
		1 1
		5 5
		3 8
		EOF
		gmt plot -Baf -W1p,blue -c1 -l"Line2" <<- EOF
		1 1
		5 5
		3 8
		EOF
		gmt plot -Baf -W1p,red -c0 -l"Line3" <<- EOF
		1 1
		2 4
		3 8
		EOF
	gmt subplot end
gmt end show
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/3974108/114311069-401aeb80-9abb-11eb-9b16-5f7897046d15.png)

**Expected outcome**

Two legend entries in panel (a).

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.2.0rc1

**Comment by PaulWessel** [comment]
This cannot be done: Switching panels around and use auto-legend.  It would require us to maintain, via temp files, all the information per panel and then at subplot end revisit all the panels to set things up.  It would be a major break with how we do it now.  So the solution here is to improve the docs to make clear that if you use the auto legend then you must complete all your plotting in a panel before moving to another.

**Comment by seisman** [comment]
> So the solution here is to improve the docs to make clear that if you use the auto legend then you must complete all your plotting in a panel before moving to another.

Sounds good to me.
