### ISSUE TITLE
curl problem between gmt and anaconda

### ISSUE THREAD

**Issue by JouSF-1409** [GenericMappingTools/gmt#5135]
it's me again. terribly sorry.

I was installing gmt on a brand new PC running Archlinux. 
After fixing the zsh git plugin problem. gmt still met the problems of curl when start like this
![curl](https://user-images.githubusercontent.com/81711503/114673274-9779bf80-9d38-11eb-996f-dd7a994233c5.png)

It's mainly because of 'curl' in /anaconda/bin, which replace the default curl of the system. 
It can be checked by command $ which curl. 
few instructions available on CSDN suggest to rename anaconda while installing and running gmt OR using $conda remove curl
like these bellow
[rename](https://blog.csdn.net/greenapple_shan/article/details/51222178)
[conda remove](https://blog.csdn.net/jinglingli_SJTU/article/details/53672151)

after quite some time, I tried out two ways to get rid of  this easily, 
1. install miniconda instead
2. while installing anaconda, chose no in the option init. or comment them when there's no need for anaconda

I think there's need to refer to this in guidelines of installing gmt on Archlinux.

BTW I see gmt 6.1.1 on community repo while trying to fix.  What's the difference?

**Comment by seisman** [comment]
This is not a GMT bug. The linking problem can happen on any operating system when multiple libraries of the same package (e.g., curl) co-exist.
