### ISSUE TITLE
Add PDF files for "Chart of Octal Codes for Characters"

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5141]
This page (https://docs.generic-mapping-tools.org/dev/cookbook/octal-codes.html) provides two charts for octal codes of characters. 

The two PNG images have low resolutions. It would be better to add high-resolution PDF files, similar to what we do for the GMT RGB charts (https://docs.generic-mapping-tools.org/dev/gmtcolors.html).

I'd like to help if you agree.

**Comment by PaulWessel** [comment]
Yes, please.  Those are ugly looking low res PNGs...

**Comment by PaulWessel** [comment]
I mistakenly gave myself a thumbs-up so I added a thumbs-down to not be too self-congratulatory....
