### ISSUE TITLE
GMTMEX is broken on Windows.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5145]
The change in ``gmtmex.c`` that added the ``free (X);`` have turned out to be completely fatal on Windows. It kills Matlab. In Julia I call the ``gmt_free_func()`` on X and nothing bad happens.

**Comment by PaulWessel** [comment]
Yes, I guess it is the age old cannot free something allocated in one dll in another dll shits on Windows.  So the solution would then be to have to export gmt_free_func on Windows so that it can be used.  How super-annoying is that.

**Comment by PaulWessel** [comment]
I'll work on this soon - have a zoom then another zoom.

**Comment by joa-quim** [comment]
Uh, yes. I had even forgotten that.

**Comment by PaulWessel** [comment]
There are two options to this:

1. Let _GMT_Destroy_Data_ call _gmt_M_free_ when the input vector is not any of the recognized families (**GMT_IS_GRID**, etc).  I would then undo my changes for the allocation of that **GMT_RESOURCES** array of structs to use GMT's memory allocation and then gmtmex.c can use `GMT_Destroy_Data (API, &X)`.
2. Add another function to the API called _GMT_Free_ (API, void *ptr) that would free GMT-allcoated memory outside GMT, and hence gmtmex.c would call `GMT_Free (API, X)` instead.  And again I would change the allocation to use GMT allocation stuff.

I think the first might be simpler as it does not extend the API.  Again, this is only an issue for Windows but we want the external code to be the same.  THoughts, @joa-quim @meghanrjones @seisman ?

**Comment by PaulWessel** [comment]
And I think we need to do this now before wrapping rc1, hence fast decisions...

**Comment by joa-quim** [comment]
I actually prefer second option as it can be applied to future situations like this. We actually already had one such function but it was dropped somewhere along the route.

**Comment by PaulWessel** [comment]
OK, that is fine.  It will keep the API cleaner.
