### ISSUE TITLE
FONT_ANNOT black ignored with -B+t+s

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#5156]
**Description of the problem**

When using a plot subtitle via `-B+t+s` the annotation color `FONT_ANNOT black` gets ignored and the annotation is colored in `MAP_FRAME_PEN`. This seems only true for `FONT_ANNOT black`. All other colors get honored. 

When using `-B+t`, `FONT_ANNOT black` and `MAP_FRAME_PEN green` everything works as expected:

![black_no_subtitle](https://user-images.githubusercontent.com/45796239/115236199-5bb96e00-a11b-11eb-9a79-08e550284895.png)

The same as above but now with an additional subtitle `-B+t+s`:

![black_subtitle](https://user-images.githubusercontent.com/45796239/115236203-5c520480-a11b-11eb-8d17-0c873a0c4328.png)

Observe how the map annotations became the color of `MAP_FRAME_PEN` instead of black. When doing the same with another color than black, e.g.  `FONT_ANNOT red`, everything works as expected:

![red_subtitle](https://user-images.githubusercontent.com/45796239/115236206-5cea9b00-a11b-11eb-98f7-65ae35394b4f.png)

**Full script that generated the error**

```
#!/usr/bin/env bash

### FAILS - black, subtitle ###
gmt begin black_subtitle png
  gmt basemap -R-24.46/-23.99/16.45/16.72 -Jm1:800000 -Bga \
    -B+t"FONT_ANNOT black"+s"I'm a Subtitle" \
    --FONT_ANNOT=black \
    --MAP_FRAME_PEN=green
gmt end show

### WORKS - black, no subtitle ###
gmt begin black_no_subtitle png
  gmt basemap -R-24.46/-23.99/16.45/16.72 -Jm1:800000 -Bga \
    -B+t"FONT_ANNOT black" \
    --FONT_ANNOT=black \
    --MAP_FRAME_PEN=green
gmt end show

### WORKS - red, subtitle ###
gmt begin red_subtitle png
  gmt basemap -R-24.46/-23.99/16.45/16.72 -Jm1:800000 -Bga \
    -B+t"FONT_ANNOT red"+s"I'm a Subtitle" \
    --FONT_ANNOT=red \
    --MAP_FRAME_PEN=green
gmt end show

### WORKS - red, no subtitle ###
gmt begin red_no_subtitle png
  gmt basemap -R-24.46/-23.99/16.45/16.72 -Jm1:800000 -Bga \
    -B+t"FONT_ANNOT red" \
    --FONT_ANNOT=red \
    --MAP_FRAME_PEN=green
gmt end show
```

**Actual outcome**

Map annotations become the color of the map frame if the color for map annotations is set to black and a subtitle is added. Map annotation colors other than black are honored.

**Expected outcome**

I expect the map annotations in the defined color regardless of subtitle.

**System information**

* Operating system: Linux
* GMT version (`gmt --version`): 6.2.0rc1

**Comment by meghanrjones** [comment]
Thanks for posting @KristofKoch, I will look into this now.

**Comment by meghanrjones** [comment]
@PaulWessel, the gsave/grestore block on L6197 - L6255 in `src/gmt_plot.c` does not seem to work well for isolating changes associated with subtitles. I have not been able to figure out a solution other than not adding the `V` and `U` to the postscript file, which I suspect would cause other issues.

**Comment by PaulWessel** [comment]
Sorry preoccupied.  Will start on this later this pm.
