### ISSUE TITLE
Bug in example21

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5158]
I run ex21.sh and I get this error:

`ex21.sh: 14: Syntax error: "(" unexpected`

Line 14:
`	wesn=($(gmt info -fT -I50 -C @RHAT_price.csv --FORMAT_DATE_IN=dd-o-yy))`

I add double quotes to fix the error but I get the following error:

`ex21.sh: 15: Bad substitution`

Line 15:
`	R="-R${wesn[0]}/${wesn[1]}/${wesn[2]}/${wesn[3]}"`

I don't know how to fix it. If you tell me I can do a PR.

**Comment by seisman** [comment]
Are you using bash on Linux, or else?

**Comment by Esteban82** [comment]
Mmm, I am not completed sure. I am using ubuntu 20.04. And I run the script writing ` sh ex.21 sh`. But now I try the original script with bash (bash ex21.sh) and it works. There is NO bug. Sorry. Should I always use bash??

**Comment by seisman** [comment]
`sh` and `bash` are not the same. As I understand it, `bash` support more syntax than `sh` (e.g., arrays as used in line 14).
