### ISSUE TITLE
Broken link to 6.2.0rc1 in the docs

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5161]
**Description of the problem**

The 'latest' option in the GMT documentation (https://docs.generic-mapping-tools.org/latest/index.html#) correctly links to 6.2.0rc1, but the 6.2rc1 dropdown does not work (https://docs.generic-mapping-tools.org/6.2rc1). I think it is an option to manually fix the links following these methods but with GMT tags (https://github.com/GenericMappingTools/pygmt/issues/1149#issuecomment-818249811). But, in my opinion it would also be fine to fix as part of the next release candidate.

**Comment by seisman** [comment]
The 6.2.0rc1 documentation doesn't show the switch:
![image](https://user-images.githubusercontent.com/3974108/115493436-c5c43700-a231-11eb-82f1-b3830093ae58.png)

I think it's because the regex doesn't match the URL of RC releases.

https://github.com/GenericMappingTools/gmt/blob/b5bad9b5fefbe01563c5159c875c87a012663079/doc/rst/_static/version_switch.js#L9

**Comment by meghanrjones** [comment]
> The 6.2.0rc1 documentation doesn't show the switch:
> ![image](https://user-images.githubusercontent.com/3974108/115493436-c5c43700-a231-11eb-82f1-b3830093ae58.png)
> 
> I think it's because the regex doesn't match the URL of RC releases.
> 
> https://github.com/GenericMappingTools/gmt/blob/b5bad9b5fefbe01563c5159c875c87a012663079/doc/rst/_static/version_switch.js#L9

Yes, I agree that this is likely the problem. A secondary problem is that I mistakenly switched the version and title in #5159. Do you think it is better to update the regex to allow for release candidate URLS or to not include a switch for pre-releases?

**Comment by seisman** [comment]
I think it's better to update the regex so that people can easily compare any two versions of a single page.

**Comment by meghanrjones** [comment]
> I think it's better to update the regex so that people can easily compare any two versions of a single page.

I agree. I can work on this, but I have not been able to get the local testing of the switch to work. Do you have any recommendations for testing locally?

**Comment by seisman** [comment]
> Do you have any recommendations for testing locally?

There is a detailed instruction in the PyGMT PR: https://github.com/GenericMappingTools/pygmt/pull/621
