### ISSUE TITLE
Polar projection should not assume angles are longitudes by default

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5167]
**Description of the problem**

The issue was first reported in https://github.com/GenericMappingTools/pygmt/pull/1221.

**Full script that generated the error**

```
gmt basemap -R0/360/0/1000 -JP8c -Bafg -png map
```
For **-JP8c**, the data is Cartesian polar projection. The v6.1.1 image is correct, but in v6.2.0rc1, GMT assumes the angles are longitudes.

| GMT v6.1.1 | GMT v6.2.0rc1 |
|---|---|
| ![](https://asset.cml.dev/ea131c95dd88b5de18bfad80df7f3516657021d7?cml=png "pygmt/tests/baseline/test_basemap_polar.png") | ![](https://asset.cml.dev/23932acecada49cb47618bcc2409c580ed3c2b9d?cml=png "pygmt/tests/baseline/test_basemap_polar.png") |

**System information**

* GMT version (`gmt --version`): 6.2.0rc1

**Comment by PaulWessel** [comment]
I think this is what #5124 is all about, no?

**Comment by seisman** [comment]
Yes, the issue should be fixed by #5124.

**Comment by PaulWessel** [comment]
Fixed via #5124.
