### ISSUE TITLE
Additional options for gmtinfo -T

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#5173]
**Description of the desired feature**

This was originally posted on the GMT Forum. Paul suggested I post it here.

I noticed that the same kinds of features for -T in grdinfo (particularly the +a and +s sub-options) are not available in the -T option for gmtinfo.

From the man page for grdinfo:

Determine min and max data value. If dv is provided then we first round these values off to multiples of dv. To exclude the two tails of the distribution when determining the min and max you can add +a to set the alpha value (in percent [2]): We then sort the values, exclude the data in the 0.5*alpha and 100 - 0.5*alpha tails, and revise the min and max. To force a symmetrical range about zero, using minus/plus the max absolute value of the two extremes, append +s. 

This is a request that the +a and +s sub-options be added to gmtinfo. Thanks!

**Are you willing to help implement and maintain this feature?** Yes - Happy to help in unit testing. Once implemented, it likely won't require much maintenance.

**Comment by joa-quim** [comment]
I'm afraid this will not be addressed anytime soon.
