### ISSUE TITLE
grdimage does not plot subsets of data correctly on a global map

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5180]
This issue has the same name as one reported to the [pygmt](https://github.com/GenericMappingTools/pygmt/issues/732) issues page, but it is the same problem in the GMT core:

```
gmt grdmath -R0/220/-30/90 -I1 -fg 0 1 RAND = t.grd
gmt grdimage t.grd -Rg -JW0/8i -B -png bad

```
which gives

![bad](https://user-images.githubusercontent.com/26473567/116507279-aa24e600-a85a-11eb-83eb-d1bfa635b372.png)

Letting @GenericMappingTools/pygmt-admin know as well.

**Comment by weiji14** [comment]
I just ran the code in https://github.com/GenericMappingTools/gmt/issues/5180#issue-870635437 on GMT master (commit 81da2a2884793332216eb97690f1c5c136333f5f) and it's giving me this image:

![bad](https://user-images.githubusercontent.com/23487320/116639266-3b5f9e00-a9bc-11eb-9342-d2241ed89e37.png)

Is this correct?

**Comment by seisman** [comment]
@PaulWessel Please double-check it again.

**Comment by PaulWessel** [comment]
OK, just did.  It works fine for me.  The gray is a function of the CPT.  Add -Q to not see it or pick a CPT (like vik) that has white.

**Comment by PaulWessel** [comment]
To be crystal clear, I just ran

```
gmt grdmath -R0/220/-30/90 -I1 -fg 0 1 RAND = t.grd
gmt grdimage t.grd -Rg -JW180/8i -B -Q -png bad1
gmt grdimage t.grd -Rg -JW0/8i -B -Q -png bad2
```

**Comment by seisman** [comment]
> The gray is a function of the CPT. Add -Q to not see it or pick a CPT (like vik) that has white.

It means the gray region contains NaN values, but the `t.grd` has no values at the region, so it should be transparent even without **-Q**, no?

**Comment by PaulWessel** [comment]
Well, the projected grid has to be a rectangle, so that is what it looks like.  We can discuss if in these situations we should automatically set up a clip path before laying down the rectangle, but that has never been done.  it has always been like this.

**Comment by seisman** [comment]
> the projected grid has to be a rectangle

I have no idea what a projected grid means.

The following commands work as I expect, so what's the difference between the above `t.grd` and the `t0.grd` here?
```
gmt grdcut @earth_relief_01d -R0/220/-30/90 -Gt0.grd
gmt grdimage t0.grd -Rg -JW180/8i -B -Q -png bad1
gmt grdimage t0.grd -Rg -JW0/8i -B -Q -png bad2
```

**Comment by PaulWessel** [comment]
PostScript image is a rectangle, so any grdimage that is plotted in PostScript is projected and yields a rectangle.  What is not within the original lon/lat boundingbox is set to NaN.  Usually using -Q is really all you need.

Diference is the default CPT.  For @grids we use the default CPT listed in the server table.  For t.grd we get turbo I think.

**Comment by PaulWessel** [comment]
If we had started with letting the -Q behavior be the default long time ago and in fact not have a -Q option then we would not have this discussion.  However, grdimage came out before PostScript level 3 introduced colormasking so -Q was added later.

**Comment by seisman** [comment]
OK. It makes sense. Closing again.

**Comment by weiji14** [comment]
What about the white parts on the left and right of the oval? Is it meant to be white or colored by the grid (as with the `-JW180/8i` example)?

**Comment by PaulWessel** [comment]
If you refer to the white parts in the two figs at the far left and far right areas you posted above then I cannot reproduce those - it looks fine when I run those examples.

**Comment by weiji14** [comment]
Ah ok, I'll try and rebuild GMT master and try again. Thanks!

**Comment by PaulWessel** [comment]
Great, it is a recent fix so probably just not updated on your end (I hope!).
