### ISSUE TITLE
Confusing error messages when calling modules with arbitrary options

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#5183]
**Description of the problem**

Not a bug per se - more like a misleading error message when calling a module with a single option it can't digest.

**Full script that generated the error**

Wanted a list of the usable fonts and instead of `gmt text -L` I wrote `gmt plot -L`. 

```
gmt plot -L
```

**Full error message**
```
gmt [ERROR]: Shared GMT module not found: plot

ERROR: No module named plot was found.  This could mean one of four cases:
  1. There actually is no such module; please check your spelling.
  2. You used a modern mode module name while running in GMT classic mode.
  3. Module exists in the GMT supplemental library, but the library could not be found.
  4. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
Shared libraries must be in standard system paths or set via environmental parameter LD_LIBRARY_PATH.
```

**Actual outcome**

Saying something about the module `plot` not found which I found a bit misleading. 

**Expected outcome**

Say something along the lines that a user shouldn't use a module with options it can't digest. Same behaviour with `coast -R`, `text -T`, etc.

**System information**

* Operating system: Linux
* GMT version (`gmt --version`): 6.2.0_a6980cb_2021.04.28

**Comment by PaulWessel** [comment]
True, but I think we need to be water tight on the classic side to not know nothing about modern things since we want to ensure it is 100% backwards compatible with classic stuff.

**Comment by PaulWessel** [comment]
Given how this works I do not think we want to open the door to modern stuff from classic.  The error message number 2 above is the case so it is not misleading.  Only one of the 4 will apply to any case, obviously.

**Comment by KristofKoch** [comment]
> The error message number 2 above is the case so it is not misleading.

@PaulWessel while I understand your argumentation I see a bit of a problem for new users which are encouraged to only learn modern mode. Error message 2 is technically correct but hard to comprehend:

* `gmt text -L`: Calling a modern mode module with correct options and everything is fine
* `gmt plot -L`: Calling a modern mode module with a single incorrect option and now I'm supposed to know that I'm running in classic mode to make sense of the error message?

From a user perspective it is not clear why running a seemingly modern mode command `gmt plot` with a single incorrect option `-L` beams me into classic mode. Without that knowledge error message 2 doesn't make much sense. 

I know little about how GMT decides what's classic and what's modern mode. From experience I'm sure a lot of thought went into this mechanism. But maybe the case presented here is worth a second look?
