### ISSUE TITLE
Pspolar not showing polarity symbols.

### ISSUE THREAD

**Issue by SquirrelKnight** [GenericMappingTools/gmt#52]
**Description of the problem**
I am currently trying to plot polarity symbols with pspolar. I have checked that my input file is the correct format. Here is an example:

FLYN 73.08 104.71 u
HSNT 86.96 97.41 u
MTCH 81.97 96.36 u
PLMP 88.97 98.98 u

When running psplot, if I use the -T flag, the stations show up just fine, so I am not sure what could be preventing the symbols (in my case circles; -Sc 0.4) from showing up. I have tried different symbol sizes as well as different fill colours for the symbols.

-Jesse

**Full error message**
Unfortunately, there was no error message.
**System information**

* Operating system: OSX High Sierra
* Version of GMT: 5.4.4 (Homebrew install)

**Comment by leouieda** [comment]
@SquirrelKnight could you include the script or exact command you ran? It also helps if you include the images that are generated.

**Comment by SquirrelKnight** [comment]
[bathyfocmec_1_MT.pdf](https://github.com/GenericMappingTools/gmt/files/2334219/bathyfocmec_1_MT.pdf)

I've attached a PDF of the figure generated by my script. It is fairly long, so I will include the relevant snippet.

`if ($showpol == 1) then`
`awk 'NR==1 {print $12,$11,$13,$22,$23,$24,5,0,0}' $pol_file | gmt psmeca $region $projection -Sa2.5i -Z$depthscale -O -K -N>> $post_script_name #For HASH`
`set pol_lon = ` awk 'NR==1 {print $12}' $pol_file` #For HASH`
`set pol_lat = ` awk 'NR==1 {print $11}' $pol_file` #For HASH`
`awk '{if (NR!=1) {print $1,$2,$3,$4}}' $pol_file | gmt pspolar $region $projection -D$pol_lon/$pol_lat -N -M2.5i -Sc0.4 -T -h1 -O -K >> $post_script_name`
`endif`

The script essentially plots the focal mechanism in question, and then overlays the poles on top of the focal mechanism. pspolar did work for me with an older version of GMT on CentOS using this exact code, so I'm not sure what changed, and unfortunately there are no errors output when running my script.

**Comment by SquirrelKnight** [comment]
I'd like to note that upon looking at the figures very carefully, you can actually see dots 1 px large for the polarities (only after converting from ps 2 pdf). When zooming in on those dots, they don't become any larger. I also tried completely removing GMT and reinstalling with brew, but had no success after doing so.

**Comment by seisman** [comment]
@SquirrelKnight Can you give us a minimal example to reproduce this issue?

There are so many variables (e.g. `$pol_lon`) in the example you posted 20 days ago, which are meaningless to us.

A minimal example should look like this:
```
gmt psmeca -Fo -R85/89/25/50 -JX7i -P -M -Sm4i -N  -L -K -G150 -T0 << EOF > test.ps
87  35 -0.26 -0.71 0.97 -0.20 -0.61 2.60 27  0    0
EOF

gmt pspolar -R -J -D87/35 -M4i -N -Sc0.3i -Qe -B0 -O << EOF >> test.ps
1 147.8 53 c
2 318.6 53 c
3 311.9 53 c
EOF
```

**Comment by SquirrelKnight** [comment]
Hi,

I have made a small script and have also realized what the problem might be.

`set min_lon = "-129.5"
set max_lon = "-126.5"
set min_lat = "48.5"
set max_lat = "50"
set projection = "-JM14c"
set boundaries = "-Bxf0.25a0.5 -Byf0.25a0.5 -BWSne"
set region = "-R$min_lon/$max_lon/$min_lat/$max_lat"
set pol_file = "Event1_pol_HASH.txt"
set post_script_name = "test_pol.ps"

set pol_lon = -127.69666
set pol_lat = 49.67583
echo $pol_lon' '$pol_lat
gmt psmeca $region $projection -P -M -Sa4i -N -L -K -G150 -T0 << EOF > $post_script_name #For HASH
-127.69666 49.67583 27.690 9 30 -98 8 0 0
EOF
gmt pspolar -R -J -D$pol_lon/$pol_lat -M4i -N -Sc0.3i -T -Qe -O << EOF >> $post_script_name
FLYN  73.08 104.71 c
HSNT  86.96  97.41 c
MTCH  81.97  96.36 c
PLMP  88.97  98.98 c
SJ06 177.47  96.15 c
SJ07 183.04  99.01 c
SJ20 154.15 105.25 d  
SJ21 194.61 100.38 d  
SJ23 180.47 107.51 d  
SJ24 167.73 110.96 c  
SJ25 156.46 114.20 c  
SJ26 206.98  98.54 c  
SJ27 202.34 101.72 d  
SJ29 191.94 110.32 d  
SJ31 163.71 121.47 c  
SJ32 214.74 102.30 c  
SJ33 210.53 107.01 d  
SJ34 205.28 113.51 c  
ZBLS  59.99 100.72 c 
EOF`

It looks like because my data has takeoff angles higher than 90 degrees, they will not plot (the stations will, but the polarity circles will not). In this case, it is functionality I would like to see added. In the meantime, I believe by subtracting 90 from any takeoff angles higher than 90, and by subtracting 180 from the azimuth, I should be able to achieve similar results. Is that correct?

**Comment by 79seismo** [comment]
Note that your scale for psmeca is 4i which is scaled to a magntidue 5 earthquake, where as scale of pspolar is not. i.e., to get the correct projection, you have to scale your pspolar bubble as follows;
new_size=4/5*magnitude of the current event

example shell code
mag=2.5
ball_size='4i'
polar_ballsize=`echo "scale=3; ${ball_size::${#ball_size}-1}*$mag/5" | bc`

gmt pspolar -R -J -D$pol_lon/$pol_lat -M$polar_ballsize -N -Sc0.3i -T -Qe -O << EOF >> $post_script_name

I also suggest you use -V -P -K flags to check for bugs in your code.

**Comment by seisman** [comment]
@79seismo The size of the beachball is 4 inch, and not scale to the magnitude 5, since he uses `-M` option.

As what he said, the problem is that pspolar only plots polarities which take off from lower hemisphere, and ignore all upper-hemisphere polarities.

**Comment by 79seismo** [comment]
Is there a solution to this problem? Can you project up-going rays to the lower focal hemisphere? Thanks!

**Comment by seisman** [comment]
It turns out this is a pspolar bug and should be fixed in https://github.com/GenericMappingTools/gmt/pull/2461.
