### ISSUE TITLE
The SCM workflow fails

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5208]
See https://github.com/GenericMappingTools/gmt/runs/2536676855 for the latest run.

The workflows fails, possibly because the SCM site (https://www.fabiocrameri.ch/colourmaps/) was redesigned recently.

**Comment by PaulWessel** [comment]
OK, unless he added more tables perhaps we can tackle this after 6.2.0 is released?

**Comment by seisman** [comment]
Yes, we can fix it later.
