### ISSUE TITLE
Confusion for header records to pstext paragraph mode

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5250]
I noticed a script I have used for a figure started to fail.  Isolating the issue:

```
cat << EOF > t.txt
> 0.5 0 12p 0 Times-Roman CM 12p 0.9i c
"Black Box" Filter
EOF
gmt pstext -R0/1/-0.5/1 -JX1i/0.75i -P -M -Glightgray -W1p -F+f+a+j -N -V t.txt > t.ps
```

The problem is that GMT defaults for what constitutes a data header record is controlled by **IO_HEADER_MARKER** which has as default the list of characters `#%!;"',#`, where the comma separates input and output header markers.  This list is newer than my script and causes the script to fail, hence not backwards compatible.  But wait, when we read input to **pstext -M** we are reading plain text sentences, hence it makes no sense to look for header records in the middle of this.  So the solution here seems to be to temporarily reset the input **IO_HEADER_MARKER** to just # so that quoted text and percentages can pass as given

Agreed, @joa-quim @meghanrjones @seisman ?

**Comment by meghanrjones** [comment]
That solution is good.

I don't know what our welcome bot is doing here...
