### ISSUE TITLE
Add plot -Ar|t to draw lines following theta or r direction in polar projections

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5260]
**Description of the desired feature**

Originally posted in the [forum](https://forum.generic-mapping-tools.org/t/1719).

For polar projections, there is no simple way to draw lines along the theta or r direction. It would be good to add **-Ar|t** to draw lines (1) **-Ar**: following the r direction then theta direction; (2) **-At**: following the theta direction then r direction.

**A minimal example:**
```
gmt begin map
gmt basemap -R0/60/0/10 -JP10c -Baf
gmt plot -W2p,red -At << EOF
0  5
60 5
EOF
gmt end show
```

**Expected output:**
![image](https://user-images.githubusercontent.com/3974108/119432639-b2016a00-bce2-11eb-8bfd-364b4afea2c9.png)

**Comment by PaulWessel** [comment]
Closed via #5263.
