### ISSUE TITLE
Improve the readability of the animation examples?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5268]
**Description of the desired feature**

I will take the [anim01.sh](https://github.com/GenericMappingTools/gmt/blob/master/doc/examples/anim01/anim01.sh) as an example. The code to generate the main script is:

```
# 2. Set up the main frame script
cat << EOF > main.sh
gmt begin
#	Plot smooth blue curve and dark red dots at all angle steps so far
	last=\$(gmt math -Q \${MOVIE_FRAME} 10 MUL =)
	gmt convert sin_curve.txt -Z0:\${last} | gmt plot -W1p,blue -R0/360/-1.2/1.6 -JX3.5i/1.65i -X0.35i -Y0.25i
	gmt convert sin_point.txt -Z0:\${MOVIE_FRAME} | gmt plot -Sc0.1i -Gdarkred
#	Plot bright red dot at current angle and annotate
	gmt plot -Sc0.1i -Gred <<< "\${MOVIE_COL0} \${MOVIE_COL1}"
	printf "0 1.6 a = %3.3d" \${MOVIE_COL0} | gmt text -F+f14p,Helvetica-Bold+jTL -N -Dj0.1i/0.05i
gmt end
EOF
```
In the script, we use `\$` a lot to avoid expanding these variables when generating the main script. 

Usually, I feel the "anmi01.sh" difficult to read and sometimes confusing due to the use of `\$`. It's possible to suppress variable expansion by simply using `'EOF'` rather than `EOF` (see https://stackoverflow.com/questions/31645341/how-to-suppress-variable-substitution-in-bash-heredocs for the original post).

Here is the new code using `'EOF'`:
```
# 2. Set up the main frame script
cat << 'EOF' > main.sh
gmt begin
#	Plot smooth blue curve and dark red dots at all angle steps so far
	last=$(gmt math -Q ${MOVIE_FRAME} 10 MUL =)
	gmt convert sin_curve.txt -Z0:${last} | gmt plot -W1p,blue -R0/360/-1.2/1.6 -JX3.5i/1.65i -X0.35i -Y0.25i
	gmt convert sin_point.txt -Z0:${MOVIE_FRAME} | gmt plot -Sc0.1i -Gdarkred
#	Plot bright red dot at current angle and annotate
	gmt plot -Sc0.1i -Gred <<< "${MOVIE_COL0} ${MOVIE_COL1}"
	printf "0 1.6 a = %3.3d" ${MOVIE_COL0} | gmt text -F+f14p,Helvetica-Bold+jTL -N -Dj0.1i/0.05i
gmt end
EOF
```

I think changing `EOF` to `'EOF'` improves the readability of the anim scripts.

**Comment by PaulWessel** [comment]
Brilliant!  Thanks @seisman for finding this - it is super annoying to do the backslashes and it scares people. Might a clever script do the replacements?

**Comment by PaulWessel** [comment]
Suggest this awaits the 6.2.0 release first.

**Comment by PaulWessel** [comment]
Second thought, seems simple enough to do, now done, and probably should be added before 6.2.

**Comment by meghanrjones** [comment]
Can this be closed now?

**Comment by seisman** [comment]
A Chinese user reported to me that the `'EOF'` syntax may not work when using "Git Bash on Windows", but I can't verify it.

**Comment by meghanrjones** [comment]
> A Chinese user reported to me that the `'EOF'` syntax may not work when using "Git Bash on Windows", but I can't verify it.

OK I will test this on Git Bash.

**Comment by meghanrjones** [comment]
I tested two of the animations (anim01 and anim02) with 'EOF' syntax on Git Bash on Windows and they worked for me.

**Comment by seisman** [comment]
> I tested two of the animations (anim01 and anim02) with 'EOF' syntax on Git Bash on Windows and they worked for me.

Great! Then I think we can close the issue.
