### ISSUE TITLE
generate mean los velocity 

### ISSUE THREAD

**Issue by neda2133** [GenericMappingTools/gmt#5274]
Hello Dears
I generated the mean los velocity  and the output is as follows:

![image](https://user-images.githubusercontent.com/73532419/120029036-c909ca00-c00a-11eb-9c88-306e39b1ccf1.png)

What is the reason for this color?

**Comment by PaulWessel** [comment]
SInce you do not point out what color you mean I have to guess: You are wondering about the background checkerboard pattern? That is due to your image viewer as it does that to show transparent pixels.  Not in the file.

**Comment by PaulWessel** [comment]
Also, since this is not a bug or similar we recommend you post such questions on the [forum](forum.generic-mapping-tools.org).
