### ISSUE TITLE
Something's wrong with distances calculation in mapproject -L

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5295]
If I generate a geodesic circle with 100 km radius with Proj and compute the distance with ``mpapproject -L`` I get variable distances like this and all considerable different from 100 km.
(We also get an WARNING that should be there)
```
julia> Ddist = mapproject(c, L=(line=[0 0], unit=:e), j=:e, par=(PROJ_ELLIPSOID="WGS-84",), Vd=1)
        mapproject  --PROJ_ELLIPSOID=WGS-84 -je -L+ue
mapproject [WARNING]: Your distance mode (Great Circle) differs from your -j option (Geodesic) which takes precedence.
Vector{GMT.GMTdataset} with 1 segments
First segment DATA
36×5 Matrix{Float64}:
  0.0        0.904369   99330.7  0.0  0.0
  0.160413   0.889834   99352.1  0.0  0.0
  0.315668   0.846697   99413.6  0.0  0.0
  0.460773   0.776346   99507.2  0.0  0.0
  0.591064   0.681042   99621.0  0.0  0.0
  0.702354   0.563851   99740.3  0.0  0.0
  0.791067   0.428539   99850.1  0.0  0.0
  0.854355   0.279455   99936.3  0.0  0.0
  0.890187   0.121392   99988.0  0.0  0.0
  0.897411  -0.0405727  99998.7  0.0  0.0
  0.875796  -0.201233   99967.0  0.0  0.0
  0.826036  -0.355427   99896.9  0.0  0.0
```
taking just the first point in my Matlab Vincenty function I get it very close and most of the difference is probably due to truncation in input
```
>> vdist(0.904369,0,0,0)

ans =

          100000.030638943
``` 

If I use ``project -Z`` I also cannot recover the input circle radius with any **-j** option. Here the case is more fuzzy because ``project`` computes only spherical circles and it's not obvious that **-jg** is doing the same sphere, though I would expect so. 
```
project  -o0,1 -C0/0 -G10 -Z200 > circ.dat
mapproject -Lpt.dat+ue circ.dat
5.50104544457e-17       0.89831528412   98776.2018419   0       0
-0.0447809811942        0.897198516113  98778.9802858   0       0
-0.0894505753527        0.893850990596  98787.287538    0       0
...
```

**Comment by PaulWessel** [comment]
Hm, I do not think so, it least not based on this.

1. Your circle is no circle but a polygon of n vertices.  So **-L** will find the shortest path from (0,0) to the _mid-point_ of all those cords, never to your vertices.  I bet if you more densely sample your proj circle the closer you will get.  But all the imaginary points on that polygon between your points are always closer than your vertices. We take each pair of vertices to define a great circle and then find crossing with the orthogonal great circle from your point.  I know they in reality are meant to be a small circle in your case but that is not what mapproject knows.
2. Distance from 0,0 to your first vertez is 100000.030639via `echo 0 0 | gmt mapproject -G0/0.904369+ue --PROJ_ELLIPSOID=WGS-84 -je`, i.e. same as you since the same algorithm.
3. Not sure about **project -Z** yet though.

**Comment by joa-quim** [comment]
Hmm, we'll continue this later tonight or tomorrow (going to Lisbon), some comments.

1. Increasing the number of points in the polygonal circle made no sensible difference. 
2. I have now a pure Geodetic buffer function, which only ArcGIS has and even it it's not clear that it works for line segments. A zoom of my test case where a polyline does a tour around the pole and returns is shown bellow. The points are the remaining vertices after having made the union of many geodetic circles. I used some cheap statistic to remove the missing dots. Ideally, only the central dot of each group should be  retained ant that is what I was expecting the -L could provide.
https://github.com/GenericMappingTools/GMT.jl/blob/master/src/proj_utils.jl#L210

```
julia> D = buffergeo("laco_polar.dat", width=111100*2);
d_mean = 217093.77531789374
```
As you can see the buffer with is ``222200`` meters but the average distance given by ``mapproject -L`` is 217093
(maximum distance is 223669.24062684373)

zooming in that image you can see a red line which is the Matlab solution but this one is spherical only and the differences are tinny here but significantly larger at high latitudes. 

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/120832365-7d9a7300-c558-11eb-9f5a-f8ca2cea59f2.png)

**Comment by PaulWessel** [comment]
The **project -Z** is doing a poor-man's ellipse by creating a Cartesian one in an azimuthal equal area projection centered on the point and project back.  However, for a degenerate one (circle) I can certainly do an exact small circle instead via spherical trig.  Not sure if I know how to generate a spherical ellipse without the lazy projection trick though.
I will work on a branch that does the circle correctly.

**Comment by PaulWessel** [comment]
I got [equations](https://math.stackexchange.com/questions/903368/ellipse-like-on-sphere) for spherical ellipses now should be able to implement this in GMT. Just need to translate/rotate the ellipse to where it should go.

**Comment by PaulWessel** [comment]
Note that you may need to set **PROJ_ELLIPSOID**=Sphere for things to make sense since we are doing spherical calculations in -L and -Z.

**Comment by joa-quim** [comment]
See this. The figure shows just the first segment and the mean distance from points to line is ~800 meters wrong. Note that the center line is a great circle in an ellipsoidal earth and from what you said ``mapproject -L`` connects the points of the center line by small circles, but the difference from both seems to be too small to explain the numbers provided by ``mapproject``.
```
julia> D = buffergeo("laco_polar.dat", width=222000);
mapproject [WARNING]: Your distance mode (Great Circle) differs from your -j option (Geodesic) which takes precedence.
d_mean = 221197.1921326989
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/120901391-73e53e00-c632-11eb-93b2-aefb7a8292c6.png)

**Comment by PaulWessel** [comment]
**mapproject -L** does not do anything using small circles - that would require a pole and a colatitude.  Everything is great circles.  Sorry, what is the gmt command being run here?

**Comment by joa-quim** [comment]
For this test image I added these lines
```
		if (n==1)
			plot(D, proj=:merc, marker=:p)
			plot!(seg, marker=:p, lw=0.1, show=1)
			Ddist2line = mapproject(D, L=(line=seg, unit=:e), j=:e)
			d_mean = mean(view(Ddist2line[1].data, :, 3))
			@show(d_mean)
		end
```
after
https://github.com/GenericMappingTools/GMT.jl/blob/master/src/proj_utils.jl#L238

For you to reproduce it you need to update GMT.jl (master) and run something like this

```
D = buffergeo([0.0 0; 5 5], width=111111);
Ddist2line = mapproject(D, L=(line=[0. 0; 5 5], unit=:e), j=:e)
d_mean = mean(Ddist2line[1].data[:, 3])
```

**Comment by PaulWessel** [comment]
Checking that you are using **--PROJ_ELLIPSOID**=Sphere when you do these things since otherwise you get a mix of ellipsoidal and spherical results and they will easily give things like 100m to several km misfits.  We may in fact need **mapproject** to set things to sphere when spherical calculations are done.  Remember, unless sphere is set we pick an _authalic_ mean sphere radius and use auxiliary latitudes, so cannot possibly match ellipsoidal results, or results run with --PROJ_ELLIPSOID=Sphere:

`mapproject [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371008.7714 m, in meter.`

**Comment by joa-quim** [comment]
I don’t want sphere  I want ellipsoid and so I’m using -je which is supposed to use ellipsoid, not authalic sphere which is the default -jg 
(All this from memory since I’m writing from the phone).

**Comment by PaulWessel** [comment]
I understand, but you probably also understand that GMT does not support intersections of geodesics etc, only great circles.  So there is no way in GMT to get an ellipsoidal -L result.  You could probably get the nearest points and then use mapproject -G (which does support geodesics) and get improved numbers.

**Comment by joa-quim** [comment]
OK, but then we should not allow **-L** and **-je** together because that was the source of this misunderstanding 

> -je to select ellipsoidal (or geodesic) mode for the highest precision and slowest calculation time.

**Comment by PaulWessel** [comment]
I agree, and there may be other things like this.

**Comment by joa-quim** [comment]
Much closer now
```
julia> D = buffergeo([0.0 0; 5 5], width=111111, proj="+proj=longlat +a=6371000 +b=6371000 +no_defs", tol=0);
julia> Ddist2line = mapproject(D, L=(line=[0. 0; 5 5], unit=:e), par=(PROJ_ELLIPSOID=6371000,));
julia> d_mean = mean(Ddist2line[1].data[:, 3])
111047.51072930203
```
The ``tol=0`` above means no DP line simplification so the union of all circles is still a bit wiggling. Letting the automatic DP tolerance do it's job
```
julia> D = buffergeo([0.0 0; 5 5], width=111111, proj="+proj=longlat +a=6371000 +b=6371000 +no_defs");
julia> Ddist2line = mapproject(D, L=(line=[0. 0; 5 5], unit=:e), par=(PROJ_ELLIPSOID=6371000,));
julia> d_mean = mean(Ddist2line[1].data[:, 3])
111061.86224631214
```
slightly improves the result and is visually more appealing. I guess this is the limit of my method until I find a way to detect which point of each circle is exactly at the buffer width distance from the line.
