### ISSUE TITLE
Sort and separate the tests scripts

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/gmt#53]
GMT has a lot of test scripts that create and compare plots. What we don't have is a measure of how many modules these tests call and how much of the code is covered. The tests also take a long time to run so they're not good for running on TravisCI (we don't want to wait 40min for a build to finish).

Quoting @PaulWessel s email:

> See plot of test durations (log-scale in seconds).  So most are around a few seconds (1-10) with a few slow ones (70 s); this is on my laptop.  I also attach the sorted list (time, test).  Before I do anything else we can talk about what might be useful? Make a plot of “coverage” somehow, meaning how many times any gmt module is called within the 812 tests?  I think we wanted a very basic set that at least ran all modules once on a minimal data set.

![test-time-distribution](https://user-images.githubusercontent.com/290082/44814161-8542b700-ab77-11e8-8f9f-de6cde740c47.png)
Distribution of test times.

Here is a file with the timing information for each test script: [test_sorted.txt](https://github.com/GenericMappingTools/gmt/files/2333715/test_sorted.txt)

**Comment by leouieda** [comment]
To run these things on CI, it would be good to be able to specify different levels of tests that we want to run. Tests that are run on every build should be fast, ideally taking no more than 10min to run in total. We can run the full test suite with the slower tests on a nightly cron job. So it would help if we could "make test-fast" and  "make test-full", for example.

**Comment by leouieda** [comment]
cc @joa-quim @seisman

**Comment by seisman** [comment]
Inspired by https://github.com/obspy/obspy_github_api and https://github.com/obspy/obspy/blob/master/.travis.yml. 

Maybe we can separate it into several tests, and use some magic comment strings like `+DOCS`, `+TESTS:FULL`, `+TESTS:0` to trigger specific tests.

**Comment by joa-quim** [comment]
Closing on a *too old and stalled* criteria.
