### ISSUE TITLE
Test GMT_cmyk.sh fails

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5308]
Current output:

![image](https://user-images.githubusercontent.com/3974108/120931429-7d68b780-c6bf-11eb-9f21-e07a9e44567b.png)

Expected output:

![image](https://user-images.githubusercontent.com/3974108/120931447-8d809700-c6bf-11eb-9d2a-efda4d0bdb9c.png)

**Comment by PaulWessel** [comment]
Related to #5300; will be examining now - the fix seems to only apply to geographic and not Cartesian.
