### ISSUE TITLE
Running ctest picks up ~/gmt.conf and cause failures

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5310]
**Description of the desired feature**

I have noticed many times if that I have a stray ~/gmt.conf laying around then running all the tests can create several failures that are actually caused by settings in the gmt.conf file.  I have wasted time trying to track down what I thought were bugs that was simply due to these settings.

Any good solutions to this? I don't think we want to delete ~/gmt.conf - might it be possible to warn somehow?

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/blob/6670f87af7e3ef53361d98112310aa54f03092e4/test/gmtest.in#L263-L272

Can we run "gmt defaults -Du > gmt.conf" to always generate a system defaults file in the "current testing" directory?

**Comment by PaulWessel** [comment]
Isn't that what those **gmt set** commands will do (create a gmt.conf in the current dir?).  I think GMT always will check the home dir (at least for the classic tests) so as long as there is something there the tests can fail.  The reason I sometimes have a gmt.conf has to do with tracking down bugs etc, so for me it is OK to delete that file always.  Could we add

```
if [ -f ~/gmt.conf ]; then
	rm -f ~/gmt/conf
fi
```

I don't this this will bother any of us developers who are the only ones (plus the CI) running the tests.

**Comment by seisman** [comment]
> Isn't that what those **gmt set** commands will do (create a gmt.conf in the current dir?).

But the **gmt set** command only add the changed settings in the "gmt.conf" file, not the full "gmt.conf". Thus `~/.gmt.conf` still has side-effects. Instead, `gmt defaults -Du` generates the full "gmt.conf", so any settings in `~/.gmt.conf` will be override by the local "gmt.conf".


> The reason I sometimes have a gmt.conf has to do with tracking down bugs etc, so for me it is OK to delete that file always. Could we add
> 
> ```
> if [ -f ~/gmt.conf ]; then
> 	rm -f ~/gmt/conf
> fi
> ```
> 
> I don't this this will bother any of us developers who are the only ones (plus the CI) running the tests.

I actually prefer to raise an error rather than silently deleting it.

**Comment by PaulWessel** [comment]
I agree an error would be preferable.  I guess if that if-test had an echo "Please remove ~/gmt.conf" then exit the tests will take 10 seconds and we would know something is up, check the log, and be wiser.  Would that be OK?

**Comment by seisman** [comment]
Yes, sounds good.
