### ISSUE TITLE
gmt coast with -E does not automatically set region correctly

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5314]
**Description of the problem**
An example in the coast documentation does not work correctly. More information in [this PR discussion](https://github.com/GenericMappingTools/gmt/pull/5313). 

**Full script that generated the error**

```
gmt coast -JM6i -Baf -EGB,IT,FR+gblue+p0.25p,red -EES,PT,GR+gyellow -pdf map
```

**Actual outcome**

![map](https://user-images.githubusercontent.com/14077947/121073463-8e3d2a00-c7a0-11eb-8f4d-764121eca9eb.png)

**Expected outcome**
![good-map](https://user-images.githubusercontent.com/14077947/121073546-a2812700-c7a0-11eb-9e94-e99d8dea44c1.png)

**System information**

* Operating system: MacOS Big Sur
* GMT version (`gmt --version`): 6.2.0

**Comment by seisman** [comment]
Hmmm, actually it really works for me.

I got the wrong image when I have a unrelated "gmt.history" file from previous runs.

**Comment by meghanrjones** [comment]
> Hmmm, actually it really works for me.
> 
> I got the wrong image when I have a unrelated "gmt.history" file from previous runs.

Same here, sorry. I incorrectly assumed that one-liners were immune to this.

**Comment by meghanrjones** [comment]
I'll submit a PR with the docs updates from https://github.com/GenericMappingTools/gmt/pull/5313#issuecomment-856177893 to clarify that -R is not required with -E.
