### ISSUE TITLE
Improve the error message when the custom symbol def file is not found

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5338]
**Description of the problem**

```
gmt plot @Top12Cities.txt -Skjunk/0.25c -Gred -W0.5p -pdf map
plot [ERROR]: Option -S: Parsing failure
```
When the custom symbol file is not found, GMT reports the "Option -S: Parsing failure" error. The error message is unclear and should be improved. I expect to see an error like:
```
Option -S: Custom symbol definition file `junk.def` or `junk.eps` is not found.
```

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.3.0_5900853_2021.06.15

**Comment by PaulWessel** [comment]
Agreed, having a look.
