### ISSUE TITLE
Improve usage documentation and break synopsis lines for all GMT modules

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5341]
https://github.com/GenericMappingTools/gmt/pull/4796/ added a `GMT_Usage` function to improve the formatting for GMT command line modules and updated the syntax for plot, basemap, and all the common options. Now, it is necessary to update the syntax for all the other modules. Help is greatly appreciated!

The documentation for GMT_Usage is in `src/gmt_api.c` at line 13563. In general, calls to `GMT_Message(API, GMT_TIME_NONE,…` will be replaced with `GMT_Usage(API, indent_level, …`, where `indent_level` is one of the following:

`0`: for synopsis message
`1`: for listing of options (e.g., -R, -J, etc.), which will be wrapped and indented if it continues past one lint.
`-1`: for the same indentation level as one, but without further indentation if it exceeds one line.
`2`: for a paragraph under an option that should be wrapped and indented if it exceeds a line.
`-2`: Same as -1 but for level 2
`3`: for separating modified under an option
`-3`: same as -1 but for level 3
And so on...

Steps for updating the usage message for a module (subject to revision):
1. The checklist below includes all the GMT modules. Before starting working on a module, add your name next to the module in the checklist. If you do not have edit access, post a comment requesting that your name be added next to the module in the checklist. This is an important step to coordinate efforts among different contributors.
2. Find the source code for the module that you will work on. For example the source code for `batch` is `src/batch.c`.
3. Find the section of the source code that creates the usage message (e.g., search for `usage:`)
4. Reformat the usage message from multiple calls to `GMT_Messsage(API, GMT_TIME_NONE,…` to a single call to `GMT_Usage (API, 0…`
5. Reformat the messages that list options from `GMT_Message (API, GMT_TIME_NONE, “\t…` to `GMT_Usage (API, 1 “\n…`
6. Reformat the option descriptions from multiple calls to `GMT_Message (API, GMT_TIME_NONE, “\t…` to one call to `GMT_Usage (API, -2, “…`
7. Reformat the modifiers/directives descriptions from calls to `GMT_Message (API, GMT_TIME_NONE, “\t…` to calls to `GMT_Usage (API, 3, “…`, with one GMT_Usage call per modifier/directive.
8. Update any `gmt_*_syntax` calls.
9. Options that take no arguments whatsoever (e.g., -N) can be set on the same line as the explanation.

To do:
- [x] batch Paul
- [x] begin Kristof
- [x] blockmean Paul
- [x] blockmedian Paul
- [x] blockmode Paul
- [x] clear Kristof
- [x] dimfilter Paul
- [x] docs Kristof
- [x] end Kristof
- [x] figure Kristof
- [x] filter1d Paul
- [x] fitcircle Meghan
- [x] gmt2kml Paul
- [x] gmtbinstats Meghan
- [x] gmtconnect Paul
- [x] gmtconvert Paul
- [x] gmtdefaults Paul
- [x] gmtget Paul
- [x] gmtinfo Kristof
- [x] gmtlogo Paul
- [x] gmtmath Paul
- [x] gmtregress Paul
- [x] gmtselect Paul
- [x] gmtset Paul
- [x] gmtsimplify Paul
- [x] gmtspatial Paul
- [x] gmtsplit Paul
- [x] gmtvector Paul
- [x] gmtwhich Meghan
- [x] grd2cpt Paul
- [x] grd2kml Paul
- [x] grd2xyz Paul
- [x] grdblend Paul
- [x] grdclip Paul
- [x] grdcontour Paul
- [x] grdconvert Meghan
- [x] grdcut Paul
- [x] grdedit Paul
- [x] grdfft Paul
- [x] grdfill Paul
- [x] grdfilter Paul
- [x] grdgdal Meghan
- [x] grdgradient Paul
- [x] grdhisteq Paul
- [x] grdimage Paul
- [x] grdinfo Paul
- [x] grdinterpolate Meghan
- [x] grdlandmask Meghan
- [x] grdmask Meghan
- [x] grdmath Paul
- [x] grdmix Paul
- [x] grdpaste Paul
- [x] grdproject Paul
- [x] grdsample Paul
- [x] grdtrack Paul
- [x] grdtrend Paul
- [x] grdvector Paul
- [x] grdview Paul
- [x] grdvolume Paul
- [x] greenspline Paul
- [x] kml2gmt Paul
- [x] makecpt Paul
- [x] mapproject Paul
- [x] movie Paul
- [x] nearneighbor Paul
- [x] project Paul
- [x] psclip Paul
- [x] pscoast Paul
- [x] pscontour Paul
- [x] psconvert Paul
- [x] psevents
- [x] pshistogram Paul
- [x] psimage Paul
- [x] pslegend Paul
- [x] psmask Paul
- [x] psrose Paul
- [x] psscale Paul
- [x] pssolar Paul
- [x] psternary Paul
- [x] pstext Paul
- [x] pswiggle Paul
- [x] psxy
- [x] psxyz
- [x] sample1d Paul
- [x] spectrum1d Paul
- [x] sph2grd Paul
- [x] sphdistance Paul
- [x] sphinterpolate Paul
- [x] sphtriangulate Paul
- [x] subplot Paul
- [x] surface Paul
- [x] trend1d Paul
- [x] trend2d Paul
- [x] triangulate Meghan
- [x] xyz2grd Meghan
- [x] supplements/geodesy/earthtide Paul
- [x] supplements/geodesy/gpsgridder Paul
- [x] supplements/geodesy/psvelo Paul
- [x] supplements/gshhg/gshhg Paul
- [x] supplements/img/img2grd Paul
- [x] supplements/mgd77/mgd77convert Paul
- [x] supplements/mgd77/mgd77header Paul
- [x] supplements/mgd77/mgd77info Paul
- [x] supplements/mgd77/mgd77list Paul
- [x] supplements/mgd77/mgd77magref Paul
- [x] supplements/mgd77/mgd77manage Paul
- [x] supplements/mgd77/mgd77path Paul
- [x] supplements/mgd77/mgd77sniffer Paul
- [x] supplements/mgd77/mgd77track Paul
- [x] supplements/potential/gmtflexure Paul
- [x] supplements/potential/gmtgravmag3d Paul
- [x] supplements/potential/gravfft Paul
- [x] supplements/potential/grdflexure Paul
- [x] supplements/potential/grdgravmag3d Paul
- [x] supplements/potential/grdredpol Paul
- [x] supplements/potential/grdseamount Paul
- [x] supplements/potential/talwani2d Paul
- [x] supplements/potential/talwani3d Paul
- [x] supplements/segy/pssegyz Paul
- [x] supplements/segy/pssegy Paul
- [x] supplements/segy/segy2grd Paul
- [x] supplements/seis/pscoupe Paul
- [x] supplements/seis/psmeca Paul
- [x] supplements/seis/pspolar Paul
- [x] supplements/seis/pssac Paul
- [x] supplements/spotter/backtracker Paul
- [x] supplements/spotter/gmtpmodeler Paul
- [x] supplements/spotter/grdpmodeler Paul
- [x] supplements/spotter/grdrotater Paul
- [x] supplements/spotter/grdspotter Paul
- [x] supplements/spotter/hotspotter Paul
- [x] supplements/spotter/originater Paul
- [x] supplements/spotter/polespotter Paul
- [x] supplements/spotter/rotconverter Paul
- [x] supplements/spotter/rotsmoother Paul
- [x] supplements/x2sys/x2sys_binlist Paul
- [x] supplements/x2sys/x2sys_cross Paul
- [x] supplements/x2sys/x2sys_datalist Paul
- [x] supplements/x2sys/x2sys_get Paul
- [x] supplements/x2sys/x2sys_init Paul
- [x] supplements/x2sys/x2sys_list Paul
- [x] supplements/x2sys/x2sys_merge Paul
- [x] supplements/x2sys/x2sys_put Paul
- [x] supplements/x2sys/x2sys_report Paul
- [x] supplements/x2sys/x2sys_solve Paul

**Comment by PaulWessel** [comment]
Hi @KristofKoch, hoping you are inspired to help out with some of these.  Start with any of the ones with the fewest non-common options to get the hang of it.

**Comment by KristofKoch** [comment]
Hi @pwessel, I’ll join the effort as soon as I’m back home again.

**Comment by KristofKoch** [comment]
Hi @meghanrjones, surely a beginners question but would you kindly explain to me what you meant by

> 8. Update any gmt_vector_syntax, gmt_cont_syntax, or gmt_label_syntax calls.

**Comment by meghanrjones** [comment]
> Hi @meghanrjones, surely a beginners question but would you kindly explain to me what you meant by
> 
> > 1. Update any gmt_vector_syntax, gmt_cont_syntax, or gmt_label_syntax calls.

Good question, the indentation in those functions would need updating if used. But, those functions are only used in the files listed below so unless working with these files you do not need to worry about this step.
```
$ gmtfind 'gmt_vector_syntax'
./src/geodesy/psvelo.c
./src/gmt_init.c
./src/gmt_prototypes.h
./src/grdvector.c
./src/psrose.c
./src/psxy.c
./src/psxyz.c
$ gmtfind 'gmt_cont_syntax'
./src/gmt_init.c
./src/gmt_prototypes.h
./src/grdcontour.c
./src/pscontour.c
./src/psxy.c
./src/psxyz.c
$ gmtfind 'gmt_label_syntax'
./src/gmt_init.c
./src/gmt_prototypes.h
./src/grdcontour.c
./src/pscontour.c
./src/psxy.c
./src/psxyz.c
```

**Comment by KristofKoch** [comment]
Ok, I won't touch those …

**Comment by KristofKoch** [comment]
I think we can grow the list of `gmt_something_syntax` functions. I encountered the following as well …

```
gmt_dist_syntax
gmt_refpoint_syntax
gmt_mappanel_syntax
```

**Comment by meghanrjones** [comment]
> I think we can grow the list of `gmt_something_syntax` functions. I encountered the following as well …
> 
> ```
> gmt_dist_syntax
> gmt_refpoint_syntax
> gmt_mappanel_syntax
> ```

Thanks, I made the checklist more general. The original instructions were just based on Paul's original PR.

**Comment by KristofKoch** [comment]
Would you mind explaining to the uninitiated how to fix those functions @meghanrjones? I just stumbled over `gmt_pen_syntax` after doing the largest part of the reformatting work on `psclip`. 

Or, if too complicated, how to proceed from there? Push it anyway and have you or @PaulWessel fix the `gmt_*_syntax` calls?

**Comment by PaulWessel** [comment]
If any of the @GenericMappingTools/gmt-contributors would like to do a bit of C coding then these chores are great starting points.

**Comment by meghanrjones** [comment]
> Would you mind explaining to the uninitiated how to fix those functions @meghanrjones? I just stumbled over `gmt_pen_syntax` after doing the largest part of the reformatting work on `psclip`.
> 
> Or, if too complicated, how to proceed from there? Push it anyway and have you or @PaulWessel fix the `gmt_*_syntax` calls?

You could search for that function in gmt_init.c and update the GMT_Message calls in that function. But, if you prefer not to worry about it the other option is to open a PR with the changes that you have made and Paul or I could tackle the gmt_*_syntax calls.

**Comment by PaulWessel** [comment]
We are at 82%, @meghanrjones! I can see the light at the end of the tunnel I think.  Folks like @KristofKoch have taken their usual 5-week European vacation I think.  Those Europeans!

**Comment by meghanrjones** [comment]
> We are at 82%, @meghanrjones! I can see the light at the end of the tunnel I think. Folks like @KristofKoch have taken their usual 5-week European vacation I think. Those Europeans!

😄 I assigned myself a couple chores for tomorrow and can add mgd77 modules to my list if still there. So close!

**Comment by PaulWessel** [comment]
Before I forget, could you please open an issue where we replace the word stdout in message with "standard output"?  We do not have to be too obtuse on this.  I have been doing this but in the end we need to do some grepping on strings and stdout and stdin and stderr.

**Comment by PaulWessel** [comment]
Just letting @KristofKoch know I am doing psclip so that we are all done with this issue and can move on to more critical items.  Thanks for all the help!

**Comment by PaulWessel** [comment]
And we are done!  I suppose we should do a review of this to make sure we did not forget some hidden gmt_init.c explanation function that still needs updates...

**Comment by meghanrjones** [comment]
> And we are done! I suppose we should do a review of this to make sure we did not forget some hidden gmt_init.c explanation function that still needs updates...

Thanks for leading the way on this! And thanks @KristofKoch for your help!

There are no GMT_Message calls left in gmt_init.c. Are you thinking a different type of review?

**Comment by PaulWessel** [comment]
We did stare at the usage quite a bit so I am not eager to do mroe, but I did think perhaps we should do something like this (not tested)

gmt --show-modules | awk '{printf "gmt %s\n", $1' | sh -s >2 log

and just have a look.

**Comment by PaulWessel** [comment]
Apparently **psxyz** never made it over... will do that one now.

**Comment by meghanrjones** [comment]
@PaulWessel, do you see more to be done here or can we close the issue?

**Comment by PaulWessel** [comment]
We can close - any minor issues we discover can be dealt with separately.

**Comment by anbj** [comment]
I might have asked about this before (sorry); why do gmt send usage message to standard error instead of standard output?

**Comment by PaulWessel** [comment]
That is how UNIX was designed and has done since the dawn of time. Results go to stdout, input comes form stdin, and errors and warnings go on stderr.

**Comment by anbj** [comment]
I did not know that. Thanks for educating me.

**Comment by PaulWessel** [comment]
It was designed so you could do things like this:

```
(myprogram < myinput > myresults) >2 errorlog
if [ -s errorlog ]; then
 <send me email etc etc.>
fi
```

**Comment by PaulWessel** [comment]
Also, you can imagine it would not be great if a warning message ended up in the file myresults - it would choke the next tool that tries to access it.

**Comment by anbj** [comment]
Absolutely. Thanks again, Paul!
