### ISSUE TITLE
-Bs is incorrectly interpreted?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5344]
**Description of the problem**

The following command uses `-Bnesw` to plot 4 axes:
```
gmt basemap -R0/40/0/40 -JX4c/4c -Bnesw -Baf -png map
```
![image](https://user-images.githubusercontent.com/3974108/122440878-fd6a0980-cf6a-11eb-94d6-ee2b060e293c.png)

Use `-Bn` gives:

![image](https://user-images.githubusercontent.com/3974108/122440917-06f37180-cf6b-11eb-977a-6f91e0183f8f.png)

Use `-Bs` gives:

![image](https://user-images.githubusercontent.com/3974108/122441043-27233080-cf6b-11eb-854b-4505cf179c11.png)

GMT may incorrectly interpret `s` as the secondary axis/annotation/label.

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): `6.3.0_17131b2_2021.06.15`

**Comment by PaulWessel** [comment]
Hm, I note it works as expected if you place -Bs as the last -B option.  I think the order is important and I think I am actually sorting these options somewhere to ensure that but perhaps it is failing in this case.  It is true the -Bs is problematic given its multiple meanings...

**Comment by PaulWessel** [comment]
See gmt_parse.c function
`GMT_LOCAL void gmtparse_ensure_b_options_order (struct GMT_CTRL *GMT, struct GMT_OPTION *options);`
The fun thing about that function is that it sets up priorities for the various -B option as to how they should be sorted.
Then it does nothing...

**Comment by PaulWessel** [comment]
I am finally tackling the sorting of the options array - seems to work.  Doing testing now.  This means the user order will no longer matter as we do an internal shuffle.
