### ISSUE TITLE
-C KEY in ternary.c is no good

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5354]
The key for CPTs is "C-(" but with this it errors. It thinks both D (a dataset) and C (a cpt) are both datasets
```
ternary(D, labels=("Clay","Silt","Sand"), marker=:p, C=C)
_cmd = ["psternary  -R0/100/0/100/0/100 -JX14c -Baafg+lClay -Bbafg+lSilt -Bcafg+lSand --MAP_GRID_PEN_PRIMARY=thinnest,gray -C -Sp2p"]
```

Turning the key to "CC(" like in ``psxy`` makes it work.

**Comment by PaulWessel** [comment]
You can do a PR to fix it but as you can see there is unfinished work to do contouring and hence -C may need to support lists of contours like in pscontour.  But I can deal with that later. do CC( for now.
