### ISSUE TITLE
Color rendering in GMT-6.1~6.2 not match the exact value

### ISSUE THREAD

**Issue by TristanBlus** [GenericMappingTools/gmt#5365]
**Rendered color not matching the value.**

Starting from GMT-6.1, I found that the rendered color was incorrect (value - color not matching), which worked well in the older version, see the picture comparision same data and cpt. Note, the cpt file and data were exactlly the same. 

**Full script that generated the error**

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/37327637/122660184-dc472a00-d1b1-11eb-938d-7095cf36c522.png)
correct rendered color in GMT-6.0.0

**Expected outcome**

![image](https://user-images.githubusercontent.com/37327637/122660198-0d275f00-d1b2-11eb-9a0a-d026882cd96f.png)
same data and cpt file,  output in GMT-6.2.0

**System information**

* Operating system: Ubuntu-20.04
* GMT version (`gmt --version`): 6.1.0 ~ 6.2.0

**Comment by PaulWessel** [comment]
We won't be able to examine this without a small test data, cpt, script etc.  We have ~1000 test script that produces test plots that we check for any failures so if colors changes we would now.  For starters, perhaps you can post your CPT here?

**Comment by TristanBlus** [comment]
> We won't be able to examine this without a small test data, cpt, script etc. We have ~1000 test script that produces test plots that we check for any failures so if colors changes we would now. For starters, perhaps you can post your CPT here?

OK, the cpt file were attached.(renamed to '.txt)
Besides, i have tested standard cpt in GMT, it also failed to rendered correctly.

[shis.cpt.txt](https://github.com/GenericMappingTools/gmt/files/6681660/shis.cpt.txt)

**Comment by PaulWessel** [comment]
Here is your CPT rendered with ±0.6 intensities in GMT 6.0.0:

![6 0 0](https://user-images.githubusercontent.com/26473567/122660799-fc2e0d80-d11f-11eb-9688-acdaec83e437.png)

Here is your CPT rendered with ±0.6 intensities in GMT 6.2.0:

![6 2 0](https://user-images.githubusercontent.com/26473567/122660800-018b5800-d120-11eb-981f-a3456f9c29d3.png)

So just plotting the colorbars gives the same result.  In both cases they end up with reddish colors reminiscent of your 2nd plot.   The hue is basically driven by the grid values, so I am not sure if your data is actually exactly the same in that area, or if you are stretching it to a different range, or if there are other things outside my control to check.

**Comment by TristanBlus** [comment]
> Here is your CPT rendered with ±0.6 intensities in GMT 6.0.0:
> 
> ![6 0 0](https://user-images.githubusercontent.com/26473567/122660799-fc2e0d80-d11f-11eb-9688-acdaec83e437.png)
> 
> Here is your CPT rendered with ±0.6 intensities in GMT 6.2.0:
> 
> ![6 2 0](https://user-images.githubusercontent.com/26473567/122660800-018b5800-d120-11eb-981f-a3456f9c29d3.png)
> 
> So just plotting the colorbars gives the same result. In both cases they end up with reddish colors reminiscent of your 2nd plot. The hue is basically driven by the grid values, so I am not sure if your data is actually exactly the same in that area, or if you are stretching it to a different range, or if there are other things outside my control to check.

Yes, only colorbar were draw correctly in both version. And I used the exact same script/data file to plot the above two picture. So there should not be any difference.

**Comment by PaulWessel** [comment]
Might you be able to do a **grdcut** and extract a smaller grid covering the part that look very different between the two plots and pack that up with a script that makes a plot that still looks like that (i.e., not as you expect), then post here?  And you are saying if you switch to 6.0.0 the same script and data will give the other plot? That would let us check it out more carefully.

**Comment by TristanBlus** [comment]
> Might you be able to do a **grdcut** and extract a smaller grid covering the part that look very different between the two plots and pack that up with a script that makes a plot that still looks like that (i.e., not as you expect), then post here? And you are saying if you switch to 6.0.0 the same script and data will give the other plot? That would let us check it out more carefully.

Okay, i uploaded the related file and scripts, please check it.
[plot_color_test.zip](https://github.com/GenericMappingTools/gmt/files/6681822/plot_color_test.zip)

**Comment by PaulWessel** [comment]
Sorry, I get the same JPG images with 6.0.0 and 6.2.0.  Perhaps you had a broken ghostscript and now you have one that works? There were lots of bugs in gs the last years and often the Linux distros lag behind in updating.  
The 6.0.0 macos bundle shipped with gs 9.50 and today with 6.2.0 I am running gs 9.54.

Can you please confirm that you have two GMT versions installed and when you switch between them via gmtswitch you can run this same script and get two different results with the same gs?

**Comment by TristanBlus** [comment]
> Sorry, I get the same JPG images with 6.0.0 and 6.2.0. Perhaps you had a broken ghostscript and now you have one that works? There were lots of bugs in gs the last years and often the Linux distros lag behind in updating.
> The 6.0.0 macos bundle shipped with gs 9.50 and today with 6.2.0 I am running gs 9.54.
> 
> Can you please confirm that you have two GMT versions installed and when you switch between them via gmtswitch you can run this same script and get two different results with the same gs?

I'm sure i use the same gs version. While I switch between gmt-6.0.0 and gmt-6.2.0, I only modified the path of gmt root in my environment variables directly( not through gmtswitch ). In this way, I can ensure that only the gmt version were changed.

**Comment by TristanBlus** [comment]
> Sorry, I get the same JPG images with 6.0.0 and 6.2.0. Perhaps you had a broken ghostscript and now you have one that works? There were lots of bugs in gs the last years and often the Linux distros lag behind in updating.
> The 6.0.0 macos bundle shipped with gs 9.50 and today with 6.2.0 I am running gs 9.54.
> 
> Can you please confirm that you have two GMT versions installed and when you switch between them via gmtswitch you can run this same script and get two different results with the same gs?

Sorry, I have retest the script. And I found this bug is in the subplot module. The original script was written to draw a m*n subplot figure, and that's where the color found to be incorrectly rendered. When I rewrite the script to draw only one data ( only one frame, not subplot), all color were the same in both gmt version.
So, I think this may be a problem in subplot?

**Comment by PaulWessel** [comment]
It depends on where you create and set the CPT. If you set it before the **subplot begin** command then it applies to all figures.  if you set it inside then it applies to all panels, and if you set it later then will be stretched to each panel.  Perhaps check out [this explanation](https://docs.generic-mapping-tools.org/dev/makecpt.html#note-on-cpts-in-modern-mode).

**Comment by TristanBlus** [comment]
> It depends on where you create and set the CPT. If you set it before the **subplot begin** command then it applies to all figures. if you set it inside then it applies to all panels, and if you set it later then will be stretched to each panel. Perhaps check out [this explanation](https://docs.generic-mapping-tools.org/dev/makecpt.html#note-on-cpts-in-modern-mode).

the cpt were set before subplot in my script, it should be applied to all figures. And while switch the gmt version, the script has no change, so there should be no difference. That's why I guess a bug in the latest version.

**Comment by PaulWessel** [comment]
I think it is more likely we fixed a bug so the previous plot is wrong... but we will see. Could you perhaps pick a coordinate near the point on the map where the two images are most unlike (i.e., the deep red area) and use **grdtrack** on your grid and that point to read off the z-value that is then internally used to convert to color.  We can then see if that z-values should give the deep red or not given your CPT range.
I think it is more likely that the previous GMT version had a bug and would stretch the CPT for each panel (hence you get the full CPT range) than the other way around, since if it is _not_ stretched and kept 0-20 then perhaps this panel is not having z-values close to 20 and thus you get the more magenta image.

**Comment by TristanBlus** [comment]
> I think it is more likely we fixed a bug so the previous plot is wrong... but we will see. Could you perhaps pick a coordinate near the point on the map where the two images are most unlike (i.e., the deep red area) and use **grdtrack** on your grid and that point to read off the z-value that is then internally used to convert to color. We can then see if that z-values should give the deep red or not given your CPT range.
> I think it is more likely that the previous GMT version had a bug and would stretch the CPT for each panel (hence you get the full CPT range) than the other way around, since if it is _not_ stretched and kept 0-20 then perhaps this panel is not having z-values close to 20 and thus you get the more magenta image.

I'm pretty sure about that the color in older version was right, since I have check the value of input data several times. Also, as I said before, when I generate the figure without subplot, the color (in gmt-6.2.0) turn to be the same as the gmt-6.0.0 output, also same with the panel in subploted figure of gmt-6.0.

**Comment by PaulWessel** [comment]
OK, but a simple check is to do `echo lon lat  | gmt grdtrack -Gyourdatagrid.nc -nn` and post the value for the lon,lat of that deep red area.  Are you able to do that?

**Comment by TristanBlus** [comment]
The value of dark red region are about 18-19.5. I hava done that. Thanks

**Comment by PaulWessel** [comment]
OK, du you mind posting your script? I dont need your data as I will simulate that but good to see how many panels and where you define the CPT, etc, so I can do it the same way.

**Comment by TristanBlus** [comment]
Okay, I will send it through email, including data and CPT.

**Comment by PaulWessel** [comment]
Thanks, tracing this to a change in either GMT or GDAL related to reading those TIF files.  The current GMT get different values...So the colors are correct given the z-values but the z-values we read differ between GMT 6.0.0 and later.

Stay tuned.

**Comment by PaulWessel** [comment]
As best we can tell, GDAL changed how GDALComputeRasterMinMax works when true was passed (trust the metadata).  But in at least your case specifically and perhaps just more recently in general, this gives incorrect answers from files such as TIF.  We have changed to pass false and now we get the correct values and your script works as before.
