### ISSUE TITLE
Loxodromes on the ellipsoid

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5369]
This should relatively simple to implement in GMT. This [GMT.jl file](https://github.com/GenericMappingTools/GMT.jl/blob/master/src/loxodromics.jl) shows how simple/complicated it is. But we need a place where to add it. Buried in ``sample1d -A`` option does not seem the best place.

And BTW, ``sample1d -A -je`` is not true either and says nothing to the user.

**Comment by PaulWessel** [comment]
Yes, if we are talking about creating a loxodrome then perhaps project -G is the place since it creates small and great circles.
We should of course document and warn what sample -A can do and not do.  When you find some issue, takes about the same time to make a PR of it no?

**Comment by joa-quim** [comment]
Too many things floating in my head and better leave this warning somewhere than risk to loose before that PR.
