### ISSUE TITLE
A blue tick

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5388]
```
gmt basemap -R-8/8/-6/6 -JM15 -Baf -BWSen --FONT_ANNOT_PRIMARY=9 --FONT_LABEL=14 --FONT_TITLE=24 --MAP_TITLE_OFFSET=7p --MAP_VECTOR_SHAPE=0.5 --MAP_TICK_PEN_SECONDARY=thinner,red --MAP_TICK_PEN_PRIMARY=thinner,blue -Tmg0/0+w6+d-14.5+t45/10/5/30/10/2+i0.25,blue+p0.5+l+jCM -png lixo
```
Running the above and zooooming

![image](https://user-images.githubusercontent.com/537321/123430113-b65dc300-d5bf-11eb-9c8e-e02ffb6a9f9c.png)

**Comment by meghanrjones** [comment]
Isn't that why the script for this figure has two basemap calls: https://docs.generic-mapping-tools.org/dev/_images/GMT_mag_rose.png? Because MAP_TICK_PEN_PRIMARY will also affect the outer frame tick colors if not. I do not see the bug in this example.

**Comment by PaulWessel** [comment]
Yes, that is a feature and not a bug.  The --PAR setting will last the whole module session and cannot know that you only want this for one aspect.
