### ISSUE TITLE
Two Julia failing tests

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5389]
This is very recent but now I have at least two julia tests that fail

1- ``psconvert lixo.ps``   (no options should default to -Tf) 
2- pswiggle [ERROR]: Unrecognized option -S

Have to go for a couple hours.

**Comment by PaulWessel** [comment]
psconvert lixo.ps runs fine for me and has always defaulted to JPG (your choice).  Not sure why Julia fails on that though.

As for pswiggle -S, it is an old deprecated option but available if willing to use GMT 5 level of compatibility:

```
			case 'S':
				if (gmt_M_compat_check (GMT, 5)) {
					GMT_Report (API, GMT_MSG_COMPAT, "-S option is deprecated; use -D instead.\n");
```

Perhaps you have upped the level to 6 - in which case you will get an error

**Comment by joa-quim** [comment]
I have submitted a [PR ](https://github.com/GenericMappingTools/GMT.jl/pull/641) to Julia today where both of those tests passed. So the failures are due to pretty recent changes (few hours). And the ``psconvert`` failure happens on command window too.

**Comment by PaulWessel** [comment]
Well, all I can tell you is that I just ran psconvert on some PS files and it silently created a JPG.  What you report is a gs error which is always either (a) bad PS file or (b) actually, that is usually the only case.  Now, if there is a bug that produced bad PS then we will need to look at what you created and how, but it should not have anything to do with psconvert though.

**Comment by joa-quim** [comment]
Don't know were to turn. All I know is that I have now 3 failing tests (new one involving subplot) that worked fine still today.

**Comment by PaulWessel** [comment]
If we make a bug in GMT taht now produces bad PS then can you run the Julia verbose, get the command and run on command line? Should be same bug then.  But perhaps it is related to the revert of the other column bug.

**Comment by PaulWessel** [comment]
BTW, working on testapi_columns.c which will read in a dataset into dataset, matrix, vector, then call gmt convert with virtual file of that type, using -i -q etc, and return back another virtual file, then writing that to disk for comparison with command line output.  I think this will pinpoint the recent problems.
In process I find -qi|o not implemented for externals on dataset, but looks like -i -o were.  I thought externals mostly would do the matlab equivalent of data(:,[1 2 2]) to duplicate columns, but you are using -i I think?

**Comment by joa-quim** [comment]
```
julia> gmt("psbasemap -R-10/0/35/45 -Ba -P -JX10d -Vq > lixo.ps")
```
in cmd
```
psconvert lixo.ps
Error: /ioerror in --showpage--
...
```
but with -Tf or -A works fine

```
C:\v
λ psconvert lixo.ps -Tf

C:\v
λ psconvert lixo.ps -A
```

Same PS generated with cmd shows not problems
```
psbasemap -R-10/0/35/45 -Ba -P -JX10d -Vq > lixo.ps

C:\v
λ psconvert lixo.ps
```

Too many things to look at.

**Comment by PaulWessel** [comment]
OK, hang in there, I am debugging -i for externals due to you guys.

**Comment by PaulWessel** [comment]
Status on this, @joa-quim ?

**Comment by joa-quim** [comment]
Lost a bit track of the -S issue (too many things to look up)
But the first one is real and non-Julian, though of minor importance and fuzzy culprit. The issue if the BBB (BigBoundingBox)

```
%%BoundingBox: 0 0 32767 32767
%%HiResBoundingBox: 0 0 32767.0000 32767.0000 
```
with this the Ghost chocks if we don't use **-A**

**Comment by PaulWessel** [comment]
If by first one you mean `gmt psbasemap -R-10/0/35/45 -Ba -P -JX10d -Vq > lixo.ps` then no problems on my end. If not please post the non-Julian command.

**Comment by joa-quim** [comment]
Just replace the BB of the ``cmd`` *ps* with the values I posted and see.

**Comment by PaulWessel** [comment]
OK, but when does this actually happen in GMT? It seems to work well in all modern cases, no?

**Comment by joa-quim** [comment]
Probably modern always set -T so the problem is invisible. But this is a very obscure corner case that doesn't worth spending time on.
