### ISSUE TITLE
-? fails when using ZSH

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#5395]
**Description of the problem**
When using the ZSH shell the `-?` argument doesn't work. Generally not a problem as no argument has the same behavior. It becomes a problem at least with `begin` and `end` where no argument is required for proper operation. As ZSH is the new default shell for MacOS this might become more of an issue.

**Full script that generated the error**

```
> gmt coast -?
zsh: no matches found: -?
>
```

**Actual outcome**

Nothing but an error message

**Expected outcome**

Full usage message for `coast`.

**System information**

* Operating system: Manjaro Linux
* GMT version (`gmt --version`): 6.3.0_b89cf1d_2021.06.26

**Comment by seisman** [comment]
We have the same issue with csh (https://github.com/GenericMappingTools/gmt/issues/3916), but I think nothing we can do on the GMT side.

For zsh, https://github.com/ohmyzsh/ohmyzsh/issues/31 provides two workarounds.

1. Add `noglob` before commands, i.e., `noglob gmt coast -?`
2. Add `unsetopt nomatch` in `.zshrc`

**Comment by seisman** [comment]
I'm closing the issue because GMT can do nothing here. Feel free to reopen the issue if you think more discussions are needed.
