### ISSUE TITLE
GMT Windows installers still use the DCW 1.1.4 data?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5408]
I can't check it, but a user reports to me that the DCW data in the GMT Windows installers is still 1.1.4, but the latest DCW version is 2.0.0.

@joa-quim Can you check the DCW version and update it to 2.0.0 if it isn't.

**Comment by joa-quim** [comment]
Why do they say that? I don't remember anyway to ask GMT to tel the DCW version. But I just opened the ``dcw-gmt.nc`` (the one that was packed in the installer) in a nc editor and the versions says ``2.0.0``

**Comment by seisman** [comment]
I downloaded the win32 and win64 installers of GMT 6.2.0 and check the README.TXT file in the `share/dcw` directory. It shows the version is 1.1.4, and the `dcw-states.txt` is also the old version.

**Comment by joa-quim** [comment]
Ah, ok. But if you do
```
ncdump -h dcw-gmt.nc | grep version
                :version = "2.0.0" ;
                :gmtversion = "6.1.1" ;
```

**Comment by seisman** [comment]
OK, that makes sense. The `dcw-states.txt` is inconsistent with the `dcw-gmt.nc` file, thus reporting some errors.

**Comment by joa-quim** [comment]
I've updated those meta files in my computer so next installer will come with them, but the dcw repo does not have any README.TXT anymore, only a README.md.

**Comment by seisman** [comment]
> I've updated those meta files in my computer so next installer will come with them

Good. Closing the issue.
