### ISSUE TITLE
Decorated lines cannot go into legend

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5416]
Playing with automatic legend generation in classic and can plot fronts, annotated but not decorated lines.
The legend man says

> Three plot symbols may take special modifiers: front (f), quoted line (q) and vector (v).

but is this lack of support for decorated lines on purpose?

```
julia> lines(x, sin.(x), ls="line&Circ", legend=(label="sin(x)"),show=1, Vd=1)
        psxy  -JX14c/9.5c -Baf -BWSen -S~d0.88:+sc0.11+gwhite+p0.75,black -R-0.2/6.4/-1.1/1.1 -W0.75 -P -K > C:\TMP\GMTjl_tmp.ps
leg = ["S - ~d0.88:+sc0.11+gwhite+p0.75,black 0.75 - 0.75 - sin(x)", #undef, #undef]
psxy [ERROR]: Segment header tries to switch from -Sq to another symbol (~d0.88:+sc0.11+gwhite+p0.75,black) - ignored
```

**Comment by PaulWessel** [comment]
Seems like it says switching from quotes line to decorated line.  Not sure why it thinks you are doing quoted lines first?

**Comment by joa-quim** [comment]
And it also thinks its reading from a segment header. Which is not so dumb since its receiving a dataset

**Comment by joa-quim** [comment]
It seems to be on purpose
```
else if (S.symbol == GMT_SYMBOL_QUOTED_LINE || S.symbol == GMT_SYMBOL_DECORATED_LINE || S.symbol == GMT_SYMBOL_FRONT)
	GMT_Report (API, GMT_MSG_ERROR, "Segment header tries to switch from -S%c to another symbol (%s) - ignored\n", S.symbol, s_args);
```

**Comment by joa-quim** [comment]
The second time it passes at line 1088 of psxy ``S.symbol`` becomes = 107 (``q``). ``options`` have ``S`` pointing to a custom symbol in ``KC:\\TMP\GMT_symbol12068.def``
Can't follow the program's logic any further from this.

**Comment by PaulWessel** [comment]
Sorry, busy all day and maybe tomorrow too.  Is this reproducible from the command line? If so could you please append that data set to go with the command to make it simpler to debug.

**Comment by joa-quim** [comment]
```
printf "0 -1\n6 1" | gmt psxy -JX14c/9.5c -Baf -BWSen -S~d0.88:+sc0.11+gwhite+p0.75,black -R-0.2/6.4/-1.1/1.1 -W0.75 -P -K > lixo.ps
echo "S - ~d0.88:+sc0.11+gwhite+p0.75,black 0.75 - 0.75 - sin(x)" > leg.txt
gmt pslegend leg.txt -R -J -O -DJMC >> lixo.ps
psxy [ERROR]: Segment header tries to switch from -Sq to another symbol (~d0.88:+sc0.11+gwhite+p0.75,black) - ignored

**Comment by joa-quim** [comment]
```
printf "0 -1\n6 1" | gmt psxy -JX14c/9.5c -Baf -BWSen -S~d0.88:+sc0.11+gwhite+p0.75,black -R-0.2/6.4/-1.1/1.1 -W0.75 -P -K > lixo.ps
echo "S - ~d0.88:+sc0.11+gwhite+p0.75,black 0.75 - 0.75 - sin(x)" > leg.txt
gmt pslegend leg.txt -R -J -O -DJMC >> lixo.ps
psxy [ERROR]: Segment header tries to switch from -Sq to another symbol (~d0.88:+sc0.11+gwhite+p0.75,black) - ignored
```

**Comment by PaulWessel** [comment]
Thanks.  Family visit interferes with intense debugging....Maybe early mornings...

**Comment by PaulWessel** [comment]
After adding #5428 it works if I use `~n1:+sc0.11+gwhite+p0.75,black` instead of what you selected since your choice is for the line drawing but is unusable for the legend.  See my suggestions for what we can do under #5428.
