### ISSUE TITLE
man pages conda installation

### ISSUE THREAD

**Issue by andreasgroh** [GenericMappingTools/gmt#5474]
Hi all,

I have installed `gmt 6.1.1` via `conda` and everything runs smoothly. However, I cannot find the man pages for the different gmt routines (I'm referring to the unix-type man pages, the html man pages are available). There are several locations holding man pages in the directory of my gmt env (e.g. `share/doc/gmt/man` - which at least holds man pages for some general routines like `gmt` or `gmtswitch`, `share/man` or just `man`), but none of them holds the man pages for the individual routines like e.g. `grdfilter`. 
Where can I find those man pages, so I can add the path to my `MANPATH` or are any additional installations steps required?

Best,

Andreas

**Comment by joa-quim** [comment]
Please use the forum when you have questions.
We don't build man pages anymore and anyway a Conda issue (which is I don't think is the case) would not belong here either.
