### ISSUE TITLE
PS_PAGE_COLOR in unset by modern theme 

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5475]
This does not set the page color, but removing the ``--GMT_THEME`` does
```
printf "0 0\n10 10" | psxy -R0/10/0/10 -JX14c/9.5c -Bpx+lx -Baf -By+lx@+2@+ -BWSen+gwhite --PS_PAGE_COLOR=#D0DFE6FF -W1 -P -K --GMT_THEME=modern > lixo.ps
```

**Comment by PaulWessel** [comment]
It is because you are setting the color first, then calling for a theme change.  Changing the order works.  So if you want to change the theme on the fly then do that first before making changes to any setting.

**Comment by joa-quim** [comment]
Hmm, that partially explains why I get this if the session is not destroyed before the call to ``pslegend``. If no frame filling then the issue is not visible and the line is correctly plotted.
```
x = 1:10
lines(x, x.^2, limits=(0,10,0,100), linewidth=2, linestyle=".-", pagecolor="#D0DFE6FF", xaxis=(xlabel="x", bgcolor=:white), ylabel="x@+2@+", legend=(label="x@+2@+", pos=:LT), Vd=1, show=1)
    psxy  -R0/10/0/100 -JX14c/9.5c -Bpx+lx -Baf -By+lx@+2@+ -BWSen+gwhite --PS_PAGE_COLOR=#D0DFE6FF -W2,,.- -P -K > C:\TMP\GMTjl_tmp.ps
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/125167655-928ea580-e199-11eb-91fa-c16b89e065b4.png)

**Comment by PaulWessel** [comment]
So I do not think this is a bug - it is a usage issue.  GMT_THEME sets multiple settings so if you are to override them you will need to start with GMT_THEME and then add them.  OK to close?

**Comment by joa-quim** [comment]
But that means the GMT rule that the order of the options is irrelevant will be broken.

**Comment by PaulWessel** [comment]
That is true... Hm, perhaps we need to enforce that --GMT_THEME is parsed first, just like we do for -J etc.  I will look at that section that "sorts" the options.

**Comment by joa-quim** [comment]
Yes, like -B<axes> -B<frame>
