### ISSUE TITLE
Cannot omit axis in polar plots 

### ISSUE THREAD

**Issue by caiociardelli** [GenericMappingTools/gmt#5478]
**Whenever I try not to plot one of the axes using polar projections (e.g. gmt basemap -JPa10c -R0/70/3800/6371 -BWeS), GMT just replaces the axis by a straight line, rather than omitting it.**

**
#!/usr/bin/env bash

gmt begin
  gmt basemap -JPa10c -R0/70/3800/6371 -BWES
gmt end show
**

```
# PASTE CODE HERE
```

**There is no error message.**

```
# PASTE ERROR MESSAGE HERE
```

**
![test](https://user-images.githubusercontent.com/20651309/125306516-abb46500-e305-11eb-8b63-b207c43a5589.png)
**

**Similar to the above, but without the straight line at the top of the map basis (i.e. no upper boundary)**

**System information**

* Operating system: Ubuntu 20.04
* GMT version (`gmt --version`): 6.2.0

**Comment by PaulWessel** [comment]
Yes, can confirm the bug.  A PR that will fix this is being prepared.
