### ISSUE TITLE
Simpler way to add a colorbar

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5513]
**Description of the desired feature**

During @leouieda's grid and pseudo-color map presentation in the UNAVCO workshop today I realize that we probably could simplify how to add a basic colorbar to **grdimage** and other map modules with color without requiring a full **gmt colorbar** call.  My proposal would add a new common option:

**-k**[_refpoint_]

where the default _refpoint_ is BC.  What this option would do is to replace the need for the command

**gmt colormap -DJ**_refpoint_

While admittedly it is not much typing saved, it has two clear benefits:

1. It lets us add color-bars to one-liner GMT commands.
2. It makes it a bit easier to find out how to add a color-bar when working in the man page of a module.

Note that **-k** would be available to _all_ plot modules that can take a CPT, hence **plot**, **plot3d**, **grdvector**, etc., etc. can suddenly add a simple color-bar.

Again, the emphasis is on those two benefits listed above.  For specifics on controlling annotations, adding labels, placing background panels etc. one must of course use **gmt colormap** directly.  In that sense it is similar to the **-l** option we added for auto-legends where you may need to run **gmt legend** specifically for some desired feature.  However, I am open to good ideas for modifiers to **-k** that would not make it too complicated.  E.g, we cannot do a full **-B** treatment, but we could add **+l**_label_ and **+u**_unit_ modifiers if that is desired.

Comments on this proposal from @GenericMappingTools/core is welcome!

**Comment by joa-quim** [comment]
In Julia
```
grdimage(rand(256,256), colorbar=true, Vd=1)
        ["grdimage  -JX14c/0 -Baf -BWSen -n+a -R1/256/1/256 -C -P -K > C:\\TMP\\GMTjl_tmp.ps", 
         "psscale  -R -J -Baf -DJMR -C -K -O >> C:\\TMP\\GMTjl_tmp.ps"]
```

**Comment by PaulWessel** [comment]
Yes, so basically your `colorbar=true` is what **-k** would do.

**Comment by joa-quim** [comment]
Yes. Long time ago I proposed that modules could call other modules (in open command line) to offer a facility like this. But it was censured.

**Comment by PaulWessel** [comment]
Well, I do not regret that censure (I assume it was me!) as that would get ugly real fast.;-)

**Comment by joa-quim** [comment]
Yes, this is really ugly
```
grdimage("@earth_relief_30m", shade=true, coast=true, show=1)
```

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/126412548-010005ad-b56e-4649-bcd8-1fc101be2ecd.png)

**Comment by PaulWessel** [comment]
No, that is not ugly, but we are talking about aa command line version of running colorbar from the grdimage command line - I thought that is what you meant.

**Comment by joa-quim** [comment]
I actually meant both. With the preference ofc of having good enough defaults so that we can resume it to a single option.

**Comment by PaulWessel** [comment]
Adding **-k** would be available in 9 GMT modules that make a plot involving a CPT.  That seems worthwhile to me.

**Comment by joa-quim** [comment]
Well, I showed examples on how much I agree with the principle.

**Comment by seisman** [comment]
I'm not a fan of the proposed new **-k** option. I like one-liner commands for their simplicity, but they're rarely used when we do some real plotting.

**Comment by PaulWessel** [comment]
It is true none of use are really doing one-liners for real plotting.  However, basically all the wrappers are doing this by having, like @joa-quim has been doing with Julia, some word equivalent to **-k**, to keep things simple for Julia users.  Presumably, PyGMT may have that too or may be thinking of adding something like `colorbar=true`.  The long-form of **-k** may become` --add-color-map` and then the command line interface has it too.  This is useful beyond the one-liners - it saves us from having to run a separate **colorbar** command, just like **-l** saves us from running a separate **legend** command.

Speaking as a non-Python, non-Julia user that rely on the GMT command line, I think **-k** would be a nice addition :-)

**Comment by leouieda** [comment]
I'm with @seisman in this one. This is additional code (including future bugs and maintenance), tests and documentation (don't forget about those 🙂) to avoid typing a few characters in uncommon use cases.

> It makes it a bit easier to find out how to add a color-bar when working in the man page of a module.

Can also be done by putting a single sentence pointing people to `colorbar` in those pages. It's less documentation to write probably.

**Comment by leouieda** [comment]
I'd be in favor if making a default colorbar was a lot of work and could not be easily done by a separate module. But since modern mode, colorbar can know about the CPT and is able to generate a good default without any arguments. The shading is a good example of this, as using a separate module means generating a separate grid in disk.

**Comment by joa-quim** [comment]
**-k** would not be for modern only. And I don't see why it cant be used in *production code* too. If the defaults are good enough the ``psscale`` job ends right there. 

Reading the ``colorbar`` man page is **scaring**. All modules that have a **-D** type option produce hart arrhythmia to me, so everything that helps preventing hart disturbances is a blessing.

**Comment by leouieda** [comment]
@gd-a then it doesn't really save any typing right? 🙂 

Considering only the usefulness of the feature: sure, add it since it will be used by someone at some point. But a feature is never free. It has to be well documented, tested, debugged, and maintained. So there is always a price to pay for features and it gets more expensive the larger and more foundational a project becomes. For a 1-off hack, features are free. For GMT, they cost quite a bit (we asked for quite a bit of money to make the project sustainable and this consideration is a big part of it).

To me the real questions is "Is it worth the price?" `inset` and `subplot` were definitely worth it. If others (mainly the ones bearing the burden) feel like this feature is worth it, then I'm all for it.

**Comment by seisman** [comment]
> From my user-only point of view, this option is no different than `-l` for legend, as long as we can tweak the default.

The exiting `-l` option and the proposed `-k` option are still a little different. We need the `-l` option to specify the label for each legend entry. Automatically adding the legend is a bonus feature to me. But the `-k` option for adding a colorbar is not necessary.

**Comment by meghanrjones** [comment]
Superseded by https://github.com/GenericMappingTools/gmt/pull/6427
