### ISSUE TITLE
Movie. Allow select the duration of the animation.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5523]
Currently in movie, the duration of an animation depends in the number of frames and the displayrate (frame per seconds -D). In occasions it is useful to indicated the desired length of the animation (and to have the displayrate calculated from the other two values).

**Comment by PaulWessel** [comment]
It is not straightforward as the number of frames is sometimes not known until _after_ we have run the preflight script. Furthermore, with the fading and title options we convert the given lengths in seconds to the equivalent number of frames, which requires knowing the frame rate.  In other words, I need to be be able to convert between frames and seconds from the beginning of **movie** and that makes your suggestion problematic.  I think you simply will have to pick a **-D** and then after you know the length you can do the math and pick another **-D**.

**Comment by Esteban82** [comment]
Ok. No problem. It is not very difficult to do the math and set the -D value.

**Comment by PaulWessel** [comment]
Yep.  Sorry though, it was a good idea.
