### ISSUE TITLE
Use MyST parser for changelog and contributing documentation

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5542]
**Description of the desired feature**

There are several open issues related to contributing/developing documentation (https://github.com/GenericMappingTools/gmt/issues/3778, https://github.com/GenericMappingTools/gmt/issues/3314, https://github.com/GenericMappingTools/gmt/issues/3313, https://github.com/GenericMappingTools/gmt/issues/3300, https://github.com/GenericMappingTools/gmt/issues/3127, https://github.com/GenericMappingTools/gmt/issues/1199), which will be quicker to address if we use the [MyST parser](https://myst-parser.readthedocs.io/en/latest/index.html) which allows sphinx documentation to be written directly in markdown.

This feature request is to use the MyST parser for some aspects of the GMT documentation, included expanded contributing documentation, developer documentation, changelog, and perhaps the simple examples proposed in https://github.com/GenericMappingTools/gmt/pull/5364. This will make it simpler to update the changelog because the release drafter notes will not need to be manually converted to ReST and will help new contributors add to the documentation because markdown is more intuitive than ReST based on anecdotal comments at the SciPy conference.

Steps:
1. Install MyST parser using steps at https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html
2. Format existing changelog as markdown

**Comment by seisman** [comment]
Just a reminder that, source code of all sphinx extensions are included in the GMT repository (https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/_extensions) to make sure that anyone can build the GMT documentation as long as Sphinx is installed.

It seems that MyST depends on many Python packages and it may be difficult to include all of them in the GMT repository.

**Comment by meghanrjones** [comment]
Alright, I will close this. Eventually, we may want to consider whether it is worth adding as a non-included dependency since it could save us time/effort and help others contribute to our documentation.
