### ISSUE TITLE
Move ninja and pngquant to development dependencies

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5554]
Ninja and pngquant are listed as GMT's optional dependencies in the [Building Instructions](BUILDING.md), but they are only useful for developers who want to build the source code faster or the documentation. The description of pngquant, "Ability to optimize PNG images", sounds like pngquant will optimize PNG images generated by GMT.

I think they should be listed as [Development dependencies](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md#development-dependencies).

**Comment by PaulWessel** [comment]
Yes I agree, they do not give GMT any more capabilities so we should not trick users here.  Development dependencies.
