### ISSUE TITLE
Add Meghan to AUTHORS.md

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5567]
@meghanrjones Don't forget to add yourself to AUTHORS.md

**Comment by meghanrjones** [comment]
Thanks for the note, @seisman! I plan to address this at the same time as https://github.com/GenericMappingTools/gmt/issues/2330, using the format posted in https://github.com/GenericMappingTools/gmt/issues/2330#issuecomment-812902414 (i.e., adding a team gallery with information about the addition process and converting AUTHORS.md to thanks.md).
