### ISSUE TITLE
GMT 6.x x2sys_cross; internal crossovers work, external do not.

### ISSUE THREAD

**Issue by bjcoakley** [GenericMappingTools/gmt#557]
In the good news department x2sys_cross seems to nail all of the crossover locations.

![AN01-block](https://user-images.githubusercontent.com/48657958/54786699-63c21f00-4bde-11e9-9405-5f3e9ef0b222.png)

Black boxes indicate external crossovers. Circles are internal crossovers. Grey lines are the crossing tracks.

The crossover values are weird though.

internal crossovers seen to be working well;

> AN01 0 AN01 0 2009-07-16T17:17:28/2010-07-22T02:41:47/28855.1 2009-07-16T17:17:28/2010-07-22T02:41:47/28855.1
-149.2652368	63.6477656	2009-07-16T19:39:47	2010-07-20T22:03:36	881.3292315	27646.5433480	329.3593283	57.4612985	116.2277325	131.7216805	70.2436619	68.6061314	NaN	NaN	1100.5144804	1100.4585601

In the source file for AN01;

The first value is; 2009-07-16T19:39:47.000 210.734633 63.647765 70.24 NaN 1101.57 AN01204
The 2nd value is; 2010-07-20T22:03:36.000 210.734774 63.647489 68.66 NaN 1104.47 AN01528

Both of these agree pretty well with the values cited in the crossover file.

External crossovers not so much;

> AN01 0 AN02 0 2009-07-16T17:17:28/2010-07-22T02:41:47/28855.1 2010-10-04T20:44:24/2010-11-12T00:33:50/7971.43
-149.2737713	63.8885183	2010-07-20T22:00:14	2010-10-22T23:26:09	27619.6964354	5517.2969864	57.2949312	148.2223904	133.3176145	130.4002543	5.9200226	32.7273767	NaN	NaN	-0.3004059	669.1302349

So the value along track AN01 is listed as 5.900. Along AN02 it is 32.72 mGals.

Looking into the source files at the time of the crossover;

In AN01; 2010-07-20T22:00:14.000 210.726247 63.888105 35.72 NaN 669.86 AN01528
In AN02; 2010-10-22T23:26:09.000 210.725842 63.888513 29.78 NaN 670.09 AN02138

So neither value corresponds to the along track value or is plausible as an interpolated value.

If you plot the crossover values at each location against each other, the internal crossovers look as you’d expect, plotting
along the 1 to 1 line.

![Internal-errors](https://user-images.githubusercontent.com/48657958/54786777-a126ac80-4bde-11e9-8678-33f83d2bf74d.png)

The external crossovers look strange;

![external-errors](https://user-images.githubusercontent.com/48657958/54786795-a8e65100-4bde-11e9-9d90-5d2617ff920f.png)

I am using the comments x2sys_cross for internal crossovers;

x2sys_cross $block -T$TAG -Il -Qi -Sl90 -Su200 -Vl -Z >> $destinationint/coa.int

And for external crossovers;

 x2sys_cross $cruise $blocks[$count2] -T$TAG -Qe -Il Sl90 -Su200 -Vl >> $destination/coa.ext

Both linear and Akima interpolation give essentially the same results.

**Comment by bjcoakley** [comment]
Never mind. I think I just figured it out. I forgot the -Z option for the external errors. Checking it now. If there is still a problem, I will get back to you.

**Comment by PaulWessel** [comment]
No problem, if you find all is well just comment and close the issue, otherwise explain what remains to be looked at.

**Comment by bjcoakley** [comment]
All works fine. Now struggling with the corrections.
