### ISSUE TITLE
the latest update version building command -gmt can't be run

### ISSUE THREAD

**Issue by brioglade** [GenericMappingTools/gmt#5572]
➜  ~ gmt --help   
gmt: symbol lookup error: gmt: undefined symbol: gmt_dataserver_url
➜  ~ which gmt 
/home/ufo/opt/gmt6/bin/gmt

set (CMAKE_INSTALL_PREFIX "/home/ufo/opt/gmt6")
set (DCW_ROOT "/home/ufo/opt/dcw-gmt-2.0.0")
set (GSHHG_ROOT "/home/ufo/opt/gshhg-gmt-2.3.7")
set (GMT_USE_THREADS TRUE)

export GMT6HOME=/home/ufo/opt/gmt6
export PATH=${GMT6HOME}/bin:$PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GMT6HOME}/lib64

No error in building process in ubuntu 20.4

**Comment by PaulWessel** [comment]
Not sure what that means - might you have more than one GMT installed somehow? That symbol (_gmt_dataserver_url_ ) is a function defined in gmt_remote.c, it is external (see prototype in gmt_prototypes.h which is included in gmt_dev.h which is included in gmt.c) and it is used in a few places around GMT.  On my system it clearly present in the shared library:

```
nm -g libgmt.6.dylib | grep gmt_dataserver_url
000000000000b0d0 T _gmt_dataserver_url
```

and gmt is obviously linked with that library:

```
otool -L gmt
gmt:
	/Users/pwessel/GMTdev/gmt-dev/rbuild/gmt6/lib/libgmt.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	/opt/local/lib/libnetcdf.19.dylib (compatibility version 19.0.0, current version 19.0.0)
...

```
Hence I do not understand what ubuntu is complaining about.  Can you use the equivalent commands on Linux (ldd, I think) to verify the above?

**Comment by brioglade** [comment]
Yes,you are right.I have to use 'sudo apt autoremove' after uninstall the package.Thanks.
 Wish you a happy life!
