### ISSUE TITLE
LaTeX support in -B flags

### ISSUE THREAD

**Issue by tasmi** [GenericMappingTools/gmt#5587]
**Description of the desired feature**

Certain text formats cannot be passed to frame/basemap due to their reliance on the '+' symbol. For example:

`fig.colorbar(frame=[‘af’, ‘x+l"Long-term 95@+th@+ percentile NDVI"’])`

fails. Alternatives using LaTeX could be:

```
fig.colorbar(frame=['af', 'x+l"Long-term 95<math>^{th}</math> percentile NDVI"'])
fig.colorbar(frame=['af', 'x+l"Long-term 95@[^{th}@[ percentile NDVI"'])
```
However, these do not yet seem to be supported. The issue can be sidestepped by hard-coding a colorbar label (suggested here: https://forum.generic-mapping-tools.org/t/using-superscript-subscript-for-axis-labels/1942).

**Are you willing to help implement and maintain this feature?** Yes

I'd be happy to give this a try, but don't have much experience with the GMT source.

**Comment by meghanrjones** [comment]
@tasmi, thanks for opening this issue! Just a heads up that I have moved it over to the core GMT repository since this is where it would be implemented. The feature would still be accessible through PyGMT after a release cycle.

**Comment by tasmi** [comment]
Thanks for looking into this!
