### ISSUE TITLE
Extend -d common option to grids/images

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5594]
**Description of the desired feature**

Currently, the -d common option substitutes a data value with IEEE NaN on input and the NaN with a different data value on output for column input. I think it would be helpful to extend this to work for grids and images as well, so that a command such as:

`gmt grdimage image.nc -Jx10i -Ccolors.cpt -B5 -Q -d0 -png image`

works to plot an image with transparent NaN values where the image has NaNs represented as 0.

I usually preprocess with a grdmath command to replace grid/image NaN values with 0, so I am curious whether a grdmath call could be used internally to implement the -d option for grids/images?

This could also replace the -N option elsewhere (such as grdfill). The difficulty would probably be for modules where there are both column and grid input, to establish whether the -d applies to column or grid input/output or both.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Searching for modules that read tables (and thus have **-di**) and deals with grids gives this list:

```
grdmask.c
sphdistance.c
grdedit.c
spotter/hotspotter.c
potential/grdseamount.c
sphinterpolate.c
nearneighbor.c
surface.c
grdmath.c
sphtriangulate.c
```

These all produce grids, so the "empty node" setting could be done via **-do**.  Hence **-di** deals with reading tables and **-do** sets a grid NaN value.

For modules that read grids, such as **grdimage**, one could imagine **-di** be used as you suggest.  However, there are other modules like **grdtrack** that read both grids and tables, and there **-di** and **-do** currently control table i/o.  

Reading grids allows us to apply modifiers, no, such as **+s**, **+o**, and **+n**.  Have you tried if **+n**0 turns zeros to NaNs?  If it does not, isn't that a bug (have not yet read the docs on what it says it should do though).

**Comment by meghanrjones** [comment]
> Searching for modules that read tables (and thus have **-di**) and deals with grids gives this list:
> 
> ```
> grdmask.c
> sphdistance.c
> grdedit.c
> spotter/hotspotter.c
> potential/grdseamount.c
> sphinterpolate.c
> nearneighbor.c
> surface.c
> grdmath.c
> sphtriangulate.c
> ```
> 
> These all produce grids, so the "empty node" setting could be done via **-do**. Hence **-di** deals with reading tables and **-do** sets a grid NaN value.
> 
> For modules that read grids, such as **grdimage**, one could imagine **-di** be used as you suggest. However, there are other modules like **grdtrack** that read both grids and tables, and there **-di** and **-do** currently control table i/o.
> 
> Reading grids allows us to apply modifiers, no, such as **+s**, **+o**, and **+n**. Have you tried if **+n**0 turns zeros to NaNs? If it does not, isn't that a bug (have not yet read the docs on what it says it should do though).

Wow, somehow I forgot this option. Is there a reason for only listing *grid* in the argument descriptions? We could write the full *grid*[=ID][+sscale][+ooffset][+ninvalid] to publicize this better for those, like me, who sometimes forget the contents of https://docs.generic-mapping-tools.org/dev/cookbook/features.html#grid-file-format-specifications.

**Comment by joa-quim** [comment]
> gmt grdimage image.nc -Jx10i -Ccolors.cpt -B5 -Q -d0 -png image

The efficient way for this would be to set a color in the CPT to be transparent.

**Comment by meghanrjones** [comment]
> > gmt grdimage image.nc -Jx10i -Ccolors.cpt -B5 -Q -d0 -png image
> 
> The efficient way for this would be to set a color in the CPT to be transparent.

This might be more efficient, but is not a user friendly solution.

**Comment by PaulWessel** [comment]
The solution involves improving the docs.  The +n modifier is the solution already.  I agree that all modules ingesting a grid should use the same synopsis syntax showing the options.  It is what we do for everything else (options, modifiers) so why not on those guys.

**Comment by meghanrjones** [comment]
> The solution involves improving the docs. The +n modifier is the solution already. I agree that all modules ingesting a grid should use the same synopsis syntax showing the options. It is what we do for everything else (options, modifiers) so why not on those guys.

OK, I will update the docs. Closing the issue since it's not a feature request.
