### ISSUE TITLE
Disallow -R...+r for non-geographic projections

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5614]
See this forum [post](https://forum.generic-mapping-tools.org/t/dont-know-what-went-with-this-code-for-plotting-histogram/1966) for a bad case of confusion regarding the purpose of **+r.**  That modifier was _never_ meant to be a way to let people give _xmin/ymin/xmax/ymax_ as an alternative to _xmin/xmax/ymin/ymax._  It was introduced for _oblique_ geographic projections where one must specify those two corners as _lon_BL/lat_BL/lon_UR/lat_UR_.  It is OK to use **+r** for geographic projections since you may need to consistently specify a region even if the particular projection parameters would allow you to use _w/e/s/n_.

What do @GenericMappingTools/core  think of barring **+r** when used with a Cartesian -JX|x scaling?

**Comment by meghanrjones** [comment]
> What do @GenericMappingTools/core think of barring **+r** when used with a Cartesian -JX|x scaling?

Why only bar this for -Jx if it is intended to only work for oblique geographic projections? Do you expect it to work and remain supported for non-oblique geographic projections?

**Comment by PaulWessel** [comment]
I suspect there are usages out there where a projection may or may not be oblique and the user want to consistently specify the region.  Barring +r for geographic will likely lead to lots of problems.
