### ISSUE TITLE
gmt movie -C10cx10cx100 creates image of 1001 pixels

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5619]
In the following script I use a canvas size of 10 x 10 cm and 100 dots per cm. It should create an image of 1000 x 1000 pixels. The information says so but I got an image of 1001 x 1001 pixels (and ffmpeg fails to create a movie from image with even pixels).

Error message:
![imagen](https://user-images.githubusercontent.com/17908951/128806179-e1b13c4f-89d1-423f-b0c7-71d47770bf65.png)

Full Script:

```

#!/usr/bin/env bash

cat << 'EOF' > pre.sh
gmt begin
    gmt math -T0/3/1 T SIND -o0,1,0 = > line.txt  
    gmt events line.txt -R-40/400/-2/2 -JX8c/8c -Ar200i > line_points.txt
gmt end
EOF

cat << 'EOF' > main.sh
gmt begin
    gmt events -R-40/400/-2/2 -JX8c/8c -Baf -B+t"Snake line" line_points.txt -Ar -T${MOVIE_COL0} -Es -W2p,red -Yc -Xc
gmt end
EOF

gmt movie "main.sh" -Sb"pre.sh" -N"Lines3" -T"line.txt" -C10cx10cx100 -Vi -Ml,png -Fmp4 -Zs

rm  line*.txt
```

**Comment by PaulWessel** [comment]
Yes, it is a bit tricky since it _really_ is working as dpi, not dpc, so there are factors like 2.54 floating around and rounding becomes and issue.  I will have to see if/why **psconvert -A+r** is/is not being used in movie.  Adobe law is ceil which would give 1001 but I thought we were passing +r in movie....

**Comment by Esteban82** [comment]
Another question, in the previous script I try to use this
```

gmt begin
    gmt math -T0/300/1 T SIND -o0,1,0 = > line.txt
    gmt basemap -R-40/400/-2/2 -JX10c/10c -B+n -Yc -Xc
    gmt events line.txt                -Ar100c > line_points.txt  # Do NOT work
gmt end
```

 but I got the error:

`events [ERROR]: Must specify -R option`

When I use this it worked:
`    gmt events line.txt -R-40/400/-2/2 -Ar100c > line_points.txt  # Work`


gmt event should not be able to read -R from the line above? 

When I use gmt events without -Ardpu (just -Ar -T) I do not have this problem.
