### ISSUE TITLE
grdimage -A, mess in the file extension

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#562]
The test ``readwrite_withgdal.sh`` now fails because the line that creates an image from a grid errors with:

```
gmt grdimage lixo.grd -Alixo.png=PNG -JX4c -Clixo.cpt
grdimage [ERROR]: Unupported image format. Supported formats are:
BMP,GIF,JPG,PNG & TIF
grdimage [ERROR]: Alternatively, append :<driver> for a valid GDAL driver
grdimage (api_export_image): Unknown Error [lixo.png=PNG]
```
The problem is in the file name ``lixo.png=PNG`` where the ``=PNG`` was not stripped out. In fact we don't need to specify the driver, but if we do, somewhere in the code we used to convert ``=PNG`` to ``=gd:PNG`` (which the form expected by ``gmt_gdalwrite``). That conversion was broken and likely recently because this test used to pass. This is also an annoying issue that keeps resurfacing again and again.

**Comment by PaulWessel** [comment]
This should be closed, no?

**Comment by joa-quim** [comment]
No. It still fails for me. Doesn't for you?
```
C:\v>grdimage --version
6.0.0_b80eaba_2019.03.21

C:\v>grdimage lixo.grd -Alixo.png=PNG -JX4c -Clixo.cpt
grdimage [ERROR]: Unupported image format. Supported formats are:
BMP,GIF,JPG,PNG & TIF
grdimage [ERROR]: Alternatively, append :<driver> for a valid GDAL driver
grdimage (api_export_image): Unknown Error [lixo.png=PNG]
Error returned from GMT API: GMT_IMAGE_WRITE_ERROR (23)
```

**Comment by PaulWessel** [comment]
Ok I see it fails.  Will look.

**Comment by PaulWessel** [comment]
Looks like bad syntax to me.  The various ways are

1. Just give lixo.png.  This is a recognized gdal format
2. If not one of the 5 standards, add =_format_
3. Be difficult and add =_gd:format_

The error message says append :_driver_ but the above says =_format_.  Why are these different.  Or is it meant to say append =gd:_driver or =_format_?

> 	-A Save image in a raster format (.bmp, .gif, .jpg, .png, .tif) instead of PostScript.
> 	   If filename does not have any of these extensions then append =<driver> to select
> 	   the desired image format. The 'driver' is the driver code name used by GDAL.
> 	   See GDAL documentation for available drivers. Note: any vector elements are lost. 

So is this not just wrong syntax and we are done?  Do we need to catch this problem?

**Comment by joa-quim** [comment]
grdimage's man says ``add =format`` and that's what we have in the test script, so yes it used to work with ``=format`` (which much nicer than ``=gd:driver``) but now is broken.
