### ISSUE TITLE
Color parsing in psimage is broken

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#563]
Tests ``transparent_png`` and ``gif`` fail with

```
/c/v/build12/test/psimage/transparent_gif> transparent_gif.sh
psimage [ERROR]: Colorname lack+t not recognized!
psimage [ERROR]: Syntax error -G option.  Correct syntax:
        -G<color>   Specify <color> as one of:
           1) <gray> or <red>/<green>/<blue>, all in range 0-255;
           2) <c>/<m>/<y>/<k> in range 0-100%;
           3) <hue>-<sat>-<val> in ranges 0-360, 0-1, 0-1;
           4) any valid color name.
           For PDF fill transparency, append @<transparency> in the range 0-100% [0 = opaque].
psimage [ERROR]: Colorname white+t not recognized!
psimage [ERROR]: Syntax error -G option.  Correct syntax:
...
```
Curiously there seems to be two different errors here because first failure message misses the ``b`` in ``black`` but not the ``w`` in ``white`` of the second and remaining

**Comment by PaulWessel** [comment]
Did you update the test? Running fine for me now.

**Comment by joa-quim** [comment]
Run the tests from -j branch. 
(in the train to Lisbon now)

Sent from my iDedo

No dia 22/03/2019, às 19:17, Paul Wessel <notifications@github.com> escreveu:

**Comment by PaulWessel** [comment]
I did (well the -joption branch was merged) and those tests pass.
It looks like you are running some older psimage version since it used to be -G<code><color> but I changed that some weeks ago to -G<color>[+modifiers].

**Comment by joa-quim** [comment]
Right, run from MinGW shell that have the path set by a batch that is pointing to, probably still SVN times, binaries.

**Comment by joa-quim** [comment]
Confirmed, script runs fine now. But this all started because the tests failed during the ``make check``phase.
