### ISSUE TITLE
Deprecated "gmt convert" syntax in anim01

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5644]
**Description of the problem**

https://docs.generic-mapping-tools.org/dev/animations/anim01.html

The anim01 script uses the following commands:
```
	gmt convert sin_curve.txt -Z0:${last} | gmt plot -W1p,blue -R0/360/-1.2/1.6 -JX3.5i/1.65i -X0.35i -Y0.25i
	gmt convert sin_point.txt -Z0:${MOVIE_FRAME} | gmt plot -Sc0.1i -Gdarkred
```
but the **-Z** option of `gmt convert` has been deprecated since GMT 6.1.

We should update the script to use the new "gmt convert" syntax.

**Comment by PaulWessel** [comment]
Hm, I generally agree but I do not see the **-Z** actually having been deprecated.  It appears in usage and synopsis with no COMPAT message,  It also has a modifier that **-q** does not (**+i**), so perhaps this is more complicated.  But for this particular usage I think switching to **-q** should be OK.  I will give it a test and do a PR.
