### ISSUE TITLE
Use include directive with start-after and end-before rather than module_common.rst_

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5654]
**Description of the desired feature**

Currently, modules that are different in classic versus modern mode have three .rst files associated with them:

- `<module>.rst`
- `<module_common>.rst_`
- `ps<module>.rst`

This structure makes it harder for new contributors to submit quick fixes to the GMT documentation because if they click the `edit on GitHub` link it is likely that the content they were looking at will not be contained in that file, but rather `<module_common>.rst_`.

I propose that we move the contents of the `<module_common>.rst_` files into `<module>.rst` files (i.e., the modern mode documentation) and then use the start-after and end-before options for the include directive to include the relevant part in the classic mode documentation:

```
.. include:: <module>.rst
    :start-after: start of common text
    :end-before: end of common text
```

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
It sounds like a good idea and can reduce the number of ReST files in the doc directory.
