### ISSUE TITLE
Improve anim02

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5663]
I see that the [animation 02](https://docs.generic-mapping-tools.org/dev/animations/anim02.html) has some issues that could be improve:

1. Its upper boundary is cropped. Also the right (see the W at the LR).
2. Its has low quality (dpi). I think it could be upgrade.
3. A mp4 could be make with more resolution/size (and post on youtube as other animations). 
4. Anything else?

I offer to make the modifications. Let me know if you agree with the 3 items.

**Comment by PaulWessel** [comment]
Thanks for bringing this up. We may wish to discuss this at a community meeting - or perhaps via github discussions.  Those first 4-5 animations predate movie and was done via scripting.  To show the result without having a very large file we dumbed them down to small gifs mostly.  Of course, this makes them look crude and not very impressive, especially 2-4.  They also differ from some of the later ones which are more complicated and fancier.  So there is some value in having very simple animation examples (spinning earth, etc) to get people started. I see anom02.sh also is printing its own angle label at TR even though movie -L should be used for this. So yes, we should fix this one but probably all of them, and possibly only do high-res YouTube versions and using standard HD format.  For anim02 this may mean extending the region to better fit a HD frame.  Looks like anim04 is failing - I see just a white movie with some line at my end.  Anim 5 only has a small number of frames (one per eigenvalue) so we annot really make that a longer movie unless we use a more elaborate gridding example.

So let's wait with doing anything until we have a group discussion next Thursday on what to do with animations in general, @meghanrjones can you please add that topic to the agenda?

**Comment by meghanrjones** [comment]
I added it to the agenda for next week. Thanks for opening the issue and offering the make the modifications, @Esteban82!

**Comment by Esteban82** [comment]
I am working a bit on the script. I see that the following line is used. 

`	gmt plot -Sc0.8i -Gwhite -Wthin <<< "256.25 35.6"`

Just for curiosity, is it the same than:

`echo 256.25 35.6 | gmt plot -Sc0.8i -Gwhite -Wthin
`

Should I use a pipe instead?

Paul, is it possible to print the rotating arrow with movie -L? I don't know how. I used an inset.

**Comment by PaulWessel** [comment]
Yes, the <<< can be replaced with the pipe you suggested.

No, the rotating arrow is not a label, so -L is out.  One could imagine adding a new code to -P for a rotating arrow, but here it is less of a progress bar and just indicates illumination direction.  If you made a movie for angles 35 to 75 you would not want that to spin around 360 like a progress indicator goes.  So I think it needs to be plotted as a symbol.

**Comment by Esteban82** [comment]
This is my new version of the animation. 

https://user-images.githubusercontent.com/17908951/130306608-706701b5-c75d-42a8-89cf-9daa5d98c590.mp4

![anim02](https://user-images.githubusercontent.com/17908951/130306617-e0145e41-c06d-4411-b7da-541c2c0febb7.png)

Script:
```

if [ $# -eq 1 ]; then	# Just make master PostScript frame 0
	opt="-M0,png"
else	# Make animated GIF
	#opt="-A+l"
	opt="-Fmp4"
fi
# 1. Create files needed in the loop
cat << 'EOF' > pre.sh
gmt begin
	gmt math -T0/360/2 T 180 ADD = angles.txt
	gmt makecpt -Crainbow -T500/4500 -H > main.cpt
    gmt grdcut @earth_relief_15s -R-114/-103/35/40 -Gtopo.nc
gmt end
EOF
# 2. Set up the main frame script
cat << 'EOF' > main.sh
gmt begin
	width=$(gmt math -Q ${MOVIE_WIDTH} 0.59i SUB =)
	gmt grdimage topo.nc -I+a${MOVIE_COL0}+nt2 -JM${width} -Cmain.cpt \
		-BWSne -B1 -X0.4i -Y0.2i --FONT_ANNOT_PRIMARY=9p
	gmt inset begin -DjBR+w0.81i+o0.1i
        echo 0.5 0.5 | gmt plot -R0/1/0/1 -JX? -Sc0.8i -Gwhite -Wthinner
		echo 0.5 0.5 ${MOVIE_COL1} 0.37i | gmt plot -Sv0.15i+e -Gred -Wthin
	gmt inset end
gmt end
EOF
# 3. Run the movie
gmt movie main.sh -Chd -Nanim02 -Tangles.txt -Sbpre.sh -D24 -Zs $opt
```

**Comment by PaulWessel** [comment]
Looks nice! A few comments:

1. Maybe "translate" to SI units instead, and round to better number (avoid 0.59 instead of 0.6 etc)?
2. Replace the banned rainbow with a more scientific colormap?
3. Maybe do every integer degree instead of 2?
4. Since you are using gmt inset, maybe draw the outline of the inset now with shade box?
5. Instead of the white circle, maybe use rose to draw something smarter, including W N S E direction labels? Maybe rose reading /dev/null.
6. Maybe the inset should have a label that says "Illumination Direction" to better explain what we are looking at?

**Comment by Esteban82** [comment]
Ok. I agree. I didn't want to change it very much from the original. With 3), I try -T0/360/1 but it seems that the changes were very smooth. 

I think that there is a problem with the arrow. I have the sensation that in the map the shadows are rotating clockwise (CW) while the arrow does it CCW.

**Comment by PaulWessel** [comment]
Yes I think you are right.  Look at those small bumps around 106W, 36:45N which seem to be out of sync.  Try 90-az for the arrow.

**Comment by Esteban82** [comment]
"Illumination Direction" means where the light is going, right? Or where it is coming from?

A new version. I have to add points 5 and 6. I use oleron master cpt. 


https://user-images.githubusercontent.com/17908951/130340162-94d1e48f-4289-4e31-b283-a3155b567051.mp4

**Comment by PaulWessel** [comment]
We usually ay "illuminated from" so it is where the source is.  But it is OK to say that the arrow shows the direction of the illumination (which it does here).  Nice!

**Comment by Esteban82** [comment]
Here the arrow shows where the light is coming from. 

I think it would be better this meaning because it shows directly the angle that should be used for grdimage -I+a.


https://user-images.githubusercontent.com/17908951/130340466-fa034b8c-5c59-4670-b24e-612a47fa4dc2.mp4

**Comment by PaulWessel** [comment]
OK, I am fine with that.  We will make sure the script and the caption says it correctly this time.

**Comment by Esteban82** [comment]
I think this is better. I just need to get a bigger arrow head.

`		echo 0.5 0.5 ${MOVIE_COL0} | gmt plot -Sk@azimuth/1c -W0.5p -Gred --MAP_FRAME_TYPE=plain`



https://user-images.githubusercontent.com/17908951/130341161-36e8a42c-30b8-4068-9113-f25c65884dd1.mp4

**Comment by PaulWessel** [comment]
Note head size just scales with pen width, so fatter pen the bigger head.

**Comment by Esteban82** [comment]
Here I modified the pen witdh and add a "label" (is font 6 so I should increase it up to 8 at least). Should I use "Ilumination Direction" or something else (like "Ligth source")?

![anim02](https://user-images.githubusercontent.com/17908951/130468848-6c2ee044-38ac-40af-9f44-fa013c4d8923.png)

**Comment by PaulWessel** [comment]
Maybe "Location of Light Source" is more descriptive here?

**Comment by Esteban82** [comment]
I think it is too long.

Which is the proper way to add the label? I am using the following. It is a bit hard to reduce the white space above the text.


Could I use `gmt plot -B+t`? I try buy it didn't work.

```
gmt inset begin -DjBR+w2.1c/2.6c+o0.2c -F+gwhite+s+p
        echo 0.5 0.5 | gmt plot -R0/1/0/1 -JX? -Sc2c -Gwhite -Wthinner -Y-0.25
	echo 0.5 0.5 ${MOVIE_COL0} | gmt plot -Sk@azimuth/1.0c -W1.75p -Gred
	echo Ligth Source | gmt text -F+cTC+f9 -D0/0
gmt end
```



![anim02](https://user-images.githubusercontent.com/17908951/130550528-40801da9-f3f8-42a6-b9fa-3add87a2eb90.png)

**Comment by PaulWessel** [comment]
I think this great, just watch spelling of light!

**Comment by PaulWessel** [comment]
I think it is good to go. but note we have an issue with the @azimuth symbol where the arc grows fine from 0 to 260 and then switches to -90 to 0.  I will need to fix that I think.

**Comment by PaulWessel** [comment]
Wait a minute, I see no such issue now and my own test it works fine for 0-360 degrees. Perhaps you updated the movie? Anyway, looks very good now.

**Comment by Esteban82** [comment]
No, I haven't updated the movie and I still see the issue. Here the frame for the angle 305º.

![anim02](https://user-images.githubusercontent.com/17908951/131203809-3ac2622f-bbd2-49de-b965-3418ef1aa239.png)

**Comment by PaulWessel** [comment]
Maybe I was dreaming... Well, it looks great so ready for a PR I think.

**Comment by Esteban82** [comment]
Ok. I will do it.
