### ISSUE TITLE
Update the default value of PS_CONVERT and the begin module

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5668]
In https://github.com/GenericMappingTools/gmt/pull/5583, some modifiers of **-A** options are moved to the **-I** option. Now, **-I** should be used to crop the image.

The default value of PS_CONVERT is `A`, but now it should be `I`. 

The "begin" module also need to be updated.

**Comment by PaulWessel** [comment]
Hm, no. -A is still the option that crops the image. -I adjusts the BB further (from original or cropped size), and N colors it.  So PS_CONVERT default will remain A.

**Comment by seisman** [comment]
I think I misunderstood these two options.
