### ISSUE TITLE
Let LaTeX expressions support colors 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5712]
**Description of the desired feature**

```
gmt text -R0/10/0/4 -Jx1c -Baf -F+f12p,1,red -png map << EOF
5 2 <math>\Delta\sigma=x^2+y^2</math>
EOF
```

**Output:**

![map](https://user-images.githubusercontent.com/3974108/131206995-af11b712-ebe3-4a8d-be8a-0fa41312d3b1.png)

It would be better if the LaTeX expressions can follow the text color settings.

**Comment by PaulWessel** [comment]
I see color is set but then unset before it can be used.  I have experimented with placement of that line and can make this work - it will just take a change in postscriptlight.c.  Will make a PR later today.
