### ISSUE TITLE
grdblen crashes with externals when input grids must be resampled.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5715]
See [topic ](https://forum.generic-mapping-tools.org/t/error-with-grdblend-gmt-jl/2029/2) in forum

The problem arises when ``grdsample`` is called and the output tries to overwrite an external object
https://github.com/GenericMappingTools/gmt/blob/master/src/grdblend.c#L474

B[n].G->data then points to invalid memory and a crash follows later when trying to access it.

**Comment by PaulWessel** [comment]
That **grdsample** command writes to a temporary file called grdblend_resampled_?_?.grd, so I dont think related to writing. Perhaps **grdblend** is trying to do something to the external input grid related to pads?

**Comment by PaulWessel** [comment]
I should have some time this afternoon to try out the Julia debug instructions etc.

**Comment by joa-quim** [comment]
Debugging from Julia calls is becoming impossibly slow. Probably I meant what happens in
https://github.com/GenericMappingTools/gmt/blob/master/src/grdblend.c#L501
