### ISSUE TITLE
Improve Anim03

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5720]
It is easier for me to open a issue to discuss the new animation before making a PR.

Modifications:

- Change to HD and SI units.
- Increase figure size
- Inverse the sense of rotation (-p**-**${MOVIE_COL0})
- Remove frame annotations and gridlines. Add north. 
- Change the point of rotation (19W instead of 20W).
- Use dem with more resolution (30 s).
- Start animation with a view from the south (180) instead of north (0).

https://user-images.githubusercontent.com/17908951/131437986-922de0aa-07fa-4318-b2fd-f4c9db1af7d4.mp4

Full script:
```
if [ $# -eq 0 ]; then	# Just make master PostScript frame 27 (az = 135)
	opt="-M30,png -Fmp4"
else	# Make animated GIF, infinitely looping
	opt="-M30,png"
fi
# 1. Create files needed in the loop
cat << 'EOF' > pre.sh
gmt begin
	gmt math -T180/540/1 -o1 T = angles.txt
	gmt makecpt -Crelief -T-2000/2000/20 -H > iceland.cpt
	gmt grdclip @earth_relief_30s -R-26/-12/63/67 -Sb0/-1 -Gabove.nc
	gmt grdgradient above.nc -A45 -Nt1 -Gintens.nc
gmt end
EOF

# 2. Set up the main frame script
cat << 'EOF' > main.sh
gmt begin
	#gmt grdview above.nc -Rabove.nc -JM16.5c -Ciceland.cpt -Qi${MOVIE_DPU} -Baf \
	#	-X7.6c -Y5c -p-${MOVIE_COL0}/35+w19W/65N+v3.8c/1.9c -Iintens.nc
    gmt grdview above.nc -Rabove.nc -JM19c -Ciceland.cpt -Qi${MOVIE_DPU} -Bf -X7.6c -Y5c -p-${MOVIE_COL0}/35+w19W/65N+v4.5c/1.7c -Iintens.nc
	gmt basemap -Tdn0.06/0.8+w2c+f+l,,,N -p-${MOVIE_COL0}/35+w19W/65N+v4.5c/1.7c
gmt end
EOF
# 3. Run the movie
gmt movie main.sh -Chd -Nanim03 -Tangles.txt -Sbpre.sh -D24 -Vi $opt -Pb -Zs
```

**Comment by meghanrjones** [comment]
Very nice! What do you think about showing the bathymetry too and including some vertical exaggeration for the above-water part? Example is below.


https://user-images.githubusercontent.com/14077947/131587752-a3cd9164-57d4-4ed0-aeff-590cb52314e6.mp4

```
if [ $# -eq 0 ]; then	# Just make master PostScript frame 27 (az = 135)
	opt="-M30,png -Fmp4"
else	# Make animated GIF, infinitely looping
	opt="-M30,png"
fi
# 1. Create files needed in the loop
cat << 'EOF' > pre.sh
gmt begin
	gmt math -T180/540/1 -o1 T = angles.txt
	gmt makecpt -Coleron -T-2000/2000/20 -H > iceland.cpt
	gmt grdcut @earth_relief_30s -R-26/-12/63/67 -Giceland.nc
	gmt grdgradient iceland.nc -A45 -Nt1 -Gintens.nc
	gmt grdclip iceland.nc -Sb0/NAN -Sr0/NAN -Gabove.nc
	gmt grdclip iceland.nc -Sa0/NAN -Gbelow.nc
gmt end
EOF

# 2. Set up the main frame script
cat << 'EOF' > main.sh
gmt begin
	gmt grdview below.nc -Rbelow.nc -JM19c -Ciceland.cpt -Qc${MOVIE_DPU} -Bf -X7.6c -Y5c -p-${MOVIE_COL0}/35+w19W/65N+v4.5c/1.7c -Iintens.nc
	gmt grdview above.nc -Rabove.nc -JM19c -JZ0.75c -Ciceland.cpt -Qc${MOVIE_DPU} -Bf -p-${MOVIE_COL0}/35+w19W/65N+v4.5c/1.7c -Iintens.nc
	gmt basemap -Tdn0.06/0.8+w2c+f+l,,,N -p-${MOVIE_COL0}/35+w19W/65N+v4.5c/1.7c
gmt end
EOF
# 3. Run the movie
gmt movie main.sh -Chd -Nanim03 -Tangles.txt -Sbpre.sh -D24 -Vi $opt -Pb -Zs
```

**Comment by Esteban82** [comment]
Yes, very nice.  Maybe we would have to indicated the amount of vertical exaggeration. Is it possible for grdview to inform this?

Also we could drape the satellite image over the topography? I failed to do it. I think I need some extra commands to properly cut the image.

**Comment by Esteban82** [comment]
In the above animation I don't like that at one point the image looks dark. This is because the lighting is placed in the opposite sector to the point of view.

So I have modified the script so that the illumination rotates along with the figure. I made 2 animations. One in which the illumination is from the front (angle 0) and another with an angle of 30. What do you think?

Angle 30: 

https://user-images.githubusercontent.com/17908951/132270960-f167d335-af07-490b-b3b1-457d6811f9f0.mp4

Angle 0: 

https://user-images.githubusercontent.com/17908951/132271434-d1a0b036-abdb-4f0d-a30e-1e063c6f4721.mp4

Full script:
```

if [ $# -eq 0 ]; then	# Just make master PostScript frame 27 (az = 206)
	opt="-M27,png -Fmp4"
else	# Make animated GIF, infinitely looping
	opt="-M27,png"
fi
# 1. Create files needed in the loop
cat << 'EOF' > pre.sh
gmt begin
	gmt math -T180/540/1 T 30 SUB = angles.txt
	gmt makecpt -Coleron -T-2000/2000/20 -H > iceland.cpt
	gmt grdcut @earth_relief_15s -R-26/-12/63/67 -Giceland.nc
	gmt grdclip iceland.nc -Gabove.nc -Sb0/NAN -Sr0/NAN
	gmt grdclip iceland.nc -Gbelow.nc -Sa0/NAN
gmt end
EOF

# 2. Set up the main frame script
cat << 'EOF' > main.sh
gmt begin
	gmt grdgradient iceland.nc -Nt1 -Gintens.nc -A-${MOVIE_COL1}
	gmt grdview below.nc -Rbelow.nc -Ciceland.cpt -Qc${MOVIE_DPU} -Iintens.nc -JM19c  -p-${MOVIE_COL0}/35+v4.5c/1.7c -Bf -X7.6c -Y5c
	gmt grdview above.nc -Rabove.nc -Ciceland.cpt -Qc${MOVIE_DPU} -Iintens.nc -JZ0.4c -p 
	gmt basemap -Tdn0.06/0.8+w1.75c+f+l,,,N -p
gmt end
EOF
# 3. Run the movie
gmt movie main.sh -Chd -Nanim03_0 -Tangles.txt -Sbpre.sh -D24 -Vi $opt -Pb -Zs
```

**Comment by meghanrjones** [comment]
Very nice! I prefer the animation with an angle of 30. Looks ready for a PR!

**Comment by Esteban82** [comment]
Ok. I think so. Regrettably the earth_relief_03s it is not available for Iceland.

**Comment by PaulWessel** [comment]
The mental to-do list is to extend the 03 and 01 to higher latitudes via other high-quality data...

**Comment by PaulWessel** [comment]
But I agree with Meghan that this is ready for a PR.
