### ISSUE TITLE
Inconsistency between rows/cols and height/width in subplot

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#573]
The rectangular layout of panels is specified via **subplot begin** by the argument _nrows_**x**_ncols_.  However, the dimensions of a panel is specified by _width/height_.  Since _width_ is related to _columns_ and _height_ to _rows_, the order is flipped between the two settings.
Since elsewhere in GMT, such as the Cartesian plot projection we stick with _width/height_ (i.e., **-JX**_width_/_height_), perhaps we should instead require _ncols_**x**_nrows_?  However, in matrix algebra one would say rows by columns so not sure.  Let me know what you think.

**Comment by joa-quim** [comment]
Leave it as is. *height/with* or *ncols* **x** *nrows* would be something no one would remember.

**Comment by PaulWessel** [comment]
OK, I guess that is fair. BTW, wonder why Github thought this was my first issue.. @leouieda ?

**Comment by PaulWessel** [comment]
Closing this as not worth doing.

**Comment by leouieda** [comment]
I have no idea. That bot has been kind of strange in the GMT repo but I guess there is no harm. I can always shut it off if you want.

**Comment by joa-quim** [comment]
Yes, I think we should shut it up. It brings nothing really useful, not even to initiated user.

**Comment by leouieda** [comment]
We can also change what it says in case you think there is something that would be a useful reminder for first time issues or PRs. We can also remove the issue message and keep the PR message (or vice versa).

**Comment by PaulWessel** [comment]
Apart from the oddness of getting the message if you have contributed already, I think it is a nice touch to be singled out that way.  I mean, it does not bother me the least.

**Comment by leouieda** [comment]
In case there is anything you'd like to change about the welcome messages, they are stored here: https://github.com/GenericMappingTools/gmt/blob/master/.github/config.yml

I don't mind them as well but particularly the PR message could have a bit more information about what we want in a new PR (standards and the like).
