### ISSUE TITLE
cpt made from process substitution fails

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5731]
Last year I posted a request for gmt to support making cpt's with process substition.
See:

* https://github.com/GenericMappingTools/gmt/issues/4361 - request
* https://github.com/GenericMappingTools/gmt/pull/4363 - implementation branch

This has now (well, June 11th probably) stopped working:

```
$ gmt grdimage @earth_relief_05m -C<(gmt makecpt -Cjet -T-1000/0/100) -JM15c -RNO -pdf map
grdimage [ERROR]: Color palette table /dev/fd/63 is empty
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
grdimage [ERROR]: Failed to read CPT /dev/fd/63.
```

Turns out it stopped working in aacc801d5bbc4844115f2bee64282ec6bf0e6252 after #5477 was merged.

Not sure why this happens, but could it be that the input a process substitution creates (``/dev/fd/63``) confuses gmt when it checks if it's empty?

**Comment by PaulWessel** [comment]
Possibly a permission issue.  Are you able to see what the file permissions and ownership on /dev/fd/63 is?

**Comment by anbj** [comment]
```
$ ls -l <(echo)
lr-x------ 1 anbj anbj 64 Sep  6 19:52 /dev/fd/63 -> 'pipe:[1196496]'
```

**Comment by PaulWessel** [comment]
So I am unable to reproduce this on macOS of course. Just checking: If you run this again and again (copy paste run) it always fails, yes?  Can you reproduce the problem, @Esteban82 and @joa-quim?

**Comment by anbj** [comment]
I'm fairly certain it always fail, yes.

**Comment by PaulWessel** [comment]
I suspect then the stat command fails to get the size.  I will see if I can add a check on that.

**Comment by PaulWessel** [comment]
Well, I do check that stat is successful (returns 0) so it really returns a size of 0.  Yet reading more about process substitution (which I was not really aware of) it seems these special files are like pipes so random access is not allowed and I suspect stat may not be allowed or that the behavior is not guaranteed to work.  To wit, while it works for me on macOS, I am unable to ls -l /dev/fd/63 so something is not clear.  I will solve this by exempting files starting with /dev/fd from that particular check.
