### ISSUE TITLE
Bug from histogram model when  using single model

### ISSUE THREAD

**Issue by wangliang1989** [GenericMappingTools/gmt#5745]
Apple M1 mac
I cannot understand why the first line about histogram is wrong. I feel that GMT think that I am trying to use the gmt4 model, so GMT think I should use the pshistogram instead of the histogram.
![QQ20210911-0](https://user-images.githubusercontent.com/12059719/132931801-6ba4d51b-c20b-43ec-a989-4ebfe286c64b.png)

**Comment by Esteban82** [comment]
I think that you must indicate a file to histogram to analyse.

**Comment by wangliang1989** [comment]
> I think that you must indicate a file to histogram to analyse.

Why histogram is different with regress?

**Comment by PaulWessel** [comment]
You are in classic mode so the name of the module is pshistogram.

**Comment by wangliang1989** [comment]
> You are in classic mode so the name of the module is pshistogram.

So, How to use the single model? Please help me?

**Comment by PaulWessel** [comment]
Not sure what you mean by “single model”.

**Comment by wangliang1989** [comment]
> Not sure what you mean by “single model”.

😢 English Language Problem

In China, we call this as single model:

````bash
gmt coast -Rg -JH15c -Gpurple -Baf -B+t"My First Plot" -pdf,png GlobalMap
````
and call this as modern model:
````bash
gmt begin GlobalMap png,pdf
gmt coast -Rg -JH15c -Gpurple -Baf -B+t"My First Plot"
gmt end
````

**Comment by Esteban82** [comment]
This is single model uses the classic mode names. So you must use pshistogram instead of histogram. Try this:

`gmt pshistogram -JX10c -T0/100/10 -I`

**Comment by Esteban82** [comment]
It is the error number 2 of your screenshot.

**Comment by meghanrjones** [comment]
Single model only works for plotting commands (see item 1 in this list: https://docs.generic-mapping-tools.org/dev/cookbook/one-liner.html#one-liner-syntax). Since the command uses the `-I` (inquire) option, no plotting occurs so you cannot use single model mode. As @Esteban82, histogram/pshistogram also requires an input file with the tabular data. Here is an example:

`gmt pshistogram  @v3206_06.txt -T0/100/10 -I`

or

```
gmt begin
gmt histogram @v3206_06.txt -T0/100/10 -I
gmt end
```

I am closing this issue since the code should not work (no plotting), but feel free to comment if you disagree.

**Comment by wangliang1989** [comment]
Thank you all.
I usually read the Chinese manual of GMT. So, I don't know the English name of "single model" should be one-line command. Not easy to read the English manual of GMT for me. I think you can realize I am from China by my photo.

**Comment by PaulWessel** [comment]
No worries, we are almost all non-english speakers by birth (I am Norwegian) but have now lived in the US so long I can be considered an english-speaker.  We do have to ask you to rephrase an expression from time to time to make sure we understand what you want - hence the questions.
