### ISSUE TITLE
Need better handling when simultaneous jobs are trying to download the same file

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5757]
**Description of the problem**

In experimenting with a movie that uses @earth_relief and where the resolution depends on the settings (#5753 ), **movie** is launching many jobs to make the frames, and these all run concurrently.  If many or all of them decide they need to use @earth_relief_01m (which is a tiled dataset) then it results in a flurry of calls via curl to download the individual tiles.  Hence several concurrent jobs may seek to download the exact same file, e.g., N60E120.earth_relief_01m_p.nc.  We prevent this chaos by creating a _lock file_ with the name /tmp/_file_.download and then apply standard file lock protocols (_fcntl_ for the *nix and _LockFileEx_ on Windows).  What this does is to deny the other processes access - they will hang until the lock is released.  However, when it is released the file of interest has been downloaded so the whole need to download again has gone away, but it is too late - we are too committed at this point.  Other jobs may successfully be reading the downloaded file when another process starts re-downloading and ruining it - leading to failed plots [there are some guesses on my part here - hard to debug this scenario...].

It seems the solution here would be that once the lock is released (which means the file has been downloaded or possibly failed for other reasons) we should _check again_ if the file is there before we continue to download.  If the file miraculously has arrived (via one of the other processes) then we should abort the download and get back to treating it as a file on the system.  It seems if we simply return from gmt_download_file with no error at that point it should continue as if it was successful.

Any thoughts or experiences on this, @GenericMappingTools/core ?

**Comment by meghanrjones** [comment]
This is the error that regularly causes a few tests to fail when the tests are run on many cores:

```
gmt [ERROR]: Failed to open /Users/User/.gmt/server/gmt_data_server.txt! [fopen error: No such file or directory]
gmt [ERROR]: Failed to rename /Users/User/.gmt/server/gmt_data_server.txt to /Users/User/.gmt/server/gmt_data_server.txt.old.
grdgradient [ERROR]: Libcurl Error: HTTP response code said error
grdgradient [WARNING]: You can turn remote file download off by setting GMT_DATA_UPDATE_INTERVAL to "off"
grdgradient [ERROR]: File /Users/User/.gmt/cache/earth_relief_05m_g was not found
grdgradient [ERROR]: Cannot find file /Users/User/.gmt/cache/earth_relief_05m_g
grdgradient [ERROR]: File /Users/User/.gmt/cache/earth_relief_05m_g was not found
grdgradient [ERROR]: Cannot find file /Users/User/.gmt/cache/earth_relief_05m_g
grdgradient [ERROR]: File /Users/User/.gmt/cache/earth_relief_05m_g not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
```

**Comment by PaulWessel** [comment]
@meghanrjones, perhaps #5777 will help - it seems correct to do regardless of the issue above though.

**Comment by meghanrjones** [comment]
> @meghanrjones, perhaps #5777 will help - it seems correct to do regardless of the issue above though.

Didn't get the previous error with that branch, but did receive this oddity (since `test/grdsample/resample.sh` only uses classic mode).

```
 493/1098 Test  #523: test/grdsample/resample.sh ...................***Failed    0.80 sec
Set GMT_SESSION_NAME = 10010
gmt [ERROR]: Option -K not allowed for modern GMT mode.
ERROR: gmtest:82
```

**Comment by PaulWessel** [comment]
Yes, that is another type of error hard to track down.  I do get that from time to time as well, and rerunning that test with ctest -R resample.sh will show that it passes.  These things are intermittent but related to ctest running things in parallel.  Perhaps some tests end up with the same PPID and this happens.
