### ISSUE TITLE
colorbar length as a percentage relative to a map side

### ISSUE THREAD

**Issue by OgnevinGeo** [GenericMappingTools/gmt#5771]
**Description of the desired feature**

Hello dear PyGMT community,

I would like to request a feature that will allow to set a colorbar's length to any desired percentage relative to a map side. Currently, it is set to 80 % by default, and a user needs to provide a specific value with `+w` modifier to change the colorbar's length. It would be very nice though if one could set any arbitrary number in percents of a map side, like 100 % as sometimes is asked by reviewers during the publication process.

This request is the follow-up to the [discussion in the GMT community forums](https://forum.generic-mapping-tools.org/t/pygmt-colorbar-length-settings/2071).

Thank you.

**Are you willing to help implement and maintain this feature?** No, I don't think I have enough skills so far

**Comment by Esteban82** [comment]
Great idea. And I think it would be useful for GMT as well.
