### ISSUE TITLE
Mix of plotting errors related to projection and/or region

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5774]
Sorry about vague description. Mix of oneliners with some problems.

Frame is partly messed up:

```
gmt grdimage @earth_relief_10m -JEPSG:3996/20c -R0/60/60/70r -Bafg -pdf test
(or gmt grdimage @earth_relief_10m -JS0/90/20c  -R0/60/60/70r -Bafg -pdf test)
```

Note bad ``-R``:

```
gmt grdimage @earth_relief -JEPSG:3996 -R0/60/120/70 -Bafg -pdf test
gmt [ERROR]: No projection selected
gmt [ERROR]: General map projection error
```

OK - now change @earth_relief to ``@earth_relief_10m`` (you'll need to run ``gmt clear sessions`` first):

```
gmt grdimage @earth_relief_10m -JEPSG:3996 -R0/60/120/70 -Bafg -pdf test
```

and you'll get a plot and a whole bunch of ``ERROR 10: Pointer 'hTransform' is NULL in 'OCTTransform'.``-messages. I guess these come from ``gdal``. If you change the projection to gmt-syntax, you'll get a plot and the following output:

```
gmt grdimage @earth_relief_10m -JS0/90/10c -R0/60/120/70 -Bafg -pdf test
grdimage [WARNING]: For a UTM or TM projection, your region 0/60/120/70 is too large to be in degrees and thus assumed to be in meters
```

Again, ``ERROR 10: Pointer 'hTransform' is NULL in 'OCTTransform'.``-messages and strange white area:

```
gmt grdimage @earth_relief_10m -JEPSG:4326 -pdf test -RNO -Bafg -I
```

Remove the ``-I`` and you won't get the error messages, but the plot still has a strange white area:

```
gmt grdimage @earth_relief_10m -JEPSG:4326 -pdf test -RNO -Bafg
```

**Comment by joa-quim** [comment]
You are missing a **+r**

```
grdimage @earth_relief_10m -JS0/90/10c -R0/60/120/70 -Bafg -pdf
unknown [WARNING]: Modern mode oneliner syntax given but no file prefix provided - using gmtsession
grdimage [WARNING]: For a UTM or TM projection, your region 0/60/120/70 is too large to be in degrees and thus assumed to be in meters
```
and this works fine for me
```
grdimage @earth_relief_10m -JS0/90/10c -R0/60/120/70+r -Bafg -pdf
unknown [WARNING]: Modern mode oneliner syntax given but no file prefix provided - using gmtsession
grdimage [WARNING]: 60 annotations along the left border were skipped due to crowding.
grdimage [WARNING]: Crowding decisions is controlled by MAP_ANNOT_MIN_SPACING, currently set to 27.1668p.
grdimage [WARNING]: Decrease or increase MAP_ANNOT_MIN_SPACING to see more or fewer annotations, with 0 showing all annotations.
```

**Comment by anbj** [comment]
Argh, it's ``+r``, not ``r``.

Sorry.

**Comment by joa-quim** [comment]
But ``r`` should work too. If it doesn't then is a backward compat bug.

**Comment by anbj** [comment]
So that's why I'm using ``r`` - I'm doing old school style without knowing it.

So

```
grdimage @earth_relief_10m -JS0/90/10c -R0/60/120/70 -Bafg -pdf
grdimage @earth_relief_10m -JS0/90/10c -R0/60/120/70+r -Bafg -pdf
```
Should produce the same plot, but does not.

**Comment by PaulWessel** [comment]
Either -R0/60/120/70+r or -R0/60/120/70r works fine - we parse for both.

**Comment by PaulWessel** [comment]
Let me know if there is anything else on this issue or if we can close.

**Comment by anbj** [comment]
A big mix here, so maybe best to close and open individual issues.

Many or the problems are still there. Recap:

- Messed up frame: `gmt grdimage @earth_relief_10m -JEPSG:3996/20c -R0/60/60/70r -Bafg -pdf test`
- The `-R` is deliberately wrong here which cause alot of `ERROR 10: Pointer 'hTransform' is NULL in 'OCTTransform'`: `gmt grdimage @earth_relief_10m -JEPSG:3996 -R0/60/120/70 -Bafg -pdf test`
- Same error, and white area in plot: `gmt grdimage @earth_relief_10m -JEPSG:4326 -pdf test -RNO -Bafg -I`. Remove `-I` and you get rid of the error messages, but still white area in plot.

**Comment by PaulWessel** [comment]
But I do not think GMT plotting supports any proj4 specifications that are not converted directly to a GMT projection, @joa-quim ?

**Comment by joa-quim** [comment]
Right. Plotting requires creating frames and those are built with the GMT machinery so all used _proj_ must be convertible to **-J** (unless no frames are required). ``mapproject`` ops should be free of this restriction.

**Comment by PaulWessel** [comment]
How can we catch this issue and at least give a warning?

**Comment by joa-quim** [comment]
Don't know. I'm not even sure what I said is completely correct. The error messages
```
ERROR 10: Pointer 'hTransform' is NULL in 'OCTTransform'.
```
means that the requested transform failed on GDAL. Why? ?

**Comment by PaulWessel** [comment]
I think that example passes in a flawed region (it is a +r region but not using +r).  So not caught in GMT I think.

**Comment by anbj** [comment]
Closing.
