### ISSUE TITLE
grdhisteq -D<table> writes to standard output

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5785]
**Description of the problem**

Even when `<table>` is provided after -D for grdhisteq, the output still gets sent to standard output. Should the docs or code be updated? This is the current description in the usage message:

```
  -D[<table>]
     Dump level information to <table> or standard output if not given.
```

**Full script that generated the error**

```
gmt grdhisteq @earth_relief_01d -R-5/5/-5/5 -Dtest.txt
```

**Actual outcome**

Result written to standard output.

**Expected outcome**

Result written to test.txt

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.3

**Comment by PaulWessel** [comment]
Hm, can confirm what you say.  Not sure why the table file is not used - will need to debug.  It is an old module that Walter wrote that probably should be refactored so that output can happen in the main and not hidden inside a function that does the computation (this all predates the API).
