### ISSUE TITLE
Revamping Map Projection Options and Semantics

### ISSUE THREAD

**Issue by billyauhk** [GenericMappingTools/gmt#5797]
**Revamping Map Projection Options and Semantics**
Background: Would like to reproduce the map at https://www.pref.toyama.jp/1510/kensei/kouhou/kankoubutsu/kj00000275.html
Projection is Azimuthal Equidistant with projection center at 36°41'43"N 137°12'41"E , but the map region is kind of oblique and the projection center is not at the center of the map. One may measure the geographic coordinates for the four corners of the map, but those information cannot be handled by GMT for drawing a map similar to the above-mentioned map.

It cannot be done by the -R's +r option, where a very narrow stripe covering Korean peninsula will result, but don't even cover all main islands of Japan:
`gmt basemap -R128.34/60.87/127.54/13.30+r -JE137.21139/36.69528/30/4i -B2g2 -Xc -Yc -Vd`

If people tried to use the +u option, the code will run into "mapproject" and stuck there waiting for input (when there is none). In strict sense azimuthal equidistant projection is not rectilinear, so I do not want to consider it as a bug. Example:
`gmt basemap -R-1076488.86/-495350.54/-2547427.23/2715664.97+u -JE137.21139/36.69528/30/4i -B2g2 -Xc -Yc -Vd`

**Are you willing to help implement and maintain this feature?** Yes.

In some sense a huge revamp might be needed in attempt to make all projections available with PROJ also available in GMT, or support non-rectangular map regions (say polygonal, which will enable border breaks). That would surely create a lot of corner cases which will require a lot of developers' time. But before that we might need to collect a list of stuff which users want to do but cannot be done under the current code (and create test cases for them).

Submit as feature request so to see how developers and existing users look at this problem, as this also correlates with quite a number of longterm bugs...or this should be put into discussions? Dunno but just set this as feature request first.

**Comment by joa-quim** [comment]
Thanks for this call but full add of PROJ projections is something we are aware of as well as its difficulties. Closing this for now.
