### ISSUE TITLE
psconvert - do not force output with -T

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5807]
Ref. https://docs.generic-mapping-tools.org/dev/psconvert.html, the only required argument is *psfiles*.

If you specify only a postscript file, ``-Tj`` is implicit.

Therefore, I think
- ``-T`` should be included as a required argument, with ``-Tj`` being noted as the default (as it is under the ``-T`` switch
- or, make ``-T`` truly optional, and do not output anything (well, not quite). This is relevant if one wants to use e.g. ``-W+g``. This will produce a tiff, which in some cases might be all you want. Another example is if I use ``gmt psconvert -Tt -W+g``. I get two identical tiff-files with two different names; one .tif and one .tiff (not quite right; the latter contains projection information as a proj string).

**Comment by meghanrjones** [comment]
What do you think about having another **-T** directive that sets no output file so that `gmt psconvert -W+g -Tn` could be used to only produce a tiff? I don't think the default behavior for `psconvert <file>` should be changed, since that would break backwards compatibility.

**Comment by anbj** [comment]
Sure, that would be a way to do it.

**Comment by PaulWessel** [comment]
Hi @joa-quim.  The way this seems to work is that if I run

`gmt psconvert t.ps -W+g -V`

I get the default JPG file:

`psconvert [INFORMATION]: Convert to JPG...`

This file is then used with gdal_translate to create a geotiff:

`gdal_translate -mo TIFFTAG_XRESOLUTION=300 -mo TIFFTAG_YRESOLUTION=300 -a_srs '+proj=stere +lat_0=90 +lon_0=35 +k=0.9996 +x_0=0 +y_0=0 +units=m +a=6378137.000 +b=6356752.314 +ellps=WGS84 +datum=WGS84 +units=m +no_defs' -co COMPRESS=LZW -co TILED=YES  't.jpg' 't.tiff'`

However, in my directory I find the desired t.tiff and the world file t.jgw but also the unrequested t.jpg.

Two issues:

- Unbeknownst to the user, the intermediate raster defaults to JPG which is not lossless (we default to **GMT_JPEG_DEF_QUALITY**=90.  So the final geotiff is already a bit compromised without me realizing it.
- I never wanted that JPG anyway, so we should delete it unless the user selects **-T** in some form.

I propose these changes: If **-W+g** is selected _and_ no **-T** given, then

1. Set  the T.quality to 100 for a lossless intermediate JPG
2. Delete the intermediate JPG when done

Agree with that?

**Comment by joa-quim** [comment]
Sure. And probably the ``gdal_translate`` step could be replaced by  call to ``grdgdal``, thus avoiding the need of having the gdal binary around (for unixers)

**Comment by PaulWessel** [comment]
Closing this for now.
