### ISSUE TITLE
Coordinates blows up if PS_MEDIA is too small to contain figure

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5808]
NB! This might a `gdal`-issue. In that case I apologize.

Related post in the forum: https://forum.generic-mapping-tools.org/t/exporting-embellished-rasters-with-proper-coordinates/1513/3

If the ``PS_MEDIA`` is too small and figure 'floats outside the edge' the coordinates blows up. The following script creates three tiff's (and tif's which I do not need, see #5807).

```
#figure is contained within PS_MEDIA - works
ps=works.ps
gmt grdimage -JM5c -RNO @earth_relief_10m -P -Bxafg -Byafg > $ps
gmt psconvert -Tt -W+g -Z $ps

#figure is too big for chosen PS_MEDIA - bad coordinates (see below)
ps=does-not-work-A4.ps
gmt grdimage -JM25c -RNO @earth_relief_10m -P -Bxafg -Byafg > $ps
gmt psconvert -Tt -W+g -Z $ps

#PS_MEDIA set to A0 is now big enough to contain the figure - works
ps=now-works-A0.ps
gmt grdimage -JM25c -RNO @earth_relief_10m -P -Bxafg -Byafg --PS_MEDIA=A0 > $ps
gmt psconvert -Tt -W+g -Z $ps
```

Remove ``-P`` and the problem affect the x-coordinates, instead of the y-coordinate due to the orientation (see below).

And here is ``grdinfo`` output of the three different tiff's:

```
$ gmt grdinfo works.tiff
works.tiff: Title: Grid imported via GDAL
works.tiff: Command: 
works.tiff: Remark: 
works.tiff: Pixel node registration used [Cartesian grid]
works.tiff: Grid file format: gd = Import/export through GDAL
works.tiff: x_min: -3300110.20963 x_max: 3292090.50074 x_inc: 8019.7088934 name: x n_columns: 822
works.tiff: y_min: 7298623.17362 y_max: 16679956.7194 y_inc: 8018.2337998 name: y n_rows: 1170
works.tiff: v_min: 1.79769313486e+308 v_max: -1.79769313486e+308 name: z
works.tiff: scale_factor: 1 add_offset: 0
+proj=merc +lon_0=12.208602 +k=1 +x_0=0 +y_0=0 +a=6378137 +rf=298.257220143428 +units=m +no_defs

$ gmt grdinfo does-not-work-A4.tiff
does-not-work-A4.tiff: Title: Grid imported via GDAL
does-not-work-A4.tiff: Command: 
does-not-work-A4.tiff: Remark: 
does-not-work-A4.tiff: Pixel node registration used [Cartesian grid]
does-not-work-A4.tiff: Grid file format: gd = Import/export through GDAL
does-not-work-A4.tiff: x_min: -2556007.23668 x_max: 1129137.2628 x_inc: 1605.02809211 name: x n_columns: 2296
does-not-work-A4.tiff: y_min: 6.89305648994e+12 y_max: 6.8930617669e+12 y_inc: 1604.91296357 name: y n_rows: 3288
does-not-work-A4.tiff: v_min: 1.79769313486e+308 v_max: -1.79769313486e+308 name: z
does-not-work-A4.tiff: scale_factor: 1 add_offset: 0
+proj=merc +lon_0=12.208602 +k=1 +x_0=0 +y_0=0 +a=6378137 +rf=298.257220143428 +units=m +no_defs

$ gmt grdinfo now-works-A0.tiff
now-works-A0.tiff: Title: Grid imported via GDAL
now-works-A0.tiff: Command: 
now-works-A0.tiff: Remark: 
now-works-A0.tiff: Pixel node registration used [Cartesian grid]
now-works-A0.tiff: Grid file format: gd = Import/export through GDAL
now-works-A0.tiff: x_min: -2556007.23668 x_max: 2554402.20859 x_inc: 1605.02809211 name: x n_columns: 3184
now-works-A0.tiff: y_min: 7797257.28588 y_max: 16179717.6942 y_inc: 1604.91296348 name: y n_rows: 5223
now-works-A0.tiff: v_min: 1.79769313486e+308 v_max: -1.79769313486e+308 name: z
now-works-A0.tiff: scale_factor: 1 add_offset: 0
+proj=merc +lon_0=12.208602 +k=1 +x_0=0 +y_0=0 +a=6378137 +rf=298.257220143428 +units=m +no_defs
```

The notion of having a *PS_MEDIA* (or *PAPER_MEDIA* as it used to be called?) seems a bit analog.

**Comment by PaulWessel** [comment]
In classic mode the PS_MEDIA setting determines what the paper size is and Ghostscript then uses that to determine where anything is written.  If you plot outside the paper then gs does not find it.  So it is on the user to ensure the paper size is selected correctly.  While we have never done so, we could consider adding a warning if a classic mode user supplies a -R -J that computes to dimensions that exceed the selected paper size.

In contrast, in modern mode we select the largest paper size possible (10x10 meter roughly) and then crop inwards.

**Comment by anbj** [comment]
A warning would probably be nice.

Would changing the default size be an alternative?

Why can't paper size be 10x10 meter in classic mode also?

```
$ gmt defaults | grep PS_MEDIA
PS_MEDIA                       = a4
```

**Comment by PaulWessel** [comment]
Classic uses expect a papersize that is either A4 or US letter by default.  It has been that way since the early 1990s and we cannot change that.  We can add a warning of course.
Spooling a 10x10m PS to a printer might make it print out 100s of pages, depending on driver.

**Comment by anbj** [comment]
I see.

If it is easy to do, a warning might be nice.
