### ISSUE TITLE
GMT World Domination map updates

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#581]
The old server would update the GMT usage map on the front page [http://gmt.soest.hawaii.edu].  I notice we have that same figure in the README on this site but it is more than a week old.  How does this plot get updated now?  Or perhaps we need to abandon this type of figure since we won't have the download data?

**Comment by joa-quim** [comment]
You may remember that I never liked that image that intended to show the worldwide adoption (many dots) but was reset every time we had a new point release. And now that we have no way to know the downloads, even more.

**Comment by KristofKoch** [comment]
Might this be helpful?

https://help.github.com/en/articles/getting-the-download-count-for-your-releases

Not exactly usable for location data but at least you get a download count.

**Comment by leouieda** [comment]
The trouble is merging the data from the many different distribution channels. That will only measure downloads from Github. But it could tells us how many people are using the development builds.

**Comment by PaulWessel** [comment]
When GMT was younger and growing, it was fun and useful to count downloads and tell NSF managers.  With distros it will not be possible.  We also have less urgency in needing to know since GMT is well established.  Thus, we could drop the counting.
The only alternative I can think of is this: Does the operating system keep track of how many times a file is accessed? One could then at least count number of times gmt_md5_server.txt has been accessed.  This only applies to users using the @remotefiles mechanism though.

**Comment by seisman** [comment]
I don't think there are any ways to count the downloads or track the locations, as we have so many ways to distribute the GMT binary and source packages. 

> https://help.github.com/en/articles/getting-the-download-count-for-your-releases
> 
> Not exactly usable for location data but at least you get a download count.

It only shows the download count via GitHub releases, which I believe very few users use.

> The only alternative I can think of is this: Does the operating system keep track of how many times a file is accessed? One could then at least count number of times gmt_md5_server.txt has been accessed. This only applies to users using the @Remotefiles mechanism though.

We have daily CI builds. It doesn't make sense to count how many times a remote file is accessed.

**Comment by PaulWessel** [comment]
Unless I hear objections we should close this issue and move on with our lives.
