### ISSUE TITLE
How to handle multi-band grids stored in GeoTiffs

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#5816]
Paging @joa-quim on this one: Now that **grdcut** can return a subset of an image (your typical 1, 3, or 4 band byte data) the issue becomes can **grdcut** also do the same for more general "images" where there are numerous bands and they are stored as floats. GDAL has a solution for this, e.g., 

`gdal_translate -projwin -163.051107059 61.219982021 -163.047286129 61.217258591 -of GTiff sentinel_mosaic.tif sentinel_mosaic_clipped.tif`

where the sentinel file has 16 double-precision bands, but it is unaware of periodic boundary conditions.  Perhaps there are no large global "images" like this we need to worry about, but if there are it would be nice for GMT to handle that since it now can do periodic boundaries for images. Alternatively, we could implement a call to _gdal_translate_, like we do in gmt_remote.c to convert JP2 files to netCDF.  A limitation would be passing the image around in memory.

There seem to be some unimplemented situations in gmt_gdalread|write.c that would need some updates for that to work.  So far these are:

1. When a float image is encountered, we successfully learn about it in the image header, but the data type, if not an int or byte, is not stored in the header, so it says **GMT_CHAR**.  This means we will allocate a byte array to hold a stack of double precision layers and this will not work.
2. It also seems that gmt_gdalwrite.c makes assumptions of layers being byte so things will go wrong here as well.

Other than that, it seems the machinery is set up to do n_bands just fine.  So perhaps overcoming these obstacles is mostly about setting image->type to **GMT_DOUBLE** (for this data set) and use that when allocating the output array as well as the de-padding step in gmt_gdalwrite.c

**Comment by joa-quim** [comment]
> where the sentinel file has 16 double-precision bands,

What Sentinel files are stored in multi-band double precision. Sentinel-1? (Never played with those yet)

**Comment by PaulWessel** [comment]
Probably processed data (via Meghan) but that file has 16 bands so no point computing a single min/max.

**Comment by meghanrjones** [comment]
I do not have much details about the provenance of the data. It's a dataset that I had from helping someone else with GMT usage, which I shared with Paul as an example of a multi-band TIFF.

**Comment by joa-quim** [comment]
Multi-band Sentinel TIFFs that I know are UInt16, not doubles. What do they represent?

**Comment by joa-quim** [comment]
Here's a multi-layer UInt16 GeoTIFF
https://github.com/GenericMappingTools/RemoteS.jl/blob/main/test/LC08_cube.tiff

**Comment by PaulWessel** [comment]
Closed due to #5819 which is now merged.
