### ISSUE TITLE
I wish to generate a velocity map at each period in spatial grid image obtained from tomographic inversion 

### ISSUE THREAD

**Issue by chinu739** [GenericMappingTools/gmt#5828]
The tomo_result file is as below :
      st1                          st2
 lat1     long1              lat2     long2     period    velocity(km/s)
17.0241 78.1812    17.4309 78.6871    5.0         3.82092
7.0241  78.1812     17.7608 78.1708     5.0         3.335 
17.0241 78.1812     17.1903 78.6139    5.0         3.72839
The example of file need to be like : https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.researchgate.net%2Ffigure%2FRayleigh-wave-phase-velocity-maps-at-periods-of-10-70-s-for-the-study-area_fig3_324124764&psig=AOvVaw2W3xXYPK0N0VZHeqCkKtgF&ust=1633156308984000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCKCcg8DLqPMCFQAAAAAdAAAAABAX

**Comment by seisman** [comment]
@chinu739 The GitHub issue is used to report GMT bugs or request new features. For general questions, please post it on the GMT forum (https://forum.generic-mapping-tools.org/).
