### ISSUE TITLE
03s SRTM tiles rely on 15s earth relief tiles even for on-land regions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#5829]
**Description of the problem**

The issue was originally found in https://github.com/GenericMappingTools/pygmt/pull/1553.

The following script plots the earth relief map around Yosemite valley (`-R-119.825/-119.4/37.6/37.825`) using the 03s grid. The region is on land, so only 03s grid is needed, but the 15s tile is also downloaded.

**Full script that generated the error**

```
gmt begin map
	gmt grdcut @earth_relief_03s -R-119.825/-119.4/37.6/37.825 -Gearth.nc
	gmt grdimage earth.nc -BWSen -Baf

	gmt grdcut @srtm_relief_03s -R-119.825/-119.4/37.6/37.825 -Gsrtm.nc
	gmt grdimage srtm.nc -BESwn -Baf -Xw+1c
gmt end show
```

I deleted all cached earth relief data, and ran the above script. The output is:
```
grdblend [NOTICE]: Remote data courtesy of GMT data server china [http://china.generic-mapping-tools.org]

grdblend [NOTICE]: Earth Relief at 3x3 arc seconds tiles provided by SRTMGL3 (land only) [NASA/USGS].
grdblend [NOTICE]:   -> Download 1x1 degree grid tile (earth_relief_03s_g): N37W120
grdblend [NOTICE]: Earth Relief at 15x15 arc seconds provided by SRTM15+V2.1 [Tozer et al., 2019].
grdblend [NOTICE]:   -> Download 10x10 degree grid tile (earth_relief_15s_p): N30W120
```

**System information**

* GMT version (`gmt --version`): 6.2.0 and 6.3.0_0dc0214_2021.09.29

**Comment by PaulWessel** [comment]
Thanks, I will see what goes on in debug.  The area is definitively just on land, but it is possible the algorithm does some fancy rounding and ends up deciding it needs a tile of 15s and then it is not used.
