### ISSUE TITLE
@earth_relief related problem

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [GenericMappingTools/gmt#5830]
Dear All,

I really appreciate if you can guide me how to solve this problem.I don't know why I can't download DEM using GMT 6.2.0 today using 

`gmt grdcut @earth_relief_01s  -R-66.3/-65/-25.2/-24 -Gdem.grd`

the error message 

```
grdcut [ERROR]: Libcurl Error: HTTP response code said error
grdcut [WARNING]: You can turn remote file download off by setting GMT_DATA_UPDATE_INTERVAL to "off"
grdcut [ERROR]: File /home/mohammad/.gmt/cache/earth_relief_01s was not found
grdcut [ERROR]: Cannot find file /home/mohammad/.gmt/cache/earth_relief_01s
grdcut [ERROR]: File /home/mohammad/.gmt/cache/earth_relief_01s was not found
grdcut [ERROR]: Cannot find file /home/mohammad/.gmt/cache/earth_relief_01s
grdcut [ERROR]: File /home/mohammad/.gmt/cache/earth_relief_01s not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
```

**Comment by seisman** [comment]
@mohseniaref-InSAR There is something wrong with the GMT server. 

You can temporarily fix it by using the https server URL:
```
gmt set GMT_DATA_SERVER=https://oceania.generic-mapping-tools.org
```

**Comment by mohseniaref-InSAR** [comment]
It fixed for me. Thanks so much!

**Comment by seisman** [comment]
As mentioned in https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932614258, the GMT server has been fixed, so the workaround is no longer needed. Please re-open the issue if you still has the same problem.
