### ISSUE TITLE
Julia tests is crashing GMT

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5831]
![image](https://user-images.githubusercontent.com/537321/135669407-6ad87a18-fb73-4c0d-b923-44bb6821fd7f.png)

It's something recent (days). When I switched back to master and updated it dies on Windows too, but only says

```
        GRDIMAGE
        GRDVIEW
ERROR: Package GMT errored during testing (exit code: 3221226356)
```
The test in question uses an image in **-G**
```
I = mat2img(rand(UInt8,90,120,3), proj="+proj=longlat +datum=WGS84 +no_defs");	# 'proj' is ignored
gmtwrite("lixo.tif", I)
grdview(rand(90,120), G="lixo.tif", J=:X12, JZ=5, Q=:i, view="145/30")
```

**Comment by joa-quim** [comment]
This reproduces the test and crashes in line 12849 of ``gmt_support.c``
```
				if (set[YLO]) {	/* d2/dy2 */
					byte = irint (2.0 * img[nb*(js + ie)+b] - img[nb*(jsi1 + ie)+b]);
					img[nb*(jso1 + ie)+b]   = gmtsupport_clip_to_byte (byte);         //   <=== HERE
```


```
grdview lixo.grd -JX12/0 -Baf -Bza -n+a -p145/30 -Qi -JZ5 -R1/120/1/90 -Glixo.tif -P > lixo.ps
```
[lixos.zip](https://github.com/GenericMappingTools/gmt/files/7269564/lixos.zip)

**Comment by PaulWessel** [comment]
Unfortunately no crash for me on master or the grdcut-gdal branch.  However, I can build in Xcode with extra memory/malloc checks to catch such issues (I assume img is being accessed outside bounds).  Which branch do you suggest?

**Comment by joa-quim** [comment]
That is in master, and it crashes in Linux too (the CI)

**Comment by PaulWessel** [comment]
Reproducible in Xcode with turning on the malloc guards etc.  On in.

**Comment by PaulWessel** [comment]
Sure it is not your files that are a bit weird? The grid is 1/120/1/90 and gridline registered while the image is 1/121/0/90 and pixel registered?

We read the image header etc successfully but then because your -R requests a subset of the image strange things happen. Works fine without the -R.

**Comment by joa-quim** [comment]
This is a made up test with dumb files.
