### ISSUE TITLE
Always show download size

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#5832]
Size is shown if single file, e.g. `831K` below:

```
$ gmt grdimage @earth_relief_20m -JM15c -RNO > /dev/null
grdimage [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdimage [NOTICE]: Earth Relief at 20x20 arc minutes from Gaussian Cartesian filtering (37 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].
grdimage [NOTICE]:   -> Download grid file [831K]: earth_relief_20m_p.grd
```

This size is *not* shown if there are mutiple files involved, e.g.:

```
$ gmt grdimage @earth_relief_05m -JM15c -RNO > /dev/null
grdblend [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdblend [NOTICE]: Earth Relief at 5x5 arc minutes from Gaussian Cartesian filtering (9 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].
grdblend [NOTICE]:   -> Download 180x180 degree grid tile (earth_relief_05m_p): S90W180
grdblend [NOTICE]:   -> Download 180x180 degree grid tile (earth_relief_05m_p): S90E000
```

Is it posssible to always show the size of all downloads?

**Comment by PaulWessel** [comment]
No.  The reason we can show the other sizes is that they are encoded in the gmt_data_server.txt listing in ~/.gmt/server, but the 14297 1s and 3s tiles are not listed individually that way as it would be too much overhead to just read that file for this purpose.  It is the same with the larger tiles even though they are fewer. Furthermore, tiles are stored on the server in JP2 format and after download converted to a local compress netCDF short int file, so we would have to store the JP2 sizes for this to be truthful. In general the 01s JP2 tiles range from 3k to 7.4 Mb while the 3s range is 2k to 1.1 Mb.  For the larger tiles (e.g. your 05m case) different ranges apply, with most of those tiles ~5 Mb.

**Comment by anbj** [comment]
Great, Paul. I see why this is not possible. Thank you for a great answer.

Closing.
