### ISSUE TITLE
Not computing min/max of images with only one layer (indexed) broke Julia wrapper

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5836]
The problem is here. I need it to compute min/max when ``raster_count == 1``
```
	if (raster_count > 0) {
		hBand = GDALGetRasterBand(hDataset, 1);	/* Ensure hBand points to the first layer */
		if (z_min == DBL_MAX && GDALGetRasterDataType (hBand) != GDT_Byte) {
```

The changes in the colormap broke other parts too. Still trying to figure out why.

**Comment by PaulWessel** [comment]
We had this discussion recently about this and since the image does not contain data (it is indices into a color table) there is not reason to routinely scan huge files and report bogus min/zmax.  If you need to now min/max indices (?) you can probably scan the file separately.  Am I missing something?

**Comment by joa-quim** [comment]
Yes, but back then I didn't know it would break some julia code. The issue there happens when I plot from a file name, that I don't know if it's of a grid or an image, and call ``grdinfo -C`` to get the min/max. The ``DBL_MAX/-DBL_MAX`` answer causes the problem. I can test for this values and not try to generate a default ``cpt`` since being an image it should carry its own information about colors, but it broke it.

And the argument of not scanning a large image is the same as for large grids, that are currently scanned. The true issue is why we do not trust the file info about min/max. We do trust when we read netcdf files (and native float grid formats) but we don't when reading grids with GDAL. I know there was an issue triggering the change but don't think we have a consistent situation and would be better recover what the issue was and try to address it in a different way.

**Comment by PaulWessel** [comment]
For indexed images we know the range of indices is 0 through n-index-1, or 0-255.  Perhaps just return 0/255 for this case?

**Comment by joa-quim** [comment]
Well, yes for RGB's but at least for indexed we should use ``true`` in
```
 GDALComputeRasterMinMax(hBand, false, adfMinMax);
```
If you are still skeptical, run ``gdalinfo`` in your big image.

**Comment by PaulWessel** [comment]
OK, stuck in zoom with family for another hour.

**Comment by PaulWessel** [comment]
I can do gdalinfo on earth_day_30s_p.tif and it is instant but only dumps the color table.
If I do it on Meghan's sentinel multi band then I get

```
Band 1 Block=17031x1 Type=Float64, ColorInterp=Gray
  NoData Value=0
Band 2 Block=17031x1 Type=Float64, ColorInterp=Undefined
  NoData Value=0
...
Band 16 Block=17031x1 Type=Float64, ColorInterp=Undefined
  NoData Value=0
```


so it is not reporting anything there.

I will try true for indexed and see if it gets slow or not.

**Comment by joa-quim** [comment]
Probably because min/max was not stored as metadata. My toy image shows:
```
Corner Coordinates:
Upper Left  (   1.0000000,  27.0000000)
Lower Left  (   1.0000000,   0.0000000)
Upper Right (  28.0000000,  27.0000000)
Lower Right (  28.0000000,   0.0000000)
Center      (  14.5000000,  13.5000000)
Band 1 Block=27x27 Type=Byte, ColorInterp=Palette
  Min=1.000 Max=8.000
  Minimum=1.000, Maximum=8.000, Mean=4.500, StdDev=2.291
  NoData Value=0
  Metadata:
    STATISTICS_MAXIMUM=8
    STATISTICS_MEAN=4.5
    STATISTICS_MINIMUM=1
    STATISTICS_STDDEV=2.2912878474779
    STATISTICS_VALID_PERCENT=88.89
```
