### ISSUE TITLE
Crash from makecpt?

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5859]
Got a crash in the middle of Julia tests saying that "variable ns used without being initialized". Can't be sure where it's coming from but seem to be ``makecpt``. And indeed in line 705 ``ns`` is not initialized if ``got_key_file`` is false. 
```
if (k < ns && keys[k]) {
```

**Comment by PaulWessel** [comment]
On Maui no lapto. Please omit to Pout->n_colors or whatever it is

Paul Wessel, Professor
Dept. of Earth Sciences
SOEST, U of Hawaii at Manoa

**Comment by PaulWessel** [comment]
Ok, on earlier flight so maybe tonight

Paul Wessel, Professor
Dept. of Earth Sciences
SOEST, U of Hawaii at Manoa
