### ISSUE TITLE
Let inset begin accept -R and -J to automatically set width or height

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#5875]
**Description of the desired feature**

Currently, the user must use mapproject to determine the appropriate size for a inset to match a given region and projection. It would be useful to allow `inset begin` to accept the region and projection of the inset, similar to subplot begin, to avoid this extra step. Here is an example of the anticipated usage:

```
gmt begin test png
    gmt grdimage @earth_relief -R-51/-48/-24/-23 -JM15c -B -Cworld
    gmt inset begin -DjBL+o0.1c -F+p1p,black -R-80/-28/-43/10 -JM2c
        gmt coast -Wthin -Swhite -Ggray 
    gmt inset end
gmt end show
```

![expected output](https://user-images.githubusercontent.com/26473567/137820144-aa6a3b06-d1b4-41a7-a052-0451c766e213.png)

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
OK, to close this issue, @meghanrjones ?
