### ISSUE TITLE
Symbol Lookup Error

### ISSUE THREAD

**Issue by daxsoule** [GenericMappingTools/gmt#588]
I am trying to get started running GMT in on a PANGEO cluster. I have Conda installed gmt 

$gmt returns >> `gmt: symbol lookup error: /opt/conda/bin/../lib/libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev`

Testing further using the tutorial scripts that are found in gmt/doc/scripts from the git repo:  

`source GMT_tut_17.sh`

returns:
`gmt: symbol lookup error: /opt/conda/bin/../lib/libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev`

**System information**
python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)

* Operating system:

[GCC 7.3.0] on linux

* Version of GMT:
Most recent... I just cloned it today.

**Comment by PaulWessel** [comment]
Not sure, but sounds like a mix of two GDAL versions and it is getting the wrong one during lookup.  @leouieda, any other ideas?

**Comment by daxsoule** [comment]
@leouieda let me know if you have any ideas or would like to chat briefly.

**Comment by leouieda** [comment]
@daxsoule thanks for reporting. Which version of GMT did you install from conda (what command did you run to install)? The 6.0.0 alpha builds are no longer being supported (we'll wait until there is an official release to rebuild those). 

Could you please paste the output of `conda list` here?

**Comment by daxsoule** [comment]
Here you go:

jovyan@jupyter-daxsoule:~$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
alembic                   0.9.9                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
arpack                    3.6.3           blas_openblash6d6ea35_1002  [blas_openblas]  conda-forge
arrow-cpp                 0.11.1           py36h3bd774a_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
atk                       2.25.90              h05f3006_1    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
av                        6.1.0            py36h7273d18_0    conda-forge
azure-common              1.1.16                    <pip>
azure-storage-blob        1.4.0                     <pip>
azure-storage-common      1.4.0                     <pip>
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.3                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.15.1               hfc679d8_0    conda-forge
bokeh                     1.0.2                 py36_1000    conda-forge
boost-cpp                 1.68.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cachetools                2.1.0                      py_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
cartopy                   0.17.0          py36h0aa2c8f_1004    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
cftime                    1.0.3.4          py36h7eb728f_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
cmake                     3.14.0               hf94ab9c_0    conda-forge
colorcet                  1.0.0                      py_0    conda-forge
conda                     4.5.11                py36_1000    conda-forge
conda-env                 2.6.0                         0    conda-forge
configurable-http-proxy   3.1.0                   node8_1    conda-forge
cryptography              2.6.1            py36h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.1           py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask                      1.0.0                      py_0    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
dask-kubernetes           0.6.0                      py_0    conda-forge
datashader                0.6.8                      py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
dcw-gmt                   1.1.4                      1001    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
distributed               1.25.0                py36_1000    conda-forge
driveanon                 0.1.0                     <pip>
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fastparquet               0.2.0            py36h7eb728f_0    conda-forge
ffmpeg                    4.0.2                ha0c5888_2    conda-forge
fftw                      3.3.8                h470a237_1    conda-forge
fiona                     1.8.4           py36heb36068_1001    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
future                    0.17.0                py36_1000    conda-forge
gdal                      2.3.3            py36hf242f0b_1    conda-forge
gdk-pixbuf                2.36.12              h4ab6910_1    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
geoviews                  1.6.0a3                    py_0    pyviz/label/dev
geoviews-core             1.6.0a3                    py_0    pyviz/label/dev
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
ghostscript               9.22              hf484d3e_1001    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gmt                       6.0.0a18        blas_openblash4f9c4ba_0  [blas_openblas]  conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
gobject-introspection     1.56.1           py36haaf12d0_1    conda-forge
google-api-core           0.1.4                      py_0    conda-forge
google-auth               1.6.1                      py_0    conda-forge
google-cloud-core         0.28.1                     py_0    conda-forge
google-cloud-storage      1.12.0                     py_0    conda-forge
google-resumable-media    0.3.1                      py_0    conda-forge
googleapis-common-protos  1.5.5                      py_0    conda-forge
graphite2                 1.3.12               hfc679d8_1    conda-forge
graphviz                  2.38.0               h08bfae6_9    conda-forge
gshhg-gmt                 2.3.7                      1002    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
gtk2                      2.24.31              hde048ef_0    conda-forge
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
holoviews                 1.11.0a11          pyh39e3cac_0    pyviz/label/dev
html5lib                  1.0.1                      py_0    conda-forge
hvplot                    0.3.0a6                    py_0    pyviz/label/dev
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_0    conda-forge
imagehash                 4.0                        py_0    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
intake                    0.3.0                      py_0    intake
intake-xarray             0.2.4                      py_0    intake
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
julia                     1.0.3           blas_openblash12d65f3_2  [blas_openblas]  conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterhub                0.8.1                    py36_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgdal                   2.3.3                hdb8f723_1    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libgit2                   0.28.1               heeda6b9_1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libpq                     11.2                 h4770945_0    conda-forge
libprotobuf               3.6.1                hd28b015_0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libspatialindex           1.8.5                hfc679d8_3    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.10               he6b73bb_0    conda-forge
libtool                   2.4.6                h470a237_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libuv                     1.26.0               h14c3975_0    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
llvmlite                  0.26.0           py36hd28b015_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.5            py36hc9114bc_0    conda-forge
lz4                       1.1.0            py36h3b97293_1    conda-forge
lz4-c                     1.8.1.2                       0    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
mako                      1.0.7                    py36_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                3.0.3                    py36_0    conda-forge
matplotlib-base           3.0.3            py36h167e16e_0    conda-forge
metis                     5.1.0                hfc679d8_3    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
mpfr                      4.0.1                h16a7912_0    conda-forge
msgpack-numpy             0.4.4.2                    py_0    conda-forge
msgpack-python            0.6.0            py36h2d50403_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
nbserverproxy             0.8.6                   py_1000    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.0            py36had58050_0    conda-forge
nettle                    3.3                           0    conda-forge
networkx                  2.2                        py_1    conda-forge
nodejs                    8.10.0                        0    conda-forge
nomkl                     3.0                           0    defaults
notebook                  5.5.0                    py36_0    conda-forge
numba                     0.41.0           py36hf8a1672_0    conda-forge
numcodecs                 0.6.2            py36hfc679d8_0    conda-forge
numexpr                   2.6.8            py36hf8a1672_0    conda-forge
numpngw                   0.0.7                     <pip>
numpy                     1.16.2          py36_blas_openblash1522bff_0  [blas_openblas]  conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
obspy                     1.1.0            py36h7eb728f_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openh264                  1.8.0                hd28b015_0    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openlibm                  0.5.4                h470a237_0    conda-forge
openspecfun               0.5.3                h26a2512_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
owslib                    0.17.0                     py_0    conda-forge
packaging                 18.0                       py_0    conda-forge
pamela                    0.3.0                    py36_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
panel                     0.3.1                      py_0    pyviz/label/dev
pango                     1.40.14              he752989_2    conda-forge
param                     1.8.1                      py_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.2.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pcre2                     10.23                         2    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.3.0            py36hc736899_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pip                       18.1                      <pip>
pixman                    0.34.0               h470a237_3    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
poppler                   0.67.0               hdf8a1b3_2    conda-forge
poppler-data              0.4.9                         0    conda-forge
postgresql                11.2                 h61314c7_0    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
protobuf                  3.6.1            py36hfc679d8_1    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
psycopg2                  2.7.7            py36h72c5cf5_2    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.7.0                      py_0    conda-forge
pyarrow                   0.11.1           py36hfc679d8_0    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycamhd                   0.7.0                     <pip>
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyct                      0.4.5                      py_0    conda-forge
pyct-core                 0.4.5                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pykdtree                  1.3.1            py36h7eb728f_2    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.6           py36hc0953d3_1000    conda-forge
pyqt                      4.11.4                   py36_3    conda-forge
pysal                     1.14.4.post2          py36_1001    conda-forge
pyshp                     2.0.0                      py_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pytables                  3.4.4           py36h5d69a80_1004    conda-forge
pytest                    3.9.1                 py36_1000    conda-forge
python                    3.6.7                h0371630_0    defaults
python-blosc              1.6.2            py36hfc679d8_1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-editor             1.0.3                    py36_0    conda-forge
python-graphviz           0.8.4                 py36_1002    conda-forge
python-kubernetes         4.0.0                    py36_1    conda-forge
python-oauth2             1.0.1                    py36_0    conda-forge
python-snappy             0.5.3            py36h00d4201_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pyviz_comms               0.6.0                      py_0    conda-forge
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        4.8.7                         2    defaults
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.19.1                   py36_0    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
rsa                       3.4.2                      py_1    conda-forge
rtree                     0.8.3                 py36_1000    conda-forge
ruamel_yaml               0.15.40          py36h470a237_0    conda-forge
scikit-image              0.14.1           py36hfc679d8_1    conda-forge
scipy                     1.2.1           py36_blas_openblash1522bff_0  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.2.0                   py36_0    conda-forge
shapely                   1.6.4           py36h2afed24_1003    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snappy                    1.1.7                hfc679d8_2    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlalchemy                1.2.8                    py36_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  conda-forge
tbb                       2019.3               h2d50403_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
thrift                    0.11.0           py36hfc679d8_1    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.23                     py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
websocket-client          0.40.0                   py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
x264                      1!152.20180717       h470a237_1    conda-forge
xarray                    0.11.0                py36_1000    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxpm               3.5.12               h470a237_2    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                         0    conda-forge
zarr                      2.2.0                      py_1    conda-forge
zeromq                    4.2.5                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

**Comment by seisman** [comment]
Closed as the issue should be fixed now. Please reopen the issue if you still have the same issue.
