### ISSUE TITLE
Coordinates of non-geog grids are not readable by GDAL

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5881]
Ex1: (notice how x|y_min/max are wrong
```
grdmath -I0.1 -R0/10/0/10 0 = lixo.grd
grdinfo lixo.grd=gd
Warning 1: dimension #1 (x) is not a Longitude/X dimension.
Warning 1: dimension #0 (y) is not a Latitude/Y dimension.
lixo.grd: Title: Grid imported via GDAL
lixo.grd: Command:
lixo.grd: Remark:
lixo.grd: Gridline node registration used [Cartesian grid]
lixo.grd: Grid file format: gd = Import/export through GDAL
lixo.grd: x_min: 0.5 x_max: 100.5 x_inc: 1 name: x n_columns: 101
lixo.grd: y_min: 0.5 y_max: 100.5 y_inc: 1 name: y n_rows: 101
```

Ex2:
```
julia> G = mat2grid(rand(Float32, 16, 16), proj4=GMT.prj4WGS84);
julia> gmtwrite("lixo2.grd", G)
julia> gdaltranslate(G, save="lixo3.grd")
```
```
grdinfo lixo2.grd=gd
Warning 1: dimension #1 (x) is not a Longitude/X dimension.
Warning 1: dimension #0 (y) is not a Latitude/Y dimension.
lixo2.grd: Title: Grid imported via GDAL
lixo2.grd: Command:
lixo2.grd: Remark:
lixo2.grd: Gridline node registration used [Geographic grid]
lixo2.grd: Grid file format: gd = Import/export through GDAL
lixo2.grd: x_min: 0.5 x_max: 15.5 x_inc: 1 name: x n_columns: 16
lixo2.grd: y_min: 0.5 y_max: 15.5 y_inc: 1 name: y n_rows: 16
```
```
grdinfo lixo3.grd=gd
lixo3.grd: Title: Grid imported via GDAL
lixo3.grd: Command:
lixo3.grd: Remark:
lixo3.grd: Gridline node registration used [Geographic grid]
lixo3.grd: Grid file format: gd = Import/export through GDAL
lixo3.grd: x_min: 1 x_max: 16 x_inc: 1 name: x n_columns: 16
lixo3.grd: y_min: 1 y_max: 16 y_inc: 1 name: y n_rows: 16
```

The problem is when GDAL complains
```
Warning 1: dimension #1 (x) is not a Longitude/X dimension.
Warning 1: dimension #0 (y) is not a Latitude/Y dimension.
```
is is triggered by missing attributes in the *x,y* coordinates, which when the file is written by GDAL have (from ``ncdump -h``
```
                x:standard_name = "projection_x_coordinate" ;
                x:long_name = "x coordinate of projection" ;
                x:units = "m" ;
```
but only
```
        double x(x) ;
                x:long_name = "x" ;
                x:actual_range = 1., 16. ;
```
when written by GMT.

In fact this is even more confuse because the dumb case should have worked even in ``lixo2.grd`` case be cause file is in geogs, but ``x_min/max = 0.5/15.5`` instead of ``1/16`` (I know I should have used ``-fg`` to tell it it's geographic but I want enphasize the non-geog cases). 

[lixo2.grd.zip](https://github.com/GenericMappingTools/gmt/files/7382469/lixo2.grd.zip)
[lixo3.grd.zip](https://github.com/GenericMappingTools/gmt/files/7382470/lixo3.grd.zip)

**Comment by PaulWessel** [comment]
Not sure what to do here. Lots of GMT grids are not containing geographic data, projected or not, so we cannot state projection_x_coordinate when in fact x is time or some non-dimensional thing.  I think the **G** in **GDAL** basically restricts GDAL to work on geographic grids and images, no? GMT is not limited in that way, hence this is not a GMT issue.  However, if there are places where we know the grid x,y are geographic projected distances (e.g., output from grdproject, perhaps) then we could consider using projection_x_coordinate instead of x, but not in general.

**Comment by joa-quim** [comment]
>  I think the G in GDAL basically restricts GDAL to work on geographic grids and images, no?

Geoographic no, Georeferenced maybe. A point is that we work mostly with georeferenced data but do not enforce that info in the grids so we fall in this type of situations.

**Comment by anbj** [comment]
The *G* in `gdal` is for *Geospatial* - which can include both geodetic and projected stuff, no?

**Comment by joa-quim** [comment]
A related issue
https://github.com/OSGeo/gdal/issues/4581

**Comment by PaulWessel** [comment]
Yes, it can have projected distances (say, in meter and projection_x_coordinate works for that) but not if x is time, weight, some random thing, etc.
