### ISSUE TITLE
GMT can't fetch referencing system when the "spatial_ref" is an attribute of other than the global "grid_mapping"

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5928]
```
julia> G = gmtread("HLS.S30.T10TEK.2021089T184941.v1.5_EVI.grd")
julia> G.proj4
""
julia> G.wkt
""
```

```
gdalinfo HLS.S30.T10TEK.2021089T184941.v1.5_EVI.grd
...
transverse_mercator#spatial_ref=PROJCS["unknown",GEOGCS[...
...
```

As an example of one that works
```
gdalinfo evi.grd
...
Metadata:
  grid_mapping#spatial_ref=PROJCS["unknown",
```

[HLS.S30.T10TEK.2021089T184941.v1.5_EVI.zip](https://github.com/GenericMappingTools/gmt/files/7437758/HLS.S30.T10TEK.2021089T184941.v1.5_EVI.zip)

**Comment by PaulWessel** [comment]
Seems this file has a single character variable called transverse_mercator, and that variable then has a bunch of attributes, including this one:

`transverse_mercator:spatial_ref = "PROJCS[\"unknown\",GEOGCS[\"unknown\",DATUM[\"Unknown based on WGS84 ellipsoid\",SPHEROID[\"WGS 84\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",-123],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]" ;`

So what are we to do? Loop over all variables in the netCDF file and see if each one might have a spatial_ref attribute?  IS this really CF conformant?  We certainly cannot guess the name of the variable (here transverse_mercator) but I guess it would be possible to search for all attributes per variable, but is this really a sane way to flag a grid as projected?

**Comment by joa-quim** [comment]
I asked about it in the GDAL list, this was the response

 > The CreateCopy() solution created me a file with the coordinates system info stored in the “transverse_mercator” attribute (why?)

>> why not ? :-) This is like this before I was born.
If you look at "Example 5.6. Rotated pole grid" of https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html, you can see that the name of the variable that stores the CRS definition can be anything. The link to it is done through the "grid_mapping" attribute of the variable of interest.
  

 
> How can I control the name of the attribute where the CRS is tored so I can find it from other programs?

>> You can't. It is set at https://github.com/OSGeo/gdal/blob/40d18b06d78d5b97f9c6387ef6a08a9c0142c884/gdal/frmts/netcdf/netcdfdataset.cpp#L5607 with the same value as the #grid_mapping_name attribute of the CRS definition vriable.

**Comment by PaulWessel** [comment]
I suppose smart people can make dumb decisions.  I have done my share.
