### ISSUE TITLE
-Mps for gmt movie does not crop the output well

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5935]
**Description of the problem**

The -M option for postscript output crops the frame in a smaller region than set by -C, for example when `anim02.sh` is run without any additional arguments.

**Full script that generated the error**

```
bash anim02.sh
```
**Actual outcome**

<img width="614" alt="image" src="https://user-images.githubusercontent.com/14077947/139739379-af9b1594-84cd-4973-9b07-418a615e3cbc.png">

**Expected outcome**

![anim02](https://user-images.githubusercontent.com/14077947/139739403-cbad0abc-56eb-4299-8cd9-5617787d0846.png)

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): dev branch

**Comment by PaulWessel** [comment]
The anim02.ps file starts like this:

```
%!PS-Adobe-3.0
%%BoundingBox: 0 0 681 383
%%HiResBoundingBox: 0 0 680.3150 382.6770
```

which is 24c wide and 13.5 hight.  Looks right to me.  `gmt psconvert -Tf anim02.ps` without -A -P gives the right PDF.  How did you get the image above? Preview?

**Comment by meghanrjones** [comment]
> The anim02.ps file starts like this:
> 
> ```
> %!PS-Adobe-3.0
> %%BoundingBox: 0 0 681 383
> %%HiResBoundingBox: 0 0 680.3150 382.6770
> ```
> 
> which is 24c wide and 13.5 hight. Looks right to me. `gmt psconvert -Tf anim02.ps` without -A -P gives the right PDF. How did you get the image above? Preview?

Ugh, yes sorry I was fooled by preview. Closing this issue.
