### ISSUE TITLE
x2sys_cross with -A crashes

### ISSUE THREAD

**Issue by DerLude** [GenericMappingTools/gmt#5937]
**Description of the problem**
Calculating crossover differences with `x2sys_init` and `x2sys_cross` (without -A) works fine. However, when I generate a combination table (using `x2sys_binlist`,`x2sys_put` & `x2sys_get`) and hand this table over to `x2sys_cross` via -A, it breaks and I get the error given below.

**Full script that generated the error**

Script, format definition tag and some files to reproduce the error:
[x2sys_minimal.zip](https://github.com/GenericMappingTools/gmt/files/7460187/x2sys_minimal.zip)

**Full error message**

```
double free or corruption (out)
./x2sys_minimal.sh:  line 30: 12954 Aborted                 (core dumped) x2sys_cross =profiles.lst -Aprofiles.cmb -T$tag > $workdir/xo2.x2s
```

**Actual outcome**

An empty file (xo2.x2s in the script above).

**Expected outcome**

A file containing the crossover results (as xo1.x2s in the script above) .

**System information**

* Operating system: Ubuntu 18.04.6 LTS
* GMT version (`gmt --version`): 6.0.0 and 6.2.0, both build from source

**Comment by PaulWessel** [comment]
Thanks, fix coming shortly.
