### ISSUE TITLE
Unnecessary error for grdcut @srtm_relief

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#5951]
**Description of the problem**

An error about incompatible -R and -I options is given for grdcut on tiled datasets. The output grid is fine, so the error is unnecessary. Introduced by https://github.com/GenericMappingTools/gmt/pull/5926.

**Full script that generated the error**

```
gmt grdcut @srtm_relief_03s_g -R135/136/35/36 -Gtest.nc
```

**Full error message**

```
grdcut [ERROR]: Grid x increment <= 0.0
grdcut [ERROR]: Grid y increment <= 0.0
grdcut (gmt_api.c:2030(gmtapi_init_grdheader)): Please select compatible -R and -I values
```

**Actual outcome**

test.nc produced with an error statement.

**Expected outcome**

test.nc produced with no error statement.

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.3.0_7e18cb1_2021.10.28

**Comment by PaulWessel** [comment]
Working on a fix.
