### ISSUE TITLE
grdtrack: Location of interpolated column depends on presence of text columns

### ISSUE THREAD

**Issue by DerLude** [GenericMappingTools/gmt#5960]
**Description of the problem**
The docs of grdtrack say it "writes out the table with the interpolated values added as (one or more) new columns". In older GMT-versions (at least in GMT4), the new columns were always added at the end (as last columns). Now, GMT seems to detect "text" columns and places the interpolated value in front of it. This means, in order to find out where grdtrack put the values, you first have to know if there are text columns in your file( and where). This seems not very convenient for me.
Is this intended or is it a bug?

File without text column works as expected:
[test1.txt](https://github.com/GenericMappingTools/gmt/files/7495819/test1.txt) (columns: lon lat val1 val2 val3)
`grdtrack test1.txt -Gearth_relief_05m` -> interpolated column is placed at the end (columns: lon lat val1 val2 val3 INT)

File with text column:
[test2.txt](https://github.com/GenericMappingTools/gmt/files/7495836/test2.txt) (columns: lon lat val1 text val3)
`grdtrack test2.txt -Gearth_relief_05m` -> interpolated column is placed before text (columns: lon lat val1 INT text val3)

**Full error message**
None

**Actual outcome**
columns: lon lat val1 INT text val3

**Expected outcome**
columns: lon lat val1 text val3 INT

**System information**

* Operating system: Ubuntu 18.04.6 LTS
* GMT version (`gmt --version`) 6.2.0 (build from source)
:

**Comment by PaulWessel** [comment]
Yes this is the expected result.  In order for GMT to consistently handle data records with or without text we moved to a system where a data record can be any number of numerical values followed by a trailing text.  Both parts are optional.  Modules that add numerical data to a record will append to the numerical part.  Hence you always know that the numbers will be in the next extra numerical column, whether you have text or not. IN your case, you know you have 3 input numerical columns so the result is appended as column 4, regardless of any trialing text.
