### ISSUE TITLE
Add -o option for rose and histogram to retrieve information.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#5979]
If a run this code, I get this info

```
gmt pshistogram  @v3206_06.txt -F -T250 -I
-5932   -24     0.0920104278485 20.3036344119
```

I think it would be good to have the option to only output one value (like the maximum value of Y) so I can create a variable. Something like this: 

`max=$(gmt pshistogram  @v3206_06.txt -F -T250 -I -o3)`

The same case happens for gmt rose -I (which gives all these values  n, mean az, mean r, mean resultant length, max bin sum, scaled mean, and linear length sum).

I manage to get the variable saving the info into a file and then using `gmt info -C -o`. So I don't really need this feature but I think that maybe it would be good to have it.

**Comment by PaulWessel** [comment]
We should be able to easily do that.  Let me see if I can squeeze it in before 6.3
