### ISSUE TITLE
grdvector pen issues

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#5988]
```
gmt grdmath -R-2/2/-2/2 -I0.1 X Y R2 NEG EXP X MUL = G.grd
gmt grdmath G.grd DDX = dzdx.grd
gmt grdmath G.grd DDY = dzdy.grd
```

``grdvector`` imposes one of **-C, -G, -W** and since **-G** and arrow head fill do the same thing one can **not** set **-W** if we do
```
gmt grdvector dzdx.grd dzdy.grd -JX12c/0 -Baf -BWSen -I0.3 -Q0.4+e+gred+n0.4+pgreen+h0 -Gred -png lixo1
```
but then the stem pen is set by the arrow head pen (``+pgreen``). 

![lixo1](https://user-images.githubusercontent.com/537321/141471972-175b7172-a990-4f33-9c5a-8e96453e0615.png)

But the stem pen transparency applies also to the head pen. In the next plot we don't see the head outline, even if we explicitly set it to opaque.
```
gmt grdvector dzdx.grd dzdy.grd -JX12c/0 -Baf -BWSen -I0.3 -W,black@100 -Q0.4+e+gred+n0.4+p1,green@0+h0 -Gred -png lixo2
```
![lixo2](https://user-images.githubusercontent.com/537321/141472025-fe2a867b-edde-40f5-bc90-d83092ce22ee.png)

**Comment by PaulWessel** [comment]
OK, so you want the stem pen and the head outline pen (if set separately) to have their own transparencies.  I will see if that is possible.

**Comment by joa-quim** [comment]
Not really wanting it but fell onto this surprising behavior.
