### ISSUE TITLE
can't set vector head fill or pen without `-W` or `-G` options

### ISSUE THREAD

**Issue by adigitoleo** [GenericMappingTools/gmt#5998]
**Description of the problem**

From [the vector attributes documentation](https://docs.generic-mapping-tools.org/latest/grdvector.html#vector-attributes):

> +g[fill] sets the vector head fill [Default fill is used, which may be no fill]. Turn off vector head fill by not appending a fill. Some modules have a separate -Gfill option and if used will select the fill as well.

> +p[pen] sets the vector pen attributes. If no pen is appended then the head outline is not drawn. [Default pen is half the width of stem pen, and head outline is drawn]. Above, we used +p2p,orange. The vector stem attributes are controlled by -W.

However, it seems that the `-G` (`-W`) option is mandatory, even if `+g` (`+p`) was given. Reading the above, it seems to me that `-G` (`-W`) should be optional in this case.

**Full script that generated the error**

```
#!/bin/sh

gmt begin arrow_head_pen
    gmt grdmath -R-2/2/-2/2 -I0.1 X Y R2 NEG EXP X MUL = z.nc
    gmt grdmath z.nc DDX = dzdx.nc
    gmt grdmath z.nc DDY = dzdy.nc
    gmt grdvector dzdx.nc dzdy.nc -JX12c/0 -Baf -BWSen -I0.3 -Q0.4+e+n0.4+ggreen+p1,red+h0
gmt end show
rm z.nc dzdx.nc dzdy.nc
```

**Error message**

```
grdvector [ERROR]: Must specify at least one of -G, -W, -C
```

**System information**

* Operating system: Linux x86_64 5.14.16-arch1-1 with GCC 11.1.0
* GMT version (`gmt --version`): 6.2.0

**Comment by PaulWessel** [comment]
Thanks for the report and example.  I have addressed the issues in PR #5999.

**Comment by Esteban82** [comment]
Is this the desire output of the Full script that generated the error?? I did it with branch of #5999.


![arrow_head_pen](https://user-images.githubusercontent.com/17908951/141661483-95c63f94-dfb2-4518-9375-1443dbb0a7e1.png)

**Comment by PaulWessel** [comment]
Yes: Default black pen (since no **-W** was set to override the default), red head outline due to **+p**red, and green fill due to **+g**green.

**Comment by joa-quim** [comment]
@adigitoleo This is mostly what GMT.jl does in https://github.com/GenericMappingTools/GMT.jl/pull/754 (except that the default -W is not **always** enforced)

**Comment by adigitoleo** [comment]
Thanks for the fix.
