### ISSUE TITLE
Change GMT line join and line end defaults to round

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#601]
**Description of the desired feature**

I propose to change the GMT defaults for PostScript line end and PostScript line join both to round.

New defaults: 
* `PS_LINE_CAP round`
* `PS_LINE_JOIN round`

My reasoning:
* This avoids the problems with the rendering of fat lines (see #431) by switching to "more advanced algorithms for drawing the join of segments and line endings" as pointed out by @uleysky.
* For most use cases the rounded line ends and joins make for a more visually pleasing plot. Especially when joining line segments at very acute angles. 

This request picks up on @PaulWessel's comment on the GMT default line join and line end settings in #431.

(I screwed up the title in the first incarnation of this feature request. Therefore this new one.)

**Comment by PaulWessel** [comment]
Thanks @KristofKoch, we can do some checking.  There are a few places in GMT where we set specific values for these parameters, such as when drawing map borders.  Your odd-shaped map frame case notwithstanding, for most of the time those boundaries need a square cap to match, but I could be more clever about handling cases at corners where one of the boundaries are not drawn.

**Comment by PaulWessel** [comment]
The specific problem with the rendering of very fat lines is peculiar and not likely to be something most users will run into.  We have a whole section in the cookbook on how to obtain a wide range of pen textures, including the special effects we can get via those two GMT defaults; see https://www.generic-mapping-tools.org/gmt/latest/GMT_Docs.html#specifying-pen-attributes.  If we changed the default then suddenly all dashed and dotted lines will look very different.  It is a relative big change I think.

**Comment by KristofKoch** [comment]
Hi @PaulWessel, point taken. I agree that this might be a remote use case. May I suggest to add a note in the cookbook about the problem and the cure for very fat lines?

**Comment by PaulWessel** [comment]
Hi @KristofKoch, does what I added at the end of https://www.generic-mapping-tools.org/gmt/latest/GMT_Docs.html#specifying-pen-attributes cover your concerns?  If so then we should close this issue.

**Comment by KristofKoch** [comment]
Hi @PaulWessel, I think the paragraph you added addresses the issue nicely. Thank you.
