### ISSUE TITLE
Add maintenance instructions for sphinx extensions/themes

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#6010]
**Description of the desired feature**

A few sphinx extensions are included in the gmt repository in `doc/rst/_extensions` and the sphinx_rtd_theme is included in `doc/rst/themes`. We should add instructions for bumping the extensions in `doc/rst/source/devdocs/maintenance.rst` and ideally a workflow to open an issue when new versions are released.

Relates to https://github.com/GenericMappingTools/gmt/issues/5282, https://github.com/GenericMappingTools/gmt/issues/5211.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
I agree. For old people it is also hard to remember why when something breaks once a year...
