### ISSUE TITLE
Bundle step fails on the macOS docs workflow

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6025]
**Description of the problem**

The macOS docs workflow is consistently failing on the Package GMT step (e.g. https://github.com/GenericMappingTools/gmt/runs/4244772423?check_suite_focus=true) with the error:
```
  /Applications/Xcode_13.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic:
  can't open file: @rpath/libgeos.3.10.1.dylib (No such file or directory)
```

So far, I have tried adding geos to [install-dependencies-macos.sh](https://github.com/GenericMappingTools/gmt/blob/master/ci/install-dependencies-macos.sh) and re-adding the `brew update` step before `brew install`, with no success.

@seisman, do you have any recommendations for fixing the workflow? Otherwise, I can switch from MacPorts to homebrew after the 6.3 release to test the setup locally.

**Comment by seisman** [comment]
Sorry, I have no idea why it fails.
