### ISSUE TITLE
pscoast -C[fill]+r overlaps lakes

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#6038]
Test code:
```bash
#!/bin/bash
PROJ="-JQ50/42/10c -R46.0/54.0/36.0/48.0"
echo "50 42" | gmt psxy $PROJ -Sc1c -W1p,black -Gred -P -K >test.ps
gmt pscoast -Df $PROJ -Ggray -Cgray+r -P -O >>test.ps
```
Result:
![test](https://user-images.githubusercontent.com/5275343/142561814-ff870337-a177-4583-b7a9-e8ebe480e959.png)
Without -Cgray+r:
![test1](https://user-images.githubusercontent.com/5275343/142562612-c35ab541-0f15-438f-bc89-3505751c6a28.png)
But painting the rivers should not affect the transparency of the lakes.

GMT b9fb8e4

**Comment by Esteban82** [comment]
@uleysky try setting the fill of lakes to transparent (`-C-+l`). I got this figure 

I think we can remove the bug label. 

Maybe it can set the default fill should be transparent for lakes when -Ccolor+r is used (and viceversa). @PaulWessel what do you think?

![costa](https://user-images.githubusercontent.com/17908951/147309435-767ab692-298b-4194-82a7-1f2aa2d0fe3d.png)


```

#!/bin/bash
PROJ="-JQ50/42/10c -R46.0/54.0/36.0/48.0"
echo "50 42" | gmt psxy $PROJ -Sc1c -W1p,black -Gred -P -K >test.ps
gmt pscoast -Df $PROJ -Ggray -Cblue+r -P -O -C-+l >>test.ps
```

**Comment by PaulWessel** [comment]
Thanks @Esteban82.  Yes I agree that when the user only wishes to paint the rivers then the lakes should not inherit that setting.  I will make a PR.
