### ISSUE TITLE
grdredpol on a synthetic block

### ISSUE THREAD

**Issue by johnsonbwalys** [GenericMappingTools/gmt#604]
**grdredpol not performing a reduction-to-pole on synthetic data**

**Hi Joaquim
I am working with modelled data of a block anomaly with inclination of -60 and declination of 0. The coordinates of the block are Cartesian. I have used grdredpol to perform a classical reduction-to-pole using the command: 
grdredpol block.grd -GRTP.nc -C0/-60 -W10000 -V
I used  a window size W10000 to speed up the testing of the code, but the result is the same with a smaller window. The output, though, is still the original block with inclination of -60. 

Any help of how I can go about this. I have checked forums, the GMT Manpages, but I can't correct the issue. 

Kind regards
Johnson
** Yes/No

**Comment by joa-quim** [comment]
@johnsonbwalys I'm afraid the ``grdrepol`` works only for geographical coordinates. Data in Cartesian coordinates normally does not span over very large areas and in those cases the classic RTP can be used. Note also that, when using -C, then -W would make no sense (there will be only one *window*, which is the entire domain), though I'm not sure the code knows that.

**Comment by johnsonbwalys** [comment]
** Thank you for your timely and helpful response**
