### ISSUE TITLE
Bug with grdgradient and -Risosocode?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6040]
I want to create a satellite map with intensities from the relief. I use this script:

```
gmt begin Marble_Intes png
	gmt basemap -RBR -JM15c -Baf
#	gmt basemap -R=AF -JM15c -Baf
	gmt grdgradient @earth_relief_20m -Nt1 -A45 -Gintens.nc
#	gmt grdinfo intens.nc
	gmt grdimage @earth_day_20m -Iintens.nc
gmt end
```
I found two things: 

First, when I run `gmt grdgradient` without -RBR I get a grid from all the world besides in the previous line I define -RBR (Brazil). Is this suppose to work this way? Or should `grdgradient` take the region from the previous line? Not sure if it is a bug or should be a feature request.

The second issue is related with the region. When I use `	gmt basemap -RBR -JM15c -Baf` I get:

`grdimage [ERROR]: Requested region exceeds illumination extent` and an empty frame: 

![Marble_Intes_Br](https://user-images.githubusercontent.com/17908951/142642143-80223dcc-73fc-4b03-b6df-100c89f0977c.png)

But when I use -R=AF or R=EU I got this message and the figure is ok. It seems there is an issue with negative longitudes. 

```
grdsample [WARNING]: Output sampling interval in x exceeds input interval and may lead to aliasing.
grdsample [WARNING]: Output sampling interval in y exceeds input interval and may lead to aliasing.

```
![Marble_Intes](https://user-images.githubusercontent.com/17908951/142641753-1e9e02ec-d9ae-40a0-9f63-1f79864f4e3b.png)

If I use `gmt basemap -R-72/-29/-35/20 -JM15c -Baf` I get the same warnings and the figure is ok:

![Marble_Intes](https://user-images.githubusercontent.com/17908951/142681771-56aea86d-9e9d-4a63-b1c4-ed96a01399d5.png)

**Comment by PaulWessel** [comment]
**grdgradient** is not a plotting module, just a calculator, hence it does not accept a previous plot region as default, only a previous data selection region. See end of [this section ](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#command-line-history) for details.

**Comment by Esteban82** [comment]
Ok. Thanks. 

I see the map and processing domains. So I must add -RBR for the first example, right? It seems like I would have to write the region twice or reorder the commands. 

Si I wonder if would be helpful to have an argument to get the map region for the processing? Maybe something like just `-R ` so the script would be:

```
gmt begin Marble_Intes png
	gmt basemap -RBR -JM15c -Baf
	gmt grdgradient @earth_relief_20m -Nt1 -A45 -Gintens.nc -R
	gmt grdimage @earth_day_20m -Iintens.nc
gmt end
```

**Comment by PaulWessel** [comment]
We can thing about it.  Right now, a -R would give a "classic mode not allowed in modern mode" error immediately.

**Comment by PaulWessel** [comment]
Can't you just run **grdgradient** first and then only one **-R** is used (plot modules will use data regions if there are no prior plot regions).

```
gmt begin Marble_Intes png
	gmt grdgradient @earth_relief_20m -RBR -Nt1 -A45 -Gintens.nc
	gmt basemap -JM15c -Baf
	gmt grdimage @earth_day_20m -Iintens.nc
gmt end show
```

**Comment by joa-quim** [comment]
I don't think it would be a good idea to start accepting **-R** exceptions in modern mode.

**Comment by PaulWessel** [comment]
No, I agree.  I think the solution is to either plan what -R to use as above, or repeat it if need be.  I am closing this issue.

**Comment by Esteban82** [comment]
Ok. Fine by me. The second issue it is not important? I wonder why it had a different behaviour between -RBR and -R-72/-29/-35/20.

**Comment by PaulWessel** [comment]
You'll get a lot of warnings if you use -Riso without rounding to nearest grid spacing via +r.
