### ISSUE TITLE
Let modifiers of -i (+d|l|o|s) available for -o.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6053]
But for some modules it is not possible to use -i (at least in direct way). 

For example, I will have to do this:

```
gmt pshistogram @v3206_06.txt -F -T50 -I -o3 | gmt info -i+d100 -C -o0
5.26
```

Instead of 
```
gmt pshistogram @v3206_06.txt -F -T50 -I -o3+d100
pshistogram [ERROR]: The -o option does not take +d|l|o|s modifiers; consider -i instead.

```

**Comment by PaulWessel** [comment]
As a command-line user I can sympathize with you on this.  I may decide to add it.  However, the external wrapper types like @joa-quim probably has no use for this as they can do those conversations easily in Julia (and Python and Matlab).  Unlike the input (which is pretty convoluted), the output is much cleaner and I may wish to add a test on this to ensure it does not add much slowness to the execution time.  E.g., if outputting a million records takes some nanoseconds longer than that is fine, etc.

**Comment by PaulWessel** [comment]
See WIP implementation in #7887.

**Comment by Esteban82** [comment]
Now it is working!! Thanks Paul!
