### ISSUE TITLE
modern theme MAP_FRAME_AXES setting needs improvement for polar plots

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6055]
**Description of the problem**

Polar azimuthal projections should have WesN annotations by default.

**Full script that generated the error**

```
gmt basemap -R0/360/-90/-60 -JS0/-90/50/5i -Ba -B+t'South Pole' -png antarctica
```

**Actual outcome**
![antarctica_wrong](https://user-images.githubusercontent.com/14077947/143311425-5eeec3db-bb3f-4ad2-8569-f6aa3c58c907.png)

**Expected outcome**

![antarctica_correct](https://user-images.githubusercontent.com/14077947/143311397-94d69430-0953-419a-9279-f03857101c7a.png)

**System information**

* Operating system: Ubuntu 20.04
* GMT version (`gmt --version`): 6.3

**Comment by PaulWessel** [comment]
Have to dig a bit deeper on this one. We have a place where we do something like what is needed, but for polar (r, theta) projections:

```
	/* Determine suitable MAP_FRAME_AXES for plot */
	if (GMT->current.proj.projection == GMT_POLAR) {	/* May need to switch what is south and north */
		strcpy (axes, GMT->current.proj.flip ? "WrStZ" : "WrbNZ");
		GMT_Report (GMT->parent, GMT_MSG_INFORMATION, "Given polar projection flip = %d, set MAP_FRAME_AXES = %s\n", GMT->current.proj.flip, axes);
	}
```

I can probably piggyback the azimuthal case for S pole here.
