### ISSUE TITLE
Bug with countour lines and decimal?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6066]
Full script:
```
	long=39
	long=39.8
gmt begin grdcontour png
	gmt coast -Rd -JW$long/15c -G200 -Sdodgerblue2
	gmt grdmath -Rg -I1 $long 21 SDIST = tmp_dist.nc
	gmt grdcontour tmp_dist.nc -C2500 -Wthin
gmt end
```
With long=39

![grdcontour](https://user-images.githubusercontent.com/17908951/143726098-665e9e5e-ffe7-4b91-a6cc-9db414607df1.png)

With long=39.8

![grdcontour](https://user-images.githubusercontent.com/17908951/143726119-c8aa530b-2130-4d8b-91db-93bce8e346c5.png)

**Comment by Esteban82** [comment]
And I get this figure in ex23 if I use `-JH89.9/25c` instead of `-JH90/25c`



![ex23](https://user-images.githubusercontent.com/17908951/143726559-10ae0953-5dce-4221-8049-734bd305569e.png)

**Comment by PaulWessel** [comment]
Yep.  I think if the nodes do not land exactly at the w/e periodic boundary then we do not detect the wrap.

**Comment by PaulWessel** [comment]
Try going to -I5 and you can see that while the west is OK (we find the intersection between the contour and the border, on the east there are no nodes outside the border and as we exit the grid on the east we are not and east but a bit inside, hence we do not detect a crossing and proper jump.

`gmt grdmath -R-140.2/219.8/-90/90 -I5 -fg 39.8  21 SDIST = tmp_dist.nc`

works for this projection but not if made with -Rg or -Rd.

**Comment by Esteban82** [comment]
In the past, my first script works without any problem. I think until 1 year ago.

**Comment by PaulWessel** [comment]
If you can find a version (6.2?, 6.1.1) or a particular commit where that worked, then it would be easier to try to fix it. Off for the test of the night now...

**Comment by Esteban82** [comment]
I have to install some old versions on windows. 

With 6.1.0 it works. With 6.1.1 it doesn't.

**Comment by PaulWessel** [comment]
I see.  The horizontal lines are missing but the global grid is still compromised by the ends.  Here is 6.1 (using -I10 so easier to see):

```
gmt begin wr
	gmt grdmath -Rg -I10 35 21 SDIST = tmp_dist.nc
	gmt grdcontour -Rd -JW35/15c tmp_dist.nc -C2500 -Wthin -B0
gmt end show
```

![wr](https://user-images.githubusercontent.com/26473567/143792455-e15eca9a-da6d-408e-ae32-f8bb57db4488.png)
