### ISSUE TITLE
Missing annotation in map_JE.sh test on Windows

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6072]
**Description of the problem**

This is a bug report for the known failing test `test/psbasemap/map_JE.sh` on windows (relates to https://github.com/GenericMappingTools/gmt/issues/6068)

**Full script that generated the error**

```
gmt basemap -B10g10 -Je-70/-90/1:10000000 -R-95/-75/-60/-55r -png map_JE
```

**Actual outcome**

![map_JE](https://user-images.githubusercontent.com/14077947/144124027-5d71bae7-0a39-4755-8e63-aff63bbef6bc.png)

**Expected outcome**

![map_JE_anywhere](https://user-images.githubusercontent.com/14077947/144124044-766f3c07-8da4-4bae-b5fb-3e337782e3df.png)

**System information**

* Operating system: Windows 10
* GMT version (`gmt --version`): 6.4.0_e66052b_2021.11.30

**Comment by PaulWessel** [comment]
Is this related to modern theme where we set _lon_horizontal_ and _lat_horizontal_?  I see gmt_init.c has

`	GMT->current.setting.map_annot_oblique = GMT_OBL_ANNOT_LON_HORIZONTAL | GMT_OBL_ANNOT_LAT_HORIZONTAL | GMT_OBL_ANNOT_EXTEND_TICKS;
`

So perhaps the PS original is just too old (from Thu Dec  6 10:53:11 2018) which predates themes.

**Comment by meghanrjones** [comment]
You are correct - we did not update this PS file after themes because I did not check the known failures (see #6075).

**Comment by PaulWessel** [comment]
Unless you have a new PS handy, I can run this and update.

**Comment by meghanrjones** [comment]
I think we should add `MAP_ANNOT_OBLIQUE=anywhere` to the test script rather than updating the PS to get the test passing again on macOS and Linux. It will still fail on Windows due to a missing annotation:
![map_JE](https://user-images.githubusercontent.com/14077947/144301974-df3754a8-ac6b-4448-82dd-f6bdc029f396.png)

**Comment by PaulWessel** [comment]
Agree, even better.  Please do.

**Comment by meghanrjones** [comment]
OK, done in https://github.com/GenericMappingTools/gmt/commit/0f5316530226e7e7f1f71c2f35426446c9d05aeb. I also updated the issue title to be more accurate.
