### ISSUE TITLE
Allow for longer history and remark strings

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6078]
**Description of the desired feature**

Since last century, the grid header strings title, history and remake (as well as units) have been defined as

```
char x_units[GMT_GRID_UNIT_LEN80];     /* units in x-direction */
char y_units[GMT_GRID_UNIT_LEN80];     /* units in y-direction */
char z_units[GMT_GRID_UNIT_LEN80];     /* grid value units */
char title[GMT_GRID_TITLE_LEN80];      /* name of data set */
char command[GMT_GRID_COMMAND_LEN320]; /* name of generating command */
char remark[GMT_GRID_REMARK_LEN160];   /* comments re this data set */
```

Hence, any GMT native binary grids are limited to those lengths.  However, there is no good reasons to limit these strings for the more typical format such as netCDF.  I am currently trying to set a remark to contain a citation and running into the 160 limit, which is silly. Also, many netCDF files have a series of concatenated command histories and even 320 becomes too small.

I think this is a backwards compatible change:

1. Replace the above fixed length char arrays with char pointers.
2. Let `GMT->session.readinfo[] `be the places where we allocate these strings based on what we find in the file
3. When writing native grids and any other format with a limit on string length, ensure we max write the length as indicated above.
4. When a grid header is freed, we free these strings as well.

Any unforeseen consequences with this, @GenericMappingTools/gmt-team?

**Comment by joa-quim** [comment]
Will break Julia and MEX that have fixed sizes in the GRID_HEADER structs

**Comment by PaulWessel** [comment]
Yes true.  Just thought of an alternative solution.  When we detect longer strings that can be held, we truncate then as we do now but store the full version in new pointers in either the grid header or the hidden grid header.  I understand this may also mean an update to the Julia structs but this is where some sort of versioning must come in, right?  There must be a way to address upgrades when necessary.

**Comment by joa-quim** [comment]
Following the semantic version that breaking change alone would imply a GMT7

**Comment by PaulWessel** [comment]
That is a valid point.  We will wait for GMT 7 on that.

**Comment by anbj** [comment]
When these strings get increased length, would it be possible to keep a history of e.g. commands that the grid has been through? As it is now, only the last command will be 'saved' in command[], I think?

Basically; append to the string; don't replace it.

**Comment by anbj** [comment]
Also, converting a netcdf file to .e.g. geotiff strips off this information:

```
$ gmt grdinfo loke-utm31-inv.nc 
loke-utm31-inv.nc: Title: Produced by grdmath
loke-utm31-inv.nc: Command: grdmath loke-utm31.nc -1 MUL = loke-utm31-inv.nc
loke-utm31-inv.nc: Remark: Hello
loke-utm31-inv.nc: Gridline node registration used [Cartesian grid]
loke-utm31-inv.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
loke-utm31-inv.nc: x_min: 662330 x_max: 663040 x_inc: 1 name: x n_columns: 711
loke-utm31-inv.nc: y_min: 8170380 y_max: 8171050 y_inc: 1 name: y n_rows: 671
loke-utm31-inv.nc: v_min: -2457.73510742 v_max: -2303.93994141 name: z
loke-utm31-inv.nc: scale_factor: 1 add_offset: 0
loke-utm31-inv.nc: format: netCDF-4 chunk_size: 143,135 shuffle: on deflation_level: 3

$ gmt grdconvert loke-utm31-inv.nc -Gloke-utm31-inv.tif=gd:GTiff

$ gmt grdinfo loke-utm31-inv.tif
loke-utm31-inv.tif: Title: Grid imported via GDAL
loke-utm31-inv.tif: Command: 
loke-utm31-inv.tif: Remark: 
loke-utm31-inv.tif: Gridline node registration used [Cartesian grid]
loke-utm31-inv.tif: Grid file format: gd = Import/export through GDAL
loke-utm31-inv.tif: x_min: 662330 x_max: 663040 x_inc: 1 name: x n_columns: 711
loke-utm31-inv.tif: y_min: 8170380 y_max: 8171050 y_inc: 1 name: y n_rows: 671
loke-utm31-inv.tif: v_min: -2457.73510742 v_max: -2303.93994141 name: z
loke-utm31-inv.tif: scale_factor: 1 add_offset: 0
```

**Comment by meghanrjones** [comment]
Would adding a new element to the header to store the citation history also be a breaking change?

**Comment by joa-quim** [comment]
Anything that changes the structures [starting at](https://docs.generic-mapping-tools.org/dev/devdocs/api.html#data-tables) is a breaking change. But the C ``struct GMT_GRID_HEADER {`` ends with a non-public ``void *hidden;`` that could eventually be used to add/read new attributes in the nc files with extended info. Doing it this way would not break anything.

**Comment by PaulWessel** [comment]
Yes, I was going to ask you if you were also wrapping the HIDDEN structs, but if you don't then that gives me wiggle room to add things there.  OK?

**Comment by joa-quim** [comment]
No wrapping of that void pointer. It just lays there wasting the 8 bytes of the pointer address. Feel free to stuff in that hidden jungle.

**Comment by PaulWessel** [comment]
Oh boy, I will add in a link to a 2 Gb hidden grid just to bring your laptop to a halt.

**Comment by joa-quim** [comment]
Ah, that's a dwarf. Nothing like a [good 3.6 GB Docker](https://forum.generic-mapping-tools.org/t/an-official-docker-image-for-gmt/2003/10) that wraps the monstrous Conda

**Comment by PaulWessel** [comment]
In the spirit of Christmas I did not add any hidden grids, this time.

**Comment by meghanrjones** [comment]
Longer history and remark strings were implemented in https://github.com/GenericMappingTools/gmt/pull/6084, so I am closing this issue. Please reopen if there is more to be done.
