### ISSUE TITLE
Memory issue with sphdistance -D

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6089]
**Description of the problem**

There is a memory corruption issue with sphdistance -D. 

**Full script that generated the error**

```
gmt sphdistance @gshhs_c.txt -Rg -I1 -Gtt.nc -Lk -D
```

**Full error message**

```
sphdistance [WARNING]: Skipped 21 duplicate points in segments
malloc: Heap corruption detected, free list is damaged 
```

**System information**

* Operating system: macOS
* GMT version (`gmt --version`): 6.4.0_8ba5e7f_2021.12.02

**Comment by PaulWessel** [comment]
Can you tell more if you run in xcode with all the malloc guards on?

**Comment by meghanrjones** [comment]
> Can you tell more if you run in xcode with all the malloc guards on?

Yes. I found this while trying to put together fun figures for the PyGMT agu poster and opened the issue to not forget about it. I will debug after finishing a few figures for the poster.
