### ISSUE TITLE
Improve -Rxmin/xmax/ymin/ymax+uunit

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6090]
I was thinking on allow the two following options to simplyfy how to define it.

-Rx+uunit. We define one value which is the same for the four values (with a negative for the min). xmin= ymin = - x. xmax = y max = x

-Rx/y+uunit. We define two values (x, y) where xmin = -x and ymin = -y.

**Comment by PaulWessel** [comment]
It is a good idea, but I do not think we need the leading x/y stuff since we can tell from the number of slashes.

**-R**_radius_**+u**_unit_
**-R**_xhalf/yhalf_**+u**_unit_

Only allowed when +u is used. The debate may be if it should be _radius_ or _diameter_ and _xside_ versus _xhalf_, etc.

**Comment by PaulWessel** [comment]
I think it makes more sense in this case to give the dimensions (e.g.. diameter for the square) since it is really a shorthand for writing -x/x = 2x.  Makes more sense to say -R300200+uk for a 300 by 200 km area than -R150/100+uk I think.  What do other @GenericMappingTools/core think?

**Comment by Esteban82** [comment]
Another question. 

I try `-R-1/1/-1/1+ud` and I got:

`Option -R: The +u<unit> modifier only applies to projected coordinates. Your unit d is ignored
`
Could we allow using degree/minutes/seconds of arc?

In the[ forum ](https://forum.generic-mapping-tools.org/t/zoom-level-base-on-the-plotted-point/2340/9?u=esteban82 )an user make the following to get the region:

`region = [lon -4, lon +4, lat-4, lat +4]
`
So, if we allow using degrees the user will could make:

```
-R4+ud    or -R8+ud if we used the diameter
-JM$lon/$lat/10c
```

**Comment by Esteban82** [comment]
> Only allowed when **+u** is used. The debate may be if it should be _radius_ or _diameter_ and _xside_ versus _xhalf_, etc.

I think that we should use radius and xhalf. It is more coherent with the general case (-Rxmin/xmax/ymin/ymax+uunit) where the distance to one side is indicated.
