### ISSUE TITLE
Improve -R+r/R/e docs

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6127]
I make this map where I use a negative value (-2) for `-R+e`.  

I thought that I was going to get an error (and that should make a feature request) but it worked. With `+R` and `+e` also seems to be working fine.

So I want to confirm this. 

And then, maybe the docs could be updated.

` gmt coast -W -png map -Baf -N1 -Df -RIT+e-2 -Slightblue`

![mapa3](https://user-images.githubusercontent.com/17908951/146446078-086205c6-5b7c-4d2f-b617-5ba273b2ae2f.png)

**Comment by PaulWessel** [comment]
Yes, I think there is no check on the sign of these increments. Perhaps @meghanrjones can polish the docs to note that a negative value goes in the opposite sense and shrinks the region.
