### ISSUE TITLE
subplot automatically adds frame settings to all subplots

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#613]
**Full script that generated the error**

```
gmt begin example png
gmt subplot begin 2x3 -Fs4c/4c -M5p/10p
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c
gmt subplot end
gmt end
```

No `-B` is used in this script, as I don't want any frames. But it seems subplot automatically adds `-BWSEN` to each subplot.

**Output**

![image](https://user-images.githubusercontent.com/3974108/55746970-1ed51f80-5a09-11e9-8c1c-faa72da0a6cb.png)

**Comment by PaulWessel** [comment]
The annotations layout is completely determined by subplot -S and since you did not do -S you are getting the default.  To get no frames whatsoever you may need to override with -B+n or something.  I have not tried that.

**Comment by seisman** [comment]
`-B+n` doesn't work.
```
psxy [COMPATIBILITY]: Error -B: <WESNZ-framesettings> given more than once!
psxy [ERROR]: Syntax error -B option. Correct syntax:
	-B[p|s][x|y|z]<intervals>[+a<angle>|n|p][+l|L<label>][+p<prefix>][+u<unit>] -B[<axes>][+b][+g<fill>][+o<lon>/<lat>][+t<title>] OR
	-B[p|s][x|y|z][a|f|g]<tick>[m][l|p] -B[p|s][x|y|z][+l<label>][+p<prefix>][+u<unit>] -B[<axes>][+b][+g<fill>][+o<lon>/<lat>][+t<title>]
psxy [ERROR]: Offending option -BWENS
```

**Comment by PaulWessel** [comment]
OK, the -B options are auto-generated by subplot so probably an issue there.  I agree there should be a way to turn off everything.

**Comment by PaulWessel** [comment]
Finally looked at this.  I can make it so no frames are plotted whatsoever by allowing subplot to take **-B+n
**.  However, with no frames and clipping we get the following (correct plot).  With PostScript output I can tell that it is otherwise correct.  Is this OK?

![example](https://user-images.githubusercontent.com/26473567/58926372-b2b02880-86e6-11e9-97c1-d66488397b97.png)

**Comment by seisman** [comment]
Looks good.

**Comment by seisman** [comment]
@PaulWessel I'd like to reopen this issue since I find more related problems.

From my understanding, no matter **-S** option is used or not, **-B** option is added to all plotting commands in a subplot. If a subplot is made by tens of plotting commands, the frame is also plotted repeatedly.

Below is an example script. In the 2nd subplot, I use a for loop to call "plot" commands 100 times.
```
gmt begin example
    gmt subplot begin 1x2 -Fs4c/4c
    echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c0

    for i in {0..100}; do
        echo 2 2 | gmt plot -R0/5/0/5 -Sc0.2c -c1
    done
    gmt subplot end
gmt end show
```
This is the output figure. The frame of the 2nd subplot looks blurry.

![image](https://user-images.githubusercontent.com/3974108/68828761-d2c01c80-0674-11ea-8fd5-e1812db1fb5e.png)

Same thing happens if **-S** is used. For example:

![image](https://user-images.githubusercontent.com/3974108/68828929-495d1a00-0675-11ea-8862-e6f7c13d60aa.png)

Maybe subplot mode should remember if the frame has been plotted?

---
Another question is about the default behavior (i.e. adding `-BWSEN` if **-S** is not used). Why was the default behavior designed in this way?

**Comment by PaulWessel** [comment]
Will have to look.  The idea was that the first plot command in a subplot panel would do -B and no other.

**Comment by PaulWessel** [comment]
So the next panel is selected with **-c** and we then allow **-B** options to be applied.  Additional overlays do not get the **-B** treatment.  This differs from your example where you are using **-c** 100 times to "start over" at the same panel.  I think this should be considered a user error and not a GMT bug.  Giving **-c** you are telling GMT to "start a new panel and draw the frame".

**Comment by seisman** [comment]
I think **-c***index* or **gmt subplot set** *index* means activating/selecting a specific panel. The panel may be new or may already exist.

In the example, I use  **-c1** multiple times, because sometimes we may want to go back and forth between different panels.

**Comment by PaulWessel** [comment]
Closing for now.

**Comment by Arjunvh** [comment]
is it possible to plot a map and psxy plot in one figure using subplot?

**Comment by joa-quim** [comment]
Yes, I don't see why not. But please use the forum to ask questions.
