### ISSUE TITLE
Plotting grid sub-regions in linear projections is bugged from Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6140]
This came out in the [forum post](https://forum.generic-mapping-tools.org/t/a-weird-issue-related-to-subplot/2460) and it doesn't look like a Julia bug. See, it screws with linear projections (including Plate Carre) but works well for *true* projections (Mercator in this example). 
Note that plotting directly from the file (i.e. without loading it first) also works well.
```
julia> G = gmtread("@earth_relief_05m");

julia> grdimage(G, region=(-180,-40,15,80), color=:geo, figsize=10, Vd=1, show=1)
        grdimage  -R-180/-40/15/80 -JX10/0 -Baf -BWSen -n+a -Cgeo -P -K > C:\TEMP\GMTjl_tmp.ps

julia> grdimage(G, region=(-180,-40,15,80), color=:geo, figsize=10, proj=:merc, Vd=1, show=1)
        grdimage  -R-180/-40/15/80 -JM10 -Baf -BWSen -n+a -Cgeo -P -K > C:\TEMP\GMTjl_tmp.ps
```

![GMTjl_tmp-fs8](https://user-images.githubusercontent.com/537321/147025673-45c5388e-4b7a-40a6-9e3d-7142fbc50067.png)

![GMTjl_tmp-fs8](https://user-images.githubusercontent.com/537321/147025755-184bfe8c-9def-4fc9-b63f-c464b4205343.png)

**Comment by PaulWessel** [comment]
Plotting geographic with linear is always odd.  I suspect on the CLI front we know the data is geographic and that sets basically -fg under the hood.  Please try to add **-fg** (or use -JX10d/0 or something to tell it) to see if that is the case.  But you also say -JQ which definitively should set -fg...

**Comment by joa-quim** [comment]
Adding ``-fg`` makes no difference. I tried ``-JQ``, even changed central meridian, to test it too.

**Comment by PaulWessel** [comment]
Will try to debug later today.

**Comment by PaulWessel** [comment]
OK, migrated all my stuff from Mac Mini to new MacBook pro laptop.  Julia on mac ports for M1 still screwed so using the alternate direct install.  Can reproduce the problem.  I noticed these too:

```
G = gmtread("@earth_relief_05m");
GMT [WARNING]: Max total memory allocated was 35.792 Mb [37530568 bytes]
GMT [WARNING]: Single largest allocation was 35.596 Mb [37324800 bytes]
GMT [WARNING]: MEMORY NOT FREED: 0.062 kb [64 bytes]
GMT [WARNING]: Items allocated: 247 reallocated: 134 freed: 245
GMT [WARNING]: Items NOT PROPERLY FREED: 2
GMT [WARNING]: Memory not freed first allocated in gmt_parse.c:955(GMT_Make_Option) (ID = 8): 0.031 kb [32 bytes]
GMT [WARNING]: Memory not freed first allocated in gmt_parse.c:955(GMT_Make_Option) (ID = 9): 0.031 kb [32 bytes]
```
Added stop points in Xcode and it all works fine - no sluggishness or spinning wheels.  Will see what I learn.

**Comment by PaulWessel** [comment]
Found an issue. Testing the fix.

**Comment by PaulWessel** [comment]
I cannot get to the memory with ID 8 since it seems it was allocated by GMT_Create_Session and I cannot get a stop in that function.  Does "using GMT" start a session?

**Comment by PaulWessel** [comment]
OK, got there.  I see `using GMT` is processing some options and those are not freed when the gmtread ends, hence a memory leak.  Probably up to @joa-quim to fix that.

**Comment by joa-quim** [comment]
>  Julia on mac ports for M1 still screwed so using the alternate direct install.

Always use the Julia binaries provided in the Julialang site.
Still want me to fix any mem leak? Julia starts a session that lasts ... till we kill it.

**Comment by PaulWessel** [comment]
No big deal, but it seems gmtread ends a session (?) and therefore complains about unfreed memory.  It is a bit odd.

**Comment by joa-quim** [comment]
Some modules still leave the session in a non-cleaned state. So when I find one such situation I delete the session at the end ant a new one will be created when needed. ``gmtread`` also creates a second session but, in principle, only when reading an ogr file, but maybe there is an indirect *recreation* in the middle that I'm not seeing right now
```
	# Because of the certificates shits on Windows. But for some reason the set in gmtlib_check_url_name() is not visible
	(Sys.iswindows()) && run(`cmd /c set GDAL_HTTP_UNSAFESSL=YES`)
	API2 = GMT_Create_Session("GMT", 2, GMT_SESSION_NOEXIT + GMT_SESSION_EXTERNAL + GMT_SESSION_NOGDALCLOSE + GMT_SESSION_COLMAJOR);
...
GMT_Destroy_Session(API2)
```

**Comment by PaulWessel** [comment]
Seems that will lead to some memory leaks. You can see them if you compile GMT with the -DDEBUG and -DMEM_DEBUG options (see the advanced Cmake file).

**Comment by joa-quim** [comment]
It's -DMEMDEBUG and I do build with them and don't see those warnings!

**Comment by PaulWessel** [comment]
Hah, that is odd.  I got it both when just running the Julia commands in the terminal as well as when hooked to Xcode.
