### ISSUE TITLE
how to add one more line of tick label to graph

### ISSUE THREAD

**Issue by alex0516** [GenericMappingTools/gmt#617]
**Description of the problem**

Hi, I have a question to ask when using the psxy or other tools. 

How to add one more line of x/y tick label to the graph? Is there any tool in GMT?

Thanks
Alex

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Version of GMT:

**Comment by joa-quim** [comment]
Sure it's possible, but you have to be more specific. For example, Idon't understand what you want to achieve. Showing us what you have tried is a good start. But nothing like a visual example of what you want. Even if it is a hand sketch.

**Comment by PaulWessel** [comment]
If you mean to have a second axis with potentially different range and annotation (e.g., one axis is degrees Celcius and the other is Fahrenheit, both going from 0 to 100 C) then you need to use psbasemap twice and just offset the plot in the x or y direction accordingly (via **-X** or **-Y**).

**Comment by seisman** [comment]
Closing. No feedback.
