### ISSUE TITLE
unexpected behavior by x2sys_datalist

### ISSUE THREAD

**Issue by bjcoakley** [GenericMappingTools/gmt#6170]
I have made some progress on utilizing x2sys for crossover errors. You may recall, I was having some trouble using x2sys_solve to estimate the best fitting parameters from the crossovers. I have been able to use it with artificial data on internal crossovers. I used the track from my 2011 Langseth cruise and, by sampling existing grids for Arctic Ocean gravity and bathymetry, created a track with negligible crossover errors. I then applied a drift of 1 mGal per day to the sampled gravity and 1 meter per day to the sampled bathymetry and used this file for my crossover analysis.

Using x2sys_solve with correction types (specified with -E) constant offset, linear drift with distance, offset plus unit scale correction and linear drift with time (options c, d, t and z). With the first three, I was able to produced corrected data. With the linear time drift option, x2sys_solve accurately estimated the drift, but the output from this process did not work well with x2sys_datalist.

So the drift parameters for this case were;

Langseth-11-210-simple-drift grav 0 1.15732e-05*((time-T))
 Langseth-11-210-simple-drift bthy 0 1.15735e-05*((time-T))

Note that the time unit was seconds and 1.15735e-05 times 86400 is very nearly one, so the program recovered the same drift slope I used to make the artificial “data.”

x2sys_solve also reported the mean and std dev of the data before and after applying these corrections. For gravity;

x2sys_solve [INFORMATION]: Before correction, mean and st.dev.: -2.11173 11.6417 x2sys_solve [INFORMATION]: After correction, mean and st.dev. : 0.000190399 0.00342762

For bathymetry;

x2sys_solve [INFORMATION]: Before correction, mean and st.dev.: -2.11117 11.6425 x2sys_solve [INFORMATION]: After correction, mean and st.dev. : 0.000798657 0.109874

The program x2sys_datalist worked well with three versions of the -E option in x2sys_solve. For the linear time drift option it reported an error.

x2sys_datalist [INFORMATION]: Your distance unit (e) implies geographic data; -fg has been set.
 x2sys_datalist [ERROR]: X2SYS Correction table (xover-test-2/xover-test-2_corrections.txt) requires a column (time) not present in COE database or auxiliary columns

It is not clear what the error refers to. The track file contains time;

64.000460 191.597291 1315739130.00 -2.34 NaN -29.96 
64.002103 191.597329 1315739160.00 -2.41 NaN -29.97
 64.003089 191.597357 1315739179.00 -2.46 NaN -29.97
 64.003721 191.597358 1315739190.00 -2.49 NaN -29.98 
64.005347 191.597358 1315739220.00 -2.56 NaN -29.98
 64.006358 191.597373 1315739239.00 -2.60 NaN -29.98

It is consistent with the .fmt file used to initialize the database.

# Define file for the Arctic format
#ASCII # File is ASCII
 #GEO # Data are geographic 
#name type NaN NaN-proxy scale offset oformat
 lat a N 0 1 0 %9.6f 
lon a N 0 1 0 %10.6f
 rtime a N 0 1 0 %13.2f 
grav a N 0 1 0 %6.2f 
magn a N 0 1 0 %7.2f 
bthy a N 0 1 0 %7.2f

The COE file uses time tags, but I don’t think x2sys_datalist should be going back to that;

Tag: xover-test-2
Command: x2sys_cross Langseth-11-210-simple-drift -Txover-test-2 -Il -Sl1.0 -Su40.0 -Qi -V -Z
lon lat t_1 t_2 dist_1 dist_2 head_1 head_2 vel_1 vel_2 grav_1 grav_2 magn_1 magn_2 bthy_1 bthy_2
Langseth-11-210-simple-drift 0 Langseth-11-210-simple-drift 0 2011-09-11T11:05:30/2011-10-07T05:44:00/7400.09 2011-09-11T11:05:30/2011-10-07T05:44:00/7400.09
 -158.601399 74.505466 2011-09-21T15:01:55 2011-10-02T04:53:50 2911.265730 5666.532446 214.025281 125.403931 11.119070 10.386424 11.826169 22.400000 NaN NaN -868.547607 -857.972286 
-159.467164 74.847982 2011-09-21T19:16:28 2011-10-01T10:33:16 2957.277146 5471.532954 213.377161 306.241110 10.480004 11.025322 -16.238760 -6.599659 NaN NaN -1812.641394 -1803.017391 
-160.402656 74.168602 2011-09-21T00:35:41 2011-10-02T11:35:31 2756.640406 5732.619761 35.554968 126.395127 10.947543 9.647302 39.769840 51.230613 NaN NaN -517.471922 -506.001902

I have not changed any of the source files during this process, so it seems whatever has come out should be consistent with the calculations in x2sys_solve.

I have attached these files and my script for doing the solving and correction of the track data. 

I invoke the script below on the command line; /bin/csh COA-correct xover-test-2 T

#!/bin/csh 

setenv X2SYS_HOME `pwd`

gmt set D_FORMAT %.6f TIME_EPOCH 1970-01-01T00:00:00 TIME_UNIT s

set TAG = $1
set model = $2

if (-e $TAG/"$TAG"_corrections.txt) then
    /bin/rm $TAG/"$TAG"_corrections.txt
endif

if ($model == "DC") then
    echo Setting DC shift.
    set F = "-Fcn"
    set E = "-Ec"
else if ($model == "D") then
    echo Setting scale by track distance.
    set F = "-Fdcn"
    set E = "-Ed"
else if ($model == "T") then
    echo Setting scale by time along track.
    set F = "-FTcn"
    set E = "-Et"
else if ($model == "S") then
    echo Setting scale by scaling Z.
    set F = "-Fzn"
    set E = "-Ez"
else
    echo "No correction model $model."
    exit
endif

foreach cruise (`cat $TAG/$TAG.lis | awk '{printf"%s ",$1}'` )
    gmt x2sys_list -Cgrav -T$TAG $TAG/crossover-files/$cruise.coa.txt -E $F -V > crossovers.grav.txt

   gmt x2sys_solve crossovers.grav.txt -Cgrav $E -T$TAG -V >> $TAG/"$TAG"_corrections.txt
   
   gmt x2sys_list -Cbthy -T$TAG $TAG/crossover-files/$cruise.coa.txt -E $F -V > crossovers.bthy.txt

   gmt x2sys_solve crossovers.bthy.txt -Cbthy $E -T$TAG -V >> $TAG/"$TAG"_corrections.txt
   
   gmt x2sys_datalist $cruise -T$TAG -L$TAG/"$TAG"_corrections.txt -Vd > $cruise.corr.trk
end

I include here the full output from x2sys_datalist using the -Vd option.

gmt [DEBUG]: Obtained the ppid from parent: 56869
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /opt/homebrew/Cellar/gmt/6.2.0_1/share/gmt
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/Bernard Coakley
gmt [DEBUG]: GMT->session.USERDIR = /Users/Bernard Coakley/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/Bernard Coakley/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/Bernard Coakley/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/Bernard Coakley/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /opt/homebrew/Cellar/gmt/6.2.0_1/share/gmt/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR /opt/homebrew/Cellar/gmt/6.2.0_1/share/gmt
gmt [DEBUG]: GMT: 6. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_reload_settings
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Found file gmt.conf
gmt [DEBUG]: Reading GMT Default parameters from file: gmt.conf
gmt [DEBUG]: Exit:  gmt_reload_settings
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 8 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /opt/homebrew/Cellar/gmt/6.2.0_1/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /opt/homebrew/Cellar/gmt/6.2.0_1/lib/gmt/plugins/supplements.so
gmt [DEBUG]: Revised options: Langseth-11-210-simple-drift -Txover-test-2 -Lxover-test-2/xover-test-2_corrections.txt -Vd
x2sys_datalist [DEBUG]: Found readable file xover-test-2/xover-test-2_corrections.txt
x2sys_datalist [DEBUG]: Replace file xover-test-2/xover-test-2_corrections.txt with path xover-test-2/xover-test-2_corrections.txt
x2sys_datalist [DEBUG]: Replace file xover-test-2/xover-test-2_corrections.txt with xover-test-2/xover-test-2_corrections.txt
x2sys_datalist [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
x2sys_datalist [DEBUG]: Look for file 0/360/-90/90 in /Users/Bernard Coakley/.gmt
x2sys_datalist [DEBUG]: Look for file 0/360/-90/90 in /Users/Bernard Coakley/.gmt/cache
x2sys_datalist [DEBUG]: Look for file 0/360/-90/90 in /Users/Bernard Coakley/.gmt/server
x2sys_datalist [DEBUG]: Got regular w/e/s/n for region (0/360/-90/90)
x2sys_datalist [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
x2sys_datalist [INFORMATION]: Your distance unit (e) implies geographic data; -fg has been set.
x2sys_datalist [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
x2sys_datalist [DEBUG]: Found readable file xover-test-2/xover-test-2_corrections.txt
x2sys_datalist [DEBUG]: Calling nc_open on xover-test-2/xover-test-2_corrections.txt, ncid = 0, err = -51
x2sys_datalist [DEBUG]: Found readable file xover-test-2/xover-test-2_corrections.txt
x2sys_datalist [ERROR]: X2SYS Correction table (xover-test-2/xover-test-2_corrections.txt) requires a column (time) not present in COE database or auxiliary columns
x2sys_datalist (x2sys_free_list): tried to free unallocated memory

Expected outcome would be track data corrected with the drift parameters estimated by x2sys_solve. No file was written.

System information
Mac OS Monterrey 12.0.1
GMT version 6.2

Note; I added .txt to the trk and fmt files so they would be accepted.
[crossovers.grav.txt](https://github.com/GenericMappingTools/gmt/files/7791206/crossovers.grav.txt)
[crossovers.bthy.txt](https://github.com/GenericMappingTools/gmt/files/7791207/crossovers.bthy.txt)
[xover-test-2.fmt.txt](https://github.com/GenericMappingTools/gmt/files/7791208/xover-test-2.fmt.txt)
[Langseth-11-210-simple-drift.trk.txt](https://github.com/GenericMappingTools/gmt/files/7791209/Langseth-11-210-simple-drift.trk.txt)
[Langseth-11-210-simple-drift.coa.txt](https://github.com/GenericMappingTools/gmt/files/7791212/Langseth-11-210-simple-drift.coa.txt)

**Comment by PaulWessel** [comment]
Hi @bjcoakley, sorry for the extreme tardiness (nothing new I know).  I am not at Oxford and hopefully I can carve out a weekend to go over all of this.

**Comment by bjcoakley** [comment]
No worries. Let me know if you need anything else.
