### ISSUE TITLE
Perennial ghost gridlines in coast needs a fix

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6173]
See this [forum post ](https://forum.generic-mapping-tools.org/t/cannot-cancel-the-display-of-grid-lines-when-using-transparent-color/2475/6)for background.  This script plotting just land shows the problem more cleanly:

`gmt coast -JW15c -R70/110/30/60 -Gblack -B  -A40000 -Dl -pdf map`

[A raster version does not show it as it is very sutbtle and requires vector graphics, i.e., PDF]

As I wrote in the forum,

> You can see the polygon boundaries are not exact. Why is not clear since they all get their coordinates from the same function _gmt_graticule_path_. So I think the path from, say (80,40) to (80,50) are exactly the same in the two neighboring blocks. However, we also have some PostScript coordinate simplifications going on and I suspect this is where there may be some tiny differences. I will make an issue and explore this. Perhaps we will need to turn off that effect for **coast**.

**Notes**: This is my hypothesis: While two neighboring blocks do share exactly the same _lon,lat_ coordinates for the shared border,  the other borders are unique to each block.  When these block polygons are converted to _PostScript_ units and further simplified, the section they have in common may start at index A in one polygon and index B in another.  The simplification algorithm probably gives slightly different results due to this difference.  I can explore this by

- Dump out the _lon,lat_ coordinates of the two blocks and verify identical coordinates along shared border
- Dump out the projected _x,y_ coordinates of the two blocks and verify identical coordinates along shared border
- Compare the two _PostScript_ polygon coordinates to verify they differ
- Experiment with turning off the _PostScript_ simplification algorithm to see if this effects is the culprit

**Comment by PaulWessel** [comment]
Preliminary findings:

1. Because the two sides of the blocks may slightly overlay when rasterized by gs the transparency has the side effect of darkening the overlap, hence what seems to be lines are appearing. 
2. Turning off the line simplification and increasing the PostScript units resolution by 10x makes no difference.

The bottom line seems to be that using transparency in pscoast is not recommended as it will have that edge effect.

**Comment by PaulWessel** [comment]
I wonder if @leeyupeng119 sued transparency to get a lighter color or if there was a plan to see through the land and ocean to something plotted beneath? I.e., is there a particular need for transparency in the plot?

**Comment by joa-quim** [comment]
It happens also without transparency. What we see then is the page color between the gaps. Clearly visible with
```
gmt coast -JH15c -Rg -Gblack -Cblue -Sskyblue -Bxya20f0g0  -A4000 -W0.25p,black -pdf lixo
```

**Comment by PaulWessel** [comment]
Yes, visible in the viewers.  But try to print it or use PNG etc instead and there are none.  If I open the PostScript version of the above command in ghostview then I see no lines even as I zoom in.  Clearly this is related to anti-aliasing as well (ie., what you see is affected by those settings in the viewer).  Used to be able to control that in macOS Preview but no longer (at least not via a Preference panel option) as I think Apple no longer bothers given the use of retina displays.

So (still) looks to me like this:

1. PDF and PS viewers may or may not offer anti-aliasing choices and for some viewers you will always see the ghostlines
2. When converting to pixels it seems to no longer be an issue (as **gs** will do the rounding)
3. With transparency in coast -G/S the anti-aliasing doubles up colors and we see ghostlines even when rasterizing.

When I temporarily turned PSL line shortening off we should have identical coordinates along the shared border, yet we still could see "gaps" in the PDF.  I do not know if this is due to some internal "snap inwards" for polygons in a PDF viewer or not since even those viewers need to convert lines to pixels.  It is possible that issue (3) above could be improved with different options to gs related to antialiasing but playing with -Q gave no relief.

**Comment by PaulWessel** [comment]
Correction: With our default 1200 dpi PS precision the two central PostScript polygons in

`gmt coast -JW15c -R79/101/39/51 -Gblack  -A40000 -Dl -ps map`

do differ a bit.  The shared vertical line at the map center is vertical in one and off by 1 PS point in its starting x-position in the other, so there is a tiny gap.  This is below the raster resolution and anti-alias settings for most but the gap ,as @joa-quim said, is in fact there.  We can eliminate it by bloating up the PostScript files but we already had that discussion years ago when we selected 1200 as reasonable.  The other effect not yet discussed is that we (again trying to save space) are writing _incremental_ coordinates.  We pay down the absolute integer start coordinate and then compute dx and dy from the integer points.  Since all those points are themselves subject to rounding, this rounding is passed on to the increment.  Hence, the 100th point's coordinates as computed by the sum of those increment may differ from that same points initial integer coordinate.  This is also why changing the dpi to 12000 still does not get away from the tiny gap.

As for the transparency and overlapping/underlapping polygons it would have to be exact I think and that certainly would mean fatter PS files.

**Comment by PaulWessel** [comment]
I tested plotting with floating point coordinates.  Destilled down to two polygons sharing the same vertical boundary.  Here is the PS called map.ps:

```
%!PS-Adobe-3.0
%%BoundingBox: 0 0 595 842
gsave 0.06 0.06 scale
0 setgray
200 200 translate
350.820790269 420.748331288 moveto
3543.30708661 420.748331288 lineto  % Bottom point of vertical line
3543.30708661 4494.45338418 lineto  % Top point of vertical line
682.606017292 4494.45338418 lineto
closepath
fill newpath
3543.30708661 420.748331288 moveto  % Bottom point of vertical line
6737.79338296 420.748331288 lineto
6406.00815594 4494.45338418 lineto
3543.30708661 4494.45338418 lineto  % Top point of vertical line
closepath
fill newpath
grestore
showpage
```

when I run 

gmt psconvert map.ps -Tf -P -A I see this (here via screen capture):

![capture](https://user-images.githubusercontent.com/26473567/147890740-b1f81245-77bc-4e43-881e-2277e97cf2cb.jpg)

As you can see, very faint ghost line down the middle despite using absolute coordinates (with excessive precision) but the point is these are _the exact same coordinates_.  If you shuffle the second polygon so that that line is drawn by _lineto_ and not close path you get the same.  So it would seen there is some sort of "snap inward" for polygons being rasterized since otherwise there should not be any line, no matter how thin.  Or, it is a gs bug/feature.  BTW, if I use Adobe Distiller I get exactly the same ghost line.

I think I will ask the gs people about this.

**Comment by joa-quim** [comment]
I think this last example kills all our hopes to *fix* this.

**Comment by PaulWessel** [comment]
I agree, even the bloated floating point PS does not help.  I can live with PDF/PS viewers who want to show those lines as long as rasters and prints look fine.

**Comment by joa-quim** [comment]
Closing as non-resolvable.
