### ISSUE TITLE
grid-plotting modules extends the grid region twice

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6174]
**Description of the problem**

Grid plotting modules like **grdimage** calls _gmt_grd_setregion_. It currently extends the region (if the source grid has more data to all sides) by 2 rows/columns.  However, later on when we read the grid, we do a similar check and extend the grid another 2 rows and columns.  In the simple example below, we plot the same 10x10 degree image at 1x1 degree resolution.  First directly via @earth_relief_01d and the second time we first do a **grdcut** for that region and then plot.  The problem due to the double-pad is that the top grid is actually 18/32/-32/-18 and has a different z-range than bottom grid that is 20/30/-30/-20. CPT is thus stretched to two different ranges and hence we get two different images of the same area:

![pads](https://user-images.githubusercontent.com/26473567/147841770-8cadbe43-7752-46f3-9189-cbb2635126fa.png)

```
gmt begin pads png
	gmt grdcut @earth_relief_01d -R20/30/-30/-20 -Gtest.nc
	gmt subplot begin 2x1 -R20/30/-30/-20 -JM10c -Fs10c -A
		gmt grdimage @earth_relief_01d -B -c -Cturbo
		gmt grdimage test.nc -B -c -Cturbo
	gmt subplot end
gmt end show
```

Temporarily changing the information messages shows the difference:

```
grdimage [NOTICE]: Auto-stretching CPT file turbo to fit data range -3159.5 to 2451.5
grdimage [NOTICE]: Auto-stretching CPT file turbo to fit data range 699 to 2451.5
```

**Note:** A **grdcut** using 18/32/-32/-18  verifies that the range used in the top case matches this larger grid.  The effect is very easy to see in this particular case due to the tiny grid and the large change in values just off the grid.  For most reasonably sized grids the effect is not noticeable.

**Comment by meghanrjones** [comment]
Closed by #6175
