### ISSUE TITLE
Section dedicated to gdal/ogr2ogr

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6209]
Although *gdal* and e.g. *ogr2ogr* is mentioned a few times in the cookbook, there is no dedicated section for it.
Would this be interesting to add? If yes, where would a natural place for it be? In section *20. The GMT Vector Data Format for OGR Compatibility* of the cookbook (https://docs.generic-mapping-tools.org/dev/cookbook/ogrgmt-format.html)?

During the last weeks I've dealt with datasets in the *geopackage*(/*spatialite*)-format and the potential in using *gmt* with *ogr2ogr* as a gateway to *many* other formats is quite compelling. Pair this with capabilities of a *spatialite*-enabled database(engine), and there is quite a lot one can do. Not to mention PostgreSQL+PostGIS. But then maybe we're to far down the rabbit hole.

First and foremost I'm thinking about *ogr2ogr*; that's the tool I've used most.

**Comment by joa-quim** [comment]
You can read ``.gpkg`` files directly with ``GMT.jl``, and it has also a ``ogr2ogr`` wrapper.

**Comment by joa-quim** [comment]
Start using it? :grinning:

**Comment by anbj** [comment]
Touché!

**Comment by meghanrjones** [comment]
I think it would be great to have an example of using ogr2ogr as a bridge to GMT in https://github.com/GenericMappingTools/gmt-examples. We'd need to discuss how to handle datasets but if this is something you're interested in feel free to open an issue over there.

**Comment by joa-quim** [comment]
The use of ``ogr2ogr`` under the hood is (**must be**) a dead end. Converting binary files to ASCII to let them be read by GMT as if *works fine* is not up to the GMT standards. It only takes a moderately big file to cause embarrassing delays. The solution is to let ``gmt_ogrread()`` be able to talk with the rest of its family.

**Comment by anbj** [comment]
So there is an ongoing NSF funded project on this? Could you link, or give some more info?

In any case, I doubt that all functionality in **ogr2ogr** will be easily available throught **gmt**, right?

**Comment by PaulWessel** [comment]
It is mentioned in the proposal but it is not just for that of course: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1948602

**Comment by anbj** [comment]
Thanks Paul. I didn't see anything about **gdal**/**ogr2ogr**, but I guess it's in there if you say so.

**Comment by meghanrjones** [comment]
FYI @anbj, I created a new project board for vector data interoperability at https://github.com/GenericMappingTools/gmt/projects to track these issues and added the relevant section from the proposal as the description with Paul's approval.

**Comment by anbj** [comment]
Thanks for letting me know @meghanrjones!
