### ISSUE TITLE
grdimage messes up map location when used with -I (hillshade)

### ISSUE THREAD

**Issue by GeohunterX** [GenericMappingTools/gmt#621]
**Description of the problem**

When running grdimage on a a colored grid (geological map generated with gdal from a geotif) together with an intensity grid to get a hillshade effect, the orientation of the geological map is misplaced. Plotting only the map OR only the intensity grid works fine. As soon as they are combined there is an offset in scale and location.

I thought it might be an issue that the grids have different increments but adjusting them with gdalwarp did not help...

**Full script that generated the error**

```
gmt grdimage map.grd -n+c -P -Idem_wgs_shades.grd -R17/20/43/45 -JM >draped.ps
```
File sizes are huge that's why I didn't upload... I could try to reproduce the error with smaller files if necessary?

**Full error message**

```
grdimage [WARNING]: Central meridian not given, default to 19.1
grdsample [WARNING]: Output sampling interval in x exceeds input interval and may lead to aliasing.
grdsample [WARNING]: Output sampling interval in y exceeds input interval and may lead to aliasing.
grdimage [WARNING]: gmt_grd_project: Output grid extrema [-1.21765/1.16006] exceed extrema of input grid [-0.626589/0.673921] due to resampling
grdimage [WARNING]: gmt_grd_project: Output grid clipped to input grid extrema

```

**System information**

* Operating system: Win10 64bit
* Version of GMT: 6.0.0_c86353c_2019.03.18

**Comment by PaulWessel** [comment]
Perhaps start with reporting the output of grdinfo for the two grids.  If they are netCDF grids, also output ncdump -h for the two grids, please.

**Comment by joa-quim** [comment]
> Version of GMT: 6.0.0_c86353c_2019.03.18

Did you build it yourself? It's not of mines, I think.

**Comment by GeohunterX** [comment]
> 
> 
> > Version of GMT: 6.0.0_c86353c_2019.03.18
> 
> Did you build it yourself? It's not of mines, I think.

No, I got it from github. I didn't change anything. But I downloaded shortly after seisman implemented the -p option for pscoupe - maybe thats why the version doesn't seem familiar to you?

**Comment by GeohunterX** [comment]
> 
> 
> Perhaps start with reporting the output of grdinfo for the two grids. If they are netCDF grids, also output ncdump -h for the two grids, please.

Sure - here it comes:

> MAP >
map.grd: Title: Grid imported via GDAL
map.grd: Command: 
map.grd: Remark: 
map.grd: Pixel node registration used [Cartesian grid]
map.grd: Grid file format: gd = Import/export through GDAL
map.grd: x_min: 16.0388792898 x_max: 22.2159600609 x_inc: 0.000837570274052 name:  n_columns: 7375
map.grd: y_min: 39.2714753757 y_max: 44.4853503317 y_inc: 0.000837570274052 name:  n_rows: 6225
map.grd: z_min: 97 z_max: 255 name: z
map.grd: scale_factor: 1 add_offset: 0
+proj=longlat +datum=WGS84 +no_defs 

< INTENSITY FILE (created from DEM and normalized) >
dem_wgs_shades.grd: Title: Produced by grdmath
dem_wgs_shades.grd: Command: grdmath ../../dem/almo_eudem_wgs_hist.grd 6 DIV = ../../dem/dem_wgs_shades.grd
dem_wgs_shades.grd: Remark: Normalized directional derivative(s)
dem_wgs_shades.grd: Pixel node registration used [Cartesian grid]
dem_wgs_shades.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
dem_wgs_shades.grd: x_min: 17.1874134411 x_max: 21.6254624145 x_inc: 0.000288860256009 name:  n_columns: 15364
dem_wgs_shades.grd: y_min: 38.6975271318 y_max: 43.2198630528 y_inc: 0.000288837958806 name:  n_rows: 15657
dem_wgs_shades.grd: z_min: -0.960327148438 z_max: 0.960327148438 name: meters
dem_wgs_shades.grd: scale_factor: 1 add_offset: 0
dem_wgs_shades.grd: format: netCDF-4 chunk_size: 129,129 shuffle: on deflation_level: 3

**Comment by PaulWessel** [comment]
Well, your grids do not cover the same region, nor do they have the same registration or even grid spacing.  The two grids need to be coregistered. Perhaps you could try to resample with grdsample:

> gmt grdresample dem_wgs_shades.grd -Rmap.grd -Gintens.grd

**Comment by joa-quim** [comment]
> No, I got it from github. I didn't change anything. But I downloaded shortly after seisman implemented the -p option for pscoupe

Sorry to insist on this, but downloaded from where? I can't find it.

**Comment by GeohunterX** [comment]
I tried that @PaulWessel  - no changes unfortunately. I even now cut them to the same registration and equalized the increment. Plotting only the map OR plotting only the intensity grid at a time plots them at the right place but as soon as they are combined the map is offset to the NE :-(

**Comment by GeohunterX** [comment]
> Sorry to insist on this, but downloaded from where? I can't find it.

I  downloaded the master branch zip (roughly one month ago) and build it from source according to the instructions

**Comment by joa-quim** [comment]
So you built it yourself. My questions are because you said you are on Windows and if you had build it you would been one of the rare persons who build GMT on Windows. Or are you referring to WinBuntu (WSL)?

**Comment by joa-quim** [comment]
I don't think the drape grid has to have the same resolution as the reliefgrid grid. This [test ](reliefgrid)shows draping of a higher resolution jpeg image on a grid.

**Comment by GeohunterX** [comment]
> So you built it yourself. My questions are because you said you are on Windows and if you had build it you would been one of the rare persons who build GMT on Windows. Or are you referring to WinBuntu (WSL)?

Oh yes then I missunderstood - sorry. I thought you would assuming that I changed the program. And again sorry - I am runnig it in a virtual box on Ubuntu 18.04.2 LTS. I keep forgetting that since my overall OS is Windows...

**Comment by GeohunterX** [comment]
> 
> 
> I don't think the drape grid has to have the same resolution as the reliefgrid grid. This [test ](reliefgrid)shows draping of a higher resolution jpeg image on a grid.

Yes that's what I thought and why I cannot explain why it doesn't work. If I use a DEM grid with a cpt and then use the intensity file everything works fine. Only as soon as I take the map (after converting it to a grd file) it doesn't work. But again - if I plot one at a time everything is also placed properly on the map. That's why I assumed that it might be a bug.

Where is the test located you are refering to? The link you set only directs me to a blank site.

**Comment by joa-quim** [comment]
Fixed the link above. The test is in test/grdview of this repo.

**Comment by PaulWessel** [comment]
I think you will have to provide material for us to reproduce.  See if you can shrink the problem down (smaller area or something) and still have your issues, then make the files available via ftp or similar.

**Comment by PaulWessel** [comment]
Also, your statement that the map is offset to the NE.  Maybe you could post 3 PNGs here showing the three cases (data OK, intensity itself OK, the combination offset) so we can see what you mean.

**Comment by GeohunterX** [comment]
Sorry for my late reply - I was travelling with restricted internet access...

I prepared a smaller dataset and have similar issues. I tried to document my steps in the following figures:
fail1.jpg contains original data input (only cut with ArcGIS and gridded from GeoTiff to grd using gdal_translate).

After applying 
```
grdsample dem_shades.grd -Rmap_cut.grd -Gdem_shades_resampled.grd
```
I got the same problems presented in fail2.jpg
![fail1](https://user-images.githubusercontent.com/48683258/56227223-42394380-6075-11e9-8eea-55834131dad9.jpg)
![fail2](https://user-images.githubusercontent.com/48683258/56227232-482f2480-6075-11e9-9491-743b08fabfe8.jpg)

**Comment by GeohunterX** [comment]
Here comes the script and according files:


[script_and_files.zip](https://github.com/GenericMappingTools/gmt/files/3085900/script_and_files.zip)

**Comment by PaulWessel** [comment]
I am addressing the error message you got in #668.

**Comment by GeohunterX** [comment]
Thank you very much!
