### ISSUE TITLE
Justification of map roses ignore space for label

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6213]
We can place a directional rose anywhere on the map via **-T**, and most easily via justification codes for the 12 points on the map.  However, if  labels are requested then two issues are apparent:

1. The default font used need to scale with the symbol and not be a fixed separate setting. Turns out this is **FONT_TITLE**                     which defaults to 24p,Helvetica,black.  This is way too big for all but poster-size maps I think, so I am sure any users of **-T** also sets a smaller font that is suitable.  In fact, our own example in the cookbook (_GMT_obl_merc.sh_) uses  **--FONT_TITLE**=8p.
2. The space needed for the labels needs to be considered in the justification so they are not falling outside the map

Here is the what is happening now:

![roses](https://user-images.githubusercontent.com/26473567/149019002-1fb9b798-51d7-4a9e-a3cd-67758a37eb59.png)

At least in modern mode that font should scale with the rose symbol size. For both classic and modern the offset should take into account the labels.

**Comment by seisman** [comment]
Maybe related to this issue:

```
gmt basemap -R-10/10/-10/10 -JM15c -TdjMC+w5c -Bafg -png map
```
The direction rose is not plotted at the middler center (MC) of the map:
![map](https://user-images.githubusercontent.com/3974108/156929712-95d8f362-2716-45c8-9e9b-b0f3598d5b15.png)

In the following command, I mistyped `+w5c` as `+5c`:
```
gmt basemap -R-10/10/-10/10 -JM15c -TdjMC+5c -Bafg -png map
```
and I got the below figure. Perhaps GMT can do better at checking the syntax?
![map](https://user-images.githubusercontent.com/3974108/156929795-62e4bff0-e524-405d-89af-ee4b9dcfe15f.png)

**Comment by seisman** [comment]
Similarly, please also verify the placements (especially the offset between the rose and the frames) are correct:

![rose](https://user-images.githubusercontent.com/3974108/165125094-c36d94b7-f4f6-4358-93fd-9940f6bcfc3f.png)
![rose](https://user-images.githubusercontent.com/3974108/165125143-b03a5596-528f-41e4-8647-80bcb02d5ea2.png)

**Comment by PaulWessel** [comment]
I guess the only thing that might need a 2nd look is the unlabeled roses. But we can see the spacing is different (smaller) than the case with WESN labels.  The question is should it be even smaller.  I assume that is what you are wondering? I see the code computes the same initial offsets for either rose, but clearly there are things later that must add more.

Let me know if this is the concern before I did into this.

**Comment by seisman** [comment]
> The question is should it be even smaller. I assume that is what you are wondering?

Yes, exactly. The spacing in PR #6626 looks better.

**Comment by seisman** [comment]
Can we close the issue?

**Comment by PaulWessel** [comment]
Yes, done
