### ISSUE TITLE
Consistency between option and modifiers related to table or file

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6236]
**Description of the desired feature**

Some GMT options, like **-Aa**|**t**|**s** in **gmt info**, uses **t** for table, whereas option **-q** uses **+f** for file instead of **+t** for table.  This is inconsistent.  I can see we have been down this road before, e.g., parsing in gmt info -A says

`case 't': case 'f':	/* Keep f (file) for backwards compatibility, but "table" is used in all similar situations */`

but clearly table is not used in all similar situations.

I will need to find all the places where a|f|s or a|t|s are used and standardinze.  Clearly, the code will need to accept either t of f to be backwards compatible.  Because we use the word table everywhere to describe the input to table-reading modules, I think we should use t and +t even though we will process f and +f as well.  OK, @meghanrjones ?

**Comment by meghanrjones** [comment]
Sounds good.
