### ISSUE TITLE
Bug with dcw-collections local file. 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6241]
I am testing dcw-collections with my local file (located in `.gmt/`). I try some examples and it works fine.

The problem was when I wanted to use codes from the official list (located in `.gmt/geography/dcw/dcw-collections.txt`) that I are not included in my local file (like IHO33). If I delete my local file, then GMT finds the code in the official list and I get the map.

```
gmt coast -RIHO33 -W -B -png mapa
coast [WARNING]: No country code matching IHO33 (skipped)
coast [ERROR]: South is outside -90 to +90 degree range
coast [ERROR]: General map projection error
```

**Comment by PaulWessel** [comment]
Just to make sure: Your local file in .gmt is called dcw.conf, yes?

**Comment by Esteban82** [comment]
No, it wasn't. Now I don't have that problem. 

Now I have this issue. Is it suppose that in `dcw.conf` I should be able to redefine the lists and regions?

For example, I redefine the bounding box of South America (in `dcw.conf`), and when I make I still get the official region of SAM (not the one of `dcw.conf`).


```
gmt coast -RSAM -W -B -png mapa

tag: SAM South America
region: -81.3288/-34.7938/-55.9805/0.4645
```
