### ISSUE TITLE
gmtremote_parse_version is killing Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6243]
I started to have errors such this that even kill the Julia session.
```
julia> logo(D="x0/0+w2i")
gmtlogo [ERROR]: Unable to parse "98
" to extract GMT version
```
It calls gmtlogo and indeed if we run on CLI
```
gmt gmtlogo -Jx1 -Dx0/0+w2i
```
we see that it ends with
```
%%BeginObject PSL_Layer_4
0 setlinecap
0 setlinejoin
3.32550952342 setmiterlimit
PSL_nclip {PSL_cliprestore} repeat
%%EndObject
gmtlogo [ERROR]: Unable to parse "98
" to extract GMT version
```

**Comment by PaulWessel** [comment]
Fixed on server - you may need to delete the first rec in your gmt_data_server.txt file.  I will see why the updates did this on the server, @meghanrjones

**Comment by PaulWessel** [comment]
Strange.  In the PR we merged an hour or so ago (which caused) this, I had change the script that counts the datasets and inserts the count as the first record in gmt_data_server.txt.  All it does now is to just copy the file from the information folder to the data folder.  Yet, the file did indeed have a new first record (99) with the other count (98 - correct) following, thus messing up the parser.  All I can thing is somehow the update script got running before the git revision took places locally?  I searched and there is no wc in any of the scripts so I am puzzled.

**Comment by meghanrjones** [comment]
The wc is in the Makefile in the PR: https://github.com/GenericMappingTools/gmtserver-admin/pull/137/files

**Comment by PaulWessel** [comment]
yes, but that is only run manually when we build a new data set.  Not run by cron or anything.  The original in information has 98 as first record now, and the update would just copy that file as is to the data server top level. So not sure where the extra record came from except from the previous version of srv_do_update.sh.

**Comment by PaulWessel** [comment]
This is the line that now places that file:

`cp -f information/gmt_data_server.txt  ../data
`

**Comment by PaulWessel** [comment]
@joa-quim let me know the fix worked for you.

**Comment by joa-quim** [comment]
It seems fixed (no time to check more before dinner)

**Comment by PaulWessel** [comment]
I see your devotion to food has not abated in the new year.

**Comment by joa-quim** [comment]
You don't want me to start showing pictures of my privileged dinners.

**Comment by joa-quim** [comment]
But we need a better fix for this. One that handles the failure graciously and does not cause crashes downward.

**Comment by PaulWessel** [comment]
Well, the fix was implemented: No longer create these files by hand.  The snafu above was a one-time transition issue with the cron job running the old script somehow,  In the future there simply is no place where a manual error can enter as the entire contents of that file is created automatically.  So I don't think spending time on anticipating issues in that file is worth it.

**Comment by joa-quim** [comment]
I would agree if an error (whatever cause) in that file didn't have the capacity to kill Julia (and maybe Matlab too).

**Comment by PaulWessel** [comment]
I will see what I can do but I think the new process precludes errors.  There are lots of other things that can kill a process which is in the hands of a human.  This one is not (anymore).

**Comment by joa-quim** [comment]
It's still very different if something crashes GMT or if that crash can propagate into a calling environment and kill it too.

**Comment by PaulWessel** [comment]
Yes, I will see if I can fake the problem and engineer a gentle ending like "sorry, no data available - format incorrect, etc"

**Comment by PaulWessel** [comment]
So I added a wrong extra 1st line with 99 that is then followed by 98 and ran

```
gmt grdimage @earth_relief_01d -R0/30/0/30 -JM15c -B -png t 
gmt [ERROR]: Unable to parse "98" to extract GMT version
grdimage [ERROR]: Remote download is currently deactivated
grdimage [ERROR]: Unable to obtain remote file @earth_relief_01d
```

but no crash.  It used to crash because the number of files were set to 99 even though the pointer returned was NULL etc. Can you please make the temporary edit to gmt_server_data.txt and run your julia command? It should not crash anything - make sure you are on master and updated.

**Comment by joa-quim** [comment]
Yes, fixed. It doesn't crash anymore
```
julia> logo(D="x0/0+w2i")
gmtlogo [ERROR]: Unable to parse "98" to extract GMT version
```
