### ISSUE TITLE
Testing with OpenMP

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6248]
**Description of the desired feature**

I am not sure if we are catching any problems related to our OpenMP implementation. Because most times when I run tests (and probably the same in the CI?) I run the tests on as many cores as possible.  For this to work I have disabled OpenMP explicitly, or unless I use gcc the Xcode compiler does not support OpenMP. 

We should make sure at least one CI test run is done with OpenMP enabled and only running one test at the time (to avoid taxing the system).

**Comment by meghanrjones** [comment]
The Linux CI tests are run with OpenMP enabled, but with 4 jobs in parallel. Should this be reduced to 1?

**Comment by PaulWessel** [comment]
Maybe 2?
