### ISSUE TITLE
Here are new Dst and F10.7 index files for mgd77 magref

### ISSUE THREAD

**Issue by mtchandl** [GenericMappingTools/gmt#625]
Current Dst and F10.7 index files are only up to 2016 in the GitHub version of GMT. The svn version had somewhat more recent indices. I recommend replacing the older indices with these, provided that they work for you guys as well. 

The .txt extensions need to be removed. They go in share/mgd77. They allowed me to compute diurnal corrections for one recent simple test data set.

The new Dst file covers Jan 1 1957 until April 10 2019 (attached)
The new F10.7 file covers Feb 1947 until April 2018 (that's as far as it goes on the current download url ftp://ftp.ngdc.noaa.gov/STP/space-weather/solar-data/solar-features/solar-radio/noontime-flux/penticton/penticton_absolute/listings/listing_drao_noontime-flux-absolute_monthly.txt)

[Dst_all.wdc.txt](https://github.com/GenericMappingTools/gmt/files/3068142/Dst_all.wdc.txt)
[F107_mon.plt.txt](https://github.com/GenericMappingTools/gmt/files/3068144/F107_mon.plt.txt)

**Comment by PaulWessel** [comment]
Thanks @mtchandl, we have updated the repos.
