### ISSUE TITLE
-B in psrose does not annotate

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6251]
Is this expected given the ``psrose`` idiosyncrasies? For example the test ``rose_centered`` has ``-Bxa10g10 -K -Bya10g10`` but nikles annotations.

**Comment by PaulWessel** [comment]
Expected given no -B machinery usage.  See #6141 for proposed solution.

**Comment by joa-quim** [comment]
Ah, I remembered it but didn't remember where it was.
