### ISSUE TITLE
Regression in parsing YYYY-MM-DD

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6262]
**Description of the problem**

The following example worked in 6.3, but does not work in the master branch since https://github.com/GenericMappingTools/gmt/pull/6225.

```
gmt basemap -R2010-01-01/2014-01-01/0/5 -B -JX10c -png test
```

**Comment by PaulWessel** [comment]
OK, but from memory I thought we were strictly expecting ISO strings in -R whereas we can read a bunch of different things form data via the DATE and CLOCK settings.  So there should be trailing T's in those dates.

**Comment by meghanrjones** [comment]
From https://docs.generic-mapping-tools.org/dev/cookbook/options.html#data-domain-or-map-region-the-r-option, T is required is CLOCK is given. I think this implies that T is not required if DATE is given but without CLOCK.

I found this when looking at https://forum.generic-mapping-tools.org/t/plotting-vectors-on-a-datetime-axis/2536/2 and think that PyGMT's examples for datetime plots will fail due to this (e.g., https://www.pygmt.org/dev/tutorials/advanced/date_time_charts.html#sphx-glr-tutorials-advanced-date-time-charts-py).

**Comment by PaulWessel** [comment]
OK, will have a deeper dive.
