### ISSUE TITLE
Support cpt-city colormaps through a CPT collections mechanism

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#6295]
**Description of the desired feature**

Originally discussed at https://github.com/GenericMappingTools/gmt/issues/6284 and the GMT community meeting, this feature request is to support cpt-city hosted colormaps through a mechanism such as ``-Ccpt-city/grass/aspect`` for the [grass apsect  CPT](http://soliton.vm.bytemark.co.uk/pub/cpt-city/grass/tn/aspect.png.index.html) that would generate the appropriate url, download the CPT, and use it in the given GMT command.

**Comment by joa-quim** [comment]
Closing as not planed.
