### ISSUE TITLE
Should we reduce size of test dir?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#630]
The test dir is the largest of the directories under the gmt repository [118 Mb]. Apart form scripts and original _PostScript_ files, the files exceeding 100k bytes are

> -rw-------  1 pwessel  wessel  1233482 Aug 17  2018 ./mgd77/01010221.mgd77
> -rw-------  1 pwessel  wessel  846970 Aug 17  2018 ./psxy/file2.gmt
> -rw-------  1 pwessel  wessel  641036 Aug 17  2018 ./psxy/connections.dat
> -rw-------  1 pwessel  wessel  606922 Mar 18 13:13 ./gmtsimplify/GSHHS_h_Australia.txt
> -rw-------  1 pwessel  wessel  582644 Aug 17  2018 ./segy/wa1_mig13.segy
> -rw-------  1 pwessel  wessel  535473 Aug 17  2018 ./pscontour/ice.bm
> -rw-------  1 pwessel  wessel  432857 Aug 17  2018 ./pstext/test.grd
> -rw-------  1 pwessel  wessel  432857 Aug 17  2018 ./grdcontour/test.grd
> -rw-------  1 pwessel  wessel  426281 Aug 17  2018 ./x2sys/c2308.txt
> -rw-------  1 pwessel  wessel  363456 Mar 18 13:13 ./exmod/ex18
> -rw-------  1 pwessel  wessel  281371 Mar 18 13:13 ./kml/coast.kml
> -rw-------  1 pwessel  wessel  239098 Aug 17  2018 ./sph/lun2.txt
> -rw-------  1 pwessel  wessel  160971 Aug 17  2018 ./grdvector/nuvel1.vx.1.5.nc
> -rw-------  1 pwessel  wessel  141732 Mar 18 13:13 ./grdvector/wy_grd000.nc
> -rw-------  1 pwessel  wessel  139891 Mar 18 13:13 ./grdvector/wx_grd000.nc
> -rw-------  1 pwessel  wessel  121429 Aug 17  2018 ./grdmask/2k.dat
> -rw-------  1 pwessel  wessel  110407 Aug 17  2018 ./grdview/super2.nc

I wonder if we should place more of these files in cache and use the remote file mechanism so that only people like developers who run the tests will download these files as needed?

**Comment by leouieda** [comment]
That sounds like a good idea. It would be best to have a separate directory for the test data files than the tutorials data.

**Comment by PaulWessel** [comment]
Right now we only have two directories for remote files: server (for the earth_relief files) and cache (anything else, including tests, tutorial, man page examples).  If we were to separate things further then we would need to add more checks since it is no longer clear what directory some file like table_21.txt belongs to, unlike earth_relief_20m which we know is under server.  We could simplify that if we renamed all those test files to start with test_* and tutorials to be tutorial_* etc, and then we would know, but otherwise we would have to search 3-4 directories to see if we find the file already, and if we don't then we don't really know where to place that file since GMT does not know that an input file is a tutorial or test file unless we used a strict naming scheme.

**Comment by joa-quim** [comment]
I wouldn't like to have a dir with too many files, which is what we would go is all test files go to same place.
Also, storing them I Hawaii means we cannot change them (ideally, shrink them).

**Comment by PaulWessel** [comment]
I understand your first point, which would suggest needing prefixes like test_ and _tutorial and _example.  Not sure about your second point.  If you changed the files then the test would fail.  I am all for shrinking large files if the test still shows what it needs to show.

**Comment by joa-quim** [comment]
My second point is that all @name files are under your control only because only you has access to them in the SOEST server(s)

**Comment by PaulWessel** [comment]
True but we need a system where any of the developers could place files there I think.  Not sure how without account access.
