### ISSUE TITLE
triangulate -Qn kills Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6306]
It looks that the warning is true after all
```
julia> triangulate(rand(5,2), R="0/1/0/1", voronoi=:pol, Vd=1)
        triangulate  -R0/1/0/1 -Qn -M -JX14c/9.5c
triangulate [WARNING]: -Qn is experimental and unstable.
```
Will try to debug to debug it latter.

**Comment by joa-quim** [comment]
Found one, but not enough to fix all shits
```
/* Need temp array to hold the coordinates of a single polygon [I hope this is large enough - don't know yet] */
		xcoord = gmt_M_memory (GMT, NULL, n_int_edges/2, double);
		ycoord = gmt_M_memory (GMT, NULL, n_int_edges/2, double);
```
When the killing happened ``n_int_edges = 6`` but later down ``np = 5`` so ``x|ycoord`` overflowed. Fixing this by not dividing by 2, solved the kill. But then another one followed. The command just fall in an apparent infinite loop and I had to kill the process. In fact, sometimes it worked fine but most of them the hang happened. 
Can't debug this since each ``step`` takes > 20 secs.

**Comment by PaulWessel** [comment]
OK, please make a short CLI test case for me so I can debug when I can find some time (doing taxes today).

**Comment by joa-quim** [comment]
No CLI. It's from externals
```
triangulate(rand(5,2), R="0/1/0/1", voronoi=:pol, Vd=1)
```

Can we tax it?

**Comment by PaulWessel** [comment]
It is too taxing.

**Comment by PaulWessel** [comment]
Well, using rand(5,2) is not helpful since each time one starts up again we get a new data set, so the particular path through the mess in _gmtsupport_voronoi_shewchuk_ changes... Can you make this into a script that sets a fixed 5x2 data set that still uses the crash so it is repeatable exactly the same each time, please?

**Comment by joa-quim** [comment]
This one crashes on ``cmd`` as well
```
triangulate xy.dat  -R-1/2/-1/2 -Qn -M -JX14c/9.5c
```
where xy.dat is
0.972426499088	0.947716871068
0.755367493002	0.798499728751
0.730237556614	0.910008572993
0.833957090001	0.951488813143
0.827406268506	0.949740549484

The problem is with the sizes of ``x|ycoord`` in gmt_support.c #L3803 that are too short.

**Comment by PaulWessel** [comment]
Thanks.  It does not crash for me on macOS yet but it certainly has some memory issues:

```
gmt triangulate xy.dat  -R-1/2/-1/2 -Qn -M -JX14c/9.5c
triangulate [WARNING]: -Qn is experimental and unstable.
> +[?o?E??polygon # 0 -L0
0.804094770815	2
-1	0.899689771699
-1	0.859791844422
...
```

It should crash in Xcode with malloc guards on.  Weill see.

**Comment by joa-quim** [comment]
Ok, happened again. This hangs ``triangulate``

```
triangulate  -R0.24/0.9/0.1/1.02 -M -Qn -JX14c/9.5c xyz.dat
```
xyz.dat
0.243506244243	0.995890171317
0.595322486968	0.7295971967
0.317750354935	0.704934338506
0.650955120382	0.205213550767
0.892937833578	0.105767574981

**Comment by PaulWessel** [comment]
Thanks.  Note that this works

`gmt triangulate -R0/0.92/0/1 -JX14c -M -Qn xyz.dat`

while this hangs:

`gmt triangulate -R0/0.91/0/1 -JX14c -M -Qn xyz.dat`

It also works for -R0/1/0/1.  I will see if I can stomach some debugging of that case.

**Comment by PaulWessel** [comment]
It seems to have with handling the cropping of the voronoi data given a -R that leaves some key corners outside the -R.  Working on it but now driving to UH for meetings.
