### ISSUE TITLE
pslegend crashes when legend width is not provided.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6308]
See https://github.com/GenericMappingTools/GMT.jl/issues/827

In fact this woks
```
legend(region=(0,10,0,8), (symbol1=(dx_left=0.25, marker="-", size=0.33, pen=2, fill=:black, dx_right=0.75, text="1s delay time"), symbol2=(dx_left=0.25, marker=:star, size=0.5, pen=:false, fill=:yellow, dx_right=0.75, text="Epicentre")), position=(inside=:BL, anchor=:BL, width=5), box=(; pen=0.5), Vd=1, show=1)
        pslegend  -R0/10/0/8 -JX12c/0 -Baf -BWSen -F+p0.5 -DjBL+w5 -P -K > C:\TEMP\GMTjl_tmp.ps
```
but crashes if I remove the ``width=5``. On an attentive look ``pslegend's`` man page says ``width`` is mandatory but the code should check that because as is
```
if (Ctrl->D.dim[GMT_X] == 0.0) {	/* Compute legend width */
		legend_item = gmt_M_memory (GMT, NULL, n_records, struct PSLEGEND_TXT);	/* Array to hold all labels */
		do_width = true;
	}
```
but later the ``legend_item`` is accessed without checking.

Funny, with a  debug build the above working code errors with
```
legend(region=(0,10,0,8), (symbol1=(dx_left=0.25, marker="-", size=0.33, pen=2, fill=:black, dx_right=0.75, text="1s delay time"), symbol2=(dx_left=0.25, marker=:star, size=0.5, pen=:false, fill=:yellow, dx_right=0.75, text="Epicentre")), position=(inside=:BL, anchor=:BL, width=10), box=(; pen=0.5), Vd=1)
        pslegend  -R0/10/0/8 -JX12c/0 -Baf -BWSen -F+p0.5 -DjBL+w10 -P -K > C:\TEMP\GMTjl_tmp.ps
pslegend [ERROR]: Option -B parsing failure. Correct syntax:

...
pslegend [ERROR]: Offending option -BWSen
```

**Comment by PaulWessel** [comment]
The man page probably needs some fixing.  +w is optional in modern mode as we compute the exact width in PostScript.  It may possibly also work in classic - not sure.  It certainly happens when -l is used.

**Comment by joa-quim** [comment]
Then, it must be a externals issue because no +w ==> crash

**Comment by PaulWessel** [comment]
> but later the `legend_item` is accessed without checking.

I see that wherever legend_item is accessed it is inside a parenthesis with a check on do_width, which is set when legend_item is created.  So where is it accessed without checking?

**Comment by joa-quim** [comment]
Don't know where it should have been checked but the crash I got was because it accessed a ``legend_item == NULL`` pointer.

**Comment by PaulWessel** [comment]
I suppose if no legend items were read and

`		legend_item = gmt_M_memory (GMT, NULL, n_records, struct PSLEGEND_TXT);	/* Array to hold all labels */`

n_records is 0, then perhaps that could trigger an issue later on.  How did you pass the legend items?

**Comment by joa-quim** [comment]
```
legend(region=(0,10,0,8), (symbol1=(dx_left=0.25, marker="-", size=0.33, pen=2, fill=:black, dx_right=0.75, text="1s delay time"), symbol2=(dx_left=0.25, marker=:star, size=0.5, pen=:false, fill=:yellow, dx_right=0.75, text="Epicentre")), position=(inside=:BL, anchor=:BL), box=(; pen=0.5), Vd=1, show=1)
```

**Comment by PaulWessel** [comment]
OK, I should be able to run that soon.  Still doing some taxing and bank loan stuff today...

**Comment by joa-quim** [comment]
But don't update GMT.jl to master because it now catches the no-width and errors earlier.

**Comment by PaulWessel** [comment]
OK, can reproduce this.  n_records = 0. I see you have one segment but you never updated the n_records, probably simplest to use gmt_set_dataset_minmax.  Right now, your dataset passed in as is but its counters are off.
.

**Comment by PaulWessel** [comment]
This may be relevant to other parts of your wrapped code I suppose.

**Comment by PaulWessel** [comment]
Perhaps GMT should be less trusting of external data sets (or anything external, like GMT grids) and do a basic sanity check to see if things are set correctly?

**Comment by joa-quim** [comment]
Don't really following you on *you never updated the n_record* (?) but you know that no-one can be trusted in this bits business.

**Comment by PaulWessel** [comment]
Yes, I agree.  I think having some sanity checking is OK.  But I do not think GMT can run _gmt_set_dataset_minmax_ on the users externally passed-in memory since it would make changes.  So the way to do this is for GMT to report that the external container is flawed and print error messages.  This will presumably only be seen by external developers who then will fix their code.

Re you question: You may correctly have set n_rows for segment 1 in your input, but you did not update the dataset's n_records variable, which still is 0, and pslegend checks that to see how much to allocate, and you your case that is 0, hence the crash.

**Comment by joa-quim** [comment]
Ok, will have to find out why that is so. Though there should be nothing special in a ``legend`` call as at the end they all land in the same generic functions.
