### ISSUE TITLE
plot -Am/-Ap are flipped

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6309]
It appears that `plot -Am` plot by following the parallel first, then the meridian. `plot -Am` follows the parallel first, then the meridian. Should it not be the other way around? Based on https://docs.generic-mapping-tools.org/dev/plot.html#a; *Alternatively, add m to draw the line by first following a meridian, then a parallel. Or append p to start following a parallel, then a meridian.*

I see that the modules `plot3d`, `grdmask`, `clip` and  `grdtrack` also has this option, but have not checked them. `sample1d` seems to be correct.

```
cat<<eof > test.gmt
>
5.53962564298	71.272033721	1
6.30984353357	71.4308039355	2
7.34727069584	71.4156247566	3
7.9243956509	71.1059801628	4
5.08609083753	71.2631386067	5
5.53962564298	71.272033721	1
eof

gmt begin blocky-line
  gmt plot test.gmt -Ap -Wthicker,red -l"plot -Ap"+jTL
  gmt plot test.gmt -l"original"
  gmt sample1d -T10k -Ap test.gmt | gmt plot -l"sample1d -Ap" -Wblue
  gmt sample1d -T10k -Am test.gmt | gmt plot -l"sample1d -Am" -Wgray
  gmt plot -B0 -Sc0.4 -Ggreen -W test.gmt
  gmt text test.gmt
gmt end show

rm test.gmt gmt.history
```

**Comment by PaulWessel** [comment]
I think what happens here is that your first gmt plot command will run as a Cartesian plot since no -J or -fg tells it otherwise.  Then the 10k triggers knowledge of geographic data and this changes the mode from Cartesian to geographic.  If I stick in a -JM15c on the first command then it is all well.

**Comment by anbj** [comment]
So that's what is happening. Thanks Paul, and sorry for buggy bug reports. Closing.
