### ISSUE TITLE
Report remote file name for cache files in grid history attribute

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#6318]
**Description of the desired feature**

For `earth_relief` data, the history attribute keeps the `@earth_relief` format rather than the local file path. It would be useful if the history for cache files also used the `@remotefile` format rather than the local file path. For context, this would help for testing grid output without needing to resort to PS images.

Example for grdcut on `@earth_relief`:

```
gmt grdcut -R0/2/0/2 @earth_relief_01d -Gexample.nc
ncdump example.nc 
netcdf example {
...

// global attributes:
		:Conventions = "CF-1.7" ;
		:title = "Produced by grdcut" ;
		:history = "grdcut -R0/2/0/2 @earth_relief_01d_p -Gexample.nc" ;
...
```

Example for greenspline on `@Table_5_11.txt`:

```
gmt greenspline -R0/7.2/-0.2/7 -I0.05 -Gexample2.nc @Table_5_11.txt -Sl -Z1
ncdump example2.nc 
netcdf example2 {
...
// global attributes:
		:Conventions = "CF-1.7" ;
		:title = "Produced by greenspline" ;
		:history = "greenspline -R0/7.2/-0.2/7 -I0.05 -Gexample2.nc /Users/meghanj/.gmt/cache/Table_5_11.txt -Sl -Z1" ;
...
```

**Comment by PaulWessel** [comment]
Hm, I guess the question is when the command string is assembled - before or after expansion to a local file.
