### ISSUE TITLE
Potential issue with sphinterpolate

### ISSUE THREAD

**Issue by sabinz** [GenericMappingTools/gmt#634]
Hi team,

Hope you're all doing well! I have been using the latest GMT version that I'm compiling from GitHub on my mac OS. I have had mixed results with using the spherical interpolation tool. 

I am trying to apply a spherical interpolation to a global CSV of (paleo) elevations that are currently 1 degree resolution, with a -180/180/-90/90 region. I've made sure that the input CSV file is being reformatted appropriately, and have also checked what it looks like just using XYZ2GRD. 

I attach a self-contained zip file of the input, script, and output that I'm getting. I am pasting the message that I got from -V4, but there's no obvious issues. I've run this on the latest version of GMT in GitHub (recompiled today) on both mac Mojave and Ubuntu Bionic, with the same results. 

```
gmt sphinterpolate tmp.csv -Rd -I1d -fg -G${name}.nc -V4
```

I appreciate any help/suggestions you might have! Thanks for all the incredible work you guys are doing for the community, really appreciate it.

Regards,
Sabin Zahirovic

**Full error message**

```
sphinterpolate [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
sphinterpolate [DEBUG]: History: Process -Rd
sphinterpolate [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
sphinterpolate [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
sphinterpolate [DEBUG]: api_init_import: Passed family = Data Table and geometry = Point
sphinterpolate [DEBUG]: Object ID 0 : Registered Data Table File tmp.csv as an Input resource with geometry Point [n_objects = 1]
sphinterpolate (api_init_import): tried to free unallocated memory
sphinterpolate [DEBUG]: api_init_import: Added 1 new sources
sphinterpolate [DEBUG]: GMT_Init_IO: Returned first Input object ID = 0
sphinterpolate [DEBUG]: GMT_Begin_IO: Mode value 1 not considered (ignored)
sphinterpolate [DEBUG]: GMT_Begin_IO: Initialize record-by-record access for Input
sphinterpolate [DEBUG]: api_next_io_source: Selected object 0
sphinterpolate [INFORMATION]: Reading Data Table from file tmp.csv
sphinterpolate [DEBUG]: GMT_Begin_IO: Input resource access is now enabled [record-by-record]
sphinterpolate [DEBUG]: Source col types: (Number,Number,Number)
sphinterpolate [DEBUG]: ASCII source scanned: Numerical columns: 3, Trailing text: N, Record type: Numerical only
sphinterpolate [DEBUG]: GMT_End_IO: Input resource access is now disabled
sphinterpolate [INFORMATION]: Do spherical interpolation using 65160 points
sphinterpolate [DEBUG]: Geographic input grid, longitudes span exactly 360
sphinterpolate [DEBUG]: Grid is considered to have a 360-degree longitude range.
sphinterpolate [DEBUG]: Chosen boundary condition for all edges: geographic
sphinterpolate [DEBUG]: Geographic input grid, longitudes span exactly 360
sphinterpolate [DEBUG]: Object ID 1 : Registered Grid Memory Reference 7f8f7492def0 as an Input resource with geometry Surface [n_objects = 2]
sphinterpolate [DEBUG]: Successfully created a new Grid container
sphinterpolate [INFORMATION]: Evaluate output grid
sphinterpolate [INFORMATION]: Call STRIPACK TRMESH subroutine...sphinterpolate [INFORMATION]: OK
sphinterpolate [INFORMATION]: INTRC0: Number of evaluations = 65341, number of extrapolations = 0
sphinterpolate (gmt_ssrfpack_grid): tried to free unallocated memory
sphinterpolate [DEBUG]: Successfully added data array to previously registered Grid container
sphinterpolate [DEBUG]: Object ID 2 : Registered Grid File Map01_000Ma.nc as an Output resource with geometry Surface [n_objects = 3]
sphinterpolate [DEBUG]: api_begin_io: Output resource access is now enabled [container]
sphinterpolate [DEBUG]: api_export_grid: Passed ID = 2 and mode = 0
sphinterpolate [INFORMATION]: Writing grid to file Map01_000Ma.nc
sphinterpolate [WARNING]: Detected 277 inconsistent values at south pole. Values fixed by setting all to average row value.
sphinterpolate [WARNING]: Detected 230 inconsistent values at north pole. Values fixed by setting all to average row value.
sphinterpolate [WARNING]: Detected 93 inconsistent values along periodic east boundary of grid. Values fixed by duplicating west boundary.
sphinterpolate [DEBUG]: region: 0 0, grid: -180 180
sphinterpolate [DEBUG]: -> region: -180 180, grid: -180 180
sphinterpolate [DEBUG]: row: 0 180, col: 0 360
sphinterpolate [DEBUG]: netCDF Library version: 4
sphinterpolate [DEBUG]: packed z-range: [-9000,6000]
sphinterpolate [DEBUG]: GMT_End_IO: Output resource access is now disabled
sphinterpolate [INFORMATION]: Gridding completed
sphinterpolate [DEBUG]: gmtapi_garbage_collection: Destroying object: C=0 A=0 ID=1 W=Input F=Grid M=Memory Reference S=Unused P=7f8f7492def0 N=(null)
sphinterpolate [DEBUG]: GMTAPI_Garbage_Collection freed 1 memory objects
sphinterpolate [DEBUG]: gmtapi_unregister_io: Unregistering object no 0 [n_objects = 2]
sphinterpolate [DEBUG]: gmtapi_unregister_io: Unregistering object no 1 [n_objects = 1]
sphinterpolate [DEBUG]: gmtapi_unregister_io: Unregistering object no 2 [n_objects = 0]
sphinterpolate (gmtlib_free_tmp_arrays): tried to free unallocated memory
gmt [DEBUG]: Entering GMT_Destroy_Session
```

**System information**

* Operating system: mac OS Mojave
* Version of GMT: 
[Uploading Spherical_Interp_GMT6.zip…]()
Version 6.0.0_e43c4e6_2019.04.14 [64-bit] [8 cores]

**Comment by PaulWessel** [comment]
Hi @sabinz, I try to click on your zip but nothing happens and nothing is downloaded...

**Comment by sabinz** [comment]
Hi @PaulWessel,

Ah that's odd, perhaps I shouldn't upload directly to GitHub - the zip file was 16 Mb...

Here's the Dropbox link:
[https://www.dropbox.com/s/myq2dcxl7y8wq7e/Spherical_Interp_GMT6.zip?dl=0](url)

Thanks Paul! 

Cheers,
Sabin

**Comment by PaulWessel** [comment]
The dropbox link goes to https://github.com/GenericMappingTools/gmt/issues/url which does nothing it seems.  Not sure what is going on actually.

**Comment by sabinz** [comment]
Oh wow, sorry, I didn't realise sharing the example would create so much for you, so sorry Paul!

I think it's because I pasted the correct text, but the wrong URL, not sure how I managed that!

https://www.dropbox.com/s/myq2dcxl7y8wq7e/Spherical_Interp_GMT6.zip?dl=0

**Comment by PaulWessel** [comment]
Thanks that works.  Super-busy week so this may take a week... But looks like your input data (cvs.tmp) is points on every degree node so dont you just want to reformat? Are there missing nodes you want to interpolate into?  Sorry, did not make any plots so the answers may be obvious if I just plot the points with psxy.

**Comment by sabinz** [comment]
Hi Paul! Thanks so much for looking into it!

Yes, in this example there's a value at every 1 degree, but the anti-meridian and the polar regions are wrong as they were generated using a cartesian interpolation method. So I would strip out those regions, and re-interpolate using the spherical interpolator. But more broadly, we will have irregular XYZ files to which we will apply spherical interpolation. Hope that makes some sense...

And no rush, hope the rest of the week goes well for you! Thanks again!

**Comment by sabinz** [comment]
Also, even if I try to do 0.1d resolution, I still get similar artefacts using the spherical interpolation... So I don't think it's just an issue because my input and output resolution are the same in the example I uploaded. Not sure... I tried some of the -Q and -T options, but it was just hanging and not producing output after a number of hours (perhaps it might need even more time).  

![Screen Shot 2019-04-15 at 5 24 07 pm](https://user-images.githubusercontent.com/14987864/56114141-4eed6700-5fa3-11e9-97c6-b83ab8c47e86.png)

**Comment by PaulWessel** [comment]
Sorry the delay. Problem is as follows: sphiinterpolate has no defense against duplicates.  All your points along the N and S points are basically on the same point on the sphere, but sphinterpolate does not check that.  I tried greenspline and it will say things like

> greenspline [ERROR]: Data constraint 212 and 1 occupy the same location but differ in observation (-4120 vs -4080)
> greenspline [ERROR]: Data constraint 212 is identical to 2 and will be skipped
> greenspline [ERROR]: Data constraint 213 and 0 occupy the same location but differ in observation (-4160 vs 0)
> greenspline [ERROR]: Data constraint 213 and 1 occupy the same location but differ in observation (-4160 vs -4080)
> 

for hundreds of records.  If you replace the N and S nodes with a single node and a single value at each pole it works fine.  I used for testing 

gmt select -R-180/180/-89.5/89.5 -fg tmp.csv > t.txt
echo 180 90 -4280 >> t.txt
echo 180 -90 0 >> t.txt
gmt sphinterpolate t.txt -Rd -I1d -fg -Gt.nc -V
gmt grdimage t.nc -CETOPO.cpt -JQ0/20i -Baf > t.ps

and it looks fine.  I will see if we can replicate greenspline's checks in sphinterpolate; if not I will at least document the expectation of no duplicates.  That code is all old fortran translated to C so not possible to debug.

**Comment by PaulWessel** [comment]
I have now ported the checks from greenspline so that in your case you will get an error complaining about data with different observations at the same location.  You will need to fix that first before sphinterpolate will do its work.  This is PR # 683.

**Comment by sabinz** [comment]
Thanks so much Paul! I can now see why this was not the case with the seafloor age-grids, as we don't have isochrons perfectly following the edges of the map. Thanks for incorporating that error message, it will help me and other users in the future in identifying the issue. Thanks again!
