### ISSUE TITLE
Building docs fails

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6345]
Trying to build the docs:

bdocr
~/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild ~/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild
ninja: error: 'doc/scripts/images/GMT_RGBchart_a4.ps', needed by 'doc/rst/source/_images/images/GMT_RGBchart_a4.pdf', missing and no known rule to make it

Perhaps this is dvc related, @meghanrjones ?

**Comment by seisman** [comment]
Did you run `dvc pull` before building the docs?

**Comment by PaulWessel** [comment]
Maybe it matters when I do it.  I will start from a fresh build and try again.

**Comment by PaulWessel** [comment]
Thanks, works now - probably did dvc pull after running something that prevent success.  The only warning I get now has been there for some time:

```
[552/552] Building HTML documentation...
/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sphinx/builders/html/__init__.py:626: FutureWarning: The configuration setting "embed_images" will be removed in Docutils 1.2. Use "image_loading: link".
  self.docwriter.write(doctree, destination)
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/tutorial/session-2_jl.rst:373: WARNING: Could not lex literal_block as "bash". Highlighting skipped.
~/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev
```

but not an error so closing this with a ping to @joa-quim.
