### ISSUE TITLE
Add an informational message to grdimage and colorbar regarding Apple Preview

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6350]
**Description of the desired feature**

Lots of users are falling into the trap that they make a PDF map of a coarse image, or request a discrete color bar, and when viewing the result on macOS with Preview the image looks either blurry (coarse **grdimage** plots) or the CPT looks continuous (for discrete CPTs).  These are decisions Apple make in Preview and we cannot fight that.  However, here are some things we can do:

1. The **grdimage** man page could have a Note: paragraph where it explains that coarse images viewed in PDF may look blurry depending on your PDF viewer and OS - this is a known issue on macOS.
2. The **colorbar** man page could do the same. But, note that **colorbar -Np** would draw a discrete color bar using _rectangles_ which would not be subject to the Apple defect.  I suggest we make **-Np** for discrete colormaps the default.  This adds just a tiny amount of more PS (draw rectangle versus a tiny image) but will avoid the most common complaint for this problems (discrete color bars).

Let me know what @GenericMappingTools/core think about this.

**Comment by WalterHFSmith** [comment]
Good idea. -W

**Comment by meghanrjones** [comment]
Sounds good. I would add grdview to the list.

**Comment by joa-quim** [comment]
3. Since Apple screws, change the default format to PNG?

**Comment by leouieda** [comment]
👍🏽 sounds great! Adding some screenshots of the problem can help people notice that this is what they're suffering from.

**Comment by remkos** [comment]
This has been mentioned in Section 9.2 of the Cookbook for ages. I suspect from 10 years now. (I wrote it).

**Comment by PaulWessel** [comment]
Well, I looked and it is not that specific on this.  yes, it points out lots of issues with going form PostScript to PDF but this specific problem is not discussed.  Someone who reads Chapter 9 may figure it out but the casual user just placing a colorbar in modern mode and getting that blurry PDF will be confused.  So no harm done in adding the extra notes I think, and the key things was to default to plotting rectangles when it is possible in the color bar.
