### ISSUE TITLE
Use png rather than PS for docs examples and scripts

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6357]
**Description of the desired feature**

Currently, all the documentation examples and scripts produce PS images. This feature request is to modify the CMake files, gmtest.in, and the scripts to use PNG images rather than PS images. The benefits of this change will be faster tests due to less conversions required by GraphicsMagick, ability to preview the images on DAGsHub and GitHub issues/PRs, and easier review of test failures on macOS by avoiding preview nonsense with vector graphics (xref https://github.com/GenericMappingTools/gmt/issues/6350).

**Are you willing to help implement and maintain this feature?** Yes

**Comment by seisman** [comment]
My only concern is, different Ghostscript versions may produce slightly different PNG images from the same PS file.

**Comment by meghanrjones** [comment]
> My only concern is, different Ghostscript versions may produce slightly different PNG images from the same PS file.

How often has this been an issue for the PyGMT tests? I think we could base our decision on that, since they should be affected similarly by Ghostscript updates.

**Comment by seisman** [comment]
See https://github.com/GenericMappingTools/pygmt/pull/85 and https://github.com/GenericMappingTools/pygmt/issues/1270.

**Comment by meghanrjones** [comment]
OK, I will address #6356 first so that we have an option for Vercel and the bundle and then look into how much time this would save for building docs and running tests so that we can make a more informed decision.

**Comment by meghanrjones** [comment]
Closing this because IMO the benefits (faster tests) do not outweigh the costs (more maintenance related to GS updates)
