### ISSUE TITLE
gmt movie fails on windows 10

### ISSUE THREAD

**Issue by dinaroy** [GenericMappingTools/gmt#636]
doc\examples\anim04 fails on Windows 10

doc\examples\anim04

doc\examples\anim04>anim_04.bat

doc\examples\anim04>echo OFF
gmt movie main.bat -C7.2ix4.8ix100 -Nanim_04 -Tflight_path.txt -Sbpre.bat -Z -H2 -Lf+o0.1i -Mps -Fnone
movie [ERROR]: No frames specified! - exiting.
doc\examples\anim04>

And there is another problem temporary folder handler not released "anim_04"  so it cannot be deleted from the same cmd console

**Comment by PaulWessel** [comment]
Something else must be going wrong before then I think.  Is the flight_path.txt file properly created first?  The message says it found no frames but that file should have 178 records.  Maybe you can remove that echo off and explore what that file looks like?

**Comment by PaulWessel** [comment]
With no further comments I don't know what to do about this.

**Comment by joa-quim** [comment]
I converted the anim_04 example to a batch and can confirm the last point. For some mysterious reason 
```
C:\v\build12\doc\examples\anim04>rmdir /S /Q anim_04
The process cannot access the file because it is being used by another process.
```
Other than this the example run fine and I got the .gif, .mp4, .webm files

**Comment by PaulWessel** [comment]
I think per movie.c it should by this point **not** be inside anim04 when trying to delete it - that is the reason for the error.  But we do a cd .. earlier - why are we not in the parent directory?

**Comment by joa-quim** [comment]
I run it from cd .. It's trying to remove ``anim_04`` from within ``anim04``, which is perfectly legal. But the original error was
```
        1 file(s) moved.
        1 file(s) moved.
The process cannot access the file because it is being used by another process.
movie [ERROR]: Running cleanup script movie_cleanup.bat returned error 32 - exiting.
```

**Comment by joa-quim** [comment]
But the whole thing is more screwed. See this
```
C:\v\build12\doc\examples\anim04>gmt movie main.bat -C7.2ix4.8ix100 -Nanim_04 -Tflight_path.txt -Sbpre.bat -Z -H2 -Lf+o0.1i -Fmp4 -Fwebm -A+l+s10
movie [ERROR]: No frames specified! - exiting.

C:\v\build12\doc\examples\anim04>
C:\v\build12\doc\examples\anim04\anim_04>
```
It changed the directory by itself and this cmd window is now f... next shows what happens when I just hit "Enter"
```
C:\v\build12\doc\examples\anim04>
C:\v\build12\doc\examples\anim04\anim_04>
C:\v\build12\doc\examples\anim04>
C:\v\build12\doc\examples\anim04\anim_04>
C:\v\build12\doc\examples\anim04>
C:\v\build12\doc\examples\anim04\anim_04>
C:\v\build12\doc\examples\anim04>
```

**Comment by joa-quim** [comment]
More findings. The issue is that running the batch with "start /B" creates a new process, owner of the "anim_04" dir, that is not deleted at the end so removing that dir fails with the _it is being used by another process_ error. Furthermore, some more incomprehensible path shit goes on such that the  
```
movie main.bat -C7.2ix4.8ix100 -Nanim_04 -Tflight_path.txt -Sbpre.bat  ...
```
works only on a second call. First call just says
```
movie [ERROR]: No frames specified! - exiting.
```

Now, I found that I can fix all this by using "cmd /C /Q" but, f..., then it doesn't run in parallel mode.

**Comment by PaulWessel** [comment]
Very strange, Windows is.  Perhaps we just need to figure out what to do.  One option is to not delete that directory if the OS won't let us and instead print some message.  But you would think this is solvable maybe with a specail Window API function call?

**Comment by joa-quim** [comment]
There must be a bloody solution to this ... but right now it's escaping to me. The worst is not even the resistance to let delete at the end but rather that stupid thing that I need to run the movie command twice because the first it errors saying "no frames"

**Comment by PaulWessel** [comment]
Please read https://ss64.com/nt/start.html and see if the stuff about start/wait and start vs call gives any useful information.

**Comment by joa-quim** [comment]
Have that page opened as well and had some hope on title tip but makes no difference.

**Comment by PaulWessel** [comment]
We will continue to support DOS until @joa-quim dies or converts to OS X (in writing).
