### ISSUE TITLE
Missing documentation of +r/+R in -E for pscoast/coast

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6367]
I cannot find any documentation of the `+r`/`+R`(/`+e`?) modifiers when using `pscoast`/`coast` with `-E` in the docs;

* https://docs.generic-mapping-tools.org/dev/coast.html#e
* https://docs.generic-mapping-tools.org/dev/pscoast.html#e

```
gmt pscoast -ENO
-R4.650158/31.138197/57.966579/71.18811
```

```
gmt pscoast -ENO+r1
-R4/32/57/72
```

```
gmt pscoast -ENO+R1
-R3.650158/32.138197/56.966579/72.18811
```

**Comment by Esteban82** [comment]
I think that those modifiers are the same modifiers for -R. In case you wonder. 


> +r to adjust the region boundaries to be multiples of the steps indicated by inc, xinc/yinc, or winc/einc/sinc/ninc [default is no adjustment]. For example, -RFR+r1 will select the national bounding box of France rounded to nearest integer degree, where inc can be positive to expand the region or negative to shrink the region.
> 
> +R to adjust the region by adding the amounts specified by inc, xinc/yinc, or winc/einc/sinc/ninc [default is no extension], where inc can be positive to expand the region or negative to shrink the region.
> 
> +e to adjust the region boundaries to be multiples of the steps indicated by inc, xinc/yinc, or winc/einc/sinc/ninc, while ensuring that the bounding box is adjusted by at least 0.25 times the increment [default is no adjustment], where inc can be positive to expand the region or negative to shrink the regi

**Comment by anbj** [comment]
Thanks @Esteban82.

`+r`/`+R`/`+e` should be mentioned under `-E` in the docs as well and maybe refer to `-R`.

**Comment by Esteban82** [comment]
> `+r`/`+R`/`+e` should be mentioned under `-E` in the docs as well and maybe refer to `-R` for usage.

Yes, I agree.

**Comment by meghanrjones** [comment]
Thanks for reporting the missing documentation @anbj

**Comment by anbj** [comment]
Thanks!
