### ISSUE TITLE
epsg.txt not installed?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#637]
It seems `share/epsg.txt` is used `gmt_plot.c` but not copied to `share` directory during installation.

**Comment by PaulWessel** [comment]
Seems to be two issues:

1. It is not distributed to the build share during installation
2. It is not in any subdirectory (unlike all other configuration files)

Maybe create a proj subdirectory and place it there?

**Comment by joa-quim** [comment]
I have to revisit this. We’ll be relying on Proj4 v6 soon (GDAL 2.5 will support only this proj4 version) and it has the epsg codes in a database file (or something similar). Very likely we’ll need to look for the proj DATA env variable.

**Comment by seisman** [comment]
@joa-quim What about the share/epsg.txt? Do we need to delete it?

**Comment by joa-quim** [comment]
Yes, we can delete it now. All should taken care by GDAL only.
