### ISSUE TITLE
gmt which and downloading 03s and 01s earth relief files

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#639]
Issuing ``gmt which -Gc @earth_relief_03s`` does nothing. Deliberately? I could see a point in ignoring this. Doing a e.g. ``gmt which -Gc @earth_relief_01s`` could start a download of 41 GB of raster data.

**Comment by abanbj** [comment]
Also, if a file exists in the current folder, issuing a ``gmt which -Gc @earth_relief_nnn`` does not download to ``~/.gmt/server``. As stated in the last post in #432.

**Comment by PaulWessel** [comment]
Well, @earth_relief_03s is not a file but a collection of 14297 individual 1x1 degree tiles.  So for the 03s and 01s there will be no download automatically like for others.  As for your other case (**-Gc**), the programs usages says

> 	-G Download file if possible and not found locally.


Well, the file is found locally (in your current folder).

**Comment by seisman** [comment]
How to get the 1x1 degree tiles? I never see these files in the GMT server.

**Comment by PaulWessel** [comment]
Hidden away.  We will be setting up mirrors on all continents but only available from SOEST now.  Close to 50 Gb compressed but you can get a copy this summer at SIO.
