### ISSUE TITLE
Allow reading all data columns in mixed numeric/text datasets

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6411]
Currently we can't do it because everything after the first text detection is read as text. But if column order is shuffled such that all text columns go to the end then we could read all numbers as numbers.
And because many CSV files have a first row with column names, it would be desirable that the column order change is reported for example in a extra comment line. 

For true CSV files, as for example
```
Latitude,Longitude,Name,alt
48.1,0.25,First point,1.1
49.2,1.1,Second point,2.2
47.5,0.75,Third point,3.3
```
I could rebuild the dataset and assign it the correct column names or even turn them into attributes. This would allow some of the manipulations that otherwise have to be done with DataFrames packages.
 
```
julia> lixo = gmtread("lixo.csv", h=1)
3×2 GMTdataset{Float64, 2}:
 48.1  0.25
 49.2  1.1
 47.5  0.75

julia> lixo.text
3-element Vector{String}:
 "First point,1.1"
 "Second point,2.2"
 "Third point,3.3"

julia> lixo.comment
1-element Vector{String}:
 "Latitude,Longitude,Name,alt\r\n"
```

**Comment by PaulWessel** [comment]
You may recall all the troubles we had with stuff like this that lead to the decision to implement the trailing text scheme.  What are you expecting? That records line n1 n2 n3 t1 t2 n4 t3 is read and becomes [n1 n2 n3 n4] {t1 t2 t3}, i.e., all numerical collected in data, all string columns appended in trailing text? Or that we somehow remember the order of mixed input?

**Comment by joa-quim** [comment]
Yes I remember we had troubles and that those lead to current behavior that is also not ideal. Don't recall if what I'm proposing would bring back the old problems. If it does then forget this.
The rational is that there are out there many **true** CSV files with a first row made with the column names and the next records contain the data, that may have interspersed text columns like my example. What I'm proposing is if we detect that first line with text and the next with mixed numeric and text we would create a GMTdatset with
```
# Latitude,Longitude,Name,alt
# original column order = 0,1,3
48.1  0.25  1.1
49.2  1.1    2.2
47.5  0.75  3.3
```
 and a text part (like we do now) with
```
 "First point"
 "Second point"
 "Third point"
```
To not complicate this further with the multi word columns we would restrict this behavior to true CSV files, that is to those where the column separator is a comma.

The parsing of this behavior would be based on the analysis of only the 2 first rows in file.
