### ISSUE TITLE
x2sys: Improve documentation.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6412]
I was reading the docs of the different `x2sys` modules and in the cookbook. If someone reads the documentation, it seems to me that it is not very clear, unlike Paul's article (2010) where it is clearly explained how to use these modules. 

I think that we should include a text in the docs of the 10 modules saying something like "This module is a part of a suite of program 
which are used to detect, analyze and process intersecting tracks. See Wessel (2010) for a detailed description of them (and the scripts of x2sys in the repository ?)." 

BTW, in only page (`x2sys_cross`) there is a reference to Wessel (2010).

What do you think?

**Comment by PaulWessel** [comment]
Yes, that is a good idea.  Unfortunately, I did not pay $3k in 2010 to make it open access.  Since you are trying this out, please add any improvements to the docs that you find helpful.  I can review them.

**Comment by Esteban82** [comment]
Mm, If the paper is NOT open access, them maybe we should (ideally) add a more detailed description in the docs. It is not legal to copy the main description of the paper in the docs, right? And to add a pre-print version of the paper?

**Comment by PaulWessel** [comment]
I could possible create a derived product that is different from the paper and more technical in nature.

**Comment by Esteban82** [comment]
That would be better.

**Comment by PaulWessel** [comment]
I will try to find time tonight to chop up some pieces of that paper.  Seems lots of the technical and equation for solving can go in x2sys_solve man page, while more of the intro and philosophy can go into x2sys_init . I think that is how it was in the ancient X-SYSTEM (precursor to x2sys in GMT3/4).
