### ISSUE TITLE
Let -Ra and -Re for gmt surface

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6417]
I think that would good to have the options `-Ra` and `-Re` for the `gmt surface` module. 
And maybe we could set `-Ra` as the default value (this would make `-R` argument optional).

**Comment by Esteban82** [comment]
Sorry. I think `-Re` (exact) should be the default option.

**Comment by PaulWessel** [comment]
Not sure about this.  It is important that users know what **-R** will work.  See -W for information.  The machinery for setting **-Re -Ra** will not give regions that are conducive to a good result.  The **-Q** machinery is smarter and can find useful **-R** but these tend to be larger than what the user wants, and hence they need to **grdcut** later.

The only automatic scheme I can imagine being useful would be if the user's **-R** (or none) is worse in terms of performance than the best one in **-Q** and then we use the **-Q** region to compute but use the user's **-R** (or exact region if none given) when writing the grid.

Pinging @WalterHFSmith as I am sure he may have an opinion on this.

**Comment by Esteban82** [comment]
I agree that it is important to know -R (and -I). My issue is mainly to make a fast grid (like a preview) with a one-line code. So maybe I don't have any problem with a larger region given by -Q.

**Comment by joa-quim** [comment]
Close?
