### ISSUE TITLE
sample1d: use increments when creating sampled geometry

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6424]
Case: assume that a crude vector line/geometry has been created.
By requirement, this geometry needs to be in multiples of steps of `xinc/yinc`.

This would be a nice feature to have in e.g. **sample1d**.

This is analogue to the `gmt pscoast -E+rxinc/yinc` option.

E.g.:

Rough outline created and used in the *here document*:

```
gmt sample1d -T20k -Ap <<eof > inc.gmt
6.84647681635633 62.9272544724352
5.14439576487769 61.8845381526104
4.91438481197517 60.4584702446148
5.34373859072654 58.955732018985
6.64713399050748 58.127692588536
9.37659729828404 59.0784045271997
9.00857977364001 60.7306498722161
6.84653671504198 62.927284421778
eof
```

An excerpt from the resulting file is this:

```
9.03541438481	59.0784045272
9.37659729828	59.0784045272
9.37659729828	59.2619873433
9.37659729828	59.4455701594
9.37659729828	59.6291529755
9.37659729828	59.8127357917
9.37659729828	59.9963186078
```

By having the given feature, I could apply an option (or modifier), e.g. `-Ixinc/yinc` -> `-I0.1/0.25`, and get:

```
9.0	59.0
9.4	59.0
9.4	59.25
9.4	59.50
9.4	59.75
9.4	59.75
9.4	60.0
```

**Comment by PaulWessel** [comment]
I see what you would like.  I am not sure though if we need a GMT option to do this, e.g.

`gmt math inc.gmt -C0 0.1 DIV RINT 0.1 MUL -C1 0.25 DIV RINT 0.25 MUL -Ca = | uniq | gmt plot -W1p
`

works pretty well?

**Comment by anbj** [comment]
Olala, that's quite a mouthful. But sure, it works well!

**Comment by anbj** [comment]
Now off to study the math manpage...

**Comment by PaulWessel** [comment]
Well, you can see why I hesitate to spend time adding this as an option, which could apply to many types of data and hence might have to go into **gmt convert** or **spatial**. But if so, it is basically having to do basic math and then check if the next modified record differs from the previous output record (i.e, _uniq_). Now, if you had a 3rd (or more) columns with data, then what? Ignore that those identical x,y records have different z values?  So the complications escalate... Meanwhile, the **gmt math** command has done its work.

**Comment by anbj** [comment]
Yes, I see.

Your comment and `grd math` command is an even better way to do this, than implementing the suggested feature.

Thanks for considering!
