### ISSUE TITLE
Add datum RGF93

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#6435]
Hi there,

The RGF93 is the "official" datum used by the French administration, would it be possible to add it in `PROJ_ELLIPSOID` ?

From what I've read, it is compatible with WGS84 down to meter-scale. From what I understand, it will be detrimental to some HRES GPS data movements I'd like to process if I were to use WGS84 instead of RGF93. 

Best,
Guillaume

**Comment by gd-a** [comment]
... Well, I just tried to play with plot, and to be honest I can't really see any difference between WGS84 and GRS-80 ... 
Feel free to close / discard if there's no point in implementing this datum

**Comment by joa-quim** [comment]
Those ellipsoids differ only in some millimeters.

**Comment by gd-a** [comment]
Hm that's why... As I'm providing the same origin through `-JB` I have no chance to see any difference on the plot... Thanks

**Comment by meghanrjones** [comment]
Given the small differences, do you still want to keep this feature request open @gd-a?

**Comment by gd-a** [comment]
Is it worth it to implement it? (I've no idea of how much time it takes).
Feel free to close the thread if it is not.

**Comment by joa-quim** [comment]
In fact there is nothing to implement here. GRS80 andWGS84 ellipsoids are virtually equally.
