### ISSUE TITLE
Custom Symbol: $t, $x & $y no longer work in 6.0.0_d85bd4f_2019.04.16

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#644]
**Description of the problem**

After just updating my GMT 6 installation I'm no longer able to use the symbol variable `$t`.  `$x` & `$y` seem not to work as well. Maybe I'm doing something really stupid but after much head scratching I suspect GMT to be the culprit.

I narrowed the script down to the test script below. I expect to get a plot with a red dot and a black letter "A" in the lower left corner. Instead I get an error message an nothing on the plot. If I comment out the last line in the symbol definition I get a red dot as expected. 

**Full script that generated the error**

```
#!/bin/bash

FILE=test_var_error.ps

cat > placing.d << END
-4 -4  A
END

cat > symbol_error.def << END
N: 1 s

0 0 0.25    c -W- -Gred
0 0 0.7  $t l -W- -Gblack
END


psxy \
	-R-5/-5/5/5r \
	-JM0/0/15c \
	placing.d \
	-Sksymbol_error/1c \
	-B30mg30m -BWSne \
	> $FILE
```

**Full error message**

```
./test_var_error.sh
psxy [DEBUG]: Obtained the ppid from parent: 4094
psxy [DEBUG]: Enter: gmtinit_new_GMT_ctrl
psxy [DEBUG]: GMT->session.SHAREDIR = /usr/local/share
psxy [DEBUG]: GMT->session.HOMEDIR = /home/kristof
psxy [DEBUG]: GMT->session.USERDIR = /home/kristof/.gmt [created]
psxy [DEBUG]: GMT->session.CACHEDIR = /home/kristof/.gmt/cache [created]
psxy [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
psxy [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
psxy [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /home/kristof/.gmt
psxy [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /home/kristof/.gmt/postscriptlight
psxy [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/share/postscriptlight
psxy [DEBUG]: Map distance calculation will be Cartesian
psxy [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
psxy [DEBUG]: Enter: New_PSL_Ctrl
psxy [DEBUG]: Exit:  New_PSL_Ctrl
psxy [DEBUG]: Enter: gmt_manage_workflow
psxy [DEBUG]: Exit : gmt_manage_workflow
psxy [DEBUG]: Enter: PSL_beginsession
psxy [DEBUG]: Exit : PSL_beginsession
psxy [DEBUG]: Enter: PSL_setdefaults
psxy [DEBUG]: Exit : PSL_setdefaults
psxy [DEBUG]: Enter: gmtlib_io_init
psxy [DEBUG]: Exit : gmtlib_io_init
psxy [DEBUG]: Enter: gmt_hash_init
psxy [DEBUG]: Exit:  gmt_hash_init
psxy [DEBUG]: Enter: gmt_hash_init
psxy [DEBUG]: Exit:  gmt_hash_init
psxy [DEBUG]: The PROJ_GEODESIC set to Vincenty
psxy [DEBUG]: Enter: gmt_getdefaults
psxy [DEBUG]: Exit:  gmt_getdefaults
psxy [DEBUG]: Enter: gmtlib_plot_C_format
psxy [DEBUG]: Exit:  gmtlib_plot_C_format
psxy [DEBUG]: Enter: gmtinit_get_history
psxy [DEBUG]: Enter: gmt_hash_init
psxy [DEBUG]: Exit:  gmt_hash_init
psxy [DEBUG]: Exit:  gmtinit_get_history
psxy [DEBUG]: Initialize FFTW with 4 threads.
psxy [DEBUG]: GMT_Create_Session initialized GMT structure
psxy [DEBUG]: Shared Library # 0 (core). Path = libgmt.so
psxy [DEBUG]: Loading core GMT shared library: libgmt.so
psxy [DEBUG]: Loading GMT plugins from: /usr/local/lib/gmt/plugins
psxy [DEBUG]: Shared Library # 1 (supplements). Path = /usr/local/lib/gmt/plugins/supplements.so
psxy [DEBUG]: History: Process -R-5/-5/5/5r
psxy [DEBUG]: History: Process -JM0/0/15c
psxy [DEBUG]: History: Process -B30mg30m
psxy [DEBUG]: History: Process -BWSne
psxy [DEBUG]: parse_B_arg_inspector: GMT4 = 0 vs. GMT = 0
psxy [DEBUG]: parse_B_arg_inspector: Assume new GMT style format in -B option
psxy [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
psxy [DEBUG]: GMT: 0. Will try to find subdir=custom stem = symbol_error suffix=.def
psxy [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
psxy [DEBUG]: Found custom symbol symbol_error.def
psxy [DEBUG]: Code c Conditional = 0 OP = psxy [ERROR]: Failed to parse symbol commands in file symbol_error.def
psxy [ERROR]: Offending line: 0 0 0.7   l -W- -Gblack
```

**System information**

* Operating system: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0 x86_64)
* Version of GMT: 6.0.0_d85bd4f_2019.04.16 [64-bit] [MP] [4 cores]

**Comment by PaulWessel** [comment]
Sorry, no idea why that part would suddenly fail.  We merged that in long time ago.  Will have to look next wee as we are having a faculty retreat this weekend to work...

**Comment by KristofKoch** [comment]
Hi @PaulWessel, 

I can't say when (as in which version) it started to fail. I was testing for ways to fail your implementation of my feature request in the old tracker ([Custom symbols: Make all input columns available inside the symbol for conditional testing](http://gmt.soest.hawaii.edu/issues/1256)) and was surprised it didn't work anymore. 

Have a nice weekend!

**Comment by PaulWessel** [comment]
Hi @KristofKoch looks like you forgot to espace your dollar signs in the symbol code.  When you create def files on the fly in a script you must use

`0 0 0.7  \$t l -W- -Gblack
`

otherwise the $t is seen as a blank variable and you end up with

`0 0 0.7  l -W- -Gblack
`

hence the error since you are missing a field.

**Comment by KristofKoch** [comment]
Hi @PaulWessel,

I have no access to my GMT6 box right now but it strongly smells like a severe case of PEBKAC on my side. Thank you for pointing it out an my apologies for wasting your time. 

All the best,
Kristof

**Comment by PaulWessel** [comment]
No worries.  Since I did the google I might as well post what PEBKAC is; see https://en.wikipedia.org/wiki/User_error#PEBKAC.
