### ISSUE TITLE
Settle on a single value for Newton's constant

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6442]
This is a minor issue (~0.1%) but nevertheless: There are several places in GMT's potential supplement where Newton's gravitational constant is used. However, they tend to use different values (I am skipping the exponent since those magnitudes may change depending on m or km etc):

- gravff, grdgravmag3d, gmtgravmag3d: 6.667
- talwani2d, talwani3d: 6.673
- gravprism: 6.674
- 

Per [Wikipedia](https://en.wikipedia.org/wiki/Gravitational_constant), the value as of 2019 is 6.67430 x ....

I suggest we place this constant in a separate include file inside the supplement so that all the modules can use the same value and also only have one place for it. WOuld that be OK with @joa-quim ? We can have different exponents or use 1.e-? as needed?

**Comment by joa-quim** [comment]
``grdgravmag3d`` has
```
Ctrl->C.rho = atof(opt->arg) * 6.674e-6;
```

**Comment by gd-a** [comment]
> But instead of a new file, why not just making it's value equal in all code files? That's not something we expect to change anytime soon. 

But, it's always good practice to declare variables independently right? 😃

**Comment by PaulWessel** [comment]
You'd be surprised at how poorly known G is and thus it is entirely reasonable to expect that in a few years the number will change again.  So I think it is good to place it in a file that the potential supplement modules needing it can include.

**Comment by joa-quim** [comment]
I know *G* is the less well know of all physical constants. Anyway, I think we are talking on differences that would only manifest on solar or even galactic scales.

**Comment by joa-quim** [comment]
OK, as long as changes will not be big enough to force a new GMT release.
