### ISSUE TITLE
Let psimage use original figure size.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6468]
I noticed that for `psimage` it is mandatory to indicate the output size of the image.

`image [ERROR]: Option -D: Must specify image width (+w) or dpi (+r)`

For some options, like my last question on the [forum](https://forum.generic-mapping-tools.org/t/how-to-add-text-in-animation-12/2728/2) or for example to changing the bands it is not necessary. 

`gmt image @needle.jpg+b2,1,0 -Dx0/0+w7c -pdf plot`

So, I proposed that:
1. Should be an option to keep the original figure size (in dpi or width).
2. Maybe (just maybe) we could set the original size as a default parameter and make the width/dpi optional.

**Comment by PaulWessel** [comment]
We may know the dimension of the image but now much more. So we either need a size or a dpi.  We could default to **GMT_GRAPHICS_DPU** (300i) of course.  That seems like the only automatic thing we could do.

**Comment by Esteban82** [comment]
Yes, I was using 300 dpi.

**Comment by joa-quim** [comment]
But we cannot know the image size **and** its dpi without reading the image first, and we don't have a tool to do that (like _imfinfo_ in Matlab.)

**Comment by PaulWessel** [comment]
Well, we know the image size after reading it. If we then set a dpi we are good to go.  All this does is to have a default dpi.

**Comment by PaulWessel** [comment]
And lots of images do not have a default dpi listed in them.

**Comment by joa-quim** [comment]
Either that or the most common is not 300. That's why I fear this will cause bad surprises.

**Comment by Esteban82** [comment]
Could we use the numbers of pixels?
