### ISSUE TITLE
Standard Postscript fonts

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#647]
https://github.com/GenericMappingTools/gmt/blob/a0545a1cc860e2ebd9054ec89a89d569f4686a85/src/standard_adobe_fonts.h#L36-L40

The last four fonts are Japanese fonts. Are they "standard" postscript fonts? If not, shall we remove these four fonts from the list?

**Comment by PaulWessel** [comment]
Maybe @joa-quim will remember better but I think these are pretty standard if you are in Japan.  They have been in GMT forever so removing them may cause hardship without any particular benefit to us.

**Comment by joa-quim** [comment]
Nope, I have no recall of this issue.
