### ISSUE TITLE
Allow use of GMT_GRAPHICS_FORMAT for one-liners

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/gmt#6508]
**Description of the desired feature**

It would be useful to have a way to specify that the output from a modern mode one-liner should be set by GMT_GRAPHICS_FORMAT. For example

```
gmt basemap -R2000/2020/35/45 -JX12c -Bxa2f+a-30 -BS --GMT_THEME=cookbook -format GMT_-B_slanted
```

would set the format based on GMT_GRAPHICS_FORMAT. My motivation for this feature request is to help the GMT docs so that the output could be set as PS for our testing purposes but users would get PDF when copying the example code. In addition, this could be useful for anyone who wants to run a suite of one-liners to produce different output formats.

Are you willing to help implement and maintain this feature? Yes

**Comment by PaulWessel** [comment]
I guess it is just picking a -name option that we replace under the hood with the default format.

some possibilities:

format
default or def
plot
name
figure
map
output or out
picture
view

I like the shorter ones
