### ISSUE TITLE
Clarify the parameters that controls the labels of map directional rose

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6511]
In the [`basemap -T` documentation](https://docs.generic-mapping-tools.org/dev/basemap.html#t), it's unclear which parameter can control the font/size of the rose labels.

**Comment by PaulWessel** [comment]
Perhaps add a cross linke to the cookbook section on map embellishments for [roses](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#placing-magnetic-map-roses)?

**Comment by seisman** [comment]
> Perhaps add a cross linke to the cookbook section on map embellishments for [roses](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#placing-magnetic-map-roses)?

Sounds good.
