### ISSUE TITLE
Annoying stale bot

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#652]
The stale bot is really annoying to me, and almost helpless. What do you think about it?

Can we disable the stale bot, or maybe change the settings:

1. increase the `daysUntilStale` to 60, as we usually cannot fix some issues in 30 days.
2. add `bug` to  `exemptLabels`, so bug reports won't be closed unexpectedly

**Comment by joa-quim** [comment]
I would say, add at least ``bug, enhancement, Feature request``.

**Comment by PaulWessel** [comment]
I would say 90 days until staleness, and I agree we dont really want to close bugs until we at least determine what to do about it.

**Comment by meghanrjones** [comment]
Do we always open the issues after stale bot closes them? If so, could we change `daysUntilClose` to something much longer than 7 so that the close/open cycle does not happen so often?

**Comment by seisman** [comment]
> Do we always open the issues after stale bot closes them?

I think most PRs/issues should not be closed. Perhaps we should just remove the stale bot?

**Comment by meghanrjones** [comment]
> > Do we always open the issues after stale bot closes them?
> 
> I think most PRs/issues should not be closed. Perhaps we should just remove the stale bot?

Would be fine with me.
