### ISSUE TITLE
Legend strips off everything after comma

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6534]
Not devastating, but still:

Everything after the comma is stripped away
```
$ echo 5 5 | gmt plot -Sc0.2c -Gblack -R0/10/0/10 -B -pdf test -l"5,5 Point"
```

**Comment by PaulWessel** [comment]
So this falls into the category of unintended consequences.  If you read the **-l** documentation, at the end it says

> Alternatively, give a list of comma-separated labels, or give no label if your segment headers contain label settings.

So your argument is seen as a comma-separated list of labels and it picks the first one here.  Possible ways around this is

- Use octal code for the comma that should be part of the label (\054).
- We could implement an escape, e.g., -l"5\\,5 Point" and check for \ and remove them

In either case the documentation should be updated to point out this case and offer this solution.

**Comment by PaulWessel** [comment]
I have updated master with a note at the end of the legend documentation to address this.  I note we have a similar situation in **-B** where titles with "+ characters gets confused with modifiers and hence we tell users to use octal \\053 for the plus.

**Comment by anbj** [comment]
Looks good Paul.

"A list of comma-separated labels"; could you explain this?

**Comment by PaulWessel** [comment]
It is in the context of multiple segments and you want each line from each segment to get their own label.

**Comment by anbj** [comment]
Got it, thanks.

Do the docs mention where one may look up octal codes? Or are users expect to find this themselves?

**Comment by PaulWessel** [comment]
Well, it is one of the top links on the doc page (Octal Codes).  We could always improve matters by adding crosslinks to those sites when that occurs, but in this case I do give the octal code for the only character you need.

**Comment by anbj** [comment]
Thanks.
