### ISSUE TITLE
Making grids: create flow chart to help users

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6541]
GMT provides several ways of gridding data;

* `triangulate`
* `nearneighbor`
* `greenspline`(?)
* `sphinterpolate`(?)
* `surface`
* more?

What about adding a section (where appropriate) and figure/flow chart in the docs that help users to choose the right algorithm for their data?

I'm happy to help with this (when time permits..), but I would need some help and input.
Many of the aforementioned utilities are new to me, and I don't have the necessary *fingerspitzengefühl*.

**Comment by PaulWessel** [comment]
It is a good idea and has been considered before.  I may have some background stuff for this in the interpolation section in my course notes/book, but not looking forward to the latex to rst translation.  Well, not to bad.

**Comment by anbj** [comment]
Very interesting. You write book; are you referring to ‘Introduction to statistics & data analysis’?

**Comment by PaulWessel** [comment]
No, something not published.

**Comment by anbj** [comment]
Sounds like a hidden gem.

**Comment by anbj** [comment]
Some thoughts that I have (or, questions really)

* sparse vs. dense data
* geo vs. cartesian (does this matter? One may go from one to the other)
* speed..?

**Comment by PaulWessel** [comment]
There is also data size.  If less than ~10k data points (computer memory dependent) you can get an exact solution with greenspline whereas with surface you will get an approximate one since it never will fully converge.  But surface can handle gazillion points.
There is issues such as global geo (spherical earth matters) vs local small area (no wrapping over poles to worry about)

**Comment by anbj** [comment]
Waiting for PW's course notes/book..?

**Comment by PaulWessel** [comment]
FYI, both my text books will soon be available from my department as a community resource for teaching. DA1 book will be a public git repo and a private one for the answers to problem so instructors can get that via us.  DA2 book may need to stay private until we prune out some copyrighted sections I think.  But it will get there.

**Comment by anbj** [comment]
That's very good news! Waiting (and hoping) to be able to get my hands on them.

**Comment by anbj** [comment]
If you're OK with that, I would be very grateful.
My email is panden at gmail dot com.
