### ISSUE TITLE
Delete or update prog_use.sh

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#655]
**Description of the problem**

This script https://github.com/GenericMappingTools/gmt/blob/master/prog_use.sh no longer works. Is it still needed? Can we delete it? If it's still useful, we need rewrite it to make it work and maybe move it to other directories (i.e. `test`).

**Comment by PaulWessel** [comment]
No need.  I just placed i in the sandbox repo instead and removed it from master directly.  It should never have been in this repo anyway.
