### ISSUE TITLE
Trying to plot decorated lines with arrows crashes Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6551]
I first thought it was because no angle and length columns in input data, but no. It's more *fundamental*

This KaBooms Julia
```
julia> plot([0.0 0 20 1; 0.4 0.6 20 1; 1 1 20 1], S="~d2c:+sv0.3", show=1, Vd=1)
        psxy  -JX14c/9.5c -Baf -BWSen -R-0.04/1.04/-0.04/1.04 -S~d2c:+sv0.3 -P -K > C:\TEMP\GMTjl_tmp.ps
```
So, we can't make decorated lines with arrows.

**Comment by PaulWessel** [comment]
Yes, but we should document what can and cannot be done, and give errors etc when required.  I will have a look.

**Comment by PaulWessel** [comment]
I think only the regular geometric symbols plus kustom symbol are allowed.
vectors, bars, fronts are not.  I suspect any 2-parameter selections are also problematic (ellipse, wedges, rectangles)
And of course decorated lines and quoted lines are out as well.

**Comment by joa-quim** [comment]
It crashes because ``gmt_plot#7692`` calls

```
gmtplot_flush_symbol_piece (GMT, PSL, xx, yy, &n, &p, &f, this_outline, &flush);
```
but ``xx`` and ``yy`` were never allocated,

**Comment by PaulWessel** [comment]
Yes, because there is no checks anywhere for what symbols are allowed - just assumptions.
I will put on the brakes.

**Comment by joa-quim** [comment]
But what's the point of having a ``case PSL_VECTOR:`` if it will **always** crash because ``xx,yy`` are not defined?

**Comment by joa-quim** [comment]
Sorry, in ``gmt_draw_custom_symbol()`` every time I see a call

```
gmtplot_flush_symbol_piece (GMT, PSL, xx, yy, &n, &p, &f, this_outline, &flush);
```
``xx,yy`` have not been defined yet (they are still NULL)

**Comment by PaulWessel** [comment]
I see no crashes in any of the custom symbol stuff across GMT.  I think it is irrelevant and soon you will not get in there in that condition.

BTW, docs for decorated symbols at least say this:

`Custom symbols need to be simple, i.e., not require data columns`

**Comment by joa-quim** [comment]
OK, may of those calls are prefixed with ``if (flush)`` and I don't know what happens to ``flush`` become true, but look at line 7692. How can it ever work if, again, ``xx,yy`` are not defined?

**Comment by PaulWessel** [comment]
As I say, if you can find a crashing case with a valid custom symbol then I will have a look.  But the reason you are seeing NULL is that the gatekeeper was looking elsewhere when you snuck in your vector.

**Comment by joa-quim** [comment]
Sorry, but I'll insist. Can you show me a code flow where it arrives at line 7692 and xx,yy have been allocated and assigned? All have to happen inside ``gmt_draw_custom_symbol()`` because those two variables are local to that function.

In fact reading and rereading the code of that function I only spot three places were xx,yy are allocated/assigned.
```
			case GMT_SYMBOL_MOVE:	/* Flush existing polygon and start a new path */
				if (flush) gmtplot_flush_symbol_piece (GMT, PSL, xx, yy, &n, &p, &f, this_outline, &flush);
				n = 0;
				if (n >= n_alloc) gmt_M_malloc2 (GMT, xx, yy, n, &n_alloc, double);
				xx[n] = x, yy[n] = y, n++;
```

```
			case GMT_SYMBOL_DRAW:	/* Append another point to the path */
				flush = true;
				if (n >= n_alloc) gmt_M_malloc2 (GMT, xx, yy, n, &n_alloc, double);
				xx[n] = x, yy[n] = y, n++;
```
and
```
			case GMT_SYMBOL_ARC:	/* Append a circular arc to the path */
...
				for (i = 0; i < na; i++) {
					if (n >= n_alloc) gmt_M_malloc2 (GMT, xx, yy, n, &n_alloc, double);
					xx[n] = xp[i], yy[n] = yp[i], n++;
```

**Comment by PaulWessel** [comment]
I am not sure I understand.  _xx_ and _yy_ are only used for lines.  Otherwise, nothing is allocated and n is 0. _gmtplot_flush_symbol_piece_ is called with NULL and 0 and nothing happen to them.  I.e., this is only relevant for custom symbols where we have

0 0 M
0.1 0.3 D
0.2 -05 D
etc.

or arc.

**Comment by PaulWessel** [comment]
If it makes you sleep better we can always start off this way:

*flush = false;
if (*n == 0) return;

/* Now do stuff that matters */
..
*n = 0;
