### ISSUE TITLE
When the coordinate is a character string, not a number, the internal storage memory used by gmt6 increases without end ON MAC

### ISSUE THREAD

**Issue by wangliang1989** [GenericMappingTools/gmt#656]
When the coordinate is a character string, not a number, the internal storage memory used by gmt6 increases without end ON MAC.

**Full script that generated the error**

```
#!/bin/bash

gmt begin
gmt figure draw_example_b png A1c
gmt coast -JH30c -Rg -BSWen -Bxaf -Byaf -Bag -Dl -A250 -Ggrey -Scornsilk
gmt plot -W2p,blue,solid -Am << EOF
>
100 -85
100 85
>
30 60
150 abc
EOF
gmt end
```

**Full error message**

```
No message error, but program won't finish
```

**System information**

* Operating system: MacOS
* Version of GMT: gmt6

**Comment by PaulWessel** [comment]
Thanks for pointing that out - it is being fixed via #659.
