### ISSUE TITLE
Users Script Contributions - requirements?

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#657]
I'm thinking about contributing to the ``Users Script Contributions`` in the docs. Any special requirements? ``bash`` vs ``dos/cmd``? Embed script as file or just as code block?

**Comment by seisman** [comment]
You can take a look at the the user script here (https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/source/gallery/users_contrib_script).

I think currently we need a bash script embedded in a rST file as a code block.

**Comment by abanbj** [comment]
Super, thanks Dongdong.

**Comment by seisman** [comment]
Closed.
