### ISSUE TITLE
[v6.4.0] grd2kml fails

### ISSUE THREAD

**Issue by seungsep** [GenericMappingTools/gmt#6587]
**Description of the problem**
grd2kml fails to produce KML files with the error message associated with grdfilter. 
But the same command line with grd2kml v6.3.0 works out with no issues.

**Full script that generated the error**

```
gmt grd2kml t.nc -Ntest -T"test" -I+d
```

**Full error message**

```
grd2kml [NOTICE]: Extended grid size is by 1024 by 1024, tile size is 512 x 512
grdfilter [ERROR]: Option -D: Input grid is geographic but your distance mode is Cartesian
```

**System information**

* Operating system: OS Big Sur 11.6.5
* GMT version (`gmt --version`): 6.4.0_2a0ffbc_2022.04.18

**Comment by PaulWessel** [comment]
Could you share the output of grdinfo t.nc?

**Comment by seungsep** [comment]
Here it is~

t.nc: Title: z
t.nc: Command: grdsample /tmp/74153.nc -I0.2s+e -Gt.nc
t.nc: Remark: 
t.nc: Pixel node registration used [Geographic grid]
t.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
t.nc: x_min: 184.590444225 x_max: 184.62838867 x_inc: 5.55555555555e-05 name: longitude n_columns: 683
t.nc: y_min: -20.5563741781 y_max: -20.5315408448 y_inc: 5.55555555556e-05 name: latitude n_rows: 447
t.nc: v_min: -0.30519798398 v_max: 154.343490601 name: z
t.nc: scale_factor: 1 add_offset: 0
t.nc: format: netCDF-4 chunk_size: 137,149 shuffle: on deflation_level: 3

**Comment by PaulWessel** [comment]
Thanks, was able to reproduce and learned a lot, see related PR.

**Comment by seungsep** [comment]
Thanks for checking out this issue!
However, I still have the same issue...

Pulled version: 6.4.0_81d3933_2022.05.02

Followings are the error message after running `gmt grd2kml t.nc -Ntest2 -I+d -Vl`

```
grd2kml [NOTICE]: Extended grid size is by 1024 by 1024, tile size is 512 x 512
grd2kml [INFORMATION]: Level 0: Factor = 2 Dim = 1024 x 1024 -> 512 x 512
grd2kml [INFORMATION]: Level 0: Low-pass-filtering the grid(s)
grd2kml [INFORMATION]: Running grdfilter : /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_data_074872.grd -D0 -Fg0.00011111111 -I0.0001111111111110822 -rp -G/var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_Z_L0_tmp_074872.grd
grdfilter [INFORMATION]: Processing input grid
grdfilter [INFORMATION]: netCDF grid /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_data_074872.grd has no default CPT.
grdfilter [ERROR]: Option -D: Input grid is geographic but your distance mode is Cartesian
```

**Comment by PaulWessel** [comment]
I think it is because @joa-quim is busy eating again and not approving pull requests.  So it is not in the system yet unless you did the branch?

**Comment by PaulWessel** [comment]
OK, just got merged.  Please update to master and try again, @seungsep.

**Comment by seungsep** [comment]
Okay, I see something has been changed. But the error message is also changed as follows:

```
grd2kml [INFORMATION]: Level 00: Mapped tile 184.580944225/184.637833114/-20.5724297337/-20.5155408448
grd2kml [NOTICE]: Level 00: Tile size: 3.41333 x 3.41333 m Tiles:   1 by   1 =     1     1 mapped   0 empty [Gaussian filtered with -Fg0.00011111111 -I0.0001111111111110822]
grd2kml [INFORMATION]: Level 1: Factor = 2 Dim = 1024 x 1024 -> 512 x 512
grd2kml [INFORMATION]: netCDF grid /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_data_078707.grd has no default CPT.
grd2kml [INFORMATION]: Reading grid from file /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_data_078707.grd
grd2kml [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grd2kml [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdimage [INFORMATION]: Read intensity grid header from file /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_intens_078707.grd
grdimage [INFORMATION]: netCDF grid /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_intens_078707.grd has no default CPT.
grdimage [INFORMATION]: Read header from file @GMTAPI@-S-I-G-G-G-N-000022
grdimage [INFORMATION]: Map scale is 2.18723e-06 km per cm or 1:0.218723.
grdimage [INFORMATION]: Allocate and read data from file @GMTAPI@-S-I-G-G-G-N-000022
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdimage [INFORMATION]: Allocates memory and read intensity file
grdimage [INFORMATION]: Reading grid from file /var/folders/r6/xzp_007d4xs_q8v6tmf0nfhm0000gn/T/grd2kml_extended_intens_078707.grd
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdimage [ERROR]: Dimensions of intensity grid do not match that of the data grid!
grd2kml [ERROR]: Unable to create a direct PNG from grid
```

**Comment by PaulWessel** [comment]
Oops, I guess I first tested it without -I and then it works.  OK, will see what is going on with -I now.

**Comment by PaulWessel** [comment]
So there is some round-off when we extract a section from an intensity grid and we get 513x513 instead of 512x512.  It has to do with the random numbers in -R.  I guess these are MBsystem etc which likes to grid in random degree increments and not, say arc seconds....
I will need to find where it ix happening and see if we are too relaxed on teh check for -R.  I suspect the -R is just a hair outside the grid nodes (e.g., 10^-8) so it adds one more row and column and boom we have 513x513.

**Comment by seungsep** [comment]
Thanks for fixing the issue! I found `grd2kml` works now as expected!
