### ISSUE TITLE
Something in the cube broke for Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6595]
It now started to error (but works fine from CLI)
```
julia> grdinfo("utmsmall.tif", C=true, Vd=1)
        grdinfo utmsmall.tif  -C
grdinfo [ERROR]: gmt_M_err_trap: -51
grdinfo [ERROR]: gmtapi_import_cube: Unable to examine cube utmsmall.tif.
```
odd thing is that if I repeat the command two more times then it starts working
```
julia> grdinfo("utmsmall.tif", C=true, Vd=1)
        grdinfo utmsmall.tif  -C
GMTdataset{Float64, 2}[]

julia> grdinfo("utmsmall.tif", C=true, Vd=1)
        grdinfo utmsmall.tif  -C
BoundingBox:  [440720.0, 440720.0, 446720.0, 446720.0, 3.74532e6, 3.74532e6, 3.75132e6, 3.75132e6, 1.7976931348623157e308, 1.7976931348623157e308, -1.7976931348623157e308, -1.7976931348623157e308, 60.0, 60.0, 60.0, 60.0, 100.0, 100.0, 100.0, 100.0, 1.0, 1.0, 0.0, 0.0]
1×12 Matrix{Float64}:
 440720.0  446720.0  3.74532e6  3.75132e6  1.79769e308  -1.79769e308  60.0  60.0  100.0  100.0  1.0  0.0
```
[utmsmall.zip](https://github.com/GenericMappingTools/gmt/files/8517596/utmsmall.zip)

**Comment by joa-quim** [comment]
This is crazy. If I add the ``is_cube = false`` from #6593, that is not yet merged then this problem goes away!!

**Comment by PaulWessel** [comment]
Well I think the function that examines the cube was before under -Q protection.  Now it is called on anything and there is no protection against tiff etc.  I will need to add some more checking now to only do this for netCDF files.

**Comment by joa-quim** [comment]
-Q is for ``grdinterpolate`` and here I was using ``grdinfo``. #6596 fixed it
