### ISSUE TITLE
Ghrrr, just found this one

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6610]
```
gmt pscoast -RSJ_phase.grd -JQ16 -W0.5 -UJ.L.+tGMTSAR+o0/0 -Df -O '-B+tInterferograma 8-20 Abril' --MAP_TITLE_OFFSET=-0.5c >> SJ_08-20.ps
pscoast [ERROR]: No input files allowed
```

(*do not fix what doesn't need to be*)

**Comment by joa-quim** [comment]
and insists

```
gmt pscoast -R331.675833322/332.249166655/38.531875/38.7697916667 -JQ16 -W0.5 -Df -O '-B+tInterferograma 8-20 Abril' --MAP_TITLE_OFFSET=-0.5c >> SJ_08-20.ps
pscoast [ERROR]: No input files allowed
```

**Comment by PaulWessel** [comment]
Ok after dinner. Which item is it (if you know?)

**Comment by PaulWessel** [comment]
Cannot reproduce this at my end.

**Comment by PaulWessel** [comment]
I dont think there were any changes to this though.  Anything not starting with a hyphen is a file and we have always checked for that.  Why would we not check for bad arguments?

Let me know what you did to get this error, io.e., a GMT.jl command since I can debug those.

**Comment by joa-quim** [comment]
Computer busy for next > 1 hour computing Interferogram with all cores. 

That was a plain CLI command.

**Comment by PaulWessel** [comment]
The first one has a grid so I cannot do it verbatim (I used another grid with no problem), and the second command also run fine.  There are no arguments that do not start with a hyphen.  If you copy/paste that command and run it again and again, it still gives exactly the same error every time?

**Comment by joa-quim** [comment]
Some f copy-paste added quotes to the command
```
'-B+tInterferograma 8-20 Abril'
```
whilst it should have been
```
-B+t"Interferograma 8-20 Abril"
```

**Comment by PaulWessel** [comment]
Good thing it is not always my fault.
