### ISSUE TITLE
Large -A in rose

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#6611]
When the bin width becomes large enough, `rose` diagram gives unexpected placements

```
echo "0.33 -90" | gmt rose -JX10c -Bg -R0/1/0/360 -L -F -A10 -D -Gblue -png works
```

```
echo "0.33 -90" | gmt rose -JX10c -Bg -R0/1/0/360 -L -F -A20 -D -Gblue -png doesntwork
```

Best,
Guillaume

**Comment by PaulWessel** [comment]
When **-D** is used then the center of the wedge is at n * inc.  So in -A10 it is 0, 10, 20, .. including 270 (your -90).  So that one captures angles from 265 to 260 (-95 to -85).  It works as you say.

For the -A20 case it is the same, with bin centers at 0, 20, etc.  270 is not one of those, so it is 260 280 (or -100, -80).  Your point at -90 thus falls into the bin that is centered at -80 and goes from -90 to -70.

So in my thinking, both examples work.   I see no bug here.

**Comment by gd-a** [comment]
So it’s not centred on the value, but on the nearest multiple of given-A? Is it on purpose?

**Comment by PaulWessel** [comment]
All histograms behave like that, whether polar or cartesian - the bins are not adjusted to center on individual data points.

**Comment by PaulWessel** [comment]
Closing this issue.

**Comment by gd-a** [comment]
Sorry, I didn't take the time to think about a clever solution.

Now that I think about it, the "expand/collapse code" function could be really a good use to illustrate (MWE + figure) all options and parameters without overloading the already packed documentation. It would alleviate some misunderstanding like the current thread, or simply ease the learning curve.

I understand it's more work, but maybe if the dev team comes up with a good framework, the community can tackle the basic examples (plot, grdimage, ...) while you focus on the more complex ones (greenspline, gravi, ...)

Thoughts (and prayers)?

**Comment by PaulWessel** [comment]
Off today on trip to Cambridge so limited time, but some comments:

1. I guess my comment above had to do with what I assumed was your confusion as to what **rose** does.  To me it is just like any other histogram I am aware of and hence the bins are fixed once you pick a width and offset.  You seemed surprised by what you got so I was wondering what lead you to believe it would not be a histogram.  If so, perhaps I could add a sentence or two to the docs to make it crystal clear.
2. As for using the expand/collapse.  Yes, that is in general a good thing to show things.  However, it really only works well for very simple things.  Having very long scripts I think it a bit unwieldy.  As for the sample1d example, it shows all the various interpolators, so not sure if it is a great example of sample1d use, but I could be convinced.
