### ISSUE TITLE
grdinfo cube broken in Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6617]
This test now fails with
```
julia> C = grdinterpolate(raw"C:\Users\joaqu\.julia\dev\GMT\test\cube.nc", T="3/4/0.25");
julia> grdinfo(C)
[Session GMT (0)]: Error returned from GMT API: GMT_PADDING_NOT_ALLOWED (71)
[Session GMT (0)]: Error returned from GMT API: GMT_PADDING_NOT_ALLOWED (71)
[Session GMT (0)]: Error returned from GMT API: GMT_OBJECT_NOT_FOUND (60)
ERROR: GMT: Failed to close virtual file
```

**Comment by PaulWessel** [comment]
earthtide("-")
ERROR: GMT: No module by that name -- earthtide -- was found.

This is true of any other supplemental module though.

julia> backtracker("-")
ERROR: UndefVarError: backtracker not defined

But different error messages.

But I wonder: You say we set GMT_LIBRARY to point to the GMT library.  Yet, nothing points to the supplement.so file.  For the Xcode builds, that file is in the plugin directory.  So you are not finding it.  I have

.../xbuild/src/plugins/Debug/supplements.so
...xbuild/src/Debug/libgmt.dylib

So I guess libgmt does not know how to find ../plugins/Debug/supplements.so.  Not sure why Apple did it that way or maybe it is our Cmake that sets this.  I have need to add more places to look for the supplements.so file.

**Comment by joa-quim** [comment]
``bactracker`` is not ported so it would never work but ``psmeca`` yes, though the ``("-")`` fails for all module (I would swear it used to work
```
julia> psmeca("-")
gmtread [ERROR]: Unrecognized option -^
gmtread [ERROR]: Must specify both input and output filenames
gmtread [ERROR]: Must specify only two filenames (input and output)
ERROR: Something went wrong when calling the module. GMT error number = 72
``` 

Anyway, I don't think I do anyhing special for the supplements. It just works when it works on the CLI.
See that the CI test worked on Mac
https://github.com/GenericMappingTools/GMT.jl/runs/6164542893?check_suite_focus=true

NOTE. If you do ``] up`` the ``sprintf`` problem should have gone.

**Comment by PaulWessel** [comment]
I restarted Julia, did ] up, then using GMT but same?

**Comment by joa-quim** [comment]
Same what? ``erthtide``? (expected) or the ``parse_R`` test? It now calls ``@sprintf`` that worked for you.
