### ISSUE TITLE
Imperfect rectangles for discrete colorbars

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6624]
**Description of the problem**

Here is the test script to generate a discrete CPT and plot it:
```
gmt begin colorbar
	gmt makecpt -Ccategorical -W -T0/10/1
	gmt colorbar -C -B -Dx0c/0c+w10c+h
gmt end show
```

In GMT 6.3, the colorbar looks bad using Apple Preview (see below):
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/3974108/165129614-193dd2a0-c6a7-4e9d-9f2e-f8ee09d11548.png">

PR https://github.com/GenericMappingTools/gmt/pull/6360 fixes the problem by plotting rectangles for discrete colorbars. After the fix, the PDF version of the new image looks good, but the PNG version is not perfect if you zoom in to check the details. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/3974108/165130591-f846e470-61b8-4f42-a767-87649c2d6c31.png">

Perhaps it's because the polygons are overlapping?

**Comment by PaulWessel** [comment]
Is it just the rasterization to PNG? Try 

`gmt begin colorbar png E1200`

Does it look better?

**Comment by seisman** [comment]
> Is it just the rasterization to PNG? Try
> 
> `gmt begin colorbar png E1200`
> 
> Does it look better?

Yes, using `dpi=1200` looks good. Does it mean that the dimensions of the polygons are accurate and not overlapping?

**Comment by PaulWessel** [comment]
Yes, there is no way for them to be overlapping since boundaries are computed for each.
I think we settled on a dpi=600 as default so I dont think we need to do anything.  Although, every decade or so perhaps the expectations need to be reset...
