### ISSUE TITLE
surface -Ll explodes

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6639]
If specifying a lower level constant when gridding with **surface**, via option **-Ll,** the solution honors the lower level but grows in a crazy way.  If the upper level is set instead via **-Lu** it is honored as expected and nothing crazy happens at the lower end. E.g., using the table data we use for many tests in GMT (with data ranging from 690 60 960):

`gmt surface @Table_5_11.txt -R0/6.3/0/6.3 -I0.1 -GLl_limits2.grd -Ll750`

![6](https://user-images.githubusercontent.com/26473567/165837342-3e78775c-a512-49e4-99fa-9622d35eafb4.png)

If I use gmt4 with the same (local) file and options I get the expected plot:

![4](https://user-images.githubusercontent.com/26473567/165837486-391e1bfb-0dca-4e8a-9649-c80980ffc727.png)

Because we (a) have very few tests for surface in general and none for -L, and (b) I have not used that option myself much and (c) neither have others, it seem since we have not received any bug report, this issue could have been there for some time - most likely during the major GMT5 porting.  I will have to compare and see what happens and why only for the lower bound.

**Comment by PaulWessel** [comment]
Must be a new bot. Hate it when I have to show my ID to the new bot so they know who they are talking to...

**Comment by joa-quim** [comment]
You must somehow be violating de CC. 😈

**Comment by PaulWessel** [comment]
It is the norwegian cursing picked up by my microphone.

**Comment by joa-quim** [comment]
See? A clear violation.

**Comment by PaulWessel** [comment]
Just a note that this is not limited to **-Ll**.  If I change the sign of the data and level and use `-Lu-750` as upper limit the same thing happens (and not in GMT 4).
Furthermore, the node used to access the lower boundary grid was not correct and after (trying to) fix that the blow-up was less but still blow -up.  So the theory so far is that there are still a bug in finding the right bound node.  Why a grid you say when I am using a constant in -L? Well, part of the processing involves removing the best-fitting plane from the data so we must also do that to the constraints, hence the 750 constant becomes a plane as well and hence a grid.
