### ISSUE TITLE
Improve sample1d -F docs

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6643]
In order to understand well [sample1d -F](https://docs.generic-mapping-tools.org/dev/sample1d.html#f) I made the following figure.

I think it could be add to the doc to help the users. What do you think? If so, Are you ok with the figure? Any ideas on how to improve it (besides adding a legend and maybe play a bit with the colors)? 

![smooth_deriv](https://user-images.githubusercontent.com/17908951/165947753-ba9d9ead-59ea-4f6f-8e13-d4a04cdc4125.png)

```
gmt begin smooth_deriv png
	gmt plot @topo_crossection.txt -Sc0.1c -Gred -N -JX6.5i/2.5i -Bf -Re
	gmt sample1d @topo_crossection.txt -T0.1 -Fl0.0001 > new.txt
	gmt plot new.txt -Wfaint,red
	gmt sample1d @topo_crossection.txt -T0.1 -Fa0.0001 > new.txt
	gmt plot new.txt -W0.25p,blue
	gmt sample1d @topo_crossection.txt -T0.1 -Fc0.0001 > new.txt
	gmt plot new.txt -W0.25p,green
	gmt sample1d @topo_crossection.txt -T0.1 -Fn0.0001 > new.txt
	gmt plot new.txt -W0.25p,orange
	gmt sample1d @topo_crossection.txt -T0.1 -Fs0.0001 > new.txt
	gmt plot new.txt -W0.25p
gmt end
```

**Comment by PaulWessel** [comment]
Sure, we could have a plot near the top of sample1d.  There are similar types of plots in the test/sample1d dir.  Note, however, that **-Fs** is the only directive that takes the fit argument, so `-Fa0.001` is meaningless and perhaps should result in an error.
Also, since you are not using nex.txt for anything other than plotting you should just pipe it through plot to shorten the script.
Maybe only use half the data to make it easier to see the differences between the splines?

**Comment by PaulWessel** [comment]
Yes, very nice.  But a few questions:

1. We should also show the smoothing spline -Fs too, no?
2. Seems like this is a great example to use -l for auto legend since you are just doing lines and labels?

**Comment by Esteban82** [comment]
The new version of the figure. 

![doc_splines](https://user-images.githubusercontent.com/17908951/165977209-6f5d76b4-75b1-47ab-904d-dbdb95dfab5f.png)



```
cat << EOF > t.txt
0	0
1	1
2	1.5
3	1.25
4	1.5
4.5	3
5	2
6	2.5
EOF
# Splines
gmt begin doc_splines png
gmt sample1d t.txt -T0.01 -Fc  | gmt plot -R-0.1/6.1/-0.1/3.1 -JX6i/3i -Baf -By+l"u(x)" -BWSne -W1p -l"Cubic spline (-Fc)"
gmt sample1d t.txt -T0.01 -Fs1 | gmt plot -W1p,orange -l"Smooth cubic spline (-Fs1)"
gmt sample1d t.txt -T0.01 -Fl  | gmt plot -W1p,blue -l"Linear spline (-Fl)"
gmt sample1d t.txt -T0.01 -Fa  | gmt plot -W1p,red -l"Akima spline (-Fa)"
gmt sample1d t.txt -T0.01 -Fn  | gmt plot -W1p,darkgreen -l"Nearest neighbor (-Fn)"
gmt plot t.txt -Sc0.1i -Gred -Wthin -l"Data"
gmt legend -DjTL+w1.9i+o0.1i -F+p1p+gwhite+s 
gmt end 
```

**Comment by PaulWessel** [comment]
Nice! Would you like to try to make this into doc/scripts/GMT_splines.sh and follow the Contributing Guide on documentation on how to add a new test or script?  I've followed @meghanrjones's write-up myself and it should be OK.  You can see in the doc/rst/source/movie.rst or others for what to do to add a figure to the documentation.  If you start such a pull request then I can help if you get stuck.  Look at the other scripts in doc/script for how to set up names etc.

Oh, maybe add "x" as label to go with the u(x) for the y-axis?

**Comment by seisman** [comment]
Nice example! I would suggest using SI units rather than US units in the script.

**Comment by meghanrjones** [comment]
Awesome example @Esteban82! I can answer questions about the process for adding it to the docs if you decide to do that. In order to push the example image to the dvc repo, you would need to let me or @seisman know after you've created a DAGsHub account so that we can give you write permissions.

**Comment by Esteban82** [comment]
Yes, I will try to add the figure. 

I only have one doubts. What is the optimal height and length (-JX) of the graph for the docs? I think it should be shorter.

**Comment by PaulWessel** [comment]
Most of the time I prefer figs with aspect ratios as you have it.  Wider than the hight.  I think it is OK.

**Comment by Esteban82** [comment]
OK. This is `-JX15c/6c`.

![doc_splines](https://user-images.githubusercontent.com/17908951/165996689-5c075921-1441-49fd-977e-688e0a8f7323.png)

**Comment by Esteban82** [comment]
> Awesome example @Esteban82! I can answer questions about the process for adding it to the docs if you decide to do that. In order to push the example image to the dvc repo, you would need to let me or @seisman know after you've created a DAGsHub account so that we can give you write permissions.

Thanks Max. This is my account: https://dagshub.com/Esteban82

**Comment by meghanrjones** [comment]
Great, you've been added to the team on DAGsHub and should be good to go. Let me know if you run into any problems.

**Comment by gd-a** [comment]
@PaulWessel : on the same track [#6611](https://github.com/GenericMappingTools/gmt/issues/6611#issuecomment-1116486175) ... @Esteban82's work could be extended?
