### ISSUE TITLE
Don't use GMT_THEME=cookbook in cookbook scripts

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6649]
In some examples in the cookbook, we use the `GMT_THEME=cookbook` setting. For example:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/3974108/166139304-c27f2e2f-c92a-448d-a130-6faa6a90ed10.png">

Why do we use it? Users may be confused that why `GMT_THEME=cookbook` is always presented in these examples.

**Comment by joa-quim** [comment]
Agree.

**Comment by meghanrjones** [comment]
It's included so that all the output images don't have different font and pen sizes due to the modern mode conf default of auto, which would look bad.

**Comment by seisman** [comment]
> It's included so that all the output images don't have different font and pen sizes due to the modern mode conf default of auto, which would look bad.

I'm not fully convinced by this reason. If the images look bad due to the different font and pen sizes, we should update the scripts so that all basemaps have similar dimensions (thus similar font and pen sizes).

**Comment by meghanrjones** [comment]
> > It's included so that all the output images don't have different font and pen sizes due to the modern mode conf default of auto, which would look bad.
> 
> I'm not fully convinced by this reason. If the images look bad due to the different font and pen sizes, we should update the scripts so that all basemaps have similar dimensions (thus similar font and pen sizes).

I recommend submitting a PR for one section of the cookbook with your solution rather than using the cookbook theme so that we can review the appearance.

**Comment by joa-quim** [comment]
Now close this?

**Comment by seisman** [comment]
there are still a lot to update

**Comment by seisman** [comment]
Closed by #8509.
