### ISSUE TITLE
Is gmtprogram.c needed?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#665]
The old gmtprogram.c shows how you can mimic the old GMT 4 executables and it says it is used under Windows.  Is that true, @joa-quim ?  if it is not used then we should remove it and its reference in CMakeLists.txt.

**Comment by joa-quim** [comment]
I believe this is the program used to create the module executables on Windows. This was made to circumvent the difficulties to make symbolic links on Windows (XP disn't even support it). Now we don't support XP anymore and I use symbolic links all the time, but not sure how easy it is to used them in older Windows versions (some required Administrator privileges to make symbolic links) .

So, I guess, we still need it while we don't know how to replace it by symlinks.

**Comment by PaulWessel** [comment]
I see this program is used to make those stand-alone executables in GmtHelperMacros.cmake:

`GmtHelperMacros.cmake:				add_executable (${_gmtmodule} ${GMT_PROGRAM})
`

Since XP is no longer supported, what do you mean by older Windows versions.  Are we supporting people not on at least Win 7?

**Comment by joa-quim** [comment]
No 7. It's enough to look at Win 10 only. Lots of [versions](https://en.wikipedia.org/wiki/Windows_10_version_history)
