### ISSUE TITLE
Someone is beeing too strict

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6653]
There is nothing wrong in the custom symbol name but
```
julia> plot(r, decorated=(locations=a, symbol=(custom="arrow", size=0.3), fill=:black, dec2=true), Vd=1)
        psxy  -JX14c/0 -Baf -BWSen -R-10.4/10/-11/11 -S~f:+skC:\Users\joaqu\.julia\dev\GMT\share\custom\arrow/0.3+gblack -P -K > C:\TEMP\GMTjl_tmp.ps

psxy [WARNING]: Your filename @GMTAPI@-S-I-D-D-T-N-000288:+skC have what appears as valid GMT modifiers (from list +Udhinosu) but are embedded rather than appended to the filename - modifiers ignored
psxy [ERROR]: Libcurl Error: HTTP response code said error
psxy [ERROR]: Probably means @GMTAPI@-S-I-D-D-T-N-000288:+skC does not exist on the remote server
psxy [ERROR]: Unable to obtain remote file @GMTAPI@-S-I-D-D-T-N-000288:+skC
psxy [WARNING]: Your filename @GMTAPI@-S-I-D-D-T-N-000288:+skC have what appears as valid GMT modifiers (from list +Udhinosu) but are embedded rather than appended to the filename - modifiers ignored
psxy [ERROR]: Option -X: Cannot find/read fixed point file ~f@GMTAPI@-S-I-D-D-T-N-000288:+skC
psxy [ERROR]: No symbol specified!
```

**Comment by PaulWessel** [comment]
Sorry, is the **f** referring to fix points and those are given by a virtual file? So the _GMT_Encode_Options_ should turn that into `-S~f?:+sk` etc?

**Comment by joa-quim** [comment]
No, no virtual files here so the mention to them already indicate a stray path. If I change the code back to accept first custom files in current dir, then it works fine.

```
julia> plot(r, decorated=(locations=a, symbol=(custom="arrow", size=0.3), fill=:black, dec2=true), Vd=1)
        psxy  -JX14c/0 -Baf -BWSen -R-10.4/10/-11/11 -S~f:+skarrow/0.3+gblack -P -K > C:\TEMP\GMTjl_tmp.ps
```

**Comment by PaulWessel** [comment]
Hm, if there are no virtual file, then were is the argument to **f**?

**Comment by PaulWessel** [comment]
I mean, **f** takes a file name and if those locations are not provided by some virtual file then presumably you have an actual file name to give it, no?

**Comment by PaulWessel** [comment]
I can debug this in Julia tomorrow if you provide what I need (e.g., a, arrow, ...)

**Comment by joa-quim** [comment]
But the complain is not on the locations (**f**) but on the custom symbol name. My second example works fine and I'm still passing the locations as an array.
``:+skC have what appears as valid GMT modifiers...``
``@GMTAPI@-S-I-D-D-T-N-000288:+skC does not exist on the remote server``

**Comment by joa-quim** [comment]
arrow.def
```
-0.5	-0.3	M
-0.2	-0.0	D
-0.5	0.3	D
 0.5	0.0	D
-0.5	-0.3	D
```

**Comment by PaulWessel** [comment]
Sorry, perhaps I am confused, but your command needs two data files:

1. The data defining your line
2. The data defining your fixed points along the line for decorations

I assume `locations=a` sets the line? Where are the fixed points given?

**Comment by PaulWessel** [comment]
And by the way, it is complaining about the fixed point file:

> Cannot find/read fixed point file

**Comment by joa-quim** [comment]
``a`` is the locations array (``r,a = streamlines(U, V);`` but you can't reproduce this yet). There is no problem with it. The problem is when I pass the custom's full name.
```
julia> r,a = streamlines(U, V);
julia> plot(r, decorated=(locations=a, symbol=(custom="arrow", size=0.3), fill=:black, dec2=true), show=1)
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/166166641-94fd29cd-7971-4bc5-88f5-fec349d804b6.png)

**Comment by joa-quim** [comment]
Update the Julia wrapper.
Do:
```
x,y = GMT.meshgrid(-10:10); u = 2 .* x .* y; v = y .^2 - x .^ 2; U = mat2grid(u, x[1,:], y[:,1]); V = mat2grid(v, x[1,:], y[:,1]);
r,a = streamlines(U, V);
plot(r, decorated=(locations=a, symbol=(custom="arrow", size=0.3), fill=:black, dec2=true), show=1)
```
Now edit the file ``common_options.jl`` at line 2781
``if (GMTver < v"6.5.0" && startswith(marca, "karrow/"))``
and change "6.5.0" to "6.4.0". The above plot command won't work anymore and the reported error will show up.

You find ``common_options.jl`` in dir ``dirname(pathof(GMT))``

**Comment by PaulWessel** [comment]
OK, you could speed this up a bit if you answered my questions. So **r** has the line coordinates and **a** has the points where you want arrows.  When I follow your steps I do crash but my error is different:

```
plot(r, decorated=(locations=a, symbol=(custom="arrow", size=0.3), fill=:black, dec2=true), show=1, Vd=1)
	psxy  -JX14c/0 -Baf -BWSen -R-10.4/10/-11/11 -S~f:+sk/Users/pwessel/.julia/packages/GMT/QLN4l/src/../share/custom/arrow/+gblack -P -K > /tmp/GMTjl_tmp.ps
psxy [ERROR]: Option -S~: Custom symbol /Users/pwessel/.julia/packages/GMT/QLN4l/src/../share/custom/arrow/ not given a valid size
```

The path looks OK since I can test it:

```
ls /Users/pwessel/.julia/packages/GMT/QLN4l/src/../share/custom/arrow*
/Users/pwessel/.julia/packages/GMT/QLN4l/src/../share/custom/arrow.def
```

However, the size argument is gone so it complains about that.  This is not the same you had above so not sure what is up with this.  I don't want to spent time debugging that when you do not see that problem on your end.

**Comment by joa-quim** [comment]
Sorry, that's the result of changes-over-changes-and-not-final-testing.
Change line 2784 to
```
marca = "k" * joinpath(dirname(pathof(GMT)), "..", "share", "custom", "arrow/") * marca[8:end]
```

I did answer your questions but you keep pointing to the locations array when there is no problem with it. The error messages refer to ``@GMTAPI@-S-I-D-D-T-N-000009:+skC`` but this means that the virtual memory address is glued with the beginning of the custom symbol file name and trimmed at the ``:`` of ``C:\...``

**Comment by PaulWessel** [comment]
Yes, I think it is related to that - so I cannot easily simulate that here.  But I will stare at that code and see if there is any allowance for Bill's colon.

**Comment by PaulWessel** [comment]
As you know, in these options the colon separates the directive from the options, so it should not be too hard to figure out how to handle that.

**Comment by joa-quim** [comment]
Given that is *forgive* the first colon I'd say it's looking backwards from the end of the line string and stop at first found.

**Comment by PaulWessel** [comment]
Working on this now.  I am excluding colons (for this purpose) if followed by \ and preceeded by a letter.  Can the C in C:\ be lower case?

**Comment by joa-quim** [comment]
Yes, all ``c:/``, ``C:/``, ``c:\`` and ``C:\`` are allowed.
