### ISSUE TITLE
FORMAT_CLOCK_IN vs FORMAT_CLOCK_OUT - combine to one paragraph?

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6654]
Could the description of `FORMAT_CLOCK_IN` and `FORMAT_CLOCK_OUT` in [gmt.conf](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#format-parameters) be condensed into a single paragraph? Isnt the machinary (code) dealing with this the same for both direction (IN and OUT)?

Same for `FORMAT_DATE_IN` and `FORMAT_DATE_OUT` (and maybe others?)

**Comment by PaulWessel** [comment]
There are a few differences, most notably the ability to se "-" for the OUT formats.  Other than that, yes, there are lots of near-repetition here that could be eliminated.  Perhaps the IN part could have the best of both those paragraph, and then the OUT could say "see IN for formattng details" In addition, for output we can also .... ?

**Comment by anbj** [comment]
Thanks for that. Sounds good!

**Comment by PaulWessel** [comment]
So, if you are energized and motivated to try this, please do - I am deep into surface...

**Comment by anbj** [comment]
Just to recap; the only difference is that with OUT you may do; *If your template starts with a leading hyphen (-) then each integer item (y,m,d) will be printed without leading zeros (default uses fixed width formats).*. Apart from that it's the same?

**Comment by anbj** [comment]
Please have a look at #6730.

**Comment by anbj** [comment]
Closing as finished.
