### ISSUE TITLE
grdfft doesn't work on externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6660]
Result grid is interspersed with columns of zeros
```
G = grdfft("@earth_relief_10m", F="3000000/2000000/500000/300000", N="a+a", f="g");
imshow(G, shade=true)
```
![GMTjl_tmp-fs8](https://user-images.githubusercontent.com/537321/166392322-188a09d5-d65f-4ea0-8a8e-65624f5bc7b2.png)

**Comment by PaulWessel** [comment]
Right,  I suspect it does not work for neither mex, julia, or pyGMT since there are real and imaginary nodes and the writing to file knows about that but looks like the virtual stuff does not.

Remind me again if you are getting back a GMT_IS_GRID or a GMT_IS_MATRIX and I will see what is involved.

**Comment by joa-quim** [comment]
I get back GRIDs

**Comment by PaulWessel** [comment]
Thanks, I will walk through the debugger and see what it is not doing here (like the gmt_nc is doing correctly).
