### ISSUE TITLE
Plot annotations without tick marks

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#667]
Is it possible to disable tick marks, but still have annotations?

E.g.
```
psbasemap -JX10c -R0/100/0/100 -Bag > annot.ps
```

gives annotations (with ticks) and gridlines. I would like to not draw the tick marks.

**Comment by PaulWessel** [comment]
Maybe try setting the tick length to zero?

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa

**Comment by PaulWessel** [comment]
Tested and works; closing.
