### ISSUE TITLE
grd2xyz and xyz2grd for cubes

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6682]
**Description of the desired feature**

Now that GMT has some tools for dealing with 3-D cubes (and we can extract layers from them since GMT3), there is the issue of how to convert a table of `x,y,z,v` data to a cube.  This is the same we do for 2-D data turning `x,y,v` triplets to grids (and reversed via **grd2xyz**).

There are two paths, obviously:

1. Add two new modules **tbl2cube** and **cube2tbl**.  These would have some of the same options as their 2D cousins but not all, and be cleanly written from scratch.
2. Enable **xyz2grd** and **grd2xyz** to handle this transparently.  I think **grd2xyz** is relatively easy to do - we learn the item is a cube and we go into a special section that writes 4 instead of 3 things with loops over layers.  **xyz2grd** should also be easy in the sense that **-R** and **-I** will tell us we are doing a cube.  The only dumb thing is the names of the modules and all the talk about grids.

Since we have already enhanced a few grd modules to handle cubes (**grdinfo**, **grdselect**) perhaps we stay the course and do option 2 as well.  I am leaning that way.

**Comment by joa-quim** [comment]
Yes, no new module. Just extend the *xyz<->grd* pair
