### ISSUE TITLE
Remove documentations of Julia wrapper

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#669]
The documentation for GMT/Julia wrapper (https://www.generic-mapping-tools.org/gmt/dev/jl_wrapper.html) is unmaintained and outdated. 

Since GMT.jl has its own documentation (https://www.generic-mapping-tools.org/GMT.jl/latest/), I think we can remove the detailed install instructions and usage, and only give a brief description and add a link to the official documentation.

**Comment by joa-quim** [comment]
Yes, I know I should have updated that section to point to the Github docs.

**Comment by PaulWessel** [comment]
Perhaps you can have a look at that so we can close this issue?
