### ISSUE TITLE
GMT cannot do parallel jobs in same directory

### ISSUE THREAD

**Issue by remkos** [GenericMappingTools/gmt#6711]
**Description of the problem**
When running two gmt (new style) scripts in parallel in the same directory, I errors that look like ghostscript errors that indicate conflicts between the two jobs writing in the same temporary PS files. I suspect that some intermediate file has a fixed name, so that the two jobs clash.

E.g.:
 **** Error: Unknown operator: '168.676114.918191269982' looks like a malformed number, replacing with 0.
                Output may be incorrect.
   **** Error: Unknown operator: '.673.48874.1953.3' looks like a malformed number, replacing with 0.
                Output may be incorrect.

I do not think that used to be the case before.

**System information**

* Operating system: macOS 12.3.1 21E258 x86_64
* GMT version (`gmt --version`): 6.4.0_620a645_2022.03.14

**Comment by PaulWessel** [comment]
Cannot be done, the [begin](https://docs.generic-mapping-tools.org/dev/begin.html#note-on-unix-shells) docs.

**Comment by remkos** [comment]
> Cannot be done, the [begin](https://docs.generic-mapping-tools.org/dev/begin.html#note-on-unix-shells) docs.

I'm not running jobs in parallel directly from the command line, but through shell scripts. E.g.:
my_gmt_script.sh blabla.png
Calling this script from make, to create multiple pngs (e.g.  make -j6 *.png), I can indeed see six individual sessions being created in ~/.gmt/sessions, each with their own jobid. So it is not the type of clash that is mentioned in the docs.
There must be some other clash, because when I run the same with make -j1 *.png, I do not get the errors.

**Comment by PaulWessel** [comment]
Interesting.  See if you can recreate this problem with a simple basemap or coast script called from a makefile and if so post it here so I can have a look.  I often have some of the GMT tests fail in mysterious ways when I run the tests since I think I have -j10 and sometimes -j20 and there is clearly some confusion at times.  Rerunning the scripts manually passes, and there is not real pattern to which scripts might fail.

**Comment by remkos** [comment]
Will do.

**Comment by remkos** [comment]
Here is some evidence from `gmt end -Vd` that an intermediate file `gmt_0_intermediate.pdf` (without any preceeding path, so within the current working directory) is created.
Unfortunately not yet duplicated in a test.
```
psconvert [INFORMATION]: Processing /Users/remko/.gmt/sessions/gmt_session.83556/gmt_0.ps-...
psconvert [INFORMATION]: An unknown psconvert setting was found but since image coordinates seem to be geographical, a linear transformation will be used.
psconvert [INFORMATION]: PS file with transparency must be converted to PDF before creating PNG
psconvert [INFORMATION]: Convert to intermediate PDF...
psconvert [DEBUG]: Running: gs -q -dNOPAUSE -dBATCH -dNOSAFER -dPDFSETTINGS=/prepress -dDownsampleColorImages=false -dDownsampleGrayImages=false -dDownsampleMonoImages=false -dUseFlateCompression=true -dEmbedAllFonts=true -dSubsetFonts=true -dMonoImageFilter=/FlateEncode -dAutoFilterGrayImages=false -dGrayImageFilter=/FlateEncode -dAutoFilterColorImages=false -dColorImageFilter=/FlateEncode -dSCANCONVERTERTYPE=2 -dALLOWPSTRANSPARENCY -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=1 -dTextAlphaBits=1 -sDEVICE=pdfwrite  -g2480x3509 -r300 -sOutputFile='gmt_0_intermediate.pdf' '/Users/remko/.gmt/sessions/gmt_session.83556/psconvert_83638d.eps'
psconvert [INFORMATION]: Convert PDF with transparency to PNG...
psconvert [DEBUG]: Running: gs -q -dNOPAUSE -dBATCH -dNOSAFER -dPDFSETTINGS=/prepress -dDownsampleColorImages=false -dDownsampleGrayImages=false -dDownsampleMonoImages=false -dUseFlateCompression=true -dEmbedAllFonts=true -dSubsetFonts=true -dMonoImageFilter=/FlateEncode -dAutoFilterGrayImages=false -dGrayImageFilter=/FlateEncode -dAutoFilterColorImages=false -dColorImageFilter=/FlateEncode -dSCANCONVERTERTYPE=2 -dALLOWPSTRANSPARENCY -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=png16m  -g2480x3509 -r300 -sOutputFile='d/6a_hrnto1-6a_hrrep1.png' 'gmt_0_intermediate.pdf'
psconvert [DEBUG]: Delete gmt_0_intermediate.pdf
psconvert [DEBUG]: Delete /Users/remko/.gmt/sessions/gmt_session.83556/psconvert_83638d.eps
```

**Comment by remkos** [comment]
I found that a local `gmt_0_intermediate.pdf` (i.e. in the current working directory) is always created when all the below conditions are satisfied:
- The output format is PNG
- The output file is in a subdirectory, so output name is, e.g., img/plot.png
- There is transparency in the plot, but this can be as obscure as using `gmt plot -Sq` even without explicit transparency.
