### ISSUE TITLE
Flag to disable headless vectors

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#6725]
If the length of the vector is less than the size of the arrow, the GMT (psxy) only draws a line, not an arrow (top of the figure). This problem can be partially solved by using the +n flag (center of the figure). But sometimes for small values it is necessary to show only the direction of the vector field, and the value itself is not so important. In this case, a flag would be useful to force the GMT to draw the arrow of the vector, regardless of its length (bottom of the figure).
![out](https://user-images.githubusercontent.com/5275343/168943496-d9129809-5225-4981-802a-9f2b6242b168.png)

```bash
PROJ="-R0/4/0/10 -JX4c/10c -Xa1c -Ya1c"

gmt psbasemap $PROJ -Bxg1 -Byg1 -P -K>out.ps

echo "1 7 90 2
2 7 90 1
3 7 90 0.5
" | gmt psxy $PROJ -W0.1c,red -Gred -Sv1c+e -P -O -K>>out.ps

echo "1 4 90 2
2 4 90 1
3 4 90 0.5
" | gmt psxy $PROJ -W0.1c,black -Gblack -Sv1c+e+n1.001c -P -O -K>>out.ps

echo "1 1 90 2
2 1 90 1
3 1 90 1
" | gmt psxy $PROJ -W0.1c,green -Ggreen -Sv1c+e -P -O>>out.ps
```

**Comment by PaulWessel** [comment]
Have you tried just using **+n** without any argument? The man page seems to say that is what you want:

`If no argument is given then +n ensures vector heads are not shrunk and always plotted regardless of vector length`

**Comment by uleysky** [comment]
My fault, sorry. +n works.
