### ISSUE TITLE
CPT labels are ignored in Julia/MEX

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6732]
See https://github.com/GenericMappingTools/GMT.jl/issues/896

**Comment by joa-quim** [comment]
I've not had time to see if the trouble may be in the Julia side.

**Comment by PaulWessel** [comment]
Will look on flight; at least makecpt-F+c has some issues

Paul Wessel
Professor, Department of Earth Sciences
(808) 956-4778 | ***@***.***
http://www.soest.hawaii.edu/earthsciences

**Comment by joa-quim** [comment]
Closing this as using -T solve the issue
