### ISSUE TITLE
Backticks vesus $(...) in shell scripting

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6736]
**Description of the desired feature**

Please see this [StackExchange](https://unix.stackexchange.com/questions/126927/have-backticks-i-e-cmd-in-sh-shells-been-deprecated#:~:text=In%20csh%2Ftcsh%2C%20the%20backticks,ever%2C%20for%20that%20matter).) note for full background.

Basically, the argument is that we should stick to `$(..)` as the recommended way to run a subshell and store the value in a variable.
There are many good arguments for this (see above).

The only argument against is that` $(...)` is not a known thing in csh/tcsh and apparently there are still folks out there using those shells.  They have back-ticks for this only.  Also, note backticks are not going away so it is not a transition thing.  Finallyl, there is nothing like this in DOS batch scripts I believe.

Please make sure you read the StackExchange summary before you voice your (now) informed opinion on this.  I was about to make a PR to replace all occurrences of this in scripts and docs but decided to go about it in this way first.

**Comment by anbj** [comment]
I replaced alot of these in #2595.

It's too bad it's not supported by csh/tcsh. Just out of curiosity; how many users are complaining abour this?

See also [this post on stackoverflow](https://stackoverflow.com/questions/9449778/what-is-the-benefit-of-using-instead-of-backticks-in-shell-scripts). `$()` is POSIX; *$() is POSIX and supported by all modern Bourne shells, e.g. ksh, bash, ash, dash, zsh, busybox, you name it.*

But csh/tsch not listed.

**Comment by Esteban82** [comment]
OK, we leave the docs. 


I had to use double backticks. With <> I get this: 

`gmt plot `gmt info -I5 -D1 @ship_15.txt` @ship_15.txt -B -Sc2p -pdf map`

**Comment by PaulWessel** [comment]
AH, I see.  Interesting failure,  maybe there is an escape sequence to use instead.  Not important.

**Comment by Esteban82** [comment]
> AH, I see. Interesting failure, maybe there is an escape sequence to use instead. Not important.

Yes, 2 backticks instead of 1.

**Comment by seisman** [comment]
Perhaps we can try [the `tab-set` directive](https://sphinx-design.readthedocs.io/en/latest/tabs.html).

For commands that need backticks/`$()`, we can show two tabs, one for bash (using `$()`), another one for csh/tcsh (using backticks).

**Comment by seisman** [comment]
I think we should use `$()` consistently in all scripts. Here are my reasons：

1. We already have many examples that use `$()`. Mixing `$()` and backticks may cause more confusion.
2. csh/tcsh users should know that `$()` is not supported by csh/tcsh. It's their responsibility to know the language they're using.

**Comment by PaulWessel** [comment]
I am in agreement. Sandwell and his things and students and postdoctoral folk use csh but us cleaning up our things should not affect that.
