### ISSUE TITLE
grdcontour having trouble with tiny mignitudes

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6738]
See the original [PyGMT](https://github.com/GenericMappingTools/pygmt/issues/1927) issue for background.

I have isolated a small 5x4 grid cut from the offending grid above that fails to let us contour the zero-contour.  This hangs:

`gmt grdcontour t.grd -V  -C10 -JX15c > t.ps`

The values are very small on either side of zero.  Here is a graphical view of the values:

![nodes](https://user-images.githubusercontent.com/26473567/169926377-a4813058-6a05-41cf-91bb-31bc7c1e62e0.png)

If I scale t.grd by 1000 and try to contour that it works.  Since **grdcontour** works by never allowing any node to be _exactly_ zero (we add a tiny amount), the issue of _tiny_ in relation to these small values is the troubles, so I know where to look.  Posting t.grd here for reference.

[t.grd.zip](https://github.com/GenericMappingTools/gmt/files/8758738/t.grd.zip)

**Comment by joa-quim** [comment]
GMT's grdcontour is a memory and CPU hungry algo (it makes a grid copy and swaps the zero for each contour). 
One day it may change to use the [marching squares](https://en.wikipedia.org/wiki/Marching_squares). Not pretending that I understand it from the wiki figures but that's what is used by GDAL, so ... one day.

**Comment by PaulWessel** [comment]
Sure, we wrote **grdcontour** back in the day (1988?) so not much info to go by - we invented our own algo.  Of course it should be rewritten by anyone who has the time to do so!

**Comment by joa-quim** [comment]
Didn't mean to reinvent. Maybe see if we can *reuse* lib code that's available.

**Comment by anbj** [comment]
I remember I posted somewhere a comparison between contouring with **gdal_contour** versus **grdcontour**. I think the time difference in completing was several 10x's.
