### ISSUE TITLE
Mysteriously gmtbinstats is not working from Julia becasuse ...

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6748]
```
julia> G = gmtbinstats("@capitals.gmt", a="2=population", R=:g, I=5, C=:z, S="1000k", Vd=1)
        gmtbinstats @capitals.gmt  -I5 -Rg -a2=population -S1000k -Cz
ERROR: Programming error, output matrix is empty
```

Same example runs fine in command line.

But this one from the tests, which outputs a dataset, works

```
gmt("binstats hex_data.txt -R0/5/0/3 -I1 -Th -Ca")
```

**Comment by PaulWessel** [comment]
First time for everything. the API does this

```
	/* 1r. Check if gmtbinstats is doing hexagonal tiling */
	else if (!strncmp (module, "gmtbinstats", 11U)) {
		type = ((opt = GMT_Find_Option (API, 'T', *head)) && opt->arg[0] != 'r') ? 'D' : 'G';	/* Giving -T[h] means we change default output from grid to dataset */
	}

```
so presumably it defaults to G for grid as the module output.  and the module itself does

```
		if (GMT_Write_Data (API, GMT_IS_GRID, GMT_IS_FILE, GMT_IS_SURFACE, GMT_CONTAINER_AND_DATA, NULL, Ctrl->G.file, Grid) != GMT_NOERROR) {
			Return (API->error);
		}
```

So it is no different than any other module writing a grid, it seems.  So not sure where the handshake fails.

**Comment by joa-quim** [comment]
The shit happens inside the GMT_Write_Data ()
```
		if (GMT_Write_Data (API, GMT_IS_GRID, GMT_IS_FILE, GMT_IS_SURFACE, GMT_CONTAINER_AND_DATA, NULL, Ctrl->G.file, Grid) != GMT_NOERROR) {

it gets out here, but silently

			Return (API->error);
		}
```
Very hard to debug since Julia and VS decided to debug at 20 sec per line. And certainly not tonight.

**Comment by PaulWessel** [comment]
If G.file is NULL then no output file was specified from Julia, no? GMT_Encode_Options should end up with a -G? here to be replaced by a virtual file name.

**Comment by joa-quim** [comment]
Yep, that has to be the bug. No -G is set and hence ``G.file`` is NULL
