### ISSUE TITLE
Issue "x2sys_cross [ERROR]: Your -R and -G settings are contradicting each other!"

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6752]

**Comment by PaulWessel** [comment]
Not sure what you want here? You must have used -Rg during x2sys_init and then changed to -Rd or similar when running x2sys_cross?

**Comment by Esteban82** [comment]
I used the following commands and I get the following error: 
```
	gmt x2sys_init $TAG -Dgeoz -Etxt -G -F $R -I30
	gmt x2sys_cross -T$TAG =tmp_track.lis -Qe $R -Ia -Vi > tmp_outs.txt
```
	
The important messages in the terminal were: 
```
Got regular w/e/s/n for region (-65.4/-60.9/-54.2/-51.9)
x2sys_cross [ERROR]: Your -R and -G settings are contradicting each other!
x2sys_cross [ERROR]: Conflicting arguments [Surco]

```	

The second was intriguing because there is no `-G` argument for x2sys_cross. Then I realize (I think) that the -G refers to `x2sys_init`.  So maybe the error message could be improve.

**Comment by PaulWessel** [comment]
Sure, it could probably say

`x2sys_cross [ERROR]: Your -R  values are contradicting the -G setting from x2sys_init!
`

If you agree, perhaps you can try to make that change in x2sys.c?

**Comment by Esteban82** [comment]
Also, I just noticed that in the [synopsis of x2sys_cross](https://docs.generic-mapping-tools.org/dev/supplements/x2sys/x2sys_cross.html#synopsis) (in the docs), the `-R` argument is not present but then it is explain in `Optional Arguments`. Should I add it in the synopsis?

**Comment by Esteban82** [comment]
> Sure, it could probably say
> 
> `x2sys_cross [ERROR]: Your -R values are contradicting the -G setting from x2sys_init! `
> 
> If you agree, perhaps you can try to make that change in x2sys.c?

Ok, I will do it.

**Comment by PaulWessel** [comment]
yes, great we must have missed it.
