### ISSUE TITLE
gmt psscale keep annotation in left by default and even using -ma in GMT 5.4.4

### ISSUE THREAD

**Issue by piyushether** [GenericMappingTools/gmt#676]
**I am trying to place a vertical scale bar with my own color scale and annotation values in GMT 5.4.4. Instead of placing scale bar vertically default, it place horizontally also it place annotation of scale bar on let side by default instead of right. Even using "-ma" along with "D"  keeps annotation on left only. How one can resolve this?**

**Full script that generated the error**

```
      gmt gmtset MAP_FRAME_WIDTH=0.2p
      gmt gmtset FONT_ANNOT_PRIMARY=11p,Times-Roman,black
      gmt gmtset FONT_LABEL=11p,Times-Roman,black
      gmt gmtset FONT_TITLE=12p,Times-Roman,black
      gmt gmtset MAP_TICK_LENGTH_PRIMARY=1p/0.5p
      gmt gmtset MAP_FRAME_PEN=thinner,black
      gmt gmtset MAP_ANNOT_OFFSET_PRIMARY=1.5p
      gmt gmtset MAP_ANNOT_OFFSET_SECONDARY=2p
      gmt gmtset MAP_LABEL_OFFSET=5p
      gmt gmtset MAP_TITLE_OFFSET=2p
      gmt gmtset PS_CHAR_ENCODING=Standard+
      gmt gmtset DIR_DCW=/usr/share/gmt-dcw/

      rflg=-R17/30/0/20
      jflg=-Jx0.8/0.2
      pscl=-DjBC+o9/0.0i+w1.5i/0.2i+e+v
      x=-Bx2f1
      y=-By4f1
      
      
      echo 0	red ";N/A" > map1.cpt
      echo 1	blue ";clean air" >> map1.cpt
      echo 2	89/245/241 ";cloud" >> map1.cpt
      echo 3	255/132/9 ";aerosol" >> map1.cpt
      echo 4	yellow ";stratospheric layer" >> map1.cpt
      echo 5	102/255/51 ";surface" >> map1.cpt
      echo 6	178/178/178 ";subsurface" >> map1.cpt
      echo 7	black ";totally attenuated" >> map1.cpt
      echo B	white >> map1.cpt
      echo F	white >> map1.cpt
      echo N	white >> map1.cpt
      
      cat $in1 | awk '{print $7,$9,$10}' | gmt psxy $jflg $rflg $x $y+l"Altitude (km)" -BWSne+t"$title -Vertical Feature Mask"  -Cmap1.cpt -Ss0.5 -P -K -A -X2 -Y20 > $out
      gmt psscale $pscl $jflg $rflg -Cmap1.cpt -L -O -S -P -K >> $out
```

****

```
No Error
```

*Ubuntu 18.10:
* GMT 5.4.4:
![CAL_LID_L2_VFM-Standard-V4-20 2016-06-02T07-59-06ZD hdf](https://user-images.githubusercontent.com/24860227/57008906-fa87ef80-6c10-11e9-9376-5a089bfd49a0.jpg)

**Comment by piyushether** [comment]
>  Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. We appreciate that you took the time to contribute!
> 
> Please make sure you read our [Contributing Guide](https://github.com/GenericMappingTools/gmt/blob/master/CONTRIBUTING.md) and abide by our [Code of Conduct](https://github.com/GenericMappingTools/gmt/blob/master/CODE_OF_CONDUCT.md).

**Comment by PaulWessel** [comment]
Not sure why you closed this issue - did you solve it? Your example does show a vertical bar but you say it is horizontal.  Also, there is no -ma but +ma modifier for switching annotation side.  Let me know if this issues should be reopened.

**Comment by piyushether** [comment]
Hi...Paul.

Accidentally this issue has closed. It is not yet solved. 
As per given manual. GMT psscale place a vertical color bar by default but in my case it placed horizontally. Later I added "+v" to get vertical.
I am sorry for typo. I used "+ma" to switch annotation to opposite but it is not working and by default it is keeping on it's left only instead of right.

**Comment by PaulWessel** [comment]
I think when you use the -DJ mechanism it presets defaults so taht the scalebar is parallel to the selected side.  If you want it to look like your plot then you would use -DJRM, not CB since CB means center bottom and that presets horizontal.  Also, RM would preset annotations on the right side of the bar.  IT seems like you are fighting with the J setting by using offsets and +v etc etc instead of picking the correct justification RM.

**Comment by piyushether** [comment]
Thank you paul.
I will try your suggestion.
But I just want to add that this same justification settings (CB) with this script works fine for older version of GMT 5.3 in my windows system. Also, it was placing a annotation on right side.

**Comment by PaulWessel** [comment]
That is possible since we had several bugs in that whole and relatively new machinery.  It may have given you wnat you wanted but it was incorrect from our point of view.  For instance, our test/psscale/autoscale.sh tests all the inside and outside option of -DJ (place outside frame) and -Dj (place inside frame) and it looks like this:
![autoscale](https://user-images.githubusercontent.com/26473567/57054976-b823da00-6c33-11e9-86cf-21499bc4ccd4.jpg)

**Comment by piyushether** [comment]
Thank you Paul. 
I resolved an issue by using -DJRM.
Thank you again for point out my mistake.
