### ISSUE TITLE
Hexagonal prisms

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6762]
Now that we have hexagonal binning in ``gmtbinstats`` and can plot them with ``plot``, it would be cool to have hexagonal prisms (plus spheres, 3d arrow cone heads) in postscript so that could walk on giants heads

![image](https://user-images.githubusercontent.com/537321/171039567-ed4567cb-a790-4c3d-bd82-ff4db41012da.png)

**Comment by PaulWessel** [comment]
I have plans for 3-D shaded spheres and ellipsoids but I also plan to stay laser-focused on my research this summer and only do new things as I personally need them.  I have PostScript example of a shaded sphere and finally got the PostSCript Level 3 book that discusses the improved shading models.  This will lead to a rewrite in grdview, for instance, but not very soon.
