### ISSUE TITLE
Fancy frame leaves tiny notches at corners due to lack of connection

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#677]
**Description of the problem**

With a fancy frame the outer perimeter is not a polygon but is plotted as 4 straight lines, thus the join settings leave a notch where they meet.

**Full script that generated the error**

```
gmt psbasemap -R180/200/-5/5 -JM4i -Baf -P > t.ps
```

It is only visible when zooming in.  Here is an example (see upper left map corner):

![imgmap](https://user-images.githubusercontent.com/26473567/57043005-04562680-6c02-11e9-8800-eb1de122856e.jpg)

The solution is to connect the perimeter segments into a complete polygon before plotting, as is done for plain map frames.

**Comment by seisman** [comment]
The same issue exists for polar projections. For example:
```
gmt basemap -JP8.0c -R0/90/0/10 -B0 -pdf map
```
![image](https://user-images.githubusercontent.com/3974108/91787261-72847200-ebd7-11ea-809a-e45c75e4dc26.png)

**Comment by PaulWessel** [comment]
Thanks, yes a bit tedious to fix but not super-important yet.

**Comment by joa-quim** [comment]
Yep, too tedious to be addressed.
