### ISSUE TITLE
$GMT_DATADIR is not picked up by gmt

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6770]
See [this](https://forum.generic-mapping-tools.org/t/how-to-set-datadir-and-see-all-environment-variables/2994) forum post for background.

A path set with `$GMT_DATADIR` will not be set in ``gmt --show-datadir``. `gmt set DIR_DATA=/data` will. According to the [cookbook](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#directory-parameters) both of these should work, and `DIR_DATA` will [override](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-DIR_DATA) the `$GMT_DATADIR` environment variable.

```
$ gmt --show-datadir
Not set
$ GMT_DATADIR=/data
$ echo $GMT_DATADIR
/data
$ gmt --show-datadir
Not set
$ gmt set DIR_DATA=/data
$ gmt --show-datadir
/data
```

So, ``gmt --show-datadir`` should report the path set by `$GMT_DATADIR`, but it does not.

**Comment by seisman** [comment]
I think you have to use `export GMT_DATADIR=/data` to define an environment variable.

**Comment by joa-quim** [comment]
That's what I was about to say
```
C:\Users\joaqu>set GMT_DATADIR=c:/j

C:\Users\joaqu>gmt --show-datadir
c:/j
```

**Comment by anbj** [comment]
> I think you have to use `export GMT_DATADIR=/data` to define an environment variable.

You're absolutely right @seisman. Strange, I didn't think `export` was needed; doesn't gmt pick it up from the current shell?

Also funny,

```
$ GMT_DATADIR=/var
$ gmt --show-datadir
Not set
export GMT_DATADIR=/var
gmt --show-datadir
/var
$ GMT_DATADIR=/var/log
$ gmt --show-datadir
/var/log
```

So setting `GMT_DATADIR` without export does nothing ("Not set"). Do it again, with `export` and it's been "initialized" - now you don't need to put `export` in front of it if you want to change the path.

Also, does anyone know where this environment variable is stored?
I thought it would be in the list created by `env`, but no;

```
$ GMT_DATADIR=/
$ env | grep -i gmt
PATH=/home/anbj/gems/bin:/home/anbj/gmt/build/bin:/home/anbj/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/anbj/.local/bin
```

**Comment by joa-quim** [comment]
```
j@Marilu:~$ export BLA=blabla
j@Marilu:~$ printenv | grep BLA
BLA=blabla

j@Marilu:~$ BLE=bleble
j@Marilu:~$ printenv | grep BLE
```

**Comment by anbj** [comment]
Thanks for the help and illustration.
So where are non-exported variables stored, or how to show them..

Closing.

**Comment by PaulWessel** [comment]
See [here](https://unix.stackexchange.com/questions/176001/how-can-i-list-all-shell-variables), especially at the very end.

**Comment by anbj** [comment]
Thanks Paul.
