### ISSUE TITLE
Improve description of table operators in gmt/grd math modules

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6778]
As I have suggested [here](https://github.com/GenericMappingTools/gmt/discussions/4678#discussioncomment-606312) I want to improve the description of the [math operators](https://docs.generic-mapping-tools.org/dev/gmtmath.html#operators).  I will work on this. It can wait until gmt 6.5.

I open this issue so you know I am working on it, and more important to ask some doubts. Any suggestions is welcome. 

I am planning to:

1. Improve the description of the `Return` column 
2. Add a link to [DLMF]( https://dlmf.nist.gov/) for complex functions.

**Comment by Esteban82** [comment]
I am thinking of adding a new column with the type of formula (like trigonometric, logic, basic math, statistical, etc). I think it would help the users. 

Is there any way to add a filter in the table (so I could ask to only show the trigonometric formulas) or to sort it?

**Comment by seisman** [comment]
> Is there any way to add a filter in the table (so I could ask to only show the trigonometric formulas) or to sort it?

Sphinx doesn't support it, but it's possible to enable filtering/sorting with [this extension](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needtable.html).

**Comment by Esteban82** [comment]
I create a table in [google docs](https://docs.google.com/spreadsheets/d/1kLIWXPxMsqNU_1WB9fu9zT30ayL8VPS-NwFDwfEkQ9E/edit?usp=sharing) with the info of the table.

There I add a new column with the `Type of Function`. For some cells (highligthed in color), I am not sure what to put (e.g. Psi (or Digamma) of A). I also add a more detailed version for the `return` column to replace the orignal. There is also a column with wikepedia and https://dlmf.nist.gov/idx/ links but that is WIP.

Let me know if you prefer that I post my doubts directly here.

**Comment by PaulWessel** [comment]
Nice start, @Esteban82.  I have some comments:

1. I would lump probability distributions, statistical, combinatorics, **LMSSCL** etc etc into a single category: Probability
2. All the crazy math functions (Bessel, Kelvin, Dilog, Legendre etc) I would place in category: Special Functions (that is how they are often referred to in math books, for instance).
3. I think some of the **BIT** operators should go into Logic (**AND**, **NOT**, **OR**, **TEST**, **XOR**) and the rest (**LEFT**, **RIGHT**) goes into Arithmetic. Computer Programming is too specific.
4. What you have as conversion and stack operations, `Ax = b` solvers,  etc I would lump together into Special Operators

That would give these six categories

- Arithmetic
- Calculus
- Probability
- Logic
- Special Functions
- Special Operators

This is usually when we dust off @WalterHFSmith to see if he can come up with better categories!

**Comment by Esteban82** [comment]
Ok. I will wait if Walter has something to add.

**Comment by WalterHFSmith** [comment]
I replied August 12 that it sounded good to me. Did you not get that email?

W

**Comment by WalterHFSmith** [comment]
Sounds good to me!

W

**Comment by Esteban82** [comment]
Finally I got some time to do this. 

I have a doubt:
1. sinc is a special function?

**Comment by PaulWessel** [comment]
Hm, good question.  I think so even though it is pretty simple.

**Comment by Esteban82** [comment]
Thanks Walter.

**Comment by WalterHFSmith** [comment]
Fortunately the series is an alternating one, so you know the error is smaller than the first term you skip.

**Comment by Esteban82** [comment]
Now I am working on the **grdmath** docs. I am adding the types of functions. 

I am using the same type of function from `gmtmath` when the have the exactly same same (which are most of them).

For the rest, I have some doubts.
There are some functions that have a similar in the `gmtmath docs` (like `DDX/DDY`, `ROTX/ROTY` and `STEPX/STEY` instead of `DDT`, `ROTT` and `STEPT`).  In this case, should I assing the same type of function?

**Comment by joa-quim** [comment]
Yes, they are the same functions.

**Comment by Esteban82** [comment]
Another doubt:

In grdmath there is CUMSUM, but in gmtmath is SUM. Boths are cumulative sum. 

I understand that are the same function but with differents names. I think that we should use a similar name for both docs. Do you agree? If so, what name should we keep?

**Comment by Esteban82** [comment]
Here I group the functions that do not appear in gmt math. 

What do you think about the groups? and the names? I am not sure to use `grid` in the names. 

Arithmetic: **ARC**, **DOT**, **POINT**
Grid calculus: **EXTREME**, **SADDLE**
Special Grid operator: **CAZ**, **CBAZ**, **CDIST**, **CDIST2**, **LDIST**, **LDIST2**, **LDISTG**, **PDIST**, **PDIST2**, **SDIST**, **SDIST2**, **SAZ**, **SBAZ**,  **AREA**, **BLEND**. **DAYNIGHT**, **INSIDE**. **TRIM**, **WRAP**
Special Grid Functions: **YLM**, **YLMg**

**Comment by PaulWessel** [comment]
> Another doubt:
> 
> In grdmath there is CUMSUM, but in gmtmath is SUM. Boths are cumulative sum.
> 
> I understand that are the same function but with differents names. I think that we should use a similar name for both docs. Do you agree? If so, what name should we keep?

Well, **grdmath** has both **CUMSUM** and **SUM**.  The latter is like in **gmtmath**, hence the same name, but **CUMSUM** takes an arg and does different things.

**Comment by Esteban82** [comment]
> Maybe the **CAZ,** etc are more geometric in nature?

Yes, maybe but I my idea was to used the same categories of gmt math. So, I should use `Calculus `instead, right?

Six types of categories of gmt math:
- Arithmetic
- Calculus
- Probability
- Logic
- Special Functions
- Special Operators

**Comment by PaulWessel** [comment]
I am OK with your plan. Thanks for doing this.

**Comment by Esteban82** [comment]
> Since you always operate on grids

Also `POINT`? 

> The operator POINT reads a ASCII table, computes the mean x and mean y values and places these on the stack.

Wouldn't it be better in `gmt math`?

**Comment by PaulWessel** [comment]
Only sensible use of POINT is to set a Lon lat point then call  another operator
