### ISSUE TITLE
Do we really want these warnings?

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6781]
While creating example figures for GMT.jl I get

```
pscoast [WARNING]: 9 annotations along the right border were skipped due to crowding.
pscoast [WARNING]: 8 annotations along the left border were skipped due to crowding.
pscoast [WARNING]: Crowding decisions is controlled by MAP_ANNOT_MIN_SPACING, currently set to 0.65.
pscoast [WARNING]: Decrease or increase MAP_ANNOT_MIN_SPACING to see more or fewer annotations, with 0 showing all annotations.
```
Those are a bit annoying as they bring nothing really useful as a warning. I think they should be moved to -Vi.

**Comment by PaulWessel** [comment]
Agreed, pls make the change

Paul Wessel
Professor, Department of Earth Sciences
(808) 956-4778 | ***@***.***
http://www.soest.hawaii.edu/earthsciences

**Comment by PaulWessel** [comment]
Agreed, pls make the change

Paul Wessel
Professor, Department of Earth Sciences
(808) 956-4778 | ***@***.***
http://www.soest.hawaii.edu/earthsciences
