### ISSUE TITLE
Improve one-line command for grdimage and categorical cpt

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6791]
I made two figures of southern Finland with a one-liner code for categorical grids. 

```
gmt grdimage @earth_mask -png mask  -JM15c -Baf -R19/32/60/63
gmt grdimage @earth_mask -png mask2 -JM15c -Baf -R19/32/60/63 -Ccategorical
```

For the second line I got hundres of these two messages and the figure is wrong. 
grdimage [WARNING]: Requested color lookup for z = 1 is not a categorical value - returning NaN color
grdimage [WARNING]: Requested color lookup for z = 0 is not a categorical value - returning NaN color
`

![mask](https://user-images.githubusercontent.com/17908951/173234603-00b44f33-83d9-4b45-88c5-e577c71405df.png)

![mask2](https://user-images.githubusercontent.com/17908951/173234669-bd89bb40-ab08-424e-acc9-517f8a1709e2.png)

**Comment by PaulWessel** [comment]
Not sure what we should do here.  We may need to flag categorical CPTs so they can be handled better.  In the first case, the turbo CPT is scaled to the data range (0-4) and all is well.  In the categorical case the same happens: 256 categorical colors are stretched to 0-4.  However, what you want is the first 4 colors.  There is no way to automate that unless we use some special flag under the hood.  The intent with this CPT was to pull out the first N:

`gmt makecpt -Ccategorical -T0/5/1 > my.cpt`

and then use that

`gmt grdimage @earth_mask -png mask2 -JM15c -Baf -R19/32/60/63 -Cmy.cpt      `

**Comment by Esteban82** [comment]
Yes, I was thinking something under the hood for the special case of `-Ccategorical` and one-liner. But maybe I am being too lazy. I don't think it's worth the effort.

**Comment by PaulWessel** [comment]
Again, the lowest bar is to improve the documentation to explain how to use this CPT.
