### ISSUE TITLE
No tight bounding box with -ps,png

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#6792]
In the following code, if I only specified a png format, then I got a figure with a nice tight bounding box. 
But when I also ask for a `ps`, then the png file has NO tight bounding box. 

`gmt basemap -R0/9/0/5 -Jx1c -Bf1a2 -Bx+lDistance -By+l"No of samples" -BWeSn -png,ps linear`

![linear](https://user-images.githubusercontent.com/17908951/173268890-a221cf3b-4aff-483c-9ece-f32416d2d704.png)

**Comment by meghanrjones** [comment]
Just a note that this issue occurs in both 6.3 and the main branch, so it's not a regression that needs to be fixed before 6.4.

**Comment by PaulWessel** [comment]
This can probably be fixed, but remember ps is not a format with a tight bounding box, eps is.

**Comment by Esteban82** [comment]
> This can probably be fixed, but remember ps is not a format with a tight bounding box, eps is.

Right. I want the original ps and the png with tight bounding box.

**Comment by Esteban82** [comment]
Ok. It is fine by me.

**Comment by PaulWessel** [comment]
I have updated the explanation given in gmt begin.
