### ISSUE TITLE
There is something wrong in the CookBook's Missipy histogram examples

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6794]
In [first case ](https://docs.generic-mapping-tools.org/dev/cookbook/options.html#gmt-cycle-3) the peak is in Mars whilst on the [vertical version](https://docs.generic-mapping-tools.org/dev/_images/GMT_cycle_4.png) the peak is in May. Also, in this version the *yy* coordinates have not the same phase in both subplots thus giving the impression that the maximum of the histogram is offset with respect to the normalized year river discharges.

**Comment by PaulWessel** [comment]
I think you are not looking at the vertical plot correctly: Match is the peak in both histogram.  Look again.

Your point about the yy and subplot is correct though.  But not a bug, just not ideal.

**Comment by joa-quim** [comment]
After bending more the head, yes, you're right sorry.
Not so important the off-phase so closing this to not accumulate issues.
