### ISSUE TITLE
Additional directives to -M in makecpt

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#6797]
In makecpt, the -M option, when combined with -D, only COLOR_NAN can be considered. This request is to permit additional directives to -M so as to be able to specify which color parameter (BACKGROUND, FOREGROUND or NAN) is to be overridden.

Paul's suggestion (in the GMT Forum) is something like this: add directives to -M so that it only applies to a subset of B, F, N. E.g. -M[b][f][n], where -M (no args) would mean -Mbfn (affect all of them).

This request was made because there are times when a user may want to have color control over just two elements (e.g., BACKGROUND AND NAN), while permitting FOREGROUND to be overridden with the -D option, that permits the user to select the foreground color to match the colors for highest z-values.

**Are you willing to help implement and maintain this feature?** No, but happy to test it.

**Comment by joa-quim** [comment]
Closing as not planed.
