### ISSUE TITLE
Revise gmt5syntax.in and add documentation

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#6806]
This perl script which is configured by CMake and ends up as the program _gmt5syntax_ in share/tools can be used to translate old GMT4 scripts to modern syntax (basically, prepending gmt to commands missing it).  There seems to be a couple of issues related to this script:

1. The documentation on [Migration](https://docs.generic-mapping-tools.org/6.4/migrating.html) has no mention of it yet it seems like a great solution to help people convert to GMT6 classic syntax.
2. The name (gmt5...) is unfortunate.

I suggest the following changes:

1. Rename the script to something without gmt5 in it, e.g., _convertgmt4_, others?)
2. Add a paragraph on this in the Migration section.

We should probably also give it a shot and maybe even show its effect on a small GMT4 script in that section.

**Comment by joa-quim** [comment]
Very low priority I think.
