### ISSUE TITLE
Present MAP_ANNOT_OBLIQUE keywords in table

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6812]
Listing and description of the different [MAP_ANNOT_OBLIQUE keywords](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-MAP_ANNOT_OBLIQUE) would be better presented in a table in my opinion. Thoughts?

I'll do this when time permits if you agree.

**Comment by meghanrjones** [comment]
What happens if you delete the build directory and build from scratch?

**Comment by anbj** [comment]
I’m fairly sure I tried that, but will try again.

**Comment by PaulWessel** [comment]
Should pull from dvc first, just like you make sure you are on master gmt git before doing things there.

**Comment by anbj** [comment]
Thanks @PaulWessel and @meghanrjones.

My mistake, same as last time (I think), is that my build directory is *not* inside the cloned gmt repo.

**Comment by anbj** [comment]
Done in #6814.
