### ISSUE TITLE
MAP_FRAME_TYPE=graph centered on {0,0}

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#6820]
Would it be possible to add an option to have this : 

```
gmt begin test png
gmt basemap -R-1/1/-1/1 -JX10c -Bafg --MAP_FRAME_PEN=0p
gmt basemap -Bb --MAP_FRAME_TYPE=graph -Y5c
gmt basemap -Bl --MAP_FRAME_TYPE=graph -Y-5c -X5c
gmt end show
```
![test](https://user-images.githubusercontent.com/74073266/175363553-32767e8c-3187-4f42-ad5c-9665615d4aa6.png)

By parsing this simple parameter : 
```
gmt basemap -R-1/1/-1/1 -JX10c -Bafg --MAP_FRAME_TYPE=graph,centered -png result
```

Best,
Guillaume

cf [forum](https://forum.generic-mapping-tools.org/t/shading-between-2-curves/3044)

**Comment by PaulWessel** [comment]
I've had this need myself so it is very likely this will happen in one form or the other.
