### ISSUE TITLE
Taylor Diagram

### ISSUE THREAD

**Issue by andrebelem** [GenericMappingTools/gmt#6821]
In a recently submitted work, I received a comment from a reviewer like this "your maps are excellent! It would be nice to keep the same graphic quality in the Taylor Diagram".
<p align='center'>
<img src="https://cdat.llnl.gov/cdat/vcdat/images/Taylor_diagram_details.jpg" width=400p />
</p>

It's nice to know that maps made with GMT/PyGMT are immediately recognized for their quality. And while pythonic solutions for Taylor Diagram already exist, it would be very interesting to have something like this in GMT (for reference, this tutorial - https://cdat.llnl.gov/Jupyter-notebooks/vcs/Taylor_Diagrams/Taylor_Diagrams.html, although there are others. But this one clearly demonstrates how the construction is done) for its possible use via shell scripting.

I can help build and maintain if any of the more experienced developers are at the forefront. So I can also learn how this management is done.

**Comment by PaulWessel** [comment]
Best bet would be a seismologist with coding skills to take charge of this.  It is too much for me to code up someone else's research needs, but I could help.  Probably start with a copy of pspolar.c and make all the changes needed.

**Comment by andrebelem** [comment]
Nice. I'll check the code too. I'm going to try to pythonize something so that the workflow in C programming is clearer. It's been a while since I've programmed in C but they say it's like riding a bicycle. Hope so. :)

**Comment by joa-quim** [comment]
Don't think this will be implemented anytime soon, so I'm closing this.
