### ISSUE TITLE
Improve the debug message about the default projection

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6855]
When running a command like `gmt coast -RJP -W1p -pdf map -Vd`, the debug message says:

```
gmt [DEBUG]: Modern: Adding -JQ15c+ to options since there is no history available.
gmt [DEBUG]: Revised options: -RJP -W1p -Vd -JQ15c+
coast [DEBUG]: History: Process -RJP
coast [DEBUG]: History: Process -JQ15c+
```

`-JQ15c+` is the old syntax so it's a little misleading. The new syntax should be `-JQ15c+du` (or maybe `-JQ15c+dw`).

**Comment by joa-quim** [comment]
We can change the line 15658 to

![image](https://user-images.githubusercontent.com/537321/218284784-f56873dd-7636-4a4b-979f-ea3baca38dfa.png)

``snprintf (scl, GMT_LEN64, "Q15c+du");``

Will that make a difference?

**Comment by joa-quim** [comment]
Change or close?

**Comment by seisman** [comment]
> We can change the line 15658 to
> 
> ![image](https://user-images.githubusercontent.com/537321/218284784-f56873dd-7636-4a4b-979f-ea3baca38dfa.png)
> 
> `snprintf (scl, GMT_LEN64, "Q15c+du");`
> 
> Will that make a difference?

Sounds good.
