### ISSUE TITLE
Drop support for 32 bit windows installer

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#6857]
**Description of the problem**
Based on the discussion at https://github.com/GenericMappingTools/gmt-for-geodesy/issues/26, it may be time to stop providing a 32 bit windows installer. If we chose to drop support, we should document the change and remove it from the relevant admin scripts and issue templates.

**Comment by joa-quim** [comment]
We may drop distributing the 32 bits installer but I keep needing the 32 bits build.

**Comment by maxrjones** [comment]
Yes, this wouldn't involve any changes to cmake files. Just dropping the 32 bits steps from e.g., https://github.com/GenericMappingTools/gmt/blob/master/admin/place-release.sh, https://github.com/GenericMappingTools/gmt/blob/master/.github/workflows/draft-release.yml and your pre-release efforts.

**Comment by joa-quim** [comment]
Ah, ok. The 32 builds installer has always been a headache for me because ``cpack`` is bugged and picks some wrong bitage dependencies (64 bits versions) and I always have to remember to hide them so they aren't picked instead of the correct ones.
