### ISSUE TITLE
psxy -SC and -ST not documented

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#686]
CookBook's example 18 uses ``-SC0.04i`` and ``-ST0.1i`` but neither ``-SC`` or ``-ST`` is documented in ``psxy`` doc.

**Comment by PaulWessel** [comment]
Not true.  Per psxy man page under **-S**:

> The uppercase symbols A, C, D, G, H, I, N, S, T are normalized to have the same area as a circle with diameter size, while the size of the corresponding lowercase symbols refers to the diameter of a circumscribed circle.

**Comment by joa-quim** [comment]
I knew I had read that already ... but -S option is soooo big that those lines are several screens up when we are reading the, for example, -St.
