### ISSUE TITLE
Add tests for dcw collections

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#6864]
**Description of the desired feature**

We should add tests for the dcw collections feature implemented in https://github.com/GenericMappingTools/gmt/pull/6064, based on recent reports that collections do not work on all platforms.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by joa-quim** [comment]
Well, yes we should but we should also close issues that are not getting attention. Close this?

**Comment by Esteban82** [comment]
In #8318 Paul add a this test ([dcw-180-crossers.sh](https://github.com/GenericMappingTools/gmt/blob/master/test/grdimage/dcw-180-crossers.sh)) that uses DCW. 

So, I think that we can close this.
