### ISSUE TITLE
Improve the template script generated by "gmt --new-script"?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6867]
Here is the template script on macOS:
```
#!/usr/bin/env -S bash -e
set -e
# GMT modern mode bash template
# Date:    2022-07-09T22:22:46
# User:    seisman
# Purpose: Purpose of this script
export GMT_SESSION_NAME=$$	# Set a unique session name
gmt begin figurename
	# Place modern session commands here
gmt end show
```
The `set -e` line is put between the shebang line and comment lines, which looks a little odd to me.

I prefer to move it after the comment lines instead:
```
#!/usr/bin/env -S bash -e
# GMT modern mode bash template
# Date:    2022-07-09T22:22:46
# User:    seisman
# Purpose: Purpose of this script
set -e
export GMT_SESSION_NAME=$$	# Set a unique session name
gmt begin figurename
	# Place modern session commands here
gmt end show
```

**Comment by PaulWessel** [comment]
I think it used to be there but something was not working and I changed it.  I wish I wrote a comment somewhere for that as I cannot recall the reason.  I agree with you of course.  If you find that it was always that way then I may be dreaming and happy to approve...

**Comment by seisman** [comment]
The `set -e` line was added in PR https://github.com/GenericMappingTools/gmt/pull/6119/files. It was added between the shebang and the comment lines and the position was not changed after that.

I've tried the following two scripts:

Without `set -e`, the script doesn't stop on errors so we can't see the error message for `gmt coast`:
```
#!/usr/bin/env -S bash -e
# GMT modern mode bash template
# Date:    2022-07-10T13:36:09
# User:    seisman
# Purpose: Purpose of this script
export GMT_SESSION_NAME=$$	# Set a unique session name
gmt begin figurename
    gmt coast -Rg -JH10c -Baf
    echo 10 10 | gmt plot -Sc0.2c -Gred
gmt end show
```

Putting `set -e` at the beginning of the script works. The script stops at the "coast" command and reports the coast error:
```
#!/usr/bin/env -S bash -e
# GMT modern mode bash template
# Date:    2022-07-10T13:36:09
# User:    seisman
# Purpose: Purpose of this script
set -e
export GMT_SESSION_NAME=$$	# Set a unique session name
gmt begin figurename
    gmt coast -Rg -JH10c -Baf
    echo 10 10 | gmt plot -Sc0.2c -Gred
	# Place modern session commands here
gmt end show
```
On the other hand, putting `set -e` after the comments works the same way as the current GMT template script.

**Comment by PaulWessel** [comment]
The shebang -e only works for me on macos now so perhaps there was a bash bug that got fixed?

**Comment by seisman** [comment]
This is my bash version on macOS 12.3.1. 
```
$ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by PaulWessel** [comment]
I see, so I now have bash from GNU, probably required by some other package:

```
 bash --version
GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

So that is why it works for me now but earlier I had the same bash as you - a crippled old apple version from 2007?.  I agree that moving set -e to after the comments is better anyway.
