### ISSUE TITLE
IDP.Generic alarm during runtime only

### ISSUE THREAD

**Issue by Xhosant** [GenericMappingTools/gmt#6876]
[

**Description of the problem**
During runtime (of example .bat 01, especially) Avast kicks up an alert, as described here: https://forum.avast.com/index.php?topic=320305.0

I assume, false positive or not (and it's most certainly not), you might be interested in knowing!

**Full script that generated the error**

```
N/A
```

**Full error message**

```
N/A (or 'We've blocked gmt.exe because it was infected with IDP.Generic')
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system: Widnows 10, 64-bit
* GMT version (`gmt --version`): 6.4.0
]

**Comment by joa-quim** [comment]
Hi,
This is clearly an Avast problem, not GMT's so I'm going to close this issue.
And, if you allow me an ...opinion. Get rid of Avast. The Windows defender is better and causes way less problems.
