### ISSUE TITLE
coast -E: map legend and plotting all states

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6885]
What about

* adding an option to [add a map legend entry](https://docs.generic-mapping-tools.org/dev/gmt.html#l-full) in [coast -E](https://docs.generic-mapping-tools.org/dev/coast.html#e).
E.g. ``coast -EUS+x"The United States of America"``.
Too bad ``+l`` is already taken.
* adding a way to plot all states, e.g. ``-EUS.*`` without having to explicitly name all.

**Comment by PaulWessel** [comment]
Not sure about that.  While I might understand why it could be useful to label "Botswana" in a legend, in general people ought to know basic geography.  It is getting close to the labeling of the longitude with a label that says "longitude".  I dont like those types of things.  But I will sleep a few weeks on it.  The -l would be used since we would not apply it to the -W -G -S -C -I -N settings I think, so only -E would make (maybe) sense.

**Comment by anbj** [comment]
Yes, I do tend to agree.

My example is also poor. The real usage would be in groups of countries, e.g.

* ``-E[country codes] -l"Countries that have signed the Svalbard Treaty"`` or
* ``-E[country codes] -l"OPEC countries"``
* ``-E[country codes] -l"NATO"``
* etc.

Since one can include many ``-E``'s in one ``pscoast`` call, that would make it necessary to be able to include a ``-l"legend`` (or equivalent) for each ``-E``.

**Comment by anbj** [comment]
Today I wanted to make a plot using dcw instead of gshhg, but no way (as I know of) to plot all countries within my given region without specifying each countrycode (you could use *continent*, but still). So a useful feature would be to have some way of wildcard/asterisk plotting everything that is within the region. Similar to the ‘plot all states’ in my original post.

**Comment by PaulWessel** [comment]
I understand. The real solution is to build GSHHG 3 at some point and then it can be built knowing these needs.  I hesitate to add a bunch of code (and time) for features that will have to be reinvented when we do GSHH3.  The next months will also be a busy (busier) time for me until we have settled in up in Nittedal.  If you attend the community zoom on Thursday you will learn about some of that!

**Comment by anbj** [comment]
Yes; I understand. Time is valuable. Closing.

Exciting news!

**Comment by anbj** [comment]
Just encountered a need for this again, I would like to do:

```
gmt begin nato
  gmt grdimage @earth_relief_10m -JS0/90/20c
  gmt coast -Enato+gblack@50 -l"nato"
  gmt coast -ERU+gred -l"no-nato"
gmt end show
```
This deviates a bit from my original suggestion of having a label per country code.
What about the use of ``-l`` in the script above?

**Comment by anbj** [comment]
Closing again.
