### ISSUE TITLE
Error in downloading remote data when environmental variable TEMP has multiple paths

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6887]
A user reported the following error when downloading the remote dataset.
```
gmt [ERROR]: Failed to create lock file C:\Users\bc-THINK\AppData\Local\Temp;C:\WINDOWS\TEMP;/gmt_data_server.txt.download
```
It seems the error is because the env variable `TEMP` has multiple paths. 

The user doesn't provide more information to me, so it's unclear which version he's using.

**Comment by PaulWessel** [comment]
How does it make sense to have a list of directories for temp files? Are applications expected to see if there is enough space (which may not be knowable) and use the first or move on?  We can add a check for this but I would think this is a screw up of the user.

**Comment by joa-quim** [comment]
It makes no sense to me either. Don’t think we should change anything because of it.

**Comment by seisman** [comment]
I agree! Closing.
