### ISSUE TITLE
externals crash when reading time column

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#689]
This (from ex21), crashes

```
julia> wesn = gmtinfo("@RHAT_price.csv", f=:T, inc=50, per_column=true,  par=(:FORMAT_DATE_IN, "dd-o-yy"), Vd=1)
" --FORMAT_DATE_IN=dd-o-yy -fT -C -I50"        # Effective command run
```
Same runs fine on command line
```
gmtinfo -fT -I50 -C @RHAT_price.csv --FORMAT_DATE_IN=dd-o-yy
```
Deep debug diving (but not deep enough) shows that in command line ``GMT->current.io.col_type[0][0] == GMT_IS_ABSTIME`` but that is not the case from the external calls and as a consequence ``ncols`` remains = 0 and ``xyzmin``, etc is not allocated and the crash happens when they are accessed.

**Comment by PaulWessel** [comment]
I think that example runs in gmtmex, no?

**Comment by joa-quim** [comment]
Yes, it runs as written in _gallery.m_ but can make it crash as well if we call it like this (which is, for good or bad, what the Julia wrapper does by default)
```
D = gmtmex('gmtread @RHAT_price.csv -Td')
I = gmtmex('gmtinfo --FORMAT_DATE_IN=dd-o-yy -fT -C -I50', D)
```

**Comment by PaulWessel** [comment]
Presumably the --FORMAT statement would go on the first line since there is no ascii reading in the second?  And the -fT  needs to go in the first I think, but perhaps -ft in the second?

**Comment by joa-quim** [comment]
Maybe, but it should not crash in the example above. It seems that --FORMAT info is not yet present when it tries to read the string record (in 
```
GMT_LOCAL unsigned int gmtio_examine_current_record (struct GMT_CTRL *GMT, char *record, size_t *tpos, uint64_t *n_columns) {
```

Also, there is a difference in how the result is shown in the shell and from externals
```
gmtinfo -fT -I50 -C @RHAT_price.csv --FORMAT_DATE_IN=dd-o-yy
1999-08-11T00:00:00     2007-12-31T00:00:00     0       300     3.12    302.63  2.4     272     3.02    286.25  207200  113183400       3.02    143.12
```

bur from mex the dates above are shown in numeric form
```
gmtmex('gmtinfo @RHAT_price.csv  --FORMAT_DATE_IN=dd-o-yy -fT -C -I50')

ans = 

  struct with fields:

       data: [934329600 1.1991e+09 0 300 3.12 302.63 2.4 272 3.02 286.25 207200 113183400 3.02 143.12]
       text: []
       ...
```

**Comment by PaulWessel** [comment]
Well , they are the same of course (the data internally are numeric 9343.... in seconds since epoch.  It is only when gmtinfo prints this to the screen that we format back knowing the data type to ascii.  So in mex if we really wanted that column to be something like a mex representation of time (probably some structure?) then that gets messy.  Better for uses who need absolute time to convert from relative time to absolute time using mex functions.

**Comment by PaulWessel** [comment]
D = gmtmex('gmtread @RHAT_price.csv -Td --FORMAT_DATE_IN=dd-o-yy -fT')
I = gmtmex('gmtinfo -C -I50', D)

works fine for me. Without the -fT the datestring is seen as trailing text and everything is returned as text.  So then gminfo comes around working on a [] data set and that does not end well.  Too late to add the --FORMAT then when there is only trailing text to read.

**Comment by joa-quim** [comment]
But it should not crash.
And why is it too late to add the --FORMAT? From the debugging, only thing that changes with respect to command line is that at ``gmtio_examine_current_record ()``,   ``GMT->current.io.col_type[0][0]`` know that it's reading a ``GMT_IS_ABSTIME`` (command line) but not from externals.

**Comment by PaulWessel** [comment]
Of course nothing should crash. It is too late to supply --FORMAT since you already have read the ascii table into memory.  There is no dd-o-yy string in memory for you to decode from D.  It has already happened and you now have seconds since epoch.  Why would --FORMAT mean anything to that?  If you run the initial gmtread example you will see that D.data is empty and D.text has all records as trailing text.  We do not decode trailing text, it is just text.

**Comment by PaulWessel** [comment]
Looks like the Julia wrapper needs to simply move the --FORMAT and -fT arguments to the read part and then it will be OK.

**Comment by joa-quim** [comment]
I'm telling you that is not what happens. When it land in ``gmtio_examine_current_record (struct GMT_CTRL *GMT, char *record, size_t *tpos, uint64_t *n_columns)`` the ``*record`` is exactly the same whether we are running from  shell or from Julia. It's only that from shell it goes into (see image)
```
	phys_col_type = gmtio_physical_coltype (GMT, col);
		if (phys_col_type == GMT_IS_ABSTIME || gmtlib_maybe_abstime (GMT, token, &no_T)) {
```
but from Julia it goes to the other branch and than tries to decode the date string as numeric and a NaN comes out. In consequence n_columns = 0 and the crash follows. 
Now Matlab wants to complicate it and crash in a way that I have not yet found why (and little patience to insist).
![Capture](https://user-images.githubusercontent.com/537321/57262226-2f59d380-7063-11e9-9770-9b302912d56e.JPG)

**Comment by joa-quim** [comment]
Regarding your other comment, that's not how it works. I use generic functions, which is what allows me that the gmtinfo wrapper is as small as this
```
function grdinfo(cmd0::String="", arg1=nothing; kwargs...)

	length(kwargs) == 0 && !isa(arg1, GMTgrid) && return monolitic("grdinfo", cmd0, arg1)

	d = KW(kwargs)
	cmd = parse_common_opts(d, "", [:R :V_params :f])
	cmd = parse_these_opts(cmd, d, [[:C :numeric], [:D :tiles], [:F], [:I :nearest_multiple],
				[:L :force_scan], [:M :minmax_pos], [:T :zmin_max]])

	common_grd(d, cmd0, cmd, "grdinfo ", arg1)		# Finish build cmd and run it
end

I actually solved it by imposing a question that when -R does not need to be determined the ``comon_grd()`` function does not read the input file and let gmtinfo do it. This solves this issue but the one when we do it in to steps (gmtread + gmtinfo)
```

**Comment by joa-quim** [comment]
OK, found that the screen capture above refers to the situation where the Julia wrapper first reads the file without any -fT --FORMAT (it could not know that it had to use it).

I'll submit just a PR to prevent the crash and than we can close this one.
