### ISSUE TITLE
Legend in plot3d

### ISSUE THREAD

**Issue by andrebelem** [GenericMappingTools/gmt#6896]
When plotting simple fixed-size cubes with plot3d, and adding `label`, there is an error message with fig.legend(). Following this issue https://forum.generic-mapping-tools.org/t/legend-for-a-plot3d/3124, "... legend calls plot for symbols so a 3-D cube symbol via plot has not been implemented (by @PaulWessel).

**Comment by joa-quim** [comment]
Closing as not planed for now.
