### ISSUE TITLE
Failing tests due to changes in earth_relief?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#6898]
**Description of the problem**

Following tests started to fail since yesterday:

```
	207 - doc/examples/ex08/ex08.sh (Failed)
	232 - doc/examples/ex33/ex33.sh (Failed)
	237 - doc/examples/ex38/ex38.sh (Failed)
	366 - test/gmtmex/WL_example_2.sh (Failed)
	459 - test/grdfill/gridfill.sh (Failed)
```
It seems there are some changes in the earth_relief files. Please confirm.

**Comment by PaulWessel** [comment]
I just got the same as you right now on a branch and was wondering why.  As far as I know, no changes done on oceania. I suspect it must be a side-effect of #6891, or what @joa-quim ?

**Comment by joa-quim** [comment]
What do I know. That PR only changed what's printed as a warning. How could it screw grid reading?

**Comment by PaulWessel** [comment]
You know a few things.  But anyway, the way I implemented that fix was not to prevent the printing but to not care about the registration.  I will do another PR that will still care (and select gridline registration) but not be fussy about it (which was the original complaint).
