### ISSUE TITLE
gdal still optional for devs?

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6917]
According to [this](https://docs.generic-mapping-tools.org/6.4/_images/GMT5_mode.png) and [this](https://docs.generic-mapping-tools.org/6.4/_images/GMT5_external.png) from the [GMT C API](https://docs.generic-mapping-tools.org/6.4/devdocs/api.html) docs, `gdal` is still optional. Isn't it a requirement now?

**Comment by PaulWessel** [comment]
Great, thanks for finding those.  Yes, GDAL is required and the images need updating.

**Comment by seisman** [comment]
Closed by https://github.com/GenericMappingTools/gmt/pull/6921.
