### ISSUE TITLE
longbasemap.sh test patch

### ISSUE THREAD

**Issue by rbdavis** [GenericMappingTools/gmt#6918]
**Description of the problem**
Fix due to changed directive arg assignment :=

**Full script that generated the error**
test/longbasemap.sh prior to 2022/07/25

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by seisman** [comment]
@rbdavis There is no need to open an issue if you already have a fix (i.e., PR #6919) for it. Issues are mainly for reporting bugs and discussing how to fix.
