### ISSUE TITLE
Link to other modules docs' arguments

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6927]
Is there an easy way to link to other modules docs' arguments? Like e.g. ``|-H|``, which I guess only works for the 'local' document(?)

[grdimage](https://docs.generic-mapping-tools.org/dev/grdimage.html) have some links that could be directed to the argument being described (top figure), and some link to ``grdimage``'s non-existing ``-T`` instead of ``grdview``'s (which is the intended destination).
 
![Screenshot from 2022-08-01 18-47-14](https://user-images.githubusercontent.com/29237824/182201474-7ec766d9-52b8-4442-aaf3-1bffe81ffd28.png)

![Screenshot from 2022-08-01 18-47-18](https://user-images.githubusercontent.com/29237824/182201487-a5eb0c02-15a8-43a4-98a1-8c6f7caa1df0.png)

**Comment by seisman** [comment]
Can you check if 
```
:ref:`grdview:-T`
```
works?

**Comment by anbj** [comment]
Thanks @seisman.

I tried that and some other cariations without any luck;

```
:ref:`grdview:-T`
:ref:`grdview.rst:-T`
:doc:`grdview:-T`
:doc:`grdview.rst:-T`
```

Result:

```
/home/anbj/gmt/gmt/b/doc/rst/source/grdimage.rst:45: WARNING: undefined label: 'grdview:-t'
/home/anbj/gmt/gmt/b/doc/rst/source/grdimage.rst:46: WARNING: undefined label: 'grdview.rst:-t'
/home/anbj/gmt/gmt/b/doc/rst/source/grdimage.rst:47: WARNING: unknown document: 'grdview:-T'
/home/anbj/gmt/gmt/b/doc/rst/source/grdimage.rst:48: WARNING: unknown document: 'grdview.rst:-T'
```

**Comment by anbj** [comment]
I'm confused how e.g. in `mapproject`, `|-C|` becomes a link; isn't` the `||` substitution in sphinx?

**Comment by joa-quim** [comment]
Yes, the module operator is actually a macro that gets expanded to do the job you want. Don’t remember the file where that happens … but there  is one🙂

**Comment by anbj** [comment]
Closing this for now. If interesting enough we can open later.
