### ISSUE TITLE
Some points about gmt begin

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6942]
[gmt begin docs](https://docs.generic-mapping-tools.org/dev/begin.html)

* *If your script only makes a single plot then this is the most opportune time to specify the name and format(s) of your plot.*: mention and add a link to [21. GMT Modern Mode One-line Commands](https://docs.generic-mapping-tools.org/dev/cookbook/one-liner.html).
* About *prefix*; *Name-stem used to construct the single final figure name [gmtsession]*. I interpret this to mean that the figure should get a session number if *prefix* is omitted. Is this correct? When I omit the prefix, e.g.
    ```
    gmt begin png; gmt grdimage -Rg @earth_relief_20m; gmt end
    ```

     I end up with a figure called *png.pdf*. Not sure how gmt knows if I'm giving the format I want or name..
* The *prefix* also may include absolute or relative path to where the figure should be placed. I cannot see this mentioned anywhere; should it be?

I'll be happy to do this if it's useful.

**Comment by PaulWessel** [comment]
I think we need to clarify that the format is optional [pdf] but if you want to specify one then the name should also be given.  Alternatively, we simply check that if the name given matches one of the recognized formats then we stick with gmt_session as the name.  We are probably not checking for your case.

**Comment by anbj** [comment]
I see.

```
gmt begin; gmt grdimage -Rg @earth_relief_20m; gmt end
```

gives *gmtsession.pdf*.

**Comment by anbj** [comment]
Done in #6962.
