### ISSUE TITLE
Search GMT_DATADIR for custom symbols

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#6944]
The ``GMT_DATADIR`` is great for storing regularly used stuff, but it does not seem to to apply to custom symbols.

I've placed my custom symbol in ``~/.gmt/gmt-data/symbols/12.def`` and ``GMT_DATADIR`` is set to ``~/.gmt/gmt-data/``. ``plot`` is not able to find this:

```
$ echo 0 0 | gmt psxy -Sk12/1c -R-0.5/0.5/-0.5/0.5 -JX10c -P > 12.ps
psxy [ERROR]: Could not find either custom symbol or EPS macro 12
psxy [ERROR]: Option -S: Parsing failure
```

It would be nice if ``GMT_DATADIR`` is searched when specifying (custom) symbols as well.

**Comment by PaulWessel** [comment]
A custom symbol is not data.  I think form memory we look in ~/.gmt though.

**Comment by anbj** [comment]
You're right; it's my subdirectory causing problems. Placing it in ``.gmt`` works.

**Comment by anbj** [comment]
So symbols are looked for in:

* `/share/custom/`
* current directory
* `~/.gmt`

**Comment by anbj** [comment]
So custom symbols need to be present in one of those dirs.
And since not data, does not apply to `GMT_DATADIR`.

Closing.
