### ISSUE TITLE
Suggestion to use a 'real' cyclic colormap in the code example of Cookbook section 3.20.5

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/gmt#6953]
The Cookbook section [3.20.5. Cyclic (wrapped) CPTs](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#cyclic-wrapped-cpts) is about how to turn a colormap into a cyclic one from a value-perspective. The code example uses the colormap _jet_, which is no cyclic colormap when looking at the start- and end-colors. I feel it makes more sense to use a colormap, which is also cyclic from a color-perspective, like _romaO_, _bamO_, _brocO_, _corkO_, _and vikO_ of the _Scientific Colormaps_ by F. Crameri or _phase_ of the _cmocean_ colormaps by Thyng et al. 2016 (built-in up on GMT 6.4.0 (: ).

**Comment by PaulWessel** [comment]
That is true of the data are periodic.  But lots of uses of cyclic colormap wants to have fringes so one can "count" how many wraps there are, e.g., in InSAR.  Both are useful for different purposes.

**Comment by yvonnefroehlich** [comment]
> That is true of the data are periodic. But lots of uses of cyclic colormap wants to have fringes so one can "count" how many wraps there are, e.g., in InSAR. Both are useful for different purposes.

Thanks @PaulWessel for your fast answer and explanation.
