### ISSUE TITLE
Vertical color bar too long with -DJMR

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#6963]
Don't understand why I'm getting this. Certainly we have tests that cover it, but still ...

This works almost fine. I'm saying *almost* because the color bar length is correct but partially overlaps the annotations. 
```
gmt grdimage @earth_relief_20m_g.grd  -JR14c -Baf -BWSen -n+a -P -K > lixo.ps
gmt psscale -Cturbo -R -J -Baf -DJBC+h -O >> lixo.ps
```
but when plotting the color bar vertically the size screws. And a very weird thing is I get the same from Julia when plotting from a file name. However, if I read the grid first into Julia and plot with the in-memory grid then the plot is fine.

```
gmt grdimage @earth_relief_20m_g.grd  -JR14c -Baf -BWSen -n+a -P -K > lixo.ps
gmt psscale -Cturbo -R -J -Baf -DJMR -O >> lixo.ps
```

![lixo-fs8](https://user-images.githubusercontent.com/537321/185100205-1e2ffe34-3d91-41b8-9b33-1dad86b473e6.png)

**Comment by joa-quim** [comment]
Strange, I can no longer reproduce the second case.

**Comment by Esteban82** [comment]
> gmt grdimage @earth_relief_20m_g.grd  -JR14c -Baf -BWSen -n+a -P -K > lixo.ps
> gmt psscale -Cturbo -R -J -Baf -DJMR -O >> lixo.ps

When I run this, I got: `psscale [ERROR]: Found no history for option -R`.

**Comment by PaulWessel** [comment]
@joa-quim must have some old gmt.history picking up incorrect values.

**Comment by joa-quim** [comment]
This issue originally happened in Julia and what I posted here was the commands that also failed in CLI, but yes, the problem must have been in a ``gmt.history``. So closing this.
