### ISSUE TITLE
Order of -B pieces matters, and one is bugged

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#700]
This works fine
```
psbasemap  -R1999-08-11T00:00:00/2007-12-31T00:00:00/0.0/300.0 -JX9i/6i -Bpxa3Of1o -BWSen > lixo.ps
```
but changing the order of last two items makes it plot a huge number of tick marks and the process has to interrupted.
```
psbasemap  -R1999-08-11T00:00:00/2007-12-31T00:00:00/0.0/300.0 -JX9i/6i -BWSen -Bpxa30f1o > lixo.ps
```

**Comment by seisman** [comment]
In your second command, `-Bpxa30f1o` should be `-Bpxa3Of1o`. Note the slight difference between `0` and `O`.

**Comment by joa-quim** [comment]
Yes, I realized that later but had no time to get back to this ( in a department meeting right now)

Sent from my iDedo

No dia 09/05/2019, às 14:40, Dongdong Tian <notifications@github.com> escreveu:

**Comment by joa-quim** [comment]
... and correcting the error makes this issue go away. Nevertheless strange that the order matter.
