### ISSUE TITLE
mapproject -L<dataset> doesn't work from externals

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7010]
It has the right KEYs but it errors with ``mapproject [ERROR]: No filename provided``

Another trouble is that it doesn't seem to work in modern mode either (CLI). In Julia I had to had a 
```
contains(cmd, "-L") && gmtlib_setparameter(G_API[1], "GMT_COMPATIBILITY", "4")
```
otherwise in modern mode, which sets GMT_COMPATIBILITY to 6, I got a compatibility error.

**Comment by PaulWessel** [comment]
And Julia is passing a -L@GMTAPI@.... name option?  It seems like it should work - I allow for remote files and we read it via GMT_Read_Data so that is not it.  The message is not from map project.c per se but probably GMT_Read_Data is not being fed a file.

I dont understand compatibility error since -L is not deprecated at all.  Seems like you have time on your hands to fire up your debugger and see what is going on.

**Comment by joa-quim** [comment]
In Julia I try to pass a GMTdaset, which is what is supposed to work,

I found that deprecation line, bust lost track of it in the many things at same time. Will try to find it again.

**Comment by joa-quim** [comment]
It seems that ``mapproject_old_L_parser`` is called and then in it we have
```
	if (!gmt_M_compat_check (API->GMT, 5)) {	/* Sorry */
		GMT_Report (API, GMT_MSG_ERROR, "Option -L: Expects -L<table>[+u<unit>][+p]\n");
		return 1;
	}
```
which will be triggered when in modern mode.

**Comment by PaulWessel** [comment]
OK, let me now when/if you find where things derail.  Seems we have done very similar things in other modules. Are you also appending any modifiers or is it just the file name?

**Comment by PaulWessel** [comment]
I see, so the bug is that when there are no modifiers it should not go into there.  Just fix that if-test so that it instead goes into the modern check when there is no slash and no modifiers.

**Comment by joa-quim** [comment]
I'm not so sure what to put in the if-test. Slashes are acceptable in file names.

**Comment by PaulWessel** [comment]
Comments says the old way was

`[-L<table>[/[+|-]<unit>]][+]`

so maybe the test should be something like this instead (to detect old syntax):

0. If you find +u or +p then it is modern syntax.
1. Find last slash in arg, if any (use strrchr).
2. If a slash is found and the next char is a plus or minus you have old syntax
3. If last character in option is a + then you have old syntax
4. If no plus/minus after slash, then if there is only one more character and it is one of the allowed units then it is old syntax
5. else it is new syntax.

So a bit more involved but perhaps safer.  You should do the check for +u +p first (modern) then 3 (old syntax) then look for slash and do 2, then 4.

**Comment by PaulWessel** [comment]
And if no slash then checks 2,4 are moot.

**Comment by joa-quim** [comment]
With #7011 my failure case no longer fails but it would be better to have better tests.

**Comment by joa-quim** [comment]
Hopefully solved (if not, it will come back)
