### ISSUE TITLE
makecpt and grd2cpt: allow hex output

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7018]
*makecpt* and *grd2cpt* could benefit from having an option/modifier to the ``-F``-agrument to specify/force output CPT to be written in hex values.

I don't know enough about this; My thought is to be able to output r/g/b as hex, but would it make sense to also do this with h-s-v and c/m/y/k?

Based on [this](https://forum.generic-mapping-tools.org/t/make-cpt-with-custom-intervals-and-colors/3251/5?u=andreas) forum post.

**Comment by anbj** [comment]
PS! It reads hex just fine.

**Comment by PaulWessel** [comment]
I think the hex format is only every used (webpages etc) as rgb.
