### ISSUE TITLE
man_pages.rst is missing

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#702]
**Description of the problem**

`man_pages.rst` is needed to generate GMT_Manpages.pdf.

https://github.com/GenericMappingTools/gmt/blob/24b9579e1fadc9cd05462716f55cddae091563c1/doc/rst/conf.py.in#L193-L198

**Comment by joa-quim** [comment]
I think we decided to drop the man pages pdf

**Comment by seisman** [comment]
If so, we should also remove it from `conf.py.in`.
