### ISSUE TITLE
psxy -L+b crashes GMT when called from Julia.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7028]
I have new Julia function, band(), which an avatar around ``psxy -L``. Most of things work well but it crashes when I pass an array with 4 columns to be used by ``-L+b``.

```
x = -10:0.11:10;
y1 = sin.(x)./x .+ 0.1;
y2 = sin.(x)./x .- 0.1;

band([x sin.(x)./x],y1,y2, fill="green@80", envelope=true, show=1, Vd=1)
    psxy  -JX14c/9.5c -Baf -BWSen -R-10.0/10.0/-0.32/1.12 -Ggreen@80 -L+b -W0.5p -P -K > C:\TEMP\GMTjl_tmp.ps
```
It works fine if I save this ``[x sin.(x)./x],y1,y2`` to file (a Mx4 matrix after being parsed by the band() function) but crashes ``psxy`` at line 2695 because L in
      ``GMT->hidden.mem_coord[GMT_Y][k] = L->data[2][k];``
has only two columns. Weirdly the dataset from which ``L`` is extracted says it has 3 segments when it should have only one.

![image](https://user-images.githubusercontent.com/537321/190239996-85b085e0-8178-41bc-b1f4-5cbccfb01e5c.png)

**Comment by PaulWessel** [comment]
What is the significance of the commas in band between the x,y and the limits? Are you sure you are passing a Mx4 matrix via a virtual file that has that dimension?  If L says it has 2 columns then that is what it got, no?  Since passing virtual files in general works I would first be suspicious of it being properly created and that the metadata are set correctly.

**Comment by joa-quim** [comment]
``[x sin.(x)./x],y1,y2`` means *accept a x y matrix with the line coordinates and append the y1 and y2 bounds*.
All fine with that (and ``band`` has simpler syntax's as well) but just found that the parsing that joins all those 3 in a Mx4 matrix is leaving some trace in a global variable used to know when plot multiple lines in one step, and the input is screwed.

So, what comes out of this is that ``psxy`` should check that ``L`` has enough columns before accessing them. These crashes are very annoying because they kill the host too.

**Comment by PaulWessel** [comment]
Sure, I can add a check that L has the right number of columns and bail if not.  Or you can add that check - you are not busy selling your house, right?
