### ISSUE TITLE
GDAL_VERSION_NUM undeclared if GDAL isn't installed

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#703]
**Description of the problem**

GDAL isn't a required dependency. If GDAL is not installed, the build will report `GDAL_VERSION_NUM` is undeclared. We should check if `HAVE_GDAL` is defined.

**Comment by PaulWessel** [comment]
Do you know where the report is coming from?

**Comment by seisman** [comment]
```
..\src\gmt_init.c(13991): error C2065: 'GDAL_VERSION_NUM': undeclared identifier
```

**Comment by joa-quim** [comment]
That's gcc playing dumb. The function where that identifier is used is only called under an #ifdef HAVE_GDAL. Anyway, PR in #704
