### ISSUE TITLE
Plot symbols to annotate the centers of closed innermost contours

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7046]
[grdcontour -T](https://docs.generic-mapping-tools.org/dev/grdcontour.html#t) allows to annotate the centers of closed innermost contours with a label. What about adding the [plot -S](https://docs.generic-mapping-tools.org/dev/plot.html#s) machinery also, so that one may use symbols instead of labels? E.g., triangle indicating upward closing, and inverted triangle indicating downward closing.

This is partly related to my #559, in my quest to differentiate upward/download closing contours and how to extract contours based on this (with e.g. [grdcontour -D](https://docs.generic-mapping-tools.org/dev/grdcontour.html#d)).

**Comment by PaulWessel** [comment]
Since it involves two separate symbols always (right?), do we really use the full plot -S for this? That is a very extensive syntax. Maybe up/down triangles makes sense, but having squares and circles would then require captions etc so what is the point?

**Comment by anbj** [comment]
Yes, you’re right. Up/down triangle (and other ‘binary symbols’ that make sense) would be nice.

**Comment by anbj** [comment]
(Isn’t a triangle often used to indicate summits/peaks on maps..?)

**Comment by anbj** [comment]
Closing this.

While I like the idea of having a symbol in the innermost closed contour, it should represent an actual point of minimum/maximum value (i.e. a peak/pit).
