### ISSUE TITLE
Custom annotations in polar plots do not annotate for ang > 180

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7060]
See, only firs annotation shows up
```
# GMTjl_custom_px.txt
179.0 ag Label1
181.0 ag Label2
```
```
gmt basemap -R0/360/0/1 -JP14 -BpxcGMTjl_custom_px.txt -Bxa0 -Byg0.2 -png lixo
```
![lixo](https://user-images.githubusercontent.com/537321/196995663-d6dd95b7-2614-46d4-b720-9853f865eb1b.png)

**Comment by joa-quim** [comment]
The bug is here

![image](https://user-images.githubusercontent.com/537321/197017900-748e43aa-1d5b-406f-af87-0e4af22d82d3.png)

The second angle, 181, was converted to -179 and then it doesn't pass the **if** test because ``limit[0] = 0; limit[1] = 360``

**Comment by PaulWessel** [comment]
Clearly the check should not be a cartesian limit check but a periodic one.  Need to assemble my new chair before any editing is possible.
