### ISSUE TITLE
Box-n-wiskers width (-E+w)

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7071]
The plot -E docs say:

> The +w modifier sets the cap width that indicates the length of the end-cap on the error bars [7p]. 

but **+w** actually sets the entire box width, not only its cap. Other that making this more clear in the manual (easy), it would be nice to have a different setting for the cap so that one could select a zero cap width.

**Comment by PaulWessel** [comment]
I agree.  Since **-S** is not used, how shall "symbol size" be specified as separate from the cap width? Do we go **+w**_cap_[/_width_] ?

**Comment by PaulWessel** [comment]
It would probably be better with **+w**_width_[/_cap_] so that +w8p sets both like now, while new syntax `+w8p/0` would set the box width and skip drawing the caps.  It would mean we change the docs as well but backwards compatibility is assured.

**Comment by joa-quim** [comment]
Yes, that looks good.
