### ISSUE TITLE
Missing color for "2" in categorical SCM colortables

### ISSUE THREAD

**Issue by DerLude** [GenericMappingTools/gmt#7075]
**Description of the problem**
It seems that all categorical SCM colortables (`gmt/share/cpt/SCM/*S.cpt`) do not have a color for "2" defined. I guess this was not intended and originates from a bug in the script that creates these files.
See e.g. `actonS.cpt`:
```
...
#----------------------------------------------------------
# COLOR_MODEL = RGB
#----------------------------------------------------------
0	46/33/77
1	230/230/240
3	196/110/155
4	119/90/134
5	212/167/197
6	213/140/178
7	159/101/147
8	80/62/106
9	218/197/217
10	212/154/187
...
```

**System information**

* Operating system: Ubuntu 22.04 LTS
* GMT version (`gmt --version`): 6.3.0

**Comment by PaulWessel** [comment]
Yep, silly bug in an awk script.  Fix submitted as #7076.
