### ISSUE TITLE
UN150 collection misses Kosovo

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7080]
And, worse, some DCW polygons don't match their neighbors.
```
julia> coast(DCW=(name=:UN150, pen=0.5, fill=:gray70), region=(17,30,40,45), proj="eck4", Vd=1, show=true)
        pscoast  -EUN150+p0.5+ggray70 -Vq -R17/30/40/45 -JKf14c -Baf -BWSen -Da -P -K > C:\TEMP\GMTjl_tmp.ps
```
![GMTjl_tmp](https://user-images.githubusercontent.com/537321/200171572-b0fe6dba-cbc8-45c4-adae-c34972b8d41e.png)

**Comment by Esteban82** [comment]
Mmm, Kosovo is not recognized by the UN. So, that it why is not included in the UN list. 

Possible solutions:
1. You could use `name=:UN150,XK`, 
2.  We could add Kosovo to UN150 (but maybe someone would like to use the UN definition). 
3.  We could create a new list (like UN150+) where we add Kosovo.

**Comment by joa-quim** [comment]
I understand that **3.** is the more correct solution, but who would find that to have all countries in that map a different UN150 would be needed (same for option **1.**). So I go for **2.**

**Comment by Esteban82** [comment]
> who would find that to have all countries in that map a different UN150 would be needed

I think that is the case for the DCW collections in general. We should make a figure where all the regions/lists can be seen with maps.

**Comment by PaulWessel** [comment]
While the UN may not recognized Kosovo it is clear that the part of that landmass is entirely within Europe regardless of name and politics.  So I think we should add it to UN150 as a bug fix.

As for mismatch - not sure.  Are some DCW polygons just not correct? Have not seen that before but not made many detailed plots either.  Or are you drawing both GSHHG and DCW?

**Comment by joa-quim** [comment]
DCW polygons only (command is in the opening post). And the differences are larger than those explainable by different datum.

**Comment by Esteban82** [comment]
Ok, I will add Kosovo to the UN150 list.
