### ISSUE TITLE
Title in postscript-files

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7104]
In postscript; is the *Title* an important thing?

```
$ gmt coast -RNO -W -ps test

$ cat test.ps | grep Title
%%Title: GMT v6.5.0_e4ef4dd_2022.11.18 [64-bit] [MP] Document from coast
```

* As far as I can tell, only .ps and .pdf cares about it - the *Title* is shown when opening the file (see screenshots).
* Can it be put inside some kind of metadata-tag in the other [supported image formats](https://docs.generic-mapping-tools.org/dev/begin.html#tbl-formats)?
* Would it make sense to be able to specify what should be in the *Title*? GMT version and module seems to be hard coded (``%%Title: GMT v6.5.0_e4ef4dd_2022.11.18 [64-bit] [MP] Document from coast``).

![Screenshot from 2022-11-21 21-42-07](https://user-images.githubusercontent.com/29237824/203262070-87851013-9bca-4c32-a9ed-2d434b91bbba.png)

![Screenshot from 2022-11-21 21-42-36](https://user-images.githubusercontent.com/29237824/203262083-d9661425-8630-4b53-af0d-c3536eb0085e.png)

**Comment by PaulWessel** [comment]
For classic GMT with stdout there was no place to add a title, e.g., file name.  To set a Title in a pdf or PS would mean either option pro some other scheme.  Is it that necessary?

**Comment by anbj** [comment]
No place to add a title as in piping postscript directly to the viewer?

It's not necessary; just curious and probing to see if there are any convenient places to put metadata.

**Comment by anbj** [comment]
If I understand correctly, these postscript metadata are not very relevant anymore - closing.
