### ISSUE TITLE
Transparency is "transparing" axes too

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7115]
```
julia> plot([1 1 0.2 0.3; 2 2 0.3 0.2], t=90, G="#0072BD", L="+D", W=0.5, Vd=1, show=1)
        psxy  -JX14c/9.5c -Baf -BWSen -t90.0 -R0.96/2.04/0.96/2.04 -G#0072BD -L+D -W0.5 -P -K > C:\TEMP\GMTjl_tmp.ps
```

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/204024595-d108b759-5092-4714-8d4c-aba2af518e9c.png)

**Comment by PaulWessel** [comment]
I think that is by design: -t sets the layer transparency.  If you just want a symbol or line to be transparent then you specify that via -G or -W.

**Comment by joa-quim** [comment]
See next bug 😄

**Comment by PaulWessel** [comment]
Not too much time for those types of debugging now.  But I dont think this issue (here) is a bug - it is a feature - so close?
