### ISSUE TITLE
Fill color in header screws -L+D polygons

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7116]
Data
```
>  -W,#0072BD -G#0072BD
1	5	0.2	0.2
2	3.4	0.2	0.275
3	1.5	0.1	0.075
4	0.2	0	0.1
>  -W,#D95319 -G#0072BD
1	5.9	0.3	0.4
2	2.8	0.275	0.2
3	4.35	0.35	0.25
4	1.3	0.1	0.2
>  -W,#EDB120 -G#0072BD
1	6.5	0.275	0.4
2	3	0.2	0.175
3	5.55	0.45	0.325
4	2	0.2	0.3
```

```
gmt plot -JX14c/9.5c -Baf -BWSen -R1/4/1/8 -L+D+p0.5p -W0.5 G4par.dat -png lixo
```
![lixo](https://user-images.githubusercontent.com/537321/204042390-9294eb68-3fb1-4a19-a906-a2a20a5890a5.png)

But if one removes the ``-G#...`` from the headers we get the right polygons, except not filled ofc

![lixo2](https://user-images.githubusercontent.com/537321/204042477-85e1d07b-4cc8-48ec-94d0-955b27df8e53.png)

**Comment by PaulWessel** [comment]
If I just plot the first polygon and extend **-R** to cover the full range I still get strangeness even though there should be no clipping now.  SO that is good news - perhaps this is a simple bug to fix:

![full](https://user-images.githubusercontent.com/26473567/204087287-1e881f70-95d2-47d2-8f94-8fac0ff1ce90.png)

The red line is plotting the polygon I manually created by doing the -L by hand.

**Comment by joa-quim** [comment]
There is another little shit, but that's probably a different issue. And is one that I cannot reproduce on CLI, only from Julia.
What I did to workaround this bug was to strip the fill color from the header and issue a -G directly and make one plot call for each polygon. But it doesn't respect the line color that is always painted black. 
```
julia> parallelplot("iris.dat", groupvar="text", quantile=0.25, band=true, pen=1, show=1)
-W,#0072BD
        psxy  -R1/4/0/1 -J -G#0072BD@70.0 -L+D -W1 -K -O >> C:\TEMP\GMTjl_tmp.ps
        psxy  -R1/4/0/1 -J -G#D95319@70.0 -L+D -W1 -K -O >> C:\TEMP\GMTjl_tmp.ps
        psxy  -R1/4/0/1 -J -G#EDB120@70.0 -L+D -W1 -K -O >> C:\TEMP\GMTjl_tmp.ps
```  
See the printed ``-W,#0072BD``, which is the header content at time of passing the GMTdataset to the ``plot`` module.
When I try to reproduce this on CLI the color in header is always respected.

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/204092315-84e43be3-04f9-4e12-83b3-a2987d945335.png)
