### ISSUE TITLE
For a Developer-- Please create a Forum account for me

### ISSUE THREAD

**Issue by pjohnson303** [GenericMappingTools/gmt#712]
Hello,

As directed here, http://gmt.soest.hawaii.edu/projects/gmt/wiki , I am requesting a Forum account so that I can ask questions and learn about successful GMT usage.

Desired user name -- Mapper3, or Mapper333, or Mapper303, etc
Contact email -- seismokid@gmail.com
Your full name -- Peggy Johnson

Thank you!

---Peggy

**Comment by PaulWessel** [comment]
Done, see email.
