### ISSUE TITLE
Fix the description for FONT_LOGO

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7125]
**Description of the problem**

As shown in the example below, `FONT_LOGO` can't change the size and color of the timestamp and label. 

```
gmt basemap -R0/10/0/5 -JX5c/3c -Baf -UMylabel --FONT_LOGO=20p,Times-Bold,red -png map
```
![map](https://user-images.githubusercontent.com/3974108/204796207-32ea5530-28da-4553-a847-1dc58377eeae.png)

Here are two issues:

1. I understand that the font size can't be changed because the size of the timestamp strings must match the height of the graphic "GMT" logo, but why can't the font color be changed?
2. The [gmt.conf documentation](https://docs.generic-mapping-tools.org/latest/gmt.conf.html#term-FONT_LOGO) says

   > Font to use for text plotted as part of the GMT time logo [[theme dependent](https://docs.generic-mapping-tools.org/latest/theme-settings.html)]. Choose auto for [automatic scaling with plot size](https://docs.generic-mapping-tools.org/latest/cookbook/features.html#auto-scaling)."
  
   The description is inaccurate and misleading because the font size can't be scaled automatically.

**Comment by joa-quim** [comment]
I say that I want something more and had even implemented it but can't find it right now. It was something to add a author, probably in the place of time.
-U is useful for more than just printing.

Will search better tonight.

**Comment by joa-quim** [comment]
OK, found it

![image](https://user-images.githubusercontent.com/537321/204906130-0ba12986-f746-4981-b979-19a6ea5628f1.png)

I made it with this syntax ``-UJ.L.+tGMTSAR+o0/0``. *I.e.*, replaced the date-time with something else.

**Comment by PaulWessel** [comment]
I suppose we can consider that as a modifier addition.  Bedtime up north though.

**Comment by seisman** [comment]
> * Fix the documentation to state this default only changes the font and the color but not the size which is fixed at 8 points.
> * Use FONT_LOGO to set the color of the user label
> * If you agree, also use FONT_LOGO to set the color of the date clock string.

Yes, I think these changes all make sense.

> I made it with this syntax `-UJ.L.+tGMTSAR+o0/0`. _I.e._, replaced the date-time with something else.

The **+t** modifier also sounds good.
