### ISSUE TITLE
Loss of siginificant digits by psbasemap

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#7136]
**Description of the problem**

A slight change to -R parameters seems to give psbasemap some troubles. Seems to get hung-up when lots of significant digits are required. This example is supposed to only make a frame, no data involved.

**Full script that generated the error**

```
outdsn=t.ps
r_param=-R38760819.06/38760819.16/-2/2
gmt psbasemap -JX9i/6.5i $r_param -Bxag+l"time (s)" -Byag+l"height (m)" -BWeSn -K -Vd > $outdsn
echo "5.5 8.4 Test of -R parameters" | pstext -JX11i/8.5i -R0/11/0/8.5 -F+f14,1+jTC -X-1i -Y-1i -O >> $outdsn

```

**Full error message**

```
No error messages - psbasemap seems to get hung. Running with -Vd reveals problems with significant digits. There was this line:

psbasemap [DEBUG]: Projected values in meters: 3.87608e+07 3.87608e+07 -2 2

Could the problem be that, internal to GMT, it is not retaining enough digits?
```

**Actual outcome**

Nothing - just runs and runs. Stuck.

**Expected outcome**

A simple frame, in a split second of wall clock time.

**System information**

* Operating system: MacOS 12.6.1
* GMT version (`gmt --version`): Version 6.5.0_c710097_2022.11.28 [64-bit] [16 cores]

**Comment by PaulWessel** [comment]
It hangs on macOS. What happens in Win (@joa-quim) and Linux (e.g., @anbj)?

**Comment by anbj** [comment]
Same on Linux with ``6.5.0_30ffdcb_2022.12.05``;

```psbasemap [DEBUG]: Projected values in meters: 3.87608e+07 3.87608e+07 -2 2``` and just hangs.
