### ISSUE TITLE
The option -bo in the gmt math has stopped working, gives a strange error

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#7142]
Test case:
echo "1 2" |gmt math -bo2 STDIN = | gmt math -bi2 -bo STDIN =
gmt [ERROR]: Unrecognized graphics format bo for modern mode one-liner command

Problem appeared after commits 2aa7f6e8abd423a40086f8a4fdc6c707418cb57d and 43bccb384663d97ee84f8110e4c50858483ec80f.

**Comment by PaulWessel** [comment]
Sorry about that.  The submitted PR should fix it.

**Comment by uleysky** [comment]
Thank you, it works.
