### ISSUE TITLE
Improve pssegy with SAC software

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7159]
**Description of the desired feature**

The pssegy module only "reads a native (IEEE) format SEGY. The SEGY file should be a disk image of the tape format (i.e., 3200 byte text header, which is ignored, 400 byte binary reel header, and 240 byte header for each trace) with samples as native real*4 (IEEE real on all the platforms to which I have access).". This correspond to the data sample format code 5 (as describe on page 7, bytes 3225-3266 in Hagelund (2017).

I found the SAC software [SEGY to ASCII Conversion and Plotting Program 2.0](https://pubs.usgs.gov/of/2005/1311/) by Mark Goldman of the USGS which can read segy with data sample format code 1 (IBM floating points, see also [forum](https://forum.generic-mapping-tools.org/t/read-convert-from-binary-ibm-4-byte-floating-point-offtopic/3517/7). It "then creates a postscript file of the seismic data using GMT".

I wonder if it would be too difficult to somehow include the funcions of the SAC software within GMT.  Specially its ability to read segy with sample format code 1 (which I think was the standard option for pre-2002 segy files). 

I could try to help testing the codes and maybe trying to write/addapt the code.

References: 
Hagelund, Rune; Stewart A. Levin, eds. (2017). [SEG-Y_r2.0: SEG-Y revision 2.0 Data Exchange format](http://seg.org/Portals/0/SEG/News%20and%20Resources/Technical%20Standards/seg_y_rev2_0-mar2017.pdf)

**Comment by joa-quim** [comment]
Federico, I'm afraid that if you don't do it yourself, or at least make a reasonable advance with it, hardly some one will do that for you. And that code is not even in C, it's C++, which a wilder beast (an horribly complicated language IMO).

I think I already pointed [this julia package](https://github.com/slimgroup/SegyIO.jl) once. As a very quick try, I did this, which uses the example data from the USGS tar file.

Note, the package lack a manual so contacting the author asking about it is probably a must. But a quick scan through the code allowed to discover that:

```
using GMT

s = segy_read("example.segy");

See what members that struct type is made of
fields(s)
(:fileheader, :traceheaders, :data)
```
Let's try the ``data`` member
```
s.data
201×349 Matrix{Float32}:
  0.0         0.0         0.0          0.0         0.0         …   0.0         0.0         0.0         0.0         0.0
  0.0         0.0         0.0          0.0         0.0             0.0         0.0         0.0         0.0         0.0
  0.0         0.0         0.0          0.0         0.0             0.0         0.0         0.0         0.0         0.0
  0.0         0.0         0.0          0.0         0.0             0.0         0.0         0.0         0.0         0.0
  0.0         0.0         0.0          0.0         0.0             0.103972    0.0974663   0.136248    0.0470953   0.0824165
  0.0         0.0         0.0          0.0         0.0         …  -1.21311    -1.25097    -1.35737    -0.614244   -0.426346
 -0.12032     0.182275    0.878226    -0.20756     1.00489         1.10096     1.14641     1.33562     0.214555   -0.288015
  0.144935    0.694865   -0.179056    -0.201913   -0.554681        0.300609    0.263506   -0.0859441   0.957655    1.44684
 -0.510772   -1.10274    -0.308126    -0.372575    0.2636         -1.01345    -0.947182   -0.550184   -1.33356    -1.408
  1.17045     0.404708   -0.0014673    1.14513    -0.632035        0.28045     0.250109    0.115904    0.384779    0.221442
 -1.14485     0.652589    0.886077    -0.961576    0.457191    …   0.36167     0.267752    0.190481    0.691181    0.566538
```
Hmm, a matrix. Probably each column is a trace that could be plotted with ``pswiggle`` but let's try a quick and dirty image
```
imshow(s.data)
```

![GMTjl_tmp-fs8](https://user-images.githubusercontent.com/537321/207646606-8b05e64a-a7e3-4d53-99b5-1b1ce27e0ad9.png)

Yep, almost sure they are traces.

**Comment by Esteban82** [comment]
Thanks Joaquim for your answer.

>  I'm afraid that if you don't do it yourself, or at least make a reasonable advance with it, hardly some one will do that for you. And that code is not even in C, it's C++, which a wilder beast (an horribly complicated language IMO).

Ok, I see. I imagine that could be this way. I will see what can I do. Specially to add the function to read data sample format code 1 (IBM floating points). I think that in the julia package is describe in [IBMFloat32.jl](https://github.com/slimgroup/SegyIO.jl/blob/master/src/types/IBMFloat32.jl). 

My issue with the julia (or python) package is that it is difficult to make my colleagues to use it.

The example.segy in the USGS tar file has a sample format code 5 (IEEE float), so it can be read by GTM.

**Comment by joa-quim** [comment]
I bet that ``segy_read()`` function can read all sorts of segy files existing in the market just like it did for the that example.

Regarding your colleagues, yes I understand the irresistible appealing of an incomprehensible bash script 😄 
More serious, can they choose?

**Comment by anbj** [comment]
I've heard rumors that Julia is a toy programming language since it starts counting from 1, and not 0. Is this true?

**Comment by joa-quim** [comment]
Yes, a very fun toy. I've played a lot with it.

**Comment by Esteban82** [comment]
> Regarding your colleagues, yes I understand the irresistible appealing of an incomprehensible bash script 😄
> More serious, can they choose?

Sorry by the delay. Yes, they can choose any software. So I could tell them to install Julia (or python) but the hard part is getting them to use it. In some cases it is already difficult to get them to use GMT. So it would be nice if they can do it with GMT.

**Comment by joa-quim** [comment]
That program can't be correct. It reads input as an integer when the ibm32 is a float. For example the integer representation of IEEE float in integer gives.
```
julia> reinterpret(Int, 1.1)
4607632778762754458
```
 To test the program, save it in a file, say ``ibm32.c`` and compile it. With GCC it would be
```
cc ibm32.c -o ibm32.exe
```
Running it confirms that the much repeated "Don't trust chatGPT generated codes" maxima is to be taken seriously
```
/c/v> ibm32
Enter number in IBM 32 format: 666
Number in ASCII format: 0.000000
/c/v> ibm32
Enter number in IBM 32 format: 999
Number in ASCII format: 0.000000
/c/v> ibm32
Enter number in IBM 32 format: 999.999
Number in ASCII format: 0.000000
/c/v> ibm32
Enter number in IBM 32 format: 4607632778762754458
Number in ASCII format: inf
```

**Comment by Esteban82** [comment]
Thanks Joaquim. I wlll use GCC to compile and test my file. 
Yes, I agree about chapGPT. I don't trust it but it could make a part of the work.

**Comment by joa-quim** [comment]
> it could make a part of the work

Sorry but hardly. Only when one can really enough to spot the errors it makes under the blanket of a very nice present.

Believe it, if you don't know C don't follow that route. It's a very *spiny* one.
Want to make your learning effort productive? 
You know the answer.

**Comment by joa-quim** [comment]
I'm in the camp of those who believe that *ChatGPT is, in technical terms, a 'bullshit generator'*, although an irresistibly attractive (down the cliff?) one.

https://www.danmcquillan.org/chatgpt.html

**Comment by Esteban82** [comment]
Ok, many thanks! I will considerer you ideas.  But, as I said before, my issue is that it hard that my coleagues willl use Julia.

**Comment by joa-quim** [comment]
I understand that. And it doesn't have to be Julia (though with it you might get some support/help from me).
The point is, from what I'm seeing it, their choice is more not using anything at all, which also fine.

**Comment by joa-quim** [comment]
Close this?
