### ISSUE TITLE
Filter1d and data with NaNs crashes from Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7168]
```
using Random

Random.seed!(18122022); xdata = sort((20:100) .+ 10 .* rand.()); xdata[40:60] .= NaN; ydata = xdata .+ 3 .* rand.();
plot(xdata, ydata, show=1)

# CRASH here
filter1d([xdata ydata], filter=(type=:median, width=10))
```
The crash occurs at line #530 of filter1d.c
```
for (row = 0; (F->data[F->t_col][row] - t_0 + small) < F->half_width; ++row);
```
apparently because ``F->data`` is all zeros so ``row`` grows until it blows.

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/208318977-fe30d304-76dc-47c6-9538-3f124396af5c.png)

**Comment by PaulWessel** [comment]
How is this passed into GMT? If it is a data set, does it have two segments (as all the NaN records are gone?).  If a matrix or 2 vectors, then perhaps GMT gets confused about all the consecutive NaN records and that cause fake segments with uninitialised data?  Does a text file with the contents of your data and data, if passed to CLI, work OK (I am guessing yes since the reading of files is well tested).

**Comment by joa-quim** [comment]
It's passed as a Matrix
```
julia> filter1d([xdata ydata], filter=(type=:median, width=10), Vd=3)
arg1 = Matrix{Float64}
"filter1d  -Fm10"
```
but something very strange happens. If I save it on disk it doesn't crash but reveals the shit
```
julia> size([xdata ydata])
(81, 2)
gmtwrite("lixo.dat", [xdata ydata])
```

```
wc lixo.dat
   1663    3304    8038 lixo.dat
```
the extra lines are made of several multi-segments filled only with zeros. So, more than one bug popped up with this example.

**Comment by joa-quim** [comment]
So, there are 21 NaNs in ``xdata``
```
julia> sum(isnan.(xdata))
21
```
and reading back the "lixo.dat" show 22 segments
```
julia> D = gmtread("lixo.dat")
Vector{GMTdataset{Float64, 2}} with 22 segments
```
First and last segments have data the other 20 have zeros only. The conclusion is that GMT takes the pairs of consecutive NaNs and create 0's multi-segments, but not all of the same size.
```
julia> size(D[1])
(39, 2)

julia> size(D[2])
(42, 2)

julia> size(D[3])
(81, 2)

julia> size(D[4])
(81, 2)

julia> size(D[5])
(81, 2)

julia> size(D[15])
(81, 2)
```

**Comment by PaulWessel** [comment]
Since `ydata` is created from `xdata` I assume both have 21 NaNs, right? So a record of all NaNs is used internally for vectors and matrices to indicate a segment header.

**Comment by joa-quim** [comment]
but what produced is
```
59.3207917692	59.4774895261
61.6398011765	61.7433859593
61.6442090994	62.5322732614
64.6461356078	65.791767145
>
0	0
0	0
0	0
0	0
0	0

many segments with only zeros

0	0
0	0
0	0
0	0
0	0
>
83.5168610127	86.1894628898
85.9273654633	86.8736747847
86.7413160935	87.523363845
89.1614837238	90.4207847419
...
```

**Comment by PaulWessel** [comment]
Yes, but please verify that your Julia data are x =  y = NaN for those sections

**Comment by joa-quim** [comment]
Sure they are. It's like in Matlab.

**Comment by PaulWessel** [comment]
Code has no protection against repeated NaN-records so choose ensues.  It is the same section causing trouble in both examples since it goes through _gmtapi_import_dataset_. Looking at solutions now.
