### ISSUE TITLE
Do we need to make *.webm files?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#719]
Our animation scripts are set up to produce both *.mp4 and *.webm files.  This adds to the processing time on the CI.  I've been around the block for a while and have never run into a *.webm file.  Is this a thing? With MP4 being an open standard, do we really need to cater to the 23 purists who want to use *.webm? Am I exaggerating?

**Comment by abanbj** [comment]
Well, if you’re a dedicated FLOSS man, I think webm is the way to go (alternatively .ogg?). Mp4 has a ‘bad’ license according to some people.

**Comment by seisman** [comment]
According to this link (https://en.wikipedia.org/wiki/HTML5_video#Browser_support), MP4 seems to be the only format supported by all browsers. 

Although our website includes both .mp4 and .webm in the video tag, the browsers I use (Chrome and Safari) always display the .mp4 one.

**Comment by joa-quim** [comment]
I think the scripts should only produce one format by default. All others are available via users choice.
And regarding the animations, what I see from Firefox are animated gifs (the age crust spins like crazy)

**Comment by PaulWessel** [comment]
To see the actual movies you must click on the animation title which opens up the page with the script and at the bottom there should be a movie to click on.  Let me know if that is not the case.

**Comment by joa-quim** [comment]
4, 6 & 7 are mp4 and the others, .gif

**Comment by PaulWessel** [comment]
I guess I am not a dedicated FLOSS man which presumably means someone purely on Linux.  Those are few and far between tons of Windows and OS X laptops.  But that is somewhat irrelevant.  We are not suggesting GMT not be able to make .webm files, just that it seems burdensome to make two formats when all browsers support the MP4 version.  Users can create their own .webm movies of course.
