### ISSUE TITLE
grdedit is broken from Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7202]
``grdedit`` is not particularly useful from wrappers, except for options **-L** and **-N**.
```
G = GMT.peaks();
G2 = grdedit(G, flip=:v, Vd=1);    # Ignore spurious -J
        grdedit  -JX14c/9.5c -Ev
G == G2
true
```
and even if I save grid to disk an work on files, grid is not changed
```
gmtwrite("peaks.grd", G)
grdedit("peaks.grd", flip=:v, Vd=1, V=true)
   grdedit peaks.grd  -JX14c/9.5c -V -Ev
...
grdedit [INFORMATION]: Flip grid vertically (FLIPUD)
grdedit [INFORMATION]: Referencing grid data to GMT_GRID memory location
grdedit [INFORMATION]: gmt_grd_BC_set: Set boundary condition for all edges: natural
grdedit [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grdedit [INFORMATION]: gmt_grd_BC_set: Set boundary condition for right  edge: natural
grdedit [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdedit [INFORMATION]: gmt_grd_BC_set: Set boundary condition for top    edge: natural
grdedit [INFORMATION]: Modified grid written to file @GMTAPI@-S-O-G-G-G-N-000043.
```
Hmm, file is still written to memory (but not flipped)
```
grdedit("peaks.grd", flip=:v, Vd=1, G="peaks.grd", V=true);
        grdedit peaks.grd  -Gpeaks.grd -JX14c/9.5c -V -Ev
grdedit [INFORMATION]: Editing parameters for grid peaks.grd:
grdedit [INFORMATION]: Flip grid vertically (FLIPUD)
grdedit [INFORMATION]: Writing grid to file peaks.grd
grdedit [INFORMATION]: Modified grid written to file peaks.grd.
```
But grid is not ud-flipped.

**Comment by PaulWessel** [comment]
Does

`grdedit("peaks.grd", flip=:v, Vd=1, G="flipped.grd", V=true);`

give you a flipped grid?  I mean, the CLI version does flip or rotate them, no?

**Comment by joa-quim** [comment]
Yes, the CLI version works well.

**Comment by PaulWessel** [comment]
But the Julia command I wrote with separate file names fails?

**Comment by joa-quim** [comment]
Yes.  That’s the weirdest one.

**Comment by PaulWessel** [comment]
And what is the command Julia creates and passes to te grdedit module in that case?

**Comment by joa-quim** [comment]
It should make no difference. That's what the CLI does. But this form *now* works. Either with a different or the same name. Must have made some double transform yesterday. But the memory versions still fail.

**Comment by PaulWessel** [comment]
And I take it you checked that G(0,0) == G2(0,0) then (whatever the syntax is for the top left node (which should be different if flipped).

**Comment by joa-quim** [comment]
```
julia> G.z == G2.z
true

julia> G = GMT.peaks();

julia> G2 = grdedit(G, flip=:v, Vd=1);
        grdedit  -Ev

julia> G.z == G2.z
true

julia> all(G.z .== G2.z)
true
```

**Comment by joa-quim** [comment]
>  G(0,0) == G2(0,0) then (whatever the syntax is for the top left node

For your learning. Contrary to Matlab, Julia distinguishes between functions and arrays. ``(...)`` is kept for functions arguments and ``[...]`` for array indices. So, it would be ``G[1,1] == G2[1,1]``

**Comment by joa-quim** [comment]
Problem is fixed if I remove these two lines in ``grdedit.c``
@PaulWessel, any recall of what was the intention?

![image](https://user-images.githubusercontent.com/537321/219100567-7d5d2221-a1d3-48f6-b366-e5f085090b95.png)
