### ISSUE TITLE
Specify grid registration in GMT examples/animations

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#7227]
**Description of the desired feature**

Since GMT 6.4 (https://github.com/GenericMappingTools/gmt/pull/6319), the default grid registration for remote files are as follows:

    1. All plotting modules: pixel-registration
    2. All processing modules: gridline-registration

This causes problems in some of the animation scripts that create an illumination file (processing=gridline) that will be applied to a relief map (plotting). The solution is to specify the registration for all the remote files used in the [examples](https://github.com/GenericMappingTools/gmt/tree/master/doc/examples).

**Are you willing to help implement and maintain this feature?** I can review, but would really appreciate help!

**Comment by joa-quim** [comment]
If someone wants to do this, please do.
