### ISSUE TITLE
Add and promote Ninja as make system for GMT

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7230]
**Description of the desired feature**

I think most/all the developers are using `ninja` to build GMT instead of older and slower `make`.  But, we do not push this anywhere, I think.  The [wiki](https://github.com/GenericMappingTools/gmt/wiki) list of prerequisites does not mention it.  I think we should put a plug somewhere as to why and add it as the preferred thing and then explain somewhere that the `cmake` command needs to take that generator, i.e.,

`cmake -G Ninja`

**Comment by anbj** [comment]
You say ``make`` in the first sentence - is this the same as the ``cmake`` that you refer to later?

**Comment by maxrjones** [comment]
> You say make in the first sentence - is this the same as the cmake that you refer to later?

`cmake` generates the platform specific build instructions (build generator), while `make` (or `ninja`) processes those instructions (build system)

make - https://en.wikipedia.org/wiki/Make_(software)
cmake - https://en.wikipedia.org/wiki/CMake
ninja - https://en.wikipedia.org/wiki/Ninja_(build_system)

**Comment by KristofKoch** [comment]
Not really prominently pushed here as well:

https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md

**Comment by anbj** [comment]
> > You say make in the first sentence - is this the same as the cmake that you refer to later?
> 
> `cmake` generates the platform specific build instructions (build generator), while `make` (or `ninja`) processes those instructions (build system)
> 
> make - https://en.wikipedia.org/wiki/Make_(software) cmake - https://en.wikipedia.org/wiki/CMake ninja - https://en.wikipedia.org/wiki/Ninja_(build_system)

Thanks!

**Comment by seisman** [comment]
FYI, I've opened PR #7837 to promote Ninja as an optional but recommended dependency. I also updated the wiki and added commands to install Ninja.
