### ISSUE TITLE
I installed GMT on windows and i keep getting module not found error. Please help me how to resolve it. 

### ISSUE THREAD

**Issue by Rabeearai** [GenericMappingTools/gmt#7232]
**Description of the problem**

**Full script that generated the error**

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by anbj** [comment]
Ask questions in the [forum](https://forum.generic-mapping-tools.org/).
