### ISSUE TITLE
gmt histogram error with "-I" outside the gmt begin/end context

### ISSUE THREAD

**Issue by SuwenJunliu** [GenericMappingTools/gmt#7240]
**Description of the problem**

the module **gmt histogram** occurs error with **-I** option outside the gmt begin/end context.

```
gmt histogram eq.dat -T -I
```

It will show **gmt [ERROR]: Shared GMT module not found: histogram**, and it may be caused by the requirement of [GMT Modern Mode](https://docs.generic-mapping-tools.org/dev/cookbook/one-liner.html), or at least the plotting command. But the tricky thing is, according to the documentation of [histogram](https://docs.generic-mapping-tools.org/6.4/histogram.html), **gmt histogram** with  **-I** option should not be considered as a plotting command, just like other commands such as **gmt surface** or **gmt blockmean**, which could be used outside the gmt begin/end context.

**System information**

* Operating system: Wsl1 of Win10
* GMT version (`gmt --version`): GMT-6.4.0

links of [eq.dat](https://docs.gmt-china.org/6.0/_downloads/37b97c4b8ba2615d0ceafaad3181bbc7/eq.dat)

**Comment by joa-quim** [comment]
Please, use the Forum for questions. 

This is an user error. In classic mode the name is **pshistogram**
