### ISSUE TITLE
@earth_day

### ISSUE THREAD

**Issue by kjz1997** [GenericMappingTools/gmt#7241]
Hello, everyone. When I used the command
`gmt begin D_20200930 png I+m0.2c gmt grdimage -JH15c @earth_day_30s -R113.040563/116.178443/34.666285/36.689723 -Baf -Bswne  gmt end show  pause`

It reported this error. What is the reason?

ERROR:
ERROR 1: TIFFFillTile:Read error at row 0, col 0, tile 119; got 0 bytes, expected 300
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: C:/Users/DELL/.gmt/server/earth/earth_day/earth_day_30s_p.tif, band 1: IReadBlock failed at X offset 119, Y offset 0:
TIFFReadEncodedTile() failed.
grdimage [WARNING]: (w - x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdimage [WARNING]: w reset from 113.040563 to 113.033333333
grdimage [WARNING]: (e - x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdimage [WARNING]: e reset from 116.178443 to 116.183333333
grdimage [WARNING]: (s - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdimage [WARNING]: s reset from 34.666285 to 34.6583333333
grdimage [WARNING]: (n - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdimage [WARNING]: n reset from 36.689723 to 36.6916666667
ERROR 1: TIFFFillTile:Read error at row 4294967295, col 4294967295, tile 4193; got 0 bytes, expected 59560
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: C:/Users/DELL/.gmt/server/earth/earth_day/earth_day_30s_p.tif, band 1: IReadBlock failed at X offset 137, Y offset 24: TIFFReadEncodedTile() failed.
grdimage [WARNING]: gmt_gdalread: GDALRasterIO failed to open band 0 [err = 3]
ERROR 1: TIFFFillTile:Read error at row 0, col 0, tile 119; got 0 bytes, expected 300
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: C:/Users/DELL/.gmt/server/earth/earth_day/earth_day_30s_p.tif, band 1: IReadBlock failed at X offset 119, Y offset 0:
TIFFReadEncodedTile() failed.

**Comment by PaulWessel** [comment]
Hard to tell what is wrong on your computer.  Probably the earth_day_30s_p.tif file got corrupted during transmission so maybe delete and start over.  All the WARNINGS are on you since you have a region that cuts across pixels.  I got this image popping out after a few seconds:

![D_20200930](https://user-images.githubusercontent.com/26473567/218306326-b9f5b903-3548-4b43-bd5d-d02aea492201.png)

**Comment by joa-quim** [comment]
Please, discuss this in the forum (I can't reproduce your error). 
I hope you are not running that entire command in a single line.
