### ISSUE TITLE
Correct fill syntax in pscost -E ... prints -R string

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#725]
Ex34 is still using the old pattern fill syntax. However, the new one has this effect

```
gmt pscoast  -R-6/20/35/52 -JM11 -Baf -BWSen -X5 -Glightgray -EFR,IT+gP8+r300 -Da
-R-6/20/35/52
```

**Comment by joa-quim** [comment]
The problem is that the ``+r300`` part is interpreted in ``gmt_DCW_parse()`` as meaning
```
	case 'r':	/* Get region from polygon(s) BB */
		F->region = true;
```

**Comment by PaulWessel** [comment]
I see.  So we need to protect that **+r**300 if **+gP** or **+gp** is given.  Will see.
