### ISSUE TITLE
Lots of warnings now building the docs

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7253]
Maybe this is standard but recently switched to home-brew and after git pull etc and building docs I get an enormous list of warnings like this:

```
[559/559] Building HTML documentation...
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/explain_-V.rst_:: WARNING: duplicate label -v, other instance in /Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/basemap.rst
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/explain_-V.rst_:: WARNING: duplicate label -v, other instance in /Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/batch.rst
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/explain_-I.rst_:: WARNING: duplicate label -i, other instance in /Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/batch.rst
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/rbuild/doc/rst/source/explain_-R.rst_:: WARNING: duplicate label -r, other instance in /Users/p

```
Anything obvious to those who speak RST?

**Comment by KristofKoch** [comment]
I get those too and found that [someone else had apparently the same problem](https://stackoverflow.com/questions/62631362/get-rid-of-duplicate-label-warning-in-sphinx). Maybe it is a lead worth following?

**Comment by PaulWessel** [comment]
We put faith in @seisman or @maxrjones to figure this out at some point.

**Comment by joa-quim** [comment]
Hmm, I only get these (and half come from non-committed branches
```
ninja docs_html
[557/557] Building HTML documentation...
C:\v\build\doc\rst\source\supplements\geodesy\earthtide.rst:94: ERROR: Unknown target name: "generate 1d array".
C:\v\build\doc\rst\source\supplements\potential\gmtflexure.rst:71: ERROR: Unknown target name: "generate 1d array".
C:\v\build\doc\rst\source\supplements\potential\talwani2d.rst:94: ERROR: Unknown target name: "generate 1d array".
source/explain_-R.rst_:6: WARNING: Duplicate explicit target name: "-r".
source/explain_-V.rst_:6: WARNING: Duplicate explicit target name: "-v".
C:\v\build\doc\rst\source\supplements\seis\shake.rst:8: ERROR: Undefined substitution referenced: "shake_purpose".
source/explain_-R.rst_:6: WARNING: Duplicate explicit target name: "-r".
source/explain_-V.rst_:6: WARNING: Duplicate explicit target name: "-v".
source/explain_-r.rst_:6: WARNING: Duplicate explicit target name: "-r".
C:\v\build\doc\rst\source\supplements\seis\vs30.rst:8: ERROR: Undefined substitution referenced: "vs30_purpose".
source/explain_-r.rst_:2: WARNING: duplicate label supplements/seis/vs30:the **-r** option, other instance in C:\v\build\doc\rst\source\supplements\seis\vs30.rst
C:\v\build\doc\rst\source\supplements\seis\shake.rst: WARNING: document isn't included in any toctree
C:\v\build\doc\rst\source\supplements\seis\vs30.rst: WARNING: document isn't included in any toctree
C:\v\build\doc\rst\source\cookbook\cpts.rst:105: WARNING: a suitable image for html builder not found: _images/GMT_App_M_1e.*
```

**Comment by joa-quim** [comment]
Now I also get hundreds of them.

**Comment by seisman** [comment]
Sphinx makes all explicit targets available globally, thus all targets must be unique. In our docs, we define targets like `-V` in one file and include it in many docs. That's why we see so many "duplicate label" warnings.

As far as I know, there is no option to suppress these warnings. So our only choice is to redirect all these warnings into a log file, and then use `grep` to filter out these useless warnings.

**Comment by PaulWessel** [comment]
I agree, silly decision by Sphinx. The grepped log is a good suggestion

**Comment by anbj** [comment]
I can't understand that no one has posted a feature request regarding this with the sphinx folks.
Surely must be a nuisance for others as well.

appending ``__`` to the target or something similar does not do anything either? (blind shot)

**Comment by seisman** [comment]
> I can't understand that no one has posted a feature request regarding this with the sphinx folks.
> Surely must be a nuisance for others as well.

There are already some complaints similar to our situation (e.g., https://github.com/sphinx-doc/sphinx/issues/10202). 



> appending `__` to the target or something similar does not do anything either? (blind shot)

I don't think it will work. The same target is still defined multiple times in the entire docs.
