### ISSUE TITLE
Changing font with @% in text also changes font size

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7254]
```
julia> text(rich("H", subscript("2"), "O is the ", smallcaps("formula")," for ", rich(underline("water"), color=:red, font=4), " liquid"), x=1, y=1, show=true, Vd=1)
        pstext  -JX14c/0 -Baf -BWSen -R0.948/1.052/0.948/1.052 -P -K > C:\TEMP\GMTjl_tmp.ps
```
The text that was generated by that ``rich()`` function, was:
```
"H@-2@-O is the @#formula@# for @%4%@;red;@_water@_@;;@%% liquid"
```
and the fig

![GMTjl_tmp](https://user-images.githubusercontent.com/537321/220123101-acff5e3c-b269-4114-99a4-714444c39cc6.png)

**Comment by PaulWessel** [comment]
The PostScript created by

` echo "H@-2@-O is the @#formula@# for @%4%@;red;@_water@_@;;@%% liquid" | gmt text -F+cMC  -JX14c/0 -Baf -BWSen -R0.948/1.052/0.948/1.052 -ps map 
`

gives the same map and tells me all the text has exactly the same specified size (FP 159 F4 for water, FP 159 F0 for "for") etc., so I think you are just assuming that all fonts are the same height if given 12p etc.  They are not.

**Comment by joa-quim** [comment]
Ok, better than.
