### ISSUE TITLE
Incorrect frame for Mercator projection with non-zero center longitude

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7256]
**Description of the problem**

```
gmt basemap -JM120/15c -R-180/180/-70/70 -Bafg -png map
```
![map](https://user-images.githubusercontent.com/3974108/220272746-619d6054-a302-4928-962e-fff28a656b93.png)

**System information**

* Operating system: Linux 
* GMT version (`gmt --version`): `6.5.0_609ccc1_2023.01.16`

**Comment by joa-quim** [comment]
Even this screws.
```
gmt basemap -JM0.000001/15c -R-180/180/-70/70 -Bafg -png map
```

**Comment by PaulWessel** [comment]
Yep.  Looks like only 0, 180 and 360 work.

**Comment by joa-quim** [comment]
But I'm confused. What is the expected outcome of? ``-JM120/15c -R-180/180/-70/70``

**Comment by joa-quim** [comment]
Yes, certainly not what we get but don't see what is expected. If one gives -R (and we must), what's the point of setting a central meridian in that map?

**Comment by PaulWessel** [comment]
Maybe in other projections we center on that meridian but not Mercator?

**Comment by joa-quim** [comment]
Hmm, I see happening in conicals, but in cylindrical?

**Comment by PaulWessel** [comment]
Would seem we should be consistent across all projections where setting central meridian setting is an option. Default is mid range but looks like for Mercator, going back to beginning, is different?

**Comment by joa-quim** [comment]
Ok, this doesn't error
```
gmt basemap -JQ120/15c -R-90/180/-70/70 -Bafg -png map
```
but the result is exactly equal to
```
gmt basemap -JQ15c -R-90/180/-70/70 -Bafg -png map
```
So, again, what's the point of setting a central meridian?

**Comment by PaulWessel** [comment]
I think it was for mapproject in order to set origin

**Comment by joa-quim** [comment]
Yes, thought on it too. But it means we should simply ignore lon_0 in cylindrical maps. Then this issue disappears.

**Comment by PaulWessel** [comment]
Not at laptop so cannot tell if your -JQ example uses mid range or 120?

**Comment by joa-quim** [comment]
It tries to use both, I think.

**Comment by PaulWessel** [comment]
How about all other cylindrical projections? Is it just Mercator that is unusual?

**Comment by joa-quim** [comment]
At least -JQ & -JJ are insensitive to lon_0

**Comment by joa-quim** [comment]
Closing as the show case no longer happens
