### ISSUE TITLE
Docs - gmt.conf : add all parameters to table

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7257]
I would like to create a 3rd column to the [THEMATIC SUB-SECTIONS prefix](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#common-specifications)-table, where all paramters are listed and linked to. Now it just contains the sub-sections, which is nice, but I think a listing - and direct links - to all params would be nice.

Alternatively make a new table where all params are listed with a brief description.

Interesting? Comments?

**Comment by anbj** [comment]
Something like this:

```
| THEMATIC SUB-SECTIONS | prefix | Parameters | description                                                        |
|-----------------------|--------|------------|--------------------------------------------------------------------|
| COLOR Parameters      | COLOR_ | BACKGROUND | Color used for the background of images                            |
|                       |        | FOREGROUND | Color used for the foreground of images                            |
|                       |        | CPT        | Default CPT table when none is selected                            |
|                       |        | ...        | ...                                                                |
| DIR Parameters        | DIR_   | CACHE      | Cache directory where we save remote cache filenames starting in @ |
|                       |        | DATA       | Session data directory                                             |
|                       |        | ...        | ...                                                                |
```

**Comment by joa-quim** [comment]
Looks nice, but needs a firm grip to not let it be wider (and if possible a bit less) than that.

**Comment by seisman** [comment]
You may want to use the list-table syntax to avoid too-wide tables.

https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table

**Comment by anbj** [comment]
Thanks for input. I'm amazed by all of the parameters available, it's going to be quite a table..

How does this look? I tried having blank fields instead of `-`, but sphinx didn't understand that.

![Screenshot from 2023-02-21 20-42-07](https://user-images.githubusercontent.com/29237824/220442993-778218ab-8c04-4ead-aa38-186ebdc7d00e.png)

**Comment by joa-quim** [comment]
That's what I'm afraid. There are more than 120 parameters and we don't want a huge table

**Comment by anbj** [comment]
> You may want to use the list-table syntax to avoid too-wide tables.
> 
> https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table

Thanks @seisman, I think this is a more handy way of doing it.

**Comment by anbj** [comment]
> That's what I'm afraid. There are more than 120 parameters and we don't want a huge table

Yes, it's going to be huge. I dont mind doing it, but if it just creates noise I'm not sure it's worth it.

**Comment by joa-quim** [comment]
Maybe wait until we have 3D tables that fit in a single screen 😄

**Comment by anbj** [comment]
I'll see what Darth has to say about his, before doing more work/closing.

**Comment by PaulWessel** [comment]
Darth has other things on his mind these days  I see no harm but a manually produced table tend to get out of sync as we add parameters. In the old days we had scripts and makefiles who built lots of doc includes, but with CMAKE it took Florian Wobbe's work to create things that CMAKE could run (we still have stuff built by CMAKE but less than before).
But narrower the better.

**Comment by anbj** [comment]
Thanks; I'll stop here. Maybe in the future!
