### ISSUE TITLE
contour -A+e option will trim out other commands

### ISSUE THREAD

**Issue by BerginJay** [GenericMappingTools/gmt#7258]
**Description of the problem**

When using -A+e option of gmt contour, the output of other commands may be incorrectly truncated. For example, if one use the legend command after contour to draw on the outside of the basemap, and the added legend has no overlapping parts with the text of contour, the legend is still incorrectly trimed. The current workaround is to use the contour command at the end or turn off the clip path manually by using `clip -C` .

**Full script that generated the error**

```
#!/usr/bin/env bash

gmt begin ex01
	gmt subplot begin 2x1 -A -M0.5c -Blrtb -Bafg -T"Low Order Geoid" -Fs16c/0 -Rg -JH16c
		gmt coast -JH? -Glightbrown -Slightblue -c0,0
		gmt grdcontour @osu91a1f_16.nc -C10 -A50+f7p -Gd10c -Ln -Wcthinnest,- -Wathin,- -T+d8p/2p+l
		gmt legend -DJBC+w10+o0/-.5c <<EOF
L 14p C this is a test without +e
EOF

		gmt coast -JH? -Glightbrown -Slightblue -c1,0
		gmt grdcontour @osu91a1f_16.nc -C10 -A50+f7p+e -Gd10c -Ln -Wcthinnest,- -Wathin,- -T+d8p/2p+l
		#gmt clip -C  # turn off the clip path manually
		gmt legend -DJBC+w10+o0/-.5c <<EOF
L 14p C this is a test with +e
EOF
	gmt subplot end
gmt end show
```

**Actual outcome**
As one can see, in subplot panel (b), the legend outside the basemap and the subplot number "b)" are both incorrectly truncated.

BTW, The `Cs` option in `then turning off clipping with clip -Cs which finally plots the original text` mentioned in the module document of [contour](https://docs.generic-mapping-tools.org/6.4/contour.html) currently invalid.

**System information**

* Operating system: macOS 12.6
* GMT version (`gmt --version`): 6.4.0

**Comment by BerginJay** [comment]
> The -A+e and clip -Cs predate subplots so I am not surprised. Does it work if you call clip for each panel?

Yes, if I call `clip -C` manually after legend, the legends and numbers are displayed properly. The question is that the contour annotations do not overlap with the area outside the basmap so the need to manually close the path seems counterintuitive.

**Comment by PaulWessel** [comment]
Think the best we can do is to improve the docs with those suggestions.  All this is coded in the PostSCript language so hard to redo without time or motivation.

**Comment by BerginJay** [comment]
Got it, I think I might try to submit a PR on the documentation, until then I'll keep this issue open if you don't mind.
