### ISSUE TITLE
grdview -D is broken in classic but not in modern

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7261]
```
gmt grdcut  @earth_relief_01m_p -R0/10/0/10 -Gtopo.nc
```
- Classic
```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@earth_day_01d_p.tif -Baf -BWSne -Qi100 -P > lixo_classic.ps
```

![lixo_classic](https://user-images.githubusercontent.com/537321/221190809-8f1108aa-5ac0-46d9-a45e-6851bd8e805a.png)

- Modern
```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@earth_day_01d_p.tif -Baf -BWSne -Qi100 -png lixo_modern
```
![lixo_modern](https://user-images.githubusercontent.com/537321/221190753-a6e588ad-887c-459f-a144-92fffc5334db.png)

**Comment by joa-quim** [comment]
Another side of this bug is that in classic this works (we have a test with it)
```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@wood_texture.jpg -Baf -BWSne -Qi100 -P > lixo.ps
```
but in modern it crashes

```
gmt grdview topo.nc -I+nt0.5 -JM5i -JZ2i -p145/35 -G@wood_texture.jpg -Baf -BWSne -Qi100 -png lixo_modern
```
I found out the reasons but can't make my cure work because of the C mysteries. It insisting in crashing when freeing an reallocated memory.

**Comment by joa-quim** [comment]
Damn it. Now  Classic and non-referenced image is upside-down. Can't find a way that pleases all  combinations of Classic/Modern vs Ref/nonRef

**Comment by PaulWessel** [comment]
Important that we do not break C CLI to make life easier in Julia.  We need to make sure it is solid in the CLI.

**Comment by joa-quim** [comment]
Ir was badly broken in CLI before these fixes.
