### ISSUE TITLE
Plotting Shapefile Issue

### ISSUE THREAD

**Issue by fboschetty** [GenericMappingTools/gmt#7277]
Hi,

I'm attempting to plot a shapefile containing lakes from https://www.bcn.cl/siit/mapas_vectoriales/index_html.
It's the masa de agua file.
The shapefile opens fine in QGIS, but it has many many features.
I've tried saving a smaller region on the shapefile (masas_lacustres_SMALL.shp also attached) but I get the same error.

**GMT script:**
```
#map parameters
proj=-JM15
bounds=-R-72.20/-71.75/-39.55/-39.25

#Files
lakes=/Users/FelixBoschetty/Desktop/ChileShapeFiles/Masas_Lacustres/masas_lacustres.shp

gmt begin 2015_Sampling
  gmt basemap $proj $bounds -Baf
  # Plot lakes
  gmt plot $lakes $bounds $proj -Glightblue
gmt end show
```
The error I get is:
[ERROR]: Bad OGR/GMT: @n not allowed before FEATURE_DATA

I get a blank basemap with no lakes!

Thanks,

Felix

--------------

GMT version 6.4.0
MacOS Monterey 12.6.3

[masas_lacustres_SMALL.zip](https://github.com/GenericMappingTools/gmt/files/10839076/masas_lacustres_SMALL.zip)
[Masas_Lacustres.zip](https://github.com/GenericMappingTools/gmt/files/10839077/Masas_Lacustres.zip)

**Comment by anbj** [comment]
Post questions in the forum, https://forum.generic-mapping-tools.org/.

**Comment by joa-quim** [comment]
And honestly, if this is in fact a bug it won't be fixed soon. What is advised here is to try ``ogr2ogr`` to do manually do the conversion to the ``gmt`` format and feed that to ``plot``. I'm going to close this issue. As said please continue it in the forum.

**Comment by PaulWessel** [comment]
Looks like -a was never specified
