### ISSUE TITLE
van der Grinten projection (-JV) fails in non -Rg domains

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#7282]
**Description of the problem**

When plotting a global map with the *van der Grinten* projection (`-JV`) everything behaves as expected, when using it to plot quadrants or hemispheres things go wild: Instead of quadrants or hemispheres I get modern art.

**Full script that generated the error**

```
gmt begin van_der_Grinten_quadrants_hemispheres png
  gmt subplot begin 2x4 -Fs8c/16c -M8c/1c -T"van der Grinten quadrant & hemisphere maps"
    while read minX maxX minY maxY title
    do
    gmt subplot set
      gmt coast -R${minX}/${maxX}/${minY}/${maxY} -JV0/8c -Bg -Dc -Glightgray -Scornsilk -A10000 -Wthinnest -B+t"${title}"
    done << EOF
-180   0   0 90 NW
   0 180   0 90 NE
   0 180 -90  0 SE
-180   0 -90  0 SW
-180   0 -90 90 W
-180 180   0 90 N
   0 180 -90 90 E
-180 180 -90  0 S
EOF
  gmt subplot end
gmt end show
```
If you prefer a one-liner use the following for a plot of the NW quadrant:
```
gmt coast -R-180/0/0/90 -JV0/10c -Bg -Dc -Glightgray -Scornsilk -A10000 -Wthinnest -view van_der_Grinten_NW_quadrant
```

**Full error message**

*No error messages generated*

**Actual outcome**

![van_der_Grinten_quadrants_hemispheres](https://user-images.githubusercontent.com/45796239/221960467-3361f95d-2de9-4fa8-8acc-522adb6ae73d.png)

**Expected outcome**

Four quadrant maps in the first row and four hemisphere maps in the second row in above plot.

**System information**

* Operating system: MacOS 13.2.1
* GMT version (`gmt --version`): 6.5.0_51b8cba_2023.02.25 also fails with 6.4.0

**Comment by KristofKoch** [comment]
Additionally similar things happen with the *Winkel Tripel* projection (`-JR`). Maybe related?

Trying to plot a western hemisphere:

Central meridian is on the domain border (0°): **fail**
![winkel-0](https://user-images.githubusercontent.com/45796239/221969239-57bd66ef-1da6-44aa-9a4f-00e2ee9432fc.png)
```
gmt coast -R-180/0/-90/90 -JR0/12c -Bg -Dc -A10000 -Gburlywood4 -Swheat1 -png winkel-0
```

Central meridian is outside the plot domain (+0.0000001°): **fail** 
![winkel-pos0 000001](https://user-images.githubusercontent.com/45796239/221969273-191310c2-9557-45bb-9511-758146d2a31a.png)
```
gmt coast -R-180/0/-90/90 -JR0.0000001/12c -Bg -Dc -A10000 -Gburlywood4 -Swheat1 -png winkel-pos0.000001
```

Central meridian is inside the plot domain (-0.0000001°): **correct** 
![winkel-neg0 000001](https://user-images.githubusercontent.com/45796239/221969300-16d8e654-e082-4a4a-9567-09401fb273f8.png)
```
gmt coast -R-180/0/-90/90 -JR-0.0000001/12c -Bg -Dc -A10000 -Gburlywood4 -Swheat1 -png winkel-neg0.000001
```

**Comment by KristofKoch** [comment]
Further experimentation confirms that it fails for all projections from the [Cookbook 6.4. Miscellaneous projections](https://docs.generic-mapping-tools.org/latest/cookbook/map-projections.html#miscellaneous-projections) chapter and also for the Mercator `-JM` projection.

**Comment by PaulWessel** [comment]
The pending #7287 appears to fix cases NE, SE, N, E, and S but works is needed for NW, SW and W - all probably related to central meridian issues.

**Comment by PaulWessel** [comment]
Removing the forced 0 central longitude from the voce script gives correct results.  So it is an issue of what that parameters is used for and why it bites so hard.

**Comment by KristofKoch** [comment]
Nice work! Thank you!
