### ISSUE TITLE
Bug or documentation issue: -Xc and -Xf don't work in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7296]
**Description of the problem**
In the following script, I try to shift the plotting origin with different ways. `-X10c`, `-Xa10c` and `-Xr10c` work as expected, but `-Xc10c` and `-Xf10c` don't.

```
gmt begin
for mode in "" "a" "c" "f" "r"; do
	echo "Shift plotting origin with -X${mode}10c"
	gmt figure shift-X${mode}10c png
	gmt basemap -R0/10/0/10 -JX10c -Baf -B+tFrame1
	gmt basemap -R0/10/0/10 -JX10c -Baf -B+tFrame2 -X${mode}10c
	gmt basemap -R0/5/0/5 -JX5c -Baf -B+tFrame3
done
gmt end show
```

**`-X10c` or `-Xr10c`**
![shift-X10c](https://user-images.githubusercontent.com/3974108/223003041-a3069372-d663-455d-b1c3-421c855b3e4d.png)

**-Xa10c**
![shift-Xa10c](https://user-images.githubusercontent.com/3974108/223003104-8f6c320d-434f-43ab-8db9-d75b20549bd5.png)

**-Xc10c**
![shift-Xc10c](https://user-images.githubusercontent.com/3974108/223003122-b2a4dcc4-95da-4108-ae39-24b2775cd473.png)

**-Xf10c**
![shift-Xf10c](https://user-images.githubusercontent.com/3974108/223003157-17b69369-5373-4fda-ae08-63d4b36f433d.png)

**System information**

* GMT version (`gmt --version`): 6.5.0_21ae9cb_2023.03.05

**Comment by PaulWessel** [comment]
Just so I understand, those work OK in classic? I can see why they may not be appropriate in modern mode so perhaps the easy way out is to

1. State in the documentation that **-Xc**|**f** are for classic only
2. Actually disallow those settings in modern.

**Comment by seisman** [comment]
> Just so I understand, those work OK in classic? I can see why they may not be appropriate in modern mode so perhaps the easy way out is to
> 
> 1. State in the documentation that **-Xc**|**f** are for classic only
> 2. Actually disallow those settings in modern.

I agree that both make no sense in modern mode.

**Comment by PaulWessel** [comment]
Implementing the new check on -Xc and -Xf yields 5-6 failures as those scripts used -Xc I think.  Will need to run without to see if any issues,

**Comment by seisman** [comment]
> Is it related?
> 
> #6291

I think these two issues are related. 

Do you agree that `-Xc` and `-Xf` don't make sense in modern mode?

Could you please check if you still have the problem in #6291 after Paul's  
PR https://github.com/GenericMappingTools/gmt/pull/7304 is merged into master?
