### ISSUE TITLE
grdpaste

### ISSUE THREAD

**Issue by kjz1997** [GenericMappingTools/gmt#7313]
When I use "grdpaste" to merge two grd files, it reports an error of "Grids do not share a common edge"
commad: gmt grdpaste vel_F1.grd vel_F2.grd -Gvel.grd

* Operating system:linux
* GMT version (`gmt --version`):Version 6.2.0
* Two grd files are adjacent satellite strips
![quick-look](https://user-images.githubusercontent.com/89446964/223919472-91c7b5e5-e5da-4138-a353-cdf74ffedd89.png)

**Comment by PaulWessel** [comment]
**grdpaste** pastes two grids and do not merge them (see **grdblend** for that).  And of course you checked first via **grdinfo** that the two grids indeed share an exact common edge? If so, please post the output of **grdinfo** for the two grids.

**Comment by kjz1997** [comment]
This is the information
root@kj-virtual-machine:/media/root/Seagate/GTM_SBAS# gmt grdinfo vel_F1.grd 
vel_F1.grd: Title: Mean Line-Of-Sight velocity from SBAS
vel_F1.grd: Command: sbas intf.tab scene.tab 49 29 2691 6096 -range 855224.2890378854 -incidence 36 -wavelength 0.0554658 -atm 2.0 -smooth 2.0 -rms 
vel_F1.grd: Remark: Mean LOS velocity from SBAS (mm/yr)
vel_F1.grd: Pixel node registration used [Cartesian grid]
vel_F1.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel_F1.grd: x_min: 0 x_max: 21528 x_inc: 8 name: x n_columns: 2691
vel_F1.grd: y_min: 0 y_max: 12192 y_inc: 2 name: y n_rows: 6096
vel_F1.grd: v_min: -311.103149414 v_max: 97.4854354858 name: z
vel_F1.grd: scale_factor: 1 add_offset: 0
vel_F1.grd: format: netCDF-4 chunk_size: 129,130 shuffle: on deflation_level: 3
root@kj-virtual-machine:/media/root/Seagate/GTM_SBAS# gmt grdinfo vel_F2.grd 
vel_F2.grd: Title: Mean Line-Of-Sight velocity from SBAS
vel_F2.grd: Command: sbas intf.tab scene.tab 43 29 3180 6096 -range 855224.2890378854 -incidence 36 -wavelength 0.0554658 -atm 2.0 -smooth 2.0 -rms 
vel_F2.grd: Remark: Mean LOS velocity from SBAS (mm/yr)
vel_F2.grd: Pixel node registration used [Cartesian grid]
vel_F2.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel_F2.grd: x_min: 0 x_max: 25440 x_inc: 8 name: x n_columns: 3180
vel_F2.grd: y_min: 0 y_max: 12192 y_inc: 2 name: y n_rows: 6096
vel_F2.grd: v_min: -386.480621338 v_max: 260.788604736 name: z
vel_F2.grd: scale_factor: 1 add_offset: 0
vel_F2.grd: format: netCDF-4 chunk_size: 133,130 shuffle: on deflation_level: 3

**Comment by PaulWessel** [comment]
Well, they are not side- by-side but on top of each other, so no pasting.  If you are looking to merge into one by averaging, see **grdblend**.

**Comment by kjz1997** [comment]
ok,thank you very much

**Comment by kjz1997** [comment]
I wonder if this is a common boundary?
root@kj-virtual-machine:/media/root/Seagate/GTM_SBAS/F2/SBAS# gmt grdinfo vel_l_F1.grd 
vel_l_F1.grd: Title: z
vel_l_F1.grd: Command: xyz2grd llpb -R113.097222222/114.361111111/34.7222222222/36.3777777778 -I2.5s/2s -r -fg -Gvel_l_F1.grd -bi3f
vel_l_F1.grd: Remark: 
vel_l_F1.grd: Pixel node registration used [Geographic grid]
vel_l_F1.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel_l_F1.grd: x_min: 113.097222232 x_max: 114.361111121 x_inc: 0.000694444444505 name: longitude n_columns: 1820
vel_l_F1.grd: y_min: 34.7222222232 y_max: 36.3777777788 y_inc: 0.00055555555557 (2 sec) name: latitude n_rows: 2980
vel_l_F1.grd: v_min: -311.103149414 v_max: 97.4854354858 name: z
vel_l_F1.grd: scale_factor: 1 add_offset: 0
vel_l_F1.grd: format: netCDF-4 chunk_size: 130,130 shuffle: on deflation_level: 3
root@kj-virtual-machine:/media/root/Seagate/GTM_SBAS/F2/SBAS# gmt grdinfo vel_F2_l.grd 
vel_F2_l.grd: Title: z
vel_F2_l.grd: Command: xyz2grd llpb -R113.993055556/115.305555556/34.9222222222/36.5722222222 -I2.5s/2s -r -fg -Gvel_F2_l.grd -bi3f
vel_F2_l.grd: Remark: 
vel_F2_l.grd: Pixel node registration used [Geographic grid]
vel_F2_l.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel_F2_l.grd: x_min: 113.993055556 x_max: 115.305555556 x_inc: 0.000694444444444 name: longitude n_columns: 1890
vel_F2_l.grd: y_min: 34.9222222222 y_max: 36.5722222222 y_inc: 0.000555555555556 (2 sec) name: latitude n_rows: 2970
vel_F2_l.grd: v_min: -386.480621338 v_max: 227.032974243 name: z
vel_F2_l.grd: scale_factor: 1 add_offset: 0
vel_F2_l.grd: format: netCDF-4 chunk_size: 135,130 shuffle: on deflation_level: 3

**Comment by PaulWessel** [comment]
What is there to wonder? 

```
-R113.097222222/114.361111111/34.7222222222/36.3777777778 
 -R113.993055556/115.305555556/34.9222222222/36.5722222222

```
have no common w/e or s/n etc.

**Comment by Esteban82** [comment]
I am closing this. There is no real bug.
