### ISSUE TITLE
Add a test program to show how to correctly pass a user-created GMT_GRID structure to GMT API?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7316]
Recently I'm working on wrapping the GMT_GRID structure in PyGMT. I want to convert a `xarray.DataArray` object (grid data in the Python ecosystem) to `GMT_GRID` and pass it to GMT modules, but I'm always getting `pointer being freed was not allocated` or `double free` errors.

Here is a C program that shows what I'm doing in PyGMT. 
```C
#include "gmt.h"

int main () {
	unsigned int mode = GMT_SESSION_EXTERNAL;
	struct GMT_GRID *G = NULL;
	struct GMTAPI_CTRL *API = NULL;
	uint64_t dim[2] = {5, 4};
	char args[1000] = {""};
	char input[GMT_VF_LEN] = {""};
	float *data = NULL;

	API = GMT_Create_Session ("test", 2U, mode, NULL);

	/* create a container for the grid */
	G = GMT_Create_Data(API, GMT_IS_GRID, GMT_IS_SURFACE, GMT_CONTAINER_ONLY, dim, NULL, NULL, 0, 0, NULL);

	/* allocate memory of the data array in the external program (C or PyGMT) */
	data = (float *)malloc(sizeof(float) * 5 * 4);
	for (int i=0; i<5*4; i++) data[i] = (float)i;

	/* assign the user data to the GMT_GRID structure */
	G->data = data;

	/* Using the grid */
	GMT_Open_VirtualFile (API, GMT_IS_GRID, GMT_IS_SURFACE, GMT_IN|GMT_IS_REFERENCE, G, input);
	sprintf (args, "%s", input);
	GMT_Call_Module(API, "grd2xyz", GMT_MODULE_CMD, args);
	GMT_Close_VirtualFile (API, input);

	/* Trying to free the data array because it's allocated by the external program. */
	free(data);

	if (GMT_Destroy_Session (API)) return EXIT_FAILURE;
	exit (0);
}
```
After compiling and running the program, I'm getting the following results:
```
./a.out
0	3	0
1	3	1
2	3	2
3	3	3
4	3	4
0	2	5
1	2	6
2	2	7
3	2	8
4	2	9
0	1	10
1	1	11
2	1	12
3	1	13
4	1	14
0	0	15
1	0	16
2	0	17
3	0	18
4	0	19
a.out(15749,0x7ff85df95680) malloc: *** error for object 0x6000004680f0: pointer being freed was not allocated
a.out(15749,0x7ff85df95680) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    15749 abort      ./a.out
```
As you can see, the output is correct, but there is an error. I think the error is because the memory of the `data` array is freed by both the C program and GMT.

Am I doing something wrong? Is it a GMT API bug? Anyway, it would be great if we can have a testapi_* program which shows how to do it correctly.

**Comment by PaulWessel** [comment]
Hm, you could try `free (G->data) `and then `G->data = NULL`.  But even if that works, perhaps you wish to add this code as` testapi_grid.c `to our suite and then it is easier (for me) to debug in Xcode since it will be built.

**Comment by joa-quim** [comment]
Dongdong, probably not easy to read at firs attempts but I think it's instructive to see what I do in GMT.jl. See function
https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L906
I think the problem is that you did not declare that memory is external, which is what line 944
```
GMT_Set_AllocMode(API, GMT_IS_GRID, G)	# Otherwise memory already belongs to GMT
```
does when in GMT it sets ``GH->alloc_mode = GMT_ALLOC_EXTERNALLY;``

**Comment by PaulWessel** [comment]
@joa-quim, that function looks like I wrote it but has no comments and no mention in the API docs.  Do you remember the genesis of `GMT_Set_AllocMode` - probably you needed it in Julia?

**Comment by joa-quim** [comment]
No particular recall. More likely we needed it for the MEX.

**Comment by seisman** [comment]
> Dongdong, probably not easy to read at firs attempts but I think it's instructive to see what I do in GMT.jl. See function https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gmt_main.jl#L906 I think the problem is that you did not declare that memory is external, which is what line 944
> 
> ```
> GMT_Set_AllocMode(API, GMT_IS_GRID, G)	# Otherwise memory already belongs to GMT
> ```
> 
> does when in GMT it sets `GH->alloc_mode = GMT_ALLOC_EXTERNALLY;`

Thanks! Using `GMT_Set_AllocMode` works as expected!

But I'm still unsure if there is a function design issue. 

When passing `GMT_CONTAINER_ONLY` to `GMT_Create_Data`, `GMT_Create_Data` calls the `gmt_create_grid` function to create the container and also sets `alloc_mode` to `GMT_ALLOC_INTERNALLY`. It makes no sense to me because `gmt_create_grid` doesn't allocate memory for the data array. Perhaps we should not set `alloc_mode` here. Instead, we can set `alloc_mode` in the `gmtapi_alloc_grid` function: https://github.com/GenericMappingTools/gmt/blob/9ab65cd9c9977fb550f86f7807f219d7ce2f4748/src/gmt_api.c#L608

It seems the grid xy coords don't have the same issue, because `xy_alloc_mode` is set in `gmtapi_alloc_grid_xy`. https://github.com/GenericMappingTools/gmt/blob/9ab65cd9c9977fb550f86f7807f219d7ce2f4748/src/gmt_api.c#L634
