### ISSUE TITLE
Add file in cache for mgd77track

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7330]
In the docs of [mgd77track](https://docs.generic-mapping-tools.org/dev/supplements/mgd77/mgd77track.html#mgd77track) there is this example

```
gmt mgd77track 01010007 -R70W/20E/40S/20N -Jm0.1 -B10g5 -A10 \
               -La1da1000kf6hf250k -pdf map
```
I think it would be good to have a real file (that should be hosted in the server) so the users could try. I could look for in the internet but maybe there is already one in the cache (I look a bit and I didn't find). Or someone has one in their pc. 

**Are you willing to help implement and maintain this feature?** Yes

**Comment by anbj** [comment]
Sorry for asking a question here; but since you commented on my forum post; can **mgd77track** read nmea?

**Comment by Esteban82** [comment]
I don't think so. This module reads mgd77 files. 

https://www.ngdc.noaa.gov/mgg/dat/geodas/docs/mgd77.txt

**Comment by anbj** [comment]
Ok, thanks.

I got the impression that it could (ref. my [forum](https://forum.generic-mapping-tools.org/t/animation-ship-track-from-nmea/3758) post).

**Comment by anbj** [comment]
Yes - I mean original NMEA.

**Comment by PaulWessel** [comment]
Your best bet would be to awk your track data to the plain tab-separated format (see **-Ft** in **mgd77convert**) and save as a `*.dat `file. That can then be used with the mgd77 tools.

**Comment by anbj** [comment]
Thanks Paul - and sorry for using github as forum.

**Comment by Esteban82** [comment]
About the main topic of this issue, I think you agree, so I will look after the 01010007 cruise.

**Comment by joa-quim** [comment]
This actually uncovered a bug. The command doesn't work in a one-liner modern.

```
gmt mgd77track 01010006 -R80W/66W/27N/33N -Jm1 -B10g5 -A10 -La1da1000kf6hf250k -png lixo
Error: /undefinedresult in --charpath--
Operand stack:
   (1963\25503\25513+00:00:00)   0   (1963\25503\25513+00:00:00)   true
Execution stack:
```
but it does in classic

![lixo](https://user-images.githubusercontent.com/537321/228390016-77ff29a5-b9ab-47d9-815b-cdae0fa1e260.png)

[01010006.nc.zip](https://github.com/GenericMappingTools/gmt/files/11095188/01010006.nc.zip)

**Comment by Esteban82** [comment]
Ok. Now that it works, I will add the file in the cache folder and edit the documentation.
