### ISSUE TITLE
Documentation : DCW long name list

### ISSUE THREAD

**Issue by gd-a** [GenericMappingTools/gmt#7335]
[for background discussion](https://forum.generic-mapping-tools.org/t/how-to-create-a-heatmap/1478/13?u=planetgus)

Would it be possible to add a sorted list of DCW long names available to gmt via -E (?and -R?).

It's not efficient to have to look at wikipidia for ISO-code, and sometimes the proper ISO-code isn't recognize by gmt. 

After a brief conversation with @Esteban82, I don't think that a very well structured list is necessary. But just something with 3 levels would be enough
>
1. Continent
    a. Country
        i. list of all regions and sub-regions in simple alphabetical order

With the long name format (I'm not even sure ISO-code is needed to be honest), a simple search in the page would be enough to know whether the region one is interested in exists in gmt.

somewhere [here](https://github.com/GenericMappingTools/dcw-gmt#readme) or create a more "gmt doc-like" page around [here](https://docs.generic-mapping-tools.org/dev/datasets.html) also referenced in **Quick links** *in a similar way as [this one](https://docs.generic-mapping-tools.org/dev/cookbook/octal-codes.html)*

**Comment by Esteban82** [comment]
I think it could be helpfull. I think that should include the DCW-Collections also.


Just two side comments:

> and sometimes the proper ISO-code isn't recognize by gmt.


Do you mean the ISO 3166-1 Alpha 2 codes? Do you have an example. Because, if so, then it is a bug. 


> (I'm not even sure ISO-code is needed to be honest)

There are names that are difficult to write or very long (like `Bolivia (Plurinational State of)`)

**Comment by Esteban82** [comment]
*. The one for Sicilia like in the forum's discussion ?

Ahh, ok. I see. But the isocodes have political meaning (countries, special territories). And Sicilia as used in the forum is related to the Island (it is part of the DCW-Collections). Which is not exactly the same as the Italian Region. Especially in relation to the geographic region they include (If you make a map of the Italian Region, Malta will appear).
