### ISSUE TITLE
Web documentation missing

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#7338]
**Description of the problem**

All documentation under https://docs.generic-mapping-tools.org is not available giving a http 404 error.

Also see forum thread "[GMT online documentation has disappeared](https://forum.generic-mapping-tools.org/t/gmt-online-documentation-has-disappeared/3779)"

**Comment by seisman** [comment]
Someone deleted the gh-pages branch, which hosts all the GMT documentation.

**Comment by seisman** [comment]
I have a gh-pages branch in my local copy, which is a snapshot on March 15 (one week ago, so not that bad). I'm pushing my local copy to GitHub to recover the online documentation. It may take several minutes. So please be patient.

**Comment by seisman** [comment]
The documentation is back online https://docs.generic-mapping-tools.org.

**Comment by KristofKoch** [comment]
Thank you, that was quick! I'm curious how you can simply delete a repository of such a big project …

**Comment by seisman** [comment]
FYI, I've enabled branch protection for the `gh-pages` branch in the settings (https://github.com/GenericMappingTools/gmt/settings/branches). Now, the `gh-pages` branch can't be deleted unless we change the settings again. But I'm unsure if the CI can push changes to the branch or not, so we need to see if the gh-pages branch is updated correctly in the following days.

**Comment by joa-quim** [comment]
Sorry, must have been me. We had some 80 stalled branches and I did a cleaning but taking care of no deleting anything that was "open" or "draft". The ``gh-pages`` didn't have any of those labels and slipped in into the deleted group.
