### ISSUE TITLE
The use of ogr2ogr to convert shape files to to ascii GMT/OGR files

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#735]
Currently, we use the #ifdef HAVE_GDAL to determine if we may issue system calls to **ogr2ogr** for translation of shape files.  However, that test checks if the GDAL library and include files are present, _not_ if the executable **ogr2ogr** is present.  Perhaps we need to have CMake check if **ogr2ogr** is available and set HAVE_OGR2OGR and use that instead?

**Comment by PaulWessel** [comment]
Also noted that **psconvert** makes a call to **gdal_translate** which is similar to the case of GMT calling **ogr2ogr**.

**Comment by joa-quim** [comment]
We can do much better. Since GDAL version 2.???? (need to find out) we can just use the library for that. Below is a piece of code that found (and modified) somewhere to call ogr2ogr from the lib. I'm certain that we can do the same with gdal_translate.
We would still maintain the system calls for older GDAL versions (there are still 1.11 versions trailing around - guess the OS who does it)

```
GDALAllRegister();

char **argv = NULL;
int error = FALSE;

argv = CSLAddString(argv, "-f");
argv = CSLAddString(argv, "GMT");

GDALDatasetH hSrcDS = GDALOpenEx("test.shp", GDAL_OF_VECTOR, NULL, NULL, NULL);

GDALVectorTranslateOptions *opt = GDALVectorTranslateOptionsNew(argv, NULL);
GDALDataset *dst = (GDALDataset *)GDALVectorTranslate("out.gmt", NULL, 1, &hSrcDS ,opt, &error);
GDALVectorTranslateOptionsFree(opt);

CSLDestroy(argv);
GDALClose(dst);
GDALClose(hSrcDS);
```

**Comment by PaulWessel** [comment]
Since we apparently need to maintain GDAL 1 calls it sees the above will just add lots of work for no particular gain yet.

**Comment by joa-quim** [comment]
I'll probably do it sometime because there is a gain for Win. With it no GDAL needs to be installed in the system. However, without a GDAL I don't yet know how to ship the PROJ4 files needed for the EPSG's decoding.

**Comment by joa-quim** [comment]
Closing. Seems a no care issue
