### ISSUE TITLE
The docs macro |p| is printing an upper case P

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7350]
Example  from the ``basemap`` man page

![image](https://user-images.githubusercontent.com/537321/228554955-3c0c7637-4811-4395-a726-d1ff4c9b706c.png)

**Comment by Esteban82** [comment]
Why is that? Because in [basemap.rst](https://github.com/GenericMappingTools/gmt/edit/master/doc/rst/source/basemap.rst) it says:  `the |-p| option`, with a lowercase letter. 
So, I don't know how to modify it (or test it) without making a PR.

**Comment by joa-quim** [comment]
Problem is that we don't have a |-p| macro and and that |-p| is somehow being translated to |-P|.
Solution for now is to remove the macro call in ``basemap``
