### ISSUE TITLE
libnetcdf vs netcdf in latest epel version

### ISSUE THREAD

**Issue by AndrewBrennanCiv** [GenericMappingTools/gmt#7351]
Judging by the discussion on you wiki page about EPEL being not up to date, this issue may already be resolved in newer versions however, I am curious if the underlying issue of GMT complaining about not being able to install a package containing libnetcdf.so is a result of an old spec file pointing to libnetcdf instead of netcdf and if so, is that fixed in a newer release?

**Full script that generated the error**

```
yum install GMT
```

**Full error message**

```
#This is actually my confirmed workaround
yum -y install netcdf && yum install -y GMT
```

**Actual outcome**
Failure to install when trying to simply let GMT take care of installing the right dependencies

**Expected outcome**
Proper install when using my workaround

**System information**

* Operating system: RHEL 8
* GMT version (`gmt --version`): 6.1.0

**Comment by joa-quim** [comment]
Don't think this can be blamed to GMT. It results from installing from a package manager, not from building/installing from our building system. And also from an old version
``GMT version (gmt --version): 6.1.0``

We'll leave this issue open for a while to see if some news come in with some actionable from us, but it will be closed in a while if nothing new.

**Comment by AndrewBrennanCiv** [comment]
I don't think this can be blamed on GMT itself either, I just didn't know if you supplied to spec file to make the package for EPEL or if Fedora took care of that on their end.

If it's the latter than you can close this as not planned. My workaround might be useful to others if they run into the same issue so it might be worth noting in the off chance someone else asks about a similar issue here later.

**Comment by AndrewBrennanCiv** [comment]
This issue has NOTHING to do with GMT or EPEL - it's a byproduct of not having codeready-builder-for-rhel-8-x86_64-rpms enabled.
 Closing now.

**Comment by AndrewBrennanCiv** [comment]
This issue has NOTHING to do with GMT or EPEL - it's a byproduct of not having codeready-builder-for-rhel-8-x86_64-rpms enabled.

 Closing now.
