### ISSUE TITLE
Rename the meca supplement

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#738]
The **meca** supplement is not well named.  While there are one or two tools that deal with focal **mec**h**a**nisms, there are tools for (GPS) velocity vectors and plotting waveforms from SAC files.  Thus, the science domains that this supplement supports is seismology and geodesy.  We should select a more descriptive name than **meca** before GMT 6 is released.  To get us started, here are some suggestions:

- seismology+geodesy
- seis+geod
- tectonophysics
- seis

Other and better suggestions?

**Comment by seisman** [comment]
The new name will be used as the directory name of meca source codes, right? Then I'm against the first two, as I really don't want "+" in any directory names.

Currently, we have five modules, 4 (psmeca, pscoupe, pspolar, pssac) for seismology, one (psvelo) for geodesy.  Seismology wins, so why not seis? 😄 

BTW, psvelo is almost decoupled from other modules. The only common function used by the two sets is "meca_get_trans". Thus we can even split meca into two supplements: seis and geodesy.

**Comment by PaulWessel** [comment]
Not a bad idea to split into seis and geodesy.  We could then move gpsgridder from potential to geodesy, since that is what it is.  And maybe @joa-quim would agree that earthtide belongs in geodesy as well?  Potential should focus on potential field stuff.  I put my flexure codes there since these are used in isostasy studies, etc, and grdseamount is a tool to make synthetic loads to test isostasy and gravity responses, so it seems OK to keep the rest.  Thoughts?

**Comment by joa-quim** [comment]
Well, earthtide is midway. Useful also for microgravity reductions. But no objections against moving it.

**Comment by seisman** [comment]
Any updates on this one?

**Comment by PaulWessel** [comment]
It sounds like we are all OK with the split. I guess we create the geodesy dir and move over gpsgridder.c and earth tide.c form potential and psvelo from meca, then rename meca to seis.  Need updated READMEs for both, and CMakeFile changes.  I can start this on one hour, or you can do it right now - just let me know so we both dont do the same.

**Comment by seisman** [comment]
OK. I will do it.
