### ISSUE TITLE
FONT_ANNOT_PRIMARY and the "+" scaling

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7420]
The man says

>FONT_ANNOT_PRIMARY
>
>    Font used for primary annotations, etc [default is [theme dependent]]. When + is prepended, scale fonts, offsets and tick-lengths relative to [FONT_ANNOT_PRIMARY]. Choose auto for [automatic scaling with plot size].

but there is no reference to how to set the scale factor. Experience shows that scale seems to be multiplied by 10.
This
```
gmt basemap -R0/100/0/70 -JX14 -Ba -png lixo
```
and this
```
gmt basemap -R0/100/0/70 -JX14 -Ba--FONT_ANNOT_PRIMARY=+10 -png lixo
```
produce the same output. And this scales by 50%
```
gmt basemap -R0/100/0/70 -JX14 -Ba--FONT_ANNOT_PRIMARY=+5 -png lixo
```
but the tickmarks, contrary to what the man says, remain unscaled.

**Comment by PaulWessel** [comment]
You can see gmt_init.c lines 10,758-10.808 for what is happening.  The same is the ratio of what font size you give relative to the default annotation font size. which is 12p I think.  So if you do --FONT_ANNOT_PROMARY+10p then the sale (should) before 10/12 and that is then used to adjust the other fonts and lines from their default values.  So unless there is some unintended mix-up with modern theme etc I would expect the tick length to shrink a tiny bit, but not a huge amount.

**Comment by joa-quim** [comment]
They (the ticks) don't shrink.
```
gmt basemap -R0/100/0/70 -JX14 -Ba --FONT_ANNOT_PRIMARY=+1 -png lixo1
```

![lixo1](https://user-images.githubusercontent.com/537321/234532755-939698ab-6fe3-4a3d-a50e-1ff0c8d42dab.png)

**Comment by PaulWessel** [comment]
So likely a side-effect to modern theme where we set stuff to NaN and then later, if NaN, assign reasonable values.  We probably are multiplying a NaN-length for tick by 1/12 and it is still NaN, then resulting in the default value.  I will hvae a look to see.

**Comment by PaulWessel** [comment]
Yep, when +1p is used we must undo the NaN initialisation and set things to their classic default values, then compute scale and multiply all those settings by scale.  Doing that affects the tick length.  Working on PR once tests are run,
