### ISSUE TITLE
-g does not work from Julia

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7425]
I don't have a reproducible example right now, but it doesn't. A quick code scan makes think that when we pass data from externals the -g check is not done.

**Comment by PaulWessel** [comment]
Looking at gmtapi_bin_input_memory it seems like it does call -g.  But you would have to debug your way through and see if something is not happening.

**Comment by joa-quim** [comment]
Yes, I saw that ``gmtapi_bin_input_memory`` call and wondered if it shouldn't be the one where -g job happens.

**Comment by PaulWessel** [comment]
Seems like it is called when reading from memory via matrix and vectors? What is your case?

**Comment by joa-quim** [comment]
I pass a GMTdataset.
Haven't had yet opportunity to debug this case.

**Comment by PaulWessel** [comment]
Well, datasets are not read it, just duplicated or referenced, so -g is not in play at all.  It is if going via matrix or vector. Of course, -g would probably mean duplicate since number of segments may change.  Not highly motivated to rewrite that section to do a -g if set....
