### ISSUE TITLE
--MAP_GRID_CROSS_SIZE has no effect if unsigned

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7431]
* Related issue: https://github.com/GenericMappingTools/gmt/pull/2877
* Maybe this would be more suitable in the forum. If so - sorry.

From [gmt.conf docs](https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-MAP_GRID_CROSS_SIZE_PRIMARY):
*Size of grid cross at lon-lat intersections.
0 means draw continuous gridlines instead.
A nonzero size will draw a symmetric grid cross.
Signed sizes have special meaning and imply grid line ticks that embellish an already drawn set of gridlines:
A negative size will only draw ticks away from Equator and Greenwich, while a positive size will draw symmetric ticks [default is 0p].*

I'm surprised to see that ``--MAP_GRID_CROSS_SIZE=2p`` has no effect. What is it supposed to do?
Is ``--MAP_GRID_CROSS_SIZE=2p`` == ``--MAP_GRID_CROSS_SIZE=+2p``? ``--MAP_GRID_CROSS_SIZE=2p`` is implicitly positive, so I would expect a result identical to that of ``--MAP_GRID_CROSS_SIZE=+2p``. At least *some* kind of effect.

See script below.

```
gmt begin test png

# plot not affected by --MAP_GRID_CROSS_SIZE=2p; shouldn't it be?
gmt psbasemap -JS0/90/10c -R0/360/64/90 -Bafg
gmt psbasemap -Bpxg1 -Bsxg2 --MAP_GRID_CROSS_SIZE=2p

# plot as expected
gmt psbasemap -JS0/90/10c -R0/360/64/90 -Bafg -Y-12c
gmt psbasemap -Bpxg1 -Bsxg2 --MAP_GRID_CROSS_SIZE=+2p

# plot as expected
gmt psbasemap -JS0/90/10c -R0/360/64/90 -Bafg -Y-12c
gmt psbasemap -Bpxg1 -Bsxg2 --MAP_GRID_CROSS_SIZE=-2p
gmt end show
```
![test](https://user-images.githubusercontent.com/29237824/235521078-50ea0864-6bc5-4218-b5b8-e7bdae2dbaa0.png)

**Comment by PaulWessel** [comment]
Well, for regular gridline crosses (first case) dont you also need to specify what your latitude spacing is for them? It is not just a single line but two lines crossing.  The grid ticks are a bit different I think.

**Comment by PaulWessel** [comment]
And also, +2p is not the same as 2p since it is the presence of the sign that dictates the type of grid tick.

**Comment by anbj** [comment]
Yes, you're right. I think part of my confusion is that crosses suddenly turn into ticks when using a signed ``MAP_GRID_CROSS_SIZE``. Need to test and read more. Thanks Paul.

Closing.
