### ISSUE TITLE
Fix missing tokens in text's table

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7434]
If you look at the table in [text](https://docs.generic-mapping-tools.org/latest/text.html) then you will see that for the change of color or size the trailing` ;` and `: `are not shown even though they are there in the RST.  In contrast, the font changing token` %` is correctly shown.  Perhaps some of the gurus in @GenericMappingTools/gmt-docs knows how to finesse that table so it shows the correct trailing` ;` and `:`?

**Comment by seisman** [comment]
https://docs.generic-mapping-tools.org/dev/text.html

The dev documentation looks correct.

**Comment by anbj** [comment]
Looks good in my own (newly) built docs as well.

**Comment by PaulWessel** [comment]
Sorry, we must have fixed it earlier - I was looking at 6.4 it seems.
