### ISSUE TITLE
Incorrect link in coast.html

### ISSUE THREAD

**Issue by josn0** [GenericMappingTools/gmt#7436]
**https://docs.generic-mapping-tools.org/6.3/coast.html has a incorrect link to ISO 3166-1 alpha-2. Link [ISO 3166-1 alpha-2 convention](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)) contains a superfluous closing bracket in the link (should be 'https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2' instead of 'https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)')**

**No script; documentation issue**

```
# PASTE CODE HERE
```

**Wikipedia does not have an article with this exact name**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by joa-quim** [comment]
Thanks. Fixed in master. Note, all doc versions other than ``dev`` will continue to display this problem.
