### ISSUE TITLE
Errors in exaggeration and scale information (with -JX)?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7437]
I run  `gmt basemap -Ba -R0/5/0/5 -JX-2/1 -png test -Vi` and got this info:

```
basemap [INFORMATION]: Linear projection implies **x-axis** distance exaggeration relative to the **y-axis** by a factor of -0.5
basemap [INFORMATION]: Map scale is -0.0005 km per cm or 1:-50.

```

I think that both statements are wrong. 
In the first, the "x-axis" and "y-axis" should be interchanged (See #4418).
In the second, the scale should always be a positive number. A similar thing happens to the "vertical" scale (it is not reported but It can be deduced trough the VE).

If you agree, I think I could fix `gmt_map.c` (at least for the second line).

![test](https://user-images.githubusercontent.com/17908951/236568491-379e3b7f-2a61-40f9-97f4-d8a4a35f63d9.png)

**Comment by PaulWessel** [comment]
Sure, but bedtime here so approvals tomorrow

**Comment by Esteban82** [comment]
Ok, I will make a PR.
