### ISSUE TITLE
Still the -Dj vs -DJ vs +j combinations

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7439]
After all these years I still can't understand this and, given the legend docs
> Note: If -Dj is used then justify defaults to the same as refpoint, if -DJ is used then justify defaults to the mirror opposite of refpoint.

it can't be right. because **-DJ** and **-Dj** produce de same result.

```
julia> lines(1:12, 1:12, legend=(label="data",position=(outside=true,anchor=:TR,justify=:TR)), show=true)
opt_D = "JTR+jTR+w1.594+o0.1"

julia> lines(1:12, 1:12, legend=(label="data",position=(inside=true,anchor=:TR,justify=:TR)), show=true)
opt_D = "jTR+jTR+w1.594+o0.1"
```

![GMTjl_j](https://user-images.githubusercontent.com/537321/236632826-43cd33ac-9032-4d2f-a785-2e31a8ab0d27.png)

**Comment by joa-quim** [comment]
But I start to get it a bit better. The problem is that **-DJ** is not good for legends in the corners.
```
julia> lines(1:12, 1:12, legend=(label="data",position=(outside=true,anchor=:TR)), show=true)
opt_D = "JTR+w1.594+o0.1"
```
![GMTjl_j](https://user-images.githubusercontent.com/537321/236639434-373c6780-c3fc-4a10-a2d4-71d907e479e9.png)

**Comment by PaulWessel** [comment]
Are you sure? I think only one legend is allowed per panel so if you do both -DJ and -Dj you only get the first?

**Comment by joa-quim** [comment]
No subplots here, just plain classical mode. What is showed is the -D option passed to pslegend.

**Comment by PaulWessel** [comment]
Can you post a MWE CLI script that shows a problem?

**Comment by joa-quim** [comment]
These both produce the same fig

```
echo 0 0 1 1 | awk '{print $1,$2,"\n",$3,$4}' | psxy -R0/1/0/1 -JX14 -W1 -Ba -P -K > lixo.ps
echo S 0.325c - 0.65c - 0.5p,, 0.79c data | pslegend -F+p0.5+gwhite -DjTR+jTR+w1.594+o0.2/0 -J -R -O >> lixo.ps

echo 0 0 1 1 | awk '{print $1,$2,"\n",$3,$4}' | psxy -R0/1/0/1 -JX14 -W1 -Ba -P -K > lixo.ps
echo S 0.325c - 0.65c - 0.5p,, 0.79c data | pslegend -F+p0.5+gwhite -DJTR+jTR+w1.594+o0.2/0 -J -R -O >> lixo.ps
```

**Comment by PaulWessel** [comment]
Well, perhaps silly, but both **-DJTR** and **-DjTR** sets the anchor point to (1,1).  However, they differ in what the default justification is.  For **-D**j it is **+jBL** (place item on the outside) while for **-DJ** it is **+jTR** (place item on the inside).  Your script overrides the defaults with explicit **+j** and it is the same justification for both - hence the legends are placed in the same place.
