### ISSUE TITLE
Inconsistent specification of ellipse parameters: plot vs project

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7443]
**Description of the desired feature**

While **psxy** has had this syntax for decades: **-Se**_direction_/_major_axis_/_minor_axis_,

I more recently (2019-2020?) added this ellipse-generator to **project**:

**-Z**_major_[unit][/_minor_/_azimuth_][**+e**]

So that was a bit dumb.  Hard to implement a 100% backwards compatible solution.  But we could try and fail at times: If given one argument then of course it is a circle diameter, but if three then it is either (the proposed) _direction_/_major_axis_/_minor_axis_ or _major_[unit]/_minor_/_azimuth_.  Ways to distinguish the two:

1. If a unit is used for any dimension then we know the order
2. If no unit and a number is negative we know it is an azimuth
3. If no unit and a number is > 360 it is _likely_ a dimension
4. If no unit and first arg is larger that the 2nd are then first is an azimuth

Stuff like 60/30/90 can then be seen as 90/60/30.  But 90/80/70 is either 90 degrees with 80 and 70 axes or 70 degrees with 90 and 80 axes. So we will have failures but in those cases we could issue a warning or information message.

Proposal: Given **project -Z** is much less used than **psxy -Se**|**E**|**j**|**J** it is OK to declare a parsing/doc bug and switch to use the established **psxy** syntax.

Thoughts?

**Comment by anbj** [comment]
Keeping it to established syntax is an advantage, in my opinion.

**Comment by joa-quim** [comment]
Not important, better not change it.

**Comment by PaulWessel** [comment]
Closing as not that important given the immensity of other issues.
