### ISSUE TITLE
Let set height for images and keep original aspect ratio

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7446]
I want to put an image and set its height and keep the original aspect ratio (so I don't know or want to define its width).  I think that there is no way to do it.

I try this script where it is posible to set the width. Also, In [image -D](https://docs.generic-mapping-tools.org/dev/image.html#d) says
> use +w[-]width[/height] to set the width (and height) of the image in plot coordinates (inches, cm, etc.). If height is not given, the original aspect ratio of the image is maintained. 

![title](https://user-images.githubusercontent.com/17908951/236728999-786ac77a-830a-4dc2-aa80-8da334bc47eb.png)

```
gmt begin title png
	echo "6 11.5 Title" | gmt text -R0/10/0/13.5 -Jx1c -F+f26p,Helvetica-Bold+jCB -X0 -Y0
     gmt image @circuit.png -DjCL+w3   
    gmt image @circuit.png -DjCM+w3/0c  
    gmt image @circuit.png -DjCR+w0/4c
gmt end

```

Also, would nice to have the option to the set the heigth for the [gmtlogo](https://docs.generic-mapping-tools.org/dev/gmtlogo.html) module.

**Comment by PaulWessel** [comment]
No, but because the aspect ratio is fixed I think the best way is to add **+h**_height_ and then only one of **+w** or **+h** can be specified.

**Comment by Esteban82** [comment]
Ok. So, I close this.
