### ISSUE TITLE
Put references in common document

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7452]
There is no central place to put references, and these are given at the end of e.g. module docs (see [greenspline](https://docs.generic-mapping-tools.org/dev/greenspline.html#references) for an example).

One solution is to gather all references in a common document, where they are defined, and then refer to these.

See [Managing bibliographic citations in Sphinx](https://chiplicity.readthedocs.io/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html#introduction) for a primer.

Short description:

Create a document, e.g. ``references.rst``, where you define the references:

```
.. [BiDB79] Biskup, J.; Dayal, U.; Bernstein, P.A..: Synthesizing independent database schemas. In: ACM SIGMOD 1979 Int. Conf. On Management of Data Proceedings, S. 143-151.

.. [BeBe79a] Beeri, C.; Bernstein, P.A.: Computational problems related to the design of normal relational schemas. ACM Trans. Database Syst., No. 1, 1979, S. 30-59.

.. [BeBe79b] Beeri, C.; Bernstein, P.A.: Computers are stupid. ACM Trans. Database Syst., No. 4, 1979, S. 253-266.
```

Refer to these with ``[reference]_``, e.g. ``[BiDB79]_``, when needed/used in docs.

Would this be worth doing?

**Comment by PaulWessel** [comment]
Yes, I would agree.  It is painful to have those references in many files like we have now.

**Comment by anbj** [comment]
I've converted the references in [greenspline](https://docs.generic-mapping-tools.org/dev/greenspline.html) and created references.rst, for a quick and dirty showcase.

Reference style (author, name, publication, year etc.) and how the references are listed can of course be changed. I don't like that the references are not aligned in a nice looking fashion (loewr figure), but maybe there's a solution to that.

![Screenshot from 2023-05-08 22-17-25](https://user-images.githubusercontent.com/29237824/236925917-800922be-4de2-4a78-93ee-6a1f5bdafce0.png)

![Screenshot from 2023-05-08 22-17-12](https://user-images.githubusercontent.com/29237824/236925939-235db53e-3eaf-48bf-9792-e9407eb0eedc.png)

**Comment by anbj** [comment]
I've done most of the references in https://github.com/GenericMappingTools/gmt/tree/single-ref.
You can build the docs if you want to see how it looks.

**Comment by PaulWessel** [comment]
Seems like you need to do some conflict resolution first.  If I try to get your branch I get this:

![merge](https://github.com/GenericMappingTools/gmt/assets/26473567/30e3217a-ff62-482b-bb2a-3f90b7264c59)

**Comment by anbj** [comment]
Hmm, didn’t think I would get any of those. Ok, I’ll check. Note that it is not finished yet.

**Comment by anbj** [comment]
Maybe you can just change the branch instead of merging?

**Comment by PaulWessel** [comment]
That is what I do: I switch to your branch, and then GIt Desktop says what that picture shows. I can see if I can make the edits and resolve the conflicts.

**Comment by anbj** [comment]
Good; don’t merge it. I’ll do a clean PR if it gets to that. 

Yes, I agree, the presentation of the refs is not optimal.

**Comment by anbj** [comment]
After sleeping on it, I dont think this is a change worth doing. When references can be presented in a better way, maybe. Comments?

**Comment by PaulWessel** [comment]
I agree.

**Comment by anbj** [comment]
Closing.
