### ISSUE TITLE
Let movie main.sh handle show to open the movie

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7455]
In modern mode script we can end with

`gmt end show`

and then the plot opens up in the default viewer.I learned today via @Esteban82 that **ffmpeg** is one of many ff tools; the full list is

`ffmpeg	ffprobe		ffplay`

So a proposal would be if main.sh ends with `gmt end show` then once movie assembles the mp4 movie it would call **ffplay**, or perhaps just "open" like we do for images? Open movie.mp4 works fine on macOS (opens QuickTime player) - how about Windows and Linux?

**Comment by Esteban82** [comment]
`ffplay` works to play a mp4 on linux. Should we test the other formats?

**Comment by PaulWessel** [comment]
Sure, but I would expect it to play anything ffmpeg can create, such as webm etc.
Does` open mg4file` work on Linux?

**Comment by Esteban82** [comment]
> Sure, but I would expect it to play anything ffmpeg can create, such as webm etc.

Ok.

> Does` open mg4file` work on Linux?

Yes, it works.

**Comment by PaulWessel** [comment]
And when @joa-quim gets back from eating again, he can tell us if it works on Windows.

BTW, I see that `gmt end show `actually ends up passing the file to **gmt docs**, which is where it ends up calling **open**.

**Comment by joa-quim** [comment]
Loong dinner. What should I test?

**Comment by PaulWessel** [comment]
If

open somemovie.mp4

works on windows

**Comment by joa-quim** [comment]
Sorry, still don't get what to test. Ofc .mp4 movies work on Windows.

**Comment by PaulWessel** [comment]
Yes of course, but does the CLI command

`open somemovie.mp4`

open your movie viewer like it does on other OS?

**Comment by joa-quim** [comment]
No. ``open`` is not known. But simply typing the file name ``somemovie.mp4`` does work.

**Comment by PaulWessel** [comment]
Sorry, I should probably have said

gmt docs movie.mp4

since that is what gmt end show does - it knows what "open" applies.
