### ISSUE TITLE
GMT downloads dataset twice

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7471]
* Originally posted in the [forum](https://forum.generic-mapping-tools.org/t/gmt-downloads-dataset-twice/3854).

* For some reason, gmt downloads the dataset twice. Since the dataset and region is exactly the same, I don't understand why it does this. No big deal using a low-res dataset like ``@earth_relief_10m``, but much worse when you want high-res like ``@earth_relief_30s``.

* Script:

```
proj=-JS0/90/50c
r=-R0/60/70/90

gmt begin map png

echo -e "* Running grdimage command..\n"
gmt grdimage ${1} ${r} ${proj} -Bafg

echo -e "* Running grdcut command..\n"
gmt grdcut ${1} ${r} -Gtemp.nc

gmt end
```

* Lets download ``earth_relief_10m``:

```
$ bash dl-dataset @earth_relief_10m
* Running grdimage command..

grdimage [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdimage [NOTICE]: SRTM15 Earth Relief at 10x10 arc minutes reduced by Gaussian Cartesian filtering (18.6 km fullwidth) [Tozer et al., 2019].
grdimage [NOTICE]:   -> Download grid file [3.0M]: earth_relief_10m_p.grd
* Running grdcut command..

gmt [WARNING]: Remote dataset given to a data processing module but no registration was specified - default to gridline registration (if available)
grdcut [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdcut [NOTICE]: SRTM15 Earth Relief at 10x10 arc minutes reduced by Gaussian Cartesian filtering (18.6 km fullwidth) [Tozer et al., 2019].
grdcut [NOTICE]:   -> Download grid file [3.0M]: earth_relief_10m_g.grd
```

* Now try ``earth_relief_30m``:

```
 bash dl-dataset @earth_relief_30s
* Running grdimage command..

grdblend [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdblend [NOTICE]: SRTM15 Earth Relief at 30x30 arc seconds reduced by Gaussian Cartesian filtering (1 km fullwidth) [Tozer et al., 2019].
grdblend [NOTICE]:   -> Download 15x15 degree grid tile (earth_relief_30s_p): N60E000
^C^C
```

**Comment by anbj** [comment]
I see now that ``grdimage`` defaults to  ``p`` registration, while ``grdcut`` defaults to ``g``. So in that way, it does make sense - they're two different datasets. Why do they default to different registrations?

**Comment by anbj** [comment]
Now I tried adding ``-rp``/``-rg`` just to see if it downloads only once, if the registration is the same. But it still downloads the dataset twice - one for pixel (``grdimage``) and one for gridline (``grdcut``). Supplying ``-r[p|g]`` doesn't change what is being downloaded.

Is this to be expected? I understand if the downloading of the data is being delegated to another module behind the scenes, and that this responsible module would have to get the grid registration instead of ``grdimage`` and ``grdcut``.

**Comment by anbj** [comment]
You're right. ``grdcut`` doesn't understand ``-r``:

```
$ gmt grdcut -JS0/90/50c -R0/60/70/90 -Gtemp.nc @earth_relief_10m -rp
gmt [WARNING]: Remote dataset given to a data processing module but no registration was specified - default to gridline registration (if available)
grdcut [ERROR]: Unrecognized option -r
```

**Comment by anbj** [comment]
``-r`` is not listed as [an option](https://docs.generic-mapping-tools.org/dev/grdcut.html#synopsis) for **grdcut**

**Comment by PaulWessel** [comment]
It is an odd option to add since for non-remote grids it is not an issue. It enters only via grdblend which calls grdsample. I suppose we could add -r and then for remote data without registration we use it to add it to the file name, while for other grids we just call grdsample?

**Comment by anbj** [comment]
Is there a way to specify default registration for remote grids?

I'm not sure what the best solution is. What I reacted to, is that a dataset was downloaded twice - well not really, since they are different registrations, but for a user that does not care about grid registration (which I would think is the majority?), it would seem strange (and waste of bandwidth). Why does **grdimage**/**grdblend** default to pixel reg. while **grdcut** defaults to gridline reg.?

**Comment by anbj** [comment]
(And specifying ``-r`` in a **grdimage** call does not make sense. I did that in my second script testing.)

**Comment by joa-quim** [comment]
Because in GMT the default is: 

- images use pixel registration
- grids use grid registration

``grdcut`` was originally a grid only operator. I've not checked what it does when working on grids _vs_ images but what it should do is to respect the data registration and **not** play ``grdedit`` toggle option.

I know that pixel vs grid registration is a boring fact to learn and even to care about but those that choose to ignore it ... still can't escape from the fact that they both exist.

**Comment by PaulWessel** [comment]
I agree. The solution here is to strengthen the docs that explains that. It could be an explain_* file included where suitable,

**Comment by anbj** [comment]
So, the behaviour is reasonable, and it just needs to be described in the docs. Should I close?

**Comment by joa-quim** [comment]
Yep, probably.

**Comment by anbj** [comment]
Closing.
