### ISSUE TITLE
pscoast -R=OC goes nuts

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7498]
With pdf it still screws something visible but with png it hangs (or is writing endlessly on disk)
```
gmt coast -R=OC -JD190.5/-13.5/-41.83/43.17/15c -Baf -BWSen -Gtomato -Slightblue -pdf lixo
```
[lixo.pdf](https://github.com/GenericMappingTools/gmt/files/11670747/lixo.pdf)

**Comment by PaulWessel** [comment]
Since OC is a long list of Oceania states, perhaps some are in > 180 and have negative longitudes and others are in < 180 and have positive longitudes, and when merged we get a mess?

**Comment by joa-quim** [comment]
yes, OC =

gmt coast  -R96/285/-56/29 -JD190.5/-13.5/-41.833333333333336/43.166666666666664/15c -Baf -BWSen -Gtomato -Slightblue -pdf lixo

**Comment by PaulWessel** [comment]
But it is a conic projection and you are jumping from S to N hemispheres? Dont think that can work? The other conics give the same result.

**Comment by joa-quim** [comment]
Matlab bug in guessing best projection for that -R
