### ISSUE TITLE
Modifiers +e|r|R for region are NOT working

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7512]
```
gmt begin test png
    gmt coast -W3,red   -N1/3,red   -RIT+R3 -Baf
    gmt coast -W1,black -N1/1,black -R6.6149/18.5135/35.4922/47.095+R3
gmt end 
```
![test](https://github.com/GenericMappingTools/gmt/assets/17908951/6ee608e5-40e0-4f7a-8979-85e0c7da9f24)

**Comment by PaulWessel** [comment]
I don’t understand what is wrong?

**Comment by Esteban82** [comment]
Shouldn't the region of the map be modified by +R3?

**Comment by PaulWessel** [comment]
And it is, no?

**Comment by PaulWessel** [comment]
It added/subtracted 3 on all sides

**Comment by PaulWessel** [comment]
Sorry now I see. Will look tonight at airport

**Comment by PaulWessel** [comment]
Hm.  There is no documentation that says you can apply +r|R|e to a plain -Rw/e/s/n setting.  It is only used for DCW. If you do w/e/s/n why would you need +R3 since you can very easly do that directly to the w/e/s/n. So for me, the -RIT+R# works while the -Rw/e/s/n+R3 quietlly fails. Perhaps we should give a error in that case?

**Comment by Esteban82** [comment]
> Perhaps we should give a error in that case?

If it is not in documentation, then I think we should say anything at all.

**Comment by PaulWessel** [comment]
"Should say anything" means "should not say anything" ?  I think we should report error when someone adds a modifier where none is supported, no?

**Comment by Esteban82** [comment]
"Should say anything" means "should not say anything" ?

Yes, sorry. We should not say anything. It's like the other case of DCW codes.

**Comment by Esteban82** [comment]
The main (only) issue was this  `-RIT+R3 `.

**Comment by PaulWessel** [comment]
And that works fine for me.  Are you not getting this:

```
gmt begin test png
    gmt coast -W3,red   -N1/3,red   -RIT+R3 -Baf
gmt end show

```
![test](https://github.com/GenericMappingTools/gmt/assets/26473567/af194732-e0b7-48e6-bc93-56be5289942b)

which I think is correct (3 degrees extension on all sides(.
