### ISSUE TITLE
Document mysterious 2-degree buffer

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7523]
Here apparently the program has an undocumented 2-degree buffer built in. Please document it somewhere. 
```
$ echo | gmt xyz2grd /dev/stdin -G/tmp/nn \
-JT-87/41/4c -I1M -R-100/100/-100/100 -V
```
> mapproject [INFORMATION]: Transform \*\* -88/-86/40/42 ** ...

GMT 6.4.

**Comment by jidanni** [comment]
> What exactly are you trying to accomplish here?

I
am just trying to make a minimal version of
https://docs.generic-mapping-tools.org/dev/gallery/ex28.html#example-28

I
merely want to make a (hollow) basemap, like the one in that example,
with meters on one side, lat and lon on the other.

I want to do this all with an empty
$ gmt xyz2grd /dev/null ...
gridfile, the purpose of which is simply to carry
around my location and PROJ definitions...

Anyway, here's a map of South Carolina,
$ gmt coast -RUS.SC -W -Na -png
Now please slap a meters/lat lon basemap around it.
Thanks!

**Comment by jidanni** [comment]
> But your -I1M (the M is not considered - you probably mean 1 mile?) it rounds those to the nearest 1 which are -88/-86/40/42.

Same for 11M, 111M:
```
$ gmt xyz2grd /dev/null -G/tmp/nn -JT-87/41/4c -I1M -R-100/100/-100/100 -V 2>&1|grep Transform
mapproject [INFORMATION]: Transform -88/-86/40/42 <- -85394.6196907/85394.6196907/-111044.260899/111547.404647 [m]
$ gmt xyz2grd /dev/null -G/tmp/nn -JT-87/41/4c -I11M -R-100/100/-100/100 -V 2>&1|grep Transform
mapproject [INFORMATION]: Transform -88/-86/40/42 <- -85394.6196907/85394.6196907/-111044.260899/111547.404647 [m]
$ gmt xyz2grd /dev/null -G/tmp/nn -JT-87/41/4c -I111M -R-100/100/-100/100 -V 2>&1|grep Transform
mapproject [INFORMATION]: Transform -88/-86/40/42 <- -85394.6196907/85394.6196907/-111044.260899/111547.404647 [m]
```

**Comment by jidanni** [comment]
> the M is not considered

https://docs.generic-mapping-tools.org/dev/xyz2grd.html :

> -Ix_inc[+e|n][/y_inc[+e|n]]
> Set the grid spacing as x_inc [and optionally y_inc].
> 
> Geographical (degrees) coordinates: Optionally, append an increment unit. Choose among:
> 
> m to indicate arc minutes
> 
> s to indicate arc seconds
> 
> e (meter), f (foot), k (km), M (mile),

If it is not considered shouldn't it print an error?

**Comment by joa-quim** [comment]
> If it is not considered shouldn't it print an error?

NO. I explained already. The whole thing is to convert the GMT proj syntax into a PROJ4. And all of it in a senseless command.

**Comment by jidanni** [comment]
Should xyz2grd and the other grid making programs bomb out with errors when no data points are given then?

Or can they still be used to contain the coordinate system data, etc. (All the info they contain besides actual grid points.)

**Comment by joa-quim** [comment]
No they can't. Again, grids are matrices and we cant have **empty matrices**.

```
gmt surface /dev/null -G/tmp/nn -JT-87/41/4c -I1M -R-100/100/-100/100
surface [WARNING]: Cartesian x-increments are unit-less! - unit ignored
surface [WARNING]: Cartesian y-increments are unit-less! - unit ignored
surface [ERROR]: No datapoints inside region, aborting
```
