### ISSUE TITLE
xyz2grd.html: y_inc: not super clear

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7525]
https://docs.generic-mapping-tools.org/dev/xyz2grd.html:

Please rewrite this sentence clearer,

> If y_inc is given but set to 0 it will be reset equal to x_inc; otherwise it will be converted to degrees latitude.

it could mean various things:

- y_inc is given
- - but set to 0
- - - it will be reset equal to x_inc
- - not set to 0
- - - it will be converted to degrees latitude. ???
- y_inc is not given
- - it will be converted to degrees latitude. ???
- - it will not be converted to degrees latitude. ???

**Comment by joa-quim** [comment]
Changed to ``If y_inc is not given or given but set to 0 m...``
