### ISSUE TITLE
xyz2grd -V: add units

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7526]
Please print the **units** (meters, feet, degrees...) for 0.0144... where I have added the "*"s,

```
echo | gmt xyz2grd /dev/stdin -G/tmp/nn \
-JT41.8820489/-87.6277999/4c -I1M -R-10/1/-10/10 -V
xyz2grd [INFORMATION]: Distance to degree conversion implies x_inc = 0.014474 *
xyz2grd [INFORMATION]: Given domain implies x_inc = 0.0144737 *
xyz2grd [INFORMATION]: Distance to degree conversion implies y_inc = 0.014474 *
xyz2grd [INFORMATION]: Given domain implies y_inc = 0.0144718 *
```
If there are no units, then add "(no units)"

> Distance to degree

No that doesn't make it clearer, thus please mention the units.

$ grdinfo also not clear:
> x_inc: 0.0144736...

**Comment by joa-quim** [comment]
But this 
```
echo | gmt xyz2grd /dev/stdin -G/tmp/nn -JT41.8820489/-87.6277999/4c -I1M -R-10/1/-10/10 -V
```
has no sense, so units of what?

**Comment by jidanni** [comment]
For things that have units, add the unit.
For things that don't have units, add "(no units)".
That would make things clearer.

**Comment by PaulWessel** [comment]
@joa-quim, I am not sure what the intention was with **-J** here.  I thought it was just verbatim passed as meta data, but clearly we end up with calls to **mapproject** to convert things:

It says inc is now 0.014474 degrees, which is 1 statute mile (1M) as the user gave.

But **grdinfo** on the grid reports the same **-R** as given and the 0.014474 increment in degrees

So @jidanni has a point that here we know x and y are in degrees but I suspect the -f0f,1f you pass to **mapproject** messes up the check at the end and it gives no (i.e., Cartesian) units.

And I think @jidanni might believe that **-J** converts either w/e/s/n or projects data but it has no effect on anything (except to fail to indicate geographic coordinates).

**Comment by jidanni** [comment]
I'm just saying that adding units or "no units" to everything might help users
like me go from only understanding 1/6 of it, advance to understanding 1/5 of it.
Better than nothing.

**Comment by PaulWessel** [comment]
Your example should end up with degrees as units. We are looking into this case.
Not in favour of writing (no units) since the data clearly have units but we just dont know what they are.  So blank is preferable.  If nothing given then there are nothing to write.

**Comment by jidanni** [comment]
Could distinguish between
- unknown units
- unmentioned units

by explicitly saying the former.

**Comment by joa-quim** [comment]
And what is the pad sneaking in here? This is a reformat job only.

**Comment by PaulWessel** [comment]
It is, but ends up going through an add pad section.

**Comment by joa-quim** [comment]
And close this one too. All seems to land in #7522
