### ISSUE TITLE
Tables with empty row at the beginning

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7527]
I see that in General Features there are some tables like these two:

https://docs.generic-mapping-tools.org/dev/cookbook/features.html#distance-units
https://docs.generic-mapping-tools.org/dev/cookbook/features.html#specifying-pen-attributes

I wonder how that happened. It seems that some configuration was modified.

**Comment by seisman** [comment]
These are the ReST source code for one table. It's just a simple table with empty headings:
```
.. _tbl-pennames:

    +------------+---------+------------+--------+
    +============+=========+============+========+
    | faint      | 0       | thicker    | 1.5p   |
    +------------+---------+------------+--------+
    | default    | 0.25p   | thickest   | 2p     |
    +------------+---------+------------+--------+
    | thinnest   | 0.25p   | fat        | 3p     |
    +------------+---------+------------+--------+
    | thinner    | 0.50p   | fatter     | 6p     |
    +------------+---------+------------+--------+
    | thin       | 0.75p   | fattest    | 10p    |
    +------------+---------+------------+--------+
    | thick      | 1.0p    | wide       | 18p    |
    +------------+---------+------------+--------+
```

**Comment by joa-quim** [comment]
And they were like that since ...

**Comment by Esteban82** [comment]
Should the first row be deleted or should it be completed with a header?

**Comment by seisman** [comment]
The first empty row can't be deleted but a header row sounds a good idea.

**Comment by joa-quim** [comment]
Can we close this?

**Comment by Esteban82** [comment]
> These are the ReST source code for one table. It's just a simple table with empty headings:
> 
> ```
> .. _tbl-pennames:
> 
>     +------------+---------+------------+--------+
>     +============+=========+============+========+
>     | faint      | 0       | thicker    | 1.5p   |
>     +------------+---------+------------+--------+
>     | default    | 0.25p   | thickest   | 2p     |
>     +------------+---------+------------+--------+
>     | thinnest   | 0.25p   | fat        | 3p     |
>     +------------+---------+------------+--------+
>     | thinner    | 0.50p   | fatter     | 6p     |
>     +------------+---------+------------+--------+
>     | thin       | 0.75p   | fattest    | 10p    |
>     +------------+---------+------------+--------+
>     | thick      | 1.0p    | wide       | 18p    |
>     +------------+---------+------------+--------+
> ```
Is it not possible to do it like the symbols table in gmtmath?

```
+-------------+-----------------------------------------+
| **PI**      | 3.1415926...                            |
+-------------+-----------------------------------------+
| **E**       | 2.7182818...                            |
+-------------+-----------------------------------------+
| **EULER**   | 0.5772156...                            |
+-------------+-----------------------------------------+
| **PHI**     | 1.6180339... (golden ratio)             |
+-------------+-----------------------------------------+
```

**Comment by seisman** [comment]
> Is it not possible to do it like the symbols table in gmtmath?

You're right. It should work.

**Comment by Esteban82** [comment]
Ok, I will try to do it. Or maybe @anbj would like to do it.

**Comment by anbj** [comment]
So we want to remove the 'empty' row at the top, or add a headertext?

**Comment by PaulWessel** [comment]
@anbj , just checking you got my personal message to you on the forum?

**Comment by anbj** [comment]
@PaulWessel, yes I did!
