### ISSUE TITLE
xyz2grd message improvements

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7532]
I can't find these anywhere, so maybe they are already fixed.

```
xyz2grd [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use dd:mm[:ss] for regions
     given in arc degrees, minutes [and seconds]. Use -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for
     regions given in projected coordinates, with <unit> selected from e|f|k|M|n|u [e]. If +u is

say

e|f|k|M|n|u     [Default: e]. 

else it looks like ...|u or ...|ue .

     set, projected regions centered on (0,0) may beset via

beset -> be set

     -R<halfwidth>[/<halfheight>]+u<unit>,
```
$ gmt --version
6.4.0

**Comment by joa-quim** [comment]
I think he means ``[Default: e]`` instead of only ``[e]``. 
But I don't understand where the ``set, projected regions centered on (0,0) may beset via`` is coming from. In fact we don't even print the **-R** summary in the ``xyz2grd`` online help.

**Comment by joa-quim** [comment]
OK, I fixed this directly on master.

**Comment by PaulWessel** [comment]
Are we going to replace all [whatever] with [Default: whatever] now? I thought it was universally understood in Unix land that [whatever] is the default value :-)

**Comment by PaulWessel** [comment]
No cases of "beset" in GMT dev.

**Comment by jidanni** [comment]
> Are we going to replace all [whatever] with [Default: whatever] now? I thought it was universally understood in Unix land that [whatever] is the default value :-)

Fixing needed in only in the worst cases of long trains of gobbledygook.

**Comment by joa-quim** [comment]
See gmt_init #L7358
Remove the ``Default:`` if your consistencymeter so determines.
