### ISSUE TITLE
Document basemap -R...+U

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7537]
https://docs.generic-mapping-tools.org/dev/gallery/ex28.html#example-28 says:
> `gmt basemap -R@Kilauea.utm.nc+Uk`

Alas, the "+U" is undocumented.

The best one can dig up is "+u".

**Comment by joa-quim** [comment]
You're right, not easy to find. It's in the CookBook
https://docs.generic-mapping-tools.org/dev/cookbook/features.html#modifiers-for-changing-units-of-grid-coordinates
