### ISSUE TITLE
Bad parsing in -llabel

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7538]
See this forum [post](https://forum.generic-mapping-tools.org/t/font-change-in-plot-l-string-not-correctly-intpreted-in-legend-command/3989) for background.

What happens is that the font switch keys %font% confuses the lame parser that tries to determine if the given label is a static string (which is true here) or a format statement (e.g., "Line %d") where the integer is supplied later.

In the user's case, the -l'@%1%m@%% (rot. feedb.)' falls victim to this lame parser )only showing relevant branch):

```
if (arg[0]) {	/* Gave a label, which may be a constant string, code, or format statement */
	char *d = strchr (arg, '%');
	if (d && strchr (d, 'd')) {
		GMT->common.l.item.label_type = GMT_LEGEND_LABEL_FORMAT;
		strncpy (GMT->common.l.item.label, arg, GMT_LEN128-1);
	}
		...
}
```

So since there happens to be a "d" in the text it happily goes into the GMT_LEGEND_LABEL_FORMAT branch.

The obvious fix here is to first hunt for @% and not just % since @% is always the start of a font change. There may be complications such as a font change followed later by an integer format. I won't address that right away but will leave comments in the code.

**Comment by joa-quim** [comment]
Fixed by #7543
