### ISSUE TITLE
modules not found when an environment variable is set on a line in a Makefile

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7539]
Gee, all I did was set oh, v=1, at the beginning of a line, and kaboom, can't use Makefiles anymore.
```
$ cat Makefile
k:
	gmt begin zzz
	v=1 gmt coast -RUS.SC -W -Na
	gmt end show
$ make
gmt begin zzz
v=1 gmt coast -RUS.SC -W -Na
```

> gmt [ERROR]: Shared GMT module not found: coast
> 
> ERROR: No module named coast was found.  This could mean one of four cases:
>   1. There actually is no such module; please check your spelling.
>   2. You used a modern mode module name while running in GMT classic mode.
>   3. Module exists in the GMT supplemental library, but the library could not be found.
>   4. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
> Shared libraries must be in standard system paths or set via environmental parameter LD_LIBRARY_PATH.

So one must do
`gmt begin zzz; v=1 gmt coast -RUS.SC -W -Na; gmt end show`
all on one line as a workaround.

**Comment by PaulWessel** [comment]
Not sure what does **make** do here? Should it not just run those lines one after the other? I suspect those are given separate process IDs and that is a no-no for [modern mode](https://docs.generic-mapping-tools.org/dev/begin.html). Maybe set that v on a separate line?

For simple one-liners you could just do

`v=1 gmt coast -RUS.SC -W -Na -pdf zzz`

**Comment by jidanni** [comment]
OK, 
```
MAP_FRAME_AXES=WE... gmt basemap -B
```
can't be done in a Makefile.
Do document that somewhere.
Yes there are tons of workarounds.

**Comment by joa-quim** [comment]
GMT is not a Unix program only. This command ``v=1 gmt coast -RUS.SC -W -Na -pdf zzz`` makes no sense on Windows. 
What is it to document?

**Comment by PaulWessel** [comment]
But GMT does not ever look for an environmental parameter MAP_FRAME_AXES? Our syntax is --MAP_FRAME_AXES=WE.  The number of environmental parameters GMT actually looks for is very limited, mostly DIRECTOR type of things.

**Comment by jidanni** [comment]
OK, it is already documented.
https://docs.generic-mapping-tools.org/dev/begin.html#note-on-unix-shells
