### ISSUE TITLE
-V: always report in -180...180

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7540]
How about always reporting -180...180, and not sometimes beyond?
```
$ gmt basemap ... -V
basemap [INFORMATION]: South Carolina (United States)
basemap [INFORMATION]: Region implied by DCW polygons is 276.646/281.453/32.0492/35.2161
basemap [INFORMATION]: Central meridian not given, default to 279.049
```

**Comment by PaulWessel** [comment]
Without checking, I think most modules that outputs geographical coordinates will respond to -**-FORMAT_GEO_OUT=-D**.  However, I note that

```
gmt pscoast -EUS.SC --FORMAT_GEO_OUT=-D
-R276.645653/281.453331/32.04921/35.21611

```
does not care.  also, there are various messages (like the one you showed from **psbasemap**) that does not use the formatting machinery and hence gives the 0-360 range, most likely.

If the day had a lot more hours we could consider fixing those things but still just 24 hours it seems. :-)
