### ISSUE TITLE
UTM example: go on to add metric basemap too

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7541]
**Description of the desired feature**

We read

> Universal Transverse Mercator [conformal][¶](https://docs.generic-mapping-tools.org/dev/basemap.html#universal-transverse-mercator-conformal)
> To use this projection you must know the UTM zone number, which defines the central meridian. A UTM basemap for Indo-China can be plotted as
> 
> gmt basemap -R95/5/108/20+r -Ju46/1:10000000 -Bafg -B+tUTM -pdf utm

Well that is just great, except many users would **also** like to know how to make the familiar **meter**s also appear on the basemap. So please add an additional example.

**Are you willing to help implement and maintain this feature?** Yes/No

Sure, if I only had an inkling of how to accomplish it!!

**Comment by joa-quim** [comment]
> Sure, if I only had an inkling of how to accomplish it!!

- use mapproject to get the limits (BoundingBox) in the desired projection
- make two psbasemap calls. One in geogs with, let say; ``-BWS -Ba`` and the other with the projected limits and ``-BEN -Ba``

**Comment by PaulWessel** [comment]
Cannot be done in a one-liner since we are not going to add more complications to -B.  So it remains a more elaborate thing. You could get those meter bounds via

`gmt mapproject -R95/5/108/20+r -Ju46/1:10000000 /dev/null -V -F -C`

and then parse out the max/xmin/ymin/ymax, here 721387.055456/2080949.09788/552077.474203/2279563.58956.

Then

```
gmt begin utm
	gmt basemap -R95/5/108/20+r -Ju46/1:10000000 -Bafg -BwS+tUTM
	gmt basemap  -R721387.055456/2080949.09788/552077.474203/2279563.58956 -Jx1:10000000 -Bafg -BNE
gmt end show

```

Unless @joa-quim has a better idea, one thing we could consider is a way to get that -R string out via mapproject.

**Comment by PaulWessel** [comment]
Sorry, now see @joa-quim basically said the same thing.

**Comment by jidanni** [comment]
(Yeah, parsing out the data from a -V call doesn't sound very dignified.)

**Comment by jidanni** [comment]
Here's what a revised example should look like.

![k](https://github.com/GenericMappingTools/gmt/assets/1230959/7342844c-e4d7-4b3d-9880-d4733dba272e)

And here's the ugly way to get it:

```
gmt begin utm
gmt basemap --MAP_FRAME_AXES=SE -R95/5/108/20+r -Ju46/1:10000000 -B
gmt coast -W -Na
gmt basemap --MAP_FRAME_AXES=NW -R721387.055456/2080949.09788/552077.474203/2279563.58956 -Jx1:10000000 -B
gmt end show
```

Note we don't goop it up with color or anything.
We are just trying to get an example for the average Joe.
We need to simplify the method more.
That's where I'm thinking making a grid file with 0 points in it,
would be one way of porting the region between commands...

**Comment by joa-quim** [comment]
> That's where I'm thinking making a grid file with 0 points in it,

You can't. A grid is a matrix

A bit better.
```
gmt begin utm
    gmt coast -W -Na -R95/5/108/20+r -Ju46/1:10000000 -BSE -Ba
    gmt basemap -R721387.055456/2080949.09788/552077.474203/2279563.58956 -Jx1:10000000 -BNW -Ba
gmt end show

```

**Comment by jidanni** [comment]
Yes, we will note in the comments that we can _goop_ the coast and basemap calls together and save a step.
But it is best to have each step separate so new users can easily turn them off and on with just a "#" in front,
without injuring the rest.

**Comment by PaulWessel** [comment]
FYI, The GMT team is busy working on podcasts for the UNAVCO GMT for Geodesy workshops so we wont really have time to implement new features right now.
