### ISSUE TITLE
N E S W, for meter etc. grids,  not just degrees

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7542]
https://docs.generic-mapping-tools.org/dev/gmt.html#axes-settings says
> +f (for geographic axes only) to give fancy annotations with W|E|S|N suffixes encoding the sign.

Hey, not fair!
In UTM, etc. we talk about meters N. and E.

So why the artificial restriction?

OK, making it suddenly apply to people's X and Y gerbil population vs. sawdust plots would cause people
to freak out.

But still, please do allow a way to turn it on for non-latitude and
longitude values, like in the image on
https://github.com/GenericMappingTools/gmt/issues/7541#issuecomment-1589594860
We see UTM, and lat/lon numbers. But only the latter have N and E on them.
But grab any government map, and all of them have N and E on them.
Therefore GMT needs to be beefed up / updated / smell the coffee.

**Comment by joa-quim** [comment]
There is a suffix option documented somewhere in the -B docs.

**Comment by joa-quim** [comment]
No. **+u**. But that would require two calls. One for horizontal and another for vertical.

**Comment by joa-quim** [comment]
And besides, negative UTM meters are not West or East, are just to the left or to the right of the central meridian.

**Comment by jidanni** [comment]
https://docs.generic-mapping-tools.org/dev/basemap.html has
> +u to append the unit set by +w to all distance annotations along the scale (for the plain scale, +u will instead select the unit to be appended to the distance length).

But that is for legends, and only meters, feet, etc. not N S E W.

**Comment by joa-quim** [comment]
And wrong because -115.87 is ``W``, not ``E``

**Comment by joa-quim** [comment]
```
gmt basemap -R0/10/0/10 -Ba+u" E" -JX10/2 -BwSen -png lixo
```
![lixo](https://github.com/GenericMappingTools/gmt/assets/537321/bafcc9b4-8698-4836-84c5-cd623c5cf5f9)

**Comment by jidanni** [comment]
> And wrong because -115.87 is `W`, not `E`

But the USA is in the Western hemisphere, so I give them 100% grades here.

**Comment by PaulWessel** [comment]
It is relative to utm map center

**Comment by joa-quim** [comment]
This is simply wrong

![image](https://github.com/GenericMappingTools/gmt/assets/537321/6855b6f2-0945-4677-a97a-f1f09147bee9)

**Comment by joa-quim** [comment]
> It is relative to utm map center

That's what I said above about the UTMs

**Comment by jidanni** [comment]
```
echo -115.875 38| proj +proj=utm +zone=11
598773.55	4206412.07
```

**Comment by jidanni** [comment]
Such ~~solutions~~ hacks can't be trusted very far, 
> gmt basemap -R-5/10/0/5 -Ba+u" E" -JX10/2 -BwSen -png lixo

**Comment by jidanni** [comment]
It's east of 500000, which is along this meridian,
```
$ echo 500000 0 | proj -I +proj=utm +zone=11
117dW   0dN
```
500000 W would be out of zone 11, "beyond the pale".

**Comment by jidanni** [comment]
https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Locating_a_position_using_UTM_coordinates :
"A position on the Earth is given by the UTM zone number and band letter and the **_easting and northing_** planar coordinate pair in that zone and band."

**Comment by joa-quim** [comment]
*easting* is not ``E``ast, but I'm not going to continue this discussion. There are way more projections than UTM.
