### ISSUE TITLE
Enable templates for those meter numbers with the little 000s at back

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7544]
**Description of the desired feature**

Look at those fancy <sup>5</sup>99<sup>000m</sup>E fields!
![20230613T120350](https://github.com/GenericMappingTools/gmt/assets/1230959/8b56a135-6a34-4cfd-abf3-88e075966c8b)

Well if the USGS has been doing it for like a hundred years, sooner or later (long term wishlist item) GMT should give a way to turn them on, right there in [basemap -B](https://docs.generic-mapping-tools.org/dev/basemap.html).

Sure, there is
> FONT_ANNOT_PRIMARY             = 12p,Helvetica,black

etc.

But I'm talking about some kind of future template where one specifies what digits etc. should go/be up/down/big/small...

**Are you willing to help implement and maintain this feature?** No

You see, we here in the ideas department just come up with the ideas, and then go off to play, as implementation specialists take over...

**Comment by joa-quim** [comment]
ex28 already has an approximation of that. I don't think we'll go beyond it. There are so many more important things where to consume our time.

**Comment by jidanni** [comment]
That's why I said long term wishlist.

Yes, in [example 28](https://docs.generic-mapping-tools.org/dev/gallery/ex28.html#example-28) he wants this feature so much that he "stoops" to pasting <sub>000</sub> on the back of strings.

That might work for a while, but once such a habit extends to the _front_ of strings, and one doesn't keep one's eyes open, one will get
- <sub>2</sub>98, <sub>2</sub>99, <sub>2</sub>00, <sub>2</sub>01... whereas a real solution would have:
- <sub>2</sub>98, <sub>2</sub>99, <sub>3</sub>00, <sub>3</sub>01...
