### ISSUE TITLE
gmtmath: add example of how to do 1 + 1

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7546]
**Description of the desired feature**

https://docs.generic-mapping-tools.org/dev/gmtmath.html needs a most basic example,
of how to simply add  1 and 1.

**Are you willing to help implement and maintain this feature?** Yes/No

Yes, as soon as I figure out how to add 1 + 1 using gmtmath, I will add an example to that page.

Currently that page only has advanced examples.

**Comment by Esteban82** [comment]
`gmt math -Q 1 1 ADD =`

**Comment by joa-quim** [comment]
And we are **not** adding that as an example.

**Comment by jidanni** [comment]
> `gmt math -Q 1 1 ADD =`

Oh.

I would never have guessed it.

I was trying

```
echo 1 1 ADD = | gmt gmtmath
echo 1 1 ADD | gmt gmtmath
echo 1  | gmt gmtmath STDIN
echo 1  | gmt gmtmath 1 1 ADD STDIN
{ echo 1; echo 1; echo ADD; echo =; }
{ echo 1; echo 1; echo ADD; echo =; }|gmt gmtmath
{ echo 1; echo 1; echo ADD; echo =; }|gmt gmtmath STDIN
{ echo 1; echo 1; echo ADD;  }|gmt gmtmath STDIN
```

I wonder why I couldn't figure it out.

**Comment by jidanni** [comment]
I am sorry.

I have been given a hack.

```
$ gmt math -Q 1 1 1 ADD =
2
gmtmath [WARNING]: 1 more operands left on the stack!
```

I have not been given the general case.

**Comment by joa-quim** [comment]
Normally we discuss these type of issues in the [forum ](https://forum.generic-mapping-tools.org/) not in issues. 
We want to keep their number under control so that we can keep looking to the truly important ones and remembering that we should try to fix them.

**Comment by PaulWessel** [comment]
Both gmtmath and grdmath have links to what RPN is.  You are expected to understand what that is and how a stack operates.

**Comment by joa-quim** [comment]
I'm closing this because we are not going to add ``1 + 1`` example.
