### ISSUE TITLE
I can't make a simple Latex expression for colorbar's label

### ISSUE THREAD

**Issue by xingwu14** [GenericMappingTools/gmt#7547]
**Description of the problem**

I want to display '\Delta' on a colorbar's label, but it gives me TWO confusing error messages. 
One is the GMT script enclosed by the maker "@[...@[" indeed try to call system LaTex, but failed to generate the EPS file. Then, I turn to debug the LaTex installlation by manually creating 'gmt_eq.tex', and use following commands to convert it to EPS file:
```
latex -interaction=nonstopmode gmt_eq.tex > /dev/null
dvips -q -E gmt_eq.dvi -o equation.eps
```
It works normally, so the LaTex installation is OK.

The other is I only installed GMT 6.4, so where  the path 'C:\progs_cygw\GMTdev\gmt5\master\src'  from ? I look over disk C, and no folder has name 'progs_cygw'.

**Full script that generated the error**

```
gmt colorbar -C -DJMR+w15.0c+v+o0.7c/0c+mu  -Bxa0.2f0.1 -By+l'@[\Delta@[b'
```

**Full error message**

```
C:\Users\hstar\AppData\Local\Temp\gmt_latex_a20952>latex -interaction=nonstopmode gmt_eq.tex  1>NUL 
PSL:C:\progs_cygw\GMTdev\gmt5\master\src\postscriptlight.c:6155: Error: Cannot open image file equation.eps!
colorbar [ERROR]: gmtplot_latex_eps: Unable to load EPS file equation.eps
colorbar [ERROR]: gmt_map_text: Conversion of LaTeX to EPS failed
The batch file cannot be found.

C:\Users\hstar\AppData\Local\Temp\gmt_latex_a20952>end [ERROR]: Failed to remove gmt_0.ps-! [remove error: Permission denied]
end [WARNING]: Unable to remove gmt_0.ps- [permissions?]
D:/program/GMT_data/sessions/gmt_session.489: Directory not empty
end [WARNING]: Unable to remove directory D:/program/GMT_data/sessions/gmt_session.489 [permissions?]
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system: Windows 11
* GMT version (`gmt --version`): GMT 6.4 running on Git Bash

**Comment by xingwu14** [comment]
I quit LaTex expressions in GMT script, and work around this issue by using Greek letter, eg., '@~\D@~'.

**Comment by seisman** [comment]
```
gmt colorbar -Cturbo -Dx0c/0c+w15.0c+v+o0.7c/0c+mu  -Bxa0.2f0.1 -By+l'@[\Delta@[b' -pdf ma
```
The command works well for me on macOS with GMT 6.4.0, so it may be a Windows-only issue.

**Comment by joa-quim** [comment]
> The other is I only installed GMT 6.4, so where the path 'C:\progs_cygw\GMTdev\gmt5\master\src' from ? I look over disk C, and no folder has name 'progs_cygw'.

Ah, I was confused by it too because that's my own directory. Checking the code I see that I build it with ``#DEBUG`` and hence it kept my local dir in the binary.

**Comment by xingwu14** [comment]
> 

I have tested it on another Windows machine as well, and the same issue occurred. I agree with your speculation.

**Comment by xingwu14** [comment]
> ```
> gmt colorbar -Cturbo -Dx0c/0c+w15.0c+v+o0.7c/0c+mu  -Bxa0.2f0.1 -By+l'@[\Delta@[b' -pdf ma
> ```
> 
> The command works well for me on macOS with GMT 6.4.0, so it may be a Windows-only issue.

I have tested it on another Windows machine as well, and the same issue occurred. I agree with your speculation.

**Comment by xingwu14** [comment]
> > The other is I only installed GMT 6.4, so where the path 'C:\progs_cygw\GMTdev\gmt5\master\src' from ? I look over disk C, and no folder has name 'progs_cygw'.
> 
> Ah, I was confused by it too because that's my own directory. Checking the code I see that I build it with `#DEBUG` and hence it kept my local dir in the binary.

Thank you for your reply. I still can't understand it. I noticed that when I run the above command on my home computer, it doesn't show this unknown path (your directory). It only happens on the office computer. Both of these computers have the same Windows 11 operating system installed, with the same GMT 6.4 package installed as well. Fortunately, it doesn't affect normal usage, and I don't intend to dwell on it.

**Comment by joa-quim** [comment]
> I still can't understand it.

See
https://github.com/GenericMappingTools/gmt/blob/6.4.0/src/postscriptlight.c#L6155

that ``, __FILE__, __LINE__);`` tells the program to print the full file name (at the time of program compiling) and line number.

I can't see why the same GMT version would print that message in one computer and not in another.

**Comment by xingwu14** [comment]
> 

I got you. As for why different information is printed on different computers, I suspect it might be because my office computer had GMT 5.4 installed two years ago, although it was later uninstalled.

**Comment by xingwu14** [comment]
> > I still can't understand it.
> 
> See https://github.com/GenericMappingTools/gmt/blob/6.4.0/src/postscriptlight.c#L6155
> 
> that `, __FILE__, __LINE__);` tells the program to print the full file name (at the time of program compiling) and line number.
> 
> I can't see why the same GMT version would print that message in one computer and not in another.

I got you. As for why different information is printed on different computers, I suspect it might be because my office computer had GMT 5.4 installed two years ago, although it was later uninstalled.

**Comment by joa-quim** [comment]
This now works on windows too.

**Comment by PaulWessel** [comment]
Good
