### ISSUE TITLE
The large number of failures

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7553]
I routinely get > 50 failures when running the test.  I think most of that is related to to not updating our _PostScript_ files because the CI that runs test uses an archaic version of **ghostscript**.  Could you remind us about the status of that, @seisman?  It is hard to detect new failures when they are drowning in these long-standing **ghostscript**-version-related problems.

**Comment by joa-quim** [comment]
I have ~12 on Win (gs 9.56) and that is similar to what we get in the CI runs. You may need to update your DVC figs.
But it's true that there at least 4 failures that are due to stranhe PS origs that seem to have different plot origins.

**Comment by PaulWessel** [comment]
`dvc pull`
Everything is up to date.    

`gs --version           `                                                                                                                                           
9.56.1

So we run the same gs and all files are up to date.  Makes no sense...

**Comment by seisman** [comment]
Here are the status of our current CI jobs:

| Platform | gs version | Failures |
|---|---|---|
| Linux | 9.55.0 | 10 | 
| macOS | 10.01.1 | 84 |
| Windows | 9.50 | 4 |

**Comment by joa-quim** [comment]
We are well aware of this situation.
