### ISSUE TITLE
Bug with DCW-Collections on Windows?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7561]
This fails with **gmt-6-4.0-win64**.  I don't know if it was fixed. I think that this is related to #6864.

```
$ gmt coast -RScandinavia -W -png lixo
coast [WARNING]: No country code matching Scandinavia (skipped)
coast [ERROR]: South is outside -90 to +90 degree range
coast [ERROR]: General map projection error
```

Also the output of `gmt pscoast -E+n` on Windows has two lines for record. I think it should have 1 as on linux.  Maybe are related.

Sample of the output on **Linux** (one single line)

```
...
MGHR    Maghreb DZ,LY,MA,MR,TN,EH
ARBC    Arab Countries  EG,SD,BH,IQ,JO,KW,LB,OM,PS,QA,SA,SY,AE,YE,DZ,LY,MA,MR,TN,EH,DJ,SO
IHO1    Baltic Sea      9.8408/30.3471/53.6016/65.9071
IHO1A   Gulf of Bothnia 17.0391/25.5092/59.6203/65.9071
IHO1B   Gulf of Finland 22.8971/30.3471/59.2154/60.7428
```
Sample of the output on **windows** (two lines):

```
# TAG	Name		Codes|Region
...
MGHR	Maghreb
	DZ,LY,MA,MR,TN,EH
ARBC	Arab Countries
	EG,SD,BH,IQ,JO,KW,LB,OM,PS,QA,SA,SY,AE,YE,DZ,LY,MA,MR,TN,EH,DJ,SO
IHO1	Baltic Sea
	9.8408/30.3471/53.6016/65.9071
IHO1A	Gulf of Bothnia
	17.0391/25.5092/59.6203/65.9071
IHO1B	Gulf of Finland
	22.8971/30.3471/59.2154/60.7428

```

**Comment by joa-quim** [comment]
> gmt coast -RScandinavia

Did this ever worked? I think not, so is not really a bug.

Can't reproduce the two lines behavior on Win (both dev and 6.4.0)
```
C:\v>pscoast -E+n
# TAG   Name            Codes|Region
UN002   DZ,EG,LY,MA,SD,TN,EH,IO,BI,KM,DJ,ER,ET,TF,KE,MG,MW,MU,YT,MZ,RE,RW,SC,SO,SS,TZ,UG,ZM,ZW,AO,CM,CF,TD,CG,CD,GQ,GA,ST,BW,SZ,LS,NA,ZA,BJ,BF,CV,CI,GM,GH,GN,GW,LR,ML,MR,NE,NG,SH,SN,SL,TG
UN015   DZ,EG,LY,MA,SD,TN,EH
```

**Comment by Esteban82** [comment]
> > gmt coast -RScandinavia
> 
> Did this ever work? I think not, so is not really a bug.

I got this map on Linux and I took the example from the dcw docs (https://github.com/GenericMappingTools/dcw-gmt/tree/master#dcw-collections).

![lixo](https://github.com/GenericMappingTools/gmt/assets/17908951/ab3b54ca-40bc-417a-984a-359cd8b18dec)

**Comment by PaulWessel** [comment]
Wont run for me:

gmt coast -RScandinavia
gmt [ERROR]: Shared GMT module not found: coast

**Comment by Esteban82** [comment]
` gmt coast -RScandinavia -W -png lixo`

**Comment by PaulWessel** [comment]
Ah!  Works.

**Comment by joa-quim** [comment]
Not for me on WSL
```
j@dell-from-hell:~$ gmt coast -RScandinavia -W -png lixo
coast [WARNING]: No country code matching Scandinavia (skipped)
```

**Comment by Esteban82** [comment]
Does it works with the full name of countries? It didn't work for me on  **gmt-6-4.0-win64**- It worked on Linux **gmt-6.5_dev.**

`gmt coast -RNorway -Baf -W -png Norway`

**Comment by joa-quim** [comment]
So I found the f. For some reason my dcw text files have Windows EOLs and when ``gmt_dcw`` reads them with
```
sscanf (line, "%s %s %[^\n]", Country[k].continent, Country[k].code,  Country[k].name);
```

the ``Country[k].name`` keeps the remaining ``\r`` and later string comparisons fail. Any reason to not read with?
```
sscanf (line, "%s %s %s", Country[k].continent, Country[k].code,  Country[k].name);
```
