### ISSUE TITLE
Issue with grdgradient and region.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7562]
## Issue

It seems grdgradient is NOT taking the region from previous commands. So in the following script, `grdgradient` makes an intesity grid of -180/180/-90/90 for any region (-Rg, -RUY, -R0/300/-90/90). If the region is (at least partially) between 180 and 360, then `grdimage` fails.
(If I select an small region, like Uruguay, them GMT makes a lot of extra work calculating a grid for the whole world.)

## Solution
In other to avoid this I have to write again the region (-R...) on grdgradient. But I was expecting the `grdgradient` could read the region from the previous command. I don't know if a bug or a feature request. 

## Full script

```
gmt begin TEST png
    gmt basemap -B0 -JW15c -Rg

#   1. Calculate intesity grids from the relief grid 
    gmt grdgradient @earth_synbath_10m -A45 -Nt1 -Grelief_gradient.nc
    gmt grdinfo relief_gradient.nc
    
#   2. Plot satelital image with hill shading efect
    gmt grdimage @earth_day -Irelief_gradient.nc
gmt end
```

**Comment by joa-quim** [comment]
This is modern mode thing, right? Because in classic we need to specify a **-R**, otherwise the whole grid is used.

**Comment by Esteban82** [comment]
Yes, modern mode. 
I remember that in classic I could use `-R` and forget about the region. But now in modern mode, I have to write the region again. 
Maybe we could let `-R` works on modern mode if the users wants to use the region of the previous commands and not the whole grid.

**Comment by PaulWessel** [comment]
Remember we have two regions now: Plot region and processing region.  We may use the latter for a plot but not a plot region for data processing.

**Comment by Esteban82** [comment]
I see: 

> However, if a data-processing module is not given a region then we only look for a previous processing domain; we never substitute a plot domain in that case.

So, I what I need is a way to access the plot domain region for the data-processing module. Something like `-R"${plot_domain}"`. Is it possible?

**Comment by joa-quim** [comment]
Close?

**Comment by Esteban82** [comment]
Yes, it is not an important feature.
