### ISSUE TITLE
Wrong error messages with grdcut -D 

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7570]
```
gmt grdcut @earth_synbath -RIT -JM15c -D
6.6125  18.5166666667   35.4916666667   47.0958333333   0.00416666666667        0.00416666666667
grdcut [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]
grdcut [NOTICE]: SYNBATH Earth Relief original at 15x15 arc seconds [Sandwell et al., 2022].
grdcut [NOTICE]:   -> Download grid file [2.9G]: earth_synbath_15s_p/
grdcut [ERROR]: Libcurl Error: Failed writing received data to disk/application
grdcut [ERROR]: Unable to obtain remote file @earth_synbath_15s_p
```
I think these error messages are wrong.

**Comment by joa-quim** [comment]
What is wrong? Notice that this is a libcurl message
```
Libcurl Error: Failed writing received data to disk/application
```

**Comment by Esteban82** [comment]
There is no error in the code. It just can be confussing for the users.

**Comment by joa-quim** [comment]
Sorry, what is that can be confusing? The libcurl message? We can't do nothing about it.

**Comment by Esteban82** [comment]
But if I add `-Vq` then that error message is not shown.

```
gmt grdcut @earth_synbath -RJP -JM15c -D+t -Vq
-R122:56:00E/145:49:30E/20:31:30N/45:31:30N -I30s/30s
```

Also, that error message doesn't appear if I had previously downloaded the grid.

**Comment by joa-quim** [comment]
If you have the grid(s) already there libcurl does not enter the game, so no error message. If **-Vq** error messages are silenced as requested. Still don't get what you are proposing.

**Comment by Esteban82** [comment]
From the docs:

> -D[+t]
> A “dry run”: Simply report the region and increment of what would be the extracted grid given the selected options. No grid is created and instead we write a single data record with west east south north xinc yinc to standard output.

When -D is used, there is no need to use libcurl at all. So, we never should get an error message.

**Comment by joa-quim** [comment]
OK, so the error is that an libcurl was run when it shouldn't have been.

**Comment by Esteban82** [comment]
It seems so. Altough I don't know exactly what is happening under the hood.
