### ISSUE TITLE
gmt surface gave segfault with pixel-node registration but not gridline-node registration, only on M1 architecture

### ISSUE THREAD

**Issue by kmaterna** [GenericMappingTools/gmt#7586]
Running a tutorial this week, we discovered 4 people having the same issue:  ```gmt surface``` gave different behaviors for ```-rg``` (success)  and ```-rp``` (segfault).  They were all M1 macs.  No issues are reported on linux or Intel-chip macs for the same commands and same data; and strangely, a few M1 macs also succeeded.  The data file we used is attached.  The problem might be instigated by something in the data file, but still, the unexpected failure of one registration over the other, and apparently just on M1 architecture, feels like it's a bug nonetheless.    Please let me know if you need help reproducing it and I'll rope in some of the participants who encountered it. 

```gmt surface xy_vert.txt -Gvert.grd -R-125.8/-122.6/39.3/41.7 -I0.0064 -rg```
--> This worked perfectly. 

```gmt surface xy_vert.txt -Gvert.grd -R-125.8/-122.6/39.3/41.7 -I0.0064 -rp```
--> This produced error message: 

ERROR: Caught signal number 11 (Segmentation fault: 11) at
0 libgmt.6.dylib 0x0000000102a12f64 _quicksort + 1528
zsh: trace trap gmt surface xy_vert.txt -Gvert.grd -R-125.8/-122.6/39.3/41.7 -I0.0064 -rp

**System information**
As one example of a system that encountered this issue: 
System: 2021 Macbook Pro, OS Ventura 13.4, Apple M1 Pro
arch: arm64
GMT: 6.4.0

[xy_vert.txt](https://github.com/GenericMappingTools/gmt/files/11919096/xy_vert.txt)

**Comment by Esteban82** [comment]
I test on linux with gmt 6.5 (dev veserion) and it worked fot both cases. No one could try with the dev version?

**Comment by PaulWessel** [comment]
Reproducible on my M1 MacBook. Crashes in quick _sort_r_ which is a GNU code we provide.  But I no longer remember why. man _qsort_ on my mac shows _qsort_r_.  I will try to re-learn why we did that and why it is always included in the CMakeList.txt set up.

**Comment by joa-quim** [comment]
I think we needed a reentrant version

**Comment by PaulWessel** [comment]
Yes, but is that not qsort_r?

**Comment by joa-quim** [comment]
Don’t remember much too but maybe something after that stupid bug in MSVC that they refused to accept as bug.

**Comment by joa-quim** [comment]
Confirmed. I reverted to a previous branch and the crash went way.
Here are the lines that cause the crash in master
```
julia> l1 = gmt("project -C22/49 -E-60/-20 -G20 -Q");
julia> l2 = gmt("project -C0/-60 -E-60/-30 -G20 -Q");
julia> gmtspatial((l1, l2), I=:e, F="l");
```

**Comment by joa-quim** [comment]
If I change the #ifdef logic and change line 4826 to (instead of #ifdef)
```
#ifndef QSORT_R_THUNK_FIRST
```
then the crash goes way.

**Comment by PaulWessel** [comment]
Hm, will need to stick in some pragma warnings to see which branch it goes into.  The original  **surface** case works OK before **and** after your change?

**Comment by joa-quim** [comment]
Didn’t try, but it cannot make any difference. My change affects only the order of arguments for that particular function.

**Comment by PaulWessel** [comment]
Could perhaps @anbj can give master a spin and try the surface commands at top.  We believe we have done this correctly for Linux but without building and running we do not know.

**Comment by anbj** [comment]
Will do. Probably later today.

**Comment by anbj** [comment]
I built *master* and ran the commands given in the first post without problems:

```
$ gmt surface xy_vert.txt -Gvert.grd -R-125.8/-122.6/39.3/41.7 -I0.0064 -rg
$ gmt surface xy_vert.txt -Gvert.grd -R-125.8/-122.6/39.3/41.7 -I0.0064 -rp
```

**Comment by PaulWessel** [comment]
Thanks, was that a BDS or another Linux?

**Comment by anbj** [comment]
Sorry. Yes Linux. Debian 11.

**Comment by joa-quim** [comment]
Bump (already sedimenting below the minor issues)

**Comment by joa-quim** [comment]
Can we close this?
