### ISSUE TITLE
Bug in movie with custom Canvas size (again)

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7587]
I made a movie with this canvas size (`-C24cx10.46cx80`) and ffmpeg couldn't make the movie. Below are the important messages IMHO from the teminal:

```
movie [WARNING]: Your frame width is an odd number of pixels (1920). This will not work with FFmpeg
movie [WARNING]: Your frame height was adjusted to 10.4605c, giving an even height of 2126 pixels
movie [INFORMATION]: Paper dimensions: Width = 24c Height = 10.4605c
movie [INFORMATION]: Pixel dimensions: 1920 x 2126
...
[libx264 @ 0x56263cc7fa00] height not divisible by 2 (1920x837)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
movie [ERROR]: Running FFmpeg conversion to MP4 returned error 256 - exiting.

```

First, **It says that 1920 is an odd number !!** Then, changes the width to 10.4605c. I don't know where 2126 comes from.
Ffmpeg can't make the movie because the heigth is 837 pixels.

Some calculations that might help:
10.46 x 80 = 836.8
10.4605 x 80 = 837
2126 / 80 = 26.575

I think it is a particular case that is well solved by the issue's calculations of #3542. I can't see where it fails.

## Full script

```
#!/usr/bin/env bash
cat << EOF > main.sh
gmt begin
	echo \${MOVIE_FRAME} | gmt text -R0/1/0/1 -JX10c -F+f200p+cCM -B0 -X0 -Y0
gmt end
EOF
gmt movie main.sh -Nffmpeg -T4 -C24cx10.46cx80 -Zs -D12 -Ml,png -Fmp4 -Vi   # Fails 
gmt movie main.sh -Nffmpeg -T4 -C24cx10.45cx80 -Zs -D12 -Ml,png -Fmp4 -Vi   # Works
```

**Comment by PaulWessel** [comment]
The 1920 was funny.  Took me a little while to reasize the message for odd height was a copy/paste from worth and hence 1920.  Also, I guess this is the first time using -C with dimensions and not -CHD etc.
