### ISSUE TITLE
Remove all mention of using 1:xxxx format with -J from the docs

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7594]
Please remove all mention of using 1:xxxx format with -J from the
docs. It is scattered all over the place, and misleads users.
It must have been copied blindly into the docs from other projections.
Thanks.

Proof:
```
gmt begin x
#   gmt coast -R270/20/305/25+r -JOc280/25.5/22/69/12c -W
    gmt coast -R270/20/305/25+r -JOc280/25.5/22/69/1:27705500 -W
gmt end show

coast [ERROR]: Cannot specify map width with 1:xxxx format in -J option
coast [ERROR]: Option -J parsing failure. Correct syntax: ...

gmt begin y
#   gmt basemap -R270/20/305/25+r -JOc280/25.5/22/69/12c        -B
    gmt basemap -R270/20/305/25+r -JOc280/25.5/22/69/1:27705500 -B
gmt end show

basemap [ERROR]: Cannot specify map width with 1:xxxx format in -J option
basemap [ERROR]: Option -J parsing failure. Correct syntax: ...
```

**Comment by PaulWessel** [comment]
Do you have an example where this happens? We are will aware of 1:xxxx with lower case and thought we have been consistent.

**Comment by jidanni** [comment]
I see, I forgot to test with the little o instead of the big O!

You know what, 

can you please change the error message top part,
```
Cannot specify map width with 1:xxxx format in -J option
```
to say instead
```
Cannot specify map width with 1:xxxx format with -JO option. Try -Jo.
```
Then close this bug. Thanks.

**Comment by PaulWessel** [comment]
But this applies to every projection, not just -Jo no?

**Comment by jidanni** [comment]
OK, I made a much clearer #7598 .
