### ISSUE TITLE
Allow downloading the documentation for offline reading

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7597]
On the proj website one can download the documentation,
via the link at the very bottom:

![20230702T194232](https://github.com/GenericMappingTools/gmt/assets/1230959/1c034403-17e7-4438-a296-b92c3fd897a7)

which expands to reveal PDF downloads.

![20230702T194346](https://github.com/GenericMappingTools/gmt/assets/1230959/85600e89-e9a8-4926-b10d-a8a655af0d4a)

Alas, on the GMT site, there is no such link.

![20230702T194310](https://github.com/GenericMappingTools/gmt/assets/1230959/40fd3034-f0da-4faf-9908-ebcc599f1802)

The only way to read GMT documentation is with an Internet connection.

**Comment by seisman** [comment]
GMT has its offline documentation installed in its `share/doc/html` directory, and you can use `gmt docs home` to open it in your local browser without internet connections.

**Comment by jidanni** [comment]
$ gmt docs home

> No internet
> Try:
>
> Checking the network cables, modem, and router
> Reconnecting to Wi-Fi
> ERR_INTERNET_DISCONNECTED

$ find /usr/share/doc/gmt* -type f|wc -l
26
$ find /usr/share/doc/gmt* -type f|grep -c html
0

$ aptitude search gmt
i   gmt
i A gmt-common
i   gmt-dcw
p   gmt-gshhg
v   gmt-gshhg-data
p   gmt-gshhg-full
p   gmt-gshhg-high
i   gmt-gshhg-low
v   gmt-gshhs-full
v   gmt-gshhs-high
v   gmt-gshhs-low
p   gmtkbabel
p   gmtp
p   golang-github-apparentlymart-go-openvpn-mgmt-dev
p   libgmt-dev
i A libgmt6
v   librust-winapi+appmgmt-dev
v   librust-winapi-0+appmgmt-dev
v   librust-winapi-0.3+appmgmt-dev
v   librust-winapi-0.3.9+appmgmt-dev
p   ogmtools
p   powermgmt-base

**Comment by jidanni** [comment]
$ aptitude search gmt | grep -c doc
0
$ dlocate gmt | grep -c html
0

**Comment by joa-quim** [comment]
Please, discuss things in the forum before opening issues for every difficulties you find. 
If you build GMT yourself or used a distro that does not distribute the documentation, ``gmt docs`` will not work.

**Comment by jidanni** [comment]
All I am saying is the docs should also be available by independent download, just like with proj.
That will cover all cases.

**Comment by jidanni** [comment]
This also means there is no way to print out a paper copy!

Yes, you heard me correctly. No PDF to print.

The best one can do is print each page separately. That's a lot of clicking.

**Comment by seisman** [comment]
> Surely it's just one line different in your configuration file versus proj's.
> 
> Since you're both using the same Read The Docs software, you just need to uncomment one line surely, then it'll start producing the PDFs.

No, GMT doesn't use the Read The Docs service as proj does, so it's impossible to produce PDFs by uncommenting one or a few lines.

We decided to entirely remove the PDF documentation in https://github.com/GenericMappingTools/gmt/issues/805, mainly because 

1. not everything that can be done in HTML translate to PDF
2. It adds bulk to the tarballs,

**Comment by jidanni** [comment]
All I know is on both sites every page bottom says

> Built with Sphinx using a theme provided by Read the Docs.

But OK, there should be at least an HTML tarball one can download, without needing to install git.

**Comment by PaulWessel** [comment]
Hm, isn't there some simple way to download an entire website tree (e.g., 6.4.0 documentation) and make a local copy?

**Comment by anbj** [comment]
Agree on this. The docs should be easility downloadable, pref. in both html and pdf. There have been forum posts requesting this. Requiring people to build the docs themselves.

Maybe something ala ``$ wget --recursive --page-requisites --adjust-extension --span-hosts --convert-links --restrict-file-names=windows --domains docs.generic-mapping-tools.org --no-parent https://docs.generic-mapping-tools.org/dev/index.html`` could work.

**Comment by anbj** [comment]
Tested the wget command above, and looks good;

```
Converted links in 445 files in 0.2 seconds.
``

**Comment by jidanni** [comment]
Okay, so somewhere on the website, when people are clicking on the link to get documentation,  have this wget method listed as the way to get documentation. And then close this bug. Thank you.

**Comment by seisman** [comment]
Maybe the easiest way is: download the [GMT tarball](https://github.com/GenericMappingTools/gmt/releases/download/6.4.0/gmt-6.4.0-src.tar.gz), uncompress it, then the documentation is available in the `gmt/doc_release/html` directory.

**Comment by jidanni** [comment]
Hmmm, maybe users could
- just get the doc tree
- and an up-to-the-minute version too

from https://github.com/GenericMappingTools/gmt/tree/master/doc
alas, there is no 'download a zip' button.

**Comment by joa-quim** [comment]
Next release will have a docs.zip in the Github site
