### ISSUE TITLE
Fix misleading -JO error message that calls itself a -J error message

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7598]
There is a terrible error message.

It sends users home without hope.

The message is
- [ERROR]: Cannot specify map width with 1:xxxx format in -J option

It should be
- [ERROR]: Cannot specify map width with 1:xxxx format in -JO option

and even better would be
- [ERROR]: Cannot specify map width with 1:xxxx format in -JO option. Use -Jo.

So all I am saying is please add a few more ASCII to this error message.

I would but the GitHub search can't find it.

**Comment by joa-quim** [comment]
Paul said it already. This is a generic error message for all **-J**, not **-JO**. I don't think it is so difficult to infer that the **-J** in that error message respects the particular one that was being attempted. It is the first tie in 30 years that this issues is raised.

**Comment by jidanni** [comment]
All I know is it is a wrong error message.

**Comment by joa-quim** [comment]
That is simple. We can make it
```
[ERROR]: Cannot specify map width with 1:xxxx format in projection option
basemap [ERROR]: Option -J parsing failure. Correct syntax:

  -J Select map proJection (<scale> in cm/degree, <width> in cm). Modifiers:
...
```

**Comment by jidanni** [comment]
Well, I think my version is clearer. But at least your version isn't wrong anymore.

**Comment by PaulWessel** [comment]
Thanks guys, I ended up submitting @joa-quim's suggestion to master.
