### ISSUE TITLE
gmt movie - ERROR: No module named movie was found.

### ISSUE THREAD

**Issue by rvbarreto** [GenericMappingTools/gmt#76]
I'm trying to run the examples for animations at [http://gmt.soest.hawaii.edu/doc/latest/Gallery.html](http://gmt.soest.hawaii.edu/doc/latest/Gallery.html) however, I receive this error message:

> ERROR: No module named movie was found.  This could mean one of three cases:
>   1. There actually is no such module; please check your spelling.
>   2. Module exists in the GMT supplemental library, but the library could not be found.
>   3. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
> Shared libraries must be in standard system paths or set via environmental parameter LD_LIBRARY_PATH.

I'm running gmt 5.4.4 on Ubuntu 16.04.3. I've just downloaded it today and built it along dcw and gshhg. I can see many other modules, but not the movie module.

> $ gmt --show-modules
> blockmean
> blockmedian
> blockmode
> filter1d
> fitcircle
> gmt2kml
> gmtconnect
> gmtconvert
> gmtdefaults
> gmtget
> gmtinfo
> gmtlogo
> gmtmath
> gmtregress
> gmtselect
> gmtset
> gmtsimplify
> gmtspatial
> gmtvector
> gmtwhich
> grd2cpt
> grd2rgb
> grd2xyz
> grdblend
> grdclip
> grdcontour
> grdconvert
> grdcut
> grdedit
> grdfft
> grdfill
> grdfilter
> grdgradient
> grdhisteq
> grdimage
> grdinfo
> grdlandmask
> grdmask
> grdmath
> grdpaste
> grdproject
> grdraster
> grdsample
> grdtrack
> grdtrend
> grdvector
> grdview
> grdvolume
> greenspline
> kml2gmt
> makecpt
> mapproject
> nearneighbor
> project
> psbasemap
> psclip
> pscoast
> pscontour
> psconvert
> pshistogram
> psimage
> pslegend
> psmask
> psrose
> psscale
> pssolar
> psternary
> pstext
> pswiggle
> psxyz
> psxy
> sample1d
> spectrum1d
> sph2grd
> sphdistance
> sphinterpolate
> sphtriangulate
> splitxyz
> surface
> trend1d
> trend2d
> triangulate
> xyz2grd
> gshhg
> img2grd
> pscoupe
> psmeca
> pspolar
> pssac
> psvelo
> mgd77convert
> mgd77header
> mgd77info
> mgd77list
> mgd77magref
> mgd77manage
> mgd77path
> mgd77sniffer
> mgd77track
> dimfilter
> gmtflexure
> gmtgravmag3d
> gpsgridder
> gravfft
> grdflexure
> grdgravmag3d
> grdredpol
> grdseamount
> talwani2d
> talwani3d
> pssegyz
> pssegy
> segy2grd
> backtracker
> gmtpmodeler
> grdpmodeler
> grdrotater
> grdspotter
> hotspotter
> originator
> rotconverter
> rotsmoother
> x2sys_binlist
> x2sys_cross
> x2sys_datalist
> x2sys_get
> x2sys_init
> x2sys_list
> x2sys_merge
> x2sys_put
> x2sys_report
> x2sys_solve

**Comment by seisman** [comment]
@rvbarreto `gmt movie` is a new module in GMT6, which is not official released yet.

**Comment by rvbarreto** [comment]
Ok, that explains everything. Maybe a side note on the page would be nice. Thanks

**Comment by seisman** [comment]
@rvbarreto As a GMT 5.4.4 user, you can refer to http://gmt.soest.hawaii.edu/doc/5.4.4/index.html.

http://gmt.soest.hawaii.edu/doc/latest/index.html is the documentation for GMT 6.0.0 only.
