### ISSUE TITLE
transparency does not work on MacOS 13.4.1

### ISSUE THREAD

**Issue by zhuozech** [GenericMappingTools/gmt#7600]
**transparency does not work on MacOS 13.4.1, used to work on the older version of MacOS, after system update, while runing the same script, transparency no longer works**

**Full script that generated the error**

```
gmt grdview afterslip.grd -Qi -Cpolar -t70
gmt plot coseisregion.txt  -Gred -t50
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**actual: No transparency **

** expected: with transparency**

**System information**

* Operating system:MacOS 13.4.1
* GMT version (`gmt --version`):6.4.0

**Comment by seisman** [comment]
What's the version of your ghostscript (`gs --version`)? How did you install GMT?

**Comment by zhuozech** [comment]
gs -- version 10.00.0
brew install gmt

**Comment by joa-quim** [comment]
That is a known problem. Until 6.5 is out either build the dev version or downgrade ghostscript to the 9.xxx series.

**Comment by joa-quim** [comment]
I'm closing this because this issue is actually fixed in DEV version.
