### ISSUE TITLE
Movie: Canvas, width and pixels

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7601]
When thinking about animation, it is more logical to work with pixels than with cm or inches. But GMT users are used to create maps with cm/inches. I think this cannot be changed.

The only thing I think that can be done about it, at least for now, is to add the pixel density for named format in the table.
I can do it. 

Any toughts?

**Comment by PaulWessel** [comment]
Sure pixels is more common, so -C1080px870p, but still need cpu to related to actual distances.
OK with me if you want to add to the docs; note that the usage message have it already:

```
-C<canvas>|<width>x<height>x<dpu>
     Specify canvas. Choose either a known named canvas or set custom dimensions.
     • Recognized 16:9-ratio names and associated dimensions:
        name:  pixel size:    canvas (SI):       dpc:      canvas (US):       dpi:
       ---------------------------------------------------------------------------
       4320p:  7680 x 4320    24 x 13.5 cm   320.0000    9.6 x 5.4 inch   800.0000
       2160p:  3840 x 2160    24 x 13.5 cm   160.0000    9.6 x 5.4 inch   400.0000
       1080p:  1920 x 1080    24 x 13.5 cm    80.0000    9.6 x 5.4 inch   200.0000
        720p:  1280 x  720    24 x 13.5 cm    53.3333    9.6 x 5.4 inch   133.3333
        540p:   960 x  540    24 x 13.5 cm    40.0000    9.6 x 5.4 inch   100.0000
        480p:   854 x  480    24 x 13.5 cm    35.5833    9.6 x 5.4 inch    88.9583
        360p:   640 x  360    24 x 13.5 cm    26.6667    9.6 x 5.4 inch    66.6667
        240p:   426 x  240    24 x 13.5 cm    17.7500    9.6 x 5.4 inch    44.3750
     • Recognized 4:3-ratio names and associated dimensions:
        name:  pixel size:    canvas (SI):       dpc:      canvas (US):       dpi:
       ---------------------------------------------------------------------------
        uxga:  1600 x 1200    24 x 18 cm      66.6667    9.6 x 7.2 inch   166.6667
       sxga+:  1400 x 1050    24 x 18 cm      58.3333    9.6 x 7.2 inch   145.8333
         xga:  1024 x  768    24 x 18 cm      42.6667    9.6 x 7.2 inch   106.6667
        svga:   800 x  600    24 x 18 cm      33.3333    9.6 x 7.2 inch    83.3333
         dvd:   640 x  480    24 x 18 cm      26.6667    9.6 x 7.2 inch    66.6667

```

**Comment by Esteban82** [comment]
> , but still need cpu to related to actual distances.

Yes, my idea is to add that info in the docs so the users can choose the dpc/dpi to get a similar quality of the named formats (along with the dimensions).

**Comment by Esteban82** [comment]
> note that the usage message have it already:
> 
> ```
> -C<canvas>|<width>x<height>x<dpu>
>      Specify canvas. Choose either a known named canvas or set custom dimensions.
>      • Recognized 16:9-ratio names and associated dimensions:
>         name:  pixel size:    canvas (SI):       dpc:      canvas (US):       dpi:
>        ---------------------------------------------------------------------------
>        4320p:  7680 x 4320    24 x 13.5 cm   320.0000    9.6 x 5.4 inch   800.0000
>        2160p:  3840 x 2160    24 x 13.5 cm   160.0000    9.6 x 5.4 inch   400.0000
>        1080p:  1920 x 1080    24 x 13.5 cm    80.0000    9.6 x 5.4 inch   200.0000
>         720p:  1280 x  720    24 x 13.5 cm    53.3333    9.6 x 5.4 inch   133.3333
>         540p:   960 x  540    24 x 13.5 cm    40.0000    9.6 x 5.4 inch   100.0000
>         480p:   854 x  480    24 x 13.5 cm    35.5833    9.6 x 5.4 inch    88.9583
>         360p:   640 x  360    24 x 13.5 cm    26.6667    9.6 x 5.4 inch    66.6667
>         240p:   426 x  240    24 x 13.5 cm    17.7500    9.6 x 5.4 inch    44.3750
>      • Recognized 4:3-ratio names and associated dimensions:
>         name:  pixel size:    canvas (SI):       dpc:      canvas (US):       dpi:
>        ---------------------------------------------------------------------------
>         uxga:  1600 x 1200    24 x 18 cm      66.6667    9.6 x 7.2 inch   166.6667
>        sxga+:  1400 x 1050    24 x 18 cm      58.3333    9.6 x 7.2 inch   145.8333
>          xga:  1024 x  768    24 x 18 cm      42.6667    9.6 x 7.2 inch   106.6667
>         svga:   800 x  600    24 x 18 cm      33.3333    9.6 x 7.2 inch    83.3333
>          dvd:   640 x  480    24 x 18 cm      26.6667    9.6 x 7.2 inch    66.6667
> ```

I didn't know this. I thougth that the docs have the same info that `gmt movie`. 

I will update the table of documents with this information. I may simplify it if it is too wide.

**Comment by PaulWessel** [comment]
Any progress on this, @Esteban82 ?

**Comment by Esteban82** [comment]
I'm afraid not. I might try to do it this weekend.
