### ISSUE TITLE
mapproject: add -WM, -Wm to get -V "Transform" parameters

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7607]
mapproject -W is very powerful,

           -W[e|E|g|h|j|n|o|O|r|R|w|x][+n[<nx>[/<ny]]]

There are many things we can produce (extending [NZ example](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#oblique-mercator-projection-jo-jo)),

-R160.659131989979/184.219657724046/-51.18901341638602/-31.31886652370631
-R170.9769371506913/-51.18901341638602/174.976186460147/-31.31886652370631+r
-R19157.1283345/19379.5184385/-5195.81602391/-4899.88909908+uk

The first two are a cinch, but as noted in #7541, the last one is
currently one big hassle:

```
gmt mapproject $R -JOA$lon/$lat/$az/3i -WR
gmt mapproject $R -JOA$lon/$lat/$az/3i -WE
gmt mapproject $R -JOA$lon/$lat/$az/3i -W -V 2>&1 |
    sed -n 's/.*<- /-R/p'|sed 's/ .*/+uk/'
```

Thus there should be -Wm and -WM options added, so one needn't resort to
parsing -V stderr to dig the info out -- "data mining".

P.S., I stuck +uk on there on a hunch. I don't even know if what I am
talking about is metric always. All I know is it is encased in -V output
and needs to be dug out.

**Comment by joa-quim** [comment]
Done
