### ISSUE TITLE
-Jo|O usage message mentions a|b|c vs. A|B|C, but doesn't mention o vs. O:

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7610]
```
$ gmt basemap 
-Jo|O<parameters>[+v] (Oblique Mercator). Specify one of three definitions:
       -Jo|O[a|A]<lon0>/<lat0>/<azimuth>/<scale>|<width>. Give origin, azimuth of oblique equator,
          and scale at oblique equator
       -Jo|O[b|B]<lon0>/<lat0>/<lon1>/<lat1>/<scale>|<width>. Give origin, second point on oblique
          equator, and scale at oblique equator.
       -Jo|Oc|C<lon0>/<lat0>/<lonp>/<latp>/<scale>|<width>.Give origin, pole of projection, and
          scale at oblique equator.
       Specify region in oblique degrees OR use -R<...>+r. Uppercase A|B|C removes enforcement of a
       northern hemisphere pole. Append +v to make the oblique Equator the y-axis [x-axis].
```
A|B|C vs. a|b|c is explained, but not O|o.
Yes, both are explained elsewhere, but oddly just one here. Version 6.4.

**Comment by PaulWessel** [comment]
We appreciate that you are looking for doc errors or weaknesses. But, the -J sections start off with explaining the upper vs lower case codes.  we do expect people to look at the full docs, and if they just scroll quickly down to -Jo|O and do not understand what the difference is then they are clearly rookie GMT users who do not know how our mapping works.  You are not one of those and we get extremely few forum/bug postings about confusing between lower and upper.  From that I think we conclude that we explain it well enough.
We are happy to fix bugs in the docs but rearrange in major ways requires us to agree with the purpose and here I at least dont. Maybe others from the @GenericMappingTools/gmt-docs disagree?

**Comment by Esteban82** [comment]
I agree with Paul that it is clear enough.

**Comment by anbj** [comment]
Have to agree. ``-J`` upper vs. lower is one of the first things that you should/have to read up on as a rookie.

**Comment by joa-quim** [comment]
I add again the request that things like this are discussed first in the forum before opening these micro-issues. We have **much too much** open issues.

**Comment by PaulWessel** [comment]
Documentation will be on summit agenda anyway
