### ISSUE TITLE
Multiple projections in subplot issue

### ISSUE THREAD

**Issue by pa345** [GenericMappingTools/gmt#7613]
I am trying to make a figure using subplot which has one column in Mollweide projection, and the second column in polar stereographic projection. Unfortunately the results are not satisfactory. My idea was to define a fixed size of each subplot in a 2x2 grid. Then I use one subplot command for the Mollweide projection -JW. Then I use a second subplot command for the stereographic -JG. Unfortunately the rows do not align correctly in the figure.

**Full script that generated the error**
```
#!/usr/bin/env bash

CBMAX="40"
CBSTEP="20"
INPUT_FILE="bin_median.txt"
EQMERIDIAN="180" # center equatorial view on 180 deg (12 MLT)

# subplot dimensions
SUBPLOT_WIDTH="3i"
SUBPLOT_HEIGHT="3i"

XNODES=$(cat $INPUT_FILE | grep "x nodes" | sed -e 's/.*x nodes: \([0-9]\+\)/\1/')
YNODES=$(cat $INPUT_FILE | grep "y nodes" | sed -e 's/.*y nodes: \([0-9]\+\)/\1/')

XYZFILE=$(mktemp)
GRDFILE=$(mktemp)

gmt set MAP_FRAME_TYPE plain
gmt makecpt -D -Cjet -T-${CBMAX}/${CBMAX} > t.cpt

gmt set MAP_TITLE_OFFSET -10p

gmt begin Fig_observations png
  gmt set FONT_TAG 16p,Times-Italic
  gmt set FONT_TITLE 16p,Helvetica

  gmt subplot begin 2x2 -Fs${SUBPLOT_WIDTH}/${SUBPLOT_HEIGHT} -JW${EQMERIDIAN}/18c -Rg -Bxg90 -Byg60 -A+o5p -M-0.5c/-0.5c

    # Br component
    cat ${INPUT_FILE} | grep -v "^#" | awk '{print $1,$2,$3}' > ${XYZFILE}
    gmt xyz2grd ${XYZFILE} -G${GRDFILE} -Rd -I${XNODES}+/${YNODES}+
    gmt subplot set 0,0 -A"B@-r@-"
    gmt grdimage ${GRDFILE} -Ct.cpt -B+t"Data"

    # Bt component
    cat ${INPUT_FILE} | grep -v "^#" | awk '{print $1,$2,$4}' > ${XYZFILE}
    gmt xyz2grd ${XYZFILE} -G${GRDFILE} -Rd -I${XNODES}+/${YNODES}+
    gmt subplot set 1,0 -A"B@-@~\161@~@-"
    gmt grdimage ${GRDFILE} -Ct.cpt

  gmt subplot end

  gmt subplot begin 2x2 -Fs${SUBPLOT_WIDTH}/${SUBPLOT_HEIGHT} -JG0/90/4c -Rg -Bxg90 -Byg60 -A+o5p -M-0.5c/-0.5c

    # Br component
    cat ${INPUT_FILE} | grep -v "^#" | awk '{print $1,$2,$3}' > ${XYZFILE}
    gmt xyz2grd ${XYZFILE} -G${GRDFILE} -Rd -I${XNODES}+/${YNODES}+
    gmt subplot set 0,1 -A"B@-r@-" -JG0/90/4c
    gmt grdimage ${GRDFILE} -Ct.cpt -B+t"Data"

    # Bt component
    cat ${INPUT_FILE} | grep -v "^#" | awk '{print $1,$2,$4}' > ${XYZFILE}
    gmt xyz2grd ${XYZFILE} -G${GRDFILE} -Rd -I${XNODES}+/${YNODES}+
    gmt subplot set 1,1 -A"B@-@~\161@~@-"
    gmt grdimage ${GRDFILE} -Ct.cpt

  gmt subplot end

  gmt colorbar -Ct.cpt -DJBC+w6i/0.5c -Bx${CBSTEP} -By+l"nT" -Y0.7c
  rm -f $XYZFILE $GRDFILE
gmt end show

```

The resulting figure is shown below. As you can see, the rows do not line up correctly. I would expect that since I specified a fixed 3i/3i size to subplot, each subplot would have the same size and the different panels would line up correctly in a grid.

![Fig_observations](https://github.com/GenericMappingTools/gmt/assets/6385941/0884ba69-0c5a-47c3-ac22-b68029a50278)

The input data file is here:

[bin_median.txt](https://github.com/GenericMappingTools/gmt/files/11963237/bin_median.txt)

**Actual outcome**

See figure - rows do not align correctly

**Expected outcome**

I want a 2x2 grid with each panel aligned as expected

**System information**

* Operating system:
* GMT version (`gmt --version`): 6.2.0

**Comment by joa-quim** [comment]
Closing this as not the place to ask for help.

**Comment by PaulWessel** [comment]
Please post such usage equations on the GMT [forum](https://forum.generic-mapping-tools.org) - GitHub is for bugs and feature requests etc.  Your case is lack of understanding of how subplot works so better to post to the forum and have more experienced users comments.  

Here is a stripped down example of your script without data.  I used **-F** modifiers to draw the lines.  You are basically plotting two subplots on top of each other, expecting some magic alignment despite different map scalings.

**Comment by PaulWessel** [comment]
Closing this issue - reiterate it on the forum after trying to align things.

**Comment by joa-quim** [comment]
It was posted in the forum already.
