### ISSUE TITLE
subplot -C  crashes GMT

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7626]
Although this happened to me by accident, the man page  says

-C[side]clearance

But if we do not specify a side, at line subplot#L454
```
n_errors += gmt_M_repeated_module_option (API, Ctrl->C.set[side]);
```
``side`` is used without being defined. Not sure what's the fix here.

**Comment by PaulWessel** [comment]
The intention was if no side then set all sides to given value but looks like I forgot. Does doc say anything?

**Comment by joa-quim** [comment]
" No side means all sides."

**Comment by joa-quim** [comment]
The fix was not good enough. Now ``-C0.25c`` raises
```
subplot [ERROR]: Option -C: 0.25c is not a valid side argument.
```

**Comment by joa-quim** [comment]
Fixed
