### ISSUE TITLE
-Joa: latitude injured. Looks like "♫"

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7627]
Here the "4" of the 42 latitude gets damaged.
```
gmt begin glencoe png
gmt basemap -Joa-87.74448235634011/42.11926875653921/57.9155192/1:2000000 -R-88/42/-87/43+r -B
gmt coast -W -Na -Glightbrown -Slightblue
gmt end show
```
![20230711T123644](https://github.com/GenericMappingTools/gmt/assets/1230959/c8a27d52-c72d-4c83-a3ef-4bc6d5148faf)
In fact it looks like a faded "♫".
GMT 6.4

**Comment by PaulWessel** [comment]
I get 42 (GMT master).  What gs version do you have? gs -version

**Comment by jidanni** [comment]
$ gs -version
GPL Ghostscript 10.01.2 (2023-06-21)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.

**Comment by PaulWessel** [comment]
OK, tjat is what I thought. gs tends to screw up something every few versions, unfortunately.  Bets if you can roll back to 9.56.1 since 10 is definitively broken.  Hence nothing we can do on the GMT side.

**Comment by jidanni** [comment]
I had better tell them at https://bugs.ghostscript.com/ .

**Comment by PaulWessel** [comment]
We will do it next week at the GMT summit in Oslo.  We need to give them a simple PostScript file and show what it looks like in 9.56.1 vs 10.*
