### ISSUE TITLE
gmt math: don't document -j

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7629]
Reading
https://docs.generic-mapping-tools.org/dev/gmtmath.html
the user sees
> see -j for calculation mode.

The user looks all over the page, including the Synopsis, but finds no
mention of "-j"
```
$ gmt math 2>&1|grep -c -- -j
0

$ gmt math -j
gmtmath [ERROR]: Unrecognized option -j
```

Therefore -j should not be documented on the gmt math page.

**Comment by joa-quim** [comment]
Haven't we talked this over and over to not open micro issues?

**-j** is a global option

https://docs.generic-mapping-tools.org/dev/gmt.html#distcalc-full

**Comment by jidanni** [comment]
$ gmt math -jg -o0 -T3.1/4.2/0.1 T =
gmtmath [ERROR]: Unrecognized option -j
