### ISSUE TITLE
grdlandmask with -A+aiS option

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#763]
**Description of the problem**

When issuing a grdlandmask command to create a southern hemisphere mask for Antarctica, and then making a world plot of test.grd, it seems that zones above -60° also have been masked.

Documentation indicates that all features north of 60°S should be skipped, but they're not.

**Full script that generated the error**

```
gmt grdlandmask -Gtest.grd -I0.01/0.01 -R-180/180/-90/0 -A+aiS -Df -r
```

**Full error message**

```
No error message - just erroneous results
```

**System information**

* Operating system: OSX 10.13.6
* Version of GMT: Version 6.0.0_ac8b8ab_2019.05.20 [64-bit] [8 cores]

**Comment by macpurity** [comment]
Example of map of test.grd

**Comment by macpurity** [comment]
It seems the option order matters! Does -A+aSi operates differently than -A+aiS? I say yes!

This command worked, as expected, doing a 10° wide (lon) slice in low resolution GHSSG:

gmt grdlandmask -Gtest.grd -I0.01/0.01 -R30/40/-90/0 -A+aSi -Dl -r

But, switching to a higher resolution gave segmentation fault errors:

gmt grdlandmask -Gtest.grd -I0.01/0.01 -R30/40/-90/0 -A+aSi -Dh -r
ERROR: Caught signal number 11 (Segmentation fault) at
0   libgmt.6.dylib                      0x0000000108e062e5 gmt_assemble_shore + 3557
1   ???                                 0x0000010000000001 0x0 + 1099511627777
Stack backtrace:
0   libgmt.6.dylib                      0x0000000108d7a2e4 sig_handler + 580
1   libsystem_platform.dylib            0x00007fff6f36ef5a _sigtramp + 26
2   ???                                 0x00007fffebe864a2 0x0 + 140737151263906
3   libgmt.6.dylib                      0x0000000108f92b9c GMT_grdlandmask + 5692
4   libgmt.6.dylib                      0x0000000108d94464 GMT_Call_Module + 628
5   gmt                                 0x0000000108d6bede main + 1070
6   libdyld.dylib                       0x00007fff6f060015 start + 1

Something is definitely amiss. The command, when switching +aSi to +aiS does NOT skip zones above -60°.

gmt grdlandmask -Gtest.grd -I0.01/0.01 -R30/40/-90/0 -A+aiS -Dl -r

**Comment by PaulWessel** [comment]
Thanks, I think the intent with the **+a** modifier was not to be used more than once.  If you see the usage message it says **+ag**|**i**|**s**|**S**], meaning just one of those.  Perhaps that is insufficient.  To clarify, you wish to use **+aS** (to skip anything BUT Antarctica (i.e., skip all data north of 60S) and for the Antarctica data we keep you wish to impose **+ai** (to use ice/water front for Antarctica coastline)?  I agree that should be a valid selection but our parsing of **-A** does not allow it.  Let me know if I understood you correctly and I will a look at the code to see what needs to change.

**Comment by macpurity** [comment]
You're on the right track, Paul. I need to create a mask for the iceshelf and don't want any masking north of 60S. This is why I have +aSi.

But following your suggestion and using only one +a option, this command fails on my system (with a segmentation fault):

gmt grdlandmask -Gtest.grd -I0.01/0.01 -R20/25/-90/0 -A+aS -Df -r

Does it work for you?

What I need to be able to do is create an Antarctica-only mask for 5° wide slices, using the full resolution GHSSG boundary, of the ice shelf edge. The command is currently incapable of doing it, regardless of specifying +aSi, or +aS.

Thanks - John

**Comment by PaulWessel** [comment]
That one crashes for me too.  So need to fix that and it is possibly related to the other issue.

**Comment by PaulWessel** [comment]
Not debugged this yet but this smaller area with intermediate resolution also crashes:

`grdlandmask -Gtest.grd -I1 -R20/25/-90/-70 -A+aS -Di
`

This will be how I celebrate Memorial Day.

**Comment by PaulWessel** [comment]
Fixed by PR #768 and will auto-close when that PR is merged.  It will now be allowed to use **-A+a**[**g**|**i**][**s**|**S**].

**Comment by PaulWessel** [comment]
Now merged - closing.

**Comment by macpurity** [comment]
Thank you, Paul! Works like a charm! Hope it didn't interfere with your Memorial Day Weekend too badly!
