### ISSUE TITLE
Use cmake instead of make in building instructions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#764]
**Description of the problem**

In [BUILDING.md](https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md), we use make commands 
```
make -j
make -j docs_man 
...
make -j install
```
to build the sources, documentations and running tests.

`make` is not cross-platform compatible. It works for cmake generators like "Unix Makefiles", but not for Ninja and Visual Studio.

I think we can change make to cmake, like
```
cmake --build .
cmake --build . --target docs_man
...
cmake --build . --target install
```

making the "make commands" platform independent.

**Comment by PaulWessel** [comment]
I just tried 

> cmake --build . --target install 

and it worked fine.  I agree with you.  Since I now use ninja I could not copy/paste the original make instructions if I wanted to.  I do think people copy/paste these so we should make sure they work across the board.
