### ISSUE TITLE
Placing directional map roses document: meaning drifts back and forth

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7661]
There is a lot of stuff on
https://docs.generic-mapping-tools.org/dev/cookbook/features.html#placing-dir-map-roses
that seems to need to be corrected:

> Map roses showing the cardinal directions of a map help the reader
orient themselves, especially for oblique projections where north-south
is not vertically aligned. However, these roses also have ornamental
value and can be used on any map projection. As for map ** scales **, a

Scales? That was the [previous section](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#placing-map-scales).
In this section we are talking about roses.

>directional map rose is added with basemap or coast and selected by the
-Td option. This option accepts the reference point where the map
rose’s anchor should be pinned. In addition to the required refpoint
and anchor arguments (and their standard modifiers discussed earlier)
there is one ** required ** and two optional modifiers. The required modifier
sets the ** si D e **:

SiDe or siZe?

>SiZe of map rose. Use +wsize to specify the full width and height of the rose. A 3 cm rose would require +w3c.

But +w isn't **required**. Looking at `gmt basemap` usage,
`-Td[g|j|J|n|x]refpoint[+f|F[level]][+jjustify][+l[w,e,s,n]][+odx[/dy]][+wwidth]`
+w is in brackets, and also I tested leaving it off, and `gmt basemap`
automatically used a default.

Yes siDe would refer to the siZe of one siDe, but maybe the intention
was to talk about what siDe of the map to put the rose on, which seems more required... But say, maybe there should be a default for that too...

> The next two modifiers are optional:

**Comment by PaulWessel** [comment]
Still at summit - will try to have a look at this over the weekend.

**Comment by joa-quim** [comment]
And de há-de a lit of a work trying to lower down the number of opened issues. Just not let grow again with minuscule issues (PRs are ok).

**Comment by PaulWessel** [comment]
Yes, syntax changed to be optional (in terms of  of map width as explain in the synopsis).  I am doing a PR to fix it.
