### ISSUE TITLE
psxyz gets crazzy with NaNs

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7672]
At lines with NaNs it goes nuts

```
gmt plot3d lixo3.dat -R-8/8/-8/8/-8/8 -JX14 -Ba -Bza -BWSZne -JZ8 -p140/30. -png lixo
```
![lixo](https://github.com/GenericMappingTools/gmt/assets/537321/b399a82b-0090-4f4d-9a7a-ecbf636c4a68)

[lixo3.zip](https://github.com/GenericMappingTools/gmt/files/12147937/lixo3.zip)

**Comment by joa-quim** [comment]
Debugging shows that NaNs have no special treatment so ``psl_ix|iy`` converts them to 0's. Where is this failing? In not breaking the input into two segments?

**Comment by PaulWessel** [comment]
Attach you data file and I can see

**Comment by joa-quim** [comment]
Data is attached.

**Comment by PaulWessel** [comment]
NaNs are used in binary files to indicate a segment header, not in ASCII

**Comment by joa-quim** [comment]
😮

**Comment by PaulWessel** [comment]
We spell it out in one of the appendix

**Comment by PaulWessel** [comment]
Read this [doc](https://docs.generic-mapping-tools.org/dev/cookbook/file-formats.html); perhaps we do have an issue?

**Comment by joa-quim** [comment]
Will check more later. When doing from Julia I pass in a dataset with NaNs and a single segment and the plot shows up correctly (line is broken at NaN)

**Comment by PaulWessel** [comment]
Actually, all works well, try:

`gmt convert lixo3.dat --IO_SEGMENT_MARKER=N,'>'`

**Comment by PaulWessel** [comment]
gmt plot3d lixo3.dat -R-8/8/-8/8/-8/8 -JX14 -Ba -Bza -BWSZne -JZ8 -p140/30. -png lixo --IO_SEGMENT_MARKER=N

![lixo](https://github.com/GenericMappingTools/gmt/assets/26473567/f68e88bc-01e6-4215-bd1c-4373f7004494)

**Comment by joa-quim** [comment]
Something weird must be going on. This all started when the data from my steel lite orbit screw in Julia because of the NaNs , now with a single line of NaNs it works well but I don’t see what’s the difference for the ASCII, CLI case that internally also has a single segment with that NaNs line. 

But today is very busy sardines day here so probably no time to investigate.
