### ISSUE TITLE
DVC files missing?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7678]
Something has happened to the DVC PostScript files.  I am unable to build the docs and get messages like this right away:

`ninja: error: '/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/doc/scripts/images/GMT_RGBchart.ps', needed by 'doc/rst/source/_images/GMT_RGBchart.pdf', missing and no known rule to make it`

Anyone who knows what to do?

**Comment by joa-quim** [comment]
And is it true or not?
I confess I don't understand how to use dvc. Tried to upload a missing PS  test as well as update 2 that were failing because of the new CPTs and failed miserably with incomprehensible error messages.

**Comment by PaulWessel** [comment]
Not sure, but my dvc dirs are now empty.  Need feedback probably from @maxrjones or @seisman .

**Comment by PaulWessel** [comment]
After fetch and status I see this

```
(base) pwessel@MacAttack-> dvc status
test/baseline/pslegend.dvc:                                                                                                             
	changed outs:
		not in cache:       test/baseline/pslegend
doc/scripts/images.dvc:
	changed outs:
		not in cache:       doc/scripts/images

```

**Comment by maxrjones** [comment]
I'll investigate this evening (ET) unless @seisman has time before then

**Comment by PaulWessel** [comment]
Any luck on this, @maxrjones ?  I am dying to build the docs again... :-)

**Comment by joa-quim** [comment]
But you got my zip files with the PSs?

**Comment by maxrjones** [comment]
https://dagshub.com/GenericMappingTools/gmt/src/master/doc/scripts/images shows the dir as missing from DAGsHub. The switch from present to absent corresponds to https://github.com/GenericMappingTools/gmt/commit/4187a073bff554407e0ce943fa8dc5d57ebd7086. I think that probable that the has no `dvc push` after those commits, which is needed for other people to be able to access those files.

I'll revert that commit and https://github.com/GenericMappingTools/gmt/commit/a3015f5eb86fade3906b931b9308a24db970ffd4 which is also missing so you have a fresh slate for updating any images in DVC, which I think it simpler than trying to make sure you have the right folder to push now.
