### ISSUE TITLE
core dumped on certain basemap -JOB invocation

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7684]
This will trigger core dump:

On chromebook linux:
```
gmt begin
gmt basemap -R-88/42/-87.9/42.1+r -JOB-88/42/-87.9/42.1/1i+v -B
gmt end
ERROR: Caught signal number 11 (Segmentation fault) at
/lib/aarch64-linux-gnu/libgmt.so.6(gmtlib_iobl+0x170)[0x76a183f070]
[0x63abb9d000]
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

And on
```
Linux 6.4.0
GMT   6.4.0
```
gmt begin; gmt basemap -R-88/42/-87.9/42.1+r -JOB-88/42/-87.9/42.1/1i+v -B; gmt end
gmt [WARNING]: GMT_COMPATIBILITY: Expects values from 6 to 6; reset to 6.
Error: /undefinedresult in --stringwidth--
Operand stack:
   PSL_AH1   0   (90\26000\234S)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1977   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--
Dictionary stack:
   --dict:775/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--   --dict:157/250(L)--
Current allocation mode is local
Current file position is 21707
psconvert [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/home/jidanni/.gmt/sessions/gmt_session.1159/gmt_0.ps-' 2> '/home/jidanni/.gmt/sessions/gmt_session.1159/psconvert_11791c.bb'] returned error 256.
end [ERROR]: Failed to call psconvert
end [ERROR]: gmtinit_process_figures returned error 79
```

**Comment by joa-quim** [comment]
This is what I get with GMTdev
```
gmt psbasemap -R-88/42/-87.9/42.1+r -JOB-88/42/-87.9/42.1/1i+v -B > lixo.ps
psbasemap [WARNING]: Your plot (WxH = nan x inf cm) placed at (2.54, 2.54 cm) may exceed your PS_MEDIA (WxH = 29.70 x 20.99 cm)
```
