### ISSUE TITLE
-L: refpoint is not required and will be placed automatically if not given. Please update docs.

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7696]
https://docs.generic-mapping-tools.org/dev/cookbook/features.html#placing-map-scales says refpoint is required.

https://docs.generic-mapping-tools.org/dev/basemap.html#l doesn't say that,
but still has refpoint outside of the brackets at
'-L[g|j|J|n|x]refpoint+wlength[e|f|k...]`

Anyway, the facts are: refpoint is not required, and and will be placed automatically if not given.

Confirm by running
```
$ gmt coast -W -Na -V -RUS.IL -JM5c -L+w50k -png x
```
Even -V shows us `Map scale origin selected to be 268.487/36.9711`:
```
coast [INFORMATION]: Derived from World Vector Shoreline, CIA WDB-II, and Atlas of the Cryosphere
coast [INFORMATION]: Processed by Paul Wessel and Walter H. F. Smith, 1994-2017
coast [INFORMATION]: Adding Borders...coast [INFORMATION]: Map scale origin selected to be 268.487/36.9711
end [INFORMATION]: Process GMT figure queue: 1 figures found
end [INFORMATION]: Processing GMT figure #0 [x png ]
```
and indeed the png file has the scale bar on it just fine.

P.S., above
```
coast [INFORMATION]: Adding Borders...coast [INFORMATION]: Map scale origin selected to be 268.487/36.9711
```
is somehow missing a newline between messages.

Anyway, please update the docs to now say that if no refpoint argument is given, the scale bar will be placed automatically. Thanks!

**Comment by joa-quim** [comment]
Sorry, does doesn't worth the time checking if that's always true (already consumed quite some time on this)
