### ISSUE TITLE
Negative map scales and backwards paper dimensions: bail out now

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7697]
I looked long and hard for what a negative map scale might mean.
https://en.wikipedia.org/wiki/Scale_(map)
https://en.wikipedia.org/wiki/Scale_(ratio)
https://en.wikipedia.org/wiki/Dimensionless_quantity
The closest I ever got was
https://imechanica.org/node/14068

I conclude that GMT should catch negative map scales,
```
$ gmt coast -W -Na -V -R-87/41/-86/42+r -JOb-86/41/-87/42/11c -Bafg -L+w50k -png x
...
coast [INFORMATION]: Map scale is -3.55278 km per cm or 1:-355278.
```
as an error, returning 'false' to the calling shell, with a message to
the user that s/he has used impossible input parameters.

It is very bad to just let it slide whereupon the user thinks everything
went OK until he notices he wasted a sheet of printer paper, or worse.

And, if somehow all this is correct, then the "-" should also
appear in the scale bar too. (A cartographic first :-( .)

By the way, sometimes the scale isn't negative, but bad parameters used
by the user still could be caught and a error message returned rather
than blindly letting it pass.

```
$ gmt mapproject -V -R-86/42/-87/41+r -JOb-86/41/-87/42/11c -W
...
mapproject [INFORMATION]: Reporting map width and height in cm
11      -37.5239116944
```

Here we are about to print a 11 x -37 centimeter map.

The only thing I could imagine this meaning is the printer machine,
rather than taking a fresh sheet from the tray, would suck back in a
previous sheet from the already printed pile, and print on that,
regardless of which other student it belonged too.

Anyway, here the user is lucky he used mapproject, and -V, to catch the
error. But GMT should catch it for him, without needing mapproject or
-V. Thanks.

Yes, you might say it is the user's own fault for making a mistake.
"Garbage in garbage out." But this is clearly a case where GMT could say
"the buck stops here. "

Anyway the negative map scale was produced by GMT, not the user.
The user gave bad input, and GMT went ahead and decided that it
will create a negative map scale (or backwards paper dimensions.)
GMT has the groundbreaking feature of negative map scales.
They either need to be documented for the cartography community to
read about. Or they should be caught before being allowed to exist.

**Comment by anbj** [comment]
> Here we are about to print a 11 x -37 centimeter map.
> 
> The only thing I could imagine this meaning is the printer machine, rather than taking a fresh sheet from the tray, would suck back in a previous sheet from the already printed pile, and print on that, regardless of which other student it belonged too.

I would pay money to see that.

**Comment by joa-quim** [comment]
Please close this or I will. Negative sizes is the way of reverting an axis sense.

**Comment by jidanni** [comment]
All I know is trying to input negative sizes and scales give
> -J parsing failure

So I don't know the best way to document what is going on.

**Comment by PaulWessel** [comment]
Looks like a but. It is only Cartesian projection we can give negative scales (as @joa-quim mentioned).  But -Jo etc shall be positive. Probably a bad mix of -R+r and -Jo I suspect.

**Comment by joa-quim** [comment]
> All I know is trying to input negative sizes and scales give…

So the solution is simple. Don’t do it.
