### ISSUE TITLE
Configure "Edit on GitHub"  link

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7703]
GitHub today has a bug.

In project.rst, please replace
```
.. include:: explain_distunits.rst_
```
with
```
Units
-----

For map distance unit, append *unit* **d** for arc degree, **m** for arc
minute, and **s** for arc second, or **e** for meter [Default unless stated otherwise], **f**
for foot, **k** for km, **M** for statute mile, **n** for nautical mile,
and **u** for US survey foot.
```
because the material about -j is not applicable to project.

I would create a pull request. Alas today GitHub has a bug.

Thanks.

Also there is a grammar error: 30 degree... needs an "s".

**Comment by jidanni** [comment]
All I want is to change one paragraph.
I don't know why I am also pulling in hundreds of other edits.
All I know is I clicked "Edit on GitHub" on
https://docs.generic-mapping-tools.org/dev/project.html

![20230805T041522](https://github.com/GenericMappingTools/gmt/assets/1230959/bf1d52dd-dfcf-46db-b76c-06a66acfd4e0)

**Comment by joa-quim** [comment]
Delete your fork and create a new one. I suspect that the problem is that you submitting from the master branch instead of from you local branch.

**Comment by jidanni** [comment]
But master is where that "Edit on GitHub" on https://docs.generic-mapping-tools.org/dev/project.html link now takes us:
https://github.com/GenericMappingTools/gmt/edit/master/doc/rst/source/project.rst .

I recall it used to go to 9.2, but now goes to master.

**Comment by seisman** [comment]
> All I want is to change one paragraph. I don't know why I am also pulling in hundreds of other edits. All I know is I clicked "Edit on GitHub" on https://docs.generic-mapping-tools.org/dev/project.html
> 
> ![20230805T041522](https://user-images.githubusercontent.com/1230959/258575495-bf1d52dd-dfcf-46db-b76c-06a66acfd4e0.jpg)

It's because you're comparing your PR branch (`jidanni-patch-999`) with your own master branch, and your master branch is hundreds of commits behind the GMT master branch. You should change the base branch to `GenericMappingTools:master` when opening PRs.

**Comment by jidanni** [comment]
> It's because you're comparing your PR branch (jidanni-patch-999) with your own master branch, and your master branch is hundreds of commits behind the GMT master branch. You should change the base branch to GenericMappingTools:master when opening PRs.

OK, I'm working on it!

So far looking for a way to change the base branch...
![20230807T034816](https://github.com/GenericMappingTools/gmt/assets/1230959/390ff7e0-1bef-4ee9-8557-545a2a13ad2d)
None there.

![20230807T034733](https://github.com/GenericMappingTools/gmt/assets/1230959/44c9a516-e6e0-47da-b561-73e4f33d5a60)

None there.

OK, I'll check settings. Hold on... Thanks.

**Comment by jidanni** [comment]
Hold on. This is all going to fail, due to the 
![20230807T040129](https://github.com/GenericMappingTools/gmt/assets/1230959/38b8ae34-12ce-4d8a-896a-62dc31eeeb2e)

**Comment by jidanni** [comment]
Apparently the new rules became available,
https://www.i-programmer.info/news/84-database/16484-github-repository-rules-now-generally-available.html
and were applied. But it turns out such rules have certain ramifications...

**Comment by PaulWessel** [comment]
Master has always been a protected branch, otherwise random people could merge stuff in without review

**Comment by jidanni** [comment]
All I know is me, Average Joe User, doesn't see this on e.g., https://github.com/OSGeo/PROJ
![20230807T043458](https://github.com/GenericMappingTools/gmt/assets/1230959/874b4312-cfba-47f6-ba61-7b8cb50fee05)
I though someone must have seen the new
![20230807T043859](https://github.com/GenericMappingTools/gmt/assets/1230959/e9df0717-b400-45a4-a9a8-b5d47fa10699)
buttons and clicked on it, but as you say, it was protected all along...

Anyway please do test of how the Average Joe User is supposed to continue submitting pull requests give the new underlying software in effect.

The wrong solution would be to elevate my privileges, because I'm super liable to screw things up.

**Comment by PaulWessel** [comment]
Maybe @seisman or @maxrjones have suggestions here? No, no elevation will occur.

**Comment by seisman** [comment]
> Anyway please do test of how the Average Joe User is supposed to continue submitting pull requests given the new underlying software in effect.
> 

![image](https://github.com/GenericMappingTools/gmt/assets/3974108/16a26330-d79c-41c1-bdf8-29164dd57602)
You just need to click the "Propose changes" button then you'll be redirected to a page like:
<img width="928" alt="image" src="https://github.com/GenericMappingTools/gmt/assets/3974108/94dc5028-a030-499e-976b-c2bc9d1e90b5">
Make sure that you select GenericMappingTools/master as the base branch.

**Comment by joa-quim** [comment]
> please do test of how the Average Joe User is supposed to continue submitting pull requests

I also find that Github is quite confuse to use when one do not have commit permissions, but **that is not our fault not under our control**.

**Comment by jidanni** [comment]
Ah ha, a vital step is to click "Compare against forks" in the upper right:
![20230808T034014](https://github.com/GenericMappingTools/gmt/assets/1230959/132fd862-a664-479f-b1fa-cd6571615d69)
Only then will we see "GenericMappingTools/master".
