### ISSUE TITLE
Cannot do mapproject -Abo

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7722]
https://docs.generic-mapping-tools.org/dev/mapproject.html says

> Use -Ao to get orientations (-90/90) rather than azimuths (0/360).

which was surely meant as a way to modify results.

Alas, as only the first letter after -A is read,
one can only use -Ao as an alias for -Afo.

There's no way to do -Abo.

As proof that only the first letter is read, -Afb should produce an
error, but doesn't.

Also as -A gives an error, then just -Ao should too. Or else -A should
be a documented alias for -Af. 

Version 6.4.

**Comment by joa-quim** [comment]
Not being possible doesn’t make it a bug. 

I’ve said this several times. We a tooooo long list of open issues that are, for several reasons, hard to address. We **don’t** want that list to grow with any than important issues.

**Comment by PaulWessel** [comment]
No bugs, just features. Says nowhere that -Abo is possible.  It is a, b, or o, and upper case for the ellipsoid.  For us to add a new letter (to "mean" backwards orientations) is not a priority.
