### ISSUE TITLE
grdview test failures

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7731]
I'm getting two test failures in grdview, ``denver`` and ``texture2_modern``. The last fails apparently because no -JZ seems to be applied and the ``denver`` fails like this. 
Me only?
Ah, and almost forgot. ``ex37`` crashed.
![denver-or8](https://github.com/GenericMappingTools/gmt/assets/537321/5d9a65da-eec5-4ac1-b884-046397a680f7)

**Comment by PaulWessel** [comment]
Sure.  I get several tutorial figs failing, Such as this with GDAL ? errors

```
ERROR 1: read: segment too long (2817) with max (54572) for codeblock 1 (p=1, b=2, r=2, c=0)

ERROR 1: Failed to decode.

ERROR 1: opj_get_decoded_tile() failed
ERROR 1: /Users/pwessel/.gmt/server/earth/earth_relief/earth_relief_30s_p/N30W105.earth_relief_30s_p.jp2, band 1: IReadBlock failed at X offset 0, Y offset 0: opj_get_decoded_tile() failed
ERROR 1: Stream too short

ERROR 1: opj_get_decoded_tile() failed
```

yet

ll /Users/pwessel/.gmt/server/earth/earth_relief/earth_relief_30s_p/N30W105.earth_relief_30s_p.jp2
ls: /Users/pwessel/.gmt/server/earth/earth_relief/earth_relief_30s_p/N30W105.earth_relief_30s_p.jp2: No such file or directory but the nc is there.

@Esteban82, you see anything odd running the tests?

This usually means the remote data did not get all tiles or similar.  I have a missing tile failure also on autoresgrid.sh

**Comment by joa-quim** [comment]
I see that one too. 
Regarding ex37 I think it was due to a careless access to -C by my grdimage PR. Fixed it but now test refuses to run saying it can't delete the test dir. Have a Win update pending so will reboot.

**Comment by joa-quim** [comment]
Wait, we have no way to voluntarily reproduce that East side wall visible in the figure, right?

![image](https://github.com/GenericMappingTools/gmt/assets/537321/0b0eecbc-0dff-406c-ab3d-8794dfe01d51)

**Comment by PaulWessel** [comment]
running denver.sh works fine for me.  I think you have a bad, missing, or jp2 vs nc (like me on others).

**Comment by joa-quim** [comment]
Yes, it was an incomplete grid download, but that gave rise to an interesting side effect of the colored side wall. It looks pretty nice and we should have a way to reproduce it.
