### ISSUE TITLE
Let gmt clear data be able to select an specific type of grid (not the whole planet).

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7738]
From the docs:

```
To only wipe your GMT server directory for Earth data, try:

gmt clear data=earth

```
I just discovered this module. But I think it would be great if I could select just a type of remote data set. 
I am thinking something like. For example, to be able to use this just to delete the earth_faa data set. 

`gmt clear data=earth_faa`

**Comment by PaulWessel** [comment]
I need this too so will have a look later today

**Comment by anbj** [comment]
This module was new to me too.

The description in [gmt](https://docs.generic-mapping-tools.org/dev/gmt.html#synopsis)-doc:

```
gmt clear items
Deletes current defaults, or the cache, data or sessions directories. Choose between defaults (deletes the current gmt.conf file used for the current modern session), cache (deletes the user’s cache directory and all of its content), data (deletes the user’s data download directory and all of its content), or all (does all of the above).
```

differs a bit from what is written in [clear](https://docs.generic-mapping-tools.org/dev/clear.html); e.g. **defaults** is not mentioned in the latter. I guess they both explain the same thing?

**Comment by anbj** [comment]
And maybe there should be a link from [gmt](https://docs.generic-mapping-tools.org/dev/gmt.html#synopsis)-doc to the modules own doc, if applicable. E.g. **clear**, **begin**, **figure**, etc.

**Comment by Esteban82** [comment]
Great. 

@PaulWessel another feature that I would like/need is a direct way to only delete my local version `gmt_data_server.txt`. 
Right now, this can only be accomplished it if I do `gmt clear data`. Not with `gmt clear data=earth`.

**Comment by PaulWessel** [comment]
Well, isn't this pretty direct?:

rm -f ~/.gmt/server/gmt_data_server.txt

**Comment by Esteban82** [comment]
> Well, isn't this pretty direct?:
> 
> rm -f ~/.gmt/server/gmt_data_server.txt

Yes, pretty direct.

**Comment by Esteban82** [comment]
I think that this was already done by #7740. I am closing it.
