### ISSUE TITLE
Make Cmake only rebuild relevant files

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7763]
* Based on [forum post](https://forum.generic-mapping-tools.org/t/cmake-builds-all-files/4202).
* Story: When doing a ``git pull``, resulting in, say, one updated doc file:

    ```
    One file changed, grdinfo.rst:

    Fast-forward
     doc/rst/source/grdinfo.rst | 5 +++++
     1 file changed, 5 insertions(+)
    ```

    Cmake will rebuild everything (~197 ‘modules’), even though the changed file does not affect any compiled code.
* Based on the excellent answer by @seisman, this does make sense; the git commit hash is used in creating the GMT version string, which again is used in a header file, propagating through "all" gmt code, causing Cmake to rebuild everything.
* Is there a more effective way to do this? That is, only rebuild modules/files/etc. that *actually* have been changed?

**Comment by joa-quim** [comment]
Not my experience. 

![image](https://github.com/GenericMappingTools/gmt/assets/537321/e94124f6-a77f-4d32-9ba5-b4e470db08ed)

**Comment by anbj** [comment]
Interesting. Why would this be different on Windows. I also use Ninja (if that makes a difference).

**Comment by seisman** [comment]
> Not my experience.
> 
> ![image](https://user-images.githubusercontent.com/537321/263534561-e94124f6-a77f-4d32-9ba5-b4e470db08ed.png)

I think it's because you didn't run `cmake .. -G Ninja` again, which will update the GMT version string and the `gmt_version.h` file.

**Comment by joa-quim** [comment]
Sure that I don’t do the cmake … step all the time. Actually I rarely need to do it.

**Comment by anbj** [comment]
I run ``cmake ..`` every time. Usually it takes a second or so - since nothing is changed. Does ``cmake ..`` know if it has to/should do the configure step 'from scratch'?

**Comment by joa-quim** [comment]
Don't know what ``cmake ...`` knows when it runs, but I know that if I delete ``CMakeCache.txt`` every thing is run as if first time. I do that when I want to force a clear state, but most of times that is not necessary so my rebuilds are almost instantaneous ... except when I swap between ``Release`` and ``Debug`` builds.

**Comment by anbj** [comment]
Yes, that's my experience as well. I thought ``cmake ..`` was smart enough to notice if things had changed, and then trigger a complete 're-run', but apparently not.

**Comment by joa-quim** [comment]
Close this?

**Comment by anbj** [comment]
Ok for me.
