### ISSUE TITLE
Rename Bookbook to Technical Reference

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7776]
**Description of the desired feature**

During the summit we discussed the organisation of the documentation, and one issue is that the file/link called CookBook isn't truthful.  A cookbook as we know it will contain lots of _recipes_, but those are actually in the illustration galleries.

I suggest we just rename the cookbook directory in the docs to techref and then update the word Cookbook (wherever it occurs, such as sidebar, links, etc.) to Technical Reference.

Ifi you agree, might there be an RST expert willing to do this PR? E.g. @GenericMappingTools/gmt-docs ?

**Comment by seisman** [comment]
> I suggest we just rename the cookbook directory in the docs to techref and then update the word Cookbook (wherever it occurs, such as sidebar, links, etc.) to Technical Reference.

I agree with the renaming. Instead of `techref`, what about renaming the cookbook directory to `reference` with the title "Technical Reference".
