### ISSUE TITLE
Handling m-dash in rst documentation

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#778]
Our RST documentation was basically translated from Latex and thus uses double-dashes -- to get a long m-dash (–).  However, sphinx presents those as double-dashes instead (e.g., https://www.generic-mapping-tools.org/gmt/latest/GMT_Docs.html#acknowledgments and see the dashes between version numbers 2.0--2.1 in line 5.
There is this suggestion (https://stackoverflow.com/questions/15258831/how-to-handle-two-dashes-in-rest) but perhaps we already have that set (?).  It seems the solution is to go through the rest files and replace -- with (on my Mac) Option-dash to get that ISO char.  Thoughts?

**Comment by seisman** [comment]
By default, sphinx will transform double-dash `--` to en-dash `–`. This always causes trouble for command line options, like `--PAR=value`. #378 was proposed to disable such transformation.

I tested with "Option-dash". It works for both HTML and PDF.

**Comment by PaulWessel** [comment]
OK, so I could just go through and find the places where it is used as an en-dash in various ranges then and insert the en-dash.

**Comment by seisman** [comment]
Closed by #782.
