### ISSUE TITLE
Make it work: pscontour -Ccolor1,color2 -I

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#78]
```
echo 1 2 3 | pscontour -JX12c/0 -Ba -R-3/3/-3/3 -Cred,green,blue -A2 -I -P -K > lixo.ps
pscontour [ERROR]: Syntax error -I option: Must specify a color palette table via -C
```
Regardless the non-sense of the above command, the refusing attitude is real. A command like this works only when the color info was passed via a file ``-Ccolor.cpt`` but not when we pass colors like the example. Did not check the code but there should be no reason why all forms of passing the color info will not work.

**Comment by PaulWessel** [comment]
Suspect the same is true in grdcontour. Note there are no z-values assigned here so what to contour? 0, 1, and 2?  What do you think is good behavior here?

**Comment by joa-quim** [comment]
Only place that ``z`` can come is from the selected contours them selfs, no? Hopefully that is not too late on the processing flow because we need to plot paint the image before the contours are drawn.

**Comment by PaulWessel** [comment]
Sorry, did not notice -A2.  So if your data goes from 0 to 20 and you use -A2 and -C sets three colors there is a problem.  I think we would need clean rules for how that may work, if at all.

**Comment by joa-quim** [comment]
I am assuming that we would interpolate the colors into the number of required intervals. Something like what happens in ``grdimage lixo.grd -Cred,green -JX10 > lixo.ps``, though this not an equivalent case.

**Comment by PaulWessel** [comment]
Let's define what should happen first. So in this case -C is either a master table (e.g., -Crainbow) or -Ccolor1,color2,...,colorn that defines a user "master" table, meaning the z-values in it are not the desired contour levels.  Two cases:

1. -A<inc> is given.  Then we calculate contour intervals from dataset min/max rounded to multiples of <inc> and sample the CPT accordingly.
2. No -A is given.  We then arbitrarily decide on 10 contours from min to max as the default contours.  Or perhaps we should compute a sensible rounded interval based on range? Nobody wants 7.37889, 9.3466, etc as the contours.

**Comment by PaulWessel** [comment]
BTW, this probably applies to grdcontour as well.

**Comment by joa-quim** [comment]
I'm not sure it worth the trouble of doing 2. If min/max is [0.3 0.7] it will be hard to figure out a good contour interval that does not have _many_ decimals.

**Comment by PaulWessel** [comment]
Well, we do this routinely with -Baf, but it is a bit different.  Here, usually a log10 of the range, floored, then raising 10 to that power gives a decent interval, in this case 0.1.  That gives n = 5 contours so we can check if n < 10 then double it.  So n = 10 and 0.05.  Not so bad for a default system when user dont care.

**Comment by PaulWessel** [comment]
Update: Both pscontour and grdcontour has this auto-contour settings.  However, if you give a master cpt or a list of colors then presumably you want to color the contours using those colors.  Thus the cpt will need to be resampled at the computer contour levels.  This is not implemented yet.
