### ISSUE TITLE
Unable to obtain remote file @earth_relief_01d_g.grd

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7804]
I am getting GMT.jl CI failures with

```
Error: [ERROR]: Unable to obtain remote file @earth_relief_01d_g.grd
```

**Comment by Esteban82** [comment]
Which server are you using? Portugal? Oceania?

**Comment by joa-quim** [comment]
It's not me, it's the CI machine so it has to be Oceania.

**Comment by Esteban82** [comment]
Is it trying to get the legacy files (i.e. in the top dir)?

**Comment by joa-quim** [comment]
Hmm, this was one of the VMs but reopening the PR again I see that other Ubuntu as well as the Mac had actually passed the test. So I'm closing this.
