### ISSUE TITLE
gmt math: only allow negative increments when +l is present

### ISSUE THREAD

**Issue by jidanni** [GenericMappingTools/gmt#7806]
https://docs.generic-mapping-tools.org/dev/gmtmath.html:
> For output values less frequently than every magnitude, use a negative integer inc:

>gmt math -o0 -T1e-4/1e4/-2+l T =

Other uses will lead to undefined results and should be restricted,

```
$ gmt math -T1/100/-1 T =
...
-94     -94
-95     -95
-96     -96
-97     -97
100     100
```

**Comment by Esteban82** [comment]
I'm not sure if I understood correctly. 

Why would someone ask for `gmt math -T1/100/-1 T =`? GMT users know (or should) that Garbage in, Garbage out.

**Comment by PaulWessel** [comment]
We cannot spend time preventing users doing -T8wehikj/9999:Kl/-123123123 if that causes SEGV, bad output, etc.

**Comment by jidanni** [comment]
I'm just saying since the program warns if the user uses zero as the increment, then if decrements are not allowed, then it should also warn about negatives, unless +l is present.

**Comment by PaulWessel** [comment]
See -I for decrementing
