### ISSUE TITLE
Tiny annotations on GMT_App_M_2.png

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7814]
I was looking at here (https://docs.generic-mapping-tools.org/dev/reference/cpts.html#labeled-and-non-equidistant-color-legends) and the annotations in the figure are now too small.

https://docs.generic-mapping-tools.org/dev/_images/GMT_App_M_2.png

**Comment by PaulWessel** [comment]
Shit, that is a new bug and clearly basing font size on the width of the vertical scales...  Will have to look.

**Comment by PaulWessel** [comment]
Confirmed, and I must have inadvertently updated this PS without being careful, so the test "passes".

**Comment by PaulWessel** [comment]
Fixed via #7816.
