### ISSUE TITLE
Regression on transparent GIF input via GDAL?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7825]
Noticed that the _transparent_gif.sh_ fails for me.  Comes that to this type of error:

```
gdalinfo /Users/pwessel/.gmt/cache/warning.gif
ERROR 4: `/Users/pwessel/.gmt/cache/warning.gif' not recognized as a supported file format.
gdalinfo failed - unable to open '/Users/pwessel/.gmt/cache/warning.gif'.
```

So GDAL does no support gif any more?  The gif file looks fine and opens in preview as well as posting here:

![warning](https://github.com/GenericMappingTools/gmt/assets/26473567/9bf64424-83a5-477c-b4ea-0a7fdf3c0fcd)

**Comment by PaulWessel** [comment]
BTW, this is
GDAL 3.7.2, released 2023/09/05 (debug build)

**Comment by PaulWessel** [comment]
But gdalinfo --formats does not output GIF as one of supported formats.  @joa-quim ?

**Comment by joa-quim** [comment]
Hmm, no problems here
```
C:\v\build>ctest -R transparent_gif
Test project C:/v/build
    Start 726: test/psimage/transparent_gif.sh
1/1 Test #726: test/psimage/transparent_gif.sh ...   Passed    1.74 sec
```

**Comment by PaulWessel** [comment]
Odd, macports or GDAL must have failed to enable gif support for some reason.  It is obviously not GMT since gdalinfo fails. So for you, this command

`gdalinfo --formats | grep GIF`

actually returns something?

**Comment by PaulWessel** [comment]
They forgot at mac ports to explicitly enable libgit. So hopefully a patch for macports in near future.

https://github.com/macports/macports-ports/pull/20530

**Comment by joa-quim** [comment]
Close this?

**Comment by PaulWessel** [comment]
Sure, I guess it will one day just work again after an update.

**Comment by joa-quim** [comment]
Still don't get what Remko&friends are doing here. I do not have to specify any git lib to have the git driver in my GDAL build.

**Comment by joa-quim** [comment]
Yes, it's `gif`, not `git`. I made the same mistake (but edited the post)

**Comment by remkos** [comment]
In any case, @PaulWessel already pointed out the PR is already in (but not yet merged): https://github.com/macports/macports-ports/pull/20530

I did some looking around on macports. This clearly cannot be blamed on any of the macports volunteers. Simply looks like gdal changed their default of compiling in GIF support from on to off when going from version 3.7.1.1 to version 3.7.2.
OK, you can say this was overlooked by the macports people.

**Comment by joa-quim** [comment]
Yep, maybe. I'm on
```
C:\v>gdalinfo --version
GDAL 3.8.0dev-7dec7e98b6-dirty, released 2023/09/01
```
and it still works for me.

**Comment by remkos** [comment]
PR https://github.com/macports/macports-ports/pull/20530 was just merged into master!

**Comment by PaulWessel** [comment]
I guess to see this now is to install macports via git?  I just do the usual `sudo port selfpldate; sudo port upgrade updated` and nothing new.

**Comment by PaulWessel** [comment]
Some patience was needed.  Now got 3.2.7_1 and all is well. Thanks!
