### ISSUE TITLE
Automatically select -Lgap layout in colobar if categorical CPT

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7830]
Currently, if you plot a color bar with a categorical CPT:

`gmt colorbar -Cclasscolor.cpt -Dx4i/4i+w5i+h -png a`

you will by default get this:

![a](https://github.com/GenericMappingTools/gmt/assets/26473567/216f8373-0aae-4809-acdd-fe8f80b06e85)

Not liking this, we usually decide to add **-L**_gap_:

`gmt colorbar -Cclasscolor.cpt -Dx4i/4i+w5i+h -L6p -png b`

![b](https://github.com/GenericMappingTools/gmt/assets/26473567/2232db58-07f0-4a98-8783-5004d22ed525)

But, since categories are never continuous we should automatically detect that and behave as if **-L** was set.  Changing this would be a "bug fix" in the sense we cannot secure backward compatibility.  Alternatively, we invent a modifier **+c** for **-L** that means "If CPT is categorical, auto-apply **-L**, else ignore it". For out one-liner plots we would certainly then add **-L+c** to the internal call. Also if gap is not set we should have a default, e.g., The `n-1 `gaps should add to 15% of the bar width (for example, here it is ~15%).

Comments?

**Comment by joa-quim** [comment]
Yes, agree and prefer the simpler solution that involves no other modifier.
