### ISSUE TITLE
-c option is missing in usages and documentations of all modern plotting modules

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#784]
All modern plotting modules don't print -c option in their usage and documentations.

**Comment by PaulWessel** [comment]
OK, I will fix this to avoid changing too much.

**Comment by PaulWessel** [comment]
This is also a time to reflect if **-c**_row_,_col_ should really be **-c**_row_/_col_ which is more typical GMT usage, no?

**Comment by seisman** [comment]
`gmt subplot set` use the `row,col` style:
```
gmt subplot set [ row,col ] [ -Afixedlabel] [ -Cside/clearance[u] ] [ -V[level] ]
```
It seems a little weird to have `gmt subplot set 1/3`.

**Comment by seisman** [comment]
After merging #785, there're still some issues.

Please check output of following commands:
- `gmt basemap -`:  unwanted ` ]` in -c option
- `gmt psbasemap -`: unwanted `[]` 
- `gmt sac -` and `gmt pssac -`: both print -O, -P, -K, -c options.

**Comment by PaulWessel** [comment]
A bit mystified by the gmt sac - case.  Running it in Xcode I come to the printing of the usage message and all the GMT_P_OPT variables show as being blank "" but yet the print statement produces -P, etc.  This seems to be specific to all PS producing modules in the supplements.  The core works fine, so something to do with extern char * settings.  I think I need to allocate these on the stack.  Will try that instead.

**Comment by PaulWessel** [comment]
OK, figured it out (had to re-learn how extern and declarations work...).  PR coming up soon.
