### ISSUE TITLE
Incorrect world file name when generating GeoTIFF file

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7844]
Issue first reported at https://github.com/GenericMappingTools/pygmt/pull/2698#discussion_r1335248729.
```
gmt psbasemap -R0/10/0/10 -JM10c -Baf > map.ps
gmt psconvert -A -P -W+g map.ps
```

The commands above produce two files: `map.tiff` and `map.pgw`. 

The world file `map.pgw` makes no sense here:

1. The output file is `.tiff`, so the expected world file extension should be `.tfw`, not `.pgw`
2. Since the GeoTIFF file already has the georeference information embedded, a world file seems useless. Perhaps we should delete the world file in this case?

**Comment by seisman** [comment]
Ping @PaulWessel and @joa-quim for comments on this issue so that we can take the same action in  the PyGMT side.

**Comment by PaulWessel** [comment]
Leaving this to @joa-quim since he wrote that module.

**Comment by seisman** [comment]
Ping @joa-quim

**Comment by joa-quim** [comment]
Yes, that `.pgw` is a mistake. But can't you just ignore it. Apparently it bothered nobody for ~15 years.

**Comment by seisman** [comment]
Better to fix it if it's a mistake.
