### ISSUE TITLE
Upgrade ex15

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#7846]
I was looking at [example 15](https://docs.generic-mapping-tools.org/dev/gallery/ex15.html#example-15) and I think it can be improved. 

### Bugs: 
In the docs it says: 
> Our lower left plot illustrates the results of gridding using a nearest neighbor technique ([nearneighbor](https://docs.generic-mapping-tools.org/dev/nearneighbor.html)) which is a local method: **No output is given where there are no data.** 

This is false (see figure). We need to add `-N4+m1` to `nearneighbor` or to modify the text. The default behaviour is "a quadrant search with 100% coverage, i.e., sectors = min_sectors = 4]". So, in the map, only the nodes surrounded by 4 data are highlighted. What should I do? Modify the script or the text?

### Important modification:
* Plot the data in at least one figure.
* Replace contours with images.

### Potencial new version

![ex15_new](https://github.com/GenericMappingTools/gmt/assets/17908951/fd42e37c-ba53-4685-b31a-dc4f96cea94e)

```
gmt begin ex15_new png
	#gmt convert @ship_15.txt -bo > ship.b
	region=$(gmt info ship.b -I1 -bi3d)
	gmt subplot begin 2x2 -M0.3c/0.1c -Fs7.5c/0 $region -JM7.5c -BWSne -T"Gridding with missing data"
		#   Raw nearest neighbor contouring
		gmt nearneighbor $region -I10m -S40k -Gnn.nc ship.b -bi
        gmt grdimage nn.nc -c1,0
        gmt plot ship.b -bi3d -Sc0.005c
		#gmt grdcontour ship.nc -JM -C250 -A1000 -Gd5c -c1,0
		#   Mask out area with no data using coastlines
	    gmt mask -I10m ship.b -T -bi3d -c1,1 -Gorange
        gmt plot ship.b -bi3d -Sc0.005c
		#gmt grdcontour ship.nc -C250 -L-8000/0 -A1000 -Gd5c
		#   Grid via surface but mask out area with no data
		gmt blockmedian ship.b -b3d > ship_10m.b
		gmt surface ship_10m.b -Gship.nc -bi
		gmt mask -I10m ship_10m.b -bi3d -c0,0
   		gmt grdimage ship.nc
		#gmt grdcontour ship.nc -C250 -A1000 -L-8000/0 -Gd5c
		gmt mask -C
		#   Clip data above sealevel then overlay land
		gmt grdclip ship.nc -Sa-1/NaN -Gship_clipped.nc
		gmt grdcontour ship_clipped.nc -C250 -A1000 -L-8000/0 -Gd5c -c0,1
        gmt grdimage ship_clipped.nc
		gmt coast -Ggray -Wthinnest
		gmt grdinfo -Cn -M ship.nc | gmt plot -Sa0.5c -Wthick -i10,11 -Gred
	gmt subplot end
gmt end show
```

**Comment by Esteban82** [comment]
Ok, then I make a PR. 

I have the doubt how to solve the bug. Do I modify the script to respect the text?

**Comment by PaulWessel** [comment]
At Indian restaurant in Kristiansand no laptop!

**Comment by Esteban82** [comment]
Ok, I have no rush. Enjoy!

**Comment by joa-quim** [comment]
Ask them for this. Fied Spinach leaves. Wonderful. 
![Uploading image.jpeg…]()

**Comment by Esteban82** [comment]
> Just edit the Tex, changing script leads to new PS for no good reason

I am not sure what file I have to modify. 
On github it says:

.. literalinclude:: /_verbatim/ex15.txt

Where I can find that file? Is it this fille (https://github.com/GenericMappingTools/gmt/blob/master/doc/examples/ex15/ex15.sh)?

**Comment by PaulWessel** [comment]
ex15.txt is built automatically by cmake from ex15.sh. Just dp the script and other things follow.

**Comment by PaulWessel** [comment]
I may be wrong here. See doc/rst/source/gallery/ex15.rst.

**Comment by Esteban82** [comment]
> ex15.txt is built automatically by cmake from ex15.sh. Just dp the script and other things follow.

Yes, I build the docs locally and the file ex15.txt is created with `cmake --build . --target docs_depends` from the .sh file. But in my local version, the figure wasn't modify. Is it done with dvc?

**Comment by PaulWessel** [comment]
If you updated doc/examples/ex15/ex15.sh to make an updated figure, then you run the tests and ex15 should fail since the new plot is compared to the old one in doc/examples/images.  After inspecting your new figure and liking it, you need to place that (from build/doc/examples/ex15 to doc/examples/images, then dvc add doc/examples/images, That creates a .gitfile somewhere so you need to then make a PR with the change (it will only show that file and possibly your script if that was not committed yet.  Then dvc push to update the fig in the DVC cloud.

**Comment by PaulWessel** [comment]
@Esteban82, if you hvae fixed/updated the script but having trouble with the fig and dvc then I could do that for you?

**Comment by Esteban82** [comment]
Ok. I was thinking of using the above script. I could make a PR if you want.

**Comment by PaulWessel** [comment]
Yep, looks good to me.
