### ISSUE TITLE
Remove the Sphinx themes/extensions from the repository?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7847]
Currently, we include the source codes of the Sphinx theme `sphinx_rtd_theme` (https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/themes/rtd) and some Sphinx extensions (https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/_extensions) in the GMT repository. 

I think the main reasons to include them in GMT are:

1. Developers/users don't have to install these Python packages to build the GMT documentation
2. They're under our control so the documentation won't suddenly break [Actually it still breaks sometimes due to changes in Sphinx].

However, including them in GMT also have some downsides:

1. The size of the GMT source tarballs increases by about 3 MB.
2. We have to maintain them manually (xref https://github.com/GenericMappingTools/gmt/issues/6010)
3. We can't use some good Sphinx extensions (e.g., https://sphinx-design.readthedocs.io/en/latest/) because their source codes are complicated or too big to be included in the repository

Since all the Sphinx packages can be installed using `pip` and `pip` itself is also easy to install,  
what about removing them from the GMT repository?

**Comment by seisman** [comment]
Comments? @PaulWessel @joa-quim @GenericMappingTools/gmt-docs

**Comment by PaulWessel** [comment]
I can live with that. Let's here form @joa-quim first.

**Comment by maxrjones** [comment]
I'd prefer for them to be removed

**Comment by joa-quim** [comment]
I guess I can live too with some more **pip**ings
