### ISSUE TITLE
MacOS Sonoma is here

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#7853]
Since Apple have released Sonoma it will for sure be many GMT users out there who will be on Sonoma and we better at least try it out. If any of you have made the move then perhaps we already know it is OK? If not I guess I will have to be the guinea pig.  We will need to know if there are any issues before we release GMT 6.5.

**Comment by anbj** [comment]
I’ve heard something about postscript not being supported on this..?

**Comment by joa-quim** [comment]
Yes, Postscript was totally irradicated.

**Comment by PaulWessel** [comment]
But that doesn’t bother me. I only make PS files when tracking bugs. All Apple has done is to yank some code so Preview cannot open PS files. Good reason to use modern mode

**Comment by PaulWessel** [comment]
Apple says this[This](https://support.apple.com/en-us/HT213250) .

**Comment by PaulWessel** [comment]
More careful story about Apple's changes related to [PostScript](https://forums.appleinsider.com/discussion/233763/sonoma-puts-the-last-nail-in-the-coffin-for-postscript-on-macos).

**Comment by joa-quim** [comment]
Yes, I read it in HackerNews

**Comment by anbj** [comment]
See also [A Postscript for Postscript in macOS](https://www.grc.com/sn/sn-941-notes.pdf) in [Security Now! #941 - 09-26-23](https://www.grc.com/securitynow.htm).

**Comment by PaulWessel** [comment]
Building, running, and testing master under Sonoma works fine, so we should not experience any release hiccups. But we should probably build the macOS installer on Ventura?

**Comment by PaulWessel** [comment]
IT is getting harder not to accidentally update macOS.  Do any of you have a Mac that runs Ventura in case we need to build an installer **not** on Sonoma?  I know Sonoma worked fine for me so no problem building, and I will try building on my Sonoma Mac and see if there are any issues installing that bundle on Ventura.  I have an Intel Mac in Hawaii but boy, it is almost impossible to socreenshare so I can click on some buttons to update Xcode....

**Comment by seisman** [comment]
I have Ventura, so I think I can check if the installer from you works fine on Ventura.

**Comment by PaulWessel** [comment]
OK,  Just updated to Sonoma and trying out the bundle  build.  It stops at 

```
build-release.sh: Running admin/gs-check.sh to ensure it passes our transparency test
build-release.sh: Ghostscript version 10.02.0 failed the test - install another gs
```

The files created for this in the build dir seems OK to me,  There are small font changes on the map frame but the diff png is black outside the frame?  I assume we could update the orig PNG in admin but wanted you to have a check first in case I am missing something.

**Comment by seisman** [comment]
I haven't upgraded to Sonoma yet, so don't see the warnings.

The warning message says:
> Please compile with -DACCELERATE_NEW_LAPACK to access the new lapack headers. [-Wdeprecated-declarations]

maybe we should follow the instructions.

**Comment by joa-quim** [comment]
Closing time?

**Comment by PaulWessel** [comment]
Yep, implemented as @seisman states.
