### ISSUE TITLE
@remotes confuse pstext

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7854]
This is a mild version that I could get that shows the root of the problem. The full case crashes GMT with this, used to work, GMT.jl example.

![image](https://github.com/GenericMappingTools/gmt/assets/537321/6fc05e74-6725-4e82-8595-4672ed957b6c)

Trying to reproduce it in CLI showed difficult but at least I could get this. It's trying to open that as a file. In the full crashing example it landed, don't know how, inside ``gmt_remote_no_resolution_given()``
```
pstext @:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60; @;;@::@:20.000000000000004:@;229/70/11;B@;;@::  -R -J -F+fHelvetica-Bold > lixo
pstext [ERROR]: File @:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60; was not found
pstext [ERROR]: Cannot find file @:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60;
pstext [ERROR]: Failed to create lock file c:\TMP/11;B@;;@::.download
pstext [ERROR]: Unable to obtain remote file @;;@::@:20.000000000000004:@;229/70/11;B@;;@::
```

Maybe the cure is just to check that for a remote/cache, second char in name must be a letter.

**Comment by PaulWessel** [comment]
Ok, will strengthen that check

**Comment by PaulWessel** [comment]
OK, **pstext** should not try to open @:..... as a _remote_ file since it is not.  But, you _are_ giving it a filename (in fact two files):

```
@:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60;
@;;@::@:20.000000000000004:@;229/70/11;B@;;@::
```

What do you expect **pstext** to do? It is given files so it will try to open them. Never has **pstext** taken a command-line argument and use that as _verbatim_ text, no?

**Comment by joa-quim** [comment]
I’m passing a single text string to be printed, not file names. The result should be what’s in the attached image. Well not exactly with the posted example because I trimmed it to only the letters “A B”.

**Comment by PaulWessel** [comment]
How are you passing your single string? Via a file name or memory file? You cannot give the string to pstext as a command argument.

**Comment by joa-quim** [comment]
I’m passing it as a GMTdataset

**Comment by joa-quim** [comment]
If just add a first character != @, the (full) example works again
```
text(rich("H", subscript("2"), greek("O")," is the ", smallcaps("formula")," for ",
     rich(underline("water"), color=:red, font="Helvetica", size=16)), x=1, y=1, frame=:none)

str = "A BEAUTIFUL RAINBOW";
C = makecpt(range=(1,length(str)+1,1));
fontsizes = 20 .+ 10 .* sin.(range(0, 3pi, length = length(str)));
rainbow_chars = map(enumerate(str)) do (i, c)
	rich("$c", color = GMT.arg2str(Tuple(round.(Int,C.colormap[i,:].*255))), size = fontsizes[i]);
end
text!("." * join(rainbow_chars), x=1, y=0.99, font="Helvetica-Bold", show=1)    # <== Let the string start with a "."
```
![GMTjl_j](https://github.com/GenericMappingTools/gmt/assets/537321/c4803151-139f-4150-91f5-9ce60eba2282)

**Comment by PaulWessel** [comment]
I get a plot with your A and B and no errors if I run

```
echo '@:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60; @;;@::@:20.000000000000004:@;229/70/11;B@;;@::' > t.txt
gmt pstext t.txt -R0/5/0/5 -JX6i -F+fHelvetica-Bold+cMC -P -B > t.ps
gmt psconvert -Tg t.ps -P -A
open t.png

```

**Comment by joa-quim** [comment]
But here you are passing a file name. The example above without the leading "." crashes GMT, and used to work (not sure when I run this example last time)

**Comment by PaulWessel** [comment]
Where is the leading "." = I don't see it? You mean the Julia case? If you pass as dataset then there will be no @remote stuff I think.  Obviously, you would have to debug and see what text "reads" from the dataset and how that might differ from reading from the file.  I don't think there has been any change to test or i/o recently.

**Comment by joa-quim** [comment]
Yes, the “.” Is in the Julia code.

**Comment by PaulWessel** [comment]
I see that _gmtinit_might_be_remotefile_ returns _true_ for a string like "@:20.0:@;70/134/251;A@;;@::@....." but that is only if such a thing is passed as a _file name_.  It cannot get there until one of the `opt->arg` contains that.  It would be easy report _false_ if the first two characters are one of the

```
       • @~ toggles between current font and Symbol font.
       • @%<no>% switches to font number <no>; @%% resets font.
       • @:<size>: switches font size; @:: resets font size.
       • @;<color>; switches font color; @;; resets font color.
       • @+ toggles between normal and superscript mode.
       • @- toggles between normal and subscript mode.
       • @# toggles between normal and Small Caps mode.
       • @_ toggles between normal and underlined text.
       • @!<char1><char2> makes one composite character.
       • @. prints the degree symbol.
       • @@ prints the @ sign itself.
       • @[<LaTeX expression>@[ may be used (except for -M).
```

combinations but who would name a file like that? So not sure what you want me to consider. My gut says this is something on the Julia side and related to the data set.  You gotta debug and see what the stuff contains.  If you write out a file from your Julia dataset, does it have all the chars?

**Comment by joa-quim** [comment]
The problem is that when I debug it landed directly inside ``gmt_remote_no_resolution_given()`` and the debugger showed me no stack trace so that I could trace the origin of the problem.

And checking batter, it's not a gdatset that is passed but instead this command
```
pstext @:20.0:@;56/38/107;A@;;@::@:25.0:@;66/75/182; @;;@::@:28.660254037844386:@;71/112/232;B@;;@::@:30.0:@;67/145/254;E@;;@::@:28.66025403784439:@;47/179/243;A@;;@::@:25.0:@;26/210/211;U@;;@::@:20.0:@;29/231/177;T@;;@::@:15.000000000000004:@;66/247/136;I@;;@::@:11.339745962155614:@;117/254/92;F@;;@::@:10.0:@;162/252/60;U@;;@::@:11.339745962155614:@;198/240/52;L@;;@::@:14.999999999999996:@;228/218/56; @;;@::@:19.999999999999996:@;248/191/57;R@;;@::@:25.0:@;254/157/47;A@;;@::@:28.660254037844382:@;249/118/29;I@;;@::@:30.0:@;235/80/14;N@;;@::@:28.66025403784439:@;213/52/6;B@;;@::@:25.0:@;183/29/2;O@;;@::@:20.000000000000004:@;145/11/1;W@;;@::  -R -J -F+fHelvetica-Bold
```

When I run
```
gmtmext('pstext @:20.0:@;56/38/107;A@;;@::@:25.0:@;66/75/182; @;;@::@:28.660254037844386:@;71/112/232;B@;;@::@:30.0:@;67/145/254;E@;;@::@:28.66025403784439:@;47/179/243;A@;;@::@:25.0:@;26/210/211;U@;;@::@:20.0:@;29/231/177;T@;;@::@:15.000000000000004:@;66/247/136;I@;;@::@:11.339745962155614:@;117/254/92;F@;;@::@:10.0:@;162/252/60;U@;;@::@:11.339745962155614:@;198/240/52;L@;;@::@:14.999999999999996:@;228/218/56; @;;@::@:19.999999999999996:@;248/191/57;R@;;@::@:25.0:@;254/157/47;A@;;@::@:28.660254037844382:@;249/118/29;I@;;@::@:30.0:@;235/80/14;N@;;@::@:28.66025403784439:@;213/52/6;B@;;@::@:25.0:@;183/29/2;O@;;@::@:20.000000000000004:@;145/11/1;W@;;@::  -R -J -F+fHelvetica-Bold > lixo.ps')
```
it crashes Matlab too.

**Comment by PaulWessel** [comment]
Well, that is expected.  If you give junk as command line arguments it will try to open them as files.  I can assure you running

`gmt pstext "This is my string"`

has never been a thing, and if that string contains a leading @ then it will probably end up in that function.  But that is user error.

**Comment by joa-quim** [comment]
You are probably right. I saw a place inside ``pstext.jl`` where it's failing to convert into dataset (as it should) because it only checks if first char is ``@``.
Anyway, GMT should catch this and not crash.

**Comment by joa-quim** [comment]
Solved in Julia with
```
elseif (cmd0 != "" && !isfile(cmd0) && (cmd0[1] != '@' || cmd0[1] == '@' && !isletter(cmd0[2])))
```
but there is still the crash.

**Comment by PaulWessel** [comment]
OK, I can add the `@<pstextcode>` check I mentioned so instead you will get file not found and not remote download stuff.

**Comment by PaulWessel** [comment]
You are sounding like Danni and Andreas in that GMT should not crash if fed complete junk. Stop feeding the junk. 

My fix for looking for pstext strings yields this:

```
gmt pstext '@:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60; @;;@::@:20.000000000000004:@;229/70/11;B@;;@::' -R0/5/0/5 -JX6i -F+fHelvetica-Bold+cMC -P -B > t.ps
gmt [ERROR]: File @:20.0:@;70/134/251;A@;;@::@:10.0:@;162/252/60; @;;@::@:20.000000000000004:@;229/70/11;B@;;@:: is not a file and looks like pstext strings.
```

and does not crash.

OK?

**Comment by joa-quim** [comment]
That doesn't crash for me neither. Possibly because the string is too short. But it does with the longer string.

> You are sounding like Danni and Andreas in that GMT should not crash if fed complete junk. 

I inspired them 😃 . The problem with the crashes is that they also kill the hosts (the externals in this case).

**Comment by joa-quim** [comment]
Yes the longer string as in the Matlab example I posted above. Don't know why the error produced is different here.

**Comment by anbj** [comment]
1. Ouch
2. @joa-quim is right - he once told me that any crash, pr. definition, is a bug.
3. I'm now wiser; "you can't enumerate badness".

**Comment by joa-quim** [comment]
[Fuzzy testing](https://en.wikipedia.org/wiki/Fuzzing) seeks specifically (but not uniquely) for crashes.
