### ISSUE TITLE
makecpt fails on small increments

### ISSUE THREAD

**Issue by zinphi** [GenericMappingTools/gmt#7856]
Small increments (<~1e-8) cause makecpt to fail with the message
```
makecpt [ERROR]: Option T: Increment is zero
```

Example that fails:
```
 gmt makecpt -D -Z -Cjet -T-1.59947e-08/1.59947e-08/3.554379945e-09 >test.cpt
```
Example that succeeds (previous times 10): 

```
 gmt makecpt -D -Z -Cjet -T-1.59947e-07/1.59947e-07/3.554379945e-08 >test.cpt
```

* Operating system: SLES 15.1 (kernel 4.12.14-197.108)
* GMT version: 6.4.0

**Comment by PaulWessel** [comment]
Reproduced here.  Will check for solution.  We have a macro called GMT_M_is_zero (x) that is a bit sloppy. There are places we may need to check for 1e-08 threshold and other places whereEPS is OK.
