### ISSUE TITLE
Output gmt info as one line per column and IO_COL_SEPARATOR

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#7914]
Maybe better suited in the forum.

Two things:

1:

Running gmt info on a file with many columns gives a mess:

```
$ gmt info file.csv -h10
fil.csv: N = 42355	<2023-07-30T06:37:01/2023-07-31T07:42:51>	<1690699021/1690789371>	<20/346.534>	<-3368.86/-2990.66>	<0.0439453125/359.983520508>	<-19.9291992188/14.1778564453>	<-29.5477294922/40.2099609375>	<8.48967399449/8.66961057298>	<74.4295589906/74.5174631942>	<29.6921/29.85915>	<1.2118/5.41505>	<22.0954/22.93595>	<-0.6564/-0.6159>	<0.22075/1.6631>	<224.5756/236.1767>	<61.58625/64.735>	<-15.77315/14.87905>	<34.92455/34.9322>	<1496.92015/1503.70325>	<-0.67035/-0.63605>	<4.79/6.22825>```
```

Suggestion: output one column on each line.
Pref. with a number indicating the column #:

```
$ gmt info file.csv -h10
file.csv: N = 42355
1: <2023-07-30T06:37:01/2023-07-31T07:42:51>
2: <1690699021/1690789371>
3: <20/346.534>
4: <-3368.86/-2990.66>
5: <0.0439453125/359.983520508>
6: <-19.9291992188/14.1778564453>
...
```

2:
I was **very** confused and surprised to see that gmt may use more than one ``IO_COL_SEPARATOR``:

```
$ cat 1 
30/07/2023 06:37:01,1690699021,20.0,-2990.66,208.3447265625
```

```
$ gmt info  1 
1: N = 1	<2023-07-30T00:00:00/2023-07-30T00:00:00>	<6.61694444444/6.61694444444>	<1690699021/1690699021>	<20/20>	<-2990.66/-2990.66>	<208.344726562/208.344726562>
```
"What the hell is the 6.61694444444/6.61694444444-range?"

```
$ gmt info  1 --IO_COL_SEPARATOR=comma
1: N = 1	<2023-07-30T00:00:00/2023-07-30T00:00:00>	<6.61694444444/6.61694444444>	<1690699021/1690699021>	<20/20>	<-2990.66/-2990.66>	<208.344726562/208.344726562>
```

GMT reads 30/07/2023  and makes it a date (which is correct), and then it finds a time, which gmt interprets as being a geographical coordiate (which is the converted to decimal degrees, 06:37:01 -> 6.61694444444).  These are separated with a **SPACE**, not a comma, which I specifically told GMT to use as the ``IO_COL_SEPARATOR`` (so implicit: **space** is not a col. sep).

Bug or feature?

**Comment by PaulWessel** [comment]
A timestamp is <date>T<clock>.

You cannot split a single coordinate into two columns. We would not split a longitude into an integer degree in one column and the remains in another, no?

I am aware that some data may come like that but that is not GMT’s fault. Awk time to repair the input.

**Comment by PaulWessel** [comment]
Column separator in GMT is white space (tab and space).

**Comment by PaulWessel** [comment]
As for one col per row, maybe a new gmt info feature.  E.g -N[+c]  where -N writes one col min/max per line and optional +c (clear) do not use <>/<> but min max?

**Comment by seisman** [comment]
> As for one col per row, maybe a new gmt info feature. E.g -N[+c] where -N writes one col min/max per line and optional +c (clear) do not use <>/<> but min max?

What's the use case for the one col per row output? I feel it's difficult to use in any programming languages.

**Comment by PaulWessel** [comment]
Maybe -N -C writes min max and without -C it writes <min>/<max>.

**Comment by PaulWessel** [comment]
I think @anbj just wants manageable output for files with too many columns. In a way like grdinfo-F which we added decades ago

**Comment by anbj** [comment]
Yes, the one col per row output is just to make things easier to analyse.
To me, this really hurts:

![Screenshot from 2023-10-16 13-07-27](https://github.com/GenericMappingTools/gmt/assets/29237824/3e6af2dc-23d2-40bb-8e64-920240bfd796)

Much better to have one line of info per col.

**Comment by anbj** [comment]
> Column separator in GMT is white space (tab and space).

Even if I give ``IO_COL_SEPARATOR=comma``?

**Comment by anbj** [comment]
The malformed **first field**, "30/07/2023 06:37:01" is stupid, totally agree on that.

* The problem is that even though I tell GMT to use comma as field sep., GMT treats this first field as two, since there is a space sep. the date and time.
* Since it's stupid, i don't want to use it. Hence I give GMT -i[columns I want to use], but, since GMT fudges up the column numbering (again, since the first field is interpreted as two), I rip out the last 5 hairs on my head.

Again, see what GMT is doing:
 This field: ``30/07/2023 06:37:01``, is output as ``<2023-07-30T00:00:00/2023-07-30T00:00:00>	<6.61694444444/6.61694444444>`` from ``gmt info``.

**Comment by PaulWessel** [comment]
Per man page it only affects output. Input handles white space, comma and semi-colon automatically.

**Comment by anbj** [comment]
Ah yes, I see that (now).. Thanks Paul. So if you hve a CSV file with commas and spaces, you're going to have a bad bad time.

**Comment by PaulWessel** [comment]
> The malformed **first field**, "30/07/2023 06:37:01" is stupid, totally agree on that.
> Again, see what GMT is doing: This field: `30/07/2023 06:37:01`, is output as `<2023-07-30T00:00:00/2023-07-30T00:00:00> <6.61694444444/6.61694444444>` from `gmt info`.

Given a column with date and another with what looks like geographic coordinate, what is gmt info supposed to do? Glue them together? This should apply to plot and blockmean etc too? No, of course not.  Bad input data puts an onus on the user, not us developers. :-)

**Comment by PaulWessel** [comment]
Yep.

**Comment by anbj** [comment]
> > The malformed **first field**, "30/07/2023 06:37:01" is stupid, totally agree on that.
> > Again, see what GMT is doing: This field: `30/07/2023 06:37:01`, is output as `<2023-07-30T00:00:00/2023-07-30T00:00:00> <6.61694444444/6.61694444444>` from `gmt info`.
> 
> Given a column with date and another with what looks like geographic coordinate, what is gmt info supposed to do? Glue them together? This should apply to plot and blockmean etc too? No, of course not. Bad input data puts an onus on the user, not us developers. :-)

Yes, totally agree. And, my mistake was to think that ``IO_COL_SEPARATOR`` controlled the input as well. Shame on me for not reading the docs.

Outputting gmt info stuff on one-line-per-column wasn't that stupid though..
