### ISSUE TITLE
grdfilter/dimfilter longopts problems

### ISSUE THREAD

**Issue by rbdavis** [GenericMappingTools/gmt#7919]
The review of the grdfilter and dimfilter longoptions resulted in the selection of an unfortunate **--distance** choice  for the **-D** options of those modules. **--distance** is already in use as a common-option longoption string for the **-j** option:

```
/* from src/gmt_common_longoptions.h */
    {   0, 'j', "distance",
                "e,f,g",                 "ellipsoidal,flatearth,spherical",
                "",                      "" },

```

I am restoring my original **--disttype** longoption string for now and submitting this as a new PR for further group review. Please check the gmt_common_longoptions.h file for potential conflicts when making future changes, thanks!

**Full script that generated the error**

```
# PASTE CODE HERE
```

**Full error message**

```
# PASTE ERROR MESSAGE HERE
```

**Actual outcome**

**Expected outcome**

**System information**

* Operating system:
* GMT version (`gmt --version`):

**Comment by seisman** [comment]
Closed by https://github.com/GenericMappingTools/gmt/pull/7923.
