### ISSUE TITLE
Title not shown with MAP_FRAME_TYPE inside

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#792]
With MAP_FRAME_TYPE=inside, the plot title is missing. 

**Full script that generated the error**

```
gmt basemap -JX10c/6c -R0/10/0/6 -Baf -BWSen+t"Title" --MAP_FRAME_TYPE=inside -png map
```

**Generated figure**

![image](https://user-images.githubusercontent.com/3974108/58447441-635c6d80-80d2-11e9-95ca-53ac4f365eee.png)

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_f5c8766_2019.05.27

**Comment by joa-quim** [comment]
Probably related to #499

**Comment by KristofKoch** [comment]
Might be due to the fact that `--MAP_FRAME_TYPE=inside` is (mainly?) intended for producing geo-tiffs? There a title would be a problem. I would consider this therefore normal behavior.

> The trouble with the -B option is that it creates a frame and very likely its annotations. That introduces pixels outside the map data extent, and therefore the map extents estimation will be wrong. To avoid this problem use --MAP_FRAME_TYPE=inside option which plots all annotations and ticks inside the image and therefore does not compromise the coordinate computations. 

_Source: [psconvert -W documentation](http://docs.generic-mapping-tools.org/latest/psconvert.html#w)_

**Comment by PaulWessel** [comment]
I am guessing @KristofKoch is correct, but there are other reasons for using inside ticks and labels than preparing geo-tiffs.  I will have a look.  If users specify a title then a title should be plotted.
