### ISSUE TITLE
README.TRIANGLE not copied when LICENSE_RESTRICTED is off

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#793]
**Description of the problem**

When LICENSE_RESTRICTED is off, src/README.TRIANGLE should be copied to share/doc/copying. However, currently it isn't.

At line 333 of src/CMakeLists.txt, `CMAKE_CURRENT_DIR` should be `CMAKE_CURRENT_SOURCE_DIR`.
https://github.com/GenericMappingTools/gmt/blob/940cdb919724360037c38c2c9d65a89702de8637/src/CMakeLists.txt#L329-L334

Beyond that, it seems the value of `GMT_EXTRA_LICENSE_FILES` is not accessible in `doc/CMakeLists.txt`, possibly caused by some variable scope rules.

**Comment by PaulWessel** [comment]
Not sure, this was all Florian Wobbe stuff.
