### ISSUE TITLE
longoption support for fitcircle

### ISSUE THREAD

**Issue by rbdavis** [GenericMappingTools/gmt#7944]
**Description of the desired feature**

longoption support for fitcircle

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by joa-quim** [comment]
Like Dongdong said, better not open these ref issues a stick to corresponding PR's only.

**Comment by rbdavis** [comment]
I specifically asked Paul about this and was instructed to open issues for the module_inc.h PRs (like this one) but not to open issues for the translation test PRs.
