### ISSUE TITLE
GMT_fill_curves is broken on Linux/Windows

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7957]
On Linux/Windows, it produces an image like this:

![GMT_fill_curves](https://github.com/GenericMappingTools/gmt/assets/3974108/5f699b3b-3b9c-4a8b-913e-821d19a5edea)

**Comment by PaulWessel** [comment]
Wasn't like that for me when I submitted that plot. Shit, wonder what happened. Just ran that script now:

![GMT_fill_curves](https://github.com/GenericMappingTools/gmt/assets/26473567/34fbf94b-8980-4bae-afb6-fb71816b9a6d)

**Comment by seisman** [comment]
Sorry, should be "Linux/Windows". It passes on macOS, for me locally and on CI.

**Comment by seisman** [comment]
Fixed by PR #7975.
