### ISSUE TITLE
No worldfile for EPS if -F is used

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#7976]
```
# Produce an example PS file
$ gmt psbasemap -R0/10/0/10 -JM10c -Baf > map.ps

# Call psconvert with -F option
$ gmt psconvert map.ps -Te -W -Fnewname      

# No .esw file is generated
$ ls
gmt.history  map.ps  newname.eps

# Without -Te, .esw is generated
$ gmt psconvert map.ps -Te -W          
$ ls                                                        
gmt.history  map.eps  map.esw  map.ps  newname.eps
```
All other formats like bmp, pdf work as expected.

`gmt --version`: 6.5.0_f30bd45_2023.10.20

**Comment by joa-quim** [comment]
Well, if any, the issue would be why there is a ``epw`` at all? Those are completely useless because nothing can use them.

**Comment by seisman** [comment]
So, a world file only makes sense for raster formats, including bmp, png, jpeg, ppm and tif, right?

**Comment by joa-quim** [comment]
Yes. World files are read by GDAL that cannot read PS.

**Comment by seisman** [comment]
Then we can give an error if a world file is requested for vector formats, or just do nothing and close this issue.

**Comment by joa-quim** [comment]
Just close it. It doesn't worth spending time on it.
