### ISSUE TITLE
Place legacy 4.5.18 install files on GitHub

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8023]
See this forum [post](https://forum.generic-mapping-tools.org/t/missing-gshhg-database-for-gmt-4-5-18/1835/3) and [here](https://forum.generic-mapping-tools.org/t/pscoast-exe-could-not-find-file-gshhg-full-resolution-shoreline/4400/4)  for background. While generally strongly not recommended, there are in fact a few who have no choice but getting GMT 4.5.18 installed so we should upgrade these from unsupported ftp to https on GitHub like the modern installers.

@seisman, it would be more efficient if you could get the files from `gmt/ancient` on the **gmtserver** and place these where they should go on GitHub rather than me messing things up and then having to ask for your cleanup help after the fact!

```
pwd
/export/gmtserver/gmt
ls -l ancient
total 177184
-rwxr-xr-x 1 pwessel gmt 19425040 Nov  8 23:45 gmt-4.5.18-pdf-win32.exe
-rw-r--r-- 1 pwessel gmt 39791396 Nov  8 23:45 gmt-4.5.18-src.tar.bz2
-rwxr-xr-x 1 pwessel gmt 32750860 Nov  8 23:45 gmt-4.5.18-win32.exe
-rwxr-xr-x 1 pwessel gmt 31888602 Nov  8 23:45 gmt-4.5.18-win64.exe
-rwxr-xr-x 1 pwessel gmt 57570441 Nov  8 23:45 gshhg-2.3.7-win32.exe

```

**Comment by seisman** [comment]
I have created a fake release https://github.com/GenericMappingTools/gmt/releases/tag/4.5.18 and uploaded these files as assets.

**Comment by PaulWessel** [comment]
Thanks!
