### ISSUE TITLE
filter1d man page has error?

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8029]
The **filter1d** documentation description adds

`For spatial series there is an option to compute along-track distances and use that as the independent variable for filtering.
`

But I do not see any such option.  This scheme (turning lon lat or x y into distances along a track) happens in **sample1d**.  I guess remove this comment and add a note somewhere with reference to **sample1d** instead?

**Comment by PaulWessel** [comment]
One of our examples says this

`gmt filter1d track.txt -Tk+a -E -Fg200 > smooth_track.txt`

But with some fake track.txt file I get

```
filter1d [ERROR]: Unable to decode  as a floating point number.
filter1d [ERROR]: Mode (=8) for distance function is unknown. Must be bug.
filter1d [ERROR]: Mode (=8) for distance function is unknown. Must be bug.
filter1d [ERROR]: Option T: Min value is NaN - cannot create array
gmt [ERROR]: Fatal error in filtering routine.
```

And GMT 4 does not have anything like -Tk either

**Comment by seisman** [comment]
> The **filter1d** documentation description adds
> 
> `For spatial series there is an option to compute along-track distances and use that as the independent variable for filtering. `

This sentence was initially added in https://github.com/GenericMappingTools/gmt/commit/664816be1e0357430426863d188abc4994dea683 to explain the new `-N` syntax `-Nc|[-|+]<unit>[+a]`, but it seems the related codes were deprecated in https://github.com/GenericMappingTools/gmt/commit/a3bc10c3458f20079bfcb456f9d10747b83fc96e and the docs were not updated.

**Comment by PaulWessel** [comment]
Hm, looks like the actual problem is that **-T** was not given an increment.  This works fine

`gmt filter1d track.txt -T2k+a -E -Fg200 > smooth_track.txt`

as the machinery for turning the rift two columns into a final columns with distances along track works as before. So I think it works but I can improve the error messages when a value is missing in **-T**.
