### ISSUE TITLE
Add a GMT default to configure default figure format in modern mode 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#803]
**Description of the desired feature**

In modern mode, if formats are not specified in `gmt begin` or `gmt figure`, the default figure format is PDF. It would be good to allow users to select the default figure format(s).

**Comment by PaulWessel** [comment]
So this is weighing the complications of adding yet another GMT defaults (GMT_PLOT_FORMAT = ps|pdf|png|PNG,...) versus having to add it each time a users does not want PDF but some other format.  It would not be too hard to add, but what does the rest of @GenericMappingTools/gmt-contributors think about this?

**Comment by joa-quim** [comment]
I tend to ignore gmt.conf altogether (always use the --PAR mechanism). Our conf list is already too big but on the other hand I understand that people might want .png by default, so I'm kind of neutral for this.

**Comment by seisman** [comment]
All modern-mode scripts in GMT repository have to generate figures in PS format, as we need PS files for testing. I'm OK with that. However, example scripts are included in rst documentations. Users may be confused why all GMT official examples uses PS rather than the default PDF format.

If the default figure format is configurable, then all example scripts can start with 
```
gmt begin ex01
```
We can set the default to ps to make tests happy. Users who copy, paste and run the example will get a PDF figure.

**Comment by PaulWessel** [comment]
OK, I will implement a GMT_GRAPHICS_FORMAT setting between now and Sunday.

**Comment by seisman** [comment]
@GenericMappingTools/core Any updates on this issue? 

IMHO, the GMT_GRAPHICS_FORMAT setting can make our documentations easier to read and should be implemented before 6.0.0 release.

**Comment by PaulWessel** [comment]
Not yet, busy with proposal, paper, fixing the problems you have pointed out in subplot, etc!
