### ISSUE TITLE
Eliminate PDF from the 6.0 build and packaging

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#805]
PDF documentation is a legacy from the past when we printed stuff.  Now it is a limitation since not everything that can be done in HTML translate to PDF.  It also adds bulk to the tarballs, etc.

The proposals is to remove all vestiges of PDF from the documentation and the CMake/build scripts.  Looking for comments from @GenericMappingTools/core here.

**Comment by seisman** [comment]
> PDF documentation is a legacy from the past when we printed stuff. 

As far as I know, there are still many users who prefer PDF documentations (printed or electronic), especially for people with slow internet connections.

> Now it is a limitation since not everything that can be done in HTML translate to PDF. 

Agree. We can focus on the HTML version, but at least should provide a PDF one. 

> It also adds bulk to the tarballs, etc.

GMT_Docs.pdf, GMT_Tutorials.pdf, GMT_API.pdf aren't included into the tarballs, right?

**Comment by joa-quim** [comment]
It would be nice that build docs didn't build by default the pdf versions of the figs nor the docs. As is, I always have to remember to delete all pdf's from the build dir before creating the Win installers.

**Comment by seisman** [comment]
> It would be nice that build docs didn't build by default the pdf versions of the figs nor the docs. As is, I always have to remember to delete all pdf's from the build dir before creating the Win installers.

Currently, `make docs_depends` always generate both PNG and PDF formats, which are used in HTML and PDF documentations, respectively. Maybe we can split `docs_depends` target into `docs_html_depends` and `docs_pdf_depends`.

**Comment by PaulWessel** [comment]
Yes, that is a good starting point.  It probably bogs down the CI to make both sets.

**Comment by seisman** [comment]
I remember we have decided to drop PDF documentations in the summit. Is it true? If so, I can make a PR to cleanup the PDF build.

**Comment by PaulWessel** [comment]
Yes, we decided to drop the PDF docs from 6.0.0 but retain then in 5.4.x in case we release an update.  Not sure if we will though.

**Comment by seisman** [comment]
Closed by #1312.
