### ISSUE TITLE
Wrong doi for mgd77 docs?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#8052]
In the page of [mgd77info](https://docs.generic-mapping-tools.org/latest/supplements/mgd77/mgd77info.html) and others there is this reference: 

Wessel, P., and Chandler, M. T., 2007, The mgd77 supplement to the Generic Mapping Tools, Comp. Geosci., 33(1), 62-75, https://doi.org/10.1023/A:1021744224009.

But the doi correspond to this article: 
Wessel, P. An Empirical Method for Optimal Robust Regional-Residual Separation of Geophysical Data. Mathematical Geology 30, 391–408 (1998). https://doi.org/10.1023/A:1021744224009

The doi for Wessel and Chandler is https://doi.org/10.1016/j.cageo.2006.05.006. 

The doi should be modified, right?

**Comment by PaulWessel** [comment]
Yes, definitely wrong
