### ISSUE TITLE
Be consistent wihen limits can be set to ±infinity

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8097]
We have a few modules (e.g., **gmtselect**, **grdcut**) that has a **-Z**_min_/_max_ type option.  If we want to disable _min_ or _max_ (i.e., have no limits or ±infinity) then we are asked in some places to use a hyphen and in other places use NaN.  My question to you are

1. Do we select **-**, which is a troublesome letter in options?
2. Do we select **NaN**, which we can easily detect even though it is not ±infinity which we dont parse for.

I think (2) is most sensible but we will of course honour the old syntax in a backwards compatible way.

**Comment by remkos** [comment]
From your options, I would go for options (2).

But in some of my own code (different project), I would allow things like
- `-Z/max`, meaning no lower bound specified; would be the same as setting min to NaN.
- `-Zmin/`, meaning no upper bound specified; would be the same as setting max to NaN.
- `-Z/`, meaning setting no lower nor upper bound; would be the same as setting both min and max to NaN.

**Comment by anbj** [comment]
I guess this also applies to e.g. **grdcontour**’s -L?
