### ISSUE TITLE
Bug with master cpt and hinge (-C+h)?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#8102]
I run this script where I set the hinge of the master cpt geo at 4000 but I got this. Is this ok? 

`gmt grdimage -RIT @earth_relief_06m.grd -png test -Cgeo+h4000`

![test](https://github.com/GenericMappingTools/gmt/assets/17908951/8f0d4eb2-73a4-4d63-90d9-0eaa2522b5e3)

**Comment by PaulWessel** [comment]
I think you must use gmt **makecpt** or **grd2cpt** to supply the hinge and get a new CPT that you want:

```
gmt makecpt -Cgeo+h4000 -T-5000/5000 > t.cpt
grdimage -RIT @earth_relief_06m.grd -png test -Ct.cpt
```

![test](https://github.com/GenericMappingTools/gmt/assets/26473567/7e520816-dbf2-4cf2-85cb-977d5d686cef)

Not sure how easy it is to implement this directly nor if we really want that?

**Comment by Esteban82** [comment]
Yes, I have use makecpt. 

But, I tought that this could be done automatically based on the docs of [grdimage -C](https://docs.generic-mapping-tools.org/latest/grdimage.html#c).

> If given a GMT Master soft-hinge CPT then you can enable the hinge at data value hinge [0] via +h, whereas for hard-hinge CPTs you can adjust the location of the hinge [0].

Also, I had the impression that in the past it was possible. I think @leouieda also had the same impression.

**Comment by leouieda** [comment]
Yes, in previous versions adding `-Cpolar+h` to grdimage for example would center the white on zero but recently this stopped happening. 

This script:

```bash
gmt begin cpt jpg
gmt grdimage @earth_relief_15s_p -RPT -Cpolar+h -Baf
gmt colorbar
gmt end show
```

Makes this in 6.4.0:
![cpt](https://github.com/GenericMappingTools/gmt/assets/290082/bf7b3d84-1eca-4dd5-8a08-3e075645e2f1)

And this in 6.3.0:
![cpt](https://github.com/GenericMappingTools/gmt/assets/290082/9944ff94-2110-424a-82ab-354d5e33e21a)

**Comment by PaulWessel** [comment]
Thanks @leouieda, will look into this tomorrow.  Must be a subtle small change that had larger consequences, and we probably do not have a test who would have alerted us.  Will make one from this.
