### ISSUE TITLE
Help needed with grdtrack and grdinterpolate man pages

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8113]
I've stared at those and the new file explain_lines.rst_  they include for the **-E** option, but that stuff is just not showing up in the HTML. Anyone with RST expertise that can see why? E.g., @GenericMappingTools/core ? @GenericMappingTools/gmt-docs ?

**Comment by joa-quim** [comment]
This has to be a RST bug. What it doesn't like is the paragraph _(3)  If |-C| is set ..._ after the include. But if I include a fake tag (`.. _-EE:`) before it like the example below then it works. It leaves an extra blank line but I guess wi'll have to live with it.

```
.. include:: explain_lines.rst_

.. _-EE:

    (3) If |-C| is set and *spacing* is given then that sampling scheme
    overrules any modifier set in |-E|.
```

**Comment by PaulWessel** [comment]
Thanks, I removed the (3) se -G for output grid since that is the same through grd* modules, and the (3) for **grdtrack** was actually placed in **-C** and I think I forgot to remove it.  So removing those dead ends fixes it.
