### ISSUE TITLE
grdimage -I breaks frame annotations.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#8115]
This one was really waiting for us to release 6.5 to then show up.

With **-I** it doesn't plot the annotations
```
grdimage @HI_topo_02.nc -R160/20/220/30+r -JOc190/25.5/292/69/12 -Ba -I -png lixo
```
![lixo](https://github.com/GenericMappingTools/gmt/assets/537321/5c8bb64e-d45a-4f41-9bd9-9be1fea3aec5)

**Comment by joa-quim** [comment]
The bug was introduced when I tried to reset more things in the API in function ``gmt_end_module()`` so that GMT.jl and GMTMEX do not inherit from previous commands. Namely, this line, gmt_init#L16638 is the culprit:

```
for (i = 0; i < 2; i++) gmt_set_column_type (GMT, GMT_IO, i, GMT_IS_UNKNOWN);	/* Must be told [or find out] what x/y are */
```

Why resetting the column type to `unknown` at the end of a module causes this bug?

**Comment by PaulWessel** [comment]
Odd, I'll have a look.

**Comment by joa-quim** [comment]
I guess that when `grdimage` calls `grdgradient`, that at the end resets the column type, is what fscrews the _intention_ of `grdimage` plotting the frame. But very odd indeed.

**Comment by PaulWessel** [comment]
OK I am at

`for (i = 2; i < GMT_MAX_COLUMNS; i++) gmt_set_column_type (GMT, GMT_IO, i, GMT_IS_FLOAT);	/* Other columns default to floats */`

Remind me, did you add this line?  I can see trouble with grdgradient doing this and then we are back in grdimage and suddenly it thinks we no longer have lon,lat?

**Comment by joa-quim** [comment]
Yes, I added it because in Julia previous knowledge of column type was breaking something (a posterior command).

**Comment by PaulWessel** [comment]
This gets tricky though.  You could put that inside an if (external) {} test but what might that do for Python.  Need to ask Dongdong to run the equivalent example and see if they are affected.

Ultimately, if this differs across the wrappers then the if-test would need to be Julia-specific and may more bits need to be set when calling GMT_Create_Session?

**Comment by joa-quim** [comment]
But maybe this is raising a more important issue. `gmt_end_module` isn't really a _end_ call all the times. Maybe we need a way to know if it's an _internal_ end, in which case probably many of the settings in that function, or the call in itself, should not be run.

**Comment by PaulWessel** [comment]
We do have that.  The GMT->hidden.func_level is set to **GMT_CONTROLLER** in gmt.c (0) and increases when the module runs.  So it would be 1. When **grdimage** calls **grdgradient** the latter should be 2, which it is,

**Comment by PaulWessel** [comment]
And then grdgradient returns it is back to 1 in grdimage.

**Comment by PaulWessel** [comment]
You could try to put an if (GMT->hidden.func_level == 1) {reset} and see if this works for you situation.

**Comment by joa-quim** [comment]
`func_level == 1` doesn't work but `func_level == 0` does. However, the enum `GMT_TOP_MODULE` = 1 so I don't know what `== 0` means.

**Comment by PaulWessel** [comment]
0 is gmt.c or your wrapper init that calls Create_Session. 1 is what module gmt.c calls via GMT_Call_Module; that is the top module.  I assume you mus do that somewhere. If that one calls another module then that is 2,

**Comment by joa-quim** [comment]
Then I'm even more confused because they all work (0 or > 1) except `== 1`, which is what should work. And when I mean _work_ I'm referring to CLI.
```
grdimage @HI_topo_02.nc -R160/20/220/30+r -JOc190/25.5/292/69/12 -Ba -I -png lixo
```

**Comment by joa-quim** [comment]
Debugging shows that when that line is hit after grdimage having called grdgradient  `func_level` is **1** and not **2**

**Comment by joa-quim** [comment]
I think the thing is: there is no `grdimage`. Only `gmt grdimage`, and that is level 0. `gmt grdimge -> grdgradient` is level 1. So, in fact my test for Julia should be `func_level == 0`. Now my doubt is if I should not put it at the top of the end_module function to prevent its execution on any level above 0.

**Comment by PaulWessel** [comment]
I don't know about this.  It was working fine (CLIP) before you make this change to reset things like _coltype_.  We cannot have this new bug in 6.5, so I suggest:

1. Add an if-test so that this only happens under GMT.jl

This means we have to add the **GMT_JULIA_WRAPPER** stuff so we can prevent things breaking the CLI.

OK?

**Comment by joa-quim** [comment]
Maybe a flag to detect which external can be useful in future but for this case, it only takes
```
if (GMT->hidden.func_level == 0)
```
that doesn't affect the CLI. I'll make a PR with it.

**Comment by PaulWessel** [comment]
FYI, I enclosed your duplicated reset section under if (GMT->parent->external) { } and the example above works again.  However, I then ran all tests and got 71 failures! Weird, but looking at some of them, e.g., ex02, I found that the original PS files were wrong.  Like the above case, ex02 has two images and only the geoid map has frame annotations while the topo has nothing.  The test image is correct but the PS is wrong.  I dont know how that could happen.  Did anyone (but me) add updated PS files to DVC after your branch was merged on October 9?  Pinging @seisman as well.

I will go ahead and add the three bit flags (via mode arg to GMT_Create_Session):

	 *   bit 5 (**GMT_MEX_WRAPPER**)  means we are using GMT API from GMT/MEX or GMT/Octave.
	 *   bit 6 (**GMT_JULIA_WRAPPER**)  means we are using GMT API from GMT.jl.
	 *   bit 7 (**GMT_PYTHON_WRAPPER**)  means we are using GMT API from PyGMT.

I will then change the test to

`if (GMT->parent->external & GMT_JULIA_WRAPPER )`  since I do not think PyGMT wants those reset, but we will find out about that once we can test.

I may add these macros as well since their use will be in the C API:

```
gmt_M_Mex_wrapper (API) (API->external & GMT_MEX_WRAPPER)
gmt_M_Julia_wrapper (API) (API->external & GMT_JULIA_WRAPPER)
gmt_M_Python_wrapper (API) (API->external & GMT_PYTHON_WRAPPER)
```

Once confirming that this restores original behavior for the CLI I will have to update those 71 PS originals in DVC...

**Comment by joa-quim** [comment]
That test wrapped under `if (GMT->parent->external & GMT_JULIA_WRAPPER )` would limit the failing to Julia only. The resetting of column types is not for this example but for other cases that I don't remember anymore when that is important.

**Comment by seisman** [comment]
> but looking at some of them, e.g., ex02, I found that the original PS files were wrong. Like the above case, ex02 has two images and only the geoid map has frame annotations while the topo has nothing. The test image is correct but the PS is wrong. I dont know how that could happen. Did anyone (but me) add updated PS files to DVC after your branch was merged on October 9?

The incorrect ex02.ps image was added in commit 7afacc0765971ab3560a2d1a8f27ee3230745a8a. Before this commit, it was correct.

**Comment by PaulWessel** [comment]
Update: Not 71 failures but 27 or so.  I forgot to set server to static...

**Comment by joa-quim** [comment]
I'm still a little worried about those levels. You say
```
#define GMT_TOP_MODULE	1	/* func_level of top-level module being called */
```
but what this issue has shown is that func_lvel = 1 means a module called by another module, so not TOP_MODULE.
I see for example in `gmtlib_create_palette`
```
PH->alloc_level = GMT->hidden.func_level;	/* Must be freed at this level. */
```
I have Heisenbug (crash) in GMT.jl that occurs when the Julia garbage man sometimes tries to free invalid memory. Broadly those occurrences seem to point to makecpt (but nothing sure). I wonder if those crashes are not originated somehow in the C side.

**Comment by PaulWessel** [comment]
No. grdgradient has level = 2 until things get overwritten in end_module and suddenly it is 1 even though it was called by grdimage (level = 1) who was called by gmt.c (level 0).
