### ISSUE TITLE
mgd77sniffer. Meaning of DC.

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#8139]
In [mgd7sniffer](https://docs.generic-mapping-tools.org/dev/supplements/mgd77/mgd77sniffer.html) I read 3 times the word "DC". I suspect that means something like a constant value but I am not very sure. I would like to know exactly what it means so I can make a PR to clarify it in the docs.

> Apply scale factor and DC adjustment to specified data field.
> 
> Grid comparison activates several additional error checks. (1) Re-weighted Least Squares Regression of ship versus grid data determines slope and DC shift, which when differing from expected 1 and 0, respectively, may indicate incorrectly scaled ship data, including incorrect units or instrument drift as well as erroneous gravity tie-in
>
> Information pertaining to an entire cruise, such as NCEI and survey institution identification codes, cruise examination time, two-way travel time corrector information, data precision warnings, as well as systematic scales, DC shifts and correlation coefficients from global grid comparisons are reported as E77 header information.

**Comment by PaulWessel** [comment]
DC shift is very much direct-current offsets...in other words a constant. Here are the better terms:

Apply scale factor and offset ...

...determines slope and interest ...

...systematic scales, constant offsets, and correlation...

**Comment by Esteban82** [comment]
Ok, great. I will make a PR.
