### ISSUE TITLE
Redesign GMT documentations

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#816]
**Description of the problem**

GMT documentation is using a pretty old RTD theme. Any special reason for this old theme? What about updating to the latest [sphinx_rtd_theme](https://github.com/rtfd/sphinx_rtd_theme), which is possibly the most popular sphinx theme.

**Comment by PaulWessel** [comment]
With GMT6 coming out real soon, seems very timely to change the look and feel of the docs.  Leo is working on a web landing page. What you think, @leouieda and @joa-quim?

**Comment by joa-quim** [comment]
Yes, let's do like women and relocate the furniture around the room.

**Comment by PaulWessel** [comment]
Spoken like a man who has endured an involuntary room rearrangement.

**Comment by joa-quim** [comment]
Well, haven't we all?
(mothers count too)

**Comment by leouieda** [comment]
This is more like a bachelor cleaning up the mess in the apartment so he can get a date because no respectable woman would want to live there.

**Comment by leouieda** [comment]
I agree with @seisman that we should update the theme while we're at it. At some point things are gonna stop working because the dependencies are too old.

**Comment by PaulWessel** [comment]
If this is just changing a setting or two in the conf.py.in then by all means give it a try now.

**Comment by seisman** [comment]
Closed by #1308.
