### ISSUE TITLE
pscoast -E doesn't respect the [-180 180] range

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#8183]
```
C:\v>pscoast -EPT -M | head
>  Portugal Segment 0
352.169736641   36.9916811582
352.162463643   36.9859504037
352.142558597   36.9748586207
...
```
This happens because in gmt_init#L9470 it **wrongly** selects the `GMT_IS_0_TO_P360_RANGE` branch
```
		if (GMT->common.R.wesn[XLO] < 0.0 && GMT->common.R.wesn[XHI] > 0.0)
			GMT->current.io.geo.range = GMT_IS_M180_TO_P180_RANGE;
		else
			GMT->current.io.geo.range = GMT_IS_0_TO_P360_RANGE;
```
and much later `gmt_lon_range_adjust (GMT->current.io.geo.range, &geo);	/* Adjust longitudes */`
put it in the [0 360] range.

I don't understand the logic of the `GMT->current.io.geo.range` setting. Shouldn't it simply be set after `GMT->current.setting.format_geo_out`?

**Comment by PaulWessel** [comment]
I suppose so. Feel free to mess with it, but hurry
