### ISSUE TITLE
Change name of Twitter

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8190]
**Description of the desired feature**

I believe name "Twitter" appears in many repos such as website and more.  Could someone who works on this go through and change to X? Do we have to have the annoying "(formerly Twitter)" there as well?

**Comment by joa-quim** [comment]
Why changing the name? Leave it as Twitter (I hate that "X" shit. Makes think on "Z")

**Comment by PaulWessel** [comment]
Fine, I am not volunteering anyway.

**Comment by seisman** [comment]
I wonder if we should also remove the Twitter icon from the website?

**Comment by PaulWessel** [comment]
Fine with me; Musk is getting a bit difficult to handle anyway.

**Comment by seisman** [comment]
Done in [6f04925be657ebad5759cb7ef6b5dc95987bee20.](https://github.com/GenericMappingTools/website/commit/6f04925be657ebad5759cb7ef6b5dc95987bee20)
