### ISSUE TITLE
grdimage docs link "Grid File Formats" to grdbarbs which has issues too.

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#8210]
https://docs.generic-mapping-tools.org/dev/grdimage.html

Sorry for such brief report but have to leave. Maybe someone can look at it before I can have time to try to fix it.

**Comment by PaulWessel** [comment]
Sorry, have no idea what you mean.  The word grdbarb does not appear in any core RSTs.

**Comment by joa-quim** [comment]
Yes, but the link is this

https://docs.generic-mapping-tools.org/dev/supplements/windbarbs/grdbarb.html#grd-inout-full

**Comment by PaulWessel** [comment]
Hm, can you fix this? If not, can you point out what is actually wrong - I dont get it.

**Comment by seisman** [comment]
Maybe the text in the red box?
<img width="1007" alt="image" src="https://github.com/GenericMappingTools/gmt/assets/3974108/192705aa-a271-475e-b3b7-857851d9caa1">

**Comment by PaulWessel** [comment]
Is this still an issue? Looks OK when I click

https://docs.generic-mapping-tools.org/dev/supplements/windbarbs/grdbarb.html#grd-inout-full

**Comment by joa-quim** [comment]
Issues were fixed, though it's still strange that we land in a supplement man page to see the `Grid File Formats` description.
