### ISSUE TITLE
coast: pattern filling for land/ocean has unexpected behavior

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#8217]
Minimal example:
```
gmt begin map png
gmt basemap -RAU -Baf
gmt grdimage @earth_relief_01d_p
gmt coast -Gp29
gmt end show
```

The output is:

![map](https://github.com/GenericMappingTools/gmt/assets/3974108/d9cb12a2-a2ba-4790-b3fc-e4c4a364662f)

For comparison, changing `-Gp29` to `-Glightred` gives:

![map](https://github.com/GenericMappingTools/gmt/assets/3974108/3f1da3cc-eff9-4226-9cda-2d6d6555c40f)

**Comment by seisman** [comment]
It also fails in GMT 6.4.

**Comment by PaulWessel** [comment]
Well. this line is the same in GMT 6.5 as in GMT 4!

`pscoast.c:	if (fill_in_use && !clobber_background) {	/* Force clobber when fill is used since our routine cannot deal with clipped fills */`

`fill_in_use` is true when there is a pattern.  Clearly, not looked at or thought about for > 1 decade, so have no answer other than the comments.

**Comment by seisman** [comment]
This line has existed since 12 years ago. So maybe it's a long-term bug.

**Comment by PaulWessel** [comment]
Not bug, feature :-(

**Comment by seisman** [comment]
OK. Here is a workaround:
```
gmt begin map png
gmt basemap -RAU -Baf
gmt grdimage @earth_relief_01d_p
gmt coast -G
gmt coast -Gp29
gmt clip -C
gmt end show
```

![map](https://github.com/GenericMappingTools/gmt/assets/3974108/210bb7ca-d0b9-4dc1-80b7-f7ae5b299eae)

**Comment by PaulWessel** [comment]
Great. Would you mind adding a sentence or two, e.g. Note: that explains this workaround?

**Comment by seisman** [comment]
I can't do it right now. So, please do it if you're available.

**Comment by PaulWessel** [comment]
Done in master.
