### ISSUE TITLE
Broken documentation link on INSTALL.md

### ISSUE THREAD

**Issue by pbcole** [GenericMappingTools/gmt#8247]
**Description of the problem**

Trying to follow instructions to install GMT.  

from: https://www.generic-mapping-tools.org/download/ link to "install guide" goes to https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md
INSTALL.md refers to https://docs.generic-mapping-tools.org/latest/install.html which gives a 404 error

**Actual outcome**

https://docs.generic-mapping-tools.org/latest/install.html returns a 404 error

**Expected outcome**

Either

- https://docs.generic-mapping-tools.org/latest/install.html should be present and displayed in browser
- Link from INSTALL.md should go to the correct location

**Comment by seisman** [comment]
Please refer to https://docs.generic-mapping-tools.org/dev/install.html now.

The https://docs.generic-mapping-tools.org/latest/install.html link will be online after we make the GMT 6.5.0 release.
