### ISSUE TITLE
Is FFTW ever found?

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#825]
I built latest FFTW (3.3.8) but our machine insists that 

```
-- Searching dependent libraries. This may take a few minutes...
-- Looking for fftwf_import_wisdom_from_filename
-- Looking for fftwf_import_wisdom_from_filename - not found
CMake Warning at cmake/modules/FindFFTW3.cmake:75 (message):
  FFTW library found, but it is either too old (<3.3) or statically-linked.
```
looking into ``FindFFTW3.cmake`` we see that it decides that based on the the outcome of
```
check_symbol_exists (fftwf_import_wisdom_from_filename fftw3.h FFTW3F_VERSION_RECENT)
```
grepping for ``fftwf_import_wisdom_from_filename`` I find it only in the .lib and .dll and nothing on source code. But grepping only for ``import_wisdom_from_filename`` I can see it in ``fftw3.h`` in an apparent undercover 
```
FFTW_CDECL X(import_wisdom_from_filename)(const char *filename);
```

It looks like our ``FindFFTW3.cmake`` is not able to do it's job.

**Comment by PaulWessel** [comment]
This is @ldldr territory I think.

**Comment by joa-quim** [comment]
This is awful. Ducking for ``FindFFTW3.cmake`` shows several and all different. Tried with this one (small)
https://github.com/KDE/labplot/blob/master/cmake/FindFFTW3.cmake
and it indeed found it (with some help), but now the building errors with things like
```
gmt_fft.c.obj : error LNK2019: unresolved external symbol fftwf_execute referenced in function fft_1d_fftwf
```
but I can see that that symbol is in fact in ``fftw3f.lib`` against which it was linked so why the hell does it complains?

**Comment by PaulWessel** [comment]
Not sure, maybe @seisman knows the magic?

**Comment by joa-quim** [comment]
Turns out that the simplest seems to be modifying that kine to
```
check_symbol_exists (import_wisdom_from_filename fftw3.h FFTW3F_VERSION_RECENT)
```
It now finds FFT and builds ... but still don't see fftw3 as a dependency of gmt.dll. Maybe it's a dynamic loading?
@leouieda what about linux? Does it work without this patch?

**Comment by joa-quim** [comment]
No. What really works is when I short-circuit the 
```
	check_symbol_exists (fftwf_import_wisdom_from_filename fftw3.h FFTW3F_VERSION_RECENT)
```
with
```
	set (FFTW3F_VERSION_RECENT TRUE)
```

**Comment by leouieda** [comment]
@joa-quim I never had it complain about that on my machines or CI.

**Comment by PaulWessel** [comment]
Sorry, cannot check since on OS X we use the Accelerate framework.

**Comment by joa-quim** [comment]
Yes, on Winbuntu the ''check_symbol_exists'' function works well too. Seems to be a problem with the Win cmake. @seisman can you please check what happened in your Win Conda builds?

**Comment by seisman** [comment]
It works for conda builds. Please check the build log https://dev.azure.com/GenericMappingTools/GMT/_build/results?buildId=579 (the last one).

**Comment by joa-quim** [comment]
Thanks, I see it.
WTF fails for me? The shit is that need to add a patch to FindFFTW3.cmake that does not interfere with the others.

**Comment by joa-quim** [comment]
Closing as bloody mysterious
