### ISSUE TITLE
imshow in Julia is now broken because of the pad

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#8254]
Plot is linear. Should not need any PAD.

```
julia> gmtwrite("lixo1.tif", rand(UInt8,32,32,3), driver=:GTiff)

julia> I = gmtread("lixo1.tif", img=true, band=[0 1 2]);

julia> imshow(I)
GMT [WARNING]: gmtapi_change_imagelayout: reordering function for case BRBa -> BRP not yet written. Doing nothing.
grdimage [ERROR]: gmt_img_project: Input image does not have sufficient (2) padding
ERROR: Something went wrong when calling the module. GMT error number = 79
```

**Comment by joa-quim** [comment]
Case is deeper. **2 bands**???
```
julia> I = gmtread("lixo1.tif", band=[0 1 2])
A GMTimage object with 2 bands of type UInt8
```

```
julia> I = gmtread("lixo.tif")
A GMTimage object with 3 bands of type UInt8
```
This case plots fine

**Comment by PaulWessel** [comment]
Please attach lixo1.tif so I can see.  Is it grayscale with transparency?

**Comment by joa-quim** [comment]
To get the file is just run the gmtwrite command that I posted.

**Comment by PaulWessel** [comment]
Give me a CLI grdimage command that crashes and I can debug.

**Comment by joa-quim** [comment]
You have to read the Julia messages.
```
julia> gmtwrite("lixo.tif", rand(UInt8,32,32,3), driver=:GTiff)

julia> I = gmtread("lixo.tif", img=true, band=[0 1 2])
A GMTimage object with 2 bands of type UInt8
Pixel node registration used
x_min: 0.5      x_max :32.5     x_inc :1.0      n_columns :32
y_min: 0.5      y_max :32.5     y_inc :1.0      n_rows :32
z_min: 0.0      z_max :255.0
Mem layout:     BRBa
```
Above the printing clearly says the image has only 2 bands.
```
julia> imshow(I)
GMT [WARNING]: gmtapi_change_imagelayout: reordering function for case BRBa -> BRP not yet written. Doing nothing.
grdimage [ERROR]: gmt_img_project: Input image does not have sufficient (2) padding
ERROR: Something went wrong when calling the module. GMT error number = 79
```

Tried to save that 2 bands image again, but some other shit gets in the middle.

```
julia> gmtwrite("lixo_2b.tiff", I,  driver=:GTiff)
GMT [WARNING]: gmtapi_change_imagelayout: reordering function for case BRBa -> BRP not yet written. Doing nothing.
gmtwrite [ERROR]: BRBa memory layout is not supported, for now only: T(op)C(ol)B(and) or TRP & BRP
gmtwrite (gmt_api.c:5147(gmtapi_export_image)): Unknown Error [lixo_2b.tiff]
[Session GMT (2)]: Error returned from GMT API: GMT_IMAGE_WRITE_ERROR (23)
[Session GMT (2)]: Error returned from GMT API: GMT_IMAGE_WRITE_ERROR (23)
[Session GMT (2)]: Error returned from GMT API: GMT_IMAGE_WRITE_ERROR (23)
ERROR: Something went wrong when calling the module. GMT error number = 23
```

**Comment by PaulWessel** [comment]
But I am not using Julia and just want a file from you that when read into GMT causes troubles. Is the problem only when using gmtread/gmtwrite and not when doing things in a module?

**Comment by PaulWessel** [comment]
I mean, if gmtread/write  insisted on there being pads then that is not right since there is no projection there?

**Comment by joa-quim** [comment]
I don't have one 2 bands file. I tried to create one above but it errored too. The problem is that grdimage is sending the image through the `if (Ctrl->D.active) { /* Must project the input image instead */` branch that calls
``if (gmt_img_project (GMT, I, Img_proj, false)) Return (GMT_RUNTIME_ERROR);	/* Now project the image onto the projected rectangle */``
and that requires a pad. But why projecting if the generated command was
```
grdimage  -JX15c/0 -n+a -R0.5/32.5/0.5/32.5 -D -P -K > c:\\TMP/GMTjl_j.ps
```

**Comment by PaulWessel** [comment]
OK, agree that projection makes no sense.  Will look after dinner (like you tell me so often!)

**Comment by joa-quim** [comment]
It's this GOTO
![image](https://github.com/GenericMappingTools/gmt/assets/537321/f1b2e84b-eb30-404c-bd84-66b2b1bc3c32)


>  (like you tell me so often!)

But never by this solar altitude.
