### ISSUE TITLE
Strange w/e/s/n return if selecting US

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8265]
In trying to make a fresh new US map from earth_relief I did

`gmt grdimage @earth_relief_02m -B -RUS -png map -Vi`

but found out (I have pruned some of the output) that we get 

```
gmt [INFORMATION]: United States
gmt [INFORMATION]: Region implied by DCW polygons is 172.436/-66.9489/18.9099/71.3907
```

This leads to stupid things like

```
grdimage [WARNING]: Your grid x's or longitudes appear to be outside the map region and will be skipped.
grdimage [WARNING]: No grid or image inside plot domain

```
I cannot believe nobody has tried this before and gotten stuck? This is bad enough for 6.5.1 perhaps...  I will see what is going on. Anyone remember any PR that tried to deal with region lately?

**Comment by Esteban82** [comment]
I think the problem is due to the region crosses the 180 longitute.

**Comment by PaulWessel** [comment]
Yes, but why would we format the west part positive in a -R string that must be continuous!

**Comment by PaulWessel** [comment]
@joa-quim, looks like we never tried a country that crosses dateline?  I'm now debugging and changing things when east < west but that is not enough as I think the tile coordinates in the filename get messed up.  Same with Russia, Fiji.  Those 3 cross the 180 medirian. Not the same as dateline which is a more crooked wiggly line.  We will need to add some checking here to avoid this problem once I understand where it now fails.

**Comment by PaulWessel** [comment]
Seems like this was dealt with - closing.

**Comment by Esteban82** [comment]
Was it fixed? I can't get the figure.

**Comment by PaulWessel** [comment]
No, strongly not.
