### ISSUE TITLE
-R is required in grdproject?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#8273]
```
gmt grdproject @earth_relief_01d_g -JH10c -Gtmp.nc
```
The above command used to work in GMT 6.4, but reports an error in GMT 6.5:
```
grdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R
```
but the documentation says:

> Specify the region of interest. You may ask to project only a subset of the grid by specifying a smaller input w/e/s/n region [Default is the region given by the grid file].

Then, why `-R` is required here?

**Comment by PaulWessel** [comment]
Vague memory says we did this to fix another issue.  Within last 1 year? Maybe you can find the commit and we can see what we were trying to fix.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/gmt/pull/7974

**Comment by joa-quim** [comment]
But what is the meaning of passing a `JH10c`? It works with `-Jh`

**Comment by seisman** [comment]
> But what is the meaning of passing a `JH10c`? It works with `-Jh`

I've never used this module, so I have no idea what `-JH10c` exactly does, but it's allowed and  also used in the test (https://github.com/GenericMappingTools/gmt/blob/master/test/grdproject/units.sh).

**Comment by PaulWessel** [comment]
Would like to find the commit the added this - are you able to help with that @seisman ?  My git skills are deteriorating... I am 95% sure we did this to fix another problem but cannot recall what that was.

**Comment by seisman** [comment]
It was added in this PR https://github.com/GenericMappingTools/gmt/pull/7974.

**Comment by seisman** [comment]
Closed by https://github.com/GenericMappingTools/gmt/pull/8286.
