### ISSUE TITLE
sample1d docs: small issues in desc of -A and -T

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#8291]
* [grdsample -A](https://docs.generic-mapping-tools.org/dev/sample1d.html#a): description of ``m`` and ``p``; shouldn't it say "**same as f**", and not "**same as +f**" - without the plus-sign? 

![1](https://github.com/GenericMappingTools/gmt/assets/29237824/30f67c39-fae7-4e55-8cec-c55f3b7d182e)

* If [-T](https://docs.generic-mapping-tools.org/dev/sample1d.html#t) is set, and [-A](https://docs.generic-mapping-tools.org/dev/sample1d.html#a) is not explicitly set, then ``-Af`` is *implicitly* set. ``-T`` does not mention this. I think it should.
E.g., these two commands give the same output:

       $ gmt sample1d -T1m file
       $ gmt sample1d -T1m file -Af

* I can fix this, if it needs to.

**Comment by PaulWessel** [comment]
You are right.  Please do.

**Comment by anbj** [comment]
Fixed in #8292.
