### ISSUE TITLE
gmt info outcome change with the seconds float point precision

### ISSUE THREAD

**Issue by MarceloBanik** [GenericMappingTools/gmt#8310]
**Description of the problem**
Changing the seconds float point precision will change the gmt info output from absolute calendar time to relative time.

**Full script that generated the error**

```
echo -e '2023-05-18T20:12:24.000000\n2023-05-18T23:05:09.000000' | gmt info -i0 -C
```
Changing the float point precision will return the expected outcome:
```
echo -e '2023-05-18T20:12:24.0000\n2023-05-18T23:05:09.0000' | gmt info -i0 -C
```

**Actual outcome**
1684440744      1684451109

**Expected outcome**
2023-05-18T20:12:24     2023-05-18T23:05:09

**System information**

* Operating system: Ubuntu 20.04.6 LTS
* GMT version (`gmt --version`): 6.5.0

**Comment by remkos** [comment]
Workaround in GMT 6.5 is to use **-fT**
```
$ echo -e '2023-05-18T20:12:24.000000\n2023-05-18T23:05:09.000000' | gmt info -i0 -fT -C
2023-05-18T20:12:24	2023-05-18T23:05:09
```
