### ISSUE TITLE
ps-insar deformation mapping using xyz2grd

### ISSUE THREAD

**Issue by DD-ZHAO** [GenericMappingTools/gmt#8317]
Hello, everyone. my requirement is to plot the deformation map generated by ps-insar on the relief map, the deformation map is a number of points, I use xyz2grd to plot the deformation field, but this command needs to specify -R and -I, my deformation field is a tilted projection, so I add +r after -R, and set -I to 0.001, my code is as follows.
<img width="604" alt="stamps代码" src="https://github.com/GenericMappingTools/gmt/assets/111511562/aff94e4a-50e1-4458-bfb9-ffc74d0e641c">
The area of the graph is a rectangle diagonal to the line joining the two corner points I specified, the area with no value is grey, not just the tilted deformation field. Also, my deformation field is discrete points and I don't think it makes sense to specify -I to generate the grid. My image is below.
![zuowufenlei](https://github.com/GenericMappingTools/gmt/assets/111511562/7a3c7492-b8e5-4e0c-b953-b7c76a998e02)
How do I change the command, or use a different one? Thank you very much for your attention!

**Comment by PaulWessel** [comment]
You are posting user questions on our GitHub issues page for bugs and feature requests.  Please stick to the Forum for such questions as they have nothing to do with GMT source code issues.
We dont know anything about ps-instar, and you pasted in an image of code rather than lines of code.  All wrong.

**Comment by DD-ZHAO** [comment]
> You are posting user questions on our GitHub issues page for bugs and feature requests. Please stick to the Forum for such questions as they have nothing to do with GMT source code issues.

Sorry,sir. I will stick this to the forum.
