### ISSUE TITLE
test/inset/inset-l2s.sh fails

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#8344]
The `test/inset/inset-l2s.sh` fails in the master branch, but I have no idea why it fails:

`inset-l2s-a.txt` and `inset-l2s-b.txt` have the same content and `fail` is 0 KB:
```
--l2stranstest -Cw25
--l2stranstest -D10/20/2/3+r+ui
--l2stranstest -Dg1/-0.5+w7
--l2stranstest -DjBR+jLT
--l2stranstest -DJBR+o1/2
--l2stranstest -Dn0/0 -Dx5/5
--l2stranstest -F+c10+gred+i4p/black
--l2stranstest -F+p2p+r1p+s1/2/gray
--l2stranstest -N -N
```

**Comment by joa-quim** [comment]
Stumbled on the same situation on Windows. Files are equal according to other diff program. And the `subplot-l2s.sh` fails for the same reason.
