### ISSUE TITLE
Cleaning old feature requests

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#8381]
Hi guys. As you know I'm always pushing into reducing the number of opened issues. Honestly, having 12 pages of issues is a nice way of not looking at all to any issue from 2'nd on pages. It happens that those pages have many feature requests that will ... hardly be addressed. 
But I'm not comfortable with drastically closing them, so I'm asking that each one of us that have feature requests open to consider whether it's not better to close them.

Joaquim

**Comment by Esteban82** [comment]
I agree. 

When we closed it, we could use the "Close as not planned". 

![image](https://github.com/GenericMappingTools/gmt/assets/17908951/c69f3910-66a0-4d73-92c4-b58613e0c3be)

**Comment by anbj** [comment]
What about closing all issues and starting with clean sheets? Issues will reappear, if they’re important and still relevant.

**Comment by joa-quim** [comment]
Issue reaper when we revisit the cause. I was thinking in closing first feature requests and leave the bug reports.

**Comment by joa-quim** [comment]
Ping

**Comment by joa-quim** [comment]
Another Ping.
