### ISSUE TITLE
grdcontour hanging

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#8387]
**grdcontour gets hung when fed a grid file that has values very close to zero, but not exactly zero.**

**Please see the post on the GMT forum page. Data and two-line script were posted there.**

**System information**

* Operating system: MacOS 13.6.4
* GMT version (`gmt --version`): 6.6.0_1443c0c_2024.02.26

**Comment by anbj** [comment]
Link to forum post with script that causes hang: https://forum.generic-mapping-tools.org/t/grdcontour-gets-hung/4697.

**Comment by seisman** [comment]
maybe related to https://github.com/GenericMappingTools/pygmt/issues/1927 and https://github.com/GenericMappingTools/gmt/issues/6738

**Comment by joa-quim** [comment]
Can you please try if my fix fixes it too?

**Comment by macpurity** [comment]
Joaquim, not sure if that was directed to me, but I updated GMT to 6.6.0_09d27ad_2024.03.03 and it still hangs on my system.

**Comment by joa-quim** [comment]
John, it was actually meant to Dongdong but meanwhile I checked that this fix also fixes #6738 so I'll be merging this soon.
To test it you need to build the branch, not from master.
