### ISSUE TITLE
Supporting Date/Time as Range of makecpt/psscale

### ISSUE THREAD

**Issue by jpesicek** [GenericMappingTools/gmt#839]
psscale does not produce proper annotations for datetime inputs.  See details here:
http://gmt.soest.hawaii.edu/issues/640#change-5085

**Comment by PaulWessel** [comment]
Thanks, I am testing something that seems to work so hopefully in a few minutes.

**Comment by PaulWessel** [comment]
Seems to work; see below.  Closing this issues, please reopen if you find any issues.

![bar](https://user-images.githubusercontent.com/26473567/58993782-396a1180-878a-11e9-9c9d-95b59d609d88.png)

**Comment by jpesicek** [comment]
can you provide the commands to make your scale? thanks

**Comment by PaulWessel** [comment]
```
gmt makecpt -T2017T/2018T/1o -Cjet > t.cpt
gmt colorbar -Ct.cpt -Dx4i/4i+w4i+h -Baf -P > t.ps
```

**Comment by PaulWessel** [comment]
Depending on what you want annotated you will need to see the rich set of units and FORMAT_DATE_MAP and FORMAT_CLOCK_MAP defaults, as specified for time axes in general.
