### ISSUE TITLE
Release of GMT 6.5.1 needed?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#8391]
I am working with Paul and Guillaume on an article about movies with GMT (**The Generic Mapping Tools and Animations for the Masses**). 

I think we will need a new GMT release (6.5.1) because I some issues (with 6.5) that I will try to fix myself (like #8209). And also becauses include some features that have already been done (like #8297).

What do you think?

I don't know is somelse is working on a paper that will need some new features or fixes. I know that @joa-quim is working on one.

**Comment by seisman** [comment]
Maybe even 6.6.0, although there are not many new features added. 

I expect that this release may take much longer than any previous releases, especially that Paul was the one that built the macOS bundle.

**Comment by Esteban82** [comment]
> Maybe even 6.6.0, although there are not many new features added.

Yes, probably. I update the scritp to GMT 6.5 for the paper about animations. So, I won't need this release soon.

I will close this issue.
