### ISSUE TITLE
Add CPTs from Scientific Colour-Maps

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#845]
[Scientific Colour-Maps](http://www.fabiocrameri.ch/colourmaps.php) added a few more CPTs recently. Do we need to add them as built-in CPTs before GMT 6 release?

**Comment by PaulWessel** [comment]
Yes, I think so.  I also no noticed that hawaii.cpt is not listed in makecpt output, so good to get them all in.  I remember I had to scale his files to fit our 0-1 or -1/1 scheme depending on hinge.

**Comment by seisman** [comment]
Closed by #848.
