### ISSUE TITLE
Tutorials for Bash and Julia: Missing links to sessions

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/gmt#8465]
**Description of the problem**
It seems like that the links to the sessions of the tutorials for Bash and Julia are no longer displayed in the GMT documentation.

The screenshots below are for Bash exemplary:

[**GMT 6.4.0**](https://docs.generic-mapping-tools.org/6.4/tutorial/bash/index.html):
![tut_bash_640](https://github.com/GenericMappingTools/gmt/assets/94163266/7b95a8ad-18b5-4149-a869-f37b3ffb3245)

[**GMT dev**](https://docs.generic-mapping-tools.org/dev/tutorial/bash/index.html):
![tut_bash_dev](https://github.com/GenericMappingTools/gmt/assets/94163266/4fdaf554-1272-4766-90f9-86642fd13e12)

**Comment by seisman** [comment]
Likely because we upgraded the Sphinx theme in https://github.com/GenericMappingTools/gmt/pull/8456.

**Comment by yvonnefroehlich** [comment]
> Likely because we upgraded the Sphinx theme in #8456.

As the links to the sections are already not displayed for GMT 6.5.0:

- https://docs.generic-mapping-tools.org/6.5/tutorial/bash/index.html
- https://docs.generic-mapping-tools.org/6.5/tutorial/julia/index.html

it must be something earlier. Maybe this is related to the changes in PR #7897:
https://github.com/GenericMappingTools/gmt/blob/e2592e1e58a115a34c7a30a0bad0d83a90a42cd0/doc/rst/source/tutorial/bash/index.rst?plain=1#L41-L49

I am not sure about the `:hidden:` The Sphinx docs says (please see https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html):

> You can also give a “hidden” option to the directive, like this:
```
.. toctree::
   :hidden:

   doc_1
   doc_2
```
> This will still notify Sphinx of the document hierarchy, but not insert links into the document at the location of the directive – this makes sense if you intend to insert these links yourself, in a different style, or in the HTML sidebar.

**Comment by seisman** [comment]
You're right. PR #8483 will fix it.
