### ISSUE TITLE
My last commit

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#8473]
I just committed directly to master by a mistake (didn't even know I was allowed to).
@seisman, problem? Revert? It's just a minor change in the gmt.conf docs.

Commit: https://github.com/GenericMappingTools/gmt/commit/0655aae2697b1bdbf70f32eff02e0f3782c0009f

**Comment by seisman** [comment]
The commit looks good in the master branch.

i will see if we can better protect the master branch

**Comment by anbj** [comment]
Thanks!

**Comment by seisman** [comment]
I've changed the master branch protection rules so that no one except @joa-quim and @seisman can push directly to the master branch.
