### ISSUE TITLE
Streamline the module usage for classic and modern mode

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#85]
When running in modern mode, all modules require an option to report the module's usage.  This is typically one of -?, -^, -+, -, or +. Otherwise they will attempt to run even if not given any options (this may lead to errors depending on the situation).  In classic mode most modules will report their usage if given no options, but a few will instead expect to run and wait for input.

To enforce the modern mode behavior across all module while retaining the existing classic behavior under classic mode I have introduced a new library function gmt_report_usage.  I have implemented it i the few functions that are a git different.  In the remaining modules all that needs to be done is to replace the two lines

	if (!options || options->option == GMT_OPT_USAGE) bailout (usage (API, GMT_USAGE));	/* Return the usage message */
	if (options->option == GMT_OPT_SYNOPSIS) bailout (usage (API, GMT_SYNOPSIS));	/* Return the synopsis */

with the new line

	if ((error = gmt_report_usage (API, options, 0, usage)) != GMT_NOERROR) bailout (error);	/* Give usage if requested */

It would be great to get some help on doing this to the ~130+ modules remaining. PS. If the two lines in a module differ in any way from the above then best to let me have a look.

**Comment by seisman** [comment]
@PaulWessel I think I can help with this issue by writing a small script.

**Comment by PaulWessel** [comment]
Thanks @seisman, I finished the last couple of modules and all tests that passed before still pass.  Closing this issue.
