### ISSUE TITLE
Figures dissapear in the documentation?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#8502]
I see this in the **dev version** on this link: https://docs.generic-mapping-tools.org/dev/reference/features.html#overview-and-the-gmt-conf-file. The figures are there in version 6.5

![image](https://github.com/GenericMappingTools/gmt/assets/17908951/f4a3c5f3-0dc5-4f84-ad3c-836417d1c9a1)

**Comment by seisman** [comment]
It's caused by a bug introduced in https://github.com/GenericMappingTools/gmt/pull/8481. Now fixed directly in the master branch.

**Comment by Esteban82** [comment]
Thanks seisman!
