### ISSUE TITLE
docs: correct url to use

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#8517]
* Do we have a better solutions for questions like this? Instead of creating new issues? Sorry..

I want to link to another page in the gmt docs.
What url should I use?
Full address, or relative? Other?

E.g.
```
`FORMAT_FLOAT_OUT <gmt.conf.html#term-FORMAT_FLOAT_OUT>`__
```

vs. 

```
`FORMAT_FLOAT_OUT <https://docs.generic-mapping-tools.org/dev/gmt.conf.html#term-FORMAT_FLOAT_OUT>`__
```

**Comment by seisman** [comment]
I think you can use:
```
:term:`FORMAT_FLOAT_OUT`
```

**Comment by anbj** [comment]
Thanks. what about when I have no ``:term:`` to refer to?

**Comment by seisman** [comment]
The `:term:` syntax is only for GMT defaults. For links to other files/targets, you need to use `:doc:` or `:ref:`. Better to read other ReST files for reference.

**Comment by anbj** [comment]
Thanks!
