### ISSUE TITLE
Allow per-test RMS threshold for plot comparisons

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#852]
**Ability to override default RMS setting given to GraphicsMagic**

The testing of our ~800 GMT scripts that make plots involve comparison between a saved original PostScript file and the one produced by the script.  We call _GraphicsMagick_ to make rasters of both and then compare them and compute a RMS difference.  If this difference exceeds the given threshold (set in CMake config as **GRAPHICSMAGICK_RMS**) the test fails, otherwise it passes.  Unfortunately, subtle differences between compilers and different OS yield slightly different plots even though there are no bugs.  For some plots these differences add up more than for others, resulting in false positives (i.e., failures that are not real failures).  These false positives makes it harder to detect new failures introduced by code changes.  We would like the ability to give an optional **GRAPHICSMAGICK_RMS** in some scripts and have that value used in the comparison.

Here is a potential solution to improve this situation:

1. Add a script-specific **GRAPHICSMAGICK_RMS** setting for false positive scripts to avoid seeing the flagged as failures
2. Add a flag **KNOWN_FAILURE** to scripts that we know fail so that they do not count towards the total failure when CI runs, since this masks any new failures
3. Modify gmtest.in to act on these optional variables accordingly.
4. Make an issue per known failure and write what we think the problem and potential solution may be so that contributors can have a look and possible fix the problem.

**Comment by seisman** [comment]
We now still have three failing tests on macOS:

- mgd77/test_cm4.sh (Failed)
- pscoast/pseudo.sh (Failed)
- psxy/antwrap.sh (Failed)

Can we add the flag KNOWN_FAILURE to the three scripts to make all tests "pass"?

**Comment by PaulWessel** [comment]
Yes, please do.

**Comment by joa-quim** [comment]
``pseudo.sh`` fails because some of the maps are not aligned. I see that it (correctly) uses ``cm`` so probably some bad conversion from inches. The best would be to fix this or just update the *original*

**Comment by seisman** [comment]
It seems this issue can be closed now.
