### ISSUE TITLE
Remote dataset moon relief: Only east side is plotted for resolution >= "05m" and gridline registration

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/gmt#8580]
**Description of the problem**

When plotting the remote dataset for the moon relief using a resolution equal or higher than `05m` and gridline registration only the east part is plotted. This is not the case for pixel registration and the other plenary remote datasets (Mars, Mercury, and Venus). For me, the issue occurs under Windows but not under Linux.
See also: https://forum.generic-mapping-tools.org/t/lunar-terrain/5304/17

```bash
gmt grdimage @moon_relief_06m_g -JN10c -BWSen -Ba -C@moon_relief.cpt -png moon_relief_06m_g
gmt grdimage @venus_relief_05m_g -JN10c -BWSen -Ba -C@venus_relief.cpt -png venus_relief_05m_g
``` 
| @moon_relief_06m_g | @venus_relief_05m_g |
| --- | --- |
| ![moon_relief_06m_g](https://github.com/user-attachments/assets/443fc3ae-6b44-45f2-a9c3-4a623ec4aaa4) |  ![venus_relief_05m_g](https://github.com/user-attachments/assets/d4477654-c3a2-470e-b446-c9e98f989fbe) |

```bash
gmt grdimage @moon_relief_05m_p -JN10c -BWSen -Ba -C@moon_relief.cpt -png moon_relief_05m_p
gmt grdimage @moon_relief_05m_g -JN10c -BWSen -Ba -C@moon_relief.cpt -png moon_relief_05m_g
```
| @moon_relief_05m_p | @moon_relief_05m_g |
| --- | --- |
| ![moon_relief_05m_p](https://github.com/user-attachments/assets/9e73c9c5-ecfa-4dec-aaef-9f52ba3eda2e) | ![moon_relief_05m_g](https://github.com/user-attachments/assets/f486a700-707d-4627-94c4-aca100a44d6f) |

**Output of -Vd**
[moon_relief_vd.txt](https://github.com/user-attachments/files/16981229/moon_relief_vd.txt)

**System information**

* Operating system: Windows | Linux
* GMT version (`gmt --version`): 6.5.0 | 6.4.0

**Comment by seisman** [comment]
Works for me on macOS, too.

**Comment by yvonnefroehlich** [comment]
So, after deleting all downloaded remote dataset data, running “gmt clear cache” (as suggested in the GMT forum), and restarting my laptop, it finally works correctly for me, and the moon relief is plotted completely for all resolutions and both registrations. Thanks for your suggestions and help! Thus, closing this issue.
