### ISSUE TITLE
Data server defaults to static not Oceania on MacOS

### ISSUE THREAD

**Issue by jwellhouse** [GenericMappingTools/gmt#8599]
I installed 6.5.0 on MacOS 12 via the gmt-6.5.0-darwin-x86_64.dmg bundle. In search of a clean install, I deleted everything in ~/.gmt

 I do not have a gmt.conf file in .gmt or anywhere else.

I then ran 

```
gmt get -Ddata=earth -I1m -N
```

which spit all sorts of errors. For example:
```
gmtget [NOTICE]: Remote data courtesy of GMT data server static [http://static.generic-mapping-tools.org]

gmtget [NOTICE]: Earth Seafloor Crustal Age (GTS12 timescale) at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of the 1m grid [Seton et al., 2020].
gmtget [NOTICE]:   -> Download grid file [126K]: earth_age_01d_g.grd
gmtget [ERROR]: Libcurl Error: HTTP response code said error
gmtget [ERROR]: Probably means @earth_age_01d_g.grd does not exist on the remote server
gmtget [ERROR]: Unable to obtain remote file @earth_age_01d_g.grd
```

In search of why it was using static, I tried

```
gmt get GMT_DATA_SERVER
static

echo $GMT_DATA_SERVER
<blank line>
```

Running 
```
gmt set GMT_DATA_SERVER sdsc-opentopography
gmt get -Ddata=earth -I1m -N
```

Works as expected. I therefore conclude that the default set in the MacOS x86 package is static not Oceania.
Thank you! 

MacOS 12
6.5.0   gmt-6.5.0-darwin-x86_64.dmg

**Comment by seisman** [comment]
Could you please run `gmt get -Ddata=earth -I1m -N -Vd` and post the full output?

**Comment by joa-quim** [comment]
Strange that no one has complained before. It looks like Paul had the server set to static when he built the .dmg
There is no point in keeping this issue open because there is nothing we can do to change that, and I don't know if we will even create .dmgs for future releases.
