### ISSUE TITLE
Cleanup vim settings in source codes

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#861]
**Description of the desired feature**

There is a vim-setting line at the end of all the CMakeLists.txt files and some other files, like
```
vim: textwidth=78 noexpandtab tabstop=2 softtabstop=2 shiftwidth=2
```

It seems useless and can be removed.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Yep, legacy of Florian, please remove.
