### ISSUE TITLE
make_dem.csh in GMT problem

### ISSUE THREAD

**Issue by Mojtaba0131** [GenericMappingTools/gmt#8614]
I have a problem about DEM download using built-in script make_dem.csh in GMT. When I run this script the following error occurs:

START: make_dem.csh

grdcut [ERROR]: Remote download is currently deactivated grdcut [ERROR]: Unable to obtain remote file @earth_relief_03s rm: cannot remove 'geoid_resamp.grd': No such file or directory

created dem.grd, heights relative to WGS84 ellipsoid

END: make_dem.csh

I would appreciate if you could help me handle this issue Thank you so much

**Comment by joa-quim** [comment]
HI, as Yvonne explained the issues is not the place to ask questions. Please repeat this at the forum.
