### ISSUE TITLE
Possible to change the name of gmt.conf and gmt.history?

### ISSUE THREAD

**Issue by marshallst** [GenericMappingTools/gmt#8618]
I was wondering if it is possible in GMT6.5.0 to change the name of gmt.conf and gmt.history to alternative names? I have played with environment variables in Ubuntu Linux (WSL1) and was able to change the location of these files, but not their names. For example
export GMT_TMPDIR="data/csv"
successfully changes the locations of gmt.conf and gmt.history

I am not sure if these are used by GMT, but I tried the following with no luck
export GMT_USER_CONFIG="data/csv/test.conf"
export GMT_HISTORY_FILE="data/csv/test.history"

The reason for this is that I am running GMT on a server and I am trying to avoid file collisions when multiple requests come in at nearly the same time, so I would like each instance of GMT to use an auto-generated custom name for gmt.conf and gmt.history.

If you have any tips or suggestions, that would be helpful.
-Scott

**Comment by Esteban82** [comment]
> The reason for this is that I am running GMT on a server and I am trying to avoid file collisions when multiple requests come in at nearly the same time, so I would like each instance of GMT to use an auto-generated custom name for gmt.conf and gmt.history.

This issue was also solve by the *[modern](https://docs.generic-mapping-tools.org/dev/reference/introduction.html#modern-and-classic-mode)* mode.

> The modern mode runs the entire workflow in a unique temporary directory, hence numerous scripts can execute simultaneously without interfering, and we can use the gmt.history information to automatically supply missing regions (-R) and projection (-J) arguments.


So, I think that I won't be possible to change the source code for this feature request.

**Comment by joa-quim** [comment]
Please (again) the issues is not the place to ask questions. Use the forum for that purpose.
