### ISSUE TITLE
Update for IGRF 14th generation

### ISSUE THREAD

**Issue by MarceloBanik** [GenericMappingTools/gmt#8634]
**Description of the desired feature**
The IGRF 14th generation was released (https://www.ngdc.noaa.gov/IAGA/vmod/coeffs/igrf14coeffs.txt)
It would be great if GMT updated their IGRF coefficients.

I implemented it after commit 6ccb32a60ff2926ff157eb6db0e1d5f647e48ed4 (see git.diff.igrf14.txt) and passed the same tests before the implementation.
[git.diff.igrf14.txt](https://github.com/user-attachments/files/17924195/git.diff.igrf14.txt)

**Are you willing to help implement and maintain this feature?** Yes/No
Yes. But I hope someone more used with the pull requests could apply the git.diff.igrf14.txt

**Comment by joa-quim** [comment]
Thanks Marcelo (I was being sloppy with this). PR #8635 is on its way to apply this patch.
