### ISSUE TITLE
possible bug when updated for IGRF 14th generation

### ISSUE THREAD

**Issue by MarceloBanik** [GenericMappingTools/gmt#8637]
**Description of the problem**
When I updated the mgd77.c, I forgot to correct the value of ll when date >= 2025.
The following git diff should fix it.
[git.diff.txt](https://github.com/user-attachments/files/17939799/git.diff.txt)

**Full script that generated the error**

```
$ echo "-40 -23 0" | gmt mgd77magref -A+t2030-01-01 -Frdihtxyz/0
```

**Actual outcome**
```
-40     -23     0       -23.6834085446  -45.1126921225  99247.1093732   140633.484713   90888.4135314   -39865.8375639  -99638.2873376
```

**Expected outcome**
```
-40     -23     0       -23.6146017145  -46.9950606818  15934.1328456   23361.7277194   14599.8192634   -6382.93561129  -17084.3124677
```
These values are compatible with the output from https://www.ngdc.noaa.gov/IAGA/vmod/pyIGRF14.zip

**System information**

* Operating system: Ubuntu 24.04.1 LTS
* GMT version (`gmt --version`): 6.6.0_0b2b696_2024.11.26

**Comment by joa-quim** [comment]
Done, thanks again.
