### ISSUE TITLE
Stop valgrind from reporting false positive memory leaks

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#866]
**Running valgrind is a valuable tool to find subtle memory leaks**

One can run all the 800+ tests under _valgrind_ by setting

`export VALGRID_ARGS="--track-origins=yes --leak-check=full"
`

before running `make check` (yes, this needs to be documented in the test dir somewhere).

However, we have one ugly section in the GMT code that is called by all modules that tricks _valgrind_ into thinking we have a memory leak, and hence we get > 8000 log files (one per module call!) with lots of identical hits, making it very hard to find any actual memory leaks.  The problem is this:

In _gmt_begin_module_sub_, we aim to make a clone of the entire `struct GMT_CTRL *GMT` structure.  This structure holds tons of stuff about GMT.  Most are stack variables, but there are lots of char * pointers to strings allocated by _strdup_ and similar.  Because life is short, we do the duplication this way:

1. Create a new GMT structure:

`	Csave = calloc (1U, sizeof (struct GMT_CTRL));
`

2, Copy over everything from GMT to Save:

`	gmt_M_memcpy (Csave, GMT, 1, struct GMT_CTRL);
`

This will include pointer addresses in GMT to allocated memory that we don't want to duplicate that way: We want to do a _strdup_ on the individual strings.

3. A bit later on we replace the bogus pointer addresses by allocating a copy:

`	Csave->session.GSHHGDIR = (GMT->session.GSHHGDIR) ? strdup (GMT->session.GSHHGDIR) : NULL;
` 

We then get _valgrind_ reports like this (there are thousands like it):

> ==20115== 59 bytes in 1 blocks are definitely lost in loss record 8 of 10
> ==20115==    at 0x4C2FE56: malloc (vg_replace_malloc.c:299)
> ==20115==    by 0x59339B9: strdup (strdup.c:42)
> ==20115==    by 0x5006BBF: gmt_begin_module_sub (gmt_init.c:11384)
> ==20115==    by 0x500D43E: gmt_init_module (gmt_init.c:12504)
> ==20115==    by 0x52C0A51: GMT_psscale (psscale.c:1531)
> ==20115==    by 0x4EAA0DB: GMT_Call_Module (gmt_api.c:10019)
> ==20115==    by 0x109354: main (gmt.c:124)

where this sequence refers to the strdup call listed in 3.  It does this because it sees that `Csave->session.GSHHGDIR` is not NULL (we lamely copied over the address from GMT to Csave in step 2), so assigning something else to it means we are "loosing" that pointer to memory and hence a leak.  _Valgrind_ does not know that GMT is also pointing to that same memory so nothing is lost, and gives these reports.

One solution is likely to _not_ use that _memcpy_ in 2. That would mean we need to do individual assignments for all the stack variables (e.g., `Csave->session.n_user_media = GMT->session.n_user_media;`) and then do the assignments in 3.  The problem is there are hundreds of these assignments so manually doing it is no joy and prone to bugs.  My only solution seems to be to write a program that reads the STRUCT_GMT definition and writes the assignment code to an include file, and have CMake create this file as part of the config.  That way, if we add a new variable to the GMT structure somewhere, the copy code is correctly updated.

I would be happy for comments and suggestions on this, especially if you see a better way!  I forgot to add that valgrid does not run on macOS.

**Comment by joa-quim** [comment]
But if it's only the pointer that is _lost_ why Valgrind reports a lost of 59 bytes instead of only 8?
Anyway, Coverity does not report any issue with this.

One thing I didn't understand in your suggested solution. Would it imply that cmake have to compile that program? I'm asking because that would not work for me. Don't know why but my laptop with 4 VS compiler versions (plus traces of some others) gives me a obscure library missing error when compiling programs in middle of cmake. Before Dongong change of removing the *_today* program in ConfigVmake.cmake, I had it patched to not using it. And I also jump the test for coasts nc version.

Perhaps the best is to drop the Valgrind test..

**Comment by PaulWessel** [comment]
I do want to see valid valgrind test. However, an alternative is to write a script to sift through all the bogus warnings from this section and keep everything else (if anything).  Since the code is not in error perhaps that is a better solution.

**Comment by joa-quim** [comment]
Are we still *Valgrining* or can we close this?
