### ISSUE TITLE
Move Matlab wrapper documentations to https://github.com/GenericMappingTools/gmtmex

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#870]

**Comment by seisman** [comment]
@PaulWessel @joa-quim Can any of you take some time migrating the file matlab_wrapper.rst to the gmtmex wiki page?

**Comment by PaulWessel** [comment]
Hi @joa-quim, could you help? I have to do Chair work for a while now after the paper and proposal both have been submitted.

**Comment by joa-quim** [comment]
I just changed the link at the top of the readme page. We can leave the ``matlab_wrapper.rst`` file trailing around but no included in case we later want to recover some bits of it.

**Comment by meghanrjones** [comment]
Could we just move this ReST file to the [GMT sandbox repo](https://github.com/GenericMappingTools/sandbox) so that we can close this issue?

**Comment by PaulWessel** [comment]
Yes, that would be OK with me so we have a saved copy of it.
