### ISSUE TITLE
GMT_DOC_URL: link to latest or specific version

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#871]
**Description of the desired feature**

GMT_DOC_URL is used by `gmt docs` to open HTML documentations. Currently it's set to http://docs.generic-mapping-tools.org/latest.

Before making public releases, we need to determine where GMT_DOC_URL links to.

1. always links to `latest`.
2. links to the version of the current release (i.e. http://docs.generic-mapping-tools.org/6.0.0 when releasing 6.0.0)

I prefer the second option, so that users always read the documentations matching the GMT version they're using.

**Comment by PaulWessel** [comment]
Hard to argue with that, I agree on option 2 as well.

**Comment by joa-quim** [comment]
Many projects in Github have two badges pointing to documentation. One with the latest official version and the other one with 'latest'. That's what we have also at the Hawaii GMT site (less the badges).

**Comment by PaulWessel** [comment]
But we cannot have two defaults in GMT.  This is where

gmt docs gravies

will take you.

**Comment by joa-quim** [comment]
If you look a https://github.com/GenericMappingTools/GMT.jl/tree/gh-pages you'll find the docs of previous versions. But that was generated by the registration script so I don't know how to do that. What we have in the ``gh-pages`` branch it's only ``dev``. If we had a ``stable`` or a ``6.0.0``, than we could have the two badges.

**Comment by joa-quim** [comment]
Ops, it looks I missed the ``gmt docs`` part. Thought we were talking about the links on the Github page.

**Comment by seisman** [comment]
Closed by #1551.
