### ISSUE TITLE
Problems when clipping with pscoast

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#875]
I'm trying to do some clipping and got into some issues. The example on the ``pscoast`` man page is representable of my problem. The postscript file seems to be faulty. No error during generation, but when converting with ``psconvert``, I get a crash. Also get into problem when trying to open in GSview.

Example:

```
gmt pscoast -R-30/30/-40/40 -Jm0.1i -B5 -Gc -P -K > africa.ps
gmt grdimage -Jm0.1i @earth_relief_05m -O -K -R >> africa.ps
gmt pscoast -Q -O >> africa.ps

psconvert -Tf -A -Z africa.ps
```
Using 97bc493

**Comment by PaulWessel** [comment]
Funny, the command `gmt pscoast -Q -O` writes -R0/0/0/0 to the PS so of course it breaks.  Will have to see why.

**Comment by PaulWessel** [comment]
The docs says no **-J** is needed but pscoast begs to differ.  Your workaround for now is to add **-R -J**; I will see if I can get it to relax.

**Comment by abanbj** [comment]
Great, works.
