### ISSUE TITLE
Spatial as a means to determine inside/outside

### ISSUE THREAD

**Issue by macpurity** [GenericMappingTools/gmt#896]
Examples on the man pages didn't quite sufficiently cover this, so consider this a request for help, more than an "issue" with GMT.

I need to be able to test whether a point location is inside or outside a complicated set of polygons (1.4 million of them, global set of polygons of inland water, possessing "hole" polygons inside of main, exterior polygons). The polygons were dumped from a .shp file, using ogr2ogr. The resulting dump looks and maps just fine, including being able to fill areas properly (using psxy -G).

But here's the question, how does one send a specific coordinate (or a set of random coords) to the set of polygons using gmtspatial and have the routine report whether each point is inside or outside? I think it is performed through the -N option.

Say the coords are in a file, test_coords.xy, and the polygons are in iw_polys.gmt. Is this the correct syntax?

gmt gmtspatial test_coords.xy -Niw_polys.gmt+a+r

I'm a bit unclear about the syntax. Thanks for any suggestions!

**Comment by PaulWessel** [comment]
I would think gmt select is better for this.  Do you actually need to get back all the points with an in|out flag or do you just want to create subsets of all inside and all outside? That is what gmt select does.

**Comment by macpurity** [comment]
Thanks, Paul. Useful suggestion. I was hoping for flag output, but I might be able to use gmtselect -F option. 

Does the -F option in gmtselect distinguish between "# @P" and "# @H" sub-polygons (closed islands)? In simple testing I've done, I don't think it does. I need the ability to make that distinction.

Yes, a point might be inside the main boundary, but if it inside a "hole" boundary, the point still reports as being inside the main boundary; the hole has been ignored, from what I can tell.

**Comment by macpurity** [comment]
This has been my test case. A simple 8x8 square, with a small 2x1 rectangle inside of it.

> poly 1
# @P
1 1
9 1
9 9
1 9
1 1
> poly 2
# @H
4 4
6 4
6 5
4 5
4 4

A point at (2,2) should return as being "inside." Bit a point at (5,4.5) should not, becuase it is inside the "hole" polygon. Hope that I'm describing that properly!

**Comment by macpurity** [comment]
Attached is my test case. A simple 8x8 square, with a small 2x1 rectangle inside of it (a "hole").

A point at (2,2) should return as being "inside." But a point at (5,4.5) should not, because it is inside the "hole" polygon. Hope that I'm describing that properly!

**Comment by macpurity** [comment]
Hmmm. Can't seem to attach a small text file!?

**Comment by PaulWessel** [comment]
You should be able to, people do so all the time (?).

**Comment by macpurity** [comment]
Here's the test case (file: tpoly.txt), as described on 6/13. And here are my gmtselect commands:

~ > echo "0.5 0.5" | gmtselect -Ftpoly.txt
~ > echo "2 2" | gmtselect -Ftpoly.txt
2	2
~ > echo "5 4.5" | gmtselect -Ftpoly.txt
5	4.5

The first case is outside of the main polygon, and nothing is returned (as expected).

The second case is inside the main polygon but not in the "hole" (with # @H in the header, upper case H). Gmtselect reports the point as being inside (as expected).

The third case is inside the "hole," yet gmtselect still reports that it is inside. That's not expected since the "hole" represents an area of exclusion. So the gmtselect command with option -F is ignoring the presence of islands (or "holes") from, e.g., a shapefile dump.

Hope this helps to describe the nature of my question. Can GMT be permitted to discriminate between outer polygons and inner polygons resulting from a shapefile dump? My aim is to have GMT inform me whether a point is: (1) inside a lake, (2) outside a lake, or (3) outside a lake because it is on an island in the lake.

**Comment by macpurity** [comment]
Not seeing the text file I attached, so here is a listing:

> poly 1
# @P
1 1
9 1
9 9
1 9
1 1
> poly 2
# @H
4 4
6 4
6 5
4 5
4 4

**Comment by PaulWessel** [comment]
So made some progress on this.  First, regular ASCII data tables do not parse any # @h headers.  That is part of the GMT/OGR syntax only.  Otherwise, we look for **-Ph** in the segment header.  From the description of file formats in 13 GMT File Formats: " Finally, if a segment represents a closed polygon that is a hole inside another polygon you indicate this with **-Ph**. This setting will be read and processed if converting a file to the OGR format."
Now, changing your file to have a segment header like

`> The -Ph means we have a hole
`

 for the second polygon did not help since GMT did not actually check for that in non-OGR files.  I am fixing that now via PR # 971.

**Comment by PaulWessel** [comment]
Hi @macpurity, is this working for you now or should we keep this issue alive?

**Comment by PaulWessel** [comment]
I think this issue is ripe for closing since the initial case presented by @macpurity passes (and has passed for some time). Please reopen if there are related issues.
