### ISSUE TITLE
Rename GMT_SOURCE_CODE_CONTROL_VERSION_STRING

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#901]
**Description of the desired feature**

With svn, we can set GMT_SOURCE_CODE_CONTROL_VERSION_STRING to the revision number, and running gmt prints something like
```
	GMT - The Generic Mapping Tools, Version 5.2.1 (r12345) [64-bit] [8 cores]
```

After switching to git, GMT_SOURCE_CODE_CONTROL_VERSION_STRING doesn't make sense anymore.

If it's set to be a commit hash, then we'll see
```
GMT - The Generic Mapping Tools, Version 6.0.0 (abcdefg) [64-bit] [8 cores]
```
The commit hash is almost meaningless.

What about renaming GMT_SOURCE_CODE_CONTROL_VERSION_STRING to GMT_PUBLIC_RELEASE?

For developers or users who use the latest master branch codes, it's set to FALSE by default. We'll see
```
GMT - The Generic Mapping Tools, Version 6.0.0_abcdefg_2019.01.01 [64-bit] [8 cores]
```

When making a new release, just set to TRUE. Users will see
```
GMT - The Generic Mapping Tools, Version 6.0.0 [64-bit] [8 cores]
```

**Are you willing to help implement and maintain this feature?** Yes

**Comment by PaulWessel** [comment]
Yes, that makes more sense with git.  Please go ahead.
