### ISSUE TITLE
Windows installer doesn't show GMT copyright information

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#902]
![image](https://user-images.githubusercontent.com/3974108/59481842-02ec6080-8e34-11e9-9290-f951ac285a49.png)

**Comment by joa-quim** [comment]
Yes, I know this. But the solution is not to show the license (no other mean of downloading;installing GMT shows the License contents) but to remove this step from the installer. But I haven't found how to do that (did not insist either for a long time).

**Comment by seisman** [comment]
What's the reason not to show the GMT license?

**Comment by joa-quim** [comment]
We don't show the license when: download the tar balls, install via github, install with any package manager, install the MacOS bundle. Why would the windows installer be different?

And what I want is to remove all unnecessary steps of the installer and leave only the important ones: The installing directory name, the add to path and the selection of which components to install.

**Comment by seisman** [comment]
Got it. Sounds reasonable

**Comment by joa-quim** [comment]
Thanks for looking into this. I'll try latter today. Now I have to leave for a while.

**Comment by abanbj** [comment]
While were talking about the Windows installer; if I remember correctly, DCW is not installed (ticked off) pr. default. Maybe it should be?

**Comment by joa-quim** [comment]
Yes, you are right but the issue is fixed.

**Comment by seisman** [comment]
@joa-quim Any updates?
