### ISSUE TITLE
Question: Plotting continuous line with changing color

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#907]
Color coding symbols is easy with ``psxy``, but is it possible to draw a continuous line with changing color based on a z-value (in a ``x,y,z``-dataset)?

An approach that I've been using is just to do a dense plot with symbols, say ``-Sc0.1c -C..`` which gives an illusion of a continuous line-like thing.

As far as I know, one line segment can only be assigned one color.

**Comment by PaulWessel** [comment]
That is indeed the only way to do it.  I usually run my line via sample1d to get it densely sampled and then plot circles.  The PostScript language does not offer any other way.

**Comment by abanbj** [comment]
Great Paul, thanks.
