### ISSUE TITLE
Long TMPDIR causes troubles

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#910]
I'm using macOS 10.14.5. On my mac, TMPDIR is defined as:
```
$ echo $TMPDIR
/var/folders/mz/d3wtwjtx4fg8qlds5lgt1c240000gn/T/
```
I never define TMPDIR myself, so I believe this is the default value set by macOS. The long TMPDIR will cause some segmental faults.

Below is an example:

In `gmtlib_get_region_from_data`, the variable `tmpfile` is only 64-bytes.

https://github.com/GenericMappingTools/gmt/blob/127bb214ce9012334c17ec915fe84804a61ade12/src/gmt_init.c#L11777

Then the `strcat` function aborts with a segment fault, because the temporary file path needs 70 bytes.
https://github.com/GenericMappingTools/gmt/blob/127bb214ce9012334c17ec915fe84804a61ade12/src/gmt_init.c#L11811

To reproduce the issue:
```
export TMPDIR /a/very/long/path/to/somewhere
gmt begin plot-test
gmt plot -JX10c -Baf << EOF
0 0
5 5
EOF
gmt end
```

Changing GMT_LEN64 to GMT_LEN128 can fix the issue in gmtlib_get_region_from_data. Other functions may have the same issue.

**Comment by PaulWessel** [comment]
All strings intended for filenames **must** use PATH_MAX as defined by the OS.  Will see if there are any others.
