### ISSUE TITLE
Reorganize the structure of GMT FTP

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#916]
I think it's time to rearrange the files on GMT FTP.

Some suggestions:

- Remove junk file `c.txt`
- Remove `contrib`. I remember it's already included in the documentations.
- Update README.GMT and VERSION

For tarballs, I've heard many users complain that they can't find win/mac installers or source codes of some old releases. I think we should design a better FTP structure, and also don't move old tarballs to a new location when making a new release, which usually make package maintainers unhappy.

**Comment by PaulWessel** [comment]
I've deleted c.txt and contrib.  There is also the hidden .message file used by ftp.

**Comment by seisman** [comment]
@PaulWessel I remember you mentioned that you're going to setup a new FTP on the gmt-server. Any updates?

**Comment by PaulWessel** [comment]
Thanks for the reminder.  I did look into this and it is not possible to set up a forward to ftp.generic-mappping-tools.org, at least not via hover (our dns forwarding service).  So not sure what we should do.

**Comment by seisman** [comment]
I thought it's possible allow the **gmt-server** accept FTP requests.

**Comment by PaulWessel** [comment]
Yes, that should be possible, but it would be something like ftp.gmtserver.soest.hawaii.edu.
