### ISSUE TITLE
Index page with supplements is not sorted

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#923]
After the split of meca into geodesy and seis there are some issues with the presentation:

Modern mode layout:
1. GEODESY should come alphabetically before IMG
2. SEIS could go on top of column 3 after GEODESY is moved.

This won't achieve perfect alphabetical lineup but avoids breaking up the two long ones.

**Comment by seisman** [comment]
Assigned to @seisman
