### ISSUE TITLE
Remove 25.1 Running GMT in isolation mode in modern mode docs

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#925]
Since a gmt modern mode session is basically its own isolation mode, it makes no sense to discuss the isolation mode for gmt classic here.  Yet, we have two GMT_Docs files, one for classic, that we currently are not building from, and the index page only shows the modern mode cookbook.  Shouldn' we add GMT_Docs_classic to the building?

**Comment by joa-quim** [comment]
Yes, I think we should. But we need to link it too from the main docs page.

**Comment by seisman** [comment]
Can you have two index files, index for modern mode and index-classic for classic?

**Comment by PaulWessel** [comment]
No, but we could add another side-bar item called Cookbook (classic) for now and add the classic bookbook beneath the modern mode one.  But now I cannot find GMT_Docs_classic.rst.
