### ISSUE TITLE
Raise a warning instead a error when requesting a PS file in modern mode

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#94]
**Full script that generated the error**

```
gmt begin map ps
gmt basemap -R0/10/0/10 -JX5c -Bafg
gmt end
```

**Full error message**

```
psbasemap [ERROR]: Must specify a paper size when requesting a PostScript file
psbasemap [ERROR]: Changing paper size to A4, but we cannot know if this is adequate for your plot.
```
The script can generate the desired plot correctly. So I think it would be better to raise warnings instead of errors and tell users to change `PS_MEDIA` if A4 paper size isn't adequate for their plot.

**Comment by PaulWessel** [comment]
OK, I can relax the level to warning (requiring -V).  We were concerned that this message would not be seen and some user may complain that they got the wrong size.  We could add some more wording to the documentation for modern mode to prevent confusion.  Would this be OK?

**Comment by seisman** [comment]
Didn't realize that warnings wouldn't be seen if -V is not used. Adding more wording to clarify this possible confusion is necessary.
