### ISSUE TITLE
How to make the x annotation rotate to some angle

### ISSUE THREAD

**Issue by alex0516** [GenericMappingTools/gmt#951]
**Description of the problem**
Hi there,

It seems impossible for GMT to make the x annotation rotated to some set angle. Am I wrong or I have not found this kind of function? Till now, I just found MAP_ANNOT_ORTHO, which only makes the x annotation orthogonal. But how to make the annotation rotating to random angle?

Cheers,
Alex

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Version of GMT:

**Comment by joa-quim** [comment]
Yes, [there is ](http://docs.generic-mapping-tools.org/dev/GMT_Docs_classic.html#axis-slanted-basemap) but it's GMT6 only feature.

**Comment by alex0516** [comment]
Thanks. I tried that in GMT6 and it didnt work. Could you specify which version of GMT could be fine?

**Comment by joa-quim** [comment]
*What* did not work? The example in the link I showed for sure works. It works in **GMT6** (GMT6 developing version for the moment but very soon the official version)
