### ISSUE TITLE
Replace bc with bash built-in syntax

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#964]
Sometimes we use `bc` in bash scripts to perform numerical calculations. It causes some troubles on Windows (e.g. azure pipeline CI), in which `bc` may be not available.

For integer calculations, we can use `$((x + y))` instead.

**Comment by PaulWessel** [comment]
I think they are floating point calculations.  We can just do gmt math -Q for that stuff, as I do pretty much everywhere else (Remko liked bc).

**Comment by PaulWessel** [comment]
I have updated the few scripts to use bash arithmetic for integers and gmt math **-Q** for floats.  See PR #965.

**Comment by seisman** [comment]
Fixed by #965.

**Comment by PaulWessel** [comment]
Why is this being labeled stale when we closed it in June?

**Comment by seisman** [comment]
No idea. Something wrong with the bot.
