### ISSUE TITLE
Question(/feature request?): Use auto CPT in psscale

### ISSUE THREAD

**Issue by abanbj** [GenericMappingTools/gmt#966]
When issuing a ``grdimage`` plot without a ``-C``, you get a (nice and very convenient) auto generated one. Is this CPT possible to reach with ``psscale`` for plotting of the color scale bar?

```
grdimage -I -JX20c data.nc -P > test.ps
psscale -C[where??] ..... >> test.ps
```

**Comment by abanbj** [comment]
And similar if you want to use the auto generated CPT in ``grdcontour -C[where??]``.

**Comment by joa-quim** [comment]
Yes, but only in modern mode. The reason is simple. The cpt must be saved (it was tailored after the grid's min/max) so that psscale (colorbar) can find it. And this is exactly what happens under the hood in the modern mode.

**Comment by abanbj** [comment]
Got it. Thanks Joaquim.
