### ISSUE TITLE
The -a option is poorly typeset in the rst docs

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#972]
I think I tried to add bold font to the -a link but this filed.  COuld those of you who know more about RST (@joa-quim, @seisman, @leouieda) try to fix this.  This is what it looks like:

![a](https://user-images.githubusercontent.com/26473567/59630091-318e6380-90e0-11e9-844c-06fa9e015260.png)

**Comment by joa-quim** [comment]
I don't think you can boldify a reference ``:ref:`\ **-a** option <-aspatial_full>``` (Here the Markdown does it)

**Comment by leouieda** [comment]
You can boldify a reference but not only a part of a reference.

**Comment by seisman** [comment]
Closed by #981.
