### ISSUE TITLE
Forum account request

### ISSUE THREAD

**Issue by evavra** [GenericMappingTools/gmt#986]
Hello! I am hoping someone can create a GMT forum account for me. Please find my info below. 

Desired username: vavra or evavra
Contact email: ellisvavra@berkeley.edu
Full name: Ellis Vavra

Thanks!

**Comment by PaulWessel** [comment]
Sine the old wiki and forum is going to be replaced, could you not ask your question or issue here instead?

**Comment by evavra** [comment]
I was hoping to post on the GMTSAR forum, and after a bit of digging just now I can't seem to find an official repository on Github for GMTSAR. Will the GMTSAR wiki/forum be replaced along with that of GMT?

As for my query: I am having issues downloading Sentinel-1 orbit files for a given list of SAFE folders using default GMTSAR scripts (organize_files_tops.csh). It is unable to establish an SSL connection and I was hoping someone may have some insight as to why it's not working.

Any info is appreciated!

**Comment by PaulWessel** [comment]
Sorry, missed the GMTSAR part.  I've created the evavra account - will email you the password.
