### ISSUE TITLE
psvelo can't get error ellipse

### ISSUE THREAD

**Issue by Soengmou** [GenericMappingTools/gmt#992]
I just install the GMT in the Ubuntu 18 online to plot a GPS rate field with the command below I used in under the CentOS. But don't get the error ellipse.
”echo 80 30 10 0 2 2 0 10mm/a| gmt psvelo  -h0 -R -W0.8,black   -Gblack   -J -L  -Se0.04c/5/10 -A0.19c+p0.7p+e  -O -K -V >>$psn”

**Comment by Soengmou** [comment]
I just copy one line of my script.

**Comment by seisman** [comment]
I don't know the exact meanings of the arguments, but it seems the second argument of -Se is *confidence*, which should be in the range of 0-1. Please see the [psvelo manual](http://docs.generic-mapping-tools.org/latest/supplements/geodesy/psvelo.html) for detailed description.

Changing `-Se0.04c/5/10` to `-Se0.04c/0.5/10`, and you'll see an ellipse. Maybe that's what you want.

**Comment by Soengmou** [comment]
Sorry for the argument. But you got my meaning. 
I changed the confidence to 0.5. It doesn't work. 
My GMT version is 5.4.3.

**Comment by seisman** [comment]
I tried the following command with GMT 5.4.5:
```
echo 80 30 10 0 2 2 0 10mm/a| gmt psvelo -h0 -Rg -W0.8,black -Gblack -JH10c -L -Se0.04c/0.8/10 -A0.19c+p0.7p+e -N -V -Baf > map2.ps
```
This is what I got:
![image](https://user-images.githubusercontent.com/3974108/59893225-3f770980-93aa-11e9-95ed-b725ae9f976b.png)

**Comment by Soengmou** [comment]
Thank you. 
The error ellipse was displayed when I added the **_-B_** .

**Comment by seisman** [comment]
That's weird. -B isn't required here. This is what I got without **-B**.
![image](https://user-images.githubusercontent.com/3974108/59894030-1c9a2480-93ad-11e9-8248-c5583bb539e3.png)

**Comment by PaulWessel** [comment]
Does your script properly end the postscript or is there a final -K hanging?

**Comment by Soengmou** [comment]
There's no -K hanging in the last line.

**Comment by Soengmou** [comment]
> That's weird. -B isn't required here. This is what I got without **-B**.
> ![image](https://user-images.githubusercontent.com/3974108/59894030-1c9a2480-93ad-11e9-8248-c5583bb539e3.png)

Yeah, very wired.

**Comment by PaulWessel** [comment]
Since it seems to work fine in 5.4.5 there isn’t anything we can do as long
as Ubuntu is so far behind on releases. You would need to build from source.

Paul Wessel, Professor and Chair
Dept. of Earth Sciences (formerly Geology & Geophysics)
SOEST, U of Hawaii at Manoa
