### ISSUE TITLE
gmt2kml appears to fail when using trailing record text as label

### ISSUE THREAD

**Issue by MarceloBanik** [GenericMappingTools/gmt#997]
**Description of the problem**
When using gmt2kml in gmt6, I couldn’t use trailing record text as label.

Using gmt 5.4.5, I get what I expected, showed below,
but with gmt 6, I didn’t get the expected label, but a generic “Point 0”.

I tried using -Ncol, but appears it didn’t work too.

I hope I understood properly the usage for option -N:
1. Specify -Ncol to use a column from the data record a single-word label (-Fe|s|t only).
2. Specify -Nt if the trailing record text should be used as label (-Fe|s|t only).

**Full script that generated the error**

```
gmtswitch 5.4.5
echo "-45 -30 1000 sjsp" | gmt 2kml -Ag -Fs -N+ | grep name
                        <name>stdin</name>
                                <name>Point Set 0</name>
                                        <name>sjsp</name>
gmtswitch 6.0.0
echo "-45 -30 1000 sjsp" | gmt 2kml -Ag -Fs -Nt | grep name
                        <name>stdin</name>
                                <name>Point Set 0</name>
                                        <name>Point 0</name>

```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:Ubuntu 18.04.2 LTS
* Version of GMT: 6.0.0_279da86_2019.06.23

**Comment by PaulWessel** [comment]
Unfortunately, a minor mistake in the parsing meant that **-Nt** (or **-N+**) was never parsed properly.  The PR #998 fixes the issue.
