### ISSUE TITLE
GhostScript trouble with -dUseFastColor=true

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#999]
When we convert PostScript of a square filled with a black/white hachure pattern to a raster format (e.g., PNG) and the -dUseFastColor=true is set (which is psconvert default), we get colored (red or green) vertical streaks ruining the image.  They are not present if dUseFastColor=false.  The problem does not affect the PDF driver (and the PostScript views fine as well) - it is only when rasterizing the plot.  This would seem to be another ghostscript bug, no?  A minimal PostScript (zipped) file is attached, as are the outputs of the two raw gs commands (gs 9.26):

1. gs -q -dNOPAUSE -dBATCH -dUseFastColor=true -sDEVICE=png16m  -g266x266 -r150 -sOutputFile='imagebugUseFastColor.png' -fimagebug.ps
![imagebugUseFastColor](https://user-images.githubusercontent.com/26473567/60062938-fa0b5280-96af-11e9-8582-5b89ee093506.png)

2. gs -q -dNOPAUSE -dBATCH -sDEVICE=png16m  -g266x266 -r150 -sOutputFile='imagebug.png' -fimagebug.ps
![imagebug](https://user-images.githubusercontent.com/26473567/60062965-10191300-96b0-11e9-9283-84b2cbcf9889.png)
[imagebug.ps.zip](https://github.com/GenericMappingTools/gmt/files/3323190/imagebug.ps.zip)

**Comment by PaulWessel** [comment]
I know you are busy @remkos but wonder if you have an opinion of whether or not this is a bug or a feature of using fast color...

**Comment by PaulWessel** [comment]
I have posted a gs bugreport with bugzilla: https://bugs.ghostscript.com/show_bug.cgi?id=701296

**Comment by PaulWessel** [comment]
Bug has been fixed in gs repo so probably 9.28 will avoid this problem.

**Comment by PaulWessel** [comment]
We will close this issue when gs 9.28 is released.

**Comment by seisman** [comment]
gs 9.50 was released and the bug was fixed. Closing this issue.
